### ISSUE TITLE
Allow log configuration in conf file

### ISSUE THREAD

**Issue by Fale** [swaywm/sway#1000]
I think it would be nice to be able to set the log path in the config file as is possible to enable logs.

**Comment by SirCmpwn** [comment]
How would we log anything that happens before the config file is read (a lot of things happen before the config file is read)

**Comment by ametisf** [comment]
IMO just adding `alias sway="sway > /var/log/sway.log 2>&1"` to your .bashrc is better than adding a feature to sway.

**Comment by Fale** [comment]
@SirCmpwn not really sure about that

@ametisf as a user yes, as a packager, I can not do it, so I guess the majority of people (everyone who did not put the alias manually) will have no logs and therefore bugs will be far less helpful.

**Comment by ametisf** [comment]
I found #43. The file could be set on compile time.

**Comment by hobarrera** [comment]
An alias *might* work, but a wrapper script seems to produced unexpected results (see #1097).

**Comment by SirCmpwn** [comment]
No.
