### ISSUE TITLE
swaylock allow popup to come through

### ISSUE THREAD

**Issue by benallard** [swaywm/sway#1056]
VirtualBox likes to remember the user when a new version is available. Their popup come through swaylock, and pressing enter while the screen is locked does dismiss the popup. Afterward, it is not possible to login anymore.

**Comment by Kunagi7** [comment]
A similar thing happens when I use stalonetray:
```stalonetray --window-type utility -bg "#073642" --geometry 4x1+60+1 -i 18```
Because I need a system tray on sway since programs like telegram desktop, vlc or aimp [wine] use it.
When I lock the screen the tray usually appears on top of swaylock and things like the number of messages from telegram can be seen on real time. Thankfully, it doesn't break unlocking.

**Comment by minus7** [comment]
I've noticed that popups show ontop of swaylock too. In particular Thunderbird/Lightning reminders. Probably new-email-notifications too; I haven't seen it directly, but I noticed that after a while I couldn't log in anymore (no reaction to keyboard input).

**Comment by CedricCabessa** [comment]
I confirm the bug, and I can not login anymore when a popup is shown on top of swaylock.
It is easy to reproduce with a few line of python (pyqt) creating a modal window:

```
#!/usr/bin/env python3
import sys
from PyQt5 import QtCore, QtWidgets

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    win = QtWidgets.QMainWindow()
    dialog = QtWidgets.QDialog(win)
    dialog.setModal(True)
    dialog.exec_()
```

Then, in a terminal:
`swaylock &  (sleep 5; ./modal.py)`

I've a simple patch here https://github.com/CedricCabessa/sway/commit/d6cc6600d0e69d7ca84064e4ea94e89055a83a42
It is not complete as the modal window still pass through swaylock, but at least the window do not steal the focus and I can type my password.
I didn't PR it as it is not complete and I'm not confortable with the meaning of the other `type` like `WLC_BIT_OVERRIDE_REDIRECT`

(my patch target 0.15)

**Comment by SirCmpwn** [comment]
That seems like a good fix to me. Feel free to send it along.

**Comment by SirCmpwn** [comment]
This will be addressed when [wlroots](https://github.com/swaywm/wlroots) is completed and [integrated with sway](https://github.com/swaywm/sway/issues/1390).
