### ISSUE TITLE
Dialogs on Some GUI Toolkits Not Centered

### ISSUE THREAD

**Issue by yanalex981** [swaywm/sway#1057]
GTK dialogs doesn't seem to be centered when opened. I experienced this with Sublime Text 3's file dialog, and Thunar's preferences dialog. Haven't noticed any odd behaviors on other GUI toolkits.

**Comment by MrSorcus** [comment]
Not only GTK apps. Qt apps has this problem too.

**Comment by SirCmpwn** [comment]
I'm closing issues that are resolved by the yet-unreleased sway 1.0.
