### ISSUE TITLE
Closing QTerminal crashes sway

### ISSUE THREAD

**Issue by K-Alchemist** [swaywm/sway#1060]
Environment:
WLC_XWAYLAND=0
QT_QPA_PLATFORM=wayland-egl

Version: 
sway version 0.11 (2017-01-20, branch "HEAD")
qterminal 0.7.1

Steps:
1. Enter wayland with those variables
2. Open QTerminal
3. Close it with the kill command. (Closing from its menu does not work and it gets stuck in the poll() function from glibc)
4. Sway session crashes instantly

Full backtrace:
http://pastebin.com/V3q85Agq

QTerminal backtrace when closing it from itself (not very sure if related):
http://pastebin.com/E2qtHbVv

This might be related to #1036 

EDIT:
This is the backtrace as of the latest commit:
http://pastebin.com/8TDGMtFt

**Comment by Fale** [comment]
could this be related? https://github.com/SirCmpwn/sway/issues/975

**Comment by SirCmpwn** [comment]
I'm closing issues that are resolved by the yet-unreleased sway 1.0.gg
