### ISSUE TITLE
Missing focus for context menus

### ISSUE THREAD

**Issue by kleinreact** [swaywm/sway#1062]
With the `xdg_positioner` update context menus are positioned properly for me now. However they are not focused by default. This means I cannot click items until I selected the first one using the arrow keys.

**Comment by WeaponX1** [comment]
I can confirm this exact problem especially in Chrome Tabs, they tend to become unresponsive unless I use keyboard navigation.

**Comment by bearcatsandor** [comment]
It may be related, but i find that dropdowns do this as well. I see the dropdown as a flash, it dissapears and then i have to use my keyboard to cycle through the items.

**Comment by lewishsh** [comment]
Have any of you managed to figure this out? I'm having this issue as well, but only with context menus in certain apps like those from the Libre Office suite. Firefox, thunderbird and evince on the other hand have fully working menus.

Not sure if this is related, but the text in menus that aren't working is also pretty blurry.

**Comment by gnidorah** [comment]
For me it happens only with Wayland native programs, XWayland programs work coreectly

**Comment by SirCmpwn** [comment]
This will be addressed when [wlroots](https://github.com/swaywm/wlroots) is completed and [integrated with sway](https://github.com/swaywm/sway/issues/1390).
