### ISSUE TITLE
Mouse pointer disappear

### ISSUE THREAD

**Issue by airstep** [swaywm/sway#1127]
I found issue with mouse pointer - that disappear when using with Visual Studio Code as an example. When I move from opened file place to folder tree it often hide mouse pointer... And I need to switch to other workspace and move mouse to make it visible again.

Mouse theme is: Pulse-Glass

[config.txt](https://github.com/SirCmpwn/sway/files/853156/config.txt)
My configuration file in atach...

**Comment by 101stArrow** [comment]
Likewise, can post my config if needed but doubt the issue arises because of it.

What versions of wlc and sway you running? Not at my computer right now will post mine later

**Comment by airstep** [comment]
My wlc version is:  0.0.8-1

But I compiled it from ABS tree (ArchLinux) and make just one change in PKGBULD - replace 'Release' to 'Upstream' to prevent random menu hide (you can see in attach).

[PKGBUILD.txt](https://github.com/SirCmpwn/sway/files/853161/PKGBUILD.txt)

**Comment by tjaartvdwalt** [comment]
I have also noticed this. 
It seems a bit sporadic, but it often happens in Google Chrome when I have Dev tools open, and try to inspect elements on the page.

**Comment by airstep** [comment]
Log in attach with possible places where mouse can
[logs.txt](https://github.com/SirCmpwn/sway/files/882284/logs.txt)
 disappear

**Comment by marcv81** [comment]
Reproduced in VSCode, sway 0.13.0, default config.

**Comment by NicholasAsimov** [comment]
Easily reproducible in git-gui 0.21 with Tk version 8.6.7. I will provide a screencast and logs later.

**Comment by SirCmpwn** [comment]
Don't bother. We've already confirmed that this isn't a problem with wlroots.

**Comment by danielcb** [comment]
Meaning you know what the problem is or you determined it's not a problem of sway/wlroots/etc? I'm just asking, because I'm seeing this in a view apps (vs code, firefox, chrome, teamviewer).

**Comment by SirCmpwn** [comment]
This will be addressed when [wlroots](https://github.com/swaywm/wlroots) is completed and [integrated with sway](https://github.com/swaywm/sway/issues/1390).

**Comment by danielcb** [comment]
Thanks!
