### ISSUE TITLE
Mouse pointer disappears in Firefox

### ISSUE THREAD

**Issue by kasicka** [swaywm/sway#1132]
When hovering over maps in Firefox, the mouse pointer disappears. This doesn't occur in Chromium or in weston.
I'm running sway from 0.12.1-1.fc27 from Fedora Rawhide, wlc 0.0.8-1.fc26.
Maybe related to https://github.com/SirCmpwn/sway/issues/1127

**Comment by airstep** [comment]
It also desappear in QtCreator studio (...

**Comment by ykrivopalov** [comment]
The same for wpa_gui and wireshark (qt) when you open menu. Looks like it reproduces for all qt5 applications

**Comment by bearcatsandor** [comment]
The pointer does come back if i move it outside the boundries of the app in question, but it takes ~5 seconds of travel.

**Comment by SirCmpwn** [comment]
Do other compositors have the same problem? Other wlc-based compositors?

**Comment by ykrivopalov** [comment]
I've checked weston (is weston wlc based?) and it doesn't have this problem

**Comment by airstep** [comment]
Why mouse even hide itself? In what kind of source or logic? I'm switching back to openbox - very annoying issue (also in other applications like qt creator, etc..)

**Comment by SirCmpwn** [comment]
Investigate it. Complaining isn't going to help.

**Comment by bearcatsandor** [comment]
Didn't you know? Open Source means that we have full access to the code so that others can fix it for us when we complain!

**Comment by airstep** [comment]
Really? I'm Investigate it... But I just wanna know direct points by creator or any open minds about this serious issue.

**Comment by woutermont** [comment]
Happens to me with gmail and some flash games in chromium. Something to do with flash?

**Comment by onny** [comment]
No I don't think so. I also have this in some native html5 webapps (like OnlyOffice web editors etc.)
