### ISSUE TITLE
Some kind of corrupted window - in java autocomplete

### ISSUE THREAD

**Issue by airstep** [swaywm/sway#1134]
Like in attach, time by time (not always - but often)

![2017_03_23_10 12 50](https://cloud.githubusercontent.com/assets/5022948/24238065/9bbd2b2c-0fb1-11e7-9a38-b9f69d3b7ad8.png)

**Comment by SirCmpwn** [comment]
I'm closing issues that are resolved by the yet-unreleased sway 1.0.
