### ISSUE TITLE
wrong position on swaybar when scale=2

### ISSUE THREAD

**Issue by motherload** [swaywm/sway#1137]
When scale=2 is enabled in the config file, the swaybar aesthetically scales correctly, everything looks fine.

But if you try to click the compartments to select some workspace, it becomes clear that the they do not coincide. Can't say by how much, but the click compartment is more than 50% wider than what you see on the screen. If you have more than 2 or 3 active workspaces, it becomes nearly impossible to select them accurately with the mouse click.

**Comment by ascent12** [comment]
I've noticed that this is still an issue, even for unscaled outputs. With scale=1, when you have 10 workspaces open, clicking on the right half of '9' will select '10'.
I suspect that the 1px border between buttons is not being accounted for when working out which button has been clicked.

**Comment by SirCmpwn** [comment]
Good catch.
