### ISSUE TITLE
Menus and dropdowns render (partly) off screen

### ISSUE THREAD

**Issue by woutermont** [swaywm/sway#1142]
It seems that (dropdown) menus has no sense of the application's window size. I notice this on multiple occasions in different applications. Some examples: 

- In chromium, a folder on the bookmarks bar containing too many bookmarks fails to show the "scroll down" indicator but simply unfolds past the bottom of the screen.

- Also in chromium, submenus of the main menu are rendered off the right edge of the screen.

- In other applications (thunar, texstudio ...), when tiled horizontally (and small enough) the rightmost menus also render off the right edge of the screen.

**Comment by AnotherBugworm** [comment]
It happens to me too, only with native wayland qt apps, don't sure about gtk. I'm forced to use xwayland because of this

**Comment by SirCmpwn** [comment]
Debug it and send a patch.

**Comment by AnotherBugworm** [comment]
https://gist.github.com/AnotherBugworm/c838d9a8a39828cbfc4422603c4d576d
version and config from here
https://gist.github.com/AnotherBugworm/5a023e0e3614450f360da41d42d8c16e

**Comment by woutermont** [comment]
Why was this issue closed? It is still present, affecting every application (as far as I know). Anything I can do to debug this?

**Comment by SirCmpwn** [comment]
It wasn't closed...

**Comment by benjiprod** [comment]
https://github.com/SirCmpwn/sway/issues/1228 was closed because of duplicate issue.

**Comment by woutermont** [comment]
Oh, right, my bad ... Still, same question: can we solve this extremely annoying issue?

**Comment by InfernoZeus** [comment]
@SirCmpwn Any ideas where I might start looking at debugging this? Is it likely to be something that will have to wait for the move to wlroots before being fixed?

**Comment by SirCmpwn** [comment]
Yeah, addressing this is in scope for wlroots.

**Comment by SirCmpwn** [comment]
I'm closing issues that are resolved by the yet-unreleased sway 1.0.
