### ISSUE TITLE
When switching workspaces, the workspace::focus event gets emitted twice

### ISSUE THREAD

**Issue by ianyfan** [swaywm/sway#1189]
I believe the issue is on these two lines:
https://github.com/SirCmpwn/sway/blob/master/sway/focus.c#L39
https://github.com/SirCmpwn/sway/blob/master/sway/focus.c#L185

When "switching" to the same workspace (as the current one), only the second event gets emitted. So I don't know if the first one is just extraneous, or whether it is still required.

**Comment by SirCmpwn** [comment]
Since you've narrowed down the problem, how about testing a fix and sending a patch?

**Comment by ianyfan** [comment]
Okay, I'll take a look.

**Comment by ianyfan** [comment]
It appears that the first case (L39) was added in order to fix #382. Removing that line now seems to work (and sending a workspace::focus event when moving a container to another workspace doesn't really make sense to me anyway since it's never technically visible), except that swaybar isn't updated correctly if it changes at the exact same time, so I don't know whether this can be fixed separately, or whether to change it so that the event is only emitted once in every situation, or just to keep it as it is for now.

If this is due to some problem in swaybar, I think it would be nice to fix it, since I've also been getting a problem that seems to be related, in which swaybar doesn't update correctly if you change the output at the same time as switching to a new (empty) workspace (i.e. in response to the workspace::focus event), but I'd have to look a bit more into how swaybar works in order to see if that's fixable.

**Comment by SirCmpwn** [comment]
It should probably be changed to emit the event just once, then, if you can sort it out.
