### ISSUE TITLE
Odd breakage when moving around windows

### ISSUE THREAD

**Issue by WhyNotHugo** [swaywm/sway#1191]
I've consistently been able to reproduce this, and the issue is pretty hard to explain:

1. Switch to an empty workspace
1. Open three windows.
1. super+w
1. Go to the leftmost window
1. super+v
1. Go to the middle window
1. super+shift+left

The titlebar will be completely screwed up: it'll be split in two, with the titles of the two windows now grouped sometimes overlap, and switching between them is glitchy. Finally, the order in which they're shown is wrong.

![2017-04-25-205210_swaygrab](https://cloud.githubusercontent.com/assets/730811/25412501/69a36d74-29f9-11e7-95f8-1e12159e9000.png)

![2017-04-25-205214_swaygrab](https://cloud.githubusercontent.com/assets/730811/25412513/75984794-29f9-11e7-9be9-f565457b721c.png)

**Comment by SirCmpwn** [comment]
I'm closing issues that are resolved by the yet-unreleased sway 1.0.

**Comment by WhyNotHugo** [comment]
Thanks!
