### ISSUE TITLE
Title-clicking doesn't work for nested windows

### ISSUE THREAD

**Issue by Atamisk** [swaywm/sway#1202]
If a nested layout of the type: 
Container 0 (workspace, tabbed or stacked layout)
    Window 1
    Container 2 (Tiled layout)
        Window 2
        Window 3

Is placed on a workspace, clicking on the title bar for container 2 does not work. However, if he screen area where Window 2 or Window 3's title bar "would be" if that container were active, that window is made active. This can conflict with providing mouse input to Window 1, as mouse input for that window can be mistakenly be interpreted as selecting Window 2 or 3 instead of the intended interaction with Window 1

**Comment by hobarrera** [comment]
For me, when simply having two tabbed windows, clicking on the title of the inactive one does nothing (whereas it changes to that window on i3).

**Comment by SirCmpwn** [comment]
I'm closing issues that are resolved by the yet-unreleased sway 1.0.
