### ISSUE TITLE
Sway on Void

### ISSUE THREAD

**Issue by julio641742** [swaywm/sway#1260]
OS: Void Linux glibc version
wlc: 0.0.9
sway: 0.13.0

I open sway via command `sway` and when I close sway this output shows up

`
7 00:15:35 - [main.c:47] [wlc] Failed to activate vt4 for restoration
`
`
7 00:15:35 - [main.c:47] [wlc] Failed to switch back to vt1
`
Can anyone help me?

**Comment by concatime** [comment]
Same on NixOS.

**Comment by concatime** [comment]
For all people on NixOS wondering, sway should be running [this way](//github.com/concatime/dotfiles/pull/1).
