### ISSUE TITLE
Variable prefix of another variable

### ISSUE THREAD

**Issue by emersion** [swaywm/sway#1287]
I have this config file:

```
set bg #323232
set bgu #000000
background $bgu
```

It expands to:

```
background #323232u
```

Which leads to this error:

```
[config.c:716] Error on line 189 'background $bgu': Invalid color definition #000000u (/home/simon/.config/sway/config)
```

I'm pretty sure this config file used to work before.

Note that i3 had this bug too, but it's now fixed: https://github.com/i3/i3/issues/2235

**Comment by RedSoxFan** [comment]
This appears to be working in both `0.15` and `master`.
