### ISSUE TITLE
Scratchpad issues when using window properties criteria for key bindings

### ISSUE THREAD

**Issue by mariusor** [swaywm/sway#1291]
Hi,

I'm trying to use the scratchpad with [sway](https://github.com/mariusor/dotfiles/blob/master/.config/sway/conf.d/judas.config#L40) and I'm having some troubles.

Toggling a window to be shown or not works with the default binding for show scratchpad, but when using the class criteria bindings it doesn't show them. 

However if a window is visible the keybinding for it works to hide it, so I suspect that sway loses access to the window's properties when it is not shown.

Let me know if there's something else I should add.

**Comment by SirCmpwn** [comment]
Can I see more detail? What's your config file look like?

**Comment by mariusor** [comment]
See the link in my original post, it was the configuration used.

**Comment by SirCmpwn** [comment]
This should work but note that because of the way the scratchpad works in sway, it'll probably be *super* buggy with any command other than scratchpad show.

**Comment by mariusor** [comment]
Thanx for the quick fix.

It works to show the window in the scratch workspace, but it doesn't work to hide it again. I'm not sure if it's the same issue, or not.

    bindsym $mod+Shift+p [class="Pidgin" instance="Pidgin" title="Buddy List"] scratchpad show
    bindsym $mod+p [class="Pidgin" instance="Pidgin" title="[^(Buddy List)]"] scratchpad show

Actually the behaviour is somewhat stranger than that: see my two bindings above. With the current build, `$mod+p` shows conversation, but it gets hidden at `$mod+shift+p`. The Pidgin's buddy list keybinding with `$mod+shift+p` works to show it (if conversation is hidden) but not to hide it, and then, to hide it I have to use `$mod+p`.  

Thank you again.

**Comment by mariusor** [comment]
@SirCmpwn could you please point me in the right direction for verifying why the key bindings work like that? Maybe I can crop up a fix.

**Comment by SirCmpwn** [comment]
Sorry, I need to rewrite the whole scratchpad system to be less complex. It's not ideal "first contribution" work.

**Comment by mariusor** [comment]
OK. No worries. :) Then maybe you have a suggestion for a first time contribution?

**Comment by SirCmpwn** [comment]
Sure! Why don't you [hop on IRC](http://webchat.freenode.net/?channels=sway-devel&uio=d4) to discuss it?

**Comment by SirCmpwn** [comment]
I'm closing issues that are resolved by the yet-unreleased sway 1.0.
