### ISSUE TITLE
Workspace switches to the newly spawned workspace , that is unnecessary. Breaking work Flow.

### ISSUE THREAD

**Issue by narutowindy** [swaywm/sway#1304]
example i opened a  mpv in $ws3,  from urxvt which is in $ws1, i dont want to switch right away to mpv to $ws3 .Sway puts me to the $ws3 rightaway, that breaks the working flow!! ,i could be doing something in the terminal.

>> i can use "workspace_auto_back_and_forth " to get back to my original workspace, but its not working at the first time spawn. 

>> i have to manually go back to my previous workspace $ws1, to work on my terminal again!!

**Comment by narutowindy** [comment]
assume : 
user working on terminal  in workspace1 .
 bash `$  >> mupdf " file.pdf" &` ;   opens in "workspace 4" automatically. 

-> in " i3 " it is opened it as Urgent workspace and doesnt switch to it .waits for the user to switch to new workspace

->  But in "sway", it switches new workspace automatically , ignoring the fact that "user could be doing something else in the terminal. "  we have to manually switch back to the workingspace to do my work. 


also in sway "workspace_auto_back_and_forth"   doesnt work at this point of time.

**Comment by SirCmpwn** [comment]
>bash `$ >> mupdf " file.pdf" & ;` opens in "workspace 4" automatically.

This does not happen in i3 unless you configure it to. Let me see your Sway config.
