### ISSUE TITLE
0.14 segfault on startup

### ISSUE THREAD

**Issue by max-orhai** [swaywm/sway#1305]
I can't get sway 0.14 to start. I'm using the latest version, but I'm new to sway. I'd like to be able to at least try it out!

This [gist](https://gist.github.com/max-orhai/7fb873ff630ac9344d5fe861db9d70bc) shows Void Linux package info and debug output for sway started from a tty, both as a regular user (it can't access a lockfile) and as root (trying to work around the permissions). I don't have a sway config file yet.

If it's just misconfigured somehow, please let me know so I can inform the package maintainers.

**Comment by SirCmpwn** [comment]
Can you get a stack trace from the core dump?

**Comment by SirCmpwn** [comment]
We don't work very hard to maintain musl support. Are you interested in maintaining it?

**Comment by embik** [comment]
I'm having the same issue and I'm on Gentoo without musl. I'll provide more deails once I got some other desktop up and running.

**Comment by max-orhai** [comment]
I don't believe it's musl-related, since my coworker (also on Void) had the same problem, using the glibc version of the package. I was able to get both Weston and Enlightenment to start without any trouble, so it's not fundamental to my Wayland setup. Might possibly be WLC, though.

I couldn't get anything interesting out of gdb, but I gave up fairly quickly. Now that I'm up and running with i3 I'll try to compile sway myself. I don't see any debugging options in the cmake lists... can you give some advice on how to get a stack trace?

**Comment by SirCmpwn** [comment]
Grab a core dump and open it with gdb.
