### ISSUE TITLE
0.14 keyboard layout switches on non-alphanumeric symbol

### ISSUE THREAD

**Issue by wyvie** [swaywm/sway#1315]
Hello. I have the keyboard layout set in my sddm scripts:
```
export XKB_DEFAULT_LAYOUT=us,ru
export XKB_DEFAULT_OPTIONS=grp:caps_toggle,grp_led:scroll

export WLC_REPEAT_DELAY=150
export WLC_REPEAT_RATE=30
```

With that, when I'm on russian layout and enter the non-alphanumeric symbol, say, ',' or ')', the layout switches on it's own, starting to produce latin symbols. Though for sway (or libinput) it seems that layout's still 'ru', because it takes me two 'caps' presses to get back to 'ru'.
Couple friends of mine report the same behaviour.

**Comment by 4e554c4c** [comment]
Sounds like a libinput problem, I don't think this is a sway issue.

**Comment by SirCmpwn** [comment]
I agree. Can you reproduce this on other compositors or under xorg?

**Comment by wyvie** [comment]
under xorg using xkb and i3 everything's fine.
may try to install other wm or de. will try kde later today or tomorrow

forgot to mention (not sure whether it's important or not), i'm using arch, my friend with the same issue is using fedora.

**Comment by wyvie** [comment]
well, in plasma on wayland everything seems fine. no unexpected keyboard layout switches.
though i've set up the settings using kde settings, so might be different that way

**Comment by SirCmpwn** [comment]
Use the exact same XKB settings configured through the same environment variables on weston.
