### ISSUE TITLE
Flickering and crash

### ISSUE THREAD

**Issue by acorreya** [swaywm/sway#1344]
Windows flickers like anything (even terminals) while scrolling. This does not show up when `swaygrab -c` is on, hence a video from my mobile phone [https://goo.gl/photos/nBq1Td3wA8AEKyeDA](https://goo.gl/photos/nBq1Td3wA8AEKyeDA) . The system hard-crashes occassionally (no magic keys to the rescue; only hard reset) but not sure if this is related to the flicker. Tried to redirect `sway -d` to a log file but loses it during the crash. Ready to provide any log...

**Comment by SirCmpwn** [comment]
GPU?

**Comment by acorreya** [comment]
it it this?
```
hwinfo --gfxcard   
10: PCI 02.0: 0300 VGA compatible controller (VGA)              
  [Created at pci.378]
  Unique ID: _Znp.CCoAMI2qUtC
  SysFS ID: /devices/pci0000:00/0000:00:02.0
  SysFS BusID: 0000:00:02.0
  Hardware Class: graphics card
  Model: "Intel Atom Processor Z36xxx/Z37xxx Series Graphics & Display"
  Vendor: pci 0x8086 "Intel Corporation"
  Device: pci 0x0f31 "Atom Processor Z36xxx/Z37xxx Series Graphics & Display"
  SubVendor: pci 0x1025 "Acer Incorporated [ALI]"
  SubDevice: pci 0x0933 
  Revision: 0x0e
  Driver: "i915"
  Driver Modules: "i915"
  Memory Range: 0x90000000-0x903fffff (rw,non-prefetchable)
  Memory Range: 0x80000000-0x8fffffff (ro,non-prefetchable)
  I/O Ports: 0x2050-0x2057 (rw)
  Memory Range: 0x000c0000-0x000dffff (rw,non-prefetchable,disabled)
  IRQ: 256 (3261 events)
  Module Alias: "pci:v00008086d00000F31sv00001025sd00000933bc03sc00i00"
  Driver Info #0:
    Driver Status: i915 is active
    Driver Activation Cmd: "modprobe i915"
  Config Status: cfg=new, avail=yes, need=no, active=unknown

Primary display adapter: #10
```

**Comment by SirCmpwn** [comment]
I can reproduce this with

```
19: PCI 02.0: 0300 VGA compatible controller (VGA)              
  [Created at pci.378]
  Unique ID: _Znp.j5duo6BuBmF
  SysFS ID: /devices/pci0000:00/0000:00:02.0
  SysFS BusID: 0000:00:02.0
  Hardware Class: graphics card
  Model: "Intel Mobile 4 Series Chipset Integrated Graphics Controller"
  Vendor: pci 0x8086 "Intel Corporation"
  Device: pci 0x2a42 "Mobile 4 Series Chipset Integrated Graphics Controller"
  SubVendor: pci 0x17aa "Lenovo"
  SubDevice: pci 0x20e4 
  Revision: 0x07
  Driver: "i915"
  Driver Modules: "i915"
  Memory Range: 0xf2000000-0xf23fffff (rw,non-prefetchable)
  Memory Range: 0xd0000000-0xdfffffff (ro,non-prefetchable)
  I/O Ports: 0x1800-0x1807 (rw)
  Memory Range: 0x000c0000-0x000dffff (rw,non-prefetchable,disabled)
  IRQ: 16 (72887 events)
  I/O Port: 0x00 (rw)
  Module Alias: "pci:v00008086d00002A42sv000017AAsd000020E4bc03sc00i00"
  Driver Info #0:
    Driver Status: i915 is active
    Driver Activation Cmd: "modprobe i915"
  Config Status: cfg=new, avail=yes, need=no, active=unknown
```

I'm tempted to pin this issue on either wlc or the graphics driver.

**Comment by acorreya** [comment]
Is there anything I should do about it? Like raising an issue somewhere?

**Comment by 4e554c4c** [comment]
You've already made an issue. If you'd like to help please debug more and send a patch.

**Comment by acorreya** [comment]
Please guide me, I'm all ears.

**Comment by SirCmpwn** [comment]
See if you can reproduce it on older kernels. If you can, start doing a bisect. Try older wlc builds if that doesn't work. Maybe things like libdrm as well. Narrow down the problem.

**Comment by PeaceAlways** [comment]
Mine too flickers, not usually but occasionally during chromium is running in full screen. I don't know but I guess this is not a graphics driver issue.

**Comment by acorreya** [comment]
Update:
Looks like it flickers rarely when using kernel `aur/linux-rt-bfq 4.9.47.37-1 (7, 0.52)`.

`4.12.13-1-ARCH #1 SMP PREEMPT Fri Sep 15 06:36:43 UTC 2017 x86_64 GNU/Linux` .

**Comment by acorreya** [comment]
Can see the same on `way-cooler 1:0.6.2-2`, less flicker on linux-rt-bfq kernel

**Comment by Timidger** [comment]
I've been seeing similar issues on Way Cooler, but only on one of my machines. It's definitely not wlc related, as I have another machine that doesn't experience the issue. It's almost certainly some dependency issue, coupled potentially with a bad driver or something. Using standard Linux kernel myself, so libdrm might be a good thing to try next.

**Comment by SirCmpwn** [comment]
How about on other non-wlc Wayland compositors?

**Comment by Timidger** [comment]
@SirCmpwn Haven't tested, I'll try running Weston tonight and see if I can reproduce it.

**Comment by Timidger** [comment]
After some testing on wlroots, I can't reproduce it (it only appears sometimes though, so maybe it just hasn't happened yet).

I'll test on wlroots later, maybe if we are lucky this is just a weird wlc edge case that didn't make it to wlroots.

**Comment by SirCmpwn** [comment]
This has been confirmed to not affect wlroots, so we'll probably just sit tight.

**Comment by natesymer** [comment]
Has any progress been made?

I get similar crashes too, I'm on the latest kernel. It only seems to happen when I have chromium open, and it happens only once or twice per day, it seems to have something to do with uptime.

Also, when I do get a crash, the only thing that works is a hard reset. Everything is completely frozen, or at least the video is frozen and everything else is still working.

**Comment by SirCmpwn** [comment]
See the previous comment.
