### ISSUE TITLE
swaybar eats a core with i3status and an external script

### ISSUE THREAD

**Issue by viluon** [swaywm/sway#1352]
When configuring `swaybar` to use [an external script](https://pastebin.com/5EN48VDK) (saved as `~/.config/sway/run-i3status.zsh`) to invoke `i3status`, the `swaybar` process eats a core (CPU usage goes up to ~100/`$(nproc)`) and doesn't display anything (the line is updating too quickly?).

Relevant part of `~/.config/sway/config`:
```
#
# Status Bar:
#
# Read `man 5 sway-bar` for more information about this section.
bar {
    status_command run-i3status.zsh
    position top
    colors {
        statusline #ffffff
        background #323232
        inactive_workspace #32323200 #32323200 #5c5c5c
    }
}
```
See also [`i3status.conf`](https://pastebin.com/BLSjh6cA) and [`/tmp/weather.txt`](https://pastebin.com/Gje17qUH).

Environment information:
```
$ uname -a
Linux archluon 4.12.12-1-ARCH #1 SMP PREEMPT Sun Sep 10 09:41:14 CEST 2017 x86_64 GNU/Linux
$ sway -v
sway version 0.14.0
```

**Comment by SirCmpwn** [comment]
This isn't enough information to reproduce your setup locally.

**Comment by viluon** [comment]
@SirCmpwn I've provided the relevant script and `swaybar` configuration. What else is needed?

**Comment by SirCmpwn** [comment]
i3status.conf and the contents of /tmp/weather.txt

**Comment by viluon** [comment]
Sorry. Updated.
