### ISSUE TITLE
Touchscreen Accuracy Problem

### ISSUE THREAD

**Issue by xeanto** [swaywm/sway#1353]
I have a touchscreen and it seems to be very inaccurate, meaning wherever i touch, about 20 - 25 pixel below where i touch is where the actual click is happening. Is this just a wayland bug, or since sway is a compositor AND a DE, is it a sway problem?

**Comment by SirCmpwn** [comment]
It's probably a libinput issue. Try the wlroots touch screen demo and tell me how that goes.

**Comment by Turbito** [comment]
It's happening for me too

```
[ae@Elyssia examples]$ ./touch
unable to lock lockfile /run/user/1000/wayland-0.lock, maybe another compositor is running
```
It opens a window and when I touch nothing happens...

**Comment by SirCmpwn** [comment]
>It's probably a libinput issue. Try the wlroots touch screen demo and tell me how that goes.
It's probably a libinput issue. Try the wlroots touch screen demo and tell me how that goes.

**Comment by Turbito** [comment]
the executable generated in wlroots/build/examples called touch?
I run it, it opens a grey window and when I touch nothing happens
Is that what you're saying?

**Comment by SirCmpwn** [comment]
No, run that example from a tty like you would run sway.

**Comment by Turbito** [comment]
Thank you
It runs as intended I guess
A pic of a cat is draw where I touch. I have tried five fingers and five cats were draw

**Comment by SirCmpwn** [comment]
The cat is precisely centered under your finger, right?

**Comment by Turbito** [comment]
Yes, is centered and it follows my touch

**Comment by SirCmpwn** [comment]
Then you can expect your touchscreen problems to go away with wlroots.
