### ISSUE TITLE
Problems with git master versions of json-c

### ISSUE THREAD

**Issue by keithbowes** [swaywm/sway#1355]
Short version:  It won't compile out of the box.  If do you change the code in order to compile it, it will crash whenever you use any key binding.  I eventually decided to see if there were earlier tags of json-c that wouldn't have this problem and it seems that even with the latest one, version 0.12.1, sway compiles and runs just fine.  Maybe the maximum version of json-c with which sway will work should be indicated in README.

Long version:
When compiling, you get type mismatch errors in five files, all involving json_object_array_length in for loops:
`
sway/ipc-server.c: In function ‘ipc_client_handle_command’:
sway/ipc-server.c:449:21: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
   for (int i = 0; i < json_object_array_length(request); i++) {
`

The five files are:
* sway/ipc-server.c
* swaybar/status_line.c
* swaybar/tray/tray.c
* swaygrab/json.c
* swaylock/main.c

The solution for that is very simple.  Merely change the type of the counter variables from int to size_t.

On pressing keys, I've traced the problem to the line in ipc-server.c:
```c
json_object_object_add(obj, "binding", sb_obj);
```

My guess is that the call to `json_object_put(obj);` later in the function frees the objects recursively and then sb_obj is used (or more likely freed, as the stdout error I get from glibc is `*** Error in 'sway': corrupted double-linked list: `) later, causing an Earth-shattering kaboom.

Here's the log file.  I used Lynx because I couldn't figure out how to upload a file with my usual browser (though, I know, Lynx should be be usual browser; with Lynx, all I had to do was ^Xe:e ~/.sway.log&lt;Return&gt;VGy:e \#1&lt;Return&gt;p:wq) and I seem not to have been logged into to github, so it's anonymous gist.  Hmm.
 https://gist.github.com/anonymous/fe18bb44c7d40d5d63fbf15427e70fdc

**Comment by SirCmpwn** [comment]
Looks like you have enough information to put a patch together?

**Comment by keithbowes** [comment]
I got it to compile by changing the CmakeLists.txt file to ignore warnings, but I have no idea how to fix the crash.  Mere typecasting doesn't work.  I guess you'd have to really change a lot of Sway's internal code so that it uses the same data types as json-c.

**Comment by mariusor** [comment]
Hi @keithbowes, I took a look at your issue also and I think besides explicitly requiring the latest json-c version in the cmake file, there's really nothing that can be done. The latest version returns int for `json_object_array_length`.

**Comment by ranisalt** [comment]
Oh, how I love C++11 auto <3

**Comment by SirCmpwn** [comment]
I'll be getting a bugfix release out fairly soon, and will address this in it.

**Comment by SirCmpwn** [comment]
Wait, if it's a bug with json-c, can Fedora ship a patched version?

**Comment by morxa** [comment]
Yes, Fedora now includes the json-c patch in Rawhide ([commit](https://src.fedoraproject.org/rpms/json-c/c/9c657adefedb4f9b0392cdbb993bb688a5907c35?branch=master)), so at least from Fedora side, the problem is fixed. I would suggest to test the patched version of json-c before doing any other work related to this issue.

**Comment by besser82** [comment]
The problem was in Sway actually…  The current patch Fedora ships was a cludge to restore the faulty behaviour when doulbe free'ing a json_object…

The fixes needed for Sway are in #1517.

I will apply these to Sway in Fedora and update json-c to the correct patch, which prevents segfaults on double free and fails an assert instead.

**Comment by cauebs** [comment]
`json-c` just got updated to 0.13 on ArchLinux. Now what?

**Comment by besser82** [comment]
@cauebs Use sway v0.15.1 release, which has all needed fixes.

**Comment by 4e554c4c** [comment]
Somewhat unrelated, should this be changed in wlroots as well? I had
trouble compiling it with the recent json-c.

**Comment by emersion** [comment]
No. wlroots doesn't use json-c.

**Comment by 4e554c4c** [comment]
I meant the `wlroots` branch of sway, sorry for confusion.

**Comment by SirCmpwn** [comment]
Next person inconvenienced by it will backport the patch to that branch.
