### ISSUE TITLE
Segfault when running without systemd (voidlinux)

### ISSUE THREAD

**Issue by Guppster** [swaywm/sway#1356]
`sway --version` : sway version  (2017-07-28, branch "")
wlc : 0.0.10

I'm trying to install sway on voidlinux and run from tty. I run into a segmentation fault with the following errors:

```
Segmentation Fault
09/13/17 09:23:53 - [main.c:65] swaybg requires the compositor to support the desktop-shell extension.
09/13/17 09:23:53 - [registry.c:256] Error opening display
09/13/17 09:23:53 - [ipc-client.c:37] Unable to connect to /run/user/1000/sway-ipc.1000.1474.sock

```

`sway -V` : https://gist.github.com/Guppster/3861e6ce580105c1c5ba502466a50797
`strace` : https://gist.github.com/Guppster/c5d5f90d737c362e3ee47ce4c91dcb60

Two lines that stood out to me at the end of the strace were: 

```
"[wlc] Could not open /dev/tty0 t"..., 46[wlc] Could not open /dev/tty0 to find free vt) 
openat(AT_FDCWD, "/dev/tty0", O_RDWR|O_CLOEXEC) = -1 EACCES (Permission denied)
```

https://github.com/SirCmpwn/sway/issues/1292

This is a duplicate but unlike the previous issue iv tried both setuid and setcap with errors on both. The above output was the result of running with just setuid. When i run with just setcap i receive the same output as the previous issue: `[main.c:48] [wlc] Could not open /dev/tty0 to find free vt`

**Comment by SirCmpwn** [comment]
Remove all caps and add setuid. It's important that you *remove* all caps if you use setuid.

**Comment by Guppster** [comment]
`getcap /usr/bin/sway` returns nothing.

**Comment by SirCmpwn** [comment]
*And* it's setuid? If so I'll need a full, unadulterated/uninterpreted debug log.

**Comment by Guppster** [comment]
```
ls -la /usr/bin/sway
-rwsr-xr-x 1 root root 320656 Jul 28 03:34 /usr/bin/sway
```
I think it is setuid. 

`sway -Vd` : https://gist.github.com/Guppster/a5694727cf4bba7e41727241bf19afd5

**Comment by SirCmpwn** [comment]
This is weird. Are you running it on musl? Do you have a coredump?

**Comment by Guppster** [comment]
Nope not on musl 

Coredump?: https://mega.nz/#!ugZwCQrS!cn3yq5nuUURQ_5GKdn7bhDnMZYFsQoinT_c2K4FYijA

**Comment by SirCmpwn** [comment]
Can you compile in debug mode (with symbols and no optimizations) and attach to that coredump to gdb, then provide a stacktrace?

**Comment by Guppster** [comment]
I'v been trying to do that, but haven't been very successful. :confused: 
Things i did:
* Cloned the repo
* Changed line 5 of CMakeLists.txt to include `-O0 -g` 
* Ran the cmake, make, make install commands
* Ran `sudo chmod a+s /usr/local/bin/sway`
* Tried to run `sway` which produced the same result as the initial post and generated a core file
* Ran `gdb sway corefile`
* typed `run` and it produced `Could not open /dev/tty0 to find free vt` which is not what it produced when ran outside of gdb. (this is usually how it behaves when i setcap outside of gdb)
* typed `backtrace` and got back `No stack` :(

**Comment by Guppster** [comment]
```
$ dbus-test-tool black-hole
Failed to connect to bus: org.freedesktop.DBus.Error.NotSupported: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
```

```
$ lspci -k |grep VGA -A 2
03:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Tahiti XT [Radeon HD 7970/8970 OEM / R9 280X]
        Subsystem: XFX Pine Group Inc. Double D HD 7970
        Kernel driver in use: radeon
```

**Comment by SirCmpwn** [comment]
Looks like this was fixed in wlc, per the discussion on the way-cooler ticket.
