### ISSUE TITLE
Fullscreen browser video not scaling properly

### ISSUE THREAD

**Issue by woutermont** [swaywm/sway#1361]
When putting a video on fullscreen in chromium or opera (not in firefox, apparently), the output scales wrong: with scaling factor 2, only the top left quarter of the video is being displayed. Firefox sometimes seems to do this as well before quickly rescaling to the correct size.

**Comment by SirCmpwn** [comment]
I'm closing issues that are resolved by the yet-unreleased sway 1.0.
