### ISSUE TITLE
Get duplicate workspaces

### ISSUE THREAD

**Issue by elverskog** [swaywm/sway#1364]
I'm seeing the workspace "2" appear twice in my right monitor in i3 manage bar (screen below) . I assume there are actually two "2" workspaces and this is not an issue with the bar. 

I couldn't find an existing issue like this. I think this happened after I moved a workspace from one monitor to the other.

I cannot access the second "2" in any logical way. Somehow I wind up on one versus the other but I can't see a pattern. I can move the first "2" workspace around but there are always 2 of them.

Please let me know if you want conf lines etc.

btw - swaygrab requires imageMagick (got a "convert not found error") but sway/swaygrab installs without it. I guess most people have it already?

![2017-09-22-114001_swaygrab](https://user-images.githubusercontent.com/7500216/30752624-dde934a0-9f8a-11e7-82af-cf20927c3dd9.png)

**Comment by SirCmpwn** [comment]
Output of swaygrab -rt get_workspaces?

**Comment by elverskog** [comment]
invalid option -- t

**Comment by SirCmpwn** [comment]
Sorry, `swaymsg -rt get_workspaces`

**Comment by elverskog** [comment]
bt - I already got rid of the dupe workspace (sorry). Not sure how I did it.

**Comment by SirCmpwn** [comment]
Well, if it happens again, reopen this and give me that command again.

**Comment by elverskog** [comment]
Will do

**Comment by SirCmpwn** [comment]
Yep, that's weird. Can you get me a Sway core dump? `gcore -o sway.core [sway's pid]`. Note this contains all of Sway's memory so if you have anything sensitive in your config or window titles or such, be mindful of that.

**Comment by elverskog** [comment]
Will do. I'm in the middle of my workday. So I keep fixing the issue and reproducing. So if I get it to break again. I will post the workspace output again as well.

**Comment by elverskog** [comment]
[workspace-dump-2.txt](https://github.com/SirCmpwn/sway/files/1325183/workspace-dump-2.txt)

I see two PIDs for sway. Sound weird? Like` ps aux | grep sway` right?

**Comment by elverskog** [comment]
Looking at getting a core dump (in Arch). This is new to me.

**Comment by elverskog** [comment]
Tried it a few ways. Always says neither PID is running. I assume ps aux and pgrep have access to that process but my user does not...or?

**Comment by elverskog** [comment]
One of the dump files is about 1.6mb the other is 65mb. I've attached the former. Lemme know if there is something I can do with the larger file. 

[sway.core.431.txt](https://github.com/SirCmpwn/sway/files/1325298/sway.core.431.txt)

**Comment by SirCmpwn** [comment]
I'm closing issues that are resolved by the yet-unreleased sway 1.0.
