### ISSUE TITLE
ipc: harmonize `get_tree` with i3

### ISSUE THREAD

**Issue by lbonn** [swaywm/sway#1386]
The tree contains most of the information but does not respect the latest i3 spec: https://i3wm.org/docs/ipc.html#_tree_reply

* no `focus` array (might be difficult?)
* in i3 responses, all of these fields are mandatory for all nodes (even `root` and `output`), whereas sway adds them selectively. In many cases, a default value of `null` or `[]` should suffice.

These issues may hinder interoperability with some existing ipc libraries.

**Comment by SirCmpwn** [comment]
Aye, you should add them and send a patch. `focus` shouldn't be difficult.
