### ISSUE TITLE
wlroots status

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/sway#1390]
## Is it done yet?

# NO

## Can I use it anyway?

# OKAY, BUT DON'T ASK US FOR HELP

This todo list is largely unordered and far from complete, but serves as a decent reference/list of things we should not forget to do.

* [x] spin up the backend
* [ ] ~~s/sway list_t/wlroots list_t/g~~
* [x] Unify sway and wlroots logging
* [x] Find and // todo all references to wlc
  * [x] Stop linking to wlc entirely
* [x] Configuration
  * [x] Re-add command handling
  * [x] [Command list](https://github.com/swaywm/sway/issues/1390#issuecomment-355792054)
* [x] Tree
  * [x] Configure wlr_output_layout for root_container
  * [x] Outputs
    * [x] Add to tree
    * [x] Re-attach workspaces to hotplugged outputs
    * [x] Handle output removal
    * [x] Handle zero outputs
    * [x] Create a workspace
    * [x] Configure outputs
  * [x] Containers
  * [x] Add shell views to tree
    * [x] xdg_shell
      * [x] Handle popups
    * [x] wl_shell
    * [x] xwayland
  * [x] Arrange windows
    * [x] L_HORIZ
    * [x] L_VERT
    * [x] L_TABBED
    * [x] L_STACKED
    * [x] Floating
    * [x] Gaps
* [x] Workspaces
  * [x] Use config file to reason about names
  * [x] Switching between workspaces (focus)
* [x] IPC
  * [x] Run IPC server
  * [x] get_version
  * [x] command
  * [x] subscribe
    * [x] send notifications
  * [x] get_tree
  * [x] get_outputs
  * [x] get_marks
  * [x] get_inputs
  * [x] get_workspaces
  * [ ] ~~get_clipboard~~
* [x] Rendering
  * [x] Wire up frame loop
  * [x] Render surfaces
    * [x] xdg_shell
      * [x] popups
    * [x] wl_shell
    * [x] xwayland
    * [x] Layer shell
    * [x] subsurfaces
  * [x] Damage tracking
  * [x] Window borders
* [x] Drag and drop
* [x] Refactor Sway's tree to support wlr structures
* [x] Input
  * [x] Enumerate devices
  * [x] wlr_cursor
  * [x] wl_seat
  * [x] Focus semantics
    * [x] Focus follows mouse
    * [x] Focus going down the tree (#1582)
  * [x] Device configuration
    * [x] Support existing features
    * [x] wlr_cursor configuration
    * [x] Extended keyboard configuration
  * [ ] Drawing tablets
    * [x] Simulate pointer events
    * [ ] tablet protocol
    * [ ] Bindings for pad buttons
  * [ ] Touch
    * [x] wl_touch
    * [ ] Simulate pointer events
    * [ ] Gesture bindings
* [x]  HiDPI
* [x] Mouse bindings
* [ ] Interactive move/resize
  * [x] Floating
  * [ ] Tiling
* [ ] Sort out forking and privledged process
* [ ] Security config
* [x] server-decorations
* [x] Revert nvidia proprietary driver stuff
* [x] Add modes to swaymsg -t get_outputs
* [x] Side projects (all need to be converted to sway-protocols)
  * [x] swaybg
  * [x] swaybar
  * [x] swaylock

Also just grep for "TODO WLR" on the wlr branch to find a bunch of notes I've left behind.

## Test plan

For now I'm only using this space as a reminder to include the stuff I expect to break but might get forgotten.

* [x] Test all IPC interactions and compare with i3
* [ ] Test the utter shit out of everything else

**Comment by fourtytwo** [comment]
How long is the wlroots transition expected to take ?

**Comment by Fale** [comment]
"My goal is to ship sway 1.0 before the end of the year. These are exciting times for Wayland, and I hope you’re looking forward to it." from https://drewdevault.com/2017/10/09/Future-of-sway.html

**Comment by PeaceAlways** [comment]
Yeah, of course we are looking forward for it.

**Comment by SirCmpwn** [comment]
Alright guys, it's go time. I have laid the foundation for a wlroots-based sway, and it's time to get everyone involved in working on porting it over. Remember to join the IRC channel, #sway-devel on freenode, for collaboration.

I added this to the OP to explain the approach we're taking:

>Large swaths of Sway code has been moved to sway/old/ and include/sway/old/ for reference. There are now two directories, sway/desktop/ and sway/tree/, where most of the work is ongoing. The former is where sway touches wlroots - event listeners, shell handlers, and so on all live here, and it has ownership over all wlr_* resources. sway/tree/ is where the sway tree is being managed, and contains code for manipulating the tree.
>
>The plan is to gradually re-implement features of sway here. We will gradually re-introduce parts of the code from the old directories and adapt them for use with wlroots, rewriting and refactoring as appropriate. I'm also taking this opportunity to do some cleanup of some of the codebase's bigger design problems - this is a good opportunity to tweak existing interfaces to be cleaner while we're refactoring everything anyway.

The next things I want to work on right now are, approximately in order:

* Spinning up the tree (getting workspaces, containers, and views into the tree)
* Spinning up the command subsystem and porting a few commands over
  * Using these to configure outputs
* Spinning up IPC
* Arranging the tree
* Rendering views

**Comment by SirCmpwn** [comment]
Backend configuration spec:

`backend add <type> [--name <name>] [args...]`: spins up a backend of the given type with the given name (or a generated name: `type-number` e.g. `libinput-0`). `[args...]` is backend-specific, such as a path to a DRM device for the DRM backend, a DISPLAY for x11, an initial number of outputs for the wayland backend, etc.

`backend del <name>`: does what it says on the tin

`backend <name> <subcommand> [args...]`: runtime manipulation of backend-specific features

### Subcommands

**wayland**

`backend wayland-0 add-output`

`backend wayland-0 del-output <id>`

**x11**

See wayland

**headless**

See wayland, plus

`backend headless-0 add-input <caps...>`

`backend headless-0 del-input <id>`

`backend headless-0 input <id> <send-keys|depress|release|click|move> [...]`

### Example use-cases

- Add an RDP backend at runtime so your buddy can pair program with you
- Add a headless backend for scripting with
- Add a nested Wayland backend to your DRM session cause you're weird
- Add an x11 backend to your DRM session so you can switch TTYs to your x session and still manipulate your sway session

**Comment by SirCmpwn** [comment]
We should probably also add `sway --no-backend` to start it up with an empty multi-backend so you can explicitly configure the backends you need at runtime.

**Comment by acrisci** [comment]
I wonder if we could support this use case with the mixed backends. I've wanted to try this out in my workflow for awhile.

I would like to "split" a monitor so it is treated as two separate sway outputs. So for instance, if I split one of my monitors in half, it will have two separate groups of workspaces (which I can assign to either output on the monitor), and when I fullscreen a container on one of the split monitors, it will only fullscreen on that half of the screen. It would also use the tree move logic for outputs when moving between them which is convenient sometimes.

The multi backend feature might allow me to use one of my outputs to have two wayland window outputs nested within them which are arranged tiled. That would give me what I want, except we would have to be careful to choose how keyboard events are delivered to the window.

**Comment by SirCmpwn** [comment]
It might be better to write some kind of plugin that spins up a DRM backend *separately* from Sway's backend support code, then subdivides the outputs on it and exposes them back into the Sway tree and handles the rendering necessities.

**Comment by 4e554c4c** [comment]
- [ ] Commands
  - [ ] Basics
    - [x] `bind`
    - [ ] `debuglog`
    - [x] `include`
    - [x] `exec`
    - [x] `exec_always`
    - [x] `exit`
    - [ ] `reload`
    - [x] `set`
  - [ ] New -- needs documentation
    - [x] `input`
    - [x] `seat`
  - [ ] Old
    - [ ] `bar`
    - [ ] `border`
    - [ ] `client`
    - [ ] `floating`
    - [ ] `focus`
    - [ ] `font`
    - [ ] `fullscreen`
    - [ ] `gaps`
    - [ ] `kill`
    - [ ] `layout`
    - [ ] `mark`
    - [ ] `move`
    - [ ] `resize`
    - [ ] `scratchpad`
    - [ ] `split*`
    - [ ] `sticky`
    - [x] `output`
    - [ ] `workspace`
  - [ ] Other
    - [ ] Criteria matching

**Comment by SirCmpwn** [comment]
Development is organized [on IRC](http://webchat.freenode.net/?channels=sway-devel&uio=d4), join us there.

**Comment by ReK2Fernandez** [comment]
any news on this?

**Comment by Wolf480pl** [comment]
I think this should be updated to reflect #1735

**Comment by SirCmpwn** [comment]
Thanks @Wolf480pl

**Comment by SirCmpwn** [comment]
Come join us in the IRC channel and ask for things to do:

http://webchat.freenode.net/?channels=sway-devel&uio=d4

#sway-devel on irc.freenode.net

**Comment by SirCmpwn** [comment]
I have split the work that remains out into separate tickets. We're almost there!

**Comment by SirCmpwn** [comment]
https://github.com/swaywm/sway/milestone/1

**Comment by asymmetric** [comment]
Should this be updated to say **YES**?

**Comment by SirCmpwn** [comment]
Sure.
