### ISSUE TITLE
VT switching input repeats

### ISSUE THREAD

**Issue by arcnmx** [swaywm/sway#1391]
Executing a program like `chvt` or [physlock](https://github.com/muennich/physlock) from within sway seems to trip up the input handling and cause it to react as if the last keys held before switching to the VT are still being held. This results in:

1. If executed from within a terminal, the enter key press is repeated constantly.
2. If executed from a `bindsym` key binding, it is executed repeatedly and tends to get the system stuck in an unusable state.

**Comment by SirCmpwn** [comment]
Why are you even doing this in the first place?

**Comment by arcnmx** [comment]
Heh, I like how physlock looks. Though the one important advantage of using physlock over swaylock currently is that a VT can trigger DPMS.

**Comment by SirCmpwn** [comment]
I think we're just not going to support this behavior.

**Comment by arcnmx** [comment]
Expected that :(

Would you accept a patch that fixes it? I've seen a lot of bugs and feature requests that get closed and it's ambiguous whether your stance is that it doesn't belong in the codebase or you're just trying to prune issues you don't have the time or interest to address. Maybe github issue labels could help with that?

**Comment by arcnmx** [comment]
Oh hm playing with it more just running `chvt` causes freezes and segfaults in sway pretty easily and can also lockup other system VTs...

**Comment by SirCmpwn** [comment]
In this case I would accept a patch.
