### ISSUE TITLE
Spontaneous segfaults

### ISSUE THREAD

**Issue by jniedrauer** [swaywm/sway#1392]
I am running sway-0.14.0-2.fc26.x86_64 from the fedora repositories. Periodically, it will segfault and dump me back to VT. I haven't seen any kind of pattern to the segfaults, although it often happens while while launching an xwayland application. More specifically, I have noticed it multiple times while I am using a python module called streamlink (https://github.com/streamlink/streamlink) to launch mpv. At a guess, it happens about once every 50 times I use it. I've also seen crashes while using firefox 57 beta.

The only other unusual thing I am running is redshift compiled from https://github.com/giucam/redshift.git, and launched by a systemd user daemon that executes `redshift -m wayland`

Log output from a crash triggered by streamlink is attached. This includes firefox subsequently crashing as well. Beyond what I've attached, it goes on to list many crashing xwayland applications over the course of the next few seconds.
[journalctl.txt](https://github.com/swaywm/sway/files/1378337/journalctl.txt)

**Comment by SirCmpwn** [comment]
https://github.com/SirCmpwn/sway/wiki#how-do-i-report-issues

**Comment by SirCmpwn** [comment]
Stack trace too as well
