### ISSUE TITLE
specified keyboard layout not being used

### ISSUE THREAD

**Issue by charlesay** [swaywm/sway#1393]
I am trying to use the US intl keyboard layout, but despite XKB environment variables being set (correctly?), the correct behaviour doesn' t happen, for example alt+q does not produce 'adiaresis'

sway version 0.14.0
Sway Config: https://gist.github.com/anonymous/519df2d477bed422f42d443f767ffa28
Sway Log: https://gist.github.com/anonymous/709d402182e4204bad89e7876e1cb4df
printenv: https://gist.github.com/anonymous/2cab4b59854040a11a299dd41fa51953

**Comment by charlesay** [comment]
i would like to use sway but can't mostly because of this. would appreciate some response

**Comment by SirCmpwn** [comment]
So debug it.

**Comment by charlesay** [comment]
any suggestions as to how?

**Comment by SirCmpwn** [comment]
gdb

**Comment by charlesay** [comment]
how do i use that in this case?

**Comment by paulolieuthier** [comment]
I got it to work by setting both `XKB_DEFAULT_VARIANT` and `XKB_DEFAULT_LAYOUT` in `~/.zshrc`.

**Comment by paulolieuthier** [comment]
> I got it to work by setting both XKB_DEFAULT_VARIANT and XKB_DEFAULT_LAYOUT in ~/.zshrc.

@charlesay I see now that you have set as well, sorry. And it only works for me when starting from a shell, not from GDM.

**Comment by paulolieuthier** [comment]
OK, it works for me now, starting Sway from GDM. Simply put your environment variables in `~/.pam_environment`.

```shell
$ cat ~/.pam_environment
XKB_DEFAULT_LAYOUT=us
XKB_DEFAULT_VARIANT=intl
```

**Comment by paulolieuthier** [comment]
Now to find why it does't respect my changes to `/usr/share/X11/xkb/symbols/us`.
