### ISSUE TITLE
_XOPEN_SOURCE and _POSIX_C_SOURCE causing trouble on FreeBSD

### ISSUE THREAD

**Issue by johalun** [swaywm/sway#1396]
Even the highest values on any these cause 
```
#define SOCK_CLOEXEC 0x10000000
#define SOCK_NONBLOCK 0x20000000
```
(and maybe more) to be hidden on FreeBSD (__BSD_VISIBLE = 0).
Optimal for FreeBSD is not using these macros at all. Is it possible to move all these declarations to some Linux specific header?

**Comment by johalun** [comment]
For now it's only one file, ipc-server.c. Maybe can make some exception for that file. The other files are ok with bumping xopen source to 700.

**Comment by SirCmpwn** [comment]
You can add ifdefs to that file to avoid defining them on FreeBSD if you like.

**Comment by johalun** [comment]
Maybe this is the culprit? 
`set(CMAKE_C_STANDARD 99)`
Setting c99 basically hides everything on FreeBSD.. 
```
#elif defined(_C99_SOURCE)	/* Localism to specify strict C99 env. */
#define	__POSIX_VISIBLE		0
#define	__XSI_VISIBLE		0
#define	__BSD_VISIBLE		0
#define	__ISO_C_VISIBLE		1999
#define	__EXT1_VISIBLE		0
```

**Comment by SirCmpwn** [comment]
You can bump it to 11 if that makes it easier?

**Comment by johalun** [comment]
No, 11 is the same. 
Here's a Q/A about similar issues. 
https://lists.freebsd.org/pipermail/freebsd-standards/2004-March/000474.html
and the source
https://github.com/freebsd/freebsd/blob/master/sys/sys/cdefs.h#L748-L773

**Comment by SirCmpwn** [comment]
This is good now, right?

**Comment by johalun** [comment]
It's working for now, although not an elegant solution.

**Comment by johalun** [comment]
Maybe it would be nice if these macros could be defined in the cmake config files instead of headers.

**Comment by ascent12** [comment]
I agree that setting it on a per-file base is pretty pointless.
It's fully expected that POSIX.1-2008 is supported. Having it defined per-file isn't going to change anything.
If it removes a lot of clutter and makes it easier for other platforms, it's even more reason to put it in the build system.

**Comment by SirCmpwn** [comment]
It's not like I'm unaware that you can define POSIX macros when you invoke the compiler. This was a deliberate design decision.

**Comment by ascent12** [comment]
Yes, I'm aware that it's a deliberate design decision, but I think it's a pointless one.
It simply adds boilerplate and people needing to worry about POSIX standard versions for absolutely no advantage.
