### ISSUE TITLE
possible bug when config variable is set in included file

### ISSUE THREAD

**Issue by majewsky** [swaywm/sway#1399]
I wanted to put this in my config (which is shared across multiple systems):

```
set $wallpaper /usr/share/sway/Sway_Wallpaper_Blue_1920x1080.png
include /home/username/.config/sway/config.d/wallpaper # local override for the $wallpaper variable
output * bg $wallpaper fill
...
bindsym $mod+Escape exec swaylock -i $wallpaper
```

Herein, the included file has just a single line

```
set $wallpaper /path/to/this/machine's/custom/wallpaper.png
```

However, the value set for `$variable` in the included file is not visible in the main config file where the variable is used. Hence, I'm seeing the default wallpaper. There are two options:

1. This is not intended, and therefore a bug in the program.
2. This is intended, and therefore a bug in the documentation since it doesn't explain this behavior.

**Comment by SirCmpwn** [comment]
Can I see your full config, please.

**Comment by majewsky** [comment]
https://github.com/majewsky/system-configuration/blob/3e8bfc00dd62a2803ce77534931e1563688a3b0c/src/sway.cfg is installed as `/etc/sway/config`, and there is no `~/.config/sway.d/config`.

The commit following that one implemented the workaround that I'm currently using: https://github.com/majewsky/system-configuration/commit/2a31e481eb8b5a93b9cb5e68555af2b4bf290104

**Comment by RedSoxFan** [comment]
This appears to be working fine for me in both 0.15.2 and master so I'm going to close this. If you are still having issues, feel free to reopen with a full debug log.
