### ISSUE TITLE
GTK+ 3.22.24 invisible/transparent windows if not alone in a tag

### ISSUE THREAD

**Issue by tuncer** [swaywm/sway#1403]
As of today's build that's using https://github.com/Cloudef/wlc/commit/e3abf0b2f322b9d376ced452190cd4dd9f6fcb8a and https://github.com/SirCmpwn/sway/commit/ea0f1f3a7edf92537f74b70b520103bb38ff1411, unless a GTK+3 window is the sole window in a tag/desk, it will be tiled into a column where the tile is completely empty as if the GTK+ window is fully transparent. If I move the window to a different tag or start it there, and it's thus the only window, it's visible and interactive.

**Comment by tuncer** [comment]
Yes, though I wouldn't be able to tell exactly when this started. Perhaps somewhere in the last week or two/three?

Maybe at some point it'd make sense to pull in and link wlc (or its successor) as a submodule of sway, making sure they're both compatible at all times.

**Comment by SirCmpwn** [comment]
Can you do a bisect?
