### ISSUE TITLE
Polybar?

### ISSUE THREAD

**Issue by AravK** [swaywm/sway#1404]
This is not really an issue, but Polybar (sweetest thing ever) doesn't work with Wayland (I think). It shows up on top of other windows, and I'm not sure whether Sway could use polybar as the `swaybar_command` in the bar. How would I use them together?
If (!) it's not possible, is there any other bar I could use that incorparates some of the Polybar features (module-based output separation, individual module update times, underlines and overlines) that _does_ work with Sway?

**Comment by SirCmpwn** [comment]
This sort of thing is something I would like to support post-wlroots, but until then you're just going to have to sit tight.

**Comment by rvc-2011** [comment]
i could get polybar work with this workaround [though not sure if its the right way]
sway config [bar portion]
#
# Setting up polybar(s)
#
bar {
    position top
i3bar_command i3bar -t
#        status_command swaybar -s 'sh $HOME/.config/polybar/swaybar'
#       tray_output primary
#       height 24
    colors {
        statusline #ffffff00
        background #2c2b2a00
        focused_workspace  #b6a8a800 #3c3b3700 #b6a8a800
                active_workspace   #3c3b379900 #b6a8a800 #3c3b3700
                inactive_workspace #3c3b3700 #99999900 #3c3b3700
                urgent_workspace   #90000000 #3c3b3700 #ffffff00
    }
}


bar {
    position bottom
i3bar_command i3bar -t
#        status_command swaybar -s 'sh $HOME/.config/polybar/swaybar'
#       tray_output primary
#       height 24
    colors {
        statusline #ffffff00
        background #2c2b2a00
        focused_workspace  #b6a8a800 #3c3b3700 #b6a8a800
                active_workspace   #3c3b379900 #b6a8a800 #3c3b3700
                inactive_workspace #3c3b3700 #99999900 #3c3b3700
                urgent_workspace   #90000000 #3c3b3700 #ffffff00
  }
}

then in autostart programs i defined two bars [top and bottom]

now the issue is bar does not display workspaces, xbacklight and window title... ! any help ?

**Comment by codethief** [comment]
@rvc-2011 I don't think this is what OP meant by "polybar". See https://github.com/jaagr/polybar .

**Comment by AravK** [comment]
@codethief , you are correct. @rvc-2011 , I'm talking about https://github.com/jaagr/polybar.

**Comment by rvc-2011** [comment]
@AravK , @codethief 
perhaps this [https://forum.manjaro.org/t/joyous-january-2018-screenshots/37440/127?u=rvc]
will show what you meant ? it is polybar(s) with workspaces displayed.

**Comment by AravK** [comment]
@rvc-2011 AFAIK Polybar can't split into pieces like in your link. Please don't tell me what I'm saying. Polybar is an **application**. The configuration in sway.conf is for swaybar, but that's not the same as polybar. What you're talking about is something different. Please show me some configuration for your "polybar" so I can tell you what I'm talking about.

**Comment by 4e554c4c** [comment]
Requesting thread lock. We should reopen this after wlroots, but I don't see any productive discussion coming out of it until then.
