### ISSUE TITLE
[Feature request] Possibility to clone/pin a workspace to more than one output

### ISSUE THREAD

**Issue by rkintzi** [swaywm/sway#1405]
I wonder if it is (or will be) possible to pin workspace (or at least window/container) to more than one output. 

Here is a use case:

As a presenter I want a slideshow to be displayed on a huge screen, and my notes only on my laptop screen. The presentation software I use is able to split those two views into two windows so I can move them to two different workspaces and then pin each of the workspaces to the different outputs (which are configured one above the other). So far so good. But I sometimes want to intermix slideshow with a live-coding session. My editor is unable to do the same thing my presentation software do, so I need a way to clone editor window (or even better the whole workspace) two to different screens. For now, it is only possible when screens are configurated to clone each other (but this makes troubles with the slideshow session when I don't want to share my notes).

PS. Thanks a lot for all the great work. I have already switched from i3 to 'sway' on my workstation at home and,  someday, will do the same at the office.

**Comment by SirCmpwn** [comment]
Seems like a good idea but will be complicated, especially if the two outputs have different resolutions. Should be possible after wlroots.

**Comment by SirCmpwn** [comment]
#1666
