### ISSUE TITLE
FreeBSD: tty permission issues

### ISSUE THREAD

**Issue by johalun** [swaywm/sway#1406]
Hi

Something has to be done regarding tty permission. Even with suid root sway does not have permission to access ttys so I assume that privileges are dropped before setting up the tty. The current fix is to chmod 660 /dev/tty* (with user in wheel group) but that's not a feasible solution.  

Weston has  a launch utility, weston-launch that runs with suid root, sets up all tty/drm stuff and then executes the compositor with dropped privileges. Maybe we have to do something similar? Or can the sway binary do this before dropping privileges?

**Comment by SirCmpwn** [comment]
>Or can the sway binary do this before dropping privileges?

Yes
