### ISSUE TITLE
sway-0.14: cannot switch workspace during app notifications

### ISSUE THREAD

**Issue by jalbstmeijer** [swaywm/sway#1407]
Using sway-0.14 on Fedora 26.

While Thunderbird  notifies on new mail of chat messages, I cannot switch workspace as long the notification has not faded or clicked away.

**Comment by Laaas** [comment]
This is true of firefox's notifications too.
Web page to demonstrate: https://drive.google.com/file/d/0By2m7AMQwLo8N3IxbFBwc2RlcUE/view?usp=sharing

**Comment by SirCmpwn** [comment]
#646
