### ISSUE TITLE
High cpu usage when using multiple monitors

### ISSUE THREAD

**Issue by ponkyh** [swaywm/sway#1408]
I get around 25% cpu usage just from sway process when an external monitor is plugged in to laptop with i7-7600U cpu. Drops to <1% instantly after unplugging the monitor.

sway version 0.15-rc1-16-g67f9b7f (2017-10-16, branch "HEAD")

wlc issue maybe?

**Comment by SirCmpwn** [comment]
https://github.com/SirCmpwn/sway/wiki#how-do-i-report-issues

**Comment by ponkyh** [comment]
Sorry.

I couldn't reproduce the problem until I started telegram. Seems to work with 1 monitor though. Might not be related to sway afterall?

https://gist.github.com/ponkyh/f677368540bda57f12b23e36cdc4a098

**Comment by SirCmpwn** [comment]
Telegram is a godawful electron driven waste of electricity. Not our fault.
