### ISSUE TITLE
sway-0.14: Thunderbird account settings window opens like a post stamp

### ISSUE THREAD

**Issue by jalbstmeijer** [swaywm/sway#1409]
Hi,

Using sway-0.14 on Fedora 26 and Thunderbird 52.3.
When opening the account settings, a very small border less window is opened.
I need to make it full screen to be able to do anything with it.

Gr, J

![output](https://user-images.githubusercontent.com/362000/31616382-dfe96166-b28c-11e7-82f5-7d9adf64becb.png)
![output2](https://user-images.githubusercontent.com/362000/31616396-e75c8662-b28c-11e7-9c0e-668aff21ca78.png)

**Comment by SirCmpwn** [comment]
#731

**Comment by SirCmpwn** [comment]
Please search the bug tracker before filing any more bugs.
