### ISSUE TITLE
sway-0.14: Teminator right mouse menu does not react to mouse pointer

### ISSUE THREAD

**Issue by jalbstmeijer** [swaywm/sway#1410]
Hi,

Using sway-0.14 on Fedora 26 with Terminator 1.91

When accessing the Terminator menu by clicking the right mouse button, the menu itself does not respond to the mouse pointer.

Using the keyboard arrow keys and enter works.

Also hovering the mouse pointer a few times horizontally over the menu can get the mouse pointer to start working  on the menu it self.

Gr, J

**Comment by SirCmpwn** [comment]
Dude read the existing issues first https://github.com/swaywm/sway/issues/1062
