### ISSUE TITLE
Can't start sway without Xwayland

### ISSUE THREAD

**Issue by johalun** [swaywm/sway#1411]
Is Xwayland a hard dependency? I get the error 
"swaybg requires the compositor to support the desktop-shell extension" 

Sounds weird that Xwayland should be required... Maybe something wrong in my config?

**Comment by SirCmpwn** [comment]
That has nothing to do with Xwayland. Full debug log, please.

**Comment by johalun** [comment]
Oh this is interesting.. Setting WLC_XWAYLAND=0 and it works. I can even launch programs like terminal with $mod+enter.
Xwayland is a bit flaky on freebsd. Might be it causing problems. 
https://pastebin.com/KSRygZGR

**Comment by johalun** [comment]
Xwayland stays on 50% cpu usage so something is wrong. Probably nothing to do with wlc/sway.

**Comment by johalun** [comment]
Is Xwayland working on Linux properly?

**Comment by SirCmpwn** [comment]
Of course.

**Comment by SirCmpwn** [comment]
What's happening here is Sway is crashing and dying before swaybg gets up. The error is misleading.

**Comment by johalun** [comment]
Most likely Xwayland issue on FreeBSD.
