### ISSUE TITLE
Double mouse pointer on fullscreen game

### ISSUE THREAD

**Issue by ranisalt** [swaywm/sway#1413]
I'm trying to play Euro Truck Simulator 2 from Steam on sway 0.14.0 (package from Arch Linux). The game draws its own pointer and conflicts with sway/wayland (henceforth way) pointer. Both are on distinct positions and the game's warp wildly, it's not even a scaled movement of way's pointer.

On the following screenshot, the game renders it's own pointer. way's pointer was near the top left border at the same time.
![2017-10-18-020045_swaygrab](https://user-images.githubusercontent.com/1993083/31701005-b99cabb8-b3bc-11e7-9a22-da845cb3a1f2.png)

It makes it impossible to control the game since only the game pointer works, while my mouse controls only way's pointer.

I thought the way wayland works would give control of the screen and input to the game instead of handling it in the wm/compositor, but it seems something is getting in between.

**Comment by SirCmpwn** [comment]
This will be addressed when wlroots is complete.

**Comment by ranisalt** [comment]
Thanks

**Comment by PeaceAlways** [comment]
I am playing DotA 2. And that just works fine without this kind of issue...

**Comment by cafehaine** [comment]
It's because dota doesn't implement it's own cursor system, simply skins the system one.
(you can see this by hitting the super key on windoz, the cursor won't move)
(Yeah I know It's a really wanky way of explaining it.)

**Comment by marchm3** [comment]
I have double pointer on assault cube and when i move system pointer, game pointer follow slower than system pointer. I use sway 0.15.0

**Comment by cafehaine** [comment]
As said previously, see #1390
