### ISSUE TITLE
swaybar can not find fcitx default tray icon 'input-keyboard'

### ISSUE THREAD

**Issue by cjacker** [swaywm/sway#1414]
fcitx input method use a non-standard tray icon 'input-keyboard' by default, that not provided in 'hicolor' icon theme.

swaybar default icon_theme configuration set to NULL in config.c and find_all_theme_dirs will fallback to 'hicolor'.

This is a issue of fcitx indeed, using a non-standard icon depend on some icon themes, but very hard to find the root cause for common users.

the solution is easy, add 'icon_theme Adwaita' to sway config 'bar' section.

Is there any possible adding more fallbacks to find_all_theme_dirs in icon.c, such as 'Adwaita', 'Oxygen'?

**Comment by SirCmpwn** [comment]
This is the first I've heard of it, so it's evidently not a major issue for users.

**Comment by blackmirroxx** [comment]
I do have the same problem as cjacker

**Comment by gebner** [comment]
@cjacker Thank you for the workaround!
