### ISSUE TITLE
[Feature request] provide a wrapper script to startup sway

### ISSUE THREAD

**Issue by cjacker** [swaywm/sway#1415]
Before launch a DE, a lot of ENV need to be setted up properly, Such as IM_MODULE etc, especially "DBUS_SESSION_BUS_ADDRESS" (tray of swaybar also need it).

Dists. usually use xinitrc.d to setup these stuff, if launching sway from a DM, such as sddm/gdm, all ENV will be ready.  but if launching sway directly from console, what DM did will be skipped.

At least , "DBUS_SESSION_BUS_ADDRESS" should be setted up properly.

for example, the 'startsway' script I used:

#!/bin/sh
#Some gtk app not wayland ready.
export GDK_BACKEND=x11

#setup input method.
. /etc/X11/xinit/xinputrc
[ -n "$GTK_IM_MODULE" ] && export GTK_IM_MODULE
[ -n "$QT_IM_MODULE" ] && export QT_IM_MODULE
[ -z "$XMODIFIERS" -a -n "$XIM" ] && XMODIFIERS="@im=$XIM"
[ -n "$XMODIFIERS" ] && export XMODIFIERS
#After sway startup, 'exec' in sway config.
[ -n "$XIM_PROGRAM" ] && export XIM_PROGRAM
[ -n "$XIM_ARGS" ] && export XIM_ARGS

#setup DBUS_SESSION_BUS_ADDRESS env.
if [ -n "$DBUS_SESSION_BUS_ADDRESS" ]; then
export DBUS_SESSION_BUS_ADDRESS
eval `sway 2>~/.swaysession-errors`
else
eval `dbus-launch --exit-with-session sway 2>~/.swaysession-errors`
fi

After sway startup, there are also some apps need autostart, such as input method, polkit agent, notification deamon etc.  it's can be done via 'exec' command in sway config.

**Comment by 4e554c4c** [comment]
If it's possible with a script/exec I see no reason for this to be sway's job. Each user's environment is different and I doubt any startup script could work for everyone. Especially things like dbus, because it isn't a hard dependency, and only used in one program.

**Comment by cjacker** [comment]
It's ok for me.

README.md said "Run sway from a TTY. Some display managers may work but are not supported by Sway (gdm is known to work fairly well)."

For non-gdm user, the tray will not work without a session bus, better to metion it in README.md.
