### ISSUE TITLE
Running sway alongside Gnome in a different tty

### ISSUE THREAD

**Issue by deepakjois** [swaywm/sway#1416]
I am not sure if this belongs here, but hoping people point me in the right direction if I have to pursue this elsewhere.

I would like to run sway alongside Gnome, in a different tty. I have Gnome 3.26 running on Wayland, launched via GDM on tty2 (I am using Arch Linux fwiw). The Gnome session is running some apps like `tilix` and `gnome-terminal`. I do the following:

* Press Ctrl-Alt-F3 (switching to tty3, the lowest free tty)
* Login as the same user running the Gnome session
* Launch `sway`
* Launch `urxvt` and try to launch `tilix` or `gnome-terminal`.

This has some weird side effects. The apps launch inside Gnome, even when I run them in Sway.

I checked the WAYLAND_DISPLAY variable, and note that it is set to `wayland-0`. I am not sure whether this is expected behavior. Can’t sway create a _new_ Wayland server (`wayland-1` or something)? Will that make this problem go away?

UPDATE: I also tried something like this
```
export WAYLAND_DISPLAY=wayland-1
sway
```
It launches sway just fine, but the display is still set to `wayland-0`. Weston on the other hand crashes:

```
$ weston
Date: 2017-10-20 IST
[15:30:09.457] weston 3.0.0
               http://wayland.freedesktop.org
               Bug reports to: https://bugs.freedesktop.org/enter_bug.cgi?product=Wayland&component=weston&version=3.0.0
               Build: unknown (not built from git or tarball)
[15:30:09.457] Command line: weston
[15:30:09.457] OS: Linux, 4.13.7-1-ARCH, #1 SMP PREEMPT Sat Oct 14 20:13:26 CEST 2017, x86_64
[15:30:09.457] Starting with no config file.
[15:30:09.457] Output repaint window is 7 ms maximum.
[15:30:09.457] Loading module '/usr/lib/libweston-3/wayland-backend.so'
[15:30:09.460] failed to create display: No such file or directory
[15:30:09.460] fatal: failed to create compositor backend
```

**Comment by SirCmpwn** [comment]
This is not a use case we support. Pick one or the other.

**Comment by deepakjois** [comment]
Ok, but may I ask why? Is this too difficult to support? Could you tell me what is involved in enabling such a use case?

**Comment by SirCmpwn** [comment]
You can debug it and investigate it yourself. But it's not something that impacts day-to-day users at all, so I don't care to waste time on it.

**Comment by deepakjois** [comment]
Sorry if it sounded like I was asking you to debug and investigate. I wasn’t, and it is fine if you don’t want to pursue this. I actually looked at the Wayland API docs and even searched the Wayland mailing list before I filed the issue and did not really get any definitive answers about running multiple Wayland sessions as a single user.

I was just looking to better understand what exactly is happening here. If that is not an appropriate question here, I apologise.

**Comment by waltervargas** [comment]
Perhaps you can try to run it as a different user. There are many things happening that authorize as the user running the session, one example is DBUS.

**Comment by waltervargas** [comment]
> Perhaps you can try to run it as a different user. There are many things happening that authorize as the user running the session, one example is DBUS.

Usually what I do is that I add another user like `walter2`, and then in the tty2: 

```
dbus-run-session -- gnome-shell --display-server --wayland
```

in tty1 I am basically running `sway`.
