### ISSUE TITLE
Spanish README translation is missing

### ISSUE THREAD

**Issue by tonyskapunk** [swaywm/sway#1417]
Currently broken link: https://github.com/swaywm/sway/blob/master/README.es.md#sway--

**Comment by tonyskapunk** [comment]
Any particular reason why not to provide Spanish translation? I can write that ;)

**Comment by SirCmpwn** [comment]
Nope, feel free to write one.

**Comment by tonyskapunk** [comment]
OK, will do, PR soon.  Thanks1
