### ISSUE TITLE
swaylock: support blur & clock like i3lock-color

### ISSUE THREAD

**Issue by 2Belette** [swaywm/sway#1420]
Would be nice to support two nice functionalities from [i3lock-color](https://github.com/chrjguill/i3lock-color):

-one is to be able to blur the current screen instead of using an image or a color; on this one i3lock-color recently changed the way they achieve it with a very quick rendering.

-another is to be able to display clock inside the ring 

Here a screenshot from there github:
![screenshot](https://user-images.githubusercontent.com/2325706/31850225-d0deb39a-b64e-11e7-96db-88328ac62a4a.png)

**Comment by cafehaine** [comment]
The blur effect can be done using swaygrab and imagemagick, so no need for that

**Comment by 2Belette** [comment]
thanks! any idea on how I could set swaylock to use them?

**Comment by cafehaine** [comment]
create a script that is called before swaylock, in which you call swaygrab, and output it's result in a file, then blur the file using imagemagick, [see here on how to do it](https://stackoverflow.com/questions/331254/how-to-pixelate-blur-an-image-using-imagemagick) .
Might not be the most efficient way of doing it but it's not that bad

**Comment by 2Belette** [comment]
that's a good tips! I just did it and it works :)

The only downside is that it is laggy (like the first version i3lock-color used in the past) this is the reason their [new approach](https://github.com/chrjguill/i3lock-color/pull/17) seems better

**Comment by SirCmpwn** [comment]
These features are better offered by a third party program than by swaylock upstream.

**Comment by ambiso** [comment]
@ddevault Could elaborate on how third party programs can achieve the same functionality (and speed) as i3lock?

**Comment by Emantor** [comment]
Fork swaylock and implement the features you want in your swaylock fork.

**Comment by JAicewizard** [comment]
keeping it in the official swaylock seems better, people look at sway as a drop-in replacement with most features of i3, they will do the same with i3-lock. People don't like having to go through 10 forks of sway to get most features they want.

**Comment by johnae** [comment]
Granted, I have a bit of a custom setup, but maybe people can use my fast blur tool which I use myself with swaylock: https://github.com/johnae/blur.

**Comment by JAicewizard** [comment]
can I get a reason why it is marked off-topic? It is purely about this topic, supporting a blur, I am not ranting or spamming leaving unhelpful messages.
