### ISSUE TITLE
swaygrab: support region selection

### ISSUE THREAD

**Issue by 2Belette** [swaywm/sway#1421]
swaygrab is working nicely but it would be nice to be able to select a window or a region with the mouse instead of taking the full screen for producing the screenshot (like [maim/slop](https://github.com/naelstrof/maim))

**Comment by cauebs** [comment]
Adding a parameter for the coordinates is already enough, then we can leave the rest of the work for slop.

**Comment by ranisalt** [comment]
I will try 😄

**Comment by SirCmpwn** [comment]
swaygrab is deprecated, through the combination of grim and slurp on sway 1.0 you can achive this functionality.

**Comment by manio** [comment]
@SirCmpwn 
If it's removed from the git and deprecated then maybe can you please update the wiki?
https://github.com/swaywm/sway/wiki#taking-screenshots

Thanks in advance! :)

**Comment by RyanDwyer** [comment]
The wiki shouldn't be updated until 1.0 is released. The content is still relevant for sway 0.15 which is the latest release.
