### ISSUE TITLE
keyboard ALT GR key doesn't work.

### ISSUE THREAD

**Issue by p3aceDC2298** [swaywm/sway#1422]
hi there i am using arch linux and i have some trouble with my keyboard only on sway , because with gnome 3.26 it works fine , but during the sway session the keyboard switch to us layout, and i want the italian -layout , so i followed the sway wiki and i created a script who start automaticaly with gdm 
on </etc/gdm/PostLogin/lang.sh> 
`export XKB_DEFAULT_LAYOUT=it`
but unfortunatley it doesn't work , then i followed the arch wiki and i created another script 
here </usr/bin/sway-iy>
`#!/bin/sh
XKB_DEFAULT_LAYOUT=it`
and then i created another sway session
here </usr/share/wayland-sessions/sway-it>
`export XKB_DEFAULT_LAYOUT=it `

 but unfortunatly nothing of this works , my keyboard was alwas with us -layout, and the only way to change it was with this command
`setxkbmap it`
this command works perfectly, the only problem is that the ALTGR key wont work....
and the strange think happened when i tried to open the plasma settings center (from my sway session) and i tried to write something on the filter fields and there my alt gr keys works fine but with any other program (browser terminal etc...) my Alt gr key wont work..... 
any suggestion???? and sorry for my poor english :)

**Comment by SirCmpwn** [comment]
I'm closing issues that are resolved by the yet-unreleased sway 1.0.
