### ISSUE TITLE
Any plan to support the XDG Desktop Application Autostart Specification?

### ISSUE THREAD

**Issue by vially** [swaywm/sway#1423]
Is there any plan to support the XDG [Desktop Application Autostart Specification](https://standards.freedesktop.org/autostart-spec/autostart-spec-latest.html)?

I'm particularly interested in auto-starting applications during startup which I think makes sense in the context of a wayland compositor. Because the spec also mentions auto-starting applications after media mounts which might fall outside the scope of this project.

i3 doesn't currently support this and I know you can work around this problem by manually adding `exec` lines to the config file. But I think implementing this in sway in a desktop agnostic way would be very useful.

PS: I'm not asking for the project maintainers to implement it. I would just like to know if they would be interested to merge this if someone were to implement it?

**Comment by SirCmpwn** [comment]
I don't want to implement this or see it implemented.

**Comment by felipec** [comment]
> I don't want to implement this or see it implemented.

Why?

I just switched from Xfce and started wondering why it wasn't working. Took me a while to find out it was the session the one with the responsibility, and sway is dropping the ball on that standard.

**Comment by andersnylander** [comment]
swaywm is not a desktop environment. It's a window manager. autostarting applications, and the methodology for how it happens, it's DE territory, which you as the user of sway is supposed to implement and customize as you see fit. If you want the support for XDG autostart feature however, it should be pretty trivial to create a script that does the necessary work for you and then call on that script from sways config.

**Comment by progandy** [comment]
There are already tools to do that, one is mentioned in the [Startup](https://github.com/swaywm/sway/wiki/Startup-(process-manager)-Integration) wiki page
https://github.com/jceb/dex
