### ISSUE TITLE
Compton features?

### ISSUE THREAD

**Issue by that1communist** [swaywm/sway#1426]
Since a separate compositor isn't possible on Wayland, and Compton is the most common (if not only?) I3 compositor, is there any plans to add Compton features?

I don't see it listed anywhere if it is part of the plan. If not, it really should be.

**Comment by 4e554c4c** [comment]
What compton features?

**Comment by that1communist** [comment]
Shadow configuration, fading, opacity of unfocused windows, there's actually a lot.
