### ISSUE TITLE
wish: document equivalent to `i3-nagbar`

### ISSUE THREAD

**Issue by markstos** [swaywm/sway#1432]
This would be useful to mention in the "i3 Migration guide".   I tested "i3-nagbar" and see it still works to display a window in `sway`, so continuing to use it also appears to be an option.

**Comment by SirCmpwn** [comment]
The thing about a wiki is, anyone can edit it!

**Comment by markstos** [comment]
Sure, but only the people who know the answers can *usefully* edit it. I don't know if there is a replacement for i3-nagbar or not, which is why I opened the issue here. I expect someone monitoring the issue tracker knows the answer.

**Comment by SirCmpwn** [comment]
There's not. If it works for you, go ahead. People do watch the wiki for changes so erroneous ones will be addressed.

**Comment by markstos** [comment]
Thanks for the clarification-- now I can update the wiki. ;)
