### ISSUE TITLE
Unresponsive after fresh build on Ubuntu

### ISSUE THREAD

**Issue by pcewing** [swaywm/sway#1433]
This could possibly be a duplicate of [issue #870](https://github.com/swaywm/sway/issues/870)

I recently put together some scripts to build/install both Wlc and Sway on a fresh Ubuntu 17.10 server installation. For reference, they can be found in this repo: https://github.com/pcewing/sway-ubuntu

Both wlc and sway seem to build and install successfully; however, upon running sway I get a black screen with the cursor stuck in the top left corner. I'm able to kill the session by pressing `mod+shift+e` twice.

The output of `sway -dV` is here:
https://gist.github.com/pcewing/1c0038381024b4b7c0ff315de685f2a0

Not sure if it is relevant but I'm experiencing this issue on a VirtualBox VM; I haven't tried this on a physical machine yet.

**Comment by SirCmpwn** [comment]
VirtualBox is not supported.

**Comment by pcewing** [comment]
Ah sorry. I did not know that!

**Comment by ranisalt** [comment]
Is it sway, wlc or wayland's fault?

**Comment by 4e554c4c** [comment]
VirtualBox's
