### ISSUE TITLE
RDP Multimonitor xfreerdp

### ISSUE THREAD

**Issue by kjwinchester** [swaywm/sway#1442]
In X11 window managers, I can run xfreerdp in multimon mode and have my RDP session spread across both of my screens, but in sway it restricts itself to one screen.

Is there anything that can be done about that?

**Comment by SirCmpwn** [comment]
This will be addressed when [wlroots](https://github.com/swaywm/wlroots) is completed and [integrated with sway](https://github.com/swaywm/sway/issues/1390).

**Comment by mox-mox** [comment]
Has this been addressed yet? Are there some steps I'll need to take to make it work for me?
When I try  `xfreerdp +fonts /monitors:1,0 /multimon /dynamic-resolution /u:$USERNAME /v:$HOST /p:$PW` I still get only one window...

**Comment by mox-mox** [comment]
Ok, so there is a tool called 'wlfreerdp', the wayland version of freerdp. Kind of obvious if I think about it. Still 'wlfreerdp +fonts /monitors:1,0 /multimon /dynamic-resolution /u:$USERNAME /v:$HOST /p:$PW' also left me with one screen :/
(And yes, I do have two physical screens configured and working.)

**Comment by progandy** [comment]
* no idea why ```xfreerdp``` wouldn't work. ```xrandr -q``` and ```xfreerdp /monitor-list``` might shed some light for you. Maybe all windows are opened on the same display (```swaymsg -t get_tree
```). If so then try to rearrange them.
* ```wlfreerdp``` does [not support](https://github.com/FreeRDP/FreeRDP/blob/701770c69a8d27440de1aad9233af69b3d7ba101/client/Wayland/wlf_disp.c#L111) multimonitor yet. (This is not a sway bug)
* you are sure that your rdp server supports multiple monitors? (not a sway bug)

**Comment by mox-mox** [comment]
> wlfreerdp does not support multimonitor yet. (This is not a sway bug)

That was a good hint.
For some reason, when I re-tried xfreerdp it worked for me.  THANK YOU very much!
It's great to see sway getting ever better and even surpassing i3.

So for future readers:
I can confirm multi-monitor support for xfreerdp works under sway. My config (relevant parts):
`.config/sway/config`:
```
output eDP-1 resolution 1600x900
output HDMI-A-1 enable  mode --custom 1920x1080
```
`xrandr -q`:
```
Screen 0: minimum 16 x 16, current 3520 x 1080, maximum 32767 x 32767
XWAYLAND0 connected 1600x900+1920+0 (normal left inverted right x axis y axis) 310mm x 170mm
   1600x900      59.95*+
XWAYLAND1 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 630mm x 360mm
   1920x1080     59.88*+
```
`xfreerdp /monitor-list`:
```
        [0] 1600x900	+1920+0
        [1] 1920x1080	+0+0
```

And my command to start the remote session:
```
xfreerdp +fonts /monitors:1,0 /multimon:force /dynamic-resolution /u:$USERNAME /v:$IP:$PORT /p:"$PASSWORD"
```

This will start the RDP session with the main Windows window on the bigger screen (swap the `/monitors:1,0` part to change that).
