### ISSUE TITLE
No keyboard input to rofi in empty workspace

### ISSUE THREAD

**Issue by Raumzeitkeks** [swaywm/sway#1444]
I experience an issue with **rofi version 1.4.2** on **sway version 0.14.0** under ArchLinux. I have _not_ tested this with the experimantal wayland version of rofi. The problem does _not_ occur with dmenu version 4.7.

When I invoke rofi on an empty workspace (as would be the case after startup or after switching to a new workspace) then the rofi window does not react to any keyboard input. As soon as I move the mouse over the window it starts working, although I set ```focus_follows_mouse no```. Even if the mouse already is over the window when invoking rofi, it is necessary to slightly move the mouse or click onto the window to get it working.
Another way to fix it, is to open a terminal emulator underneath or switch to a another workspace containing something. (This of course needs to be done through keybindings, as rofi would otherwise close.) Rofi then immedialty becomes responsive.
The same is true if I launch rofi on a populated workspace, but then a switch to an empty workspace. This can even go back an forth: While on an occupied workspace input works; after switching to an empty one it stops; when going back to a populated one it works again.

**Comment by SirCmpwn** [comment]
https://github.com/swaywm/sway/issues/267
