### ISSUE TITLE
[Feature Request] Output mirroring

### ISSUE THREAD

**Issue by cauebs** [swaywm/sway#1447]
There is already a request for showing one workspace on multiple outputs (#1405), but I feel the ability to mirror outputs completely would be useful as well. What are your thoughts on this?

**Comment by SirCmpwn** [comment]
This will be addressed when [wlroots](https://github.com/swaywm/wlroots) is completed and [integrated with sway](https://github.com/swaywm/sway/issues/1390).

**Comment by dvc94ch** [comment]
Does this work now? I tried
```
output eDP-1 pos 0 0
output DP-1 pos 0 0
```
but that only mirrors the cursor not the workspace.

**Comment by emersion** [comment]
See https://github.com/swaywm/sway/issues/1666
