### ISSUE TITLE
Secondary screen not locked after detaching/attaching screen

### ISSUE THREAD

**Issue by morganhein** [swaywm/sway#1448]
I use a laptop and fairly regularly dock to a monitor. If I lock my screen using swaylock, then plug in my secondary monitor, the secondary monitor is not blanked out.

You cannot move the context to the secondary monitor, but it does display the swaybar and background.

**Comment by SirCmpwn** [comment]
I'm closing issues that are resolved by the yet-unreleased sway 1.0.
