### ISSUE TITLE
.

### ISSUE THREAD

**Issue by gnidorah** [swaywm/sway#1450]

**Comment by SirCmpwn** [comment]
Don't obsfucate issues when you close them. What was this about?

**Comment by gnidorah** [comment]
@SirCmpwn Sorry, pal. Let me reformulate that.

**Comment by gnidorah** [comment]
@SirCmpwn Ok, I've tracked the issue and described it and proposed a solution for distro maintainers. I believe though that only NixOS currently does wrapping. Sorry for the noise.

**Comment by SirCmpwn** [comment]
Yes, this is indeed a downstream issue.
