### ISSUE TITLE
xkb layouts: ISO_LevelN_Latch not working correctly

### ISSUE THREAD

**Issue by janpath** [swaywm/sway#1451]
In xkb keyboard layouts there are three type of modifiers `ISO_Level<N>_<Method>`, where \<N> ∈ {3,5} and \<Method> ∈ {Shift, Latch, Lock}. Shift and Lock are supposed to work like shift and capslock and work fine in sway. Latch should behave as a modifier to the next key you type (after you released the modifier). But instead in sway it behaves identical to Shift.

## How to reproduce:

1. Copy [this keyboard layout](https://gist.github.com/janpath/2aedc2864c945d954b4333bc52a6ef50) to `/usr/share/X11/xkb/symbols/latch_test`. This is just the latin keyboard layout with capslock mapped to `ISO_Level3_Latch`.
2. Start sway with this keyboard layout: `XKB_DEFAULT_LAYOUT=latch_test sway`.
3. Go somewhere you can input text, press and release _capslock_, then type _q_.

### Expected result:

This should result in an '@', just as in xorg.

### Actual result:

This results in a 'q'. If you were to hold _capslock_ while pressing _q_, it actually does type an '@', so it behaves like `ISO_Level3_Shift`.

## Version

```
$ pacman -Q sway wayland wlc libinput libxkbcommon
sway 0.14.0-1
wayland 1.14.0-1
wlc 0.0.10-1
libinput 1.9.1-1
libxkbcommon 0.7.2-1
```

**Comment by SirCmpwn** [comment]
I'm closing issues that are resolved by the yet-unreleased sway 1.0.
