### ISSUE TITLE
Sway freezes when the lid is closed for ~5 seconds and then reopened 70% of the time

### ISSUE THREAD

**Issue by moonheart08** [swaywm/sway#1452]
I dunno if you all can reproduce it, but i can. I tried to make a debug log of a reproduction of the issue, but sway doesn't like the idea of having its output redirected to a file.

Basically, it freezes up entirely. I cant even switch TTYs. Shutdown (via a power button press) works normally, but that's systemd-logind's job, so not surprising. Only way out i know of is a full reboot.

**Comment by 4e554c4c** [comment]
>sway doesn't like the idea of having its output redirected to a file

There should be no problem with this, it is very common to do. Also without a log we can't really help you out. Perhaps state why you can't create a debug log.

**Comment by moonheart08** [comment]
I've been trying to redirect sway's output via '>', but im suprisingly incompetent with a terminal. IF someone can point me in the right direction, i'll do it.

**Comment by Timidger** [comment]
@moonheart08 Try using `&>` to capture all output (from both stderr and stdout). AFAIK Sway outputs to stderr (so `2>` will work too)

**Comment by 4e554c4c** [comment]
@Timidger yep it outputs to stderr, `sway -d 2> sway.log` should do the trick

**Comment by SirCmpwn** [comment]
I'm closing issues that are resolved by the yet-unreleased sway 1.0.
