### ISSUE TITLE
Crash on Reload After Disabling Output

### ISSUE THREAD

**Issue by reedjosh** [swaywm/sway#1453]
First time posting an issue for anything. I'll do my best to help, but bear with me as I'm kinda newbish.

To begin, the use case is that I load sway, then I close my laptop lid. To do so I attempt to turn off the display. Later, I try to reload sway and it crashes.

Here are the commands I'm using:
Start sway from tty: `sway 2> ~/.swaylog`
Eventually disable laptop display: `swaymsg output eDP-1 disable`
mod+shift+c: reload sway and cause a crash.

Here's the contents of the `.swaylog` file for that session.

> 11/03/17 14:22:03 - 11/03/17 14:22:03 - [main.c:69] [main.c:69] Using output 0 of 2Using output 1 of 2
> 
> 11/03/17 14:22:18 - [main.c:69] Using output 0 of 2
> 11/03/17 14:22:18 - [debug_log.c:88] swayc_log:swayc_log: no container ...
> Gdk-Message: Error reading events from display: Broken pipe
> 11/03/17 14:22:18 - [ipc-client.c:50] Unable to receive IPC response

I'm using Arch Linux, and sway version 0.14.0-1.

Here's my config: [https://gist.github.com/reedjosh/02192841820b18a84f6d0a07b310011d](url)

In it I set the displays as:
`output eDP-1 resolution 1920x1080 scale 1`
`output DP-1 resolution 3840x2160 scale 1`

This seems to be an issue such that sway thinks the display should be there and it's not. Maybe my method isn't supported, and if so, how should I go about laptop lid events and display disabling/enabling?

Thank you for your support and the great WM you provide!

**Comment by SirCmpwn** [comment]
I'm closing issues that are resolved by the yet-unreleased sway 1.0.
