### ISSUE TITLE
Mouse cursor disappears when using qt applications. 

### ISSUE THREAD

**Issue by protelescristata** [swaywm/sway#1458]
The cursor disappears while hovering over some elements in rstudio and virtualbox. 
This problem doesn't seem to affect gtk applications.
Thanks for the great work!

**Comment by SirCmpwn** [comment]
This will be addressed when [wlroots](https://github.com/swaywm/wlroots) is completed and [integrated with sway](https://github.com/swaywm/sway/issues/1390).
