### ISSUE TITLE
Swaybar (i3status) not displaying (version 0.14.0)

### ISSUE THREAD

**Issue by soleera** [swaywm/sway#1459]
I have been using sway on and off for a little while, so this may just be a case of an outdated configuration, but for some reason when starting up a sway session swaybar does not appear. Any ideas you might have about what's going on would be much appreciated!

[sway.log](https://github.com/swaywm/sway/files/1457043/sway.log)
[config.txt](https://github.com/swaywm/sway/files/1457049/config.txt)

**Comment by SirCmpwn** [comment]
Can you run `swaybar -b bar-0 -d` and let me know how that goes?

**Comment by soleera** [comment]
Yep, that worked; swaybar displays with window buttons, i3status, and uses the config file successfully (font, colours,  etc.). Here's a gist of the debugging messages:
[https://gist.github.com/soleera/c30974d6e924fb4885cba9d5fd613b6b#file-swaybar-log](url)

**Comment by SirCmpwn** [comment]
404

**Comment by 4e554c4c** [comment]
That's weird, it shouldn't be any different if started from the command line.

**Comment by 4e554c4c** [comment]
`0.14` is outdated. In that version swaybar will crash if it can't get a D-Bus connection when started. Either start D-Bus before starting swaybar or upgrade to `0.15`.

**Comment by soleera** [comment]
0.15.0 just got added to my distribution's repo a couple of days ago (gentoo), so I've updated to that and don't have any more issues with swaybar. Not quite sure why swaybar wouldn't be able to get a connection to dbus though since I start dbus at boot time;
`
root #  rc-update add dbus default
* rc-update: dbus already installed in runlevel `default'; skipping
`
