### ISSUE TITLE
Unable to move workspaces on azerty keyboard layout

### ISSUE THREAD

**Issue by BartWillems** [swaywm/sway#1460]
Hi,

I'm unable to move anything to/from workspaces on azerty using these commands:
`bindsym $mod+1 workspace $ws1`
`bindsym $mod+Shift+1 move container to workspace $ws1`

I believe this is because I already have to hold shift in order to use the numbers on the top row of my keyboard.

**Comment by nlescoua** [comment]
Use the following configuration to circumvent the issue. Note that i3 (contrary to sway) support you specification ($mod+1 ....)

# switch to workspace
bindsym $mod+ampersand workspace 1
bindsym $mod+eacute workspace 2
bindsym $mod+quotedbl workspace 3
bindsym $mod+apostrophe workspace 4
bindsym $mod+parenleft workspace 5
bindsym $mod+egrave workspace 6
bindsym $mod+minus workspace 7
bindsym $mod+underscore workspace 8
bindsym $mod+ccedilla workspace 9
bindsym $mod+agrave workspace 10

# move focused container to workspace
bindsym $mod+Shift+ampersand move container to workspace 1
bindsym $mod+Shift+eacute move container to workspace 2
bindsym $mod+Shift+quotedbl move container to workspace 3
bindsym $mod+Shift+apostrophe move container to workspace 4
bindsym $mod+Shift+parenleft move container to workspace 5
bindsym $mod+Shift+egrave move container to workspace 6
bindsym $mod+Shift+minus move container to workspace 7
bindsym $mod+Shift+underscore move container to workspace 8
bindsym $mod+Shift+ccdedilla move container to workspace 9
bindsym $mod+Shift+agrave move container to workspace 10

**Comment by Alphare** [comment]
> bindsym $mod+Shift+ccdedilla move container to workspace 9

Note: it's ccedilla, like above, else sway will spit out and error.

**Comment by kwmbe** [comment]
For any belgian azerty users:

```
bindsym $mod+ampersand workspace 1
bindsym $mod+eacute workspace 2
bindsym $mod+quotedbl workspace 3
bindsym $mod+apostrophe workspace 4
bindsym $mod+parenleft workspace 5
bindsym $mod+section workspace 6
bindsym $mod+egrave workspace 7
bindsym $mod+exclam workspace 8
bindsym $mod+ccedilla workspace 9
bindsym $mod+agrave workspace 10
```

**Comment by ringo32** [comment]
much easer is like : 
bindcode $mod+10 workspace number 1

you can use this code in azerty or qwerty much easier to switch this way :-)

**Comment by vinthara** [comment]
Digging an old post @nlescoua 
Thanks for the suggestion, do you think there is a remap for the key ² as well.
As in
& -> ampersand
é -> eacute
What about ² ?

**Comment by ringo32** [comment]
> And it seems ² it is named twosuperior.\n

Just with wev find your key code and use bindcide in i3/sway?
