### ISSUE TITLE
wine windows and sway

### ISSUE THREAD

**Issue by alexjp** [swaywm/sway#1462]
Hi,

Thanks for sway.

I am trying/(have to) to use a wine app and everytime I close a window from that same app ( or closing the app itself), i experience a wine hang and error:
```
fixme:event:wait_for_withdrawn_state window 0x1005e/1400004 wait timed out
fixme:event:wait_for_withdrawn_state window 0x10098/1400005 wait timed out
```

I found similar issues in here:
https://github.com/baskerville/bspwm/issues/222 ( was fixed and close )
and
https://github.com/stumpwm/stumpwm/issues/277

Can it be fixed, so that it works properly with sway ?

Thanks !

**Comment by acrisci** [comment]
Fixed in wlroots.
