### ISSUE TITLE
No Monitor Refresh Rate Options

### ISSUE THREAD

**Issue by gstark31897** [swaywm/sway#1464]
I have a 144hz monitor and it currently defaults to 60hz when using sway.

Correct me if I'm wrong, but it doesn't appear that sway has a way to configure refresh rates for monitors.

Typically I'd be able configure this through xrandr, but since sway is wayland based; sway needs to configure it.

This would most likely need to be addressed after the wlroots changes are going, but a config option like this would do the trick:
**output** <name> <refresh_rate|ref> \<Hz>

**Comment by SirCmpwn** [comment]
This will be addressed when [wlroots](https://github.com/swaywm/wlroots) is completed and [integrated with sway](https://github.com/swaywm/sway/issues/1390).

**Comment by deevus** [comment]
But how?

**Comment by progandy** [comment]
man 5 sway-output

https://github.com/swaywm/sway/blob/ea097631af79d49ec7c4f63e9167a52a82444643/sway/sway-output.5.scd#L25

**Comment by deevus** [comment]
I must be running an older version as that man page doesn't exist. 

```
$ sway -v
sway version  (2018-07-26, branch "")```

I'm running Fedora 28 (current release version as of this post). I installed sway using `dnf install sway`

**Comment by deevus** [comment]
```
Name         : sway
Version      : 0.15.2
Release      : 1.fc28
Arch         : x86_64
Size         : 670 k
Source       : sway-0.15.2-1.fc28.src.rpm
Repo         : @System
From repo    : updates
Summary      : i3-compatible window manager for Wayland
URL          : https://github.com/swaywm/sway
License      : MIT
Description  : Sway is a tiling window manager supporting Wayland compositor protocol and
             : i3-compatible configuration.
```
