### ISSUE TITLE
Segfault while copying text from terminal to Firefox

### ISSUE THREAD

**Issue by dmeijboom** [swaywm/sway#1465]
**Steps to reproduce:**

1. Open 'gnome-terminal' on the right
2. Open 'firefox-development' on the left
3. Copy output from terminal using Ctrl-Shift-C
4. Close terminal with Ctrl-D
5. Copy text to firefox in an inputfield with Ctrl+V
6. Segfault..

**Logs from journal:**
```
Nov 15 21:15:15 dmeijboom-linux kernel: sway[1414]: segfault at 0 ip 00007fad65101c19 sp 00007ffec3f6dba0 error 4 in libwayland-server.so.0.1.0[7fad650fb000+10000]

Nov 15 21:15:46 dmeijboom-linux kernel: sway[9905]: segfault at 0 ip 00007f65caefdc19 sp 00007fff8cc01bf0 error 4 in libwayland-server.so.0.1.0[7f65caef7000+10000]
```

**Computer:**
MacBook Pro HiDPI screen.

**Video card(s)**
```
00:02.0 VGA compatible controller: Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09)
01:00.0 VGA compatible controller: NVIDIA Corporation GK107M [GeForce GT 650M Mac Edition] (rev a1)
```

Note that only my intel onboard card is enabled.

If additional information is needed, please let me know. I'm not sure what else to specify.

**Comment by SirCmpwn** [comment]
Thanks for the info, that's helpful - but we could use a little more:

https://github.com/SirCmpwn/sway/wiki#how-do-i-report-issues

**Comment by dmeijboom** [comment]
Thanks! Here is the additional information: https://gist.github.com/dmeijboom/64ff38bff135444731e0bab3cb520ed8

**Comment by SirCmpwn** [comment]
Wait, what segfaults? Sway?

**Comment by dmeijboom** [comment]
I think so because in the logs from journalctl it says "sway [PID]" and I'm returning to my display manager (which is SDDM). I'm not 100% sure though. I will try it again in another application to make sure the segfault is happening in sway and not in Firefox.

**Comment by SirCmpwn** [comment]
See if you can find a core dump for it.

**Comment by dmeijboom** [comment]
Hmm, on second thoughts I think it's Firefox and not sway. I can't find a coredump for Sway but I can find multiple coredumps for Firefox so I think this issue can be closed. Sorry ;)
