### ISSUE TITLE
NumLock switching inconsistent

### ISSUE THREAD

**Issue by wimgoeman** [swaywm/sway#1466]
Hi,

I come from using i3  on Ubuntu 16.04 to sway on Ubuntu 17.10.

After logging in, numlock seems to be disabled in Sway. When I open a gnome-terminal, and press numlock in it, I can use the numpad for numbers in the terminal. But when I open firefox I cant use the numpad, and the numlock key does not change anything. 

I also noticed the keyboard light for numlock does not light up when activating it.

When using a gnome session on wayland I dont have this issue.

Any help appreciated! I'd love to switch to wayland/sway but this is keeping me from it.

Thanks!

**Comment by teiesti** [comment]
This seems to be a dublicate of #1308. The issue should finally vanish when wlc is replaced by wlroots in the upcoming version 1.0.

**Comment by SirCmpwn** [comment]
I'm closing issues that are resolved by the yet-unreleased sway 1.0.
