### ISSUE TITLE
swaymsg works, sway <command> does not

### ISSUE THREAD

**Issue by goose121** [swaywm/sway#1467]
Pretty much the title. The only way that I can communicate with the running sway instance is with `swaymsg <command>` or `i3 <command>`. `sway <command>` gives the error `{ "success": false, "error": "Permission denied" }`, while `i3-msg <command>` gives this slightly more verbose error:
```
ERROR: Your command: (null)
ERROR:               (null)
ERROR: Permission denied
{ "success": false, "error": "Permission denied" }
```
I'm running version 0.15-rc1-48-g7c3b0ff (2017-11-15, branch "master").

**Comment by SirCmpwn** [comment]
Can you add this to `/etc/sway/security.d/10-sway.conf`, restart sway, and see if it can be reproduced?

```
ipc /usr/bin/swaymsg {
    * enabled

    events {
        * disabled
    }
}
```

**Comment by goose121** [comment]
`s/swaymsg/sway`, but it worked! Thank you so much!

**Comment by SirCmpwn** [comment]
Thanks, leaving this open so we don't forget to add that to the default security config.

**Comment by goose121** [comment]
Also, you may want to add a similar clause for `/usr/bin/i3-msg` so that e.g. `sway-dmenu-desktop` works.

**Comment by ofwinterpassed** [comment]
This solution does not work for me! Trying to use dmenu to confirm exiting via a script that runs:
```sh
[ $(echo -e "No\nYes" | dmenu -i -p "Close session?") == "Yes" ] && swaymsg exit
```
nothing happens if i choose Yes in the menu and if I run `swaymsg exit` in a terminal I get `Error: Permission denied for exit via IPC`

Please help!

**Comment by emersion** [comment]
Shouldn't be an issue anymore, security things have been removed.
