### ISSUE TITLE
tray icons not showing

### ISSUE THREAD

**Issue by cycomanic** [swaywm/sway#1469]
I can not make tray icons show. I've gone through the discussion at #1372 but nothing mentioned there worked for me, neither appindicator icons nore ksni items work. Nothing shows. Attached is the log for swaybar when I start konversation. I'm running sway compiled from source on ubuntu 17.10.
[swaybar6.log](https://github.com/swaywm/sway/files/1485070/swaybar6.log)
Sway cmake output.
[cmake.txt](https://github.com/swaywm/sway/files/1485072/cmake.txt)

**Comment by SirCmpwn** [comment]
What software are you using that does not work?

**Comment by cycomanic** [comment]
I've tried konversation, tried vlc, tried the script mentioned in the other discussion based on python-kde4: [https://github.com/ubuntu/gnome-shell-extension-appindicator/blob/master/indicator-test-tool/ksni.py](url)
clementine (with sni-qt installed). Not sure what other ones to test. It does not seem that there is a tray area even showing. If I add a separator_symbol and tray_padding to very high numbers nothing changes on the bar.

**Comment by 4e554c4c** [comment]
@cycomanic Yep, that's intended. If there aren't any items then `tray_padding` doesn't do anything. Also `separator_symbol` doesn't apply to the tray. In your logs it shows that it finds konversation and its icon just fine, so I don't see what's wrong. (perhaps try resetting all those config changes and try again?)

**Comment by cycomanic** [comment]
OK, just did a check after removing the padding, konversation is working now. None of the other apps are showing I suspect that's due to #1372 ? I thought according to the thread there the ksni.py utility should work?

**Comment by cycomanic** [comment]
OK, just did a check after removing the padding, konversation is working now. None of the other apps are showing I suspect that's due to #1372 ? I thought according to the thread there the ksni.py utility should work?

**Comment by SirCmpwn** [comment]
Move this discussion to #1372
