### ISSUE TITLE
Clipboard history

### ISSUE THREAD

**Issue by ghost** [swaywm/sway#1470]
If I understand correctly, clipboard managers in wayland can't work anymore, by design. According to [this comment](https://bugzilla.gnome.org/show_bug.cgi?id=775905#c1) it's the compositor's responsibility to implement clipboard managing, because apps are not privileged enough.

Basically it should be as simple as storing clipboard events incrementally in a file, instead than replacing the previous selection; for security and compatibility with existing set-ups, the default history length would be 1. Then it's up to third party apps to retrieve and display the clipboard's history (for example from sway-msg).

**Comment by acrisci** [comment]
The implementation would be a little tricky since we pass file descriptors between the windows and not the actual contents themselves.

**Comment by SirCmpwn** [comment]
This should be possible, but it's not going to be done for some time.

**Comment by ormung** [comment]
Sure, no problem! Thank'you for your interest.

**Comment by Freyr666** [comment]
Wouldn't it be more sane to make a protocol for clipboard access with events on update? It can be useful not only for clipboard managers but also for dictioonaries and other stuff.

**Comment by emersion** [comment]
https://github.com/swaywm/wlr-protocols/issues/20
