### ISSUE TITLE
Hide mouse cursor on inactivity

### ISSUE THREAD

**Issue by rightaway** [swaywm/sway#1471]
Just like `unclutter` does for X, it would be useful to have a setting for the amount of seconds of mouse inactivity after which to hide the mouse cursor.

**Comment by oblitum** [comment]
You can use this tool to hide your mouse under Wayland, I've just written it and I'm happily making use of it:

- https://gitlab.com/interception/linux/plugins/hideaway

**Comment by ReekyMarko** [comment]
Just as a PSA for anyone stumbling here, Sway can do this natively also, f.ex `seat * hide_cursor 8000`

**Comment by skrat** [comment]
I love how things just go away and sensible defaults are included where I need them, thank you sway

**Comment by dzintars** [comment]
Is there something similar for when i start typing?

**Comment by tmpm697** [comment]
@dzintars `seat * hide_cursor when-typing enable`

**Comment by Zeioth** [comment]
> @dzintars `seat * hide_cursor when-typing enable`

Can be combined with 

     seat * hide_cursor 8000

Or do you need to set both separately?

**Comment by dzintars** [comment]
Booth separately.
