### ISSUE TITLE
Sway makes Gnome Shell crash(?), overrides it as default compositor and freezes upon TTY switch

### ISSUE THREAD

**Issue by codethief** [swaywm/sway#1473]
I just installed Ubuntu 17.04 on my Thinkpad T450s and wanted to see what Sway is like (been using i3 for years), so right after the Ubuntu installer had finished I installed Sway v0.14.0 from the inofficial Ubuntu repository that I found in the wiki.

Without making any adjustments to the configuration, I then switched to a different TTY (`Ctrl+Alt+F6`) and ran `$ sway` just as the docs suggested.

Results:

1. Sway runs beautifully at first, recognizing both, the Thinkpad's screen as well as an external monitor
2. When I want to switch back to the default Gnome Shell (`Ctrl+Alt+F7`) I see nothing but a black screen with a white cursor in the top left corner.
3. Switching back to Sway still works, though, so I do that and reboot.
4. After rebooting, I expected Gnome Shell to be started again but instead Sway is being fired up. Also, my Thinkpad's screen is not working anymore / disabled and only the external screen is being used by Sway now. 
5. I now want to switch to a different TTY to start the Gnome Shell. Result: Sway freezes and I can't switch the TTY anymore. I have to press the power button to reboot.
6. After the 2nd reboot, the situation is the same as in 4). I do 5) again and Sway freezes once again. So this seems to be a reproducible issue.

Expected results:

- Gnome Shell should not be replaced as default Wayland compositor.
- Gnome Shell on TTY 7 should not crash upon starting Sway on TTY 6.
- Sway should not freeze upon switching TTYs.
- Sway should recognize my Thinkpad's built-in screen at all times.

I obviously didn't expect Sway to be fired up after boot-up, so I can't provide any logs unfortunately. (And since I can't switch TTYs anymore without my main Sway instance freezing I also can't create a debug log in any other way.) I do think this should be a reproducible issue, though, given that installing Sway was literally the first thing I did after installing Ubuntu.

I realize there could be multiple issues at work here. Maybe Gnome Shell isn't handling TTY switches too well or maybe it's Sway or maybe there's an underlying issue with Wayland that causes the TTYs not to be separated as well as expected and, thus, multiple compositors to interfere with each other. Or maybe it's all of those things at the same time. And then there's still the question why GDM as Ubuntu's new login manager is suddenly starting Sway instead of Gnome…

**Comment by SirCmpwn** [comment]
Sway does not support running concurrently with other compositors. Just don't do it.

**Comment by codethief** [comment]
Thanks, that's good to know. But now after rebooting I'm running it alone (the only Gnome-related process  `$ ps faux | grep gnome` can find is `/usr/lib/at-spi2-core/at-spi2-registryd`) and it's still freezing upon switching TTYs and/or exiting (see item 7 above which I just added). So I suspect there is more going on that simply running two compositors at the same time. Unless, of course, running two compositors at once caused some permanent damage, i.e. left some traces behind that are now causing all these issues(?)

**Comment by SirCmpwn** [comment]
Switching TTYs in general is not supported either. That may impove with wlroots, but for now - just don't do it.

**Comment by codethief** [comment]
Ok, good to know, too. Could you add a corresponding warning to the README file? In my case I'll simply reinstall Ubuntu now and try again but other users probably wouldn't be happy to do that.

**Comment by SirCmpwn** [comment]
Why do you have to reinstall ubuntu? In any case, this problem is not nearly common enough to justify a spot in the readme.
