### ISSUE TITLE
Switching workspaces is unreliable and moving containers does not work 

### ISSUE THREAD

**Issue by codethief** [swaywm/sway#1475]
The title says it all. I'm using a configuration which resembles the default i3 config:

```
# Windows key; used as the general modifier key
set $mod Mod4

# […]

# switch to workspace
bindsym $mod+1 workspace 1
bindsym $mod+2 workspace 2
bindsym $mod+3 workspace 3
bindsym $mod+4 workspace 4
bindsym $mod+5 workspace 5
bindsym $mod+6 workspace 6
bindsym $mod+7 workspace 7
bindsym $mod+8 workspace 8
bindsym $mod+9 workspace 9
bindsym $mod+0 workspace 10

# alternatives
bindsym F1 workspace 1
bindsym F2 workspace 2
bindsym F3 workspace 3
bindsym F4 workspace 4
bindsym F7 workspace 7

# move focused container to workspace
bindsym $mod+Shift+exclam move workspace 1
bindsym $mod+Shift+quotedbl move workspace 2
bindsym $mod+Shift+section move workspace 3
bindsym $mod+Shift+dollar move workspace 4
bindsym $mod+Shift+percent move workspace 5
bindsym $mod+Shift+ampersand move workspace 6
bindsym $mod+Shift+slash move workspace 7
bindsym $mod+Shift+parenleft move workspace 8
bindsym $mod+Shift+parenright move workspace 9
bindsym $mod+Shift+equal move workspace 10

# alternatives
bindsym $mod+F1 move workspace 1
bindsym $mod+F2 move workspace 2
bindsym $mod+F3 move workspace 3
bindsym $mod+F4 move workspace 4
bindsym $mod+F7 move workspace 7
```

Switching workspaces mostly works (albeit sometimes with significant lag of up to ~10 seconds) but moving containers does not work at all, neither using `$mod+Shift+<number>` nor using `$mod+<function key>`.

I'm using Sway 0.14.0 on Ubuntu 17.10.

**Comment by 4e554c4c** [comment]
Please attach debug log and switch to 0.15 if possible.

**Comment by t-8ch** [comment]
@codethief
I also had the problem of not being able to move containers to workspaces.
The configuration between i3 and sway differs here:
```
#i3:
bindsym $mod+Shift+1 move workspace 1

#sway
bindsym $mod+Shift+1 move container to workspace 1
```

**Comment by albocc** [comment]
@t-8ch You might have an old version of the i3 config. My i3 config has the same syntax as Sway does and the default config seems to have it too:

https://github.com/i3/i3/blob/d2e86da84f0db78dabcd5e587cbb3fe36ae428a4/etc/config#L134

**Comment by t-8ch** [comment]
Thanks @albocc , I am actually not sure why I wrote this comment, as my current config looks like the example one and works -.-
