### ISSUE TITLE
xterm and Xresources?

### ISSUE THREAD

**Issue by pauledd** [swaywm/sway#1476]
Hi
This is not an issue but how can I make xterm in sway make use of my ~/.Xresources file.
I have a sway start script which contains:
```
xrdb -merge ~/.Xresources
export XKB_DEFAULT_LAYOUT=de
sway
```
but my Xresources settings are still unrecognized by xterm.

PS.
BUT when I start sway and I type "xrdb -merge ~/.Xresources" in xterm and close it, reopen a new xterm my settings are recognized...

Any ideas anyone?

**Comment by kiljacken** [comment]
`xrdb` must be run _after_ sway is started as XWayland is started by sway. I (used to, not currently using sway) do it with an `exec` in my sway config.

**Comment by pauledd** [comment]
thank you, that works!
