### ISSUE TITLE
Chromium blurry with "output * scale 2"

### ISSUE THREAD

**Issue by maletor** [swaywm/sway#1481]
When comparing sway vs i3 with `Xft.dpi 200`, chromium is not doing something correct with the scaling and it appears blurry.

Chromium has `force-device-scaling` but it shouldn't be necessary as it can read from the DPI of your screen to set the scale correctly. Is this a bug in Chromium or sway or wlc? Are you able to reproduce?

**Comment by SirCmpwn** [comment]
Xwayland does not support scaling.

**Comment by maletor** [comment]
Thanks for the quick response. I understand you are working on this longer term with wlroots. Appreciate it.

**Comment by torpak** [comment]
@maletor i think you misunderstood: Scaling will ever only work correctly with wayland applications. Chromium still uses X and there for Xwayland unter sway and will not scale correctly until it switches to wayland.

**Comment by maletor** [comment]
@torpak but what about Chromium's internal chromium's `force-device-scale-factor` flag? That would work with XWayland correctly?

**Comment by torpak** [comment]
@maletor I have no idea, since i don't use chromium. But as i understand it that would be the same for all environments using xwayland for legacy applications. So maybe you should ask chromiums developers?

**Comment by mijoharas** [comment]
Just to provide on update on this for anyone that finds this issue. At some point in the last 2 months this was fixed. With absolutely no changes from me chrome auto-scaling now looks crisp and correct.

**Comment by jhasse** [comment]
just for the record: https://bugs.chromium.org/p/chromium/issues/detail?id=578890
