### ISSUE TITLE
First character dropped after switching to window

### ISSUE THREAD

**Issue by PureW** [swaywm/sway#1495]
Hello,

Just switched to Wayland and Sway, having used i3 for a few years before that. 

I'm seeing a behaviour where switching window to a terminal (tried both termite and urxvw) using `super+<number>` or `super+<L or H>` results in the first key press sending the command typed so far.

An example might be clearer:
```
# Terminal on 2 active, type ab
$ ab
# Switch to 1 with `super+1`
# Switch back to terminal on 2 with `super+2`: type cd
$ abd
```

**Comment by yw662** [comment]
cannot reproduce with termite&&fish

**Comment by SirCmpwn** [comment]
I cannot reproduce this, either.
