### ISSUE TITLE
Only Mod1 is recognized

### ISSUE THREAD

**Issue by oblitum** [swaywm/sway#1496]
I've put this on my `~/.config/sway/config`:

```
bindsym Mod1+y exec touch /tmp/Mod1
bindsym Mod2+y exec touch /tmp/Mod2
bindsym Mod3+y exec touch /tmp/Mod3
bindsym Mod4+y exec touch /tmp/Mod4
bindsym Mod5+y exec touch /tmp/Mod5
```

Reloaded configuration, then I tried all control keys `+y` in a blank workspace and just got the `/tmp/Mod1` file out. This means that it seems I have no way of creating mappings with my keyboard's Windows key, CTRL, etc, only Alt works? Also bad is that I can't use Left Alt vs Right Alt for different mappings.

### Side note

This also was the reason I've expent a long time thinking Sway was simply not recognizing keyboard input at all on my machine, until I realized it was because of the default Mod4 mappings:

- https://github.com/Cloudef/wlc/issues/283#issuecomment-348683148

(Isn't it safer bet to have Mod1 in default config?)

Another thing is that I coudn't find docs about what Mod[N] means in a Wayland context, I remember this from Xmodmap but, does Sway rely on Xmodmap/X for input? Personally I'd prefer to be able to use control keys directly, LEFTCTRL, RIGHTALT, etc.

**Comment by SirCmpwn** [comment]
I'm closing issues that are resolved by the yet-unreleased sway 1.0.
