### ISSUE TITLE
Blurred font with some GTK+ 3 app with wayland backend

### ISSUE THREAD

**Issue by N46AN** [swaywm/sway#1502]
`Linux 4.13.0-0.bpo.1-amd64 #1 SMP Debian 4.13.4-2~bpo9+1 (2017-10-17) x86_64 GNU/Linux`
`Debian GNU/Linux 9 \n \l`

sway git master 7c3b0ff
wlc git master e3abf0b
weston 1.12.0-3

Summary:
Some GTK+ 3 application would have blurred font with GDK_BACKEND=wayland
Those application does not have blurred font in weston 1.12.0-3

Step to reproduce:
1. Launch sway in tty
2. Launch `GDK_BACKEND=wayland pluma`

Actual Behaviour
Pluma has blurred font. (And as a bonus, all menus except "File" and "Help" are inoperable)

Expected Behaviour
Pluma should have sharp font as in weston

Screenshots:
http://img.vim-cn.com/60/2cc9b1f2282eea3e56d4c31c66a8f0b11137ad.png
http://img.vim-cn.com/bf/a12deb136e92e2b27517cbdc564673f7dbac98.png

Debug log (`sway -d >pluma-blurred 2>&1`) :
http://cfp.vim-cn.com/cbdGH

$HOME/.config/sway/config
http://cfp.vim-cn.com/cbdGJ

**Comment by SirCmpwn** [comment]
This will be addressed when [wlroots](https://github.com/swaywm/wlroots) is completed and [integrated with sway](https://github.com/swaywm/sway/issues/1390).
