### ISSUE TITLE
Workspaces switch incorrectly on multihead

### ISSUE THREAD

**Issue by wilecoyote2015** [swaywm/sway#1510]
On my multihead setup with three outputs, sometimes workspace switching occurs on another workspace than the active one (where the mouse is located) and certain workspaces cannot be acessed on some outputs.

There are three monitors on my setup with the following workspace assignments on sway start: 
output 1: 1
output 2: 3 
output 3: 2

Steps to reproduce:  
1. start terminal on workspace 2
2. on output 3, switch to workspace 4 
3. on output 2, switch to workspace 2

The last step fails, as output 3 switches to workspace 2, even though the cursor is on output 2.

I am using a recent GIT build (sway version 0.15.0) from master branch on Arch Linux.

Log and Config:
https://gist.github.com/wilecoyote2015/9810acde40d6c6bf400ee41d3cec29ce

**Comment by SirCmpwn** [comment]
Can you still reproduce this?
