### ISSUE TITLE
Shadow support?

### ISSUE THREAD

**Issue by that1communist** [swaywm/sway#1511]
My usecase is a black border when unfocused and a white border when focused, meaning when I have a floating window on a white background, i can't see the border, compton shadows fix this, and it'd be really nice to have this on sway, and I mostly post this to find out if this is planned.

**Comment by SirCmpwn** [comment]
You already requested this -_-

https://github.com/swaywm/sway/issues/1426

**Comment by that1communist** [comment]
Yeah but I figured I was too broad. Not supporting most compton features =/= not supporting shadows.
