### ISSUE TITLE
Context menus sometimes get caught underneath windows.

### ISSUE THREAD

**Issue by bwbw223** [swaywm/sway#1512]
![image with context menu under window](https://user-images.githubusercontent.com/11503394/33916419-bdcff448-df76-11e7-8b56-d1dd4b3265b9.JPG)

**Comment by SirCmpwn** [comment]
This will be addressed when [wlroots](https://github.com/swaywm/wlroots) is completed and [integrated with sway](https://github.com/swaywm/sway/issues/1390).
