### ISSUE TITLE
[feature proposal] Trackpad gestures to switch workspaces.

### ISSUE THREAD

**Issue by rafaelleru** [swaywm/sway#1514]

**Comment by acrisci** [comment]
You need to put in a little more effort for big proposals like this 😄 .

**Comment by rafaelleru** [comment]
okey, I will improve it tonigh 😄

**Comment by clarcharr** [comment]
I think a better request would just be trackpad gestures mapping to keybindings. Which could be possible, but I'm not sure how that would work from the libinput side.

**Comment by rafaelleru** [comment]
Yes what I mean is that it will be cool if in the config file you can specify that 4 fingers swipe left is for go to the next workspace, or 3 fingers swipe up to move the focused cointainer to a superior container.

**Comment by rafaelleru** [comment]
Since libinput is the default input manager in wayland and it supports multitouch gestures I think that will be cool to define some gestures in the config file, for example 4 fingers swipe to change the workspace or 3 fingers up to reveal the scratchpad windows. It is only a idea and I can think if it is even possible.

**Comment by SirCmpwn** [comment]
I'm not sure libinput supports that. To develop this I would need to have access to hardware with a multi-touch touchpad for testing and research, which I currently do not have.

**Comment by SirCmpwn** [comment]
If you'd like to work on this, start by learning how libinput works and how it interfaces with wlroots, then do some experimentation to find out how that takes shape with your hardware.

**Comment by rokyfox** [comment]
For anyone else who is looking for this, checkout [libinput-gestures](https://github.com/bulletmark/libinput-gestures). It allows mapping any command to swipe and pinch gestures. Works perfectly with `swaymsg` commands.

**Comment by sevensidedmarble** [comment]
How doable would it be to get swapping through workspaces by slowly dragging between them, ala macos? (if you haven't seen it before, its like you actually drag between the workspaces with three fingers)

**Comment by emersion** [comment]
Sorry, we won't add animations or eye-candy features like this.

**Comment by specious** [comment]
Looks like #4952 is working on implementing this.

**Comment by RPigott** [comment]
#4952 allows the user to configure swipe gestures. It doesn't add animated workspace transitions.

**Comment by sevensidedmarble** [comment]
Is there a reason why animations are off the table? Sway is one the best WMs for Wayland out there. This would be a seriously killer feature that would bring a *lot* of users.

**Comment by emersion** [comment]
Glad you like Sway, The reason is that we don't want Sway's scope to grow uncontrolled -- we have little resources to maintain it. Feel free to implement these features in a fork ofc.

**Comment by emersion** [comment]
> bring a lot of users

Ah, I forgot to mention: Sway is not a product, it's an open-source project. Our goal isn't to attract as many users as possible.
