### ISSUE TITLE
move container to back_and_forth

### ISSUE THREAD

**Issue by Kaligule** [swaywm/sway#1518]
It is currently possible to switch to the workspace where you were before:

> bindsym $mod+b workspace back_and_forth

It is not possible to move a container (window) there:

> \# doesn't work
> bindsym $mod+Shift+b move container to workspace back_and_forth

This is counterintuitive and makes it harder to work with workspaces that are named on the fly. It would be nice to support this.

**Comment by SirCmpwn** [comment]
Does i3 support this feature?

**Comment by Kaligule** [comment]
To be honest I am not sure. I was 100% certain I have used this command 100 times in i3, but I can't find it in my old config or the default configs.

**Comment by SirCmpwn** [comment]
i3 has docs

**Comment by Kaligule** [comment]
You are right. It is documented [here](https://i3wm.org/docs/userguide.html#_changing_named_workspaces_moving_to_workspaces).

**Comment by SirCmpwn** [comment]
Cool, +1
