### ISSUE TITLE
config: Can't exec a command (command not found)

### ISSUE THREAD

**Issue by Moret84** [swaywm/sway#1520]
Hi, 
I have installled j4-dmenu-desktop to use as application launcher but it is not started at all when I type the matching keyboard shortcut. The sway log says /bin/sh: j4-dmenu-desktop: command not found.
It works fine if I run it from the terminal, though. I use zsh, but I can also run j4-dmenu-desktop from the bourne shell using sh -c 'j4-dmenu-desktop'. Could someone help ?

**Comment by SirCmpwn** [comment]
https://github.com/SirCmpwn/sway/wiki#how-do-i-report-issues

**Comment by Moret84** [comment]
So sorry,
I use Sway on Archlinux (a fresh install) and the version is 0.15.0.

The debug log is here: 

https://gist.github.com/Moret84/1b23f52dbd3537f284bc0f76bdfe43b4

**Comment by SirCmpwn** [comment]
What is the output of `which j4-dmenu-desktop` in your shell?

**Comment by SirCmpwn** [comment]
Oh, it's because of your quoting. Replace this:

    bindsym $mod+d exec --no-startup-id "j4-dmenu-desktop --no-generic"

With this:

    bindsym $mod+d exec j4-dmenu-desktop --no-generic

(no-startup-id is unrelated but sway doesn't and won't support it anyway)

**Comment by Moret84** [comment]
/usr/bin/j4-dmenu-desktop

Yeah  just read #521 . Sorry. You can close.
