### ISSUE TITLE
Feature request: Allow for runtime swaybar bindsym commands

### ISSUE THREAD

**Issue by oblitum** [swaywm/sway#1521]
Specifically in my case I wished I could toogle the swaybar height between 0 and 17, so to get manual [hide mode](https://github.com/swaywm/sway/issues/2#issuecomment-348697982).

**Comment by oblitum** [comment]
Just noticed that setting height to 0 cause the bar height get the font's height, as it's set by default. So I would still stumble upon that limitation.

**Comment by 4e554c4c** [comment]
Honestly I would just run a script that determined if swaybar is running, and either kill it if it is or start it otherwise.

**Comment by oblitum** [comment]
Interesting, I'll go about trying that, though full bar reload can be a bit overkill, i3status for example, requires some time to load.

**Comment by oblitum** [comment]
OK, this does a great job, thanks for the tip @4e554c4c :

```
bindsym $mod+a exec pkill swaybar
bindsym $mod+Shift+a exec swaybar -b bar-0
```

As mentioned, the only caveat is the bar reload, which takes some time. I'll leave the issue open and it's more general than this, and also could be implemented in a better way, feel free to close though.
