### ISSUE TITLE
Key bindings stop working until the mouse is moved in certain cases

### ISSUE THREAD

**Issue by tsloughter** [swaywm/sway#1522]
sway version 0.15-rc1-48-g7c3b0ff (2017-11-05, branch "master")

Using the configured key combos to switch workspaces `Mod-#` will stop working until the mouse is moved  in certain cases.

One case, though I'm fairly sure not the only one, that I've found to consistently result in this is having firefox open on workspace 1 and a pidgin conversation on workspace 2. Clicking on a link in the pidgin conversation opens a tab in firefox but after clicking the link, `Mod-1` does not work to switch to the first workspace (or any workspace) until the mouse is moved.

Update: Actually I've just discovered I only have to hover over the link in pidgin and the little hover text appears under the link, so it is likely unrelated to the opening of the link but a result of the little text box that pops up when hovering over a link.

**Comment by cafehaine** [comment]
probably duplicate of #646

**Comment by tsloughter** [comment]
Ah, yup! I hadn't pinned it down to the hover and forgot the name of "tooltips" so missed that. Thanks.
