### ISSUE TITLE
Changes to expect from wlroots

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/sway#1524]
This will eventually morph into the 1.0 changelog. There's a lot of changes, so it'll take some time to enumerate them. Please comment if I forgot anything.

**General**

- Permission to take screenshots/record the screen is now configurable
- Rendering overhaul dramatically improves performance, accuracy, and power usage
- The scratchpad has been overhauled and is much less buggy

**Input**

- You can now configure discrete "seats", each with their own set of input devices, discrete mouse cursor, and focused windows
- Drawing tablets are now supported
- XKB options (i.e. keyboard layout) can be configured in your config file and changed at runtime

**Displays**

- Rotating and flipping outputs now supported
- Output mirroring now supported
- Fractional scaling is now possible (i.e. 1.5x)
- Floating windows can be dragged between outputs (including mixed DPI configurations)
- More exotic display configurations now supported
- Hotplugging more stable

**Wayland Features**

- Rich content (rich text, images, etc) can be copied from Wayland to Xwayland and vice versa
- Drag and drop now supported
- The following Wayland protocol extensions are now supported:
    - surface-layers
    - input-method
    - presentation-time
    - pointer-constraints
    - relative-pointer
    - xdg-output
    - tablet
    - idle_inhibit
    - gtk-primary-clipboard

**Surface Layers**

We have developed a new Wayland protocol extension that enables many of your old desktop features to be adapted for Sway and other Wayland compositors. Much of the software to take advantage of this does not yet exist, but features possible protocol with this include:

- Selecting a region of the screen to screenshot (ala slop)
- Third party panels, lockscreens, wallpaper software
- On screen keyboards
- Notification daemons
- dmenu/rofi/etc

**Backends**

- DRM: Multiple graphics cards now supported
- DRM: Atomic DRM modesetting now supported
- DRM: DisplayPort MST (e.g. daisy chaining) now supported
- Wayland: Now supported as an end-user feature (previously limited to developers)
- X11: Now supported as an end-user feature (previously limited to developers)
- Headless: Provides scriptable fake displays and fake input devices
- The Nvidia proprietary driver is no longer supported (or any other proprietary driver that does not implement KMS/DRM/GBM)

**Bugs Closed**

Too many to list.

**Comment by acrisci** [comment]
Single-frame reflows will be a big deal when we get around to doing it.

**Comment by SirCmpwn** [comment]
>Single-frame reflows will be a big deal when we get around to doing it. The idea is to make rendering smoother when the position of the containers change so all the updates happen in one frame so it seems like a single update.

I'm not sure how to distill this into a statement meaningful for end-users.

**Comment by SirCmpwn** [comment]
>- Rendering overhaul dramatically improves performance and accuracy

Added "and accuracy" to maybe address that

**Comment by emersion** [comment]
>Backends can now be added or removed at runtime, which lets you do things like adding a Wayland windows as a virtual "display" (nested in Sway or on another compositor), or something similar with an X11 virtual display, etc.

Should be removed
