### ISSUE TITLE
Sway test suite proposal

### ISSUE THREAD

**Issue by acrisci** [swaywm/sway#1528]
We've talked about this before, but now that we are designing the headless backend into sway, it is now possible to have a test suite with the wlroots changes.

Sway is a unique project in that it has many contributors who do small pieces of functionality that they personally want in the window manager. Tests are valuable in this case so we can freely accept small contributions without fear of breaking things previous submitters rely upon.

I think last time we discussed this, we determined that tests should be out of tree (perhaps in a sway-tests project) sort of like the Linux Test Project with a different maintainer (I will sponsor this project).

Goals:

* Tests written in the Go programming language
* Run a headless instance of sway and use [i3ipc](https://godoc.org/go.i3wm.org/i3) Go library to communicate with the process
* Run tests when PRs are submitted to sway

Nongoals:

* 100% code coverage
* Test rendering or DRM backend
* Require tests for every feature

**Comment by SirCmpwn** [comment]
fwiw you could probably test rendering too by writing a simple test client that just draws a solid color or so.

**Comment by SirCmpwn** [comment]
Closing this as it'll happen out of tree anyway.
