### ISSUE TITLE
Multibackend

### ISSUE THREAD

**Issue by acrisci** [swaywm/sway#1529]
This issue is adapted from #1390 

### Example use-cases

- Support tests #1528 
- Add an RDP backend at runtime so your buddy can pair program with you
- Add a headless backend for scripting with
- Add a nested Wayland backend to your DRM session cause you're weird
- Add an x11 backend to your DRM session so you can switch TTYs to your x session and still manipulate your sway session

Backend configuration spec:

`backend add <type> [--name <name>] [args...]`: spins up a backend of the given type with the given name (or a generated name: `type-number` e.g. `libinput-0`). `[args...]` is backend-specific, such as a path to a DRM device for the DRM backend, a DISPLAY for x11, an initial number of outputs for the wayland backend, etc.

`backend del <name>`: does what it says on the tin

`backend <name> <subcommand> [args...]`: runtime manipulation of backend-specific features

### Subcommands

**wayland**

`backend wayland-0 add-output`

`backend wayland-0 del-output <id>`

**x11**

See wayland

**headless**

See wayland, plus

`backend headless-0 add-input <caps...>`

`backend headless-0 del-input <id>`

`backend headless-0 input <id> <send-keys|depress|release|click|move> [...]`

**Comment by acrisci** [comment]
@SirCmpwn is this a block command? And if it is, shouldn't we make the block config api the same as the command api like the others?

**Comment by acrisci** [comment]
Actually thinking about it now, maybe this is better left as a command and not a config block.

**Comment by SirCmpwn** [comment]
Aye, this is not a block.

**Comment by acrisci** [comment]
I think we should have an IPC command to list the backends.

**Comment by acrisci** [comment]
I think we should add a `--backend=<wayland|x11|drm|headless|none>` to `sway` to control the initial backend.

**Comment by SirCmpwn** [comment]
I think we should just do `--no-default-backend` and make them configure it via IPC

**Comment by acrisci** [comment]
I think that naming things (output, input, backend) should either always be a flag (set with `--name`) or always be a positional argument for consistency.
