### ISSUE TITLE
Output transform doesn't change pointer orientation

### ISSUE THREAD

**Issue by cawilliamson** [swaywm/sway#1534]
I'm currently experimenting with sway built against wlroots (wlroots branch of sway too of course.)

I've noticed that using `output * transform 270` works great at rotating the display but sadly does nothing for pointer orientation. I do realise this is still in development but just thought I'd create an issue report just in case this was missed.

Feel free to close this down if this is already known but I didn't see it in the wlroots-related ticket.

**Comment by emersion** [comment]
Are you testing with the Wayland backend?

**Comment by cawilliamson** [comment]
@emersion Good question - checked the output log and it looks like I was actually running under xwayland. Oops! Any suggestion on how to switch to xwayland as the backend with wlroots+sway? I know you could disable it previously with `WLC_XWAYLAND=0` but not sure what the equivalent is in wlroots.

**Comment by emersion** [comment]
I'm talking about the backend: how did you run `sway`? In a tty or in another compositor?

**Comment by cawilliamson** [comment]
Ah - in a tty yes.

**Comment by emersion** [comment]
Can you reproduce with rootston?

**Comment by SirCmpwn** [comment]
Obtain a debug log.

**Comment by emersion** [comment]
Fixed a while ago with https://github.com/swaywm/wlroots/pull/522
