### ISSUE TITLE
Request: Can Sway be loaded as an alternate environment from Ubuntu 1710 Login?

### ISSUE THREAD

**Issue by nick-walt** [swaywm/sway#1547]
I have a stock install of Ubuntu 1710 running Wayland by default and I'd like to be able to select Sway as an option in addition to X.org and Wayland in the GDM login screen. Is this possible? Would really like to see a How To that explicitly addresses all required steps to install Sway.

So far, I (and most likely many others who haven't spent time under the Linux hood) don't know how Sway if and how Sway can be used in the latest Ubuntu.

If potential users know exactly how Sway is used and can be confident in being able to switch between Sway and the default Ubuntu environment, when logging in, I think Sway would find greater adoption.

I know that good documentation is hard (I've written plenty myself) but it is sooooo required in open source. Explicit, accurate, concise, complete, non-technical language except where required, and sequences captured so that users aren't lost. As soon as documentation has lost a user it has failed (this is the super hard part).

Good documentation is good UX and UI, FTW! If I figure out how this is installed, etc, happy to help write documentation for a Wayland Ubuntu installation that will cater to less technical users.

Thanks :)

**Comment by SirCmpwn** [comment]
This is not and will not be supported. The FAQ has information on starting Sway.

**Comment by SirCmpwn** [comment]
We have damn good documentation, thank you very much, if only our users would actually read it.

**Comment by nick-walt** [comment]
Hi mate, yeah I read through the documentation first then found the unsupported PPA and decided to take the plunge and installed it. Does exactly what I was wondering about: putting the option to use Sway as a session in GDM login, above X.org and Wayland (if that is the right way to say it).

Having Sway as a selectable session is a nice way to try something as different as a tiling wm. Sat there looking at a beautiful screen but no idea what to do next. A bit like a new user who follows a How To that references vi instead of Nano and has no idea wtf is going on when nothing happens as they increasingly bash their keyboard.

Followed your video showing the key commands and was able to see the selectable options arising after pressing Super + D. Though, a few of them didn't work, like resizing windows.

BUT! I'm writing this from within Chrome in Sway.

I'm sure you guys have good doco, but it's probably making a lot of assumptions about what the user understands. Good doco helps less knowledgeable users understand the tech better through a first-principles revelation as they read through it. This is hard to write without pissing off the advanced users, but it can be done with the right intent.

I'm gonna get back to exploring this deep UI. Cheers on creating something so beautifully fluid.
