### ISSUE TITLE
Invalid memory freeing 

### ISSUE THREAD

**Issue by awkure** [swaywm/sway#1548]
```
λ sway -v
sway version 0.15-rc1-48-g7c3b0ff (2018-01-03, branch "master")
```
After manual installation sway crashes at startup with the following error log

```
*** Error in `sway': free(): invalid pointer: 0x000055ff2aa11641 ***
```

Assuming that it tries to free the memory pointed to invalid location and then immediately crashes. Meanwhile weston works perfectly so I don't think that the problem with my wayland setup.

**Comment by SirCmpwn** [comment]
Can you provide consistent reproduction steps and maybe run it through valgrind?

**Comment by SirCmpwn** [comment]
And a debug log.

**Comment by awkure** [comment]
Just found out that the problem was inside my configiguration file. 
So to reproduce the bug just add the following 
```
set $ws10 " name "
bindsym Mod1+0 workspace $ws10
```
And here's my [debug.log](https://github.com/swaywm/sway/files/1602866/debug.log)

**Comment by SirCmpwn** [comment]
Thanks, that's helpful.

**Comment by 4e554c4c** [comment]
Should be fixed
