### ISSUE TITLE
sway wont start anymore - Arch GNU/Linux - json-c 

### ISSUE THREAD

**Issue by ReK2Fernandez** [swaywm/sway#1553]
Hello Arch updated the json-c lib from 12.x to 13 and sway is hardcoded to depend on json-c 12.x
so it wont start.. so all people running on Arch GNU/Linux that will and already updated wont be able to start sway..
Is there a workaround until this gets updated?

**Comment by MTHSBGN** [comment]
I'm currently running Arch and json-c 0.13-1 and I don't have any problem starting sway. Are you sure the problem comes from the json-c library?

**Comment by ReK2Fernandez** [comment]
thats what the log for sddm said when it was trying to start it. also when I try to compile a new version it broke on json-c complaining it was looking for the older version. Im about to go to bed but will reproduce tomorrow and take a picture or something of the console since the only way to see it is to ctrl+alt+f4 etc

**Comment by MTHSBGN** [comment]
I'm not using sddm so I can't reproduce your problem but you should try to start sway from the console to see what happens. 
On another note, I do have the same error as you when trying to build sway from source.

**Comment by 4e554c4c** [comment]
@ReK2Fernandez `sway --version`

**Comment by SirCmpwn** [comment]
sddm is not supported, and Arch should be up to date. Run -Syu.

**Comment by ReK2Fernandez** [comment]
@SirCmpwn is up to date this is the issue.. started after I updated 2 nights a go. and is not a sddm issue.. it wont compile against the new json-c and if sddm is not supported how do you run sway? because lxdm does not support wayland yet.

**Comment by SirCmpwn** [comment]
How did you install sway?

**Comment by ReK2Fernandez** [comment]
pacaur -S aur/sway-git so first thing that came to my mind is to recompile so it compiles against the latest libs, but is hardcoded to use the old one.. so fails

**Comment by SirCmpwn** [comment]
It should go without saying that the unstable version is not supported. Install sway from community.

**Comment by ReK2Fernandez** [comment]
@SirCmpwn ok I can do that, still I find amusing that you dont support your own app :) the -git is just like doing a git clone and compiling that way manually :) I like to run the latest version because of some issues I had last month dont remember why at the moment but that was the reason I changted to git, doing it this way arch knows about it.. while if I do a git clone it does not.

**Comment by SirCmpwn** [comment]
The json-c problem has in fact been fixed, a fact known to all developers working on Sway, for whom the git repository is intended. End users are meant to use the stable releases, for which the problem has also been fixed in a different way.
