### ISSUE TITLE
Parent steals focus from SNI menus

### ISSUE THREAD

**Issue by Hummer12007** [swaywm/sway#1557]
When the cursor gets over the menu popup region which overlaps the parent window (but is on top) focus is transferred to the parent window.
@4e554c4c

**Comment by 4e554c4c** [comment]
Yes, I had this issue too. But after a bunch of digging through WLC and sway's handlers I couldn't figure it out. Menus will be changing a lot soon (they will be mostly going through dmenu, and then changed again under wlroots) so don't know if this will be fixed.

**Comment by emersion** [comment]
This is a 0.15 issue, closing.
