### ISSUE TITLE
urxvt fails

### ISSUE THREAD

**Issue by NewbProgrammer101** [swaywm/sway#1560]
I have URXVT installed. 

I pressed $mod+enter to launch urxvt. 

Nothing happened.

Stripped log since I don't have copy and paste:

[exec_always.c:34] Executing urxvt
urxvt: can't open display :0, aborting.

**Comment by SirCmpwn** [comment]
https://github.com/SirCmpwn/sway/wiki#how-do-i-report-issues

**Comment by NewbProgrammer101** [comment]
I'll report my issue correctly in the next one.
