### ISSUE TITLE
Channel bits mismatch on newer Mesa

### ISSUE THREAD

**Issue by ManDay** [swaywm/sway#1565]
Sway on Intel Iris 550 IGP shows wrong colors (typical appearence of channel mismatch) as of the following [commit in Mesa](https://cgit.freedesktop.org/mesa/mesa/commit/?id=9e63cbacb6bc10b4426fc2af4989fbdc86ec4167)

**Comment by SirCmpwn** [comment]
Can I see a screenshot?

**Comment by ManDay** [comment]
![sway](https://user-images.githubusercontent.com/1059827/34956201-6d656228-fa28-11e7-8fc4-eb9cb6c2a501.jpg)

This is what I see. The background image in use is [this one](http://natbg.com/calm-storm-lightning-river-lake-clouds-nature-trees-wallpaper/)

**Comment by fooishbar** [comment]
Specifically, that's getting a 10bpc (but still 32bpp) EGLConfig, and adding it to KMS as an XRGB8888 buffer. If you look at how Weston's compositor-drm does it, we explicitly pass attribs to match the correct format when calling `eglChooseConfig`. Even without the presence of 10bpc configs, as channel order is defined, EGL could very legitimately return you a XBGR8888 (in KMS format naming) config, leading to swapped channels.

**Comment by ManDay** [comment]
No longer an issue with master@{1 May 18}, cheers.
