### ISSUE TITLE
False duplicate key when using bindcode

### ISSUE THREAD

**Issue by avbobylev** [swaywm/sway#1567]
Cannot bind hotkeys (`Fn+Space`, `Fn+F7`) that have save keysym `NoSymbol`, but different keycodes (according ot `xev` output) with the `bindcode` command.

Only one of bindings works depending on which one is first in the sway config file. The other is considered duplicate, overriden (according to log) but completely ignored.

sway version

    0.15.1

xev output

    KeyRelease event, serial 25, synthetic NO, window 0x800001,
     root 0x29c, subw 0x0, time 279561, (65,74), root:(749,98),
     state 0x0, keycode 248 (keysym 0x0, NoSymbol), same_screen YES,
     XLookupString gives 0 bytes:
     XFilterEvent returns: False

    KeyPress event, serial 28, synthetic NO, window 0x800001,
     root 0x29c, subw 0x0, time 283891, (65,74), root:(749,98),
     state 0x0, keycode 253 (keysym 0x0, NoSymbol), same_screen YES,
     XLookupString gives 0 bytes:
     XmbLookupString gives 0 bytes:
     XFilterEvent returns: False

sway config

    #248 - Fn + Space
    bindcode 248 exec surfer
    #253 - Fn + F7
    bindcode 253 exec remmina

sway log

    I: 01/14/18 21:22:56 - [commands.c:519] handling config command 'bindcode 248 exec surfer' 
    D: 01/14/18 21:22:56 - [commands.c:344] find_handler(bindcode) 0
    D: 01/14/18 21:22:56 - [bind.c:168] bindcode - Bound 248 to command exec surfer
    I: 01/14/18 21:22:56 - [commands.c:519] handling config command 'bindcode 253 exec remmina' 
    D: 01/14/18 21:22:56 - [commands.c:344] find_handler(bindcode) 0
    D: 01/14/18 21:22:56 - [bind.c:157] bindcode - '253' already exists, overwriting
    D: 01/14/18 21:22:56 - [bind.c:168] bindcode - Bound 253 to command exec remmina

**Comment by SirCmpwn** [comment]
I'm closing issues that are resolved by the yet-unrelated sway 1.0.
