### ISSUE TITLE
multiple seat: only make cursor appear for seat if it has a pointer configured

### ISSUE THREAD

**Issue by martinetd** [swaywm/sway#1568]
For example on a setup where you occasionally plug laptop into an extra pointer+keyboard that you'd like to see in another seat -- most of the time there's no device in 2nd seat, so it doesn't make sense to have cursor laying around at that time (and now I'm trying that, it's pretty annoying)

Could also remove cursor when pointer is unplugged, if we can tell no device left with pointer capability.

**Comment by emersion** [comment]
Related: if the seat only contains a tablet, hide the cursor when the pen leaves the tablet.
