### ISSUE TITLE
[Feature Request] LibInput Tap Button Remapping

### ISSUE THREAD

**Issue by alexschneider** [swaywm/sway#1569]
This is something that is available in LibInput under Xorg (see https://wiki.archlinux.org/index.php/Libinput#Button_re-mapping) but to the best of my knowledge it's not available in Sway. 

To be more specific - I'd like to be able to configure my taps so that 1 finger taps are left click, 2 finger taps are middle click, and 3 finger taps are right click (currently 2 and 3 are swapped). 

Perhaps an easier version of #1514 😄

**Comment by martinetd** [comment]
Just to not lose the 5 minutes I spent on this on IRC, the map is a simple 2-values enum so would be very similar to the rest of sway-input, just need to call [libinput_device_config_tap_set_button_map](https://wayland.freedesktop.org/libinput/doc/latest/group__config.html#gacc1e504af35eecc37e3381569ec9d2f8) like the others.

Could get an easy label (but should probably done in wlroots branch at this point, not sure if cherry-pick would work well)
