### ISSUE TITLE
when will "scratchpad" support appear?

### ISSUE THREAD

**Issue by Artlant** [swaywm/sway#1572]
when will scratchpad support appear?

example:
`for_window [class="htop"] move window to scratchpad, move scratchpad //etc.`

**Comment by SirCmpwn** [comment]
Scratchpad support has been in for ages.

**Comment by Artlant** [comment]
@SirCmpwn 
this line does not work

// move to scratchpad
`for_window [class="(?i)tilix"] move window to scratchpad, move position 0 18, resize set 1280 550, move scratchpad`

// show/hide Tilix
`bindsym F12 [class="Tilix"] scratchpad show`

replace "**Tilix**" with another application

**Comment by SirCmpwn** [comment]
https://github.com/SirCmpwn/sway/wiki#how-do-i-report-issues

**Comment by Artlant** [comment]
```
sway -v 
sway version 0.15.1
```
description of the problem:
Apps are only run in tiling mode. Switching in scratchpad mode does not work.

config file:
https://github.com/Artlant/dotfiles/blob/master/.config/i3/config

logs attach
[.sway.log](https://github.com/swaywm/sway/files/1642409/default.sway.log)

**Comment by SirCmpwn** [comment]
Looks like "move window to scratchpad" is not supported. Try just `move scratchpad` instead.

**Comment by Artlant** [comment]
@SirCmpwn still did not work. I wanted to do a screenshot but it did not work. (_gnome-screenshot is_ fails)
Also this one does not work (auto-focus on a new window).
```
for_window [class="(?i)"] focus
# for_window [class=".*"] focus
# for_window [class="^.*"]] focus
```
I have not tried the last two, maybe they will work

**Comment by SirCmpwn** [comment]
Screenshots are done with `swaygrab`, read the man page to learn about it.

Make sure that the class names and such line up correctly, native wayland programs for example do not have a window class. Use `swaymsg -t get_tree` to find window properties.

**Comment by Artlant** [comment]
@SirCmpwn yes, thank you. Teams really work.
Unfortunately I can not switch between sway and i3wm. If you go to ctrl + alt + f2 then the previous session ends.
[gettree_out.log](https://github.com/swaywm/sway/files/1643318/gettree_out.log)

**Comment by Artlant** [comment]
@SirCmpwn  I also used
`bindsym $mod+Shift+KP_Subtract [floating] move scratchpad`
but they also do not work

**Comment by SirCmpwn** [comment]
>Unfortunately I can not switch between sway and i3wm. If you go to ctrl + alt + f2 then the previous session ends.

This is not supported

**Comment by SirCmpwn** [comment]
Based on your get_tree try this:

```
for_window [class="tilix"] move position 0 18, resize set 1280 550, move scratchpad
bindsym F12 [class="tilix"] scratchpad show
```

**Comment by Artlant** [comment]
@SirCmpwn я попробовал - tilix как был tilingтак и остался. 

Потом я попробовал другое приложение "telegram". Запустил - ничего не показалось, 
нажал несколько раз на _Insert_ 
`bindsym Insert [class="TelegramDesktop"] scratchpad show `
- ничего 

Зашел в htop. Процесс загружен. Нажимаю еще несколько раз на _Insert_ и окно появилось. Только по центру экрана. Нажал еще раз на _Insert_ окно dont hide

@SirCmpwn I tried - _tilix_ as was tiling and stayed.

Then I tried another "_telegram
_" application. Started - nothing seemed,
clicked several times on _Insert_
`bindsym Insert [class =" TelegramDesktop "] scratchpad show`

nothing

I went into the _htop_. The process is loaded. I click a few more times on _Insert_ and the window appeared.

default in i3wm _scratchpad show_ - show/hide.
Only in the center of the screen (). Clicked once again on _Insert_ window dont hide


![2018-01-18-191759_swaygrab](https://user-images.githubusercontent.com/13064767/35112138-c962b706-fc85-11e7-9912-1d4a232b5307.png)

**Comment by Artlant** [comment]
@SirCmpwn 
Still a question and how to finish session? I visited via _i3-msg exit_. But probably correctly _sway-msg exit_?

**Comment by Artlant** [comment]
@SirCmpwn Or you can try my _config_. On your PC? replacing _tilix_ with its terminal or other application. Does scratchpad work correctly for you?

**Comment by Artlant** [comment]
@SirCmpwn 
and another question.

`for_window [class="(?i)xxkb"] ...`

_(?i)_ - does not work in sway?

**Comment by 4e554c4c** [comment]
@Artlant First of all: calm down. Spamming comments will not help anything and it just make people block you and your issue. Second of all: read the manual (`man sway`, `man 5 sway`) and the wiki pages because they contain much useful information. Finally,
>I click a few more times on Insert and the window appeared.

Your issue is solved.

Github issue comments are not the place for this kind of discussion. We have an IRC support channel for a reason.

**Comment by Artlant** [comment]
@4e554c4c 
> Your issue is solved.

nice. But where? I do not see a solution. (dont hide. Wrong position - this is according to your "solved") If the problem in my OS is - ok. Write, I have everything working and a screenshot. I'll understand that I did something wrong.

> read the manual
You on the page say that the config is fully compatible with the i3wm version. But this is not so. And I want to find out why.
If this is me and write. Or you do not care - too. I'll understand.
But if it's reproduced and you have then it's definitely a bug.
