### ISSUE TITLE
Shift keys not working in some windows

### ISSUE THREAD

**Issue by triebelf** [swaywm/sway#1573]
I'm a new user of sway. I'm using the German NEO keyboard layout, which has
some unusual modifiers and multiple layers. It works great on Linux console and
also GDM / Gnome. With sway I have this small issue that it doesn't allow me to
type upper case letters in some windows (Firefox, Thunderbird), but works with
termite. If you need more info, please ask.

[sway_output.txt](https://github.com/swaywm/sway/files/1648797/sway_output.txt)

[config_check.txt](https://github.com/swaywm/sway/files/1648031/config_check.txt)

**Comment by kon14** [comment]
Possibly related to #1266

**Comment by ppascher** [comment]
I have the same problem using German AdNW keyboard layout.
I start sway using
`XKB_DEFAULT_LAYOUT=de XKB_DEFAULT_VARIANT=adnw XKB_DEFAULT_MODEL=pc105 sway`

I get the same error messages as @triebelf : 
```
xkbcommon: ERROR: Key "<MDSW>" added to modifier map for multiple modifiers; Using Mod3, ignoring Mod5
xkbcommon: ERROR: Key "<HYPR>" added to modifier map for multiple modifiers; Using Mod2, ignoring Mod4
xkbcommon: ERROR: Key "<LFSH>" added to modifier map for multiple modifiers; Using Lock, ignoring Shift
```
The problem only exists with XWayland Windows. Using native Wayland programs the layout works as expected. The layout also works fine using X without XWayland.
I tried various xkb options but did not find a solution so far.

**Comment by stwa** [comment]
looks like the error only tells that a key has been added to a modifier map multiple times:
https://github.com/xkbcommon/libxkbcommon/issues/44
this happens independently of x11/(x)wayland or i3/sway and should not cause any problems.
i'll try to debug this problem as i am also using the german neo layout.

**Comment by SirCmpwn** [comment]
It seems this is not a sway bug.
