### ISSUE TITLE
Document environment variables set by sway

### ISSUE THREAD

**Issue by 4e554c4c** [swaywm/sway#1575]
`sway(1)` already documents all environment variables that affect sway, but nowhere can I find what environment variables sway sets. This would help debugging problems by better defining the sway environment.

**Comment by ianyfan** [comment]
`SWAYSOCK I3SOCK WAYLAND_DISPLAY XCURSOR_SIZE XCURSOR_THEME`

**Comment by emersion** [comment]
Also `DISPLAY` for Xwayland.
