### ISSUE TITLE
gentoo + open rc - keyboard not working

### ISSUE THREAD

**Issue by vadimshv28** [swaywm/sway#1576]
Hello, I installed Sway on gentoo with open rc, it started, but my keyboard does not work. please, help.
[sway2.log](https://github.com/swaywm/sway/files/1663648/sway2.log)

**Comment by SirCmpwn** [comment]
Summoning @Hummer12007 to this thread

Are you in the input group?

**Comment by vadimshv28** [comment]
if I understood you correctly, then i use root, for run sway. Pls Im sorry my english.

**Comment by Hummer12007** [comment]
Do not use root.

**Comment by vadimshv28** [comment]
I did:
Chmod o+rwx /dev/**/*
run sway from user, and keyboard not working
![1516972312180-1055264320](https://user-images.githubusercontent.com/26827621/35441208-5a2cc4de-02ee-11e8-93f6-798af931c9d8.jpg)
and im sorry my English

**Comment by SirCmpwn** [comment]
@DarkReef maybe you can help this guy out in Russian?

**Comment by Hummer12007** [comment]
@Vadimshv28, зайди вечером в irc-канал.

**Comment by vadimshv28** [comment]
Понял. Попробую

**Comment by vadimshv28** [comment]
@Hummer12007, посмотри пожалуйста лог из под юзера, всетаки удалось через таймаут его собрать: 
https://github.com/vadimshv28/files/blob/master/sway5.log

**Comment by Hummer12007** [comment]
Хм, а почему у тебя старая версия sway? (0.15.0). В репозитории же 0.15.1

**Comment by albocc** [comment]
I don't know if you managed to solve your issue, but I just installed sway on Gentoo (with OpenRC too of course) and it works out of the box after I set the `XDG_RUNTIME_DIR` variable according to the Gentoo wiki: https://wiki.gentoo.org/wiki/Weston (section "Usage").
PS: Don't run the command `chmod o+rwx /dev/**/*` on your system. This will give every user access to all your devices! You should instead make sure what devices you need add your users to the respective groups. (For the record, I am part of the following groups: `adm wheel floppy audio cdrom video usb input users portage utmp`)

**Comment by vadimshv28** [comment]
Hi, I did not solve the problem, thanks I take your advice.
