### ISSUE TITLE
GTK dropdown items not usable

### ISSUE THREAD

**Issue by ainmosni** [swaywm/sway#1577]
Hi,

I have sway 0.15.1 running with wayland 1.14.0 on arch linux and dropdowns and context menus will appear but are not clickable. They don't show a highlight and I can't click them. The applications I have trouble with are xfce4-terminal and gnome-terminal. I can however use the menus with the keyboard. These menus work fine under gnome.

**Comment by SirCmpwn** [comment]
This is a known issue that will be fixed in the wlroots update.

**Comment by ainmosni** [comment]
Thanks, looking forward to it, just wanted to add that sway is higher quality than I expected and I'm enjoying using it.
