### ISSUE TITLE
Ubuntu 17.10 WiFi Network Problems

### ISSUE THREAD

**Issue by rschulman** [swaywm/sway#1578]
I'm running 17.10 and installed sway from the PPA. It is accessible from the gear icon in gdm and starts up great. When it first starts up, the network is operational and I can reach the internet. After a few minutes, however, the network was no longer reachable, even though `ip a` showed a working adapter with an IP assigned.

I took the wifi interface down then back up and the same thing happened: initial connection but lost after a minute or two.

I didn't get much chance to experiment further last night, but will be able to tinker with it later.

**Comment by SirCmpwn** [comment]
There is a 0% chance this is Sway's fault. Maybe GNOME starts NetworkManager for you or something.
