### ISSUE TITLE
Unable to launch sway

### ISSUE THREAD

**Issue by jni** [swaywm/sway#1580]
I use the Dvorak keyboard layout and the setting appears to be interfering with Sway launching. When I try to launch Sway from multi-user mode or from a graphical terminal, I get the following error:

```
 $ sway
xkbcommon: ERROR: Couldn't process include statement for 'macintosh_vndr/us(dvorak)'
xkbcommon: ERROR: Abandoning symbols file "(unnamed)"
xkbcommon: ERROR: Failed to compile xkb_symbols
xkbcommon: ERROR: Failed to compile keymap
01/27/18 09:21:09 - [main.c:48] [wlc] Failed to init compositor
```

When I try to launch sway from gdm, the screen flashes for a second and then I am dumped back to the gdm login screen. (I've seen others suffering from this error but the reason appeared different.)

I'm running Ubuntu Linux 17.10 on a 2013 Macbook Air.

Any ideas? Thanks!

**Comment by SirCmpwn** [comment]
gdm is not supported. What did you set your XKB environment to?

**Comment by jni** [comment]
Sorry I should have mentioned that I’m new at this, so I don’t know how to answer your question...

**Comment by SirCmpwn** [comment]
How did you specify your keyboard layout?

**Comment by 4e554c4c** [comment]
xkb settings are to be specified through environment variables to sway. See [this wiki entry](https://github.com/swaywm/sway/wiki#keyboard-layout) and `sway(5)` for more info.
For example, I'm a dvorak user who uses right-alt as an XCompose key, so I put 
```
export XKB_DEFAULT_LAYOUT=dvorak
export XKB_DEFAULT_OPTIONS=compose:ralt
```
in init files that run before sway.

**Comment by jni** [comment]
@SirCmpwn I'm not actually sure anymore, but I think I set it when initially setting up Ubuntu, since the gdm login screen is set to Dvorak.

@4e554c4c,
> the init files that run before sway

And what are those exactly? =)

But I suspect I need to disable my other settings before I can go this route...

For the record, I'd read various places that gdm was not the right way to run sway, although I've seen a couple of posts (lost the link now) saying that selecting Sway from the login settings menu worked for them. But the guide that I (roughly) followed to try to get Sway working is this one:

https://github.com/swaywm/sway/wiki/Debian-installation-guide

Specifically the line at the end to turn off the graphical login. However I still got the error above.

**Comment by hareluuu** [comment]
@jni 
`And what are those exactly? =)`

In this case I'm guessing it would be .bash_profile or a custom file that is made to auto-run on startup

There's some troubleshooting help and info here: https://wiki.archlinux.org/index.php/Sway that mentions .bash_profile and .zprofile as files to use for setting the keyboard layout. The wiki is centered on arch but the general commands and tips are mostly system-agnostic in this case.

**Comment by jni** [comment]
Thanks @SirCmpwn @4e554c4c @hareluuu for your help so far. At one point I'd like to be able to specify automatically booting into Sway, but right now I can't even boot into it manually. As mentioned before, I booted into the multi-user.target, and running `sway` with or without some XKB prefixes results in the same error (see attachment). As @SirCmpwn hinted, probably there is some keyboard layout call that is incompatible with Sway being run when Sway launches (something to do with Wayland launching?), but I have no idea how to turn it off. Any further ideas would be much appreciated!

![image](https://user-images.githubusercontent.com/492549/35547543-be8666ba-05cd-11e8-9353-809aac342342.jpeg)

**Comment by jni** [comment]
As another aside, @SirCmpwn, the Archlinux Sway wiki that has been referred to multiple times already (https://wiki.archlinux.org/index.php/Sway) points to GDM being able to pick up Sway at least in some cases. In my install I believe it's picking it up correctly but then running into the above problem when trying to launch it.

**Comment by hareluuu** [comment]
Can you try exporting `XKB_DEFAULT_LAYOUT=dvorak` instead of `XKB_DEFAULT_VARIANT`?

As for booting directly into desktop, it can be done with GDM by modifying `/etc/gdm/custom.conf` as explained here: https://wiki.archlinux.org/index.php/GDM#Automatic_login

I'm not really sure how to do this without a login manager in wayland and Google hasn't been helpful, so I hope someone else chimes in.

**Comment by cafehaine** [comment]
to automatically start sway without a login manager, you should use something like
https://wiki.archlinux.org/index.php/Getty#Automatic_login_to_virtual_console
and then a .bashrc (or whatever your shell is) with the following lines:
```
# If running trom tty1 start sway
if [ $(tty) == "/dev/tty1" ]; then
	sway
	exit 0
fi
```

**Comment by hareluuu** [comment]
@cafehaine sorry for off-topic but thank you so much, I remember looking for a way to do this for days and just giving up and using a login manager.

**Comment by SirCmpwn** [comment]
Closing since login managers are not supported
