### ISSUE TITLE
Debian Install Instructions: huge download

### ISSUE THREAD

**Issue by rolfen** [swaywm/sway#1581]
I have followed the [Debian Installation Guide](https://github.com/swaywm/sway/wiki/Debian-installation-guide):

Below "Finally, we can install sway itself.", there is a command to install sway build dependencies:

```
sudo apt-get install libpcre3 libpcre3-dev libcairo2 libcairo2-dev libpango1.0-0 libpango1.0-dev asciidoc libjson-c3 libjson-c-dev libcap-dev xsltproc libpam0g-dev
```

This would need about 1GB of free space, and download hundreds of megabytes.
I have added `-o APT::Install-Suggests=0 -o APT::Install-Recommends=0` to the command, to disable all suggested or recommended package, and gotten the space requirements down to 33MB, and command completes quickly.

Using that, sway compiles OK and seems to run OK, although I never ran it before, so I cannot be certain whether anything is missing.

I suggest amending the instructions.

**Comment by SirCmpwn** [comment]
The thing about wikis is that anyone can edit them

**Comment by rolfen** [comment]
OK. However I am not very familiar with the compilation process, and with compiling software in general.

It compiles without errors (they might have been warnings). I didn't find any tests.

Is it reasonably safe to skip installing optional and recommended dependencies? Should I be worried about unforseen consequences?

**Comment by rolfen** [comment]
I missed that part where it says that the instructions are community maintained.
However a second opinion would still be welcome.
