### ISSUE TITLE
Track focus throughout the tree for each seat

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/sway#1582]
If I switch from workspace 1 to workspace 2, open some windows, switch back to 1, then back to 2, whatever I left as the focus should become focused again. This used to be trivial - each container just kept a `swayc_t *focused` which we'd traverse down the tree and find whatever used to be focused on that workspace. We'll have to figure out something to do with mutliple seats here. Remember that seats can be added/removed at runtime.

**Comment by Timidger** [comment]
Not sure if this is useful in regards to multiple seats, but the way Way Cooler handles it is we keep an "active" number that's stored on each edge in the tree (see [here](https://github.com/way-cooler/way-cooler/blob/master/src/layout/core/path.rs)). 

This also allows us to delete a container and it will refocus the last one that was focused within that group by finding the next container with the lowest number in that container (something which i3 handles but Sway currently doesn't AFAIK).

**Comment by SirCmpwn** [comment]
Grep for "TODO FOCUS" to find a bunch of shit I've littered around regarding this.

**Comment by SirCmpwn** [comment]
Plan for fixing this:

Seats were designed with only ever focusing views in mind, but in practice will need to be able to focus any kind of container. I want seats to be the source of truth for what container is currently focused, even if they aren't doing any input dispatching to it or whatever.

We need to be able to walk focus both up and down the tree. For example, when we destroy a view, we need to walk up to transfer focus to its parent - seat should handle this automatically. When we move to a new workspace, we need to walk down the tree to find out what was last focused on that workspace. Consider this situation, where `V` indicates `focused child` and `.` indicates `unfocused child`:

```
    root container
          |
          V
        output
         /  \
        V    .
workspace    workspace
    |          /  \
    V         .    V
 window   window  container
                   /    \
                  V      .
               window  window
```

In this situation, the left workspace's window is focused. If we move from the first workspace to the second, we need to resume focus all the way down to that leaf.

Given that we need to (1) find the focused container of a seat and (2) track old paths down the focus tree, we keep the `focused` pointers up to date in the tree and have seats point to whatever they have focused. This gets complicated when we have several seats, because a container may have >1 focused child. To solve this, we should have a separate tree of focus for each seat, which is referenced whenever switching to a workspace on behalf of a seat.

**Comment by acrisci** [comment]
Can you elaborate on the focus tree? Is it private to the seat? Does it have its own data structure independent of the containers? How might it get updated when the structure of the tree changes?

**Comment by SirCmpwn** [comment]
I was thinking the seat owns it, given that the seat owns focus in general. It has its own data structure separate from the containers, and I think we'll want to make some kind of destruction signal for swayc_t that it can use to handle their removal.

**Comment by SirCmpwn** [comment]
I'm not 100% sure on the approach here, be creative.
