### ISSUE TITLE
Variable interpolation in `swaymsg` not working

### ISSUE THREAD

**Issue by nwallace** [swaywm/sway#1586]
I'm not able to use variables with swaymsg in my config file.

I think this is the same issue as [this one](https://github.com/swaywm/sway/issues/1349), so if you'd rather re-open that one and move the conversation there, go for it.

Anyway, the issue is that I can't use a variable in a call to swaymsg from inside my config file.

I'm trying to launch some applications on certain workspaces on login. Here's the gist of the issue:

```
set browser firefox
set messenger riot-desktop

exec swaymsg "workspace 1; exec $browser"
exec swaymsg "workspace 2; exec $messenger"
```

In the debug logs I see that it's not interpolating the variable. Is there a way to escape it in the string so that it will interpolate?

I also tried `exec swaymsg "workspace 1; exec" $browser` like `echo` syntax, but that didn't work either.

Is this supported and I just missed the documentation, or is this a bug?

**Comment by SirCmpwn** [comment]
This is currently by design, it matches the behavior of i3. However, we intend to change it. The ticket for this is here: https://github.com/swaywm/sway/issues/548
