### ISSUE TITLE
closing window in scratchpad makes sway crash

### ISSUE THREAD

**Issue by chep** [swaywm/sway#1587]
I can reproduce it easily:

Open terminal
move to scratchpad
Open an other terminal
move to scratchpad

Now I'm able to switch between the two terminals with "scratchpad show"

Use "exit" command in one of the two terminals
scratchpad show => sway crashes

**Comment by SirCmpwn** [comment]
The scratchpad is due for an overhaul soon.

**Comment by chep** [comment]
Ok,

I have no debug information but it's look like a recursive loop. gdb gives me
huge backtrace. More than 3k calls to ipc_json_describe_container_recursive

**Comment by SirCmpwn** [comment]
"Overhaul" means your debug information isn't necessary anyway - we're going to completely rewrite the scratchpad from, err, scratch.
