### ISSUE TITLE
IPC query to list seats

### ISSUE THREAD

**Issue by acrisci** [swaywm/sway#1589]
Create an ipc command to list seats and get info.

Example:

```
swaymsg -t get_seats
```

It should return seat info like what devices are attached, the currently focused container, and the name of the seat.

Possibly like this:

```json
[
  {
    "name": "seat0",
    "focused": "ID",
    "devices": [
      "1234:5687:Some_Keyboard",
      "8489:9582:Some_Mouse"
    ]
  }
]
```

**Comment by ianyfan** [comment]
What does this still require?

**Comment by SirCmpwn** [comment]
To be implemented in the first place?

**Comment by ianyfan** [comment]
It is? I can run `swaymsg -t get_seats` just fine.

**Comment by SirCmpwn** [comment]
Oh so it seems
