### ISSUE TITLE
Warning in detect_proprietary()

### ISSUE THREAD

**Issue by sudo97** [swaywm/sway#1594]
I am using nouveau, but code in detect_proprietary detects nvidiafb as nvidia driver. And prints Warning about it. But nvidiafb is only: "Framebuffer driver for nVidia graphics chipset".
the check for strstr("nvidiafb", "nvidia") returns true seomehow, so it has to be fixed

**Comment by sudo97** [comment]
well if I swap those strings it does not return true on nvidiafb(which is logical), but what if some nvi module exists, it would return true in this case.

Why not use strcmp?

**Comment by SirCmpwn** [comment]
We can just change it to strncmp(line, "nvidia ", 7)
