### ISSUE TITLE
Unable to compile sway on archlinux with json-c 0.13

### ISSUE THREAD

**Issue by DarkReef** [swaywm/sway#1599]
After update json-c from 0.12.1 to 0.13.1 sway can't be complied due to code conflict in newer version and cmake require:
- `find_package(JsonC 0.12.1 REQUIRED)`

Rollback on older version json-c can (and probably would) cause kernel panic on reboot.
Would sway migrate on json-c 0.13?

**Comment by martinetd** [comment]
json-c won't ever cause a kernel panic, but this already has been done in the 0.15 and wlroots branches anyway - please use the 0.15 branch.

**Comment by DarkReef** [comment]
@martinetd oh, my bad. Thanks.
