### ISSUE TITLE
Segfault when brushing over mousepad

### ISSUE THREAD

**Issue by jhalmen** [swaywm/sway#1600]
Had some dust on my mousepad, wanted to wipe it off, used 4 fingers for it. As they came off the mousepad one by one sway crashed.
can't reproduce every time, fingers seem to need to slide off just the right way.
using sway 0.15.1

error message:
../libinput-1.10.0/src/evdev-mt-touchpad-tap.c:1073: tp_tap_handle_state: Assertion `tp->tap.nfingers_down <= tp->nfingers_down' failed.

**Comment by 4e554c4c** [comment]
Sounds like a race in libinput. This doesn't sound like sway's fault.

**Comment by jhalmen** [comment]
managed to reproduce in weston, so i guess it can't be sways fault

**Comment by SirCmpwn** [comment]
Yeah, report to libinput.
