### ISSUE TITLE
Previous windows become laggy after killing swaylock

### ISSUE THREAD

**Issue by albocc** [swaywm/sway#1606]
Sometimes it happens that `swaylock` locks the screen but I am not able to enter the password. In those situations I switch to a different `tty`, log in there and kill the `swaylock` process, log out of that `tty` and switch back to `tty7`.

However, now all the previous windows (e.g. Firefox, Thunderbird or URxvt) cause the mouse cursor to become laggy (i.e. rendered at a very slow framerate like 10 fps). If I switch to a different workspace or open new windows, the cursor will work properly there.

Opening new windows after killing `swaylock` also causes artifacts over other windows sometimes, even on other screens, which I am only able to "remove" by resizing the corresponding windows by making them float and then tile again for example.

I am using sway version 0.15.1 and I launch `swaylock` via a custom mode in the configuration file like this:

    set $Locker swaylock -c aaaaaa
    set $mode_system System (l) lock, (e) logout, (s) suspend, (h) hibernate, (r) reboot, (Shift+s) shutdown
    mode "$mode_system" {
        bindsym l exec --no-startup-id $Locker, mode "default"
    }

**Comment by SirCmpwn** [comment]
I'm closing issues that are resolved by the yet-unrelated sway 1.0.
