### ISSUE TITLE
High CPU usage on cursor movement (over Xwayland windows only?)

### ISSUE THREAD

**Issue by albocc** [swaywm/sway#1607]
I noticed that when I keep moving my cursor over any window the CPU usage on my Core i7-4790K rises to around 35% (of a single core that is).

I observed this with Firefox, Thunderbird and also URxvt. However, this doesn't happen on an empty workspace where I am only moving my cursor over the wallpaper. This might indicate that it's only affecting windows rendered via Xwayland but I might be wrong.

I am running sway version 0.15.1 on Gentoo.

**Comment by iH8c0ff33** [comment]
I also get that and the cursor is really slow, as well as videos in firefox

**Comment by jannispinter** [comment]
I'm facing the exact same issue.

**Comment by JakeHedman** [comment]
Same thing happens to me but also on empty workspaces. Also version 0.15.1 but on Arch.

**Comment by SirCmpwn** [comment]
This will be fixed by the wlroots port.

**Comment by SirCmpwn** [comment]
I'm closing issues that are resolved by the yet-unrelated sway 1.0.
