### ISSUE TITLE
[Feature request] Screen recording/sharing with PipeWire

### ISSUE THREAD

**Issue by Sunderland93** [swaywm/sway#1612]
PipeWire is a new multimedia server, formerly known as "PulseAudio for video". It allows to screen recording/sharing in Wayland (and also remote desktop), and needed for sandboxed apps, e.g. Flatpak. See https://github.com/PipeWire/pipewire/

P.S. sorry for my english

**Comment by ascent12** [comment]
This is more of a wlroots problem.
It's been discussed briefly, but nothing has been decided yet.

**Comment by SirCmpwn** [comment]
We have implemented a screen capture protocol, it's up to someone else to plug this into pipewire now.

**Comment by Sunderland93** [comment]
@SirCmpwn this protocol is being proposed to wayland-protocols?

**Comment by SirCmpwn** [comment]
Well, we'll get there eventually.

**Comment by emersion** [comment]
For those interested, this project aims to implement PipeWire support: https://github.com/emersion/xdg-desktop-portal-wlr
