### ISSUE TITLE
title bar missing when focused on tab with split container with borderless children

### ISSUE THREAD

**Issue by mathroc** [swaywm/sway#1618]
in this example I have a tabbed container, the 3rd tab is a vertically split container with two borderless window inside

when I'm on the first tab I have this:

![2018-03-07_01 49 49](https://user-images.githubusercontent.com/291531/37067437-0ed41296-21aa-11e8-90ad-c5200d3667a3.png)

and when I switch to the 3rd tab I have this:

![2018-03-07_01 47 55](https://user-images.githubusercontent.com/291531/37067449-1c726de4-21aa-11e8-916a-f35720f58f0d.png)

I expect to either still show the tabs title bar or at least not reserve the space at all

note: I just realized all children don't need to be borderless for this to happen: only the one with the focus

**Comment by SirCmpwn** [comment]
I'm closing issues that are resolved by the yet-unrelated sway 1.0.
