### ISSUE TITLE
Crash: Mouse movement btwn monitors into an XWayland window

### ISSUE THREAD

**Issue by probitlabs** [swaywm/sway#1619]
##### Bug Report:
Currently using `v0.15.1` on NixOS unstable, Sway crashes approximately every 10th time I try switching between monitors per mouse (means: moving beyond the 2nd monitors edge).

When this happens, all windows stay on their position, but the whole graphical user interface doesn't respond to keyboard respectively mouse inputs any more. Also, the cursor sticks on the 2nd monitor.

If I then try to reload the configuration (using `Mod+Shift+c`), I'm not even able to exit Sway in any way, so then only reboot helps.

Sway is my default compositor, so specifically this bug tarnishes my workflow every few minutes the last weeks.

##### My Configuration:
```
[…]

output eDP-1 scale 1
output eDP-1 res 3840x2160 pos 0,135
output HDMI-A-2 scale 1
output HDMI-A-2 res 3840x2160 pos 3840,0

workspace "0:tty"
workspace "0:tty" output eDP-1
[…]
           
workspace "4:ttx"
workspace "4:ttx" output HDMI-A-2
[…]
```

##### Nix Setup:
```
[…]
    programs.sway = {
        enable = true;
        extraPackages = (with pkgs; [
	    xwayland rxvt_unicode termite i3lock
	]);
    };
[…]
```

**Comment by probitlabs** [comment]
##### Update:

It can be reproduced by:

1) Using a current (*since when?*) Sway version
2) Shifting the output's positioning normal towards the orientation. (by `135`, in my case)
3) Sliding along the partly "died" and partly "monitor-jumping" edge of the screen on a monitor. (from the upper-left-hand corner down, in my case)
4) Now Sway's dead. (You can't do something compositor respectively input related)

##### Ascii Visualization:

```
     !--Slide on that edge--
      \ v /
       .______.
       |v     |
.______|v     | << MONITOR 2
|      |<_____|
| MONI | TOR1
|______|
```

---

##### Edit:
It seems to **only** go wrong if `MONITOR1` is currently displaying an *XWayland window*.

It seems to also happen when the output's positioning is not even shifted; when I move the cursor from the upper-left-hand corner downwards—but using just the `pos 0,0` shift for the 2nd monitor—, I can also reproduce the error.

**Comment by SirCmpwn** [comment]
Can you reproduce this with sway 1.0-alpha.4?
