### ISSUE TITLE
titlebar from window in other tabs are still active

### ISSUE THREAD

**Issue by mathroc** [swaywm/sway#1621]
if I click on the position of a window titlebar that is in another tab, it switches to that tab and focus the window

eg: on a workspace I have two tabs: the first one contains firefox fullscreen, and the second one 4 terminal windows, sometimes when clicking around in firefox I'm taken to one of the terminal because I click at the same spot the titlebar of the terminal would have been if the tab with the terminal windows was active. it's quite surprising

**Comment by SirCmpwn** [comment]
I'm closing issues that are resolved by the yet-unrelated sway 1.0.
