### ISSUE TITLE
Only can execute Sway inside an i3 session

### ISSUE THREAD

**Issue by southern-tools** [swaywm/sway#1627]
Cannot execute Sway directly from tty
I attached the result of sway -dV 2> ~/sway.txt

[sway.txt](https://github.com/swaywm/sway/files/1832325/sway.txt)

Thank you for your help,

Diego

**Comment by SirCmpwn** [comment]
@Hummer12007 

looks like GPU drivers are misinstalled or something

**Comment by comunity-tools** [comment]
Thank you for your response, drivers seem to be ok but I don't realize what is failing

**Comment by Hummer12007** [comment]
@comunity-tools
0) Do you have mesa installed?
1) `emerge --info`
2) `emerge --info sway`

**Comment by comunity-tools** [comment]
0. Yes, I have mesa. Here the info about portage and sway:

1. [emerge_info.log](https://github.com/swaywm/sway/files/1834739/emerge_info.log)

2. [emerge_info_sway.log](https://github.com/swaywm/sway/files/1834740/emerge_info_sway.log)

Thank you for your help
