### ISSUE TITLE
0.15.2?

### ISSUE THREAD

**Issue by ghost** [swaywm/sway#1644]
When Sway 0.15.2 will got released? Thanks.

Here's my vision for dislikers.
After 0.15.0 there was a promise that next release will be 1.0 wlroots, HOWEVER there were fixes to wlc version, so 0.15.1 was released as intermediate release with thoose fixes.
Likewise there were more fixes merged after 0.15.1 to wlc branch and they should similarly form 0.15.2

**Comment by 7415963987456321** [comment]
They are currently on a two week, hackathon, I reckon the next release will be 1.0 or some RC before that.

**Comment by peeevo** [comment]
Here's my vision for dislikers.
After 0.15.0 was 1.0 promised, but there were fixes to wlc version, so 0.15.1 was released with them instead.
Likewise there were more fixes merged after 0.15.1 to wlc (non wlroots) version and they similarly should get into 0.15.2

**Comment by emersion** [comment]
0.15.2 has been released https://github.com/swaywm/sway/releases/tag/0.15.2
