### ISSUE TITLE
Reloading config doesn't set new modes/scale/etc

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/sway#1656]

**Comment by emersion** [comment]
Cannot reproduce anymore, likely fixed in the last 7 days.

**Comment by SirCmpwn** [comment]
```
output X11-1 scale 2
```

Start sway, edit config to remove that line, reload

Probably not wlroots-specific

**Comment by emersion** [comment]
Hum, I'm not sure how to fix this. Not specifying an ouput option means "don't change it".

**Comment by SirCmpwn** [comment]
At runtime, sure. At reload time we should probably reset everything imo.

**Comment by emersion** [comment]
#1752
