### ISSUE TITLE
Update pointer when windows move under them

### ISSUE THREAD

**Issue by acrisci** [swaywm/sway#1663]
To reproduce:

Move windows with the keyboard commands and make sure the cursor updates to reflect whatever surface it is under.

The underlying issue is that we don't send pointer enter/leave events to the new surface under the cursor.

A simple test case is to open two gnome terminals and call `layout splith` and `layout splitv` with the cursor in a position so that it is over a ttilebar in one of the layouts and the i-beam on the other. You'll notice that the cursor does not switch from leftptr to i-beam as it should once the windows are rearranged.

**Comment by SirCmpwn** [comment]
This seems premature given that #1601 isn't even merged
