### ISSUE TITLE
update focus-inactive on window close

### ISSUE THREAD

**Issue by acrisci** [swaywm/sway#1670]
When a window closes, the focus-inactive list should be updated to reflect the window closing.

For instance, if you switch workspaces, and open a window on that workspace, and then that window closes, focus-inactive should be reverted to the visible workspace and not the previous workspace.

The function `workspace_is_visible()` will not work correctly without this feature.

I think it will be enough to replace the window with the next focus inactive of the parent, or the parent itself in this case, but that will need some testing.

**Comment by RyanDwyer** [comment]
Looks like this was fixed in #1769.
