### ISSUE TITLE
Can't open after setting caps

### ISSUE THREAD

**Issue by vitorhugomattos** [swaywm/sway#1679]
I did a fresh install of Sway and everything was working, but it was very laggy, so I installed Xorg video drivers for my AMD GPU (using the radeon open source driver, should I try with the amdgpu open driver, maybe?) and lag was gone.

But, after installing video driver, the swaybar gone away with the lag… So I came to search for a solution. I tried to setcaps for Sway binary and now can't open it anymore. It returns this:

```
E: 03/31/18 10:32:28 - [main.c:285] sway executable has both the s(g)uid bit AND file caps set.
E: 03/31/18 10:32:28 - [main.c:287] This is strongly discouraged (and completely broken).
E: 03/31/18 10:32:28 - [main.c:289] Please clear one of them (either the suid bit, or the file caps).
E: 03/31/18 10:32:28 - [main.c:291] If unsure, strip the file caps.
```

What should I do? Readme tells me to do that, but binary tells to do not. And if it works, I don't think it will make swaybar work again too.

~ yep, i'm not good at english ~

**Comment by SirCmpwn** [comment]
What distro?

**Comment by vitorhugomattos** [comment]
Void Linux. I managed to get sway working (and swaybar too) by reinstalling it, but without the capabilities I can't change tty, right?

**Comment by SirCmpwn** [comment]
Right. TTY switching is not supported without logind (or elogind).

**Comment by vitorhugomattos** [comment]
Yes, that is because I installed elogind instead of ConsoleKit, but now I need to set the capabilities. I will do some tests and take conclusions after... Is the `cap_sys_ptrace` really necessary? They've been set correctly? I'll return the responses here later.

**Comment by SirCmpwn** [comment]
Follow the instructions in the readme for use with logind.
