### ISSUE TITLE
Drop wl_shell support

### ISSUE THREAD

**Issue by emersion** [swaywm/sway#1692]
No one uses it, it's deprecated, and we have no way to test it.

It's just an issue to track the progress of this.

**Comment by emersion** [comment]
Ref https://github.com/hdante/hello_wayland/issues/5

**Comment by Bob131** [comment]
I have to contest the notion that "no one uses it". The Wayland-EGL backend in [Cogl](https://cogl3d.org) relies on it specifically, and removal of support for it in Sway breaks anything that depends on it (and subsequently anything that uses [Clutter](https://wiki.gnome.org/Projects/Clutter)).

**Comment by ddevault** [comment]
Nothing *should be* using it. It's deprecated. They should be patched.

**Comment by Bob131** [comment]
I don't disagree, but unfortunately Cogl is both a major piece of infrastructure in GNOME land and currently on life support.

Regardless of whether it should or shouldn't be, wl_shell is still very much in use.

**Comment by aparcar** [comment]
Am I right that this issue stop the mail client Evolution from running?

> Failed to initialize gtk+: Unable to initialize the Clutter backend: no available drivers found.

**Comment by emersion** [comment]
Evolution works for me. Do you have an old version of Evolution?

**Comment by Sunderland93** [comment]
Is `wl_shell` usefull on non-desktop systems?

**Comment by ddevault** [comment]
No. `wl_shell` was not dropped because it is not useful, but because it is broken. A new protocol should be written for non-desktop systems if xdg-shell is not a good fit.
