### ISSUE TITLE
broken SNI

### ISSUE THREAD

**Issue by vitorhugomattos** [swaywm/sway#1694]
every sway intance returns
```
E: 03/31/18 23:33:28 - [sni_watcher.c:443] Connection is null, cannot initiate StatusNotifierWatcher E: 03/31/18 23:33:28 - [tray.c:205] Connection is null, cannot init SNI host
```
when started.

complete stderr with debug flag enabled: https://paste.rs/ZoP

**Comment by 4e554c4c** [comment]
If DBus isn't running then swaybar can't start the tray. This isn't a bug.

**Comment by vitorhugomattos** [comment]
dbus service is running. it's actived by runit and all the other processes that require dbus-daemon (i.e., pulseaudio, elogind etc.) are working.

![:)](https://i.imgur.com/3v5Mwrn.png)

**Comment by vitorhugomattos** [comment]
rly, it`s working fine with ```dbus-launch sway``` x-P
