### ISSUE TITLE
How to use assign?

### ISSUE THREAD

**Issue by acklackl** [swaywm/sway#1695]
In i3 we could use xprops to find the window class name and use

assign[class="classname"] workspace 1

But in wayland, xprop wouldn't work. How could we use assign in swaywm?

**Comment by SirCmpwn** [comment]
`man 5 sway` to learn about available criteria

`swaymsg -t get_tree` to see properties of containers in your session

**Comment by tmccombs** [comment]
`swaymsg -t get_tree` works, but it's certainly not as easy to find the app you care about in the json output as clicking on a window with xprop.

**Comment by emersion** [comment]
Shouldn't be too hard to use slurp to get a coordinate and then a little script to iterate over the tree and get the container under the cursor.

**Comment by ammgws** [comment]
@tmccombs Just wrote a quick (fish) script [here](https://github.com/ammgws/dotfiles/commit/fc2693769632c56c7a9f6f7d4282362f45dd3600) that does that if you are interested.

**Comment by markstos** [comment]
Here's link to a newer version of the fish script above with some fixes

**Comment by tmccombs** [comment]
I also wrote a python script to do this [here](https://github.com/tmccombs/swaytools/). It's the `swayinfo` script.
