### ISSUE TITLE
wlr: crash starting steam

### ISSUE THREAD

**Issue by 4e554c4c** [swaywm/sway#1728]
Looks like a heap corruption to me, hard to reproduce but the following might be the cause:
<details>
<p>
<pre>
==12188== Invalid write of size 8
==12188==    at 0x5F75137: wl_list_remove (in /usr/lib/libwayland-server.so.0.1.0)
==12188==    by 0x12AD85: handle_destroy (xwayland.c:129)
==12188==    by 0x4E93641: wlr_signal_emit_safe (signal.c:29)
==12188==    by 0x4E55C35: wlr_xwayland_surface_destroy (xwm.c:216)
==12188==    by 0x4E56C99: xwm_handle_destroy_notify (xwm.c:601)
==12188==    by 0x4E57A10: x11_event_handler (xwm.c:1036)
==12188==    by 0x5F729B1: wl_event_loop_dispatch (in /usr/lib/libwayland-server.so.0.1.0)
==12188==    by 0x5F7114B: wl_display_run (in /usr/lib/libwayland-server.so.0.1.0)
==12188==    by 0x110DC6: server_run (server.c:129)
==12188==    by 0x1106FB: main (main.c:414)
==12188==  Address 0x17914360 is 128 bytes inside a block of size 264 free'd
==12188==    at 0x4C2E10B: free (vg_replace_malloc.c:530)
==12188==    by 0x4E8739A: destroy_surface (wlr_surface.c:632)
==12188==    by 0x5F70C11: ??? (in /usr/lib/libwayland-server.so.0.1.0)
==12188==    by 0x5F70C61: wl_resource_destroy (in /usr/lib/libwayland-server.so.0.1.0)
==12188==    by 0x4E85A07: surface_destroy (wlr_surface.c:48)
==12188==    by 0x92641C7: ffi_call_unix64 (in /usr/lib/libffi.so.6.0.4)
==12188==    by 0x9263C29: ffi_call (in /usr/lib/libffi.so.6.0.4)
==12188==    by 0x5F747FC: ??? (in /usr/lib/libwayland-server.so.0.1.0)
==12188==    by 0x5F70F78: ??? (in /usr/lib/libwayland-server.so.0.1.0)
==12188==    by 0x5F729B1: wl_event_loop_dispatch (in /usr/lib/libwayland-server.so.0.1.0)
==12188==    by 0x5F7114B: wl_display_run (in /usr/lib/libwayland-server.so.0.1.0)
==12188==    by 0x110DC6: server_run (server.c:129)
==12188==  Block was alloc'd at
==12188==    at 0x4C2EEF5: calloc (vg_replace_malloc.c:711)
==12188==    by 0x4E873BC: wlr_surface_create (wlr_surface.c:637)
==12188==    by 0x4E7169E: wl_compositor_create_surface (wlr_compositor.c:33)
==12188==    by 0x92641C7: ffi_call_unix64 (in /usr/lib/libffi.so.6.0.4)
==12188==    by 0x9263C29: ffi_call (in /usr/lib/libffi.so.6.0.4)
==12188==    by 0x5F747FC: ??? (in /usr/lib/libwayland-server.so.0.1.0)
==12188==    by 0x5F70F78: ??? (in /usr/lib/libwayland-server.so.0.1.0)
==12188==    by 0x5F729B1: wl_event_loop_dispatch (in /usr/lib/libwayland-server.so.0.1.0)
==12188==    by 0x5F7114B: wl_display_run (in /usr/lib/libwayland-server.so.0.1.0)
==12188==    by 0x110DC6: server_run (server.c:129)
==12188==    by 0x1106FB: main (main.c:414)
==12188== 
==12188== Invalid write of size 8
==12188==    at 0x5F7513F: wl_list_remove (in /usr/lib/libwayland-server.so.0.1.0)
==12188==    by 0x12AD85: handle_destroy (xwayland.c:129)
==12188==    by 0x4E93641: wlr_signal_emit_safe (signal.c:29)
==12188==    by 0x4E55C35: wlr_xwayland_surface_destroy (xwm.c:216)
==12188==    by 0x4E56C99: xwm_handle_destroy_notify (xwm.c:601)
==12188==    by 0x4E57A10: x11_event_handler (xwm.c:1036)
==12188==    by 0x5F729B1: wl_event_loop_dispatch (in /usr/lib/libwayland-server.so.0.1.0)
==12188==    by 0x5F7114B: wl_display_run (in /usr/lib/libwayland-server.so.0.1.0)
==12188==    by 0x110DC6: server_run (server.c:129)
==12188==    by 0x1106FB: main (main.c:414)
==12188==  Address 0x17914358 is 120 bytes inside a block of size 264 free'd
==12188==    at 0x4C2E10B: free (vg_replace_malloc.c:530)
==12188==    by 0x4E8739A: destroy_surface (wlr_surface.c:632)
==12188==    by 0x5F70C11: ??? (in /usr/lib/libwayland-server.so.0.1.0)
==12188==    by 0x5F70C61: wl_resource_destroy (in /usr/lib/libwayland-server.so.0.1.0)
==12188==    by 0x4E85A07: surface_destroy (wlr_surface.c:48)
==12188==    by 0x92641C7: ffi_call_unix64 (in /usr/lib/libffi.so.6.0.4)
==12188==    by 0x9263C29: ffi_call (in /usr/lib/libffi.so.6.0.4)
==12188==    by 0x5F747FC: ??? (in /usr/lib/libwayland-server.so.0.1.0)
==12188==    by 0x5F70F78: ??? (in /usr/lib/libwayland-server.so.0.1.0)
==12188==    by 0x5F729B1: wl_event_loop_dispatch (in /usr/lib/libwayland-server.so.0.1.0)
==12188==    by 0x5F7114B: wl_display_run (in /usr/lib/libwayland-server.so.0.1.0)
==12188==    by 0x110DC6: server_run (server.c:129)
==12188==  Block was alloc'd at
==12188==    at 0x4C2EEF5: calloc (vg_replace_malloc.c:711)
==12188==    by 0x4E873BC: wlr_surface_create (wlr_surface.c:637)
==12188==    by 0x4E7169E: wl_compositor_create_surface (wlr_compositor.c:33)
==12188==    by 0x92641C7: ffi_call_unix64 (in /usr/lib/libffi.so.6.0.4)
==12188==    by 0x9263C29: ffi_call (in /usr/lib/libffi.so.6.0.4)
==12188==    by 0x5F747FC: ??? (in /usr/lib/libwayland-server.so.0.1.0)
==12188==    by 0x5F70F78: ??? (in /usr/lib/libwayland-server.so.0.1.0)
==12188==    by 0x5F729B1: wl_event_loop_dispatch (in /usr/lib/libwayland-server.so.0.1.0)
==12188==    by 0x5F7114B: wl_display_run (in /usr/lib/libwayland-server.so.0.1.0)
==12188==    by 0x110DC6: server_run (server.c:129)
==12188==    by 0x1106FB: main (main.c:414)

**Comment by 4e554c4c** [comment]
Also rendering is really weird, but that's probably another issue

**Comment by emersion** [comment]
Bump: can you try again?

**Comment by SirCmpwn** [comment]
It works for me but I noticed some issues - sway doesn't rearrange the layout when it makes new windows, so their size isn't right. If you switch between workspaces or otherwise trigger a layout update it fixes the sizes.

**Comment by emersion** [comment]
Works for me too.
