### ISSUE TITLE
Complete resize command

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/sway#1737]
* [x] `resize grow|shrink width|height [<amt>] [px | ppt]`
* [x] `resize grow|shrink <direction> <px> px or <ppt> ppt`
* [x] `resize grow|shrink left|right|up|down`
* [x] `resize set <width> [px | ppt] <height> [px | ppt]`

**Comment by meakio** [comment]
I will try to do it this week.
I need to understand `resize grow|shrink width|height [<amt>] [px | ppt]` and how these commands operate in i3.
