### ISSUE TITLE
splitting a container as a child of a workspace should wrap a container around it

### ISSUE THREAD

**Issue by acrisci** [swaywm/sway#1749]
Calling `layout splitv` on a child of the workspace should wrap a container around it. The wrapping container should have the layout that is called in the command. This is to allow the workspace to return to its default layout when all the windows are closed. Right now, sway keeps the layout of the last layout assigned to a child container until the layout command is called again with a different layout.

[test](https://github.com/swaywm/sway-tests/blob/d98fe4bd9b0bcdc02e300eb4f63ca445715a5cfd/test/test_layout.py#L34-L56)

**Comment by RedSoxFan** [comment]
This appears to have been resolved at some point
