### ISSUE TITLE
Move command improvements

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/sway#1764]
* [Can open nested containers perpetually](https://github.com/swaywm/sway/pull/1700#issuecomment-379369056)
* [This problem](https://github.com/swaywm/sway/pull/1700#issuecomment-379367452)

**Comment by emersion** [comment]
>Can open nested containers perpetually

I've fixed that

**Comment by SirCmpwn** [comment]
Woohoo

**Comment by SirCmpwn** [comment]
I think this is good now.
