### ISSUE TITLE
Backport swaybar tray support

### ISSUE THREAD

**Issue by emersion** [swaywm/sway#1768]

**Comment by mckinney-subgraph** [comment]
Hey,

After discussing with @SirCmpwn and @emersion on IRC, I have started working on this. The first phase will be to re-implement the SNI dbus protocol using the *sd-bus* API. I'll add this as a first item to the task list.

I am also still reading through the tray code and looking at the efforts already undertaken so I will update this task list as I progress. If other people have some tasks in mind, please add them to the issue.

- [ ] Implement SNI dbus protocol using sd-bus

**Comment by SirCmpwn** [comment]
cc @4e554c4c

**Comment by skrps** [comment]
Is this being worked on?

I have a (not naïve, I hope) question: is it *really* necessary to
implement tray support using sd-bus API?  AFAIK, it is not present in
non-SystemD distros and could be a problem for those who want this
feature.

There is some project similar to eudev or elogind, but for sd-bus, that
I am not aware of?

**Comment by SirCmpwn** [comment]
This is not being worked on, feel free to adopt it. elogind ships with sd-bus.

**Comment by SirCmpwn** [comment]
Also, for the record, tray support should be compile-time optional.

**Comment by mckinney-subgraph** [comment]
Actually, I will submit a pull request for "minimal viable SNI" at some point during this week.

**Comment by mckinney-subgraph** [comment]
Err yeah, sorry :(. I had the "minimal viable SNI" patch in the works but ran into troubles getting it working with the event loop code and then my free time evaporated. I am happy to continue to working on this when I have some spare time but can't give an ETA.

**Comment by SirCmpwn** [comment]
Can you post the WIP patch so someone else doesn't have to start from scratch?

**Comment by mckinney-subgraph** [comment]
@SirCmpwn Sure, can do.

**Comment by SirCmpwn** [comment]
Thanks!

**Comment by 4e554c4c** [comment]
I can also work on this if sd-bus isn't a requirement

**Comment by SirCmpwn** [comment]
I don't think the old code is very maintainable. I know it's my fault for pushing back against sd-bus before. I'd rather not port it as-is, I think it'd be better to refactor it.

**Comment by SirCmpwn** [comment]
I think I would prefer to continue to have broad support for what the ecosystem is actually doing. I think KDE is in the wrong here, it's better to improve the canonical protocol than to encourage the proliferation of proprietary protocols.

**Comment by SirCmpwn** [comment]
I realize those two sentences conflict with each other. The point being that I want to support the freedesktop protocol as the primary target, but I acknowledge the popularity of the KDE protocol so we should support it as well. We should consider it deprecated and encourage the ecosystem to move over time, however.

**Comment by 4e554c4c** [comment]
>the canonical protocol
Well Canonical moved to the KDE protocol too <.<

Jokes aside, the freedesktop protocol is insufficient to deal with the current KDE implementation. I fixed this in the old codebase by creating a new /sway specific proprietary protocol/ separate from the freedesktop one to deal with the inconsistencies between them, but this is sort of a mess.

Honestly I'd appreciate it if you could bring this up at XDC 2018, about either standardizing the KDE protocol (which would probably be the easiest, since it's the defacto standard now) or whether the KDE folks would be down to switch back to the freedesktop protocol (with a bunch of extensions)

**Comment by SirCmpwn** [comment]
Yeah, we can start talks. But in the meantime, let's implement both.

**Comment by emersion** [comment]
GNOME and GTK+ are moving away from status icons, so don't expect them to move this forward. Also expect many apps to remove status icons instead of adopting a new protocol.

**Comment by SirCmpwn** [comment]
afaik KDE has no plans to move away from status icons.

**Comment by SirCmpwn** [comment]
Copying @kbroulik and @notmart, some relevant KDE peeps

**Comment by mckinney-subgraph** [comment]
@SirCmpwn @4e554c4c

I submitted a PR with the patch. I ironed out one of the issues and included notes about the other one. Also, I wrote a simple testing tool to interact with the service. I will put it up today and add the link.

**Comment by mckinney-subgraph** [comment]
@SirCmpwn @4e554c4c 

The SNI testing tool:
https://github.com/mckinney-subgraph/snit

**Comment by SirCmpwn** [comment]
Thanks!

**Comment by emersion** [comment]
>Now that this is nearing feature-completion, I would very much appreciate anyone who would like to help test this out and let me know which applications don't work to see what edge cases I haven't accounted for.

https://github.com/swaywm/sway/pull/3249
