### ISSUE TITLE
Modifiers need to be held before other buttons are pressed for interpreting keybindings

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/sway#1770]
1. Depress enter
2. Depress mod
3. Observe terminal spawn

**Comment by thejan2009** [comment]
How does one depress a key without pressing it before? If this is related to pressing the buttons for so long that key repeat kicks in, then the same issue exists in i3.

**Comment by SirCmpwn** [comment]
Depress has the same meaning as press, only press can sometimes imply releasing it as well.

1. Apply pressure to enter key
2. Apply pressure to mod key
3. Observe terminal spawn
4. Release pressure from all keys

**Comment by thejan2009** [comment]
Ah, I see. I could reproduce this in DRM and wayland backends, but not X11.

**Comment by smlx** [comment]
I can't reproduce this on master. Fixed?

**Comment by SirCmpwn** [comment]
Yep, seems to be fixed.
