### ISSUE TITLE
Simulate input events with sway commands

### ISSUE THREAD

**Issue by ddevault** [swaywm/sway#1779]
```
seat "default" cursor move +10,0
seat "default" cursor set 100,100
seat "default" cursor press|release left|right|1|2|3...
seat "default" keyboard press|release H
seat "default" keyboard type "hello world"
```

**Comment by emersion** [comment]
Additional note: if the currently focused client supports text-input, we can use that to type text.

**Comment by athas** [comment]
I have interest in making this time, as well as possibly the time.  However, I have no experience with sway's codebase, or Wayland programming in general.  Can anyone suggest a good point to start looking?

**Comment by NilsIrl** [comment]
Would it also be possible to have virtual seats?

Seats which don't have any input device attached to them and can only be controlled through `sway` commands.

**Comment by mvdan** [comment]
I could almost get this to work with commands like:

```
seat - cursor set 50 50
seat - cursor press button1
seat - cursor release button1
```

If I understand the docs correctly, this should move the cursor at 50x50 and do a full mouse left-click.

However, it doesn't quite work. The mouse does move, but the click happens at the last position the mouse was in. I tried adding sleeps, in between the calls to `swaymsg`, but still the same.

**Comment by mvdan** [comment]
Thinking about it some more, I think what I tried above would work if I was able to use a virtual seat, much like what @NilsIrl suggested.

**Comment by mvdan** [comment]
I was wondering if https://github.com/swaywm/sway/pull/4674 could help here, but I don't see a way to create a virtual pointer.

**Comment by paulolieuthier** [comment]
@emersion forgive my ignorance but why isn't something like `wlr_seat_keyboard_send_key` enough, instead of relying on a text input protocol?

**Comment by emersion** [comment]
This depends on the keymap. If you want to send a Hangul character while having your keyboard configured as en-us, it just won't work.

**Comment by paulolieuthier** [comment]
That makes sense, but I don't think the text input protocol can be used to enter keys like arrows (the [input method](https://github.com/wayland-project/wayland-protocols/blob/b0a25f26d3e8b5ad24773881a9a895dd9cc75466/unstable/input-method/input-method-unstable-v1.xml#L145-L157) protocol has a "keysym" request that looks promising).

Before trying to use those protocols, I'm [trying to implement](https://github.com/swaywm/sway/compare/master...paulolieuthier:simulate-keyboard?expand=1) the new commands using `wlr_seat_keyboard_send_key`, but can't get it to enter the arrow keys (using key codes from `xev`). Can you help you me?

**Comment by emersion** [comment]
>enter keys like arrows

Yeah, for these we'll still need raw keycodes.

>but can't get it to enter the arrow keys

There's an offset of 8 between raw Linux key codes and libxkbcommon key codes. Maybe that's the issue? Can you try getting a `WAYLAND_DEBUG=1` log of wev?

**Comment by paulolieuthier** [comment]
The offset hint nailed it, subtracting 8 from the numbers got from `wev` produces the expected keys. Now I can finally bind capslock+hjkl to arrow keys (without messing with the system keymap)! :smile: 

I'll try to experiment with the protocols and send PR that also handles complex texts besides raw key codes.

**Comment by emersion** [comment]
Note, you don't need to edit system keymaps to do this. See https://github.com/swaywm/sway/issues/4250

**Comment by paulolieuthier** [comment]
Yeah, thanks. I had seen that. But I also want to have it layout-independent and all inside sway's config (which I can achieve using `xkb_options lv3:caps_switch` and `bindsym Mod5+`).

**Comment by Tezkerek** [comment]
Can I send modifier keys with `wlr_seat_keyboard_send_key`?  
I tried `press ctrl, press c, release c, release ctrl`, and `wev` receives those events in order, but in Alacritty for example I just get the letter `c`, rather than `ctrl+c`.

**Comment by MatthiasGrandl** [comment]
> I could almost get this to work with commands like:
> 
> ```
> seat - cursor set 50 50
> seat - cursor press button1
> seat - cursor release button1
> ```
> 
> If I understand the docs correctly, this should move the cursor at 50x50 and do a full mouse left-click.
> 
> However, it doesn't quite work. The mouse does move, but the click happens at the last position the mouse was in. I tried adding sleeps, in between the calls to `swaymsg`, but still the same.

I am having exactly the same issue. Mouse moves, but clicks occur at the physical mouses last location. Also I can't get scroll events (button 4 and 5) to happen at all.

**Comment by sloonz** [comment]
> seat "default" cursor move +10,0
> seat "default" cursor set 100,100

Those commands move the cursor but without emiting any cursor move event (as seen in wev/xev). Is that intended ?

**Comment by zwastik** [comment]
So how do we send keystrokes?

**Comment by danieldg** [comment]
Send using the virtual-kbd protocol like in this example client (not really ready for merge, and I never bothered to finish it up): https://github.com/danieldg/wlroots/commit/7fb7a372c5c80742a9c2984d9a0fc27a3186a631

**Comment by Inc0n** [comment]
I was working on this recently, based of from https://github.com/danieldg/wlroots/commit/7fb7a372c5c80742a9c2984d9a0fc27a3186a631, since I do have demand for this, interest from myself. 

I added kbd style key sending and reworked it with a little bit with some new stuff I found.

I was also wondering if I could get some help on crating a meson.build for this little thing alone, personally, I would love to have my project folder just to have the files that I would need, if that would be possible.

Otherwise, I could always fork the project and upload files there.

**Comment by emersion** [comment]
Do you know about [wtype](https://github.com/atx/wtype)?

**Comment by nkakouros** [comment]
> Do you know about [wtype](https://github.com/atx/wtype)?

My own experience with wtype is that the events sent by wtype get received by sway itself and not the application (e.g. the browser).

**Comment by emersion** [comment]
Sway should forward the wtype events to the focused client, as if they were coming from a physical keyboard.

**Comment by emersion** [comment]
Ref https://git.sr.ht/~emersion/wl-ime-type which uses input-method to send the text.

**Comment by agoodshort** [comment]
`wtype` worked really well for me to remap Lock+e to escape
```
bindsym Control+e exec wtype -k 'Escape'
```
In my opinion using `bindsym` to remap keys is a great workaround. It avoids installing advanced keyboard manager like `kmonad`.

I think this method has its place in the [Tricks wiki](https://github.com/swaywm/sway/wiki/Tricks).

**Comment by emersion** [comment]
Closing: I don't think Sway commands are great for this. Between the virtual input protocols and input-method, there are plenty of ways to simulate input events already.
