### ISSUE TITLE
swaybar: [failed to parse i3bar json]

### ISSUE THREAD

**Issue by NilsBrause** [swaywm/sway#1785]
I am currently testing sway version 1.0-alpha.1-29-g07b6be62 using my [i3 config](https://gist.github.com/NilsBrause/a6b433befed49768f8c12474ab4d561a) as well as my [status stript](https://gist.github.com/NilsBrause/470819d8622cd4e5aaa5c0bb3a66eecf). Both worked fine with i3. Unfortunately in sway the message **[failed to parse i3bar json]** is displayed in red in the swaybar. Also, swaybar is at 100% CPU usage, being stuck in a poll loop:

`poll([{fd=6, events=POLLIN}, {fd=4, events=POLLIN}, {fd=5, events=POLLIN}], 3, -1) = 1 ([{fd=5, revents=POLLNVAL}])`

The debug log suggests that there is a broken pipe between swaybar and my script:

`/home/nils/status.sh: line 98: echo: write error: Broken pipe`

**Comment by RyanDwyer** [comment]
Can you please try again with the latest commit in the wlroots branch? It may have been fixed in commit bac65078.

**Comment by NilsBrause** [comment]
I'm on 48fca1c7 now, and the problem persists.

**Comment by NilsBrause** [comment]
With gdb, it seems like the first few lines of the status script output (after the version line) aren't being read in:
```
Breakpoint 2, i3bar_handle_readable (status=0x555555778cb0) at ../sway/swaybar/i3bar.c:113
113             char *cur = &state->buffer[state->buffer_index];
(gdb) n
114             ssize_t n = read(status->read_fd, cur,
(gdb)
113             char *cur = &state->buffer[state->buffer_index];
(gdb)
114             ssize_t n = read(status->read_fd, cur,
(gdb)
116             if (n == -1) {
(gdb) p *state
$22 = {click_events = false,
  buffer = 0x555555778d80 "{ \"name\" : \"net_tap0\", \"color\" : \"#ff0000\", \"full_text\" : \"tap0: down\" },\n{ \"name\" : \"net_tun0\", \"color\" : \"#00ff00\", \"full_text\" : \"tun0: 10.0.0.18 & 2a03:4000:15:2a3:1::1003\", \"short_text\" : \"10.0.0"...,
buffer_size = 4096, buffer_index = 0, current_node = 0x0, escape = false, depth = 0, nodes = {JSON_NODE_UNKNOWN <repeats 16 times>}}
```
Note that the '[' is missing. Then, a ']' is encountered, status_error closes the fd, and the poll in the event loop alsways immediately returns with an error for the status fd, resulting in 100% CPU usage.

I don't know why it doesn't read the first few lines, but to get rid of the high CPU usage, could we maybe remove the status fd from the event loop in the status_error function?

Interestingly, it works fine when being run manually with `strace swaybar -b bar-0`
Another workaround is adding a `sleep 1` to the first line of the script.

**Comment by NilsBrause** [comment]
Alright, I think I got it: 

fdopen is used to associate a FILE stream with the status read fd. This stream is buffered. Therefore read_line_buffer will not only read a single line but potentially more from the fd. Making the FILE stream unbuffered using `setvbuf(status->read, NULL, _IONBF, 0);` fixes this (like [1]).

Unfortunately, this didn't seem to make it work with my script and i3status didn't work anymore either. Looking at the i3bar/JSON parser revealed, that it doesn't expect the opening '[' of the infinite array. When using i3status before, the '[' was in the FILE stream buffer. Therefore that didn't matter. Since it is present now, the i3bar/JSON parser has to be changed accordingly (maybe like [2] but this is just a quick hack).

[1] https://github.com/NilsBrause/sway/commit/e8b222a4e8fbf9e630b1c92a47d5f25dc8b829bf
[2] https://github.com/NilsBrause/sway/commit/e74c07ad0450c319109cf1cfd17e0d3c5317ee3e

**Comment by emersion** [comment]
Can't we just use `getline` from `_POSIX_C_SOURCE >= 200809L`?

**Comment by SirCmpwn** [comment]
I would consider a patch for that

**Comment by ianyfan** [comment]
Should be fixed by https://github.com/swaywm/sway/pull/2640 please check
