### ISSUE TITLE
Buffer transform & fullscreen input not protocol compliant

### ISSUE THREAD

**Issue by Zubnix** [swaywm/sway#1787]
Run weston-fullscreen. The cursor & red tiles don't match. When applying buffer transform the whole app rotates where it should appear the same.

**Comment by SirCmpwn** [comment]
What version of sway are you using?

**Comment by Zubnix** [comment]
master

**Comment by SirCmpwn** [comment]
If the issue affects rootston as well, please file a bug with [wlroots](https://github.com/swaywm/wlroots). Thanks!
