### ISSUE TITLE
swaygrab incorrect resolution of the captured content

### ISSUE THREAD

**Issue by petoknm** [swaywm/sway#1799]
I am running a 4K screen at FullHD resolution and when I capture it using swaygrab it produces a FullHD image as expected but the image shows only 1 quarter of the screen content (upper left quarter). I tried capturing another screen that is running at a native resolution and it works correctly.

**Comment by SirCmpwn** [comment]
This will be addressed when [wlroots](https://github.com/swaywm/wlroots) is completed and [integrated with sway](https://github.com/swaywm/sway/issues/1390).
