### ISSUE TITLE
Intellij menus behaves wierd

### ISSUE THREAD

**Issue by snaggen** [swaywm/sway#1805]
When testing 1.0.0 alpha I started Intellij with the export _JAVA_AWT_WM_NONREPARENTING=1 environment variable. 
It starts fine, but when I click a menu it will split the screen, and show the menu in just a small part of the right side of the screen (since it is shown in the correct size) and fill the rest of the right side of the screen with whatever image happens to be in some random memory I guess...

**Comment by snaggen** [comment]
I assume you closed this, due to some commit. It might be nice to reference this issue in the commit, or just mention it when closing. Nice to see this handled so fast though.... will pull and try.

**Comment by SirCmpwn** [comment]
I closed this due to **don't report bugs for the alpha god dammit**
