### ISSUE TITLE
problem with italian keyboard

### ISSUE THREAD

**Issue by enricoT** [swaywm/sway#1812]
Hi, im on archlinuxarm armv7h raspberry pi 3 b

> yaourt -Qi sway-git
Name            : sway-git
Version         : r2589.78740b97-1
Description     : i3 compatible window manager for Wayland
Architecture    : armv7h
URL             : http://swaywm.org
Licenses        : MIT
Groups          : None
Provides        : sway
Depends On      : wlc-git  xorg-server-xwayland  xcb-util-image  json-c  pango  cairo  wayland
                  gdk-pixbuf2
Optional Deps   : rxvt-unicode: Default terminal emulator. [installed]
                  dmenu: Default for launching applications. [installed]
                  imagemagick: For taking screenshots. [installed]
                  ffmpeg: For recording screencasts. [installed]
                  i3status: To display system information with a bar. [installed]
Required By     : None
Optional For    : None
Conflicts With  : sway
Replaces        : None
Installed Size  : 5.33 MiB
Packager        : Unknown Packager
Build Date      : Fri Apr 13 21:16:48 2018
Install Date    : Fri Apr 13 21:17:05 2018
Install Reason  : Explicitly installed
Install Script  : Yes

my script to run sway is:
`cat sway
#!/usr/bin/env bash
export XKB_DEFAULT_LAYOUT=it
export XKB_DEFAULT_VARIANT=,nodeadkeys
export XKB_DEFAULT_OPTIONS=grp:alt_shift_toggle,
export _JAVA_AWT_WM_NONREPARENTING=1

# sway -d 2> ~/sway.log
sway
`

I cant find / or ~ at the proper position of italian keyboard

**Comment by sellleon** [comment]
I don't think this is related to your problem, but you shouldn't put the , (comma) before nodeadkeys and after grp:alt_shift_toogle, as you're only using one default keyboard layout.
But nonetheless your script produces the correct result for me. Note that I use sway-wlroots-git 1.0.alpha.1.r46.g57851704-4 from AUR.

**Comment by SirCmpwn** [comment]
I'm closing issues that are resolved by the yet-unrelated sway 1.0.
