### ISSUE TITLE
Remove or replace output pos <X,Y>

### ISSUE THREAD

**Issue by nearffxx** [swaywm/sway#1822]
The new syntax for output <X,Y> is not working.
e.g., "swaymsg output eDP-1 pos 0,1200 res 1920x1200" GIves the following error:
Error: Missing position argument (y).

While it works in the legacy mode
swaymsg output eDP-1 pos 0 1200 res 1920x1200

**Comment by emersion** [comment]
Is this on Sway 0.15 or 1.0-alpha.1?

**Comment by nearffxx** [comment]
I tried on 1.0-alpha.1, but IIRC both version are affected.

**Comment by emersion** [comment]
Changed the issue to remove this feature.

Conflicts with https://i3wm.org/docs/userguide.html#command_chaining

**Comment by emersion** [comment]
Considering using `pos XxY` instead.

**Comment by SirCmpwn** [comment]
How about `pos XliterallyanythingY`

**Comment by nearffxx** [comment]
I prefer "pos XxY", it makes more sense since it's a coordinate.

**Comment by emersion** [comment]
>I prefer "pos XxY", it makes more sense since it's a coordinate.

I _think_ he was being sarcastic.

**Comment by SirCmpwn** [comment]
>I *think* he was being sarcastic.

I wasn't :<

**Comment by emersion** [comment]
Yet another fact to add to this drama: `strtod` parses hex numbers. It means "0x42" is not parsed as (0, 42) but is parsed as (66, error).

**Comment by RyanDwyer** [comment]
You can use quotes to prevent splitting on the comma. However, Bash will swallow the quotes and not pass them to swaymsg so you have to escape them.

    $ swaymsg output FOO-1 pos \'100,100\'

I'll leave this open for now, pending someone else agreeing that we're right to leave it as it is.
