### ISSUE TITLE
for_window and assign seems to have no effect for any native Wayland app

### ISSUE THREAD

**Issue by vgribov** [swaywm/sway#1825]
sway version 0.15.2 on Arch Linux.

Tried to set border properties for `termite` with the following command:

    for_window [class="termite"] border pixel 1

and it has no effect.

The `swaymsg -t get_tree` outputs the following:

    "window_properties": {
        "class": "termite",
        "instance": "termite",
        "title": "vgribov@vgribov-lnx:~",
        "transient_for": null
    },
 
Same thing with `evolution`: I've tried to assign it to a workspace using command:

    assign [class="[Ee]volution"] 4

without any success.

**Comment by bpinto** [comment]
@vgribov I've noticed I use capitalized "Termite" class on my configuration file, could it be it?

`for_window [class="Termite"] border pixel 1`

**Comment by vgribov** [comment]
@bpinto I have tried the following in my config:

    for_window [class="Termite"] border pixel 1

unfortunately, it doesn't make my Termite window having 1 pixel border without a title.

**Comment by thebunnyrules** [comment]
I've had the same experience with for_window. It has no effect in 0.15.

**Comment by bpinto** [comment]
From what I've seen on the codebase, native wayland apps do not accept the class criteria, I think you have to use `title` or `id`.

**Comment by thebunnyrules** [comment]
Thanks, I'll keep that in mind for the future but title was actually the first thing I tried.

**Comment by tardypad** [comment]
@bpinto Could you please precise what you mean by that previous comment, I'm not sure which codebase you're refering to?
Do you mean "Sway doesn't support class criteria from native Wayland apps" or "Native Wayland apps don't support class criteria at all" or something else?

I just opened the issue https://github.com/thestinger/termite/issues/595 before seeing your comment

**Comment by tardypad** [comment]
Got a reply in that other issue I mentioned, saying "Native Wayland apps don't support window class".

But I guess this bug report stays valid nevertheless.
Since Sway seems to have assigned "termite" to it, I would expect such rules to work too
