### ISSUE TITLE
Convince mpv to render at the resolution we assign it when tiled

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/sway#1826]
It just renders with the resolution of the video right now.

**Comment by emersion** [comment]
This is probably a wl-shell issue. Someone please try with mpv-git!

**Comment by bpinto** [comment]
I couldn't reproduce this problem with latest sway/wlroots and mpv 0.27.2.

**Comment by emersion** [comment]
That's not helpful. You need to enable the Wayland backend and use mpv-git.

**Comment by bpinto** [comment]
The description didn't mention it was a wayland backend only problem, now that you've mentioned it, I'm running mpv with `--opengl-backend=wayland`

`v0.27.2`: issue reproducible.
`git(e7e06a4)`: issue **not** reproducible.

**Comment by emersion** [comment]
Oh, yeah, sorry, this was mentioned on IRC but not here. Thanks for testing!

**Comment by bpinto** [comment]
Just to add more information to this issue, the latest released version is `0.28.2` and it has this issue fixed.

Both gentoo and arch (and maybe other distros) are still on `0.27.2`.
