### ISSUE TITLE
Fullscreen improvements

### ISSUE THREAD

**Issue by RyanDwyer** [swaywm/sway#1828]
- [x] Containers need to be fullscreenable.
- [ ] Surfaces can request to be fullscreened on a specific output, which is currently ignored (#1813).
- [x] Moving a fullscreen view to another workspace unfullscreens it.
- [x] Unmanaged xwayland surfaces need to be rendered if the fullscreen view is xwayland (eg. Chromium context menu).

**Comment by somdoron** [comment]
Also, when using xwayland app (chromium) in full screen context menu doesn't show up.

**Comment by emersion** [comment]
Yeah, that's because unmanaged xwayland surfaces need to be rendered if the fullscreen view is xwayland.

**Comment by somdoron** [comment]
@RyanDwyer I think it is worth adding that to the list.

**Comment by atomnuker** [comment]
I think blanking background needs to be moved to wlroots, since with direct scanout you can't avoid doing it.

**Comment by SirCmpwn** [comment]
I disagree. We're going to give the user the tools to deal with direct scan-out themselves.

**Comment by emersion** [comment]
It's already in wlroots if you use `wlr_output_set_full screen_surface`. And yes, it should be there.

**Comment by SirCmpwn** [comment]
For the record, I'm not happy with wlr_output_set_fullscreen_surface

**Comment by emersion** [comment]
It seems you're not happy with direct scan-out too.

**Comment by SirCmpwn** [comment]
ding ding ding

But fwiw I'm on board with making wlroots support it, but like everything else we need to do it in an unopinionated way.

**Comment by emersion** [comment]
Agreed.

**Comment by petabyteboy** [comment]
The wallpaper should still be rendered in fullscreen for transparent applications.

**Comment by emersion** [comment]
>The wallpaper should still be rendered in fullscreen for transparent applications.

No. Won't work with direct scan-out.

**Comment by atomnuker** [comment]
A setting was agreed on to toggle that.

**Comment by atomnuker** [comment]
fullscreen flipping is still not synchronized (e.g. it can tear), right? This ought to be added.
Also fullscreen mode doesn't yet stop the frame callback for all invisible surfaces below.

**Comment by emersion** [comment]
>fullscreen flipping is still not synchronized (e.g. it can tear), right?

No, it is synchronized, it can't tear.

>Also fullscreen mode doesn't yet stop the frame callback for all invisible surfaces below.

It should and used to, probably a bug.

**Comment by RyanDwyer** [comment]
Closing this because the last remaining item has a specific issue for it (#1813).

**Comment by ssendev** [comment]
>> The wallpaper should still be rendered in fullscreen for transparent applications.

> A setting was agreed on to toggle that.

But i can't seem to find it. Or was it just agreed on and not implemented?

**Comment by RyanDwyer** [comment]
It's not been implemented.

**Comment by petabyteboy** [comment]
The wallpaper is still not rendered for fullscreen transparent applications.

**Comment by RedSoxFan** [comment]
> The wallpaper is still not rendered for fullscreen transparent applications.

The `xdg-shell` protocol states that fullscreen windows should be rendered over a solid black background. Rendering the wallpaper would be a violation of the specification, which is why this has not been implemented

**Comment by ssendev** [comment]
Would it be possible to add a separate "fully maximized" mode which looks
like fullscreen but has transparency
