### ISSUE TITLE
xwayland windows do not show

### ISSUE THREAD

**Issue by Laaas** [swaywm/sway#1833]
My config:
```
bindsym Return exec urxvt
bindsym Escape exit
```

In addition, after opening sway, pressing return, and then pressing escape, sway segfaults with the following coredump: https://drive.google.com/open?id=1jlNp3D7Tm2-pRbWDtLFnMJdp1gltYZsq

stderr when I ran sway -d: https://pastebin.com/jcerWUeQ

I tested with urxvt, firefox-developer-edition, and gnome-terminal.

**Comment by emersion** [comment]
What happens when you launch an Xwayland app from a Wayland terminal? Logs?

Can you provide the stack trace of the coredump?

**Comment by Laaas** [comment]
stack trace: ```
* thread #1, name = 'sway', stop reason = signal SIGSEGV
  * frame #0: 0x00007fd3e80e2137 libwayland-server.so.0`wl_list_remove + 7
    frame #1: 0x000055cbc4290049 sway`handle_unmap(listener=0x000055cbc5dcc1f0, data=0x000055cbc5b9a780) at xwayland.c:233
    frame #2: 0x000055cbc429015a sway`handle_destroy(listener=0x000055cbc5dcc208, data=0x000055cbc5b9a780) at xwayland.c:263
    frame #3: 0x00007fd3e9bdddc8 libwlroots.so.0`wlr_signal_emit_safe(signal=0x000055cbc5b9a860, data=0x000055cbc5b9a780) at signal.c:29
    frame #4: 0x00007fd3e9b9ddf6 libwlroots.so.0`wlr_xwayland_surface_destroy(xsurface=0x000055cbc5b9a780) at xwm.c:245
    frame #5: 0x00007fd3e9ba035f libwlroots.so.0`xwm_destroy(xwm=0x000055cbc5b50400) at xwm.c:1244
    frame #6: 0x00007fd3e9b9c9fa libwlroots.so.0`wlr_xwayland_finish(wlr_xwayland=0x000055cbc5a14150) at xwayland.c:138
    frame #7: 0x00007fd3e9b9d498 libwlroots.so.0`wlr_xwayland_destroy(wlr_xwayland=0x000055cbc5a14150) at xwayland.c:341
    frame #8: 0x00007fd3e9b9cbd4 libwlroots.so.0`handle_display_destroy(listener=0x000055cbc5a141b0, data=0x000055cbc58b5700) at xwayland.c:196
    frame #9: 0x00007fd3e80ddb82 libwayland-server.so.0`___lldb_unnamed_symbol18$$libwayland-server.so.0 + 82
    frame #10: 0x00007fd3e80de177 libwayland-server.so.0`wl_display_destroy + 23
    frame #11: 0x000055cbc428369f sway`server_fini(server=0x000055cbc44bd360) at server.c:129
    frame #12: 0x000055cbc428308e sway`main(argc=2, argv=0x00007fffa1e5dd68) at main.c:423
    frame #13: 0x00007fd3e78f3f4a libc.so.6`__libc_start_main + 234
    frame #14: 0x000055cbc42820ba sway`_start + 42
```

The coredump is just 2 MiB compressed FYI.

**Comment by Laaas** [comment]
I was using my own pointer constraints branch of wlroots (obviously), but it seems it broke xwayland somehow.... Seems like it was all my fault!

**Comment by emersion** [comment]
Rebase your branch

**Comment by Laaas** [comment]
Yeah I just rebased it and it works fine now, great.
