### ISSUE TITLE
Bindsyms using Mod5 (ISO_Level3_Shift) fail

### ISSUE THREAD

**Issue by frsfnrrg** [swaywm/sway#1844]
Using wlroots & sway builds from today (swaywm/wlroots@12bf39a715b2 and 48c84cd1f).

My relevant environment variables are

      export XKB_DEFAULT_OPTIONS=lv3:caps_switch

And the relevant lines of `.config/sway/sway` are `set $mod Mod5` and `bindsym $mod+Return exec st`.
Pressing keys `CapsLock+Enter`  should launch `st`; it doesn't. The cause is that `keysym_is_modifier` in 
`sway/input/keyboard.c` is overly specific in detecting modifiers; comparing with `xmodmap` output, I find

    shift       Shift_L (0x32),  Shift_R (0x3e)
    lock      
    control     Control_L (0x25),  Control_R (0x69)
    mod1        Alt_L (0x40),  Alt_R (0x6c),  Meta_L (0xcd)
    mod2        Num_Lock (0x4d)
    mod3      
    mod4        Super_L (0x85),  Super_R (0x86),  Super_L (0xce),  Hyper_L (0xcf)
    mod5        ISO_Level3_Shift (0x5c),  Mode_switch (0xcb)

so that `keysym_is_modifier` is most likely missing `XKB_KEY_Num_Lock`, `XKB_KEY_Mode_switch`, and `XKB_KEY_ISO_Level3_Shift`. (Now that I have added these cases to my local version of sway, `CapsLock+Enter` does launch `st`.)

It would be nice if sway would identify which keysyms generate modifiers from the xkb API instead of using using a hardcoded list which only works with default keyboards.

**Comment by emersion** [comment]
We've not (yet) found a way to do this automatically.

`xmodmap -pm` is implemented here: https://cgit.freedesktop.org/xorg/app/xmodmap/tree/exec.c#n215

**Comment by emersion** [comment]
From #wayland:

```
08:38 <daniels> emersion: yeah, keyboard shortcuts are ... exciting. especially when you get to multiple layouts and realise that people want ctrl+w to work regardless of whether they're in cyrillic or latin mode
08:39 <daniels> emersion: anyway, yeah, there's i'm afraid no real connection between keysyms and modifiers, especially as you have things like latching modifiers
```

**Comment by frsfnrrg** [comment]
I've made a short script (https://github.com/frsfnrrg/shortcut/blob/master/shortcut.py) with
which to compare shortcut implementations. It requires Python3.6 and `xev`.  So,

* Shortcuts for i3 (⊃ KDE) are group+modifier+keysym or group+modifier+keycode; very simple (see `shortcut_i3`) hence fast and bug free.
* Sway's current shortcut handling is unintuitive -- it can't distinguish `Ctrl+a+b` from `Ctrl+b+a`,  and hardcodes modifiers. My translation is `shortcut_sway`, which skips translated keysyms due to complexity.† 
* `shortcut_delta` is the shortcut behavior that I would prefer; a generalization of i3's behavior to short sequences of key combinations, such as `Ctrl+m/Meta+r/Meta+s`. A keypress is a modifier keypress if the next key press has a different modifier state.†† We store the last N keypresses which are not modifier keypresses, and match regular shortcuts based on the suffixes of stored keypresses along with the current keypress (which may or may not be a modifier keypress) . (Thus `Ctrl+Hyper_L` is a valid key combination.) Release shortcuts are triggered on any keyrelease when the shortest stored keypress suffix matches. [In an actually implementation, when a shortcut is triggered, the ring of stored keypresses is wiped so we don't overcall; this isn't shown in `shortcut.py`.]

†(Isn't Unicode case normalization more appropriate? After all, some users might have keyboard states that translate QWERTY to Dvorak, and if they cared for key positions, they'd use `bindcode` not `bindsym`)
††Hopefully this would also identify latching modifiers.

**Comment by martin-braun** [comment]
Thank you for this issue. I wasn't able to bind `ISO_Level3_Shift` which is the right option key on German Macintosh keyboards, but binding `Mod5` worked. This issue was helpful for me.
