### ISSUE TITLE
Pointer events not sent on holding a button if pointer moved outside of surface

### ISSUE THREAD

**Issue by atomnuker** [swaywm/sway#1862]
Very specific but breaks workflow.

Example: open up a text editor or a terminal (native, not xwayland), start holding the mouse and selecting text as you move up. Eventually once you go over the bar mouse events should still be sent, however this only happens with X11 windows. Native Wayland windows receive no events.

The same issue happens if you have 2 terminals side by side. Selecting text, holding the mouse button and moving the cursor across another surface yields no events sent to the client. This seems to affect X11 windows as well.

**Comment by SirCmpwn** [comment]
I looked into this a while earlier and the change will be a bit involved.

**Comment by zeGrandpa** [comment]
Hi, did 82423b8 solve this issue ?

**Comment by emersion** [comment]
Yeah, this has been fixed.
