### ISSUE TITLE
Steam popups are unclickable

### ISSUE THREAD

**Issue by emersion** [swaywm/sway#1865]
The keyboard can be used to select items though.

**Comment by den731** [comment]
Menu items can be pseudo "clicked" by hovering the mouse over item and pressing enter. Main menu item seems to be clickable, but not its subsequent menu entries.

Just a tid-bit for others as a workaround

**Comment by eiz** [comment]
This was annoying me a bit so I traced it out and it arises when the xwayland integration in wlroots resets the input focus after an X client tries to change it: https://github.com/swaywm/wlroots/blob/51bfdd620e70c41e1a9fb4ce7831eddfb1bf893b/xwayland/xwm.c#L1192

Steam's menu system seems to have some really odd focus behavior and when the compositor resets the input focus the menu disappears before handling the selection. Honestly not sure what the correct fix is.

**Comment by emersion** [comment]
Thanks for investigating. So removing this fixes the issue? What is the value of `ev->mode`? Does it work in Weston? (not sure Weston has the same behaviour)

**Comment by eiz** [comment]
Yeah, removing it fixes the issue. ev->mode is XCB_NOTIFY_MODE_NORMAL.

As for what happens in Weston, I get very odd behavior. The pointer tracking doesn't seem to work correctly -- the hover menus appear and disappear when the pointer is at the wrong location (there is an offset), and the items also don't work when selected. `gnome-shell --wayland --nested` works as expected, though.

**Comment by clarfon** [comment]
Is there any particular problems with removing these lines for now, or is this something that Valve should fix upstream?

**Comment by soreau** [comment]
It should be fixed in xwm. I see the code stems from [weston b18f788e2e747](https://github.com/wayland-project/weston/commit/b18f788e2e747) but it isn't clear from the commit message what case(s) this fixes exactly. I can verify that removing the code fixes the issue with steam.

**Comment by emersion** [comment]
This commit isn't supposed to fix anything. It just makes the xwm more strict and prevents clients from setting an arbitrary focus.

**Comment by clarfon** [comment]
So… this is a bug on Sway's end? Or on Valve's end? Or both?

Basically I'm wondering what exactly needs to be done to fix this issue. I'd be willing to help out once I know what needs to be done to fix this.

**Comment by emersion** [comment]
Sway's xwm is strict. Steam is a client that expects to be able to set focus in an arbitrary fashion.

I'd say it's a Valve bug, so I'd report it to them. Since it's closed software I'm not sure this has a chance to get fixed.

**Comment by clarfon** [comment]
Ah, makes sense. This should probably be closed then, considering how there's not really anything that can be done.

**Comment by soreau** [comment]
> Sway's xwm is strict.
Don't you mean wlroots?

**Comment by emersion** [comment]
Indeed, Sway's xwm is backed by wlroots.

**Comment by soreau** [comment]
I'm saying if this is ignored, all wlroots compositors will continue to be broken in the same way, right? What might be the consequences of leaving this code out?

**Comment by emersion** [comment]
X11 clients would be able to steal focus.

(Leaving this open because I'm not yet sure it's worth it to keep this code -- X11 clients are able to sidestep each other in many ways, why bother?)

**Comment by clarfon** [comment]
For what it's worth, I opened up an issue for Steam. It appears that it's had focus problems since the very beginning on X-based window managers, so it does seem like this would be a Steam bug.

I haven't run into this kind of issue on any other program, so, I'm not 100% sure if there's anything that actually would need this. Allowing any client to arbitrarily steal focus seems pretty bad.

**Comment by luispabon** [comment]
@clarfon do you have a link to the issue at steam I could subscribe to?

**Comment by dywedir** [comment]
@luispabon https://github.com/ValveSoftware/steam-for-linux/issues/6211

**Comment by Uramekus** [comment]
![2019-06-12_19:51:20](https://user-images.githubusercontent.com/4643873/59391914-33f16600-8d4c-11e9-9d15-ceb1a02f80b4.png)
as a side remark, context menus work on the steam beta leak, as a workaround its avaliable on https://www.reddit.com/r/Steam/comments/bykilq/steam_library_update_work_in_progress_via_steamdb/

**Comment by HoshiYamazaki** [comment]
> ![2019-06-12_19:51:20](https://user-images.githubusercontent.com/4643873/59391914-33f16600-8d4c-11e9-9d15-ceb1a02f80b4.png)
> as a side remark, context menus work on the steam beta leak, as a workaround its avaliable on https://www.reddit.com/r/Steam/comments/bykilq/steam_library_update_work_in_progress_via_steamdb/

For me it's not working fully even in the beta, maybe this is because I use mixed dpi but I don't know...

**Comment by AsuMagic** [comment]
> > as a side remark, context menus work on the steam beta leak, as a workaround its avaliable on https://www.reddit.com/r/Steam/comments/bykilq/steam_library_update_work_in_progress_via_steamdb/
> 
> For me it's not working fully even in the beta, maybe this is because I use mixed dpi but I don't know...

Not fixed for me. Still happens on the Steam beta client.
It's worth mentioning that some of these menus _still work_ when you open them while keeping LMB pressed and release it on the item you want. This unfortunately doesn't work for all of them.

I get broken submenus in the steam friends interface unless I set the relevant window to floating.

**Comment by emersion** [comment]
Fixed in https://github.com/swaywm/wlroots/pull/1980
