### ISSUE TITLE
captured picture > clipboard

### ISSUE THREAD

**Issue by DpoBoceka** [swaywm/sway#1870]
Is it possible to pipe screenshot to clipboard like it is with X server, like:
maim -s | xclip -selection clipboard -t image/png

**Comment by clarcharr** [comment]
Considering how the clipboards are synchronised on wlroots, why can't you just use xclip? Perhaps a `swayclip` tool might be nice to have, but once 1.0 comes out, that will work by itself.

**Comment by emersion** [comment]
>Is it possible to pipe screenshot to clipboard like it is with X server, like:
maim -s | xclip -selection clipboard -t image/png

This is not yet possible, but it's planned.

>Considering how the clipboards are synchronised on wlroots, why can't you just use xclip? Perhaps a swayclip tool might be nice to have, but once 1.0 comes out, that will work by itself.

No, xclip won't work unless an xwayland window is focused. This is a security feature to prevent X11 apps from spying on your clipboard.

**Comment by emersion** [comment]
https://github.com/swaywm/wlr-protocols/issues/20
