### ISSUE TITLE
swaylock: lock even if provided image doesn't exist

### ISSUE THREAD

**Issue by clarcharr** [swaywm/sway#1872]
On 0.15.2, `swaylock` will fail to run if the image does not exist; I consider this a bug because deleting/moving the lock background is a way of disabling any autolock scripts which call `swaylock`.

I assume that 1.0 has not changed this behaviour.

**Comment by SirCmpwn** [comment]
This is the intended behavior. Maybe make your lockscreen image owned by another user?

**Comment by clarcharr** [comment]
So, a PR that changes the behaviour to default to a white screen like when an image is not supplied, I'm assuming would not be accepted?

**Comment by SirCmpwn** [comment]
Correct.

**Comment by ggreer** [comment]
A common use case is showing a blurred or pixelated version of the screen while locked. That means using swaygrab + swaylock. But if swaygrab fails, the user still wants their screen locked.

**Comment by clarcharr** [comment]
Personally I think that any invocation of swaylock that doesn't explicitly have `--help` or something similar in the arguments should still lock the screen. I would disagree with using a swaygrabbed image to lock though, as that's a security nightmare, but locking despite malformed input seems reasonable.

Although also, I can't really do anything if the head dev disagrees. This isn't worth forking, although I will probably submit a PR at least documenting that swaylock will fail if the image doesn't exist, as it is the expected behaviour.
