### ISSUE TITLE
Split swaylock into a standalone project

### ISSUE THREAD

**Issue by ddevault** [swaywm/sway#1875]

**Comment by emersion** [comment]
How will we manage the common lib?

**Comment by SirCmpwn** [comment]
Copying what we need and refactoring the rest away

**Comment by RedSoxFan** [comment]
Related #3413

**Comment by emersion** [comment]
We should also migrate issues to the new repos.

**Comment by RedSoxFan** [comment]
I think github lets repo admins move issues between repos within an organization now. I'm not sure if anyone other than ddevault is a repo admin though.

However, some issues may be better off recreated and linked to in the existing issue due to spanning multiple items.

**Comment by ddevault** [comment]
Yeah, I can. If anyone cares, prepare a list of issues and I'll move them.
