### ISSUE TITLE
gcc 7.3.1: sway/sway/tree/view.c:115:2: error: ‘height’ may be used uninitialized in this function

### ISSUE THREAD

**Issue by dmeijboom** [swaywm/sway#1888]
GCC version: 7.3.1
OS: Archlinux

It seems that in `sway/sway/tree/view.c:90` there are four variables (x, y, width and height) initialized without a value. GCC throws an error about this and because of this I can no longer compile sway from master on Archlinux.

I'm no expert in C, at all but I can create a pull-request if the fix is something like initializing them with a NULL value or something.

Can someone put me in the right direction?

**Comment by emersion** [comment]
Yes, please open a PR initializing these variables.
