### ISSUE TITLE
How is the current stability of Sway and is there an official forum?

### ISSUE THREAD

**Issue by thebunnyrules** [swaywm/sway#1891]
Hi everyone, I know that this is an Issues section on github which is supposed to be dedicated for troubleshooting rather than opinions but I wasn't sure if Sway had a forum. 

I was just wondering how stable Sway has become at this point. I'm on Gnome-Shell wayland at the moment and am looking to replace it with something lighter and sway looks really awesome and deliciously simple.

**Comment by emersion** [comment]
Please ask these questions on IRC, thanks!
