### ISSUE TITLE
Anyway of getting xclip and xsel working with sway?

### ISSUE THREAD

**Issue by thebunnyrules** [swaywm/sway#1897]
Hi, I noticed that even though they worked perfectly in gnome-shell wayland running native wayland apps, xclip and xsel no longer work with sway running native wayland apps (I've tested this with both the new alpha and 0.15). Is it a bug, is it by design or is it some feature that the gnome DE supports but Sway doesn't? Is there anything I can do to get them to work?

**Comment by emersion** [comment]
It's by design. In 1.0 X11 clients will only be able to access the clipboard if a X11 window is focused.

You can use `swaymsg` to read and write the clipboard instead (not yet implemented in sway 1.0).

**Comment by thebunnyrules** [comment]
Nice! Is there something similar for reading selections?

**Comment by emersion** [comment]
`swaymsg -t get_clipboard` IIRC

**Comment by emersion** [comment]
https://www.urbandictionary.com/define.php?term=iirc

**Comment by thebunnyrules** [comment]
I see.... hahaha

**Comment by thebunnyrules** [comment]
I was able to get swaymsg -t get_cliboard TEXT

to grab clipboard content. Is there anyway of getting selection content (in the style of xsel)?

**Comment by SirCmpwn** [comment]
No, in sway 0.15 the primary selection is an X concept that isn't tracked by Sway. Just use xsel to get it.

**Comment by thebunnyrules** [comment]
xsel doesn't work on the wayland native windows (at least not in sway, for some reason it seems to work in gnome-shell wayland).

**Comment by SirCmpwn** [comment]
That's because Wayland native windows don't have a primary selection. In gnome they have a special primary selection protocol, which sway 1.0-alpha.1 supports.

**Comment by thebunnyrules** [comment]
Yey!!! :+1:  That's great to know.

**Comment by thebunnyrules** [comment]
swaymsg -t get_cliboard TEXT 

I noticed that the above command would cut off after 578 characters in Sway 0.15. Is this by design or a bug ? If it's by design, where can I modify the limit in the source code?

**Comment by emersion** [comment]
Search for "get_clipboard" in the source code? This is most likely a bug, and will be fixed in 1.0.

**Comment by thebunnyrules** [comment]
Ok. I'll way for the 1.0 release. Thanks emersion.
