### ISSUE TITLE
Is it possible to disable snapping for some windows?

### ISSUE THREAD

**Issue by thebunnyrules** [swaywm/sway#1898]
I have a few scripts that open windows  that need to be of a certain size and preferably centered. I was wondering if there's a way of getting sway to ignore them with regards to the windows snapping? I'd be using hotkeys setup in sway config to run them.

**Comment by SirCmpwn** [comment]
You can set up `for_window` rules to automatically float them.

**Comment by thebunnyrules** [comment]
Thanks alot.
