### ISSUE TITLE
cursor stuck in "edit mode" on dual screen

### ISSUE THREAD

**Issue by nearffxx** [swaywm/sway#1902]
1:
on screen 1: open urxvt
on screen 2: open virtualbox and run a VM
2:
click something on the VM
click urxvt
3:
done, now the cursor is stuck in editing mode, the only way to solve it, is to close the VM with the keyboard.

sway version 1.0-alpha.1-192-gb45e2bd9 (May  2 2018, branch 'master')

**Comment by dmeijboom** [comment]
I have the same problem but it doesn't happen when I start the vm in detached mode.

**Comment by SirCmpwn** [comment]
What is "edit mode"?

**Comment by dmeijboom** [comment]
In my case the cursor is "grabbed" by Virtualbox. I can move it around but clicking on things other than the virtual-machine doesn't work. It can only be stopped by closing the virtual machine.

**Comment by SirCmpwn** [comment]
Can you interact with native wayland windows? I'm inclined to close this as an Xwayland problem.

**Comment by nearffxx** [comment]
Just tried on termite, I can.

**Comment by SirCmpwn** [comment]
And the cursor is correct over termite?

**Comment by nearffxx** [comment]
Yes

**Comment by SirCmpwn** [comment]
Then this is an Xwayland problem, nothing we can do about it (and probably nothing they can do about it either).
