### ISSUE TITLE
Floating views support

### ISSUE THREAD

**Issue by emersion** [swaywm/sway#1910]
Proposed plan:

1. Add a list of floating view containers to `sway_workspace`. The container position is in layout-local coords. The first view is the topmost one.
2. Add commands to float and un-float views
3. Render floating views, handle damage tracking
4. Handle input
5. Check that fullscreen still works
6. Automatically float views that aren't resizable. Support resizable views becoming unresizable.

Will be done later:
- Interactive move/resize

**Comment by SirCmpwn** [comment]
Lemme just ruin your day real quick: floating views are children of the workspace they're mostly in. If you switch workspaces, all of the floating windows go with it unless they're sticky.

**Comment by emersion** [comment]
Man, I shouldn't even try to write this kind of thing without a cup of coffee.

**Comment by RyanDwyer** [comment]
I have some notes about implementing this too. These are about a week old now.

My notes say to use a wl_list in the workspace, but I'm undecided. You could alternatively use a container with L_FLOATING.

My notes follow...

Add to struct sway_workspace:

* wl_list *floating // list of floating containers, position in list determines draw order

Add to struct sway_container:

* bool is_floating
* bool is_sticky
* struct sway_container *floating_workspace

Implement `floating` command:
* call container_set_floating(struct sway_container *container, bool enable)

Implement `sticky` command:
* require container to be floating or return error
* set is_sticky on container

container_set_floating():
* remove container from tree
* add to workspace's floating list
* set container's floating_workspace to workspace
* set container.is_floating
* set container's x, y, width, height
* call arrange_workspace()

change container_move():
* if container being moved is floating, only consider outputs (same logic as fullscreen)

change container_move_to():
* recenter if moving floating container to new output

change render_output():
* if not using fullscreen, call render_floating(output)

create render_floating(output):
* iterate all workspaces
* iterate their floating containers
* render if: container overlaps this output and (container's workspace is visible or container is sticky)

When focusing a floating container:
* bring to front of workspace's floating list and push others back

When mapping a view:
* If view sets certain hints, set floating
* See i3 manage.c line 433 for hints

When using move command:
* If container is floating, adjust the x/y values

For a separate PR:
* resizing floating windows with mouse
* directive: floating_modifier
* directive: focus mode_toggle
* move commands (unless it breaks stuff not having it)
* Reassign floating container's workspace when moved

Tests:
* Test rofi
* Float a container with multiple children and move them around within their floating parent
* Test placing a floating window between two outputs
* Test sticky

**Comment by SirCmpwn** [comment]
You might have covered this but I don't have time to read all of that, apologies if I'm duplicating stuff here

- List of floating windows lives on the workspace
- Floating windows have layout coordinates
- When interactively moved across outputs the parent workspace changes when the center of the view crosses the threshold

**Comment by SirCmpwn** [comment]
https://github.com/swaywm/sway/issues/2063
