### ISSUE TITLE
Xwayland window configure issues with fullscreen

### ISSUE THREAD

**Issue by emersion** [swaywm/sway#1914]
1. Open xwayland app on workspace 1
2. Open a fullscreen Xwayland app on workspace 2
3. Switch to workspace 1, cannot interact with xwayland window, input is messed up
4. Switch back to workspace 2, things get even more messed up

Tested with Firefox and Highway Blossoms.

I think this happens because we don't tell Xwayland the z-index of windows - it seems that's done with a configure event IIRC. There are also rendering issues when switching back and forth to the fullscreen container, not sure it's related, maybe we're just sending garbage configure events (osu! seems to be affected as well).

I think this is the same bug as https://github.com/swaywm/sway/issues/1902

**Comment by emersion** [comment]
We probably need to un-fullscreen when switching workspaces, and re-fullscreen when switching back.

Should investigate how i3 does it.

**Comment by ianyfan** [comment]
Is this still an issue? I don't think I've been having issues with fullscreen xwayland windows.

**Comment by emersion** [comment]
Cannot reproduce with Firefox. Will try with a game.

**Comment by emersion** [comment]
Just tried again, cannot reproduce, yay!
