### ISSUE TITLE
Add a way to set clipboard

### ISSUE THREAD

**Issue by emersion** [swaywm/sway#1919]
So in sway 0.15 we had a `clipboard <data>` command, but I'm not happy with it since the payload contents is an argument. It doesn't let you specify the MIME type and doesn't support binary data.

So here's a list of possible solutions:
1. Keep this `clipboard` command as is
2. Add a `IPC_SET_CLIPBOARD` message, this would allow to do things like `pass github.com | swaymsg -t set_clipboard`. But how to set the MIME type? Should that be a JSON header before the data?
3. Allow the `clipboard` command to take a file as input (meh, doesn't support pipes)

Thoughts?

Related: do the same for the primary selection.

**Comment by SirCmpwn** [comment]
>Add a IPC_SET_CLIPBOARD message, this would allow to do things like pass github.com | swaymsg -t set_clipboard. But how to set the MIME type? Should that be a JSON header before the data?

You can do `passs github.com | swaymsg -t set_clipboard text/plain`

**Comment by SirCmpwn** [comment]
Note, the IPC already sends along your command text even for non-command IPC messages

**Comment by emersion** [comment]
>You can do passs github.com | swaymsg -t set_clipboard text/plain

The current IPC client doesn't pipe stdin to the IPC server. I could do that and on the server side read from the client FD in a blocking mode until the client hangs up. I wonder if there's a better way to do this.

**Comment by Moelf** [comment]
How should I pass a image/png to swaymsg clipboard?
Using scenario: screenshot to the clipboard.

**Comment by emersion** [comment]
Assuming you're talking about 0.15:

> It doesn't let you specify the MIME type and doesn't support binary data.

From the issue description

**Comment by emersion** [comment]
Update: the `clipboard` command has been removed, this will be dealt with in https://github.com/swaywm/wlr-protocols/issues/20

**Comment by adabru** [comment]
In the meantime you can use [wl-clipboard](https://github.com/bugaevc/wl-clipboard). It provides the programs `wl-copy`and `wl-paste` that can deal with different MIME-types and implement some tricks that circumvent the missing clipboard-protocol.

**Comment by emersion** [comment]
The data-control protocol has been implemented a while ago.

**Comment by devurandom** [comment]
> > Add a IPC_SET_CLIPBOARD message, this would allow to do things like pass github.com | swaymsg -t set_clipboard. But how to set the MIME type? Should that be a JSON header before the data?
> 
> You can do `passs github.com | swaymsg -t set_clipboard text/plain`

Does not work with Sway WM 1.4:
```
❯ swaymsg -t set_clipboard
2020-04-10 14:26:21 - [swaymsg/main.c:448] Unknown message type set_clipboard
```

How do I do this these days?

**Comment by emersion** [comment]
https://github.com/bugaevc/wl-clipboard
