### ISSUE TITLE
Is there a way to enable icon support in gnome apps such as nautilus while in sway?

### ISSUE THREAD

**Issue by thebunnyrules** [swaywm/sway#1921]
I'm using Nautilus as a file manager in Sway since it runs native Wayland. As expected, none of the icons for the files/folders shows. Is there a way I can assign icon themes for GTK apps running in Sway?

**Comment by SirCmpwn** [comment]
If there is, it's not sway's business. Ask the Nautilus or GTK people for help.

**Comment by thebunnyrules** [comment]
Isn't icon support handled by the WM how can it not be Sway's business?

**Comment by emersion** [comment]
Nah, sway doesn't handle icons displayed in nautilus.

**Comment by thebunnyrules** [comment]
Seems strange to me but I don't really understand enough on how Nautilus or Sway works to comment. I'll ask them for help and see what they say.
