### ISSUE TITLE
Xwayland views not configured properly

### ISSUE THREAD

**Issue by emersion** [swaywm/sway#1925]
Their position is off by the title height after the first configure. To reproduce, open Firefox and open a popup or a menu right after.

If you switch to another workspace and switch back again, it reconfigures the window with the correct position.

**Comment by RyanDwyer** [comment]
I can't replicate this. I have borders showing, start Firefox from rofi, then right click on the page or left click the settings menu in the top right. The popups look aligned correctly. If I switch to another workspace and back and open the popups again then I don't notice anything different.

**Comment by emersion** [comment]
Another way to reproduce: open Atom, start typing, a few seconds there's a white flash and the view is no longer rendered at the correct position (y offset). Switching workspaces fixes it.

**Comment by apreiml** [comment]
I've similar problems with mattermost. I also tried atom and I got those messages on both of them:

```
[32477:0627/182924.431307:ERROR:gles2_cmd_decoder.cc(17652)] [.DisplayCompositor-0x1cf805e97000]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name
[32477:0627/182924.431329:ERROR:gles2_cmd_decoder.cc(9709)] [.DisplayCompositor-0x1cf805e97000]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
```

**Comment by emersion** [comment]
Can't reproduce this one anymore. I still have black buffers in Atom, but I can reproduce in Weston, so we probably can't do anything about it.
