### ISSUE TITLE
Swaybar crashes if any text contains character '&'

### ISSUE THREAD

**Issue by tardypad** [swaywm/sway#1937]
Sway 0.15.2 on Arch Linux

I initially found this bug via i3blocks display, but I've tested a bit further and setting a workspace name with a '&' inside also makes the bar crashes (when you switch to that workspace)

I don't know if this bug is related to another "Swaybar crashing" report I found #1091

**Comment by heghe** [comment]
Do you use pango markup font? Because '&' needs to be escaped when using pango. See #1935

**Comment by emersion** [comment]
Please provide a stacktrace.

**Comment by tardypad** [comment]
@heghe Indeed I was using directly pango markup within i3blocks but not when setting the workspace name
Testing a bit more on workspace name with the characters you mention in that PR:
both & and < make the bar crashes but not > and '

@emersion I don't have time at the moment to compile sway but will try one of these days
Isn't it reproduceable as such already though?
