### ISSUE TITLE
Closing a floating window goes back to "wrong" tiled window after

### ISSUE THREAD

**Issue by tardypad** [swaywm/sway#1939]
Sway 0.15.2 on Arch Linux

Steps to reproduce:
- open 2 tiled windows (we'll call them Left and Right)
- open a floating window
- go to tiled window Right
- if you use your `focus mode_toggle` binding you'll keep switching between the tiled window Right and the floating window
- now go the floating window and close it

Result:
Tiled window Left gets the focus

Expectation:
 It would be more user-friendly to have the tiled window Right gets the focus, since it was the previous one we were on

It surely is not a huge problem but it's a bit disturbing to find oneself on that wrong window afterwards
(I think the "wrong" is actually always the first window in the current layout)

**Comment by SirCmpwn** [comment]
I'm closing issues that are resolved by the yet-unrelated sway 1.0.
