### ISSUE TITLE
Floating window appears above swaylock if window launched after

### ISSUE THREAD

**Issue by tardypad** [swaywm/sway#1941]
I have a systemd timer that regularly opens a notification floating window.
If that action is triggered while swaylock is running, the window gets visible nevertheless on top of swaylock

It is "easy" to reproduce without such setup though
- Define a rule to set a window to be floating
```
for_window [title="yo"] floating enable
```
- in a terminal launch a similar command
```
sleep 10 && termite --title="yo"
```
- run swaylock during those 10 seconds

You should see the termite window displayed on top of swaylock after this delay

**Comment by SirCmpwn** [comment]
What version of sway?

**Comment by SirCmpwn** [comment]
Oh, it's obvious. 1.0 doesn't support floating yet

**Comment by SirCmpwn** [comment]
This will be addressed when [wlroots](https://github.com/swaywm/wlroots) is completed and [integrated with sway](https://github.com/swaywm/sway/issues/1390).
