### ISSUE TITLE
Mouse randomly refocuses hovered window even after changing focus via keyboard

### ISSUE THREAD

**Issue by chebykinn** [swaywm/sway#1946]
Steps to reproduce:
1. Open two windows
2. Hover mouse over first window.
3. Change focus to next window.
4. After some delay focus will be returned to first window.

Expected behavior: focus stays as it was set until mouse is moved to another window.

sway version: 7d707e6865cb123018157582f673711f20cda2f2

**Comment by chebykinn** [comment]
Can't reproduce in 0c96d757d0d5d1762390dd119cbe344e8781c19f, closing.

**Comment by chebykinn** [comment]
This is sometimes hard to reproduce, sometimes it's always happening.

**Comment by SirCmpwn** [comment]
What's the latest commit you're able to reproduce this with? of both sway and wlroots

**Comment by chebykinn** [comment]
sway: 9731d080bea58fee78bd52bb5633cb37ec7edc22
wlroots: 341af97125b4376d7a38f00299539ebb050b235c
Latest for today, just pulled recently.

**Comment by chebykinn** [comment]
Is mouse focusing based on inactivity?

**Comment by chebykinn** [comment]
I think I know why this is happening. Mouse focusing in sway is motion-based, so my mouse sometimes sends spurious motions and pointed window instantly gets focused! i3's behaviour is different. You can move mouse inside pointed window and focus will not change until you cross the border of this window.

**Comment by chebykinn** [comment]
Yes, it's focus_follow_mouse issue, quote from i3 docs: "By default, window focus follows your mouse movements **as the mouse crosses window borders.** "
