### ISSUE TITLE
Implement a method to get PID (and other relevant information) in layout tree

### ISSUE THREAD

**Issue by Marteon** [swaywm/sway#1973]
One could include the PID in `swaymsg -t get_tree`.

**Comment by adtac** [comment]
I'd like to see this as well.

My use-case is this: when I'm in a terminal and want to open another one, I'd like for the new terminal to have the same working directory as the previous one. If there was a `.pid` field, I can hack together a script that's something like `swaymsg -t get_tree | jq '.. | select(.focused? == true) | .pid` to get the PID, and then get the working directory with `readlink /proc/$PID/cwd`.

I haven't contributed to sway or read the source code before, but I'll try my hand at this this weekend :)

**Comment by ianyfan** [comment]
@adtac Are you still working on this?

**Comment by adtac** [comment]
I tried hacking something together, but I didn't get anywhere. If you'd like to pick this up, feel free!
