### ISSUE TITLE
1.0's hide_edge_borders behavior doesn't match 0.15's

### ISSUE THREAD

**Issue by ggreer** [swaywm/sway#1975]
https://github.com/swaywm/sway/pull/1960 implemented hide_edge_borders for sway 1.0. The man page says "Hide window borders adjacent to the screen edges.", but that PR hides all borders, including ones not adjacent to screen edges. Also, it hides titles if hide_edge_borders is set to "vertical" or "both".

**Comment by SirCmpwn** [comment]
cc @RedSoxFan

**Comment by RedSoxFan** [comment]
Oops. I'll submit a fix for both issues. The latter is a trivial change. Not sure about the former.

**Comment by RyanDwyer** [comment]
The former should be easily fixed. You don't need to traverse the tree to figure out if the container is at the edge of the output. Just compare the container's position to the output's dimensions (something like `container->x == 0` and `container->x + container->width == output->width`).

**Comment by SirCmpwn** [comment]
gaps

**Comment by RedSoxFan** [comment]
If there are gaps, then the border won't be on the screen edge. I think @RyanDwyer's suggestion would work. Since gaps are not yet implemented in sway 1.0, I cannot test against gaps though.
