### ISSUE TITLE
exec swaylock in config

### ISSUE THREAD

**Issue by limadm** [swaywm/sway#1980]
If I put my tty to autologin into sway and lock the screen immediately, the screen seems frozen until I use certain binds (e.g. `$mod+e exec pcmanfm`). Other binds, like `$mod+Return`, do nothing. Switching workspaces or exiting with `$mod+Shift+q` is possible.

```bash
$ head -n5 ~/.config/sway/config
# lock screen (autologin)
exec swaylock -c 203040

### Variables
#
```
With swaywm/sway@1837756dbed222a6233366f186693e1aeefc2439 and swaywm/wlroots@1e5b5d15a6da6e414ee4dec832d7d4a80e74f71e

**Comment by SirCmpwn** [comment]
This is a pretty weird use-case tbh. Can you try `exec sleep 500 && swaylock -c 203040`?

**Comment by SirCmpwn** [comment]
Note that it's a known problem that swaylock doesn't prevent keybindings from going through yet.

**Comment by limadm** [comment]
My sleep takes seconds as arguments, so I used `exec sleep 500 && swaylock -c 203040`.
After the autologin, I waited for 30s, then pressed `$mod+e`.
It opened the file manager window, and after 5 seconds, started swaylocker.
No worries, I saw the `bindsym --locked` suggestion. :)

**Comment by limadm** [comment]
Issue was fixed last week. :)
