### ISSUE TITLE
[:question:] What is the reason to unconditionally advertise giving CAP_SYS_PTRACE/TTY_CONFIG to sway

### ISSUE THREAD

**Issue by TLogiviere** [swaywm/sway#1981]
#### Hello,
From the read-me:
>On systems with logind, you need to set a few caps on the binary: `sudo setcap "cap_sys_ptrace,cap_sys_tty_config=eip" /usr/local/bin/sway`

Probably the precision that it is only needed for dev/debug purposes is missing, but let me remind you that sway actually shoots to the user that the Parent<)Child limitation of the trace capacity, enforced by the kernel for security purpose, can be a security risk (:question:):
>[sway/sway/main.c:193] !! DANGER !! Sway does not have CAP_SYS_PTRACE and cannot enforce security rules for processes running as other user

But in which world I, a fellow linux user in the endless quest for a desktop providing good UX, would give an experimental software the capacity to « trace arbitrary processes using ptrace » c.f. [the man page](https://linux.die.net/man/7/capabilities)? And so possibly eavesdrop and modify (tty_config, same man page) every corners of my system ?

Sway is not a security software right ? And obviously not the system kernel so why does it talks like such ?

**Comment by SirCmpwn** [comment]
Sway uses CAP_SYS_PTRACE to read `/proc/:pid/cmdline`, which it uses to enforce security rules. This is something we will not be doing indefinitely, we're working on a new design.

**Comment by TLogiviere** [comment]
> it uses CAP_SYS_PTRACE to enforce security rules

Can you please give at least one example of such security rules? Is there a document where I can easily consults them ?
> This is something we will not be doing indefinitely, we're working on a new design.

Definitely... This has some crazy havoc potential.

**Comment by SirCmpwn** [comment]
>Can you please give at least one example of such security rules? Is there a document where I can easily consults them ?

man 7 sway-security
