### ISSUE TITLE
Title text is rendered over right border

### ISSUE THREAD

**Issue by RyanDwyer** [swaywm/sway#1983]
If a title is long enough, it'll render over the right side border. It should stop prior to to the border. This was working but broke when damage was implemented.

The previous method used a scissor, but that can't be used now because the damage implementation uses scissoring and you can't have multiple scissors in effect at the same time.

What's a good way to resolve this? I can think of two options:

1. Change wlroots so it supports mutliple scissors.
2. Generate the texture at a clipped size, but I don't like this idea because we'd have to regenerate the textures every time a container is resized.

**Comment by emersion** [comment]
It's still using scissors for clipping, but now the clipping box is intersected with the damaged region.
