### ISSUE TITLE
mpv switching video resolutions causes damage tracking problems

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/sway#1987]
If I have mpv 0.28.2 in tiling mode and use >< to switch between videos in a playlist of different resolutions, only one of the buffers gets damaged and I start to see flashing frames in the leftover space.

**Comment by SirCmpwn** [comment]
cc @atomnuker, when switching between videos in a playlist mpv should probably re-center the video

**Comment by atomnuker** [comment]
I already reported a bug 2 days ago: #1972 
Its a bug in sway/wlroots, not mpv. mpv will resize the window and rerun the whole code to figure out what dimensions it needs to fit in, and for that it needs an xdg resize event.

**Comment by emersion** [comment]
>Its a bug in sway/wlroots, not mpv. mpv will resize the window and rerun the whole code to figure out what dimensions it needs to fit in, and for that it needs an xdg resize event.

I believe this is a mpv bug. However this issue about damage tracking is still a sway bug.

**Comment by SirCmpwn** [comment]
This is also a sway bug.

**Comment by atomnuker** [comment]
Is it? With my fix in mpv it works fine. It was a misbehaving client after all.

**Comment by emersion** [comment]
Even with misbehaving clients, sway shouldn't show damage tracking artifacts.

**Comment by emersion** [comment]
I though mpv was resizing its `wl_surface`, but it's not, so the artifacts are actually in the client buffer, we can't do anything about it.
