### ISSUE TITLE
sway should send XDG_TOPLEVEL_STATE_TILED state when appropriate

### ISSUE THREAD

**Issue by atomnuker** [swaywm/sway#1988]
Currently sway always sends the MAXIMIZED state. To be more correct, it can send XDG_TOPLEVEL_STATE_TILED_TOP/BOTTOM/LEFT/RIGHT state to inform clients as to where they are on the screen. They'll still behave the same.

**Comment by emersion** [comment]
Requires xdg-shell stable 1.14.
