### ISSUE TITLE
Launching kitty returns wl_surface@13: error 3: xdg_surface must not have a buffer at creation

### ISSUE THREAD

**Issue by dryya** [swaywm/sway#1992]
[sway.log](https://github.com/swaywm/sway/files/2007595/sway.log)
On  sway version 1.0-alpha.2-22-g76bdbe93 (May 15 2018, branch 'master'), launching the kitty terminal emulator gives this output:
```
wl_surface@13: error 3: xdg_surface must not have a buffer at creation
[135 23:29:00.699834] [glfw error 65544]: Wayland: Focusing a window requires user interaction
[135 23:29:00.699870] [glfw error 65544]: Wayland: Window position retrieval not supported
```
I've attached a debug log - I opened sway, opened kitty under xwayland, then tried to open native wayland kitty and exited.

Previous discussion at: https://github.com/kovidgoyal/kitty/issues/157.

**Comment by emersion** [comment]
Can you provide a Wayland debug log? (set `WAYLAND_DEBUG=1` and launch your client)

**Comment by SirCmpwn** [comment]
Note that it's likely that Weston is more tolerant of protocol errors than Sway, and it is in fact a kitty bug.
