### ISSUE TITLE
Cursor not working near bottom and right edges

### ISSUE THREAD

**Issue by maxhetfeld** [swaywm/sway#1997]
Given: One app is open in fullscreen mode.

When you move mouse cursor to the right or bottom edge in any app cursor stops controlling or working in the app.

For example in Firefox when you move mouse cursor to the right edge you expect to touch a scrollbar and begin scrolling, but this is not happening.

I've tried everything from here in my config:

```
new_window pixel 0
window_border 0
default_border none
hide_edge_borders both
focus_follows_mouse no
```

Still was not able to use the mouse cursor.

**Comment by SirCmpwn** [comment]
What version of sway?

**Comment by SirCmpwn** [comment]
I can't reproduce on wlroots. We're moving away from wlc.
