### ISSUE TITLE
Gaps & Other features

### ISSUE THREAD

**Issue by natesymer** [swaywm/sway#1998]
I was wondering what the status of the configuration commands was. Specifically, I'm interested in when gaps will be implemented.

I had seen a checklist in the issues before the alpha versions of Sway 1.0.0, but now I can't seem to find it. If it's still being updated, where is it?

**Comment by emersion** [comment]
Gaps are implemented in sway 0.15. The status of the wlroots implementation is here: https://github.com/swaywm/sway/issues/1390

**Comment by natesymer** [comment]
Right, Gaps are implemented in sway 0.15, but I want to use the latest. Do you have plans to implement gaps in 1.0.0?

**Comment by emersion** [comment]
Read the status issue I linked above, grep for gaps. Patches welcome!
