### ISSUE TITLE
configuring 

### ISSUE THREAD

**Issue by kzwkt** [swaywm/sway#2001]
mz kezboard is acting weird on coppzing sample config to sway/config y and z are swapped and shift+1234 are producing weird szmbols how to fix that

**Comment by SirCmpwn** [comment]
What's your keyboard layout? Did you configure it?

**Comment by kzwkt** [comment]
how to set it i dont know it works fine in xorg though

**Comment by SirCmpwn** [comment]
Answer the damn questions you're asked

**Comment by kzwkt** [comment]
i didnt configure it in sway

**Comment by maxhetfeld** [comment]
i assume you've copied `.bash_profile` configuration from Arch Linux wiki.

Check what encoding you have:

```
if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
  XKB_DEFAULT_LAYOUT=**us** exec sway
fi
```
