### ISSUE TITLE
If an xdg-toplevel which is a child of another is fullscreened by the client...

### ISSUE THREAD

**Issue by ddevault** [swaywm/sway#2002]
sway will fullscreen its parent instead.

**Comment by SirCmpwn** [comment]
Example: virt-manager does this when you open a VM.

**Comment by RedSoxFan** [comment]
Are you still able to reproduce this? I think this might have been fixed sometime in the last ~10 months.

**Comment by ddevault** [comment]
Nah, I haven't seen this lately.
