### ISSUE TITLE
Missing blinking cursor in Intellij Idea after moving focus back

### ISSUE THREAD

**Issue by anti-social** [swaywm/sway#2008]
After the main Idea's window is refocused, the blinking cursor in the edit area disappears. A row where the cursor should be is highlighted, control keys works but text editing is broken. To restore editing I should click anywhere in the edit area.

The problem is also present in weston.

**Comment by emersion** [comment]
Which sway version are you using?

**Comment by anti-social** [comment]
`0.15.2`

**Comment by apreiml** [comment]
This also happens in current master branch.

Could this be related to https://github.com/swaywm/wlroots/issues/678?

**Comment by emersion** [comment]
Probably not. swaywm/wlroots#678 is rootston-specific.

**Comment by apreiml** [comment]
Here's a small java application to reproduce the issue https://gist.github.com/apreiml/df8272f44975fca592453865fd9f62d0

It also fails with rootston when alt tabbing between windows. It works fine with i3 though.

**Comment by MaBeuLux88** [comment]
Using i3wm, I had a similar problem and google lead me here. Switching to another window and coming back to IntelliJ / Pycharm / WebStorm results in a lost blinking cursor. I had to click with my mouse on the IDE to get it back.
Solution that needs to be applied in all the tools: Help > Edit Custom Properties... > add this line: "suppress.focus.stealing=false" > Save & restart the IDE.

**Comment by mirabilos** [comment]
Unfortunately, this does not seem to work with evilwm ☹
