### ISSUE TITLE
External monitor and laptop display being merged into one

### ISSUE THREAD

**Issue by juicetin** [swaywm/sway#2013]
Hi,

When starting sway (from tty with `startx` with `exec sway` in the `.xinitrc`) with a 4k monitor plugged into my 1080p laptop on Arch (kernel version 4.16.8-1), I get a single large monitor that's 3840x2610+1080 (the 'missing' 1920 on the laptop below the 4k in layout is simply cut off).

Running `swaywm -t get_outputs` confirms that this is the case as well, showing just a single display.

**Comment by emersion** [comment]
Sway isn't an X11 compositor. To start it, just run `sway` in a tty (without `startx`).

**Comment by juicetin** [comment]
Yikes, didn't even realise my mistake as I typed it out. Thanks!
