### ISSUE TITLE
Cursor changes size

### ISSUE THREAD

**Issue by mklpiening** [swaywm/sway#2014]
### Problem
My cursor increases its size by 2 when focussing a program. If I move the cursor away from the window, it shrinks back to its normal size.

This happens with every Program I am using.

The problem persists when I scale my monitors using the hidpi function.

### Setup
2 3840x2160 monitors
sway 0.15.2
Fedora 28

**Comment by emersion** [comment]
What's the program you're using?

In Wayland, the cursor is always set by the app, so some apps might use a cursor size which is too large (e.g. all Weston clients).

**Comment by mklpiening** [comment]
I am using mainly urxvt, firefox, audacity, chromium and vscode and the problem persists with all of these programs.

**Comment by emersion** [comment]
These are all xwayland programs, so this seems like a bug in sway 0.15.

**Comment by NicholasAsimov** [comment]
Weirdly I have the same issue on sway 1.0@0f71547. xwayland programs have much larger cursor.

I have 1 monitor with 2560x1440 resolution.

**Comment by somdoron** [comment]
@NicholasAsimov I was able to fix it by setting the cursor size to 16 in .Xdefaults
```
Xcursor.size: 16
```

**Comment by NicholasAsimov** [comment]
@somdoron thanks, great info!
