### ISSUE TITLE
Switching VTs works randomly

### ISSUE THREAD

**Issue by emersion** [swaywm/sway#2020]
With a fresh session, it works well. For some reason, after some time, it doesn't work anymore.

**Comment by ascent12** [comment]
Oddly enough, opening X11 in another VT seems to affect it.

**Comment by Marteon** [comment]
But using `chvt` always works. Only the Keycombo doesn't work.

**Comment by smlx** [comment]
I can reproduce this by starting and exiting gvim immediately after starting sway.
It doesn't occur after just starting gvim - exiting is what triggers it.
