### ISSUE TITLE
source_based games non_sticked cursor

### ISSUE THREAD

**Issue by DpoBoceka** [swaywm/sway#2038]
When I launch any source game (counter-strike 1.6, half-life 1/2 etc) from steam and place it on unoccupied workspace - the cursor doesn't "stick" to a crosshair. So I can "roam" on the application like it's a regiular browser. Same issue with most modern source games. 
Perhaps, the solution is quite simple and someone can help me out?

**Comment by SirCmpwn** [comment]
This is a known problem, it's being worked on.

**Comment by ILMostro** [comment]
Any additional information or links to ongoing work regarding this?
I see the same thing with CS:GO (first-person shooter game) in Steam.
Is this an issue with sway or steam?

**Comment by ascent12** [comment]
It depends on the pointer-constraints and relative-pointer wayland protocols, which is still being worked on inside wlroots.

**Comment by ILMostro** [comment]
@ascent12 thank you for that quick response.  I did also notice [another bug](https://github.com/swaywm/sway/issues/2227) where that's mentioned as well.  Hopefully, this helps in keeping track of duplicate or similar issues; and it may prevent additional duplicates from being opened.
So the relevant work is being done within the `wlroots` project/library.
