### ISSUE TITLE
Proposal: only one swaybg instance for all outputs

### ISSUE THREAD

**Issue by emersion** [swaywm/sway#2051]
Instead of starting one `swaybg` instance per output, only have one for all of them.
* This is more consistent with `swaybar`
* This removes the need for the compositor to (re-)spawn or kill `swaybg` when an output is hotplugged or when the config is updated
* This makes `swaybg` easier to run on other compositors

**Comment by SirCmpwn** [comment]
+1

**Comment by SirCmpwn** [comment]
We might also consider making the command line interface user-friendly

**Comment by ianyfan** [comment]
What about: `swaybg -o <output> [-i <image> -m <mode> -c <color>] -o <another-output> etc.` as CLI, with long options?

Also, would this mean that if no valid outputs are found, swaybg would continue to run in case a valid output is then hotplugged?

**Comment by ddevault** [comment]
+1

**Comment by ianyfan** [comment]
Unfortunately, my above suggestion would break any other programs that can currently be used as `swaybg_command`.

**Comment by emersion** [comment]
I don't think we want to keep the current `swaybg` CLI interface.

**Comment by ddevault** [comment]
We've never made any API stability promises about the swaybg interface. [In fact...](https://github.com/swaywm/sway/blob/master/swaybg/main.c#L263)

**Comment by RedSoxFan** [comment]
> This removes the need for the compositor to (re-)spawn or kill swaybg when an output is hotplugged or when the config is updated

If swaybg doesn't get (re-)spawned when the output config changes, wouldn't that require an IPC protocol or a wallpaper wayland protocol to obtain the change?

**Comment by emersion** [comment]
Yes. Let's keep it simple and restart on config change.
