### ISSUE TITLE
swaylock unicode support

### ISSUE THREAD

**Issue by Organic-Code** [swaywm/sway#2061]
Swaylock does not handle all unicode characters (namely : à, é, è, ç, «, » [probably others but didn't test more ; I did test for characters like ï, ®, þ, ..., which did not work either, but those require altgr+key combination for my keyboard layout and I am not sure wether altgr combinations are supported by swaylock or not, given that it seems to consider altgr itself as a keypress and not as a dead key])

nb: using sway 0.15.2

**Comment by SirCmpwn** [comment]
Can you try it on master? swaylock now uses UTF-8.

**Comment by Organic-Code** [comment]
It work as intended on master, with algr combinations as well
