### ISSUE TITLE
Floating status

### ISSUE THREAD

**Issue by RyanDwyer** [swaywm/sway#2063]
- [x] Basic floating support
- [x] Automatically detect and float xwayland modals/dialogs/etc
- [x] `sticky`
- [x] `floating_modifier`
- [x] `floating_minimum_size` and `floating_maximum_size`
- [x] `default_floating_border`
- [x] `focus mode_toggle`
- [x] `focus floating` and `focus tiling`
- [x] `move <direction> <px>`
- [x] `move [absolute] position`
- [x] `move position mouse`
- [x] `move container to workspace` on a floating container
- [x] `resize grow|shrink <direction> <px>`
- [x] `resize set <width> <height>`
- [x] Move window by dragging title bar
- [x] Resize floating views by dragging borders
- [x] Ensure `sway_workspace->floating->children` remains in focus order
- [x] Allow floating containers

**Comment by SirCmpwn** [comment]
Note all of the interactive move/resize stuff also applies to tiled views

**Comment by RedSoxFan** [comment]
All items listed above are now implemented

**Comment by sharethewisdom** [comment]
I have a window assigned to a workspace that appears on a large output. I need it to float, and I'd like a larger `floating_minimum_size` and `floating_maximum_size` only for windows in that workspace.

Can this be done? My `for_window` [..] floating_minimum_size 1920 x 1000 doesn't take affect.

`sway version 1.1-rc1-3-g9dca18b6 (May  7 2019, branch 'master')`
