### ISSUE TITLE
Display doesn't support idle protocol

### ISSUE THREAD

**Issue by ya-isakov** [swaywm/sway#2071]
Hello! I'm testing sway from master branch, and found that swayidle is not working if started from sway config. Here is how it is in config:
exec swayidle timeout 30 'swaylock -c 000000' timeout 60 'swaymsg "output * dpms off"' resume 'swaymsg "output * dpms on"' before-sleep 'swaylock -c 000000'
After exiting sway, on console I can see this message: Display doesn't support idle protocol

If I'm starting it from e.g. weston-terminal in running sway, everything works properly

**Comment by SirCmpwn** [comment]
Has anyone confirmed this? Is it still reproducable?

**Comment by ya-isakov** [comment]
I've tried to reproduce it on new master, and cannot, so closing it
