### ISSUE TITLE
sway evoked from tty: no mouse and no keyboard (swaymsg -t get_inputs doesn't show anything)

### ISSUE THREAD

**Issue by Tormen** [swaywm/sway#2086]
# PROBLEM:
sway when started without Xorg (from tty) seems to start fine, config gets parsed, mouse pointer large in top left corner visible, but:
no keyboard shortcut except ctrl+alt+del to restart works and mouse is also stuck.

Even Ctrl+Alt+F3 trying to attempt tty does not work.
Even after Sysreq + R (release) this does not work.

## // Potentially related:
`swaymsg -t get_inputs` returns an EMPTY list `[ ]`

Evoking sway from within kde running Xorg works fine, but also here the `swaymsg -t get_inputs` is EMPTY.

# SETUP & VERSIONS
archlinux 64-bit with `sway`, `wayland`, `xorg-server-xwayland` installed

sway version 0.15.2

# CONFIG FILE:
1. FIRST I tried without user config, so using `/etc/sway/config`
    --> same problem

1. THEN I tried to create `~/.config/sway/config`
    containing `/etc/sway/config` + some extra lines at the end, see:
https://0x0.st/s2RS.txt

# DEBUG OUTPUT:
evoked from `~/.zshrc` with:

        `XKB_DEFAULT_LAYOUT=us exec /usr/bin/sway --debug > ~/sway.log 2>&1`

`sway.log` see:

https://0x0.st/s2RM.txt

## // swaymsg___get_inputs.log:
https://0x0.st/s2Rj.txt

## // swaymsg___get_outputs.log:
https://0x0.st/s2Re.txt

**Comment by SirCmpwn** [comment]
I'm closing issues that are resolved by the yet-unrelated sway 1.0.
