### ISSUE TITLE
mpv/wayland sometimes become stuck

### ISSUE THREAD

**Issue by emersion** [swaywm/sway#2090]
I'm not sure how to reproduce this reliably, but sometimes mpv's output freezes when using the wayland backend. Moving the cursor fixes it after some time.

**Comment by bitraid** [comment]
For me mpv always freezes under sway (both versions 0.x and 1.0alpha), whether using wayland or xwayland for mpv, if it starts from qutebrowser (running under wayland) and then move it to a different workspace and switch to it. After 9 seconds it freezes, and gets fixed when switching back to qutebrowser's workspace (but freezes againg after 9 seconds if i leave that workspace). I've seen this happening on multiple machines running  archlinux x64.

**Comment by RyanDwyer** [comment]
Completely random guess here, but could it be that the system is under too much load? Could it be taking more than 16.6ms to render a frame? That would explain why it happens consistently for some people and inconsistently for others. And why it happened for emersion when he opened 3-4 instances of mpv.

**Comment by martinetd** [comment]
If you think it's missing some callback and fucks its loop up (I still think for opengl mpv should setup the frame callback in swap buffer and not from the previous frame callback), feel free to try this commit: https://github.com/martinetd/mpv/commit/853119a130cab9211446d2b8e6fa4aae5f390482 ; that doesn't work for vulkan so it's not a proper fix and won't get taken but might give an idea...

I can't reproduce it at all, if you can send some log with WAYLAND_DEBUG=1 indicating around what timestamp the freeze starts it might help figure it out.


On the other hand, I got a fun one just now... Probably unrelated and should report that to the other side, nothing I could do woke it up
```
[vo/gpu/opengl] vertex shader source:
[vo/gpu/opengl] [  1] #version 440
[vo/gpu/opengl] [  2] #define tex1D texture
[vo/gpu/opengl] [  3] #define tex3D texture
[vo/gpu/opengl] [  4] #define LUT_POS(x, lut_size) mix(0.5 / (lut_size), 1.0 - 0.5 / (lut_size), (x))
[vo/gpu/opengl] [  5] in vec2 vertex_position;
[vo/gpu/opengl] [  6] in vec2 vertex_texcoord0;
[vo/gpu/opengl] [  7] out vec2 texcoord0;
[vo/gpu/opengl] [  8] in vec2 vertex_t_color;
[vo/gpu/opengl] [  9] out vec4 ass_color;
[vo/gpu/opengl] [ 10] void main() {
[vo/gpu/opengl] [ 11] gl_Position = vec4(vertex_position, 1.0, 1.0);
[vo/gpu/opengl] [ 12] texcoord = vertex_texcoord;
[vo/gpu/opengl] [ 13] ass_color = vertex_ass_color;
[vo/gpu/opengl] [ 14] }
[vo/gpu/opengl] vertex shader compile log (status=0):
[vo/gpu/opengl] 0:12(1): error: `texcoord' undeclared
[vo/gpu/opengl] 0:12(12): error: `vertex_texcoord' undeclared
[vo/gpu/opengl] 0:13(13): error: `vertex_ass_color' undeclared
[vo/gpu/opengl] 
[vo/gpu/opengl] shader link log (status=0): error: linking with uncompiled/unspecialized shader
```

**Comment by bitraid** [comment]
I tried @martinetd commit, but it still freezes. The system is not under heavy load, either. The combination i previously described, always freezes mpv - but i'm not able to capture the wayland debug of mpv when is directly spawn from qutebrowser. Calling a script to start mpv and capture the debug doesn't reproduce the problem. The detailed steps i use to freeze mpv are:
- Start qutebrowser using wayland: make sure `qt.force_platform = 'xcb'` is not present in `config.py` and the env variable `QUTE_SKIP_WAYLAND_CHECK=1` is set.
- Enter command mode `:` and call mpv to play a video, e.g: `spawn mpv https://www.youtube.com/watch?v=Zsz7Shbnb9c` (needs youtube-dl, you can also use a local video).
- Move the mpv window to a different workspace and switch to it (or to any workspace other than the one qutebrowser is). It takes about 8-9 seconds for mpv to freeze (i've tested it on different machines).
- Switching back to qutebrowser's workspace unfreezes mpv.

**Comment by martinetd** [comment]
That's probably different, maybe something with qutebrowser buffering stdout since redirecting stdout makes the problem go away. switching back to qutebrowser workspace would give qutebrowser the focus so that might do something about how it handles the output? You can check what happens with strace on the mpv process

**Comment by bitraid** [comment]
Well, thats weird: running strace to the mpv process, stops the problem from reproducing. I guess it has something to do with QT running under wayland - so yeah, that must be a different problem.

**Comment by aminb** [comment]
Out of curiosity, have you tried setting mpv's `x11-bypass-compositor=no` and see if that works around the issue or not? You can either do that in the config file or like `mpv --x11-bypass-compositor=no` in terminal.

**Comment by bitraid** [comment]
Thanks for the suggestion @aminb - i tried it but still the same.
What did work though is the `--no-terminal`, so i think @martinetd guessed it right: something to do with mpv's stdout, when is run from QT under wayland (under x11 is ok). Something similar to when running mpv under tmux and then entering `copy-mode`.

**Comment by emersion** [comment]
I've not seen this for a while. Will reopen if I can reproduce again.
