### ISSUE TITLE
Consider Moving Away from Github

### ISSUE THREAD

**Issue by Hyleus** [swaywm/sway#2104]
With the recent news about Microsoft acquiring Github, I believe it's time that Sway should consider to move somewhere else, maybe Gitlab could be considered? The software is itself FOSS. I believe that projects like Sway, which are free software, should be hosted itself on a platform which is free and isn't run by a mega corporation, which was/is in the past very harmful to software in general.

I've made this issue here, but I believe it also applies to wlroots and the other stuff.

**Comment by emersion** [comment]
Deplicate of #22
