### ISSUE TITLE
Toggling dpms changes output layout

### ISSUE THREAD

**Issue by RyanDwyer** [swaywm/sway#2127]
Run the following: `swaymsg "output * dpms off"; sleep 3; swaymsg "output * dpms on"`.

On resume, my output layout is changed to an automatically generated one. The positioning I have in my config is ignored but transformations are preserved. Running `swaymsg reload` makes it re-apply the positioning from my config.

**Comment by emersion** [comment]
This is because when you run `output * dpms off`, the output position is changed to be automatic instead of fixed. Related to #2122 - as said on IRC, we probably want a function that merges output configs, and don't change the output positioning if not specified in the config.
