### ISSUE TITLE
mouse, window focus

### ISSUE THREAD

**Issue by ReK2Fernandez** [swaywm/sway#2132]
I experience this on i3 and when I switched  some of my computers to sway same issue. 
https://github.com/i3/i3/issues/2778
example of what just happened to me, I am on 4 terminals and I mouse over to another one but when I type im still typing on the old terminal.. takes some times, and rituals to finally get it to type on the terminal I am focusing with the mouse.
im at work now and just happened to me and is very annoying, will get more detailes if needed when home tonight.
 blackarch ~ ]$ sway -v
sway version 0.15.2

**Comment by adonikh** [comment]
Hello, I'm having the same issue with mouse window focus, It doesn't work at first boot up when I log out and log back in it works again normally. Any luck fixing this?
