### ISSUE TITLE
Clipboard issue with some characters

### ISSUE THREAD

**Issue by tardypad** [swaywm/sway#2133]
Sway 0.15.2 on Arch Linux

I've noticed some issues when using the `swaymsg clipboard <data>` command

* "impossible" to copy when `<data>` contains a ',' or a ';'
```
$ swaymsg clipboard 'a,b'
Error: Unknown/invalid command
```
I tried to escape the ',' but then it's part of the result
```
$ swaymsg clipboard 'a\,b'
$ swaymsg -t get_clipboard text/plain
a\,b
```

* when there are multiple consecutive spaces, they get squeezed
```
$ swaymsg clipboard 'a    b'
$ swaymsg -t get_clipboard text/plain              
a b
```

**Comment by SirCmpwn** [comment]
We're not going to support using the clipboard this way from 1.0 forward.

**Comment by SirCmpwn** [comment]
(and the new approach won't have this issue)
