### ISSUE TITLE
container builds for testing and development

### ISSUE THREAD

**Issue by colin-williams** [swaywm/sway#2142]
I asked in the irc channel awhile back. It might be easier to develop and test if we could create containerizable builds of `sway` and  requirements https://github.com/swaywm/wlroots so we could run a both a stable environment and a seperate test environment. It also might be useful for regression testing, comparing builds.

I'm not sure what's required to make this work. But I believe people have containerized other desktop environments.

**Comment by SirCmpwn** [comment]
This isn't really something I'm interested in supporting upstream, but it might be possible for others to do.

**Comment by smlx** [comment]
@colin-williams you might be interested in this Docker-based builder https://gitlab.com/smlx/sway-build

It's Debian-specific, but should be adaptable for other distros.
