### ISSUE TITLE
how soon sway get in debian repository?

### ISSUE THREAD

**Issue by likeubuntu** [swaywm/sway#2148]
thanks for reply.
but this package no in debian and ubuntu repository.

**Comment by likeubuntu** [comment]
da i pohuy na etoto proect togda

**Comment by emersion** [comment]
The wiki has some instructions to install sway on debian/ubuntu: https://github.com/swaywm/sway/wiki/Debian-installation-guide

Please use IRC if you need support. Issues are for bug reports. You're sending 250 emails each time you submit one.

**Comment by likeubuntu** [comment]
sway not work with xwayland?
i see xwayland need for depends.
sry my second question in closed thread but this principial quest for me, i not use xwayand and no have this in system.

**Comment by emersion** [comment]
>Please use IRC if you need support. Issues are for bug reports. You're sending 250 emails each time you submit one.

http://webchat.freenode.net/?channels=sway&uio=d4

**Comment by likeubuntu** [comment]
well, in any case, thanks, I realized what sway is at this stage of development. success to you with this project.
I hope soon it will be available in Debian and ubuntu and remove the dependence as a mandatory xwayland.
at the moment I will continue to use weston.
closed.
