### ISSUE TITLE
input commands don't work in config file

### ISSUE THREAD

**Issue by Hello71** [swaywm/sway#2156]
Ever since switching to wlroots, input commands do not work in the config file. I have tried the following:

```
input "1267:5:Elan_Touchp" {
    accel_profile adaptive
    tap enabled
    click_method clickfinger
}
```

```
input 1267:5:Elan_Touchp accel_profile adaptive
input 1267:5:Elan_Touchp tap enabled
input 1267:5:Elan_Touchp click_method clickfinger
```

None of the selected options appear to be activated. However, if I enter the second block on the command line with each preceded by `swaymsg`, they are successfully activated.

**Comment by SirCmpwn** [comment]
which version of sway?

**Comment by Hello71** [comment]
git master. I see that the libinput is initialized *after* the config is read, so I have no idea how this is supposed to work. (maybe I should look at the output config...)

**Comment by SirCmpwn** [comment]
We have a function which applies input configuration when new input devices are discovered.

**Comment by Hello71** [comment]
The name of the input got "ad" added to the end.
