### ISSUE TITLE
Make it easier to toggle inputs

### ISSUE THREAD

**Issue by rileyinman** [swaywm/sway#2157]
From my limited knowledge of libinput, it seems like it should be possible to query the current events state of an input and toggle it. Currently `sway input` can only send the 3 state events of libinput but it would be nice to have a user-accessible `toggle` event for purposes such as keyboard shortcuts or scripting. I currently use a ThinkPad and therefore toggle the touchpad on a semi-regular basis, so this would be a great help for me.

**Comment by The-King-of-Toasters** [comment]
I second adding an event toggle feature. Coming from i3 `XF86TouchpadToggle` worked OOTB. I've replicated this using a script, but it's too process intensive for actual use.
