### ISSUE TITLE
Moving views from hidpi to lodpi outputs doesn't re-render borders

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/sway#2158]

**Comment by RyanDwyer** [comment]
Can you please provide steps to reproduce? I set up two outputs in a nested session with one of them having a scale of 2, then moved a floating view between the two and observed the title texture updating correctly. Then I moved a tiled view between the outputs and also observed the title texture updating.

**Comment by SirCmpwn** [comment]
Can no longer reproduce this
