### ISSUE TITLE
Damage tracking issues with floating windows

### ISSUE THREAD

**Issue by emersion** [swaywm/sway#2160]
Run e.g.

```
env WAYLAND_DISPLAY= zenity --modal --error
```

Try clicking the button.

**Comment by RyanDwyer** [comment]
This is fixed in the atomic PR.

For anyone trying to replicate this, I found I needed to have `for_window [class="Zenity"] floating enable` in my config, and I needed to run zenity on an empty workspace which means launching it via rofi rather than by terminal.

**Comment by emersion** [comment]
Note that _sometimes_ it works properly, and sometimes it doesn't. Never got zenity to work correctly though.

Yeah, you need to float zenity (I'm using my xwayland autofloat branch right now, so I didn't have to do it manually). Also I can reproduce when the workspace isn't empty.

**Comment by RyanDwyer** [comment]
Can you confirm it's not an issue in my atomic branch?

**Comment by emersion** [comment]
Was a duplicate of #2161, as I'm not running atomic yet but can't reproduce anymore.
