### ISSUE TITLE
Floating gpg-pinentry doesn't seem to get frame events

### ISSUE THREAD

**Issue by emersion** [swaywm/sway#2161]
This one is pretty weird. From time to time `pinentry-gnome3` doesn't seem to get frame events and is frozen to a unfocused state. This doesn't seem like a damage issue because switching workspaces doesn't make it go away. Input events are processed correctly though, as I can type my password normally (without visual feedback).

**Comment by aperezdc** [comment]
I have seen this as well, and is 100% reproducible when the layout of the active container is “tabbed” when `pinentry-gnome3` is executed. Switching the layout to “split” makes the window receive events again.

**Comment by emersion** [comment]
Oh, that makes sense - this is probably a `view_is_visible` issue then.

**Comment by SirCmpwn** [comment]
This happens for me with split layouts too.

**Comment by emersion** [comment]
>This happens for me with split layouts too.

Cannot reproduce.
