### ISSUE TITLE
hidpi unplug monitor re-render issue

### ISSUE THREAD

**Issue by floatious** [swaywm/sway#2167]
I'm using sway from master branch, a couple of days old.

My laptop has a hidpi screen, I use scaling on this screen.
I also have an external monitor (with no scaling).

output eDP-1 scale 2 pos 0 0
output DP-2 transform 270

The font in my gnome-terminal and in chromium on the laptop screen is really crisp.

If I unplug my external monitor, I can see that the laptop screen is re-rendered.

The font in all existing windows (chromium and gnome-terminals) gets really blurry.
It looks like the windows have been scaled up and then scaled down, i.e. a very noticeable
loss of quality.

However, if I open up new window (like a new gnome-terminal), the font in that new
window is really crisp. (Like normal).
The existing windows are still blurry though.

**Comment by CharliesPotteryEmporium** [comment]
The same occurs when reloading configuration file ($mod+shift+c)

**Comment by tokyovigilante** [comment]
Also noticing this when waking an output from sleep (Radeon VII with mesa drivers).

**Comment by RedSoxFan** [comment]
Possibly related #4314. Not sure due to the age of this issue.

**Comment by emersion** [comment]
Can you still reproduce this issue?

**Comment by floatious** [comment]
Haven't noticed the issue in recent releases.
