### ISSUE TITLE
Window border renders over context menu and can't use context menu parts outside the window

### ISSUE THREAD

**Issue by minus7** [swaywm/sway#2189]
Steps to reproduce:
1. Run xfce4-terminal (Gtk3 not specifically configured to use wayland)
2. Right click at the lower/right part of the window, so the context menu will need to move outside the window
3. Enjoy border drawn over menu.
  Bonus: can't hover items outside the main window.
  Bonus 2: artifacts after the menu closes

![screen](https://user-images.githubusercontent.com/419104/42136715-2ce04d5a-7d61-11e8-9b1d-af2f70b2242b.png)

**Comment by RyanDwyer** [comment]
The rendering is fixed in #2183, and the cursor interaction will be fixed in #2062 which I'll do afterwards.

**Comment by RyanDwyer** [comment]
Fixed by #2772.
