### ISSUE TITLE
pasting does not work in weston-terminal (crashes weston-terminal)

### ISSUE THREAD

**Issue by stapelberg** [swaywm/sway#221]
Steps to reproduce:
1. Select a word
2. Open the context menu, chose Copy
3. Open the context menu again, chose Paste
4. Observe how the weston-terminal window closed instead of the word being pasted.

The feature works in weston, but is broken in sway.

**Comment by SirCmpwn** [comment]
Likely an issue with wlc. Clipboard is "partially working" in wlc. Paging @Cloudef.

**Comment by Cloudef** [comment]
Partially working mainly means that xwayland <-> wayland isn't handled. This sounds more like bug in wlc's data-device implementation.
