### ISSUE TITLE
Any electron app and sway crashes the electron app

### ISSUE THREAD

**Issue by ReK2Fernandez** [swaywm/sway#2221]
I been noticing this only on wayland/sway  possible all wayland... but I only use sway under wayland so can't really tell. But this is annoying and I'm sure is a electron thing because that thing sucks... I hate it, but some apps(signal, keybase) the devs are to lazy to create real desktop UI's in QT/GTK etc and do electron, so is basically a browser, what I don't get is that chromium does not crashes but electron does, supposedly is the same technology... so just wanted to open this for 2 reasons.
- Im I the only one experiencing this?
- If is more people, why is this happening? is there a work around?

Symptoms:
at first works fine.. after a bit specially with signal or keybase when I get a msg to me, then it freezes until I kill it and restart it, and again the same process... so far only when someone msg's me. 

Thanks.

**Comment by emersion** [comment]
Which sway version?

**Comment by ReK2Fernandez** [comment]
@emersion latest stable
```
[ blackarch ~ ]$ sway -version
sway version 0.15.2
```
have not try on the 1.x beta yet

**Comment by ReK2Fernandez** [comment]
@emersion so this is fixed on the 1.x of sway? is it ready for me to upgrade since I use signal/keybase a lot on a daily basis? or should I wait? I dont mind small bugs here and there, but this one in particular may be worse than the ones on 1.x for me.

**Comment by emersion** [comment]
I use Atom and Keybase on Sway 1.0. Sway 1.0 is not for end users, it's for developers. That means a lot of things are not yet implemented and/or broken. You can try it out, but don't expect us to help you setting it up.

**Comment by ReK2Fernandez** [comment]
@emersion I was a developer before I started to work as a penetration tester 15 years a go, still code and build my own tools, so I think  I can handle it, my worries are only the state of usability, but I don't need much, if I can run terminology, my browsers and keybase/signal im good.

**Comment by ReK2Fernandez** [comment]
I fixed this today  https://github.com/signalapp/Signal-Desktop/issues/2567
