### ISSUE TITLE
Mouse spinning in X11 games

### ISSUE THREAD

**Issue by blitmap** [swaywm/sway#2227]
I'm not sure how to describe this issue without sounding very uninformed.

I can play Left4Dead2 through Steam in weston.  I cannot do this with sway.  I am running Arch Linux and I have tried with both the regular sway package and the "sway-wlroots-git" package.  L4D2 runs well with no issues in weston.  With sway, when I move the mouse it just shows the view spinning as if I'm looking at my feet and turning around in a circle.  (it spins very rapidly)

If I had to guess I would say this is related to relative pointer events?  I imagine this is part of xwayland support.

Thank you for your time. <3

**Comment by blitmap** [comment]
I'm not sure why the tag 'fixed by wlroots' was added...  I built the 'sway-wlroots-git' package.  It was not working.  Are you saying in the future it may be fixed by that library?

**Comment by emersion** [comment]
It's being worked on, and it's not a Sway issue, it's a wlroots issue.

**Comment by YaLTeR** [comment]
Hey so I'm hitting this issue in sway and it works correctly in rootston. Maybe it's a sway issue after all?
`sway version 1.0-beta.2-136-g14cab786 (Jan  9 2019, branch 'master')`

**Comment by emersion** [comment]
Duplicate of https://github.com/swaywm/sway/issues/2382
