### ISSUE TITLE
keys in mupdf don't work

### ISSUE THREAD

**Issue by Hello71** [swaywm/sway#2231]
steps to reproduce:

1. install mupdf
2. mupdf a pdf file
3. press buttons

expected results:

the action is performed (e.g. q quits, arrows move the document)

actual results:

nothing happens

additional information:

mupdf 1.13.0-1
sway 1.0.alpha.3.r186.g6595d07e-1
wlroots r2825.ffc87808-1

it was definitely working before, now it doesn't. funnily enough though, it *does* work if I run sway in sway. also, mouse dragging still works.

**Comment by RedSoxFan** [comment]
I tried to look into this. `mupdf` is working as expected in `sway 0.15.2`. However it does not work in `rootston` either, which suggests this is either a `wlroots` issue or an issue in both `rootston` and `sway`.

Looking at `WAYLAND_DEBUG=1` for `rootston` and `sway master`, the key events are being emitted. However when I attach `xev` to the window id, there are no keyboard events received (mouse events are being received). I'm not noticing any obvious differences in the output of `WAYLAND_DEBUG=1` for `sway 0.15.2`, where it is working.

**Comment by sharethewisdom** [comment]
Is there some progress on this issue? Should one create a `wlroots` issue, then? How can I help other than confirming @RedSoxFan 's observations? I 'd really like this to be solved because I heavily rely on both sway-wlroots and mupdf. The same problem occurs with [mupdf-gl](https://www.archlinux.org/packages/community/x86_64/mupdf-gl/), by the way.

I guess mupdf does not _"set metadata to its windows"_ (as quoted from xdotool(1)), and so there is no PID associated with it. Is that a problem?

**Comment by ianyfan** [comment]
Strangely, keys seems to work when mupdf is the first xwayland window to be opened, but not after that.

**Comment by jplatte** [comment]
I'm experiencing a very similar issue in the Signal desktop app. Mouse events are received, but keyboard events are *often* not received. What I mean by often is that sometimes it just doesn't work at all, and sometimes it works for a while after starting Signal and then it stops working.

**Comment by Wolf480pl** [comment]
According to `xwininfo -all`, mupdf doesn't set the input flag in WM hints.

I looked it up in the [ICCCM Spec](https://www.x.org/releases/X11R7.6/doc/xorg-docs/specs/ICCCM/icccm.html#input_focus), and looks like there are 3 ways to handle input (and 1 to not handle it), and one of them involves setting WM_TAKE_FOCUS in WM_PROTOCOLS, but unsetting the input flag... in which case the WM should still send the WM_TAKE_FOCUS message, if I understand correctly?
