### ISSUE TITLE
mpv/xwayland fullscreen isn't atomic

### ISSUE THREAD

**Issue by emersion** [swaywm/sway#2237]
Fullscreen is not part of transactions yet.

**Comment by RyanDwyer** [comment]
Yes it is. Each shell's implementation calls `arrange_and_commit` in the `request_fullscreen` handler. The fullscreen properties are copied into the container state. And when rendering, we use the `current` properties to check if there's a fullscreen view.

Is there a bug somewhere that causes it to not work as intended?

**Comment by emersion** [comment]
Probably, fullscreening mpv on xwayland isn't atomic for me
