### ISSUE TITLE
Crash when opening floating windows

### ISSUE THREAD

**Issue by aereaux** [swaywm/sway#2246]
On latest master, I get a crash when opening floating windows which open directly to floating.  This can be seen with x11-ssh-askpass.

I think it's related to https://github.com/swaywm/sway/commit/15dc5286e280ddd06e845dc57115243e72f2339e , as that's where the crash happens.

[debug.log](https://github.com/swaywm/sway/files/2184903/debug.log)
[backtrace.log](https://github.com/swaywm/sway/files/2184904/paste.log)

**Comment by SirCmpwn** [comment]
cc @RyanDwyer

**Comment by RyanDwyer** [comment]
Fixed by #2248.
