### ISSUE TITLE
sway/config.c:619:4: warning: ‘current_config’ may be used uninitialized in this function [-Wmaybe-uninitialized]

### ISSUE THREAD

**Issue by Hello71** [swaywm/sway#2249]
seems broken to me too, if `config->current_config != NULL` then `current_config` is never assigned to

**Comment by Hello71** [comment]
I don't understand the logic in 23c1c26c3fedf5470dbee9fe97c2374a48588863.

**Comment by Hello71** [comment]
I also don't follow why we abort processing if expand_line fails, but keep trying if anything else goes wrong.

**Comment by emersion** [comment]
The goal is to save the whole file contents in a buffer, `current_config`. But we only do this for the main config file, not for config files included in another config file (that's what the `config->current_config == NULL` check is for, it sets `reading_main_config` to `true`).

Initializing `current_config` to NULL would probably be enough to fix this.
