### ISSUE TITLE
Specifying socket for swaylock does not work

### ISSUE THREAD

**Issue by Marteon** [swaywm/sway#2257]
Hello.
I noticed that `swaylock --socket` does not work.
When calling `swaylock` with the specified socket(e.g. sway at `tty1`) from a terminal emulator within another sway session (e.g. `tty2`) it always starts the lockscreen at `tty2`.
When doing the same from cli in `tty2`  and having a sway session in `tty1` the `swaylock` command hangs forever.
Even executing `swaylock` through `swaymsg -s sway_socket_on_tty1 exec swaylock` does not work.
What is interesting is that event setting `SWAYSOCK` and `I3SOCK` to the correct path does not work.

**Comment by SirCmpwn** [comment]
You need to also set WAYLAND_DISPLAY accordingly for that to work. In any case, the option is deprecated for sway 1.0 so it's not going to be a concern for long.

**Comment by Marteon** [comment]
@SirCmpwn I don't quite understand.
It the `--socket` option deprecated or setting `SWAYSOCK` at all?
Also setting `WAYLAND_DISPLAY` accordingly does not fix the problem.
