### ISSUE TITLE
Proposal: `urgent enable|disable` command

### ISSUE THREAD

**Issue by RyanDwyer** [swaywm/sway#2258]
You would execute it with criteria:

* `[app_id="foo"] urgent enable`
* `[mark="foo"] urgent disable`

An example use case would be a chat program which doesn't support urgency or requesting focus but provides desktop notifications. Your notification daemon could, upon receiving a notification from this chat program, execute `swaymsg [some criteria] urgent enable`.

Another example is having a background script monitoring your GitHub notifications or email inbox for new messages, then when it gets a result it sets an appropriate browser window to urgent. If the notifications/emails are read from another location then the script can run `urgent disable` to clear the urgency.

Another example is configuring your shell to mark the window as urgent when it completes a long running command. If your terminal supports "urgent on bell", you can do this already by echoing a bell character, but using a sway command would work for all terminals. However, this would require the shell to determine its container ID so it can use it in the criteria, and I'm not sure how you'd do that.

Lastly, it would simply be useful to test the urgency implementation.

**Comment by SirCmpwn** [comment]
At first, I thought this would let you ignore urgency from windows matching a criteria, which sounded coolio.

**Comment by RyanDwyer** [comment]
I don't see why we couldn't do that too. I used the terms enable and disable to fit with the fullscreen and floating commands. If you wanted to keep that consistency then we could have `urgent {enable,disable,allow,deny}` where allow and deny controls whether the view can request urgency itself. Or you could not be consistent and have `urgent {on,off,enable,disable}` but I prefer the first option.
