### ISSUE TITLE
Set LD_LIBRARY_PATH at compile time

### ISSUE THREAD

**Issue by cawilliamson** [swaywm/sway#2262]
Hi folks!

I'm really enjoying using the sway 1.0 alphas (which I need since my display is rotated so needed wlroots) o far but have a simple problem which likely has a simple fix.

With the older sway builds the following option did the trick for NixOS (since it uses funky paths)

`-DLD_LIBRARY_PATH=/run/opengl-driver/lib:/run/opengl-driver-32/lib`

I can't find an equivalent option for the newer meson / ninja build - can anyone point me in the right direction?

**Comment by emersion** [comment]
This is a TODO. We probably need an option to disable this security "feature".

**Comment by SirCmpwn** [comment]
We need to provide a meson_option which sets the appropriate LD_LIBRARY_PATH.

**Comment by cawilliamson** [comment]
Oh good - not just me missing something in the docs then! :+1:

**Comment by cawilliamson** [comment]
I bodged together a quick patch to force the correct path for now:

```
--- a/sway/main.c
+++ b/sway/main.c
@@ -280,11 +280,9 @@

        // Security:
        unsetenv("LD_PRELOAD");
-#ifdef _LD_LIBRARY_PATH
-       setenv("LD_LIBRARY_PATH", _LD_LIBRARY_PATH, 1);
-#else
-       unsetenv("LD_LIBRARY_PATH");
-#endif
+
+        // NixOS:
+        setenv("LD_LIBRARY_PATH", "/run/opengl-driver/lib:/run/opengl-driver-32/lib", 1);

        int c;
        while (1) {
```

I'll have a look in to this more thoroughly shortly and see if I can submit a PR with the needed change to support this properly as a meson arg - just wanted a quick 'N dirty workaround for now.
