### ISSUE TITLE
Screen capture in 1.0 alpha / master? (swaygrab)

### ISSUE THREAD

**Issue by DawidLoubser** [swaywm/sway#2263]
Hi Folks,

Been having the greatest time running on sway full-time for work today (Git master), the bugfixes just keep on coming! You guys are doing amazing work.

I need to take some screenshots, and can't find any trace of `swaygrab` - what am I missing? Does this functionality exist since the switch to wlroots?

**Comment by SirCmpwn** [comment]
https://github.com/emersion/grim

**Comment by emersion** [comment]
In the future, please ask this kind of questions on IRC (#sway on Freenode).

**Comment by DawidLoubser** [comment]
Sure thing, apologies for the noise.
