### ISSUE TITLE
Focus randomly gets stuck on one monitor and window

### ISSUE THREAD

**Issue by includereserved** [swaywm/sway#2274]
I don't know how to reproduce this reliably. I use Firefox and Termite on Arch Linux. When this happens I can only move my mouse inside one monitor nor focus on any other window in that workspace. No keybinds register, except for Toggling floating mode/Holding mod and dragging the window around or resizing.

**Comment by includereserved** [comment]
Actually I can focus on other workspace and toggle floating/move them around but my keyboard is still stuck focused on one window.

**Comment by includereserved** [comment]
@RyanDwyer Can you please clarify? wlroots is installed. Do I need to recompile?

**Comment by RyanDwyer** [comment]
You didn't specify a version and I was going to ask you which version you were using, but then I saw this:

> move them around (with mod+mouse)

That feature is not implemented in the 1.0 alpha yet, so I concluded that you were using 0.15 stable.

Please run `sway --version` to confirm.

**Comment by includereserved** [comment]
Yes, I am using 0.15.2. I will switch to the alpha.
