### ISSUE TITLE
Renderer redesign

### ISSUE THREAD

**Issue by emersion** [swaywm/sway#2291]
The renderer as it is now as some limitations and some design issues. We need to overhaul it, and we need to make sure the input code is updated accordingly.

* Iterators: either make them nicer or remove them (I personally like them so I'll try to make them nicer)
* Popups need to be rendered after everything else (think of it as two layers: one layer with views, and another layer on top with popups and unmanaged wayland surfaces). I think this adds a lot of complexity and I'd prefer to render things in the focus order (last rendered = last focused), but iirc there were some issues with this approach.
* Subsurfaces still need to be rendered with their parent surface

cc @RyanDwyer

**Comment by RyanDwyer** [comment]
I would love to see the view rotation code removed. It adds complexity and I don't know of a valid use case for it.
