### ISSUE TITLE
Freeze when reloading config

### ISSUE THREAD

**Issue by jniedrauer** [swaywm/sway#2293]
When reloading sway (meta+shift+c), screen stops updating. I am also unable to switch to a TTY with ctrl+alt+2. From another machine (via ssh), I can pkill -f sway at which point I get kicked back to a TTY.

This began occurring when I added this line to my sway config:
```
output * bg `wallpaper` fill
```
(`wallpaper` is an executable script which returns the path to an image)

I am unable to reproduce this when running sway with the -d switch. This leads me to believe it is a race condition.

Without verbose logging, this is the only output:

```
swaybg: ../swaybg/main.c:215: main: Assertion `state.compositor && state.layer_shell && state.output && state.shm'
 failed.
```

Reproduced on 1.0-alpha.4

**Comment by RedSoxFan** [comment]
This appears to be one of the many issues with `output *`. I am able to replicate this consistently when an `output *` command is given before (or given without) `output <name>` commands. When the `output <name>` commands are first, I cannot replicate at all.

**Comment by jniedrauer** [comment]
> I am able to replicate this consistently when an output * command is given before (or given without) output <name> commands. When the output <name> commands are first, I cannot replicate at all.

Confirmed, this is the behavior I am seeing. Thank you.

**Comment by SirCmpwn** [comment]
Assertions are used for catching programmer error. This is normal, yes.
