### ISSUE TITLE
Using output wildcard undoes multimonitor order

### ISSUE THREAD

**Issue by includereserved** [swaywm/sway#2295]
Not sure if this is expected behavior.

I took a look at https://github.com/swaywm/sway/blob/master/sway/commands/output.c but couldn't rule out why this happens.

**Comment by RedSoxFan** [comment]
Can you post your config?

**Comment by SirCmpwn** [comment]
Ah, so that's what causes it. I've been running into this problem for a while but wasn't sure of the exact cause. The bug is probably somewhere in here:

https://github.com/swaywm/sway/blob/master/sway/config/output.c

**Comment by includereserved** [comment]
Yeah I ran in to it at first when setting the background with the wildcard but eventually just added it to the end of the line for each monitor.
