### ISSUE TITLE
Default focused output

### ISSUE THREAD

**Issue by somdoron** [swaywm/sway#2297]
I'm using sway version 1.0-alpha.3-299-gf516dbfb with two outputs (laptop and external).
The external is my main output with workspace 1 assigned to it.

However when starting sway the laptop output is the focused one (while I want the external one to be focused).
I tried to add to the configuration `focus output DP-1`, but it didn't help.

Primary flag for output might help but I didn't found anything in the docs.

Any ideas?

**Comment by RyanDwyer** [comment]
I don't think it's possible at the moment.

Perhaps after setup we could focus the output closest to 0,0 as this is likely the user's intended primary.

**Comment by SirCmpwn** [comment]
Nah, I think we should just figure out why `focus output DP-1` at the end of the config didn't work (probably because it wasn't deferred).

**Comment by ValenTheRed** [comment]
Hi, this isn't working for me using sway version 1.9, packaged with fedora 40 Sway spin. Tried both of the `focus` and `exec swaymsg` way mentioned in the wiki, none of them work. `focus` does work when I run it through `swaymsg` in foot. 

Any advice?

My `sway/config`

```config
include /etc/sway/config.d/*
include /etc/sway/config

set {
    $laptop  eDP-1
    $monitor HDMI-A-1
}

exec swaymsg focus output $monitor
```
