### ISSUE TITLE
Windows drawn over bar

### ISSUE THREAD

**Issue by emersion** [swaywm/sway#2302]
When I run a new app it first gets drawn over the bar, and is then drawn at the correct position. This causes some damage issues. It shouldn't get drawn over the bar in the first place.

![screenshot](https://user-images.githubusercontent.com/506932/42911326-78bc4c68-8ae2-11e8-97ec-89f78c4e8165.png)

**Comment by emersion** [comment]
Same bug: ![](https://i.imgur.com/IO78iIY.png)

**Comment by RyanDwyer** [comment]
Does that PR fix the second issue too?

**Comment by ianyfan** [comment]
Yes
