### ISSUE TITLE
input ... numlock|capslock off|on

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/sway#2311]
Would be nice to set the initial state for modifiers.

**Comment by progandy** [comment]
I think that needs a new export in wlroots, maybe ```wlr_keyboard_set_modifiers``` to complement ```wlr_keyboard_get_modifiers```.

**Comment by RyanDwyer** [comment]
What do you think of having numlock on by default (ie. if there's nothing in the config to say otherwise)?

**Comment by SirCmpwn** [comment]
I like it

**Comment by RedSoxFan** [comment]
Closed by #2330

**Comment by ggreer** [comment]
The new default behavior is not fun on many laptop keyboards, where the "number pad" reuses U, I, O, J, K, L, and other keys.

Also on most systems, isn't the default numlock value configurable in the BIOS? I don't know of any other window manager that defaults to messing with numlock.
