### ISSUE TITLE
Scrolling often scrolls two steps at once

### ISSUE THREAD

**Issue by minus7** [swaywm/sway#2312]
This is particularly annoying when using Tree Style Tab Bar in Firefox: scrolling on the tab bar sometimes skips a tab then. With a couple hundred tabs it happens in ~50% of cases, with three tabs I couldn't observe the problem.
I also observed the same behavior in xfce4-terminal (a wayland GUI as far as i can tell) by scrolling in the weechat nick list. It doesn't happen often here.
Due to the large amount of tabs slowing down Firefox and making double scroll happen more often, I'd assume it may be processing events twice. I'll give it a try on Weston to compare.

**Comment by SirCmpwn** [comment]
This is an Xwayland bug

https://github.com/swaywm/wlroots/issues/848
