### ISSUE TITLE
Floating z-index is inverted

### ISSUE THREAD

**Issue by emersion** [swaywm/sway#2315]
1. Open two floating windows
2. Focus is messed up

**Comment by RyanDwyer** [comment]
I just opened two xwayland windows in the current master, floated them, moved one so it's partially overlapping the other, then was able to focus between them by clicking each one. I didn't notice any problems.

Can you give a more specific example?

**Comment by emersion** [comment]
Hmm. It's probably related to focus wrapping. For instance open `gnome-dictionary`'s preferences, then click "add" (this opens another floating window). When you move your cursor over the stack it switches focus.

I'd say focus wrapping ignores floating z-index.
