### ISSUE TITLE
Set key repeat rate and key delay

### ISSUE THREAD

**Issue by mb720** [swaywm/sway#2321]
Hi and thanks a lot for Sway!

I've figured out that I can set the key delay rate and the key repeat rate using

    export WLC_REPEAT_RATE=100
    export WLC_REPEAT_DELAY=250

in `.bashrc`. Those environment variables are documented [here](https://github.com/mikkeloscar/wlc#env-variables).

Browsing Sway's source code, I saw that `include/sway/config.h` defines

    int repeat_delay;
    int repeat_rate;

This made me hope to be able to set those values for my keyboard in `~/.config/sway/config` using

    input "1:1:AT_Translated_Set_2_keyboard" {
        repeat_rate 100
        repeat_delay 250
    }

This doesn't have an effect when reloading Sway's configuration, though.

My question is whether it's possible to set the key repeat rate and the key delay other than using wlc's environment variables.

Thanks!

**Comment by RyanDwyer** [comment]
The code you're looking at is the alpha-1.0. You're running sway 0.15, which is in the 0.15 branch.

So for now you'll need to use the environment variables, and when 1.0 is released you'll be able to define it in the config using the example you gave.
