### ISSUE TITLE
status_command in swaybar

### ISSUE THREAD

**Issue by mb720** [swaywm/sway#2322]
Reading `man sway-bar` and Sway's online documentation, I assumed the following in `~/.config/sway/config` would write the current date to the status bar:

    bar {
        status_command date
    }

This doesn't work though: swaybar still shows the workspaces on the left, but there's no text on the right.

When I then switch workspaces, this appears in red on swaybar's right end:

    ERROR: swaybar cannot access the statusline

Is `status_command` to be used differently?

These produced the same results:

    status_command exec date
    status_command /usr/bin/date

I'm using Sway 0.15.2 on Arch Linux 4.17.5

Thanks!

**Comment by RedSoxFan** [comment]
Use the following:
`status_command while date; do sleep 1; done`

The `status_command` is executed only once and should be a stream of output. Using just `date` outputs one line of text and then closes the output stream (thus there is nothing to read from).
