### ISSUE TITLE
Sway crash when connecting another display while swaylock is running

### ISSUE THREAD

**Issue by somdoron** [swaywm/sway#2324]
I'm also not using display manager, so when sway crash it goes back to tty1 with full access.

sway version 1.0-alpha.4-43-g27f65b94 (Jul 21 2018, branch 'master')

Following is the log output

```
2018-07-22 09:23:50 - [backend/drm/drm.c:218] Skipping pageflip on output 'DP-1'
(EE) failed to read Wayland events: Connection reset by peer
2018-07-22 09:23:50 - [common/ipc-client.c:68] Unable to receive IPC response
urxvt: X connection to ':0' broken, unable to recover, exiting.
```

Steps to reproduce:
1. On a laptop disconnect any external outputs
2. Lock the screen with swaylock
3. Connect another output

**Comment by somdoron** [comment]
If I ran without any open apps it is crashes as well, with following error:

```
2018-07-22 09:30:24 - [backend/drm/drm.c:218] Skipping pageflip on output 'DP-1'
(EE) failed to read Wayland events: Broken pipe
2018-07-22 09:30:24 - [common/ipc-client.c:68] Unable to receive IPC response
```

**Comment by somdoron** [comment]
swaylock by the way doesn't report anything

**Comment by emersion** [comment]
We can't really investigate without a stack trace. Please provide a stack trace with debugging symbols enabled.

**Comment by somdoron** [comment]
how do I enable debugging symbols?

**Comment by SirCmpwn** [comment]
>how do I enable debugging symbols?

If you have to ask, you should not be using the alpha releases.

**Comment by somdoron** [comment]
@SirCmpwn I'm an experienced programmer (managing few popular open source projects myself), probably can fix this myself and I want to contribute to sway.
My C experience is on Windows and not linux, so I don't know how to enable debug symbols, if you can point to the right direction that will help.

**Comment by martinetd** [comment]
If you compiled this yourself you already have debug symbols (meson enables them by default); so you're probably asking the wrong question.
You can get the stack traces from a core dump after sway crashed, have a look at coredumpctl

**Comment by somdoron** [comment]
@martinetd thanks.

@SirCmpwn @emersion I edited the issue and attached the stacktrace.

**Comment by SirCmpwn** [comment]
Read the stack trace, figure out the problem, send a patch.

**Comment by somdoron** [comment]
https://github.com/swaywm/sway/issues/2324
