### ISSUE TITLE
Verify sway's IPC matches i3's IPC

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/sway#2334]
I know at least get_tree isn't right.

**Comment by ianyfan** [comment]
(Possibly non-exhaustive) list of properties missing in `get_tree`:

- border
- current_border_width
- deco_rect
- floating
- floating_nodes
- fullscreen_mode
- geometry
- last_split_layout
- orientation
- output
- percent
- scratchpad_state
- stick
- swallows
- window
- window_properties
- window_rect
- workspace_layout

All the other commands seem to match i3.

**Comment by SirCmpwn** [comment]
Anyone interested in finishing this one up?

**Comment by ianyfan** [comment]
I think this might actually be finished, and that the remaining properties are, as discussed in #2530, undocumented and therefore should not be added.

**Comment by SirCmpwn** [comment]
Sweet!
