### ISSUE TITLE
Verify sway commands match i3 commands

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/sway#2336]
Find a list of i3 commands and make sure we have all of them in sway (at least all the ones we want to have). Double check that each sway implementation supports the same arguments as the i3 equivalents.

Criteria:
- [x] class
	- [x] \_\_focused__
- [x] instance
	- [x] \_\_focused__
- [x] window_role
	- [x] \_\_focused__
- [x] window_type
	- [x] normal, dialog, utility, toolbar, splash, menu, dropdown_menu, popup_menu, tooltip, notification
- [x] id
- [x] title
	- [x] \_\_focused__
- [x] urgent
	- [x] latest/newest/last/recent (sway: only latest)
	- [x] oldest/first (sway: only oldest)
- [x] workspace
	- [x] \_\_focused__
- [x] con_mark
- [x] con_id
	- [x] \_\_focused__
- [x] floating
- [x] tiling

Commands:
- [x] exec ~~[--no-startup-id]~~
	- [x] command chaining
	- [x] exec quoting
- [x] split
	- [x] split vertical|horizontal|toggle
	- [x] splith
	- [x] splitv
	- [x] splitt
- [x] layout
	- [x] layout default|tabbed|stacking|splitv|splith (sway: default possible but not documented)
	- [x] layout toggle [split|all] (sway: all is ignored)
	- [x] layout toggle [split|tabbed|stacking|splitv|splith] [split|tabbed|stacking|splitv|splith] (sway: anything except split is ignored)
- [x] focus
	- [x] \<criteria> focus (undocumented)
	- [x] focus left|right|down|up
	- [x] focus parent|child|floating|tiling|mode_toggle
	- [x] focus output left|right|up|down|~~primary~~|\<output> (sway: no primary)
	- [x] focus mode_toggle
- [x] move
	- [x] move <left|right|down|up> [\<px> px] (sway: documentation does not specify px can be included)
	- [x] move [absolute] position <pos_x> [px] <pos_y> [px] (sway: absolute ignored)
	- [x] move [absolute] position center (sway: absolute ignored)
	- [x] move position mouse (sway: allows "absolute")
	- [x] move window|container to mark \<mark>
	- [x] move container|workspace to output left|right|down|up|current|~~primary~~|\<output> (sway: no primary; allows "window")
- [x] swap container with id|con_id|mark \<arg>
- [x] sticky enable|disable|toggle
- [x] workspace
	- [x] workspace next|prev|next_on_output|prev_on_output
	- [x] workspace back_and_forth
	- [x] workspace [--no-auto-back-and-forth] \<name> (sway: no --no-auto-back-and-forth)
	- [x] workspace [--no-auto-back-and-forth] number \<name> (sway: no --no-auto-back-and-forth)
	- [x] move [--no-auto-back-and-forth] [window|container] [to] workspace \<name> (sway: no --no-auto-back-and-forth; "to" has to be included)
	- [x] move [--no-auto-back-and-forth] [window|container] [to] workspace number \<name> (sway: no --no-auto-back-and-forth; "to" has to be included; undocumented)
	- [x] move [window|container] [to] workspace prev|next|current (sway: current undocumented)
        - [x] move container to workspace back_and_forth
	- [x] Also can be identified with both: "number \<number>: \<name>"
	- [x] rename workspace [\<old_name>] to <new_name>
- [x] resize
	- [x] resize grow|shrink <direction> [\<px> px [or \<ppt> ppt]]
	- [x] resize set \<width> [px|ppt] \<height> [px|ppt] (sway: no ppt) (#1737)
- [x] mark
	- [x] mark [--add|--replace] [--toggle] \<identifier>
	- [x] unmark \<identifier>
- [x] title_format \<format>
	- [x] Pango placeholders: %title, %class, %instance
- [x] border
	- [x] border normal|pixel [\<n>]
	- [x] border none|toggle
- [x] ~~shmlog~~
	- [x] ~~shmlog <size_in_bytes>~~
	- [x] ~~shmlog on|off|toggle~~
- [x] debuglog on|off|toggle
- [x] ~~restart~~
- [x] reload
- [x] exit
- [x] scratchpad
	- [x] move scratchpad (sway: also allows "to")
	- [x] scratchpad show
- [x] nop [\<comment>]
- [x] bar
	- [x] ~~bar hidden_state hide|show|toggle [\<bar_id>]~~
	- [x] ~~bar mode dock|hide|invisible|toggle [\<bar_id>]~~
- [x] mode <name>
- [x] floating enable|disable|toggle
- [x] fullscreen
- [x] kill

Configuration:
- [x] comments
- [x] font (sway: can be command)
- [x] Bindings
	- [x] Keyboard: bindsym|bindcode [--release] [\<Group>+][\<Modifiers>+]<keysym|keycode> command 
	- [x] Mouse: bindsym [--release] [--border] [--whole-window] [--exclude-titlebar] [\<Modifiers>+]button\<n> command
- [x] mode [--pango_markup] \<name>
- [x] floating_modifier \<Modifier> (sway: also includes normal|inverse)
- [x] floating_m<in|ax>imum_size \<width> x \<height>
- [x] default_orientation horizontal|vertical|auto (default follows on monitor size)
- [x] workspace_layout default|stacking|tabbed (sway: can be command; allows auto)
- [x] Default border (default: normal)
	- [x] default_[floating_]border normal|none|pixel
	- [x] default_[floating_]border normal|pixel \<px>
- [x] hide_edge_borders none|vertical|horizontal|both|smart (default: none)
- [x] for_window \<criteria> \<command>
- [x] no_focus \<criteria>
- [x] set $\<name> \<value> (sway: can be command, despite documentation; if \<name> is given without $, the $ is silently added instead of error)
- [x] ~~set_from_resource $\<name> <resource_name> \<fallback>~~
- [x] Assign (sway: can be command)
	- [x] assign \<criteria> [→] [workspace] [number] \<workspace> (sway: no number)
	- [x] assign \<criteria> [→] output left|right|up|down|primary|\<output> (sway: undocumented)
- [x] exec[_always] ~~[--no-startup-id]~~ \<command>
- [x] workspace \<workspace> output \<output> (sway: can be command)
- [x] Colors:
	- [x] \<colorclass> \<border> \<background> \<text> \<indicator> <child_border>
	- [x] colorclass: client.focused client.focused_inactive client.unfocused client.urgent client.placeholder client.background
- [x] ~~ipc-socket \<path> (default: /tmp/i3-%u.XXXXXX/ipc-socket.%p)~~
- [x] focus_follows_mouse yes|no (default: yes) (sway: does not document that the default is yes)
- [x] mouse_warping output|none (default: output)
- [x] popup_during_fullscreen smart|ignore|leave_fullscreen (default: smart)
- [x] focus_wrapping yes|no|force (default: yes)
- [x] force_focus_wrapping yes|no (deprecated)
- [x] ~~force_xinerama yes|no (default: no)~~
- [x] workspace_auto_back_and_forth yes|no (default: no) (sway: can be command)
- [x] force_display_urgency_hint \<timeout> ms (default: 500)
- [x] focus_on_window_activation smart|urgent|focus|none (default: smart)
- [x] show_marks yes|no (default: yes) (marks starting with _ will never be drawn) (sway: can be command)
- [x] line continuation \
- [x] bar
	- [x] i3bar_command \<command> (passed to "sh -c") (default: i3bar) (sway: uses swaybar instead of i3bar)
	- [x] status_command \<command> (passed to "sh -c")
	- [x] mode dock|hide|invisibile (default: dock)
	- [x] hidden_state hide|show (default: hide)
	- [x] modifier \<Modifier>|none (default: Mod4)
	- [x] bindsym [--release] button\<n> \<command>
	- [x] id <bar_id> (default: bar-x) (sway: default is not documented)
	- [x] position top|bottom
	- [x] output ~~primary~~|\<output>
	- [x] ~~tray_output none|~~primary~~|\<output>~~
	- [x] tray_padding \<px> [px] (default: 2)
	- [x] font \<font>
	- [x] separator_symbol \<symbol> (default: vertical)
	- [x] workspace_buttons yes|no (default: yes)
	- [x] strip_workspace_buttons yes|no (default: no)
	- [x] binding_mode_indicator yes|no (default: yes)
	- [x] Colors:
		- [x] background, statusline, separator, focused_background (fallback: background), focused_statusline (fallback: statusline), focused_separator (fallback: separator), focused_workspace, active_workspace, inactive_workspace, urgent_workspace, binding_mode (fallback: urgent_workspace)

Sway-exclusive:
- ~~clipboard \<content>~~
- layout auto <next|prev>
- layout auto [master|ncol] [inc|set] \<n>
- move <next|prev|first>
- floating_scroll
- gaps (TODO: check against i3-gaps)
- output
- ~~seamless_mouse~~
- include
- swaybg_command
- swaybar_command
- input
- seat
- opacity
- urgent enable|disable|allow|deny

**Comment by progandy** [comment]
There are at least some commands that don't support the same boolean representations, for example focus_wrapping. sway only allows yes, no and force. i3 allows anything. 
```force``` is matched the same,
```yes``` can be anything that [eval_boolstr](https://github.com/i3/i3/blob/7411dfa5efc0c6035e7c644cd9c64166f516e81a/src/config_directives.c#L51) recognizes (```1```, ```yes```, ```on```, ```true```, ```enable```, ```active```)
```no``` is everything else

https://github.com/i3/i3/blob/master/include/commands.h

**Comment by SirCmpwn** [comment]
We should probably use something similar to eval_boolstr ourselves.

**Comment by ianyfan** [comment]
Made a start. Most seems to be there, mainly issues of documentation.

Criteria:
- [x] class
	- [x] \_\_focused__
- [x] instance
	- [x] \_\_focused__
- [x] window_role
	- [x] \_\_focused__
- [x] window_type
	- [x] normal, dialog, utility, toolbar, splash, menu, dropdown_menu, popup_menu, tooltip, notification
- [x] id
- [x] title
	- [x] \_\_focused__
- [x] urgent
	- [ ] latest/newest/last/recent (sway: only latest)
	- [ ] oldest/first (sway: only oldest)
- [x] workspace
	- [x] \_\_focused__
- [x] con_mark
- [x] con_id
	- [ ] \_\_focused__
- [x] floating
- [x] tiling

Commands:
- [ ] exec [--no-startup-id] (sway: no --no-startup-id, though is this X-only?)
	- [x] command chaining
	- [x] exec quoting
- [x] split
	- [x] split vertical|horizontal|toggle
	- [x] splith
	- [x] splitv
	- [x] splitt
- [ ] layout
	- [ ] layout default|tabbed|stacking|splitv|splith (sway: default possible but not documented)
	- [ ] layout toggle [split|all] (sway: all is ignored)
	- [ ] layout toggle [split|tabbed|stacking|splitv|splith] [split|tabbed|stacking|splitv|splith] (sway: anything except split is ignored)
- [ ] focus
	- [ ] <criteria> focus (undocumented)
	- [x] focus left|right|down|up
	- [x] focus parent|child|floating|tiling|mode_toggle
	- [ ] focus output left|right|up|down|primary|<output> (sway: no primary)
	- [x] focus mode_toggle
- [ ] move
	- [ ] move <left|right|down|up> [\<px> px] (sway: documentation does not specify px can be included)
	- [ ] move [absolute] position <pos_x> [px] <pos_y> [px] (sway: undocumneted; does not allow px)
	- [ ] move [absolute] position center
	- [x] move position mouse (sway: allows "absolute")
	- [ ] move window|container to mark <mark>
	- [ ] move container|workspace to output left|right|down|up|current|primary|<output> (sway: no primary; allows "window")
- [x] swap container with id|con_id|mark <arg>
- [x] sticky enable|disable|toggle
- [ ] workspace
	- [x] workspace next|prev|next_on_output|prev_on_output
	- [x] workspace back_and_forth
	- [ ] workspace [--no-auto-back-and-forth] <name> (sway: no --no-auto-back-and-forth)
	- [ ] workspace [--no-auto-back-and-forth] number <name> (sway: no --no-auto-back-and-forth)
	- [ ] move [--no-auto-back-and-forth] [window|container] [to] workspace <name> (sway: no --no-auto-back-and-forth; "to" has to be included)
	- [ ] move [--no-auto-back-and-forth] [window|container] [to] workspace number <name> (sway: no --no-auto-back-and-forth; "to" has to be included; undocumented)
	- [ ] move [window|container] [to] workspace prev|next|current (sway: current undocumented)
	- [ ] Also can be identified with both: "number <number>: <name>"
	- [x] rename workspace [\<old_name>] to <new_name>
- [ ] resize
	- [x] resize grow|shrink <direction> [\<px> px [or <ppt> ppt]]
	- [ ] resize set <width> [px|ppt] <height> [px|ppt] (sway: no ppt)
- [ ] mark
	- [x] mark [--add|--replace] [--toggle] <identifier>
	- [x] unmark <identifier>
- [x] title_format <format>
	- [x] Pango placeholders: %title, %class, %instance
- [x] border
	- [x] border normal|pixel [\<n>]
	- [x] border none|toggle
- [ ] shmlog
	- [ ] shmlog <size_in_bytes>
	- [ ] shmlog on|off|toggle
- [x] debuglog on|off|toggle
- [ ] restart
- [x] reload
- [x] exit
- [x] scratchpad
	- [x] move scratchpad (sway: also allows "to")
	- [x] scratchpad show
- [ ] nop [\<comment>]
- [ ] bar
	- [ ] bar hidden_state hide|show|toggle [\<bar_id>]
	- [ ] bar mode dock|hide|invisible|toggle [\<bar_id>]
- [x] mode <name>
- [x] floating enable|disable|toggle
- [x] fullscreen
- [x] kill

Configuration:
- [x] comments
- [ ] font (sway: can be command)
- [ ] Bindings
	- [ ] Keyboard: bindsym|bindcode [--release] [\<Group>+][\<Modifiers>+]<keysym|keycode> command (sway: --released undocumented)
	- [ ] Mouse: bindsym [--release] [--border] [--whole-window] [--exclude-titlebar] [\<Modifiers>+]button<n> command
- [x] mode [--pango_markup] <name>
- [x] floating_modifier <Modifier> (sway: also includes normal|inverse)
- [x] floating_m<in|ax>imum_size <width> x <height>
- [x] default_orientation horizontal|vertical|auto (default follows on monitor size)
- [ ] workspace_layout default|stacking|tabbed (sway: can be command; allows auto)
- [x] Default border (default: normal)
	- [x] default_[floating_]border normal|none|pixel
	- [x] default_[floating_]border normal|pixel <px>
- [x] hide_edge_borders none|vertical|horizontal|both|smart (default: none)
- [x] for_window <criteria> <command>
- [x] no_focus <criteria>
- [ ] set $<name> <value> (sway: can be command, despite documentation; if <name> is given without $, the $ is silently added instead of error)
- [ ] set_from_resource $<name> <resource_name> <fallback>
- [ ] Assign (sway: can be command)
	- [ ] assign <criteria> [→] [workspace] [number] <workspace> (sway: no number)
	- [ ] assign <criteria> [→] output left|right|up|down|primary|<output> (sway: undocumented)
- [ ] exec[_always] [--no-startup-id] <command> (sway: no --no-startup-id, though is this X-only?)
- [ ] workspace <workspace> output <output> (sway: can be command)
- [x] Colors:
	- [x] <colorclass> <border> <background> <text> <indicator> <child_border>
	- [x] colorclass: client.focused client.focused_inactive client.unfocused client.urgent client.placeholder client.background
- [ ] ipc-socket <path> (default: /tmp/i3-%u.XXXXXX/ipc-socket.%p)
- [x] focus_follows_mouse yes|no (default: yes) (sway: does not document that the default is yes)
- [x] mouse_warping output|none (default: output)
- [ ] popup_during_fullscreen smart|ignore|leave_fullscreen (default: smart)
- [ ] focus_wrapping yes|no|force (default: yes) (undocumented)
- [x] force_focus_wrapping yes|no (deprecated)
- [ ] force_xinerama yes|no (default: no)
- [ ] workspace_auto_back_and_forth yes|no (default: no) (sway: can be command)
- [ ] force_display_urgency_hint <timeout> ms (default: 500)
- [ ] force_on_window_activation smart|urgent|focus|none (default: smart)
- [ ] show_marks yes|no (default: yes) (marks starting with _ will never be drawn) (sway: can be command)
- [x] line continuation \
- [x] bar
	- [x] i3bar_command <command> (passed to "sh -c") (default: i3bar) (sway: uses swaybar instead of i3bar)
	- [x] status_command <command> (passed to "sh -c")
	- [ ] mode dock|hide|invisibile (default: dock)
	- [ ] hidden_state hide|show (default: hide)
	- [ ] modifier <Modifier>|none (default: Mod4)
	- [ ] bindsym [--release] button<n> <command>
	- [x] id <bar_id> (default: bar-x) (sway: default is not documented)
	- [x] position top|bottom
	- [ ] output primary|<output> (sway: no primary)
	- [ ] tray_output none|primary|<output> (sway: no primary)
	- [x] tray_padding <px> [px] (default: 2)
	- [x] font <font>
	- [x] separator_symbol <symbol> (default: vertical)
	- [x] workspace_buttons yes|no (default: yes)
	- [x] strip_workspace_buttons yes|no (default: no)
	- [x] binding_mode_indicator yes|no (default: yes)
	- [x] Colors:
		- [x] background, statusline, separator, focused_background (fallback: background), focused_statusline (fallback: statusline), focused_separator (fallback: separator), focused_workspace, active_workspace, inactive_workspace, urgent_workspace, binding_mode (fallback: urgent_workspace)

Sway-exclusive:
- clipboard <content>
- layout auto <next|prev>
- layout auto [master|ncol] [inc|set] <n>
- move <next|prev|first>
- floating_scroll
- gaps (TODO: check against i3-gaps)
- output
- seamless_mouse
- include
- swaybg_command
- input
- seat
- opacity
- urgent enable|disable|allow|deny

**Comment by SirCmpwn** [comment]
Thanks for putting that list together, much appreciated! I went through and crossed out some things that don't make sense for sway to implement.

>- [ ] font (sway: can be command)
>- [ ] workspace_layout default|stacking|tabbed (sway: can be command; allows auto)
>- [ ] set $<name> <value> (sway: can be command, despite documentation; if <name> is given without $, the $ is silently added instead of error)
>- [ ] workspace <workspace> output <output> (sway: can be command)
>- [ ] workspace_auto_back_and_forth yes|no (default: no) (sway: can be command)
>- [ ] show_marks yes|no (default: yes) (marks starting with _ will never be drawn) (sway: can be command)

Can you elaborate on these? Are these just differences with i3 rather than things sway is missing (save for better `set` docs)?

>- clipboard <content>
>- seamless_mouse

These aren't present on master, was this list prepared against 0.15?

**Comment by ianyfan** [comment]
> was this list prepared against 0.15?

I accidentally started on the 0.15 docs and when I switched to the 1.0 docs I forgot to check ones that were removed.

The ones that I put "can be command" means that in i3, they're only supposed to be used in the config file but in sway they can also be executed at runtime. I don't know if you want to change it. Otherwise, it works as well as in i3.
(I was going to put a note about that in the original comment but forgot)

I also noticed a few markdown escapes I missed, I'll fix that.

**Comment by SirCmpwn** [comment]
Gotcha, thanks

**Comment by ianyfan** [comment]
Actually, if primary outputs aren't being supported you can mark them off.

**Comment by martinsb** [comment]
I noticed that "tiling" and "floating" criteria do not work.
Ex. `for_window [tiling] border none` yields error that `Token 'tiling' is not recognized`. The same happens if using `floating` criterion.

**Comment by SirCmpwn** [comment]
Thanks @martinsb, @RyanDwyer fixed that in #2755.

**Comment by SirCmpwn** [comment]
All done! Special thanks to @ianyfan for their hard work on shoring this up.

**Comment by ndrewtl** [comment]
Hooray! Thank you so much @SirCmpwn and all contributors for making this happen. This project is so exciting, as is `wl-roots`. Huge shoutout to everyone volunteering hours of their lives to make this work, and many thanks!

**Comment by orestisf1993** [comment]
New stuff in i3 4.16:

- `strip_workspace_name yes|no` - https://i3wm.org/docs/userguide.html#_strip_workspace_numbers_name
- `title_align left|center|right` - https://i3wm.org/docs/userguide.html#_window_title_alignment
- i3-msg: add support for the SUBSCRIBE message type - https://github.com/i3/i3/pull/3435
- `border toggle` now accepts an optional pixel argument - https://i3wm.org/docs/userguide.html#_changing_border_style
- `resize set` now accepts the `width` and `height` keywords - https://i3wm.org/docs/userguide.html#resizingconfig
- allow multiple assignments of workspaces to output - https://i3wm.org/docs/userguide.html#workspace_screen

**Comment by SirCmpwn** [comment]
Can you open a new ticket for those things?

**Comment by orestisf1993** [comment]
A new ticket for each or a single for all?

**Comment by SirCmpwn** [comment]
Up to you.

**Comment by Arnaudv6** [comment]
disclaimer: never used i3 and really new to this all.  
And I know this is hackish/defeating.  
But those lines in config should work isn't it?
`for_window [class="[.]*"] floating enable, focus;`
I also tried this one:
`for_window [id="[.]*"] floating enable, focus;`
yet I get `Token 'class' is not recognized`
respectively `Token 'id' is not recognized`

**Comment by Arnaudv6** [comment]
Should I open a new bug?

**Comment by ddevault** [comment]
Yes. And send a patch

**Comment by Arnaudv6** [comment]
#3653
@ddevault: I would take years to send a patch there really sorry, just hope this gets tackled before.

**Comment by ddevault** [comment]
That's total horseshit.

**Comment by paualberto** [comment]
What about `set_from_resource`? It's strikethrough'd in the issue, but not sure if it's implemented, this breaks compatibility with i3 configs

**Comment by RedSoxFan** [comment]
> What about `set_from_resource`?

`set_from_resource` loads a value from the X resource database. Sway does not use the X resource database and there is not a Wayland equivalent.

**Comment by paualberto** [comment]
> `set_from_resource` loads a value from the X resource database. Sway does not use the X resource database and there is not a Wayland equivalent.

You're right, appearently this is what the i3 guide says.
I was using `set_from_resource $user echo "$USER"` which actually work for getting your username into i3 config to write multi-user configs. It also works for reading any other env variable.
Is there another way to read env variables in sway config?

**Comment by RedSoxFan** [comment]
> I was using `set_from_resource $user echo "$USER"` which actually work for getting your username into i3 config to write multi-user configs. It also works for reading any other env variable.

You can just replace it with `set $user $USER` (or better yet, just replace all instances of `$user` with `$USER`). See https://www.reddit.com/r/i3wm/comments/4zq30r/is_there_a_way_to_use_bash_environmental/d6y50tt/

> Is there another way to read env variables in sway config?

No, there is no way to read an environment variable's value into a sway variable

**Comment by emersion** [comment]
You can use command substitution in `include` directives, e.g. ``include `hostname`.conf``.

**Comment by Patricol** [comment]
Couldn't find a more relevant issue for this:

`set $<name> <value>` doesn't work inside `mode <name> {}` blocks, which doesn't match i3's behavior.

Is that a bug, an intentional divergence, or an oversight?

Also, @RedSoxFan,  i3's `set_from_resource $<name> <resource_name> <fallback>` does allow for the inclusion of a fallback. If drop-in compatibility with i3 configurations is desired, sway could just interpret `set_from_resource` commands including `<fallback>` args as `set $<name> <value (fallback)>`.

In interpreting my 450 line i3 config file, those are the only two stumbles sway had.

**Comment by RedSoxFan** [comment]
> `set $<name> <value>` doesn't work inside `mode <name> {}` blocks, which doesn't match i3's behavior.
> Is that a bug, an intentional divergence, or an oversight?

I think this is an oversight since they don't really have any relation to modes since they are not scoped. I'll submit a PR to allow it (it's only a one line change anyway)

> sway could just interpret `set_from_resource` commands including `<fallback>` args as `set $<name> <value (fallback)>`

I have no problem submitting a PR to add this for i3 compatibility and just documenting that the fallback is always used and the command only exists for compatibility with i3 configs. @ddevault @emersion any objections?

**Comment by ddevault** [comment]
I'd rather not implement `set_from_resource`, no.

**Comment by jpie726** [comment]
Why is `ipc-socket` struck-through? I don't use it, but sway seems to break compatibility with this.
