### ISSUE TITLE
Proposal: Tree code restructure

### ISSUE THREAD

**Issue by RyanDwyer** [swaywm/sway#2343]
I'm making this issue to discuss some ideas for the sway codebase. I admit the ideas I'm proposing here are somewhat ambitious. I expect this would be something we'd look at after 1.0 is released, maybe even as a sway 2.0 kind of thing, if we did it at all.

My proposal aims to improve the tree-related code, more specifically in the area of containers:

* The term container refers to both any node in the tree, as well as a node of type `C_CONTAINER`.
* There is no type-specific struct for `C_CONTAINER`s. Instead, we shove everything into `sway_container` and the other types ignore the properties which don't apply to them.
* Disabled outputs don't have a swayc, unmapped views don't have a swayc, but sway_workspaces always do. There is inconsistency here, and there's no real reason for the swayc to be optional.
* `container.c` and `layout.c` are collectively over 2000 lines of code, and it's not clear what should go in which file.
* There's little strategy or consistency to where files are placed - the tree directory contains a `layout.c` and `arrange.c`, and we have two `output.c` files in different folders, with header files that don't match.
* Containers try to be generic, but then end up having to do type-specific logic.

That last point is a big one. Containers *must* be generic for the focus stack and transactions, but in many places the container-first approach doesn't seem to be providing much of a benefit. It has issues like lack of typehinting and having to assert the type of container passed to functions. In most cases we already know what type of container we're dealing with when we call a generic container function, and the generic container functions tend to check the container type and have different code paths anyway, hence why I think the container-first approach isn't working well.

On a related note, `C_CONTAINER`s and `C_VIEW`s are actually very similar. In i3 they are the same type. In sway they are separate, which has lead to things like views being able to be fullscreened/floated/marked but not containers. Considering all this functionality should apply to containers as well, there is little reason to keep these types separated.

I think we should consider combining `C_CONTAINER`s and `C_VIEW`s into one type, and consider having a more conventional approach where outputs, workspaces and containers are our primary data types. Each of these could have a node struct which is basically a generic handle. We would prefer type-specific functions and structs rather than generic ones. I think the only places where the node struct would be used is in the focus stack and transactions.

Here's an example of what I mean:

    struct sway_node {
        enum node_type type; // root, output, workspace or con
        union {
            struct sway_root *root;
            struct sway_output *output;
            struct sway_workspace *workspace;
            struct sway_con *con;
        };
        // Nothing else in this struct
    };

    struct sway_root {
        struct sway_node node;
        list_t *outputs;          // struct sway_output
        list_t *saved_workspaces; // struct sway_workspace, for when there are no outputs connected
        list_t *scratchpad;       // struct sway_con
        ...
    };

    struct sway_output {
        struct sway_node node;
        list_t *workspaces;       // struct sway_workspace
        char *name;
        ...
    };

    struct sway_workspace {
        struct sway_node node;
        struct sway_output *output;
        list_t *tiling;             // struct sway_con
        list_t *floating;           // struct sway_con
        char *name;
        ...
    };

    struct sway_con {
        struct sway_node node;
        struct sway_workspace *workspace; // Always set for all containers
        struct sway_con *parent;          // NULL if in the root of the workspace
        list_t *children;                 // struct sway_con

        struct sway_view *view;           // NULL for actual containers
        char *title;
        ...
    };

    struct sway_view {
        struct sway_con *con;
        ...
    };

Some benefits of this structure are:

* No double meaning of the word container.
* More conventional approach makes it easier to work with.
* Because the node struct is not a pointer and is embedded within each struct, we wouldn't have to manually create or track these like we currently do for `output->swayc` and `view->swayc`.
* We wouldn't have piles of generic code in `container.c` and `layout.c`.
* Typehinting/no container-type assertions.
* We could use the more appropriate `title` property for containers/views rather than reusing the `name` property.
* We could easily find a container's workspace or output by using `con->workspace` and `con->workspace->output`.
* Functions in general would be easier to read as they wouldn't contain as much branching logic.
* Possibly less lines of code overall, due to less branching and type assertions.

Some downsides of this structure are:

* We may have similar functions like `root_for_each_container`, `output_for_each_container`, `workspace_for_each_container` and `container_for_each_container`, where each function calls the next one in the chain. This means there's potential for there to be more lines of code overall, but these functions would be simple and easy to understand.
* Changing stuff introduces risk of breakage.

I don't consider the number of lines of code to be an important measurement, but I think it'd turn out to be around the same anyway.

---

I also think we should consider restructuring the filenames so there's a `types` directory similar to wlroots. This directory would contain most code, but for the more involved stuff like rendering, `container_at` and `container_get_in_direction` we could separate those into a different directory... maybe called `tasks`?

So the `sway/desktop`, `sway/input` and `sway/tree` directories could be replaced with something like:

    sway/types/container.c
    sway/types/criteria.c
    sway/types/input/cursor.c
    sway/types/input/input-manager.c
    sway/types/input/keyboard.c
    sway/types/input/seat.c
    sway/types/node.c
    sway/types/output.c
    sway/types/root.c
    sway/types/server.c
    sway/types/shells/layer_shell.c
    sway/types/shells/xdg_shell.c
    sway/types/shells/xdg_shell_v6.c
    sway/types/shells/xwayland.c
    sway/types/transaction.c
    sway/types/view.c
    sway/types/workspace.c

    sway/tasks/arrange.c
    sway/tasks/container_at.c
    sway/tasks/get_in_direction.c
    sway/tasks/render.c

---

I'm keen to get everyone's thoughts on this. Is this worth doing? Is there anything that would make this impractical?

**Comment by SirCmpwn** [comment]
I like your data structures but not the proposed rehoming of files.

**Comment by RyanDwyer** [comment]
I've made a start on this and I'm convinced this is what's best for the project. But before I get too deep I want to check that the development strategy I'm using is one that will be acceptable.

Ideally I would break it down into smallish commits that can each be compiled and are easy to review, but to do it that way would require a transition state where both nodes and sway_containers can represent a generic tree item. This would be very complicated.

The method I want to use is to change everything in one commit so I don't have to worry about a transition state. There would be one commit with thousands of lines changed. Almost everything in the tree directory would be undiffable. Because of this, it would have to undergo a significant amount of testing before merging.

Is that acceptable?

**Comment by SirCmpwn** [comment]
Make it as small as practically possible, and ideally do it when there aren't many open PRs which will have to rebase. Then I'm okay with it.
