### ISSUE TITLE
floating_modifier behavior does not match man page

### ISSUE THREAD

**Issue by Rikorose** [swaywm/sway#2347]
#2296 implements the [i3 behavior](https://i3wm.org/docs/userguide.html#floating_modifier).
The [man page](https://github.com/swaywm/sway/blob/a211daf/sway/sway.5.scd#L324) describes one additional argument (normal/inverse).

I see two options:
1. Update man page to match i3
2. Change the floating_modifier command such that it accepts one additional optional argument (normal/inverse)

**Comment by SirCmpwn** [comment]
https://github.com/swaywm/sway/issues/2335
