### ISSUE TITLE
Opacity and extending the focus classes with more options

### ISSUE THREAD

**Issue by RyanDwyer** [swaywm/sway#2362]
Currently we have an `opacity` command which sets the opacity of the current view. This could be useful for things like tracing an image by giving your tracing program transparency. But I think a much more common and useful scenario would be having the opacity follow the focus around. If we're going to change this then we'll probably end up breaking the `opacity` command, so we should do it before 1.0 is released.

Thinking forward, I can see us implementing a shadow command too. Then you could have the focused view have a shadow, and the others with a lighter or no shadow. Maybe also changing the shadow in response to the view becoming urgent.

If we were to do this then we could extend the focus class commands (eg. `client.focused`) with more values, but that'd get cumbersome when shadows are added to it, because shadows would have several properties.

We could make the existing format deprecated and introduce a new configuration block like this:

    client.unfocused {
        border       #333333
        background   #222222
        text         #888888
        indicator    #292d2e
        child_border #222222
        opacity      0.8
        shadow       ...
    }

Thoughts?

**Comment by SirCmpwn** [comment]
I'm a bit conflicted. I think that if you want to have opacity follow the focused window around, a small daemon listening on IPC could do it. But if we set aside my reservations in that respect...

```
client.unfocused {
    border       #333333
    background   #222222
    text         #888888
    indicator    #292d2e
    child_border #222222
    opacity      0.8
    shadow       ...
}
```

I like this but I think we should pitch it to i3 first. I also don't think this necessarily has to break the opacity command.

**Comment by progandy** [comment]
Breaking opacity for select views doesn't sound good to me. If unfocused windows are set to partially transparent, I'd like to make specific windows opaque, for example the pdf viewer while editing a latex document.

**Comment by RyanDwyer** [comment]
Ah, yep. Another use case would be having an unfocused mpv window being opaque.

I think this is best left to an IPC script.
