### ISSUE TITLE
Regression: last member of a workspace doesn't get focus when closing siblings

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/sway#2363]
```
(workspace split-v
  (view A)
  (container split-h
    (view B)
    (view C focus)))
```

If you close views C and B, you'd expect A to receive focus, but it does not.

**Comment by RyanDwyer** [comment]
I can't replicate it in master using your example.

This might be fixed in the floating containers PR. Can you test it there?

**Comment by SirCmpwn** [comment]
ACK, fixed there.

**Comment by RyanDwyer** [comment]
@SirCmpwn Can this be closed now?

**Comment by SirCmpwn** [comment]
Yep
