### ISSUE TITLE
Turning monitor off and on loses open windows

### ISSUE THREAD

**Issue by seropp** [swaywm/sway#2374]
Turning monitor first off and then on, loses open windows. I don't know how to get them back.

**Comment by SirCmpwn** [comment]
https://github.com/SirCmpwn/sway/wiki#how-do-i-report-issues

**Comment by seropp** [comment]
Thanks, here it is:

sway version 1.0-alpha.4-43-g27f65b94 (Jul 21 2018, branch 'master')

Linux computer 4.17.8-1-ARCH #1 SMP PREEMPT Wed Jul 18 09:56:24 UTC 2018 x86_64 GNU/Linux

Started sway, super+enter (twice) to get 2 termite terminals up and running, turned off monitor, turned on, exited sway. My config just changes urxvt to termite.

https://gist.github.com/seropp/a3e5cfadb43dee609be0362878e3e121

**Comment by SirCmpwn** [comment]
We don't accept issues for the alpha releases unless you're willing to write a patch. Are you willing to write a patch?

**Comment by seropp** [comment]
It seems very strange to me that issues are not accepted for alpha, especially since I provided a clear description and it's 100% reproducible on my end, but I actually thought I was helping.

**Comment by SirCmpwn** [comment]
It would seem a lot less strange if you had read the [release notes](https://github.com/swaywm/sway/releases/tag/1.0-alpha.4):

>**Please do not submit bug reports for this version of sway.** Submit patches instead.
