### ISSUE TITLE
Pointer constraints & relative pointer

### ISSUE THREAD

**Issue by ddevault** [swaywm/sway#2382]
Depends on https://github.com/swaywm/wlroots/pull/852

**Comment by emersion** [comment]
Relative pointer is still WIP. Pointer constraints need sway support (they are only in wlroots).

**Comment by Laaas** [comment]
Seems relevant: https://github.com/swaywm/sway/pull/3516

**Comment by rkanati** [comment]
Yeah, this is working correctly for me on master. Should probably close.
