### ISSUE TITLE
Add and remove cursor on the fly as input devices are added/removed

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/sway#2398]
Follow-up to https://github.com/swaywm/sway/pull/2397

**Comment by chr0me-sh** [comment]
I'm not sure how this applies to USB inputs being inserted or removed, but at the moment if I remove my pointer kernel module the cursor does leave, and reappear when I insert the module again.

**Comment by emersion** [comment]
>the cursor does leave

Try without opening an app. I suspect this is a client hiding the cursor when the seat looses the pointer capability. We don't have code to do so in sway.

**Comment by chr0me-sh** [comment]
> Try without opening an app

Yep, I believe the effect came from the mouse auto hiding when I started typing.

**Comment by emersion** [comment]
I guess so.
