### ISSUE TITLE
Support for DRI_PRIME flag with Nouveau

### ISSUE THREAD

**Issue by JonnyMako** [swaywm/sway#2399]
Is there a way to get Sway working with hybrid graphics laptop with multiple monitors connected to both the Intel (built-in and VGA) and Nvidia (2 DisplayPorts) all at the same time?

Currently I'm using Nouveau and swaymsg -t get_outputs only sees:
Output DP-1
  Geometry: 2560x1440 @ 0,0
  Scale factor: 1x
  Workspace: 1

Output DP-3
  Geometry: 1920x1200 @ 2560,0
  Scale factor: 1x
  Workspace: 11

It does not see the monitor connected to VGA and it does not see the built-in laptop display. Is DRI_PRIME flag supported on Sway? I'm trying out the latest git version of Sway.

thanks!

**Comment by SirCmpwn** [comment]
https://github.com/swaywm/wlroots/issues/934
