### ISSUE TITLE
Sticky windows disappears

### ISSUE THREAD

**Issue by Alexays** [swaywm/sway#2416]
**Version:**
sway version 1.0-alpha.4-259-gb49904dd (Aug  3 2018, branch 'master')

Can't extract usefull informations from debug log

Sticky windows disappears after switching some workspaces if these don't get focus
**How to reproduce**
- Create a sticky window
- Create tiling window on same workspace
- Switch several times between another workspace and the current

After some switch, sticky windows that have not received focus will disappear

**Comment by emersion** [comment]
https://github.com/swaywm/sway/wiki#how-do-i-report-issues

**Comment by Alexays** [comment]
My fault I added the version

**Comment by Alexays** [comment]
I think there is not only a focus problem because if I move to a new workspace sticky windows aren't there
