### ISSUE TITLE
"Reload sway" via swaynag should dismiss swaynag if errors were fixed

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/sway#2427]

**Comment by RedSoxFan** [comment]
The code is in place to do so and It is working fine for me.

Do you get two swaynag instances if you reload with errors still in the config?

**Comment by SirCmpwn** [comment]
No, that works. I didn't toggle details to see what the real error was. New problem: having errors in your config and starting sway doesn't show swaynag.

**Comment by RedSoxFan** [comment]
> No, that works.

Weird. It kills swaynag before reading anything from the config.

> New problem: having errors in your config and starting sway doesn't show swaynag.

Is `swaynag` in your path or are you setting `swaynag_command`?

**Comment by SirCmpwn** [comment]
>Weird. It kills swaynag before reading anything from the config.

I mean, it works as expected. It's dismissed when I reload and if there are still errors I don't see two.

It's in my path.

**Comment by RedSoxFan** [comment]
Are you still having issues with swaynag not starting or dismissing correctly?

**Comment by SirCmpwn** [comment]
Nope
