### ISSUE TITLE
Feature request: avoid running sway as root

### ISSUE THREAD

**Issue by tdw546** [swaywm/sway#2438]
> On systems with logind, you need to set a few caps on the binary:
> 
> sudo setcap "cap_sys_ptrace,cap_sys_tty_config=eip" /usr/local/bin/sway
> 
> On systems without logind, you need to suid the sway binary:
> 
> sudo chmod a+s /usr/local/bin/sway
> 

As someone looking for a more secure alternative for X11, I am somewhat dissappointed to learn that sway requires root permissions to run.

It would be awesoe if we could avoid running this large c application as root at all or at least drop privileges right ater the start.

Please note that cap_sys_ptrace and cap_sys_tty_config are effectifly equal to full root:
https://forums.grsecurity.net/viewtopic.php?f=7&t=2522

**Comment by SirCmpwn** [comment]
We *do* immediately drop privledges on start.

**Comment by SirCmpwn** [comment]
We also no longer require caps at all on systems with logind or elogind, that should probably be updated.

**Comment by tdw546** [comment]
Wow thanks, that is awesome

**Comment by hanko34** [comment]
After removing all caps from sway, the following warning is given at startup:

> [sway/sway/main.c:197] !! DANGER !! Sway does not have CAP_SYS_PTRACE and cannot enforce security rules for processes running as other users.

Testet on: sway version 1.0-alpha.5-43-g425ee270 (Aug  9 2018, branch 'master')

Is the warning still valid or a leftover?

**Comment by SirCmpwn** [comment]
Leftover. I just removed it.

**Comment by concatime** [comment]
Is `libcap` still required now? Even for wlroots?

**Comment by emersion** [comment]
wlroots requires it to do a sanity check before starting the direct session.

**Comment by emersion** [comment]
sway uses it to drop capabilities. We should make it optional, and I wonder if we should keep it at all (we could just stick to `setgid`). Also we're keeping `CAP_SYS_PTRACE`, we shouldn't do that.
