### ISSUE TITLE
failed to load driver: amdgpu

### ISSUE THREAD

**Issue by hanko34** [swaywm/sway#2442]
When running sway, the performance for native wayland application is rather bad and after logout I get this message:

> libGL error: MESA-LOADER: failed to retrieve device information
> libGL error: unable to load driver: amdgpu_dri.so
> libGL error: driver pointer missing
> libGL error: failed to load driver: amdgpu

When I run weston, everything works fine and there are not issues with the driver or the performance of graphical applications. The amdgpu driver itself seems to have loaded normally too.

I suspect this to also be the source of the problem when running firefox (with native wayland support), which crashes every time i double click the navigation bar after a website hat already been opened.

> Gdk-Message: 16:47:49.946: Error reading events from display: Invalid argument

This also does not happen when running weston.

Here is the full debug 
[log.txt](https://github.com/swaywm/sway/files/2275275/log.txt)

There are also some potentially interesting entries in dmesg

> [  677.941317] sway[3510]: segfault at 1c1 ip 00006d3ef73295a0 sp 00007613e76f9758 error 4 in libwlroots.so.0.0.0[6d3ef7322000+3e000]
> [  820.826721] sway[4946]: segfault at 140 ip 000008f6d0bbee31 sp 00007ec7ccc84760 error 4 in sway[8f6d0b97000+35000]
> [  909.145213] sway[5853]: segfault at c8 ip 0000016f0b43c6d1 sp 00007d2575c26d10 error 4 in sway[16f0b42a000+35000]
> 
> [ 1090.415615] sway[6094]: segfault at 140 ip 00000b7adca5ae31 sp 0000727a157f6d40 error 4 in sway[b7adca33000+35000]
> [ 1128.707836] sway[7716]: segfault at 18 ip 000069e1ec460500 sp 00007561dead6aa0 error 4 in libwayland-server.so.0.1.0[69e1ec45a000+11000]
> [ 2558.879045] sway[8284]: segfault at 140 ip 00000590727afe31 sp 00007f8894a067f0 error 4 in sway[59072788000+35000]
> [ 2574.212603] sway[11905]: segfault at a3600000017 ip 00000a36cdabde3d sp 000070253a159250 error 4 in sway[a36cda96000+35000]
> 
> [  978.106791] Chrome_~dThread[6366]: segfault at 0 ip 00006fa75c574371 sp 00006fa754453ac0 error 6 in libxul.so[6fa75c569000+4dd9000]
> [  978.106821] Chrome_~dThread[6477]: segfault at 0 ip 0000678456c0d371 sp 000067844eaecac0 error 6 in libxul.so[678456c02000+4dd9000]

sway version 1.0-alpha.5-43-g425ee270 (Aug  9 2018, branch 'master')

GPU: AMD Radeon RX 480

**Comment by SirCmpwn** [comment]
Can you use rootston? If not, please open a bug on the wlroots tracker.

**Comment by hanko34** [comment]
I can use rootston, however the same issues apply if I run e.g. firefox in rootston

**Comment by SirCmpwn** [comment]
Please move this bug to the wlroots tracker.
