### ISSUE TITLE
Feature request: Fixed number of (empty) workspaces

### ISSUE THREAD

**Issue by hanko34** [swaywm/sway#2443]
Please add an option to allow for the creation of a fixed number of workspaces and to prevent deleting empty workspaces.

I know this is not i3 behavior, but this should be rather easy to implement and can be disabled by default.

As someone coming from awesomeVM I absolutely cannot work without this and it would make switching to sway for many other easier as well.

**Comment by hanko34** [comment]
I do not know how to implement it myself but, looking at the the following code section, it should be easy to build this feature if a new config option e.g. called "persistent workspaces" were to be implemented:

https://github.com/swaywm/sway/blob/01af34391267e91461a4ab7a1234dd58f45d2c93/sway/input/seat.c#L335

If this line were to be changed to also check for this config option and only delete the workspace if it is not set (which would be the default), this feature would already be complete.

I don't know how to implement a new config option or how to check it, but I would be glad to support this and e.g. do some extensive testing.

**Comment by emersion** [comment]
>Please add an option to allow for the creation of a fixed number of workspaces and to prevent deleting empty workspaces.

Not sure we want to support this. We already have a bunch of i3 extensions though.

>As someone coming from awesomeVM 

If you come from awesome you might want to support the [Way Cooler](https://github.com/way-cooler/way-cooler) project.

>I do not know how to implement it myself

https://drewdevault.com/2018/03/17/Hack-everything-without-fear.html

**Comment by elr32** [comment]
Although I would also like to see persistent workspaces in sway, I found a good workaround to make sway behave more like Awesome.

In hopes this might help anyone: https://gist.github.com/elr32/67fc5c758e05090b00e3d7ff3c8e9633

**Comment by SirCmpwn** [comment]
If you want to use Awesome check out Way Cooler.

**Comment by hanko34** [comment]
> If you want to use Awesome check out Way Cooler.

Way Cooler is a cool project too, however it is still at least a year behind sway and currently cannot even be compiled (I have tried a lot!!!)

In any case thanks for the script I will try that as an alternative.

**Comment by SirCmpwn** [comment]
Go help them out!

**Comment by aviau** [comment]
I have implemented static workspaces using a script.

See https://github.com/swaywm/sway/issues/4928#issuecomment-586116020
