### ISSUE TITLE
Some applications don't show up in the systray

### ISSUE THREAD

**Issue by sudoman** [swaywm/sway#2456]
Hello,

I noticed that not all application show their icons in the systray / notification area. Quassel IRC works, but Nagstamon does not. It would be great if they all showed their icons. : )

I'm using sway version 0.15.2 on Fedora 28.

Thanks,
Andrew

**Comment by SirCmpwn** [comment]
There are two standards for tray icons: SNI and Xembed. Only the former is supported at the moment.
