### ISSUE TITLE
Weird bug when toggling between floating and tiled

### ISSUE THREAD

**Issue by emersion** [swaywm/sway#2467]
1. Open a terminal and Gedit, focus Gedit
2. Switch Gedit mode between floating and tiled a few times
3. Switch focus between floating containers and tiled containers

The result is a floating Gedit window with half-drawn borders which we can't interact with (it seems it's neither tiled nor floating).

**Comment by RyanDwyer** [comment]
Some easier steps to reproduce:

1. Open any two views
2. Float one of them
3. With the floating view focused, run `focus mode_toggle` three times

Anyway, I encountered this in my refactor-seat-get-focus branch and fixed it there. I don't remember exactly what the issue was.
