### ISSUE TITLE
Drag'n'drop works badly or not at all in some apps

### ISSUE THREAD

**Issue by minus7** [swaywm/sway#2469]
Dragging songs around in GMPC to reorder them doesn't work: The drag is dropped pretty much immediately. Treestyle Tab Bar in Waterfox exhibits the same problem, but it's a bit more obvious what's going wrong here: as soon as the mouse enters the surface that is drawn when dragging, the drag drops. In GMPC it's the song row that appears under the cursor. In Waterfox it's the tab; here it doesn't drop immediately because the dragged tab is rendered south of the pointer and it only drops when you move the mouse down

**Comment by emersion** [comment]
https://github.com/swaywm/wlroots/pull/841
