### ISSUE TITLE
Workspaces from other outputs have incorrect scaling after unplugging

### ISSUE THREAD

**Issue by atomnuker** [swaywm/sway#2485]
To test, have 2 outputs, one with a scale factor of 2 and one with a scale factor of 1.
Put some clients on workspaces on the second output (the one with scale = 1), then unplug the second output.
The workspaces then migrate to the first output (scale = 2) and clients are upscaled by the compositor, rather than letting them scale themselves. The only way to fix this is to move the clients to another non-empty workspace with correctly scaled clients.
I suppose the issue is that enter events are not sent when workspaces are migrated between outputs or between workspaces.

**Comment by RyanDwyer** [comment]
Will be fixed in #2483.
