### ISSUE TITLE
Shadow around cursor after reloading sway

### ISSUE THREAD

**Issue by aminb** [swaywm/sway#2486]
After reloading sway a few times, a small but still noticeable black shadow appears around the cursor.

Couldn't figure out how to get rid of it, other than by exiting sway and starting it again.

**Comment by emersion** [comment]
Yeah, I've suspected this to happen for quite some time. I think we draw multiple times the cursor image for some reason.

**Comment by aminb** [comment]
Right. @SirCmpwn also pointed out that it probably happens because new cursor is created without cleaning up the old one, which they end up piling up on top of each other.

Any hints on where to look for this? My first instinct was to look into `sway/commands/reload.c` but there wasn't much there, aside from a call to `load_main_config`. `sway/config.c` does seem to include some mentions to inputs.

**Comment by SirCmpwn** [comment]
Look for wlr_cursor related stuff, it's the thing which is responsible for drawing cursors on screen.
