### ISSUE TITLE
Closing fullscreen windows no longer focuses the other windows on that workspace

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/sway#2534]

**Comment by RyanDwyer** [comment]
If the terminal is the only view in the workspace before running mpv then everything seems to work correctly. If I have two terminals open, use one to launch mpv, fullscreen mpv then press `q`, it looks like the workspace itself is focused (both terminals have focused styling) and one of the terminals has keyboard focus.

Is that what you're experiencing?

**Comment by SirCmpwn** [comment]
Hmm, this works for me now. Maybe I didn't have all my ducks in a row when I tested it before.
