### ISSUE TITLE
Sway fails to start

### ISSUE THREAD

**Issue by biblepix** [swaywm/sway#2538]
I have been using Sway for a few months now, and suddenly it won't start up. I have no idea what has caused this. Reinstalling Wayland and wlc didnt help. Attat
[sway.log](https://github.com/swaywm/sway/files/2331883/sway.log)
ching log file. Can someone help me?

**Comment by SirCmpwn** [comment]
This will be addressed when [wlroots](https://github.com/swaywm/wlroots) is completed and [integrated with sway](https://github.com/swaywm/sway/issues/1390).
