### ISSUE TITLE
Choppy cursor movement when dpms off

### ISSUE THREAD

**Issue by kamiyaa** [swaywm/sway#2551]
This is on a laptop with the trackpad as input. When connected to another display (in my case via vga), and setting the laptop's monitor to dpms off, the cursor becomes choppy and laggy.

on:
sway version 1.0-alpha.5-176-g98ef29c2 (Aug 28 2018, branch 'master')
wlroots version 2f484537181c515082b632f9d575613abda72a48

**Comment by emersion** [comment]
Maybe related to https://github.com/swaywm/sway/issues/2486

**Comment by emersion** [comment]
Can you try https://github.com/swaywm/wlroots/pull/1320?

**Comment by emersion** [comment]
https://ptpb.pw/RDz1
