### ISSUE TITLE
Workspace losing focus

### ISSUE THREAD

**Issue by trmendes** [swaywm/sway#2556]
I have a few shortcuts configured that will open the apps I use the most. Few of those apps are configured to be oppened on their repective workspaces using the assigned key.

 The scenario:

 I'm, for example, on workspace 2 and hit a shortcut to run an app, this app will run and then it will be assigned to its workspace, for example 6.

So now I'm on workspace 2 and there is an app running on worksapce 6 just like expected. 

What happens now is that all the apps on workspace 2 loose focus and the only way to get back to those apps is to hit my shortcut to move me to workspace 6 (where the new app is loaded) and then hit the shortcut to move me back to workspace 2. After doing it everything starts to work again \o/.

I'm using the master:HEAD version of both sway and wlroots

**Comment by RyanDwyer** [comment]
I'm having trouble reproducing this. I put this in my config:

    assign [class="Firefox"] workspace 2

Then in a single output session, I opened a terminal on workspace 1, created workspace 2 and put a terminal there, switched back to workspace 1 and launched Firefox. Firefox opened on workspace 2 and my focus remained on the terminal in workspace 1.

**Comment by trmendes** [comment]
It normally happens when I first start sway. When I do so, the first thing I do is to press the shortcut to start firefox on WS2 then I move to the WS2 using a shortcut for that and then I start Signal Messenger with another shortcut assignet to WS8 and now I'm just wondering if this could be an issue with electron apps

[sway_config.txt](https://github.com/swaywm/sway/files/2342892/sway_config.txt)

I'm posting my config file as a resource..it has a txt extension because it seems like github can't post a file without an ext here (I might be wrong)

Anyway....this behavior isn't constant but it is pretty common here on my setup. 

I'm going to run sway on debug mode to see if something come out from the logs and I post here latter....what else could I do to bring more valuable information to this issue?

**Comment by trmendes** [comment]
Awesome @RyanDwyer ...I'll try it all out and I'll let you know the results....thanks

**Comment by trmendes** [comment]
It seems like it is Electron related. I ran a shortcut for libreoffice and after 10 tries nothing happened....then I ran a shortcut for Riot which is Electron based and the issue happen straight away.

**Comment by trmendes** [comment]
I belive this one is related to #2746

**Comment by trmendes** [comment]
I have been facing other problems with Electron apps on sway. Since a few git updates back they started to freeze a lot and the app container blinks once in a while.

**Comment by nagisa** [comment]
Know an easy way to reproduce this issue as I’ve been facing it with firefox.

1. Have in your config something like `assign [class="Firefox"] workspace 1`;
2. Open firefox, then open a new window of firefox and move the new window to a workspace other than 1st;
3. With the new window focused click `Ctrl+N` to open a new window (alternatively right-click any link and “Open Link in New Window”);
4. Observe being unable to interact with a page or most of the Firefox UI (e.g. omnibar or the hamburger menu);
5. Switch to workspace 1 and then back;
6. Observe being able to interact with the pages again.

**Comment by RedSoxFan** [comment]
I think this is resolved by https://github.com/swaywm/wlroots/pull/1541 and would have only occurred when a xwayland client had focus and another xwayland client was opened (which appears to be true for every application listed in this thread).

I'm going to close this via swaywm/wlroots#1541, but if anyone is able to reproduce, feel free to reopen.
