### ISSUE TITLE
Middle click works despite middle_emulation being disabled for a touchpad

### ISSUE THREAD

**Issue by atomnuker** [swaywm/sway#2570]
As the title says, setting middle_emulation to disabled for a touchpad doesn't actually disable middle click emulation, and as the libinput default is a 3 finger tap a middle click event is still generated upon performing this action.

**Comment by RedSoxFan** [comment]
According to the [libinput documentation](https://wayland.freedesktop.org/libinput/doc/latest/middle-button-emulation.html), tap to click is not effected by middle emulation. Middle emulation only determines whether to translate simultaneous left and right button events into middle button events. Setting middle emulation to enabled or disabled is working fine for me, but some devices may not support configuration.

Assuming you actually do want to disable middle tap to click, there really are not many options. The only three states for tap to click are:
  - tap to click is disabled
  - tap to click is enabled with button map lrm (1 finger tap = left, 2 fingers = right, 3 fingers = middle)
  - tap to click is enabled with button map lmr (1 finger tap = left, 2 fingers = middle, 3 fingers = right)

Only the first option disables middle tap to click, but that would disable both left and right tap to click as well.
