### ISSUE TITLE
Inhibit idle while playing fullscreen video

### ISSUE THREAD

**Issue by glpub** [swaywm/sway#2595]
swayidle works well and it switches the screen while playing video
is it possible optionally to stop such behavior of it?

**Comment by emersion** [comment]
What video player are you using?

mpv should already have this behaviour, and I think vlc on Wayland too.

**Comment by glpub** [comment]
Hm
Just tried both mpv and vlc - monitor goes blank
And when chromium or firefox play youtube video the screen switches off too

**Comment by clarcharr** [comment]
I'm still running into this problem on master. It would be nice if there were some kind of manual override, e.g. a keyboard shortcut that could toggle off swayidle manually. Right now, I just kill the swayidle process, which isn't ideal because then I have to manually restart it later.

**Comment by emersion** [comment]
I'd also like more control over `swayidle`, to e.g. be able to immediately blank the screen when locking the computer. Maybe a third-party idle daemon should be created if these features are too much for `swayidle`.

**Comment by clarcharr** [comment]
Can't you just run swaylock and turn on DPMS with the same keyboard combination?

**Comment by emersion** [comment]
>Can't you just run swaylock and turn on DPMS with the same keyboard combination?

Nah, because I want the screen to be turned on again when I move my cursor/type on my keyboard to unlock.

**Comment by progandy** [comment]
@clarcharr Did you try to run mpv with ```--stop-screensaver```?

**Comment by Hi-Angel** [comment]
Interestingly, when playing a video in Qutebrowser, the screen only turns of for a few seconds, and then comes back.

Any hints, what needs to be looked at to fix this issue?

**Comment by akiva** [comment]
I second this. Some way to trigger a keepalive would be great.

**Comment by emersion** [comment]
Related to https://github.com/swaywm/sway/issues/3070

**Comment by efouladi** [comment]
Given that wlroots already implemented zwp_idle_inhibit_v1, shouldn't this be on the apps to adhere to?

**Comment by raidzero** [comment]
Just wanted to chime in here and offer a pretty simple workaround. I use swayidle and I have inhibitors in place by way of wrapper scripts around my idle actions. Inhibitors are AC power present and pulseaudio playing.

You may want to just query sway for any fullscreen containers using IPC and also query alsa/pulseaudio for active playback. If sound is playing and a fullscreen container is focused, you can assume that video is playing.

I can give some example scripts if necessary.

**Comment by RedSoxFan** [comment]
I'm going to close this in favor of #3070, which is more generic/powerful and has syntax proposals. I don't think it makes sense to keep both open

**Comment by DenseComet** [comment]
@raidzero could you link your example scripts?

Thanks!

**Comment by raidzero** [comment]
@DenseComet here is what I have: 
run.sh runs swayidle with all the other scripts as actions.

https://github.com/raidzero/dotfiles/tree/master/.config/sway/idle
