### ISSUE TITLE
FR: change keyboard layout only if exact keys have been pressed

### ISSUE THREAD

**Issue by glpub** [swaywm/sway#2596]
I have configured alt+shift as kbd layout switch keys to mirror windows settings on the office PC
But it makes impossible to use alt+shift+<some key here> keybindings in applications like Jetbrains IntelliJ

In windows one can press alt+shift+<some key> and that will not switch kbd layout instead that will call appropriate keybinding in the application

Is it possible to have such behavior in sway?

**Comment by emersion** [comment]
This is handled by libxkbcommon IIRC, so probably not.
