### ISSUE TITLE
Gentoo - swaybg requires the compositor to support..

### ISSUE THREAD

**Issue by Kreyren** [swaywm/sway#2607]
**ISSUE**
when **sway** is invoked it results in **swaybg requires the compositor to support the desktop-shell extension.urity rules for processes running as other users.** error followed by **Unable to recieve IPC response enforce security rules for processes running as other users.** if swaybf USE flag is disabled.

**EXPECTED**
To start sway WM.

**NOTE**
Suspect issue with **swaybg**. If swaybg USE flag is removed == results in new issue.

**INFO**
> uname -r == 4.18.5-gentoo

> uname -a == Linux localhost 4.18.5-gentoo #3 SMP Sun Sep 2 17:06:23 -00 2018 x86_64 Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz GenuineIntel GNU/Linux

> emerge --info == https://paste.pound-python.org/show/pXNPT5PCJ1VrBQt6UUFG/

> sway 0.15.2 == https://packages.gentoo.org/packages/dev-libs/sway

> wayland 1.15.0 == https://packages.gentoo.org/packages/dev-libs/wayland

> Gentoo with testing builds == `ACCEPT_KEYWORDS="~amd64"` in `make.conf`

> x11-libs/gdk-pixbuf == is emerged v2.36.12.

> running 9999 version (emerged from source) of sway atm.

**PROGRESS**
1. Testing 9999 version of https://packages.gentoo.org/packages/dev-libs/sway == same issue

2. Removed swaybg from USE flags 
2.1 New result: **[ipc-client.c:50] Unable to recieve IPC response enforce security rules for processes running as other users.**
2.2 Can't find any resources about issue 2.1.

3. Is https://forum.voidlinux.org/t/sway1-0-alpha-5-install/6544/39 relevant?
3.1 created /tmp dir with chmod 1777 for a USER.

**Comment by emersion** [comment]
Closing because it's a 0.15 issue.

**Comment by Kreyren** [comment]
> Closing because it's a 0.15 issue.

Read the article i said that i used 9999 version which is using the latest git at the time..

Based on sway github issues most of issues is ignored by the sway developers so it's probably better to keep it to closed.. I'm not sure if i want to contribute to seemingly abadonware..

**Comment by emersion** [comment]
>Read the article i said that i used 9999 version which is using the latest git at the time..

No, 9999 still builds the 0.15 branch, not the master branch.

>Based on sway github issues most of issues is ignored by the sway developers

We don't have time to afford investigating all issues. I already spend most of my free time working on Sway and other open-source projects, and it's the case of many contributors too. Keep in mind that sway is not a product, it's a collaborative project, so don't expect commercial support.

You can help us by sending pull requests instead of opening issues. If you really can't investigate your issue, you can always support @SirCmpwn on Patreon.

>I'm not sure if i want to contribute to seemingly abadonware..

I wouldn't call a project abandonware when [48 pull requests have been merged since last week](https://github.com/swaywm/sway/pulse).

**Comment by alexjp** [comment]
as a gentoo user, @Kreyren you can check that the ebuild 9999 version is not latest git of master, but 0.15 branch

`
cat sway-9999.ebuild 
# Copyright 1999-2018 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=6

inherit git-r3 eutils cmake-utils

DESCRIPTION="i3-compatible Wayland window manager"
HOMEPAGE="http://swaywm.org/"

EGIT_REPO_URI="https://github.com/swaywm/sway.git"
EGIT_BRANCH="0.15"
.......
`

**Comment by Kreyren** [comment]
> as a gentoo user, @Kreyren you can check that the ebuild 9999 version is not latest git of master, but 0.15 branch
> 
> ```
> cat sway-9999.ebuild 
> # Copyright 1999-2018 Gentoo Authors
> # Distributed under the terms of the GNU General Public License v2
> 
> EAPI=6
> 
> inherit git-r3 eutils cmake-utils
> 
> DESCRIPTION="i3-compatible Wayland window manager"
> HOMEPAGE="http://swaywm.org/"
> 
> EGIT_REPO_URI="https://github.com/swaywm/sway.git"
> EGIT_BRANCH="0.15"
> .......
> ```

Noted, afaik most of 9999 builds is mirror to the github not sure why its limited on this ebuild. My bad then.

> > Read the article i said that i used 9999 version which is using the latest git at the time..
> 
> No, 9999 still builds the 0.15 branch, not the master branch.
> 
> > Based on sway github issues most of issues is ignored by the sway developers
> 
> We don't have time to afford investigating all issues. I already spend most of my free time working on Sway and other open-source projects, and it's the case of many contributors too. Keep in mind that sway is not a product, it's a collaborative project, so don't expect commercial support.

I'm aware of that thats the point of FOSS, but since the response took so long i assumed that none is maintaining sway and when i look last time the last commit was long ago too..  

> You can help us by sending pull requests instead of opening issues. If you really can't investigate your issue, you can always support @SirCmpwn on Patreon.
> 
> > I'm not sure if i want to contribute to seemingly abadonware..
> 
> I wouldn't call a project abandonware when [41 pull requests have been merged since last week](https://github.com/swaywm/sway/pulse).

Noted, not problem then.
