### ISSUE TITLE
Sway's strcasestr conflicts with the one in FreeBSD's libc

### ISSUE THREAD

**Issue by sghctoma** [swaywm/sway#2616]
FreeBSD has an strcasestr function in libc, which causes a conflict with sway's strcasestr from include/stringop.h (introduced in 7e81e58). What would be the appropriate fix for this? Renaming sway's strcasestr, or using preprocessor directives to use the libc version on FreeBSD? The former feels cleaner to me, but better to ask.

**Comment by emersion** [comment]
We generally don't do the former (ie. we don't use GNU-specific functions with a fallback). Why is the FreeBSD symbol visible? Don't you need to define `_BSD_VISIBLE` to use it?

**Comment by sghctoma** [comment]
Yup, my bad, did not think this through. Sorry for that.
__BSD_VISIBLE is needed, but it is defined by default unless there are some other feature macros defined. Only needed to define __POSIX_C_SOURCE in files that include stringop.h to resolve this.
I will send a PR, but I'd like to test in on a Linux machine too, to ensure nothing broke.

**Comment by emersion** [comment]
Hmm, isn't there a way to disable `__BSD_VISIBLE` without defining `__POSIX_C_SOURCE`? This could be done either in Meson or in `stringop.h`.

**Comment by sghctoma** [comment]
If `_POSIX_C_SOURCE` is not defined, `__BSD_VISIBLE` is disabled only if one of the following is defined:

- `_ANSI_SOURCE`
- `_C99_SOURCE`
- `_C11_SOURCE`

I have tried adding the `-D_C11_SOURCE=1` parameter through meson.build, but than `_POSIX_C_SOURCE` had to be defined at even more places, because otherwise `struct timespec` is hidden.
So in summary, I don't think there is a cleaner way.

**Comment by sghctoma** [comment]
I've read everything I could about feature macros in the past few days, but I've never dealt with them before I started using sway/wlroots, so this may be a dumb question:

What could cause a scenario where a FreeBSD build fails and a Linux build succeeds while using _POSIX_C_SOURCE? As per my understanding, when only the _POSIX_C_SOURCE macro is defined, the compilation environments should be the same (= everything the defined POSIX version provides, and nothing else) on both operating systems. Is there something I'm missing here? I would like to fully understand the possible drawbacks before sending the pull request.

On a related note: the fact that struct timespec is visible only with _POSIX_C_SOURCE is a bug in FreeBSD. It is in the C11 standard, so it should also be visible when __STDC_VERSION__ >= 201112L (which is true for sway, since -std=c11 sets that macro). I have filed a bug (https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=231425), and when that gets resolved, maybe sway should define _C11_SOURCE, and the _POSIX_C_SOURCE defines added here could be removed.

**Comment by emersion** [comment]
>What could cause a scenario where a FreeBSD build fails and a Linux build succeeds while using _POSIX_C_SOURCE?

Use `strcasestr` in a file it wasn't used before

**Comment by sghctoma** [comment]
Ah, OK, thanks @emersion, I was overthinking it, and could not see the obvious answer.

Maybe I'm spending too much time on this, but I'd like to do it right, and because of this, I still have questions. I hope it's not a problem :)

The root cause of this issue is that with no feature test macros defined, FreeBSD gives you everything (POSIX 2008 + XSI extensions, C11 + EXT1 extensions, BSD specific stuff). So right now there are files in wlroots and sway that use a much wider namespace set than needed. This could be solved by defining `_C11_SOURCE` in meson.build, which gives only C11. 

@SirCmpwn, I know you've rejected the idea of defining feature test macros at the build system level before, but if I understood correctly, the reason behind that was to keep every file at the narrowest possible namespace. Would defining a macro that minimizes the build environment on FreeBSD acceptable? 

If it is acceptable, I have another question:
There is one problem with using `_C11_SOURCE` currently: the file sway/ipc-server.c causes trouble, because POSIX 2008 is needed for `setenv`, but `SOCK_NONBLOCK` and `SOCK_CLOEXEC` are not POSIX (nor any other standard). On FreeBSD, they are guarded by `__BSD_VISIBLE`, therefore both `_POSIX_C_SOURCE` and `_C11_SOURCE` will hide them. This is currently solved by not defining any feature macros on FreeBSD (= everything is visible), but it would be possible to use two `fcntl` calls to set `FD_CLOEXEC` and `O_NONBLOCK` instead. This would make ipc-server.c POSIX compliant. What do you think?

**Comment by SirCmpwn** [comment]
I'm okay with setting feature test macros at the build system level now. I wanted to avoid it because if we build with a subset of options we may not need everything, but it's really not that important.

**Comment by sghctoma** [comment]
OK, thanks for the answer. I'll send a PR shortly.
