### ISSUE TITLE
PPA appears to be broken

### ISSUE THREAD

**Issue by brianmay** [swaywm/sway#2623]
As referenced by https://github.com/swaywm/sway/wiki/Unsupported-packages:

```
Reading package lists... Done
W: The repository 'http://ppa.launchpad.net/s.noack/ppa/ubuntu cosmic Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/s.noack/ppa/ubuntu/dists/cosmic/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

From a Debian/stretch system.

**Comment by brianmay** [comment]
Sorry, not sure where I should file bug reports concerning "Unsupported-packages." Possibly that wiki page should be updated to have contact details for bug reports...

**Comment by RyanDwyer** [comment]
Ubuntu Cosmic hasn't been released yet. Are you running a dev version of Ubuntu?

The PPA contact's name is in the PPA URL: https://launchpad.net/~s.noack. You could ask him, but I'd wait until Cosmic is released.

**Comment by brianmay** [comment]
No, like I said this is Debian/stretch.

I have no idea why `add-apt-repository ppa:s.noack/ppa` is choosing to use cosmic, or what I should be using instead.

I looked up that web page, but couldn't find any way of contacting him.

**Comment by RyanDwyer** [comment]
Closing this.

* As the wiki says, we don't provide support for PPAs
* The PPA is for sway 0.15, which we are no longer accepting issues for
* When 1.0 is released, that wiki page will likely be changed or removed anyway

**Comment by brianmay** [comment]
Maybe you should update https://github.com/swaywm/sway to point to the preferred way of installation then? Currently the first thing I see is the unsupported packages.

There are also stern warnings not to use the 1.0 release "Note that sway alpha releases are not considered complete, are missing many features, and will have many bugs. You are strongly encouraged to remain on sway 0.15.x if you are not prepared to deal with constant breakage and keep quiet about it. Please do not submit bug reports for this version of sway. Submit patches instead."

So as a new user of swarm I am confused what I should be using. Or maybe I should avoid this project  until it becomes more mature?

**Comment by ascent12** [comment]
>So as a new user of swarm I am confused what I should be using

There is not an entirely obvious answer to that right now.
At this point, sway 1.0 is literally an entirely different program than sway 0.15 (as in, basically all of the code has changed), so nobody really wants to support or even really think about 0.15. We're in a limbo of "0.15 is too old" but "1.0 isn't released yet".

As said in https://github.com/swaywm/sway/issues/1735#issuecomment-425046390, we want to get a real release out somewhat soon, and get people off of 0.15.

That stern warning is somewhat outdated (but not entirely). In general, sway 1.0 is very solid; I've been using it as my daily driver for ages now. Until there is a real release and people package it, you're going to need to compile it yourself.

**Comment by SirCmpwn** [comment]
If you want Debian or Ubuntu support, you've gotta step up and do it yourself. Our ports are maintained by users who use that distribution, and none of the core devs are on Debian or Ubuntu. Don't make demands, send patches!

**Comment by heiserhorn** [comment]
There is a ITP open in debian https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=821397.

Work has been done on https://salsa.debian.org/swaywm-team/sway

The package builds correctly and based on the ITP thread there might be an upload of b2 on experimental if not once version 1.0 is released it will be uploaded in unstable.

Cheers

Mike
