### ISSUE TITLE
(IPC) Root node contains no focus information

### ISSUE THREAD

**Issue by ianyfan** [swaywm/sway#2632]
When running `swaymsg -t get_tree` the root node has an empty focus array. This is since the focus array is built from the focus stack, which does not contain outputs.

Possible solutions I have thought of:

1. track outputs on the focus stack (not sure what additional logic is required to make this not break anything)
2. when building the focus array for the root container, use workspaces on the focus stack to determine which outputs should be included, or something (this requires additional logic to make sure that entries are not duplicated)

**Comment by RyanDwyer** [comment]
I would definitely go with option 2. If we were to go with option 1 then we'd have to make exceptions in places (eg. if node is output, return) which makes things more difficult for ourselves. If we go with option 2 then the logic isn't too hard - just build a list of unique outputs using `seat_for_each_node`, `node_get_output`, and `list_find` to prevent duplicates.
