### ISSUE TITLE
Cannot use ";" for seperating two commands in exec/exec_always

### ISSUE THREAD

**Issue by nycex** [swaywm/sway#2642]
If I use ";" for seperating this command:
`exec_always --no-startup-id pkill compton; compton --config ~/.config/compton.conf`
I get this error:
`[handlers.c:1120] Error on line 'exec_always --no-startup-id pkill compton; compton --config ~/.config/compton.conf': Unknown/invalid command`
But if I use "&&" it perfectly works:
`exec_always --no-startup-id pkill compton && compton --config ~/.config/compton.conf`
But I can't use that, because I don't know if compton is running already.

**Comment by SirCmpwn** [comment]
You need to wrap the command in quotes. Ditch `--no-startup-id` while you're at it, it has no effect on sway.

**Comment by Nikola-Milovic** [comment]
I am not quite sure I get how to run multiple commands at once. I am doing this currently 

```
set $mode_gammastep Set colour temperature: (a)uto, (r)eset, (1)500K, (2)500K, (3)000K, (4)000K, (5)000K, (6) day, ;
set $bright ~/scripts/set-brightness
set $contr ~/scripts/set-contrast
set $killgam killall gammastep
mode "$mode_gammastep" {
    bindsym a exec "$killgam;gammastep -P -t 5000:4000", mode "default"
    bindsym r exec "$killgam;gammastep -x; $bright 50 ; $contr 50", mode "default"
    bindsym 1 exec "$killgam;gammastep -P -O 1500; $bright 0; $contr 30", mode "default"
    bindsym 2 exec "$killgam;gammastep -P -O 2500; $bright 15; $contr 40", mode "default"
    bindsym 3 exec "$killgam;gammastep -P -O 3000; $bright 25; $contr 50", mode "default"
    bindsym 4 exec "$killgam;gammastep -P -O 4000; $bright 35; $contr 50", mode "default"
    bindsym 5 exec "$killgam;gammastep -P -O 5000; $bright 45; $contr 50", mode "default"
    bindsym 6 exec "$killgam;gammastep -x; $bright 70; $contr 70", mode "default"
 
    # exit mode: "Enter" or "Escape"
    bindsym Return mode "default"
    bindsym Ctrl + c mode "default"
    bindsym Escape mode "default"
}

bindsym $mod+Ctrl+s mode "$mode_gammastep"
```

And its behaving weirdly

**Comment by 100espressos** [comment]
But when reduced, those become like: ```exec "command1;command2", something_more``` so perhaps keep trying different formatting?

Here at least, this seems to work properly (and alternately, a script with those commands stuffed in it):
```exec "pkill swaybg; swaybg -m fit -i wallpaper"```
