### ISSUE TITLE
Cannot use con_id for window specific actions

### ISSUE THREAD

**Issue by nycex** [swaywm/sway#2643]
When I use i3, I used this command to close normal windows and hide my scratchpad terminal:
`bindsym $mod+q [con_id="__focused__" instance="^(?!scratch|dropdown).*$"] kill; [con_id="__focused__" instance="^(?scratch|dropdown).*$"] scratchpad show`
But now, no commands where the con_id should be `__focused__`:
`[con_id="__focused__" instance="^(?scratch|dropdown).*$"] `
are working anymore.

My sway version: 0.15.2

**Comment by nycex** [comment]
Another example is my scratchpad show keybind:
`bindsym $mod+g [instance=$scratchterm] scratchpad show`

**Comment by Marteon** [comment]
0.15 Bugs are not accepted anymore
