### ISSUE TITLE
[1.0 Alpha] Sway crashes after a few seconds

### ISSUE THREAD

**Issue by nycex** [swaywm/sway#2650]
[Here is the paste of the output](http://ix.io/1mRS)
sway version: 1.0-alpha.5-362-g5abf8322 (Sep 17 2018, branch 'master')

**Comment by ascent12** [comment]
>Warning: Proprietary Nvidia drivers are NOT supported. Use Nouveau.

The nvidia proprietary driver does not support the required interfaces for sway/wlroots to work.
In the off-chance you're using nvidiafb, that won't work either, since it's not a KMS driver.

**Comment by nycex** [comment]
The problem is, you cannot really use nouveau for games.

**Comment by emersion** [comment]
>The problem is, you cannot really use nouveau for games.

https://drewdevault.com/2017/10/26/Fuck-you-nvidia.html

**Comment by ascent12** [comment]
Go bother Nvidia to support GBM then.
