### ISSUE TITLE
[Alpha 1.0] Sway also crashes with Nouveau drivers

### ISSUE THREAD

**Issue by nycex** [swaywm/sway#2651]
So, I just installed nouveau to use the sway 1.0 Alpha and I get this error:
`[sway/sway/server.c:39] Unable to create backendevice`
sway version: 1.0-alpha.5-362-g5abf8322 (Sep 17 2018, branch 'master')

**Comment by emersion** [comment]
Weird, the error message is "Unable to create backend" (not "backendevice").

Can you please give use the full debug logs?

**Comment by nycex** [comment]
```
2018-09-17 15:22:05 - [sway/sway/server.c:33] Preparing Wayland server initialization
2018-09-17 15:22:05 - [sway/sway/server.c:39] Unable to create backendevicegind
```

**Comment by nycex** [comment]
That's with the -d option

**Comment by emersion** [comment]
Please redirect the output to a file.

```
sway -d >sway.log 2>&1
```

**Comment by nycex** [comment]
Weird. That's the output now
```
2018-09-17 15:42:10 - [sway/sway/server.c:33] Preparing Wayland server initialization
2018-09-17 15:42:10 - [backend/session/logind.c:404] Successfully loaded logind session
2018-09-17 15:42:10 - [backend/backend.c:128] Found 0 GPUs
2018-09-17 15:42:10 - [backend/backend.c:267] Failed to open any DRM device
2018-09-17 15:42:10 - [sway/sway/server.c:39] Unable to create backend
```

**Comment by nycex** [comment]
Ok, wait that was an error on my side, but now, that i've fixed this, I get this error:
http://ix.io/1mS2

**Comment by emersion** [comment]
Can you describe what you do, and what happens?

Do you have a debug log?

```
coredumpctl gdb
bt full
```

**Comment by nycex** [comment]
[This](http://ix.io/1mS2) is the debug log

**Comment by emersion** [comment]
Sorry, I meant stack trace, not debug log. Please answer my other questions.

**Comment by nycex** [comment]
1. I just start sway via commandline on tty1 and it just pops up for about half a second and then crashes
2. [That](http://ix.io/1mS3) is the stacktrace I get when I type what you said, no idea if I did something wrong

**Comment by emersion** [comment]
It seems you're auto-starting Firefox in your config file. What you uploaded is a Firefox stack trace.

Can you try to get a sway stack trace? You should:

* List all available coredumps with `coredumpctl -r`
* Find the latest one from sway. Read its PID.
* Get the stack trace: `coredumpctl gdb <pid>` and then `bt full`

**Comment by nycex** [comment]
There is no stack trace for sway

**Comment by nycex** [comment]
Okay, starting discord appearently also crashes sway, but chromium doesn't

**Comment by SirCmpwn** [comment]
If you have multiple bugs file multiple bug reports.

**Comment by nycex** [comment]
Its actually one bug, I just listed the applications that don't work

**Comment by nycex** [comment]
I meant that bug, but I didn't know why it was crashing and thought it was because of the graphics driver.
But it's

**Comment by ownaginatious** [comment]
>Ok, wait that was an error on my side, but now, that i've fixed this, I get this error:
http://ix.io/1mS2

@nycex I'm experiencing the same thing with 0 GPUs found. Do you happen to remember what the error on your side was?
