### ISSUE TITLE
[Alpha 1.0] Sway crashes with firefox, discord, etc

### ISSUE THREAD

**Issue by nycex** [swaywm/sway#2657]
When I start sway on the new 1.0 Alpha version, it crashes, when I start firefox, steam, discord, and probably with other applications I don't use or didn't try out.
sway version: 1.0-alpha.5-362-g5abf8322 (Sep 17 2018, branch 'master')

**Comment by SirCmpwn** [comment]
Logs?

**Comment by Marteon** [comment]
I narrowed it down.
It does not depend on the programms but on your config.
The `assign [class="Firefox"] workspace` causes the crash.
While testing it on my setup it only crashed with `auto-back-and-forth` enabled but you don't seem to have this in your config.

**Comment by nycex** [comment]
Ehm, I think I tried to removed that and it didn't work

**Comment by nycex** [comment]
Wait a minute I'll just try that out

**Comment by nycex** [comment]
Hm. The problem just dissappeared. But now I have the same problem as in #2658

**Comment by emersion** [comment]
If sway crashes, please provide a sway stack trace (`coredumpctl gdb sway`).

**Comment by emersion** [comment]
Ping
