### ISSUE TITLE
input <id> settings not applied

### ISSUE THREAD

**Issue by petoknm** [swaywm/sway#2661]
I have noticed that a configuration file that was working in the 0.15 branch now doesn't work on the master branch. 

```
input "2:1:PS/2_Synaptics_TouchPad" {
    tap enabled
    natural_scroll enabled
}
```

I have noticed that the ID of the input device changed (from 0.15 branch) and I of course changed it in the config file as well. Even with the correct id (from swaymsg -t get_inputs) the settings for the input don't get applied.

 ```shell
> swaymsg -t get_inputs
Input device: PS/2 Synaptics TouchPad
  Type: Mouse
  Identifier: 2:1:PS/2_Synaptics_TouchPad
  Product ID: 1
  Vendor ID: 2
```

How can I debug this to get more info why it doesn't apply the settings?
Thank you.

**Comment by SirCmpwn** [comment]
https://github.com/SirCmpwn/sway/wiki#how-do-i-report-issues

**Comment by petoknm** [comment]
```
> swaymsg -t get_version
sway version 1.0-alpha.5-364-g15dadaaa (Sep 18 2018, branch 'master')
```
Log:
https://gist.github.com/petoknm/df6c77b91e79f375962af5a838e99262

**Comment by petoknm** [comment]
Seems like `1739:31251:DLL07BE:01_06CB:7A13_Touchpad` is the actual touchpad... In that case its not a bug. I have no idea why I have two touchpads on my XPS15... Thanks
