### ISSUE TITLE
Proposal: configure input devices with *

### ISSUE THREAD

**Issue by emersion** [swaywm/sway#2662]
e.g.

```
input * {
  xkb_variant altgr-intl
}
```

This is especially useful if you routinely plug in random keyboards.

**Comment by ianyfan** [comment]
What about `seat *` as well?

**Comment by emersion** [comment]
Hmm, I've not seen seat commands that would be useful with `seat *`. Did I miss a use-case?

**Comment by ianyfan** [comment]
I don't know tbh, it just seemed like a natural question to ask.

**Comment by jplatte** [comment]
According to `man 5 sway`:

    * may be used in lieu of a specific device name to configure all input devices.

But this might explain why I couldn't set my keyboard layout this way :sweat_smile:
