### ISSUE TITLE
swaybar: failed to parse i3bar json

### ISSUE THREAD

**Issue by cnt0** [swaywm/sway#2664]
I'm using sway with https://github.com/greshake/i3status-rust.
I started seeing this error after upgrading to cdce604d8e166ae905b394306fece4e7f035cedd. The problem arises here: https://github.com/swaywm/sway/blob/3600b3db577298bc553c394a4b09e71163f76561/common/pango.c#L131  
`args` contains not one but multiple outputs of i3status-rust ([example](https://github.com/swaywm/sway/files/2395837/swaybar.txt)) and its length is indeed >= 2048 - is this an expected behavior?

**Comment by ianyfan** [comment]
Can you provide your `i3status-rust` config? The default config works for me.

**Comment by Ogromny** [comment]
Same for me...

**Comment by cnt0** [comment]
Applied this patch, no success. 
[My config](https://github.com/swaywm/sway/files/2397646/i3status_rs_config.txt)
From what I see, `args` should normally contain some separate tokens from swaybar, like ` Wed 19/09 20:13`. In my case everything goes normal and then it tries to process this big raw json (see my attachment in the first post). Looks like some race condition.

**Comment by ianyfan** [comment]
Strange. How reproducible is it? And do you have to wait 5 minutes each time?

**Comment by cnt0** [comment]
looks like https://github.com/swaywm/sway/pull/2672 fixes it
