### ISSUE TITLE
Sway crashes on reattaching external monitors

### ISSUE THREAD

**Issue by JonnyMako** [swaywm/sway#2675]
I suspect this may have something to do with programs running under XWayland, but sometimes when I reattach my external monitors, sway crashes. (log attached)
[swaycrash.log](https://github.com/swaywm/sway/files/2398068/swaycrash.log)

**Comment by JonnyMako** [comment]
> Please include the stack trace.
> 

Attached.
[sway-gdb-bt.log](https://github.com/swaywm/sway/files/2398158/sway-gdb-bt.log)

**Comment by emersion** [comment]
Duplicate of https://github.com/swaywm/sway/issues/2648
