### ISSUE TITLE
Drag and drop is broken

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/sway#2682]
I cannot drag anything between two weston-dnd windows.

**Comment by RyanDwyer** [comment]
Works fine for me.

**Comment by emersion** [comment]
I can reproduce.

**Comment by RyanDwyer** [comment]
Is there anything special you need to do to reproduce this? I have tried:

* Dragging from tiling to tiling, floating to floating, tiling to floating and floating to tiling
* Wayland backend and DRM backend
* Default config
* `focus_follows_mouse` enabled and disabled

I can't fault it.

**Comment by SirCmpwn** [comment]
Seems like weston-dnd works for me now, but nautilus doesn't.

**Comment by SirCmpwn** [comment]
Now it works. ¯\\\_(ツ)_/¯
