### ISSUE TITLE
swaybar: simultaneous events may cause it to run out of buffers and not render new status

### ISSUE THREAD

**Issue by ianyfan** [swaywm/sway#2692]
Suppose your status command sends a status upon workspace change.

Then you switch to a new workspace.

Then you get events: workspace::new, workspace::focus, status command.

Each event triggers a render, using a buffer and is committed. But there are only two buffers, so the status command event does not get a buffer, and is therefore not rendered.

Introduced by 8a5ff5a4dbcefabaaeae98c1c53befcb986ba117 since it removes the `wl_display_roundtrip`s.

**Comment by emersion** [comment]
The fix is to listen to frame events on the surface to prevent rendering more buffers than necessary.
