### ISSUE TITLE
How to change keys like xmodmap?

### ISSUE THREAD

**Issue by JackalopeGit** [swaywm/sway#2707]
I have an useless keyboard button (has '<' and '>') on my laptop and I want to set ISO_Next_Group to it.
setxkbmap is very bumsy with limit to 'grp' names.
I like to see it like this: "XKB_MAP = .Xmodmap".

**Comment by ianyfan** [comment]
When https://github.com/swaywm/sway/issues/1779 is added you might be able to do something like `bindsym <useless key> ... keyboard type <useful key>`

**Comment by emersion** [comment]
It's not yet implemented.
