### ISSUE TITLE
Cant run firefox and chromium

### ISSUE THREAD

**Issue by RorraVox** [swaywm/sway#2711]
Cant run firefox and chromium on ArchLinux
error:
Firefox:
Error: cannot open display :0
Chromium:
Gtk-WARNING **: cannot open display :0
Never done before.
I can on gnome.

**Comment by Marteon** [comment]
What os do you run? What sway version are you using?

**Comment by RorraVox** [comment]
ver: 0.15.2
os: ArchLinux(Antergos)
