### ISSUE TITLE
add tap-and-drag to sway-input

### ISSUE THREAD

**Issue by PumbaPe** [swaywm/sway#2721]
I would like to be able to disable tap-and-drag in sway-input since it's enabled by default and it's very annoying. Knowing next to nothing about programming, I tried to implement it myself by basically copying and modifying every instance of drag_lock (after all the corresponding libinput function is just `libinput_device_config_tap_set_drag_enabled()` instead of `libinput_device_config_tap_set_drag_lock_enabled()`) and everything compiled fine, but the command was not recognized and additionally it broke some other input commands.
I'm guessing it would be a very easy thing to implement for someone who knows how this works, so could someone be so kind and take a try at this?

**Comment by SirCmpwn** [comment]
Can you open a pull request with your broken work?

**Comment by PumbaPe** [comment]
I must have missed something the first time around, after forking and cloning properly and redoing the additions it actually works! Here is the pull request: #2725
