### ISSUE TITLE
Typing in IntelliJ, finishing a token causes input to stall

### ISSUE THREAD

**Issue by Hello71** [swaywm/sway#2731]
steps to reproduce:

1. open a Java class
2. enter some code (e.g. Hello World) using keyboard

expected results:

the code is input.

actual results:

after every auto-completable token (with default settings: "class", "Hello", "void", "main") the keyboard input stops responding (in the application). clicking inside the input window allows text to be input again.

additional information:

sway a5317166, wlroots 0347d542, idea ultimate 2018.2.3.182.4323.46. on 2017.3.1.173.3942.27, the input text is instead buffered until clicking in the input window, upon which the buffered input is immediately inserted at the new cursor location.

**Comment by Hello71** [comment]
you know what, this is too much work, I'll just use xephyr or xpra or something

**Comment by Ogromny** [comment]
I have the same exact bug on sway 1.2
