### ISSUE TITLE
Swaylock (sometimes, seemingly) does not accept correct password

### ISSUE THREAD

**Issue by colemickens** [swaywm/sway#2743]
Most of the time, when this happens, it occurs at the same time as: https://github.com/swaywm/sway/issues/2706... however...

To address that issue, I had actually removed `swayidle`'s ability to do any DPMS, it should've only been invoking `swaylock`. Today I went to grab some coffee, came back, and `swaylock` had activated. While I was able to type normally, it was very clearly not accepting my valid password. (I checked caps lock, there's nothing else that should've been interfering).

(I mitigated by switching to another TTY and issuing `pkill swaylock`.)

Please note, I'm using a pre-release 1.0 build using HEAD of sway/wlroots from about 12 hours ago.

I'm mostly trying to figure out how I can give additional debug data. Should I patch `swaylock` and have it log keystrokes to try and see what's going on?

**Comment by martinetd** [comment]
Ah, sorry I had misunderstood your first message. If you have nothing that would make logind take input devices off I'm not sure what it would be, feel free to have a look at logs with `WAYLAND_DEBUG=1` to confirm if you have the same problem (you should see multiple `wl_seat@*.get_keyboard()` and then `wl_keyboard@*.key` will be printed for each of the new keyboards)

**Comment by colemickens** [comment]
It repro'd again, but I didn't have debug enabled. I did get a video though: https://photos.app.goo.gl/mxRM2TiHjUgVm8ZP9 

13s - 22s demonstrates the problem I've described. Input slows, and then circle interior flashes red very quickly as if it's validating and rejecting the password after each keystroke. As you can see, in this instance, it was only doing it part of the time, you can see after 23s that it seems to go back to taking the keystrokes normally.

**Comment by DawidLoubser** [comment]
Can confirm, this has been driving me crazy over the past week. It recently started happening.
I have, in my `.config/sway/config`:

```
exec swayidle before-sleep 'swaylock -c 102020 -i /some/picture.jpg'
```

**Comment by SirCmpwn** [comment]
This hasn't always been broken, right? How about a bisect?

**Comment by RyanDwyer** [comment]
@colemickens @DawidLoubser Can you please check if #2771 resolve this?

**Comment by colemickens** [comment]
I've updated to `5d21c33f13f34ed592388512cc092986324c8f35` and am setting `WAYLAND_DEBUG` now. I'll update if I see it again.

**Comment by martinetd** [comment]
Please note that you're literally writing your password one letter at a time to wherever you log swaylock's output, so we cannot recommend to leave WAYLAND_DEBUG set for normal use - remember to purge old logs when you're confident this works

**Comment by RyanDwyer** [comment]
Closing this as it was likely fixed by the PR mentioned a few comments back. If it occurs again then please create a new issue.
