### ISSUE TITLE
Difficulty opening sway with AMD GPU

### ISSUE THREAD

**Issue by ndrewtl** [swaywm/sway#2744]
Hi! First of all thank you so much for writing sway. It's a wonderful project and I'm incredibly grateful.

I've been having issues running sway 0.15.2 on a new AMD GPU, using the `amdgpu` driver. I've gotten sway to work with the graphics card physically removed from the PC, but when I plug my HDMI cord into the GPU, I get this error message:
```
user@hostname $ sway
10/01/18 13:52:36 - [main.c:48] [wlc] Failed to activate vt1 for restoration
10/01/18 13:52:36 - [main.c:48] [wlc] Failed to switch back to vt1
10/01/18 13:52:36 - [main.c:67] swaybg requires the compositor to support the desktop-shell extension.
```

On subsequent invocations of sway, the error message doesn't show at all, and the program appears to exit successfully:
``` 
user@hostname $ sway
user@hostname $ echo $?
0
```
In order to make sure the problem was unique to sway, I tried and succeeded to get both XMonad and Wayland GNOME working correctly.

I've checked out the driver situation, and things seem to be working fine:
```
user@hostname $ lspci
...
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/570/570X/580/580X] (rev e7)
01:00.1 Audio Device: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 580]
...
```
```
user@hostname $ dmesg | grep amd
[    0.000000] Command line: BOOT_IMAGE=/vmlinuz-linux root=UUID=XXXXX... rw quiet amdgpu.dc=1
[    0.000000] Kernel command line: BOOT_IMAGE=/vmlinuz-linux root=UUID=XXXXX... rw quiet amdgpu.dc=1
[    0.958923] [drm] amdgpu kernel modesetting enabled.
[    0.959484] fb: switching to amdgpudrmfb from VESA VGA
[    0.959957] amdgpu 0000:01:00.0: Invalid PCI ROM header signature: expecting 0xaa55, got 0xffff
[    0.960027] amdgpu 0000:01:00.0: VRAM: 8192M 0x000000F400000000 - 0x000000F5FFFFFFF (8192M used)
[    0.960028] amdgpu 0000:01:00.0: GTT: 256M 0x0000000000000000 - 0x000000000FFFFFFF
[    0.960242] [drm] amdgpu: 8192M of VRAM memory ready
[    0.960242] [drm] amdgpu: 8192M of GTT memory ready
[    1.210972] fbcon: amdgpudrmfb (fb0) is primary device
[    1.248108] amdgpu 0000:01:00.0: fb0: amdgpudrmfb frame buffer device
[    1.287158] [drm] Initialized amdgpu 3.26.0 20150101 for 0000:01:00.0 on minor 0
````
The only thing amiss appears to be the 'Invalid PCI ROM header signature' warning, and to my eyes so far, this appears to be [relatively innocuous](https://www.phoronix.com/forums/forum/linux-graphics-x-org-drivers/open-source-amd-linux/45819-radeon-0000-01-00-0-invalid-rom-contents).

For the sake of my hands (I've copying these logs out manually from another computer) I won't type out the full verbose sway trace, as almost everything seems to be in order. `sway -V` displayed no error messages, but didn't launch the display either. For all intents and purposes, it seemed to print environment variables, verbosely load the config, and then exit. The only line of note was the following:
```
user@hostname $ sway -V
...
10/01/18 14:28:05 - [main.c:50] [wlc] Failed to open X11 display
...
```

Weirdly enough, under my (Wayland) GNOME instance, sway seems to open fine.

I'm hoping I can find some answers here. Does anyone know what's going on? Thanks again for developing this project and cheers to you all.

**Comment by RyanDwyer** [comment]
This is fixed in the 1.0 alpha. By the way, we're not currently fixing issues in sway 0.15. I appreciate the fact that you typed your log messages by hand, though :)
