### ISSUE TITLE
swaybar: trailing comma causing invalid JSON in i3bar implementation

### ISSUE THREAD

**Issue by simonics** [swaywm/sway#2747]
Recently, PR https://github.com/swaywm/sway/pull/1441 was effectively reverted by https://github.com/swaywm/sway/commit/87c93d6ad986faa384f1279e21c10e35c798686a

This breaks click events for the particular [i3bar implementation](https://github.com/enkore/i3pystatus) that I'm using, and possibly others that feed the input straight into strict JSON parsers. I've patched the comma out in my build, and have confirmed that i3bar click events are functional again.

Is there any particular reason for the trailing comma to be present?

**Comment by ianyfan** [comment]
Can this be fixed by sending a leading comma instead? (except for the first item obviously)

**Comment by simonics** [comment]
A quick patch would suggest that a leading comma is functional with my particular i3bar implementation, regardless of whether the first item has a leading comma. Removing the comma on the first output has no discernable effect.

My assumption is that [a leading comma removal](https://github.com/enkore/i3pystatus/blob/master/i3pystatus/core/io.py#L197-L199) in the implementation I'm using has a lot to do with this. I'm not sure whether other implementations have something similar, or whether i3 spits out leading commas.

```
diff --git a/swaybar/i3bar.c b/swaybar/i3bar.c
index 8e9b038b..7caabff2 100644
--- a/swaybar/i3bar.c
+++ b/swaybar/i3bar.c
@@ -276,7 +276,7 @@ enum hotspot_event_handling i3bar_block_send_click(struct status_line *status,
 	json_object_object_add(event_json, "button", json_object_new_int(button));
 	json_object_object_add(event_json, "x", json_object_new_int(x));
 	json_object_object_add(event_json, "y", json_object_new_int(y));
-	if (dprintf(status->write_fd, "%s,\n",
+	if (dprintf(status->write_fd, ",%s\n",
 				json_object_to_json_string(event_json)) < 0) {
 		status_error(status, "[failed to write click event]");
 	}
```

**Comment by ianyfan** [comment]
Then honestly, your implementation isn't properly parsing JSON, it's parsing lines of JSON arrays with optional leading commas, which may happen to be valid JSON.

**Comment by simonics** [comment]
I would agree, the implementation could (and perhaps should) be validating more stringently. Thanks for the fix, appreciate it! I'll read up on the code style and submit my own pull request next time.
