### ISSUE TITLE
sway wasting significant CPU on clients that don't refresh often

### ISSUE THREAD

**Issue by atomnuker** [swaywm/sway#2748]
To reproduce: play any audio file with embedded artwork in mpv with the wayland backend
Result: sway wastes 60% CPU while mpv wastes 10% more than it needs to

What happens is that with embedded artwork, mpv doesn't have anything to draw hence reschedules the frame callback to the next opportunity using wl_surface_commit() without damaging anything.
sway seems to do a lot of spinlocking and locking in general as seen on perf. At least it doesn't damage the whole surface.

**Comment by RyanDwyer** [comment]
What perf arguments are you using?

**Comment by atomnuker** [comment]
Just perf top, but mostly looked at htop.
The PR as-is does fix the issue, now mpv spends as much time as it needs to decode the audio and sway's CPU use is the same as in idle with just htop open (0.0% - 1.3%).
