### ISSUE TITLE
Update wiki for 1.0

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/sway#2750]
We need to do this before we ship the release.

**Comment by SirCmpwn** [comment]
I have written the updates, will push them once we release.

**Comment by Fallstar** [comment]
Hi,
On https://github.com/swaywm/sway/wiki#window-rules-to-adjust-sways-borders the example is `for_window [id="nautilus"] border none`, whereas the `id` must be numeric.

**Comment by emersion** [comment]
Can you edit the wiki? I think it means to say `app-id`instead of `id`.

**Comment by ggreer** [comment]
I think the correct field is "app_id", not "app-id". (At least, that's what works for me in master as of 2019-02-12.)
