### ISSUE TITLE
X apps crash Sway

### ISSUE THREAD

**Issue by J0nnyMak0** [swaywm/sway#2758]
opening any app running in xwayland crashes Sway. Log attached.
[sway.log](https://github.com/swaywm/sway/files/2442816/sway.log)

**Comment by emersion** [comment]
Hmm, maybe related to the new SSD code.

Can you attach a stack trace too? (`coredumpctl gdb sway` and then `bt full`)

**Comment by Dudemanguy911** [comment]
It's #2703. Some applications can trigger CSD and subsequently crash. I've only been able to trigger this with Pale Moon though (e.g. urxvt and pcmanfm work fine).

There was a couple of things that I noticed. In xwayland.c:
```
static void handle_set_decorations(struct wl_listener *listener, void *data) {
	struct sway_xwayland_view *xwayland_view =
		wl_container_of(listener, xwayland_view, set_decorations);
	struct sway_view *view = &xwayland_view->view;
	struct wlr_xwayland_surface *xsurface = view->wlr_xwayland_surface;

	bool csd = xsurface->decorations != WLR_XWAYLAND_SURFACE_DECORATIONS_ALL;
	view_update_csd_from_client(view, csd);
}
```
`WLR_XWAYLAND_SURFACE_DECORATIONS_ALL`` can sometimes 0 which sets the bool to 1 and executes.

And then ``view_update_csd_from_client`` in view.c
```
void view_update_csd_from_client(struct sway_view *view, bool enabled) {
	wlr_log(WLR_DEBUG, "View %p updated CSD to %i", view, enabled);
	if (enabled && view->border != B_CSD) {
		view->saved_border = view->border;
		if (container_is_floating(view->container)) {
			view->border = B_CSD;
		}
	} else if (!enabled && view->border == B_CSD) {
		view->border = view->saved_border;
	}
	view->using_csd = enabled;
}
```
In my case, Pale Moon triggers `container_is_floating` and then crashes while setting view->border = B_CSD.

**Comment by JonnyMako** [comment]
> Hmm, maybe related to the new SSD code.
> 
> Can you attach a stack trace too? (`coredumpctl gdb sway` and then `bt full`)

Attached. Although it looks like its notify-osd that is triggering the crash...
[gdb.txt](https://github.com/swaywm/sway/files/2442966/gdb.txt)

**Comment by emersion** [comment]
It's not the right stack trace, you probably have multiple. You can list them with `coredumpctl -r` and then run GDB on a specific one with `coredumpctl gdb <pid>`.

**Comment by JonnyMako** [comment]
> It's not the right stack trace, you probably have multiple. You can list them with `coredumpctl -r` and then run GDB on a specific one with `coredumpctl gdb <pid>`.
> 
> Also please run `bt full` in GDB.

Yes, I couldn't find sway in the list there. I attached the latest. I uninstalled notify-osd and now the crash I have /usr/lib/Xorg in coredumpctl list. Would a trace of that be helpful?

**Comment by emersion** [comment]
Eh, not really. Can you try running `sway` in GDB in sway (aka `gdb sway` in a sway session), then make it crash?

**Comment by JonnyMako** [comment]
> Eh, not really. Can you try running `sway` in GDB in sway (aka `gdb sway` in a sway session), then make it crash?

Sorry. I can't get a Sway coredump that way either.

**Comment by ppascher** [comment]
Here is a coredump when "playonlinux" crashes:
```#0  0x0000557ec73d59a6 in container_is_floating (container=0x0) at ../sway/tree/container.c:738
#1  0x0000557ec73d97a9 in view_update_csd_from_client (view=0x557ec839ab30, enabled=true) at ../sway/tree/view.c:344
#2  0x0000557ec73dfa26 in handle_set_decorations (listener=0x557ec839ad90, data=0x557ec839a8e0) at ../sway/desktop/xwayland.c:253
        xwayland_view = 0x557ec839ab30
        view = 0x557ec839ab30
        xsurface = 0x557ec839a8e0
        csd = true
#3  0x00007f64d97fc7f1 in wlr_signal_emit_safe (signal=0x557ec839aad8, data=0x557ec839a8e0) at ../util/signal.c:29
        pos = 0x557ec839ad90
        l = 0x557ec839ad90
        cursor = {link = {prev = 0x557ec839ad90, next = 0x7ffe2f57a670}, notify = 0x7f64d97fc73b <handle_noop>}
        end = {link = {prev = 0x7ffe2f57a650, next = 0x557ec839aad8}, notify = 0x7f64d97fc73b <handle_noop>}
#4  0x00007f64d97ae75c in read_surface_motif_hints (xwm=0x557ec82c9970, xsurface=0x557ec839a8e0, reply=0x557ec838d8c0) at ../xwayland/xwm.c:597
        decorations = 0
        motif_hints = 0x557ec838d8e0
#5  0x00007f64d97aeb46 in read_surface_property (xwm=0x557ec82c9970, xsurface=0x557ec839a8e0, property=253) at ../xwayland/xwm.c:666
        cookie = {sequence = 369}
        reply = 0x557ec838d8c0
#6  0x00007f64d97af5c9 in xwm_handle_property_notify (xwm=0x557ec82c9970, ev=0x557ec83870f0) at ../xwayland/xwm.c:906
        xsurface = 0x557ec839a8e0
#7  0x00007f64d97b00a5 in x11_event_handler (fd=77, mask=1, data=0x557ec82c9970) at ../xwayland/xwm.c:1273
        count = 2
        event = 0x557ec83870f0
        xwm = 0x557ec82c9970
#8  0x00007f64d9839702 in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#9  0x00007f64d98382ac in wl_display_run () at /usr/lib/libwayland-server.so.0
#10 0x0000557ec73a85b5 in server_run (server=0x557ec73feae0 <server>) at ../sway/server.c:174
#11 0x0000557ec73a7cca in main (argc=3, argv=0x7ffe2f57ab58) at ../sway/main.c:384
        verbose = 0
        debug = 1
        validate = 0
        long_options = 
            {{name = 0x557ec73e79a4 "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x557ec73e79a9 "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x557ec73e79b0 "validate", has_arg = 0, flag = 0x0, val = 67}, {name = 0x557ec73e79b9 "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x557ec73e79bf "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x557ec73e79c7 "verbose", has_arg = 0, flag = 0x0, val = 86}, {name = 0x557ec73e79cf "get-socketpath", has_arg = 0, flag = 0x0, val = 112}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        config_path = 0x0
        usage = 0x557ec73e7560 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
        c = -1
```

**Comment by emersion** [comment]
Thanks. Seems like https://github.com/swaywm/sway/pull/2759 is a fix.

**Comment by JonnyMako** [comment]
@emersion I'm still getting crashes. I suspect they are related to this issue. The best way to reproduce is to try and move ($Mod+left click window title and drag) to edge of screen or beyond. I can get the crash consistently as long as there are at least two windows on screen. With multi monitor setup moving windows to an empty screen *sometimes* produces a crash.

I am unable to produce any coredump files on my system, so I'm looking into that. Sorry. I can attach a plan log file if you like.
