### ISSUE TITLE
Crash when moving window out of container

### ISSUE THREAD

**Issue by JonnyMako** [swaywm/sway#2765]
To reproduce:

Create S[viewa, viewb]
Now move viewa or viewb out of the container, to get crash.

Log attached.
[sway.log](https://github.com/swaywm/sway/files/2447889/sway.log)

Edit: Simpler case

**Comment by DawidLoubser** [comment]
Agreed, this started happening for me today also.

**Comment by aereaux** [comment]
Backtrace: [gdb.txt](https://github.com/swaywm/sway/files/2448624/gdb.txt)
