### ISSUE TITLE
eglCreateContext fails with radeon driver

### ISSUE THREAD

**Issue by DawidLoubser** [swaywm/sway#2766]
This might be a bit crazy, but I compiled sway + wlroots for 32-bit i686 - I really want to run it on an old laptop that I have lying around.

Upon launch, I get:

```
[sway/sway/server.c:40] Unable to create backendeviceerererer
```

Is it futile to try and run sway on i686? Any theories? This is on a laptop from 2004 with ATI Radeon Mobility M6 LY video card.

wlroots built just fine.

**Comment by SirCmpwn** [comment]
Do you have any more logs to share?

**Comment by emersion** [comment]
It seems you're not redirecting the logs to a file. Please use:

```
sway -d >sway.log 2>&1
```

**Comment by DawidLoubser** [comment]
[sway.log](https://github.com/swaywm/sway/files/2452107/sway.log)

Ah, I've been wondering how to run sway with logging! Thanks. Log attached. 
It would make my day to get sway running on this golden oldie. Sway seems to be so resource-efficient, it's perfect for an almost 20-year-old machine.

Hope you can help! With regards to building via Arch Linux AUR, this was my process:

* I manually installed `meson` 0.48 via pip - 32-bit AUR doesn't have it.
* I installed `wlroots-git` from AUR, after changing `arch` to `i686` and removing `meson` build dep.
* I installed `sway-latest-git` from AUR, after changing `arch` to `i686` and removing `meson` build dep.

Everything compiled fine, but fails to load as per attached `sway.log`.

**Comment by emersion** [comment]
Hmm, so:

* You don't have a cursor plane (but I think we fake it in this case)
* `eglCreateContext` fails

Have you tried Weston or kmscube?

**Comment by SirCmpwn** [comment]
I think i686 is a red herring. This is more likely to be the culprit:

>Initializing DRM backend for /dev/dri/card0 (radeon)

The radeon driver is old and unmaintained, I'm not sure it's going to have all of the features we need. Does AMDGPU work with your card?

**Comment by emersion** [comment]
It seems we can't find any appropriate EGL config. It would help to list all available EGL configs. Not sure there's a tool to do so.

**Comment by DawidLoubser** [comment]
> I think i686 is a red herring. This is more likely to be the culprit:
> 
> > Initializing DRM backend for /dev/dri/card0 (radeon)
> 
> The radeon driver is old and unmaintained, I'm not sure it's going to have all of the features we need. Does AMDGPU work with your card?

Afraid it does not. 
@emersion might be onto something - is there any way which I can find out which EGL configs *are* available?

I started this little experiment with my doubts about sway running on this old hardware - but if there is a way to get it to work, it would be really sweet :-)

**Comment by SirCmpwn** [comment]
`glxinfo`

**Comment by SirCmpwn** [comment]
We need eglGetPlatformDisplayEXT and eglCreatePlatformWindowSurfaceEXT

**Comment by DawidLoubser** [comment]
Hmm, nothing about those print out:

```
$ glxinfo | grep -i egl
    GL_NV_texgen_reflection, GL_NV_texture_rectangle, GL_OES_EGL_image, 

```

I'm thinking I'm out of luck with `sway` + `ati radeon`

**Comment by emersion** [comment]
Can you print the whole output of `glxinfo`?

**Comment by DawidLoubser** [comment]
> Can you print the whole output of `glxinfo`?

Sure! Here you go: [glxinfo.txt](https://github.com/swaywm/sway/files/2453281/glxinfo.txt)

**Comment by emersion** [comment]
Closing because this isn't a Sway issue (Weston also fails to run).
