### ISSUE TITLE
Firefox 'Restore Previous Session' causes it to load behind sway's titlebar

### ISSUE THREAD

**Issue by Ranguvar** [swaywm/sway#2767]
Firefox opens normally, but pressing Resume Previous Session causes it to reload with the tab bar obscured by sway's titlebar.

**Comment by DawidLoubser** [comment]
I've noticed this as well. If I take Firefox to fullscreen and back (Meta + F) then it sits normally.

**Comment by RyanDwyer** [comment]
Which version of sway? Please run `swaymsg -v`.

**Comment by Ranguvar** [comment]
sway version 1.0-alpha.6-147-gc1f09939 (Oct  5 2018, branch 'makepkg')

**Comment by DawidLoubser** [comment]
`sway version 1.0-alpha.6-145-gc8d1f376 (Oct  4 2018, branch 'master')`

**Comment by Ranguvar** [comment]
Happens with i3 also. Likely Firefox bug.

**Comment by emersion** [comment]
>Happens with i3 also

If it happens on i3 as well, we can't really do anything about it
