### ISSUE TITLE
RFE: transparency of inactive windows

### ISSUE THREAD

**Issue by Hi-Angel** [swaywm/sway#2787]
As the title says.

I'm open to work on this in my spare time *(I don't have much, so don't expect it got get ready quickly, but I'm interested in that work)*, and here's the report to make sure nobody is against implementing that.

[There's a demand](https://github.com/swaywm/sway/issues/2#issuecomment-248215403), and even though there're more important issues, but it's my personal show-stopper for migrating from i3+Compton over to Sway.

I'm new to Sway codebase, and would be glad if someone outlined the steps needed to implement this.

**Comment by SirCmpwn** [comment]
You could accomplish this with a little Python script that connects to IPC and issues `opacity` commands as focus changes.

**Comment by Hi-Angel** [comment]
Oh, that's interesting, thanks, I'll look at that.

**Comment by johnae** [comment]
@SirCmpwn Is that actually possible with the implementation of opacity as it is today? Afaik you can only ever issue opacity commands for the currently focused window. So you could set the opacity to something when the window gets focus and that's all. It doesn't seem possible to set the opacity to something else when the window looses focus.

**Comment by emersion** [comment]
You can use criteria to apply opacity to other windows.

**Comment by Hi-Angel** [comment]
So, for the most part I've figured how to do it *(I'll document it when it's complete, but basically one have to use `i3ipc-python` library, which needs to be modified to search for sway instead of i3; and then bind a small function to focus event to traverse windows in search for unfocused ones)*. One thing I don't see is: how to apply opacity command to a particular window? Looking at `opacity.c` it takes just a single argument, the opacity value.

**Comment by SirCmpwn** [comment]
Use criteria.

**Comment by emersion** [comment]
Use criteria.

**Comment by Hi-Angel** [comment]
But which criteria do I have to use? There doesn't seem to be "focused" criteria — do I need to extract window id in python script, and then issue a command for that id? Is that id unique?

**Comment by ianyfan** [comment]
You can use `[con_id=__focused__]`

**Comment by Hi-Angel** [comment]
Thank you all!

So, in short, the steps are:

1. Install via package manager or pip the [i3ipc-python](https://github.com/acrisci/i3ipc-python) library.
2. Find in the file `i3ipc.py`of its installation the line:
	```python
	['i3', '--get-socketpath'],
	```

	and replace with 
	```python
	['sway', '--get-socketpath'],
	```
3. run the following script:
	```python
	import i3ipc

	ipc = i3ipc.Connection()

	def on_window_focus(ipc, e):
		for c in ipc.get_tree():
			if c.focused:
				c.command('opacity 1')
			else:
				c.command('opacity 0.8')

	ipc.on("window::focus", on_window_focus)
	ipc.main() # enter command loop
	```

gotchas:
* `--get-socketpath` of sway only works within its session, so be sure to execute it from there.

-------

I'll make a PR to have it in Sway documentation, but I'll probably get to that around next weekend.

**Comment by Hi-Angel** [comment]
Good point, will do.

**Comment by SirCmpwn** [comment]
I use i3ipc-python on sway without any patches...

**Comment by Hi-Angel** [comment]
> I use i3ipc-python on sway without any patches...

Oh, it's probably because sway sets `SWAYSOCK` variable, which is respected by `i3ipc-python`. Granted, I didn't check it because the analogous `I3SOCK` is never set by i3 themselves, and I thought it works the same for sway. Oh, well.

**Comment by Hi-Angel** [comment]
As changing wiki does not require PRs, I'm posting a text here, and if nobody has any objections I'm planning to add it somewhere around tomorrow.

As ATM there's just one effect, I'd create a new page **Transparency** with following content:

-----

On X11, transparency of inactive windows required a compositor, like `compton`, `compmgr`, etc. Since on Wayland sway is the compositor, it's implemented here.

Inactive windows can be made transparent by binding `opacity α` commands to `focus` events, where `α` is the opacity value. This can be accomplished with a simple script. An example with python:

1. Install from a system package manager or `pip` a python library to talk to sway through i3 ipc protocol, [i3ipc](https://github.com/acrisci/i3ipc-python).
2. Save the following as `inactive-windows-transparency.py`:
	```python
	import i3ipc

	ipc = i3ipc.Connection()
	prev_focused = None

	for window in ipc.get_tree():
		if window.focused:
			prev_focused = window
		else:
			window.command('opacity 0.8')

	def on_window_focus(ipc, focused):
		global prev_focused
		if focused.container.id != prev_focused.id: # https://github.com/swaywm/sway/issues/2859
			focused.container.command('opacity 1')
			prev_focused.command('opacity 0.8')
			prev_focused = focused.container

	ipc.on("window::focus", on_window_focus)
	ipc.main() # enter command loop
	```
3. Add to autostart `exec --no-startup-id python ~/Path-to-script/inactive-window-transparency.py`

**Comment by SirCmpwn** [comment]
Can you make a pull request adding something to `contrib/` instead?

**Comment by Hi-Angel** [comment]
Sure, will do. I was thinking too that it would be nice to have such scripts somewhere in source repo, so people could fix bugs in them if they found something. Not to say they can't do it in wiki, just git-repository has a better interface for it.
