### ISSUE TITLE
swaylock: capslock indicator is unhelpful

### ISSUE THREAD

**Issue by colemickens** [swaywm/sway#2788]
"My friend" types his password with the Caps Lock activated. When he locks his screen and hits 'Caps Lock', the 'Caps Lock' text shows up.

Unfortunately, this text appears in the same way, with the same duration, regardless of if it is being enabled or disabled. Meaning that the user doesn't know if the next keystroke will be capitalized or not, until they've already hit the key and then see if it still says Caps Lock (meaning it was just enabled), or if the text has gone away (because it was just disabled).

I propose one of the following:
* be more explicit -- "Caps Lock ON" that persists, with "Caps Lock OFF" that displays when disabling, until next key press. Probably the smallest UX change, but I guess it leaks a tiny bit extra additional information to any potential shoulder-surfers
* allow users, such as my friend, to disable the Caps Lock text indicator, and instead do something like `--indicator-ring-caps-lock` to be able to change the ring color to indicate that Caps lock is or isn't enabled (this is more a feature request, I guess, though...)

**Comment by SirCmpwn** [comment]
How about both?

**Comment by colemickens** [comment]
Both would be great too.

I tried peeking at the code, I see [the switch statement](https://github.com/swaywm/sway/blob/082488a81c491faa71ddc2c87fe985ef28f5d69d/swaylock/render.c#L96), but it seems like it shouldn't be showing "Caps Lock" when it has just been disabled, unless there is a bug that causes the `xkb->caps_lock` to not be updated ahead of the switch? I also see what looks like code to specifically handle [damaging/redraw when it's toggled](https://github.com/swaywm/sway/blob/1698260533ea71791d07cfc9d0efab08fb893450/swaylock/password.c#L90). I'm probably missing some pertinent details. Please advise if you want help fixing/adding this, or ignore me if you or someone else can handle it.

**Comment by SirCmpwn** [comment]
I don't know the answer to these questions. As the person who most recently looked at this code, I'd wager you as the expert.

**Comment by progandy** [comment]
Out of security considerations, i3lock went for not displaying the modifier status at all before the password entry is complete. The list of enabled modifiers is only displayed when the user is notified about a wrong password. Is that something sway should do as well?

https://github.com/i3/i3lock/pull/5#issuecomment-74132471

**Comment by SirCmpwn** [comment]
Those security considerations are pretty weak but I'm not opposed to the idea
