### ISSUE TITLE
Sway crashes when setting opacity for current window without windows

### ISSUE THREAD

**Issue by johnae** [swaywm/sway#2792]
I found this while I was playing around with an IPC daemon. Can easily be reproduced by just adding this to the config file (assuming no programs are otherwise autostarted I guess):

```
exec swaymsg "opacity 0.75"
```

I guess it tries to set the opacity for something that is null and crashes...

**Comment by johnae** [comment]
In `sway/commands/opacity.c` it doesn't look like it is checking whether `config->handler_context.container` is null though I'm no expert on the codebase at all.

**Comment by emersion** [comment]
Can you open a pull request to fix this?

**Comment by johnae** [comment]
Working on it...

**Comment by johnae** [comment]
Created a pull request. Verified locally that this solves the issue.
