### ISSUE TITLE
Multimonitor broken on Optimus/Prime

### ISSUE THREAD

**Issue by JonnyMako** [swaywm/sway#2800]
2 out of my 4 monitors have a gray background and show no screens after the latest update. And when I try to reload Sway, I get a crash, but this part is already reported as a separate issue. Not sure if they are related. Log attached.
[sway.log](https://github.com/swaywm/sway/files/2456919/sway.log)

**Comment by emersion** [comment]
This part is weird:

```
2018-10-08 11:57:00 - [subprojects/wlroots/backend/drm/legacy.c:21] DP-3: Failed to page flip: No such file or directory
2018-10-08 11:57:00 - [subprojects/wlroots/backend/drm/legacy.c:21] DP-1: Failed to page flip: No such file or directory
```

>2 out of my 4 monitors have a gray background and show no screens after the latest update

What do you mean? Are they turned off? Are they completely gray and frozen?

Can you try rootston (in wlroots) to see if you have the same issue? (And try to open an app -- the background there is gray)

If you can reproduce there, can you use `git bisect` to pin down which specific commit is the culprit?

**Comment by JonnyMako** [comment]
> What do you mean? Are they turned off? Are they completely gray and frozen?
> 

They are turned on, but completely gray (akin to default rootston window, I can see cursor).  I can open a window on one of my other monitors where windows are visible and when I move them to DP-1 or DP-3 the window disappears when it is supposed to be on them, an re-appears on the working monitors.

> Can you try rootston (in wlroots) to see if you have the same issue? (And try to open an app -- the background there is gray)
> 

rootston seems to be working fine.

> If you can reproduce there, can you use `git bisect` to pin down which specific commit is the culprit?

**Comment by DawidLoubser** [comment]
Just came here to post the same thing. Attached another log, if it helps.

[sway-second-screen-not-working.log](https://github.com/swaywm/sway/files/2458160/sway-second-screen-not-working.log)

Behaviour:

1. On startup, both monitors (internal laptop, and external) fire up.
2. Sometimes the external monitor is all grey, sometimes is shows my background image
3. If I switch to external monitor (e.g. workspace 2) and do something like open a terminal, it opens, but does not display at all.
4. If I "move current focused window" to e.g. my laptop monitor, it appears.
5. If I move it back to external monitor, it disappears - external monitor just displays either background, or neutral grey.

Attached logfile was captured while doing some of the above, if that helps.

```
$ swaymsg -v
sway version 1.0-alpha.6-187-ga999269e (Oct  8 2018, branch 'master')
```

**Comment by SirCmpwn** [comment]
We need someone to do a git bisect here.

**Comment by JonnyMako** [comment]
> We need someone to do a git bisect here.

I can do this. However, I don't know how this would work with wlroots and sway being two different repos. Will bisecting sway even guarantee a successful build with the latest wlroots and vice versa? If you or someone else can suggest a way, I'd be happy to help.

**Comment by JonnyMako** [comment]
> It's easier if you can reproduce this on rootston, which is part of the wlroots repository.

@emersion initially suggested that, but the issue is not there on rootston. I can display windows in rootston.

**Comment by JonnyMako** [comment]
I thought I'd also mention this following behavior. With the external monitor seemingly gray, if I transfer a window to it, the window is not displayed. However, now, in this state, if I reload Sway, the wind appears. I can't interact with it, but as long as the wind is "selected" (blindly), if I type something into that window, and then again reload Sway, the text that I typed has in fact been entered into the window. I hope this can give some clues to isolate the issue.

**Comment by JonnyMako** [comment]
So it seems the problem may lie elsewhere. I can't get external monitors to work with even older versions of Sway which I am sure worked before. So the problem is either the new X (1.20) and/or nouveau/intel drivers. I can't seem to find a combination that I'm able to roll back to, to make multimonitor work with Sway. So if nobody else is able to see this problem, I'm guessing they are on older X and/or Nouveau drivers. A final worst possible case is some Nouveau dirver bug which only affects my particular card (Quadro). Either way I'm unable to figure this out. If somebody has suggestions, I can try.

**Comment by JonnyMako** [comment]
In any case the page flip error is coming from line#21 in wlroots/backend/drm/legacy.c
```
	if (drmModePageFlip(drm->fd, crtc->id, fb_id, DRM_MODE_PAGE_FLIP_EVENT, conn)) {
		wlr_log_errno(WLR_ERROR, "%s: Failed to page flip", conn->output.name);
		return false;
	}
```

**Comment by ascent12** [comment]
That code basically calls right into the kernel, so that would be the component that may affect it.
That has nothing to do with X11 or mesa drivers.

**Comment by DawidLoubser** [comment]
This may be obvious, but just to add to the above: On the same machine with the same kernel + drivers, multi-monitor with xrandr in i3 works fine, but not in sway.

_I'm sure that doesn't eliminate either as options for the source of this bug, but just wanted to add that._

**Comment by JonnyMako** [comment]
@ascent12 thanks for the suggestion. I rolled back the kernel (upto 4.17). Still no dice. :disappointed: :

**Comment by Emantor** [comment]
Maybe rolling forward to the latest 4.19-rc8 helps?

**Comment by JonnyMako** [comment]
> Maybe rolling forward to the latest 4.19-rc8 helps?

@Emantor It was fun building the kernel, but unfortunately, did not resolve the problem
```
4.19.0-rc8-mainline #1 SMP PREEMPT Fri Oct 19 15:19:18 CDT 2018 x86_64 GNU/Linux
```

**Comment by JonnyMako** [comment]
So, it occurs to me, xrandr shows DP-1-1 and DP-1-3, but the page-flip error references DP-1 and DP-3. Could this naming mismatch be the issue?

**Comment by SirCmpwn** [comment]
Are you using a DisplayPort hub or daisy chaining?

**Comment by JonnyMako** [comment]
> Are you using a DisplayPort hub or daisy chaining?

Neither. This is a vanilla Optimus laptop.

**Comment by JonnyMako** [comment]
Now I'm convinced this change from DP-3 to DP-1-3 is a recent change that triggered this. The weird thing is I had DP-3 in my sway config and it still activates the correct monitor, so I failed to notice this change. Where is this DP-1-3 naming change coming from?

**Comment by JonnyMako** [comment]
> We use a different naming scheme than Xorg, and just follow the same name that the kernel gives the devices.
> DP-1-3 implies that it's a DisplayPort MST connection.

I see. Ok, then I guess I'm back to square one. I am unable to provide any useful information for you to be able to narrow this down. Let me know if you want me to try something. Otherwise, I'll keep checking back after kernel updates to see if any of them fixes this.

**Comment by DawidLoubser** [comment]
For the record, my sway config does not contain any references or configuration to external displays - I've always just relied on the automatic behaviour when I plug in an external display.
In addition to my Optimus laptop, I'm also running sway on a pure intel laptop. I've been too afraid to upgrade sway because of this issue, but I'll bite the bullet and report back if the issue also happens on it ( and figure out which version to downgrade to again, as I actually use multi-monitor on this laptop with sway all the time, and the per-display scaling etc is glorious. Don't want to lose that like I did on my Optimus laptop.

**Comment by JonnyMako** [comment]
So, just out of curiosity, I disabled hybrid graphics in the BIOS of my laptop, and bingo! all four monitors sprung back to life! Even in X11 the ports are numbered as before DP-1 DP-2 DP-3 etc. So, there you are. I still think this is some bug in how muxed outputs handled. I'm just not sure where the bug is. Clearly, Sway was working before with both Intel and Nvidia cards active. Now I have to lose Intel to get Sway working on all monitors. Just wanted to update you guys.

**Comment by JonnyMako** [comment]
And I was able to bisect and find the problem commit:
good:
https://github.com/swaywm/wlroots/commit/24a48d4858a9d5eda0be86e20cbf0d378895063a
bad:
https://github.com/swaywm/wlroots/commit/b7b781ff448675cc8486d7aa8f6d78d1f1e7c727

**Comment by RyanDwyer** [comment]
That bad commit was reverted in the following commit. Are you sure you bisected correctly?

**Comment by JonnyMako** [comment]
@RyanDwyer I apologize. You are right. Something went wrong in my bisect. I believe, this is the bad commit:

https://github.com/swaywm/wlroots/commit/ba9142274765869cd58ec0c55e7ef8da0354ed25

**Comment by JonathanILevi** [comment]
This problem occurs (for me) will any monitors on non-primary graphics cards.  My guess is with the Optimus/Prime that the external displays are powered by the non-primary dedicated graphics.

I have a desktop with **multiple** (three, different, non-sli) graphics cards and only the monitors on the "first" graphics cards are rendering correctly.

Regardless of the version of Sway:
wlroots commit 4e89a2 is the last commit that works.
wlroots commit eb44d1 does not work (this commit reverts 1280b4)
wlroots commit 1280b4 also does not work but eb44d1 reverts it.

The commits that caused the problem are changing what triggers a frame/buffer to render.  It looks like the new logic never finds the non-primary graphics cards worthy of rendering (save when reloading or switching ttys).

I was trying to fix the problem myself but it is over my head (:

I will see about reproducing the issue with Rootston, as was asked.

**Comment by JonnyMako** [comment]
> I will see about reproducing the issue with Rootston, as was asked.

FYI, I already reproduced it with rootston. That is how I was able to bisect wlroots and find the problem commit earlier today...
