### ISSUE TITLE
Floating windows affect gaps

### ISSUE THREAD

**Issue by natesymer** [swaywm/sway#2802]
I have smart gaps and smart borders enabled.

Whenever I open the save dialog in Chrome (cntrl+s), the floating window that appears causes either the inner or outer gaps to not be rendered.

**Comment by natesymer** [comment]
This is to say that one of them is set to 0 for the duration of the floating window being on the screen. After it's gone, things return to normal.

**Comment by SirCmpwn** [comment]
Aren't gaps always not rendered

**Comment by SirCmpwn** [comment]
Heh, okay

**Comment by natesymer** [comment]
Sorry, I'm coding for work too! Otherwise I'd be a lot better about adding details.

Another important tidbit is that whilst the floating window is focused, the gaps are not rendered right. While the floating window doesn't have focus (and a tiled one does), everything is normal.

Open chrome, bring up the save menu (ctrl+s), and then drag your mouse in and out of it. Also, try using the keybindings to change focus to and away from the floating save dialog/menu.
