### ISSUE TITLE
CRTC missing after turning chained DP monitors off & on

### ISSUE THREAD

**Issue by minus7** [swaywm/sway#2822]
- Chain two monitors onto one DP port
- Turn off the first monitor. Both are disconnected now.
- Turn it on again. The screen stay off and you can find this message in the logs `[subprojects/wlroots/backend/drm/drm.c:503] Cannot modeset 'DP-3': no CRTC for this connector` when running `swaymsg output DP-3 dpms on`

**Comment by emersion** [comment]
Can we have logs?

**Comment by minus7** [comment]
[sway.log](https://github.com/swaywm/sway/files/2476873/sway.log)

**Comment by emersion** [comment]
Can you still reproduce?

**Comment by minus7** [comment]
The specific issue is gone, but others have appeared:
- Monitors were previously listed as DP-2 and DP-3, now are DP-4 and DP-5.
- After turning on the monitor again, I have an additional workspace named '2', i.e. I have two workspaces named '2' after turning the first monitor off and on once.
- The chained monitor doesn't turn on itself, only after I press some button on it, but that's probably due to a bit weak signal.

**Comment by Emantor** [comment]
The connector names being different can't be changed and is expected with MST. It's best to use the names as identifiers.

**Comment by minus7** [comment]
That makes sense. Using names works, and also seems to cause issue 2 to disappear.
Re issue 3, the logs show the second monitor is detected immediately with the first one in the chain, and it not turning on on its own doesn't seem to be sway's fault.
