### ISSUE TITLE
In bar hide mode, bar is not shown above fullscreen windows

### ISSUE THREAD

**Issue by aereaux** [swaywm/sway#2832]
With i3, when using `bar mode hide`, the bar is shown on top of fullscreen windows when the modifier key is pressed.  Sway does not show it.

**Comment by ianyfan** [comment]
This would require sway to render top-layer panels above fullscreen containers.

I am not sure which behaviour is intended.

**Comment by SirCmpwn** [comment]
Or we could put swaybar in the overlay layer.
