### ISSUE TITLE
swaylock: Segfault when passing invalid image.

### ISSUE THREAD

**Issue by cedws** [swaywm/sway#2833]
This is a low priority bug and doesn't typically impact users. For stability reasons, the program should exit gracefully and not segfault.

Example 1:
```
$ touch fakeimage
$ swaylock -i fakeimage
10/14/18 22:20:18 - [main.c:321] Failed to load background image: Image file “fakeimage” contains no data
Segmentation fault (core dumped)
```

Example 2:
```
$ swaylock -i /dev/null
10/14/18 22:20:34 - [main.c:321] Failed to load background image: Image file “/dev/null” contains no data
Segmentation fault (core dumped)
```

Example 3:
```
$ swaylock -i /dev/zero
10/14/18 22:20:43 - [main.c:321] Failed to load background image: Couldn’t recognize the image file format for file “/dev/zero”
Segmentation fault (core dumped)
```

**Comment by emersion** [comment]
Could you send a pull request to fix this?

**Comment by c-edw** [comment]
I'll give it a go.

**Comment by RyanDwyer** [comment]
Are you using an older version of swaylock? That error is generated from `background-image.c`, not `main.c` like your log says. Also I can't reproduce it - for me it shows a white screen when the image doesn't exist.

**Comment by emersion** [comment]
Yeah, same for me with e.g. `/dev/null`.
