### ISSUE TITLE
Reliable crash on rearranging windows w/ mouse

### ISSUE THREAD

**Issue by colemickens** [swaywm/sway#2846]
First, I apologize that I can't offer a script to reproduce this. I only know how to do certain things with the mouse.

Note, all of the following are done by dragging the window to the top/bottom 10% of the other panel to rearrange my panels.

Spawn three terminals - A, B, C. They should appear as three columns.

```
  |     |  
  |     |  
A |  B  |  C
  |     |  
  |     |
```

Then move C to stack on B:

```
  |    
  |  C
A |------ 
  |  B
  |   
```

Then move C to stack on A:

```
   |    
 C |
---|  B 
 A | 
   |
```

Then move B to the bottom of the first column (**thereby empying the second column** maybe relevant?):

```
 C     
---
 A 
---
 B   
```

Crashes here....

**Comment by colemickens** [comment]
This is HEAD of wlroots/sway at this time:
* sway: `cd02d60a992ee38689a0d17fc69c4e2b1956f266`
* wlroots: `8beeb88309d87474e1b4e8eadcf245a24f04b2d0`

**Comment by SirCmpwn** [comment]
When you say "move" do you mean "drag and drop"? Can you describe this in terms of discrete, details steps we can do to reproduce? Steps like, "drag window C onto the far left drop area of window B". Windows have 9 drop areas, center, left, right, upper, lower, and far left, far right, far upper, far lower. Only two of the "far" areas will be valid, depending on the layout of the parent container (for splitv the far upper and far lower areas are valid). Can you describe your issue in these terms?

Also, if it's a crash, please obtain a core dump and give us the output of `bt full` from gdb.

**Comment by colemickens** [comment]
Sorry, I tried to edit and add a bit of that earlier - it is indeed a series of drag and drop events.

I'm not sure I understand the difference between "upper" and "far upper" in the context of a window. The only thing I can guess is that "upper" is the top part of the window and "far upper" is the slice along the edges of a bigger container or the workspace?

Given my confusion, a video might be better: https://photos.app.goo.gl/GHyMv3DySmX5dxxv7 

Let me also try to be more precise:

1. Open three terminals, such that they're each in a column.
2. Drag 'C' to the (far?) upper drop area of window 'B'. (eliminating the third column)
3. Drag 'C' to the (far?) upper drop area of window 'A'. (causing the second column to become a vertically split container)
4. Drag 'B' to the (far?) lower drop area of window 'A'. (eliminating the second column [and container])

(The parenthetical bits are just my observations/guesses at what is going on.)



Unfortunately, I can't figure out how to get a core dump or backtrace given that `sway` suspends and I can't even change TTY. I don't have a second machine to SSH and I can't figure out how to send keystrokes to a nested instance.

**Comment by c-edw** [comment]
There's no coredump for me. It does segfault but the latest entry in `coredumpctl` was yesterday (bearing in mind I just triggered it).

**Comment by SirCmpwn** [comment]
>Unfortunately, I can't figure out how to get a core dump or backtrace given that sway suspends and I can't even change TTY. I don't have a second machine to SSH and I can't figure out how to send keystrokes to a nested instance.

You probably need to run `sway -c some-other-config` and use a different modifier key (like Alt) there.

**Comment by lephe** [comment]
I can also reproduce this bug, and I got a coredump (11 seconds after the crash). Here is the output of `bt full` from gdb:

[sway-2846-backtrace.txt](https://github.com/swaywm/sway/files/2492265/sway-2846-backtrace.txt)

**Comment by RyanDwyer** [comment]
@lephe Can you reproduce it on the latest master? If so, please provide a new backtrace.

**Comment by lephe** [comment]
Sure. I had a bit of a hard time because @colemickens' initial arrangement did not work anymore. I had to use another drag-and-drop scheme:

```
  |   |             |                  |               B
  |   |   drag C    |  B   drag B   B  |    drag C ---------
A | B | C   =>   A  +-----   =>   -----+  C   =>       A
  |   |             |  C            A  |           ---------
  |   |             |                  |               C
```

Anyway, here is a backtrace with `wlroots 9e060be` and `sway 0a4735c`: [sway-2846-backtrace-2.txt](https://github.com/swaywm/sway/files/2497361/sway-2846-backtrace-2.txt)
