### ISSUE TITLE
Cursor is huge in Firefox/Thunderbird/gVim with second (HiDPI) screen

### ISSUE THREAD

**Issue by Marteon** [swaywm/sway#2853]
With the following screens configured
```
output DP-1 mode 3840x2160
output eDP-1 mode 1920x1080
```
and
```
$ swaymsg -v
swaymsg version 1.0-alpha.6-276-g113751ea (Oct 16 2018, branch 'master')
```

I get a huge cursor in Firefox and Thunderbird. When e.g. Termite is focused the cursor has it normal size. As soon as the cursor enters Firefox/Thunderbird it becomes huge (About 4 times as large as normal).
When the cursor is still outside of Firefox but Firefox is focused via keybindings the cursor stays normal as long as I don't enter Firefox.

`$ sway -d`
[sway.log](https://pastebin.com/ZhQeWfMb)

**Comment by SirCmpwn** [comment]
This is probably an Xwayland bug, not a sway bug.

**Comment by RyanDwyer** [comment]
I think you can fix this by putting this in your ~/.Xdefaults file:

    Xcursor.size: 16

**Comment by emersion** [comment]
This would probably be fixed by backporting https://github.com/swaywm/wlroots/pull/1294 to sway

**Comment by SirCmpwn** [comment]
+1

**Comment by emersion** [comment]
https://github.com/swaywm/sway/pull/2868
