### ISSUE TITLE
swaybar/dmenu focuses on wrong monitor

### ISSUE THREAD

**Issue by twoertwein** [swaywm/sway#2856]
When I start sway with two monitors connected, the swaybar/dmenu seems to be always focused on the same monitor. I don't know whether that is an issue with swaybar or dmenu: when I run dmenu, it is always shown on the same monitor even when I'm on a workspace on a different monitor.

In my setup workspaces 1-4 are on the internal laptop monitor and workspace 0 on the external monitor:
```
workspace 1 output eDP-1
workspace 2 output eDP-1
workspace 3 output eDP-1
workspace 4 output eDP-1
workspace 0 output DP-1
```

I use sway-git from Archlinux's AUR (r4986.fa2d2c85).

**Comment by SirCmpwn** [comment]
This is a limitation with Xwayland, not anything we can do about it. Try bemenu instead?

**Comment by twoertwein** [comment]
thanks, I didn't know about that. (It worked on 0.15.2.)
