### ISSUE TITLE
swaylock: Scaling parameter has no effect.

### ISSUE THREAD

**Issue by c-edw** [swaywm/sway#2867]
Passing `-s` or `--scaling` to swaylock appears to have no effect. The input image `-i` is always stretched to fill the screen. I think I recall this working recently, so the bug has probably been introduced within the past few days.

Version:
```
swaylock version 1.0-alpha.6-285-g799f285c (Oct 17 2018, branch 'master')
```

Steps to reproduce:
1. Execute `swaylock -s center -i Sway_Tree.png` (get this image from `assets/`)
2. Observe that the image is stretched to fill the screen and is not centered

**Comment by c-edw** [comment]
I will try to track down the commit that introduced this bug.

**Comment by c-edw** [comment]
I haven't been able to find the cause/commit of this. `git bisect` didn't work out so well because I would have to find the correct version of wlroots for each commit. The only thing I know is that version `swaylock version  (2018-07-26, branch "")` of swaylock works correctly.

**Comment by SirCmpwn** [comment]
There shouldn't be more than, say, 10-15 hops between here and there in a bisect. Even if you have to find the appropriate wlroots version, that doesn't sound too bad? Just `git log --since=[date of sway commit]`

**Comment by c-edw** [comment]
Alright, so it looks like the bug goes all the way back to 0.15.2, or it's on wlroots... not entirely sure. I discovered along the way that 
```
./build/swaylock/swaylock -i ~/Downloads/Sway_Tree.png -s center
``` 
works, but 
```
./build/swaylock/swaylock -s center -i ~/Downloads/Sway_Tree.png
``` 
doesn't.

**Comment by emersion** [comment]
It seems that `-i` resets `state->args.mode`. Can you try to send a patch to fix it?
