### ISSUE TITLE
Window title is cut off at the end with pango fonts

### ISSUE THREAD

**Issue by jplatte** [swaywm/sway#2869]
This happens in particular with my default font, Encode Sans, but it can be reproduced with long titles in other fonts, e.g. Liberation Sans as in the minimal config below. Here's a screenshot:

![screenshot](https://user-images.githubusercontent.com/951129/47139969-6500c000-d2bd-11e8-8d62-b2b8cbd086c3.png)

`sway version 1.0-alpha.6-300-g103b7bc4 (Oct 18 2018, branch 'makepkg')`

Config and log: https://gist.github.com/jplatte/b9556b716d4cc9f30cb9da66035f2f3d

**Comment by RyanDwyer** [comment]
Someone in chat had the same problem, and they bisected it to c495164f6059d8f352afeead86a510365cc802a1 as being the first bad commit. It is suspected that the bug is in Cairo.

**Comment by SirCmpwn** [comment]
I wonder if we can make a minimal reproducable test case to submit a cairo bug with?

**Comment by cyberhuman** [comment]
I have the same issue with `font pango:dejaVu Sans Mono 8`, and it's even more pronounced (even shorter titles are cut off), probably because of monospace font?
