### ISSUE TITLE
In a setup with varying display scales, swaybar adds unnecessary space between bar elements

### ISSUE THREAD

**Issue by jplatte** [swaywm/sway#2873]
This is what my bar usually looks like:

![bar_right](https://user-images.githubusercontent.com/951129/47161083-909d9d80-d2f1-11e8-9fdb-44163deae4d2.png)

And when moving my cursor between outputs, this happens to the bar on the output(s) with a lower scale factor:

![bar_wrong](https://user-images.githubusercontent.com/951129/47161086-92676100-d2f1-11e8-9682-edb67af7e195.png)

It resets itself after a little while.

I will try debugging and fixing this issue myself, so for now have not attached a minimal repro config or log, but will add them if I give up fixing this.

**Comment by SirCmpwn** [comment]
Are you using fractional scaling?
