### ISSUE TITLE
pid->workspace tracking regression

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/sway#2880]
This no longer works at all. Introduced sometime in the past two weeks. Someone on IRC had the same issue.

**Comment by RyanDwyer** [comment]
I can't reproduce. I tried with this config:

    workspace 1 output WL-1
    workspace 2 output WL-1
    workspace 3 output WL-1
    workspace 4 output WL-1
    workspace 5 output WL-1
    workspace 6 output WL-2
    workspace 7 output WL-2
    workspace 8 output WL-2
    workspace 9 output WL-2
    workspace 10 output WL-2
    
    workspace 6
    exec firefox
    workspace 2
    exec terminator
    workspace 5

**Comment by RyanDwyer** [comment]
Never mind. I ran it with the X11 backend and reproduced it.

**Comment by SirCmpwn** [comment]
fwiw I use a script. In my sway config:

`exec startup`

In the startup script:

```
swaymsg workspace 1
swaymsg exec qutebrowser
swaymsg workspace 2
swaymsg exec "urxvt -e mutt"
swaymsg workspace 3
swaymsg exec "urxvt -e weechat"
```

**Comment by ppascher** [comment]
For me the issue is gone when setting "focus_follows_mouse no". So it seems to be a focus rather than an output problem. Possibly related to #2815

**Comment by SirCmpwn** [comment]
I was experiencing #2815 independently of this issue. But they could both be focus related.

**Comment by SirCmpwn** [comment]
Can't reproduce this since some recent sway commit.
