### ISSUE TITLE
Unable to start sway after pull request 2870

### ISSUE THREAD

**Issue by johnae** [swaywm/sway#2891]
Sway exits immediately upon startup after https://github.com/swaywm/sway/pull/2870 with message:

```
2018-10-20 11:36:35 - [swaybg/main.c:228] Unable to connect to the compositor. If your compositor is running, check or set the WAYLAND_DISPLAY environment variable.
```

I've tested several versions of sway before that pull request and all start fine, it's when running commit `75ea19c71b08e4b3dd1ad053944724fd91dc04bd` swaybg claims not being able to connect to compositor.

What more would you like me to do?

**Comment by RyanDwyer** [comment]
It will be resolved when #2890 is merged.
