### ISSUE TITLE
[RFC] Swaybar configures with wrong height

### ISSUE THREAD

**Issue by ianyfan** [swaywm/sway#2892]
If you run swaybar with workspace buttons disabled, and do not send a status, then change an output property, such as scale, then it sets the output dirty, but since there's nothing to render, the bar configures with 0 height, causing it to fill the whole screen.

There is an easy fix: check for `height > 0` in: https://github.com/swaywm/sway/blob/cafb1ff4f78b0f093ab4da987174b92762696366/swaybar/render.c#L522

but I have also been wondering whether to initialise swaybar with a small height of, say, 1, to provide a visual indication to the user that it has started. Currently, it doesn't render anything, which does not signal whether something is wrong until a status is sent correctly for it to render.

Thoughts?

**Comment by SirCmpwn** [comment]
Sure.

**Comment by emersion** [comment]
>but I have also been wondering whether to initialise swaybar with a small height of, say, 1, to provide a visual indication to the user that it has started.

Maybe render an empty bar with a reasonable height? (20px?)

**Comment by SirCmpwn** [comment]
>Maybe render an empty bar with a reasonable height? (20px?)

+1
