### ISSUE TITLE
Log driver info on sway startup

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/sway#2894]
So we can turn nvidia users away without wasting time on troubleshooting :wink:

**Comment by RyanDwyer** [comment]
The Nvidia warning is included in the log but it gets lost in the information. Maybe we could open swaynag instead - but if we do that then we should consider providing a way for the user to say "don't show this again".

**Comment by SirCmpwn** [comment]
Sway probably shouldn't even start up on nvidia. It's just going to break.

**Comment by clarcharr** [comment]
A swaynag notification honestly seems like a much better idea than what was merged. Added more comments in the original PR.

**Comment by ascent12** [comment]
You wouldn't even get as far as being able to see the swaynag notification if you were on Nvidia.
