### ISSUE TITLE
bindsym with multimedia key

### ISSUE THREAD

**Issue by megamann** [swaywm/sway#2897]
Hy.
**bindsym** with multimedia key not work properly.
My config (example one key):
`bindsym XF86HomePage exec apps-1`
`bindsym $mod+XF86HomePage exec apps-2`
`bindsym Mod1+XF86HomePage exec apps-3`
When press first or second or third combination **sway** always runs apps-1

**Comment by SirCmpwn** [comment]
https://github.com/SirCmpwn/sway/wiki#how-do-i-report-issues

**Comment by megamann** [comment]
`sway version 1.0-alpha.6-329-gc75098e9 (Oct 20 2018, branch 'master')`

[log.sway.txt](https://github.com/swaywm/sway/files/2498854/log.sway.txt)

**Comment by adabru** [comment]
I have the same issue with XF86TouchpadOn(keycode 200), XF86TouchpadOff(201), XF86MonBrightnessDown(232), XF86MonBrightnessUp(233), XF86WebCam(220), XF86Launch7(194), etc. but not with XF86AudioRaiseVolume, XF86AudioLowerVolume, XF86AudioNext(171), XF86AudioPlay/XF86AudioPause(172), XF86AudioPrev(173), XF86AudioStop/XF86Eject(174). At least in my case all meida keys above a certain keycode threshold (~194) don't propagate modifiers. In case of e.g. XF86AudioPlay the keysym changes from the shiftkey, though.

@megamann you can try removing all bindsyms from your sway.conf (so they are not absorbed) and running `xev` to see which media keys propagate modifiers and which ones don't. I ended up using the media keys that work with modifiers, violating the function that is printed on them.

I looked a little bit at the `/usr/share/X11/symbols/*` files but couldn't find a clue there (I looked superficially though).

**Comment by stsquad** [comment]
I seem to have a similar problem (sway version 1.0-beta.2) with the XF86AudioPlay not making it to Emacs. Running xev I see it as:

    KeymapNotify event, serial 30, synthetic NO, window 0x0,
    keys:  4294967199 0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
           0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0

I have the raise and lower volume keys captured by sway but other "media" keys do arrive, for example XF86Mail:

    KeyPress event, serial 32, synthetic NO, window 0x1c00001,
    root 0x39f, subw 0x1c00002, time 11035962, (33,43), root:(2584,541),
    state 0x0, keycode 163 (keysym 0x1008ff19, XF86Mail), same_screen YES,
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyRelease event, serial 34, synthetic NO, window 0x1c00001,
    root 0x39f, subw 0x1c00002, time 11036073, (33,43), root:(2584,541),
    state 0x0, keycode 163 (keysym 0x1008ff19, XF86Mail), same_screen YES,
    XLookupString gives 0 bytes:
    XFilterEvent returns: False

**Comment by RedSoxFan** [comment]
Some light on what divides the bindings that work and do not work: https://github.com/swaywm/sway/issues/3540#issuecomment-471174161

There is likely an issue with sharing modifiers across the keyboard devices in a seat.

**Comment by emersion** [comment]
Probably related: https://github.com/swaywm/wlroots/issues/1217

**Comment by unresolvedsymbol** [comment]
I have shift+volume keys and volume keys bound by themselves and that works fine but for some reason it doesn't work on backlight keys...

**Comment by emersion** [comment]
Probably because they come from a different libinput keyboard...

**Comment by YorozuyaDev** [comment]
are you using lightdm? #https://github.com/CanonicalLtd/lightdm/issues/63 I have the same issue with bright keys

**Comment by RedSoxFan** [comment]
@YorozuyaDev, that is unrelated to this issue. That issue is about input devices being missing when using lightdm.

There are no missing input devices for this issue. The issue here is that a physical keyboard is exposed as multiple different input devices (or at least can be -- it's common for laptops). The modifier keys and most `XF86*` keys are not exposed by the same input device. Since modifiers are not shared across input devices (the keymaps may be different), one input device will have an event with only modifiers and another input device will have an event with only a `XF86*` key. This results in bindings for `XF86*` being executed instead of `<modifier>+XF86*`

**Comment by schauveau** [comment]
@YorozuyaDev  To better understand the problem and figure out which keys can or cannot be used with modifiers, I recommend that you try the libinput program (yeah ... the name is strange but that is an actual program that  should be provided by a package such as libinput-tools) to inspect the input events.
For example, as shown below, on my machine the modifiers are handled by the input device event0 (AT Translated Set 2 keyboard) while the brightness keys are handled by event5 (Video Bus).
```
 (shell) sudo libinput debug-events --show-keycodes
...
 event0   KEYBOARD_KEY      +7.28s      KEY_LEFTCTRL (29) pressed
 event0   KEYBOARD_KEY      +7.39s      KEY_LEFTCTRL (29) released
-event5   KEYBOARD_KEY     +10.75s      KEY_BRIGHTNESSUP (225) pressed
 event5   KEYBOARD_KEY     +10.75s      KEY_BRIGHTNESSUP (225) released
```

**Comment by YorozuyaDev** [comment]
ok @RedSoxFan , libinput shows that key_brightnessup is pressed so maybe they use a different libinput keyboard, however with other display manager (GDM, SDDM) bindsyms work fine

**Comment by Emantor** [comment]
swaywm/wlroots#1217

**Comment by emersion** [comment]
Indeed, this is a duplicate.

**Comment by billop** [comment]
https://github.com/swaywm/sway/pull/4373 doesn't fix https://github.com/swaywm/sway/issues/3540 for me on a Thinkpad T480. XF86MonBrightnessUp is on "Video Bus" for me.

**Comment by adabru** [comment]
Hi @billop, for keyboard_grouping I had to make sure that I have the same keyboard layout and repeat info for my keyboard and my Video bus (see `man sway-input` → keyboard_grouping).  i.e. you should use a config like `input type:keyboard { ... }` instead of `input "YOUR_KEYBOARD_ID" { ... }`. Furthermore just reloading the sway config didn't update the grouping for me, I restarted my system and after that it worked.

**Comment by billop** [comment]
Thanks a lot @adabru, putting my keyboard config into `input type:keyboard {...}` fixed https://github.com/swaywm/sway/issues/3540 for me. And now I don't have to copy and paste my remappings for every keyboard I own. Didn't even know that was possible.

**Comment by TheChymera** [comment]
Until recently, [this config](https://chymera.eu/ppb/bd8e50) allowed me to kill windows by pressing <kbd>alt</kbd>+<kbd>xf86search</kbd>. Sadly, this stopped working.

Either `bindsym alt+c kill` or `bindsym xf86search kill`, bot not `bindsym alt+xf86search kill`. I tested it with other keys and it appears that XF86* keys do not accept modifiers. This worked in sway for a few months now, and only stopped working recently (probably a system update). Can you help me out?

**Comment by RedSoxFan** [comment]
@TheChymera 
If you run `sudo libinput debug-events`, does it show the alt key being released right before the XF86* keys are pressed? If so, it is not a sway issue. I'm not sure why that would change unless you are using a different keyboard though.

**Comment by TheChymera** [comment]
@RedSoxFan 

I also thought that's what was happening, but was not aware of how to check. It seems the alt key is only shown as released after I press the search key, so maybe this is something that can be fixed via sway?

```
silenthost ~ # libinput debug-events
-event2   DEVICE_ADDED     Power Button                      seat0 default group1  cap:k
-event3   DEVICE_ADDED     Video Bus                         seat0 default group2  cap:k
-event1   DEVICE_ADDED     Power Button                      seat0 default group3  cap:k
-event0   DEVICE_ADDED     Sleep Button                      seat0 default group4  cap:k
-event13  DEVICE_ADDED     CORSAIR CORSAIR K83 Wireless USB Receiver Keyboard seat0 default group5  cap:k
-event14  DEVICE_ADDED     CORSAIR CORSAIR K83 Wireless USB Receiver Consumer Control seat0 default group5  cap:kp scroll-nat
-event17  DEVICE_ADDED     CORSAIR CORSAIR K83 Wireless USB Receiver Mouse seat0 default group5  cap:p left scroll-nat scroll-button
-event19  DEVICE_ADDED     CORSAIR CORSAIR K83 Wireless USB Receiver Touchpad seat0 default group5  cap:t  size 93x65mm ntouches 1 calib
-event20  DEVICE_ADDED     Logitech USB Receiver             seat0 default group6  cap:k
-event21  DEVICE_ADDED     Logitech USB Receiver Mouse       seat0 default group6  cap:p left scroll-nat scroll-button
-event22  DEVICE_ADDED     Logitech USB Receiver Consumer Control seat0 default group6  cap:kp scroll-nat
-event23  DEVICE_ADDED     Logitech USB Receiver System Control seat0 default group6  cap:k
-event10  DEVICE_ADDED     HDA Intel PCH HDMI/DP,pcm=8       seat0 default group7  cap:
-event11  DEVICE_ADDED     HDA Intel PCH HDMI/DP,pcm=9       seat0 default group7  cap:
-event12  DEVICE_ADDED     HDA Intel PCH HDMI/DP,pcm=10      seat0 default group7  cap:
-event4   DEVICE_ADDED     HDA Intel PCH Front Mic           seat0 default group7  cap:
-event5   DEVICE_ADDED     HDA Intel PCH Rear Mic            seat0 default group7  cap:
-event6   DEVICE_ADDED     HDA Intel PCH Line Out            seat0 default group7  cap:
-event7   DEVICE_ADDED     HDA Intel PCH Front Headphone     seat0 default group7  cap:
-event8   DEVICE_ADDED     HDA Intel PCH HDMI/DP,pcm=3       seat0 default group7  cap:
-event9   DEVICE_ADDED     HDA Intel PCH HDMI/DP,pcm=7       seat0 default group7  cap:
-event13  KEYBOARD_KEY     +1.476s	*** (-1) pressed
-event14  KEYBOARD_KEY     +1.987s	KEY_SEARCH (217) pressed
 event14  KEYBOARD_KEY     +2.117s	KEY_SEARCH (217) released
-event13  KEYBOARD_KEY     +2.171s	*** (-1) released
 event13  KEYBOARD_KEY     +3.701s	*** (-1) pressed
-event14  KEYBOARD_KEY     +3.799s	KEY_SEARCH (217) pressed
 event14  KEYBOARD_KEY     +3.997s	KEY_SEARCH (217) released
-event13  KEYBOARD_KEY     +4.259s	*** (-1) released
 event13  KEYBOARD_KEY     +7.641s	*** (-1) pressed
-event14  KEYBOARD_KEY     +8.216s	KEY_SEARCH (217) pressed
 event14  KEYBOARD_KEY     +8.410s	KEY_SEARCH (217) released
-event13  KEYBOARD_KEY     +8.884s	*** (-1) released
 event13  KEYBOARD_KEY     +14.201s	*** (-1) pressed
c event13  KEYBOARD_KEY     +14.267s	*** (-1) released
 event13  KEYBOARD_KEY     +14.994s	*** (-1) pressed
c event13  KEYBOARD_KEY     +15.098s	*** (-1) released
 event13  KEYBOARD_KEY     +16.885s	*** (-1) pressed
 event13  KEYBOARD_KEY     +17.132s	*** (-1) pressed
```

**Comment by RedSoxFan** [comment]
My next guess would be the custom keyboard layout that you created recently (#4250). Does it work with a non-custom keyboard layout? I'm not sure what adjustments would have to be made if that is the issue though, but it would be a configuration issue.

**Comment by schauveau** [comment]
@TheChymera  I suspect that your problem is caused by the smart  keyboard_grouping feature:

      seat <name> keyboard_grouping none|smart
           Set how the keyboards in the seat are grouped together. Currently, there are two op‐
           tions. none will disable all keyboard grouping. This will make it so each keyboard de‐
           vice has its own isolated state. smart will group the keyboards in the seat by their
           keymap and repeat info. This is useful for when the keyboard appears as multiple sepa‐
           rate input devices.  In this mode, the effective layout is synced between the key‐
           boards in the group. The default is smart. To restore the behavior of older versions
           of sway, use none.

The way I understand that text is that keyboards are only grouped if they are declared with the SAME layout.

For instance, on my laptop, the **alt** key is provided by input **1:1:AT_Translated_Set_2_keyboard** while the **XF86MonBrightnessDown** key is provided by **0:6:Video_Bus**.  

I have the following configuration:

     input "1:1:AT_Translated_Set_2_keyboard" {
       xkb_layout  us 
       xkb_options compose:ralt,shift:both_capslock_cancel
    }

and the binding alt+XF86MonBrightnessDown is not recognized.
However, the same binding works fine if I add a similar configuration for **0:6:Video_Bus**:

     input "0:6:Video_Bus" {
       xkb_layout  us 
       xkb_options compose:ralt,shift:both_capslock_cancel
    }

**Comment by RedSoxFan** [comment]
> @TheChymera I suspect that your problem is caused by the smart keyboard_grouping feature:

Based on the linked config which only has a single `input type:keyboard` block, the only way it would be the keyboard grouping is if it is hitting #5455. It is possible since the Alt and XF86Search keys are on different inputs in that log. The easy test/workaround for that would be to use `input *` instead of `input type:keyboard`.

**Comment by schauveau** [comment]
@RedSoxFan  Indeed! Could that be related to the repeat info mentioned in the text? By the way, where do the default repeat delay and rate come from? Sway, libinput, Linux or the device itself?

**Comment by schauveau** [comment]
I just noticed that in his libinput debug-events dump, the device event14 has cap:kp  so KEYBOARD+POINTER so @RedSoxFan  is probably right

**Comment by RedSoxFan** [comment]
> Could that be related to the repeat info mentioned in the text? 

Nope. They are never set in the linked config so it would be using the default, which would be identical.

> where do the default repeat delay and rate come from?

Sway

https://github.com/swaywm/sway/blob/76adcc3fd3aca74bf45db69d6dbcf3a8443ff159/sway/input/keyboard.c#L958-L965

> I just noticed that in his libinput debug-events dump, the device event14 has cap:kp so KEYBOARD+POINTER

Ya. It's probably hitting #5455. Luckily this case is easy to workaround.

It may have just became visible when that custom layout was added if there wasn't any layout being set prior - or if it was changed from `input *` to `input type:keyboard` in the process.

**Comment by TheChymera** [comment]
@RedSoxFan so how can I fix this in the sway config? I need the custom keyboard, thought, since there are a few characters I had to add.

**Comment by RedSoxFan** [comment]
> so how can I fix this in the sway config?

Use `input *` instead of `input type:keyboard`

**Comment by TheChymera** [comment]
@RedSoxFan thank you :) but it still doesn't work https://chymera.eu/ppb/f98240 Any idea what I'm doing wrong? tried `bindsym alt+XF86Search kill` both with capitalization and without.

**Comment by RedSoxFan** [comment]
> but it still doesn't work ... Any idea what I'm doing wrong? 

If it isn't a grouping issue, then I'd try testing without your custom layout. It's possible that your custom layout needs tweaking, but I'm not sure what changes would be needed.

**Comment by TheChymera** [comment]
@RedSoxFan this also doesn't work :( https://chymera.eu/ppb/d3df2d

**Comment by Isti115** [comment]
I am experiencing issues with this currently as well. In my case it has never worked before, since this is the first time I'm trying to set these more complicated hotkeys up, but based on these issues I was so far only able to figure out that my programmable keyboard is treated as not _one_, not _two_, not even _three_, but **four** different input devices. I haven't managed to activate grouping yet in any way, maybe instead of the "smart" setting a more manual option could be provided, where I can list which devices I'd like to group? Thanks for all your work! :)

**Comment by TheChymera** [comment]
@Isti115 
>  I have kept on experimenting and after changing to `input * { xkb_file ... }` and rebooting, the modified versions of the special keys started working.

I was hoping this would work for me as well (since it only broke after reboot not after update), but it did not :(
What version of sway are you using?

**Comment by RedSoxFan** [comment]
> this also doesn't work

If you provide a debug log, I can confirm the keyboards are being grouping appropriately.

> maybe instead of the "smart" setting a more manual option could be provided, where I can list which devices I'd like to group

Related #5218 and #5213

> In connection with this, I would prefer to have a way to list multiple identifiers, for example separated by commas, so I wouldn't have to have duplicated lines in my config for the multiple devices,

I doubt this feature request would be accepted as it adds complexity to the config/command parsing for minimal gain.

**Comment by Isti115** [comment]
@TheChymera Currently I am on a sway-git build from 2020-06-20. (r6415.eeb90a79-1 to be precise.)
@RedSoxFan Thanks for the replies, it's understandable.

**Comment by schauveau** [comment]
@Isti115 Your weird behavior remind me the time when I was trying to figure out why some of my binding were working intermittently. Are you sure that you are not affected by #3843?

**Comment by Isti115** [comment]
Hmm, that's an interesting suggestion, but I tested the behavior with both built-in layouts and my own custom one as well, and was unable to reproduce the scenario, when specifying inputs individually does not group them and a reboot is required to fix it.

**Comment by TheChymera** [comment]
@RedSoxFan @Isti115 hm, strange, another reboot fixed it, I'll get back if it fails again with my sway log. Many thanks in any case :)

**Comment by Isti115** [comment]
After _(who knows how many, let's just say)_ a few reboots this broke again without any change to the config file... This is very misterius now. I'm trying to make some sense of the situation, but sadly without too much luck.

Maybe at least a way to know which keyboard has been assigned to which group could be added to `swaymsg -t get_inputs`, which would help identifying the source of these sorts of problems?
