### ISSUE TITLE
swaylock does not exit and uses 100% CPU

### ISSUE THREAD

**Issue by Marteon** [swaywm/sway#2898]
`swaymsg version 1.0-alpha.6-313-gd855837d (Oct 20 2018, branch 'HEAD')`

Seemingly random swaylock does not terminate and uses 100% CPU.
It happened several times and at leas one time was after suspend.
When it happens again I'll attach the logs.

**Comment by emersion** [comment]
Also happened to me. Maybe we're not correctly handling being disconnected from the display.

**Comment by ascent12** [comment]
I ran into a somewhat similar issue with swaybar ages ago where we weren't handling POLLNVAL/POLLHUP properly, causing the poll loop to spin extremely quickly, wasting 100% CPU.

**Comment by RyanDwyer** [comment]
If you run swaylock from the command line you should get log output.

You might find it easier to run sway in a nested session (use a different config file with a different mod key) and launch swaylock into the nested session by running (from your normal session) `WAYLAND_DISPLAY=wayland-1 swaylock`. You could add log statements to `common/loop.c` in `loop_poll` to see how frequently it's hitting that function. You could also log these:

* See if `pfd.revents` has the `POLLHUP` or `POLLERR` or `POLLNVAL` bits set.
* Check that `ms` doesn't sit at 0 all the time.
* Check that `poll` is not returning -1.

**Comment by martinetd** [comment]
It's not easy to tell with github still buggy, but #2925 will be a fix for this, there's no need to spend more time debugging this issue.
(a first approximation to the logging you suggest adding is strace, though; much easier to run and gives all the bits you suggested to log)

**Comment by RyanDwyer** [comment]
It just happened for me on 641fbe576e10064b253671acd0360b500232a235, which is a commit in a branch of mine which is branched from 46fc4ba4e3e2444ff68a894ab837d8e1e3324e0a.

After unlocking, a swaylock process was still running. I straced it and got this repeatedly:

    poll([{fd=3, events=POLLIN}], 1, -1)    = 1 ([{fd=3, revents=POLLIN|POLLHUP}])
    poll([{fd=3, events=POLLIN}], 1, 2147483647) = 1 ([{fd=3, revents=POLLIN|POLLHUP}])

**Comment by emersion** [comment]
We need to handle `POLLHUP` and stop the event loop in that case.

**Comment by ianyfan** [comment]
Closing by https://github.com/swaywm/sway/pull/2925, please re-open if you are still experiencing this issue.

**Comment by xyproto** [comment]
When I log into my locked computer over ssh, I see that swaylock uses 100% CPU on one of the cores. I have never had issues with swaylock not terminating, though, so I'm not sure if this is the same issue or not.

* Arch Linux
* `swaylock version 1.0-beta.1-6-ga918844e (Oct 22 2018, branch 'master')`

**Comment by Emantor** [comment]
The fix for this was only merged on 24th of October, please update your sway version.

**Comment by xyproto** [comment]
ok, thanks
