### ISSUE TITLE
pid->workspace tracking steals pointer focus

### ISSUE THREAD

**Issue by ddevault** [swaywm/sway#2899]
If I run a process on another workspace, switch back to the first one, then wait for the process to open its window, I can't click on the window I had focused on the first workspace.

**Comment by emersion** [comment]
Does this only happen with xwayland windows?

**Comment by emersion** [comment]
Ah, on IRC it seems it's the case. It because the other window is stacked over the currently focused one on map. We need to restack the focused one on top.

Probably requires wlroots changes?
