### ISSUE TITLE
Feature Request: add gap funtionality to swaybar.

### ISSUE THREAD

**Issue by iBurley** [swaywm/sway#2904]
Ahoy, big fan of what you're doing and congrats on the big 1.0.

Now that you're at full feature-parody with i3 I was wondering if I might request something that I've been wanting for a while but assumed was too small and unimportant to bring up, gap functionality on swaybar. I know even i3-gaps doesn't support this on i3bar (and they say it would be a large undertaking), but I wasn't sure if maybe it would be easier for you since this is a from-scratch implementation. I don't know how much demand there would be for a feature like this, but as somebody who would only use lemonbar or polybar over the default to add gaps around the bar to match the window gaps, this is a feature I'd certainly love to see. 

Thanks.

**Comment by SirCmpwn** [comment]
This would be pretty easy, we can just set a margin on the layer surface.
