### ISSUE TITLE
"output * dpms off" does not enable screens back upon key presses

### ISSUE THREAD

**Issue by Hi-Angel** [swaywm/sway#2910]
DPMS was never used to disable screen completely, but rather temporarily, as a means of saving power. E.g. on X11 the command `xset dpms force off` disables screens only until a mouse moved or a key pressed.

However on sway the command `output * dpms off` disables screens completely.

# Steps to reproduce

1. Execute `swaymsg "output * dpms off"` *(this should light off the screens)*.
2. Press a key

# Expected

Screens light up back

# Actual

Screens stay black, and I see no way to light them up.

# Additional info

sway build from today, commit a4d68358.

**Comment by SirCmpwn** [comment]
For this behavior you need to configure swayidle, see the man page for details.

**Comment by Hi-Angel** [comment]
@SirCmpwn what's the usecase of not having that behavior by default?

**Comment by SirCmpwn** [comment]
This design is more flexible and accomodates more use-cases.

**Comment by ncoop** [comment]
I have this line in my i3 config:
```config
bindsym ctrl+mod1+s exec "xset dpms force off"
```

And in sway config:
```config
bindsym ctrl+mod1+s exec swayidle -w \
  timeout 1 'swaymsg "output * dpms off"' \
  resume 'swaymsg "output * dpms on "; pkill -nx swayidle'
```

It's a hack, and I worry about that `pkill`, but it works so far.

**Comment by Hubro** [comment]
Here is my solution:

In my autostart.sh script (launched by an `exec` in my Sway config):

```
# Sleep monitors after 20 minutes idle
swayidle \
    timeout 1200 'swaymsg "output * dpms off"' \
    resume 'swaymsg "output * dpms on"' \
    &
```

Sway keybind:

```
bindsym $mod+F7 exec "bash -c 'sleep 0.2; killall -USR1 swayidle'"
```

Sending the "USR1" signal immediately triggers the timeout in `swayidle`. The sleep is just so I have time to let go of all the keyboard keys before the swayidle timeout triggers, otherwise the screen will immediately wake back up.

**Comment by cartok** [comment]
Guys I have the same problem, I do not get my screen back online. It just stays black.
Even this does not work:
```
swaymsg "output * enable dpms on"
```

**Comment by SuperCowProducts** [comment]
@Hubro are you sure `bash -c 'sleep 0.2; killall -USR1 swayidle'` works for you? When I run it it turns off the screen, but then the screen won't turn on again after pressing any key.

**Comment by SuperCowProducts** [comment]
@ddevault how are we expected to make a keybinding that turns off display *until* a key is pressed?
