### ISSUE TITLE
Crash when moving program to workspace with another fullcreen program.

### ISSUE THREAD

**Issue by DutchMofo** [swaywm/sway#2915]
When I moved a program(termite) to another workspace that had another program open in fullscreen(mpv) sway crashed. After the crash I restarted sway and did the above steps and got the same result.
 
Never written an issue before so let me know if you need more information.

**Comment by emersion** [comment]
Can you upload the backtrace? (`coredumpctl gdb sway` and then `bt full`)

**Comment by DutchMofo** [comment]
Do I need to have sway running and then cause the crash?

**Comment by emersion** [comment]
You need to:
1. Cause the crash
2. Without rebooting, execute `coredumpctl gdb sway` and then type `bt full`
3. Upload the output of the command

**Comment by DutchMofo** [comment]
Here you go, 
https://gist.github.com/DutchMofo/79619cc7e85d04f386beeaf7a7a08909

Also congrats on sway 1.0!
