### ISSUE TITLE
Map XF86PowerOff

### ISSUE THREAD

**Issue by mb720** [swaywm/sway#2916]
Hi!

I'm having a great time with Sway! :+1: 

I'd like to suspend my Lenovo laptop using the power button.
For this, I added the following to my Sway `config`:

    bindsym XF86PowerOff exec systemctl suspend

This didn't have any effect though. Suspecting that the `systemctl suspend` part might not work when called from a keybinding, I tried to map `XF86PowerOff` to a command that I knew would work from a keybinding:

    bindsym XF86PowerOff exec amixer -q set Master toggle

I know that `amixer -q set Master toggle` works because I can execute it by pressing `XF86AudioMute`.

Toggling volume with `XF86PowerOff` didn't work either which tells me that the key mapping in Sway's configuration file does nothing on my system.

I can suspend my system by executing `systemctl suspend` in the shell.

Is there a way to bind a command to the power button using `XF86PowerOff`?

---

Sway version: 0.15.2
Arch Linux 4.18.12

**Comment by SirCmpwn** [comment]
If you're using systemd you're probably better of configuring `/etc/systemd/logind.conf`

**Comment by skrps** [comment]
> This didn't have any effect though.

Maybe your user doesn't have the permission to do so.

**Comment by mb720** [comment]
@skrps: Thanks for your comment. I don't think that's it since I can suspend my system by executing systemctl suspend in the shell. I updated my original question with that piece of information.

**Comment by skrps** [comment]
You can see what's wrong with `exec systemctl suspend` by seeing the log generated by Sway.

I stand with @SirCmpwn here though: you're better off editing `/etc/systemd/logind.conf` (`/etc/elogind/logind.conf` for those using elogind).

**Comment by mb720** [comment]
`exec systemctl suspend` works fine; for example with this key mapping, I can suspend the machine by pressing the mute button:

    bindsym XF86AudioMute exec systemctl suspend

As helpfully suggested, I edited `/etc/systemd/logind.conf`:

    HandlePowerKey=suspend

I made the changes effective with `sudo systemctl restart systemd-logind` (which logged me out).

Pressing the power button on my loptop for about half a second will suspend the machine, just like I wanted it to.

Thanks for your help!

**Comment by Ferdi265** [comment]
I think this is slightly relevant:

on my system, XF86AudioMute, XF86AudioRaiseVolume and XF86AudioLowerVolume don't work, even though they work fine with `xev` in Xorg and Xwayland, and other XF86 keys _do_ work in sway for me. (for example XF86MonBrightnessUp and Down)

I haven't found a better way to test inputs than `xev`. If there is a pure wayland alternative, that would be nice.

**Comment by SirCmpwn** [comment]
A wayland equivalent of xev would be a pretty easy weekend project for an interested programmer.

Fwiw XF86AudioRaiseVolume et al work fine for me.

**Comment by Ferdi265** [comment]
I'm currently trying to printf-debug sway's input handling to see where it goes wrong.
The keysym is correctly made into a binding, but the get_active_binding says modifiers don't match for the XF86Audio buttons. I'll try to further look into this.
