### ISSUE TITLE
sway: Configuration path is not parsed correctly.

### ISSUE THREAD

**Issue by c-edw** [swaywm/sway#2927]
This is a bug that occurs when specifying the `-c` parameter to Sway. The two paths in the steps below are theoretically the same but only one of them works when passed to Sway.

Steps to reproduce:
1. Launch Sway with `-c .config/sway/config` 
2. Observe that it works
3. Launch Sway with ` -c ./config/sway/config`
2. Observe that it doesn't work

**Comment by emersion** [comment]
`.config` != `./config` (but `.config` == `./.config`)

**Comment by c-edw** [comment]
Hmm, I thought they were the same, but `nano` also refuses the second path. Plus, I checked the code and it's just calling `fopen` so there isn't room for anything to go wrong. Will have to brush up on my UNIX :+1: Thanks!

**Comment by c-edw** [comment]
Sorry, I'm tired. It's obvious why that didn't work.
