### ISSUE TITLE
sway depends on git?

### ISSUE THREAD

**Issue by Arnaudv6** [swaywm/sway#2931]
Hello guys, I followed your work as an amateur but with much interest: thanks a lot for all you've achieved, and the way you stuck to your nice vision..  

building sway-1.0-beta with `meson build`:   
`meson.build:130:2: ERROR:  Problem encountered: git is required to make the version string`
Yes, I found a PC without git! :1st_place_medal:

**Comment by SirCmpwn** [comment]
git is used to determine the current version. So, yes.

**Comment by Arnaudv6** [comment]
might add it to dependencies list?

**Comment by SirCmpwn** [comment]
Send patch?

**Comment by ianyfan** [comment]
Is it customary to require git for building from sources if it's just to get the version string? Why not make it optional and just produce a message like "unable to provide version string since this was not built with git available"?

**Comment by SirCmpwn** [comment]
I prefer to break rather than ship "unable to provide version string..." because we depend on the version string in bug reports.

**Comment by progandy** [comment]
It looks like there is already a build option for meson called ```sway-version```

**Comment by Arnaudv6** [comment]
#2937
