### ISSUE TITLE
Disabling an output doesn’t DPMS it off

### ISSUE THREAD

**Issue by linkmauve** [swaywm/sway#2948]
I disabled my laptop’s output with `output LVDS-1 disable`, expecting it would be DPMS’d off, but instead it keeps the last frame of the TTY painted on it, with backlight on.

**Comment by linkmauve** [comment]
An easy workaround is to reload the configuration, it will then DPMS it off.

**Comment by RedSoxFan** [comment]
What version of `sway` are you using? This was implemented a while ago in https://github.com/swaywm/sway/pull/2572 and appears to still be working for me.

Can you please post a debug log?

**Comment by RedSoxFan** [comment]
Sorry, I completely misunderstood this issue before. #3280 should fix this.
