### ISSUE TITLE
Unwanted workspace move when a surface gets closed there

### ISSUE THREAD

**Issue by linkmauve** [swaywm/sway#2951]
How to reproduce:
- Have a terminal on workspace 1.
- Run mpv, while it’s loading move to workspace 2.
- Go back to workspace 1.
- Wait for the song to finish playing.

Expected result:
You stay in your terminal.

Actual result:
You are moved to an empty workspace 2.

**Comment by linkmauve** [comment]
I don’t have `focus_on_window_activation` set, and I have a single enabled output.

**Comment by RyanDwyer** [comment]
Which terminal are you using? And is mpv launching a window to show album art?

**Comment by linkmauve** [comment]
Stupidterm (some libvte one, so using GTK+), and mpv is indeed displaying a video, otherwise no surface would get created, as there would be no buffer to attach.

**Comment by RyanDwyer** [comment]
I can't reproduce this.

**Comment by c-edw** [comment]
I have also experienced this bug. My terminal emulator of choice is Terminator. I produce the bug by doing the following:
1. Start Sway
2. Enter workspace 1
3. Open terminal emulator (Terminator in my case)
4. Launch `gedit` (or another affected application) through the terminal
5. Move the `gedit` window to workspace 2
6. Ctrl+C the process from within the terminal
7. Observe that workspace 2 is focused and is blank
8. Observe that swaybar incorrectly displays still being in workspace 1
9. Enter workspace 1
10. Observe that the terminal is there
