### ISSUE TITLE
Configuration reload leaves orphaned swaybg processes

### ISSUE THREAD

**Issue by CameronNemo** [swaywm/sway#2952]
After reloading my configuration, I am seeing some orphaned swaybg processes hanging about. In fact each reload generates two of them.

I am running Void Linux, glibc, kernel 4.18.16, with elogind.

Please tell me if there is any more information you need.

**Comment by madblobfish** [comment]
I could not reproduce your issue, could you post your configuration?

**Comment by CameronNemo** [comment]
I can reproduce with the default configuration.

**Comment by madblobfish** [comment]
Please provide a debug log and the exact sway version. (see https://github.com/swaywm/sway/wiki#how-do-i-report-issues)

**Comment by CameronNemo** [comment]
http://ix.io/1qfm

**Comment by emersion** [comment]
Hmm, just realized I still have swaybar processes left behind when I Ctrl+C sway.

**Comment by RedSoxFan** [comment]
Is anyone still able to replicate this?

**Comment by CameronNemo** [comment]
FWIW I have not seen this exact behavior, but I did see a zombie swaybg recently.

**Comment by emersion** [comment]
I'm going to close this, as we now disconnect swaybg instead of killing it.
