### ISSUE TITLE
Multiseat support for swaylock

### ISSUE THREAD

**Issue by BurningTreeC** [swaywm/sway#2959]
if I lock my sway session with a keyboard assigned to seat0, swaylock accepts input only from my seat1 keyboard

**Comment by ascent12** [comment]
Are we talking about logind seats or sway seats?
If it's the latter, I would argue that this would be the correct behaviour.

**Comment by BurningTreeC** [comment]
@ascent12 **sway seats** ... I didn't expect this, say I have two keyboards quite distant from each other, I'd expect I can unlock with the one I locked the session. If it's standard behavior or you want it like this, just ignore my issue and I'll close it

**Comment by ascent12** [comment]
Locking the screen locks the entire session, meaning that both seat0 and seat1 are now locked.
I think it makes sense for either seat to unlock the session.
This stops seat0 from locking the screen and disallowing seat1 to continue doing whatever they're doing.

If we were talking about logind seats, it'd be different, but that's not the same kind of multiseat.

I don't know what other developers think about this, though.

**Comment by emersion** [comment]
Related to https://github.com/swaywm/sway/issues/2780
