### ISSUE TITLE
[i3-ipc compatibility] output event not implemented

### ISSUE THREAD

**Issue by Ferdi265** [swaywm/sway#2967]
the "output" subscribable event is not yet implemented in sway.

sway ipc instead answers to the ipc event with `{"success": false}` and logs

    [sway/sway/ipc-server.c:687] Failed to parse request: Resource temporarily unavailable

The "Resource temporarily unavailable" seems to come from errno, which is not relevant here. The event name just failed the `strcmp` chain, which doesn't set errno.

**Comment by ianyfan** [comment]
We don't emit output events anywhere yet, since it's not documented by i3 when they are emitted, so there hasn't really been a reason to allow it to be subscribed to yet.

**Comment by SirCmpwn** [comment]
I don't see any reason to implement output subscribe given it doesn't really do anything in i3.

**Comment by progandy** [comment]
@ianyfan i3 just forwards notifications it receives from RandR
> https://i3wm.org/docs/3.e/ipc.html#_available_events
> output (1)
>    Sent when RandR issues a change notification (of either screens, outputs, CRTCs or output properties).

**Comment by Ferdi265** [comment]
Also, independent of wether we implement it or not, the irrelevant errno formatted message should IMO be removed / changed. It just doesn't make sense here.

**Comment by emersion** [comment]
Yes. Please send a patch.

**Comment by Ferdi265** [comment]
Will do :)

**Comment by philipflohr** [comment]
@SirCmpwn I'm writing a little tool helping to configure outputs which could use the output event. 
If I write a patch implementing the output event will you merge it?

**Comment by emersion** [comment]
@philipflohr You may be interested in https://github.com/emersion/kanshi

**Comment by philipflohr** [comment]
@emersion thanks but not excatly what I'm looking for as I plan to implemet workspace -> output save/restore and other features. 

But maybe there can be some mutual inspiration
https://github.com/philipflohr/SwayMonMan

@ddevault Would you merge a patch implemeting the output event?

**Comment by moljac024** [comment]
How does kanshi work? I wanted to write a similar tool/script for myself and I was hoping I could rely entirely on sway's IPC (I don't need this to work for anything else right now). I guess I could still do it with polling of get_outputs but that sounds so inefficient.

This would be a useful feature to have and I don't think sway should be crippled by trying to imitate i3 perfectly. After all, Wayland is not X.org and sway already differs on those points. This would be another reasonable difference from i3 IMO.

**Comment by Ferdi265** [comment]
Kanshi probably listens on the xdg_output wayland protocol. These kinds of things don't neccessarily need to be done via a custom IPC, since wayland already has protocols for it.

**Comment by emersion** [comment]
>Kanshi probably listens on the xdg_output wayland protocol.

Nah, kanshi uses the output-management protocol.

https://github.com/emersion/kanshi/blob/master/protocol/wlr-output-management-unstable-v1.xml

**Comment by Ferdi265** [comment]
> output management protocol

ahh. I didn't know that's a thing, but I figured it would be a wayland protocol.

**Comment by barjonas** [comment]
The manpage is pretty definitive:

> "The following events are currently available:"
> ...
> 0x80000001 	output 	Sent when outputs are updated

From the perspective of this Sway noob writing some IPC integration code, this thread was my only indication that the reason I was getting "success = false" to my subscribe request was because it wasn't implemented. The most consistent alternative in my case will be polling GET_OUTPUTS, which is definitely inferior.
