### ISSUE TITLE
commands in config variables doesn't seem to work

### ISSUE THREAD

**Issue by budRich** [swaywm/sway#2968]
in i3 this is possible to do in the config:   
```text
set $super bindsym Mod4
$super+a exec COMMAND
$super+b exec COMMAND
```

this doesn't work in the sway config. No big deal, just wanted to let you know if you want full compatibility with i3 config. Also it's a nice way to keep the lines cleaner and shorter in the config.

tested on `sway version 1.0-beta.1-36-g7160b8aa (Oct 23 2018, branch 'master')`

i use arch btw

**Comment by avrelaun** [comment]
Same here with output variables:

set $scr2 HDMI-A-2
set $scr2 DP-1

bindsym $mod+g move workspace to output $scr1
bindsym $mod+Shift+g move workspace to output $scr2

workspace 1:one output $scr1
workspace 2:two output $scr2
