### ISSUE TITLE
Backward-compatible I3SOCK IPC

### ISSUE THREAD

**Issue by Snaipe** [swaywm/sway#2976]
Some libraries and programs are currently not working out-of-the-box with sway, because they expect X11-specific fields to always have a non-null value (e.g. class/instance, window).

Those fields are normally there for xwayland windows, but are otherwise null for wayland ones; this ends up crashing any script trying to regexp-match a string against a null,nil,None object, among other things.

A solution to this problem would be to serve a second IPC socket for I3SOCK, and make the output try to accommodate the quirks of i3's original X11-centric output.

Some fairly obvious changes for the I3SOCK output would include:
* set the contents of `class`, `window_properties.class`, `window_properties.instance` with the value of `app_id` for wayland windows.
* always provide `window_properties.*` for wayland windows.
* as a bonus, removing any extra json fields added by sway; not completely necessary, but keeps the output undistinguishable from a stock i3.

Other less-obvious changes:
* @RyanDwyer mentioned that dock containers exist in i3's output but not sway's.
```
2018-10-25 15:18:00     ryan-au BTW, i3's IPC has dock containers and ours doesn't
2018-10-25 15:18:09     ddevault        dock containers?
2018-10-25 15:18:21     ryan-au And in one of the calls I think the root container is returned in the output list
2018-10-25 15:18:42     ryan-au Yeah, it goes root > output > dock, or root > output > content > workspace or something like that
```
* providing an ID for `window` and `window_properties.transient_for` fields? This is a bit delicate, do we provide some fake ID, or an actual xwayland-registered placeholder that identifies the wayland window?

As a side note, I've been running a proxy server on top of I3SOCK in my local machine that does the class/instance-as-app_id change, and previously broken scripts start working again (although with some config tweaking needed, as most programs used to capitalize the instance or class, but this is to be expected anyways).

**Comment by emersion** [comment]
>this ends up crashing any script trying to regexp-match a string against a null,nil,None object, among other things.

This seems strange, do all x11 programs set class and instance? We could set them to an empty string, but that wouldn't make legacy scripts work.

**Comment by ianyfan** [comment]
If this gets implemented, it could also remove unnecessary xwayland properties from SWAYSOCK.

**Comment by SirCmpwn** [comment]
Some of them are necessary because they, well, come from xwayland. Like window class should still be there.

**Comment by Snaipe** [comment]
Well that could be a good way to actually have some sections of the json that makes sense.

For instance, I recently added `window_properties` to sway's json output for xwayland windows since i3 has that map in its output, but it brings `window_properties.class`, which is a duplicate of `class`, and `window_properties.title`, which is a duplicate of `name`.

I don't know how you feel about deviating too much from i3's output in SWAYSOCK, but you *could* clean things up a bit by putting xwayland-related stuff in an `xwayland` map (notably `window`, `class`, and `instance`) and then setting it to null for native wayland windows.

**Comment by SirCmpwn** [comment]
>I don't know how you feel about deviating too much from i3's output in SWAYSOCK, but you could clean things up a bit by putting xwayland-related stuff in an xwayland map (notably window, class, window_properties.instance, and window_properties.transient_for) and then setting it to null for native wayland windows.

Not fond of this. I don't want to deviate much at all.

**Comment by Snaipe** [comment]
Just so we're on the same page, since i3's output features a "dock area" container that we probably want to mimic in I3SOCK, can we omit it in SWAYSOCK, or do you consider that to deviate too much from i3's output?

I guess a better question would be: do we keep *all* i3 fields in SWAYSOCK, even those that are either unimplemented, or don't always make sense, and set them to e.g. null, or can we selectively omit them? I'm not 100% sure what the backward-compat policy for the IPC is.

**Comment by emersion** [comment]
Closing, we won't be breaking i3 compat in SWAYSOCK.
