### ISSUE TITLE
[Question] Background color to wallpaper

### ISSUE THREAD

**Issue by JonnyMako** [swaywm/sway#2981]
When I set a wallpaper with `output` and the wallpaper is centered, and does not cover the entire area of the screen, there is a gray background behind the wallpaper. This is presumably from rootston? Is there a way to change this background color?

**Comment by RedSoxFan** [comment]
> This is presumably from rootston? 

Sway does not inherit anything from Rootston. They are two different compositors that use the wlroots library. It's just the default background color.

>  Is there a way to change this background color?

You can use `output <name> bg <image> <mode> <fallback-color>`.
Example: `output eDP-1 bg ~/wallpaper.png center #000000`
