### ISSUE TITLE
GNOME-Boxes and mouse cursor 

### ISSUE THREAD

**Issue by trmendes** [swaywm/sway#2988]
I have GNOME Boxes ```3.30.2``` running on sway ```version 1.0-beta.1-23-g7583b0b8a50e (Oct 25 2018, branch 'master')``` and every time I move the mouse cursor to the GNOME Boxes window the cursor disappear and I get a message

```[sway/input/cursor.c:1222] denying request to set cursor from unfocused client```

**Comment by trmendes** [comment]
It works if I have output scale equal to 2. Before that I had it equal to 1.8

**Comment by emersion** [comment]
Hmm, it should still work with a 1.8 scale.

**Comment by trmendes** [comment]
I'm now back to 1.8 and it is working. I'll let you know if it happens again.
