### ISSUE TITLE
Unable to make a tabbed layout

### ISSUE THREAD

**Issue by atomnuker** [swaywm/sway#3002]
To reproduce:
Go to a new workspace
Create a new terminal
Set its layout to vertical
Try to set its layout to tabbed
Nothing will happen.

What this prevents:
Having 2 containers, side by side, with one being tabbed.

**Comment by atomnuker** [comment]
They don't because I wanted the simplest possible version to replicate.
I'm using no borders at all, that's maybe related?

**Comment by RyanDwyer** [comment]
Works with `default_border none` as well. Can you please attach a debug log?

**Comment by progandy** [comment]
> Try to set its layout to tabbed
> Nothing will happen.

> I'm using no borders at all, that's maybe related?

When there are no borders, then the master branch doesn't show the tabs if there is only one window, you have to open at least two. (65328ef60c9468ae44b4b1d6316d604c47293ec3)

**Comment by atomnuker** [comment]
I think that's wrong, I preferred the default behavior - to open one terminal, make it tabbed, and then open new tabs as I need.
I'd agree to make it a setting, but forcing this on users isn't nice.

**Comment by SirCmpwn** [comment]
>I think that's wrong, I preferred the default behavior - to open one terminal, make it tabbed, and then open new tabs as I need.

I agree, we should probably do this.

**Comment by SirCmpwn** [comment]
Can anyone start up an i3 session to confirm that claim?

**Comment by progandy** [comment]
@SirCmpwn I still run i3 most of the time, here are some tests:
```
$ i3 --version
i3 version 4.15 (2018-03-10) © 2009 Michael Stapelberg and contributors
$ cat /tmp/i3.conf 
hide_edge_borders none
default_border pixel

set $mod Mod4

bindsym $mod+v split v
bindsym $mod+b split h
bindsym $mod+t layout toggle splitv splith tabbed stacked
bindsym $mod+s layout stacked

bindsym $mod+Shift+c reload
bindsym $mod+Shift+r restart
bindsym $mod+Shift+e exec --no-startup-id i3-msg exit
bindsym $mod+Return exec termite

# change focus
bindsym $mod+h focus left
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+l focus right

# move focused window
bindsym $mod+Shift+h move left
bindsym $mod+Shift+j move down
bindsym $mod+Shift+k move up
bindsym $mod+Shift+l move right
```
**```hide_edge_borders smart```, ```default_border pixel```**

- 2 terminals open
  splitv, splith - no titlebar
  tabbed, stacked - titlebar visible
- 1 terminal open 
  splitv, splitv - no titlebar
  tabbed, stacked - no titlebar

**```hide_edge_borders smart```, ```default_border normal```**

- titlebars always visible

**```hide_edge_borders none```, ```default_border pixel```**
- 2 terminals open
  splitv, splith - no titlebar
  tabbed, stacked - titlebar visible
- 1 terminal open
  splitv, splitv - no titlebar
  tabbed, stacked - no titlebar
- 2 terminals side by side (splith), left terminal in a tabbed container:
  - no titlebar visible
  - while focusing on the left terminal, open another one
  - left tabbed container shows two terminals with tabbar.
