### ISSUE TITLE
[enhancement] Support modifying scroll sensitivity

### ISSUE THREAD

**Issue by sxmichaels** [swaywm/sway#3004]
I've just started using sway 1.0-beta1 on a laptop, and one glaring issue I've noticed is that scrolling via the touchpad is _really_ sensitive, and there doesn't seem to be any configuration option for libinput itself to change this. Physical mice have a `MOUSE_WHEEL_CLICK_ANGLE` property, which according to [this stackoverflow post](https://unix.stackexchange.com/questions/307663/change-scroll-speed-with-libinput) affects scroll rate, but I can't find any equivalent for touchpads. Similarly, the [libinput API](https://wayland.freedesktop.org/libinput/doc/latest/api/group__config.html) also doesn't seem to have a function for directly modifying scroll.

I think that this could be fixed by adding a `scroll_factor` option for `input` entries in sway's config that would be used to scale the delta values of scroll events from the device (which I think happens [in pointer.c here](https://github.com/swaywm/sway/blob/9658d4bcc564dd7c5c82aa1b8795cccedfaabb70/sway/input/cursor.c#L1027)).

**I'm willing to make a PR for this myself**, but I would like a bit of guidance before doing so if possible, as I have a few questions:

1. Is this change best made in sway, or wlroots? Since the other input config options are in Sway, I assume the former.
2. All of the other input configuration options currently map directly to libinput functions (see [here](https://github.com/swaywm/sway/blob/cafb1ff4f78b0f093ab4da987174b92762696366/sway/input/input-manager.c#L141)). Adding an external scaling factor for scroll deltas would be a break from this. Perhaps I should make a PR for libinput to implement this feature, and only then add support for it to Sway?

**Comment by progandy** [comment]
@emersion: libinput doesn't want that option
https://bugs.freedesktop.org/show_bug.cgi?id=89323

**Comment by emersion** [comment]
All right, makes sense to do that in sway then.

**Comment by sxmichaels** [comment]
Ah, glad you found that issue. I was worried about exactly that, since the libinput devs seems to be a bit… averse to configuration, to put it mildly. One comment on that issue states "There is nothing to configure at this level in the stack, this is something that would need to be sorted in the toolkits/compositor." I will start familiarizing myself with the sway/wlroots source to see how I can implement this, then.

Would it be preferable if I implement this at the wlroots level and make an API that sway (and potentially other WMs) can use, or should I do it all in sway?

It looks like one way, if it's done via wlroots, is to modify [this line](https://github.com/swaywm/wlroots/blob/2518de655c7278728736d22549656c639e4c92f0/backend/libinput/pointer.c#L129) to have a scale factor for the `delta` value. The equivalent in sway appears to be [here](https://github.com/swaywm/sway/blob/9658d4bcc564dd7c5c82aa1b8795cccedfaabb70/sway/input/cursor.c#L1027).

**Comment by emersion** [comment]
I don't think we need to make wlroots changes for this feature.
