### ISSUE TITLE
Cursor remains showing after Sway exits to framebuffer terminal

### ISSUE THREAD

**Issue by milkey-mouse** [swaywm/sway#3017]
- Version: `sway version 1.0-beta.1-106-g1c2a356d (Oct 28 2018, branch 'master')`
- Debug log: https://gist.github.com/milkey-mouse/fbfca6cf5b92e2e1d418049135c36131
- Configuration file: [default](https://github.com/swaywm/sway/blob/1c2a356dcf43f2fbd633a2e2badabbfd4b9e6cb3/config.in)

I have sway configured to start when I log into TTY 1:

    if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
        exec sway
    fi

I don't have a login manager or anything like that.

The bug is kind of funny: when I exit sway & logind regains control, a (frozen) mouse cursor remains on my Linux framebuffer. Obviously I can't take a screenshot since there's not actually a WM running at that point.

**Comment by RedSoxFan** [comment]
Are you still able to replicate this? I think with the current code base, the cursor image will be hidden when the seat loses the `WL_CAPABILITY_POINTER` capability on exit.

**Comment by milkey-mouse** [comment]
It seems to be fixed as of `1.0_rc1`.

**Comment by milkey-mouse** [comment]
For some reason this issue is back for me on `1.0_rc3`. Perhaps it was intermittent to begin with and I got lucky twice with `1.0_rc1`.

**Comment by ascent12** [comment]
This is actually a wlroots issue.

**Comment by milkey-mouse** [comment]
Should I open an issue there?

**Comment by ascent12** [comment]
@milkey-mouse It's a simple fix, so I just opened a PR for it: https://github.com/swaywm/wlroots/pull/1571

Can you confirm that it works for you?

**Comment by milkey-mouse** [comment]
That patch seems to work, thanks!
