### ISSUE TITLE
Transparency Inconsistencies related to Gaps

### ISSUE THREAD

**Issue by kon14** [swaywm/sway#303]
I've noticed some strange behaviour with my terminals' transparencies and the way they behave depending on whether gaps are enabled or disabled. The issue is persistent and seems to affect true and native transparencies differently. I've verified this with urxvt and sakura. 

In the examples below you'll notice it's mostly native transparency not working at all and true transparency not working with gaps disabled.
Even so I won't restrict this by marking it as a Native transparency issue due to the various different results I've had while reproducing and documenting the issue, some of which I might have missed in the post. 
For instance, I'm almost certain true transparency wouldn't work with or without (not sure about which one it was) gaps at a time, while native would, but now it's all gone whatever!

Sakura is yet another gtk terminal (native wayland support present if built with latest gtk3 versions), it features it's own configuration files (sadly lots of values are hardcoded) and awesome font rendering.

In order to get Native/True transparency for urxvt you need to edit ~/.Xresources and then launch a terminal after reloading the resource values with xrdb ~/.Xresources. Here are some values for both:

!Common Value
URxvt.background: [70]#000000
! Pick one, comment the other obviously
! Native Transparency:
URxvt*.transparent: true
! True Transparency:
URxvt.depth: 32

While gaps are being disabled urxvt's native transparency won't work (solid background colour). 
True transparency (both urxvt and sakura) doesn't work either.

While true transparency doesn't normally work without gaps, launching a terminal with true transparency in a workspace with more than 3 (subjective? read on) horizontal windows being present (the new term included) results in transparency instantly working as expected.

This is probably due to **another bug** I've noticed: 
Launching multiple windows horizontally (in the same workspace) creates a gap on the right end of the screen (gaps disabled), the width of which seems to increase the more windows you launch.
It's probably due to remaining pixels not being allocated to any of the windows (while dividing the screen's width / windows) but, since the gap is present on workspaces with even numbers of windows too (in that case horizontal pixels should divide perfectly), I'm kinda doubtful.
The above behaviour is reproduceable at any time on my 1366x768 display and might possibly affect vertical stacks too. The number of displayed windows required for the gap to show up might depend on the resolution even though it seems unlikely to me.

With gaps enabled true transparency seems to work properly. Native transparency won't work that way either.

**How to reproduce**:
1. Enable gaps
2. Edit Sway's config, toggle gaps and reload.
3. Edit .Xresourses and un/comment, toggling between transparency types.
4. xrdb ~/.Xresources && urxvt
5. Notice whether it works
6. Edit .Xresourses and un/comment, toggling between transparency types.
7. xrdb ~/.Xresources && urxvt
8. How about now? Note changes.
9. Disable Gaps
10. Notice changes (this is still using the latest trans type)
11. Toggle transparency type once more, xrdb, terminal
12. Any changes?
13. Repeat from 1, launching sakura in a workspace with at least X windows present (horizantally placed), if done already move on.
14. Gasp in terror once you realize the complexity of this :O 
15. Obligatory pass out

May the odds be with you.

**Comment by SirCmpwn** [comment]
I feel like I've seen some of this behaviour before. How long has it been since you updated sway?

**Comment by kon14** [comment]
Just rebuilt it today, could wlc be related? I didn't rebuild the latter yet but I'll be doing it anyway.

**Comment by SirCmpwn** [comment]
It's generally best to update both of them at the same time. If the issue persists, let me know and I'll investigate it.

**Comment by kon14** [comment]
Same thing as before

**Comment by SirCmpwn** [comment]
Alright. I'll try to reproduce this when I have time. In the meantime, can you produce a sway log? What distribution are you on?

**Comment by kon14** [comment]
Just sway -d 2> ~/sway.log right? I believe I might be confusing myself with orbment a bit.

I'm on gentoo, building diretly from git. I'll try following my instruction list for the loop in order to help navigate the output.

**Comment by SirCmpwn** [comment]
Lot of gentoo people coming forward with problems today. Probably gentoo that's busted, not sway.

Yes, that's how you get a log.

**Comment by kon14** [comment]
[Here](http://paste.debian.net/343744/)'s the log, I removed the initialization/exit lines.

I haven't been active in the irc lately but I bet most of those issues had to de with a) systemd (most gentoo users use openrc) and b) possibly non set environmental variables.

Since superuser privileges are required by wlc in order to spawn sway, as is, outside of X without logind being present, gentoo users and everyone else not using systemd have to setuid sway (owned by root) before launching it, something that should be in the README.md

chown root /path/to/sway && chmod u+s /path/to/sway is all that's required with /path/to/sway being /usr/local/bin/sway if default make install is used.

**Comment by SirCmpwn** [comment]
The readme does mention that you have to setuid it.

**Comment by kon14** [comment]
My bad then, think I've asked this in #sway before as I couldn't find it at the time (could be I was blind all along?)

**Comment by SirCmpwn** [comment]
https://github.com/SirCmpwn/sway/commit/fd4cf52518d265c681951bc4c193a2956afefc40

**Comment by kon14** [comment]
Yeap, must have been earlier then, glad it's there in any case.

**Comment by mikkeloscar** [comment]
I just tested this, and only true transparency seems to work for me, but it works the same way whether I use gaps or not.
