### ISSUE TITLE
focus output right doesn't loop

### ISSUE THREAD

**Issue by adouzzy** [swaywm/sway#3030]
sway version 1c2a356 (Oct 29 2018, branch 'master')

"focus output right" doesn't loop through all outputs. 
On the other hand, "move workspace to output right" loops.
From my muscle memory, i3 does loop through outputs.

I am not sure if this is a bug or feature request.
Thanks

**Comment by ascent12** [comment]
>I am not sure if this is a bug or feature request.

It's a bug. We try to match i3 behaviour as much as we can, and 'left' seems to work properly.

**Comment by adouzzy** [comment]
Right does work, it moves to the rightest output and then stopped.
I just tried left. It behaves similarly as right.

**Comment by RyanDwyer** [comment]
I started to do this, but having both `enum movement_direction` and `enum wlr_direction` is causing some grief. We have a function in `move.c` called `opposite_direction` which is exactly what we need, but it works with `enum wlr_direction` while the `focus` command uses `enum movement_direction`.
