### ISSUE TITLE
Negative output coordinates are possible using the config file but not using swaymsg

### ISSUE THREAD

**Issue by philipflohr** [swaywm/sway#3035]
By writing something like this
```
output eDP-1 pos 0 0 res 1920x1080
output DP-5 pos 0 -1080 res 1920x1080
```
in the config file it's possible to create a layout which uses negative coordinates. 

swaymsg forces the use of positive coordinates.

For consistent behavior either swaymsg should support negative coordinates or all coordinates should be positive.

**Comment by emersion** [comment]
Use `--`.

```
swaymsg -- output DP-5 pos 0 -1080 res 1920x1080
```

**Comment by SirCmpwn** [comment]
Swaymsg is interpreting your negative coordinates as flags. Pass `--` to disambiguate flags from the rest of your arguments, e.g. `swaymsg -- output DP-5 pos 0 -1080`
