### ISSUE TITLE
Sway not launching on Intel IGP w/ installed nvidia card

### ISSUE THREAD

**Issue by likyng** [swaywm/sway#3039]
Hi, my system is a thinkpad with an Intel IGP and NVIDIA graphics card. The only monitor (e-DP1) is connected to the Intel IGP card internally.

My intention is the use the Intel IGP exclusively for rendering, while having the prop. NVIDIA driver installed so I can test CUDA code. 

kernel: `4.18.16-arch1-1-ARCH`
sway version: `d3a62633`
wlroots version: `70ca7dae`

When I launch sway without setting any env. vars., by `sway`, it doesn't start citing the NVIDIA drivers. Log: [sway-std.log](https://github.com/swaywm/sway/files/2532610/sway-std.log)

When I launch sway using: 

    #!/bin/bash
    val=$(udevadm info -a -n /dev/dri/card1 | grep boot_vga | rev | cut -c 2)
    cmd="WLR_DRM_DEVICES=card$val sway --debug 2> ~/sway.log"
    export XKB_DEFAULT_LAYOUT=de
    export XKB_DEFAULT_VARIANT=nodeadkeys
    export XKB_DEFAULT_OPTIONS=

    eval "$cmd"

Sway doesn't start citing that it couldnt create a backend. Log: [sway1.log](https://github.com/swaywm/sway/files/2532611/sway1.log)

On my system, /dev/dri/card0 is the Intel card, which is the boot_vga.  
Output of `udevadm info -an /dev/dri/card0`: [card0.log](https://github.com/swaywm/sway/files/2532612/card0.log)
  
Output of `udevadm info -an /dev/dri/card1`: [card1.log](https://github.com/swaywm/sway/files/2532613/card1.log)

Starting sway with:  
* `WLR_DRM_DEVICES=/dev/dri/card0` results in sway not starting citing prop. NVIDIA drivers (log same as above)
* `WLR_DRM_DEVICES=/dev/dri/card1` results in sway not starting because it couldn't create a backend (log same as above)

It was my impression that I should be able to use sway with my Intel card, even though I also have an NVIDIA card, is that incorrect? I am able to launch rootston without a problem.

When I remove the NVIDIA prop. driver and don't install Nouveau, I am able to launch sway, albeit it starts slowly and doesn't shutdown cleanly, similiar to: #2784 , Log:

**Comment by progandy** [comment]
Your first sway log already says it all:
> **launch with --my-next-gpu-wont-be-nvidia** 

https://github.com/swaywm/sway/pull/2896#issuecomment-432489890

**Comment by SirCmpwn** [comment]
If the nvidia module is loaded on your system, you are not permitted to file bugs of any sort.
