### ISSUE TITLE
segfault in cursor_rebase on startup

### ISSUE THREAD

**Issue by tcpaiva** [swaywm/sway#3043]
*  sway version

sway version 1.0-beta.1-116-ge21a2334 (oct 31 2018, branch 'master')

* after some help at irc, I was instructed to open this issue with the related [stack trace](https://pastebin.com/DtTw8wKy).

Thank you very much and please let me know if some other information is needed.

**Comment by emersion** [comment]
Hmm, it seems `ws->floating` contains NULL items, which is weird. Can you post your config and debug logs?

**Comment by tcpaiva** [comment]
I'm afraid I don't have anything anymore. I had to reinstall my system due to software requirements.
