### ISSUE TITLE
swaymsg get_outputs show inaccurate "Current mode"

### ISSUE THREAD

**Issue by colemickens** [swaywm/sway#3051]
I've been re-applying my Sway config to try to figure out what is going on with position of my monitors (very specific combinations work, while other positions that look good on paper don't actually work).

Anyway, during this I noticed this:

```
Output eDP-1 'Sharp Corporation 0x148B 0x00000000'
  Current mode: 1920x1080 @ 59.997002 Hz
  Position: 0,0
  Scale factor: 2x
  Transform: normal
  Workspace: 4
  Available modes:
    3840x2160 @ 47.997002 Hz
    3840x2160 @ 59.997002 Hz
```

I can say from staring at the monitor at this moment, that display is not running at 1920x1080 mode.

Edit: debug log: [sway.log](https://github.com/swaywm/sway/files/2541320/sway.log)

**Comment by colemickens** [comment]
I've added this to my config:

`output "eDP-1" enable mode 3840x2160@59.997002Hz pos 0 0 scale 2`

`get_outputs` still reports the incorrect 1080p mode as the current mode.

**Comment by emersion** [comment]
The issue template is not meant to be ignored like this. Please include debug logs.

**Comment by martinetd** [comment]
Anyway we're probably returning the mode after scaling in swaymsg -t get_output, I just tried to change scale and value follows.

That should be trivial to fix (just remultiply or find the correct field), send a PR!

**Comment by colemickens** [comment]
I'll try to fix it. Here's debug logs as well: [sway.log](https://github.com/swaywm/sway/files/2541320/sway.log)

**Comment by emersion** [comment]
We should use wlr_output.width,height,refresh. Maybe we're incorrectly using the output's container width/height instead?

**Comment by colemickens** [comment]
Found so far:

* `sway->root->output->items[n]` derives width and height from `wlr_output_transformed_resolution`: https://github.com/swaywm/sway/blob/b1aec1ef14459e3458ebb85a69bccad97e7658e7/sway/tree/output.c#L79
* def of `wlr_output_transformed_resolution`: https://github.com/swaywm/wlroots/blob/675cf8457ef3493112def366d7090731172ee872/types/wlr_output.c#L321

Looks suspicious. Both branches do the same thing, neither multiply by scale. Let me know, I can move the issue over if I'm on the right track.
