### ISSUE TITLE
Trigger resize on possible size-modifying events

### ISSUE THREAD

**Issue by archshift** [swaywm/sway#3055]
When using sway, I notice that often applications will paint with the wrong size, rendering either too big or too small for their tiles.

Can sway force a resize event on the following actions to prevent this?
- Window creation (e.g. on program startup)
- Moving a tile to a different workspace

**Comment by emersion** [comment]
Can you provide a clear description of the issue, with reproduction steps?

Some applications refuse to render bigger or smaller than a given size.

**Comment by archshift** [comment]
Hm, reproduction's been difficult. I'll close this issue for now, but keep watch for what I'm doing the next time I see odd painting behavior.

**Comment by archshift** [comment]
Ah, I spotted it.
![image](https://i.imgur.com/ZYoMVO6.jpg)

(Sorry for this being a photo of my screen).

Basically, this seems to happen intermittently when I cold-open Firefox, e.g. from booting up my computer. It paints to the correct size if I resize the window or toggle floating, etc.

**Comment by cafehaine** [comment]
always happened on i3 with firefox for me, not linked with sway imo

**Comment by smlx** [comment]
Also happens occasionally with Firefox on i3 for me.

It's reported for other tiling WMs too: https://bugzilla.mozilla.org/show_bug.cgi?id=927621

Not a sway bug.
