### ISSUE TITLE
JetBrains/IDEA unresponsive after dragging secondary floating window.

### ISSUE THREAD

**Issue by c-edw** [swaywm/sway#3069]
In JetBrains IDEA (Java IDE), dragging the window *under* a tertiary floating window will cause the application to become completely unresponsive. This is a bit complex to reproduce. I am not sure if this only applies to IDEA or any application which might open multi-layered floating windows in this fashion.

Version:
```
sway version 1.0-beta.1-110-gd3a62633 (Oct 31 2018, branch 'master')
sway version 1.0-beta.1-110-gd3a62633 (Nov  5 2018, branch 'master')
```

(edit) I've done a git pull and rebuilt Sway, but the commit hash shown by `swaymsg -t get_version` and `/usr/local/bin/sway -v` hasn't changed to reflect what's current on master. Is it not the latest commit hash that's shown?

Steps to reproduce:
1. Start Sway
2. Start JetBrains IDEA
3. Navigate to `Settings...` under `File` (top left)
4. Under the settings tree, navigate to `Editor > Code Style > Java`
5. Locate the gear icon next to the `Scheme` dropdown
6. Click the gear icon and navigate to `Import Scheme > IntelliJ IDEA code style XML`
7. A file selector should open. Now, focus and drag the floating window **underneath** the file selector (Settings).
8. Observe that IDEA is unresponsive and can only be SIGKILL'd

**Comment by emersion** [comment]
>is there anything we can do on Sway/wlroots side to fix this?

Yeah, we can prevent windows from being re-stacked under their parent. There's already an issue about this iirc.

>However, I did still test it on i3wm and noticed a certain graphical bug didn't occur as it does with Sway. See below (there's a white/blackish border around the loading splash which isn't supposed to be there).

Probably a window size issue specific to X11.

**Comment by c-edw** [comment]
>Yeah, we can prevent windows from being re-stacked under their parent. There's already an issue about this iirc.

Alright, great.

>Probably a window size issue specific to X11.

I didn't phrase it very well. The graphical bug did not occur on i3wm, but it does on Sway.

**Comment by c-edw** [comment]
I will close this and raise a separate issue then. Thanks.
