### ISSUE TITLE
Airblader fork features

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/sway#307]
This issue tracks our progress implementing the features of @Airblader's i3 fork: https://github.com/Airblader/i3

Commands:
- [x] gaps
- [x] workspace <ws> gaps [inner|outer] <px>
- [x] smart_gaps
- [ ] smart_borders
- [x] bar { border }
- [x] bar { height }
- [x] rgba colors

**Comment by mikkeloscar** [comment]
Do you know what a block is in the context of a bar? I'm trying to figure out how `bar { border }` should be implemented in the config file and the [airblader/i3 docs](https://github.com/Airblader/i3#background--color) mention **individual blocks**, but I'm not sure what those blocks are?

Any idea what `bar { border }` should look like in the config?

**Comment by SirCmpwn** [comment]
That's not a config file option, it's part of the JSON you can send via stdout from status_command to have formatted colors and such.

**Comment by Airblader** [comment]
In your swaybar screenshot from today it seems to me that the gaps are actually implemented incorrectly. The spacing between two windows is double the spacing on the screen edges. This was a bug in the old original gaps patch which I've fixed quite a while ago.

**Comment by SirCmpwn** [comment]
I have the gaps configured like so in that screenshot:

    gaps outer 0
    gaps inner 10

Incorrect?

**Comment by Airblader** [comment]
Your settings are fine, but the gaps implementation is wrong. Using the same gaps settings, see the following screenshot. The gap between the two windows is just as big as the gap between a window and the screen edge, as it should be. In sway this seems to be incorrect because the gap between two windows is double the size of the gap between window and screen edge.

This is (at least in i3) a problem because if you just inset a window, you will naturally run into this problem. What you need to do is divide the gaps by two for edges between two windows.

![screenshot-2015-12-17_07-07-21](https://cloud.githubusercontent.com/assets/2392216/11869324/fd94a85c-a48c-11e5-9349-60220f34a777.png)

**Comment by SirCmpwn** [comment]
I see. The gaps right now are just implemented as margins. I'll see about fixing this, thanks!

**Comment by Airblader** [comment]
Sure, no problem. Does sway support fullscreening nested containers? You might want to check gap behavior there, too, as in i3-gaps I had to do some fixes for it.

**Comment by SirCmpwn** [comment]
As in fullscreening the actual container, instead of views? No, that's not supported, but would probably be fairly easy to do.

**Comment by Airblader** [comment]
We don't really support this in i3 either, but it does work for the most part. It's not really a big deal. I honestly don't see why you'd want to fullscreen nested containers anyway. :)

**Comment by SirCmpwn** [comment]
I could see it being useful if you have a complicated layout going and you want to focus on only some part of it for a while. You're right that I don't consider it a high priority, though. Sway also doesn't support floating containers like i3 does.

**Comment by StephenBrown2** [comment]
I thought that was fixed with #96 ?

**Comment by Airblader** [comment]
Looks like it, yes, but the screenshot I saw from @SirCmpwn had the bug.

**Comment by StephenBrown2** [comment]
Possibly relevant diffs:

layout.c
https://github.com/SirCmpwn/sway/compare/616d630fb028e44359bc6f14d16f94564341c092...master#diff-6323e3c4489ba02f066e3dfbe4e3cbb0L153

https://github.com/SirCmpwn/sway/compare/616d630fb028e44359bc6f14d16f94564341c092...master#diff-6323e3c4489ba02f066e3dfbe4e3cbb0R367

container.c
https://github.com/SirCmpwn/sway/compare/616d630fb028e44359bc6f14d16f94564341c092...master#diff-33eb90e0d9b730214dd88b31235f3c4cL70

https://github.com/SirCmpwn/sway/compare/616d630fb028e44359bc6f14d16f94564341c092...master#diff-33eb90e0d9b730214dd88b31235f3c4cL176

**Comment by nixpulvis** [comment]
I'm a bit new to bar configuration, but is there a way to add margin/gaps around the bar easily too?

**Comment by SirCmpwn** [comment]
Not presently, no.

**Comment by nixpulvis** [comment]
Oh well, might be worth adding a `gaps` set of options to the `bar` config. I know people have accomplished this kind of thing with polyvar, but if my understanding is correct that depends on an X server.

**Comment by emersion** [comment]
We have implement everything in master.

**Comment by BigFonz** [comment]
v
