### ISSUE TITLE
Idle inhibit if a window is focused which matches some criteria

### ISSUE THREAD

**Issue by ddevault** [swaywm/sway#3070]
```
inhibit_idle [criteria] focus|visible|open
```

**Comment by RyanDwyer** [comment]
How about `[criteria] inhibit_idle focus|visible|open`? It'd be less code (don't have to deal with criteria in the command) and users could bind it to a key so it can run on the currently focused view.

**Comment by SirCmpwn** [comment]
Hmm, I'm not sure I like that design.

**Comment by emersion** [comment]
We could also add `inhibit_idle fullscreen` to only inhibit idle if fullscreened.

**Comment by m-khvoinitsky** [comment]
For me it looks like inventing the wheel and making sway do the work of swayidle. 
Shouldn't swayidle just implement org.freedesktop.PowerManagement? The only problem is that I was unable to find a specification for it (all links I found are 404). However, a lot of applications and desktop environments use it.

**Comment by emersion** [comment]
>For me it looks like inventing the wheel and making sway do the work of swayidle.

Nah, applications can inhibit idle for a specific surface, making it possible to e.g. turn off all screens except the ones where a video is playing.
