### ISSUE TITLE
Features from i3 4.16

### ISSUE THREAD

**Issue by orestisf1993** [swaywm/sway#3082]
Like in https://github.com/swaywm/sway/issues/2336#issuecomment-435686783:

- [x] `strip_workspace_name yes|no` - https://i3wm.org/docs/userguide.html#_strip_workspace_numbers_name
- [x] `title_align left|center|right` - https://i3wm.org/docs/userguide.html#_window_title_alignment
- [x] i3-msg: add support for the SUBSCRIBE message type - https://github.com/i3/i3/pull/3435
- [x] `border toggle` now accepts an optional pixel argument - https://i3wm.org/docs/userguide.html#_changing_border_style
- [x] `resize set` now accepts the `width` and `height` keywords - https://i3wm.org/docs/userguide.html#resizingconfig
- [x] allow multiple assignments of workspaces to output - https://i3wm.org/docs/userguide.html#workspace_screen
- [x]  i3-nagbar: add option for button that runs commands without a terminal - https://github.com/i3/i3/pull/3258
- [x] ipc: introduce the sync IPC command for synchronization with i3bar - https://github.com/i3/i3/pull/3214
  - Note: It has been decided sway will not support this fully and just returns `{'success': false}` on `IPC_SYNC`

**Comment by orestisf1993** [comment]
> Am I correct in thinking that having strip_workspace_numbers and strip_workspace_name enabled is invalid?

i3 will only respect one of them if they are both specified.

**Comment by ianyfan** [comment]
There are some more additions outlined in [the release notes](https://github.com/i3/i3/blob/next/RELEASE-NOTES-4.16), e.g. sync command, so don't close this until they've all been sorted.

**Comment by SirCmpwn** [comment]
>There are some more additions outlined in the release notes, e.g. sync command, so don't close this until they've all been sorted.

Can you enumerate these and update the OP?
