### ISSUE TITLE
[Question] Set Variables via bindsym in config

### ISSUE THREAD

**Issue by skaldesh** [swaywm/sway#3093]
I would like to know whether it is possible to set variables via bindsym commands. I will explain my use case, which should make it clear what I want:  

```
        mode "display" {
		# select display
		bindsym 1 mode "display1"
		bindsym 2 mode "display2"
	
		# return to default mode
	        bindsym Backspace mode "default"
	}
	bindsym $mod+m mode "display"

	mode "display1" {
		# enable display
		bindsym c output $dlap enable
		
		# disable display
		bindsym v output $dlap disable

		# return to display mode
		bindsym Backspace mode "display"
	}

	mode "display2" {
		# enable display
		bindsym c output $dhdmi enable
		
		# disable display
		bindsym v output $dhdmi disable

		# return to display mode
		bindsym Backspace mode "display"
	}
```

As you can see, I have a base display mode. Then I can select a display by entering a number (1 and 2 so far). I defined two modes ("display1" and "display2") that essentially contain the exact same commands, just for different displays.  

My Question now: Is there a better way to achieve this? Something like setting some kind of variable, where I store the currently selected display (so pressing 1 sets the display variable to $dlap, pressing 2 sets the display variable to $dhdmi). Then I would not have to duplicate my modes.

**Comment by Marteon** [comment]
You should write a script for this.

**Comment by RedSoxFan** [comment]
I think the following is what you are looking for:

```
set $display $dlap
mode "display" {
    # select the display
    bindsym 1 set $$display $dlap
    bindsym 2 set $$display $dhdmi

    # enable or disable the display
    bindsym c output $$display enable
    bindsym v output $$display disable

    # return to the default mode
    bindsym Backspace mode "default"
}
bindsym $mod+m mode "display"
```

**Comment by skaldesh** [comment]
@RedSoxFan Thank you, exactly what I wanted!  
Do you have an idea, how to make it visible, which display is currently selected? Before, that was indicated by the different modes. I checked the doc with man 5 sway-bar, but I think it is not possible to set the display string for the current mode in a custom manner, right? Any other idea?  

If its not possible out of the box, not bad at all, I am happy with this solution anyways :)

**Comment by RedSoxFan** [comment]
It is not possible to display it in the mode string.

You could write the contents of the display variable to a file before entering the mode and on display change, delete (or empty) the file on mode exit, and read the contents (if it exists) into a custom status line though.
