### ISSUE TITLE
swaylock: PAM doesn't use config file in /usr/local/etc/pam.d.

### ISSUE THREAD

**Issue by c-edw** [swaywm/sway#3096]
This is not an issue with sway or swaylock itself, but may be an installation issue on some systems. I have PAM installed on my Fedora 28 system, but it doesn't use the configuration file installed to `/usr/local/etc/pam.d`. When I use swaylock, it will lock me out because PAM isn't aware of this file. Moving it to `/etc/pam.d` fixes this.

I didn't notice this until now because I just removed the Sway (0.15) package, which places the configuration file at `/etc/pam.d`. 

I assume that anybody building master is supposed to make a symlink or a copy to `/etc/pam.d`, but this should be noted somewhere.

**Comment by progandy** [comment]
Can you try to build with #3178 while setting sysconfdir to ```/etc```? Of course, you'll have to make sure that the files in ```/etc``` aren't conflicting with packages you installed with you package manager, but everything except the pam configuration is in the ```/etc/sway/``` directory

    meson build -Dsysconfdir=/etc 
    ninja -C build
    sudo ninja -C build install

**Comment by c-edw** [comment]
It works well. I am concerned though that needing to specify `-Dsysconfdir` will complicate the process for developers. Shouldn't this be the default, and if not, why?

**Comment by c-edw** [comment]
Closing since the issue has been resolved, though I would like to continue this discussion.
