### ISSUE TITLE
sway freezes on unknown xkb_layout

### ISSUE THREAD

**Issue by chzzzh** [swaywm/sway#3097]
When xkb_layout is set to random string, desktop freezes. Apparently, debug log doesn't show anything interesting, it handles config as usual.

sway version 1.0-beta.1-172-g7fa7f4f4 (Nov 10 2018, branch 'master')
https://pastebin.com/531NVs99

p.s.: you rock 🙂

**Comment by progandy** [comment]
Is it really frozen or is just the keyboard not configured and therefore sway doesn't receive keyboard events?

**Comment by chzzzh** [comment]
> Is it really frozen or is just the keyboard not configured and therefore sway doesn't receive keyboard events?

No, sway received every needed configurations in original instance, I removed the garbage from it before debugging. But even in original one everything seems ok now, so it was kinda random. Sorry for disturbing.
