### ISSUE TITLE
Sway 1.0-beta.1 segfault

### ISSUE THREAD

**Issue by PyroLagus** [swaywm/sway#3099]
I'm using Intel graphics with sway version 54c712f (Oct 21 2018, branch 'master'). Since sway just crashed with a segfault while it was on swayidle, I have no idea how to reproduce this.

Here is the output of `coredumpctl gdb sway` followed by `bt full`: https://gist.github.com/PyroLagus/996c83f4679b8150ea8e0130e953455d

**Comment by RyanDwyer** [comment]
That commit doesn't exist. Anyway, your version is around 3 weeks old and it was likely fixed by 63d076dc2abba0cab6fb78bb2e36088f0b4f9ae5.
