### ISSUE TITLE
swayidle uninterruptable

### ISSUE THREAD

**Issue by JonnyMako** [swaywm/sway#3101]
I start swayidle like so:
```
swayidle timeout 30 'swaylock -c 000000' timeout 60 'swaymsg "output * dpms off"' resume 'swaymsg "output * dpms on"' before-sleep 'swaylock -c 000000'
```
After lock activates, I log back in and now, I can't interrupt swayidle anymore. I have to kill the process.
I can however, interrupt prior to lock activating.
```
2018-11-10 11:36:35 - [swayidle/main.c:93] Failed to send Inhibit signal: Invalid argument
2018-11-10 11:37:05 - [swaylock/main.c:889] Parsing CLI Args
2018-11-10 11:37:05 - [swaylock/main.c:248] output name is eDP-1
```

**Comment by jpoppe** [comment]
Same here, running latest sway/wlroots from Arch AUR, without the _before-sleep_ argument **swayidle** works finr.

**Comment by JonnyMako** [comment]
Yes, this is now fixed. Thanks!
