### ISSUE TITLE
--whole-window for mouse bindings is missing from sway

### ISSUE THREAD

**Issue by milkmiruku** [swaywm/sway#3103]
As title.

**Comment by shibumi** [comment]
yep would be nice to have this feature in sway as well

**Comment by RedSoxFan** [comment]
This is already implemented. If it is not working for you, please provide your config and a debug log.

**Comment by emersion** [comment]
Feel free to re-open if necessary.

**Comment by shibumi** [comment]
```
11/28/18 16:20:50 - [config.c:721] Error on line 67 'bindsym --whole-window $mod+button2 floating toggle': Unknown key '--whole-window' (/home/chris/.config/i3/config)
```

Sway Version: 0.15.2 (on Arch Linux)

CC: @RedSoxFan @emersion

**Comment by shibumi** [comment]
I guess the feature has been added in one of the new alpha or beta releases, correct?

**Comment by emersion** [comment]
Yes.
