### ISSUE TITLE
Sway systemd user service unit

### ISSUE THREAD

**Issue by vivien** [swaywm/sway#3105]
Is it possible to write a systemd user service to run Sway on a system without Desktop Environment or Display Manager?

**Comment by emersion** [comment]
Yes, it should be possible. I have no idea how to do it. I don't think we're interested in having it in our repo.

(You could maybe use the Weston one as a start: https://gitlab.freedesktop.org/wayland/weston/merge_requests/39)

**Comment by vivien** [comment]
The link seems to run Weston as a system-wide service, not a user service, which seems hacky. Starting Sway as a systemd user service would unclutter the shell profile (which is discutably the place to start it), and benefit from environment.d or dependencies such as starting graphical apps wanting sway.service.

**Comment by emersion** [comment]
Sure, I've linked the Weston service to give a starting point, it's not a complete solution.

Feel free to configure your systemd services as you see fit.

**Comment by emersion** [comment]
(As a side note, we don't officially recommend people to start sway in their `.profile` -- I personally just start it from a TTY)

**Comment by vivien** [comment]
Thanks. You type `sway` in your TTY every times you're logged in? What do you guys recommend?

**Comment by SirCmpwn** [comment]
I just type `sway` in at my TTY, too.

**Comment by vivien** [comment]
I hope someone can post a sway.service user unit in this issue soon for reference. In the meantime, I'll type `sway` in the TTY too, this is still much cleaner than polluting the shell profiles, thank you!

**Comment by agboom** [comment]
Hi @vivien, I recently migrated to Sway and ventured the goal to do away of GDM as display manager. Still, I wanted Sway to automatically start at boot, so a systemd service would do justice.

[This gist](https://gist.github.com/agboom/eaec2697e3848cd626f25d428d8c30c6) contains the service I currently use. It's for a HiDPI display, so you may want to adapt it to your needs.

I didn't create the configuration entirely myself, it's an adaptation of [Orbital's](https://github.com/giucam/orbital#running-orbital) example service file (another Wayland compositor).

You're free to use it as you like. If you have any feedback or suggestions for improvement, please leave them in the comment section of the gist snippet. I posted some instructions in the comments.
