### ISSUE TITLE
bindkey does not work with diaeresis (ä,ö,ü)

### ISSUE THREAD

**Issue by cmdcelp** [swaywm/sway#3107]
sway version 1.0-beta.1-2-ga4d68358 (Oct 21 2018, branch 'master')
loads config and works fine, except any key combination with ä,ö or ü , including shift+ä,ö,ü, does not work accordingly.
kernel 4.18.16.a-1
wayland 1.16.0-1

**Comment by emersion** [comment]
You need to use `xev` to find out the name of the keysym you'll use in the config.

**Comment by cmdcelp** [comment]
tested. Yes keysym works. however, shouldn't every key work as is? All media keys etc. just working fine with the xev "key name" as well and they are even manufacturer specific.
