### ISSUE TITLE
No longer able to build sway after commit #27b930d 

### ISSUE THREAD

**Issue by lcandeago** [swaywm/sway#3120]
Using the latest wlroots and sway master from today (13-11) when trying to compile sway I get the following error:
```
../sway/commands/create_output.c:4:24: error: expected value in expression
#if WLR_HAS_X11_BACKEND
                       ^
```
Reverting the #if to #ifdef allows me to compile just fine

**Comment by emersion** [comment]
Can you make sure you have the latest wlroots and sway from git? I think you have an outdated wlroots.

If you still can't build, can you share a copy of your `/usr/include/wlr/config.h`?

**Comment by lcandeago** [comment]
Indeed, I was using the latest master, but previously I had built wlroots without specifying the --prefix=/usr, hence sway was picking up the wlroots version in /usr/local/lib instead of the newly compiled one in /usr/lib
After removing the /usr/local wlroots version it works!

Sorry for the fuzz.
