### ISSUE TITLE
Failed to build in the latest commit # 47cca240

### ISSUE THREAD

**Issue by adouzzy** [swaywm/sway#3123]
git commit:
47cca240 2018-11-13 (HEAD -> master, origin/master, origin/HEAD) Merge pull request #3102 from emersion/render-software-cursors [GitHub]

Error Message:
`
[78/270] Compiling C object 'sway/sway@@sway@exe/desktop_output.c.o'.
FAILED: sway/sway@@sway@exe/desktop_output.c.o
cc -Isway/sway@@sway@exe -Isway -I../sway -Iinclude -I../include -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/local/include -I/usr/local/include/json-c -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/libdrm -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -std=c11 -g -DWL_HIDE_DEPRECATED -DWLR_USE_UNSTABLE -Wno-unused-parameter -Wno-unused-result -Wundef '-DSYSCONFDIR="//usr/local/etc"' '-DSWAY_VERSION="1.0-beta.1-152-g47cca240 (" __DATE__ ", branch '"'"'master'"'"')"' -pthread  -MD -MQ 'sway/sway@@sway@exe/desktop_output.c.o' -MF 'sway/sway@@sway@exe/desktop_output.c.o.d' -o 'sway/sway@@sway@exe/desktop_output.c.o' -c ../sway/desktop/output.c
../sway/desktop/output.c: In function ‘damage_surface_iterator’:
../sway/desktop/output.c:420:3: error: implicit declaration of function ‘wlr_surface_get_effective_damage’; did you mean ‘wlr_surface_get_extends’? [-Werror=implicit-function-declaration]
   wlr_surface_get_effective_damage(surface, &damage);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   wlr_surface_get_extends
cc1: all warnings being treated as errors
[79/270] Compiling C object 'sway/sway@@sway@exe/desktop_render.c.o'.
FAILED: sway/sway@@sway@exe/desktop_render.c.o
cc -Isway/sway@@sway@exe -Isway -I../sway -Iinclude -I../include -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/local/include -I/usr/local/include/json-c -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/libdrm -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -std=c11 -g -DWL_HIDE_DEPRECATED -DWLR_USE_UNSTABLE -Wno-unused-parameter -Wno-unused-result -Wundef '-DSYSCONFDIR="//usr/local/etc"' '-DSWAY_VERSION="1.0-beta.1-152-g47cca240 (" __DATE__ ", branch '"'"'master'"'"')"' -pthread  -MD -MQ 'sway/sway@@sway@exe/desktop_render.c.o' -MF 'sway/sway@@sway@exe/desktop_render.c.o.d' -o 'sway/sway@@sway@exe/desktop_render.c.o' -c ../sway/desktop/render.c
../sway/desktop/render.c: In function ‘output_render’:
../sway/desktop/render.c:1022:2: error: implicit declaration of function ‘wlr_output_render_software_cursors’; did you mean ‘wlr_output_lock_software_cursors’? [-Werror=implicit-function-declaration]
  wlr_output_render_software_cursors(wlr_output, damage);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  wlr_output_lock_software_cursors
cc1: all warnings being treated as errors
[83/270] Compiling C object 'sway/sway@@sway@exe/input_input-manager.c.o'.
ninja: build stopped: subcommand failed.`

**Comment by trobjo** [comment]
I still can't build sway after building wlroots from the current master branch. 

143/259. 
sway/sway@@sway@exe/commands_swap.c.o
Error: test_id defined but not used. [-Werror=unused-function]. 

And then below: 
152/259
sway/sway@@sway@exe/commands_workspace.c.o
ninja: build stopped: subcommand failed. 

Where does meson/ninja keep the log? I only have a tty now (building from a clean install), and I don't know how to copy the output.

**Comment by martinetd** [comment]
Just redirect stdout/stderr to a file, ninja will detect that and write to a file -properly - but really latest wlroots master + sway master works (I tested just now); you must have some old wlroots install not cleaned up, or you reinstalled update to a different path or something.
You need to figure that out, probably from meson output or the actual ninja build file to see what it's compiling.

**Comment by emersion** [comment]
@trobjo It seems your compiler emits a warning that doesn't happen on our setups. Can you try https://github.com/swaywm/sway/pull/3126?

>The interesting thing is I now don't even get to build it

Maybe you have a dirty `build` dir. Can you try to delete it and do it again?

**Comment by trobjo** [comment]
I did just that and now it just complains about wlroots not being installed. That was in fact the initial reason why I installed the Aur build. Is there a flag to make it ignore it, or is that not intended behaviour?

**Comment by trobjo** [comment]
I should perhaps mention that I build both wlroots and sway with xwayland/X11-backend disabled. So far it's been working fine.

**Comment by emersion** [comment]
>I did just that and now it just complains about wlroots not being installed. That was in fact the initial reason why I installed the Aur build. Is there a flag to make it ignore it, or is that not intended behaviour?

It most likely installs wlroots in `/usr/local`, so you need to configure pkg-config to search files there and your linker to search libraries there.

**Comment by martinetd** [comment]
That sounds like wlroots isn't really being installed? How do you install it? If it's not being installed in a standard location you need to tell sway's meson where to find it (with e.g. `PKG_CONFIG_PATH` but that shouldn't be needed for /usr/local iirc)

**Comment by trobjo** [comment]
I exported the environment variables, thank you, and I'm now back to the good old error. The log can be viewed here:
https://transfer.sh/se09A/logforsway

**Comment by emersion** [comment]
Can you try the pull request is mentioned?

**Comment by trobjo** [comment]
Yes. I'll do that first thing in the morning. I'll be back.

**Comment by trobjo** [comment]
Emersion: I saw sircmpwn merged it so I just tried to build from the master branch and it works flawlessly now, thanks!
