### ISSUE TITLE
Focus issues with code completion popups in SublimeText

### ISSUE THREAD

**Issue by SDEagle** [swaywm/sway#3139]
With sway 1.0-beta.1-195-gc36665bc (Nov 16 2018, branch 'master') (and ever since I started using sway when the beta arrived):

When typing in sublime triggers a code completion popup to be opened this causes some weird focus issues.
Sublime always loses focus for a very brief moment (I noticed because sublime has a save on focus lost feature which I had enabled). 
Also, sometimes the completion popup disappears basically immediately after opening.

On Gnome Wayland, this does not happen.
To me this sounds somewhat related to #3007

**Comment by tokyovigilante** [comment]
Also seeing this odd behaviour, particularly annoying as I have both newline-on-save and save-on-focus-lost enabled causing the cursor to jump around.

**Comment by tokyovigilante** [comment]
This seems to be fixed with ST3 dev version 3184. I spoke to their devs about some other Wayland issues (scroll etc) that are now fixed too.

**Comment by SDEagle** [comment]
:thinking: just tried that build out - I didn't get any autocomplete at all - so unable to verify if it's actually fixed. Also while looking through the sublime forums I found this thread https://forum.sublimetext.com/t/build-3183-save-on-focus-lost-and-about-problems/40772/5 so seems like there are still some bugs somewhere... I wonder what Gnome on Wayland does differently so that the whole issue is avoided...

**Comment by tokyovigilante** [comment]
Are you also running up-to-date wlroots/sway? I re-enabled save-on-focus-lost a few days ago and have had no particular issues.

**Comment by SDEagle** [comment]
Yes. Just tried it out again. With sway `1.0-beta.2-93-ga96e8674` and wlroots `0.2.r65.ge2c216a4` and the latest stable sublime (3176) there are still focus issues. I should mention that they changed slightly. Currently, a (supposedly wrong) focus lost event seems to happen whenever to autocomplete popup is closed. The issues on focus beeing lost when the autocomplete popup appears seem to be resolved though. The latest sublime dev build (3184) shows still no autocomplete at all.

**Comment by SDEagle** [comment]
Allright, with sublime dev build 3186 the problem seems to be fixed, so I'm going to close this.
