### ISSUE TITLE
Focus follows mouse not updating on fullscreen change

### ISSUE THREAD

**Issue by tokyovigilante** [swaywm/sway#3149]
I often use two windows side-by-side vertically split (terminal and editor etc) and have noticed focus-follow-s-mouse (FFM) does not always update the window under the mouse correctly after a fullscreen change. 

Example: I have two windows, an editor (left) and terminal (right). If I switch the left window to fullscreen, then move the cursor to right half of the screen, and then switch the window back to normal, I would expect that as the cursor is now over the right window, that window would become active. However I have to move the cursor out of the window, then back in, for it to become active.

Using sway/wlroots master.

**Comment by emersion** [comment]
I think you want `focus_follows_mouse always`.

Maybe related to https://github.com/swaywm/sway/pull/3118

**Comment by tokyovigilante** [comment]
Sorry I've just seen #3081 yeah, that does fix 99% of what I'd like, but focus doesn't change until I move the mouse in the window the mouse is over. I'd rather it updated after the fullscreen switch.
