### ISSUE TITLE
Virtualbox guest on Arch/Sway host is not able to capture the keyboard

### ISSUE THREAD

**Issue by benjaminbauer** [swaywm/sway#3150]
sway version 1.0-beta.1-138-gd19648a3 (Nov  4 2018, branch 'master')

When running a Virtualbox VM, even when Virtualbox tells me, that it captured the keyboard, sway still seems to get "first pick" on any keystroke (e.g. Alt+d, or Mod+1). Is there any way to change the behaviour to what other WMs/OSs do, i.e. every keystroke except for the defined "Host Key" gets only evaluated inside the VM?

**Comment by benjaminbauer** [comment]
Thanks @emersion (Simong?)!
Noob question: Is there a way I can "activate" that protocol simply by configuration, or would this require a change in sway or wayland itself (the protocol in question is still declared "unstable")?

**Comment by emersion** [comment]
>Simong?

Yeah, this is more-or-less how my name is pronounced in French. :)

>Is there a way I can "activate" that protocol simply by configuration, or would this require a change in sway or wayland itself

Unfortunately this requires to implement the protocol in wlroots and in sway. 

It seems Xwayland doesn't support this protocol though. Maybe xwayland-keyboard-grab is the one we need to support? (Or just wait until VirtualBox migrates to Wayland…)

> (the protocol in question is still declared "unstable")

"Unstable" Wayland protocols are not really unstable. It just means that a new major version can be published (if there's a v1 there can be a v2), but they actually have the same stability guarantees as stable protocols (which don't have explicit major version numbers).

**Comment by emersion** [comment]
Fixed in https://github.com/swaywm/sway/pull/5021
