### ISSUE TITLE
Overnight crash while idle

### ISSUE THREAD

**Issue by stsquad** [swaywm/sway#3153]
Sway version:

    sway version 1.0-beta.1 (via Gentoo)

* Sway Version:

No debug log as I wasn't reproducing a problem, it crashed overnight. The logs I do have are:

dmesg:
    [1269386.679311] sway[11165]: segfault at 0 ip 000055844ebe5f34 sp 00007ffd5c3fc4b0 error 4 in sway[55844ebd1000+39000]
    [1269386.679330] Code: 40 08 48 8b 78 08 e8 5b c9 fe ff 48 8d 7b 18 e8 42 c0 fe ff 48 89 df 5b e9 41 cb fe ff 66 0f 1f 84 00 00 00 00 00 41 54 55 53 <83> 3e 01 0f 86 88 00 00 00 48 8b 47 20 48 8d 57 18 48 39 c2 48 8d

core dump:

    (gdb) bt
    #0  0x000055844ebe5f34 in seat_node_from_node ()
    #1  0x000055844ebe6c1f in seat_set_raw_focus ()
    #2  0x000055844ebff6bc in container_begin_destroy ()
    #3  0x000055844ec022a7 in view_unmap ()
    #4  0x000055844ec06257 in handle_unmap ()
    #5  0x00007fe4fa4df50c in wlr_signal_emit_safe () from /usr/lib64/libwlroots.so.0
    #6  0x00007fe4fa4a5c13 in xsurface_unmap () from /usr/lib64/libwlroots.so.0
    #7  0x00007fe4fa4a6eae in x11_event_handler () from /usr/lib64/libwlroots.so.0
    #8  0x00007fe4fa519be2 in wl_event_loop_dispatch (loop=0x558450202f10, timeout=timeout@entry=-1) at /var/tmp/portage/dev-libs/wayland-1.16.0/work/wayland-1.16.0/src/event-loop.c:641
    #9  0x00007fe4fa5187fa in wl_display_run (display=0x558450205700) at /var/tmp/portage/dev-libs/wayland-1.16.0/work/wayland-1.16.0/src/wayland-server.c:1260
    #10 0x000055844ebd315e in main ()
    (gdb) f 0
    #0  0x000055844ebe5f34 in seat_node_from_node ()
    (gdb) x/5i $pc
    => 0x55844ebe5f34 <seat_node_from_node+4>:      cmpl   $0x1,(%rsi)
       0x55844ebe5f37 <seat_node_from_node+7>:      jbe    0x55844ebe5fc5 <seat_node_from_node+149>
       0x55844ebe5f3d <seat_node_from_node+13>:     mov    0x20(%rdi),%rax
       0x55844ebe5f41 <seat_node_from_node+17>:     lea    0x18(%rdi),%rdx
       0x55844ebe5f45 <seat_node_from_node+21>:     cmp    %rax,%rdx
    (gdb) p/x $rsi
    $1 = 0x0

So it looks like a NULL dereference. Unfortunately the debug symbols don't give much additional information in this build. Looking at the backtrace I wonder if this was triggered by a client crashing or exiting overnight?

I'll see if I can generate a reproducer.

**Comment by stsquad** [comment]
My thoughts could be the disappearing client might have been an ssh client in a terminal shell timing out overnight.

**Comment by stsquad** [comment]
I rebuilt with debug symbols enabled which should (in theory) still match the binary/coredump I have:

    (gdb) bt
    #0  seat_node_from_node (seat=0x55845042d020, node=0x0) at ../sway-1.0-beta.1/sway/input/seat.c:193
    #1  0x000055844ebe6c1f in seat_set_raw_focus (seat=0x55845042d020, node=0x0) at ../sway-1.0-beta.1/sway/input/seat.c:633
    #2  0x000055844ebff6bc in wl_signal_emit (data=0x55845058d060, signal=0x55845058d090) at /usr/include/wayland-server-core.h:468
    #3  container_begin_destroy (con=0x55845058d060) at ../sway-1.0-beta.1/sway/tree/container.c:90
    #4  0x000055844ec022a7 in view_unmap (view=view@entry=0x55845058bb20) at ../sway-1.0-beta.1/sway/tree/view.c:635
    #5  0x000055844ec06257 in handle_unmap (listener=0x55845058bdb0, data=<optimized out>) at ../sway-1.0-beta.1/sway/desktop/xwayland.c:378
    #6  0x00007fe4fa4df50c in wlr_signal_emit_safe () from /usr/lib64/libwlroots.so.0
    #7  0x00007fe4fa4a5c13 in xsurface_unmap () from /usr/lib64/libwlroots.so.0
    #8  0x00007fe4fa4a6eae in x11_event_handler () from /usr/lib64/libwlroots.so.0
    #9  0x00007fe4fa519be2 in wl_event_loop_dispatch (loop=0x558450202f10, timeout=timeout@entry=-1) at /var/tmp/portage/dev-libs/wayland-1.16.0/work/wayland-1.16.0/src/event-loop.c:641
    #10 0x00007fe4fa5187fa in wl_display_run (display=0x558450205700) at /var/tmp/portage/dev-libs/wayland-1.16.0/work/wayland-1.16.0/src/wayland-server.c:1260
    #11 0x000055844ebd315e in main (argc=<optimized out>, argv=<optimized out>) at ../sway-1.0-beta.1/sway/main.c:404
    
I was an XWAYLAND client that died:

    (gdb) f 5
    #5  0x000055844ec06257 in handle_unmap (listener=0x55845058bdb0, data=<optimized out>) at ../sway-1.0-beta.1/sway/desktop/xwayland.c:378
    378             view_unmap(view);
    (gdb) p view
    $3 = (struct sway_view *) 0x55845058bb20
    (gdb) p *$
    $4 = {type = SWAY_VIEW_XWAYLAND, impl = 0x55844ec21b60 <view_impl>, container = 0x55845058d060, surface = 0x558450638490, xdg_decoration = 0x0, pid = 22985, x = 1682, y = 27, width = 1916, height = 1146, saved_x = 0, saved_y = 0, saved_width = 0, saved_height = 0, natural_width = 884, natural_height = 532, title_format = 0x0, border = B_NORMAL, saved_border = B_NONE, using_csd = false, border_thickness = 2, border_top = false, border_bottom = true, border_left = true, border_right = true, urgent = {tv_sec = 0, tv_nsec = 0}, allow_request_urgent = true, urgent_timer = 0x0, saved_buffer = 0x0, saved_buffer_width = 1916, saved_buffer_height = 1146, geometry = {x = 0, y = 0, width = 1916, height = 1146}, saved_geometry = {x = 0, y = 0, width = 1916, height = 1146}, destroying = false, executed_criteria = 0x5584505759b0, marks = 0x558450521510, marks_focused = 0x0, marks_focused_inactive = 0x0, marks_unfocused = 0x0, marks_urgent = 0x0, {wlr_xdg_surface_v6 = 0x55845042de80, wlr_xdg_surface = 0x55845042de80, wlr_xwayland_surface = 0x55845042de80, wlr_wl_shell_surface = 0x55845042de80}, events = {unmap = {listener_list = {prev = 0x55845058bc38, next = 0x55845058bc38}}}, surface_new_subsurface = {link = {prev = 0x0, next = 0x0}, notify = 0x55844ec025e0 <view_handle_surface_new_subsurface>}}

From the window title I'm fairly sure it was a ssh terminal that died overnight (possibly while the screen was locked).

**Comment by stsquad** [comment]
@RyanDwyer ahh ok - the 1.0-beta.1 only just dropped in the gentoo repos. I'll switch to the -9999 version (git head) and see if it happens again - unless a new beta is likely to be tagged soon.

**Comment by emersion** [comment]
Closing for now - please re-open if you can reproduce with the latest sway/wlroots commit.

**Comment by stsquad** [comment]
@emersion no that's fine. It hasn't re-occurred since and I haven't restarted the session since I moved up to the -9999 build.
