### ISSUE TITLE
firefox update notifications appears centered insteadof at the menu

### ISSUE THREAD

**Issue by mathroc** [swaywm/sway#3154]
when there's an update notification (try the nightly channel to get one every now and then) instead of appearing near the menu hamburger icon, it appears centered on the window

**Comment by ascent12** [comment]
I'm not using Firefox nightly right now, so I haven't confirmed this, but I assume that firefox is opening these windows as new wayland surfaces. In wayland, the client has no control of how it's placed, and sway is just doing its default of putting it into the middle. We're not going to add client-specific hacks.

I'd recommend using a notification daemon such as [mako](https://github.com/emersion/mako) instead, which firefox can use, and will correctly place the notification.

**Comment by mathroc** [comment]
I'm not sure this is it, I'm using make and it works well for web notifications. the "update notification" is something different

it's similar to this:

![screenshot_2018-11-19_15 45 35](https://user-images.githubusercontent.com/291531/48714106-3e161080-ec12-11e8-9922-777d5795c716.png)

but not exactly like this because this one is correctly positioned, I'll post a screenshot when I get a new notification

besides, the "update notification" was positioned correctly before the beta

**Comment by emersion** [comment]
Seems like an xwayland issue.

**Comment by mathroc** [comment]
it didn't take long to have another one:

![screenshot_2018-11-19_16 39 36](https://user-images.githubusercontent.com/291531/48717484-cf3cb580-ec19-11e8-8bb6-0b53af240f9a.png)

@emersion even though it worked with sway 0.15 you think it could be related to xwayland and not sway ?

**Comment by emersion** [comment]
I mean, it's probably a bug in sway that happens for xwayland clients.

**Comment by mathroc** [comment]
ok :+1:  I'm leaving this open then

**Comment by emersion** [comment]
Can you confirm your Firefox is using Xwayland and not Wayland directly?
