### ISSUE TITLE
default_orientation auto does not work on transformed output

### ISSUE THREAD

**Issue by marienz** [swaywm/sway#3156]
On sway version 1.0-beta.1-209-g67d24e8f (Nov 19 2018, branch 'HEAD'), a monitor rotated to portrait (`transform 90` or `transform 270`) defaults to horizontal layout for tiled containers. It should default to vertical layout instead (with the default `default_orientation` of `auto`).

It looks like this was introduced by the fix for #3015, which moved `apply_output_config` after workspace initialization to fix a crash (when `apply_output_config` triggered an output layout change, it ended up in layout code that assumed the output had a workspace). That change causes this issue because `output_get_default_layout` (called from `workspace_create`) looks at `output->height` and `output_width`, which now do not yet have the configured transform applied to them.

(The revision history is a little confusing: the relevant commit is cd0bae80b6f1cc27ffff47618b4332449468134c, but the crash referenced in its commit message was fixed differently. See discussion on #2993.)

I'm not sure what the correct fix is (if I did I'd be opening a pull request instead of an issue...):

- Keep calling `apply_output_config` after creating the default workspace, but fix up the orientation of the default workspace after that. This is probably the easiest fix to implement, but seems a little messy: we'd have to remember whether we created a default workspace, and I don't know if `apply_output_config` can end up in code that needs the default layout to already be correct (or worse: affect workspace/layout configuration, which our layout fixup then interferes with).

- Change `apply_output_config` to not synchronously trigger a layout change, and move it back before workspace initialization. I'm not sufficiently familiar with sway's event loop and/or the wlroots event system to know what this would look like. If feasible, we wouldn't have to temporarily have a workspace with the wrong layout.

If you give me some pointers on what a fix should look like, I'm happy to take a stab at it.

For completeness, see https://gist.github.com/marienz/b68168590660cef20cfa2091a40bbd0f for my config, log output, "swaymsg -t get_outputs", and "swaymsg -t get_tree" after creating two windows on the monitor with the wrong layout. The config is not very minimal, but it's mostly keybinds that should be easy enough to ignore.

(A careful reader of the config and log output will spot some "subpixel" stuff that doesn't exist in upstream sway... that's a local patch that doesn't affect layout, but is neither useful nor sane enough to submit. Let me know if that's an issue and I'll get rid of it.)

**Comment by AIceste** [comment]
Any chance this has been happening again for the past year or so? Did not look into it much yet (yes, 1year of procrastinating), but a working config suddenly stopped working for me for my vertical monitor some while ago and i'm thinking maybe the same issue was modified-in again without consideration for the history behind this fix. 

I'm hoping to get to it eventually, but I figured in the meantime I might as well ask around. 

Thanks,

**Comment by marienz** [comment]
I'm not currently seeing this on Sway 1.10.1 (with no recent relevant changes to my config: `default_orientation` not specified, so I should get the "default default"): I get vertical splits on a vertical monitor, horizontal splits on a horizontal monitor.

(If it happened on older Sway versions I would *probably* have noticed. I don't think I'm running Sway 1.11 yet anywhere, but since 1.10 released a little under a year ago if this was broken in a release it couldn't be 1.11 to fit your timeline.)

**Comment by AIceste** [comment]
Aight thanks for letting me know. I'll probably try to identify what part of my config is causing it & creating a separate issue at some point then.

Edit (for completion for the time being):

Version is 1.11.

This is only an issue for the workspaces created by default at sway startup, in my case "1" and "2". If from the vertical output I navigate to a different workspace assigned to no output or to another workspace on that output, it will be working as expected*.

Refresh (super_L + shift + r on default config) does not fix it, but setting the tiling direction once fixes it for all subsequent refresh (meaning I can only reproduce reliably by restarting sway).

*This also means that the issue can be patched by adding workspace command(s) to run at startup -- one to open a workspace assigned to the vertical display and, if desired, another to go back to the default workspace.

**Comment by marienz** [comment]
> This is only an issue for the workspaces created by default at sway startup

Ah, you're right, I can reproduce that on Sway 1.10.1 too. I wasn't testing with a freshly-started Sway when I left my previous comment, and it hadn't occurred to me "initial workspace" might matter.
