### ISSUE TITLE
Missing IPC scratchpad replies/move events

### ISSUE THREAD

**Issue by mihaicmn** [swaywm/sway#3159]
I want to implement a module for a custom status bar which shows information about scratchpad containers.

For this I need a way to be notified when a container is added/removed to/from scratchpad.

My proposal would be to add a new IPC_EVENT_SCRATCHPAD event type and new events for each root_scratchpad_{add_container,remove_container,show,hide} method. This is similar to workspace events.

If this is acceptable I'll submit a PR.

Any feedback is appreciated.

**Comment by emersion** [comment]
I think you can already do this with move events?

(See e.g. https://github.com/acrisci/i3-dstatus/blob/master/i3dstatus/generators/scratchpad)

**Comment by mihaicmn** [comment]
In i3 get_tree's reply contains the hidden scratchpad windows as floating nodes on the "__i3_scratch" workspace which belongs to the "__i3" output. Should we keep the same approach for sway or is it acceptable adding a new json object, called "scratchpad", within the root json object?

Also moving a window to/from scratchpad does trigger move events in i3.
