### ISSUE TITLE
What can i3blocks and i3blocks-contrib do to support sway?

### ISSUE THREAD

**Issue by kb100** [swaywm/sway#3164]
Hi, I'm the maintainer of the [i3blocks-contrib](https://github.com/vivien/i3blocks-contrib) repo. [i3blocks](https://github.com/vivien/i3blocks) is a scheduler built for customizing the output to i3bar. The scheduler is language agnostic, i.e. scripts can be written in whatever language you prefer. The i3blocks-contrib repository holds many different scripts that may be helpful for customizing your i3bar. Since sway is meant to be a drop-in replacement for i3, undoubtedly some of your users will be coming from a setup using i3blocks and i3blocks-contrib.

This is not a request to make sway work with i3blocks. This IS a request for information about anything that i3blocks and i3blocks-contrib can do to help you and your users integrate i3blocks as part of their setup. So with that in mind, some basic questions:

1. Does it make sense long term for your users to use i3blocks with swaybar, or does swaybar contain its own agnostic scheduler that makes i3blocks not relevant for sway users (except possibly those migrating from i3)?

2. Have you or any of your users complained of i3blocks not working for their setup? If so, were any specific blocks at fault? (E.g. if a block depended on xtitle, obviously it would not work with sway).

3. Are there any "gotchas" that block writers should keep in mind that may not be obvious, e.g. global environmental variables that should not be overwritten etc.?

Even if nothing comes to mind currently, please feel free at any point to direct users having troubling with i3blocks+swaybar over to our repositories (to i3blocks-contrib if it is script related), or to let us know of anything we can do to help ease integration issues on your end.

Highly anticipating the sway package in debian, your work is greatly appreciated.

**Comment by RedSoxFan** [comment]
Closing since I don't think this needs to remain open. I'm not aware of any issues using i3blocks with sway. If there are any future issues in getting something i3blocks related to work with sway, feel free to stop by the IRC channel
