### ISSUE TITLE
Sway coredumps (Illegal instruction) on qemu x64

### ISSUE THREAD

**Issue by twitchyliquid64** [swaywm/sway#3165]
Debug Log: https://pastebin.com/UWaHjJfN

Configuration: No (default) configuration (sway is installed via `ninja install` into the system).

### Reproduction

1. Start QEMU with `sudo qemu-system-x86_64 -enable-kvm -smp 2 -m 4G -drive format=raw,file=disk.img`
2. Login to the TTY (this is a systemd system so `pam_systemd.so` sets up the session).
3. Run `sway` or `sway -d`
4. Grey screen & cursor is observed for a fraction of a second, before `Illegal instruction (core dumped)`.

Works fine on the one piece of real hardware I tested.

I also tried the `beta` version released on githu,b & I also tried with kvm disable. Same issue for both.

### Versions
```
> qemu-system-x86_64 --version
QEMU emulator version 2.11.1(Debian 1:2.11+dfsg-1ubuntu7.6)
Copyright (c) 2003-2017 Fabrice Bellard and the QEMU Project developers

> sway -v
sway version 1.0-beta.11-213-gcecf00b9 (Nov 20 2018, branch 'master')
```

`wlroots` is also head at time of writing (040d62de0076a349612b7c2c28c5dc5e93bb9760).

libffi is was downloaded from: ftp://sourceware.org/pub/libffi/libffi-3.2.1.tar.gz, and is version `3.2.1`. The test suite passed successfully following build.

Linux: `4.18.5`.
Wayland: `1.12.0`
Wayland-protocols: `1.16`

### Core dumps

[Sway binary](https://pastebin.com/v2GXUccZ)

[Swaybg + sway binary - short](https://pastebin.com/B8UfMRwu)

### Other

![Crash](https://user-images.githubusercontent.com/6328589/48818361-d807b700-ecff-11e8-8922-412e691682ec.png)
![Environment variables](https://user-images.githubusercontent.com/6328589/48818365-da6a1100-ecff-11e8-9105-0613547c4104.png)

**Comment by emersion** [comment]
Can you obtain a stack trace? (`coredumpctl gdb sway` then `bt full`)

Not sure we can do anything about an "illegal instruction". Maybe try recompiling on your VM?

**Comment by martinetd** [comment]
If it's an optimization thing try running qemu with an addition `-cpu host` switch, that might help

**Comment by twitchyliquid64** [comment]
Stack traces are in the _coredump_ section, sorry about my english.

Normally 'illegal instruction' means the stack was messed up, and the return pointer was corrupted (pointed to a place in an executable page that happened to be an invalid instruction).

**Comment by martinetd** [comment]
Welcome to recent gcc versions that enable optimizations which require hardware feature not present in "bare" VMs - most virtualization tools will enable a subset of -cpu host which would make this work though.

If you really care about this you can pass some CFLAGS like `-mtune=generic` when building... virtually everything (your problem is in libffi).

Closing this for now, this isn't a sway issue.
