### ISSUE TITLE
Screen output interlaced modes...

### ISSUE THREAD

**Issue by pauledd** [swaywm/sway#3167]
Hi
using sway version 1.0-beta on gentoo linux with mesa/1.20 and intel/modesettings driver on my skylake IGPU
inspecting possible outputs:

```
swaymsg -t get_outputs
Output HDMI-A-1 'Unknown BenQ GL2460 53E00568SL0'
  Current mode: 1920x1080 @ 50.000000 Hz
  Position: 0,0
  Scale factor: 1.000000
  Transform: normal
  Workspace: 1
  Available modes:
    720x400 @ 70.082001 Hz
    640x480 @ 59.939999 Hz
    640x480 @ 60.000000 Hz
    640x480 @ 75.000000 Hz
    720x480 @ 59.939999 Hz
    720x480 @ 60.001999 Hz
    720x480 @ 59.939999 Hz
    720x480 @ 60.000000 Hz
    720x576 @ 50.000000 Hz
    720x576 @ 50.000000 Hz
    800x600 @ 60.317001 Hz
    800x600 @ 75.000000 Hz
    832x624 @ 74.551003 Hz
    1024x768 @ 60.004002 Hz
    1024x768 @ 75.028999 Hz
    1280x720 @ 50.000000 Hz
    1280x720 @ 59.939999 Hz
    1280x720 @ 60.000000 Hz
    1152x864 @ 75.000000 Hz
    1280x800 @ 59.910000 Hz
    1280x1024 @ 60.020000 Hz
    1280x1024 @ 75.025002 Hz
    1600x900 @ 60.000000 Hz
    1680x1050 @ 59.882999 Hz
    1920x1080 @ 50.000000 Hz
    1920x1080 @ 50.000000 Hz
    1920x1080 @ 59.939999 Hz
    1920x1080 @ 60.000000 Hz
    1920x1080 @ 59.939999 Hz
    1920x1080 @ 60.000000 Hz
```
I want 1920x1080 @ 50.000000 Hz non Interlaced but what do I have to put into my sway config?
I currently have:
`output HDMI-A-1 mode 1920x1080@50Hz bg /usr/share/backgrounds/sway/Sway_Wallpaper_Blue_1920x1080.png fill`
and that starts my screen in interlaced mode... not usable at all, how do you distinguish between the mode interlaced and not interlaced output?

**Comment by emersion** [comment]
We should probably filter these interlaced modes out with `DRM_MODE_FLAG_INTERLACE`.

**Comment by pauledd** [comment]
Slightly offtopic... If I start my old X-Window system instead of sway/wayland than xrandr shows me the different interlaced modes with a small "i" right after the resolution so that I can choose what to set...

```
 xrandr 
Screen 0: minimum 320 x 200, current 1920 x 1080, maximum 8192 x 8192
HDMI-1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 531mm x 299mm
   1920x1080     60.00 +  50.00*   59.94  
   1920x1080i    60.00    50.00    59.94  
   1680x1050     59.88  
   1600x900      60.00  
   1280x1024     75.02    60.02  
   1280x800      59.91  
   1152x864      75.00  
   1280x720      60.00    50.00    59.94  
   1024x768      75.03    60.00  
   832x624       74.55  
   800x600       75.00    60.32  
   720x576       50.00  
   720x576i      50.00  
   720x480       60.00    59.94  
   720x480i      60.00    59.94  
   640x480       75.00    60.00    59.94  
   720x400       70.08
```

**Comment by emersion** [comment]
And what happens if you choose an interlaced mode there? Does it work?

**Comment by pauledd** [comment]
I dont have to set anything special in X-Window mode... it defaults to 1920x1080 non-interlaced, but I then later do a "xrandr -r 50" to set my Monitor to 50Hz.
But yes... If I do a "xrandr --output HDMI-1 --mode 1920x1080i" it changes to interlaced.. but as I said, I need not-Interlaced ;)
And I need 50Hz and thats the reason I changed the option line in sway config. If I dont specify it in the sway config and leave the default setting:
`output * bg /usr/share/backgrounds/sway/Sway_Wallpaper_Blue_1920x1080.png fill`
then sway starts in 1080 non interlaced... but of cause not in my desired 50hz...

**Comment by emersion** [comment]
Okay. So

- A temporary fix would be to filter out interlaced modes
- A better fix would be to let users choose between interlaced and non-interlaced modes

**Comment by pauledd** [comment]
>     * A temporary fix would be to filter out interlaced modes
To be honest, I've never ever heard of anyone who needed interlaced output, but maybe there are still some cathode ray tube users out there who need this... 

But then sway sould maybe  not default to interlaced when a mode is configured in the config file with "Hz" specified. If I set output to:
`output HDMI-A-1 mode 1920x1080`
then it does not do interlaced but as soon as I add "*Hz" to the resolution it uses the interlaced mode not matter if 50 or 60Hz ...

**Comment by atomnuker** [comment]
I agree, just filter out interlaced modes until someone complains. I've been doing that for months and haven't encountered problems not getting a good mode on any displays.

**Comment by emersion** [comment]
Okay, this makes sense. @atomnuker Can you send your patch as a PR?

**Comment by pauledd** [comment]
hm, so I pulled sway and wlroots master again and recompiled and installed but I still get a interlaced video signal if I have specified a "Hz" value in my config:
`output HDMI-A-1 mode 1920x1080@50Hz`
` swaymsg -t get_version
sway version 1.0-beta.1-213-gcecf00b9 (Nov 22 2018, branch 'master')`
Did I miss something?

**Comment by emersion** [comment]
What's the output of `swaymsg -t get_outputs`?

**Comment by pauledd** [comment]
```
swaymsg -t get_outputs
Output HDMI-A-1 'Unknown BenQ GL2460 53E00568SL0'
  Current mode: 1920x1080 @ 50.000000 Hz
  Position: 0,0
  Scale factor: 1.000000
  Transform: normal
  Workspace: 1
  Available modes:
    720x400 @ 70.082001 Hz
    640x480 @ 59.939999 Hz
    640x480 @ 60.000000 Hz
    640x480 @ 75.000000 Hz
    720x480 @ 59.939999 Hz
    720x480 @ 60.001999 Hz
    720x480 @ 59.939999 Hz
    720x480 @ 60.000000 Hz
    720x576 @ 50.000000 Hz
    720x576 @ 50.000000 Hz
    800x600 @ 60.317001 Hz
    800x600 @ 75.000000 Hz
    832x624 @ 74.551003 Hz
    1024x768 @ 60.004002 Hz
    1024x768 @ 75.028999 Hz
    1280x720 @ 50.000000 Hz
    1280x720 @ 59.939999 Hz
    1280x720 @ 60.000000 Hz
    1152x864 @ 75.000000 Hz
    1280x800 @ 59.910000 Hz
    1280x1024 @ 60.020000 Hz
    1280x1024 @ 75.025002 Hz
    1600x900 @ 60.000000 Hz
    1680x1050 @ 59.882999 Hz
    1920x1080 @ 50.000000 Hz
    1920x1080 @ 50.000000 Hz
    1920x1080 @ 59.939999 Hz
    1920x1080 @ 60.000000 Hz
    1920x1080 @ 59.939999 Hz
    1920x1080 @ 60.000000 Hz
```
Thats how it looks like: https://www.youtube.com/watch?v=B77-_0YWYPk

**Comment by emersion** [comment]
Seems like wlroots hasn't been updated. How are you installing sway? Can you run `ldd $(which sway)`?

**Comment by emersion** [comment]
Seems like the fix had an issue (https://github.com/swaywm/wlroots/pull/1385). Can you try again updating wlroots?

**Comment by pauledd** [comment]
Works now. Thanks :)

```
 swaymsg -t get_outputs
Output HDMI-A-1 'Unknown BenQ GL2460 53E00568SL0'
  Current mode: 1920x1080 @ 50.000000 Hz
  Position: 0,0
  Scale factor: 1.000000
  Transform: normal
  Workspace: 1
  Available modes:
    720x400 @ 70.082001 Hz
    640x480 @ 59.939999 Hz
    640x480 @ 60.000000 Hz
    640x480 @ 75.000000 Hz
    720x480 @ 59.939999 Hz
    720x480 @ 60.000000 Hz
    720x576 @ 50.000000 Hz
    800x600 @ 60.317001 Hz
    800x600 @ 75.000000 Hz
    832x624 @ 74.551003 Hz
    1024x768 @ 60.004002 Hz
    1024x768 @ 75.028999 Hz
    1280x720 @ 50.000000 Hz
    1280x720 @ 59.939999 Hz
    1280x720 @ 60.000000 Hz
    1152x864 @ 75.000000 Hz
    1280x800 @ 59.910000 Hz
    1280x1024 @ 60.020000 Hz
    1280x1024 @ 75.025002 Hz
    1600x900 @ 60.000000 Hz
    1680x1050 @ 59.882999 Hz
    1920x1080 @ 50.000000 Hz
    1920x1080 @ 59.939999 Hz
    1920x1080 @ 60.000000 Hz
```
