### ISSUE TITLE
On-screen keyboard does not work

### ISSUE THREAD

**Issue by JonnyMako** [swaywm/sway#3172]
`virtboard` does not work. On starting the keyboard, I get the following:

```
No input method manager global, some functionality unavailable
Could not register to session manager: Cannot invoke method; proxy is for a well-known name without an owner and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag
```
I'm on:

```
sway -v
sway version 1.0-beta.1-211-gbf7af9c6 (Nov 20 2018, branch 'master')
```

**Comment by emersion** [comment]
`input-method` is implemented in wlroots, but not in sway.

**Comment by tokyovigilante** [comment]
I'm hoping to work on this once I finish implementing switch events.

**Comment by ianyfan** [comment]
> Can you check if the dbus invokation works?
> 
> ```
> busctl call --user sm.puri.OSK0 /sm/puri/OSK0 sm.puri.OSK0 SetVisible b true
> ```
> 
> The keyboard should appear after this.

https://github.com/swaywm/sway/pull/2376#issuecomment-441193511

**Comment by JonnyMako** [comment]
Why is this closed? Has `input-method` been implemented in Sway?

**Comment by emersion** [comment]
input-method has not been implemented yet. This is a separate issue from the one you reported though, so I'm opening a new one: https://github.com/swaywm/sway/issues/3407

virtboard should work without input-method (see the logs: "some functionality unavailable"). You didn't reply to dcz here: https://github.com/swaywm/sway/pull/2376#issuecomment-441193511

**Comment by JonnyMako** [comment]
ok, thanks. I missed that.
