### ISSUE TITLE
tree/root.c: possible memory leak

### ISSUE THREAD

**Issue by baloo** [swaywm/sway#3180]
I might be missing something, but I believe there is a memory leak in https://github.com/swaywm/sway/blob/master/sway/tree/root.c#L240

The `pw` pointer and `pw->workspace` are lost when the function exits which yields a memory leak.
related to #2165

**Comment by emersion** [comment]
The `pw` struct is inserted to the `pid_workspaces` list, which is then [free'd later](https://github.com/swaywm/sway/blob/master/sway/tree/root.c#L228-L238).
