### ISSUE TITLE
Sway reinterprets display position if displays are identified by unique name

### ISSUE THREAD

**Issue by TheChymera** [swaywm/sway#3186]
* Sway Version:  1.0-beta.1

* Debug Log: http://bpaste.net/show/66b7401a82ea (this log includes sway launch with the broken configuration and switching mid-session to the fixed configuration).

* Configuration File:
  * broken: http://bpaste.net/show/af932b2faac9
  * fixed: http://bpaste.net/show/0ef352cc96f3

* `swaymsg -t get_outputs` for reinterpreted display position when identifying monitors by name (“broken” config above): https://bpaste.net/show/75d17a7b6138

It appears that whenever I identify the monitors by their proper names (make+model+serial), the coordinates of my primary display are adjusted so that it lies to the right side of the secondary display (incidentally I want it precisely the other way around). This is fixed by configuring the outputs with the displayport handle, though it should work either way. Additionally the current “fix” is incomplete, since different monitors, which by their nature require different positioning, may be attached to the same display port.

Additionally there seems to be some ambiguity regarding the nomenclature. What is used as a “name” in the man page seems to correspond not to the “name” field in the `get_outputs` JSON, but rather to make+model+serial.

**Comment by emersion** [comment]
Please use `position x y` instead of `position x,y`. The latter is causing issues with i3's syntax to execute multiple commands.

**Comment by TheChymera** [comment]
@emersion I have switched to that, however, the issue appears just the same.

**Comment by RedSoxFan** [comment]
For nomenclature, `name` is used to refer to the port and `identifier` is used to refer to the `<make> <model> <serial>` string. The term `identifier` is not used directly in the IPC or man page, but `sway-output(5)` does specify that the `<make> <model> <serial>` string can be used in place of `name`.

As for your issue, it appears to just  be a typo in the serial portion of the identifier you have connected via `eDP-1`. In your config, you have `Unknown 0x492D 0x0000000` (7 zeroes), but the actual identifier should be `Unknown 0x492D 0x00000000` (8 zeroes).
