### ISSUE TITLE
sway crashes display without a clear error message when XDG_RUNTIME_DIR isn't set

### ISSUE THREAD

**Issue by BetaRays** [swaywm/sway#3187]
After installing sway 1.0-beta.1 on Gentoo, simply running `sway` (or `sway -C`) makes my display crash (I cannot switch TTYs).
By redirecting the output to a file and viewing it through SSH, I can see an error message about XDG_RUNTIME_DIR.

Would it be possible to output the error message without locking the display?

**Comment by emersion** [comment]
Please post full debug logs.

**Comment by BetaRays** [comment]
@emersion https://ptpb.pw/GJ5K
As you can see there is a line about XDG_RUNTIME_DIR:
> error: XDG_RUNTIME_DIR not set in the environment
But I can't see this line without redirecting the log elsewhere (and if it's a file you have to sync using sysrq) since it freezes my display before displaying it.

**Comment by ianyfan** [comment]
> `wlr_backend_destroy` is supposed to reset everything properly

Has this been addressed?

**Comment by emersion** [comment]
No, so if we fail for another reason, we might also freeze the system. I suspect this is a bug in wlroots' direct session.

**Comment by BetaRays** [comment]
By the way, having a file instead of a directory in XDG_RUNTIME_DIR does the same thing.

**Comment by emersion** [comment]
Well there's `_DIR` in the name…

**Comment by BetaRays** [comment]
Yes, it's less likely to pose problems, but the problem can still be triggered.

**Comment by emersion** [comment]
I agree that `wlr_backend_destroy` should work

**Comment by BetaRays** [comment]
So is it a wlroots issue and not a sway issue?

**Comment by emersion** [comment]
Needs investigation. Maybe we forget to destroy the backend/display in sway.
