### ISSUE TITLE
Swayidle high CPU usage after pull request #3049

### ISSUE THREAD

**Issue by Bryophyllum** [swaywm/sway#3190]
Swayidle sits at 100% CPU usage after a Sway session has been started.
The bug may have been introduced in https://github.com/swaywm/sway/commit/d46d221118f7b4ffeb0fe0fcba296fbbd78a0cbd.

**Comment by emersion** [comment]
How do you start it? I don't have such issues.

**Comment by Bryophyllum** [comment]
I use an alias `sway="export XKB_DEFAULT_LAYOUT=de && export QT_QPA_PLATFORM=wayland-egl && export QT_WAYLAND_DISABLE_WINDOWDECORATION="1" && sway"`

```This is my Swayidle config:
### Idle configuration
exec swayidle \
        timeout 600 "brightnessctl --save --device=acpi_video0 && brightnessctl set 10% --device=acpi_video0" \
        resume 'brightnessctl --restore --device=acpi_video0' \
        timeout 3600 'swaymsg "output * dpms off"' \
        resume 'swaymsg "output * dpms on"' \
```
