### ISSUE TITLE
Right-click does not work after workspace change on X11 backend

### ISSUE THREAD

**Issue by mithodin** [swaywm/sway#3193]
Sway version: sway version 1.0-beta.1-237-g0ebb4107 (Nov 26 2018, branch 'master') with wlroots b5093a94
[sway.log](https://github.com/swaywm/sway/files/2615169/sway.log)

I am using the X11 backend. If I switch between workspaces, I can type and left-click in the window I have changed to, but not right-click. In some dialogs (e.g. file select), left-click also does not work. This is fixed by pressing enter or typing into any text field. This is 100% reproducible. I did not encounter this problem with the beta.1 release at the time.

Also, on a system with a non-shitty gpu where I can use wayland directly, this problem is not observed with the same release.

**Comment by RedSoxFan** [comment]
Are you still able to reproduce this?

**Comment by mithodin** [comment]
Yes, as of right now (wlroots fe187fc8, sway 9abac858) the problem persists.

**Comment by RedSoxFan** [comment]
Would you be able to provide some concrete reproduction steps? I'm not able to replicate it based off of your description

**Comment by mithodin** [comment]
Step 1: open a program that is interactable with right-click (e.g. a browser) on workspace n.

Step 2: Switch to workspace k ≠ n via keyboard shortcut (it does not occur if the switch is triggered via mouse click in the status bar).

Step 3: switch back to workspace n

Step 4: right-click anywhere in the program. The program does not respond.

Step 5: press any key. The program now responds to right clicks again.

As I said, this happens 100% of the time.

**Comment by RedSoxFan** [comment]
> Step 2: Switch to workspace k ≠ n via keyboard shortcut (it does not occur if the switch is triggered via mouse click in the status bar).
> Step 5: press any key. The program now responds to right clicks again.

Since you are using the x11 backend, what are you running sway inside of? It sounds like there may be some interference/conflict.

**Comment by mithodin** [comment]
I am starting sway via an .xinitrc script called from lightdm. I can post the script if it helps.

However, if interference from something else is to blame, this should have occurred also in earlier versions, no? This is definitely a regression.

**Comment by emersion** [comment]
Probably a wlroots bug related to the last X11 backend input changes.

Disclaimer: this bug has pretty low priority, I'd suggest you investigate what's going on.

**Comment by mithodin** [comment]
I will do the debug run on monday, since it's actually my work pc that has the problem. I'm happy to help in whichever way I can, however figuring out this bug is a bit beyond my current skillset, I think. I completely understand if there are higher priority issues. If I do start looking into it, what should I read to get a grasp of what wlroots and sway are even doing with regards to this bug?

**Comment by emersion** [comment]
The X11 backend is relatively small. Should probably add some debug logs to figure out what's going on. It's in `backend/x11` in the wlroots tree.

**Comment by mithodin** [comment]
This is fixed in 1.0-rc5. Not sure what did it, but the problem is gone.
