### ISSUE TITLE
Damage issues with Firefox on Wayland menus

### ISSUE THREAD

**Issue by JonnyMako** [swaywm/sway#3197]
Some symptoms:
1. Menus are drawn over each other. (attached).
2. Context menu stays on screen even after clicking outside the menu.
![menus](https://user-images.githubusercontent.com/6559121/49039660-0238f900-f186-11e8-98ac-8cd23dc922b8.png)

**Comment by emersion** [comment]
Can you try https://github.com/swaywm/sway/pull/3199?
