### ISSUE TITLE
Middle mouse kill window weird

### ISSUE THREAD

**Issue by pauledd** [swaywm/sway#3201]
* Sway Version:
sway version 1.0-beta.1-213-gcecf00b9 (Nov 22 2018, branch 'master')

Hi
I tried to bind my middle mouse button to the kill command:
sway.conf:
```
...
bindsym button3 kill
...
```
First it seems to work on a bunch of windows when middle-mouse clicking the title bar it closes the window (right after starting sway), but later and after opening "some" more windows (firefox etc...) it doesnt work anymore. I then press all possible mouse buttons in any irregular order an the last press is middle-mouse then it sometimes work... this is quite weird. Or am I doing it wrong in my config? I tried to tail the sway.log while this closing attempt (does not work) but there is no coincident output.

**Comment by emersion** [comment]
Please attach a debug log.

**Comment by emersion** [comment]
… and also a complete config.

**Comment by pauledd** [comment]
sure
[sway.log](https://github.com/swaywm/sway/files/2623614/sway.log)

[config.txt](https://github.com/swaywm/sway/files/2623622/config.txt)

**Comment by RedSoxFan** [comment]
Are you still able to replicate this? I think #3339 should have fixed this.

**Comment by RedSoxFan** [comment]
I'm closing to close this since I'm pretty sure #3339 fixes this. However, if you are able to replicate, feel free to reopen.

**Comment by pauledd** [comment]
sorry for the delay, I currently struggle with installing sway on gentoo again so I cant test it until this is solved. Thanks anyway.
