### ISSUE TITLE
Segfault when using scratchpad

### ISSUE THREAD

**Issue by 7415963987456321** [swaywm/sway#3203]
Sway segfaults when retreiving windows from the scratchpad.

Steps to reproduce:
I. open three terminals (alacritty),  
II.  throw them all to the scratchpad (mod+Shift+-)
III.  flip through the scratch pad couple of times (mod+-)
IV.   sway segfaults.

Sway version: 
1.0-beta-1-245-gdbf8e1ce (Nov 28, 2018, branch 'master')

Debug log:
https://gist.github.com/7415963987456321/59c73250a3135a02275a73877cee4139

Config:
https://gist.github.com/7415963987456321/809f04a30aac61ab12504d8aa0e2111f

**Comment by RedSoxFan** [comment]
Can you please provide a backtrace? I'm not able to replicate.

**Comment by 7415963987456321** [comment]
Output from running `coredumpctl gdb sway`  and `bt full`
https://gist.github.com/7415963987456321/3c7448ce12ac15ea3bfd01ddde06b3f5
Not sure if i'm doing this right, was expecting more output from this. Not very experienced with gdb.
