### ISSUE TITLE
Support mouse cursor snapping

### ISSUE THREAD

**Issue by The-King-of-Toasters** [swaywm/sway#3205]
Version: `sway version 1.0-beta.1-239-gaf7a9762 (Nov 28 2018, branch 'makepkg')`
Config: default

## Problem
Right now sway doesn't support mouse cursor snapping. It would be nice it it could.

My editor of choice, acme (from plan9port), uses mouse snapping when opening new windows and searching through text. Here is a [video of it in action in i3](https://www.sgregoratto.me/i3-acme.webm).
Using acme in sway is a different experience. It seems the program thinks the cursor has moved, but sway keeps it in the same spot. Here are a couple of images that show what I mean (since I couldn't find a screen recorder that worked):
![swacme1](https://user-images.githubusercontent.com/9159492/49127472-5693c400-f2bf-11e8-8ce6-b9ef74442413.png)
![swacme2](https://user-images.githubusercontent.com/9159492/49127471-55fb2d80-f2bf-11e8-9875-6cd2c7cd4838.png)
![swacme3](https://user-images.githubusercontent.com/9159492/49127470-55fb2d80-f2bf-11e8-9532-638a62fa4545.png)

You can try this out by compiling/downloading plan9port and running `acme`. My version looks different, but the changed are only superficial.

**Comment by ascent12** [comment]
In wayland, clients are deliberately not given the ability to move the cursor anywhere.
So this feature is currently not possible, and I don't see a good reason to add it, especially since it opens up the possibility for the client to abuse this.

**Comment by The-King-of-Toasters** [comment]
That's a shame. I guess this would mean that not even wayland programs could move the mouse on your behalf?
