### ISSUE TITLE
White Squares in Status bar and dmenu

### ISSUE THREAD

**Issue by s170648** [swaywm/sway#3220]
I installed sway-git + wlroots-git on a fresh arch linux install today (29.11.2018).

Upon opening sway the status bar, dmenu and exit prompt ( on Super + Shift + E) was filled with White squares (U+25A1), rendering everything unusable.

Issue was fixed by installing the ttf-dejavu font.

Haven't seen this mentioned anywhere, so i wanted to post it in case anyone else runs into this problem.

**Comment by progandy** [comment]
Did you have no font installed at all? Then it should be normal you got placeholders. sway-git should probably depend on ```ttf-font``` for arch linux and on some other generic (meta)package name on other distributions.

**Comment by s170648** [comment]
Yes, i had no fonts installed, as described it was a clean arch linux install, just adding sway-git and wlroots-git. (as well as some miscellaneous packages like open-vm-tools and trizen)

Adding a font as a dependency sounds good, as it is apparently required for sway to function properly.
