### ISSUE TITLE
swaymsg-output: dpms off/on resets brightness

### ISSUE THREAD

**Issue by CameronNemo** [swaywm/sway#3224]
* Sway Version: sway version 1.0-beta.2
* Debug Log: http://ix.io/1uXd
* Configuration File: default

When running `swaymsg "output * dpms off"` followed by  `swaymsg "output * dpms on"`, I expect that this will only affect the DPMS state and the brightness will remain the same. However, if the brightness is set to 0 before the dpms-off command is run, the dpms-on command resets the brightness to the maximum value.

**Comment by progandy** [comment]
Brightness 0 might be considered the same as dpms off by some drivers. Since there is no other known brightness value if you turn the screen back on, then it defaults to 100%.

**Comment by CameronNemo** [comment]
Uf. I was afraid it was my driver. Feel free to close.
