### ISSUE TITLE
[BUG] When in Tabbed mode, cursor can be above title bars

### ISSUE THREAD

**Issue by lord-re** [swaywm/sway#3230]
* Sway Version: sway version 1.0-beta.2-5-g7702943e (Dec  1 2018, branch 'HEAD')

When you put windows in **tabbed mode** in a workspace, place your mouse cursor the higher you can.
**The cursor will be slightly above the title bars** so you can't use the mousewheel to scroll the windows.

You must go down by a few pixels to be on the title bars and being able to use the mousewheel.

It's rather anoying as i use tabbed mode a lot with qutebrowser and i'm used to this technic with i3.

**Comment by David96** [comment]
As a workaround you could do something like "for_window [class="qutebrowser"] border none" in your config (or whatever qutebrowser's window class is) - at least for me scrolling works fine without a border.
So the bug seems to be that mouse events on the window border are not being processed.

**Comment by lord-re** [comment]
Hoo yes it works !

So maybe the way to fix this should be to remove the borders when windows are tabbed, no ?
