### ISSUE TITLE
Sway crashes when focusing a scratchpad window via swaymsg [app_id="something"] focus

### ISSUE THREAD

**Issue by camoz** [swaywm/sway#3235]
Sway version: `sway version 1.0-beta.1-256-ga22d0c0f (Nov 28 2018, branch 'master')`
Sway config: default config
Debug log: https://gist.github.com/camoz/8d8be0ee4bde590f375374677bcbd816
# Steps to reproduce
* Start sway with default config
* run `termite --name="sdf"`
* move the new window to scratchpad via key binding
* try to show it via `swaymsg [app_id="sdf"] focus`
# Expected behavior
Scratchpad window (termite) shows up
# What happens
Sway crashes, see debug log.

BTW I only tested that with termite for now.

**Comment by emersion** [comment]
Please submit a stack trace (`coredumpctl gdb sway` then `bt full`).

**Comment by camoz** [comment]
Will try, never done that. I assume it's important to run immediately after the crash?
I will learn about coredumpctl...

**Comment by emersion** [comment]
No, you can run it anytime after it crashes, before it crashes again.

**Comment by camoz** [comment]
Okay, will take me a bit, since I have to reproduce again....

**Comment by emersion** [comment]
You can also run `coredumpctl -r` t list all coredumps (1 coredump = 1 crash), and `coredumpctl gdb <pid>` to run GDB on a specific one.

**Comment by camoz** [comment]
Here we go, hope it helps.
Stack trace: https://gist.github.com/camoz/f24e5c30ac022ffedc62a11ae4513f49
