### ISSUE TITLE
Some commands crash sway when operating on hidden scratchpad containers

### ISSUE THREAD

**Issue by camoz** [swaywm/sway#3236]
Sorry for not digging into it further and not isolating the specific commands which cause the crash. However, the config is only minimally changed from the default config (last 4 lines are relevant).
Also, please tell me how I could improve the issue title.

Sway version: `sway version 1.0-beta.1-256-ga22d0c0f (Nov 28 2018, branch 'master')`

Sway config: https://gist.github.com/camoz/dd915707940dd72d386e1ea8b1546e11
Relevant are the four lines.

# Steps to reproduce
* start sway with attached config file (see last 4 lines)
* press $mod+Shift+backslash (which will run the command `termite --name="scratchterm_full"`)
# What happens
Sway crashes, see debug log: https://gist.github.com/camoz/99a4b09179189138163a39436634b461
# What should happen
Sway should not crash. Interestingly, when I press $mod+backslash, it works (which will run `termite --name="scratchterm_full`)
Here's a log with just $mod+backslash pressed: https://gist.github.com/camoz/9cb9d7d0719c731e4e56df42452bf8f3

The difference is obviously the size of the window:
`for_window [app_id="scratchterm"] floating enable; border none; resize set 100 ppt 50 ppt; move absolute 0 23; move scratchpad; scratchpad show`
`for_window [app_id="scratchterm_full"] floating enable; border none; resize set 100 ppt 100 ppt; move absolute 0 23; move scratchpad; scratchpad show`

**Comment by camoz** [comment]
Maybe this is related to https://github.com/swaywm/sway/issues/3235

Should I also provide a stack trace here?

**Comment by emersion** [comment]
Yes please

**Comment by camoz** [comment]
Stack trace: https://gist.github.com/camoz/0f1e29a62a4e84d10094f58bca29cf0d

**Comment by camoz** [comment]
Here it crashed without the scratchpad involved (stack trace): https://gist.github.com/camoz/f3265830fb868ae7b80813d5888297b6

In config:
`bindsym $mod+Shift+backslash exec termite --name="scratchterm_full"`
`for_window [app_id="scratchterm_full"] floating enable; border none; resize set 100 ppt 100 ppt; move absolute 1280 23`

Then hitting $mod+Shift+backslash...
