### ISSUE TITLE
Large delay on rendering of neovim under xterm

### ISSUE THREAD

**Issue by jpsamaroo** [swaywm/sway#3248]
When running neovim in xterm on sway 1.0-beta.2, nothing renders for about 4 seconds, or until I resize/fullscreen/move the xterm window containing neovim. This was reproducible in sway, but not in rootston (nested in sway). Running sway nested within sway also reproduces the issue, as well as when run nested with `-Ddamage=rerender`, per advice from @emersion . Running neovim under alacritty works as intended, rendering immediately. Regular vim works fine as well. I haven't seen a similar issue elsewhere so far.

**Versions:**

OS: Gentoo x86_64
GPU: Intel HD Graphics 520 (i965 Mesa driver)

swaymsg -t get_version: sway version 1.0-beta.2 (Dec 3 2018, branch 'HEAD')
- Compiled from git clone, no Gentoo patches

wlroots: 0.2 (Git)
xterm version: xterm-327 (Gentoo package)
neovim version: neovim-0.3.1 (Gentoo package)

**Configs:**

Logs from `sway -d 2> ~/sway.log`: https://pastebin.com/C4xC4vdm

Sway config: https://pastebin.com/YQbjquCx

Reproducible from plain (no config) xterm and neovim

**Comment by shioyama** [comment]
Maybe related to #3232 ...? That problem is also "fixed" by changing windows/reloading/etc.

**Comment by SamHH** [comment]
I'm experiencing this issue as well.

Versions: Sway: 1.0, Neovim: 0.3.4
Repro: Open any new window (terminal, web browser, anything) as a split below or beside the terminal with Neovim active. Roughly half of the time it will clear the screen containing Neovim, displaying nothing but the cursor. It fixes itself within a few seconds, or you can force a fix by switching back to the broken window - sometimes at this stage you also need to move the cursor.
Terminals: Alacritty, Termite
Editors: Only Neovim; neither Vi nor Vim exhibit this behaviour.

**Comment by joshuarubin** [comment]
I _think_ I'm having a similar issue. Using kitty term, but also tested under Alacritty. vim doesn't have the issue, but neovim does.

Whenever I yank or cut a line, the whole term window briefly resizes (shrinks horizontally) and screws up my nvim splits.

This was not an issue with the pre 1.0 release I was using but happens all the time with 1.0.

**Comment by emersion** [comment]
Can you still reproduce this issue?

**Comment by SamHH** [comment]
I haven't experienced this issue in so long that I forgot all about it. :slightly_smiling_face:
