### ISSUE TITLE
startup segfault

### ISSUE THREAD

**Issue by vperilla** [swaywm/sway#3254]
when I try to start sway I get a segfault, I use i915 driver, until my
last update I use sway normally.

I install sway and wlroots from Archlinux aur
yay -S wlroots-git
yay -S sway-git

sway version 1.0-beta.2-17-gbca21ee0 (Dec  3 2018, branch 'master')

[journalctl error](https://gist.github.com/vperilla/38edabc7e03bae96b274d0d5a20289e4)
[sway.log](https://gist.github.com/vperilla/46a082c9bbd5f12a6a4f807c27eb59ad)

**Comment by RedSoxFan** [comment]
Can you please post the full backtrace (`coredumpctl gdb sway` followed by `bt full`) as well as your wlroots version?

**Comment by vperilla** [comment]
[coredumpctl output](https://gist.github.com/vperilla/2e219a590b350a1681acfebfaeab33c0)

wlroots version aur/wlroots-git r3030.73423c98-1

**Comment by RyanDwyer** [comment]
Your wlroots version is from September 5th. Try updating it.

**Comment by vperilla** [comment]
I see this output on dmesg
285.789972] sway[2637]: segfault at 8 ip 00007fc6083f1080 sp 00007ffea8680b58 error 4 in libwayland-server.so.0.1.0[7fc6083eb000+7000]

**Comment by yw662** [comment]
Seems that we are having the same issue. #3265

**Comment by vperilla** [comment]
If I temporaly remove this line, I can run sway from my i3 session but crash eventually

https://github.com/swaywm/sway/blob/dbf8e1cead12ba775a9a702140576c5f7406c380/sway/server.c#L100

**Comment by vperilla** [comment]
In my case with /usr/bin/sway also get segmentation fault

**Comment by vperilla** [comment]
I can run sway with the next packages:
sway version 1.0-beta.2-33-g01420193 (last version)
wlroots version wlroots-git-0.2.r10.g273e110b-1-x86_64.pkg.tar.xz (2018-12-03)

Error happens If update wlroots to a newer version (since wlroots-git-0.2.r12.g3efc6bc3-1-x86_64.pkg.tar.xz also (2018-12-03))
