### ISSUE TITLE
Missing xdg_foreign support?

### ISSUE THREAD

**Issue by bemeurer** [swaywm/sway#3273]
I'm trying to run gnome-music on `sway version 1.0-beta.2-22-g0c3f0dfd (Dec  8 2018, branch 'master')` and I get the following output:
```
$ gnome-music
17:07:29 WARNING        XDG Music dir is not set
17:07:29 WARNING        XDG Music dir is not set

(org.gnome.Music:19174): Grilo-WARNING **: 17:07:29.258: [dleyna] ../grilo-plugins/src/dleyna/grl-dleyna-servers-manager.c:138: Unable to fetch the list of available servers: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name com.intel.dleyna-server was not provided by any .service files

(org.gnome.Music:19174): Gdk-WARNING **: 17:07:32.567: Server is missing xdg_foreign support

(org.gnome.Music:19174): Gtk-WARNING **: 17:07:32.568: Unable to show 'None': Operation not supported

(org.gnome.Music:19174): Gdk-WARNING **: 17:07:37.708: Server is missing xdg_foreign support

(org.gnome.Music:19174): Gtk-WARNING **: 17:07:37.709: Unable to show 'None': Operation not supported
```

Whenever I try to set my music library, ideas?

**Comment by ascent12** [comment]
Right, we don't support `xdg_foreign` yet. Support needs to be added to wlroots before it can be added to sway.
It's nice to know of a client that actually uses it now, but I don't understand why gnome-music would have a hard dependency on it.

**Comment by ascent12** [comment]
Actually, are you running gnome-music as a flatpak or in some sort of similar container thing?
That would explain why it requires it if you do.

**Comment by bemeurer** [comment]
@ascent12 I just installed it from pacman. I tried to manually set XDG_MUSIC_DIR but to no help, Guess it's broken for now.

**Comment by ascent12** [comment]
I tried running gnome-music myself, and it also fails when run inside weston or with GDK_BACKEND=x11.
I believe this is actually a problem with gnome-music instead of sway.
```
$ GDK_BACKEND=x11 gnome-music
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/gnomemusic/application.py", line 110, in do_activate
    self._window = Window(self)
  File "/usr/lib/python3.7/site-packages/gnomemusic/window.py", line 96, in __init__
    self._setup_view()
  File "/usr/lib/python3.7/site-packages/gnomemusic/window.py", line 153, in _setup_view
    self.player = Player(self)
  File "/usr/lib/python3.7/site-packages/gnomemusic/player.py", line 531, in __init__
    self._player = GstPlayer()
  File "/usr/lib/python3.7/site-packages/gnomemusic/gstplayer.py", line 77, in __init__
    self._setup_replaygain()
  File "/usr/lib/python3.7/site-packages/gnomemusic/gstplayer.py", line 101, in _setup_replaygain
    self._filter_bin.add(self._rg_volume)
TypeError: Argument 1 does not allow None as a value
```

**Comment by bemeurer** [comment]
@ascent12 I just installed it from pacman. I tried to manually set XDG_MUSIC_DIR but to no help, Guess it's broken for now.

**Comment by bemeurer** [comment]
FWIW Lollypop works perfectly fine :)

**Comment by emersion** [comment]
I cannot reproduce, gnome-music works for me.

In any case, this is an issue with gnome-music. Lack for xdg-foreign support should not be fatal.

**Comment by p4block** [comment]
I've been having this issue for a while on sway-git  (Arch) shortly after 1.5 was released. Opening apps such as Gedit or Celluloid is impossible unless they are run from a terminal (!?) 

Running from wofi, clicking on icons on Nautilus etc will do nothing.

**Comment by fluix-dev** [comment]
@p4block is your issue related to this issue (do some logs show xdg_foreign issues)? It seems like you should open a new issue instead with whatever info you can get.

**Comment by p4block** [comment]
@fluix-dev I posted it here because the only logs I get are on the terminal I launched wofi/nautilus from:
`(org.gnome.Nautilus:976241): Gdk-WARNING **: 22:42:10.777: Server is missing xdg_foreign support`

What I don't understand is why, for example, EOG works, but Gedit or Celluloid don't, as it still shows the xdg_foreign message.

**Comment by p4block** [comment]
It was DBUS being semi-broken in my setup. I used to run sway with `dbus-run-session sway` and had `exec systemctl --user import-environment` in my config (and that was working somehow in sway 1.5) The two didn't like each other anymore, apparently.

Run sway normally and switched to the more detailed exec found on the [troubleshooting guide.](https://github.com/swaywm/sway/wiki#gtk-applications-take-20-seconds-to-start)

So, turns out the xdg_foreign was a false lead.
