### ISSUE TITLE
Clicking around in kitty can crash sway

### ISSUE THREAD

**Issue by mninja** [swaywm/sway#3274]
Sway can crash when clicking around in kitty 0.13.1. I'm not sure exactly what produces it, although mousedown + drag to select text + click immediately (or just clicking a whole lot in a short period) seems to cause it every time.

As far as I can tell, it only happens for rapid events. Slowly attempting the above reproduction doesn't crash.

Sway version: `sway version 1.0-beta.2-22-g0c3f0dfd (Dec  8 2018, branch 'master')`
Log: https://gist.github.com/mninja/47ce45e3987bcac9d544ecbe5bd6934b

**Comment by RedSoxFan** [comment]
Can you please provide a full backtrace (`coredumpctl gdb sway` followed by `bt full`)?

**Comment by mninja** [comment]
https://gist.github.com/mninja/0fcacf31a85491182468559377e2f206

**Comment by mninja** [comment]
I built 0.2 from git.

**Comment by tarmack** [comment]
I had this same issue, it was related to the primary selection refactor in wlroots. It has not been an issue for me anymore for quite a while now. Is it still an issue for you @mninja?

**Comment by emersion** [comment]
@mninja Please upgrade wlroots and sway to the latest commit.

**Comment by RedSoxFan** [comment]
> speaking of which I haven't been able to compile sway despite successful installing wlroot-master,
`error: ‘WLR_INPUT_DEVICE_SWITCH’ undeclared`

It sounds like either you have multiple version of wlroots and an older one is being used or wlroots is not updating correctly. `WLR_INPUT_DEVICE_SWITCH` was added to wlroots fairly recently (12 days ago)

**Comment by Moelf** [comment]
> > speaking of which I haven't been able to compile sway despite successful installing wlroot-master,
> > `error: ‘WLR_INPUT_DEVICE_SWITCH’ undeclared`
> 
> It sounds like either you have multiple version of wlroots and an older one is being used or wlroots is not updating correctly. `WLR_INPUT_DEVICE_SWITCH` was added to wlroots fairly recently (12 days ago)

I compiled wlroots and installed it following what in https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=wlroots-git  how do I make there's no other version of wlroots

**Comment by emersion** [comment]
> Please upgrade wlroots and sway to the latest commit.

Ping

**Comment by emersion** [comment]
Feel free to re-open if you can reproduce
