### ISSUE TITLE
Reloading the config file turns off scaling

### ISSUE THREAD

**Issue by terminalnode** [swaywm/sway#3277]
Reloading the config file ('reload' binding in config file) turns of scaling for my display. 

sway version 1.0-beta.2-20-gcf6edaf2 (Dec  6 2018, branch 'master')
wlroots 0.2.r18.gfdb67ff6-1
(sway-git and wlroots-git packages in the arch user repository)

These are the configurations I've tried to set my scaling with:
``output eDP-1 pos 0 0 res 2560x1600 scale 1.9``
and
``output eDP-1 pos 0 0 res 2560x1600``
``output eDP-1 scale 1.9``
I've also tried other scaling factors and it makes no difference.

[debug.txt](https://github.com/swaywm/sway/files/2660917/debug.txt)

**Comment by RedSoxFan** [comment]
This is a bug with the default output configs we use to reset settings removed from the config or changed at runtime and not in the config on reload. I'll rework the system within the next day or so.

The band-aid for this would be to replace `eDP-1` with `Apple Computer Inc Color LCD 0x00000000` in your config.

**Comment by terminalnode** [comment]
Yes, that fixes it. Thank you.

**Comment by vKnmnn** [comment]
I have this issue aswell, although i'm not sure if it's identical. using sway-git from AUR. `sway version 1.0-rc1-257-gbd32b300 (Apr 25 2019, branch 'master')`
reloading sway resets the scaling i set with output eDP-1 scale 2.

**Comment by caleb-allen** [comment]
I have the same issue @vKnmnn is seeing on sway version 1.4.

The solution that @RedSoxFan of using the name, rather than `eDP-1`, in my config works, by setting the scale to 1.
