### ISSUE TITLE
sharing windows in chrome/firefox does only work partially

### ISSUE THREAD

**Issue by yannick** [swaywm/sway#3282]
sway version 1.0-beta.2-20-gcf6edaf2 (Dec  6 2018, branch 'master')

when i have  a meeting in e.g. google meet (or hangouts) and i want to share a window of my screen (or a screen) not all windows do appear.

in firefox-wayland e.g. wayland terminal windows do not appear but also some other apps
in chrome (xwayland) the set of apps that are shown is even more restricted but seemingly does not follow a pattern

**Comment by emersion** [comment]
This is expected.

I think firefox-wayland is in the process of implementing xdg-desktop-portal. When that happens, a wlroots portal could be used for screen sharing.

**Comment by yannick** [comment]
how does gnome make it work then and could that be enabled too temporary?

**Comment by emersion** [comment]
https://github.com/emersion/xdg-desktop-portal-wlr
