### ISSUE TITLE
default_border doesn't update on reload

### ISSUE THREAD

**Issue by terminalnode** [swaywm/sway#3292]
sway version 1.0-beta.2-20-gcf6edaf2 (Dec  6 2018, branch 'master')

**Steps to reproduce:**
* specify "default_border pixel 5" in ~/.config/sway/config
* reload sway (default binding $mod+shift+c)
* specify "default_border pixel 1" in ~/.config/sway/config
* reload sway (default binding $mod+shift+c)

**Expected behaviour:**
The thickness of the window borders should change between these reloads.

**Actual behaviour:**
Border thickness doesn't change. It does however change if you kill sway and restart it.

**Debug log:**
[debug.txt](https://github.com/swaywm/sway/files/2682475/debug.txt)

**Comment by emersion** [comment]
`default_border` only affects new windows.

**Comment by terminalnode** [comment]
Oh. Then it does work, sorry for the noise. Feel free to close this issue.
