### ISSUE TITLE
Sway freezing system on Gentoo

### ISSUE THREAD

**Issue by zarper39** [swaywm/sway#3295]
Hello! I'm having an issue that resembles both [3024](https://github.com/swaywm/sway/issues/3024) and [3247](https://github.com/swaywm/sway/issues/3247). I'm running with OpenRC and radeon graphics and attempting to run it with capabilities.

I was able to run it without problems with elogind as expected but it freezes with or without suid and capabilities otherwise. Trying to start sway with "-dV" leads it to just being frozen with:

`[sway-1.0-beta.2/sway/server.c:34] Preparing Wayland server initialization`

until I force a shutdown. Running it as root gets more output which mentions it loads the driver and everything else successfully but then alerts that it's unable to drop privs (if you'd like to see the logs for that if you know it can be useful, please say so). It may also be worth noting that this occurred with sway and wlc before the move to wlroots. Basically I ran 0.15 on Debian and Arch and both would freeze up with the same message. After the move to wlroots under systemd (I'd assume because of logind) it worked beautifully. I've been trying to set it up without (e)logind for a bit but I'm stumped and hopefully haven't overlooked anything obvious.

**Comment by SpeedJack** [comment]
Your user is in the `input` and `video` groups? (It not, add yourself to these groups) 
If you use consolekit, you must run sway with `exec ck-launch-session sway`. You do it?

These things are printed on screen by emerge after Sway installation. You do not need to manually setuid or set capabilities, these are properly set automatically by the ebuild.

If it still doesn't work, redirect all output to a file when launching sway. When it hangs, reboot, and copy here the content of the file. Add also the output of `emerge --info dev-libs/wlroots dev-libs/sway`.

**Comment by ascent12** [comment]
@zarper39 
Make sure you've done the steps in https://github.com/swaywm/sway/wiki/Running-Sway-without-systemd
If that continues to not work, can you provide the entire debug log?

>@SpeedJack  If you use consolekit, you must run sway with exec ck-launch-session sway

Neither consolekit nor consolekit2 are supported by sway/wlroots, and shouldn't be required for it to start.

**Comment by zarper39** [comment]
Ah well I have to thank you both lol. It was something obvious. I did as you guys instructed with the debug log and turns out that wasn't the only message. It lead me to XDG_RUNTIME_DIR and then a quick search brought up [issue 3187](https://github.com/swaywm/sway/issues/3187) where if XDG_RUNTIME_DIR isn't set it throws an error that won't show on the frozen screen but does show you in the log. Sorry for the time waste but I majorly appreciate anyway as I've been ripping my hair out trying to figure that one out lol.

For the relevant lines it shows:
`error: XDG_RUNTIME_DIR not set in the environment`
`[sway-1.0-beta.2/sway/server.c:146] Unable to open wayland socket`
