### ISSUE TITLE
Dual screen single background

### ISSUE THREAD

**Issue by PlusMinus0** [swaywm/sway#3296]
* Sway Version: 1.0-beta.2-38-gc8284176 (Dec 16 2018, branch 'master')

Assuming this set up:
```
output HDMI-A-1 resolution 1920x1080 position 0,0
output HDMI-A-2 resolution 1920x1080 position 1920,0
```

Is ist possible to set up a wallpaper 3840×1080 to span both screens?

**Comment by RyanDwyer** [comment]
You can split the wallpaper into two images and assign them separately to each output.

**Comment by emersion** [comment]
You could also create a new wallpaper client replacing `swaybg` for this specific use-case.

**Comment by PlusMinus0** [comment]
Thanks, so not out of the box.

> You can split the wallpaper into two images and assign them separately to each output.

That’s what I'm doing currently, was hoping to get around it.

> You could also create a new wallpaper client replacing swaybg for this specific use-case.

Alright, will look into it.

**Comment by emersion** [comment]
Closing because this won't be implemented in `swaybg`.
