### ISSUE TITLE
mpv falls back to non-accelerated playback on Intel GPU/CPU 8th Gen (vaapi)

### ISSUE THREAD

**Issue by sydneymeyer** [swaywm/sway#3299]
mpv falls back to non-accelerated playback on Intel GPU/CPU 8th Gen (vaapi):

[sydney@x1 ~]$ mpv Downloads/Moon.2009.1080p.Bluray.x264-hV/Moon.2009.Limited.1080p.Bluray.x264-hV.mkv 
Resuming playback. This behavior can be disabled with --no-resume-playback.
Playing: Downloads/Moon.2009.1080p.Bluray.x264-hV/Moon.2009.Limited.1080p.Bluray.x264-hV.mkv
 (+) Video --vid=1 (*) (h264 1920x800 23.976fps)
 (+) Audio --aid=1 (*) (dts 6ch 48000Hz)
error: failed to resolve wl_drm_interface(): /usr/lib/libEGL_mesa.so.0: undefined symbol: wl_drm_interface
Cannot load libcuda.so.1
AO: [pulse] 48000Hz 5.1(side) 6ch float
VO: [gpu] 1920x800 yuv420p
AV: 00:23:02 / 01:37:09 (23%) A-V:  0.000
Saving state.

mpv 0.29.1 options: gpu-context=wayland; hwdec=vaapi

sway version 1.0-beta.2-39-g1442d4e6 (Dec 16 2018, branch 'master')

wlroots at commit "c4c1d63a0c0d7315a1a4468d62d883371ba3ec4e"

4.19.8-arch1-1-ARCH Linux Kernel from Arch Linux

sway debug log: https://gist.github.com/sydneymeyer/4f7775989714db581efd7904490b9d34

**Comment by ascent12** [comment]
This is not a sway/wlroots issue.

> error: failed to resolve wl_drm_interface(): /usr/lib/libEGL_mesa.so.0: undefined symbol: wl_drm_interface

**Comment by sydneymeyer** [comment]
I never had any issues with this setup until i updated my sway/wlroots combo yesterday.

**Comment by emersion** [comment]
Sway doesn't touch libEGL_mesa.so at all, so it's **very** unlikely that Sway is involved with your issue.

**Comment by ascent12** [comment]
I'd start by making sure you're using a recent build of mpv (i.e. make sure you're not using an AUR package from ages ago), and your OpenGL and EGL libraries are installed correctly.
But we have nothing to do with these. Hardware decoding is not tied to anything we're doing.

**Comment by sydneymeyer** [comment]
@ascent12 OK, Thanks.
@emersion It indeed appears to be an issue with libva/libva-intel-driver.
Particulary [https://github.com/intel/intel-vaapi-driver/issues/419#issuecomment-445164123](url)
Anyway.. sorry for the noise and thank you both for your quick help.
