### ISSUE TITLE
Sway crashes when the 'split' command is used on an empty workspace

### ISSUE THREAD

**Issue by jpoppe** [swaywm/sway#3304]
* Sway Version: sway version 1.0-beta.2-42 g5f255410 (Dec 17 2018, branch 'master')      
                                                                                         
* Debug Log: TBD (I skipped this since it is so simple to reproduce the bug, if still needed, let me know in the comments and I will upload a proper debug log).                                                        
                                                                                         
* Configuration File (not really needed, see the next section for how to trigger the crash):                                                                    
bindsym $mod+Return split v, exec termite                                                
                                                                                         
* Steps to reproduce (type this on the command line, hit enter, and poof, Sway is gone..):                                                                    
$ sway 'workspace empty_workspace; split v'                                              
                                                                                         
* Note:  With version: r5338, commit: cf6edaf2 everything works fine, it broke a (couple) of (commit
(s) after this commit.

**Comment by emersion** [comment]
Please include a stack trace: `coredumpctl gdb sway` and then `bt full`.
