### ISSUE TITLE
Sway crashes when using the IRC app Polari

### ISSUE THREAD

**Issue by mwenzkowski** [swaywm/sway#3311]
* Sway Version: 1.0-beta.2-28-gb61a936c (Dec 16 2018, branch 'master')
* Debug Log: [sway.log](https://gist.github.com/mwenzkowski/9e528a476a6064eca16f9fc8c722b9d4#file-sway-log)
* Configuration File: Default configuration
* Stack Trace: [stack trace](https://gist.github.com/mwenzkowski/9e528a476a6064eca16f9fc8c722b9d4#file-stack-trace)

This crash occurred while I was trying out the IRC application [Polari](https://wiki.gnome.org/Apps/Polari) (Version  3.30.2) on Arch Linux.
To reproduce the problem:

0. (`rm .cache/polari/close-confirmation-shown`)
1. Start Polari
2. Close Polari (Either via key binding or by clicking the close button on the CSD)
3. A dialog window opens, asking if Polari should be closed or if it should keep running in background
4. Press the escape key
5. The main window of Polari vanishes, but the dialog window remains (which I guess is a bug in Polari, since it should be the other way round)
6. Move the mouse cursor on the dialog window, then sway crashes

The dialog window is only shown on the first run, so to reproduce it another time step 0. is necessary. I tried this five times and sway crashed every time.

**Comment by emersion** [comment]
Can you try to reproduce after updating wlroots?

**Comment by mwenzkowski** [comment]
I have build both wlroots (commit swaywm/wlroots@c4c1d63a0c0d7315a1a4468d62d883371ba3ec4e) and sway (commit 477bca5e288cc3155c536265272490b413328778) from source and I can still reproduce the crash.
I also tried it in rootston and there it doesn't crash.

**Comment by emersion** [comment]
Can you post a `WAYLAND_DEBUG=1` debug log of Polari?

**Comment by mwenzkowski** [comment]
Here is the log: [polari.log](https://gist.github.com/mwenzkowski/9e528a476a6064eca16f9fc8c722b9d4#file-polari-log).
This time I noticed that sway crashes as soon as the mouse cursor enters the dialog window. If the cursor was on the dialog window already, the crash occurs immediately when the mouse is moved.
I have updated the description above accordingly.
