### ISSUE TITLE
Drag icons in chromium / chrome stop moving after fade-in

### ISSUE THREAD

**Issue by jeLee6gi** [swaywm/sway#3317]
* Sway Version: sway version 1.0-beta.2-34-g1897edab (Dec 14 2018, branch 'master')

When using drag&drop on an image in chromium / chrome, the drag icon stops moving after the initial fade-in animation.

Steps to reproduce:
* Open chromium / chrome and start dragging any image

**Comment by alexbakker** [comment]
Passing ``--disable-gpu-driver-bug-workarounds`` to Chromium fixes this issue for me.

**Comment by c-edw** [comment]
Can you test if this still happens (without that flag)? I gave it go a go myself, seems to work okay.

**Comment by jeLee6gi** [comment]
I just tested on sway version 1.0-rc1-8-ga1a99421 (Feb  4 2019, branch 'master') and chromium 72.0.3626.81 and my drag icons still get stuck.

**Comment by emersion** [comment]
Can't reproduce.

**Comment by jeLee6gi** [comment]
I'm not affected by this issue anymore on sway version 1.0-rc1-132-g6728db28 (Feb 28 2019, branch 'master') and chromium 72.0.3626.119. Thank you for the suggestions!
