### ISSUE TITLE
Sway background scaling

### ISSUE THREAD

**Issue by HolyStephano** [swaywm/sway#3319]
so I'm using pywal to change colors and whatnot, and I don't have the background manually set in the sway config so pywal can change it on the fly. Sway seems to be scaling the background  (image is 4912x3264) down (screen is 1920x1080) to fit and i'd like to either know how it does the scaling or if i can somehow set it not to scale?

**Comment by emersion** [comment]
`man sway-output`

**Comment by HolyStephano** [comment]
I don't quite know. I have an image bigger than my resolution and no matter what i set it gets scaled and some parts get cut off.

**Comment by emersion** [comment]
"center" is supposed to cut off without scaling.
