### ISSUE TITLE
Sway stays at a gray screen at launch

### ISSUE THREAD

**Issue by Bryophyllum** [swaywm/sway#3322]
* Sway Version: sway version 1.0-beta.2-52-g788b7157 (Dec 22 2018, branch 'master')

After rebuilding wlroots and sway againts the master branches from today, I'm greeted by the gray screen with only the mouse cursor and windows borders visible. 
For a brief moment I can see my wallpaper flash, but it reverts to the gray immediately. I did rebuild Sway and Wlroots yesterday and haven't experienced this problem until just now.
Those commits could be related: https://github.com/swaywm/sway/commit/788b715776b6d8c1ed3c67929a17a4d0d4079458 & https://github.com/swaywm/wlroots/commit/b6b1bf94900fca760a839796794161a2160a9f89

I am able to send a sigterm signal to a running Sway instance and it exits gracefully without crashing.

**Comment by emersion** [comment]
Please provide logs.

**Comment by Bryophyllum** [comment]
Sorry about that, here are the logs: https://gist.github.com/Bryophyllum/9bae47daea1dc2f899b1cf73c00a30b7

I'll try running sway with the default conifiguration to eliminate one possibility.

**Comment by johnae** [comment]
Yep same here after just updating to latest wlroots + latest sway.

**Comment by mstoeckl** [comment]
Changing the following lines seems to resolve the issue.

    diff --git a/sway/desktop/output.c b/sway/desktop/output.c
    index ed504bdf..79ad7faa 100644
    --- a/sway/desktop/output.c
    +++ b/sway/desktop/output.c
       @@ -108,7 +108,7 @@ static bool get_surface_box(struct surface_iterator_data *data,
               };
 
            struct wlr_box intersection;
    -       return wlr_box_intersection(&output_box, &rotated_box, &intersection);
    +       return wlr_box_intersection(&intersection, &output_box, &rotated_box);
     }
     
     static void output_for_each_surface_iterator(struct wlr_surface *surface,
    diff --git a/sway/desktop/render.c b/sway/desktop/render.c
    index 1260d85a..14881e96 100644
    --- a/sway/desktop/render.c
    +++ b/sway/desktop/render.c
    @@ -261,7 +261,7 @@ static void render_saved_view(struct sway_view *view,
            };
     
            struct wlr_box intersection;
    -       bool intersects = wlr_box_intersection(&output_box, &box, &intersection);
    +       bool intersects = wlr_box_intersection(&intersection, &output_box, &box);
            if (!intersects) {
                    return;
            }
    diff --git a/sway/tree/container.c b/sway/tree/container.c
    index b106e0d9..0a96088e 100644
    --- a/sway/tree/container.c
    +++ b/sway/tree/container.c
    @@ -979,7 +979,7 @@ void container_discover_outputs(struct sway_container *con) {
                    output_get_box(output, &output_box);
                    struct wlr_box intersection;
                    bool intersects =
    -                       wlr_box_intersection(&con_box, &output_box, &intersection);
    +                       wlr_box_intersection(&intersection, &con_box, &output_box);
                    int index = list_find(con->outputs, output);
     
                    if (intersects && index == -1) {

**Comment by mbrumlow** [comment]
I think the issue has to do with wlr_box_rotated_bounds. In the #1441 refactor the last argument was moved to the first argument. But when fixing all the function calls some of the time the last argument was moved to the first argument. 

Example: https://github.com/swaywm/wlroots/commit/b6b1bf94900fca760a839796794161a2160a9f89#diff-ae57019f4a7cc8a21cd43879bd2bf787L220
