### ISSUE TITLE
Sway starts on black screen

### ISSUE THREAD

**Issue by ZJaume** [swaywm/sway#3325]
* Sway Version: sway version 1.0-beta.2-52-g788b7157 (Dec 22 2018, branch 'master')
* Debug Log: https://gist.github.com/ZJaume/da002b6dd12313145790a58781bc8f7f
* Configuration File: default
* Starting from tty

Sway starts on blackscreen, does not respond to any command and has to be killed from another tty.
Using intel graphics.

**Comment by RyanDwyer** [comment]
Please try again with the latest master.

**Comment by ZJaume** [comment]
Yep, it's working, thanks!
