### ISSUE TITLE
question: how to disable drag in tabbed layout

### ISSUE THREAD

**Issue by rvi64** [swaywm/sway#3328]
The 1.0 beta release introduced dragging windows in different layouts, and it's not a problem for me since i don't have titlebars. Except in tabbed. When i click the tab the hand cursor appears so i can drag the tab. Can i disable this feature in config?

**Comment by RyanDwyer** [comment]
Try `tiling_drag disable`.

**Comment by rvi64** [comment]
> Try `tiling_drag disable`.

that worked, thanks!

**Comment by rvi64** [comment]
it's not in the `sway(5)` tho, right?

**Comment by RedSoxFan** [comment]
> it's not in the sway(5) tho, right?

Nope. I just opened a PR to add it. https://github.com/swaywm/sway/pull/3332
