### ISSUE TITLE
get current keyboard layout

### ISSUE THREAD

**Issue by rvi64** [swaywm/sway#3330]
keyboard layout settings can be set in input field, but how do i then obtain my current keyboard language? xkbkeyboard_state doesnt work, maybe theres some command i dont know?

**Comment by RedSoxFan** [comment]
The output of `swaymsg -t get_inputs` includes the active keyboard layout

**Comment by rvi64** [comment]
thanks, i'll have to figure out for which exact keyboard tho, but that's the feature lol
