### ISSUE TITLE
color picking tool

### ISSUE THREAD

**Issue by rvi64** [swaywm/sway#3331]
is the any color picking tool that works with sway windows?

**Comment by rvi64** [comment]
you know what, making screenshot with `grim` and pasting it to `gimp` is actually much better than i thought. it has these pixel-borders, dimensions and stuff. so if someone to make the color picking tool it MUST have the zoom effect to grab just the right pixel.
also, `grim` is making TRUE color images, i believe `scrot` and `maim` do not correctly display colors, (though i may be wrong here), but i always had this problem when screenshot does not actually have the colors that are on the screen, and it depends on the brightness of a monitor. now on whichever brightness the colors are always the same as intended.

**Comment by emersion** [comment]
Related: https://github.com/emersion/slurp/issues/13

**Comment by emersion** [comment]
Also note that this feature is necessary for complete xdg-desktop-portal support.

This is not a sway issue though. All the necessary Wayland protocols are already in place.

**Comment by emersion** [comment]
Closing because this isn't a sway bug.
