### ISSUE TITLE
Black screen with a simple config

### ISSUE THREAD

**Issue by ljedrz** [swaywm/sway#3350]
Sway works just fine *unless* I try to use a config file; when I do, I only get a black screen and a cursor and I need to go to another tty to kill it because it doesn't work properly.

`swaymsg -t get_version`:
`sway version 1.0-beta.2-60-g9bf1b7a0 (Dec 28 2018, branch 'master')`

[`sway -dV` & `config`](https://gist.github.com/ljedrz/33ded50f7b004367639f332cfad07b54)

**Comment by Marteon** [comment]
What do you mean with not properly?
Since the config does not do much there isn't much that can not work.

**Comment by terminalnode** [comment]
Maybe try to start with the default config file, then add and remove things as you go along.

As Marteon said your config file doesn't really contain much. There's literally just a mod-key definition and volume control. You need some controls for navigating workspaces, input/output configuration, probably want a statusbar as well.

**Comment by ljedrz** [comment]
Yep, that did the trick; I thought the default settings were hardcoded and custom config was building upon / overriding them. When I copied `/etc/sway/config` to `~/.config/sway/config` and added volume control it worked as expected. Thanks!
