### ISSUE TITLE
Unable to drop root [...]

### ISSUE THREAD

**Issue by southern-tools** [swaywm/sway#3363]
Hello, I am trying to run Sway on my minimal gentoo system (openrc without consolekit, pam, elogind) and I get this error:
`[sway-1.0-beta.2/sway/main.c:209] Unable to drop root (we shouldn't be able to restore it after setuid), refusing to start`
I already followed this [instrucctions](https://github.com/swaywm/sway/wiki/Running-Sway-without-systemd) so I had ran:
`setcap cap_sys_admin=eip /usr/bin/sway`
and
`chmod +s /usr/bin/sway`
Sway and Wlroots are compiled with "filecaps".
Here the [log](https://paste.pound-python.org/show/6axgKhh6XGZmjocKAGJN/).
Thank you in advance for your help.

**Comment by RedSoxFan** [comment]
I think this comment may help: https://github.com/swaywm/sway/issues/3247#issuecomment-444058339

I haven't used gentoo, but I think the issue is that both the capability and the SUID bit are set and based on that comment, it looks like `filecaps` should handle setting the correct one for you. I may be misunderstanding that comment though

**Comment by southern-tools** [comment]
Thank you @RedSoxFan for your help.
You are right about `filecaps`, I recompiled Sway and then ran `getcap /usr/bin/sway` getting `/usr/bin/sway = cap_sys_admin+ep`. So far so good.
On the other hand, without `chmod +s /usr/bin/sway` the system freezes and I have to reboot (and I don't get any log file)

**Comment by RedSoxFan** [comment]
> On the other hand, without chmod +s /usr/bin/sway the system freezes and I have to reboot (and I don't get any log file)

Is your user in the `input` group? Excerpt from the previously linked comment:
> If, in this case, the computer freezes, the problem is something else.
> From the logfile, Sway seems unable to read input devices. Emerge, at the end of Sway installation,
> should have printed this message:
> You must be in the input group to allow sway to access input devices!
> So you must add your user to the input group: gpasswd -a input <username>.

**Comment by southern-tools** [comment]
Yes, I have my user in the `input` and also the `video` group as per [gentoo handbook](https://wiki.gentoo.org/wiki/Sway).

**Comment by southern-tools** [comment]
Ok, I was able to solve the problem.
I was wrong about the lack of a log file, it only needed some time "frozen" to generate it. The new [log](https://paste.pound-python.org/show/klZBvujNVdjRqRSwUkOA/) has not the warning: `Unable to drop root [...]` but now: `XDG_RUNTIME_DIR not set in the environment`.
So, following the [gentoo handbook](https://wiki.gentoo.org/wiki/Weston) for Weston, I added:
`if test -z "${XDG_RUNTIME_DIR}"; then
    export XDG_RUNTIME_DIR=/tmp/${UID}-runtime-dir
    if ! test -d "${XDG_RUNTIME_DIR}"; then
        mkdir "${XDG_RUNTIME_DIR}"
        chmod 0700 "${XDG_RUNTIME_DIR}"
    fi
fi`
to my .bash_profile.
I was finally able to start Sway, so I am closing this ticket.
Again, thank you very much @RedSoxFan for your help.
