### ISSUE TITLE
Slow downs when moving mouse around between certain areas of the screen

### ISSUE THREAD

**Issue by mxmilkb** [swaywm/sway#3368]
So I mentioned this in #sway a couple of weeks ago, but just system upgraded after being away and the issue remains.

When I move the mouse pointer between certain parts of the screen, sway takes up a lot of cpu.

Instances of changes where this happens (and vice versa):
* from the background into swaybar
* from a max window into swaybar
* in Firefox when moving from a non-anchor link area to an anchor link area
* FF: moving vertically over plain text lines (e.g. in a GitHub README)
* FF: moving over a button
* FF: moving up and down a bookmark dropdown menu
* Quassel: moving between channel list column to timestamp column, between time stamp column to msg nickname column, from that to msg contents area, from that to the channel user list column. also, moving over hyperlinks.

Instances of changes where this doesn't [appear to] happen in Firefox:
* moving between tabs
* moving between bookmark bar items
* moving between the viewport and bookmark bar items
* when moving between contiguous link areas, e.g., on GitHub, in the "The following issues might be related"

Not all slow downs are equal in how much things slow down. The worst are between application windows and over the edge of the sway bar. With two floating terminals partly overlapping near the corner of the screen, I've had overall CPU usage spike to 98+%.

I've also temp renamed my config so it's not loaded but the problem remains.

sway version 1.0-beta.2-94-g5bf4daf2 (Jan  2 2019, branch 'master')

[debug log](https://gist.github.com/milkmiruku/e74db6ec66af108e0c368fe283e1464d) - in which I stary sway, switch from one monitor to the other, open a terminal, move the mouse around over window edges, then logout.

**Comment by emersion** [comment]
Is there anything in `dmesg`? Can you do a `perf` record?

**Comment by milkmiruku** [comment]
https://gist.github.com/milkmiruku/dc34125dac988512c097ff9c83fe602d

**Comment by milkmiruku** [comment]
I've only experienced this problem with sway for about a month. I have a hunch it's related to the "Replace _XOPEN_SOURCE with _POSIX_C_SOURCE" commit, but it's only a hunch.

**Comment by emersion** [comment]
>I have a hunch it's related to the "Replace _XOPEN_SOURCE with _POSIX_C_SOURCE" commit, but it's only a hunch.

Very unlikely

**Comment by emersion** [comment]
Can you reproduce with the latest wlroots commit?
