### ISSUE TITLE
Undo map_to_output

### ISSUE THREAD

**Issue by robertgzr** [swaywm/sway#3371]
I'm testing sway 1.0-beta.2

I sometimes what to lock my pointer to my external monitor, I do that by running:
 `sway input "<input-id>" map_to_output "<output-id>"`.

But as far as I was able to find there is no command to map it back to all outputs. It would be nice to be able to do `sway input "<input-id>" map_to_output *` to reset it.

For now even reloading config doesn't reset it... I have to reconnect the device.

**Comment by emersion** [comment]
+1, can you send a pull request?

**Comment by RedSoxFan** [comment]
It would probably also be a good idea to reset inputs on reload like we do for outputs. If i remember correctly, libinput has functions for getting the default values for a device
