### ISSUE TITLE
sway lookup error: sway: undefined symbol: wlr_primary_selection_device_manager_create

### ISSUE THREAD

**Issue by noopro** [swaywm/sway#3374]
Hi,

On arch linux, wlroots-git updated from 0.1.r24.g659d39ba-1 to 0.2.r64.g84c90475-1. Since then I have been getting the below error message when launching swaywm. Unsure whether this should issue should have been created under swaywm/wlroots. Thanks in advance and any thoughts welcome!

Sway Version:
sway version 4.15.0.1 (03-13-2018)
sway-git r4928.b80cf982-1

Other:
xf86-video-nouveau 1.0.15-3
wlroots-git 0.2.r64.g84c90475-1
mesa-18.3.1-1

Video card:
% lspci -k | grep -A 2 -E "(VGA|3D)"
02:00.0 VGA compatible controller: NVIDIA Corporation C79 [GeForce 9400M] (rev b1)
Subsystem: Apple Inc. C79 [GeForce 9400M]
Kernel driver in use: nouveau

Debug Log:sway lookup error: sway: undefined symbol: wlr_primary_selection_device_manager_create
% sway -d
sway lookup error: sway: undefined symbol: wlr_primary_selection_device_manager_create

Configuration File:
Default from /etc/sway/config

**Comment by emersion** [comment]
wlroots-git isn't upgraded to the latest commit.

**Comment by noopro** [comment]
Okay, thanks! So my understanding from what you have said is that I would need to roll back to the previous wlroots-git for now and then wait for the most recent release?
