### ISSUE TITLE
Compositor Effects

### ISSUE THREAD

**Issue by Olie440** [swaywm/sway#3380]
This issue was raised two years ago before Sway came with a compositor: https://github.com/swaywm/sway/issues/453.

Are there any plans to implement any compositor effects similar to what Compton has for X?
The main ones i'd like to see are: 

- Fading between work-spaces
- Shadows
- Opacity

**Comment by emersion** [comment]
>before Sway came with a compositor

Sway has always been a Wayland compositor. Things work differently on X11 and on Wayland.

Sway has the roles of a X11 server + X11 WM + X11 compositor.

>Are there any plans to implement any compositor effects similar to what Compton has for X?

No, sorry, this isn't planned.

However, you can already set a window's opacity with the `opacity` command. See `contrib/inactive-windows-transparency.py` for example usage.

If you want effects, other compositors might suit you better (e.g. https://github.com/WayfireWM/wayfire).

**Comment by Olie440** [comment]
Does Sway work with other Compositors? (ie. Serving just the roles of X11 server + X11 WM).
I like Sways layout and ability to have config be ported from i3, but I also want to be able to have a fading effect and shadows.
I imagine most users coming from i3 would feel the same.

**Comment by emersion** [comment]
>Does Sway work with other Compositors? (ie. Serving just the roles of X11 server + X11 WM).

No, you can't use sway and another compositor at the same time.

**Comment by Olie440** [comment]
Ok thank you for the information.

**Comment by WillPower3309** [comment]
[swayfx](https://www.github.com/willpower3309/swayfx) currently has rounded corners and shadows, as well as dimming. Although, blur is currently in a draft PR, so it will be merged soon. Fade animations will be next!

**Comment by saxophone-guy** [comment]
Just a suggestion, but Hyprland seems promising

**Comment by emersion** [comment]
Note that Hyprland's main developer, vaxry, has been banned from the FreeDesktop.Org community.
