### ISSUE TITLE
Sway does not register bindsym commands binded to $mod+q

### ISSUE THREAD

**Issue by ghost** [swaywm/sway#3393]
* Sway Version: 1.0-beta.2-135-gf9cea7f0 (Jan  9 2019, branch 'master')

* Debug Log: https://gist.github.com/Bryophyllum/a3061c183e4ea292977b6faecb08a3b3

Instead it does send $mod+q to a client (types the letter "Q" or closes some programs as defined in their behaviour).

I did the bisection of the recent commits made after https://github.com/swaywm/sway/commit/327236a7ab5beacd925d8e9a16b3f11badb99abf and the commit https://github.com/swaywm/sway/commit/140bc2dd5b81205df58bf06e695788e689fae397 was marked as the first bad commit: https://gist.github.com/Bryophyllum/d53220c98bfe863f600246d1aa284e97

**Comment by RedSoxFan** [comment]
Can you please post your config file? Either there is a trailing open brace at the end of your config or something weird is going on with brace detection.

```
2019-01-09 16:15:16 - [sway/sway/config.c:680] Read line 390: bindsym $mod+q mode "run"   
2019-01-09 16:15:16 - [sway/sway/config.c:691] Detected open brace on line 392            
2019-01-09 16:15:16 - [sway/sway/config.c:733] Entering block 'bindsym $mod+q mode "run"'
<end of config reading>
```

**Comment by ianyfan** [comment]
This one might be nicer depending on your opinion of goto:
```
diff --git a/sway/config.c b/sway/config.c
index dfbe4cb9..6c6bca5e 100644
--- a/sway/config.c
+++ b/sway/config.c
@@ -610,12 +610,14 @@ static int detect_brace(FILE *file) {
                strip_whitespace(line);
                if (*line) {
                        if (strcmp(line, "{") != 0) {
-                               fseek(file, pos, SEEK_SET);
                                lines = 0;
                        }
-                       break;
+                       goto end;
                }
        }
+       lines = 0;
+end:
+       fseek(file, pos, SEEK_SET);
        free(line);
        return lines;
 }
```

**Comment by Bryophyllum** [comment]
@RedSoxFan Here you go: https://gist.github.com/Bryophyllum/57110715fbe7620bc55b086e1f692af6

@ianyfan I applied the former patch and it works now! I tried applying the latter too, but I was getting `Hunk #1 FAILED at 610` while patching.

**Comment by RedSoxFan** [comment]
The config looks fine so it is definitely an issue with brace detection. However, it looks like ianyfan's got it covered and can turn the patch (or an equivalent) into a PR.
