### ISSUE TITLE
flameshot not opening

### ISSUE THREAD

**Issue by martynas-m** [swaywm/sway#3405]
sway version 1.0-beta.2-147-g212baf2f (Jan 10 2019, branch 'master'

type flameshot or flameshot gui- nothing happens. no error, no ui.

note: grim works and produces sreenshot.

**Comment by emersion** [comment]
Flameshot won't work anyway, because it only supports GNOME and KDE.

See https://github.com/lupoDharkael/flameshot/issues/446
