### ISSUE TITLE
Add input-method support

### ISSUE THREAD

**Issue by emersion** [swaywm/sway#3407]

**Comment by ascent12** [comment]
@c-edw https://github.com/wayland-project/wayland-protocols/blob/master/unstable/input-method/input-method-unstable-v1.xml

**Comment by johnchen902** [comment]
https://github.com/swaywm/wlroots/blob/master/protocol/input-method-unstable-v2.xml

Is this the v2 of the protocol?

**Comment by johnchen902** [comment]
https://github.com/swaywm/wlroots/blob/master/protocol/input-method-unstable-v2.xml

Is this the v2 of the protocol?

**Comment by emersion** [comment]
Yes. The wlroots side already has an implementation.

**Comment by helionmelion** [comment]
Hello, after some retries, I was able find a way to use fcitx-mozc with sway (japanese input).
https://github.com/helionmelion/sway-fcitx-workaround
It's not 100% but seems ok to everyday use. Hope this helps.

**Comment by Laaas** [comment]
How come v2 isn't part of the wayland-protocols repository? Is it controversial?

**Comment by emersion** [comment]
It's still being reviewed. It's also missing an implementation of some parts of the protocol.

**Comment by helionmelion** [comment]
I updated https://github.com/helionmelion/sway-fcitx-workaround 

Details of my home desktop:
using Arch Linux
u̶s̶i̶n̶g̶ ̶S̶D̶D̶M̶ ̶d̶i̶s̶p̶l̶a̶y̶ ̶m̶a̶n̶a̶g̶e̶r̶
using GDM display manager
sway windows manager
zsh shell
using JAPANESE NATIVE KEYBOARD jp(OADG109A)
I want Japanese and Brazilian Portuguese input method.

Update: this time I created the file ~/.config/environment.d/wayland.conf and put this:

export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
fcitx -r
export _JAVA_AWT_WM_NONREPARENTING=1
export XDG_SESSION_TYPE=wayland
export GDK_BACKEND=wayland
export CLUTTER_BACKEND=wayland
export QT_QPA_PLATFORM=wayland-egl
export SDL_VIDEODRIVER=wayland
export QT_WAYLAND_FORCE_DPI=physical
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1

and on ~/.config/sway/config

input "1:1:AT_Translated_Set_2_keyboard" {
xkb_layout "jp,br"
xkb_model "jp(OADG109A)"
xkb_options "grp:rctrl_rshift_toggle,grp_led:scroll"
xkb_numlock enabled
}
exec_always fcitx -r

This two config files are sourced and will execute fcitx.

Must be noted that toggle key combinations here and fcitx must not be the same. So I choose rctrl here and default ctrl+space in fcitx/mozc.
The combination rctrl+rshift will change jp to pt-br layout and lit scroll lock.

**Comment by Laaas** [comment]
@emersion I want to work on adding support for this protocol; Do you think it's worth it even though it's still "being reviewed"? Are there going to be any drastic changes to it? Are there even any clients using the v2 protocol?

**Comment by emersion** [comment]
There's work for this in https://github.com/swaywm/sway/pull/4740

**Comment by lifranc** [comment]
> @emersion I want to work on adding support for this protocol; Do you think it's worth it even though it's still "being reviewed"? Are there going to be any drastic changes to it? Are there even any clients using the v2 protocol?

Pioneers are those who do not ask those questions, and just do it.
