### ISSUE TITLE
Documentation for multihead with X11 backend

### ISSUE THREAD

**Issue by mithodin** [swaywm/sway#3421]
I have spent some time figuring out how to do a workable multihead setup with the X11 backend. To spare others the frustration, I would like to do a small writeup and add it to the wiki. Would that be okay with the maintainers? If not, where would be the appropriate place to publish that information?

**Comment by emersion** [comment]
Sure, go ahead. But please add disclaimers that this isn't a recommended way to run sway, that a lot of features will be missing and that a regular setup should be used instead.

**Comment by mithodin** [comment]
That I can do.

**Comment by emersion** [comment]
Note: maybe it's possible to make each wlroots window fullscreen instead of moving it? This should increase performance.

**Comment by mithodin** [comment]
But then those windows will span the whole output, no?

**Comment by emersion** [comment]
Isn't this what you're trying to do with `xdotool`?

**Comment by mithodin** [comment]
Well, it depends on what you mean by fullscreen. The guide depends on X.org presenting a unified screen covering all physical screens. So, just going fullscreen would mean one window spanning all physical screens, which is not what I want. I've read a bit into the xdotool documentation and I don't think there is even a concept of fullscreen, because I don't have any underlying wm, just a pure X.org server. I may be wrong in that respect though.

**Comment by mithodin** [comment]
Well, at least for me, there is no obvious performance issue. Top shows Xorg at around 0.3% cpu and sway mostly at around 2% with occasional spikes to around 10.
