### ISSUE TITLE
System freeze when connecting external display.

### ISSUE THREAD

**Issue by c-edw** [swaywm/sway#3442]
I don't have a reliable way of reproducing this currently, nor any logs. It's only occurred twice out of the all the times I've connected an external display. It doesn't appear to be a crash, but instead a large consumption of system resources. The system will lag progressively worse over a few seconds and then freeze (laptop fan kicks in indicating high CPU usage).

I will add any more information I obtain here.

**Comment by emersion** [comment]
A `perf` record would be nice to have.

**Comment by anelam** [comment]
I have similar problems. My laptop is attached to a docking station. When I start sway from the tty, sometimes all screen stay black. When using the laptop without the attached displays (docking station) I have no problems. (I will provide logs later)

Additionally one of the two attached displays stay black after unlocking from swaylock with dpms management via swayidle. ([log](https://gist.github.com/anelam/711e599e60b6db40985ae63e84d4b907))

I use the latest master versions.

**Comment by emersion** [comment]
This seems like a different issue.

**Comment by c-edw** [comment]
I've finally got a repro on this. I'm working on something else at the moment so I'll come back with the `perf` later.

1.  Modify your Sway config such that a specific workspace will display on an external display when plugged in, for example:
```
output DP-1 pos 0 0 res 1920x1080
output eDP-1 pos 0 1080 res 1920x1080
workspace 1 output eDP-1
workspace 2 output DP-1
```
where `DP-1` is my external monitor.

2.  Start Sway **without the external monitor plugged in**
3.  Open two (unverified, could be any number) tiling windows (st, in my case) in the workspace specified to show on the external display, in my case workspace 2
4. Connect the external display
5. Observe that once the workspace moves to the external display, the system freezes

**Comment by Emantor** [comment]
You can try to use sysrq for the reboot, this way your logs will be flushed to disk.
If that does not work this might be a kernel issue and it would be useful to create a netconsole setup.
I also had some success by using SSH and attaching gdb to a running sway on my laptop to debug hotplug issues.

**Comment by emersion** [comment]
Yeah, attaching gdb would be a good idea too before perf records.

**Comment by c-edw** [comment]
SysRq has unfortunately never worked for me. I doubt that this freezing is a kernel issue. I'll have to get creative with this, thanks for the tips.

**Comment by c-edw** [comment]
I have retested this and can't produce the bug with the steps above anymore. It may have been inadvertently fixed. If it happens again, I will reopen this issue.
