### ISSUE TITLE
Cannot disable an input device

### ISSUE THREAD

**Issue by mdeff** [swaywm/sway#3443]
Using `swaymsg input <identifier> events disabled` (with identifiers taken from `swaymsg -t get_inputs`), I can disable many devices (trackpad, mouse, internal and external keyboard) but not my wacom pen. Any idea?

Edit: I was able to disable it with `xinput --disable 'Wacom ISDv4 EC Pen'` under X11 with libinput, so that should not be a libinput issue.

**Comment by emersion** [comment]
Can you send a debug log?

**Comment by mdeff** [comment]
[Debug log](https://gist.github.com/mdeff/a37b5816e9304ddbfd54b3bf611264e9). I started sway with `sway -d 2> ~/sway.log` then ran `swaymsg input 1386:236:Wacom_ISDv4_EC_Pen events disabled` followed by `swaymsg exit`.

**Comment by emersion** [comment]
Weird, it seems we do call `libinput_device_config_send_events_set_mode(dev, LIBINPUT_CONFIG_SEND_EVENTS_DISABLED)` (line 1379).

**Comment by mdeff** [comment]
Any idea how I can track that further?

**Comment by RedSoxFan** [comment]
Can you please post a log using this branch https://github.com/RedSoxFan/sway/tree/libinput-send-events-verbose? I added some code to check the status returned by `libinput_device_config_send_events_set_mode`

**Comment by mdeff** [comment]
I got a build failure:
```
/usr/bin/ld: sway/345c74e@@sway@exe/desktop_xdg_shell.c.o: in function `_close':
/tmp/makepkg/sway-git/src/build/../sway/sway/desktop/xdg_shell.c:236: undefined reference to `wlr_xdg_toplevel_send_close'
/usr/bin/ld: sway/345c74e@@sway@exe/desktop_xdg_shell.c.o: in function `close_popups_iterator':
/tmp/makepkg/sway-git/src/build/../sway/sway/desktop/xdg_shell.c:246: undefined reference to `wlr_xdg_popup_destroy'
```

**Comment by emersion** [comment]
Please upgrade wlroots.

**Comment by mdeff** [comment]
The issue seems to be ([full debug log](https://gist.github.com/mdeff/d18beeffb00a28dcb2ef453f7c8f7d5c)):
```
[input-manager.c:202] input_manager_libinput_config_pointer(1386:236:Wacom_ISDv4_EC_Pen)
[input-manager.c:276] libinput_config_pointer(1386:236:Wacom_ISDv4_EC_Pen) send_events_set_mode(1)
[input-manager.c:281] Unsupported event mode 1
[input-manager.c:284] Supported bitmask: 0
```

That's surprising as `xinput --disable` used to work. I guess sway should also report a failure?

**Comment by emersion** [comment]
Note that `events disabled` doesn't necessarily means it's completely disabled.

**Comment by RedSoxFan** [comment]
> Note that events disabled doesn't necessarily means it's completely disabled.

True. Should we add actual enabled/disable commands then?

**Comment by emersion** [comment]
(Context about "doesn't necessarily mean it's completely disabled")

>The Send Events Mode is libinput’s terminology for disabling a device. It is more precise in that the device only stops sending events but may not get fully disabled. For example, disabling the touchpad on a Lenovo T440 and similar leaves the top software buttons enabled for the trackpoint. Available options are enabled (send events normally), disabled ( do not send events), disabled on external mouse (disable the device while an external mouse is plugged in).

https://wayland.freedesktop.org/libinput/doc/latest/configuration.html

**Comment by emersion** [comment]
I don't get why `events disabled` isn't supported for the device. Maybe we should ask libinput devs about this?

**Comment by RedSoxFan** [comment]
After looking at the libinput source, it appears that libinput supports `LIBINPUT_CONFIG_SEND_EVENTS_DISABLED` for all devices, except tablet tools.

**Comment by whot** [comment]
> After looking at the libinput source, it appears that libinput supports LIBINPUT_CONFIG_SEND_EVENTS_DISABLED for all devices, except tablet tools.

that's a bug, please file one in libinput for this. tablets have a different backend so I probably forgot to implement this bit there and no-one noticed.

**Comment by emersion** [comment]
Reported here: https://gitlab.freedesktop.org/libinput/libinput/-/issues/476

**Comment by emersion** [comment]
Fixed in libinput: https://gitlab.freedesktop.org/libinput/libinput/-/commit/0d06bfc4e27bf4a56a7f34b3f20c4a61570e765c
