### ISSUE TITLE
swaybar tray: Inherited themes not getting processed because of typo

### ISSUE THREAD

**Issue by bitthief** [swaywm/sway#3445]
I've been debugging the swaybar tray implementation and realized that there's a typo in the code which prevents inherited themes from being picked up properly:

https://github.com/swaywm/sway/blob/70637b40fe98bda420e279e2e059fc93a9f538d6/swaybar/tray/icon.c#L138

This should be obviously changed to **Inherits**.

Patch which fixes the issue:

```
--- a/swaybar/tray/icon.c	2019-01-16 06:50:14.242595574 +0200
+++ b/swaybar/tray/icon.c	2019-01-16 06:50:51.744594107 +0200
@@ -135,7 +135,7 @@ static int entry_handler(char *group, ch
 			theme->name = strdup(value);
 		} else if (strcmp(key, "Comment") == 0) {
 			theme->comment = strdup(value);
-		} else if (strcmp(key, "Inherists") == 0) {
+		} else if (strcmp(key, "Inherits") == 0) {
 			theme->inherits = strdup(value);
 		} else if (strcmp(key, "Directories") == 0) {
 			theme->directories = split_string(value, ",");
```

I'm using the Faenza-Dark theme and swaybar is still not picking it up, it only reports five themes being picked up on my system (ironically including Faenza and Faenza-Ambiance), so I need to debug more. I'll open a new issue when I get to the bottom of it.

**Comment by RedSoxFan** [comment]
Can you please submit the patch as a PR?

**Comment by ianyfan** [comment]
Good catch, submit a PR.

Feel free to ask me any questions about the tray implementation to help you debug the problem.
