### ISSUE TITLE
Sway crashes when closing any window

### ISSUE THREAD

**Issue by daanjderuiter** [swaywm/sway#3450]
This happens for any type of window, I have obtained logs for it with Alacritty. I am on version "1.0-beta.2-153-ga43863aa (Jan 13 2019, branch 'master')", wlroots version "0.2.r130.g0e0ba65b-1". Debug log: [sway.log](https://github.com/swaywm/sway/files/2769676/sway.log). Stack trace: [swaybt.log](https://github.com/swaywm/sway/files/2769680/swaybt.log). To eliminate any possible unrelated variables, I limited my sway config to
```
set $mod Mod4
bindsym $mod+Return exec alacritty
bindsym $mod+Shift+q kill
```
I have no clue why this is happening, any help would be greatly appreciated.

**Comment by daanjderuiter** [comment]
When running sway from the command line inside i3 (no debug flag), the sway session stops in the described fashion with the message "sway: symbol lookup error: sway: undefined symbol: wlr_xdg_surface_send_close". These errors usually indicate to me that wlroots needs updating, but in this case both sway and wlroots are at their most recent versions as provided in the Arch User Repo, which directly source their respective GitHub-repos.

**Comment by emersion** [comment]
>These errors usually indicate to me that wlroots needs updating

Indeed, your wlroots is out-of-date. Maybe you have multiple wlroots versions installed and it's picking an older version. Find out with `ldd $(which sway) | grep wlroots`.

**Comment by emersion** [comment]
This stacktrace looks corrupted. `wlr_region_rotated_bounds` doesn't call `handle_unmap`, and `nrects = 21977` is impossible.

**Comment by emersion** [comment]
Ah, and I cannot reproduce.

**Comment by daanjderuiter** [comment]
Purging any sway-related files and reinstalling fixed the issue
