### ISSUE TITLE
Thunar FileManager Segfaults

### ISSUE THREAD

**Issue by jnduli** [swaywm/sway#3453]
I've been trying to use thunar file manager with sway but each time it fails with a segfault.
I tried running thunar with gdb and here is the log:

```
(gdb) run
Starting program: /usr/bin/thunar
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff352e700 (LWP 2577)]
[New Thread 0x7ffff2d2d700 (LWP 2578)]
[New Thread 0x7ffff24ea700 (LWP 2579)]
[New Thread 0x7ffff1ce9700 (LWP 2580)]

Thread 1 "thunar" received signal SIGSEGV, Segmentation fault.
0x00007fff00000033 in ?? ()
```

I'm not sure what is the problem and this occurs every single time. I've tested this with i3 and it doesn't crash (so I believe it's an issue related to sway).

This is the sway version I'm running:

```
sway version 1.0-beta.2-103-g728e5700 (Jan  6 2019, branch 'master')
```

What file manager works well with swaywm?

**Comment by emersion** [comment]
This seems to be a thunar issue.

Is thunar running natively under Wayland or is it running as an X11 app via Xwayland? Can you send a `WAYLAND_DEBUG=client` log?

>What file manager works well with swaywm?

Please don't workaround the issue, instead help fixing it! :)

**Comment by sydneymeyer** [comment]
I have thunar also crashing when launching with "GDK_BACKEND=wayland" in .bashrc, as soon as i interact with it.. no problems with x11 backend.

**Comment by emersion** [comment]
Please report this to the Thunar devs.
