### ISSUE TITLE
Sway segfaults on startup 

### ISSUE THREAD

**Issue by Bryophyllum** [swaywm/sway#3459]
* Sway Version: sway version 1.0-beta.2-212-gdc1eac0c (Jan 18 2019, branch 'master')
* Configuration File: https://gist.github.com/Bryophyllum/57110715fbe7620bc55b086e1f692af6
* Stack Trace, if sway crashes: https://gist.github.com/Bryophyllum/25e6b675a77fc6070df9a8772f122935

However, I've got Sway to work on a X11 session by accidentally running it while troubleshooting the problem on my backup i3 setup.

**Comment by emersion** [comment]
Do you have the latest commit?

**Comment by emersion** [comment]
Can you try https://github.com/swaywm/sway/pull/3460?

**Comment by Bryophyllum** [comment]
@emersion I've re-built master branch of Sway just now and it works. I must've built it within a short time window where the neccessary commit was not merged, given that Arch's `makepkg` reports wlroots to be up-to-date with its master branch. I was really unlucky it appears. 😅

**Comment by emersion** [comment]
Eh, I see. I think https://github.com/swaywm/sway/pull/3454 broke sway and https://github.com/swaywm/sway/pull/3455 fixed it, and I've missed it because I was working on both at the same time. Sorry about that.
