### ISSUE TITLE
Tray Icon not updating / interaction

### ISSUE THREAD

**Issue by Moelf** [swaywm/sway#3465]
* Sway Version: `sway version 1.0-beta.2-224-g639b66b6 (Jan 18 2019, branch 'master')`

I can see tray icons such as skype and vpns, but 1) I need Ctrl-C to refresh their display status 2) they are not clickable. Is this currently a supported feature?

If so is there any further documentation than `man sway-bar`. Thx.

**Comment by ianyfan** [comment]
Some apps' menus don't work because they use the canonical dbus protocol, which hasn't been implemented yet.
However, their status should change, can you attach a debug log?

**Comment by Moelf** [comment]
> Some apps' menus don't work because they use the canonical dbus protocol, which hasn't been implemented yet.
> However, their status should change, can you attach a debug log?

https://pastebin.com/y5pRY5Cw

**Comment by ianyfan** [comment]
Ah, sorry, I mean for swaybar. This probably means you have to run it manually, i.e. `swaybar -d -b <bar-id>` (use `swaymsg -t get_bar_config` to get ids)

**Comment by kbrah** [comment]
I have the same problem

This is my debug log 
https://pastebin.com/6x8gBm0Z

**Comment by Moelf** [comment]
> Ah, sorry, I mean for swaybar. This probably means you have to run it manually, i.e. `swaybar -d -b <bar-id>` (use `swaymsg -t get_bar_config` to get ids)

https://pastebin.com/CYj5z8W6

**Comment by Moelf** [comment]
the delay in icon status update is fixed in the latest master.

**Comment by ianyfan** [comment]
Fixed by https://github.com/swaywm/sway/pull/3502/ possibly?

**Comment by kevr** [comment]
> Fixed by #3502 possibly?

No, this does not fix the interaction issue.

**Comment by RPigott** [comment]
The updating issue was fixed. See #6249 for menu support.
