### ISSUE TITLE
Add ability to select input event modes to toggle

### ISSUE THREAD

**Issue by The-King-of-Toasters** [swaywm/sway#3470]
- Sway version: `sway version 1.0-beta.2-226-g1cce14e7 (Jan 19 2019, branch 'master')`
- Debug log: https://www.sgregoratto.me/paste/sway-test.log

## Details

Toggling my T420's touchpad does not immediately disable it, as it takes one extra toggling to do so. This does not happen when re-enabling the touchpad using the same command. The following table shows whats happening on my end:

|Event|Touchpad Status|Expected Touchpad Status|
|-|-|-|
|startup (default)|ON|ON|
|`input ... toggle`|ON|OFF|
|`input ... toggle`|OFF|ON|
|`input ... toggle`|ON|OFF|

## Steps to reproduce

I have the following line in my config:

    bindsym XF86TouchpadToggle      input "2:7:SynPS/2_Synaptics_TouchPad" events toggle

But the behaviour can be observed using the default config and following these steps:

1. `exec sway -c /etc/sway/config`
2. Open a terminal and run `swaymsg input "2:7:SynPS/2_Synaptics_TouchPad" events toggle`

**Comment by RedSoxFan** [comment]
A touchpad likely supported three modes: `enabled`, `disabled_on_external_mouse`, and `disabled`. Currently `events toggle` cycles through all supported modes for the device.

**Comment by The-King-of-Toasters** [comment]
Oh yeah, looks like I missed that section in sway-input(5). Since this is related to #3443, I also support separating disabled_on_external_mouse.

**Comment by RedSoxFan** [comment]
> I also support separating disabled_on_external_mouse.

I no longer have any interest in doing that. I spaced out on some things that libinput event modes handle differently than a true enable/disable and it does not make sense to change the existing command.

As for this issue, I'd rather just add the ability to list the modes to toggle, falling back to all supported modes. This would be somewhat similar to how layout toggle works
