### ISSUE TITLE
Better default output mapping for touch devices

### ISSUE THREAD

**Issue by edrex** [swaywm/sway#3475]
Touch devices are currently mapped to the coordinate rect containing all outputs. I think this isn't a good default mapping since it's never correct: most touch devices are coupled to a display, we just don't know which one.

## Proposal
 1. With no metadata about how touch devices should be mapped, map to the first output by default.
 2. In a later iteration, maybe use libwacom metadata (IntegratedIn [example](https://github.com/linuxwacom/libwacom/blob/master/data/wacom.example#L50), [list thread](https://sourceforge.net/p/linuxwacom/mailman/linuxwacom-devel/thread/20121122232734.GA4812%40yabbi.HOME/#msg30133982))) to make a better guess.

**Comment by emersion** [comment]
Yeah, I'm not sure this is enough. Nobody sets the edev `WL_OUTPUT` property, and its meaning is not well-defined since output names are not consistent between compositors.

Related to https://github.com/swaywm/wlroots/issues/940

**Comment by haukened** [comment]
Is there any update to this?  I just switched from i3 to sway, and i'm definitely missing this functionality.
in X11 there's the `xinput --map-to-output` option.  I've read through this but don't quite understand.  Is there some way i can manually map it for my setup? or assist in helping with an automated solution?

**Comment by edrex** [comment]
@haukened you can map to output in sway.conf/via swaymsg https://github.com/swaywm/sway/blob/master/sway/sway-input.5.scd#mapping-configuration

**Comment by haukened** [comment]
This worked perfectly. Thank you!

**Comment by emersion** [comment]
We now have heuristics to automatically map built-in touchscreens to built-in outputs.
