### ISSUE TITLE
[Question] Change $mod based on keyboard

### ISSUE THREAD

**Issue by J0nnyMak0** [swaywm/sway#3479]
I have a Model M keyboard that I want to use right control as the mod key on. I want to be able to do this on the fly. I used to do this in X with Xmodmap like so:
```
remove mod4 = Super_L Super_R
remove control = Control_R
add mod4 = Control_R
```
What is the best way to achieve this in Sway?

**Comment by Kommynct** [comment]
You're going to have to learn how to edit xkb.

/usr/share/X11/xkb/symbols/us

is the file you'd want to edit, but that'll edit it globally.

**Comment by RedSoxFan** [comment]
You should be able to run the following from a binding or swaymsg:
```
input <identifier> xkb_options ctrl:swap_rwin_rctl
```
You can get the `<identifier>` for the keyboard from `swaymsg -t get_inputs`

See `man 5 sway-input` and `man 7 xkeyboard-config` for more information/options.

**Comment by aerappa** [comment]
I'm having a similar issue. Want to swap caps and escape. I was trying to emulate the example in `/etc/sway/config` but I'm getting errors. I attached my config and log file as well as the output of `swaymsg -t get_inputs`
[get_inputs.log](https://github.com/swaywm/sway/files/2777659/get_inputs.log)
[sway.log](https://github.com/swaywm/sway/files/2777660/sway.log)

. Thanks in advance.

**Comment by RedSoxFan** [comment]
@aerappa, Sway 0.15.0 does not support the configuration options. I would recommend installing sway from git master (Sway has been completely rewritten since 0.15.x). I have no idea if the dependencies are up-to-date on Ubuntu 18.04 or if you would have to compile those from source as well.

**Comment by JonnyMako** [comment]
> You should be able to run the following from a binding or swaymsg:
> 
> ```
> input <identifier> xkb_options ctrl:swap_rwin_rctl
> ```
> 
> You can get the `<identifier>` for the keyboard from `swaymsg -t get_inputs`
> 
> See `man 5 sway-input` and `man 7 xkeyboard-config` for more information/options.

@RedSoxFan  is there a way to apply sequentially? For example, this seems to do something but not quite what I was expecting:
```
xkb_options altwin:swap_alt_win,ctrl:swapcaps
```

**Comment by RedSoxFan** [comment]
Try the following (it appears to work for me):
```
xkb_options "altwin:swap_alt_win,ctrl:swapcaps"
```

Commas are used to separate a list of commands so they have to be in quotes otherwise it won't be parsed correctly.

**Comment by JonnyMako** [comment]
Indeed, it seems to work for the inbuilt keyboard for my laptop, but on my external PS2 keyboard, `lctrl` is not working. Using xev, I can see the remapping worked, and the keypress is registered as `Control_L`, but shortcuts using the `ctrl` key don't work. So I'm at a loss. Let me know if someone can think of a way to debug. thanks!

(The external keyboard is an omni key ultra T and has a dipswitch to switch ctrl-alt-caps. I encounter the same problem in both diswitch positions.)

**Comment by RedSoxFan** [comment]
You can try: `xkb_model omnikey101`, but if the keypress is registering correctly in xev, I'm not sure it will have any effect.

**Comment by JonnyMako** [comment]
> You can try: `xkb_model omnikey101`, but if the keypress is registering correctly in xev, I'm not sure it will have any effect.

Thanks for the reply. Yes, specifying xkb_model did not fix it. No big deal. I'll can live with a slightly less ergonomic position for `ctrl` :grin:
