### ISSUE TITLE
[question] setting bindsym

### ISSUE THREAD

**Issue by copypaste10** [swaywm/sway#3483]
sway version 1.0-beta.2-91-g3d7c20f0 (Dec 31 2018, branch 'master')

"bindsym $mod+d exec $menu" in the sway config is the standard to use dmenu.
$mod is assigned to the Super-Key. I want to use only 1 key, but it doesn't work.

Only "bindsym $mod exec $menu", then dmenu doesn't open. How can I only keybind 1 key to open dmenu?

**Comment by RedSoxFan** [comment]
`bindsym Super_L exec $menu` should work. `Mod4` is a modifier and `Super_L`/`Super_R` are the keys themselves.
