### ISSUE TITLE
Launching xembedproxy crashes swaybar with tray enabled

### ISSUE THREAD

**Issue by jakebailey** [swaywm/sway#3487]
Forgive me if I'm jumping the gun on testing the new tray with `xembedsniproxy`, but the bar crashes when I try to launch the proxy to get any of my icons to show up.

- Sway version: `sway version 1.0-beta.2-243-g410c9613 (Jan 21 2019, branch 'master')` (with a small patch to set `enable-tray` to `true`).
- xembedsniproxy version: `xembed-sni-proxy-git v5.14.90.r14.gad1a76b8-1`
- Debug log: https://termbin.com/z4kh
- Backtrace: https://termbin.com/gs12

All that I need to reproduce the problem is:

1. Start sway.
2. Start `xembedsniproxy`.
3. Start Chromium (with something which adds tray icons, i.e. running in the background or Hangouts).
4. swaybar crashes, a window is created for each tray icon, and a black box appears in the top left corner of the screen on all workspaces.

Interestingly through some combination of stopping the proxy, closing things, and starting again with Chromium already loaded, I can get it to not crash. As in, it's the same as step 4 above, but instead of crashing, I get the two icons which should have loaded in the bar (but very garbled and changing).

**Comment by ianyfan** [comment]
The plan is to eventually build an xembed proxy into swaybar, though it's not very high priority right now.

I have trouble debugging this because I've been struggling to build xembedproxy for myself. (can't work out how cmake works lol)
