### ISSUE TITLE
Disable Xwayland at runtime?

### ISSUE THREAD

**Issue by c-edw** [swaywm/sway#3492]
In #676, the env variable `WLC_XWAYLAND` is said to disable Xwayland. Obviously, wlc isn't used and this variable doesn't exist anymore. It looks like the only way to run Sway without Xwayland right now is to compile with Xwayland disabled in `meson_options.txt`.

Could a new env variable be introduced to disable Xwayland at runtime, or are users expected to just compile without Xwayland support?

**Comment by emersion** [comment]
You can use the `xwayland` config option.

**Comment by c-edw** [comment]
I haven't seen this documented anywhere so I'll add it to the wiki.

**Comment by emersion** [comment]
If it's not in the manpage, please add it there.
