### ISSUE TITLE
Support for key remapping

### ISSUE THREAD

**Issue by rhajdacki** [swaywm/sway#3503]
Are there any plans (or maybe it is already somehow possible) to support key remapping to achieve similar effects to Authotkey or Autokey? 
So it would be possible to make CapsLock work as additional modifier key and CapsLock+H, CapsLock+J, CapsLock+K, CapsLock+L shortcuts act as cursor keys?

**Comment by ddevault** [comment]
You can do some of this with xkb, check out xkeyboard-config(7)

**Comment by rhajdacki** [comment]
As far as I can see this is not possible with xkeyboard-config. You can turn CapsLock into Hyper with `caps:hyper` in xkb_options. However for example making Hyper+H generate left cursor key press does not seem possible.
There is no command in Sway to generate "virtual" key presses so setting shortcut with `bindsym` also isn't an option. `xdotool` could be a solution but it is X specific.
Is there anything I missing here? 
Does adding key automation command seem as good fit for Sway?

**Comment by ddevault** [comment]
bindsym Hyper+h seat seat-0 cursor press button1; seat seat-0 cursor release button1

**Comment by emersion** [comment]
>keyboard cursors

What are these? Are you referring to sending a left arrow key?

**Comment by rhajdacki** [comment]
Yeap: https://en.wikipedia.org/wiki/Arrow_keys

**Comment by emersion** [comment]
Then you'll be interested in this issue: https://github.com/swaywm/sway/issues/1779

**Comment by nostdm** [comment]
Interesting coincidence, I was just doing the exact same thing, trying to map CapsLock to Hyper and use it as a modifier. I added `xkb_options caps:hyper` but realized there is currently no way to map one key to another in sway (good to see it's already being worked on). 

I will look into using ydotool but not sure why it pulls in custom libraries `libevdevPlus` and `libinputPlus`

**Comment by rhajdacki** [comment]
I haven't tried ydotool yet. There other tools out there that use `/dev/uinput` like for example https://github.com/myfreeweb/evscript . They don't seem mature though.

**Comment by progandy** [comment]
You can probably copy your keyboard layout from ```/usr/share/X11/xkb/symbols/``` to a new name in ```~/.xkb/symbols/```, modify it and then set your keyboard layout in sway to that.

https://wiki.archlinux.org/index.php/X_keyboard_extension#Mouse_control
https://www.vinc17.net/unix/xkb.en.html

**Comment by jpeeler** [comment]
Unsure if commenting on such an old issue is helpful. But wanted to document this somewhere (along with perhaps receiving some validation of my assumptions). To start, here's a working config to have caps lock remapped to hyper:

~/.config/sway/config:
```
input "type:keyboard" {
    xkb_layout "custom"
    #xkb_options caps:hyper
    #xkb_file ~/.config/xkb/custom
}
bindsym mod3+f [app_id="foot"] focus
```

~/.xkb/symbols/custom:
```
# verify with xmodmap
xkb_symbols "basic" {
  include "pc+us"

  replace key <CAPS> {
    [ Hyper_L, Hyper_L ]
  };

  modifier_map Mod3 { Hyper_L };
};
```

What I found was that using xkb_options for changing caps to hyper worked, but didn't change the modifier it was associated with (which by default is mod4, [shown also here](https://github.com/baskerville/sxhkd/issues/175#issuecomment-636404995)). I'm assuming that specifying xkb_file is used when one wants to override all of the various components, so here with just the symbols xkb_layout was much easier to configure.

It seems Hyper has had some type of special handling in the past over the course of several years:
https://github.com/swaywm/sway/commit/eea80e7276f49e5d07b22db071f3ab0b6f9ffe18 - (2017)
https://github.com/swaywm/sway/commit/1d8591d9026c19f5c308bed5961341b00aef69ca - (2015)

But now, here are the current modifiers:
https://github.com/swaywm/sway/blob/a55472c6d882d806e9d6fc0a78a7f7d8f888492e/sway/input/keyboard.c#L22-L33

I'm guessing that it was the old special handling that allowed the comment that [Drew made](https://github.com/swaywm/sway/issues/3503#issuecomment-457212559) earlier to work. Even with my remapping in place `Hyper` is not detected as valid, but `Hyper_L` is (neither actually works though).

Ultimately my config looks very similar to what is linked from the [wiki](https://github.com/swaywm/sway/wiki#load-a-modified-custom-xkb-keymap-xmodmap-equivalent). I just spent so much time trying to get everything working with just the xkb_options.
