### ISSUE TITLE
Firefox waitcursor causes hang and firefox "crash", includes testcase

### ISSUE THREAD

**Issue by cg9999** [swaywm/sway#3506]
Versions:
sway version 1.0-beta.2-268-g8b056cfc (Jan 23 2019, branch 'makepkg')
wlroots 0.2.r154.gc41d0130-1
Firefox nightly 66.0a1 (2019-01-23) (64-bit) running in wayland mode
Running on Arch Linux with latest updates.

Description:
Web page showing the spinning wait mouse pointer causes first some kind of hang, where mouse cannot be moved, but the animation continues.

After a few seconds firefox crashes/disappears, but no error messages or core dumps are produced. Mouse will again move when firefox has disappeared.

If running in xwayland mode, no issues. Also no issues under Weston.

Debug log:
[sway_firefox_waitcursor_debuglog.txt](https://github.com/swaywm/sway/files/2788521/sway_firefox_waitcursor_debuglog.txt)

HTML testcase to show the waitcursor
[testcase.zip](https://github.com/swaywm/sway/files/2788524/testcase.zip)

**Comment by emersion** [comment]
Can you send a `WAYLAND_DEBUG=client firefox` log? (It'll be big, please don't move the mouse while the cursor is spinning)

**Comment by cg9999** [comment]
WAYLAND_DEBUG=client firefox log:
[clientdebug.zip](https://github.com/swaywm/sway/files/2788680/clientdebug.zip)

**Comment by edrex** [comment]
I can't reproduce with the testcase.

```
sway version 1.0-beta.2-274-g5f45a4bb (Jan 26 2019, branch 'master')
wlroots 209210d307 (master Jan 25)
firefox-nightly 66.0a1.20190126-1 (via AUR)
```
Interestingly with the official nightly the wait cursor amimates, while with the flatpak build it doesn't. But no crash.

**Comment by cg9999** [comment]
I'll close this as it seems to be fixed now.
I believe it may have been related to  #3368
Thanks for fixing!
