### ISSUE TITLE
Crash when attaching a tablet pen to a new seat

### ISSUE THREAD

**Issue by YaLTeR** [swaywm/sway#3512]
* Sway Version: `1.0-beta.2-271-gba96983b (Jan 24 2019, branch 'master')`
* Debug Log: https://gist.github.com/YaLTeR/3f8205e6282312ee83480452a18da55a#file-sway-log
* Configuration File: default
* Stack Trace, if sway crashes: https://gist.github.com/YaLTeR/3f8205e6282312ee83480452a18da55a#file-backtrace

1. Open a terminal.
2. `swaymsg seat seat1 attach 10429:117:UGTABLET_TABLET_G3_4x3_Pen`
3. Sway crashes.

This is one of the input devices registered by my drawing tablet.

**Comment by schickst** [comment]
I was able to reproduce the crash when using the beta.2 version you mentioned in combination with wlroots-0.2. 

However, with the current sway-rc1 and the corresponding wlroots-0.3 no crash occurred. 
@YaLTeR, can you confirm this?

**Comment by YaLTeR** [comment]
Still reproduces on `sway version 1.0-rc1-31-gee56428b (Feb  7 2019, branch 'master')` and https://github.com/swaywm/wlroots/commit/20d404a091fa92f56be4825bbaf89e4027fda154
