### ISSUE TITLE
crash on "move" command in tabbed mode

### ISSUE THREAD

**Issue by rvi64** [swaywm/sway#3527]
* Sway Version: sway version 1.0-beta.2-282-g6b8bf109 (Jan 28 2019, branch 'master')

* Debug Log: [sway.log](https://gist.github.com/rvi64/8b75ecf9904a77adc32528c3e0d8d2a1)

in tabbed layout when trying to "move" a window in the position it can not be in, like move right-most window to the right, or left-most window to the left, sway crashes. works on any configuration, or just by `swaymsg 'move up'`.

**Comment by emersion** [comment]
Please provide a stack trace. You can do so by running `coredumpctl gdb` and then `bt full`.

**Comment by rvi64** [comment]
[trace](https://gist.github.com/rvi64/1ee59109937e508fd9fda00e5a29a3f4)
