### ISSUE TITLE
Error: Target STRING not available

### ISSUE THREAD

**Issue by yory8** [swaywm/sway#3533]
sway version 1.0-beta.2-281-g68a28e48

This happens when I try to paste some text copied from an application that has been since quitted. Instead than the text itself, I get this error message.

I would expect sway to just remember the copy buffer even after quitting, as it's the most convenient solution (if privacy is a concern, it could be put behind a config).
Or, if it's by design, just nothing at all (the error message ends with a newline, which in some applications equates to an ENTER).

**Comment by ddevault** [comment]
I assume you're an alacritty user?

**Comment by emersion** [comment]
>I would expect sway to just remember the copy buffer even after quitting, as it's the most convenient solution (if privacy is a concern, it could be put behind a config).

This isn't possible without a password manager.

**Comment by ddevault** [comment]
Well, this is a bug in alacritty. I assume it's also a bug in firefox.

**Comment by ddevault** [comment]
By password manager, @emersion means clipboard manager.

**Comment by emersion** [comment]
Related to https://github.com/jwilm/alacritty/pull/1583

**Comment by yory8** [comment]
@emersion yes, and https://github.com/neovim/neovim/issues/2642, it seems to be about xclip, though I didn't know it was used in firefox

**Comment by emersion** [comment]
For the record, the Wayland equivalent to `xclip` would be `wl-clipboard`, you could make a PR to add support for it in neovim.

I think Firefox uses directly the X11 API so I'm not sure what happens here. I also never had this kind of issue with Firefox and I use it as my daily driver, copy-pasting from/to xwayland/wayland apps all the time.

**Comment by yory8** [comment]
@emersion in fact, I'm not getting it anymore "from geany to firefox"  nor "from alacritty to firefox" . that's weird, I could swear it happened just yesterday :confused:
