### ISSUE TITLE
sway doesn't build anymore

### ISSUE THREAD

**Issue by CaptainBloodz** [swaywm/sway#3544]
Hi,
sway failed to compile here, using ninja-1.8.2 & scdoc-1.5.2 :

ninja -C build
ninja: Entering directory `build'
[1/263] Generating sway.5 with a custom command.
FAILED: sway.5 
/bin/sh -c '/usr/bin/scdoc < ../sway/sway.5.scd > sway.5'
Error at 61:9: Cannot nest inline formatting.
[2/263] Generating sway-bar.5 with a custom command.
FAILED: sway-bar.5 
/bin/sh -c '/usr/bin/scdoc < ../sway/sway-bar.5.scd > sway-bar.5'
Error at 13:8: Cannot nest inline formatting.
[3/263] Generating sway-input.5 with a custom command.
FAILED: sway-input.5 
/bin/sh -c '/usr/bin/scdoc < ../sway/sway-input.5.scd > sway-input.5'
Error at 10:70: Cannot nest inline formatting.
[4/263] Generating sway-output.5 with a custom command.
FAILED: sway-output.5 
/bin/sh -c '/usr/bin/scdoc < ../sway/sway-output.5.scd > sway-output.5'
Error at 13:56: Cannot nest inline formatting.
[6/263] Generating 'protocols/protocol...ta/xdg-output-unstable-v1-protocol.c'.
ninja: build stopped: subcommand failed.

**Comment by capelito** [comment]
Hi,
I also have problems installing sway-git from the Archlinux AUR:

scdoc 1.8.1 is installed

$ yay -S sway-git

/usr/bin/sh -c '/usr/bin/scdoc < ../sway/sway/sway-bar.5scd > sway-bar.5'
Error at 23:0: Expected _ before starting new paragraph (begain with _ at 21:75)

**Comment by Kunagi7** [comment]
@capelito I had this issue too! I solved it by compiling scdoc from git and checking out to the tag 1.8.0. 
I tried to compile scdoc directly from master (1.8.1) and it threw the same error.

**Comment by CaptainBloodz** [comment]
Ok, Used to work.
Thks

**Comment by emersion** [comment]
I believe this is a scdoc bug. @ddevault, any ideas?

**Comment by emersion** [comment]
A temporary workaround for those who build manually is `meson build -Dman-pages=disabled`.

**Comment by emersion** [comment]
Fixed in https://github.com/swaywm/sway/commit/82461c4165ce44e1ea63d5d8c3bda080b6f57148. Please update to scdoc 1.8.1.
