### ISSUE TITLE
Windows not equal sizes after leaving fullscreen.

### ISSUE THREAD

**Issue by c-edw** [swaywm/sway#3547]
Similar to #2866.

![image](https://user-images.githubusercontent.com/38229097/52090179-8190e180-25a8-11e9-9934-79113a763062.png)

Steps to produce:
1. Move to an empty workspace
2. Spawn one window and fullscreen it ($mod+F)
3. Spawn two more windows whilst in fullscreen
4. Leave fullscreen ($mod+F)
5. Observe that one of the windows is larger than the other two

On i3, the windows would be of equal size.

**Comment by athrungithub** [comment]
it swaybar?.
 for my it's ok

**Comment by pedrocr** [comment]
Had a look at the code to try and see what was happening. It seems the sequence of events is something like this:

1. The window is fullscreen so now has the full width as it's size
2. New windows are opened and get 0 width
3. When fullscreen is finally exited then `apply_horiz_layout()` is finally called with a full-width size for the first window and 0 for all the others. This creates the uneven layout

Fixing this requires either not keeping the fullscreen width/height in the container width/height or changing the layout calculations to operate on saved_width and saved_height when fullscreen. The first option seems less of a hack but may require deeper surgery in the display code.
