### ISSUE TITLE
wl-paste causes layout flickering

### ISSUE THREAD

**Issue by carloabelli** [swaywm/sway#3548]
* Sway Version: sway version 1.0-beta.2-290-g4f4424f6 (Jan 29 2019, branch 'master')
* Debug Log: https://gist.github.com/carloabelli/e2ca02a8e68f42411e6919c5bbaab6da
* Configuration File: default

When running `wl-paste` (from [wl-clipboard](https://github.com/bugaevc/wl-clipboard)), the window(s) appear to very briefly jump to a different layout and then back to the original layout.

For instance if there is a single window open, it appears to quickly jump to ~50% width and then back to 100% width.

This does not happen on `wl-copy` only `wl-paste` and does not occur when using other methods of pasting e.g. ctrl-V.

**Comment by ianyfan** [comment]
Are you sure you're not using an old version of wl-clipboard?

**Comment by emersion** [comment]
In any case this isn't a sway bug. wl-clipboard used to use a hack to set the clipboard selection.

**Comment by husam212** [comment]
I'm having this issue with sway 1.0 and wl-clipboard 1.0.

**Comment by Emantor** [comment]
Yes, the release version of wl-clipboard has this bug. Update to the master version from git and bug the maintainer for another release :wink:
