### ISSUE TITLE
Black screen and cursor on PowerVR GPU

### ISSUE THREAD

**Issue by southern-tools** [swaywm/sway#3558]
I am getting a black screen trying to run sway on a Eee pc x101ch.
On the log file, I get the following error repeated in a loop:

`2019-02-02 14:24:17 - [wlroots-0.2/backend/drm/drm.c:357] Starting renderer on output 'LVDS-1'
2019-02-02 14:24:17 - [wlroots-0.2/backend/drm/legacy.c:21] LVDS-1: Failed to page flip: Invalid argument
2019-02-02 14:24:17 - [wlroots-0.2/backend/drm/drm.c:809] LVDS-1: Retrying pageflip`

It has integrated intel graphics, the output of `lspci | grep VGA` is:
`00:02.0 VGA compatible controller: Intel Corporation Atom Processor D2xxx/N2xxx Integrated Graphics Controller (rev 09)`

Thank you in advance for your help

**Comment by Emantor** [comment]
I suspect that this is a rebranded PowerVR graphics card, those cards do not have an open source driver, meaning they won't support modesetting.

**Comment by southern-tools** [comment]
I see, well, thank you very much for your help. I will still not close the ticket just in case somebody comes up with  a solution (but apparently you are right).

**Comment by mirh** [comment]
https://www.phoronix.com/scan.php?page=news_item&px=Linux-5.6-DMA-BUF-HEAPS
Or anyway, if you can get this to be backported to your current kernel version https://github.com/paulkocialkowski/linux/commit/804b4aed1211e301652c8e6237d2765ed2b79cce

**Comment by emersion** [comment]
Closing because this is about a closed-source driver. These aren't officially supported by Sway.
