### ISSUE TITLE
Commands issued via swaymsg aren't split at newlines

### ISSUE THREAD

**Issue by ianyfan** [swaywm/sway#3566]
Run `swaymsg "$(echo 'workspace 1\n workspace 2')"`

Result on i3: end up on workspace `2`

Result on sway: end up on workspace `1 workspace 2`

**Comment by ianyfan** [comment]
Commands in i3 also seem to not ignore whitespace, e.g. run `swaymsg 'workspace 2 '`

Result on i3: end up on workspace `2 `

Result on sway: end up on workspace `2`

**Comment by RedSoxFan** [comment]
> Commands in i3 also seem to not strip trailing whitespace

I'll fix that in a second PR since it affects binding too. I'll change the current one to not close this issue.

**Comment by RedSoxFan** [comment]
> > Commands in i3 also seem to not strip trailing whitespace
> 
> I'll fix that in a second PR since it affects binding too. I'll change the current one to not close this issue.

Actually it looks like that's a bug in i3 (https://github.com/i3/i3/issues/3316#issuecomment-405259574) so I'm just going to close this since I don't think we should add support for bugs.
