### ISSUE TITLE
Using bar goes to "$workspace" rather than $workspace

### ISSUE THREAD

**Issue by nperry** [swaywm/sway#3575]
Steps:
1. Use default config
2. Open a window on workspace 1. 
3. Move to workspace two
4. Using mouse click on the workspace 1

Actual:
Goes to "1"

Expected
Goes to 1

[neil@desktop ~]$ swaymsg -t get_version
sway version 1.0-rc1-11-g1e65cc1e (Feb  5 2019, branch 'master')

**Comment by v44r** [comment]
Reverting 1e65cc1e fixes it.
