### ISSUE TITLE
[Feature Request] Rounded Corners

### ISSUE THREAD

**Issue by facocalj** [swaywm/sway#3583]
Hello sway developers,

Rounded corners are super sexy.
Is there any chance of implementing them in sway?

Thank you!

**Comment by ddevault** [comment]
No chance.

**Comment by Th3Whit3Wolf** [comment]
### Questions
I think that rounded corners would be much desired feature for many people interested in tiling window managers

1.) Do you mean that there is no chance of implementing them now or there's  no chance of them ever being implemented?

2.) If someone wanted that feature would it be an i3-gaps scenario where they would need to fork sway or is there a way write a program that would implement that?

**Comment by DirectorX** [comment]
https://github.com/Javyre/bspwm/commit/6ccad79a927387780e497c4c613067286989984b
https://github.com/resloved/i3/commit/68fdfccc1a7fd094451ddda54c7f881e4f880609
https://github.com/Airblader/i3/issues/167#issuecomment-484335058

**Comment by HolyStephano** [comment]
I would like to see this added as well, but I don't see it as needed unless it gets merged into Airbladers fork.

**Comment by rileyinman** [comment]
It looks like as of [this commit](https://github.com/Airblader/i3/commit/001816781d591bd0038fb8a3e637743b16987aa9) to Airblader's fork, the corner radius can be set in i3-gaps. Does this mean it would be reconsidered for sway?

**Comment by Airblader** [comment]
That's very misleading. That commit I *not* merged into i3-gaps, its just a PR.

**Comment by blinry** [comment]
I'd also love to see this feature in sway! @ddevault, when you say "no chance", what exactly do you mean? Under which conditions could rounded corners end up in sway?

**Comment by emersion** [comment]
This means we aren't interested in having this feature upstream. Feel free to fork sway and add it.

**Comment by ahmadie** [comment]
Where is my round edges !!

**Comment by g00nix** [comment]
@ddevault why not?
