### ISSUE TITLE
XWayland DPI should always be 96 no matter which scaling settings are and which actual DPI displays have

### ISSUE THREAD

**Issue by m-khvoinitsky** [swaywm/sway#3584]
* XWayland DPI is autodetected based on random (?) plugged monitor on startup, does not changes at runtime (you may do it manually, though), has only one value per server no matter how many displays you have and how vary their DPIs (that's one of flaws of X11)
* X11 clients render bigger fonts based on aforementioned DPI
* Sway has its own scaling for each output and X11 windows get scaled twice

```
xdpyinfo | grep -B 2 resolution
screen #0:
...
  resolution:    118x118 dots per inch
```

Workaround: place the following on the top of your sway config:
```
exec --no-startup-id xrandr --dpi 96
```

* Sway Version:
```
$ swaymsg -t get_version
sway version 1.0-rc1-8-ga1a99421 (Feb  4 2019, branch 'master')
```

**Comment by emersion** [comment]
This is an Xwayland bug: https://github.com/swaywm/wlroots/issues/1119

Would be nice to understand what's going on in Xwayland's code.

**Comment by m-khvoinitsky** [comment]
In my case, 118x118 dots per inch is an actual DPI of one of my displays, so it looks like something a bit different.

**Comment by m-khvoinitsky** [comment]
It seems that XWayland merely (as well as regular xorg server) gathers DPI from EDID which works fine if you have one display and a regular xorg server. But if you have a wayland compositor which scales windows according to their preferences and assuming that everything that comes from XWayland is 96 dpi, some issues happen.

**Comment by emersion** [comment]
DPI != scale

DPI can be used by X11 clients to adjust their font size. However all X11 clients are well aware that they should render in LoDPI, and they do so.

In the end, this doesn't sound like a bug to me.

**Comment by m-khvoinitsky** [comment]
> DPI != scale

Well, ignoring custom user's preferences based on display proximity, vision, etc., in perfect setup, scale should be equal to display's DPI divided by 96 to get the same picture on different displays to be the same physical size. So, it's not the same, true, but they correlate.

> However all X11 clients are well aware that they should render in LoDPI, and they do so.

That's not true. They do it for everything except for fonts. Try to exec, for example, `xrandr --dpi 192` and then restart any of your X11 clients.

Probably, XWayland should not try to detect display's DPI and always use 96 in the first place. From that point, it may be considered as XWayland bug.

**Comment by emersion** [comment]
>scale should be equal to display's DPI divided by 96 to get the same picture on different displays to be the same physical size

Scale matching DPI seems pretty unlikely.

>That's not true. They do it for everything except for fonts. Try to exec, for example, `xrandr --dpi 192` and then restart any of your X11 clients.

```
xrandr --dpi 192
env GDK_BACKEND=x11 gnome-calculator
```

works correctly for me.

**Comment by m-khvoinitsky** [comment]
So, after long, more careful testing: it seems that you're right: dpi changes happen on display hot plug, XWayland completely ignores setting dpi via xrandr hence the workaround doesn't work.
I'll try workaround proposed in https://github.com/swaywm/sway/issues/3499#issuecomment-456576277.
I guess we can close this issue in favor of https://github.com/swaywm/wlroots/issues/1119.
