### ISSUE TITLE
Cursor missing from external displays

### ISSUE THREAD

**Issue by JonnyMako** [swaywm/sway#3586]
sway version 1.0-rc1-22-g09c2a46b (Feb  5 2019, branch 'master')

Mouse cursor is missing from external monitors.

**Comment by c-edw** [comment]
Could you show your config file? I'm using an external monitor via DP and have no issues with missing cursors.

**Comment by JonnyMako** [comment]
ok, I've done a bisect, and this is the offending commit:
https://github.com/swaywm/wlroots/commit/7bc43413edc2db04bbfba395f9606957ff2fa21c

**Comment by c-edw** [comment]
@VincentVanlaer Would you be willing to look into this?

**Comment by RedSoxFan** [comment]
Can this be closed or is this still an issue for some configurations/setups?

**Comment by JonnyMako** [comment]
> Can this be closed or is this still an issue for some configurations/setups?

I think failing to fall back to a software cursor is still an issue for some Radeon cards. Not sure if there is a separate issue.

**Comment by JonnyMako** [comment]
Maybe we can close this now. swaywm/wlroots#1584 may fix Radeon issues?
