### ISSUE TITLE
Sway intermittent crashes with popup menus

### ISSUE THREAD

**Issue by JonnyMako** [swaywm/sway#3591]
```
sway version 1.0-rc1-24-ga3c53148 (Feb  5 2019, branch 'master')
```
I'm seeing intermittent crashes when clicking in context menus. Trace attached.

[gdb.txt](https://github.com/swaywm/sway/files/2834234/gdb.txt)

**Comment by emersion** [comment]
Fixed by https://github.com/swaywm/sway/pull/3585
