### ISSUE TITLE
Sway crashes immediately after startup

### ISSUE THREAD

**Issue by PhotonMike** [swaywm/sway#3598]
Recently after an update, sway began immediately crashing. Executing `sway` results in my wallpaper briefly flashing, then returning to the tty immediately.
Distro: Arch (x64)
Sway version (`sway -v`):  `sway version 1.0-beta.2-232-g62260ab5 (Jan 20 2019, branch 'master')`
(sway installed from `wlroots-git` and `sway-git` aur packages)
GPU: Intel 3rd gen (`i915`)

Debug log (`sway -d 2>sway.log`): [sway.log](https://github.com/swaywm/sway/files/2836842/sway.log)
Coredump: [coredump.txt](https://github.com/swaywm/sway/files/2836846/coredump.txt)

**Comment by emersion** [comment]
Weird. Are you sure you're running the latest commit of both sway and wlroots?

Can you run with ASAN? (`meson build -Db_sanitize=address`)

**Comment by PhotonMike** [comment]
Thanks for the tip, it appears that the AUR packages are out of date. (even though they are git packages?) After I built and installed it manually, it finally launched.

**Comment by Emantor** [comment]
Did you use an AUR helper for the installation? And if yes, which one did you use?

**Comment by PhotonMike** [comment]
I used yay.

**Comment by Emantor** [comment]
Unless I'm misreading the man page, yay requires the use of `--rebuild` otherwise it will just use the already build package from cache.
