### ISSUE TITLE
Opening some XWayland apps to the scratchpad crashes sway

### ISSUE THREAD

**Issue by hughwilliams94** [swaywm/sway#3613]
I am attempting to have an application (MineTime, https://github.com/marcoancona/MineTime/issues) open into the scratchpad automatically. However, once I set the relevant configuration, opening the application crashes Sway. It is an Electron app which runs under XWayland, I have tried with other apps running under XWayland (e.g. Thunderbird) and opening them to the scratchpad seems to work fine. 

Unfortunately the app is not yet open-source but the devs seem to be somewhat respondent, so I can query specifics with them if necessary.

* Sway Version: sway version 1.0-beta.2-204-g70637b40 (Jan 17 2019, branch 'master')
* Debug Log: https://gist.github.com/hughwilliams94/513a9024bb17c23136651e8a92243cc4
* Configuration File: https://gist.github.com/hughwilliams94/eee02e06aa64e2ff5173faf5450cf215
* Stack Trace: https://gist.github.com/hughwilliams94/836235b0f2acd13b1e4f5ecb5df72361

## Steps to reproduce

* In config set 'MineTime' app to move to scratchpad when opened with:
 `for_window [class="MineTime"] move scratchpad`
* Open MineTime app
## What happens

Segfault in sway

## What should happen

MineTime application opens in the background and can be opened by flicking through the scratchpad

**Comment by Emantor** [comment]
If I am not mistaken this was fixed by https://github.com/swaywm/sway/pull/3488

**Comment by hughwilliams94** [comment]
Yes #3488 does seem to have fixed it. Apologies, I was running the sway-git package but it had not been rebuilt recently enough!
