### ISSUE TITLE
Segfault when switching to stacking layout

### ISSUE THREAD

**Issue by defau1t** [swaywm/sway#3618]
* Sway Version: 1.0_beta2 installed from sorrow overlay on Gentoo (fully updated)
* Debug Log: https://paste.pound-python.org/show/2HMR6KsVBiUChEU0LSrK/
* Configuration File: https://paste.pound-python.org/show/G8KwGDUXP37Ez1QV4kZu/

All I do is press **the key to enable stacking layout** (tried various mods and keys) and sway segfaults.

Running `$ swaymsg layout stacking` works fine, but using a hotkey fails.

Might be relevant, might not: I am using the dvorak keyboard layout set through the sway.desktop file.

Relevant section from dmesg:
`sway[19270]: segfault at 55cd6d375550 ip 000055d16c87d21f sp 00007ffc132872a0 error 4 in sway[55d16c84e000+3b000]`

`Code: d0 00 00 00 c5 fb 10 54 24 08 c5 f1 57 c9 c5 f3 2a ca c5 eb 5c c0 c5 fb 5e c1 c5 fb 2c d0 3b 50 04 7d 18 48 8b 40 08 48 63 d2 <48> 8b 04 d0 e9 28 fe ff ff 0f 1f 84 00 00 00 00 00 48 89 de 48 89`

**Comment by RedSoxFan** [comment]
>  Sway Version: 1.0_beta2

1.0-beta.2 was released over 2 months ago (Nov 29, 2018) and there has been numerous changes to the code base since then. Can you please try with git master?

**Comment by defau1t** [comment]
Just installed rc1 and no dice. Only difference is offset in dmesg is now 40000 vice 3b000

**Comment by RedSoxFan** [comment]
Full backtrace snippet:
```
#0  0x000055f70781b413 in container_at_stacked
    (parent=0x55f709099910, lx=100, ly=100, surface=0x7ffd0dcc0080, sx=0x7ffd0dcc0088, sy=0x7ffd0dcc0090) at ../sway/tree/container.c:256
        child = 0x7ffd0dcc0088
        box = {x = 10, y = 40, width = 1077, height = 567}
        seat = 0x55f708f3c340
        children = 0x55f708f7f250
        title_height = 0
        child_index = -2147483648
        current = 0x7ffd0dcc0080
```

Relevant source:
```c
int title_height = container_titlebar_height();
int child_index = (ly - box.y) / title_height;
```

From your config:
```
font Hack 0px
titlebar_border_thickness 0
titlebar_padding 0 0
```

So it looks like you are using a font and padding that cause the title bars to be 0px tall, which is causing a division by zero, resulting in `child_index` getting set to `INT_MIN` (as close to negative infinity a 32-bit signed integer can get). I'll have a PR up to protect against this in a minute

**Comment by defau1t** [comment]
I had initially set the titlebar to zero pixels to remove the titlebar completely, until I found the default_border command and never set those values back to normal. Thanks for helping out! Changing it back to non-zero fixes the issue, and still keeps my titlebars out of the way!
