### ISSUE TITLE
Segfaults on Gentoo (DRM master problem)

### ISSUE THREAD

**Issue by NexusAlpha** [swaywm/sway#3620]
Sway segfaults and freezes the system on Gentoo for me. I am in the input and video group and the filecaps are successfully set by portage. The XDG runtime dir is also set using a script. No elogind (because it fails emerging) or consolekit. 

Sway debug log: http://dpaste.com/1DJD3J0
Backtrace: http://dpaste.com/3A1GR6J

**Comment by emersion** [comment]
The backtrace is not a backtrace, it's a system call trace. Can you get a proper backtrace (aka. stack trace)? You can obtain one from coredumps, though I'm not sure how this works on Gentoo.

**Comment by NexusAlpha** [comment]
I think by running it through gdb but it also freezes the system when run inside the debugger.

**Comment by emersion** [comment]
Yes, that's expected. Look up how to enable coredumps on your system, or use gdb via ssh.

**Comment by progandy** [comment]
Gentoo has a helpful wiki.

https://wiki.gentoo.org/wiki/Project:Quality_Assurance/Backtraces#Core_dumps
https://wiki.gentoo.org/wiki/Project_Talk:Quality_Assurance/Backtraces#Core_dump_naming_and_save_path

**Comment by NexusAlpha** [comment]
No "core" file is being created by ulimit. If I understand correctly I have to set the limit of the coredump by using ulimit and then run sway. But after the freeze and force reboot no file is being created.

**Comment by CaptainBloodz** [comment]
Do you yave xwayland enabled?

**Comment by RedSoxFan** [comment]
> But after the freeze and force reboot no file is being created.

The core dump will be removed on reboot. You'll have to ssh in or do something like:
```
(sleep 5 && killall sway) &
sway -d 2>sway.log
```

Also, your system call trace shows `[wlroots-0.2/backend/session/direct-ipc.c:35] Do not have CAP_SYS_ADMIN; cannot become DRM master` (which doesn't match your debug log btw).

If that trace is up to date, you need to verify the capabilities of the sway binary with `getcap`. It most likely is incorrect.

**Comment by prometheanfire** [comment]
What flags did you use to install sway? if running with systemd/elogind you should be fine.  if not it should install with cap_sys_admin on /usr/bin/sway.

**Comment by NexusAlpha** [comment]
I'm still unable to get the coredump, sorry. I've built sway beta2 with without swayidle and swaylock, the other USE-Flags are default. And yes those logs were taken at the same crash, don't know why they don't match. Both sway and wlroots were emerged with the filecaps flag and the caps are set correctly even though the error persists. I'm currently trying to install elogind without luck.

**Comment by emersion** [comment]
If the executable is suid, enabling coredumps will require more setup.

**Comment by prometheanfire** [comment]
iirc beta2 was still cap_sys_admin as was the original 1.0-rc1.  1.0-rc1-r1, 1.0-rc2 and 9999 were changed to use suid.

     fowners root:0 /usr/bin/sway                                                                                         
     fperms 4511 /usr/bin/sway

**Comment by prometheanfire** [comment]
can you give the output of `id` as well?  video, input and users groups could help (though I think video is mainly for webcam).

**Comment by NexusAlpha** [comment]
Little update: I managed to install elogind now and also upgraded to rc2. It still segfaults but now within a different stage and doesn't freeze the system anymore, so we're slowly getting there.

**Comment by NexusAlpha** [comment]
But I think the primary issue itself was solved by installing elogind. Soll I'll close this issue now.
