### ISSUE TITLE
Terminals lose transparency in fullscreen

### ISSUE THREAD

**Issue by JonnyMako** [swaywm/sway#3624]
```
sway version 1.0-rc1-37-gf5190d1f (Feb  8 2019, branch 'master')
```

When I full screen any of the terminals with transparency set, the window becomes opaque. For example, in Termite, I'm setting transparency like so: `background = rgba(29,31,33,.8)`

Correct me if I'm wrong but I'm positive, I could see the wallpaper through the transparency in full screen mode before.

[sway.log](https://github.com/swaywm/sway/files/2846457/sway.log)

**Comment by emersion** [comment]
No, this is by design.

**Comment by JonnyMako** [comment]
ok, thanks.

**Comment by talbergs** [comment]
Is it possible then to fullscreen termite and have it opaque?

**Comment by emersion** [comment]
See https://github.com/swaywm/sway/issues/3624#issuecomment-461910064
