### ISSUE TITLE
Touchpad config being ignored

### ISSUE THREAD

**Issue by vitorhugomattos** [swaywm/sway#3626]
* Sway Version: 1.0-rc1-37-gf5190d1f (Feb 8 2019, branch 'master')
* Debug Log: https://paste.rs/1QT
* Configuration File: https://paste.rs/AO9

Sway (or maybe libinput?) totally ignores my configuration. I tried reloading the configuration file (with Mod+Shift+c), restarting Sway and even restarting my netbook, nothing worked.

![screen](https://user-images.githubusercontent.com/2721565/52515483-50955a00-2c03-11e9-8149-d4ea72334bdf.png)
`libinput list-devices` and sway config file

Don't know about others input devices.

**Comment by vitorhugomattos** [comment]
In debug log I just started sway, reloaded the config and exited.

**Comment by RedSoxFan** [comment]
> input "2:14:SynPS/2_Synaptics_TouchPad" {
	dwt false
	tap enabled
	natural_scroll enabled
	middle_emulation enabled
}
> 
> 2019-02-09 00:35:30 - [sway/input/input-manager.c:467] adding device: '2:7:SynPS/2_Synaptics_TouchPad'

It looks like the identifier in your config is incorrect. Also, just for reference `libinput list-devices` will always show the default settings for the device, not the settings used by Sway

**Comment by vitorhugomattos** [comment]
Uh, looks like I can't trust clipboard. Sorry for the inconvenience :)
