### ISSUE TITLE
swaybar does not overlay some things when overlaying windows (using hide)

### ISSUE THREAD

**Issue by prometheanfire** [swaywm/sway#3628]
using 1.0-rc1

An example is that swaybar does not overlay the site favicons so the favicons pop through when pushing the bar when the bar is visible. (firefox)  This type of thing also seems to hit xfce4-terminal.

**Comment by emersion** [comment]
I don't get what's wrong. Can you describe in more detail, and if possible add a screenshot of the bug?

**Comment by prometheanfire** [comment]
the normal way I do screenshots won't work, but I'll take a photo (grim isn't package, might do that some time).

**Comment by prometheanfire** [comment]
https://www.youtube.com/watch?v=n9700mnxaUs

**Comment by RedSoxFan** [comment]
It looks like this is actually an issue with your bar colors, It appears that the border and background colors for `inactive_workspace` are completely transparent.

**Comment by prometheanfire** [comment]
yep, that was it, thanks
