### ISSUE TITLE
swaylock doesn't accept user password

### ISSUE THREAD

**Issue by sydneymeyer** [swaywm/sway#3632]
sway version 1.0-rc1-38-g995b6eda (Feb  9 2019, branch 'master')
swaylock version 1.3-4-g37280a9 (Feb  9 2019, branch 'master')

swaylock fails to accept user password with [pam.c:102] pam_authenticate failed: invalid credentials

**Comment by RedSoxFan** [comment]
If you are using Arch Linux, see https://github.com/swaywm/sway/issues/3631

_Also in the future, please use the swaylock issue tracker (https://github.com/swaywm/swaylock/issues) for swaylock related items._

**Comment by sydneymeyer** [comment]
> If you are using Arch Linux, see #3631

Indeed. Duplicate of #3631. Setting meson prefix for swaylock solves the issue.

> _Also in the future, please use the swaylock issue tracker (https://github.com/swaywm/swaylock/issues) for swaylock related items._

Of course, will do.
