### ISSUE TITLE
Alpha on border colors

### ISSUE THREAD

**Issue by vitorhugomattos** [swaywm/sway#3642]
* Sway Version: sway version 1.0-rc1-37-gf5190d1f (Feb  8 2019, branch 'master')
* Debug Log: https://paste.rs/Zbr
* Configuration File: https://paste.rs/fUI

Border colors with alpha don`t work ()

> without alpha
![image](https://user-images.githubusercontent.com/2721565/52538811-4176ef00-2d5e-11e9-87c7-cf197ec07aad.png)

> with alpha
![image](https://user-images.githubusercontent.com/2721565/52538846-b4806580-2d5e-11e9-84e6-5da8a7a102ba.png)

> real alpha color
![image](https://user-images.githubusercontent.com/2721565/52538857-cb26bc80-2d5e-11e9-90b4-61c9b3b54aca.png)

note that it's the exactly same color from my bar's `focused_workspace` property

**Comment by emersion** [comment]
Can you still reproduce?
