### ISSUE TITLE
Specify monitor output using edid

### ISSUE THREAD

**Issue by MayeulC** [swaywm/sway#3649]
I apologize if this is already supported or not doable as proposed, I haven't found it in the documentation, and I am just beginning to understand the i3/sway configuration syntax. 

Sway version: 0.15.2 (for now, eagerly waiting for 1.0)

My use case is the following: I use sway on my laptop, and I have a docking station, as well as a few monitors I usually connect it to.
That's not really the case for now, but my display configuration needs might differ depending on which docking station I plug to.

I would like to be able to specify the display configuration on a per-monitor basis, with something like:

```
## Currently:
output eDP-1 resolution 1920x1080 position 10680,0
output DP-3 resolution 1920x1080 position 9600,0
## What I would like:
output eDP-1 resolution 1920x1080 position 10680,0
output E2218HN@DP-3 resolution 1920x1080 position 9600,0
```
In the current form, `E2218HN` is a monitor identifier that can be grepped from `/sys/class/drm/card0-DP-3/edid`. I think that a condition like an edid substring would be enough, as it also allows to specify a serial number, or whatever interesting identifiers might be reported by the edid.

Going forward, it might be interesting to define different blocks with various configuration sets, depending on what is connected. Examples with arbitrary syntax:
```
output "E2218HN@DP-3+E2218HN@DP-1" {
 ## output configuration in case the connected monitors match the above rule
}
output "(E2218HN@DP-3|DP-2)+DP-1" {
 ## output configuration in case the connected monitors match the above rule
}
```

**Comment by emersion** [comment]
You can already use monitor identifiers from `swaymsg -t get_outputs`. For instance:

```
> swaymsg -t get_outputs
Output LVDS-1 'Chimei Innolux Corporation 0x1484 0x00000000' (focused)
```

The identifier is "Chimei Innolux Corporation 0x1484 0x00000000".

**Comment by MayeulC** [comment]
All right, thanks a lot for the answer. I do not have these identifiers, but I guess it's due to my older sway version. Feel free to close this issue, unless you want to keep the part about configuration blocks :slightly_smiling_face:

**Comment by emersion** [comment]
>Going forward, it might be interesting to define different blocks with various configuration sets, depending on what is connected.

See https://github.com/emersion/kanshi
