### ISSUE TITLE
"Can't open display" when running sway without xwayland support

### ISSUE THREAD

**Issue by CaptainBloodz** [swaywm/sway#3651]
sway version 1.0-rc1-45-gfb4f2928 (Feb 11 2019, branch 'HEAD')
By curiosity, I gave a try to sway/wlroots without xwayland.
Starting and exiting fine, but as soon as I try a terminal e.g. Meta+Crl,
log ( sway command redir to file ) returns "Can't open display" message.

rc_1 behave the same.

Thks 4 ur attention

**Comment by emersion** [comment]
If you're trying to open a terminal which uses X11, it won't work without Xwayland.

Please provide full debug logs.

**Comment by CaptainBloodz** [comment]
I have no idea which terminal I could use but firefox is compiled with wayland, so maybe it will work as replacement, for test purpose only.

**Comment by emersion** [comment]
Wayland terminals include termite, alacritty, gnome-terminal.

Closing because this isn't a bug.

**Comment by CaptainBloodz** [comment]
works fine!
