### ISSUE TITLE
Proposal: user-defined shaders

### ISSUE THREAD

**Issue by ddevault** [swaywm/sway#3652]
Not sure if we actually want to do this, but someone on HN proposed it and it might not be that rough after I gave it some thought.

    shader my-shader load path/to/vertex.glsl path/to/fragment.glsl
    shader my-shader set my_color vec3 0.0 0.0 1.0 1.0
    for_window [.*] shader my-shader

We'd then use these shaders when rendering those windows, rather than the wlr_renderer shaders. Seeking feedback.

**Comment by ddevault** [comment]
Hmm, annoying problem: different pixel formats.

**Comment by rkanati** [comment]
How would this interact with, e.g. the vulkan renderer proposal? And how much could you really achieve with this - cute effects, sure, but is there something bigger I'm missing?

**Comment by ddevault** [comment]
Just cute effects, yeah. Not sure how it would interact with the Vulkan proposal (poorly, I assume).

**Comment by edrex** [comment]
Practical use case: one could use this to implement a generic "dark mode" that value-inverts pixels if the average pixel value over the window is > 50% (like [FF Dark Reader addon](https://addons.mozilla.org/en-US/firefox/addon/darkreader/), thanks @shinyrice)

**Comment by cafehaine** [comment]
I guess it also could be used to implement the rounded corners that some users were asking for

**Comment by mxmilkb** [comment]
Also to tint icons of applications/etc in a bar/panel to match the general colour theme. There is X11 bar/panel that does that, cannot remember the name though (was it tint2?).

**Comment by emersion** [comment]
>Practical use case: one could use this to implement a generic "dark mode" that value-inverts pixels

Yes

> if the average pixel value over the window is > 50%

Probably not.

>I guess it also could be used to implement the rounded corners that some users were asking for

No

>Also to tint icons of applications/etc in a bar/panel to match the general colour theme. 

And no

**Comment by ddevault** [comment]
Wait, why couldn't user-defined shaders be used to implement rounded corners? And tinting icons in the bar seems possible to me too. "Average pixel value" does sound difficult-to-impossible though.

**Comment by emersion** [comment]
>Wait, why couldn't user-defined shaders be used to implement rounded corners?

We render them as rectangles separately from the window. We'd need to change how we render borders and titlebars. Well I guess it would be possible (but more work).

>And tinting icons in the bar seems possible to me too

You can't tell whether a pixel is from an icon or not. Or do you want to apply the filter to all pixels no matter what?

**Comment by ddevault** [comment]
Ah, I was thinking about rounding the actual surface of the window.

>You can't tell whether a pixel is from an icon or not. Or do you want to apply the filter to all pixels no matter what?

Just apply the shader to a specific part of the image, and skip that pixel if it's equal to your bar's background color?

**Comment by emersion** [comment]
>Just apply the shader to a specific part of the image, and skip that pixel if it's equal to your bar's background color?

I mean, it could work in some situations, but not if the bar status blocks don't have a fixed width. If you try to apply the filter to the whole bar, it'll break status blocks colors (that match the color scheme). If you have a fixed list of accepted colors, antialiasing is tricky.

**Comment by mxmilkb** [comment]
Shaders for patterns on borders? I changed recently from themed border and split indicator colours to try #00ff00 and #ff0000, as I found myself not figuring from peripheral vision where the split was and getting mildly distracted by having to saccade enough to find it. If there were a cycling colour, or slowly moving semi-transparent pattern, or a subtle but steady modulation in glow or occasional gleam in the border on the indicator edge border, even at 2px wide, heck, I could set my active window and split indicator border colours the same and I could (in many possible cases) still/always know whether to open a window or change the split direction. Movement of light and dark can jump out so much more than a static difference in colour. Accessibility and theming. (Eventually, HiDPI Quake water borders..?)

I guess not for sway, but shaders for 'live' virtual desktops? Like Enlightenment ([new](https://i.imgur.com/68F2uFA.jpg) and [old](https://adamspiers.org/computing/X11_screenshots/ThinkPad/Enlightenment-2.jpg))?

**Comment by retrotails** [comment]
I'd like to see a full-screen shader option for more advanced redshift alternatives (tinted monochrome, or hue changes so blue != black etc), or maybe more crazy stuff like a reverse-sharpen filter I wrote to work around my TV's always-on filtering. there could be other interesting uses (for the per-window shader) like a chroma key to add transparency to apps that don't support it, so I can see my background for once. (quick and ugly mockup)
![transparent_small](https://user-images.githubusercontent.com/10767978/58937789-6b0aba80-8741-11e9-9ed5-92e57ea53f48.jpg)

oh also idk if windows are repainted every frame or how that works, but a boolean for whether the shader needs updated every frame would be nice.

**Comment by emersion** [comment]
>chroma key to add transparency to apps that don't support it, so I can see my background for once

There's an `opacity` command.

**Comment by retrotails** [comment]
> There's an `opacity` command.
I didn't know about that feature, though having the text etc transparent is pretty bothersome in comparison. maybe a little too resource intensive for a nitpick but I'd still enable a chroma key shader on the desktop.

**Comment by NotAFile** [comment]
I'd love to have this ability. Previously, I had used a custom shader in the X compositor to enable a "night mode" that desaturated the screen in the evening to be less appealing. It would be neat to be able to do this again in sway.

**Comment by imyxh** [comment]
If I understand the suggestion correctly, I think it would be a huge benefit for accessibility if we were be able to easily invert colors in a window. Especially with bindsym.

**Comment by retrotails** [comment]
@imyxh could also have sharpening, a contrast curve or even a magnifying glass under the cursor if the shader can get mouse coordinates. with a few external variables you could make it fancy with fading, animations etc and build something polished with just shaders and a little scripting.

**Comment by emersion** [comment]
Related: https://github.com/swaywm/wlroots/issues/1904

**Comment by WillPower3309** [comment]
Could user defined shaders open the possibility for Gaussian blur on transparent windows?

**Comment by imyxh** [comment]
> Could user defined shaders open the possibility for Gaussian blur on transparent windows?

Not familiar with the sway codebase but I feel like how this would work depends on whether the shader is applied before or after transparency rendering. GLSL fragment shaders can [definitely](https://github.com/stonexjr/glsl-fast-gaussian-blur/blob/master/5.glsl) handle Gaussian blur, but if you want the window to blur *with* the background (as a sampling source) I would assume that the shader would have to be applied after the alpha compositing—which would look very weird with, say, dark theme shaders.

**Comment by SFort** [comment]
Reading this i get the impression the anwser is no,
but any chance this could allow for an inverted mouse cursor?

**Comment by ddevault** [comment]
Just to avoid letting this thread drag on, but the likelihood of this feature being implemented is very slim.

**Comment by Xyene** [comment]
Closing out this ticket to prevent confusion, as per https://github.com/swaywm/sway/pull/5639#issuecomment-683336945.

**Comment by Scrumplex** [comment]
Maybe this can be revisited, now that we have a Vulkan renderer?

**Comment by emersion** [comment]
Maybe, need to investigate how modular Vulkan shaders are, and how this would interact with a potential migration to compute shaders.

**Comment by wentam** [comment]
Given that this was closed on the basis of being a "flashy" feature, I thought I'd bring up my use-case for this. Don't mean to add to any "I want this" spam, just thought it might be helpful to bring up a clearer practical justification than just generically "accessibility", as I have a real health issue I'm trying to work around.

I have light sensitivity problems and media that flashes the screen bright white or rapidly flickers causes me problems. While I'd like it if those who create media would do better about posting seizure warnings or respect our eyes a little more, I'd really like to protect myself from this with some kind of global luminance smoothing or flash detection shader (would probably need access to a few of the previous frames).

There is a very real safety justification for this feature in my opinion.

Support for many visual accessibility features could be generalized with a shader mechanism, and thus prevent the need for many features to tackle them individually. If you dislike feature bloat, this is exactly the type of thing to implement to support the general case flexibly.
