### ISSUE TITLE
Token 'class' not recognized (nor is token 'id')

### ISSUE THREAD

**Issue by Arnaudv6** [swaywm/sway#3653]
Such lines in config don't work:  
`for_window [class="[.]*"] floating enable, focus;`  
`for_window [id="[.]*"] floating enable, focus;`

sways says respectively:  
`Token 'class' is not recognized`  
`Token 'id' is not recognized`

**Comment by RedSoxFan** [comment]
It looks like you compiled without xwayland support

**Comment by Arnaudv6** [comment]
yes I did. I take it those lines only apply in X world?

**Comment by emersion** [comment]
Yeah, on Wayland use `app-id`.

**Comment by Arnaudv6** [comment]
Thank you both.
