### ISSUE TITLE
Specifying outputs for workspaces requires full device name

### ISSUE THREAD

**Issue by terminalnode** [swaywm/sway#3655]
When using the option `workspace <name> output <outputs...>` to specify which output a workspace should be displayed on this requires you to specify the full device name rather than eDP-1, DP-1, HDMI-1 etc.

Works:
`workspace 1 output 'Apple Computer Inc Color LCD 0x00000000'`

Doesn't work:
`workspace 1 output eDP-1`

Being able to use the short names (eDP-1 etc) would be really handy.

swaymsg -t get_version
sway version 1.0-rc1-45-gfb4f2928 (Feb 11 2019, branch 'master')

**Comment by RedSoxFan** [comment]
Can you please send a debug log?

**Comment by terminalnode** [comment]
Oh, nevermind. It seems I'm stupid. I didn't realise this was a bug, I thought it was just a feature that wasn't implemented yet. In producing the bug report I realised it was my fault all along as I was using commas to separate the output names, i.e.: `workspace 6 output DP-1, DP-2, HDMI-1` etc instead of `workspace 6 output DP-1 DP-2 HDMI-1`.
