### ISSUE TITLE
Incorrect --version output when built from source tarball but git is installed

### ISSUE THREAD

**Issue by jbeich** [swaywm/sway#3656]
Regressed by #3578. Affects downstream builds of both releases and snapshots.

```
$ git --version
git version 2.20.1
$ curl -o sway-1.0-rc2.tar.gz https://codeload.github.com/swaywm/sway/tar.gz/1.0-rc2
$ tar xzf sway-1.0-rc2.tar.gz
$ cd sway-1.0-rc2
$ meson _build
$ ninja -C _build
$ _build/sway/sway --version
sway version  (Feb 12 2019, branch '')
```

**Comment by SpeedJack** [comment]
The code inside the `if git.found()` block should be executed only if we are in a valid git repo (maybe checking if the `.git` directory exists?). Otherwise the `else` block should be executed.

**Comment by martinetd** [comment]
There are ways to use git that do not rely on a .git directory (environment variable, .git file redirecting to another directory (e.g. worktrees), etc)

I would run the git commands as long as git is found, and if their output is empty fallback to the else code instead.
