### ISSUE TITLE
Screen flicker on wallpaper change

### ISSUE THREAD

**Issue by dg10a** [swaywm/sway#3659]
This script is running in the background:

```
while true; do
    swaymsg -t command "output * bg `find /path/to/wallpaper/folder/ | shuf -n 1` fill"
    sleep 30
done 
```

On every wallpaper change, the screen flickers.

**Comment by emersion** [comment]
That's expected, `swaybg` is killed and restarted on config change.

**Comment by dg10a** [comment]
Is there currently a way achieve this effect?

**Comment by emersion** [comment]
No. The way `swaybg` works now (no standalone config file, everything passed as arguments) makes it kind of annoying to implement. We could use a pipe, but we'd need to pass other arguments too, and this involves serializing…

**Comment by emersion** [comment]
Maybe https://github.com/vilhalmer/oguri has a way to do this?

**Comment by dg10a** [comment]
Sort of:
```
while true; do
    pkill oguri
    oguri <output> `find /path/to/wallpaper/folder/ | shuf -n 1` &
    sleep 30
done 
```

No more screen flickering, but stopping `oguri` shows the default background before the next image.

**Comment by emersion** [comment]
>Sort of

Well if you kill it it's just the same as `swaybg`.

**Comment by dg10a** [comment]
Not quite. The `swaybg` method causes the entire screen to flicker, regardless of whether the background is visible. The `oguri` method only causes the background to flicker, but doesn't affect anything else.

**Comment by emersion** [comment]
Running `oguri` on top of `swaybg` is the same as running `swaybg` twice.

**Comment by dg10a** [comment]
I think I'm only running `oguri` and not `swaybg`. Is `oguri` running/using `swaybg`? I don't see any independent `swaybg` processes running.

**Comment by yorickvP** [comment]
`swaymsg output DP-1 bg ~/wp/069.png stretch` causes the entire screen (including the windows) to flicker, not just the background

**Comment by RedSoxFan** [comment]
Related

**Comment by RedSoxFan** [comment]
(Sorry for accidental close/reopen. Misclick while attempting to reply on my phone)

**Comment by dg10a** [comment]
Confirmed that running `swaybg` manually doesn't cause the flicker.

Here's a working solution with no pauses between images:
```
#!/bin/sh
swaybg <output> `find /path/to/wallpaper/folder/ | shuf -n 1` fill &
OLD_BG=$!
while true; do
    swaybg <output> `find /path/to/wallpaper/folder/ | shuf -n 1` fill &
    NEXT_BG=$!
    sleep 30
    kill $OLD_BG
    OLD_BG=$NEXT_BG
done 
```

**Comment by yorickvP** [comment]
The commit was reverted. Should this be reopened?
