### ISSUE TITLE
[feature request] Hide titlebar on windows with CSD

### ISSUE THREAD

**Issue by Edootjuh** [swaywm/sway#3661]
`sway version 1.0 (Mar 11 2019, branch 'makepkg')`

I'd like to automatically set the `border` to `none` on windows that have client side decorations (or at least GTK 3 headerbars), even in tiling mode. I show titlebars by default but this is redundant when the window already shows the window title.

I suggest allowing something like the following config:

```
for_window [csd] border none
```

Would this be possible?

**Comment by emersion** [comment]
We already have `border csd`.
