### ISSUE TITLE
Libreoffice window won't appear when started from file manager

### ISSUE THREAD

**Issue by avrelaun** [swaywm/sway#3666]
context:
    * archlinux
    * sway version 1.0-rc1-45-gfb4f2928 (Feb 12 2019, branch 'master')
    * libreoffice from arch repos
    * pcmanfm-gtk3 from arch repos

I have been using sway since the first 1.0 beta and building / running it every week. IIRC I always had the following issue on sway:

- When starting Libreoffice directly from rofi, I see the splash screen, Libreoffce starts up and I can open any file.

- When I double click on a libreoffice file on my file manager PCManFm whith LibreOffice not running, the libreoffice splash screen starts up in background (oosplash process runs infinitely) but never shows up, let alone starting the actual app.

- When starting Libreoffice and then double clicking on a Libreoffice file on my file manager, the file opens nicely on Libreoffice.

**Comment by emersion** [comment]
Does it work properly in Weston?

**Comment by avrelaun** [comment]
I cannot even start Libreoffice on weston "Cannot open display".

**Comment by avrelaun** [comment]
I updated Libreoffice from 6.1.4 to 6.2 today, it now works as expected.
