### ISSUE TITLE
Swaybar has issues with alpha (opacity) in json protocol?

### ISSUE THREAD

**Issue by harrisonthorne** [swaywm/sway#3670]
**sway version 1.0-beta.2-279-g783fadab (Jan 27 2019, branch 'master')**

Swaybar is having some funky issues dealing with color alpha values with my i3bar protocol json:
```json
,[{"name":"brightness","full_text":"<span color=\"#49648C10\" font=\"Material Design Icons 12\"></span>  <span color=\"#49648C10\" font=\"Fira Sans 10\">4%</span>","short_text":"<span color=\"#49648C10\" font=\"Material Design Icons 12\"></span>","markup":"pango","separator":true},{"name":"volume","full_text":"<span color=\"#49648C10\" font=\"Material Design Icons 12\"></span>  <span color=\"#49648C10\" font=\"Fira Sans 10\">5%</span>","short_text":"<span color=\"#49648C10\" font=\"Material Design Icons 12\"></span>","markup":"pango","separator":true},{"name":"network","full_text":"<span color=\"#6a92cb\" font=\"Material Design Icons 12\">蠟</span>  <span color=\"#6a92cb\" font=\"Fira Sans 10\">COMCAST</span>","short_text":"<span color=\"#6a92cb\" font=\"Material Design Icons 12\">蠟</span>  <span color=\"#6a92cb\" font=\"Fira Sans 10\">COMCAST</span>","markup":"pango","separator":true},{"name":"sbattery","full_text":"<span color=\"#6a92cb\" font=\"Material Design Icons 12\"></span>  <span color=\"#6a92cb\" font=\"Fira Sans 10\">100%</span>","short_text":"<span color=\"#6a92cb\" font=\"Material Design Icons 12\"></span>  <span color=\"#6a92cb\" font=\"Fira Sans 10\">100%</span>","markup":"pango","separator":true},{"name":"weather","full_text":"<span color=\"#6a92cb\" font=\"Material Design Icons 12\"></span>  <span color=\"#6a92cb\" font=\"Fira Sans 10\">35°</span>  <span color=\"#49648cc0\" font=\"Fira Sans 10\">Clear sky</span>","short_text":"<span color=\"#6a92cb\" font=\"Material Design Icons 12\"></span>  <span color=\"#6a92cb\" font=\"Fira Sans 10\">35°</span>","markup":"pango","separator":true},{"name":"date","full_text":"<span color=\"#6a92cb\" font=\"Material Design Icons 12\"></span>  <span color=\"#6a92cb\" font=\"Fira Sans 10\">4:17 pm</span>  <span color=\"#49648c10\" font=\"Fira Sans 10\">Tue, Feb 12</span>","short_text":"<span color=\"#6a92cb\" font=\"Material Design Icons 12\"></span>  <span color=\"#6a92cb\" font=\"Fira Sans 10\">4:17 pm</span>","markup":"pango","separator":true}]
```

renders like this:

![actual](https://cdn1.imggmi.com/uploads/2019/2/13/baa82d7e7a8c3ba6cd5cdf7b9e65c83f-full.png)

these are the colors i expect to see:

![expectation](https://cdn1.imggmi.com/uploads/2019/2/13/e59acb04d2afed958028b34802708325-full.png)

You can notice that there are some weird artifacts being rendered within "Clear sky" and a little bit within the date on the very right. The brightness, volume, "Clear sky" and date all use alpha values in their colors (as in the json above). everything else is completely opaque.

it might be worth noting that the json above (or a json similar to it) is printed over and over again very rapidly as the brightness and volume icons are designed to fade every time (and only when) a brightness/volume key is pressed. This makes for an eye-candy animation effect.

I will edit the json in a moment so it's more readable.

**Comment by harrisonthorne** [comment]
**Update:** Well, I can explain the cause of what I've described. Transparent text reveals the wallpaper, not the background of the status bar, which was unexpected for me. Is transparent text supposed to show through to the wallpaper, or should it show through only to the background of the status bar?

**Comment by emersion** [comment]
>Transparent text reveals the wallpaper, not the background of the status bar, which was unexpected for me.

Hmm. How does i3 handle this?
