### ISSUE TITLE
Cannot build RC2 on Debian (incl. Buster/Sid) because of json-c 0.13 dependency

### ISSUE THREAD

**Issue by krotonic** [swaywm/sway#3681]
Seems like it is impossible to build Sway (RC2) on Debian (Jessie/ Stretch/ Buster/ Sid) because of dependency to json-c version 0.13 while currently only 0.12.1 is supported on both of them:
[json-c buster](https://packages.debian.org/source/buster/json-c)
[json-c sid](https://packages.debian.org/source/sid/json-c)
(see link for jessie & stretch also)

install log:
```
`The Meson build system
Version: 0.49.2
Source dir: /tmp/sway/sway
Build dir: /tmp/sway/sway/build
Build type: native build
Project name: sway
Project version: 1.0
Native C compiler: cc (gcc 8.2.0 "cc (Debian 8.2.0-16) 8.2.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29)
Dependency json-c found: NO found '0.12.1' but need: '>=0.13'
Found CMake: /usr/bin/cmake (3.13.4)
Dependency json-c found: NO (tried cmake)

meson.build:40:0: ERROR:  Invalid version of dependency, need 'json-c' ['>=0.13'] found '0.12.1'.
```

If there's another way to install I would love to hear it. Really looking forward to try it out :)

**Comment by ddevault** [comment]
This is Debian's problem, not ours.

**Comment by ddevault** [comment]
Sorry, that was a bit too curt. But Debian's bugtracker is the better place to report this.

**Comment by krotonic** [comment]
Ok, that's unfortunate. But thanks for the answer. I'm gonna stick with i3 then.

**Comment by ddevault** [comment]
Why not just report the bug to the right place?

**Comment by progandy** [comment]
It should be possible to build an additional package for json-c 0.13 that lives alongside the 0.12.x version. That should not make it "impossible" to build sway, just harder.

**Comment by krotonic** [comment]
@ddevault Because there is one already: [https://tracker.debian.org/pkg/json-c](https://tracker.debian.org/pkg/json-c). But as Buster is currently in freeze it could take quite a while until it gets released into stable. 

@progandy thanks :) will give it a try

**Comment by maxstepanov** [comment]
I wonder what's so crucial in version 0.13 of this library that sway can't live without.
Most of the popular Linux distributions still don't include this version. May be in a year or two.
Prior to release sway didn't have this problem.
I guess, we'll have to wait ...

**Comment by ascent12** [comment]
@maxstepanov If I recall correctly, there was a breaking change in their API/ABI or something like that, albeit a minor one. Regardless, it's something that needed to be updated and it's just a maintenance burden to support both.

We have a policy of keeping up with the latest versions of dependencies. We aren't going to hold back dependency versions because distros that lag years behind upstream; we aren't targeting Debian or even any particular Linux distro, just whatever software is the most up to date.
