### ISSUE TITLE
firefox scale issue when multiple outputs active on laptop and one has a scale of 1.5

### ISSUE THREAD

**Issue by evilbulgarian** [swaywm/sway#3682]
https://bpaste.net/show/1ea89b9b10fa this is my outputs config
https://bpaste.net/show/56c4ad727ccb is my get_outputs
and https://imgur.com/a/RAYtpIG is what it looks like

* Sway Version:
sway version  (Feb 11 2019, branch '')

* Debug Log:
https://bpaste.net/show/3fc4ed9c96a7

* Configuration File:
start firefox in main laptop screen with scale of 1.5, move firefox window to one of the other 1080p displays. firefox is displayed in a fraction of the size.

**Comment by edrex** [comment]
I see this too. It's a Firefox bug so it should be reported there.

Workaround: after moving the firefox window between different-scale outputs, take some action to change the window W/H such as opening another window beside it, then removing it. This causes the firefox window to redraw correctly for me (although sometimes it takes several attempts)

**Comment by edrex** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1528581
