### ISSUE TITLE
dmenu focus getting stolen when a new window appears

### ISSUE THREAD

**Issue by FreeFull** [swaywm/sway#3683]
```
$ swaymsg -t get_version
sway version 1.0-rc1-56-ge8c472ae (Feb 14 2019, branch 'master')
```

If a new window appears while dmenu is active, the focus is stolen from dmenu and given to the new window. There doesn't seem to be any way to give the focus back to dmenu, so it has to be killed. An easy way to reproduce this is to launch dmenu, and then use a keybinding to launch a terminal.

**Comment by athrungithub** [comment]
it's look problem with xwayland and wayland native apps.
run dmenu and open urxvt and dmenu have focus.

**Comment by c-edw** [comment]
Steps to produce:

- Trigger dmenu ($mod+d)
- Launch a native Wayland app via keybind if possible (I launch Alacritty with $mod+Enter)
- Observe that the focus is stolen from dmenu
- Observe that Xwayland applications are uninteractable and only native Wayland applications can be used

**Comment by ddevault** [comment]
This is by design and a limitation of using an Xwayland application (dmenu) for this purpose. Check out bemenu for an alternative.
