### ISSUE TITLE
Display freeze on config reload.

### ISSUE THREAD

**Issue by c-edw** [swaywm/sway#3685]
Reloading the config ($mod+Shift+C) under ordinary conditions is freezing my display. I think the system is still responsive because I can still hear audio play after triggering it.

Can anyone else reproduce this?

**Comment by RedSoxFan** [comment]
I am not able to replicate. Would you be able to provide a debug log? The following should allow you to obtain one without having to do a hard reboot:
```
(sleep 10 && killall sway) &
sway -d 2> sway.log
```

If this just started happening today, can you try rolling wlroots back to https://github.com/swaywm/wlroots/commit/5c8d2da0a1cd3839663d070532ba45bd61d374ca? Maybe there is a case where modesetting to the current mode is needed that is being overlooked.

**Comment by ggreer** [comment]
This only happens to me if I have a background set in my config.

**Comment by emersion** [comment]
```
2019-02-15 01:05:40 - [sway/config/output.c:176] Unable to terminate swaybg [pid: 1713]
```

Interesting. Maybe we block in `waitpid`.

We should probably just disconnect the client instead of killing it.

**Comment by RedSoxFan** [comment]
Actually I am able to replicate this. Reverting https://github.com/swaywm/wlroots/pull/1545 fixes it for me.

**Comment by c-edw** [comment]
Fixes it for me too.

**Comment by c-edw** [comment]
https://github.com/swaywm/wlroots/pull/1545 has been reverted so I'm closing this. I believe @RedSoxFan is going to look into getting it working as it would've otherwise been nice to have.

**Comment by emersion** [comment]
FWIW with this commit I was also experiencing freezes on shutdown, because swaybar wasn't killed properly:

```
2019-02-16 11:48:41 - [sway/config/bar.c:22] Terminating swaybar 8978
<freeze>
```
