### ISSUE TITLE
eDP-1 dpms on fails when thunderbolt DP-1 disconnected while dpms off

### ISSUE THREAD

**Issue by edrex** [swaywm/sway#3688]
Steps:
 - `swaymsg "output * dpms off"; sleep 5; swaymsg "output * dpms on"`
 - disconnect USB-C HDMI adapter (DP-1) while displays are off
 - eDP-1 doesn't come back on

Hardware: Dell XPS-13 9360(4K) + Trianium USB-C HDMI hub
swaymsg -t get_version: sway version 1.0-rc1-45-gfb4f2928 (Feb 12 2019, branch 'master')

Logs: https://termbin.com/0te1
 - control where adapter isn't disconnected (*22:51:28*)
 - experiment where is it disconnected (*22:51:46*).

Notes:
 - Output can be restored by `swaymsg output eDP-1 disable && swaymsg output eDP-1 enable`.
 - I have had issues with this hardware and outputs not working on resume under X11 with this hardware config, so I may have quirky hardware. Still, maybe wlroots can detect the failure and reinit?

**Comment by emersion** [comment]
Can you try https://github.com/swaywm/sway/pull/3689?

**Comment by edrex** [comment]
#3689 fixes this for me
