### ISSUE TITLE
Remove xdg-shell-unstable-v6 support

### ISSUE THREAD

**Issue by emersion** [swaywm/sway#3690]
Probably not anytime soon. This is just an issue to track various toolkits/clients progress.

- [x] EFL ([since 1.21.0](https://git.enlightenment.org/core/efl.git/commit/src/lib/ecore_wl2/ecore_wl2_display.c?id=ffa276fce3b812372a063431903fa0569d71fcb2))
- [x] GLFW ([since 3.3](https://github.com/glfw/glfw/pull/1152), doesn't support v6, only wl-shell and xdg-shell stable)
- [x] Gstreamer ([since 1.16](https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/commit/67bb17e4fae76f8f662fdd69bba6cdaaf37a90fa))
- [x] GTK3 ([since 3.22.30](https://gitlab.gnome.org/GNOME/gtk/commit/2e7ac262be15fb402c4103d28533c6c6d955bf65))
- [x] Qt (since 5.12)
- [x] mpv ([since 0.29.0](https://github.com/mpv-player/mpv/commit/76211609e3c589dafe3ef9a36cacc06e8f56de09), doesn't support v6, only xdg-shell stable)
- [ ] Ozone ([only supports v5 and v6](https://chromium.googlesource.com/chromium/src/+/master/ui/ozone/platform/wayland/host/wayland_connection.cc), but Wayland support is experimental anyway)
- [x] SDL2 ([since 2.0.8](https://hg.libsdl.org/SDL/rev/bc702c5a7c3a))
- [x] Weston ([since 6.0.0](https://gitlab.freedesktop.org/wayland/weston/merge_requests/103))
- [x] winit

**Comment by nielsdg** [comment]
Just a heads up that the next GStreamer release will have support for XDG shell stable in at least [glimagesink](https://gitlab.freedesktop.org/gstreamer/gst-plugins-base/merge_requests/66) and [vaapisink](https://gitlab.freedesktop.org/gstreamer/gstreamer-vaapi/merge_requests/39)

**Comment by nielsdg** [comment]
Annnd if [this](https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/merge_requests/225) gets merged in time, GStreamer 1.16 will also have support for XDG shell in `waylandsink`

**Comment by emersion** [comment]
Seems like Gstreamer 1.16 has been released with xdg-shell stable support.

**Comment by ddevault** [comment]
Seems like we're about ready to ditch it. I don't really care about Ozone.

**Comment by ascent12** [comment]
Looking at that ozone code, it appears they have both v6 and stable support.

**Comment by ddevault** [comment]
Doesn't look like it supports xdg-shell stable to me. Still think we should axe v6 though

**Comment by ascent12** [comment]
Ah, you right. I was getting confused by seeing https://chromium.googlesource.com/chromium/src/+/master/ui/ozone/platform/wayland/host/wayland_connection.cc#648, but I forgot that got renamed to xdg_wm_base_ping.

**Comment by ecocode** [comment]
So this commit kills chromium-ozone on sway ?
on launch I get:
```
ERROR:wayland_connection.cc(92)] No xdg_shell object
FATAL:ozone_platform_wayland.cc(160)] Failed to initialize Wayland platform
```
Is there any other way to run native wayland chromium on sway-wayland ?

**Comment by emersion** [comment]
>Is there any other way to run native wayland chromium on sway-wayland ?

Yes: send a patch for xdg-shell stable.

**Comment by hedgepigdaniel** [comment]
Looks like Ozone has support now, at least in the development branch: https://chromium-review.googlesource.com/c/chromium/src/+/1939493

**Comment by berylline** [comment]
There are changelogs for Qt 5.12 that mention support for xdg-shell stable if you need them:

https://wiki.qt.io/New_Features_in_Qt_5.12

https://www.qt.io/blog/2018/12/14/whats-new-wayland-platform-plugin-qt-5-12

Just an FYI, that's all.

**Comment by emersion** [comment]
Thanks, updated the list since this may be used as reference by other projects.

**Comment by berylline** [comment]
@emersion No problem. :)
