### ISSUE TITLE
Stale tray icons on program exit

### ISSUE THREAD

**Issue by gnidorah** [swaywm/sway#3699]
Last checked with `sway version 1.0-rc2`

If one AppIndicator program registers multiple icons, then there is a stale icon in tray on program exit.

Demo program: https://github.com/gnidorah/appindicator-tray-demo

Screenshots:
1. The program is running and registered two icons
![1](https://user-images.githubusercontent.com/12064730/52895574-ae124380-31cd-11e9-8522-9ac4cee53f2d.png)
2. The program has exited and left one stale icon
![2](https://user-images.githubusercontent.com/12064730/52895583-c6825e00-31cd-11e9-9714-ebd1189a93fd.png)

cc @ianyfan @4e554c4c @mckinney-subgraph

**Comment by emersion** [comment]
Can you try https://github.com/swaywm/sway/pull/3702?

**Comment by gnidorah** [comment]
@emersion Works fine!
