### ISSUE TITLE
Keyboard rate/delay no changes

### ISSUE THREAD

**Issue by krnl0138** [swaywm/sway#3703]
Changed configuration of keyboard delay/rate.

**Expected Behavior.** The keystrokes become faster
**Current Behavior.** Nothing changes.

sway-git 1.0-rc1-64-g5c78e5cd (Feb 16 2019, branch 'master')
wayland-git Installed: 1.16.90.2144.d7b0b79-1
wlroots-git Installed: 0.3.r14.g9e49ceb1-1
zsh 5.7.1 (x86_64-pc-linux-gnu)
`swaymsg -t get-inputs`: https://pastebin.com/XgecAQgE

According to wiki I put this line into my `$HOME/.config/sway/config`.
I substitute an identifier with `"1:1:AT_Translated_Set_2_keyboard"` respectively.
```
input <identifier> {
    repeat_delay 500
    repeat_rate 5
} 
```
I tried different numbers and identifiers from inputs, with or without quotes.
No changes after reboot or re-login. 

I also tried to put into `$HOME/.zshenv`
```
export WLC_REPEAT_RATE=5
export WLC_REPEAT_DELAY=500
```
and also passed them with `env` command on sway boot. No changes again.

**Note:** I got my layouts and grp:caps_toggle managed via enviroments in .zshenv. 
But when i put them into sway config in a form of 
```
xkb_layout us,de
xkb_options grp:caps_toggle
```
while commenting them in `.zshenv` file accordingly, nothing happens and I can't change my layout.

What am I doing wrong?

**Comment by RedSoxFan** [comment]
Can you please send a debug log (`sway -d 2>sway.log`)?

Also, sway does not use wlc anymore so any of the `WLC_` environment variables will have no effect.

**Comment by krnl0138** [comment]
@RedSoxFan, here it is. https://pastebin.com/1wmhGKGV

**Comment by RedSoxFan** [comment]
Just as a sanity check, can you try using `input * {` instead of the identifier.

Also, I see you are using alacritty in the log. Are you experiencing the issue in all applications or just alacritty?

**Comment by krnl0138** [comment]
@RedSoxFan, thanks, I figured it out, kind of.

1. Everything is working until I have `input *` in my config, that's great news.
2. **Alacritty** inverts rate property, e.g. if I have 80 then **alacritty** types really slowly, but **xterm** and **st** are smooth and fast. However, if I nailed it to 10, **alacritty** starts to fly, but typing in chromium and other apps becomes slow as hell.

I don't even know what to do with both issues now.

**Comment by emersion** [comment]
Probably an Alacritty bug

**Comment by RedSoxFan** [comment]
1. That's probably a bug in sway. I'll take a look
2. https://github.com/jwilm/alacritty/issues/2041

**Comment by RedSoxFan** [comment]
For 1, what do you have in your `input *` block? I'm not seeing it in the debug log
Or did you mean it works with `input *`, but not `input 1:1:AT_Translated_Set_2_keyboard`?

**Comment by krnl0138** [comment]
@RedSoxFan, works with `input * ` but not with `input 1:1..`. From my config.
```
input * {
    repeat_delay 200
    repeat_rate 10
    xkb_layout us,ru
    xkb_options grp:caps_toggle
}
```

**Comment by emersion** [comment]
You probably need to quote the device name?

**Comment by krnl0138** [comment]
@emersion, I did quote, respectively, it doesn't apply

**Comment by RedSoxFan** [comment]
Are you using an external keyboard? There is also `2522:37008:A4TECH_USB_Device_Keyboard`, which sounds like it could be an actual keyboard. If not, I'd try the various identifier listed by get_input until you find the right one. If `input *` works, one of the identifiers should match the device you are using

**Comment by krnl0138** [comment]
@RedSoxFan, I thought that too, but after revision `1382:12290:HID_0566:3002` has worked for me.
Also I installed alacritty-git from AUR, still no changes, however, patch was merged to master according to their bugtracker, weird stuff.
Anyway, it seems to be closed now, thanks for help guys, you are awesome!

**Comment by RedSoxFan** [comment]
> Also I installed alacritty-git from AUR, still no changes, however, patch was merged to master according to their bugtracker, weird stuff.

I think the fix was for a dependency so it may not be pulling the newest version of the dependency yet

**Comment by krnl0138** [comment]
@RedSoxFan, it may be reasonable to add this hint with `input *` into the documentation / wiki for newcomers, because it is really confusing when some options work, but others don't all of a sudden.
Like:

> **Keyboard repeat delay and rate**
>
> input \<identifier\> {
>     repeat_delay 500
>     repeat_rate 5
> }
>
> If you see no changes with your current identifier, you could try using * instead of \<identifier\> to apply those parameters to all identifiers at once. After this you can manually sort out the identifier you need by substitution.

**Comment by emersion** [comment]
I believe it should be added to the DESCRIPTION part because it applies to all input commands.

Could also do the same for seats.
