### ISSUE TITLE
Wrong mpv floating window size and borders

### ISSUE THREAD

**Issue by bitraid** [swaywm/sway#3718]
This problem occurs when mpv is configured to run as a floating window.
Similar to the old #680, although version 0.15.2 worked as expected for me.
It is maybe related to #2176 and #3106 

intel graphics
sway version 1.0-rc1-74-g7baaa3a0 (Feb 18 2019, branch 'master')
wlroots version 0.3-fd0b625ab
mpv version 0.29.0-134-g8b563a0346

* Configuration File:
Default configuration with the addition:
`for_window [app_id="mpv"] floating enable`

* Debug Log:
https://gist.github.com/bitraid/86638d2d95c54bdb2048586b18ccd5c3

* mpv Log:
https://gist.github.com/bitraid/206dfb02cc87f32d41900cd7e7d5e02e
>[vo/gpu/wayland] Resizing due to xdg from 1024x768 to 665x499
>[vo/gpu/wayland] Handling resize on the egl side

* Steps to reproduce:
1. Open the terminal.
2. Run: `mpv /usr/local/share/backgrounds/sway/Sway_Wallpaper_Blue_768x1024.png --no-config --image-display-duration=inf -v`

* Expected behavior:
The mpv floating window should have the dimensions of the playing image/video (as it happens with version 0.15.2 and i3wm).

* Actual behavior:
The mpv window has a smaller size and its borders are incorrect. Furthermore, switching to the tiling area after scaling the mpv window to its either half, normal or double size (<kbd>Alt</kbd>+<kbd>0</kbd>, <kbd>Alt</kbd>+<kbd>1</kbd>, <kbd>Alt</kbd>+<kbd>2</kbd>), resets the window size. Manual resize of the window seems buggy, messes up the borders and can't increase after a certain size.

**Comment by bendooru** [comment]
>The mpv window has a smaller size

If the option `floating_maximum_size` is unset it will default to 66% of your output's width and height, respectively, which may explain the initial wrong size and upper limit on manual resizing.

>messes up the borders

Can confirm, mpv seems to always render with the initial aspect ratio, so after resizing the image/video may spill out of the container.

**Comment by emersion** [comment]
Maybe related to https://github.com/swaywm/sway/issues/3593

**Comment by bitraid** [comment]
Thanks for the patch, it works better now but there are still issues with resizing: mismatch window - borders size, which might also produce artifacts on the background tiling area.

**Comment by RedSoxFan** [comment]
> there are still issues with resizing: mismatch window - borders size, which might also produce artifacts on the background tiling area.

Can you provide more information and possibly reproduction steps and/or a screenshot?

**Comment by bendooru** [comment]
Using this minimal config


    bindsym Mod4+e exit
    bindsym --release Print exec grim $(date +grim_%Y-%m-%d-%H%M%S%N.png)
    for_window [app_id="mpv"] floating enable

    output "*" bg #ff0000 solid_color

    exec mpv --no-config --gpu-context=wayland -v --image-display-duration=inf /usr/share/backgrounds/sway/Sway_Wallpaper_Blue_1136x640.png > ~/mpv-resize.log

Produces the following behaviour: First resizing vertically: If a video is playing, the transparent areas seen here may become corrupted.

![grim_2019-03-03-115911613870131](https://user-images.githubusercontent.com/17952483/53694330-8914f780-3dad-11e9-8e9f-7f74a0e58bf6.png)

Then horizontally:

![grim_2019-03-03-115919904185828](https://user-images.githubusercontent.com/17952483/53694339-a9dd4d00-3dad-11e9-838a-8bcf05ba0a29.png)

Logs: 
[sway-resize-debug.log](https://github.com/swaywm/sway/files/2923030/sway-resize-debug.log)
[mpv-resize.log](https://github.com/swaywm/sway/files/2923034/mpv-resize.log)

**Comment by RedSoxFan** [comment]
The first screenshot is due to mpv keeping the aspect ratio constant and sending a surface smaller than the view. In this situation we just center the surface in the view. I think this is working as intended, but it is possible that it could be changed to have sway render black bars.

The second is #3029
