### ISSUE TITLE
layout change targets focused container, while in i3 it targets parent

### ISSUE THREAD

**Issue by edrex** [swaywm/sway#3724]
In i3, layout change targets the parent of the selected container always.

In sway, layout change targets the parent only if the selected container is a window, otherwise it targets the selected container.

The behavior is only different when there are three or more levels of containers, and an intermediate level container is selected.

For example, with [ a b ] selected in the following layout,

```
 -------
| a |   |
 ---| c |
| b |   |
 -------
```

pushing `Ctrl-e` would change to

```
 -------
| | |   |
|a|b| c |
| | |   |
 -------
```
while in i3 it would change to

```
 -------
|   a   |
|-------|
|   b   |
|-------|
|       |
|   c   |
|       |
 -------
```

I noticed this the first time I played with sway but of course at that time there were bigger issues. Now things are so stable I'm nitpicking :)

If it's confirmed as a bug, I'd like to fix it as a #firstpatch since it's probably a one-liner (c isn't my native lang)

**Comment by RedSoxFan** [comment]
> If it's confirmed as a bug, I'd like to fix it as a #firstpatch

Since this does not match i3's behavior, I'm going to confirm this as a bug. Feel free to work on it and send a PR
