### ISSUE TITLE
[feature request] add an desktop session entry to include the debug.log

### ISSUE THREAD

**Issue by sanga** [swaywm/sway#3727]
or perhaps just amend the current desktop session entry (when installing from git) to output the debug log somewhere.

(at least for i3 as packaged for ubuntu), I get GDM entries for both "i3" and "i3 with debug log". When installing sway from git I get "sway" (which I gather is injected to `/usr/local/share/wayland-sessions/sway.desktop`. For debugging I imagine it would be very useful to also include an entry to drop the debug log somewhere (maybe `~/.cache/sway.log` for example)

**Comment by ddevault** [comment]
No thanks.
