### ISSUE TITLE
Liberapay donations

### ISSUE THREAD

**Issue by oliverpool** [swaywm/sway#3731]
Hi,

thank for this amazing piece of software!

Do you have any plan to set-up the donation page on liberapay (https://liberapay.com/on/github/swaywm) ?

I just saw that @ddevault is accepting donations there (https://liberapay.com/SirCmpwn/) and was wondering if it would be much work to open the team page.

Otherwise I would be happy to donate to the individuals directly :-)

**Comment by ddevault** [comment]
The logistics of figuring out how to pay who and when and what for are complicated and difficult to get right. Today I work full time thanks to the donations on LiberaPay, and I hope tomorrow I'll be able to support more people. Until then, I just try to buy hardware and send it to devs when they need it, etc. I think the status quo is fine, but if there are any sway or wlroots devs who feel differently, please reach out privately.

I appreciate your interest and support :)
