### ISSUE TITLE
Segfault with /dev/uinput usage

### ISSUE THREAD

**Issue by logol** [swaywm/sway#3747]
Hey, I'm not sure if this really is a sway issue, but when I'm using [this](https://github.com/bendahl/uinput) uinput wrapper library for go, sway segfaults when using the `RightPress()` function (which should simulate the press of the right mouse button).  Sway identifies the virtually created device and other things like mouse movement or left clicks work as expected.

Sway Version: 1.0-beta.2-236-g5c834d36 (Jan 21 2019)

stacktrace doesn't seem to be so useful.. but I can provide a core dump if needed
```
Core was generated by `sway'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f2a2c743701 in ?? ()
[Current thread is 1 (LWP 4927)]
(gdb) thread apply all bt full

Thread 2 (LWP 4928):
#0  0x00007f2a2bf42f5c in ?? ()
No symbol table info available.
#1  0x0000000000000000 in ?? ()
No symbol table info available.

Thread 1 (LWP 4927):
#0  0x00007f2a2c743701 in ?? ()
No symbol table info available.
#1  0x000055f13814fa60 in ?? ()
No symbol table info available.
#2  0x000055f13870e000 in ?? ()
No symbol table info available.
#3  0x0000000000000001 in ?? ()
No symbol table info available.
#4  0x000000001af3ea01 in ?? ()

... and about 40 more lines like this
```

**Comment by ascent12** [comment]
Without debugging symbols, that backtrace isn't useful.
Also, sway doesn't use any threads itself, and those would all come internally from your GPU driver, so they can be ignored.

There is also the possibility this is a libinput issue, because it would go through them before it reaches us. Does it work on another wayland compositor (e.g. weston)?

**Comment by logol** [comment]
It seems this only happens when I do **not** add extra delays between the different commands e.g. press/release. Anyways it is related to libinput, I can reproduce on weston - so no sway issue... closing.
