### ISSUE TITLE
Make bindsym --whole-window work on empty workspace like i3

### ISSUE THREAD

**Issue by GSF1200S** [swaywm/sway#3750]
sway version 1.0-rc1-98-gd3d79565 (Feb 22 2019, branch 'master')

Using bindsym --whole-window $mod+button2 works when over an open window (e.g. termite) and any command bound to it functions as it should. In my case, I have a launcher menu (which is actually termite launched like Rofi would be) set to spawn. If you $mod+button2 on an empty workspace/desktop however, nothing happens. An enhancement was filed against i3 for this feature: https://github.com/i3/i3/issues/2097

How difficult would this be to incorporate in Sway? I am prepared to run the latest git, provide logs or provide whatever information you may need.

**Comment by RedSoxFan** [comment]
I'm actually going to label this as a bug since sway's behavior unintentionally differs from i3's. For some reason, I thought this did not work in i3, but just confirmed it does.

> How difficult would this be to incorporate in Sway? I am prepared to run the latest git, provide logs or provide whatever information you may need.

It should be relatively easy to implement. No logs or anything needed
