### ISSUE TITLE
swaymsg: socket path issue

### ISSUE THREAD

**Issue by CaptainBloodz** [swaywm/sway#3769]
sway -v
sway version 1.0-rc1-115-gd4b1e71b (Feb 24 2019, branch 'HEAD')
swaymsg 
[sway-9999/swaymsg/main.c:385] Unable to retrieve socket path
-
Sorry if this is due to subtile changes made regarding execution environment.
Thks 4 ur attention.

**Comment by CaptainBloodz** [comment]
temporaly fixed with:
export SWAYSOCK=$(ls /run/user/*/sway-ipc.*.sock | head -n 1)

Thks 4 ur attention

**Comment by CaptainBloodz** [comment]
toto

**Comment by CaptainBloodz** [comment]
temporary fixed with:
export SWAYSOCK=$(ls /run/user/*/sway-ipc.*.sock | head -n 1)

Thks 4 ur attention

**Comment by 2m** [comment]
Thanks, this helped my. I needed just a tiny modification:

```
export SWAYSOCK=(ls /run/user/1000/sway-ipc.* | head -n 1)
```

**Comment by stratosgear** [comment]
I am trying to run a wallpaper changing script from inside a systemd service and I get a:

```
Dec 06 23:40:59 serenity set_walls[183521]: 2019-12-06 23:40:59 - [swaymsg/main.c:404] Unable to retrieve socket path
```
while running:

```
swaymsg -t get_outputs -r
```
to get a list of my monitors (sometimes I have attached monitors to my laptop)

**BUT** in my case the socket that works is the second one, so I have to run:

```
export SWAYSOCK=(ls /run/user/1000/sway-ipc.* | sed -n 2p)
```

Any idea why there are two sockets and how to dynamically be able to decide which one is the correct one?

**Comment by stratosgear** [comment]
Ha!  `sway --get-socketpath` gives you the current socket used!

**Comment by ammgws** [comment]
Is the output the same as /run/user/(id -u)/sway-ipc.(id -u).(pidof sway).sock ?

**Comment by stratosgear** [comment]
For me yes!  But `sway --get-socketpath` is easier no? Well, I guess it would depend on the conditions under which you need it, but still...

**Comment by xeruf** [comment]
`sway --get-socketpath` prints the contents of `SWAYSOCK` ^^

**Comment by JetForMe** [comment]
```
$ sway --get-socketpath
sway socket not detected.
```

**Comment by waffle-frame** [comment]
Hi, i faced the same problem.

I'm using Fedora Linux 38 (Workstation Edition) x86_64.
When I try to run I get the following error:

```
00:00:00.008 [../swaymsg/main.c:491] Unable to retrieve socket path
```

How can this be fixed?

I also used all the material that I found in this issue and got another error:
```
$ export SWAYSOCK=(ls /run/user/1000/sway-ipc.* | head -n 1)
bash: syntax error near unexpected token `|'
```

**Comment by wrenparismoe** [comment]
Same here

**Comment by HidemaruOwO** [comment]
Me too

**Comment by BenSYZ** [comment]
> Hi, i faced the same problem.
> 
> I'm using Fedora Linux 38 (Workstation Edition) x86_64. When I try to run I get the following error:
> 
> ```
> 00:00:00.008 [../swaymsg/main.c:491] Unable to retrieve socket path
> ```
> 
> How can this be fixed?
> 
> I also used all the material that I found in this issue and got another error:
> 
> ```
> $ export SWAYSOCK=(ls /run/user/1000/sway-ipc.* | head -n 1)
> bash: syntax error near unexpected token `|'
> ```

you missed a `$` before `(`, so the correct command is:
```sh
export SWAYSOCK=$(ls /run/user/1000/sway-ipc.* | head -n 1)
```

**Comment by waffle-frame** [comment]
I had to switch to Arch Linux OS, but thanks for the answer anyway.
I think you made one lucky person's day!
@BenSYZ

**Comment by anonhostpi** [comment]
_**NOTE:**_

`export SWAYSOCK=$(ls /run/user/1000/sway-ipc.* | head -n 1)` may not work as intended if you have multiple sway sock files.

I'm assuming that this can happen when you are running sway on different ttys or if you had failures restarting sway. It happened on my environment. Just had to specify the sock manually.

You can also use `ps eax | grep 'SWAYSOCK' | grep -o 'SWAYSOCK=[^ ]*' | cut -d'=' -f2` to get all *used\*\** instances of SWAYSOCK.
- \*\*SWAYSOCK is set by sway automatically sway _after_ it is started. Because of this, if no process has been spawned after sway starts, the above greps will return empty.
- Tested on Ubuntu Server 22

**Comment by anonhostpi** [comment]
Better method for getting unique sockets:

```
lsof /run/user/1000/sway-ipc.* 2>/dev/null | awk '{print $9}' | tail -n +2 | sort | uniq
```

This grabs any sockets _actively_ being used. You may have to change the `awk` format string based on your output from lsof.

**Comment by Anoncheg1** [comment]
I don't use systemd that is why I don't have "/run/user/". I have seatd service runned that should provide everything I guess. 

I run sway this way:
```bash
#!/bin/sh
if test -z "${XDG_RUNTIME_DIR}"; then
  export XDG_RUNTIME_DIR=/tmp/"${UID}"-runtime-dir
    if ! test -d "${XDG_RUNTIME_DIR}"; then
        mkdir "${XDG_RUNTIME_DIR}"
        chmod 0700 "${XDG_RUNTIME_DIR}"
    fi
fi
sway
```

Please help. I can't use "swaymsg" command.
