### ISSUE TITLE
RFC: Changes to output transform command.

### ISSUE THREAD

**Issue by c-edw** [swaywm/sway#3770]
There are a few changes I would like to make to the `transform` command possibly post-1.0. I'm willing to send a patch for these.

- The first one is 'additive' transforms. The would allow users to prefix the rotation value with a plus (`+`) or minus (`-`), and this value would be added to the current rotation value. An example usage:

```
# Each time I press $mod+R, my screen rotates 90 degrees.
bindsym $mod+R output eDP-1 transform +90
```

- The second is that I would like to improve the arg parsing for the `transform` command. Currently, it won't allow for a user to have a rotation of `0`, you have to pass `normal`. Same for `360` or `720` (obviously these are redundant, but still valid). To fix this, I would like to parse the value as an int and then apply a modulus operation to clamp it between 0-360 degrees. It looks like the command also allows `flipped-` in the value so the actual implementation will be a bit more complex.

**Comment by RedSoxFan** [comment]
>  The first one is 'additive' transforms. The would allow users to prefix the rotation value with a plus (`+`) or minus (`-`), and this value would be added to the current rotation value.

`transform [flipped-](90|180|270) [clockwise|anticlockwise]` already exists for +/- 90/180/270 degree relative transformations. I'm not sure how useful arbitrary degree rotations would be, but there may be a use case

>  The second is that I would like to improve the arg parsing for the `transform` command. Currently, it won't allow for a user to have a rotation of `0`, you have to pass `normal`. Same for `360` or `720` (obviously these are redundant, but still valid). To fix this, I would like to parse the value as an int and then apply a modulus operation to clamp it between 0-360 degrees. It looks like the command also allows `flipped-` in the value so the actual implementation will be a bit more complex.

I'm fine with `0` as an alias for `normal`. However, I am not a fan of clamping the transformation. I think that whatever is supplying the transformation should be in charge of clamping the values and making sure it is supplying a valid value. My comments on the arbitrary degree rotations here are the same as above

**Comment by ddevault** [comment]
>There are a few changes I would like to make to the transform command possibly post-1.0.

Note that we'll accept the patch into master whenever you want. We won't include it in 1.0 but 1.0 isn't based on master.

**Comment by c-edw** [comment]
@RedSoxFan There isn't a way to have additive rotations right now. I didn't explain what I mean by that very clearly. If I specify a rotation of `+90`, then I would expect executing it four times to bring me back to the original rotation. Values without a plus/minus prefix will behave as they do now (a static rotation).

@ddevault Are commits being cherry-picked from master?

**Comment by RedSoxFan** [comment]
> @RedSoxFan There isn't a way to have additive rotations right now. I didn't explain what I mean by that very clearly. If I specify a rotation of `+90`, then I would expect executing it four times to bring me back to the original rotation. Values without a plus/minus prefix will behave as they do now (a static rotation).

For +/- 90/180/270 transformations, you can append the transform with `clockwise` and `anticlockwise` for relative transformation. So `transform 90 clockwise` four times (or `transform 180 clockwise` twice) would accomplish that. Other arbitrary degree transformations are not currently supported

> @ddevault Are commits being cherry-picked from master?

_(Obviously I'm not ddevault, but)_ yes

**Comment by c-edw** [comment]
Ah I see now, it does rotate relatively with `clockwise`/`anticlockwise`. I'm not a fan of how that works personally. I would rather just pass `-90` or `90` for example to determine the direction and then you could instead pass `relative` when desired.

```
# Rotate relatively 90 degrees (clockwise)
output eDP-1 transform 90 relative

# Rotate relatively by -90 degrees (anticlockwise)
output eDP-1 transform -90 relative

# Rotate by a static -180 degrees.
output eDP-1 transform -180
```

I have a feeling you won't be keen on this either though. I do still think that values outside of the -360 to 360 range should be accepted. There's nothing invalid about a 720 degree rotation.

**Comment by RedSoxFan** [comment]
> I have a feeling you won't be keen on this either though

Submit a PR. If others are fine with it, I won't block it from being merged. The only part of it that I'm not a huge fan of is the clamping since I think that should be done by the caller. If you are parsing it as an integer, that is trivial anyway. If you are going that route, you may want to consider making flipped a flag to make parsing easier. Relative could be implemented as one as well if you wanted.

**Comment by tokyovigilante** [comment]
We did talk about using +/-<offset> for relative transforms in rather than the clockwise/anticlockwise in IRC before the original pull request (#3046), it doesn’t bother me too much if it changes.

I’m not sure accepting anything other than 90/180/270 or >360 degree relative transforms is a bad idea per se, but I don’t know what scenario you would have a valid transform >270, and I always like to have a defined set of inputs rather than having to parse a large set.

**Comment by emersion** [comment]
>I would rather just pass `-90`

It would parse as a flag, IIRC.

Another issue is that we use wlroots output transform enums, which only has 0/90/180/270 transforms. What's your use-case for arbitrary transforms?

**Comment by c-edw** [comment]
Not arbitrary transforms. I would just like values that fall outside of the 0-360 degree range to be wrapped and accepted.

I put together a small example program which might clear things up a bit: https://gist.github.com/c-edw/2c147ee041763b028467d8ab0e73c2d0

You'll see if you run it with odd values like `./a.out normal -270`, it wraps the value to 90 (`WL_OUTPUT_TRANSFORM_90`). Or you could pass -720 degrees and it will wrap the value to simply `WL_OUTPUT_TRANSFORM_NORMAL`.

**Comment by emersion** [comment]
>I would just like values that fall outside of the 0-360 degree range to be wrapped and accepted.

Yes, I get that. But why would you need that?

**Comment by c-edw** [comment]
I don't need it per se, but I can imagine a scenario where a script calculates some value of its own and tries to pass a value outside of that range. It's like I said above, a 720 degree rotation is valid anyway so I don't see why the command would bounce a value like that.

I'm not too bothered about that part though. The reason I started looking at this code is because I can't pass `transform 0`, which is irritating. I can send a patch for just that component soon, but it leaves holes such as 'should `flipped-0` also be allowed?'

**Comment by emersion** [comment]
>script calculates some value of its own and tries to pass a value outside of that range

The script can easily clamp the value. I'm more worried about bug reports like "transform 42 doesn't return an error but doesn't do anything".

I'm fine with adding "0" as an alias for "normal".
