### ISSUE TITLE
Output position appears to reset after rotation.

### ISSUE THREAD

**Issue by c-edw** [swaywm/sway#3773]
I have Sway configured so that I have an external monitor above my primary one and I can move my cursor across them:

```
set $display_width 1920
set $display_height 1080

output $display_primary {
       	pos 0 $display_height res $display_widthx$display_height
}

output $display_other {
       	pos 0 0 res $display_widthx$display_height
}
```

This works fine until I rotate my primary screen (`$display_primary`) four times clockwise to reach a normal rotation again.

```
output eDP-1 transform 90 clockwise
```

After doing that, the output position appears to be reset so I can't move my cursor between my monitors vertically.

**Comment by RedSoxFan** [comment]
Can you send the output of `swaymsg -t get_outputs` before and after rotating? It's working fine for me with your config snippet

**Comment by c-edw** [comment]
I've tried it again this morning and can't produce the issue myself... maybe a fluke. I was fiddling with the config quite a lot after all. As usual, I'll reopen the issue if I encounter it again.
