### ISSUE TITLE
Escape character in mode with pango markup 

### ISSUE THREAD

**Issue by schauveau** [swaywm/sway#3775]
sway version 1.0-rc1-116-g2510e3df (Feb 24 2019, branch 'master')

I am trying to create a mode with pango markups (to add colors). Unfortunately, I noticed that the single and double quote characters (so '  and ") are escaped differently in the bindsym and in the mode commands. This is problematic since they are needed for the pango markup attributes. It took me 2 hours to figure out how to obtain something that works.  The purpose of that bug report is (1) to point out what does not work and why and (2) to give a syntax that works for the current master branch. 

So let's assume that we are trying to create a mode using the following $HELLO variable. The intuitive way does not work:  

```set $HELLO "<span bgcolor='blue'>Hello</span>"
bindsym Alt+F3 mode "$HELLO"
mode --pango_markup "$HELLO" {
   bindsym Escape mode "default"
}
```
So I tried several variants with and without double-quote and the following syntax is the only one that works:

```
set $HELLO "<span bgcolor='blue'>Hello</span>"
bindsym Alt+F3 mode "$$HELLO"
mode --pango_markup $HELLO {
   bindsym Escape mode "default"
}
```
  
So the rules are:
- The value of the variable **MUST** be "quoted" in the set command
- The variable given to bindsym mode **MUST USE A DOUBLE $**. Here the "quotes" are optional.
- The variable given to mode --pango_markup **MUST NOT BE QUOTED** and **MUST USE A SINGLE $**.

**Comment by RedSoxFan** [comment]
The value given to set is a literal replacement so
```
set $HELLO "<span bgcolor='blue'>Hello</span>"
bindsym Alt+F3 mode "$HELLO"
mode --pango_markup "$HELLO" {
```
will be converted to
```
bindsym Alt+F3 mode ""<span bgcolor='blue'>Hello</span>""
mode --pango_markup ""<span bgcolor='blue'>Hello</span>"" {
```
which will not work due to having invalid quoting



With #3777, the following will work
```
set $HELLO "<span bgcolor='blue'>Hello</span>"
bindsym Alt+F3 mode $HELLO
mode --pango_markup $HELLO {

# - or -

set $HELLO <span bgcolor='blue'>Hello</span>
bindsym Alt+F3 mode "$HELLO"
mode --pango_markup "$HELLO" {
```

**Comment by schauveau** [comment]
Thanks. That works and this is a lot more intuitive than my double $ trick.
