### ISSUE TITLE
Workspaces are not moved to external display as expected.

### ISSUE THREAD

**Issue by c-edw** [swaywm/sway#3778]
In my configuration file, I have:

```
workspace 1 output $display_primary
workspace 3 output $display_primary
workspace 5 output $display_primary
workspace 7 output $display_primary
workspace 9 output $display_primary
```

This means that when I connect an external display, the workspaces in between will be moved there in an alternating pattern. This works, but only if I start Sway with the external display connected.

If I start Sway without the external display connected and spawn some windows in the first three workspaces for example *and then* connect an external display, only the fourth will appear there. I would expect the second and fourth workspace to appear there according to the configuration above.

**Comment by emersion** [comment]
If you don't specify workspace-output mappings, the output on which workspaces will appear is not defined.

**Comment by c-edw** [comment]
I see. The reason I'm looking at this is because I'm looking to see if I can get my config to be more versatile across different display setups. I essentially would like to be able to say "put these workspaces on this display always, put the other workspaces on any other display if available".

But now that I think about it, this should probably be done through a shell script.

**Comment by emersion** [comment]
>I essentially would like to be able to say "put these workspaces on this display always, put the other workspaces on any other display if available".

You can specify multiple outputs for each workspace.
