### ISSUE TITLE
Proposal: Single key event mode

### ISSUE THREAD

**Issue by schauveau** [swaywm/sway#3779]
When using `mode` to create a menu, each `bindsym` command typically ends with a `mode "default"` action to quit the menu. Keys that are not handled by any bindsym command are passed to the focused windows which can be confusing and potentially dangerous. I am proposing to add a mechanism to insure that the mode handles exactly one keypress. I see 2 ways to achieve that

(1) by providing a command to be executed when no other bindsym command was triggered:
```
mode $appmenu {
   bindsym $mod+f exec firefox ; mode "default"
   bindsym $mod+e exec emacs ; mode "default"
   bindsym $mod+t exec thunderbird ; mode "default"
   binddefault  mode "default"
}
```
(2) by providing an option to restore the default (or previous?) mode when any keypress (or mouse button?) is detected:  

```
mode --single $appmenu {
   bindsym $mod+f exec firefox 
   bindsym $mod+e exec emacs
   bindsym $mod+t exec thunderbird 
   # open a sub-menu 
   bindsym $mod+F1 mode $appmenu2
}
```
In the last case, the `mode default` are not required anymore after the bindsym. Ideally, the default mode should be restored BEFORE executing any bindsym command to allow other modes to be opened (as in the F1 mode).

**Comment by emersion** [comment]
Has this been suggested to i3 already?

**Comment by schauveau** [comment]
No. 
PS: I am not a i3 user. I am experienced with Awesome (so a very flexible Lua configuration) and I am looking for a Wayland alternative.

**Comment by ddevault** [comment]
If you can convince i3, we'll add it.
