### ISSUE TITLE
Allow setting custom modes

### ISSUE THREAD

**Issue by jakubn551** [swaywm/sway#3791]
Hi, i would like to know if sway have some support for external gpu (expresscard) and gpu hotswap.
and second question: how to use non native resolution if it is possible. Thanks.

**Comment by emersion** [comment]
>external gpu

Yes, this is supported.

>gpu hotswap

Not supported, but it won't work with ExpressCard anyway.

>non native resolution

Not yet supported, but shouldn't be hard to add.

**Comment by ascent12** [comment]
This is more of a wlroots issue than a sway issue.

>gpu hotswap

This is planned, but not at the top of my priority list.

>>non native resolution

>Not yet supported, but shouldn't be hard to add.

I actually had some code sitting on a branch somewhere implementing the width*height@rate -> mode part, but I couldn't be bothered hooking the rest of it up at the time. I should dig that up at some point.

**Comment by emersion** [comment]
>I actually had some code sitting on a branch somewhere implementing the width*height@rate -> mode part, but I couldn't be bothered hooking the rest of it up at the time. I should dig that up at some point.

Note that we already have a wlroots function adding a custom mode to a DRM output.

**Comment by ascent12** [comment]
>Note that we already have a wlroots function adding a custom mode to a DRM output.

Yeah, I meant hooking it up to `wlr_output_set_custom_mode`. Calculating the `drmModeModeInfo` yourself is somewhat non-trivial, and I don't want the user to have to resort to anything archaic like xfree86 modelines or something.
