### ISSUE TITLE
manpages don't build with scdoc 1.9.1

### ISSUE THREAD

**Issue by CaptainBloodz** [swaywm/sway#3792]
sway version 1.0-rc1-130-g4431ae68 (Feb 28 2019, branch 'HEAD')
/usr/bin/scdoc < ../sway-9999/sway/sway-ipc.7.scd > sway-ipc.7: Error at 217:1: Expected either '|' or ':'

**Comment by emersion** [comment]
You need scdoc 1.9. See https://github.com/swaywm/sway/pull/3788

**Comment by CaptainBloodz** [comment]
Ok, indeed 1.8.1 here

**Comment by everdabling** [comment]
Similar problem with scdoc 1.9.1

Ninja gives
[7/273] Generating sway-ipc.7 with a custom command.
FAILED: sway-ipc.7 
/bin/sh -c '/usr/local/bin/scdoc < ../sway/sway-ipc.7.scd > sway-ipc.7'
**Error at 268:3: Tables cannot be indented**
[12/273] Generating 'protocols/protocols@@client_protos@sta/xdg-shell-protocol.c'.
ninja: build stopped: subcommand failed.

**Comment by CaptainBloodz** [comment]
same here:
ninja -v -j3 -l3 -C /var/tmp/portage/gui-wm/sway-9999/work/sway-9999-build
ninja: Entering directory `/var/tmp/portage/gui-wm/sway-9999/work/sway-9999-build'
[1/273] /bin/sh -c '/usr/bin/scdoc < ../sway-9999/sway/sway.1.scd > sway.1'
[2/273] /bin/sh -c '/usr/bin/scdoc < ../sway-9999/sway/sway.5.scd > sway.5'
[3/273] /bin/sh -c '/usr/bin/scdoc < ../sway-9999/sway/sway-bar.5.scd > sway-bar.5'
[4/273] /bin/sh -c '/usr/bin/scdoc < ../sway-9999/sway/sway-input.5.scd > sway-input.5'
[5/273] /bin/sh -c '/usr/bin/scdoc < ../sway-9999/sway/sway-ipc.7.scd > sway-ipc.7'
FAILED: sway-ipc.7 
/bin/sh -c '/usr/bin/scdoc < ../sway-9999/sway/sway-ipc.7.scd > sway-ipc.7'
Error at 268:3: Tables cannot be indented

**Comment by vkobel** [comment]
Same here, looks like you really need scdoc `==1.9.0`: https://git.sr.ht/~sircmpwn/scdoc/archive/1.9.0.tar.gz
I managed to compile sway using this version.

**Comment by RedSoxFan** [comment]
There is a bug in scdoc 1.9.1. The patch to fix it has been submitted (https://lists.sr.ht/~sircmpwn/public-inbox/%3C20190228141744.5250-1-bosrsf04%40gmail.com%3E)

**Comment by monsieurh** [comment]
Out of curiosity, why not using `pandoc` to build the doc instead of `scdoc` ?

**Comment by Ferdi265** [comment]
the ArchLinux community repo has switched to scdoc 1.9.1. For now it is impossible to build sway on ArchLinux with manpages without downgrading scdoc.

**Comment by Emantor** [comment]
From IRC:
`emersion ╡ workaround: meson -Dman-pages=disabled`

**Comment by RedSoxFan** [comment]
Update: scdoc was patched ~90 minutes ago so the current scdoc master should allow building sway with man pages enabled. 1.9.1 is still the newest release, but the patch should be included in the next scdoc release

**Comment by RedSoxFan** [comment]
scdoc 1.9.1 is no longer the newest scdoc release so I'm going to close this. sway should have a successful build when man pages are enabled with scdoc 1.9.0 and 1.9.2 or newer.
