### ISSUE TITLE
spotify escapes workspace assignment

### ISSUE THREAD

**Issue by CaptainBloodz** [swaywm/sway#3793]
A couple of apps assigned to workspaces here:
assign [class="Mixxx"] 6
assign [class="Carla"] 7
assign [class="Audacity"] 8
assign [class="Spotify"] 7
assign [class="Firefox"] 9
assign [class="Cadence"] 10

among which Spotify doesn't work.
I'm not 100% sure, but AKAIR it has been working recently,

**Comment by emersion** [comment]
Can you share the output of `swaymsg -t get_tree` when Spotify is running?

Also a debug log.

**Comment by CaptainBloodz** [comment]
swaymsg -t get_tree
{
   "id": 1,
   "name": "root",
   "rect": {
     "x": 1920,
     "y": 0,
     "width": 1920,
     "height": 1080
   },
   "focused": false,
   "focus": [
     26
   ],
   "border": "none",
   "current_border_width": 0,
   "layout": "splith",
   "orientation": "horizontal",
   "percent": null,
   "window_rect": {
     "x": 0,
     "y": 0,
     "width": 0,
     "height": 0
   },
   "deco_rect": {
     "x": 0,
     "y": 0,
     "width": 0,
     "height": 0
   },
   "geometry": {
     "x": 0,
     "y": 0,
     "width": 0,
     "height": 0
   },
   "window": null,
   "urgent": false,
   "floating_nodes": [
   ],
   "sticky": false,
   "type": "root",
   "nodes": [
     {
       "id": 2147483647,
       "name": "__i3",
       "rect": {
         "x": 1920,
         "y": 0,
         "width": 1920,
         "height": 1080
       },
       "focused": false,
       "focus": [
         2147483646
       ],
       "border": "none",
       "current_border_width": 0,
       "layout": "output",
       "orientation": "horizontal",
       "percent": null,
       "window_rect": {
         "x": 0,
         "y": 0,
         "width": 0,
         "height": 0
       },
       "deco_rect": {
         "x": 0,
         "y": 0,
         "width": 0,
         "height": 0
       },
       "geometry": {
         "x": 0,
         "y": 0,
         "width": 0,
         "height": 0
       },
       "window": null,
       "urgent": false,
       "floating_nodes": [
       ],
       "sticky": false,
       "type": "output",
       "nodes": [
         {
           "id": 2147483646,
           "name": "__i3_scratch",
           "rect": {
             "x": 1920,
             "y": 0,
             "width": 1920,
             "height": 1080
           },
           "focused": false,
           "focus": [
           ],
           "border": "none",
           "current_border_width": 0,
           "layout": "splith",
           "orientation": "horizontal",
           "percent": null,
           "window_rect": {
             "x": 0,
             "y": 0,
             "width": 0,
             "height": 0
           },
           "deco_rect": {
             "x": 0,
             "y": 0,
             "width": 0,
             "height": 0
           },
           "geometry": {
             "x": 0,
             "y": 0,
             "width": 0,
             "height": 0
           },
           "window": null,
           "urgent": false,
           "floating_nodes": [
           ],
           "sticky": false,
           "type": "workspace"
         }
       ]
     },
     {
       "id": 26,
       "name": "HDMI-A-1",
       "rect": {
         "x": 1920,
         "y": 0,
         "width": 1920,
         "height": 1080
       },
       "focused": false,
       "focus": [
         23,
         11
       ],
       "border": "none",
       "current_border_width": 0,
       "layout": "output",
       "orientation": "none",
       "percent": 1.0,
       "window_rect": {
         "x": 0,
         "y": 0,
         "width": 0,
         "height": 0
       },
       "deco_rect": {
         "x": 0,
         "y": 0,
         "width": 0,
         "height": 0
       },
       "geometry": {
         "x": 0,
         "y": 0,
         "width": 0,
         "height": 0
       },
       "window": null,
       "urgent": false,
       "floating_nodes": [
       ],
       "sticky": false,
       "type": "output",
       "active": true,
       "primary": false,
       "make": "Unknown",
       "model": "Monitor TV",
       "serial": "",
       "scale": 1.0,
       "transform": "normal",
       "current_workspace": "1",
       "modes": [
         {
           "width": 720,
           "height": 400,
           "refresh": 70082
         },
         {
           "width": 640,
           "height": 480,
           "refresh": 59940
         },
         {
           "width": 640,
           "height": 480,
           "refresh": 60000
         },
         {
           "width": 640,
           "height": 480,
           "refresh": 72809
         },
         {
           "width": 640,
           "height": 480,
           "refresh": 75000
         },
         {
           "width": 720,
           "height": 480,
           "refresh": 59940
         },
         {
           "width": 720,
           "height": 480,
           "refresh": 60000
         },
         {
           "width": 720,
           "height": 576,
           "refresh": 50000
         },
         {
           "width": 800,
           "height": 600,
           "refresh": 56250
         },
         {
           "width": 800,
           "height": 600,
           "refresh": 60317
         },
         {
           "width": 1024,
           "height": 768,
           "refresh": 60004
         },
         {
           "width": 1280,
           "height": 720,
           "refresh": 50000
         },
         {
           "width": 1280,
           "height": 720,
           "refresh": 59940
         },
         {
           "width": 1280,
           "height": 720,
           "refresh": 60000
         },
         {
           "width": 1152,
           "height": 864,
           "refresh": 59967
         },
         {
           "width": 1440,
           "height": 900,
           "refresh": 59901
         },
         {
           "width": 1680,
           "height": 1050,
           "refresh": 59883
         },
         {
           "width": 1920,
           "height": 1080,
           "refresh": 23976
         },
         {
           "width": 1920,
           "height": 1080,
           "refresh": 24000
         },
         {
           "width": 1920,
           "height": 1080,
           "refresh": 50000
         },
         {
           "width": 1920,
           "height": 1080,
           "refresh": 59940
         },
         {
           "width": 1920,
           "height": 1080,
           "refresh": 60000
         }
       ],
       "current_mode": {
         "width": 1920,
         "height": 1080,
         "refresh": 60000
       },
       "nodes": [
         {
           "id": 23,
           "name": "1",
           "rect": {
             "x": 1920,
             "y": 22,
             "width": 1920,
             "height": 1058
           },
           "focused": false,
           "focus": [
             24,
             36
           ],
           "border": "none",
           "current_border_width": 0,
           "layout": "splith",
           "orientation": "horizontal",
           "percent": null,
           "window_rect": {
             "x": 0,
             "y": 0,
             "width": 0,
             "height": 0
           },
           "deco_rect": {
             "x": 0,
             "y": 0,
             "width": 0,
             "height": 0
           },
           "geometry": {
             "x": 0,
             "y": 0,
             "width": 0,
             "height": 0
           },
           "window": null,
           "urgent": false,
           "floating_nodes": [
           ],
           "sticky": false,
           "num": 1,
           "output": "HDMI-A-1",
           "type": "workspace",
           "representation": "H[termite (null)]",
           "nodes": [
             {
               "id": 24,
               "name": "luc@acerlpm:~",
               "rect": {
                 "x": 1920,
                 "y": 22,
                 "width": 960,
                 "height": 1058
               },
               "focused": true,
               "focus": [
               ],
               "border": "normal",
               "current_border_width": 2,
               "layout": "none",
               "orientation": "none",
               "percent": 0.5,
               "window_rect": {
                 "x": 2,
                 "y": 0,
                 "width": 956,
                 "height": 1032
               },
               "deco_rect": {
                 "x": 0,
                 "y": 0,
                 "width": 960,
                 "height": 24
               },
               "geometry": {
                 "x": 0,
                 "y": 0,
                 "width": 574,
                 "height": 338
               },
               "window": null,
               "urgent": false,
               "floating_nodes": [
               ],
               "sticky": false,
               "type": "con",
               "fullscreen_mode": 0,
               "pid": 30750,
               "app_id": "termite",
               "visible": true,
               "marks": [
               ],
               "nodes": [
               ]
             },
             {
               "id": 36,
               "name": "Spotify",
               "rect": {
                 "x": 2880,
                 "y": 22,
                 "width": 960,
                 "height": 1058
               },
               "focused": false,
               "focus": [
               ],
               "border": "normal",
               "current_border_width": 2,
               "layout": "none",
               "orientation": "none",
               "percent": 0.5,
               "window_rect": {
                 "x": 2,
                 "y": 0,
                 "width": 956,
                 "height": 1032
               },
               "deco_rect": {
                 "x": 0,
                 "y": 0,
                 "width": 960,
                 "height": 24
               },
               "geometry": {
                 "x": 0,
                 "y": 0,
                 "width": 800,
                 "height": 600
               },
               "window": 8388609,
               "urgent": false,
               "floating_nodes": [
               ],
               "sticky": false,
               "type": "con",
               "fullscreen_mode": 0,
               "pid": 24930,
               "app_id": null,
               "visible": true,
               "marks": [
               ],
               "window_properties": {
                 "class": "Spotify",
                 "instance": "spotify",
                 "title": "Spotify",
                 "transient_for": null
               },
               "nodes": [
               ]
             }
           ]
         },
         {
           "id": 11,
           "name": "9",
           "rect": {
             "x": 1920,
             "y": 22,
             "width": 1920,
             "height": 1058
           },
           "focused": false,
           "focus": [
             12
           ],
           "border": "none",
           "current_border_width": 0,
           "layout": "splith",
           "orientation": "horizontal",
           "percent": null,
           "window_rect": {
             "x": 0,
             "y": 0,
             "width": 0,
             "height": 0
           },
           "deco_rect": {
             "x": 0,
             "y": 0,
             "width": 0,
             "height": 0
           },
           "geometry": {
             "x": 0,
             "y": 0,
             "width": 0,
             "height": 0
           },
           "window": null,
           "urgent": false,
           "floating_nodes": [
           ],
           "sticky": false,
           "num": 9,
           "output": "HDMI-A-1",
           "type": "workspace",
           "representation": "H[Firefox]",
           "nodes": [
             {
               "id": 12,
               "name": "spotify escapes workspace assignment · Issue #3793 · swaywm\/sway - Mozilla Firefox",
               "rect": {
                 "x": 1920,
                 "y": 22,
                 "width": 1920,
                 "height": 1058
               },
               "focused": false,
               "focus": [
               ],
               "border": "normal",
               "current_border_width": 2,
               "layout": "none",
               "orientation": "none",
               "percent": 1.0,
               "window_rect": {
                 "x": 2,
                 "y": 0,
                 "width": 1916,
                 "height": 1032
               },
               "deco_rect": {
                 "x": 0,
                 "y": 0,
                 "width": 1920,
                 "height": 24
               },
               "geometry": {
                 "x": 0,
                 "y": 0,
                 "width": 1916,
                 "height": 1032
               },
               "window": 6291472,
               "urgent": false,
               "floating_nodes": [
               ],
               "sticky": false,
               "type": "con",
               "fullscreen_mode": 0,
               "pid": 0,
               "app_id": null,
               "visible": false,
               "marks": [
               ],
               "window_properties": {
                 "class": "Firefox",
                 "instance": "Navigator",
                 "title": "spotify escapes workspace assignment · Issue #3793 · swaywm\/sway - Mozilla Firefox",
                 "transient_for": null,
                 "window_role": "browser"
               },
               "nodes": [
               ]
             }
           ]
         }
       ]
     }
   ]
 }

**Comment by CaptainBloodz** [comment]
Sorry to ask but for debug log, do you mean:
1) console echo from sway compiled with debug as a configuration? ( which I'd have to figure out how since my gentoo doesn't provide...)
2) gdb backtrace

**Comment by emersion** [comment]
```
sway -d >sway.log 2>&1
```

**Comment by CaptainBloodz** [comment]
console debug  from start to exit:
[sway.log](https://github.com/swaywm/sway/files/2916081/sway.log)
NB: The tree logged above belongs to this session.

**Comment by CaptainBloodz** [comment]
I've trim down the sway/config for logging.
Then put it back together with a few changes, e.g. the way and order to start jackdbus related stuff.
Now spotify is properly assigned.

Will come back here if something more consistent is to be reported.
Confused  :((

**Comment by CaptainBloodz** [comment]
Even more confused:
Before I got your replay, I've rebuilded sway with -ggdb CFLAGS, which seems the reason why Spotify assignment got to work all of a sudden!!!
I understood that as I reverted sway build to normal, then restarted.

**Comment by RedSoxFan** [comment]
This is an issue with Spotify itself. It is setting WM_CLASS after mapping so assign commands are not going to work with it (and it is also a ICCCM violation). According to [a Spotify developer in 2016](https://community.spotify.com/t5/Desktop-Linux/WM-CLASS-window-property-on-Linux/m-p/1427287/highlight/true#M4226), it is a limitation of the way they are using the Chromium Embedded Framework (CEF).

[i3 recommends](https://github.com/i3/i3/issues/2060#issuecomment-155179472) using the following instead (which is working for me in Sway):
```
for_window [class="Spotify"] move container|window to workspace $workspace
```

**Comment by CaptainBloodz** [comment]
sway version 1.0-rc1-138-g43035951 (Mar  2 2019, branch 'HEAD')
-
Additionally, log reports:
2019-03-01 15:28:37 - [sway-9999/sway/commands.c:253] Handling command 'exec spotify'
2019-03-01 15:28:37 - [sway-9999/sway/commands.c:145] find_handler(exec)
2019-03-01 15:28:37 - [sway-9999/sway/commands/exec_always.c:46] Executing spotify
Failed to connect to user bus: No such file or directory
2019-03-01 15:28:37 - [sway-9999/sway/commands/exec_always.c:87] Child process created with pid 13356
2019-03-01 15:28:37 - [sway-9999/sway/tree/root.c:253] Recording workspace for process 13356

Thks

**Comment by CaptainBloodz** [comment]
after exec spotify In /swat/config, I added
for_window [class="Spotify"] move window to workspace $workspace
which works at start but not a later instance, e.g. from dmenu.

**Comment by japhir** [comment]
The workaround hasn't worked for me in a while now. Any ideas?
First [1300 lines of sway.log](http://ix.io/1Gwd) (seems to continue logging even though I tried not to ;-))

**Comment by AndreasBackx** [comment]
Same here, I cannot get this assignment to work like it used to work in i3.

**Comment by RedSoxFan** [comment]
@japhir, it looks like you are using:
```
for_window [class="Spotify"] move to workspace $ws10
```

You can try one of the following (both should work):
```
for_window [class="Spotify"] move window to workspace $ws10
# -- or --
for_window [class="Spotify"] move container to workspace $ws10
```

Currently sway requires an explicit `window`/ `container`, whereas i3 does not. I'll submit a PR within the next couple hours to add the missing syntax options that i3 allows for (https://github.com/i3/i3/blob/a574346964ce17d35df2ef9072ba16e26209ac84/parser-specs/commands.spec#L316-L324)

@AndreasBackx, I'm going to take a guess that you omitted the `window`/`container` as well. If you are using the 1.0 release, you can switch to one of the syntax options above. If you are on git master, the PR should be up shortly

**Comment by AndreasBackx** [comment]
@RedSoxFan thank you for the explanation. Both the window and container options work for me.

**Comment by japhir** [comment]
@RedSoxFan thanks! I saw the above explanation and tried a literal `window|container`, but not either of the options :S. This works, thanks for checking!
What's the difference between a container and a window? I can't find `container` in the man page or the wiki.

**Comment by RedSoxFan** [comment]
> What's the difference between a container and a window

It's just an alias. The syntax comes from i3 and they allow either to be given. The bottom line is you can give either and get the same result. If you are on git master, you can also omit it since #4069 has been merged

> I can't find container in the man page or the wiki.

The layout is a tree. You have the root, outputs, workspaces, and containers. The containers are children of the workspace. The branches are just for layout purposes and the leaves have views, which are the actual application windows

**Comment by jsravn** [comment]
This assignment works for me, at least initially, but then Spotify changes its workspace sporadically on its own during usage. Is there a way to lock it to a workspace? `for_window [class="Spotify"] move container to workspace $ws5` is what I'm using.

**Comment by Exagone313** [comment]
I had the same issue of @jsravn. When clicking the icon to go to fullscreen mode in Spotify, it would open a new window on the initial workspace (where Spotify window got moved from).

I solved it by adding a second rule with `title`:
```ini
for_window [class="Spotify"] move window to workspace $w
for_window [class="Spotify" title="Spotify.*"] move window to workspace $w
```
