### ISSUE TITLE
Games don't run if Sway config misses external monitor configuration

### ISSUE THREAD

**Issue by gnidorah** [swaywm/sway#3796]
`sway version 1.0-rc3`

I use laptop (screen eDP-1) and occasionally connect external monitor to it (screen HDMI-A-2). Sway works if configuration file only has line describing laptop monitor
```
output eDP-1 pos 1920,0 res 1920x1080 scale 1.5
```
However games crash (extremetuxracer for example).
```
The requested video mode is not available, switching to a valid mode
fish: 'nix run nixpkgs.extremetuxracer…' terminated by signal SIGSEGV (Address boundary error)
```
If I add line describing external monitor and restart Sway
```
output HDMI-A-2 pos 0 0 res 1920x1200
output eDP-1 pos 1920,0 res 1920x1080 scale 1.5
```
games run OK.

**Comment by Gigg1ty** [comment]
I had a somewhat similar issue, and my setup looks like yours. My primary screen is my TFT, and i have a TV connected to the left of my TFT:

`output DP-1 mode 1920x1080@119.982002Hz pos 1920 0`
`output HDMI-A-2 mode 1920x1080@60Hz pos 0 0`

If the screen to the left (pos 0,0) is disabled, Firefox (with wayland enabled) will no longer show any menus (eg. right click on links to open in a new tab, or when clicking on folders in the bookmarks toolbar).
I believe some applications do not handle it very well, if the only active screen is not positioned at 0,0.

I solved this through a script. My TV is initially disabled in sway's config (and the TFT is at position 0,0):

`output DP-1 mode 1920x1080@119.982002Hz pos 0 0`
`output HDMI-A-2 disable`

The script then enables HDMI-A-2 again, and moves DP-1 to 1920,0:

`swaymsg "output HDMI-A-2 enable"`
`swaymsg "output DP-1 mode 1920x1080@119.982002Hz pos 1920 0"`
`swaymsg "output HDMI-A-2 mode 1920x1080@60Hz pos 0 0"`

**Comment by RedSoxFan** [comment]
> If the screen to the left (pos 0,0) is disabled, Firefox (with wayland enabled) will no longer show any menus 

That is https://github.com/swaywm/sway/issues/3135#issuecomment-448794177 and unrelated to this issue.

This issue is probably due to clients not being able to change the resolution and whatever the native resolution for HDMI-A-2 is (which I'm guess is not 1920x1200 since it works with that mode), is not supported by the game. After reading https://bugzilla.redhat.com/show_bug.cgi?id=1289714, it looks like the solution may be implementing viewporter (wlroots tracker for viewporter - https://github.com/swaywm/wlroots/issues/633)

**Comment by gnidorah** [comment]
@RedSoxFan HDMI-A-2 native resolution is 1920x1200. eDP-1 native resolution is 1920x1080. Again I got issues with games when I forgot to include
`output HDMI-A-2 pos 0 0 res 1920x1200`
in my config. After I've added it, games started to work.
I just think there should no be error or crash with games in that situation, there should be either warning that something is missing, or games should just work.

**Comment by RedSoxFan** [comment]
> HDMI-A-2 native resolution is 1920x1200.

So HDMI-A-2 automatically gets set to `1920x1200` even without it being set in the config? Can you post the output of `swaymsg -t get_outputs` with and without the config line? If the mode is the same, it should make no difference.

> I just think there should no be error or crash with games in that situation, there should be either warning that something is missing, or games should just work.

Sway has no control over the games code and cannot detect when it is going to crash

**Comment by gnidorah** [comment]
@RedSoxFan 
[with-line.txt](https://github.com/swaywm/sway/files/2923583/with-line.txt)
[without-line.txt](https://github.com/swaywm/sway/files/2923584/without-line.txt)
The only difference is:
```
--- without-line.txt    2019-03-03 22:35:28.383772291 +0300
+++ with-line.txt       2019-03-03 22:34:15.455752680 +0300
@@ -9,7 +9,7 @@ Output eDP-1 'Sharp Corporation 0x1447 0
 
 Output HDMI-A-2 'Acer Technologies Acer V243PWL LV8080034233'
   Current mode: 1920x1200 @ 59.950001 Hz
-  Position: 3200,0
+  Position: 0,0
   Scale factor: 1.000000
   Transform: normal
   Workspace: 2
@@ -35,4 +35,3 @@ Output HDMI-A-2 'Acer Technologies Acer
     1280x1024 @ 75.025002 Hz
     1680x1050 @ 59.882999 Hz
     1920x1200 @ 59.950001 Hz
```

**Comment by RedSoxFan** [comment]
What version of xwayland are you using? extremetuxracer is working fine for me in Arch Linux with xwayland 1.20.4 with the same config. It looks like https://gitlab.freedesktop.org/xorg/xserver/merge_requests/2/, which was merged in 1.20.2 might be related.

**Comment by gnidorah** [comment]
Its not only etr, but also for e.g. steam's deponia don't start if external monitor line is missing

**Comment by gnidorah** [comment]
`xwayland-1.20.4`
Ok, I've tried some more games (supertux, wesnoth...) and they seem to work. Perhaps that's etr issue then.
Some games fail with "couldn't init graphics", but I suppose that's distro issue.
I just wonder though whether the following could influence on etr
```
-  Position: 3200,0
+  Position: 0,0
```
