### ISSUE TITLE
Drag and Drop Stops Working

### ISSUE THREAD

**Issue by SwayUser** [swaywm/sway#3801]
* Sway Version:
sway version 1.0-rc1-134-g88b283c5 (Mar  1 2019, branch 'master')

* Debug Log:
https://0x0.st/z-ne.log (nautilus-wayland.log)
https://0x0.st/z-n2.log (gajim-wayland.log)
https://0x0.st/z-n_.log (sway.log)

* Configuration File:
https://0x0.st/zipQ.txt

* Steps to reproduce
1. Start Nautilus
1. Start Gajim in floating mode
1. Open an image in eog
1. Drag the image into gajim, but don't finish it (just move the image from the window away again).
1. Observe that drag and drop stops working after some time.

**Comment by emersion** [comment]
Gah. I can reproduce by just dragging a floating Nautilus. My previous patch fixed exactly this bug, I've probably missed something.

**Comment by emersion** [comment]
Okay, this one is a little different. It seems that it breaks only when dragging a window without the mod key. That is:

1. Open Nautilus
2. Make it floating
3. Drag the titlebar
4. Drag-and-drop is broken

**Comment by emersion** [comment]
Fixed in https://github.com/swaywm/sway/pull/3812
