### ISSUE TITLE
Introduce default seatop

### ISSUE THREAD

**Issue by RyanDwyer** [swaywm/sway#3813]
For after 1.0 is released.

The idea is we'd add a none/idle/normal/default seatop which handles most of `dispatch_cursor_button` and `cursor_send_pointer_motion` (ie. click to focus, `focus_follows_mouse`, starting other seatops). We would then treat seatops as being more like a seat state, so there's always a seatop in progress. It might make more sense to rename seatops to seat states at this point.

This would remove a good chunk of code out of `cursor.c`, would remove some early returns, and should make it easier to manage things like sending button events and tracking which buttons are pressed.

**Comment by emersion** [comment]
+1

We do the same in wlroots for grabs, we have a default grab.
