### ISSUE TITLE
issue with sway-ipc.7.scd wrong indent

### ISSUE THREAD

**Issue by lapryx** [swaywm/sway#3815]
when installing sway-git using makepkg ninja returns an error:

Error: a failure occured in build()

below are the last lines of codes containing the error and other usefull info:

ninja: Entering directory '/sway-git/src/build'
[4/243] Generating sway-ipc.7 with a custom command.
FAILED: sway-ipc.7
/usr/bin/sh -c '/usr/bin/scdoc < ../sway/sway/sway-ipc.7.scd > sway-ipc,7'
Error at 268:3 Tables cannot be indented
[9/243] Compiling C object 'common/92a5dc0@@sway-common@sta/background-image.c.o' .
ninja: build stopped: subcommand failed.
==> ERROR: A failure occured in build()
        Aborting. . .

it seems like there is an indentation error in ../sway/sway/sway-ipc.7.scd at line 268 thus below the lines surrounding 268 in sway-ipc.7.scd:

236        [
237	    {
238		    "name": "HDMI-A-2",
239		    "make": "Unknown",
240		    "model": "NS-19E310A13",
241		    "serial": "0x00000001",
242		    "active": true,
243		    "primary": false,
244		    "scale": 1.0,
245		    "transform": "normal",
246		    "current_workspace": "1",
247		    "modes": [
248			    {
249				    "width": 640,
250				    "height": 480,
251				    "refresh": 59940
252			    },
253			    {
254				    "width": 800,
255				    "height": 600,
256				    "refresh": 60317
257			    },
258			    {
259				    "width": 1024,
260				    "height": 768,
261				    "refresh": 60004
262			    },
263			    {
264				    "width": 1920,
265				    "height": 1080,
266				    "refresh": 60000
267			    }
268		    ],
269		    "current_mode": {
270			    "width": 1920,
271			    "height": 1080,
272			    "refresh": 60000
273	    	    }
274	    }
275    ]

**Comment by emersion** [comment]
You need scdoc == 1.9.0 or >= 1.9.2 to build man pages. It won't work with 1.9.1.

As a temp workaround, you can pass `-Dman-pages=disabled` to meson.

**Comment by lapryx** [comment]
Thanks a lot, did not know this was an issue. now everything is installing.
