### ISSUE TITLE
missing sway-ipc.*.soc

### ISSUE THREAD

**Issue by lapryx** [swaywm/sway#3817]
sway -v:
sway version 1.0-rc1-141-ga053823f (Mar 4 2019, branch 'master')

i keep getting errors about the socket and using env | grep SWAYSOCK returns:
SWAYSOCK=

after this i tried setting the SWAYSOCK with export SWAYSOCK=$(ls /run/user/*/sway-ipc.*.sock | head -n 1) but this returned:
ls: cannot acces '/run/user/*/sway-ipc.*.sock': no such file or directory. 
i couldn't find any similar issue and was hoping someone could point me the way to finding/fixing this missing file.

**Comment by RedSoxFan** [comment]
Sway sets `SWAYSOCK` on launch. What exactly are you trying to do? Some more information may help point you in the right direction.

**Comment by RedSoxFan** [comment]
Were you able to resolve this issue?

**Comment by lapryx** [comment]
Yes, thanks for the support. I have since left this project behind.

Kind regards,
Thijs
