### ISSUE TITLE
ninja -C build fails

### ISSUE THREAD

**Issue by aspieln3r** [swaywm/sway#3831]
ninja: Entering directory `build'
[73/273] Compiling C object 'sway/345c74e@@sway@exe/server.c.o'.
FAILED: sway/345c74e@@sway@exe/server.c.o 
cc -Isway/345c74e@@sway@exe -Isway -I../sway -Iinclude -I../include -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/uuid -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/json-c -I/usr/include/libevdev-1.0/ -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/libdrm -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -std=c11 -g '-DSWAY_SRC_DIR="/home/fsinft/git-clones/sway"' -DWL_HIDE_DEPRECATED -DWLR_USE_UNSTABLE -Wno-unused-parameter -Wno-unused-result -Wundef -Wvla '-DSYSCONFDIR="//usr/local/etc"' '-DSWAY_VERSION="1.0-rc1-148-g0df76ed9 (" __DATE__ ", branch '"'"'master'"'"')"' -pthread  -MD -MQ 'sway/345c74e@@sway@exe/server.c.o' -MF 'sway/345c74e@@sway@exe/server.c.o.d' -o 'sway/345c74e@@sway@exe/server.c.o' -c ../sway/server.c
../sway/server.c: In function ‘server_start’:
../sway/server.c:187:52: error: ‘struct wlr_xwayland’ has no member named ‘display_name’; did you mean ‘display’?
   setenv("DISPLAY", server->xwayland.wlr_xwayland->display_name, true);
                                                    ^~~~~~~~~~~~
                                                    display
[82/273] Compiling C object 'sway/345c74e@@sway@exe/desktop_output.c.o'.
ninja: build stopped: subcommand failed.

**Comment by emersion** [comment]
You need to upgrade wlroots.

Always upgrade wlroots when you upgrade sway.

**Comment by aspieln3r** [comment]
I'm using latest wlroots from AUR
`aur/wlroots-git 0.4.1.r20.g30d34261-1 (+25 6.15%) (Installed: 0.4.1.r26.g2baad6eb-1)`

**Comment by emersion** [comment]
wlroots is at 2baad6e, not g30d34261. Update it.

**Comment by aspieln3r** [comment]
Thanks 
Issue is fixed
