### ISSUE TITLE
SWAYSOCK duplicated in man

### ISSUE THREAD

**Issue by CaptainBloodz** [swaywm/sway#3834]
sway version 1.0-rc1-149-g7f700e08 (Mar  8 2019, branch 'HEAD')
-
ENVIRONMENT
       The following environment variables have an effect on sway:

       SWAYSOCK
           Specifies the path to the sway IPC socket.

       XKB_DEFAULT_RULES, XKB_DEFAULT_MODEL, XKB_DEFAULT_LAYOUT, XKB_DEFAULT_VARIANT, XKB_DEFAULT_OPTIONS
           Configures the xkb keyboard settings. See xkeyboard-config(7). The preferred way to configure the keyboard is via the
           configuration file, see sway-input(5).

...
       I3SOCK
           For compatibility with i3, specifies the path to the sway IPC socket

       SWAYSOCK
           Specifies the path to the sway IPC socket

**Comment by emersion** [comment]
One is in the "The following environment variables have an effect on sway" section, the other is in the "The following environment variables are set by sway" section.
