### ISSUE TITLE
[Feature Request] Rotate input

### ISSUE THREAD

**Issue by ReekyMarko** [swaywm/sway#3840]
I have a 2-in-1 laptop and sometimes I like to rotate the screen 90 degrees and read PDF's and the like. Back in X, I used to be able to do this: `xrandr --output eDP --rotate right && xinput set-prop "ELAN Touchscreen" --type=float "Coordinate Transformation Matrix" 0 1 0 -1 0 1 0 0 1`

I can do the first part of the command, the rotating of the screen in Sway, but the second part, which is rotating the input of the touch screen I did not find in the documentation, so I think this is not implement yet.

**Comment by emersion** [comment]
Can you try mapping the touch screen to the output?

**Comment by ReekyMarko** [comment]
How does one do that? Sorry, I'm very new to Sway

**Comment by emersion** [comment]
You can have a look at the manpage: `man 5 sway-input`. Grep for "map". ;)

**Comment by ReekyMarko** [comment]
That worked a treat! Thank you very much and sorry for wasting your time. I will check the man pages more thoroughly next time :smile:

**Comment by mb720** [comment]
Thanks for the hint, @emersion! 👍

This worked for me:

    swaymsg input <my-touch-screen> map_to_output <my-monitor>

To get input and output devices, I did `swaymsg -t get_inputs` and `swaymsg -t get_outputs` respectively.

On my Lenovo X220 tablet, this ended up being

    swaymsg input 1386:230:Wacom_ISDv4_E6_Pen map_to_output LVDS-1

After that, I flipped the screen using

    swaymsg output LVDS-1 transform 180

and positioning the cursor on the screen using a finger or the stylus worked flawlessly.

**Comment by fidelsalz** [comment]
Thanks @emersion  for the hint and @mb720 for giving exact commands, they worked perfect.
Just to comment that mouses (and maybe pointers) remap automatically after screen rotation.

**Comment by goekce** [comment]
What about if I want to rotate the input and then map to an output?

I tried `input $tablet rotation_angle 180`, however this did not work

Background: I have my tablet on the right side of my keyboard. The cable input to my tablet is from the left, so the cable disturbs my keyboard.

**Comment by rzimmerdev** [comment]
Any progress on this? I would like to rotate one of my inputs by 90 degrees. Why was it closed?
