### ISSUE TITLE
Missing input devices when using LightDM

### ISSUE THREAD

**Issue by schauveau** [swaywm/sway#3843]
I am using sway compiled from git master on Debian and I noticed that my Fn+Brightness keys were not reporting any events when Sway is started by LightDM (via a custom desktop file in /usr/share/wayland-sessions/ ). Everything works fine when Sway is manually started from a VT.

So I eventually figured out that Sway via LigthDM is missing 3 input devices including the one that reports brightness key events. However, those missing input devices exist and can be tested using evtest or libinput. I also noticed that the missing input devices (and the brightness key events) become visible after switching back and forth to another VT. 

I suspect a race condition between LightDM and Sway (because of ibus?)   
 
I am using a SSD so Sway starts quite fast. Adding a `sleep 1` before sway appears to solve the problem for me. 

System information:
- debian buster
- ligthdm 1.26.0-3
- sway version 1.0-rc1-145-g19df2e59 (Mar  6 2019, branch 'master')

**Comment by ddevault** [comment]
Report this bug with lightdm please.

**Comment by schauveau** [comment]
https://github.com/CanonicalLtd/lightdm/issues/63
