### ISSUE TITLE
Monitor occasionally gets wrong resolution on connect

### ISSUE THREAD

**Issue by kennylevinsen** [swaywm/sway#3844]
* Sway Version: 7f700e08ac8ac95c395b54c86b40d2fc79242310
* Debug Log: None right now, I'll get one later.
* Configuration File: Nothing interesting.

Upon connecting my Dell XPS 9370 to a TB3 dock with two identical 4k screens connected over DisplayPort, one screen will *sometimes* go to 1920x1200 instead of 3840x2160.

swaymsg -t get_outputs insists in this mode that the monitor is only 1080p, despite EDID information being identical when read both normally and while in this defective mode (minus serial number which is just 2 apart).

I have not found one single thing that fixes it. Restarting sway, reconnecting the dock, reconnecting the monitor, changing inputs back and forth, turning it on and off... After trying them all a sufficient amount of times, it ends up working as it should.

The screens never had problems when they were connected to my Ubuntu desktop (also over DisplayPort, also using IGD albeit a 6th gen chip rather than 8th gen in the laptop), nor on a Macbook Pro through the same dock, making it seem like the screens and dock are all fine.

**Comment by RedSoxFan** [comment]
> Debug Log: None right now, I'll get one later.

A debug log may help

> go to 1920x1200 instead of 3840x2160.
> swaymsg -t get_outputs insists in this mode that the monitor is only 1080p

So it's getting set to a mode that isn't listed as available? Currently, the only code path where sway will set a custom mode is when the output advertises no available modes.

> over DisplayPort

Are you using MST and the connector names are changing? If so, try using the output identifiers instead in your config

**Comment by kennylevinsen** [comment]
> A debug log may help

I'll try to get one, but I've been too busy actually using the machine to try to provoke it actively, and I'm not sure how much the debug log would trash my disk if I left it running for days. :/

> So it's getting set to a mode that isn't listed as available?

Sway is setting to the highest mode it thinks is available (1920x1200). However, this is not the highest mode of the screen.

The monitor is only sometimes misinterpreted as being 1920x1200. However, the EDID is identical when read manually during both the "downgraded" mode, and when it correctly sets to 4k. The EDID is also identical to its sibling, apart from a +2 on the serial number.

> Are you using MST and the connector names are changing?

SST and static connector names (DP-1 + DP-2). Connections are through a TB3 dock and a USB-C -> single displayport adapter (dual output docks are a little bit of a pain).

I have as experiment used the screen identifiers and written resolutions/positions, but the issue persists as the screen is misidentified to have a lower max resolution.

While this laptop + IGD + TB3 dock + screens + sway is the only configuration that has exhibited this error (desktop + screens + gnome = no issue, MBP + TB3 dock + screens + macOS = no issue), I am not entirely sure if sway holds any responsibility here.

**Comment by kennylevinsen** [comment]
Okay, so I got a log. However, it seems like Sway tries to modeset DP-1 (the weird screen) to 4k initially, but gets a bad link. Once it comes back up, it only detects 1920x1080 as max mode.

[sway.log](https://github.com/swaywm/sway/files/2950127/sway.log)

I'm starting to get suspicious of my hardware, even though both screen and dock works fine elsewhere...

I'll poke around a bit, and close the ticket if I find a problem elsewhere. In the meanwhile, it appears that turning off the screen for 30 seconds fixes the issue.

**Comment by RedSoxFan** [comment]
I'm not sure if it will help, but can you try the following:
- `echo 0xFF | sudo tee /sys/module/drm/parameters/debug`
- reproduce the issue
- `echo 0x00 | sudo tee /sys/module/drm/parameters/debug`
- upload dmesg

Note: DRM debugging is very verbose so the quicker you can reproduce, the easier it will be to sift through

**Comment by kennylevinsen** [comment]
Thanks for the input. I'll try to see if I can get some debug out of that at some point.

However, I think it's safe to assume that this is definitely not a sway issue, but a lower-level problem, so I'll close this issue.
