### ISSUE TITLE
Some keyboard button combinations do not work

### ISSUE THREAD

**Issue by andersnylander** [swaywm/sway#3847]
With sway 1.0-rc4: 
On a swedish keyboard layout I have configured sway as such:

```code
input * {
	xkb_layout se
	xkb_model pc105
}
```
On this keyboard, the symbols "less than", "greater than" and the "pipe" character are all available on the "102nd" key (scan code KEY_102ND). "<" is produced by simply pressing the button. "greater than" is produced by holding shift and pressing the button. The pipe character is produced by holding AltGr and pressing the button. This is how the button works in most cases, but when I try doing this in sway it doesn't work. Every button combination produces "<" and no other character.

Similarly, the "backslash" key (scan code KEY_BACKSLASH) produces " ' " when pressed, and is supposed to produce an asterisk character when holding shift and pressing button. But every button combination simply produces the ' character instead.

I do not know if there are other inaccessible characters, but these symbols are all pretty important when working in terminal emulators. I do not know if this problem is local to sway, wlroots, or another library dependency.

**Comment by andersnylander** [comment]
After some investigation, I've been able to reproduce this issue on 2 different computers, but the key point is the keyboard itself; A Kingston Hyper-X Alloy FPS (HX-KB1RD1-NO. The second computer, a laptop, does not have this issue when using the laptop keyboard, but when plugging this keyboard in as an external, it exhibits the same issue.

I'm attaching a few xev logs produced in i3wm, sway, and sway-on-laptop (with built-in keyboard) in the hopes that they'll shed some insight as to what's going on here; Already I can see some differences in behaviour between the 3 setups, though I can't pinpoint yet whether this issue belongs here or in a different issue tracker.

Interestingly, the only setup where this issue is exhibited is also the only one that spawns multiple "MappingNotify" events whenever I attempt to type the "greater than" symbol.
[i3_xev.log](https://github.com/swaywm/sway/files/2952614/i3_xev.log)
[laptop_xev.log](https://github.com/swaywm/sway/files/2952615/laptop_xev.log)
[sway_xev.log](https://github.com/swaywm/sway/files/2952616/sway_xev.log)

**Comment by emersion** [comment]
What is the output of `swaymsg -t get_inputs`?

**Comment by andersnylander** [comment]
[get_inputs.log](https://github.com/swaywm/sway/files/2952746/get_inputs.log)

**Comment by emersion** [comment]
May be related to https://github.com/swaywm/wlroots/issues/1217

**Comment by andersnylander** [comment]
Yes, that looks like it's the issue I'm seeing.

**Comment by schauveau** [comment]
Another workaround could be to define a compose key (man 7 xkeyboard-config).
That should gives you access to a lot of additional characters (see /usr/share/X11/locale/en_US.UTF-8/Compose ) and you can add more by creating a ~/.XCompose file. 
For instance mine looks like that:
```
include "%L"    # DO NOT REMOVE: Provide the default compose settings
<Multi_key> <i> <n> <f>         : "∞" U221E   # infinity
<Multi_key> <v> <2>             : "√" U221A   # racine carree
<Multi_key> <v> <3>             : "∛" U221B   # racine cubique
<Multi_key> <u> <u>             : "µ" U221B   # Micro or mu
<Multi_key> <p> <i>             : "π" U03C0   # PI  
<Multi_key> <s> <u> <m>         : "∑" U2211   # Sum 
<Multi_key> <E> <equal>         : "∈" U2208   # Member of  
<Multi_key> <U> <equal>         : "⊆" U2286   # Subset of
<Multi_key> <U> <U>             : "⊂" U2282   # Strict Subset of
```
