### ISSUE TITLE
focus floating window with keyboard (mod+left or mod+right)

### ISSUE THREAD

**Issue by athrungithub** [swaywm/sway#3859]
open two applications in floating mode, partially or fully covered.
Change the application (mod + left or mod + right) using the keyboard and the application does not pass to the front.

Sorry for my English.

**Comment by xPMo** [comment]
Confirmed: `sway 1.0-rc1-149-g7f700e08 (Mar  7 2019, branch 'makepkg')`. Also, confirmed that this is not i3 behavior.

Focus travels between floated windows, but the newly focused window is not raised. This occurs when:
- floating ⇒ floating (as in `focus right`/`left`/...)
- tiling ⇒ floating (as in `focus floating` or `focus mode_toggle`)
- passing mouse over the lower window (with `focus_follows_mouse`)

Should focused windows always be raised? I know some window managers choose to expose an option for this. (XFCE4, for example).

**Comment by Vorsplummi** [comment]
> Should focused windows always be raised? I know some window managers choose to expose an option for this. (XFCE4, for example).

There should at least be option for it. Making focused window always rise would match i3 behaviour and make interacting with floating windows usable with keyboard.

**Comment by xPMo** [comment]
> Making focused window always rise would match i3 behaviour and make interacting with floating windows usable with keyboard.

I agree, it should be the default behaviour regardless.
