### ISSUE TITLE
Mouse settings seemingly lost after using sway for a while

### ISSUE THREAD

**Issue by johnae** [swaywm/sway#3863]
Sway version:
sway version 20c4d242f64f68fc89d72c364506fa7bd854904e

I realize this is somewhat vague. I'll try to follow up with something more concrete. For possibly as much as a few days (I tend to update sway, wlroots, swaylock, swayidle every other day) I've had an issue where I can no longer scroll using my mouse (it's a Microsoft Surface Arc Mouse).

I don't know if this is a sway issue but it starts out working for a while and then at some point doesn't anymore, as in no reaction whatsoever to scroll events. This could be something else ofc but it happened quite recently and I didn't change any configuration in sway. I have a non-verified "feeling" it might have something to do with swaylock/swayidle but tbh I don't know.

As I said, I'll try to follow up with more info.

**Comment by emersion** [comment]
Try running `swaymsg -t get_inputs --raw` to get a list of currently applied libinput settings.

**Comment by johnae** [comment]
For that device I get these settings when scrolling doesn't work:

```json
 {
     "identifier": "1118:2354:Surface_Arc_Mouse",
     "name": "Surface Arc Mouse",
     "vendor": 1118,
     "product": 2354,
     "type": "pointer",
     "libinput": {
       "send_events": "enabled",
       "accel_speed": 0.0,
       "accel_profile": "adaptive",
       "natural_scroll": "enabled",
       "left_handed": "disabled",
       "middle_emulation": "disabled",
       "scroll_method": "none",
       "scroll_button": 274
     }
   },
```

**Comment by johnae** [comment]
And when it does work, it looks like this:

```json
{
     "identifier": "1118:2354:Surface_Arc_Mouse",
     "name": "Surface Arc Mouse",
     "vendor": 1118,
     "product": 2354,
     "type": "pointer",
     "libinput": {
       "send_events": "enabled",
       "accel_speed": 0.0,
       "accel_profile": "adaptive",
       "natural_scroll": "enabled",
       "left_handed": "disabled",
       "middle_emulation": "disabled",
       "scroll_method": "none",
       "scroll_button": 274
     }
   }
```
So basically no difference. I've got another mouse like this at home and the same things happens when using that so it's not the mouse itself it would seem at least.

**Comment by RedSoxFan** [comment]
The libinput config looks fine. Just to confirm, if you run `sudo libinput debug-events`, do the axis events show up?

**Comment by johnae** [comment]
@RedSoxFan Will get back to you when I lose the scrolling again, never used libinput debug-events, very useful. Atm, when it works, I get the axis events just fine. No surprise there I guess.

**Comment by johnae** [comment]
Ok so when I lose scrolling I also no longer see any axis events using `sudo libinput debug-events`.

**Comment by RedSoxFan** [comment]
If it's is not showing in `libinput debug-events`, then sway is not getting the event from libinput and there is nothing we can do. It is either a libinput, driver, or hardware issue. I'd suggest starting with the libinput tracker and see where they point you as they'll probably have a better idea where the issue may lie.

**Comment by johnae** [comment]
For anyone finding this issue - a follow-up is that I had upgraded to Linux 5.0 and I thought it likely it started happening after that, so I then downgraded to 4.20.14 and all was well again so I submitted a kernel bug: https://bugzilla.kernel.org/show_bug.cgi?id=202909

**Comment by leachim** [comment]
I am experiencing a similar issue with Linux kernel 5.1, using sway 1.1-rc2
