### ISSUE TITLE
Feature request: pseudo-tiled window mode

### ISSUE THREAD

**Issue by mxmilkb** [swaywm/sway#3867]
In a nutshell; where windows are placed in a tiled position but not resized.

As seen in [herbstluftwm](https://github.com/herbstluftwm/herbstluftwm/blob/master/src/clientlist.cpp#L571) and [bspwm](https://github.com/baskerville/bspwm/blob/master/src/tree.c#L102).

Examples:
- https://herbstluftwm.org/img/hlwm-pseudotile-1.png
- https://i.imgur.com/xQOaAFQ.png - bspwm (the calculator)
- https://i.redd.it/hyd6bsedq3021.png - bspwm

**Comment by emersion** [comment]
I think we already do this for windows that have a fixed size.

We try not to add features from other tiling window managers, otherwise sway will become like Frankenstein. Instead, you could contribute to projects like https://github.com/Bl4ckb0ne/bspwc/

**Comment by mxmilkb** [comment]
Maybe sway does - might you have an example of such a program?

Fair enough. I thought this one might not have been as out there a new layout system.

**Comment by mxmilkb** [comment]
Found one, the remove chat log popup of Quassel;

![rose_2019-04-18-09:13:33](https://user-images.githubusercontent.com/108225/56346580-5d619b80-61ba-11e9-8b12-665969afc67f.png)

**Comment by unresolvedsymbol** [comment]
There is no way to set a fixed size for a window outside of the program that created it's code though, correct?
