### ISSUE TITLE
sway chrashes in get_deco_rect()

### ISSUE THREAD

**Issue by mwenzkowski** [swaywm/sway#3870]
I am using sway with the commit 783b3d6b378db0bdf2a10bfa8a6787bd4b152a5a from the master branch. With the default configuration sway crashes if I do the following after sway has started:

1.  Start a terminal (in my case termite)
2. Execute the following in this terminal
```
swaymsg layout tabbed, floating enable, border pixel, move absolute 0 0, workspace 2
```
Here is the [debug log](https://gist.github.com/mwenzkowski/5ac497937d6f39d1b6558fd947b8a4f9#file-sway-log) and the [stack trace](https://gist.github.com/mwenzkowski/5ac497937d6f39d1b6558fd947b8a4f9#file-stack-trace).

**Comment by gdamjan** [comment]
seems to happen to me too with sway-1.0 (wlroots 0.5.0 - both from [community] on Arch). 

I run firefox nightly in wayland mode (GDK_BACKEND=wayland), open Help -> About, and then when I try to move the popup window to the workspace 3 or 4, sway crashes.

I have a rule  for firefox and the popup:
```
for_window [app_id="firefox"] {
  border normal 0
  move container to workspace 1 web
}
for_window [app_id="firefox" title="^About Firefox Nightly$"] {
  border normal 1
  floating enable
}
```

(interestingly enough, when I move the popup to workspace 2, where konsole is running, sway doesn't crash).

**Comment by RedSoxFan** [comment]
There is a missing case for floating views on an empty workspace that has the tabbed layout set. I'll submit a bug fix PR in a few hours, if no one beats me to it.

**Comment by languitar** [comment]
Any chance to get a maintenance release out with this fix?

**Comment by RedSoxFan** [comment]
> Any chance to get a maintenance release out with this fix?

That would be up to @ddevault
