### ISSUE TITLE
Add support for layer shell popups

### ISSUE THREAD

**Issue by emersion** [swaywm/sway#3871]
Required by https://github.com/swaywm/sway/issues/3799

**Comment by agraven** [comment]
Proper tray support is one of the main things keeping me from using sway as my daily driver, so I'm interesting in helping implement this.

Exactly what are layer shell popups, and how would one go about implementing them, roughly speaking?

**Comment by emersion** [comment]
Layer shell popups allow desktop UI elements (like the bar) to show menus. For how it works, see the layer-shell protocol in wlr-protocols. For how it should be implemented, see rootston. A test client is available in wlroots examples.

**Comment by schickst** [comment]
#4307

**Comment by Kommynct** [comment]
Pretty sure this should be closed.

**Comment by emersion** [comment]
Fixed in https://github.com/swaywm/sway/pull/4307
