### ISSUE TITLE
output <name> bg not working

### ISSUE THREAD

**Issue by ZakharEl** [swaywm/sway#3874]
setting the background no longer works. Have the right name for output, got it from swaymsg -t outputs. Also have the correct optional dependency installed for swaybg. It started to not work after having had updated wlroots.

Relevent error file is included these lines:
2019-03-11 19:32:30 - [common/background-image.c:49] Failed to read background image: out of memory.
Sway was compiled without gdk_pixbuf support, so only
PNG images can be loaded. This is the likely cause.

I reinstalled sway hoping it would compile with gdk_pixbuf support but I don't believe it did.

**Comment by RedSoxFan** [comment]
Debug log?

**Comment by ZakharEl** [comment]
I updated with the relevent info above. Even after reinstalling sway it still wouldn't load the background.

**Comment by RedSoxFan** [comment]
>Sway was compiled without gdk_pixbuf support, so only PNG images can be loaded. This is the likely cause.
>I reinstalled sway hoping it would compile with gdk_pixbuf support but I don't believe it did.

Are you compiling it manually or installing from a package? If you are using the Arch Linux package, you'll want 1.0-2 or newer since 1.0-1 was compiled without gdk_pixbuf support

**Comment by ZakharEl** [comment]
I installed it from the arch aur. It says it's version 1.0

**Comment by RedSoxFan** [comment]
The `sway-git` AUR package should compile with `gdk_pixbuf` support since `gdk-pixbuf2` is a dependency. Are you using a different AUR package? Does it work with the `sway` package in `community`?

**Comment by ZakharEl** [comment]
yeah it's the community package. Thanks for your help.
