### ISSUE TITLE
Multiple shortcuts don't work with the suggested environment variables set

### ISSUE THREAD

**Issue by vandenheuvel** [swaywm/sway#3878]
* Sway Version: 1.0-3
* [Debug log](https://gist.github.com/vandenheuvel/61a042136926e24a461d5fe08721a985)
* [Configuration File](https://gist.github.com/vandenheuvel/152d4d583dda24fefaa63b4b79b9d693)
* Environment variables in [.config/environment.d/envvars.conf](https://gist.github.com/vandenheuvel/6b5d33e613f0dc10e26913fa77247fdd)
* Description: I am unable to start a new terminal (Super + Enter) or use the dmenu (Super + D). Simply, nothing happens. I am able to close Sway as expected.

I am using HiDPI, multihead, fractional scaling. Only when I set the environment variables (see wiki) as described, this problem occurs. When I set one of these variables manually before starting individual applications, things work as expected (for example, starting GDK_BACKEND=wayland firefox-beta from any terminal).

**Comment by RedSoxFan** [comment]
Don't set the environment variables globally as it will cause issues for applications without wayland support. Most applications that support wayland have already switched over to using wayland without the need for setting these variables. For the ones that haven't, set the necessary variable(s) for just the effected applications

_`_JAVA_AWT_WM_NONREPARENTING=1` is fine to keep global_

**Comment by vandenheuvel** [comment]
@RedSoxFan I wasn't trying to start any applications; just dmenu or a new virtual terminal. Shouldn't that work with these variables set?

**Comment by RedSoxFan** [comment]
It looks like you have `xwayland disable` in your config. Both `urxvt` and `demnu` use the xwayland backend and will not function with xwayland disabled

**Comment by vandenheuvel** [comment]
Then it makes sense, thanks a lot. I assumed that those would be compatible.
