### ISSUE TITLE
[Feature Request] Mouse follows focus

### ISSUE THREAD

**Issue by basingone** [swaywm/sway#3880]
I would love for sway to have this to have this. Is there anything like xdotool for wayland ? ( in case this gets rejected it wouldn't be too hard to implement this using a similar tool )

**Comment by Emantor** [comment]
Are you talking about:
```
mouse_warping container
```

**Comment by RedSoxFan** [comment]
Sounds like `mouse_warping container` like Emantor mentioned.

> Is there anything like xdotool for wayland ?

There is #1779, which is sway specific and not fully implemented yet
