### ISSUE TITLE
Error loading libwlroots on sway 1.0

### ISSUE THREAD

**Issue by AlessioDP** [swaywm/sway#3881]
On latest sway-git and wlroots-git I cannot execute it.

Debug log:
```
sway: error while loading shared libraries: libwlroots.so.1: cannot open shared object file: No such file or directory
```

I tried to install wlroots and sway by compiling them manually.

For now, I can make it works with:
- sway 017a7c4da169ace601f282c87a9aaabc138a34d3
- wlroots master

**Comment by ddevault** [comment]
Update wlroots.

**Comment by nifker** [comment]
@ddevault This does not even work with sway 1.0 and wlroots 5.0.

**Comment by AlessioDP** [comment]
@nifker With a manual compilation of wlroots it worked for me.

**Comment by ddevault** [comment]
Yes, it does. You do not have wlroots 0.5 installed correctly.
