### ISSUE TITLE
nonunicode bitmap font + workspace name with emoji kills apps and bar

### ISSUE THREAD

**Issue by mxmilkb** [swaywm/sway#3883]
If I specify a bitmap font ("font pango:Gohu GohuFont 10") and use a unicode symbol ("8🔒") as part of a workspace name, it kills all apps and gives a blank desktop with cursor.

**Comment by RedSoxFan** [comment]
Can you post a debug log? I just tried it and I'm not able to reproduce.

**Comment by mxmilkb** [comment]
Huh, can't seem to recreate today, pango seems smart enough to use an actual unicode glyph. Sorry for the noise.
