### ISSUE TITLE
Documentation Request: list of keys available

### ISSUE THREAD

**Issue by james-lawrence** [swaywm/sway#3885]
I havent been able to find any list of keys for the configuration. been looking for both i3 documentation or sway specific. given how the majority of the configuration for sway is key bindings this list of all available keys would be handy.

in particular I was looking for keys for volume, mute, suspend, etc.

**Comment by carloabelli** [comment]
sway(5) seems to provide enough info (at least in my opinion):

> You may use XKB key names here (*xev*(1) is a good tool for discovering these).

There is a good amount of documentation about XKB elsewhere.

To summarize it: Start `xev` and press the key you want to bind. Look for something of the form `(keysym 0xff0d, Return)` in the output. You can use that second value plus optional modifiers e.g.
```
bindsym $mod+Return exec $term
```

If you really want to get a full list of keysyms, you can use `xmodmap -pme` and `xmodmap -pke` for modifiers and keys respectively (maybe these could be mentioned in the manual), but using `xev` gives you more certainty that you are mapping the correct key.

**Comment by james-lawrence** [comment]
ah I missed that line in the documentation. maybe a list of some esoteric key names followed by a link to a more comprehensive list would be in order for the documentation/example configuration?

**Comment by ddevault** [comment]
xev is the best way, you just press the key and it tells you what it is. If someone makes a wayland equivalent, though, that'd be nice.

**Comment by hboetes** [comment]
> xev is the best way, you just press the key and it tells you what it is. If someone makes a wayland equivalent, though, that'd be nice.

wev is there now, for documentation purposes.
