### ISSUE TITLE
drm reports output disabled for enabled+dpms off output

### ISSUE THREAD

**Issue by yorickvP** [swaywm/sway#3890]
* Sway Version: 1.0

When an output is enabled but dpms off, DRM reports it as disabled.

This is a problem, since [systemd uses this](https://github.com/systemd/systemd/blob/master/src/login/logind-core.c#L590) information (external screen connected+enabled) to automatically suspend the system, which happens now whenever screens go in DPMS.
This worked with X11.

```bash
$ swaymsg output DP-2 dpms on
$ head /sys/class/drm/card0-DP-2/{status,connected,dpms}
==> /sys/class/drm/card0-DP-2/status <==
connected
==> /sys/class/drm/card0-DP-2/enabled <==
enabled
==> /sys/class/drm/card0-DP-2/dpms <==
On
$ swaymsg output DP-2 dpms off
$ head /sys/class/drm/card0-DP-2/{status,connected,dpms}
==> /sys/class/drm/card0-DP-2/status <==
connected
==> /sys/class/drm/card0-DP-2/enabled <==
disabled
==> /sys/class/drm/card0-DP-2/dpms <==
Off
```

**Comment by emersion** [comment]
The "dpms" property in DRM is being phased out IIRC. @ascent12 Thoughts?

**Comment by ascent12** [comment]
Right. The way for setting DPMS on atomic drivers is to set the ["ACTIVE"](https://01.org/linuxgraphics/gfx-docs/drm/gpu/drm-kms.html#standard-connector-properties) property on the CRTC. In fact, it'll even fail if we try to set the legacy DPMS property if I recall correctly.
Systemd should not be probing this state.

**Comment by emersion** [comment]
The docs say:

> Legacy property
>
>Note that this property cannot be set through the MODE_ATOMIC ioctl, userspace must use “ACTIVE” on the CRTC instead.

So it's a systemd bug. Please report it to them.

**Comment by yorickvP** [comment]
https://github.com/systemd/systemd/issues/12001
