### ISSUE TITLE
swaybg is restarted when "output * dpms on" is sent, even if dpms is already on

### ISSUE THREAD

**Issue by RX14** [swaywm/sway#3892]
```
sway version 1.0-rc1-178-gd64e8ba9 (Mar 14 2019, branch 'master')
```

When I run `swaymsg "output * dpms on"`, `swaybg` is restarted and the background of every output flashes for a few frames, even when the output is already on. This is mildly annoying.

This is triggered by using the below swayidle when charging, the dpms is never turned off but turning dpms on must happen every time.
```
swayidle \
    timeout 300 '[[ $(cat /sys/class/power_supply/BAT1/status) == "Discharging" ]] && swaymsg "output * dpms off"' \
    resume 'swaymsg "output * dpms on"'`
```

**Comment by emersion** [comment]
This happens because we restart swaybg when the output config changes.

**Comment by helionmelion** [comment]
put something like:
```
exec_always killall swaybg 
output * bg /usr/share/backgrounds/sway/Sway_Wallpaper_Blue_1920x1080.png fill
```
must note instead using DPMS on / DPMS off method
```
swaymsg "output * dpms off"' \
    resume 'swaymsg "output * dpms on"'`
```
I use 
`resume 'swaymsg "output * enable"' `
