### ISSUE TITLE
firefox/wayland: main & modules menu lists don't drop down, e.g. on left clicks or arrows navigation+CR

### ISSUE THREAD

**Issue by CaptainBloodz** [swaywm/sway#3896]
firefox/xwayland worls just fine.
Nevertheless, in wayland mode left click menus don't drop down, neither in main menu nor modules.
It is just me, or something to live with for the time being?

Thks 4 ur attention.

**Comment by yorickvP** [comment]
I also experience this bug sometimes, but it can be fixed by restarting sway.

**Comment by RedSoxFan** [comment]
Is this #3135 or something different?

**Comment by yorickvP** [comment]
I have not been able to find the popups anywhere. I'll collect a debug log next time I see it.

**Comment by CaptainBloodz** [comment]
Trying to help:
firefox-65.0.2 + gtk+-2.24 & gtk+-3.24.1 here.
If firefox is launched from terminal, action doesn't report anything.
App main menu dropdown lists also fails via arrow keys.

**Comment by CaptainBloodz** [comment]
clicking on module icon triggers:

 [wlroots-9999/types/wlr_surface.c:609] New wlr_surface 0x560315f3aa50 (res 0x560315ef5cb0)

and nothing happens.

App main menu wise, navigating to bookmark menu (Alt+mouse left click select), then arrow down + CR pops Bookmarks management in a new windows, as expectedfs

**Comment by CaptainBloodz** [comment]
Closing as it seems fixed, very likely due to environment changes.
