### ISSUE TITLE
A non-existing window appears when you press a key when you are in pcmanfm-gtk3

### ISSUE THREAD

**Issue by skostrigin** [swaywm/sway#3898]
A non-existing window appears when you press a key when you are in pcmanfm-gtk3

Steps to reproduce :
1. Open pcmanfm-gtk3
2. Press keys on the keyboard, example, keys " g "

System : Archlinux
Sway version : sway 1.0-3 in the official repository arch linux
Wlroots version : wlroots 0.5.0-1 in the official repository

PS. no matter which keyboard layout is English or Russian.

**Comment by CaptainBloodz** [comment]
Pressing a keyboard sequence in pcmanfm(gtk2 here) should open a text input box bottom right of the screen, which contents, i.e. the sequence, serves as an helper to find beginning matched file in the current displayed directory.
Maybe the non existing window skostrigin refers to is an issue on the text input box management?

No such an issue here on pcmanfm+gtk2@gentoo

**Comment by RedSoxFan** [comment]
```
2019-03-14 22:15:28 - [sway/desktop/xdg_shell.c:480] New xdg_shell popup
Gdk-Message: 22:15:28.992: Window 0x559b694907d0 is a temporary window without parent, application will not be able to position it on screen.
```

If you run pcmanfm in weston, you can briefly see the entry box being rendered at the wrong location. This is a pcmanfm issue. Please report it to them.
