### ISSUE TITLE
pcmanfm-gtk3 does not want to execute executable files

### ISSUE THREAD

**Issue by skostrigin** [swaywm/sway#3899]
pcmanfm-gtk3 does not want to execute executable files

Steps to reproduce:
1. Open pcmanfm-gtk3
2. Press on file to open
3. Choose run, do not works

System : Archlinux
Sway version : sway 1.0-3 in the official repository arch linux
Wlroots version : wlroots 0.5.0-1 in the official repository

PS. Why the sway error, because in kde, pcmanfm-gtk3, execute executable files

**Comment by ddevault** [comment]
...this is definitely not our bug. Talk to pcmanfm.
