### ISSUE TITLE
SDDM + TTY switch

### ISSUE THREAD

**Issue by CaptainBloodz** [swaywm/sway#3900]
I acknowledge SWAY doesn't support DE/WM.
Still SDDM works fine here, allowing to switch between sway and alternate classic xorg-server.
One annoying issue remains, as SWAY gets lost when switching TTY back and forth.
When switching back to TTY7, SWAY session isn't displayed anymore, but SDDM login window instead, in a blocked state.
The only way I found to 'recover' is to kill SWAY process, e.g. 'pkill sway' from TTY1.
As a result TTY7 gets automatically activated/selected, in a operational state.

Maybe someone has faced an similar situation, and found a way to fix it?

Thks 4 ur attention.

**Comment by ddevault** [comment]
>I acknowledge SWAY doesn't support DE/WM.

Thanks for stopping by!

**Comment by progandy** [comment]
Did you try to look at TTY8?

**Comment by CaptainBloodz** [comment]
Yeah babe, TTY8 rocks.
Thks progandy, 4 ur attention, interest & support.
