### ISSUE TITLE
Firefox/wayland keyring password in secondary window

### ISSUE THREAD

**Issue by CaptainBloodz** [swaywm/sway#3903]
Context menu in, at least, one qt app [single in workspace], now opens in side windows instead of central position.
Makes me think of a regression, but I might be wrong.

Thks 4 ur attention.

**Comment by emersion** [comment]
We'll need a lot more details.

Which app? Which menu? How to reproduce? Which version of sway? Debug logs?

**Comment by CaptainBloodz** [comment]
Initially seemed occuring for most apps.
I daily update sway & wlroots.
Now seems more like at random.

It will take a little time to ensure stable conditions, if any,  for the issue to raise.

**Comment by CaptainBloodz** [comment]
Env
a) Firefox is opened at sway start, assigned to workspace 4 and has a plugin that reopens last session automagically.
b) Github password is stored in firefox's 'keyring'.

1) Open firefox
2) Go to github/sway
3) Sign in
4) Display some open issues

5) Close SWAY $mod+Shift+E

6) Login back to SWAY
7) goto workspace 4

Result:
Firefox github/swaywm/sway/issues page has been reopened.
A seconf window on the right requests the password for keyring.

**Comment by CaptainBloodz** [comment]
Seems fixed xith firefox-66.0-r1/gcc 8.3.0
