### ISSUE TITLE
Gamma control not working on amdgpu RX550

### ISSUE THREAD

**Issue by pvreevil** [swaywm/sway#3904]
wlroots gamma-control not working since rc4.

amdgpu RX550

**Comment by emersion** [comment]
Has it ever worked at all? Can you send debug logs?

**Comment by pvreevil** [comment]
Disabling AMD DC on Kernel solved the issue. Thanks for your attention.

**Comment by joshuarubin** [comment]
I'm not sure that disabling DC should be required for this to work. When I run `gamma-control` on my Vega64 it just hangs. I'm happy to provide debug logs, just need to know how.
