### ISSUE TITLE
Please extend the README 'running' section to suggest keeping xwayland installed

### ISSUE THREAD

**Issue by SjonHortensius** [swaywm/sway#3907]
As a new user of wayland using sway it is tempting to remove xorg-server-xwayland as it seems like a minor and optional compatibility layer. However, as #2965 and other issues prove (I have been bitten by this as well) - most applications (including `dmenu`, `sway` itself and `termite`) do not function if xwayland is not installed (unless explicitly configured - which is counter-intuitive). I would suggest to extend the "Running" section of the README on the frontpage with:

> You will probably want to have xwayland installed, since most wayland applications will not start without it

**Comment by c-edw** [comment]
This is something you can send a PR for. That way you can phrase it however you see fit.

**Comment by emersion** [comment]
Yeah, please send a PR.

**Comment by SjonHortensius** [comment]
Sure, I just wanted to gauge the sentiment first. :)
