### ISSUE TITLE
Recomend wf-recorder instead wlstream

### ISSUE THREAD

**Issue by ernierasta** [swaywm/sway#3908]
Hi, just wanted to ask to mention [`wf-recorder`](https://github.com/ammen99/wf-recorder) on release page as an alternative to `wlstream`. From what I had read on reddit it works better than `wlstream`. In my case, `wlstream` segfaults. Hopefully it will improve, but in the meantime it can be a solution for some users.

BTW: Congratulations for 1.0! It is amazing!

**Comment by ddevault** [comment]
I mentioned wf-recorded in the blog post:

https://drewdevault.com/2019/03/11/Sway-1.0-released.html
