### ISSUE TITLE
Rotated output advances rotation on each reload

### ISSUE THREAD

**Issue by minus7** [swaywm/sway#3912]
On current master, e687e120e0cd49157a2bc2d1a509d4fb1fa43490, having a rotated output (degree and direction are irrelevant) will make it rotate by the given amount on each reload. E.g. with `transform 90 anticlockwise` and reloading, it will be 90° rotated. After another reload it will be 180° rotated.

**Comment by RedSoxFan** [comment]
Don't use `clockwise` or `anticlockwise` in the config as they are relative to the current transform. When specifying the transform in the config, use `(flipped-)90/180/270` directly

**Comment by minus7** [comment]
The man page has these words under a config option for a reason, I see. Sorry for the noise.

**Comment by emersion** [comment]
Maybe we should rename those, they are confusing

**Comment by RedSoxFan** [comment]
> Maybe we should rename those, they are confusing

Maybe we can just guard `clockwise/anticlockwise` with a `if (!config->reading)`?

**Comment by emersion** [comment]
We could do that, but we've chosen not to in the first PR so that you can adjust position with multiple relative commands in the config. It probably doesn't make sense regardless, and would be good to guard them.

Their name is still confusing though.

**Comment by RedSoxFan** [comment]
> We could do that, but we've chosen not to in the first PR so that you can adjust position with multiple relative commands in the config. It probably doesn't make sense regardless, and would be good to guard them.

`output <name-or-id> transform 90/180/270 clockwise|anticlockwise` does not even work when the config is first read since the output doesn't yet exist and it is not deferred. The only time it triggers is during a reload and the output is not reset in any way before the handler is executed so you experience this specific issue.

> Their name is still confusing though.

Suggestions?

**Comment by minus7** [comment]
`transform relative <degree>` or make the degree relative if prefixed by `+` or `-`, though I fear that may be confusing as well (`-` being relative)

**Comment by tokyovigilante** [comment]
I'm not impartial obviously, but `clockwise`/`anticlockwise` are unambiguous in terms of the rotation direction, whereas +/- and `left`/`right` are ambiguous when referring to a 2D vertical plane.

**Comment by emersion** [comment]
Sure, but it's not clear it's relative. Also, when you use `transform 90`, you already need to know whether it's clockwise or anti-clockwise.

**Comment by minus7** [comment]
FWIW clockwise/anticlockwise isn't unambigious either. You can interpret it as the rotation of the output/monitor or the rotation of the image displayed. I assumed former and got it the wrong way around. Imo it'll always involve trial and error when configuring, so it's not really important.
