### ISSUE TITLE
Sway background is grey until config reload

### ISSUE THREAD

**Issue by FreeFull** [swaywm/sway#3919]
sway version: `sway version 1.0-rc1-184-g73605dac (Mar 16 2019, branch 'master')`
[sway.log](https://github.com/swaywm/sway/files/2974128/sway.log)
[config](https://github.com/swaywm/sway/files/2974131/config.txt)
The relevant line from the config: `output * bg "/home/freefull/wallpapers/0_a4ab4_6dab62ae_orig.jpg" stretch`

When I start up sway, the background ends up grey instead of getting set to the image in my config. As soon as I reload, the background gets set correctly.

**Comment by emersion** [comment]
I can reproduce. @RedSoxFan Any ideas?

**Comment by RedSoxFan** [comment]
Looks like I overlooked that `get_output_config` skips the wildcard case for #3916. It should be fine to add it with the current version of things. Unfortunately, I'll be away from my laptop for the next ~8hrs. I can submit a PR to add it then, if someone else doesn't before then
