### ISSUE TITLE
firefox wayland github: drag & drop attachment fails

### ISSUE THREAD

**Issue by CaptainBloodz** [swaywm/sway#3921]
I have to switch to firefox xwayland to attach sway.log by drag & frop.
Can't find an alternate solution that would work in wayland mode as it is default here. Any idea?

Thks 4 ur attention

**Comment by FreeFull** [comment]
For me it works if, while dragging, I use the keyboard to switch focus to the Firefox window

**Comment by emersion** [comment]
Hmm. Might be a firefox bug, not sure. A `WAYLAND_DEBUG=client` log of Firefox would help investigating.

**Comment by FreeFull** [comment]
I can't seem to reproduce this any more.

**Comment by CaptainBloodz** [comment]
I didn't get that a click would open a file selector.
So that's not sa critical as an issue.
Still, drag & drop doesn't work here with firefox-66.0-r1/wayland (via GDK_BACKEND)
