### ISSUE TITLE
Copy & Paste lag while switching workspaces

### ISSUE THREAD

**Issue by d4g** [swaywm/sway#3923]
# Description
Copy and paste lags/does not work as expected when quickly switching workspaces.
# How to reproduce
- copy something from qutebrowser
- switch the workspace to a workspace with an open terminal (termite)
- paste it (ctrl-shift-v)
- nothing happens
- switch back and forth
- suddenly the text appears in termite
# Version
``sway -v
sway version 1.0-rc5``
``termite --version
termite v14``

**Comment by emersion** [comment]
This is a qutebrowser bug.
