### ISSUE TITLE
wl_data_source.cancelled not sent when dropping outside any surface

### ISSUE THREAD

**Issue by yorickvP** [swaywm/sway#3932]
* Sway Version: 1.0

* Reproduction Steps:

1. start weston-dnd, make it floating
2. drag to outside of weston-dnd and release mouse

**Comment by emersion** [comment]
WAYLAND_DEBUG log: https://gist.github.com/nickdiego/5becea1a865a96d56a3b14ca1381c39e

Last event is `motion`:

```
[1923619.502] wl_data_device@17.motion(5662254, 40.882812, 239.566406)
```

It should be `cancelled` instead.

**Comment by Emantor** [comment]
Don't the following two lines indicate that the offer was accepted?
```
[1923619.502] wl_data_device@17.motion(5662254, 40.882812, 239.566406)
[1923620.367]  -> wl_data_offer@4278190081.set_actions(7, 2)
[1923620.441]  -> wl_data_offer@4278190081.accept(6400, "text/plain")
```

**Comment by emersion** [comment]
`accept` is used for feedback during drag-and-drop. See https://emersion.fr/blog/2020/wayland-clipboard-drag-and-drop/

**Comment by emersion** [comment]
Eh, you're right, my bad.

**Comment by emersion** [comment]
Eh, no, sorry - `accept` is indeed used for feedback, but that's legacy so not mentioned in my article.

**Comment by nickdiego** [comment]
Furthermore, I've observed some misbehavior regarding enter/leave events. It seems like the client just receives the leave event once the pointer enters another surface (perhaps some tiling-mode assumption is being made at server side?).

**Comment by Emantor** [comment]
Looks like `wlr_seat_pointer_notify_button` is never called when the pointer is outside of a surface.

**Comment by nickdiego** [comment]
> Looks like `wlr_seat_pointer_notify_button` is never called when the pointer is outside of a surface.

@Emantor Does this also fix the issue I describe in the [comment above](https://github.com/swaywm/sway/issues/3932#issuecomment-611751908) ? Or maybe I should file a separate issue for it?

Anyways, thanks for looking into it.

**Comment by Emantor** [comment]
> > Looks like `wlr_seat_pointer_notify_button` is never called when the pointer is outside of a surface.
> 
> @Emantor Does this also fix the issue I describe in the [comment above](https://github.com/swaywm/sway/issues/3932#issuecomment-611751908) ? Or maybe I should file a separate issue for it?

Not sure, haven't looked into it yet. Would be nice if you could test #5200.

**Comment by nickdiego** [comment]
Just gave it a try. This is what I observed:

1. Dragging a file out of nautilus into the desktop shell seems to finish the dnd session, but not sure if it does internally everything expected by clients. I mean, the "fly back" effect in the drag icon that happens on Gnome Shell, for example, does not show up on Sway. [Here](https://gist.github.com/nickdiego/1814cb6c471cc78143f0bb61d0c1d34e) is the debug log for this case.

2. When one drags a file out of its original Nautilus window, enters a second nautilus window (activating it = focus_follows_mouse yes), and then goes back over the desk shell and releases the mouse button there, the file is "moved" to the last focused window. Here's the [debug log](https://gist.github.com/nickdiego/1814cb6c471cc78143f0bb61d0c1d34e). Not sure if this is a app bug in surface activation / data_device enter events, etc. 

Let me know if you need further info.
Thanks.

**Comment by emersion** [comment]
>I mean, the "fly back" effect in the drag icon that happens on Gnome Shell, for example, does not show up on Sway

I think this effect is performed by GNOME Shell itself.

>Not sure if this is a app bug in surface activation / data_device enter events, etc.

Maybe we don't send `leave` in this case?

**Comment by nickdiego** [comment]
> Additionally, I've noticed some misbehavior regarding enter/leave events. It seems like the client just receives the leave event once the pointer enters another surface (perhaps some tiling-mode assumption is being made at server side?).

@emersion Oh, that just reminded me this ^
Indeed, maybe there's something else that needed to be fixed in dnd events handling.

**Comment by nickdiego** [comment]
Thanks for fixing this.

Just opened #5220 to track the aforementioned wl_data_device::leave events issue.
