### ISSUE TITLE
assign using app name?

### ISSUE THREAD

**Issue by mxmilkb** [swaywm/sway#3938]
[Carla](https://github.com/falkTX/Carla) identifies by name but not app_id.

Sway does not include an apps name in the criteria for workspace assignment (`'assign [name="Carla"] $ws7: Token 'name' is not recognised`)

Is assignment by name something sway could do, or is there a reason to avoid that (and a request should be made of Carla instead)?

```
...
             {
               "id": 12,
               "name": "Carla",
               "rect": {
                 "x": 4,
                 "y": 46,
                 "width": 1358,
                 "height": 718
               },
               "focused": false,
               "focus": [
               ],
               "border": "pixel",
               "current_border_width": 3,
               "layout": "none",
               "orientation": "none",
               "percent": 1.0,
               "window_rect": {
                 "x": 0,
                 "y": 3,
                 "width": 1358,
                 "height": 718
               },
               "deco_rect": {
                 "x": 904,
                 "y": 0,
                 "width": 452,
                 "height": 22
               },
               "geometry": {
                 "x": 0,
                 "y": 0,
                 "width": 1058,
                 "height": 716
               },
               "window": null,
               "urgent": false,
               "floating_nodes": [
               ],
               "sticky": false,
               "type": "con",
               "fullscreen_mode": 0,
               "pid": 9899,
               "app_id": "python3",
               "visible": false,
               "marks": [
               ],
...
```

**Comment by RedSoxFan** [comment]
Try `title` instead of `name`. The `name` property in the IPC reply should be the title (before `title_format`).

As for opening a Carla issue, it would probably be more useful if it set its own app id rather than using `python3`

**Comment by mxmilkb** [comment]
title does it, thanks :+1:

**Comment by ddevault** [comment]
Don't forget to reach out to Carla so other users don't experience the same issue.

**Comment by mxmilkb** [comment]
```
<falktx> that is expected and unavoidable afaik
<falktx> all python based applications get that as their initial application name
<falktx> if you know of a way to change this, let me know
```
#lad on Freenode

**Comment by mxmilkb** [comment]
For future reference https://github.com/qutebrowser/qutebrowser/pull/4153

**Comment by ddevault** [comment]
Would the qutebrowser fix not apply here as well? Also, if the problem lies in PyQt, report the bug to them.

**Comment by mxmilkb** [comment]
> Would the qutebrowser fix not apply here as well?

Indeed, which was why I mention it.

> Also, if the problem lies in PyQt

[It does](https://github.com/wayland-project/wayland-protocols/blob/70ed9d7ee8f6491032fcccb74f25693851d740f2/stable/xdg-shell/xdg-shell.xml#L590). I'll pass the message on.

**Comment by ddevault** [comment]
No, I mean can't the same fix that was done for qutebrowser be applied to Carla as well? And the issue doesn't lie in Qt if Qt provides a means of solving it - which qutebrowser seems to take advantage of.
