### ISSUE TITLE
swaybar tray context menu is not shown

### ISSUE THREAD

**Issue by oblique** [swaywm/sway#3939]
I'm not sure if this is a configuration issue or just not implemented but when I right-click (or middle-click) on an icon in systray, the context menu is not shown.

My swaybar config:

```
bar {
    font Hermit 13
    position top
    status_command i3status

    colors {
        background #101010
        statusline #5f87d7
        separator  #404040

        focused_workspace   #a78edb #a78edb #000000
        active_workspace    #101010 #101010 #a78edb
        inactive_workspace  #101010 #101010 #606060
        urgent_workspace    #101010 #101010 #d81860
    }
}
```

**Comment by oblique** [comment]
logs: [swaybar.log](https://github.com/swaywm/sway/files/2985383/swaybar.log)

**Comment by progandy** [comment]
The icon probably uses dbusmenu, which is not implemented yet.

In the meantime you could try [Waybar](https://github.com/Alexays/Waybar), but the menu will open somewhere in the middle of the screen.

More about the tray status in https://github.com/swaywm/sway/issues/3799
