### ISSUE TITLE
[RFE] Allow disabling warnings for missing background image

### ISSUE THREAD

**Issue by khardix** [swaywm/sway#3944]
* Sway Version: `sway version 1.0`
* Debug Log: https://gist.github.com/khardix/3e38f9f910b1d5f86823552a016e4ff2
* Relevant Part of Configuration File: https://gist.github.com/741f19123cfb49055604acb878dee2c4

I use single configuration file for two workstations. Each of these workstations has different set of outputs, and uses different background picture(s). As a result, each time I start sway, I'm nagged about pictures from the other workstation missing. These warnings are issued even when fallback background color is set.

I would like to have an option to specify that if the background image is missing and the fallback background is specified, sway should not emit a warning.

**Comment by emersion** [comment]
You can ``include ~/.config/sway/`hostname`/*`` for this.
