### ISSUE TITLE
Doesn't start when render-only GPU is plugged in

### ISSUE THREAD

**Issue by xoac** [swaywm/sway#3945]
* Sway Version:
sway version 1.0

* Debug Log:
logs when starting from tty
[pastebin](https://gist.github.com/xoac/02000b676e68e853d68663ee6227db57)

Also some info when starting sway with sddm:
```
mar 20 20:18:33 wiki-igt sddm-helper[9285]: pam_kwallet5(sddm:session): pam_kwallet5: pam_sm_open_session
mar 20 20:18:33 wiki-igt sddm-helper[9290]: pam_kwallet5: final socket path: /run/user/1000/kwallet5.socket
mar 20 20:18:33 wiki-igt sddm-helper[9285]: Starting: "/usr/share/sddm/scripts/wayland-session sway"
mar 20 20:18:33 wiki-igt sddm[627]: Session started
mar 20 20:18:34 wiki-igt kernel: sway[9292]: segfault at 28 ip 00007f51cd33ed24 sp 00007ffd0e7e34e0 error 4 in radeonsi_dri.so[7f51cd17d000+83e000]
mar 20 20:18:34 wiki-igt sddm-helper[9285]: [PAM] Closing session
mar 20 20:18:34 wiki-igt sddm-helper[9285]: pam_unix(sddm:session): session closed for user sylwek
mar 20 20:18:34 wiki-igt sddm-helper[9285]: pam_kwallet5(sddm:session): pam_kwallet5: pam_sm_close_session
mar 20 20:18:34 wiki-igt sddm-helper[9285]: pam_kwallet5(sddm:setcred): pam_kwallet5: pam_sm_setcred
mar 20 20:18:34 wiki-igt sddm-helper[9285]: [PAM] Ended.
mar 20 20:18:34 wiki-igt sddm[627]: Auth: sddm-helper exited with 11
mar 20 20:18:34 wiki-igt sddm[627]: Greeter stopping...
mar 20 20:18:34 wiki-igt sddm[627]: Socket server stopping...
mar 20 20:18:34 wiki-igt sddm[627]: Socket server stopped.
mar 20 20:18:34 wiki-igt sddm[627]: Display server stopping...
mar 20 20:18:34 wiki-igt sddm-greeter[9258]: Message received from daemon: LoginSucceeded
mar 20 20:18:34 wiki-igt sddm-greeter[9258]: The X11 connection broke (error 1). Did the X11 server die?
mar 20 20:18:34 wiki-igt systemd-logind[586]: Session c9 logged out. Waiting for processes to exit.
mar 20 20:18:34 wiki-igt sddm[627]: Display server stopped.
mar 20 20:18:34 wiki-igt sddm[627]: Running display stop script  "/usr/share/sddm/scripts/Xstop"
mar 20 20:18:34 wiki-igt sddm[627]: Removing display ":0" ...
mar 20 20:18:34 wiki-igt sddm[627]: Adding new display on vt 1 ...
mar 20 20:18:34 wiki-igt sddm[627]: Loading theme configuration from ""
mar 20 20:18:34 wiki-igt sddm[627]: Display server starting...
mar 20 20:18:34 wiki-igt sddm[627]: Running: /usr/bin/X -nolisten tcp -auth /var/run/sddm/{d96755dc-a431-40b0-949d-28e8bb87cdce} -background none -noreset -displayfd 20 -seat seat0 vt1
mar 20 20:18:34 wiki-igt sddm-helper[9256]: [PAM] Closing session
mar 20 20:18:34 wiki-igt sddm-helper[9256]: pam_unix(sddm-greeter:session): session closed for user sddm
mar 20 20:18:34 wiki-igt sddm-helper[9256]: [PAM] Ended.
```

* Configuration File:

I didn't create any config yet.

* Stack Trace, if sway crashes:
journalctl logs says there is segfault but no coredump :(
```
Wed 2019-03-20 19:05:29 CET     834   995   995   6 missing   /usr/bin/sddm-greeter
Wed 2019-03-20 19:05:29 CET     640     0     0   6 missing   /usr/lib/Xorg
Wed 2019-03-20 19:32:51 CET    2199  1000  1000   6 missing   /usr/lib/org_kde_powerdevil
Wed 2019-03-20 19:32:57 CET    2120  1000  1000  11 missing   /usr/bin/kdeinit5
Wed 2019-03-20 19:32:57 CET    2076  1000  1000  11 none      /usr/bin/kwin_wayland
Wed 2019-03-20 19:33:05 CET    2157  1000  1000  11 missing   /usr/bin/plasmashell
Wed 2019-03-20 19:35:38 CET     849   995   995   6 missing   /usr/bin/sddm-greeter
Wed 2019-03-20 19:35:38 CET     656     0     0   6 missing   /usr/lib/Xorg
Wed 2019-03-20 20:14:18 CET    9209  1000  1000  11 missing   /usr/lib/org_kde_powerdevil
Wed 2019-03-20 20:14:18 CET    1694  1000  1000   6 missing   /usr/lib/org_kde_powerdevil
Wed 2019-03-20 20:14:24 CET    1620  1000  1000  11 missing   /usr/bin/kdeinit5
Wed 2019-03-20 20:14:28 CET    1577  1000  1000  11 none      /usr/bin/kwin_wayland
Wed 2019-03-20 20:14:32 CET    1656  1000  1000  11 present   /usr/bin/plasmashell
```

I can run sway from terminal  in plasma shell sesion (also wayland). 

My drivers:
```
mhwd -l -d                                                                                                                                                                                    20:32:48 
--------------------------------------------------------------------------------
> PCI Device: /devices/pci0000:00/0000:00:1c.0/0000:01:00.0 (0380:1002:6660)
  Display controller ATI Technologies Inc Sun XT [Radeon HD 8670A/8670M/8690M / R5 M330 / M430]
--------------------------------------------------------------------------------
  > INSTALLED:

   NAME:        video-ati-hwe
   ATTACHED:    PCI
   VERSION:     2016.09.13
   INFO:        X.org ati video driver. Standard open source driver for AMD graphic cards with OpenCL, VAAPI and VDPAU support.
   PRIORITY:    2
   FREEDRIVER:  true
   DEPENDS:     -
   CONFLICTS:   video-amdgpu video-ati video-catalyst video-vesa video-amdgpu-hwe 
   CLASSIDS:    0300 0380 
   VENDORIDS:   1002 

   NAME:        video-linux
   ATTACHED:    PCI
   VERSION:     2018.05.04
   INFO:        Standard open source drivers.
   PRIORITY:    2
   FREEDRIVER:  true
   DEPENDS:     -
   CONFLICTS:   -
   CLASSIDS:    0300 0380 0302 
   VENDORIDS:   1002 8086 10de 



  > AVAILABLE:

   NAME:        video-linux
   ATTACHED:    PCI
   VERSION:     2018.05.04
   INFO:        Standard open source drivers.
   PRIORITY:    2
   FREEDRIVER:  true
   DEPENDS:     -
   CONFLICTS:   -
   CLASSIDS:    0300 0380 0302 
   VENDORIDS:   1002 8086 10de 


--------------------------------------------------------------------------------
> PCI Device: /devices/pci0000:00/0000:00:02.0 (0300:8086:1916)
  Display controller Intel Corporation HD Graphics 520
--------------------------------------------------------------------------------
  > INSTALLED:

   NAME:        video-linux
   ATTACHED:    PCI
   VERSION:     2018.05.04
   INFO:        Standard open source drivers.
   PRIORITY:    2
   FREEDRIVER:  true
   DEPENDS:     -
   CONFLICTS:   -
   CLASSIDS:    0300 0380 0302 
   VENDORIDS:   1002 8086 10de 



  > AVAILABLE:

   NAME:        video-linux
   ATTACHED:    PCI
   VERSION:     2018.05.04
   INFO:        Standard open source drivers.
   PRIORITY:    2
   FREEDRIVER:  true
   DEPENDS:     -
   CONFLICTS:   -
   CLASSIDS:    0300 0380 0302 
   VENDORIDS:   1002 8086 10de 

   NAME:        video-vesa
   ATTACHED:    PCI
   VERSION:     2017.03.12
   INFO:        X.org vesa video driver.
   PRIORITY:    0
   FREEDRIVER:  true
   DEPENDS:     -
   CONFLICTS:   -
   CLASSIDS:    0300 
   VENDORIDS:   * 
```

**Comment by schauveau** [comment]
I do not know sddm but according to your logs, it appears that it executes /usr/bin/X instead of sway. 
According to https://www.systutorials.com/docs/linux/man/5-sddm.conf the desktop files for the wayland sessions must be in /usr/share/wayland-sessions instead of /usr/share/xsessions.
That could be the problem. 

Regarding your tty issue, it seems that sway cannot handle your radeon card (/dev/dri/card1). 
You could try to set WLR_DRM_DEVICES=/dev/dri/card0 as described in https://github.com/swaywm/sway/wiki

**Comment by RedSoxFan** [comment]
So first off, we don't support display managers so any issues with SDDM is going to be ignored.

However, you did provide a debug log when running from the tty so that is valid. Since you are using the radeon driver, it is probably too old to support the required EGL features needed. If the amdgpu driver is supported for your card, I would suggest trying that.

Depending on the configuration of the connectors/outputs for the two cards, you can try using `env WLR_DRM_DEVICES=/dev/dri/card0 sway` like schauveau suggested, which will only use the intel graphics

**Comment by ascent12** [comment]
>Since you are using the radeon driver, it is probably too old to support the required EGL features needed

For the record, we do support the radeon driver and try to target any hardware going as far back as 2010 or so. However, I cannot say for certainty how older drivers are going to hold up in multi-gpu situations.

**Comment by RedSoxFan** [comment]
> > Since you are using the radeon driver, it is probably too old to support the required EGL features needed
> 
> For the record, we do support the radeon driver and try to target any hardware going as far back as 2010 or so. However, I cannot say for certainty how older drivers are going to hold up in multi-gpu situations.

For the record, I was just basing that comment off of https://github.com/swaywm/sway/issues/2766#issuecomment-427515479

**Comment by ascent12** [comment]
Looking at that log, it appears that it's not really an issue with EGL; it supports what's needed.
However, the device is render-only (`[wlroots-0.5.0/backend/drm/drm.c:179] Found 0 DRM CRTCs`) which isn't something we probably aren't handing gracefully. `WLR_DRM_DEVICES=/dev/dri/card0` is definitely the workaround here.

**Comment by xoac** [comment]
I can run sway with `WLR_DRM_DEVICES=/dev/dri/card0`.

Is this issue resolved or it's bug I need to specify it manually?

**Comment by emersion** [comment]
>However, the device is render-only ([wlroots-0.5.0/backend/drm/drm.c:179] Found 0 DRM CRTCs) which isn't something we probably aren't handing gracefully.

We should probably ignore such GPUs.

**Comment by Philz69** [comment]
> > However, the device is render-only ([wlroots-0.5.0/backend/drm/drm.c:179] Found 0 DRM CRTCs) which isn't something we probably aren't handing gracefully.
> 
> We should probably ignore such GPUs.

Shouldn't this be false? ( in /backend/drm/drm.c )
`181 drm->num_crtcs = res->count_crtcs;
182     if (drm->num_crtcs == 0) {
183         drmModeFreeResources(res);
184        return **true**;
185      }
'
In turn, it would cause  ( in backend/drm/backend.c )
`191 if (!init_drm_resources(drm)) {
192         goto error_event;
193     }
`
to execute and would prevent the crash by simply continuing to the next DRM device?

If this make any sense i'll commit the changes and have @xoac test them!

**Comment by ascent12** [comment]
I honestly thought we were already doing such a check inside of https://github.com/swaywm/wlroots/blob/master/backend/session/session.c#L228-L250, meaning we wouldn't even try to initialise the DRM at all.
Maybe that code was removed or I'm confusing it with the weston function I based that off of.

**Comment by Philz69** [comment]
That code is still present and is executed. 

I might be wrong but in this particular case i do not see why it would fail any of the checks.
I have limited understand of drm / kms, maybe I should let someone else handle this.

**Comment by gorsheninmv** [comment]
> Looking at that log, it appears that it's not really an issue with EGL; it supports what's needed.
> However, the device is render-only (`[wlroots-0.5.0/backend/drm/drm.c:179] Found 0 DRM CRTCs`) which isn't something we probably aren't handing gracefully. `WLR_DRM_DEVICES=/dev/dri/card0` is definitely the workaround here.

Sorry, but can you understand what`s the render-only device? I have similar problem trying to use AMD card as a primary one (WLR_DRM_DEVICES=/dev/dri/card1 sway). How can I force my laptop to use the AMD card?

**Comment by emersion** [comment]
A render-only GPU doesn't have any connectors. It means you can't directly connect any output to it.

**Comment by Philz69** [comment]
Is there ever a scenario where we should initialize a render-only GPU?

**Comment by emersion** [comment]
One could want to force compositing on a render-only GPU. It's generally not a good idea.

**Comment by xoac** [comment]
I wasn't using sway for a while. And today I have checked the version 1.4 and the bug is still there.

**Comment by emersion** [comment]
wlroots ignores render-only devices now.
