### ISSUE TITLE
Changing screen brightness for OLED displays

### ISSUE THREAD

**Issue by mherzberg** [swaywm/sway#3950]
Is there any way to change the screen brightness for OLED displays? Using `/sys/class/backlight` does not work with OLEDs, since they do not have any backlight. Under X, I was using xrandr --output eDP1 --brightness <new_brightness_level>, which does not work anymore. It seems it must now be handled by the Wayland compositor.

**Comment by merildev** [comment]
https://github.com/swaywm/sway/wiki/i3-Migration-Guide

Use `light` or `brightnessctl`.

**Comment by mherzberg** [comment]
Thank you for your answer. Since tools like `light` and `brightnessctl` all rely on `/sys/class/backlight`, they do unfortunately not work.

`icc-brightness` looks interesting, but I was unfortunately not able to get it to work on my machine. I was hoping to find a more lightweight and sway-native solution, but it seems there are currently no plans for that. Thanks again.

**Comment by cafehaine** [comment]
since it's OLED you could rely on changing the gamma ramps to achieve the same effect as lowering the 'backlight'. For this you could use one of the redshift forks supporting wayland

**Comment by emersion** [comment]
FWIW the wlroots gamma example supports setting brightness:

https://github.com/swaywm/wlroots/blob/master/examples/gamma-control.c#L144

**Comment by yakthungba** [comment]
[ddcutil](https://github.com/rockowitz/ddcutil) is what you're looking for.

**Comment by georgerabus** [comment]
> [ddcutil](https://github.com/rockowitz/ddcutil) is what you're looking for.

using ddctuil doesn't work on laptops apparently

```
$ ddcutil detect
Invalid display
   I2C bus:  /dev/i2c-9
   DRM connector:           card1-eDP-1
   EDID synopsis:
      Mfg id:               SDC - UNK
      Model:
      Product code:         16737  (0x4161)
      Serial number:
      Binary serial number: 0 (0x00000000)
      Manufacture year:     2020,  Week: 46
   This is a laptop display.  Laptop displays do not support DDC/CI
```
