### ISSUE TITLE
[Feature request]  Support workspace renaming during swaymsg exec handling

### ISSUE THREAD

**Issue by mliszcz** [swaywm/sway#3952]
I have a script that issues `rename workspace number <x> to '<x>:  <app_id or class>'` command upon every focus change event. It does not work well if workspace is renamed during `exec` handling (e.g. some launcher calls `swaymsg exec ...` and then exits immediately causing a focus change).

Simplest scenario that reproduces the issue:
1. In workspace "1" in terminal window type: `swaymsg exec app; swaymsg rename workspace number 1 to '1: new'`

Expected result: There is one workspace ("1: new") with two windows (terminal + app).
Actual result: There are two workspaces: "1: new" with terminal, "1" with app.

Following change in `root_workspace_for_pid` in `sway/tree/root.c` fixes the issue:
```diff
        if (pw && pw->workspace) {
                ws = workspace_by_name(pw->workspace);
+               if (!ws) {
+                   ws = workspace_by_number(pw->workspace);
+               }

                if (!ws) {
                        sway_log(SWAY_DEBUG,
                                        "Creating workspace %s for pid %d because it disappeared",                                                                           
                                        pw->workspace, pid);
                        ws = workspace_create(pw->output, pw->workspace);
                }
```

My question is: would it be possible to support described scenario? I can send a PR if you are ok with the solution proposed above.

**Comment by RedSoxFan** [comment]
SGTM. Can you submit your proposed diff as a PR?

**Comment by mliszcz** [comment]
Hi,

I've opened a PR (#3959), however after thinking a little more about this I'm not convinced that this is the right approach. The fix does not address a scenario where workspace changes number during rename.

In i3 following scenario always yields the same result (regardless which command completes first):

```
{ i3-msg exec chromium & } ; { i3-msg rename workspace 2 to 1 & }
```

So either `exec` is atomic or they track the the workspace by some unique id instead of a name.

Anyway, @RedSoxFan could you please help to review the PR?
