### ISSUE TITLE
xkb_options do not apply in xwayland

### ISSUE THREAD

**Issue by yorickvP** [swaywm/sway#3955]
* Sway Version: cdcc2a5bb52a34865eee2ec3d09a38b047c08ffd

* Debug Log: https://pub.yori.cc/sway-xkb.log

* Configuration File: https://pub.yori.cc/i3_config

I have `xkb_options caps:escape` in my sway config. This works for wayland clients, but capslock is still capslock in Xwayland clients. setxkbmap also does not show this option.

**Comment by ForTheReallys** [comment]
I'm not in front of my computer right now so this is just a wild guess: do you have that same option set for your x server as well? Maybe caps and escape get swapped after sway swaps them?

**Comment by ForTheReallys** [comment]
Try running `sway reload`.

**Comment by RedSoxFan** [comment]
Can you still replicate this? It appears to be working fine for me

**Comment by yorickvP** [comment]
nope, still broken in f5d1c27226a74a234664af9b35ab226a67386e8e

**Comment by emersion** [comment]
Can you try `input * xkb_options caps:escape` instead of specifying the identifier? It doesn't seem like the input settings get applied to any device.
