### ISSUE TITLE
[feature-request] Allowing to (optionnally) use CRITERIA as a *find/search* that fails if it turned out empty, instead of a never-failing *filter*

### ISSUE THREAD

**Issue by Tormen** [swaywm/sway#3961]
* Sway Version: v1.0

It just feels wrong to have to do:
`bindsym $mod+a exec swaymsg -t get_tree|jq '..|if .focused? //empty then .app_id? else null end'|grep -q "keepassxc" && swaymsg '[app_id="keepassxc" con_id="__focused__"] move to scratchpad' || swaymsg '[app_id="keepassxc"] move window to workspace current, focus'`

Instead of being able to do something like this: 
`bindsym $mod+a exec swaymsg '[app_id="keepassxc" con_id="__focused__"] move to scratchpad' 
|| swaymsg '[app_id="keepassxc"] move window to workspace current, focus')`

Because:
  * it forces you to have to filter *twice*: Once to satisfy the `if condition` and then `swaymsg` is doing it again just to know which window to move :((

  * plus its not *atomic* anymore and can thus fail ugly if the window looses focus between the if-condition is evaluated and the swaymsg move to scratchpad is executed!

----------

I know that the CRITERIA from `man 5 sway` are a FILTER. And thus should not fail.
But I still think giving the sway user the option to convert the FILTER into a SEARCH/FIND that actually /can/ fail, would be a great feature to swaywm.
For instance like this:
 * a CRITERIA is a (never failing) FILTER when wrapped into `[ ]` 
 * a CRITERIA is a (failing if nothing was found) SEARCH/FIND when wrapped into `{ }`

Like this sway would stay backwards compatible and the `man 5 sway` page would not have to be changed except for the CRITERIA section at the end! :)

---------

Or can someone think of (a) a more elegant solution or (b) a solution that would be atomic and thus could not miss its purpose (fail) ?

**Comment by Tormen** [comment]
Especially for the `bindsym` command the fact that CRITERIA can 'fail' are really neat:

Because then you /consciously/ want to achieve something. In which case it can also make sense to have an `assign` fail if the CRITERIA does not match. Same goes for all CRITERIA dependend commands from `man 5 sway`.

**Comment by ddevault** [comment]
Changing this behavior is not acceptable, because it'd be a breaking change and a deviation from i3 behavior. I'm not terribly excited about adding an option, either, as it would add unnecessary complexity and fishing that information through is non-trivial.
