### ISSUE TITLE
Discussion of README translations.

### ISSUE THREAD

**Issue by c-edw** [swaywm/sway#3965]
I alluded to this in https://github.com/swaywm/sway/pull/3922#issuecomment-473652064.

Some translations of the README are outdated and still reference wlc, others are pretty much 1:1 with the English version. I think if you're monolingual in one of these languages with an outdated README, the outdated translations might just end up misleading you.

It's excellent that there are so many translations available, but keeping them maintained is difficult. There's also the question of how often these translations are used.

I guess this is kind of an RFC about what/if we can do anything about this.

**Comment by ddevault** [comment]
We should probably just remove the outdated translations.

**Comment by emersion** [comment]
On other thing we could do is somehow ping maintainers on a README change. Or offer a way to subscribe to README changes.

**Comment by emersion** [comment]
Ah, the latter seems to be possible (though undocumented): https://github.com/swaywm/sway/commits/master/README.md.atom

**Comment by c-edw** [comment]
One other idea I had would be to split off the language-independent parts such as the dependencies into a separate file (`DEPENDENCIES.md`?). This would reduce friction when they need to be updated and ensure everybody is getting the required stuff.
