### ISSUE TITLE
screen flicker when using floating windows

### ISSUE THREAD

**Issue by rumpelsepp** [swaywm/sway#3970]
$ swaymsg -t get_version
    sway version 1.0

I use a terminal emulator as a floating window as an application starter. I have recorded a video of the problem: https://files.rumpelsepp.org/recording.mp4

I use a trivial rule like this ` for_window [title="^launcher$"] floating enable` and I set the window title of the terminal emulator (`kitty`) via a commandline flag. If you need more information, let me know.

**Comment by passbe** [comment]
Had the exact same issue you are describing. However when I switched away from kitty to termite the issue did not appear. Can you confirm this?

**Comment by rumpelsepp** [comment]
Ah jo. Seems you are right. The same flicker is sometimes triggered when I use `wl-paste`.

**Comment by rumpelsepp** [comment]
It might be related to this one: https://github.com/kovidgoyal/kitty/issues/1482

**Comment by rumpelsepp** [comment]
I think the component which flickers is kitty and not sway.
