### ISSUE TITLE
[Enhancement] Revoke key or mouse button binding

### ISSUE THREAD

**Issue by GSF1200S** [swaywm/sway#3971]
This is an issue/idea I originally thought related to button mapping and thus was inserted as a comment in another issue. My issue is exclusively with mouse bindings, and it seemed possible using "seat" but I have not had any luck. Nonetheless, it applies to keyboard bindings as well. Is it possible to have Sway revoke or abandon a bindsym?

Use case: if I don't bind button8 or button9 at all in the config, applications like nemo correctly process them as "back" and "forward" buttons. If I do create a binding in the config (or with swaymsg 'bindsym <blah blah>' while running) like:
`bindsym --whole-window button8 exec virsh send-key Arch KEY_LEFTALT KEY_LEFT`

`bindsym --whole-window button9 exec virsh send-key Arch KEY_LEFTALT KEY_RIGHT`
It works exactly as it should- pressing button8 and button9 executes the respective virsh command and virsh sends the keys to my VM. Of course now nemo isn't going to see button8 or button9 since Sway is executing the virsh commands. I can't seem to get button8 and button9 to unmap- I can bindsym them to a different command, but they will not be recognized by nemo again unless I exit sway and start again (again with no bindsym commands for button8 or button9 in the config). xev doesn't even register them being pushed, though libinput events does.

I tried playing with seat - cursor like:
`swaymsg 'bindsym --input-device=blahblah --whole-window button8 seat - cursor press button8`

`...etc`
but that doesn't seem to set it back to how it would be if I hadn't bindsym'd button8 or button9 at all.

Im not experiencing a crash and the corresponding entries in the config (in the case where they are bound upon Sway's start) are listed above, so I don't think I need a Sway log or config post. I am running Sway version 1.0 from the Arch Community repo, but I can move to the latest git of wlroots or sway for testing, troubleshooting, etc. If a log or config is required, I'll be happy to upload them...

**Comment by schauveau** [comment]
I add a quick look in the source code of sway and I came to the conclusion that revoking a specific binding is probably not possible in the current version. The only place where bindings are cleared is during shutdown or while reloading the config. So `swaymsg reload` is probably a better workaround than exit and restart.
Also, if your VM is in a X11 window then you may want to have a look to X11 tools such as xbindkeys.

**Comment by RedSoxFan** [comment]
>  I came to the conclusion that revoking a specific binding is probably not possible in the current version

This is a feature request after all and a trivial one at that. All that needs to happen is search for a binding matching the given keys/buttons/modifiers/flags (which is already done to check for overriding) and remove it from the list, if found.
