### ISSUE TITLE
Feature request: window back and forth focus

### ISSUE THREAD

**Issue by tardypad** [swaywm/sway#3974]
Similarly to the `workspace back_and_forth` command a `focus back_and_forth` command would be quite handy to keep switching focus between 2 windows

There was such a feature request for i3 https://github.com/i3/i3/issues/838.
From what I gathered, it was rejected because it would add some unnecessary complexity within the source code and the feature could "easily" be done using IPC.

I thought that maybe this feature would be simpler to add within sway source code and could then be considered for inclusion.

**Comment by norcalli** [comment]
I have a systemd process which keeps track of the window ordering and puts it into redis and then a separate script which reads from redis to pick the last focused window. It works very well, but as someone who has implemented this feature fully using IPC, it's easy, but not trivial. The current version is written in Lua, but I can post the first shell version later if you want a solution in the interim.

**Comment by tardypad** [comment]
Thanks but I don't really want to introduce such a complexity in my system just to have this feature :p
That's why I'm asking for this feature to be directly integrated within Sway.

I have read few posts here and there of people hacking it around for i3, I'd like to avoid those if possible.
It seems to be a functionality that I'd expect to be "simple enough" to implement on a window manager side

**Comment by ddevault** [comment]
Rejecting this for the same reasons i3 did. You should try to convince i3 first - we aren't a second chance for rejected i3 features.

**Comment by tardypad** [comment]
I do believe there should be a second chance for such features rejected by i3.
Some could have been rejected because too complex given the i3 source code or given some other reasons related to X, just to name a couple. Those reasons could be gone in Sway and Wayland and it would be worth reconsidering them.

The way I see it, from an user perspective, having a "workspace back and forth" feature but not a "window back and forth" one is a sort of inconsistency.
The "workspace back and forth" was added even though it's probably as "simple" to implement it using IPC as it is to do it for the window one. Maybe the workspace feature was trivial to implement in the core in contrary to the window one. I'd find this acceptable as a reason to have only one of the two.

I was mainly just wondering if this is really still the case in sway itself

**Comment by ddevault** [comment]
>I do believe there should be a second chance for such features rejected by i3.

Well, I disagree.
