### ISSUE TITLE
Feature request: provide setenv command

### ISSUE THREAD

**Issue by schauveau** [swaywm/sway#3976]
My proposal is to add the ability to customize the environment variables used by all future exec commands. That would typically be done by a `setenv` command.
Some X11 window managers provide that feature (e.g. SetEnv in fvwm,  DBUS  org.gnome.SessionManager.Setenv on Gnome, ...) and for those that do not, the same effect can usually be achieved by restarting the WM typically with a --replace option. 
The goal is of course to change the environment of future applications without having to restart Sway. 
A non-exhaustive list of uses cases is:
- change the default locale (e.g. LANG, LANGUAGE, LC_*)
- start or restart daemons that store their status in environment variables (e.g. ssh-agent, pgp-agent, dbus, ....).  That use case is probably the most interesting.
- enable or disable the use of alternative versions of applications compiled in /opt/ by changing PATH, LD_LIBRARY_PATH, ...
- set or unset variables used to choose between X11 or Wayland backends (e.g. SDL_VIDEODRIVER, GDK_BACKEND, ...)

**Comment by RedSoxFan** [comment]
Prior art #704 (from 2016)

**Comment by ddevault** [comment]
I'm still not really a fan of this feature.

**Comment by emersion** [comment]
I'm not a fan either.

i3 discussion about this: https://github.com/i3/i3/pull/1801

**Comment by akvadrako** [comment]
It would be nice to have this. I can't set my some environmental variables until after sway starts because they depend on the composter running. So it basically means I need to change all `exec` lines to `exec wrapper.sh`. It works but it isn't convenient.

**Comment by m01** [comment]
So technically I don't think this feature is necessary, but some feature that allows configuring environment variables for child processes would definitely be convenient. I also respect your choice on which features to merge/implement and which use-cases to support (e.g. re: login managers) :slightly_smiling_face:.

In the hope that this is useful for the community:

Observe that `sway` only launches programs via keyboard shortcuts or `exec`, and in both cases I believe it uses `sh` as a wrapper.

This means that you can do the following:

```
set $menu "swaymsg exec -- 'XDG_CURRENT_DESKTOP=sway ECORE_EVAS_ENGINE=wayland_egl ELM_DISPLAY=wl ELM_ACCEL=gl MOZ_ENABLE_WAYLAND=1 <launcher binary>'"
bindsym $mod+d exec $menu
# or, for things that are just launched in the background rather than in response to a user command
exec FOO=abc BAR=baz <some-binary>
```

I today discovered that this method was actually [suggested](https://github.com/i3/i3/pull/1801#issuecomment-122601849) for i3 back in 2015.

Something like `eval $(ssh-agent -c)` is trickier, but also possible. `sway` is awesome, and it gives you good tools that you can compose to meet your needs. I'll leave this as an exercise for the reader.

This solves problems like:
- You want to use the real `sway` binary, and not a wrapper script, for whatever reason, and/or
- You need to set a _window-manager specific_ environment variable, like `XDG_CURRENT_DESKTOP=sway` for https://github.com/emersion/xdg-desktop-portal-wlr, and none of the options at https://github.com/emersion/xdg-desktop-portal-wlr/wiki/systemd-user-services,-pam,-and-environment-variables or https://wiki.archlinux.org/index.php/Systemd/User#Environment_variables work for you. Unlike ~/.xinitrc (& ~/.xsession?), I don't believe `~/.pam_environment` supports conditional logic, which makes it difficult to switch between sway and say an X11 window manager that you might have to use occasionally.

It would be nice if the above at least continued to work, despite it being ugly :slightly_smiling_face:. In any case, thanks a lot for `sway`!

**Comment by tmccombs** [comment]
The absence of this feature basically necessitates the use of a wrapper script.  And that in turn complicates using sway with a display manager. 

Besides the already mentioned `XDG_CURRENT_DESKTOP` environment variable, this would also be useful for environment variables that should be set if using wayland, for example SDL_VIDEODRIVER, etc.

**Comment by schauveau** [comment]
@tmccombs I do not know how standard that is but LightDM on Debian is calling `/etc/X11/Xsession` and the only difference with an actual X11 session is that it sets `XDG_SESSION_TYPE=wayland`. In practice, that means that `ssh-agent`, `dbus` and other services that install a script in ` /etc/X11/Xsession.d/` work out of the box since they can customize the `STARTUP` command and the environment.  The user script `~/.xsessionrc` is also executed and can be used to customize the environment:

LightDM sets `XDG_SESSION_TYPE` but not `XDG_CURRENT_DESKTOP`. There is `DESKTOP_SESSION` so my 
 `~/.xsessionrc` contains something like that 

```
if [ "$XDG_SESSION_TYPE" = "wayland" ] ; then
   # Set the wayland environment here
   export GDK_BACKEND="wayland,x11"
   export QT_QPA_PLATFORM="wayland"
   ... 
   if [ "$DESKTOP_SESSION" = "sway" ] ; then
      export XDG_CURRENT_DESKTOP="sway"
   fi
fi
```
