### ISSUE TITLE
[feature-request] per window bindsym

### ISSUE THREAD

**Issue by joshuarubin** [swaywm/sway#3983]
I'd like to change some keyboard bindings depending on the focused window.
It seems like there might be a way that I just can't figure out
Maybe by using `for_window` with some criteria including `__focused__` and setting a mode. But then I'd also need a way to match all _other_ windows to change back to the default mode.

Any help would be greatly appreciated!

**Comment by ddevault** [comment]
You could do your mode idea with a script daemon that keeps an eye on which window is focused and updates the mode accordingly? A first-class feature will have to wait until i3 adds something like that - you can ask them if you'd like.
