### ISSUE TITLE
xclip over ssh doesn't work until primary set from a local X application

### ISSUE THREAD

**Issue by khughitt** [swaywm/sway#3984]
## Overview

I've been trying to get `PRIMARY` to sync over SSH so that I can do simple things like yank text in a remote (Neo)vim session and paste it into a local editor.

This works in my previous Awesome/X11 setup, but behaves less consistently in Sway/Wayland.

Pasting from remote primary selection seemed to work sometimes and not others, and for the longest time I couldn't figure out why. I finally made some progress and can now at least reproduce the issue.

## To reproduce

1. SSH into remote machine with xclip installed
2. Copy text to PRIMARY using xclip, e.g. `date | xclip`
3. Attempt to paste (shift-insert) into a second local terminal
4. Nothing happens (most of the time...  sometimes this works off the bat)
5. Switch focus to a local X app (e.g. chromium) and select some text with the mouse to copy it to PRIMARY
6. Switch back to SSH session and repeat xclip command
7. Text can now be pasted into local terminal

Here is where it gets even stranger, and this may be an issue for [Neovim](https://github.com/neovim/neovim), but since it relates to the above, I'm including it here for now...

8. Open a neovim session (`:checkhealth` detects xclip as clipboard tool)
9. Yank some text (`set clipboard=unnamed` specified in init.vim to have yanked text go to PRIMARY)
10. Paste text into local terminal (WORKS)
11. Repeat with different text (No longer works!)
12. At this point, xclip is also broken until I copy some text to primary in a local X application again.
13. I can repeat this process and each time yanking / pasting from primary works the first time, and then breaks.

## System Info 

**Local**:

- Arch Linux 64-bit (Linux 5.0.3)
- sway-git (1.0-rc1-202-g3a31889d (Mar 27 2019, branch 'master'))
- wlroots-git (2019/03/27 0.5.0.r11.g17f68873-1)
- termite v14

**Remote**:

- Arch Linux 64-bit (Linux 5.0.3)
- xclip 0.13
- $TERM = xterm-termite
- Neovim v0.3.2-1032-gccb005b9e

**Comment by emersion** [comment]
xclip is an X11 tool and won't work in Wayland. Use wl-clipboard instead.

**Comment by progandy** [comment]
that sounds like some hack with X-Forwarding. 

You might be able to do something similar to this macos sample. https://gist.github.com/burke/5960455

Some helpful hints: systemd services for ```wl-clipboard``` with socket activation, ```Accept=true``` and ```StandardInput=socket```.

**Comment by khughitt** [comment]
Thanks for the suggestions! I do use wl-clipboard on the local side where I'm running sway, but there is no Wayland server for it to interact with on the remote side.

**Comment by bahaaza** [comment]
Sorry for pumping this old issue, but I am having similar issue, I have a server running on X11, I am working with vim on the server, the primary clipboard doesn't work unless I copy something to primary clipboard from a Xwayland window running on my computer, and if I copy to primary from a Wayland window the issue returns this is super annoying!, I have tried gnome wayland session and this issue doesn't happen there at all.

Is there a solution for this issue, without using a terminal under Xwayland?
