### ISSUE TITLE
Disable ptrace by default

### ISSUE THREAD

**Issue by schauveau** [swaywm/sway#3987]
I am running sway from git master on a Debian/Buster machine so with systemd and not suid-root. 

I noticed that the sway process does not disallow ptrace by default. I feel that this is a serious security issue since keyloggers are trivial to implement by *ptracing* the read() calls on /dev/input/event? devices. 

Wouldn't it make sense to call `prctl(PR_SET_DUMPABLE, 0)` at startup and maybe to add a command line (or build) option to allow developers to make coredump and to debug?

**Comment by emersion** [comment]
Keyloggers can override your $PATH and make you run a rogue version of sway anyway.

The better solution is to run untrusted clients in sandboxes, be it Flatpak or another mechanism.

**Comment by schauveau** [comment]
Of course but is that a reason to make their life easy?

**Comment by emersion** [comment]
You could argue all applications should disable ptrace. In which case *you* should disable ptrace locally.

It's not about making keyloggers' life easy. It's about not making us feel like we're secure with a half-baked "solution", and think about a real solution instead.

In other words, securing the compositor against processes running as the current user in the same namespace is not going to work no matter what you do. It's not worth it to try to do it.

**Comment by schauveau** [comment]
You are probably right and on second though a proper sway keylogger could have some practical uses like for instance debugging input issues. That should make a nice small github project.

**Comment by schauveau** [comment]
In case someone would have a use for it: https://github.com/schauveau/sway-keylogger

**Comment by Emantor** [comment]
FWIW, there is also [ptrace scope](https://www.kernel.org/doc/Documentation/security/Yama.txt)

**Comment by emersion** [comment]
>So, protecting a compositor against a trivial attack is pointless. It is a bit like locking your house which is stupid because burglars can easily break your doors and windows.

This is quite ridiculous. It seems you haven't understood at all the problem.

Now are you going to ask Firefox to disable ptrace? Because this is clearly where people are going to type in their credit card numbers and account passwords.

Next should we unset `$PATH` for better security? (We used to unset `$LD_PRELOAD` and `$LD_LIBRARY_PATH` in the past, it's quite similar)

Now come on, instead of spreading FUD please try to help with an actual solution.

**Comment by emersion** [comment]
>That other keylogger intercepts the communications between the compositor and a wayland client using the LD_PRELOAD trick and it can only be applied to new applications. My approach is different since it directly observes the communications between the compositor and the Linux kernel.

Oh, btw, you could just have used a `LD_PRELOAD` lib overriding libinput/wlroots functions, that would've worked too

**Comment by schauveau** [comment]
@Emantor  Thanks. I will reference ptrace_scope
 
@emersion Ridiculous? ... maybe. FUD? not really. FUN? Yeah! Clearly.
