### ISSUE TITLE
GTK Applications Fail to Launch without Xwayland

### ISSUE THREAD

**Issue by carloabelli** [swaywm/sway#3989]
* Sway Version: `sway version 1.0`
* Debug Log: https://pastebin.com/rcUnfhTt

1. Launch sway without xwayland installed
2. Attempt to launch a GTK3 application e.g. gtk3-demo using the wayland backend
3. The application does not appear, but also does not exit

This issue does not occur for QT or other applications such as Alacritty.

On weston the applications launch normally.

Installing xwayland fixes the issue even though GTK is using the wayland backend.

**Comment by louis-irl** [comment]
Hm, that's odd.  I'm running GTK applications without Xwayland fine.  Have you disabled xwayland in your config file?

**Comment by emersion** [comment]
You need to disable Xwayland in your config file.

```
[wlroots-0.5.0/xwayland/xwayland.c:110] failed to exec Xwayland: No such file or directory
```

**Comment by elongl** [comment]
How?

**Comment by cafehaine** [comment]
It’s in the man page of sway (5): https://github.com/swaywm/sway/blob/8ee054b1b95b7466c0dd89bfc9026f4083fb0016/sway/sway.5.scd#L88

**Comment by elongl** [comment]
Thanks! I don’t get that error anymore, however I’m still getting “Can’t open display” when I try to dmenu or urxvt. Any idea why?

**Comment by cafehaine** [comment]
Because without Xwayland you cannot start any X11 apps, including dmenu or urxvt. You either need to install xwayland, or find alternatives to those apps.
