### ISSUE TITLE
Workspace names should support Pango markup

### ISSUE THREAD

**Issue by somini** [swaywm/sway#3993]
This is similar to #2217, #589, but for workspace names on swaybar.

* Sway Version: 1.0

* Configuration File:

```
set $w1 "1:<b>W1</b>"
```

This should render as "1:**W1**"

**Comment by RedSoxFan** [comment]
Set `pango_markup enabled` in your bar config

**Comment by somini** [comment]
Can confirm, it was on the "sway-bar(5)" manpage even. Thanks.
