### ISSUE TITLE
GTK "open file" prompts taller than their output

### ISSUE THREAD

**Issue by kennylevinsen** [swaywm/sway#4000]
## Sway version:

AUR sway-git, sway version 1.0-rc1-206-gdd28e6a6 (Mar 31 2019, branch 'master')

## Debug log

[debuglog.txt](https://github.com/swaywm/sway/files/3026534/debuglog.txt)

## Configuration file

[config.txt](https://github.com/swaywm/sway/files/3026535/config.txt)

## Issue

GTK "open file" prompts always open taller than the output they're on.

## Reproduction steps

- Open a GTK app
- Open a file picker (ctrl + o)
- Observe file picker position/size

## Tested applications:

- Wayland: Firefox 66, Firefox Nightly, Sublime Text 3 all create a floating window with CSD 75% above the output edge (i.e. only the last row of pixels form the text is visible), bottom edge of window is at bottom edge of output.
- XWayland: Firefox 66, same as wayland, sway border title is 75% above output edge (i.e. only the last row of pixels form the text is visible), however, bottom is slightly *above* output edge.

While other popups work fine, such as the Firefox print popup, I do not believe I have seen any file picker that did not exhibit this issue on my system.

**Comment by kennylevinsen** [comment]
Hmm, seems to not occur after restart of sway, making reproduction a bit trickier.

It does, however, occur for me quite often.

**Comment by FreeFull** [comment]
I've hit this issue in the past too. I think GTK save dialogs actually remember how big they were the previous time, so if you resize it to be smaller that might stick.

**Comment by kennylevinsen** [comment]
Yes, that appears to be the case. In fact, if I open two "Open file" popups in different applications (even xwayland and wayland), resizing popup A and then focusing popup B makes popup B take on the new size of A.

So I suppose the issue is the initial size. I wonder if the information resets after a while.

**Comment by FreeFull** [comment]
I think I also recall hitting this issue with Xorg and i3, so I'm not sure if sway is at fault at all.

**Comment by RedSoxFan** [comment]
This is a GTK issue - https://gitlab.gnome.org/GNOME/gtk/issues/771
