### ISSUE TITLE
Sway "soft-crash" after resume

### ISSUE THREAD

**Issue by kennylevinsen** [swaywm/sway#4001]
# Sway version

sway version 1.0-rc1-206-gdd28e6a6 (Mar 31 2019, branch 'master')

# Debug log

[swaycrash-cut.txt](https://github.com/swaywm/sway/files/3027117/swaycrash-cut.txt)

# Configuration File:

[config.txt](https://github.com/swaywm/sway/files/3027118/config.txt)

# Problem

After resume, sway "soft-crashed" by wiping all workspaces, leaving them grey with nothing on them (with exception a screen that wasn't registered until after the crash) until sway was reloaded.

However, afterwards, I am now left in a weird state where two of my screens duplicate a cursor (one of the screens that crashed, the other one being the one that didn't initialize until afterwards). Despite the screens both showing a cursor, click events only go to one which workspace is active (except sometimes where it refuses to follow).

Odd.

**Comment by RedSoxFan** [comment]
> After resume, sway "soft-crashed" by wiping all workspaces, leaving them grey with nothing on them (with exception a screen that wasn't registered until after the crash) until sway was reloaded.

I think that would be #3625

> However, afterwards, I am now left in a weird state where two of my screens duplicate a cursor

It looks like both DP-1 and DP-2 are matching the output config `Goldstar Company Ltd LG Ultra HD 0x00003200` after resume and are being placed in the same location

**Comment by kennylevinsen** [comment]
> It looks like both DP-1 and DP-2 are matching the output config Goldstar Company Ltd LG Ultra HD 0x00003200 after resume and are being placed in the same location

Ugh, that does indeed seem to be the case. I also now notice a bad link error on DP-1, which is part of my repeating issues with that setup...

**Comment by RedSoxFan** [comment]
Closing since the first part already has a separate issue (#3625) and I don't there is anything we can do for the second.
