### ISSUE TITLE
Multihead monitor above

### ISSUE THREAD

**Issue by caasihaon** [swaywm/sway#4002]
There seems to be an issue with some applications not being clickable (keyboard works) when multihead settings consist of laptop screen and monitor that is positioned above the laptop screen. **Please note, this does not affect default sway config**.

I am on fully upgraded Arch Linux.
Some unlikable applications would include:
- Google chrome stable  Version 73.0.3683.86 (Official Build) (64-bit)
- PCManFM
but these applications are clickable:
- Gedit
- Nautilus

Steps to reproduce:
Launch any above mentioned not clickable application on default workspace and move to worksapce on external monitor positioned above.
Please note, when the application is back on the main workspace it becomes clickable again.

**Sway version:** sway version 1.0
[sway-log](https://gist.github.com/caasihaon/fa26307b81e06135bb8da7510c130c74)
[sway config](https://gist.github.com/caasihaon/934e03f5c56b38d3e6583a4cb100b8a4)

Please note. For positioning the monitor above I have not found any docs so I tried with `-1080` which positions everything correctly

**Comment by ascent12** [comment]
This is an known Xwayland issue. It doesn't handle negative coordinates well, and things will be unclickable.
Change your config so that everything appears as positive coordinates, and it should work fine.

**Comment by caasihaon** [comment]
cheers for a quick response, as you suggested issue is resolved by making values positive. If anyone will face similar issue, here are the relevant sway configs that need changing:
```
output eDP-1 pos 0 0 res 1920x1080
output HDMI-A-2 pos 0 -1080 res 1920x1080
```
replace to
```
output HDMI-A-2 pos 0 0 res 1920x1080
output eDP-1 pos 0 1080 res 1920x1080
```
