### ISSUE TITLE
Output priority (when enabled outputs is more than supported)

### ISSUE THREAD

**Issue by oarmstrong** [swaywm/sway#4010]
I have a laptop as well as a dock with 3 external displays connected to it. Due to the fact that my graphics card only supports 3 displays, I have to disable the internal display when I dock for the third external display to work.

Is it possible for sway to support some method of priority on the configured outputs so that it can do this automatically?

```
~> swaymsg -t get_version
sway version 1.0
```

The only output configuration I have is to set the positions of the external monitors.

```
output DP-4 {
        pos 0 0
}

output DP-3 {
        pos 1920 0
}

output DP-5 {
        pos 3840 0
}
```

Whenever I dock, DP-4 and DP-3 activate correctly, but I have to run the command `swaymsg output eDP-1 disable` to disable the internal display and after that DP-5 pops into life.

Hopefully this is clear. It would be really neat if sway could support this, but if not then I'd really appreciate any pointers to a workaround that may help me. Cheers.

**Comment by RedSoxFan** [comment]
You might want to check out https://github.com/emersion/kanshi

**Comment by oarmstrong** [comment]
@RedSoxFan That looks very promising, thanks. I'll take a look and if that fits my needs I'll close this issue off.

**Comment by oarmstrong** [comment]
Apologies this took a little while for me to get back around to. Seems like `kanshi` does the job quite nicely. Misses a few features but it makes sense for me to go contribute over there or follow the ideas and make something myself. I did run into a separate problem with sway but I'll file a new issue for that.

Thanks for the pointer to that project!
