### ISSUE TITLE
Unknown/invalid command 'border'.

### ISSUE THREAD

**Issue by c-edw** [swaywm/sway#4014]
This command is documented [here](https://github.com/swaywm/sway/blob/1e1d9e12991e9a9be72da1fe0c887d9087dffe3a/sway/sway.5.scd#L94) but Sway throws an error when attempting to use it.

Example:

```
border normal 10
```

**Comment by RedSoxFan** [comment]
It sounds like you are trying to use `border` in your config. If you are trying to set the default border, use `default_border` and/or `default_floating_border`.

`border` changes the border for either the focused view or the view(s) specified by critieria and cannot be used directly in the config as their is no view to operate on. `border normal 10` should work fine with swaymsg (or any other IPC client) and bindings

**Comment by c-edw** [comment]
I see, thanks.

**Comment by c-edw** [comment]
One other thing - could you confirm whether i3 deprecated commands such as `new_window` and `new_float` have been intentionally omitted from the manpages?

**Comment by RedSoxFan** [comment]
> One other thing - could you confirm whether i3 deprecated commands such as `new_window` and `new_float` have been intentionally omitted from the manpages?

I think we support them for convenience, but they are undocumented so users find the newer preferred version when looking through the documentation. With that said `force_focus_wrapping` is documented with a note that `focus_wrapping` is preferred so there is some inconsistency.
