### ISSUE TITLE
some gui with basic java deploy not showing up, seems like androidstudio issues

### ISSUE THREAD

**Issue by mh4nx7net** [swaywm/sway#4018]
seems like same issue when run android studio. i had run ghidra nsa tools. noo gui showing up. just blank screen . anyone have same issue like me ?

**Comment by Nikki1993** [comment]
In the wiki https://github.com/swaywm/sway/wiki#issues-with-java-applications

**Comment by michaljroszak** [comment]
Install wmname and do wmname LG3D

**Comment by RedSoxFan** [comment]
See the link Nikki1993 provided and set that environment variable. The other suggestion may work, but is not the recommended solution as it requires an additional (unnecessary) dependency and is essentially a hack that could break at any moment

**Comment by pal3dreamer** [comment]
installing wmname and doing wmname LG3D worked.
