### ISSUE TITLE
Libinput-gestures swiping for mouse side-buttons breaks mouse functionality

### ISSUE THREAD

**Issue by daanjderuiter** [swaywm/sway#4024]
I am currently trying to set up libinput-gestures for Sway to use horizontal swiping as forward/backward mouse buttons. The libinput-gestures documentation doesn't go any further than suggesting xdotool, which is why I am asking here - forgive me if wlroots is a more suitable place to file this, I am not very familiar with the inner workings of Sway. Also, sorry if this seems somewhat incoherent, but I'm really not sure what's going on here.
My `libinput-gestures.conf` currently contains the following two lines:
```
gesture swipe right     swaymsg seat seat0 cursor press BTN_EXTRA
gesture swipe left      swaymsg seat seat0 cursor press BTN_SIDE
```
This sort of works, but fails when interacting with an XWayland client (specifically: Firefox), where the bind works the first time, but then there seems to be some issue with the cursor focusing on the client (visible since the cursor theme changes from my Xorg-theme to the default Wayland-theme), after which either the binds do not work anymore (and I need to interact with some other window before gesture functionality is restored), or mouse functionality just disappears entirely, which is persistent when reloading Sway, and requires me to just exit Sway. Using a normal mouse's side buttons works completely fine.
I have recreated the issue with a bare config which gave the following [log](https://github.com/swaywm/sway/files/3051459/sway.log). I am running Sway version 1.0-8, wlroots 0.5.0-1, both from the official Arch repos.

**Comment by progandy** [comment]
Don't forget to send a "release" event after the "press".

**Comment by daanjderuiter** [comment]
Thanks, that was very silly of me. The cursor theme changing still occurs but mouse functionality is completely fine, at least

**Comment by daanjderuiter** [comment]
Still, a dedicated mouse does not do that; is there some other way that emulating mouse buttons is supposed to be done under Sway?
