### ISSUE TITLE
Set $XDG_CURRENT_DESKTOP on startup?

### ISSUE THREAD

**Issue by ndrewtl** [swaywm/sway#4025]
I'm currently running [variety](https://github.com/varietywalls/variety) which requires `XDG_CURRENT_DESKTOP=sway` in order to properly set the wallpaper. It doesn't seem to be set when I run sway, and a quick search through the code shows that sway doesn't seem to set it at all. Is there a reason for this? I'm currently setting the variable in a startup script when running sway, but I'm curious if you would support just setting the variable when sway starts.

Thanks for all your work!

**Comment by ddevault** [comment]
...no. That's absolutely the wrong way to test for the ability to set a wallpaper on sway. It should check for the existence of the `layer-shell` global on the Wayland display.

**Comment by ddevault** [comment]
Actually, I see that it's an IPC client. It should check if `SWAYSOCK` is set instead.

**Comment by ndrewtl** [comment]
Thanks! To confirm, the correct test is just the _existence_ of `SWAYSOCK`? I might submit a PR over there.

**Comment by emersion** [comment]
Yeah, `SWAYSOCK` being in the env means you're inside a Sway session and you can talk to the IPC server.

**Comment by tmccombs** [comment]
The XDG_CURRENT_DESKTOP environment variable needs to be set in order for XDG portals to work. See https://wiki.archlinux.org/title/XDG_Desktop_Portal. 

This means it is basically required to use a wrapper script to set XDG_CURRENT_DESKTOP. And that doesn't play very well with a display manager that executes sway directly. 

It also impacts the interpretation of the OnlyShowIn and NotShowIn properties of application desktop files, which can impact if entries show up in launchers. 

This really seems like something that sway should just set.  

Or alternatively, implement https://github.com/swaywm/sway/issues/3976 and have `setenv XDG_CURRENT_DESKTOP sway` in the default configuration.

**Comment by smlx** [comment]
@tmccombs you can put this in your sway config and no wrapper is required.
```
exec dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway
```
https://dbus.freedesktop.org/doc/dbus-update-activation-environment.1.html

**Comment by emersion** [comment]
@tmccombs Even if Sway would set XDG_CURRENT_DESKTOP, it wouldn't be enough for xdg-desktop-portal, which is started via D-Bus activation (not as a child process of Sway).

**Comment by Architector4** [comment]
> [@tmccombs](https://github.com/tmccombs) you can put this in your sway config and no wrapper is required.
> 
> ```
> exec dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway
> ```
> 
> https://dbus.freedesktop.org/doc/dbus-update-activation-environment.1.html

Worth noting that this does not apply for applications that are started as a child process of sway. As far as I can tell, a wrapper script is still required if processes spawned by sway need to see `XDG_CURRENT_DESKTOP=sway` if you're starting it from a TTY.
