### ISSUE TITLE
swaybar tray dbus connection error

### ISSUE THREAD

**Issue by rvi64** [swaywm/sway#4027]
when i run swaybar it shows me this error
```
[swaybar/tray/tray.c:42] Failed to connect to user bus: No such file or directory
```
Void Linux x86_64-musl
dbus service is working
```
; ls /run/user/1000/dbus-1/
services
```

**Comment by emersion** [comment]
You most likely don't start D-Bus properly.

**Comment by rvi64** [comment]
```
; cat /var/service/dbus/run
#!/bin/sh
[ ! -d /run/dbus ] && install -m755 -g 22 -o 22 -d /run/dbus
exec dbus-daemon --system --nofork --nopidfile
```
starts like this

**Comment by rvi64** [comment]
if i run `dbus-launch` before sway the message dissappears but tray is still not there.

**Comment by emersion** [comment]
You need to start a session bus, not a system bus.
