### ISSUE TITLE
tooltips from firefox are visible on all workspaces

### ISSUE THREAD

**Issue by Tormen** [swaywm/sway#4030]
sway version 1.0-rc1-221-g4b892a79 (Apr  6 2019, branch 'master')
Mozilla Firefox 66.0.2

steps to reproduce:
* start firefox on an empty workspace
* Hover over the home icon (beside the location bar)
* something like "Firefox Home Page" tooltip should appear (beside the cursor)
* now switch to new workspace

actual result:
* the tooltip is still visible (alone on the empty workspace)

expected result:
* the tooltip should not be visible anymore on new workspace

**Comment by emersion** [comment]
Duplicate of https://github.com/swaywm/sway/issues/2529

Please search for old issues before submitting new ones.

**Comment by Tormen** [comment]
@emersion : Thanks!! - Yeees, absolutely. And I tried... but obviously not hard enough :/
