### ISSUE TITLE
[Feature Request] Spiral

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [swaywm/sway#4034]
## Feature Request
I know it's not native to i3 however there was an i3 fibonacci mod that allowed the user to tile with a fibonacci spiral type layout native to bspwm. I know a lot of users tend to try to tile that way but I think a build in automatic solution would be much more ideal.

Would the swaywm team be open to implementing a feature like this?

**Comment by ddevault** [comment]
Nope.

**Comment by duffydack** [comment]
Just a fyi for @Th3Whit3Wolf , this can be easily achieved (somewhat) with 
 for_window [class=".*"] split toggle

**Comment by Th3Whit3Wolf** [comment]
Thank you @duffydack! That's brilliant. I couldn't make it work with
```shell
for_window [class=".*"] split toggle
```
but I could make it work with
```shell
for_window [app_id=".*"] split toggle
```

**Comment by mxmilkb** [comment]
If it's not obvious, these can be used together for a pseudo automatic spiral layout.

```
for_window [class=".*"] split toggle
for_window [app_id=".*"] split toggle
```

Failings are that it doesn't ignore non-floating windows (improvement possible?), and, naturally, it is not workspace contextual.

**Comment by greole** [comment]
Using 

`for_window [class=".*"] split toggle`

splits sometimes in the wrong direction after moving a window to a different workspace. However, I adapted the [i3-alternating-layout](https://github.com/olemartinorg/i3-alternating-layout) script for  sway, which can be found [here](https://github.com/greole/sway-alternating-layout)
