### ISSUE TITLE
Weird behavior with qutebrowser

### ISSUE THREAD

**Issue by lovesegfault** [swaywm/sway#4036]
I use qutebrowser as my main browser, and I'm on Sway 1.0 running on Gentoo. I have qutebrowser (Qt based) compiled with Wayland support, so it runs natively, as opposed to on Xwayland.

Whenever I open two windows under the same qutebrowser instance, if I set the workspace to a tabbed layout or if I move one of them to another workspace, then the browser freezes and stops working. Setting the workspace back to tiled, or moving the windows back to the same workspace unfreezes it.

Reproduction steps:
1. Open qutebrowser (with `QT_QPA_PLATFORM=wayland`)
2. Open Netflix and start playing The Office (US) [Crucial step!]
3. Open a new tab with anything on it
4. Move the tab onto a new window (`gD`)
5. Everything should be working fine
6. Tab the workspace OR move one window to another workspace
7. Everything stops working
8. Tile the workspace OR move window back
9. Everything works again.

Please let me know if there is anything else I can provide.

**Comment by emersion** [comment]
This is a known qutebrowser bug.

**Comment by RedSoxFan** [comment]
https://github.com/qutebrowser/qutebrowser/issues/4389
