### ISSUE TITLE
Crash when moving a floating window to another workspace

### ISSUE THREAD

**Issue by 1ace** [swaywm/sway#4039]
Sway version: 1.0

Debug Log: https://gist.github.com/610bb19379fa23f16cb1f645e2d1066b

Stack Trace: not running a debug build of sway, so the backtrace was empty (https://gist.github.com/24c16e8ee23d95290818f8476b56e948); I'll try to remember to do it again with a debug build later

Steps to reproduce:
- `workspace 1`
- open window
- `floating toggle`
- `move container to workspace 2`
- crash with `SIGFPE`

**Comment by Emantor** [comment]
This should afair be fixed on current master.

**Comment by RedSoxFan** [comment]
Duplicated of #3870

**Comment by 1ace** [comment]
Thanks, good to know it's been fixed!
