### ISSUE TITLE
Fullscreen terminals don't retain transparency

### ISSUE THREAD

**Issue by daanjderuiter** [swaywm/sway#4040]
See title. I have a transparent terminal, and have noticed that, when toggling it to fullscreen, the transparency is discarded and I am left with a completely black terminal. This has happened for all terminal emulators I have tested (Alacritty, Termite, Terminator, XFCE Terminal, Gnome Terminal, Konsole). This is contrary to my experience in i3, where I can see the full wallpaper behind a fullscreen terminal. Does anyone know why this occurs? I am running Sway 1.0, but have experienced this in earlier releases as well.

**Comment by emersion** [comment]
This is by design: https://gitlab.freedesktop.org/wayland/wayland-protocols/blob/master/stable/xdg-shell/xdg-shell.xml#L935

This allows for optimizations when a window is fullscreen and prevents clients from spoofing a semi-transparent authentication dialogs.

**Comment by daanjderuiter** [comment]
Shame, I was not aware of this design choice. Thanks for the link, anyways

**Comment by Hummer12007** [comment]
https://sr.ht/DG1I.patch - a fix for this (it works rather great for me though YMMV).
@emersion is there a chance that a PR adding a knob for this behavior would be merged?

**Comment by emersion** [comment]
I'm not for it, the renderer code is already complicated enough.

**Comment by Hummer12007** [comment]
OK, I'll take a look if a simple implementation is possible then.

**Comment by Penguin-Guru** [comment]
[Here](https://gist.github.com/ForgottenUmbrella/eb3df8d3a5cf470f63bccde929cfbb93) is another patch I happened across, based on the previous. Hopefully @ForgottenUmbrella won't mind me linking it here (I'll delete this if you want). I haven't looked at the code or tried it yet but I may at some point soon.
