### ISSUE TITLE
[Feature request] Contexts

### ISSUE THREAD

**Issue by stammon** [swaywm/sway#4044]
I often use several workspaces when working on something. When switching to a entirely different thing, I use a different set of workspaces. Having workspaces around of one of the sets, when working with the other set is a distraction, that bothers me a lot.

XMonad has a solution to this: Contexts
- Implementation: https://github.com/Procrat/xmonad-contexts
- Screencast: https://www.youtube.com/watch?v=PNvO06Xofms&feature=youtu.be

I suggest two possible ways to go about this in sway:

1. Add contexts as a new entity to sway
    - This would force every user of sway to understand the idea of contexts, when learning about all the features of sway
    - This will probably add lots of overhead to maintainers of sway
    - Whenever a new feature is considered, their impact and integration to contexts has to be considered as well, even when most users don't need contexts

2. Provide the necessary API to implement contexts externally
Sway/i3 already has a very useful API, but the following commands don't exist yet, but are needed / useful to implement contexts:
    - Rename workspace e.g. `rename-workspace 3 myContext-3`
    - Add a hidden flag to workspaces e.g. `hide-workspace/show-workspace myContext-3`
    - Execute a operation on all windows in a workspace (like kill all of them) e.g. `exec-all-windows workspaceName [swayCommand]`

    These suggested API functions are very basic and probably useful anyway.
    - Renaming workspaces seems to be a very basic operation.
    - Adding/Hiding workspaces is a bit more special, but useful anyways. Other API calls should not list hidden workspaces (maybe there even needs to be a separate call to list the hidden ones as well). It will make integration with a swaybar trivial. This might also be useful for other things like if someone wants to have several scratchpads
    - Execute a operation on all windows in a workspace: It's not necessary, but I'd like to be able to kill a context and all associated windows

As you can see, I'm more in favor of the second approach. The 3 above mentioned changes can be implemented independently of each other and also independently of the contexts implementation itself. 

I'd love to hear your feedback on this and if you approve of it, I might implement the changes for approach 2 and PR them.

**Comment by emersion** [comment]
I think you can already implement this with a script. Get a snapshot of the current state with `swaymsg -t get_tree`, move all windows to the scratchpad (empty workspaces will automatically be removed). When you want to restore, move windows back from the scratchpad to workspaces (creating workspaces as needed) using the snapshot.

**Comment by stammon** [comment]
If I have several hidden workspaces, how do I select the right windows to get from the scratchpad?

You can probably get it to work, but this seem rather like a big workaround. When it comes to my everyday work environment, I'd like to have something solid.

**Comment by emersion** [comment]
>If I have several hidden workspaces, how do I select the right windows to get from the scratchpad?

Each time you switch contexts, you save the list of (container IDs, workspace) before moving containers to scratchpad. When switching back, use container IDs to uniquely identify windows.

**Comment by stammon** [comment]
I guess this works but I have some issues with it:
- I use the scratchpad personally as well
- Writing all this code to save and restore windows and their layout seems unnecessary, when all that needs to be added to sway is a hidden workspace flag
- When moving windows to/from the scratchpad, the remaining windows on the screen will get resized. This should normally not be a problem, but some programs have nasty behavior when being resized (like terminal emulators, that crop the lines)
- Windows can become urgent, which makes the workspace marked as urgent and should probably result in the context to be marked as urgent. Can you do that with the scratchpad approach as well?
- Moving the windows from and two workspaces takes time and is something visible to the user. It doesn't happen instantaneously. This is just bad user experience

**Comment by facocalj** [comment]
I do find the idea of "contexts" very interesting. Specially when working on multiple projects, each with multiple window and workspaces.

@stammom Would a context encompass all the workspaces off all outputs, or would it be confined to a single output? 

If you're suggesting the former, all workspaces could be assigned to "context 0" by default, unless the user shifts to a different context or moves a workspace to a different context. Which I believe, would simplify the implementation.

And talking of which, you could only move a workspace to a context, not a window to a context, right?

**Comment by ddevault** [comment]
I encourage you to try building a script for this, or to use Waymonad, but I'm not interested in adding these kinds of features to sway.

**Comment by stammon** [comment]
> Would a context encompass all the workspaces off all outputs, or would it be confined to a single output?

In my understanding of contexts, a context encompasses all outputs. Being in one context means only workspaces of this context are visible on their respective output. 

> If you're suggesting the former, all workspaces could be assigned to "context 0" by default, unless the user shifts to a different context or moves a workspace to a different context. Which I believe, would simplify the implementation.

Yes there is a default context, the one you have open at the time. Implementationwise I'd rename all other workspaces to magiccontextprefix-contextname-workspacename and hide them.

> And talking of which, you could only move a workspace to a context, not a window to a context, right?
Right. You can always make a custom keybinding, that moves a window into a new workspace and move that workspace into another context, although moving workspaces around contexts altough possible isn't the way you are supposed to use it.

> I encourage you to try building a script for this, or to use Waymonad, but I'm not interested in adding these kinds of features to sway.

That's sad to hear, but I understand, that you can't just add every feature to sway in order to keep it maintainable.

Still the main change I need is support for hidden workspaces, which either
- needs patching everything, that ever talks to sway, to ignore those workspaces I want to be hidden
- or sway not to include hidden workspaces in it's output, which is easier to implement, but a bigger burden to you than to me

I think I will proceed with a patched Waybar, that doesn't show certain outputs, that start with a certain prefix, to hide workspaces. If contexts ever gets used by lots of users and the overall balance of effort is much smaller by adding the feature in sway than patching the tooling, I'll ask again about hidden workspaces in sway.
