### ISSUE TITLE
[Feature] exec with initial commands on the new surface

### ISSUE THREAD

**Issue by norcalli** [swaywm/sway#4045]
# Motivation

Often times, I want to run something like `exec --init='floating enable' st` or `exec --init='mark A' st` so that I can have commands associated with the new window (currently using `exec st; mark A` would run the mark on the currently focused window).

One alternative currently is to use `for_window`. However, this required uniquely marking every single window that is created. Additionally, if one wanted to do this without modifying their config ahead of time, they would have to make the `for_window` criteria on the fly through IPC or swaymsg. In the current code, there is no checking against duplicate criteria/commands, so each time it would be added, and then each time it would be checked multiple times.

Therefore, I would say that there is no way to actually achieve this in sway, not even with a script, as when you create a process with `exec`, the IPC only tells you if it was successful, not the PID of the new command, meaning that you cannot poll for the new window to open before running the command.

And even if you could poll for the window before running the command, there is the downside such as in the case of the floating command, where it will first be drawn as tiling causing a redraw for every window on the workspace before it will be sent to floating. This is circumvented when using `for_window`, so obviously there should be a better solution.

# Implementation

After looking through the code, it seems like the best implementation would be a sort of one-off criteria which matches based on the `pid`, similar to how the `pid_workspaces` list creates an optimistic list of pids and their associated workspaces, we can create a list of commands and associated pids. When the pid shows up, we run the command and remove it from the list.

**Comment by schauveau** [comment]
That would be a nice feature but I do not see how it could be done using the pid because predicting the pid of the process that will own the future surface is probably quite hard. That could work if you 'exec' a proper executable binary file but not if the command is a wrapper script or if it calls an already running instance (e.g. firefox, emacsclient, ...).

The best way to implement the proposed enhancement is probably to apply the settings to the next surface that will be created. This is not perfect but that should work most of the time as long as the windows are opened in the expected order.

Here is a quick hack to do that: 
```
set $AUTO 0
for_window [shell="."] mark --add "auto_$$AUTO" ; set $$AUTO 0
for_window [con_mark="auto_0"] mark --toggle auto_0 
for_window [con_mark="auto_1"] mark --toggle auto_1 ; floating enable 
for_window [con_mark="auto_2"] mark --toggle auto_2 ; fullscreen enable
```
and then set the variable $AUTO to 1 to create a floating window and 2 to start fullscreen as shown below:
```
(shell)  swaymsg 'set $AUTO 1 ; exec xterm'
(shell)  swaymsg 'set $AUTO 2 ; exec xterm'
```

**Comment by schauveau** [comment]
Here is an advanced version that uses pattern matching to allow multiple actions on the next surface:
```
set $PROP none
for_window [shell="."] mark --add "prop:$$PROP:"
for_window [con_mark=^prop.*:floating:] floating enable 
for_window [con_mark=^prop.*:fullscreen:] fullscreen enable 
for_window [con_mark=^prop.*:border10:] border normal 10
for_window [con_mark=^prop.*:sticky:] sticky enable
for_window [con_mark=^prop:] mark --toggle "prop:$$PROP:" ; set $$PROP none
```
and then do something like that:
```
swaymsg 'set $PROP floating:border10:sticky ; exec xterm'
```

**Comment by norcalli** [comment]
That's a valid point about pid's not surfacing, and if you look in the `pid_workspaces` example, the existing solution is to associate a timestamp with the pid on launch, and those are periodically vacuumed with a timeout (currently 60 seconds) for some methods which access pid_workspaces, which I think is a pretty good solution.

I do like those workarounds of embedding property signals via marks, though. Good stuff.

I'll take a stab at implementing this and see how it is received once the work is done.

**Comment by emersion** [comment]
Can't you use a script that listens to IPC events?

**Comment by norcalli** [comment]
@emersion yeah, you're right, I could. I subscribed after double-forking. However, it is not easy for the typical user, I imagine.

			local pid = daemonize(execute)
			sway:subscribe({"window"})
				:timeout(1.0)
				:findL(function(e)
					return e.container.pid == pid
				end)
				:each(function(e) 
					pretty(sway:criteriaMsg({con_id = e.container.id}, init))
				end)
