### ISSUE TITLE
Better behaviour when run on X11

### ISSUE THREAD

**Issue by tbm** [swaywm/sway#4046]
This is obviously a very minor issue, but would it make sense to print an error when swaymsg (and possibly other commands) are run on X11 instead of Wayland?

Currently I get:

```
$ swaymsg -t get_outputs
Output eDP-1 '(null) (null) (null)'
  Current mode: 0x0 @ 0.000000 Hz
  Position: 0,0
  Scale factor: 0.000000
  Transform: (null)
  Workspace: 4
swaymsg: json_object.c:1214: json_object_array_length: Assertion `json_object_get_type(jso) == json_type_array' failed.
```

and `swaymsg -t get_inputs` just hangs.

**Comment by ddevault** [comment]
Do you mean when running them on i3?

**Comment by tbm** [comment]
yes, I'm (still) using i3. But I assume swaymsg will never work on any X11 WM (or at least `get_outputs`, which I'd assume is wayland specific and won't work on X11).

Like I said, this is a very minor issue. But there's a real use scenario here: people planning to switch to sway/wayland, installing the package, reading the man page (while still on X11) and trying to run `swaymsg -t get_outputs` as they read the man page.

**Comment by ddevault** [comment]
Actually, there's no reason swaymsg wouldn't work on i3 - it just use the IPC protocol, not anything Wayland specific. So I would accept a patch improving its behavior under i3.

**Comment by ddevault** [comment]
That being said, the applicability of the information you get out of swaymsg during an i3 session to your future sway sessions is dubious.
