### ISSUE TITLE
Reloading sway should clear error messages

### ISSUE THREAD

**Issue by tbm** [swaywm/sway#4047]
I started sway and it showed an error bar saying that my config file has an error.  I edited the file, fixed the error and reloaded sway but the error message was still there.

At it turns out, sway doesn't remove existing error messages upon reload.  I think i3 has the same behaviour.  To me this seems strange and confusing, but maybe there's a good reason for it.

**Comment by RedSoxFan** [comment]
Currently swaynag is spawned, the PID is stored, and the PID is killed on reload. It should be killed on reload, but for whatever reason, this approach seems to have issues on some setups. I think a version of #3708 for swaynag will be needed
