### ISSUE TITLE
Unable to initialize the Clutter backend: no available drivers found.

### ISSUE THREAD

**Issue by pviotti** [swaywm/sway#4050]
Hi there, I can't run Totem (Gnome's default video player) as it complains about the Clutter backend not being initialized, as follows:

```shell
➜  ~ totem    

(totem:25283): Clutter-CRITICAL **: 19:34:08.647: Unable to initialize Clutter: Unable to initialize the Clutter backend: no available drivers found.

(totem:25283): Totem-WARNING **: 19:34:08.647: gtk-clutter failed to initialise, expect problems from here on.

(totem:25283): Clutter-CRITICAL **: 19:34:08.714: Unable to initialize Clutter: Unable to initialize the Clutter backend: no available drivers found.

(totem:25283): Clutter-WARNING **: 19:34:08.715: Missing Cogl context: was Clutter correctly initialized?
[2]    25283 segmentation fault (core dumped)  totem
```

Sway version: 1.0 (on Arch Linux)  

Is it a well-known incompatibility? Should I run some daemon to initialize Clutter on Wayland..?  
Other similar Gnome applications (e.g. gnome-calculator, gnome-boxes, gnome-characters, nemo, etc) work just fine.  
(I don't post sway's log as I guess it does not matter: I run it without display manager, with a rather normal configuration, and it does not crash when I try to run Totem. )

**Comment by emersion** [comment]
This is a known Clutter bug: it doesn't support xdg-shell.

**Comment by agraven** [comment]
So does this mean clutter applications is entirely unusable, or is there a workaround, like setting environment variables or similar?

**Comment by emersion** [comment]
I'm not aware of any workarounds, The proper solution is to help GNOME folks migrate away from Clutter (Clutter is being phased out).

**Comment by manio** [comment]
Hi!
I have similar problem when trying to start evolution under sway+xwayland:
```
$ evolution
Failed to initialize gtk+: Unable to initialize the Clutter backend: no available drivers found.
```
The resolution for me was to start it like this:
```$ GDK_BACKEND=x11 evolution```
Now it is working, hope this helps... :)

found here: https://gitlab.gnome.org/GNOME/gtk/issues/1390
