### ISSUE TITLE
How to copy the first screen to second screen

### ISSUE THREAD

**Issue by chenjie199234** [swaywm/sway#4052]
when have a meeting
i need to put my notebook computer's screen to the big screen.
i can use the hdmi to expand the screen use output command in config file
but how to copy the screen
i need the screen to be same on my notebook computer's screen and the big screen

**Comment by RedSoxFan** [comment]
Output mirroring is not yet supported. See #1666 for more information

**Comment by progandy** [comment]
At the moment you might be able to capture an output with [dmabuf-capture](https://github.com/swaywm/wlroots/blob/master/examples/dmabuf-capture.c) and pipe it to ffplay on the second output.
