### ISSUE TITLE
[bug] IPC returns incorrect payload type when issuing command while subscribed

### ISSUE THREAD

**Issue by norcalli** [swaywm/sway#4053]
`sway version 1.0-rc1-234-gb2cfcebe (Apr 14 2019, branch 'ashkan')`

I have a script which listens for a particular event using `subscribe` and then issues a command via `RUN_COMMAND`. The result for the `RUN_COMMAND` is given the type of `0x80000003`, which is the window event type (the type I subscribed to).

I was using the payload type to try to distinguish between results, and was wondering why my program seemed stuck, and it's because the result type isn't distinguished properly. I would expect it to be `0`.

**Comment by norcalli** [comment]
Looking at the code, I can see why. A race condition between the time that `client->current_command` is checked and when `ipc_send_reply` is done. I'm not exactly sure why the reply type isn't sent as a parameter, but it seems like that is the best solution, i.e. modify `ipc_send_reply` to pass the reply_type. Global variables and C race conditions are why I program in Rust exclusively now, lol.

**Comment by RedSoxFan** [comment]
> it seems like that is the best solution, i.e. modify ipc_send_reply to pass the reply_type

Sounds reasonable to me. PRs welcome

> Global variables and C race conditions are why I program in Rust exclusively now, lol.

This is not a global variable and is not a race condition. This is purely a logic issue and using a different language is not going to eliminate logic issues. It is possible for events to be sent while `RUN_COMMAND` is being processed. The events are overwriting the current command for any client subscribed to that event. When the command goes to send the reply, the current command for the ipc client will be whatever the last event sent was instead of the command. This is not a race condition since the outcome is deterministic.

**Comment by norcalli** [comment]
Using the `client->command_type` to pass information to the method is very similar to a global variable access bug is what I was getting at, and you're right, I meant a data race (I was thinking about the `client` being borrowed as mutable while it is being immutably borrowed). I'm working on the PR right now. It's an easy-ish fix.

**Comment by migonos0** [comment]
> `sway version 1.0-rc1-234-gb2cfcebe (Apr 14 2019, branch 'ashkan')`
> 
> I have a script which listens for a particular event using `subscribe` and then issues a command via `RUN_COMMAND`. The result for the `RUN_COMMAND` is given the type of `0x80000003`, which is the window event type (the type I subscribed to).
> 
> I was using the payload type to try to distinguish between results, and was wondering why my program seemed stuck, and it's because the result type isn't distinguished properly. I would expect it to be `0`.

Hello, I'm having troubles finding a way to run a command for the focus event, you mentioned you have a working script for it, I'd highly appreciate if you could provide me some insight on how to achieve the same. Thanks in advance for your time.
