### ISSUE TITLE
[Not an Issue] Gui frontend for nmcli

### ISSUE THREAD

**Issue by varshitgithub** [swaywm/sway#4055]
Hi there,
I am using Sway+Waybar. Lastly I was unable to use NetworkManager via gui.
There is one gui client,ie nm-applet which never worked for me.Also it's not that much featurefull.
So,I've decided to write Gui frontend for nmcli(thus Network Manager) . I am writing it as Shell Script using YAD(yet another dialog).
The project is not yet completed.I have short time to work on this and many problems are there to overcome.
I appreciate your interest in this project.Link for the repo:
[https://gitlab.com/varshitbhat/nmguish](url)

**Comment by emersion** [comment]
Please refrain from advertising your projects on the issue tracker.

**Comment by varshitgithub** [comment]
> Please refrain from advertising your projects on the issue tracker.

All Right.Just asking.
Is there any GUI alternative at this moment so that I can use??

**Comment by emersion** [comment]
Ask somewhere else, e.g. on the IRC channel. This issue tracker is meant to track issues.
