### ISSUE TITLE
No mode information on disabled output

### ISSUE THREAD

**Issue by ranisalt** [swaywm/sway#4057]
When an output is disabled on Sway, it provides no information whatsoever about the output. Example: I want to get available modes on a disabled output to choose the best resolution to enable it, but the `modes` attribute comes empty (`[]`).

* Sway Version: 1.0
* Configuration File: N/A
* Steps to reproduce:
1. `swaymsg output <name> disable`
2. `swaymsg -t get_outputs`

The latter displays no information besides the output is inactive. If enabling the output through `swaymsg output <name> enable`, I can then read available modes, but it is very annoying to have a three step (`enable`, `get_outputs`, `disable`) process just to detect resolutions.

Edit: modes are still available through `/sys/class/drm/card0-<name>/modes`, but then I have to query two different sources at different times to obtain available modes.

For the record, `xrandr` is able to list available modes for disconnected outputs.

**Comment by emersion** [comment]
IIRC this is just the IPC server not sending modes for disabled outputs.

**Comment by ranisalt** [comment]
@emersion nice, I'll try myself to contribute then :P

**Comment by emersion** [comment]
Excellent. Feel free to ask questions on IRC (`#sway-devel` on Freenode).
