### ISSUE TITLE
Swaybar remains visible after setting hidden_state to hide.

### ISSUE THREAD

**Issue by JangYeeun** [swaywm/sway#4066]
* Sway Version:
1.0 (arch repository 1.0-8)

* Configuration File:
```
mode "test mode" {
    bindsym Escape mode default; bar hidden_state hide
}
bindsym $mod+period mode "test mode"; bar hidden_state show

...

bar {
    mode hide
    ....
}
```

* Debug Log:
https://gist.github.com/JangYeeun/e154be114fe99b74a1f71675134ca14e

After pressing `$mod+period` (and releasing `$mod`) the bar is visible. (as expected)
After pressing `Escape` the bar is still visible. (expected to disappear)
Only after pressing `Alt` or `Ctrl` or `Shift` or `$mod` the bar will disappear.

**Comment by athrungithub** [comment]
`bindsym $mod+period bar mode toggle`

**Comment by JangYeeun** [comment]
That command docks and undocks the bar, which makes all windows resize.

What I am trying to achieve is to have the bar only visible when I enter a custom mode and then hide the bar when I exit that mode.
With that I can display, using the mode name, information about possible options in that mode.
