### ISSUE TITLE
mpv no window under Sway WM dual screen setup with autofit & autofit-larger options

### ISSUE THREAD

**Issue by Mel34** [swaywm/sway#4076]
* Using AMDGPU with Rx580 card

* Sway Version: `sway version 1.0`

* Debug Log: [debug log](https://gist.github.com/Mel34/7959b5e1638b4610548ed6f249132140)

* Configuration File: [config file](https://gist.github.com/Mel34/ab9b6d562f9181ed8bbdc7c76022b85b)

* Steps to reproduce:
Issue is described in the mpv bug report I opened [here](https://github.com/mpv-player/mpv/issues/6653)

* Stack Trace, if sway crashes: doesn't crash

**Comment by emersion** [comment]
It seems like it's properly using the Wayland mpv backend. Can you obtain a `WAYLAND_DEBUG=client` log?

**Comment by Mel34** [comment]
[Here](https://gist.github.com/Mel34/3d7a9f018fe8c5b06d6c86b6992d5e24) you go.

**Comment by RedSoxFan** [comment]
Are you still experiencing this issue? From the logs, it looks like mpv was crashing. The logs abruptly end and the xdg top level was created, but never mapped.

**Comment by Mel34** [comment]
Yes. I've since updated sway to master branch (sway-git from AUR).

**Comment by RedSoxFan** [comment]
I was able to replicate. I get the same behavior in both Weston and GNOME. In KDE, the issue occurs even with a single output. This is a mpv issue.

**Comment by Mel34** [comment]
Alright, I'll go poke them in my bug report to MPV. Thanks for looking into this @RedSoxFan
