### ISSUE TITLE
Can't use __focused__ in class criteria

### ISSUE THREAD

**Issue by Epse** [swaywm/sway#4083]
I use Sway v1.0 and was trying some things out to see if I could make inactive windows transparent. According to the man pages, something like `for_window [class="__focused__"] opacity 0.5` should do it. This however, errors out upon reloading Sway with the message:
`Token "class" requires a value`.
On any other value for the `class` criterium, the config file is accepted.

(As far as I can tell, using `con_id="__focused__"` should also work, but this doesn't do anything.)

Sidenote: thanks a lot for the hard work, Sway is amazing!

**Comment by ddevault** [comment]
Double check your reading of the man page. That's not quite how the `__focused__` criteria works.

There's a script here which does what you want:

https://github.com/swaywm/sway/blob/master/contrib/inactive-windows-transparency.py

**Comment by Epse** [comment]
That's possible, but I would assume it should still be a valid class name? 

24 Apr 2019, 17:30 by notifications@github.com:

**Comment by cartok** [comment]
This still does not explain how to use that poorly documented `__focused__` in queries
