### ISSUE TITLE
How do I get sway's current background(s) file paths?

### ISSUE THREAD

**Issue by harrisonthorne** [swaywm/sway#4086]
`sway version 1.0-rc1-221-g4b892a79 (Apr  7 2019, branch 'master')`

Hi! I'm developing a little program and I'm wondering if there is a way to get the file path to the background image(s) for all outputs. Google and the man pages haven't been much help yet.

**Comment by emersion** [comment]
No, this isn't possible. We have no plans to add this feature as of now.

**Comment by harrisonthorne** [comment]
Heard loud and clear.

**Comment by progandy** [comment]
There is a way, set a script as swaybg_command that logs the filenames and then executes the original swaybg. Or disable swaybg_command and do all background configuration including rendering to the outputs in your own application.
