### ISSUE TITLE
Unclickable Areas

### ISSUE THREAD

**Issue by Muhkoenig** [swaywm/sway#4087]
```
bindsym $mod+p output eDP-1 pos 0 1080 res 1920x1080; \
        output DP-1 pos 1920 0 res 3840x2160; \
        output DP-1 scale 1.2
```
On `sway-git-r5883.8adb70f9` with the above output configuration i get unclickable areas on both monitors. Switching back to release 1.0 fixes the issue.

**Comment by emersion** [comment]
Does this only affect X11 clients?

**Comment by Muhkoenig** [comment]
As far as I can tell it only effects X11 clients.

**Comment by emersion** [comment]
Duplicate of https://github.com/swaywm/sway/issues/4064
