### ISSUE TITLE
Tray does not show up

### ISSUE THREAD

**Issue by nerddan** [swaywm/sway#4100]
- sway version: 1.0
- config: default
- bar: i3status
- log: https://gist.github.com/nerddan/4abb9e982073e37d7b441a8a46343d89

The tray icons do not show. If I run another bar through `swaybar`, an exactly identical bar shows and still without tray icons, and the terminal has these output:

```
$ swaybar --bar_id bar-0
i3status: trying to auto-detect output_format setting
i3status: auto-detected "i3bar"
2019-04-28 19:11:47 - [sway-1.0/swaybar/tray/watcher.c:185] Failed to acquire service name: File exists
2019-04-28 19:11:47 - [sway-1.0/swaybar/tray/watcher.c:185] Failed to acquire service name: File exists
^CExiting due to signal.
```
These lines also appeared in the log.

Here is the line printed the error log.
https://github.com/swaywm/sway/blob/master/swaybar/tray/watcher.c#L185

**Comment by rumpelsepp** [comment]
The support for tray icons is not fully implemented yet. I think the following links might be interesting for you:

* https://github.com/swaywm/sway/issues/3799
* https://github.com/swaywm/sway/wiki#where-are-my-tray-icons

**Comment by nerddan** [comment]
I don't get it. Is it not implemented at all, or some features is missing?
My tray is not shown at all, is this the supposed behaviour?

**Comment by rumpelsepp** [comment]
AFAIK there are different APIs to let your app notify that there is tray functionality available (there is a list in the referenced issue). Not all of them are implemented.

**Comment by Kommynct** [comment]
Depending on your distro, try installing libappindicator-gtk3 or your distros equivalent package.

**Comment by nerddan** [comment]
@Kommynct Thank you! I installed `libappindicator-gtk3` and had sway restarted, but nothing changed. Even the error information is still

```
2019-04-28 19:11:47 - [sway-1.0/swaybar/tray/watcher.c:185] Failed to acquire service name: File exists
```

**Comment by QasimK** [comment]
(I installed `libappindicator-gtk3` and the tray icon *did* appear for me at least)

**Comment by ObiWahn** [comment]
My problem was that I did not have a DBUS session. After creating systemd user services the icons started to appear in the swaybar after the next login. If you struggle make sure that ` set | grep DBUS` shows something like `DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus`.
