### ISSUE TITLE
[enhancement] allow a prev/next window navigation

### ISSUE THREAD

**Issue by Soundtoxin** [swaywm/sway#4103]
* Sway Version:
`sway version 1.0`

I would like to see additions that would fit the names `focus next` and `focus next_on_input`. I'm missing awesomewm's ability to cycle through all the windows on a workspace with two keys (a previous and next, super-j and super-k by default). If there's a way to determine the age of windows, aka the order they opened, I was thinking this could be used. There's already a way to cycle through workspaces and outputs, but if you have windows open split in both directions you have to use a mix of up/down and left/right to get around. This is fine to have, but I'd also like a lazier method where I can just go forward and back through a list of the windows on a workspace.

This might also work well with the option of showing window titles in the panel. That way you could see one direction went left and the other went right in the order of open windows.

**Comment by RedSoxFan** [comment]
i3's stance: https://github.com/i3/i3/issues/907
> 1. The order in which alt+tab switches through windows is not easily predictable

I think this bullet point from the i3 issue is enough to say this is better as an IPC script. We could hard code some semantics for cycling, but they would all be arbitrary and different users could prefer different semantics. Having this be configurable would quickly become complicated.

_I'll leave this open for now in case the others disagree._

**Comment by emersion** [comment]
Agreed.

**Comment by Soundtoxin** [comment]
Alt Tab usually changes order constantly so that just using it twice brings you back and forth between two windows. What I want would keep the order the same and just traverse back and forth through the list, the same way you move between adjacent workspaces.

**Comment by RedSoxFan** [comment]
> What I want would keep the order the same and just traverse back and forth through the list

I just quoted the wording from the i3 issue. Alt-Tab is just a specialized version of window cycling with the back and forth functionality added though. The same argument applies without that additional functionality.

**Comment by Soundtoxin** [comment]
Windows could be assigned a number when spawned, and reassigned a number when moved to a new workspace. (e.g. window 7 from workspace 1 may become window 3 in workspace 2 if there are already two other windows)
I'd like to think that Sway isn't limited to doing just what i3 can do, but if it's difficult to implement then I understand.

**Comment by RedSoxFan** [comment]
> I'd like to think that Sway isn't limited to doing just what i3 can do

It isn't that Sway is limited to i3's feature set, but that the reasoning for i3 not implementing the feature is also valid for Sway.

> Windows could be assigned a number when spawned, and reassigned a number when moved to a new workspace

Again, this is an arbitrary ordering and other users may want to iterate over the windows in a different ordering. This ordering can also quickly become confusing and non obvious what the next and previous windows are without adding an additional indicator or window list as mentioned in the i3 issue.

I still think this is better as an IPC script. You are free to use whichever semantics you wish and there is sufficient information exposed to allow for a script to be written
