### ISSUE TITLE
No way to reset xkb_options

### ISSUE THREAD

**Issue by joshuarubin** [swaywm/sway#4105]
Version: `1.0`

I've written an API client that sends `input '*' xkb_options ...` messages depending on the focused window (so I can have some different key bindings for different apps). As a result sway is constantly updating those values.

As the default `xkb_options` are fine most of the time, I need a way to reset to the default values but `xkb_options` complains that an argument is required.

I've resorted to sending the invalid message `input '*' xkb_options none` which works, but results in errors being logged.

It would be nice if there was an official way to do this.

**Comment by emersion** [comment]
Can't you `input '*' xkb_options ''`?

We pass those values straight to libxkbcommon.

**Comment by joshuarubin** [comment]
Yeah, guess that does work, I thought I tried that but was actually sending an empty string and not the literal `''`. Thanks!
