### ISSUE TITLE
sway 1.0 crash (during -Syu)

### ISSUE THREAD

**Issue by goesmin** [swaywm/sway#4110]
Probably my fault but you never know.

* 1.0
* no log (can't reproduce)

`#0  0x00007fbf8026782f in raise () at /usr/lib/libc.so.6`
`#1  0x00007fbf80252672 in abort () at /usr/lib/libc.so.6`
`#2  0x00007fbf7fc58820 in  () at /usr/lib/libwayland-server.so.0`
`#3  0x00007fbf7fc56ed0 in  () at /usr/lib/libwayland-server.so.0`
`#4  0x00007fbf7fc52319 in  () at /usr/lib/libwayland-server.so.0`
`#5  0x00007fbf7fc5285c in wl_resource_post_event () at /usr/lib/libwayland-server.so.0`
`#6  0x00007fbf7fbeac59 in  () at /usr/lib/libwlroots.so.2`
`#7  0x00007fbf7fbeb17b in wlr_seat_set_keyboard () at /usr/lib/libwlroots.so.2`
`#8  0x000055e865dd6802 in  ()`
`#9  0x000055e865ddb39e in  ()`
`#10 0x000055e865ddb54c in  ()`
`#11 0x000055e865ddc978 in  ()`
`#12 0x000055e865dec041 in  ()`
`#13 0x000055e865dc5f00 in  ()`
`#14 0x00007fbf7fc5575c in wl_event_loop_dispatch_idle () at /usr/lib/libwayland-server.so.0`
`#15 0x00007fbf7fc55816 in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0`
`#16 0x00007fbf7fc5439c in wl_display_run () at /usr/lib/libwayland-server.so.0`
`#17 0x000055e865daf562 in  ()`
`#18 0x00007fbf80253ce3 in __libc_start_main () at /usr/lib/libc.so.6`
`#19 0x000055e865daf9ae in  ()`

**Comment by ddevault** [comment]
I think we stand basically no chance at fixing this with a symbol-less backtrace and no reproducability.
