### ISSUE TITLE
swaybar disable changing workspaces with mouse wheel

### ISSUE THREAD

**Issue by uglywizkid** [swaywm/sway#4114]
Exists there any way to disable changing workspaces with mouse wheel? In i3 this can be established with

```
bar {
  wheel_up_cmd nop
  wheel_down_cmd nop
}
```

**Comment by hmohamad** [comment]
According to `man sway-bar`:

`bindsym [--release] button[1-9]|<event-name> <command>`

Executes command when the mouse button has been pressed (or if released is given, when the button has been released). The buttons can be given as a x11 button number or an event name, which can be obtained from `libinput debug-events`. To disable the default behavior for a button, use the command nop.


So in this case its button 4 and 5 for vertical scrolling and 5 & 6 for horizontal scrolling.
```
bar {
    # diable vertical scrolling
    bindsym button4 nop
    bindsym button5 nop
    # diable horizontal scrolling
    bindsym button6 nop
    bindsym button7 nop
}
```

**Comment by uglywizkid** [comment]
Thanks. This works charmfully.

**Comment by larchenkov** [comment]
Is it possible to do the same for window tabs?

**Comment by larchenkov** [comment]
Has the same question it's very annoying when window tabs switching with scroll

**Comment by jayache80** [comment]
@larchenkov Yes. To disable mousewheel-over-titlebars-changes-tabs behavior, simply put the same `bindsym`s in the regular config section, outside of the `bar` block. So, in my config, I have:
```
bar {
    ...
    # Don't let mousewheel scrolling change workspaces
    # Diable vertical scrolling
    bindsym button4 nop
    bindsym button5 nop
    # Diable horizontal scrolling
    bindsym button6 nop
    bindsym button7 nop
}

# Don't let mousewheel scrolling change tabs
# Diable vertical scrolling
bindsym button4 nop
bindsym button5 nop
# Diable horizontal scrolling
bindsym button6 nop
bindsym button7 nop
```
You need it in both sections like that if you want to disable that behavior for both the status bar and title bars.

(Sorry for the noise, but this post comes up on google when searching for "swaywm mousewheel titlebars")

**Comment by nermolov** [comment]
What would the config be to *enable* scrolling on title bars? I'm using default binding config and don't have it.

**Comment by stacyharper** [comment]
I'm trying to disable the touch drag that change workspace as the mouse wheel does. The `libinput debug-events` show me the TOUCH_DOWN but it does not work from my sway config. Is it possible ?

**Comment by stacyharper** [comment]
Okay my bad, button6 and button7 also handle the touch horizontal drag !

**Comment by stacyharper** [comment]
My bad for the previous message. Looking at the code, it is not possible to disable the touch events yet :(

**Comment by yellow-footed-honeyguide** [comment]
Guys, in my case switching between workspaces by scrolling persists despite configuration changes.

### Environment
Sway version: 1.9
Waybar version: 0.10.4
Linux kernel: 6.9.12-200.fc40.x86_64
Mouse: Bluetooth Logitech MX Master 3S

### My steps
~/.config/sway/config
```
bar {
      swaybar_command waybar
      bindsym button4 nop 
      bindsym button5 nop 
      bindsym button6 nop 
      bindsym button7 nop 
}
```
Executed ```swaymsg reload```
Attempted to scroll wheel in workspace area

### Expected Behavior and Actual Behavior
Mouse scrolling should not switch workspaces.
Scrolling the mouse wheel causes switching between workspaces.
