### ISSUE TITLE
Help Requested to Test swaybar

### ISSUE THREAD

**Issue by juanitotc** [swaywm/sway#4115]
I've compiled sway-1.0 with "-Dtray=enabled" and am trying to test it.

Atfter much searching, I've been unable to find the answers to the following questions - any help (or pointing in the right direction) would be appreciated:

Will the swaybar tray work with "xwayland disable" in the sway config?

Can an application icon be added to the tray such that clicking on the icon launches the application and if so, what is the sway config command for this?

I understand that apps such as blueman and networkmanager can put an icon in the tray, which enables right-click selection of a wifi network, etc - this is does not work for me, is there a sway config command to enable it?

**Comment by emersion** [comment]
>Will the swaybar tray work with "xwayland disable" in the sway config?

Yes

>Can an application icon be added to the tray such that clicking on the icon launches the application and if so, what is the sway config command for this?

You need to use/create a client with tray icon support.

>I understand that apps such as blueman and networkmanager can put an icon in the tray, which enables right-click selection of a wifi network, etc - this is does not work for me, is there a sway config command to enable it?

They use a legacy mechanism to create tray menus called xembed. See https://github.com/swaywm/sway/issues/3799
