### ISSUE TITLE
swaymsg --quiet option and return status code

### ISSUE THREAD

**Issue by tardypad** [swaywm/sway#4116]
Using sway 1.0 on Arch Linux

I'm using the "--quiet" option of swaymsg which is described in the manual as
"Sends the IPC message but does not print the response from sway."

I was expecting this option to only affect the output but not the return status code.
Consider the differences between the following commands:

`swaymsg xxx`
outputs "Error: Unknown/invalid command 'xxx'" 
return status code is 1

`swaymsg --quiet xxx`
outputs nothing
return status code is 0 

I'm not sure if this is to be considered a bug or not.
Reporting it just in case.

**Comment by emersion** [comment]
I believe this is a bug.
