### ISSUE TITLE
gtk settings problem 

### ISSUE THREAD

**Issue by kristoferus75** [swaywm/sway#4118]
Hi !

sway version is 1.08

I want to use this gtk settings :

vi .config/sway/config

```
set $gnome-schema org.gnome.desktop.interface

exec_always {
    gsettings set $gnome-schema gtk-theme 'Arc-Darker'
    gsettings set $gnome-schema icon-theme 'Faenza-Dark'
#   gsettings set $gnome-schema cursor-theme 'Your cursor Theme'
}
```

But if i open perhaps  thunar the theme and icon settings are not used !?

if i edit the .profile and add this line the gtk theme in thunar is used:

`export GTK_THEME=Arc-Darker`

Why this doesnt work ín the sway config and how can i set the icon theme ?

Thanks

kind regards

kristoferus75

**Comment by emersion** [comment]
>sway version is 1.08

This version doesn't exist.

>But if i open perhaps thunar the theme and icon settings are not used !?

This is a GTK+ issue. See e.g. https://wiki.archlinux.org/index.php/GTK+#Basic_theme_configuration
