### ISSUE TITLE
show all opened windows

### ISSUE THREAD

**Issue by kristoferus75** [swaywm/sway#4121]
Hi !

I use sway 1.0

Is it possible to see all openend windows (for all workspaces) with a shell command to use it in a rofi or dmenu and to switch to this opened windows and to this workspace ->  like a window switcher ? (with rofi i use it this on xfce)

thanks

kind regards

kristoferus75

**Comment by ddevault** [comment]
You can probably accomplish this with swaymsg -t get_tree and `[...criteria...] focus`. See the man pages for details.

**Comment by Emantor** [comment]
```
bindsym $mod+g exec swaymsg \[con_id=$(swaymsg -t get_tree | jq -r '.nodes | .[] | .nodes | . [] | select(.nodes != null) | .nodes | .[] | select(.name != null) | "\(.id?) \(.name?)"' | rofi -dmenu -i | awk '{print $1}')] focus
```
Is my naive `jq` shell script.

**Comment by kristoferus75** [comment]
Hi Emantor !

 Thanks :-)

I have tested it and it shows only the tilled windows and not the floating windows and if im on an oher workspace it doesnt focus to that workspace to that windows !

Sorry i have no idea how to correct this !

Thanks

kind regards kristoferus75

**Comment by kristoferus75** [comment]
Hi ! 

With this script it works now :

```
#!/bin/bash

# Get available windows
windows=$(swaymsg -t get_tree | jq -r '.nodes[1].nodes[].nodes[] | .. | (.id|tostring) + " " + .name?' | grep -e "[0-9]* ."  )

# Select window with rofi
selected=$(echo "$windows" | rofi -dmenu -i | awk '{print $1}')

# Tell sway to focus said window
swaymsg [con_id="$selected"] focus
```

kind regards 

kristoferus75

**Comment by lorendias** [comment]
@kristoferus75 has the swaymsg structure changed since May? The script no longer works.

**Comment by VanLaser** [comment]
How about simply using: `rofi -show window` ?

**Comment by shapeoflambda** [comment]
Tweaked the above code to make it work with floating windows:

```sh
#!/bin/bash

# Get regular windows
regular_windows=$(swaymsg -t get_tree | jq -r '.nodes[1].nodes[].nodes[] | .. | (.id|tostring) + " " + .name?' | grep -e "[0-9]* ."  )

# Get floating windows
floating_windows=$(swaymsg -t get_tree | jq '.nodes[1].nodes[].floating_nodes[] | (.id|tostring) + " " + .name?'| grep -e "[0-9]* ." | tr -d '"')

enter=$'\n'
all_windows="$regular_windows$enter$floating_windows"

# Select window with rofi
selected=$(echo "$all_windows" | rofi -dmenu -i | awk '{print $1}')

# Tell sway to focus said window
swaymsg [con_id="$selected"] focus
```

**Comment by tobiaspc** [comment]
I reimplemented the above snipped in python, removing the need to include the window id for wofi, dropping the jq dependency and improving startup time by ~40% on my laptop, running in power saving mode.

See here: https://github.com/tobiaspc/wofi-scripts

**Comment by sim590** [comment]
I was looking for something a bit more like this (coming from AwesomeWM):

https://github.com/guotsuan/awesome-revelation

It show all windows in the same workspace and lets us choose the window with a key and then it switches to the window in its workspace. Is there anything of the sort that exists nowadays? That would be very nice.

**Comment by tmpm697** [comment]
@sim590 Woa, that's awsome-revelation seems overkill but very nice/handy switcher. But for it to work with sway, client needs to aware of window's location on screen. From `swaymsg -t get_tree` we can get window size and location on screen.

So we need to center `display` random character for each window and also able to read user input from that `display`. No idea how but that some verboses.

**Comment by davxy** [comment]
https://github.com/davxy/dotfiles/blob/main/sway/applist.py

Inspired by @tobiaspc

**Comment by FelixSchausberger** [comment]
I have rewritten the script in Rust with [fuzzel](https://codeberg.org/dnkl/fuzzel?ref=mark.stosberg.com) as launcher (and it therefore supports icons!)

You can find it here: [SwayFocus](https://github.com/FelixSchausberger/swayfocus), inspired by @davxy and @tobiaspc 

It should not be impossible to write a simple app that shows a preview of all open workspaces using some screenshot utility. If I find time for it I might have a look at it.

**Comment by GotaLoveFiraCode** [comment]
BTW, rofi has this feature built in: `rofi -terminal '$term' -modes window -show window`

**Comment by skybert** [comment]
> BTW, rofi has this feature built in: rofi -terminal '$term' -modes window -show window

Sadly, that doesn't show all windows. On my system, it only shows some windows, like Chrome. It doesn't show apps like Firefox, Emacs, Kitty.

```
$ sway --version
sway version 1.9
$ rofi -v
Version: 1.7.5
```

**Comment by GotaLoveFiraCode** [comment]
Huh sorry man, can't help you there! I tried it with rofi 1.7.5 too, and was fully successful — so it has to be some external factor. Good luck!

**Comment by VanLaser** [comment]
Isn't that related to how rofi sees windows, as in maybe it only sees the wayland native ones, and not the ones running through X?
