### ISSUE TITLE
Help if possible for tray icon support

### ISSUE THREAD

**Issue by aus9** [swaywm/sway#4125]
Please note I am not submitting a bug report at this stage. If you have time, I am seeking help to enable tray icon support in a planned submission to Tinycore Linux 64 bit which is a ram drive busybox distro.
Comments :
I have read these links
https://github.com/swaywm/sway/issues/1624   SNI
https://github.com/swaywm/sway/issues/3799  planned tray features
https://github.com/swaywm/sway/blob/master/meson.build   our build dep check etc

Questions if I may
1) looking at the meson build I read it slightly different to real coders so forgive me I am wrong
```
tray_deps_found = systemd.found() or elogind.found()
if get_option('tray').enabled() and not tray_deps_found
	error('Building with -Dtray=enabled, but libsystemd and libelogind have not been not found')
endif
have_tray = (not get_option('tray').disabled()) and tray_deps_found
```
by loading elogind-dev and its main package, my compile shows
xwayland: true...gdk-pixbuf: true....systemd: false...elogind: true..tray: true... man-pages: true
But it appears the wording in your error msg = but libsystemd and libelogind have not been not found
Could that be re-worded to mean but libsystemd and/or  libelogind have not been not found ?

Q2) To get tray icon support will setuid cause a fail?
As Tinycore tries to load the least number of dependencies, and I thankyou for the option of setuid
that would mean I only use elogind-dev for the build and not the actual running of tray icon support

Q3) Can anyone supply a config snippet that I could cheat off that the contributor knows on their distro
shows a tray icon please?

Q4) Am I missing something.....am I missing a protocol. ie what running dependency I am missing please?
SNI for example....what do I need or what do you guys use on your distro

Thankyou very much for taking time to read my help issues
If my questions too stupid for you, feel free to have a laugh as we all need a laugh.
I could submit sway without elogind as a build and running dep and have no tray icon support,
if I am unable to resolve these queries

thanks again

**Comment by emersion** [comment]
1. I don't get it. In case the user wants to build the tray but doesn't have systemd/elogind, we prinbt an error message.
2. elogind is a runtime dependency. You can't use elogind to build sway and then remove it from your system.

I don't know the answer to other questions.

Closing because it's not a sway issue.
