### ISSUE TITLE
Use of long output identifers breaks output handling

### ISSUE THREAD

**Issue by colemickens** [swaywm/sway#4131]
```
sway rev = 51c077798cf06ebd5e27271fb5e276c181f8a077
````

```
$ swaymsg output eDP-1 disable   # works
$ swaymsg output eDP-1 enable   # works

$ swaymsg output eDP-1 disable   # works
$ swaymsg output eDP-1 enable   # works

$ swaymsg output "'Sharp Corporation 0x148B 0x00000000'"  disable   # works
$ swaymsg output "'Sharp Corporation 0x148B 0x00000000'"  enable   # does nothing

$ swaymsg output eDP-1 enable   # does nothing
```

This also happens if you use the long identifiers in the configuration file, but for now I've removed all `output ...` lines from my config (and fully restarted sway). I tested this many times to ensure that my config file was unrelated and that this happens reliably.

[sway.log](https://github.com/swaywm/sway/files/3149771/sway.log)

**Comment by prometheanfire** [comment]
hmm, I think this is the same as what's happening to me.

https://gist.githubusercontent.com/prometheanfire/54eceb72ea4b7601b1ce3b5cf90a5184/raw/8193f82b2695e4396409b2366995402d325af49f/gistfile1.txt

**Comment by progandy** [comment]
I think the problem is that sway just has no information about the monitor while the output is disabled. Therefore it cannot enable it. To implement it, you might have to loop over all disabled outputs, enable it, read the identifier, and if it is the wrong one, disable it again and continue.

**Comment by RedSoxFan** [comment]
> You might have to loop over all disabled outputs

Sway already loops over all outputs

I located the issue (a typo). PR incoming

**Comment by progandy** [comment]
Thanks, I got lost a bit in the code. I thought sway forgets the name and then has to reacquire it.
