### ISSUE TITLE
Losing mouse grasp moving floating windows towards edges

### ISSUE THREAD

**Issue by l4rzy** [swaywm/sway#4133]
* Sway Version: `sway version 1.1-rc1-3-g9dca18b6 (May  7 2019, branch 'master')`
* Debug Log: [sway.log](https://gist.github.com/l4rzy/74d0df4f91119d42d37ac478d44b159a)
* Configuration File: default

**Description**: Moving a floating window towards screen edges e.g. `URxvt` (XWayland) and `gtk3-demo` (Wayland) caused the window to lose its mouse grasp (tested with all 4 edges), though the window itself continued to move along that direction and it's no help trying to move back the window once I release the mouse. Interestingly, the moved window appeared to be rendered on another workspace through the workspace indicator, but it was actually not rendered on that workspace by switching to that workspace and check.

**Expectation**: The window should stop moving as the mouse stop. I'm fairly new to sway, so I'm not sure this is a bug or feature :), but as a sane expectation, this is weird.

**Comment by sheenobu** [comment]
I *think* this is the bug i was about to create a report for. in sway running as a window in X11, the same thing happens. in rootston (the compositor in wlroots, it works properly).

 * Sway Version: `sway version 1.1-rc1-21-g49258829 (May 31 2019, branch 'master')`

If your mouse is pressed down and dragged outside the screen, we are still getting wlr_event_pointer_motion_absolute events. this doesn't happen if the mouse isn't pressed.

the rate of change of the windows x or y position is being calculated based on this event: [gdb session ](https://gist.github.com/sheenobu/42e9485f0ebacbc3c331c15e3fa700b3)

fixing the left and top sides are easy enough but i don't know the outcomes, and this fix mirrors wlroots/rootstons behavior (hacky, don't use):

```
index 61084447..82950eaa 100644
--- a/sway/input/cursor.c
+++ b/sway/input/cursor.c
@@ -275,6 +275,9 @@ static void handle_cursor_motion_absolute(
        wlr_cursor_absolute_to_layout_coords(cursor->cursor, event->device,
                        event->x, event->y, &lx, &ly);
 
+       if (lx < 0) { lx = 0; }
+       if (ly < 0) { ly = 0; }
+
        double dx = lx - cursor->cursor->x;
        double dy = ly - cursor->cursor->y;
```

I've run out of time to keep typing. The _real_ fix might be bounds checking seatop_move_floating_event.
