### ISSUE TITLE
Firefox windows freeze on screen when in tab view

### ISSUE THREAD

**Issue by JonnyMako** [swaywm/sway#4134]
`sway version 1.1-rc1-2-g51c07779 (May  6 2019, branch 'master')`

Steps to reproduce:

In a blank workspace:
1. Start Firefox-nightly under wayland
2. Add a new window with Ctrl+n.
3. Arrange them side by side
4. Add a third new firefox window to any one of the two containers
For example we have: V[S[ff1,ff2], ff3]. At this point all three firefox windows are responsive.
5. Now covert the stacked container to tabbed view with $mod+w. So now we have V[T[ff1, ff2], ff3]. Now all three firefox windows become unsponsive.

I don't think this is a mozilla issue. Let me know otherwise and I'll report to mozilla.

**Comment by emersion** [comment]
This is a Firefox issue.

**Comment by JonnyMako** [comment]
ok, thanks. Reported to mozilla:
https://bugzilla.mozilla.org/show_bug.cgi?id=1550076
