### ISSUE TITLE
Add a configuration option to set a tablet as a relative input

### ISSUE THREAD

**Issue by Eragonfr** [swaywm/sway#4139]
I have a Wacom intuos M Bluetooth, and i like using it as a relative input.
I haven't view any sway configuration option to set that.
It's possible to add that into sway ? Or into wlroots ?

**Comment by ascent12** [comment]
libinput does give us relative coordinates for tablet events, but sway isn't hooked up to use it.

https://github.com/swaywm/sway/blob/master/sway/input/cursor.c#L440-L469
(`struct wlr_event_tablet_tool_axis` has that `dx` and `dy` as a member).

I'll admit that the input code would be the part I'm the least familiar with, but I don't think it would be that hard for someone to add support for that.

**Comment by Eragonfr** [comment]
Progress with the issue #2288  ?

**Comment by Eragonfr** [comment]
I'm not a good dev, and I don't know how i can add my modification in a good way. I want to add an option similar to `option "Mode Relative"`(from X libinput configuration) into main sway configuration file; so users can choose between relative and absolute input.
Do you have any idea how I can create that ?
