### ISSUE TITLE
Clipboard manager: clipman

### ISSUE THREAD

**Issue by pat-s** [swaywm/sway#4143]
Listed as "TBD" in https://github.com/swaywm/sway/wiki/i3-Migration-Guide.

[clipman](https://github.com/yory8/clipman) was suggested in [this](https://www.reddit.com/r/swaywm/comments/bke1od/found_a_sway_config_that_rocks/en0exx3?utm_source=share&utm_medium=web2x) reddit thread. 

It works flawlessly so far for me and supports both `dmenu` and `rofi`.

There is also a [youtube vid](https://www.youtube.com/watch?v=2qfxmCgmHdM&feature=youtu.be) about it.

**Comment by emersion** [comment]
The wiki is editable.

(Clipman seems to be a wrapper around wl-clipboard. TBH it could just have been a shell script.)

**Comment by talbergs** [comment]
> TBH it could just have been a shell script.

A service: `wl-paste -w wl-paste -p >> ~/.clipboard-history`
And menu: `tac ~/.clipboard-history | rofi -dmenu | wl-copy`

**Comment by NilsIrl** [comment]
> `wl-paste -w wl-paste -p >> ~/.clipboard-history`

Unfortunately it wouldn't work with multiline selections :(

**Comment by UltraBlackLinux** [comment]
it seems to have been deleted...
