### ISSUE TITLE
hide_cursor disables pointing when cursor is hidden

### ISSUE THREAD

**Issue by terminalnode** [swaywm/sway#4145]
Using sway RC1.

When posting this I found issue #3431, which seems to point to the same issue but with a different desired outcome.

I almost never want to see the cursor and therefor have a very short hide_cursor timeout. Usually this works well, except when reading tooltips in a browser or something like that I have to keep the cursor moving at all times or the tooltip/hover text/whatever will disappear.

Would it be possible to add an option where the cursor is just hidden but not disabled? Personally I think it would be useful to be able to have both of these options. One to simply hide the cursor and then another one with a longer timeout to disable it.

**Comment by emersion** [comment]
TBH I'm not a fan of this. Invisible-but-still-active cursors are confusing.

**Comment by RedSoxFan** [comment]
I agree with emersion. I'm going to close this since it was decided in #3967 that we won't be adding more complexity to `hide_cursor`.

**Comment by terminalnode** [comment]
Fair enough. :+1:
