### ISSUE TITLE
Falsely think it's using NVIDIA driver

### ISSUE THREAD

**Issue by Moelf** [swaywm/sway#4147]
~I hate NVIDIA very much like everyone here~

I'm using NVIDIA purely for the computational purpose (CUDA), and sway would warn me (and force me to use `--my-next...` even though it's not running on NVIDIA because `nvidia-smi` says:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.74       Driver Version: 418.74       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1070    Off  | 00000000:09:00.0 Off |                  N/A |
| 27%   37C    P8     5W / 151W |      0MiB /  8119MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

I don't really now how `sway` (or in general any wayland DE) detects this but maybe there's a way to suppress the warning?

**Comment by Moelf** [comment]
the physical set-up is: ` eGPU --- tb3 --- laptop --- other tb3 --- monitor`

**Comment by Emantor** [comment]
Detection is done by opening `/proc/modules/` and looking for the nvidia driver, you won't get around this unless you unload the `nvidia` module.

**Comment by Moelf** [comment]
I see, but in my case `sway` is not using it, and to my best knowledge, there's no way using `cuda` without running nvidia driver. Maybe I can load it after lunching `sway`? Not sure how to achieve that though.

**Comment by ddevault** [comment]
You need to uninstall the nvidia driver. Sway or cuda: choose one.
