### ISSUE TITLE
Grouped config option in libinput not working

### ISSUE THREAD

**Issue by luispabon** [swaywm/sway#4151]
* Sway Version:
1.0

* Debug Log:
https://pastebin.com/6P9DVVR1 >> with the non working config
https://pastebin.com/8rrH5BwL >> with the working config

My config is pretty close to default, I've just started with sway today. Nothing inherited from i3.

* Configuration File:
This doesn't work:
```
input "739:31251:DLL07BE:01_06CB:7A13_Touchpad" {
    accel_profile flat
    drag enabled
    tap enabled
}
```
This, however, does:
```
input "1739:31251:DLL07BE:01_06CB:7A13_Touchpad" tap enabled
input "1739:31251:DLL07BE:01_06CB:7A13_Touchpad" drag enabled
input "1739:31251:DLL07BE:01_06CB:7A13_Touchpad" accel_profile flat
```

**Comment by RedSoxFan** [comment]
This appears to be a typo:
`input "739:31251:DLL07BE:01_06CB:7A13_Touchpad" {`
`input "1739:31251:DLL07BE:01_06CB:7A13_Touchpad"`

You are missing the first character (`1`) in the block version.

**Comment by luispabon** [comment]
What a plonker :sweat_smile:
