### ISSUE TITLE
Setting multiple input options with xkb_options

### ISSUE THREAD

**Issue by leachim** [swaywm/sway#4152]
* Sway Version:

sway version 1.1-rc2 (May 12 2019, branch 'HEAD')

* Debug Log:

[sway debug log](https://gist.github.com/leachim/dec5299de3628d52aaa98436585dc99e)

* Configuration File:

>input "1452:597:Vinpok_Taptek" {    
>    xkb_options altwin:swap_lalt_lwin    
>    xkb_options ctrl:ralt_rctrl      
>}   

It seems not possible to specify two xkb options in sway. In this case, only the first option is applied. I also tried to change the lines to: 

> xkb_options "altwin:swap_lalt_lwin;xkb_options ctrl:ralt_rctrl" 

but that doesn't seem to work either. I tested with a bluetooth keyboard, and with my laptop keyboard as well. On the laptop, only the second command is applied.

**Comment by leachim** [comment]
Just realizing that this might be closely related to #4151 , possibly a regression?

**Comment by RedSoxFan** [comment]
Try the following (comma separated not space separated):
```
input "1452:597:Vinpok_Taptek" {
    xkb_options "altwin:swap_lalt_lwin,ctrl:ralt_rctrl"
}
```

As for using multiple `xkb_options` lines, the value will be replaced not appended, which is why you are seeing the command one being applied

**Comment by leachim** [comment]
Thanks, that solved it.

**Comment by ArsenyZorin** [comment]
This does not work for me. I tried to swap caps with esc and change layout with physical esc button:
```
input * xkb_layout "us,ru"
input * xkb_options "caps:swapescape,grp:caps_toggle"
```
This config only swaps caps and escape and does not append second option

**Comment by emersion** [comment]
These two options don't work together. You can't map Caps Lock to Esc and then expect Caps Lock to toggle the layout.

**Comment by ArsenyZorin** [comment]
So I have to find some workaroud. Ok. Thanks!
