### ISSUE TITLE
Project wiki example systemd user unit does not work

### ISSUE THREAD

**Issue by cowile** [swaywm/sway#4157]
I have been trying to start sway as a systemd user unit using the example on the [project wiki](https://github.com/swaywm/sway/wiki/Systemd-integration#running-sway-itself-as-a---user-service). Sway does not start at all.

* ~/.config/systemd/user/sway.service:

```
[Unit]
Description=sway - SirCmpwn's Wayland window manager
Documentation=man:sway(5)
BindsTo=graphical-session.target
Wants=graphical-session-pre.target
After=graphical-session-pre.target

[Service]
Type=simple
ExecStart=/usr/bin/sway
```

* Sway Version:

```
{
   "human_readable": "1.0",
   "variant": "sway",
   "major": 1,
   "minor": 0,
   "patch": 0,
   "loaded_config_file_name": "\/home\/$USER\/.config\/sway\/config"
 }
```

* journalctl --user -u sway:

```
May 16 11:52:31 carbon-x1 systemd[963]: Started sway - SirCmpwn's Wayland window manager.
May 16 11:52:31 carbon-x1 sway[27079]: 2019-05-16 11:52:31 - [wlroots-0.5.0/backend/wayland/backend.c:199] Could not connect to remote display: No such file or directory
May 16 11:52:31 carbon-x1 sway[27079]: 2019-05-16 11:52:31 - [wlroots-0.5.0/backend/x11/backend.c:185] Failed to open X connection
May 16 11:52:31 carbon-x1 sway[27079]: 2019-05-16 11:52:31 - [wlroots-0.5.0/backend/session/logind.c:576] Session '893' isn't a graphical session (type: 'tty')
May 16 11:52:31 carbon-x1 sway[27079]: 2019-05-16 11:52:31 - [wlroots-0.5.0/backend/session/direct-ipc.c:35] Do not have CAP_SYS_ADMIN; cannot become DRM master
May 16 11:52:31 carbon-x1 sway[27079]: 2019-05-16 11:52:31 - [wlroots-0.5.0/backend/session/session.c:96] Failed to load session backend
May 16 11:52:31 carbon-x1 sway[27079]: 2019-05-16 11:52:31 - [wlroots-0.5.0/backend/backend.c:282] Failed to start a DRM session
May 16 11:52:31 carbon-x1 sway[27079]: 2019-05-16 11:52:31 - [sway-1.0/sway/server.c:46] Unable to create backend
May 16 11:52:31 carbon-x1 systemd[963]: sway.service: Main process exited, code=exited, status=1/FAILURE
May 16 11:52:31 carbon-x1 systemd[963]: sway.service: Failed with result 'exit-code'.
```

**Comment by ddevault** [comment]
The wiki content is unsupported - if you figure it out, update the wiki. Good luck.

**Comment by boucman** [comment]
it's sway that exits immediately. Not the unit that is not started... It seems to complain that it does not have CAP_SYS_ADMIN
It makes sense that a normal user does not have cap_sys_admin, but I'm not sure why it's needed, nor how it is not needed when launching sway from the shell...

**Comment by ascent12** [comment]
A wayland compositor needs elevated permissions access to /dev/input/*  and CAP_SYS_ADMIN to use a certain privileged operation on GPUs which is required for VT switching to work properly.
If you're logged into a normal systemd login session, we will use logind which handles all of these extra permissions for us, as allows us to run as a completely normal user. However, systemd units don't run inside of your normal login session, so logind isn't going to work. We have to do it the manual way, which means extra permissions (usually suid root).

It's really an upstream systemd issue and there isn't anything we can do about it. I don't know if it's possible to write a unit file which will work robustly in all situations with a Wayland compositor. Another solution is for someone to write a minimal display manager that works with Wayland compositors. I don't think most sway users are going to want to pull in GDM.

**Comment by cowile** [comment]
Thanks for weighing in. This isn't urgent, but it is something of an annoyance I have been looking at on and off. I found some [email tidbits](https://patchwork.freedesktop.org/patch/190638/?series=34525&rev=1) that suggest it should be possible to start a wayland-based WM this way, but not enough to synthesize a working setup.

**Comment by rindeal** [comment]
This isn't systemd issue at all, but logind/wlroots issue. It's the same problem that Xorg devs debated 5 years ago [in this thread](https://lists.x.org/archives/xorg-devel/2014-February/040476.html).

I managed to run sway from a `systemd --user` process by trivially patching wlroots, but not without some annoyances.

Major problem in making all this work is deprecated logind "session-guessing" behaviour as documented [here](https://github.com/systemd/systemd/issues/6852). Sadly, the APIs are still not gone even after 2 years passed.

I'll do some more patching and will see where that leads to.

**Comment by mnussbaum** [comment]
I think you need to set the `XDG_SESSION_TYPE` environment variable to a value of `wayland` such that it's set for your sway systemd unit. I have sway running as a systemd user unit and I have the session type set in `/etc/environment`, but I'm sure there are other places it could be set too. Some docs about that env var can be found [here](http://man7.org/linux/man-pages/man8/pam_systemd.8.html).

Wlroots looks to see if that session type is set [here](https://github.com/swaywm/wlroots/blob/master/backend/session/logind.c#L575), and when it doesn't find a match it's logging `Session '893' isn't a graphical session (type: 'tty')` as you see in your log output.

**Comment by rindeal** [comment]
> I think you need to set the `XDG_SESSION_TYPE` environment variable to a value of `wayland` such that it's set for your sway systemd unit. I have sway running as a systemd user unit and I have the session type set in `/etc/environment`, but I'm sure there are other places it could be set too. Some docs about that env var can be found [here](http://man7.org/linux/man-pages/man8/pam_systemd.8.html).
> 
> Wlroots looks to see if that session type is set [here](https://github.com/swaywm/wlroots/blob/master/backend/session/logind.c#L575), and when it doesn't find a match it's logging `Session '893' isn't a graphical session (type: 'tty')` as you see in your log output.

This works around the problem just halfway. You will get sway running, but it defies the purpose of logind's session type parameter (all sessions will be 'wayland' including tty, ssh, ...) and doesn't solve the issue with the inability to change VTs.

**Comment by boucman** [comment]
is it simply a normal environment variable ? if yes you can set it with Environment= in the service itself, right ?

**Comment by ascent12** [comment]
@rindeal What types of changes to wlroots are you talking about?

**Comment by rindeal** [comment]
> is it simply a normal environment variable ? if yes you can set it with Environment= in the service itself, right ?

The variable is read by pam_systemd not sway, as such it must be set before you even log in.

**Comment by rindeal** [comment]
> @rindeal What types of changes to wlroots are you talking about?

Specifying the ID of a session that should be taken over. The current systemd user unit support code introduced in https://github.com/swaywm/wlroots/commit/c138da233b618ab5d42e4810f1ad7f2e687f2a59 assumes that user is logging in using GDM or something similar.

**Comment by ascent12** [comment]
I wouldn't be opposed to an environment variable doing that. We already have several similar sorts of things for overriding a bunch of our autodetection logic.

**Comment by emersion** [comment]
Isn't there a "standard" env variable for this?

**Comment by ascent12** [comment]
I don't think so? If there already is something established, then sure, use that.
Something along the lines of
```
WLR_LOGIND_SESSION=/org/freedesktop/login1/session/_32 sway
```

**Comment by rindeal** [comment]
> Isn't there a "standard" env variable for this?

There is, check out [this code](https://github.com/swaywm/wlroots/pull/1705).

**Comment by joshuarli** [comment]
@cowile is your user in the `input` and `video` groups?

**Comment by cowile** [comment]
@joshuarli I tried that on your suggestion and got the exact same errors.

**Comment by sternenseemann** [comment]
The issue is that the session related variables are not set in the systemd user service manager's environment (it is started independently from your session).

This is a fundamental issue of sway relying on the current session if you want to run it in an user service, since there is no nice way probably to figure out which session to use etc.

There is however a workaround for this: Before starting your user service, use `systemctl --user import-environment`. This will import any env vars (including the session related ones) into the systemd user service manager's environment.

```bash
systemctl --user import-environment
systemctl --user start sway
```
