### ISSUE TITLE
Crash in RDP backend

### ISSUE THREAD

**Issue by groovyo** [swaywm/sway#4163]
**Version**
sway: 1.1-rc1-8-g578c1956 (May 15 2019, branch 'master')
wlroots: 0.6.0.r9.g461c4f58-1

**Configuration file**
Default at /etc/sway/config

**Debug log & backtrace**
```
#0  0x00007f1eb5b2fecc __memcpy_sse2_unaligned_erms (libc.so.6)
#1  0x00007f1eae0b4103 n/a (radeonsi_dri.so)
#2  0x00007f1eadfc62f7 n/a (radeonsi_dri.so)
#3  0x00007f1eadfc6702 n/a (radeonsi_dri.so)
#4  0x00007f1eb5d12fb3 gles2_read_pixels (libwlroots.so.3)
#5  0x00007f1eb5d0f39d output_commit (libwlroots.so.3)
#6  0x00007f1eb5d334f1 wlr_output_commit (libwlroots.so.3)
#7  0x00005655378264ca output_render (sway)
#8  0x0000565537822387 damage_handle_frame (sway)
#9  0x00007f1eb5d3f04e wlr_signal_emit_safe (libwlroots.so.3)
#10 0x00007f1eb5d3f04e wlr_signal_emit_safe (libwlroots.so.3)
#11 0x00007f1eb5d0f20a signal_frame (libwlroots.so.3)
#12 0x00007f1eb5d8310a n/a (libwayland-server.so.0)
#13 0x00007f1eb5d837f2 wl_event_loop_dispatch (libwayland-server.so.0)
#14 0x00007f1eb5d8239c wl_display_run (libwayland-server.so.0)
#15 0x000056553781ea37 server_run (sway)
#16 0x000056553781df4e main (sway)
#17 0x00007f1eb5ab0ce3 __libc_start_main (libc.so.6)
#18 0x000056553780ff1e _start (sway)
```
[sway-rdp.log](https://github.com/swaywm/sway/files/3195557/sway-rdp.log)
[sway-rdp-bt.txt](https://github.com/swaywm/sway/files/3195558/sway-rdp-bt.txt)

**Steps to reproduce**
At one terminal start sway with RDP backend:
```
WLR_RDP_TLS_CERT_PATH=$CERT_DIR/tls.crt \
WLR_RDP_TLS_KEY_PATH=$CERT_DIR/tls.key \
WLR_RDP_ADDRESS=0.0.0.0 \
WLR_BACKENDS=rdp \
sway -Vd -c /etc/sway/config > sway-rdp.log 2>&1
```
at another terminal run:
`xfreerdp -v localhost --bpp 32 --size 1024x768 --rfx`

Move pointer around in xfreerdp window for some time, sometimes clicks are needed or moving outside/inside the xfreerdp window.
Usually crashes in a few seconds after xfreerdp is started. Also parts of the backgound image is rendered where mouse pointer and sway bar should be.
![screenshot-2019-05-19-230032](https://user-images.githubusercontent.com/5281988/57987502-d63e6680-7a8a-11e9-8f8d-7b9256ecdab1.png)

**Comment by emersion** [comment]
The RDP backend has been removed. Use wayvnc instead.
