### ISSUE TITLE
Sway won't set/display wallpaper

### ISSUE THREAD

**Issue by soymjolk** [swaywm/sway#4164]
Sway version: `sway version 1.1-rc1-3-g9dca18b6 (May  7 2019, branch 'master')`
OS: Arch Linux 5.0.13
Config file: [https://hastebin.com/wayucejuhu.pl](hastebin)
Debug log: [https://hastebin.com/julopajoda.bash](hastebin)

Upon launching Sway, the background is set to a grey colour. I currently have it set in the config file to tile an image in my .wallpapers folder. I have also tried using hsetroot and feh, but they don't work either. I'm not too sure what's going on, and I'd be super appreciative if someone could help me figure it out. Thank you!

**Comment by Emantor** [comment]
Did you install `swaybg`? This is now a separate project because it is not strictly sway specific and can be used with every wlroots compositor.

**Comment by soymjolk** [comment]
> Did you install `swaybg`? This is now a separate project because it is not sway specific and can be used with every wlroots compositor.

I didn't have it installed. Installing `swaybg-git` fixed my problem. Thank you!

**Comment by Arunscape** [comment]
Just came across this as well (version 1.1.1-1 on Arch Linux after a `pacman -Syu`)
commenting to confirm that installing swaybg (at the time, 1.0-2) has fixed the issue :+1:
