### ISSUE TITLE
Cannot scroll with mouse wheel while selecting text

### ISSUE THREAD

**Issue by freb** [swaywm/sway#4172]
Version: `sway version 1.1-rc1-3-g9dca18b6 (May  7 2019, branch 'master')`

[sway-err.log](https://github.com/swaywm/sway/files/3209584/sway-err.log)

I am using the default config.

When I upgraded from version 1.0 stable, the ability to select text (just hold the left mouse button and drag over text) while also scrolling the screen with the mouse scroll wheel stopped working. I use this pretty regularly to accurately select large amounts of text that flow off of the visible page instead of having the page scroll for me as the cursor approaches the bottom or top of the window.

To reproduce the issue, I logged in with the default config file, opened my terminal (urxvt), hit enter a bunch of times, then attempted to scroll while selecting text. It did not work.

Just to be clear, the left mouse button is depressed while trying to scroll with the mouse wheel.

**Comment by samerickson** [comment]
Are you sure that is not an issue with `urxvt`?

**Comment by emersion** [comment]
Can you try to do the same in `weston-eventdemo` and `xev`, and see what is the ordering of the mouseup event and scroll events?

**Comment by freb** [comment]
@samerickson It is not limited to urxvt. It is system wide (Chromium, Sublime Text, Windows VM, etc.). It  I just mentioned urxvt since that is what is simulated in the log. I double checked it isn't my mouse. I jumped into the IRC channel about a week ago and someone else confirm the same issue on a different OS. I'm on Arch, not sure what they were on.

@emersion with `xev` I don't see any mouse wheel events fire while holding down either left or right mouse button. I only see the button down and up events:

```
ButtonPress event, serial 34, synthetic NO, window 0x1e00001,
    root 0x3a1, subw 0x0, time 1323283451, (447,46), root:(2737,757),
    state 0x10, button 1, same_screen YES

# unreported mouse scrolling events here

ButtonRelease event, serial 34, synthetic NO, window 0x1e00001,
    root 0x3a1, subw 0x0, time 1323285195, (447,46), root:(2737,757),
    state 0x110, button 1, same_screen YES
```

In `weston-evendemo` I see the same thing:

```
button time: 1323498982, button: 272, state: pressed, x: 770, y: 33
pointer frame

# unreported mouse scrolling events here

button time: 1323502706, button: 272, state: released, x: 770, y: 33
pointer frame
```

**Comment by emersion** [comment]
Maybe this is a libinput option or something?

**Comment by freb** [comment]
I'll see if I can find anything.

**Comment by gilbertorconde** [comment]
Im having the same issue. Is there anything i can try to help track this problem?

**Comment by DaAngus** [comment]
@gilbertorconde @freb 
I think I found the culprit: 
`smart_gaps on`
If you have one window on the workspace the window fills the screen.
The described bug occurs.

Without smart_gaps the global gaps rules are applied and you can select + scroll as expected.

With smart_gaps the area that determines to scroll down is still there, but only 1px tall.
