### ISSUE TITLE
IPC: get_inputs improvments

### ISSUE THREAD

**Issue by arthurzam** [swaywm/sway#4175]
I'm using sway version `1.1-rc3`.
I'm working on a program that need to interact with sway's IPC. I would like you to enhance the `GET_INPUTS` command:

- A way to print a specific input (for example based on `idVendor` and `idProduct`, or based on full name - any will be welcomed).
- An event for inputs change (for example `xkb_active_layout_name` change, disconnection).

I want to know what are your thoughts about those additions (I prefer the second one, but I think it is more difficult to implement than the first one). If you are positive about the first one, I might be able to implement it (I understand we need to add `if` before [this](https://github.com/swaywm/sway/blob/master/sway/ipc-server.c#L744) line, and to parse the request to know the wanted filter).

**Comment by emersion** [comment]
What is your use-case?

**Comment by arthurzam** [comment]
The use case is querying every second the value of `xkb_active_layout_name` of a specific keyboard. The keyboard `vendor` and `product` are known. It is of course possible to parse and traverse all the JSON output, but is redundant.
The best way I can think of better querying is to parse the IPC payload as an array of `vendor` and `product`, thus backward compatible and supports filter query.

**Comment by emersion** [comment]
>I'm working on a i3status like application.

Okay, so you want to display the current layout in your bar?

>but is redundant.

I don't get it. You mean you need to parse all input devices and check their vendor/product?

If so, I don't think that's a concern for us. Worst case scenario, you need to iterate over 10 or 20 elements.

>An event for inputs change 

This would need to be consistent with the existing output event.

**Comment by arthurzam** [comment]
Yes, this is mostly the case.
I thought we can optimize `GET_INPUTS` case using filtering on server side (sway IPC) which is quite basic and in my opinion the expected way.

About the event of input change, I don't really know how to design it. I agree it should be consistent.

**Comment by emersion** [comment]
>I thought we can optimize GET_INPUTS case using filtering on server side (sway IPC) which is quite basic and in my opinion the expected way.

-1, for the reasons explained above. Moving the filtering of a few elements in sway provides almost no value.

>About the event of input change, I don't really know how to design it. I agree it should be consistent.

It's not clear when the [i3 output event](https://i3wm.org/docs/ipc.html#_output_event) is emitted. It would be helpful if someone could check exactly when it's emitted in i3 (hotplug, unplug, position/mode change, etc).

**Comment by arthurzam** [comment]
I don't exactly understand why are you against some basic filtering, but I guess you understand better the policy of changing Sway's protocols.
Thank you for your fast and informative reply.
