### ISSUE TITLE
Sway not working with DisplayLink devices

### ISSUE THREAD

**Issue by swinny89** [swaywm/sway#4176]
Not really a bug report as much as a feature request. Looks like Gnome/mutter is the first Wayland compositor to solve the issue, and maybe a similar solution can be done for sway?

https://gitlab.gnome.org/GNOME/mutter/merge_requests?scope=all&utf8=%E2%9C%93&state=merged&author_username=ppaalanen

https://gitlab.gnome.org/GNOME/mutter/merge_requests?scope=all&utf8=%E2%9C%93&state=merged&author_username=epm

**Comment by ddevault** [comment]
This bug belongs with [wlroots](https://github.com/swaywm/wlroots), not sway. But I thought we already supported this.

**Comment by swinny89** [comment]
@ddevault It does not seem to be working for me, but maybe I just don't know what I am doing. Is there somewhere I can find information on using DisplayLink with wlroots/sway? Or is this supposed to be working out of the box?

**Comment by ddevault** [comment]
It should just work OOTB. If you have issues, take it to the wlroots tracker.

**Comment by spaceone** [comment]
This hit me, too. For google searchability here are the symtoms:
```
swaynag: swaynag/swaynag.c:390: swaynag_setup: Assertion `swaynag->compositor && swaynag->layer_shell && swaynag->shm' failed.

Aborted (core dumped)
```
