### ISSUE TITLE
Sway tabs can change height and cause app redraws

### ISSUE THREAD

**Issue by luispabon** [swaywm/sway#4179]
* Open firefox
  * Enable sway tabbed mode
  * Open two tabs
  * Load google in one
  * Load https://github.com/svenstaro/rofi-calc in the other 

The second tab has a calculator utf character that's taller than usual, making the sway tab taller when you choose the corresponding firefox tab. This in turn makes the firefox window smaller and causes a redraw which looks like flickering.

Sway 1.1rc2, FF67 (official ubuntu 19.04 package, running in wayland. Also happens via xwayland tho) .

Video:
https://www.youtube.com/watch?v=Nl95q1Zt05w

Screenshots:
![image](https://user-images.githubusercontent.com/6388823/58328817-fa9f9780-7e2a-11e9-91f0-c920a3f2eceb.png)
![image](https://user-images.githubusercontent.com/6388823/58328839-02f7d280-7e2b-11e9-8b0d-f85b3bc8be1d.png)

**Comment by cyberhuman** [comment]
This issue has been reported several times already #4107, #3719, #3114.
I'm quite annoyed by this behaviour, too, but AFAIU the recommendation is to tweak FontConfig :-(

**Comment by johnae** [comment]
Yeah this issue hasn't always been an issue in sway. At least not one I've encountered. Until now when it happens all the time.
When it does happen I can get the tabs back to the proper size by fullscreening / unfullscreening. I'm not sure but it seems to at least happen more frequently when connected to external display - in which case scale on that is 1.0 and internal display is 2.0. I'm on an Dell XPS 13 9370.

**Comment by ddevault** [comment]
This is by design. Consult the font config guides for your distro.

**Comment by luispabon** [comment]
I disagree this is a fontconfig issue. Window sizing is the window
manager's remit.
