### ISSUE TITLE
Allow bindsym --locked for existing bindsyms

### ISSUE THREAD

**Issue by clarfon** [swaywm/sway#4183]
My keyboard has only one key for play/pause, and in most cases this runs `playerctl play-pause`. However, I'd like to have it run `playerctl pause` *only* when on a lock screen, e.g. let you pause the player but not start it back up again until locked.

For this, it'd be nice if we had an option to `bindsym` the version for an unlocked screen in addition to `bindsym --locked`, so that we can run different scripts when on the lock screen and not. I figure that there are more examples than this one but it'd be a cool functionality to add regardless.

**Comment by RedSoxFan** [comment]
You should be able to just use (order shouldn't matter):
```
bindsym XF86PlayPause exec playerctl play-pause
bindsym --locked XF86PlayPause exec playerctl pause
```

**Comment by clarfon** [comment]
…that is a much better idea.

I should also add that currently, doing this does not work, and the bindings just conflict with each other.

**Comment by RedSoxFan** [comment]
> …that is a much better idea.
> 
> I should also add that currently, doing this does not work, and the bindings just conflict with each other.

For some reason, I thought it was already possible. Anyway, I submitted the change as #4187.

> Also FWIW the key is just called `XF86Play` even though the button should be `XF86PlayPause`.

Ah, I typed that reply from my phone and was trying to go off of memory.
