### ISSUE TITLE
Swaynag requires the mouse

### ISSUE THREAD

**Issue by samerickson** [swaywm/sway#4184]
It would be really nice to have the ability to use `swaynag` without forcing the user to use a mouse.

I.E. pressing Enter results in closing the message, and pressing left and right arrows would allow for toggling through available options.

**Comment by smlx** [comment]
you can achieve this by replacing your use of swaynag with dmenu, rofi etc.
what are you actually trying to achieve with swaynag?

**Comment by RedSoxFan** [comment]
Related https://github.com/swaywm/wlr-protocols/issues/32

**Comment by keithbowes** [comment]
I use zenity to produce messages, and they're accessible with both a keyboard and mouse.  I've even replaced that "do you really want to exit?" message with zenity.  However, swaynag is still used to inform me of errors in config files, and I have to use the mouse to see exactly what the errors are.

**Comment by samerickson** [comment]
Thanks for the info @keithbowes

**Comment by b0o** [comment]
I've written a little wrapper script which allows for interacting with swaynag with the keyboard: https://github.com/b0o/swaynagmode

**Comment by PopeRigby** [comment]
@samerickson I think this issue should be re-opened, because it still isn't fixed.

**Comment by ohk2kt3t4** [comment]
FYI, the same request was recently rejected by i3: https://github.com/i3/i3/issues/4248

I have been using swaynagmode as a workaround

**Comment by tokyo4j** [comment]
FWIW, labwc now has a fork of `swaynag` called `labnag` and we're implementing keyboard control on top of it: https://github.com/labwc/labwc/pull/3120
