### ISSUE TITLE
Core dump when logging out

### ISSUE THREAD

**Issue by boyerjohn** [swaywm/sway#4186]
Distro: Arch Linux
Sway version: 1.0-8

I don't use an NVIDIA GPU.

I wasn't able to reproduce this issue, but it happened when I was logging out with the following hotkey:
```
bindsym $mod+Shift+e exit
```

I only had Firefox and a terminal open when exiting.

Config: https://pastebin.com/A9Yc4svJ

Stack trace:
```
Process 562 (sway) of user 1000 dumped core.

Stack trace of thread 562:
#0  0x00007f1a292301c3 wl_list_insert (libwayland-server.so.0)
#1  0x00007f1a291e9e8b n/a (libwlroots.so.2)
#2  0x00007f1a291c5084 wlr_seat_destroy (libwlroots.so.2)
#3  0x00007f1a2922bcdf n/a (libwayland-server.so.0)
#4  0x00007f1a2922c467 wl_display_destroy (libwayland-server.so.0)
#5  0x00005653dbb6595b n/a (sway)
#6  0x00005653dbb63476 n/a (sway)
#7  0x00007f1a2982cce3 __libc_start_main (libc.so.6)
#8  0x00005653dbb639ae n/a (sway)
```

**Comment by emersion** [comment]
Needs a better stack trace (sway wasn't built with debugging symbols).

**Comment by ddevault** [comment]
If you can't reproduce and can't get a dump with symbols... there's nothing we can do.

**Comment by boyerjohn** [comment]
I figured as much, but unfortunately this has only ever happened once and all my attempts to reproduce it have failed.
