### ISSUE TITLE
us international keyboard altgr dead keys

### ISSUE THREAD

**Issue by k-dannemand** [swaywm/sway#4190]
I apologize if this is the wrong place to ask.

But I really want to use sway and I have already set it up so I'm ready to use it as a dailydriver. BUT I can't get "US International AltGr dead keys" to work !.
and thats a deal breaker for me :(

so please can someone to help me get this to work so i can start using sway!

**Comment by emersion** [comment]
Please ask about this in the IRC channel.

**Comment by k-dannemand** [comment]
@emersion thanks will do .

**Comment by nschloe** [comment]
I need this too. Can you, for the sake of completeness, post the solution here?

**Comment by markstos** [comment]
Example:

```
input type:keyboard {
    xkb_layout us
    xkb_variant altgr-intl
    # Make Capslock work as additional control.
    xkb_options ctrl:nocaps
    # Press Alt+Shift to cycle through keyboard layouts
    # Full list of combinations that can be used for switching is here:
    # https://man.archlinux.org/man/xkeyboard-config.7#Switching_to_another_layout
    xkb_options grp:alts_toggle
}
```
