### ISSUE TITLE
Drag-n-drop breaks session-wide if dropping in gap

### ISSUE THREAD

**Issue by kennylevinsen** [swaywm/sway#4196]
## Usual details
* Sway Version: swaymsg version 1.1-rc1-21-g49258829 (May 30 2019, branch 'master')
* Configuration File:
```
gaps inner 8px
```

## Reproduction
From any application (tested nautilus, firefox-nightly with MOZ_ENABLE_WAYLAND=1):
1. Initiate drag and drop with any item
2. Drop in the gap around the window

## Actual result
Drag-n-drop operation freezes, with the "drag" hanging. Drag and drop no longer works in the session.

## Expected result
Cancelled drag-n-drop operation.

**Comment by Xyene** [comment]
I just tried this on master with nautilus and Firefox, and drag-n-drop didn't bail afterwards. I'm guessing whatever was broken got patched since 1.1.
