### ISSUE TITLE
Can't configure the hot key to change the keyboard layout

### ISSUE THREAD

**Issue by HardDie** [swaywm/sway#4200]
* Sway Version:
sway version 1.0

* Debug Log:
https://pastebin.com/fwj5BewL
-> Jump to second desktop
-> Open console
-> Typing text (Eng)
-> Press Ctrl+Shift
-> Typing text (Eng)
-> Press and hold Shift
-> Typing text (Can)

* Configuration File:
https://github.com/HardDie/My_linux_settings/blob/master/.config/sway/config

I can't configure the hot key to change the keyboard layout.
I installed grp:ctrl_shift_toggle, and then press this combination, nothing happened.
But if I press and hold the Shift key, the keyboard layout will change from English to Canadian with capital letters, but after release the layout will again be in English.
I tried the same thing with grp:caps_toggle and the behavior was the same.

**Comment by RedSoxFan** [comment]
On the wayland and DRM backends, everything works fine for me. However, on the x11 backend, there appears to be some conflict. By looking at `watch -n0.1 swaymsg -t get_inputs`, I can see that both `shift` and the configured `xkb_options` setting will change the layout, but it flickers back and forth. Not sure what the fix is.

**Comment by HardDie** [comment]
How can I check which sway backend is using right now? And how to run Wayland instead of X11, if it is used?

**Comment by emersion** [comment]
As a user, you should always be running with the DRM backend. Wayland and X11 backends are useful for debugging.

**Comment by HardDie** [comment]
Then I don't understand how to solve my problem

**Comment by emersion** [comment]
Try using `xkb_variant` instead of `(eng)`

**Comment by HardDie** [comment]
I tried setup `xkb_variant "eng,ca(eng)"` and  `xkb_variant "eng,ru"` but change layouts stop works at all.
Could you please give me an example of using xkb_variant? Maybe I'm doing something wrong

**Comment by emersion** [comment]
```
xkb_layout "us,ca"
xkb_variant ",eng"
```

**Comment by HardDie** [comment]
Oh, I understand what the problem is.
I forgot that I start the session with the startx command and put the `exec sway` in xinitrc.
Replaced startx with sway and everything works fine.

But still it looks like a bug?

**Comment by emersion** [comment]
That's really not how you should use sway. This is a completely unsupported setup.

Instead, just run `sway` from a TTY.
