### ISSUE TITLE
wacom tablet support

### ISSUE THREAD

**Issue by newincpp** [swaywm/sway#4206]
Hello,
I have a wacom intuos 2 working perfectly on most systems. but in sway I have multiple problems with it:

BTN_STYLUS and BTN_STYLU2 are both interpreted as right click.
None of the other button are doing anything.

libinput debug-events is detecting those input without problems despite those problems so I'm guessing the problem is on sway side.
I would have gladly remap the inputs myself like I would have done with X11 but it seems there is no such features with sway. All the bindsym stuff I tried didn't help.

**Comment by cafehaine** [comment]
Same on my huyon tablet
