### ISSUE TITLE
Release 1.1.1 reports itself as 1.0

### ISSUE THREAD

**Issue by danielotero** [swaywm/sway#4211]
I think is due to the fact that you forgot to update the [`meson.build`](https://github.com/swaywm/sway/blob/1.1.1/meson.build#L4) file before the tagging.

https://github.com/swaywm/sway/blob/e1c4104d020d0cc3f07c618706fbddd05f4daf9a/meson.build#L3-L5

Both `sway --version` as `swaymsg -t get_version` report "1.0".

**Comment by ddevault** [comment]
Too late to fix it. That's life

**Comment by danielotero** [comment]
That was fast! I guess it doesn't deserve a 1.1.2 :rofl: 

A suggestion to avoid this mistake in the future is to bump the version number as soon as you do the release.

Anyways, thank you all for your work.
