### ISSUE TITLE
FreeBSD no libinput 1.1-RC3

### ISSUE THREAD

**Issue by copypaste10** [swaywm/sway#4212]
Hi there,

on Linux Sway works fine. I tried to run Sway on FreeBSD but did not succeed. I keep getting those errors:
https://imgur.com/e7nWD5V

What I did? Installed drm-kmod, added user to video-group and exported /tmp as environment dir. The problem is libinput, which seems not functioning. If I open sway without libinput then Sway opens but I get no inputs. What to do? (libinput and evdev are already installed)

I also realized there is no /etc/sway/ after installing Sway by "pkg install sway". I had to copy my config from Linux.

**Comment by ddevault** [comment]
This is a FreeBSD bug, not a sway bug. Speak to the maintainers of the sway package on FreeBSD.
