### ISSUE TITLE
[intel/iris] [backend/drm/atomic.c:55] eDP-1: Atomic commit failed (modeset): Permission denied

### ISSUE THREAD

**Issue by colemickens** [swaywm/sway#4215]
I saw the other Intel Iris related issue was closed. I think this is different. I know very little about graphics, particularly in Linux, so I'm not sure if this is an issue with Mesa, Iris, Sway, etc.

**Please also note this is a pre-release version of Mesa**. However, I'm hoping it doesn't hurt to have an issue open to discuss this, especially since it seems to partially work and someone else in IRC said it was working flawlessly for them.

After starting Sway, the mouse cursor is drawn, but nothing else. When I hit `$mod+Enter`, I can see that the terminal is started based on the cursor changing, but the getty console still shines through instead of any sway drawing (other than the cursor).

The sway log is filled with this:
```
2019-06-04 18:29:18 - [backend/drm/atomic.c:55] eDP-1: Atomic commit failed (modeset): Permission denied
2019-06-04 18:29:18 - [backend/drm/util.c:202] Unable to add DRM framebuffer: Invalid argument
2019-06-04 18:29:18 - [backend/drm/atomic.c:55] eDP-1: Atomic commit failed (modeset): Permission denied
2019-06-04 18:29:18 - [backend/drm/util.c:202] Unable to add DRM framebuffer: Invalid argument
2019-06-04 18:29:18 - [backend/drm/atomic.c:55] eDP-1: Atomic commit failed (modeset): Permission denied
2019-06-04 18:29:18 - [backend/drm/util.c:202] Unable to add DRM framebuffer: Invalid argument
```

Actually, it starts with lots of those lines, despite running sway like this:

```
sway -c ~/.config/sway/config-stock -d &> sway.log
```

and then I've pasted the log: https://gist.github.com/b2057033c74bd91b5d24a203db85dee2

Version information:
```
[cole@xeep:~]$ sway --version
sway version 799f5a2cd5ffa83d73816489aa8683564bc226f7

[cole@xeep:~]$ swaymsg -t get_version
sway version 799f5a2cd5ffa83d73816489aa8683564bc226f7

[cole@xeep:~]$ cat ~/code/nixpkgs/pkgs/development/libraries/mesa/default.nix | rg "version ="
  version = "19.1.0-rc3";

[cole@xeep:~]$ cat ~/code/nixpkgs/pkgs/development/libraries/libdrm/default.nix | rg "name ="
  name = "libdrm-2.4.98";

```

**Comment by ascent12** [comment]
Are you running with logind or the direct session?
I would say reasonably close to the start of the log but you didn't post it.

Also, since we're getting errors from kernel interfaces, a DRM kernel log would be helpful.
```sh
echo 0xff | sudo tee /sys/module/drm/parameters/debug
```
Note, that doing this enable EXTREMELY spammy kernel log messages.
Reproduce your error as quickly as you can, then disable it with
```sh
echo 0x00 | sudo tee /sys/module/drm/parameters/debug
```
By doing it quickly, there will be far fewer messages that needed to be sifted through.

Retrieve the logs with `journalctl -k -b` or `dmesg`.

**Comment by colemickens** [comment]
Hrm. I had pasted the gist link to the log above, but I think I uploaded the wrong log from a wrong local dir here? I can't explain how I uploaded a partial log... but I'm getting a "normal" looking Sway log now. I've attached it along with the relevant dmesg output.

Approximately what I did was this:
```
sudo dmesg --clear
echo 0xff | sudo tee /sys/module/drm/parameters/debug; sway -d &>sway.log; echo 0x00 | sudo tee /sys/module/drm/parameters/debug
dmesg > sway.dmesg.log
```

When Sway started:

1. The getty console contents remained, the cursor appeared, and the display began to redden. (`exec redshift` is in my sway config).
2. I pressed `$mod+Return`, saw the cursor change to an I beam.
3. I pressed my hotkey to quit, `$mod+Ctrl+Alt+Delete`, Sway exitted. The screen flashed black and then a darker version of the same screen contents, sans mouse, returned.

and then I've attached both `sway.log` and `sway.dmesg.log` here:
* [sway.log](https://github.com/swaywm/sway/files/3255483/sway.log)
* [sway.dmesg.log](https://github.com/swaywm/sway/files/3255479/sway.dmesg.log)

**Comment by ascent12** [comment]
```
[18494.726393] [drm:drm_ioctl [drm]] pid=922, dev=0xe200, auth=1, DRM_IOCTL_MODE_ADDFB2
[18494.726433] [drm:intel_framebuffer_init [i915]] No Y tiling for legacy addfb
[18494.726446] [drm:drm_internal_framebuffer_create [drm]] could not create framebuffer
[18494.726454] [drm:drm_ioctl [drm]] pid=922, ret = -22
```
That would do it. I was intending to complete modifier support as part of the wlroots renderer work, but there is no harm in adding this part now.

Can you try out wlroots compiled with https://github.com/swaywm/wlroots/pull/1715 and see if that fixes it for you?

**Comment by colemickens** [comment]
I checked this a few times:
* https://github.com/swaywm/wlroots/pull/1715 does NOT fix this (similar/same logs)
* https://github.com/swaywm/wlroots/pull/1641 DOES fix this

If you want to check my work: https://github.com/colemickens/nixpkgs-wayland/blob/wlroots-temp/pkgs/wlroots/default.nix#L29

**Comment by colemickens** [comment]
Thanks folks, this was fixed with the merge in wlroots: https://github.com/swaywm/wlroots/pull/1715

**Comment by colemickens** [comment]
Rather, this is the one that was merged: https://github.com/swaywm/wlroots/pull/1641
