### ISSUE TITLE
fullscreen scratchpad lost

### ISSUE THREAD

**Issue by swalladge** [swaywm/sway#4216]
In sway 1.0, I could use the following config to have a fullscreen scratchpad window, that stayed fullscreen on toggling scratchpad:

```
bindsym Mod4+Ctrl+minus move scratchpad, scratchpad show, fullscreen enable
```

With sway 1.1, subsequent calls to `scratchpad show` changes the window size back to the default scratchpad size, losing fullscreen.

Curious to know what the expected behaviour of this is. Either way, the update broke my workflow and I'm keen for either a workaround or a fix. :)

**Comment by RedSoxFan** [comment]
The behavior you are currently experiencing is the expected behavior. It was changed to match i3.

As far as a workaround, I can't think of anything.

**Comment by RedSoxFan** [comment]
Now that #4218 is merged,  the following should work (if building from git master). It may be possible to come up with something more elegant though
```
# Make fullscreen scratchpad
bindsym Mod4+Ctrl+minus mark --add __temp, move scratchpad; [con_mark="^__temp$"] scratchpad show, fullscreen enable, unmark __temp; exec swaymsg -- mark --add __fs_$(date +%s)

# Toggle scratchpad, retaining fullscreen
bindsym Mod4+minus scratchpad show; [con_mark="^__fs_.*$"] fullscreen enable

# Remove fullscreen retention
bindsym Mod4+Mod1+minus fullscreen disable, exec swaymsg -t get_tree | jq '.. | objects | select(.focused) | .marks[] | select(test("__fs"))'  | xargs -r swaymsg unmark
```

**Comment by swalladge** [comment]
Awesome, thanks! That works perfectly. I added the `-n1` flag to xargs for unmarking though, to handle the case where multiple marks were accidentally added.
