### ISSUE TITLE
grey background

### ISSUE THREAD

**Issue by swalladge** [swaywm/sway#4217]
* Sway Version: 1.1.1

Background on all outputs is grey. Setting a background color or filename via config or swaymsg does not change the background.

This issue was introduced after I upgraded from version 1.0.

**Comment by RedSoxFan** [comment]
Install swaybg (https://github.com/swaywm/swaybg). It has been extracted to a separate project in 1.1

**Comment by swalladge** [comment]
Oh right, thanks! I guess I should have read the release notes...
