### ISSUE TITLE
Criteria Application

### ISSUE THREAD

**Issue by crondog** [swaywm/sway#422]
With for_window (and eventually assign when implemented) the criteria matching on a new view sets the focus to the new view so it can apply the rest of the commands https://github.com/SirCmpwn/sway/blob/master/sway/handlers.c#L221 

This means that `for_window [class="st-256color"] move container to workspace 5; split toggle` for example will always focus my terminal if i am on another workspace which is not what I always want (or what i3 does for that matter)

**Comment by SirCmpwn** [comment]
I'm closing issues that are resolved by the yet-unreleased sway 1.0.
