### ISSUE TITLE
Screen is black after turning the monitor off and on

### ISSUE THREAD

**Issue by AN3223** [swaywm/sway#4227]
sway version 1.0

Configuration:
  Default

Steps to reproduce:
  1. Start Sway
  2. Turn monitor off
  3. Turn monitor back on

Expected result:
  I should see the desktop

Actual result:
  Backlight turns on but the screen is just black. Pressing keys doesn't do anything, and I can't switch to a different TTY.

Workaround:
  I can switch to a different TTY beforehand, turn the screen off, turn the screen back on, and then return to the TTY running Sway.

[sway.log](https://gist.github.com/AN3223/70beeb3d1911109d73f0c981f817fbfa)
(this got lost when copying the logs into Firefox: when I view the logs in Less or Vim it has a bunch of ^@ repeated at the bottom, I'm not sure if that's significant at all)

Additional information:
  Out of curiosity I tried the command `swaymsg "output * dpms off" && swaymsg "output * dpms on"` and it turned the screen off and on properly. However introducing a sleep in between, like `swaymsg "output * dpms off" && sleep 5 && swaymsg "output * dpms on"` will result in a black screen.

**Comment by emersion** [comment]
The log doesn't contain the part where the `dpms` command is handled.

Also, please generate minimal logs: start sway, reproduce, stop sway, upload logs. No need for Firefox, it'll only clutter the logs.

**Comment by AN3223** [comment]
> The log doesn't contain the part where the `dpms` command is handled.

I turned off my monitor via the power button during the first logs, calling dpms was in a separate session, sorry I should have mentioned this before. Here's a session where I just open sway, open a terminal, run `swaymsg "output * dpms off" && sleep 5 && swaymsg "output * dpms on"`, receive a black screen, and then stop sway:
[sway.log2](https://gist.github.com/AN3223/fe6ab8d73b0d133b22a0c41078020fab)

**Comment by emersion** [comment]
```
2019-06-08 14:13:25 - [wlroots-0.5.0/backend/drm/atomic.c:55] HDMI-A-1: Atomic commit failed (modeset): Invalid argument
```

Could you try getting a DRM debug log?

```sh
sudo dmesg -C
echo 0xff | sudo tee /sys/module/drm/parameters/debug
swaymsg "output * dpms off" && sleep 5 && swaymsg "output * dpms on"
sleep 2
echo 0x00 | sudo tee /sys/module/drm/parameters/debug
dmesg >dmesg.log
```

**Comment by AN3223** [comment]
[dmesg.log](https://gist.github.com/AN3223/52e597e72795665895b84be250e7f2fc)
[sway.log3](https://gist.github.com/AN3223/1fc0a2d87a65b379581f990dee5e7aec)

**Comment by emersion** [comment]
Looks like we don't have enough data. New plan: run `dmesg -w >dmesg.log` before reproducing the bug, stop it right after the bug has been triggered. Bonus points if you do it quick so we don't have a 10MB log.

**Comment by AN3223** [comment]
[sway.log4](https://gist.github.com/AN3223/969d0219f8f8b959bcc40df48ba374a8)
[dmesg.log2](https://gist.github.com/AN3223/29a9fae6aa1dbe426a915171ec752091)
[and the commands I ran, just in case](https://gist.github.com/AN3223/15c3ff7176241528b0b278abeafa73e5)

**Comment by emersion** [comment]
>and the commands I ran, just in case

LGTM

>dmesg.log2

Bleh, I can't find any error in there…

**Comment by AN3223** [comment]
On a whim I updated my kernel from 4.19.49-1-MANJARO to 5.1.8-1-MANJARO, tested before and after, and now this seems to work as expected. No more black screen!

**Comment by RedSoxFan** [comment]
@AN3223, since it sounds like this was a kernel issue, can this be closed or is there still something unresolved that I'm missing?

**Comment by AN3223** [comment]
> @AN3223, since it sounds like this was a kernel issue, can this be closed or is there still something unresolved that I'm missing?

Everything is good now, I'll close the issue.

**Comment by matthiasak** [comment]
> > The log doesn't contain the part where the `dpms` command is handled.
> 
> I turned off my monitor via the power button during the first logs, calling dpms was in a separate session, sorry I should have mentioned this before. Here's a session where I just open sway, open a terminal, run `swaymsg "output * dpms off" && sleep 5 && swaymsg "output * dpms on"`, receive a black screen, and then stop sway:
> [sway.log2](https://gist.github.com/AN3223/fe6ab8d73b0d133b22a0c41078020fab)

I have had issues with say not turning screen back on if I leave the machine and come back later. It could be related to swaylock, or wlroots itself, but adding an exec call to the sway config has fixed my 3-screen setup.

```
$ tail -n 5 ~/.config/sway/config 
exec xrdb -load ~/.Xresources
exec blueman-tray
exec swaymsg "output * dpms on"
#exec systemctl restart bluetooth
include /etc/sway/config.d/*
```
