### ISSUE TITLE
input: add option for device classes

### ISSUE THREAD

**Issue by felipec** [swaywm/sway#4230]
I can do a sane configuration like this:

    input 1267:12341:ELAN1301:00_04F3:3035_Touchpad tap enabled

But what if I want to use this configuration in different machines? I would expect to be able to do:

    input touchpad tap enabled

In fact I don't see why this isn't the default (along with naturall_scroll), but oh well.

**Comment by RedSoxFan** [comment]
For Sway 1.1 (or building from git master), you can use `input type:touchpad tap enabled`

> In fact I don't see why this isn't the default (along with naturall_scroll), but oh well.

Defaults are set by libinput. Sway does not touch these unless requested by the user.

**Comment by felipec** [comment]
> Defaults are set by libinput. Sway does not touch these unless requested by the user.

I know the wrong defaults are set by libinput.

**Read** my request before closing:

> input: add option for device classes

Do I have to repeat what my request is? I'm asking to add an option to to configure a class of input devices, instead of a single device.

So that this works:

> input touchpad tap enabled

For all devices of class "touchpad".

Your comment about the defaults is a red herring and has nothing to do with the issue I opened.

**Comment by FreeFull** [comment]
Perhaps you should read the first part of Red's comment again. This feature already exists in Sway 1.1 and above.

**Comment by felipec** [comment]
Whoops! Since I didn't see the blockquote I skipped that part.

**Comment by emersion** [comment]
Please be nice @felipec. Even if the issue was closed by mistake there's no need to be rude.
