### ISSUE TITLE
titlebar settings per output

### ISSUE THREAD

**Issue by razic** [swaywm/sway#4231]
hello :) thanks for sway! its great.

i'd love to be able to use the `font`, `titlebar_border_thickness`, and `titlebar_padding` commands with `output` somehow.

for example, with swaybar i can fully customize each bar, and restrict them to certain outputs.

it seems like right now titlebar settings are applied globally. i might be able to implement it if you think it's possible. what do you think?

**Comment by razic** [comment]
i've been thinking a bit more about this. while i would personally be happy with just being able to change the font size for titlebars on a per output basis, i'm also curious about your thoughts on more styling options in general. waybar is a gtk app, so it loads a css context, making styling super easy. would having the ability to put a gtk app in the titlebars like we can with sway be feasible? if not, is css is out of the question too? i wonder what kind of implications, if any, all this might have on the tree geometry.

i just [got this merged](https://github.com/Alexays/Waybar/pull/373) on waybar which adds a css class with the name of the output the bar is on. this gives me the ability to change the font size for each bar which is sorely needed to support multi-head setups with mixed resolutions. even with integral output scaling, you'll want to scale down the fonts as mentioned in `sway-output(5)`.

wdyt?

**Comment by ddevault** [comment]
No thanks, I think the complexity/value-add ratio on this isn't good enough.

**Comment by razic** [comment]
@ddevault Can you please give a bit more feedback here.

This is in the sway docs:

```bash
You may be better served by setting an integral scale factor
and adjusting the font size of your applications to taste.
```

While each application I use does give me this support, the titlebars of sway does not (which is inconsistent with other parts of sway like the swaybar). I personally prefer to use the native stacking and tabbing in sway, which means that setting the application font size doesn't help.

If you don't want to put an entire CSS processor into each titlebar, fine, but at least let me change the font size per output and not globally. I run a 27" 4k monitor next to a 27" 1440p monitor and without the ability to scale the titlebar fonts, I'm screwed.

What do you think?
