### ISSUE TITLE
Sway and wlroots rebuild in official repositories?

### ISSUE THREAD

**Issue by copypaste10** [swaywm/sway#4232]
Hello,
Somewhere you wrote to rebuild wlroots whenever the sway package gets an update. Is it necessary to do so when you get updates of official repositories of Fedora, Arch and so on? There's a sway package in the community repository of Arch Linux.

**Comment by emersion** [comment]
You should either install sway *and* wlroots from your official repo, or install both manually. If you choose to install them manually, you also need to update them together.
