### ISSUE TITLE
Performance issues with "seat seat0 cursor set x y"

### ISSUE THREAD

**Issue by sloonz** [swaywm/sway#4233]
* Sway Version: `sway version 1.1.1`

Freshly compiled from git tag "1.1.1", since weirdly sway-1.1.1 on ArchLinux gives 1.0 to swaymsg -t get_version and sway -v

* Debug Log: https://pastebin.com/f8hq6yCd

Note that I removed ~ 2 MB worth of repeating lines (replaced them by --SKIP--)

* Configuration File: Bug also happen in default configuration

I want to be able to simulate smooth mouse movement from a script.

Under i3/X, I use [xte](https://linux.die.net/man/1/xte). I thought I could just `swaymsg -t command seat seat0 cursor set x y` to achieve the same result with Sway.

Unfortunately, it doesn’t works. Sending ~60 such commands per second (for visual smoothness) makes Sway use 100% of CPU, with the cursor moving only ~1-2 times per second and the terminal instance running the script (tested both with alacritty and xterm) ending up getting killed.

Here is a Python script reproducing the issue : https://gist.github.com/sloonz/865f49654a7d64d0500debe0b6e75661

It basically tries to smoothly move the cursor on a circle of radius 300 px centered around (500, 500) at 1 turn/second. Running it results in a non-smooth movement, Sway using huge amount of CPU, and the terminal running the script getting killed.

**Comment by sloonz** [comment]
Note that commenting https://github.com/swaywm/sway/blob/f0f5de9a9e87ca1f0d74e7cbf82ffceba51ffbe6/sway/commands/seat.c#L50 (input_manager_apply_seat_config) "fixes" the issue.

**Comment by emersion** [comment]
We might need to get a bitmask of pending seat configuration fields, to only apply those.

**Comment by emersion** [comment]
Actually just a flag to say whether the seat config has changed would be enough.
