### ISSUE TITLE
crash on config reload with standard config /etc/sway/config

### ISSUE THREAD

**Issue by Tormen** [swaywm/sway#4234]
* **Sway Version**: `sway version 1.1-rc1-32-g4d93b96b (Jun  8 2019, branch 'master')`

* **Debug Log**: of `sway -d -c /etc/sway/config &>sway.log`: http://sprunge.us/FpdsHK

* **Configuration File**: `/etc/sway/config` http://sprunge.us/Wq5ZxM

* **Steps to reproduce**:
 1.) start sway as user `me` with standard config: with `sway -d -c /etc/sway/config`
 2.) issue config reload by pressing default keyboard shortcut `$mod+Shift+c`
 3.) sway crashes

* **Stack Trace**, if sway crashes:
    `coredumpctl gdb sway` with `bt full`: http://sprunge.us/OaK0zK

* **Remarks**:
```
-rw-r--r-- 1 root root 6740 Jun  8 19:44 /etc/sway/config
drwxrwx--- 1 root root    0 Jun  8 19:46 /etc/sway/config.d
```
So I tried `chmod 755 /etc/sway/config.d` but same same: crash.
FYI: There are no files under /etc/sway/config.d.

**Comment by Emantor** [comment]
As far as I can see this seems to be some kind of race with the transactions. Can you reproduce with: ```
meson build -Db_sanitize=address
```
Than I can get a better idea about the race.

**Comment by Tormen** [comment]
I did build it from hand with and without `-Db_sanitize=address` , but can't reproduce :(

Not sure why not :(

So I am moving on to next crash which I actually wanted to report, when I ran into this problem since yesterday.
