### ISSUE TITLE
Shift key issue on CM Storm Quickfire Pro Ultimate keyboard

### ISSUE THREAD

**Issue by quej1976** [swaywm/sway#4251]
sway version 1.1-rc1-40-g9670ccee (Jun 13 2019, branch 'master')

I'm experiencing strange behavior on my CM Storm Quickfire Pro Ultimate keyboard.
When I'm pressing shift + key, it's not working as expected on some keys.
This keys are - = [ ] ; \ , . and /
The issue is the same on the default us layout and on the fr layout on the same keys.
It works perfectly on a regular Dell usb keyboard.
There is no such issue with X11 wm like i3.

**Comment by FreeFull** [comment]
This is probably the same issue as https://github.com/swaywm/wlroots/issues/1217

**Comment by emersion** [comment]
Indeed, thanks for spotting this. Closing as a duplicate.
