### ISSUE TITLE
Switching TTY stops input in wterm

### ISSUE THREAD

**Issue by MichaelMackus** [swaywm/sway#4256]
sway version: swaymsg says 1.0, however I have installed the sway 1.1.1 from portage (I'm assuming sway is reporting the incorrect version here..)

Steps to reproduce: Spawn a wterm terminal, then switch to a new TTY. Upon switching back, the wterm terminal does not respond to any user input (I even tried clicking the window & toggling floating mode).

Results in weston: When I spawn a wterm terminal, switch TTY, and then switch back, I'm able to input into the terminal when I click the wterm window.

**Comment by emersion** [comment]
Can you post a log of wterm with `WAYLAND_DEBUG=1`?

**Comment by MichaelMackus** [comment]
[wterm.log](https://termbin.com/irhn)
[sway.log](https://termbin.com/55lj)

**Comment by MichaelMackus** [comment]
Related wterm issue: https://github.com/majestrate/wterm/issues/9

**Comment by ii8** [comment]
This looks like a bug in wterm. Sway and weston behave differently but both are correct, wterm should be handling seat capability events.

This issue can be closed i think.

**Comment by emersion** [comment]
Ah, indeed, we remove all input devices on TTY switch.
