### ISSUE TITLE
for_window (sway config)

### ISSUE THREAD

**Issue by copypaste10** [swaywm/sway#4259]
To cut it short by inserting 

> for_window [app_id="nemo"] floating enable

Nemo starts as a floating window. Now I only want to add a specific operation of Nemo to open as floating window. It would look like

> for_window [app_id="nemo" instance="..."] floating enable

How do I know about all available instances? Is there a program to search for it?

**What is the problem about?**
Inside Nemo (file manager) you open a directory. Inside the directory are many files. I type the first letter of a specific file to find it quickly. Unfortunately there doesn't appear a small popup window, but instead a tiled window which is too big. After some seconds the large popup disappears.
It appears Nemo fully supports the Wayland protocol and starts as native wayland window instead of xwayland. When I start nemo by GDK_BACKEND=x11 then the popup (typeahead) appears small (just a floating window as it should).

**Comment by Emantor** [comment]
`nemo` should be fixed to use the correct GTK-functions to show popups, this should not be worked around ins sway.

**Comment by emersion** [comment]
Indeed, this is a Nemo bug.

**Comment by copypaste10** [comment]
Ok guys I will make a bug report on Nemo git. Nonetheless I need a temporary solution until they fix this bug.
Does the instance option even work on native Wayland protocol?

**Comment by copypaste10** [comment]
I used `swaymsg -t get_tree` and at least got the name "nemo" out of the temporary tiling window. So title="nemo" helps to make it floating. It only works because the main window of Nemo gets a window name describing the working directory.

Is there another possibility to circumvent this issue? This issue also applies to **Nautilus**(type-ahead). Are there some "children" options available to the for_window line?

**Comment by Schroedi** [comment]
I came here because of the Nautilus type-ahead problem. The popup title there seems to be unique in my quick tests so that this works for me: 
`for_window [title="org.gnome.Nautilus"] floating enable `

**Comment by freed00m** [comment]
@schickst are you sure you didn't mean app_id instead of tittle?

**Comment by schickst** [comment]
@freed00m, did you mean @Schroedi?

**Comment by freed00m** [comment]
@schickst :D sorry yes, hard to tap with fingers
