### ISSUE TITLE
Negative positions break mouse click events / text selection

### ISSUE THREAD

**Issue by efenex** [swaywm/sway#4260]
sway version 1.0 (package 1.1.1 on ArchLinux)

When using negative positioning for outputs, although the position of the outputs is correct, cursor events are not handled correctly.

Example configuration to reproduce:

- 3 monitors, 2x 3840x2160 (DP4, DP7) in top row and 1x 3200x1800 (eDP1) in bottom row

eDP1 0 0
DP4 1600,-2160
DP7 -2240,-2160

This breaks text selection and mouse clicks on DP4 & DP7 (cursor moves correctly, but clicks have no effect)

Issue is fixed when modifying positions to:

eDP1 2240 2160
DP7 0 0
DP4 3840 0

Either negative positions should be disallowed, or cursor events should be handled correctly.

Big thanks to kennylevinsen on freenode for helping me to find the root cause and figure out a working configuration!

**Comment by emersion** [comment]
This is an xwayland bug.
