### ISSUE TITLE
Sway broke my KMS

### ISSUE THREAD

**Issue by happysmash27** [swaywm/sway#4263]
I'm not quite sure how to reproduce this, but when I had lots of memory thrashing, opened and closed swaylock at many points, had htop open on tty2, and restarted xdm some times, Sway and my KMS pretty much broke, with swaybar gone, me being unable to switch TTYs, and xdm not launching with the error drmSetMaster failed. Things only started working again when I killed sway. This is on Sway 1.0.

**Comment by emersion** [comment]
Please re-open if you can reproduce on the latest release. Also provide some Sway debug logs.
