### ISSUE TITLE
Qt menu bars broken since latest qt5* updates

### ISSUE THREAD

**Issue by p-hamann** [swaywm/sway#4268]
Since the latest qt5* updates in ArchLinux (*5.12.3-1 -> *5.12.4-1), the menu bars are broken. It is possible to open every menu bar item exactly one time and then the application has to be restarted to open the respective items again.

Steps to reproduce on ArchLinux:
1) Update qt5
2) Open a Qt5 application with Wayland support
3) Open a menu bar item, e.g. "File", and close it immediately
4) Try to open this menu bar item again

**Comment by Emantor** [comment]
I strongly suspect this to be a qt5 issue.

**Comment by p-hamann** [comment]
I've asked a friend to test it with KDE on Wayland and he has said that it works. I've just tested it by myself and you're right, sorry
