### ISSUE TITLE
Sway focuses wrong monitor

### ISSUE THREAD

**Issue by shumvgolove** [swaywm/sway#4272]
`Sway Version: Sway 1.1-rc1-14-g0e582f1a (May 24 2019, branch 'master')`

I have a multi-gpu setup with HDMI monitor connected to the AMD card and VGA monitor connected to the Intel card. In the configuration file I have:
```
output HDMI-A-3 pos 0 0 res 1920x1080
output VGA-1 pos 1920 0 res 1280x1024
```
After I login with TTY, sway focuses on VGA monitor, although it definitely needs to focus on HDMI one. It gets annoying when you always need to switch to the left monitor when starting Sway.

**Comment by RedSoxFan** [comment]
Currently, sway focuses the first detected output (that is not disabled) on startup. You can add `focus output <name-or-identifier>` (or `exec swaymsg focus output <name-or-identifier>` -- so it doesn't trigger on reload) to your sway config to manually set the output to focus.

I'm not sure if this is worth changing. Using any form of heuristics may not result in the desired output being focused either. It may be better just to have this be set in the config to the user's preference.

**Comment by shumvgolove** [comment]
Thank you for explanation. I'll change the wiki page for those who stumble on the same issue.

**Comment by shumvgolove** [comment]
[Wiki] (https://github.com/swaywm/sway/wiki#multihead)
