### ISSUE TITLE
Sway occasionally crashes when changing monitor/dock while laptop is hibernated

### ISSUE THREAD

**Issue by joachimneu** [swaywm/sway#4276]
This has been an issue again and again over the past half a year that I started to use sway: It occasionally crashes when my setup changes, around plug-on/plug-off of external monitors/docks and/or hibernation of the laptop. It happens roughly once a week and I haven't identified a pattern/cannot reliably reproduce the crash. Whenever it happens, I update sway, but all versions have been somewhat affected.

* Sway Version: r5928.6b6eb147-1
* Debug Log: https://gist.github.com/joachimneu/558ebf43e289c6fee95b9ffed365e643 (tail of the debug log, please let me know if you need earlier output)
* Stack Trace: https://gist.github.com/joachimneu/effeee1c7047114209175b13d01a9af2 (how do I get the symbol table info right?)

I will update this issue as I hopefully collect more crash logs/stack traces.

**Comment by sanga** [comment]
https://github.com/swaywm/sway/issues/4149 Same stack as here by the looks

**Comment by joachimneu** [comment]
Thanks! Any idea, how I can get the "symbol table info" in gdb right? Then I can also collect more crash logs/stack traces, in case that helps.

**Comment by RedSoxFan** [comment]
> how I can get the "symbol table info" in gdb right

Build both wlroots and sway from source. The package you have installed has the debug symbols stripped.

**Comment by Emantor** [comment]
This is a wlroots issue, see swaywm/wlroots#1297.
