### ISSUE TITLE
Link workspaces to output

### ISSUE THREAD

**Issue by jasperro** [swaywm/sway#4278]
Is it possible to add a feature that when you close you detach a second monitor and later reattach the monitor, the workspaces which were previously on the second monitor would go back to that screen?

So when I have workspace one and two on the first screen, and three and four on the second screen, detach the second screen and attach it again, I still have one and two on the first screen and three and four on the second screen. What happens now is that workspace one stays on the first screen and two, three and four go to the second screen.

**Comment by RedSoxFan** [comment]
The requested behavior is how Sway should be handling the situation. Can you please provide your config file and a debug log?

**Comment by jasperro** [comment]
driver: i915
version: sway version 1.1-rc1-47-gb59139c2 (Jun 22 2019, branch 'master')
config and log: [github gist](https://gist.github.com/jasperro/aa237e0201885970f5cec45d513f11f5)

**Comment by RedSoxFan** [comment]
There was a logic issue in the code preventing this from working. #4279 should fix it
