### ISSUE TITLE
Feature request: x2x equivalent.

### ISSUE THREAD

**Issue by dnfm** [swaywm/sway#4292]
Apologies if this is actually a wlroots issue, but an excellent feature would be the equivalent of what x2x does in xorg.  And with wlroots now supporting freerdp, I suspect that should be doable: add a (fake) output, and then send its events over rdp to another sway instance on another system.

**Comment by Depau** [comment]
Came here looking for "fake output".

My use case would be to add a fake display (such as with the `VirtualHeads` option of the Xorg Intel driver) then stream it manually "somehow" (i.e. ffmpeg).

**Comment by dnfm** [comment]
With HEADLESS outputs, and wayvnc, this is effectively done.

**Comment by aij** [comment]
I'm not seeing it. How would one use `wayvnc` as an `x2x` replacement?

I suppose it could enable the `-to` side of `x2x`, but how do you get the `-from` side? Is there a VNC client that can grab the mouse+keyboand and send keyboard/mouse/clipboard without graphics?
