### ISSUE TITLE
[QUESTION] Normalizing to Xft.dpi

### ISSUE THREAD

**Issue by hovnatan** [swaywm/sway#4295]
I have 1920x1080 display and in X.org I used to set the `Xft.dpi` to 157 in `.Xdefaults`. In sway, it looks like the same setting affects all other programs other than sway bar and sway window titles. Is there a way to use the same dpi setting in sway internal fonts?

**Comment by Ferdi265** [comment]
`.Xdefaults` is not read by native wayland applications. It might be that most of the applications you use are still using Xorg and are therefore displayed using Xwayland, and therefore they are picking up Xorg-specific settings.

**Comment by RedSoxFan** [comment]
As Ferdi265 mentioned, `.Xdefaults` is for X11 and is not read by native wayland applications. Only applications using XWayland will read it. For native wayland applications, add `output <name-or-identifier> scale <scale>` to your sway config. See `man 5 sway-output` and `swaymsg -t get_outputs` for more information.
