### ISSUE TITLE
Gaps create unequally sized windows

### ISSUE THREAD

**Issue by pedrocr** [swaywm/sway#4296]
* Sway Version: 1.1-rc1-51-gf5d1c272 (Jun 30 2019, branch 'master')
* Debug Log: https://gist.github.com/pedrocr/834aa8956c30510f2d2bb2bf17afdef4
* Configuration File: default config

When using gaps windows that are the same size become unequally sized. To make it obvious just open two windows side by side a do something like:

```
swaymsg gaps inner all set 500
```

The end result will be something like this:

![unevengaps](https://user-images.githubusercontent.com/246322/60403018-65ad5e00-9b8f-11e9-9f00-d7a036a49cd3.png)

While large gaps make this very noticeable it happens on any sized gap.

**Comment by copypaste10** [comment]
I also use gaps and it appears to affect the left window. For example I use 2 Nemo windows. Whenever I type a filename into the current folder inside of Nemo, the left Nemo window size decreases.

**Comment by RedSoxFan** [comment]
@copypaste10  That's a Nemo issue and has nothing to do with this one. Since it's not setting a parent for the window, it's being treated as a top level window and is being tiled.
```
Gdk-Message: 22:40:02.388: Window 0x55897ba544d0 is a temporary window without parent, application will not be able to position it on screen.
(nemo:8748): Gdk-CRITICAL **: 22:40:02.388: gdk_window_get_effective_toplevel: assertion 'GDK_IS_WINDOW (window)' failed
(nemo:8748): Gdk-WARNING **: 22:40:02.388: Couldn't map as window 0x55897ba544d0 as popup because it doesn't have a parent
```
