### ISSUE TITLE
Having a configuration file results in unusable desktop (grey screen)

### ISSUE THREAD

**Issue by AndreaOrru** [swaywm/sway#4301]
Sway works fine with no config file. However, oddly, I get a grey screen and an unresponsive desktop even with an empty config. I tried on both latest stable release and master branch with the same results.

Here is the failing log:
https://paste.debian.net/1090068/

Working log:
https://paste.debian.net/1090069/

**Comment by RedSoxFan** [comment]
> However, oddly, I get a grey screen and an unresponsive desktop even with an empty config

This is expected. If you are starting sway with an empty config, the only bindings will be to switch to a different VT and there won't be any wallpaper (so all the outputs will be the default gray). The only way to interact with Sway at that point would be over IPC.

**Comment by AndreaOrru** [comment]
I see. Thank you!
