### ISSUE TITLE
Feature request: set gamma via output

### ISSUE THREAD

**Issue by brandsimon** [swaywm/sway#4302]
I'd like to be able to set gamma values in the sway config via output, something like this:
```
output $PRIMARYMONITOR {
    gamma 1:0.8:0.5
    scale ...
}
```
Would something like this get merged?

**Comment by emersion** [comment]
What's your use-case?

If it's for redshift-like functionality, we have a protocol for this. If it's for screen calibration, I'd rather wait for the Wayland color management discussions to finish before doing anything.

**Comment by brandsimon** [comment]
@emersion 
It is for screen calibration. Do you have a link to the discussion?

**Comment by emersion** [comment]
Here's the latest proposal: https://patchwork.freedesktop.org/series/60924/

**Comment by brandsimon** [comment]
I tried setting the Gamma value with redshift before starting sway:
`redshift -m drm -l manual -O 6500 -g 1:0.9:0.9`
This works fine, but when I change to another tty and switch back, sway is resetting itself to 1:1:1.
Is this a bug or a feature?

**Comment by ascent12** [comment]
Changing DRM properties that are not managed by wlroots directly should not be expected to be preserved or to really work at all.

**Comment by emersion** [comment]
Use `redshift-wlr-gamma-control-git` and `redshift -m wayland` instead. Note, doesn't support oneshot iirc.

**Comment by brandsimon** [comment]
@ascent12 @emersion 
Ok, thank you very much!
Is there a reason, oneshot does not work? Is it just not implemented or is it a limitation of redshift/wlroots/sway?

**Comment by emersion** [comment]
The protocol needs the client to stay alive. The gamma ramps will be reset when the client goes away. This is a safety net for misbehaving clients, macOS has a similar API. Another mechanism (e.g. stdin) can e used to replace the oneshot mode.

**Comment by brandsimon** [comment]
@emersion 
Ok great, thank you for the explanation.

**Comment by brandsimon** [comment]
I found a working solution for me: https://github.com/swaywm/wlroots/pull/1851/files
I would prefer a native setting, but this is working for me. :)

**Comment by emersion** [comment]
We have no plans to add another way to set the gamma LUTs, closing.
