### ISSUE TITLE
Colors on swaybar

### ISSUE THREAD

**Issue by alsoijw** [swaywm/sway#4309]
I can use escape string to add color like this
`echo -en "\033[37;1;41m Внимание \033[0m"`
What can I do with swaybar?

**Comment by mstoeckl** [comment]
You'll need to edit [your sway config file](https://github.com/swaywm/sway/wiki#configuration). The [default config file](https://github.com/swaywm/sway/blob/master/config.in) has a few colors set, and a list of further [config options](https://github.com/swaywm/sway/wiki#swaybar-configuration) is given by [`man 5 sway-bar`](https://manpages.debian.org/experimental/sway/sway-bar.5.en.html).

**Comment by alsoijw** [comment]
As I understand in man page is speaking about backgrounds, separators etc.
But I asked about colors in command output like this
`"\033[31m1\033[32m2"`
where 1 is red and 2 is green.
If I put this command in status status_command, I will get single statusline color with incorrect characters like this
`[31m1[32m2`

**Comment by RedSoxFan** [comment]
You can use pango markup. See `man 5 sway-bar` and `man 7 swaybar-protocol`.
