### ISSUE TITLE
Black screen on some Wine games after they lose focus

### ISSUE THREAD

**Issue by junglerobba** [swaywm/sway#4324]
I observed this on Dark Souls 1, Zero Escape VLR and Earth Defense Force 5. After losing focus (moving mouse out of game window, switching workspace) the game window turns black without any way of getting an image back besides restarting the game. EDF still shows a cursor though. 
I tested Dark Souls 1 on GNOME Wayland and could not reproduce this behavior.

sway version 1.1-rc1-61-gc312a10c (Jul 11 2019, branch 'master')

[Debug Log with default config](https://gist.github.com/junglerobba/2c077d5cbd09e4b221c93c3997b3ac33)

Steps to reproduce:

1. Start any of the listed games
2. Switch to a different workspace, the game turns black at this point

**Comment by emersion** [comment]
I notice this as well with other games.

**Comment by cafehaine** [comment]
Might be unrelated, but something similar happens with Dota 2 (sdl, xwayland). It doesn't happen when the game is in "borderless windowed" mode though

**Comment by junglerobba** [comment]
FWIW, this also happens with Wayfire.

**Comment by p4block** [comment]
Also Car Mechanic Simulator 2018. Sometimes it doesn't happen the first time, but will happen the second time.

Lost a bit of progress in the game due to this >:(

**Comment by ammgws** [comment]
> It doesn't happen when the game is in "borderless windowed" mode though

Cheers, experienced this with The Walking Dead game and turning off fullscreen in the settings did the trick.

**Comment by mikesbytes** [comment]
I have also had this same bug with Doom Eternal (which uses vulkan, if that makes a difference)

**Comment by p4block** [comment]
Note that this problem **can be worked around** by running the uniconize daemon or a program/script with similar functionality:

https://github.com/neXromancers/uniconize

**Comment by antoyo** [comment]
I'm having this issue with sway 1.5.1 on Arch.
The PR #5566 should be included in this version, no?

**Comment by kennylevinsen** [comment]
No, 1.5 was tagged 2020-07-16, that PR was opened 2020-07-21. 1.5.1 is just a wlroots compatibility bump.
