### ISSUE TITLE
Xwayland: segmentation fault without -rootless

### ISSUE THREAD

**Issue by mviereck** [swaywm/sway#4327]
* Sway Version: sway version 1.1-rc1-63-ge3a3917d (Jul 14 2019, branch 'master') 

* Debug Log: https://gist.github.com/mviereck/d6dfa89228de9058475db116ca9dad83

* Configuration File: default configuration

 * Step to reproduce: Run `Xwayland :10`

Trying to run `Xwayland :10` leads to a segmentation fault:
```
(EE) 
(EE) Backtrace:
(EE) 0: Xwayland (OsLookupColor+0x139) [0x55bf800455c9]
(EE) 1: /lib/x86_64-linux-gnu/libpthread.so.0 (funlockfile+0x50) [0x7fc99a4bf77f]
(EE) 2: /usr/lib/x86_64-linux-gnu/libwayland-client.so.0 (wl_proxy_marshal_constructor+0x84) [0x7fc99b221274]
(EE) 3: Xwayland (_start+0x1b79) [0x55bf7fee77a9]
(EE) 4: Xwayland (CompositeRegisterImplicitRedirectionException+0x1c86) [0x55bf7fffe706]
(EE) 5: Xwayland (MapWindow+0x1a9) [0x55bf8003ad49]
(EE) 6: Xwayland (InitFonts+0x355) [0x55bf800134f5]
(EE) 7: /lib/x86_64-linux-gnu/libc.so.6 (__libc_start_main+0xeb) [0x7fc99a31009b]
(EE) 8: Xwayland (_start+0x2a) [0x55bf7fee41fa]
(EE) 
(EE) Segmentation fault at address 0x0
(EE) 
Fatal server error:
(EE) Caught signal 11 (Segmentation fault). Server aborting
(EE) 
Aborted (core dumped)
```
It does not happen with `Xwayland :10 -rootless`. It also does not happen in Weston.

Sway is running in a container and nested in an X session. However, the bug is [confirmed elsewhere](https://github.com/mviereck/dockerfile-x11docker-xwayland/issues/1) in a native sway drm session.

**Comment by emersion** [comment]
This isn't a sway issue.

**Comment by manio** [comment]
Hi!
I just want to share some info for reference and for other users with similar problem...
Recently I cannot run any X program under sway. Starting Xwayland from terminal (I know - this is not the way how it should be launched) gives the following backtrace:
```
(EE)
(EE) Backtrace:
(EE) 0: Xwayland (OsLookupColor+0x135) [0x56288465ede5]
(EE) 1: /lib/x86_64-linux-gnu/libpthread.so.0 (funlockfile+0x50) [0x7f540835e18f]
(EE) 2: /usr/lib/x86_64-linux-gnu/libwayland-client.so.0 (wl_proxy_marshal_constructor+0x86) [0x7f5409071286]
(EE) 3: Xwayland (_start+0x13b5) [0x5628844fadc5]
(EE) 4: Xwayland (CompositeRegisterImplicitRedirectionException+0x1a87) [0x562884615fe7]
(EE) 5: Xwayland (MapWindow+0x1d9) [0x5628846540c9]
(EE) 6: Xwayland (InitFonts+0x355) [0x56288462b805]
(EE) 7: /lib/x86_64-linux-gnu/libc.so.6 (__libc_start_main+0xea) [0x7f54081abcca]
(EE) 8: Xwayland (_start+0x2a) [0x5628844f87ba]
(EE)
(EE) Segmentation fault at address 0x0
(EE)
Fatal server error:
(EE) Caught signal 11 (Segmentation fault). Server aborting
(EE)
```

The solution for me was to install original sway packages from debian, as I have it compilled and installed manually.

**Comment by mobrine-mob** [comment]
Just out of curiousness, did someone ever manage to fix this and run Xwayland?
