### ISSUE TITLE
Feature request: configuration of DISPLAY and WAYLAND_DISPLAY

### ISSUE THREAD

**Issue by mviereck** [swaywm/sway#4328]
I am interested to use a nested sway session for [x11docker](https://github.com/mviereck/x11docker) that allows to run container applications on X servers and Wayland compositors. 

Using sway with x11docker would require three configuration options:
 - Setting the X display number of Xwayland. (`DISPLAY`).
 - Disabling X extension `MIT-SHM` of Xwayland.
 - Setting the Wayland socket name (`WAYLAND_DISPLAY`).

 Not mandatory, but useful: 
 - Xwayland option `-auth` to specify a cookie.

Would you consider to make this configurable?

**Comment by emersion** [comment]
Not a fan of this. Why do you need to do that?

>Disabling X extension MIT-SHM of Xwayland.

Probably a bad idea.

**Comment by mviereck** [comment]
> Disabling X extension MIT-SHM of Xwayland.
> Why do you need to do that?

Containers are isolated from the system through namespaces. The shared memory is part of the IPC namespace.

To allow MIT-SHM the IPC namespace from host must be shared with the container. That severely degrades container isolation. Normally a container has its own IPC namespace.

Xwayland in general works well  with disabled MIT-SHM extension as I see in other setups.

**Comment by nemesis64** [comment]
I'd also like to have this.

**Comment by timjrd** [comment]
+1 for multiple XWayland instances

**Comment by muradm** [comment]
+1 i'm running multiple sway's on different terminals without systemd, and it is a headache when WAYLAND_DISPLAY and DISPLAY are not predefined

**Comment by emersion** [comment]
Should be easy to percolate the DISPLAY and WAYLAND_DISPLAY to the script that started Sway. e.g.

```sh
export SWAY_STARTUP="$XDG_RUNTIME_DIR/sway-startup.$$.pipe"
mkfifo "$SWAY_STARTUP"
sway
read display wayland_display <"$SWAY_STARTUP"
rm "$SWAY_STARTUP"
export DISPLAY="$display" WAYLAND_DISPLAY="$wayland_display"
```

And in the Sway config:

```sh
exec echo "$DISPLAY" "$WAYLAND_DISPLAY" >"$SWAY_STARTUP"
```

> multiple XWayland instances

Unrelated to this issue.

* * *

Closing because implementing the suggested feature is too dangerous, we can't easily make the difference between a broken DISPLAY/WAYLAND_DISPLAY where we should error out, a DISPLAY/WAYLAND_DISPLAY conflict where we should also error out, and a DISPLAY/WAYLAND_DISPLAY requested by the user.
