### ISSUE TITLE
SetGroup xkb action not working on X11 applications

### ISSUE THREAD

**Issue by edyounis** [swaywm/sway#4329]
* Sway Version: 1.1

* Reproduce:
1. Configure sway input with grp:caps_toggle and another layout and switching between layouts works. (Toggle here means push+release caps key and you are in layout 2 until push+release again)
2. Configure sway input with grp:caps_switch and another layout and switching between layouts works for internal sway bindings and wayland-native applications but not xwayland applications. (Switch here means while caps key is down you are in layout 2)
3. This can be tested using the utilities in the libxkbcommon repo: interactive-wayland and interactive-x11. The wayland repo will register keysyms from layout 2, while the x11 will not.

For some reason, using a switch option to switch between layouts (while key is down) does not work for x applications, while the toggle one works just fine.

**Comment by emersion** [comment]
Can you reproduce in another Wayland compositor? (e.g. `weston --xwayland`)

**Comment by RedSoxFan** [comment]
I can replicate in both Weston and KDE. Looks like this is a XWayland issue.
