### ISSUE TITLE
Gray Background

### ISSUE THREAD

**Issue by fredfortier** [swaywm/sway#4333]
The desktop background does not carry the `bg` config, it is always gray. The problem started after upgrading from an older 1.0 beta to 1.1.
```
$  swaymsg -t get_version
sway version 1.1-rc1-63-ge3a3917d (Jul 15 2019, branch 'master')
$ uname --all
Linux localhost.localdomain 5.1.17-300.fc30.x86_64 #1 SMP Wed Jul 10 15:20:27 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

The most notable parameter of my config is probably my dual monitor setup and use of fractional scaling:
```
output HDMI-A-1 pos 0 0 res 3440x1440
output HDMI-A-1 bg /usr/local/share/backgrounds/sway/Sway_Wallpaper_Blue_1920x1080.png fill
output eDP-1 scale 1.5
output eDP-1 pos 3440 0 res 1920x1080
output eDP-1 bg /usr/local/share/backgrounds/sway/Sway_Wallpaper_Blue_1920x1080.png fill
```

[sway.log](https://github.com/swaywm/sway/files/3393083/sway.log)

[config.txt](https://github.com/swaywm/sway/files/3393095/config.txt)

**Comment by emersion** [comment]
swaybg is now in a separate repository, and is a mandatory dependency of sway. Please install it too.
