### ISSUE TITLE
Feature request: Allow subscribing to xkb layout changes

### ISSUE THREAD

**Issue by bbaserdem** [swaywm/sway#4334]
Version: 1.0

I am trying to write a script that would display the selected keymap, and print a new line every time the layout is changed. In X, I use xkb-switch to accomplish this task, as it has a subscribe option.

I can read it fine according to docs; `swaymsg -t get_inputs | jq '.[] | select(."xkb_active_layout_name") | ."xkb_active_layout_name"` works fine. However, right now this can only be polled in a script, which is not desirable (time delay between change events) An event that can be subscribed to on active keyboard layout change (Something like `swaymsg -t subscribe '["xkb_active_layout_name"]' -w` would be useful.

Or, I currently use `xkb_options "grp:caps_toggle"`; using caps lock to cycle through the keymaps. I cannot bindsym to this key now however. 'bindsym Caps_Lock "swaymsg -t send_tick 'keymap_changed'"' does not send a tick.

**Comment by emersion** [comment]
Maybe we should have an `input` event, just like we have an `output` event

**Comment by RedSoxFan** [comment]
> Maybe we should have an `input` event

Sounds reasonable to me. What events should we expose? Some ideas:
- `added`
- `removed`
- `xkb_layout_changed`
- `libinput_config_changed`

> just like we have an `output` event

Just as a note, the `output` event is not currently implemented (see #4020).

**Comment by bbaserdem** [comment]
These cover all the bases for keyboard layout changes, and plugging in/out input devices.

At least I can build my entire toolkit that I have currently on X by subscribing to these events.
