### ISSUE TITLE
Feature request: "move workspace to next"

### ISSUE THREAD

**Issue by Jamedjo** [swaywm/sway#4346]
## What

Ability to cycle which output a workspace appears on. Maybe with `swaymsg move workpace to output next`.

## Why

Make it easier to get workpaces on to the desired output.

I find it very difficult to arrange where monitors are using the pixel positioning, so `move output to workpace left` style commands are not set up correctly.

For myself I've solved this with a script to select individual screens, but for other people this might be a bit complicated to set up and involves installing external tools `fzf` and `jq`:

```bash
# Move workspace to other screens
set $term_run urxvt -e zsh -c
bindsym $mod+Shift+w exec $term_run "source ~/.fzf.zsh && swaymsg -t get_outputs | jq -r '.[] | select(.focused!=true) | [.name, .make, .model] | @tsv' | fzf --select-1 --reverse --prompt='Move workspace to:' | awk '{print $1}' | xargs -r swaymsg move workspace to"
bindsym $mod+Alt+w exec swaymsg -t get_outputs | jq '.[] | select(.focused!=true) | .name' | head -n1 | xargs swaymsg move workspace to
```

**Comment by RedSoxFan** [comment]
This falls in the same boat as `focus next` (see #4103), where you have to define what `next` is. Unfortunately, there is not a clear definition for this. You could have outputs anywhere so any algorithm for iterating through them is purely arbitrary and prone to disagreement. This is better suited for a script.

**Comment by Jamedjo** [comment]
> This falls in the same boat as focus next (see #4103), where you have to define what next is

Good point, although I think this is a lot simpler than with windows because people tend to only have a handful of outputs and because it is useful with any (even random) order. Especially since the most common use case would be having 2 monitors, where the order makes no difference at all.

What if we called this `move workspace to other` to make clear that there would be no guarentee on order and no corresponding `previous`?

I was originally looking to do this in the order returned by `get_outputs` but couldn't think of an easy way to do so. I've now updated my approach to <code>swaymsg -t get_outputs | jq '.[] | .name' | sed -n "1p;/`swaymsg -t get_outputs | jq '.[] | select(.focused==true) | .name'`/{n;p;}" | tail -n1 | xargs swaymsg move workspace to</code>, in case anybody finds this looking to achieve similar.

**Comment by kevenwyld** [comment]
I found that @fbergroth's solution identified non-active displays (plugged in but not enabled) as well as active ones.  So you would get stuck at the end when the next display was not an active output.  I modified it slightly to filter those out.

```
bindsym $mod+x exec "swaymsg -t get_outputs |jq '[.[] | select(.active == true)] | .[(map(.focused) | index(true) + 1) % length].name' |xargs swaymsg move workspace to"
```

**Comment by chmduquesne** [comment]
Thank you!

I modified your snippet to make it reusable in other situations:

```
# No next output, see https://github.com/swaywm/sway/issues/4346
set $next_output swaymsg -t get_outputs -r | jq -r \
    '[.[] | select(.active)] | .[(map(.focused) | index(true) + 1) % length].name'

bindsym $mod+x exec swaymsg move workspace to "$($next_output)"
```

**Comment by ismay-tue** [comment]
> This falls in the same boat as `focus next` (see [#4103](https://github.com/swaywm/sway/issues/4103)), where you have to define what `next` is. Unfortunately, there is not a clear definition for this. You could have outputs anywhere so any algorithm for iterating through them is purely arbitrary and prone to disagreement. This is better suited for a script.

Focus next (now) exists in sway. Also, i3 has focus next output, so it should be valid for sway. This PR resolves this issue: https://github.com/swaywm/sway/pull/9128

**Comment by georglauterbach** [comment]
Sounds nice! Maybe we should re-open this as a tracking issue.

**Comment by ismay-tue** [comment]
There's also this one, which is still open: https://github.com/swaywm/sway/issues/8799, although it's not move but focus, so yeah, maybe reopening makes sense.
