### ISSUE TITLE
[Feature Request] Blur Kernels

### ISSUE THREAD

**Issue by petrmanek** [swaywm/sway#4356]
Would it be possible to implement background blurring in sway?

In X11, compositors like `compton` can efficiently apply arbitrary convolution kernels specified in their config files. Here's an example of such a kernel (5x5 gaussian):

```
5,5,0.018316,0.082085,0.135335,0.082085,0.018316,0.082085,0.367879,0.606531,0.367879,0.082085,0.135335,0.606531,0.606531,0.135335,0.082085,0.367879,0.606531,0.367879,0.082085,0.018316,0.082085,0.135335,0.082085,0.018316,
```

It would be nice to have something similar in sway, especially since the implementation doesn't seem too complicated and the feature would help considerably in semi-transparent setups. Here's one idea: the blur kernel could be introduced as an `output` configuration option.

Note: This feature (or its superset) has been already requested in #453 and #3380.

**Comment by petrmanek** [comment]
Would please at least provide an explanation? I would be happy to open PR.

**Comment by emersion** [comment]
See the other issues you referenced. We're not interested in blur, sorry. Other compositors might be interested in this, though.

**Comment by petrmanek** [comment]
@emersion Funny that you should mention that. I've studied the other feature requests quite extensively before opening this one (as anybody should), and have made some observations about them:

1. They requested generic sets of features (e.g. "implement fancy effects in sway") - this is _not_ the case here: I'm proposing a very specific feature, which although is nice-to-have, has some very clear applications,
2. No implementation suggestions were provided - here I've provided a simple proposal, which could be expanded into a realistic implementation plan,
3. While in the previous issues, the author response always was: _"this is not a priority,"_ or: _"we have better things to do"_, they have _not_ explicitly said: _"we don't want this."_

As a developer, the whole point of open-sourcing software like sway means that anyone can come in, fork it and add their favorite features. Now, I didn't open this issue to nag anyone to implement a pretty feature for me ASAP. I completely understand that you have milestones and release cycles to complete, and I don't want to disrupt that. And in addition, I'm perfectly happy to implement it myself.

For me, this feature request is only about finding out whether someone is working on this already, and getting your opinion on the implementation details, so that when I'm done with the work, it will be mergeable upstream.

Please let me know whether your _"not interested"_ response refers to putting the feature on implementation schedule or rather having the feature in your code base at all.

**Comment by emersion** [comment]
We're not interested in this feature.

**Comment by ascent12** [comment]
Blur is not a particularly trivial thing to implement. You can't simply apply it to all surfaces with alpha without it looking like crap. Many clients use client-side decorations, which often involves an alpha border, meaning you're going to be blurring past the boundaries of the client's contents. KDE actually developed an extension protocol for specifically telling the compositor what part to blur, which is another protocol that needs to be implemented (probably not that hard) and would limit it to clients that actually speak that protocol.

Another part is that the renderer is currently not set up for doing complex effects. wlroots' renderer was actually designed to be shit on purpose. More features could eventually be added, but it's not something I want to do right now while that section is going through a redesign.
I'll oppose sway side-stepping wlr_renderer to do any OpenGL itself.

And as @emersion mentions, nobody (of the core developers) really seems particularly interested. We don't have release schedules and roadmaps; people just do whatever interests them.
It's great if other people come in and implement features they want (that's the power of open-source), but the maintenance burden and overall vision must be taken into consideration when upstreaming anything.

**Comment by emersion** [comment]
(Side note, blur also has implications wrt. damage tracking)

**Comment by petrmanek** [comment]
@ascent12 Thanks for a more nuanced explanation! I suspected that there might be a problem like this buried inside.

I don't know whether my capacity will allow me to play with this feature right now, but I would definitely like to do it at some point in the future. I really like using sway on my laptop, and this is one of the features I desperately miss.

Perhaps by the time the renderer redesign is complete, it will be a better opportunity to try make something like this happen. For anyone skimming this issue in the future, I will post updates here as they happen and will be happy for any feedback.

**Comment by aro1999** [comment]
> @ascent12 Thanks for a more nuanced explanation! I suspected that there might be a problem like this buried inside.
> 
> I don't know whether my capacity will allow me to play with this feature right now, but I would definitely like to do it at some point in the future. I really like using sway on my laptop, and this is one of the features I desperately miss.
> 
> Perhaps by the time the renderer redesign is complete, it will be a better opportunity to try make something like this happen. For anyone skimming this issue in the future, I will post updates here as they happen and will be happy for any feedback.

Hey, how do you do? Any news?

**Comment by petrmanek** [comment]
@aro1999 Hi! Nothing new on my end. I've been using sway and following its development for a while now, and it seems to me that there is definitely a group of users interested in this feature (including me). Some have even created their own forks, for instance [this one][fork].

Still, unless sway devs say otherwise, the previous discussions in this thread and [this PR][pr] lead me to believe that for the time being all fancy visual features won't be upstreamed.

[fork]: https://github.com/fluix-dev/sway-borders
[pr]: https://github.com/swaywm/sway/pull/5639

**Comment by afreidz** [comment]
fwiw ... i think it might then be a bit of a misnomer to call `sway` a "compositor" for wayland if any visual effects are not planned to be upstreamed.  i think its more of a window-manager at that point.  its especially frustrating that `sway`/wl-roots takes the compositor role and therefore users can't even run an external compositor to achieve the effects (similar to i3+picom).  no disrespect, the hard work is appreciated.  but this seems like a roadblock that may prevent adoption of `sway` over its i3 counterpart.  unless i am missing something?

**Comment by emersion** [comment]
Wayland compositors have nothing to do with X11 compositing managers. A Wayland compositor is what a Wayland server is called.

Moreover, nothing forces an X11 compositing manager to implement fancy features like blur. For instance, xcompmgr is an X11 compositing manager that doesn't.

**Comment by afreidz** [comment]
fair enough. i just think one of the key features of "compositing" is the ability to manipulate the frames in the buffer before displaying them. while there are certainly reasons beyond fancy decorations to "composite", i think its also fair to say that decorations/effects are one of them. and i also think its fair given the historical precedence X11 has set. while i appreciate wanting to keep their definitions separated between wayland and X11, i also think there is a functional link. traditionally, picom/compton has been used by people who want "compositing effects" on window managers which have decided not to support them out of the box. picom/compton runs as the "compositor" for the window manager. this is great because it supports the needs of both the maintainer, and the user. i would be totally fine continuing this paradigm with sway. however, sway already takes the role of compositor which prevents an external one from running. sway seems to be taking the stance of not wanting to support composite effects while also blocking other means of achieving them. which was the basis of my previous comment.

**Comment by emersion** [comment]
X11 has a protocol for compositing managers. Nobody has written one for Wayland yet, but it would be possible. Honestly, given the high complexity involved, I'd NACK such a protocol.

**Comment by WillPower3309** [comment]
[swayfx](https://www.github.com/willpower3309/swayfx) currently has blur in a draft PR, so it will be merged soon

**Comment by harogaston** [comment]
@emersion that said you should just as well ditch transparency then. Transparency without blur is pointless from any sensible UI design approach.
