### ISSUE TITLE
[Feature Request] Support for Zoom

### ISSUE THREAD

**Issue by MichaelAquilina** [swaywm/sway#4358]
Zoom is a video conferencing/screen sharing application used by a number of companies. Right now Zoom works perfectly fine in sway except for screen sharing. When you attempt to share a screen in sway, nothing is listed on the list of possible things to share. This is possibly the only issue I have with sway right now that would prevent me from using it full time at my current job.

Zoom's screen sharing works on GNOME wayland (I'm guessing due to some specific wayland protocol). I am aware that sway has also implemented a way to perform screen sharing (based on this issue https://github.com/swaywm/sway/issues/1612) and so i thought I would open up an issue to see how hard it would be to make this also work for Zoom.

To be clear, I am 100% aware that Zoom is a closed source application which makes it very hard for you guys to do anything. But I was hoping that perhaps the protocol implemented in sway was similar enough to that found in GNOME that we could get this working with some configuration.

**Comment by ddevault** [comment]
https://github.com/emersion/xdg-desktop-portal-wlr

**Comment by oblednov** [comment]
> https://github.com/emersion/xdg-desktop-portal-wlr
How does that help?

**Comment by mmlb** [comment]
@MichaelAquilina I contracted zoom support a few weeks ago to figure out what protocol they were using for Wayland screen sharing and to see about getting then to support/work with the wlroots protocol. After an initial "not currently looking to expand support" type message they responded they've changed their stance. No eta from them though.

**Comment by MichaelAquilina** [comment]
@mmlb thanks for the follow up! Please send any updates here so that others (and myself) can take a look at any useful information that's passed on to you :)

**Comment by kuba-gaj** [comment]
@MichaelAquilina Could you please let me know how you made it work at all (even without screen sharing?)

I get `This application failed to start because it could not find or load the Qt platform plugin "wayland-egl"` when trying to start it.

**Comment by MichaelAquilina** [comment]
@kuba-gaj seems like you have some missing package dependencies. Search for `wayland-egl` or `qt-wayland` in your distros package manager.

**Comment by mmlb** [comment]
> @mmlb thanks for the follow up! Please send any updates here so that others (and myself) can take a look at any useful information that's passed on to you :)

can/will do!

**Comment by lanzafame** [comment]
@mmlb Have you received any updates from Zoom? I am happy to badger them some more if they have gone silent on you.

**Comment by mmlb** [comment]
@lanzafame , please do. I will ask about any updates too.

**Comment by AdrienLemaire** [comment]
> https://github.com/emersion/xdg-desktop-portal-wlr

I think @ddevault meant that xdg-desktop-portal-wlr is the application that should solve the screen sharing issue, but @emersion lacks time to work on it, thus there's no deadline on this feature.

**Comment by emersion** [comment]
Even when we have time to work on something, we never do deadlines.

**Comment by billop** [comment]
@kuba-gaj 
> I get `This application failed to start because it could not find or load the Qt platform plugin "wayland-egl"` when trying to start it.
> 
> For me it also is the only "must-have" left to completely switch to sway :/

Unset your `QT_QPA_PLATFORM` environmental variable so that zoom launches with xwayland. I would edit the desktop file so that the exec line looks like this:
```
Exec=env -u QT_QPA_PLATFORM /usr/bin/zoom %U
```

**Comment by Croissong** [comment]
@billop So you got screensharing working? Could you please share which packages you installed and what environment variables you have (un)set to get it working?
I can't get it to work :(
Thanks in advance!

**Comment by progandy** [comment]
As far as I know, currently the only option is a v4l2loopback camera or [gnome-dbus-emulation-wlr](https://gitlab.com/jamedjo/gnome-dbus-emulation-wlr) while running zoom with dxwayland.

**Comment by hypergig** [comment]
I noticed today that the "share a second camera" feature made its way into the linux version of zoom
![Screenshot from 2020-09-16 17-29-20](https://user-images.githubusercontent.com/8643560/93395042-342bbb80-f843-11ea-8ca2-50ff6cd52099.png)
This should in theory make it much easier to share your screen with any one of the camera emulator ticks

**Comment by tkerber** [comment]
For reference, https://github.com/emersion/xdg-desktop-portal-wlr combined with firefox/chromium (and xdg-desktop-portal and pipewire) and the web version of zoom works to support screensharing now.

**Comment by wakatara** [comment]
@tkerber Can you give details on the setup you have for that perhaps? I'd be interested in seeing details to try to get it working (and not married to the Zoom download client at all, so... =] ).

What packages are required (if you could puzzle it out and any config files we would need to take note of?).

**Comment by mauro3** [comment]
I just followed https://wiki.archlinux.org/title/PipeWire#WebRTC_screen_sharing.  If I remember correctly, that just works for me.

Although, I find that sound is less well handled in the web-client (did not investigate why).  Thus what I usually do is to have one zoom instance in chromium open (for the screensharing) and one in the desktop client (handling sound and camera).

**Comment by smlx** [comment]
This is a dirty hack but works passably with the Zoom flatpak with Wayland: https://gitlab.com/smlx/gnome-dbus-emulation-wlr/-/commit/a01e1b345e9d2af072b3e8aff31e52049a909783

Zoom has a bunch of bugs with Wayland, not least of which is that they don't use the correct co-ordinate transform for screen scaling, which means that even on Gnome screen sharing is totally broken when using scaling.
