### ISSUE TITLE
Touchscreen events seemingly sent to wrong display

### ISSUE THREAD

**Issue by luispabon** [swaywm/sway#4365]
* Sway Version:
 master 36aa67e
wlroots [master 76ef089](https://github.com/swaywm/wlroots/commit/76ef089f52b20a2def3dd1f8a8564af165050dcb)

* Debug Log:

Nothing on the sway debug logs. The following on `libinput debug-events` while moving finger on touch display.:

```
-event18  TOUCH_DOWN       +10.47s	0 (0) 80.96/56.87 (270.08/107.25mm)
 event18  TOUCH_FRAME      +10.47s	
 event18  TOUCH_MOTION     +10.52s	0 (0) 80.99/56.87 (270.17/107.25mm)
 event18  TOUCH_FRAME      +10.52s	
 event18  TOUCH_MOTION     +10.53s	0 (0) 81.01/56.87 (270.25/107.25mm)
 event18  TOUCH_FRAME      +10.53s	
 event18  TOUCH_MOTION     +10.54s	0 (0) 81.06/56.87 (270.42/107.25mm)
 event18  TOUCH_FRAME      +10.54s	
 event18  TOUCH_MOTION     +10.55s	0 (0) 81.11/56.83 (270.58/107.17mm)
 event18  TOUCH_FRAME      +10.55s	
 event18  TOUCH_MOTION     +10.56s	0 (0) 81.19/56.78 (270.83/107.08mm)
 event18  TOUCH_FRAME      +10.56s	
 event18  TOUCH_MOTION     +10.57s	0 (0) 81.26/56.74 (271.08/107.00mm)
 event18  TOUCH_FRAME      +10.57s	
 event18  TOUCH_MOTION     +10.58s	0 (0) 81.34/56.74 (271.33/107.00mm)
```
Tons of that.

`swaymsg -t get_inputs` --> https://pastebin.com/aMzXLpkt
`swaymsg -t get_outputs` --> https://pastebin.com/4BMpevV3

* Configuration File:
https://github.com/luispabon/sway-dotfiles/tree/master/configs/sway 
I don't have any touchscreen specific config. Tried on another user with a blank sway config and the issue remains.

* Problem
When I have all my 3 displays connected, touchscreen events from the laptop's touch display are sent to one of the two external displays. This includes dragging for scroll, selecting stuff etc. Seems to be independent of which display and app have focus (I have click to focus). Essentially if I drag down on the laptop's touch display, an app on another display will scroll down.

* Stack Trace, if sway crashes:
n/a

**Comment by emersion** [comment]
This is expected, there is no way to reliably and automatically map a touchscreen to an output. You need to manually map your touchscreen to your output with `map_to_output`.

**Comment by luispabon** [comment]
Thank you @emersion . I wonder if it could be worth adding the man pages to the wiki as currently their discoverability is very low - it isn't obvious `sway-input` exists as a man page since there's no such command.
