### ISSUE TITLE
Kodi renders offset by 38px

### ISSUE THREAD

**Issue by breadcat** [swaywm/sway#4366]
* Sway Version: 1.0
* Debug Log: https://pastebin.com/TaiR1PTP
* Configuration File: https://pastebin.com/gmxG5rtY

I'm automatically starting Kodi (installed via the `kodi-wayland` ArchLinux package). It launches fine, except the rendering is offset at the top by about 38px. I would usually put this down to being a weird Kodi issue, but you can fix the issue by toggling it's fullscreen behaviour with `$mod+f`.

I've tried removing the bar, which did nothing, forcing Kodi to be fullscreen via `for_window` but this also made no difference.

Grim screenshot captured [showing issue](https://imgur.com/a/tPlMwc9), and [after manual fix](https://imgur.com/a/d4om28f)

**Comment by Emantor** [comment]
Please test with weston and verify that this is a sway issue.

**Comment by breadcat** [comment]
Thanks, I've just checked it with Weston 6.0.1 installed, launching from the built-in terminal does not show the border, so seems to be a sway issue.

**Comment by breadcat** [comment]
I've just tried this on my laptop that also runs Sway 1.0 on Arch and I can't recreate this issue. It only appears to be on the HTPC which is strange as Weston isn't affected.

For a bit more information, ss the window is drawn, you get an outline border for a split second, and then I believe the 38px gap is where window controls have been drawn.

**Comment by breadcat** [comment]
This issue seems to have sorted itself during the upgrade to 1.2_rc2-1 from the Arch repositories on both tested computers, so I'll close it.
