### ISSUE TITLE
Proposal: xkb_redirect_key cmd

### ISSUE THREAD

**Issue by edyounis** [swaywm/sway#4367]
I propose a new command: xkb_redirect key.

Synopsis: `xkb_redirect_key <state1> <key1> <state2> <key2>`

This would redirect the keycode key1 and modifier state state1 to key2 in state state2. This can be done so applications ontop of sway see the second keycode and state whenever the first keycode and state is observed. I am proposing this here to get opinions from the core devs first, before I hack this up. I have a few questions:

1) Is this something the core devs would want/be okay with?

2) Is this possible given the current architecture of sway? I believe this would be pretty easy by conditionally editting the event that is passed to clients on key press/release.

3) Should this be done before or after the sway internal bindings are checked?

Thanks

**Comment by emersion** [comment]
I'd prefer to see something like https://github.com/swaywm/sway/issues/1779

**Comment by edyounis** [comment]
> I'd prefer to see something like #1779

Yeah, I agree. I am limited in my time to implement and my uses cases will be solved by simulating single key press/release events. Do you have any advice for me to get started on this?

**Comment by emersion** [comment]
The first step would be to use `wlr_keyboard_notify_key` to simulate keycodes.

Closing in favor of #1779
