### ISSUE TITLE
resizing windows with the mouse causes floating windows to move

### ISSUE THREAD

**Issue by colemickens** [swaywm/sway#4369]
```
[cole@xeep:~]$ sway --version
sway version 1a16262903dce09a60f94698afa96c1b2c91c264

[cole@xeep:~]$ swaymsg -t get_version
sway version 1a16262903dce09a60f94698afa96c1b2c91c264
```

See the video: https://youtu.be/KN6cFeOVnUI

I am opening some termite instances and then using right click mouse and drag to resize the containers. The floating window should not move, yet does.

debug log: 
[sway.log](https://github.com/swaywm/sway/files/3429366/sway.log)

**Comment by magicthighs** [comment]
This also happens to me, and happens whenever focus changes to another window.

sway version 1.1-rc1-78-g1a162629 (Jul 25 2019, branch 'master')
