### ISSUE TITLE
wrong cursor used in gtk apps

### ISSUE THREAD

**Issue by itapai** [swaywm/sway#4379]
Hi,

I'm trying to use this cursor https://github.com/itapai/ater-yellow with sway, and it works fine in a workspace (when the mouse is not positioned in an app), but when I move it to, let's say firefox ( running on wayland ) I'm getting the default cursor.
I have xwayland disabled.

~/.icons/default/index.theme

```
[Icon Theme]
Name=Default
Comment=Default Cursor Theme
Inherits=ater-yellow
```

```
~ ls .local/share/icons/ater-yellow/
LICENSE  README.md  cursors/  index.theme*  pictures/
```

and in ~/.config/sway/config
```
exec_always ~/.config/sway/bin/import-gsettings \
    gtk-theme:gtk-theme-name \
    icon-theme:gtk-icon-theme-name \
    cursor-theme:gtk-cursor-theme-name
```
~/.config/gtk-3.0/settings.ini
```
[Settings]
gtk-theme-name=Adwaita
gtk-icon-theme-name=Papirus
gtk-font-name=Cantarell 11
gtk-cursor-theme-name=ater-yellow
gtk-toolbar-style=GTK_TOOLBAR_BOTH
gtk-toolbar-icon-size=GTK_ICON_SIZE_LARGE_TOOLBAR
gtk-button-images=1
gtk-menu-images=1
gtk-enable-event-sounds=1
gtk-enable-input-feedback-sounds=1
gtk-xft-antialias=1
gtk-xft-hinting=1
gtk-xft-hintstyle=hintfull
```
as described [in the official wiki](https://github.com/swaywm/sway/wiki/GTK-3-settings-on-Wayland).

Making sure everything is set correctly.
```
~ gsettings get org.gnome.desktop.interface cursor-theme
'ater-yellow'
 ~ gsettings get org.gnome.desktop.interface cursor-size
24
```

Thanks,
Cheers

**Comment by emersion** [comment]
sway has no influence over the GTK+ cursor theme.

**Comment by itapai** [comment]
If I open the GTK app with xwayaland, the correct cursor is displayed.

Is this an issue with sway, or wayland in general?

**Comment by itapai** [comment]
I got it working by changing the /usr/share/icons/default/index.theme directly, instead of ~/.icons/default/index.theme

Someone is not reading the user config.

Cheers
