### ISSUE TITLE
[Feature Request]: set maximum resolution

### ISSUE THREAD

**Issue by Stunkymonkey** [swaywm/sway#4382]
I am having an older laptop, which I use all the time. If I am connecting to some 4k-display my laptop automatically switches to the maximum resolution and tries everything in 4k. Since it is an older laptop is causes huge lags. 
It would be nice to have an option, for setting the resolutions maximum at FullHD and not beyond. So I can still use older projectors with only HD-resolution but also work on a 4k display.

As a workaround, I set a keyboard shortcut to manually set the resolution to FullHD.

**Comment by emersion** [comment]
You can set a 1080p resolution with an `output` command matching the monitor connector/identifier. If this isn't enough, a script can do it.

**Comment by Stunkymonkey** [comment]
oh true forgot that
thanks
