### ISSUE TITLE
Right/Secondary-Click does not work with some GTK Applications

### ISSUE THREAD

**Issue by sydneymeyer** [swaywm/sway#4383]
It appears that Right/Secondary-Click does not work with some GTK Applications, e.g. Transmission, Rhythmbox, etc.

So far, i.e:
- Transmission GTK: Secondary Mousebutton on torrent items
- Rhythmbox: Items in play queue.
- Gnome Web (Epiphany): Secondary MB on e.g. text selection.

sway version 1.1-rc1-79-g17c9a0e8 (Jul 27 2019, branch 'master')

edit: this is with GDK_BACKEND=wayland

**Comment by RedSoxFan** [comment]
What's the output of `swaymsg -t get_outputs`? This is probably #3135

**Comment by sydneymeyer** [comment]
Output DP-2 'Dell Inc. DELL U2417H 5K9YD862ARAL' (focused)
  Current mode: 1920x1080 @ 60.000000 Hz
  Position: 1920,0
  Scale factor: 1.000000
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 1
  Available modes:
    720x400 @ 70.082001 Hz
    640x480 @ 59.939999 Hz
    640x480 @ 59.939999 Hz
    640x480 @ 60.000000 Hz
    640x480 @ 75.000000 Hz
    720x480 @ 59.939999 Hz
    720x480 @ 59.939999 Hz
    720x480 @ 59.939999 Hz
    720x480 @ 60.000000 Hz
    720x480 @ 60.000000 Hz
    720x576 @ 50.000000 Hz
    720x576 @ 50.000000 Hz
    800x600 @ 60.317001 Hz
    800x600 @ 75.000000 Hz
    1024x768 @ 60.004002 Hz
    1024x768 @ 75.028999 Hz
    1280x720 @ 50.000000 Hz
    1280x720 @ 59.939999 Hz
    1280x720 @ 60.000000 Hz
    1280x720 @ 60.000000 Hz
    1152x864 @ 75.000000 Hz
    1280x1024 @ 60.020000 Hz
    1280x1024 @ 75.025002 Hz
    1600x1200 @ 60.000000 Hz
    1920x1080 @ 23.976000 Hz
    1920x1080 @ 24.000000 Hz
    1920x1080 @ 50.000000 Hz
    1920x1080 @ 59.939999 Hz
    1920x1080 @ 60.000000 Hz
    1920x1080 @ 60.000000 Hz
    1920x1080 @ 60.000000 Hz

Output eDP-1 'Unknown 0x06DF 0x00000000' (inactive)
  Available modes:
    1920x1080 @ 48.009998 Hz
    1920x1080 @ 60.012001 Hz

**Comment by sydneymeyer** [comment]
@RedSoxFan or do you meant swaymsg -t get_inputs?

Input device: Apple Wireless Keyboard
  Type: Keyboard
  Identifier: 1452:570:Apple_Wireless_Keyboard
  Product ID: 570
  Vendor ID: 1452
  Active Keyboard Layout: German
  Libinput Send Events: enabled

Input device: ThinkPad Extra Buttons
  Type: Keyboard
  Identifier: 6058:20564:ThinkPad_Extra_Buttons
  Product ID: 20564
  Vendor ID: 6058
  Active Keyboard Layout: German
  Libinput Send Events: enabled

Input device: TPPS/2 Elan TrackPoint
  Type: Mouse
  Identifier: 2:10:TPPS/2_Elan_TrackPoint
  Product ID: 10
  Vendor ID: 2
  Libinput Send Events: enabled

Input device: SynPS/2 Synaptics TouchPad
  Type: Touchpad
  Identifier: 2:7:SynPS/2_Synaptics_TouchPad
  Product ID: 7
  Vendor ID: 2
  Libinput Send Events: enabled

Input device: AT Translated Set 2 keyboard
  Type: Keyboard
  Identifier: 1:1:AT_Translated_Set_2_keyboard
  Product ID: 1
  Vendor ID: 1
  Active Keyboard Layout: German
  Libinput Send Events: enabled

Input device: Apple Inc. Magic Trackpad 2
  Type: Touchpad
  Identifier: 1452:613:Apple_Inc._Magic_Trackpad_2
  Product ID: 613
  Vendor ID: 1452
  Libinput Send Events: enabled

Input device: Sleep Button
  Type: Keyboard
  Identifier: 0:3:Sleep_Button
  Product ID: 3
  Vendor ID: 0
  Active Keyboard Layout: German
  Libinput Send Events: enabled

Input device: Lid Switch
  Type: Switch
  Identifier: 0:5:Lid_Switch
  Product ID: 5
  Vendor ID: 0
  Libinput Send Events: enabled

Input device: Video Bus
  Type: Keyboard
  Identifier: 0:6:Video_Bus
  Product ID: 6
  Vendor ID: 0
  Active Keyboard Layout: German
  Libinput Send Events: enabled

Input device: Power Button
  Type: Keyboard
  Identifier: 0:1:Power_Button
  Product ID: 1
  Vendor ID: 0
  Active Keyboard Layout: German
  Libinput Send Events: enabled

**Comment by sydneymeyer** [comment]
@RedSoxFan Indeed, nevermind previous comment. This happens only if the internal display is disabled, after enabling the internal laptop display (eDP-1) the context menus show up on DP-4.

**Comment by RedSoxFan** [comment]
Yup, this is #3135. These are application bugs. They are using a [deprecated GTK function](https://github.com/swaywm/sway/issues/3135#issuecomment-448794177) that is not supported on Wayland and may result in incorrect positioning of context menus, tooltips, etc.

**Comment by sydneymeyer** [comment]
@RedSoxFan I see, thanks for the explanation. There are apparently already bugs [1] reported regarding this issue, at least for transmission.

[1]https://github.com/transmission/transmission/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+wayland
