### ISSUE TITLE
Exchanging two keys in keyboard layout

### ISSUE THREAD

**Issue by mielouk** [swaywm/sway#4396]
swaymsg -t get_version
sway version 1.0

* Configuration File:
https://8n1.org/15696/15ad

Finally, explain the steps you took in plain English to reproduce the problem below.

* Stack Trace, if sway crashes:

If you use systemd, you should be able to open the coredump of the most recent crash with GDB like so:

    coredumpctl gdb sway

And then type `bt full` to obtain the stack trace.

**Comment by emersion** [comment]
https://github.com/swaywm/sway/wiki#xmodmap-equivalent
