### ISSUE TITLE
Exchanging two keys in keyboard layout

### ISSUE THREAD

**Issue by mielouk** [swaywm/sway#4397]
swaymsg -t get_version
sway version 1.0

* Configuration File:
https://8n1.org/15696/15ad

To be able to type in Dutch more easily with the de(bone) layout, I need to switch J and Q in the layout, as I've learned [here](https://github.com/swaywm/sway/issues/4250) from @RedSoxFan 

Till now [this](https://8n1.org/15697/4279) is what I got, which reverts me to QWERTY and I'm not sure how to progress or what I did wrong.

**Comment by emersion** [comment]
(Closing because this isn't a sway bug.)

**Comment by mielouk** [comment]
Where should I put it then?

**Comment by RedSoxFan** [comment]
If it's reverting to QWERTY, then your custom layout either cannot be found or is invalid. If you are running sway master, swaynag should show the first line of the error. For 1.1.1 or the full error message, look at a debug log. FWIW, the layout you linked works for me so I would check the location you have it saved to

Either way, as emersion pointed out this isn't a sway bug. #sway on irc.freenode.net would be a better location for this sort of discussion.

**Comment by mielouk** [comment]
Due to the help from @progandy I [found](https://github.com/xkbcommon/libxkbcommon/issues/102) my user error.

The new partial layout in ~/.xkb/symbols/de-bone-j-q looks like this:

```
default partial alphanumeric_keys
xkb_symbols "basic" {
  include "de(bone)"
	name [Group1] = "BoneJQ";
	key <AD01> { [ q, Q, at, U03D5, Prior, Prior, U211A ] };
	key <AC11> { [ j, J, ellipsis, Greek_theta, period, KP_Decimal, Greek_THETA ] };
};
```
To find the right content for the brackets I used xmodmap -pke, deleted the first doubled entries and separated the rest with commas. The 5th and 6th positions were exchanged to keep the functionality. 

In /usr/share/X11/xkb/keycodes/evdev it is possible to find the keycode corresponding with the keypos (AD, AC, ....)

This layout is now called upon in the sway config via:

```
input type:keyboard xkb_layout "de-bone-j-q"
input * xkb_variant ""
input "DasKeyboard" xkb_model "pc105"
```

Note the empty variant and that there is only one layout! (My bad, thx again @progandy )

The sway wiki to change the layout like with xmodmap [points](https://github.com/swaywm/sway/issues/4250) towards the bug report answered by @RedSoxFan . If I would've used the IRC nobody could find this explanation.

Thx to everybody involved!
