### ISSUE TITLE
Systemd integration SWAYSOCK environment variable missing

### ISSUE THREAD

**Issue by nwallace** [swaywm/sway#4398]
Following instructions from [this wiki page](https://github.com/swaywm/sway/wiki/Systemd-integration), I set up Waybar to run as a user systemd service. But waybar's environment apparently doesn't see the SWAYSOCK variable:

```
$ systemctl --user status waybar.service
# ... elided
[warning] module sway/workspaces: Disabling module "sway/workspaces", Socket path is empty
# ... elided
``` 

That warning comes from [a line of code which tries to read the value of the `SWAYSOCK` env variable](https://github.com/Alexays/Waybar/blob/5b270dae0dd89b3146983c78869d42a5abcbd751/src/modules/sway/ipc/client.cpp#L45).

I can fix the problem after starting sway by executing `systemctl --user import-environment SWAYSOCK` then restarting waybar.service, but if this is a consistent problem across systems, the wiki page should be updated either with a fix or a warning.

Relevant config files:

```
File: /etc/sway/config.d/10-systemd
───────────────────────────────────────────────────────────────────────────────
exec "systemctl --user import-environment; systemctl --user start sway-session.
target"
───────────────────────────────────────────────────────────────────────────────
───────────────────────────────────────────────────────────────────────────────
File: .config/systemd/user/sway-session.target
───────────────────────────────────────────────────────────────────────────────
[Unit]
Description=sway compositor session
Documentation=man:systemd.special(7)
BindsTo=graphical-session.target
Wants=graphical-session-pre.target
After=graphical-session-pre.target
───────────────────────────────────────────────────────────────────────────────
───────────────────────────────────────────────────────────────────────────────
File: .config/systemd/user/waybar.service
───────────────────────────────────────────────────────────────────────────────
[Unit]
Description=Highly customizable status bar for wlroots compositors.
Documentation=https://github.com/Alexays/Waybar/wiki/
PartOf=graphical-session.target

[Service]
Type=simple
ExecStart=/usr/bin/waybar --log-level warning

[Install]
WantedBy=sway-session.target
```

**Comment by Emantor** [comment]
Looks like systemd does not like complex environment variables during import, see i.e. https://github.com/systemd/systemd/issues/5481 and follow-ups.
I think its best to restrict the imports to SWAYSOCK anyway, since other ENV variables might have unintended side effects within the systemd user environments. Can you change the wiki page accordingly?

**Comment by nwallace** [comment]
I'll try changing `/etc/sway/config.d/10-systemd` to import just SWAYSOCK later today. If that works, I'll update the wiki and close this. Otherwise, I'll report back

**Comment by emersion** [comment]
(Closing since this isn't a sway bug.)

**Comment by nwallace** [comment]
@emersion Is there a better way to report issues that aren't code bugs?

In the meantime, I managed to fix this issue for myself by moving the `exec` call out of the system config file (`/etc/sway/config.d/10-systemd`) into my own user config file (`~/.config/sway/config`). I kept the line exactly the same:

```
File: ~/.config/sway/config
───────────────────────────────────────────────────────────────────────────────
# ...
exec "systemctl --user import-environment; systemctl --user start sway-session.
target"
# ...
```
I don't understand why this made a difference, though, so I'm reticent to update the wiki. Is it because I configured the systemd target and its services for my personal user, rather than as system services? Would the original version have worked if I'd done those as system services? Why didn't it work with my setup?

**Comment by freed00m** [comment]
Have anyone of you figured out how to get SWAYSOCK in the systemd --user environment (for services) without calling "systemctl --user import-environment SWAYSOCK" from shell?

Calling it inside the systemd service unit wont actually import it.

The weird thing I start both sway and waybar after graphical target reached from default getty text login and SWAYSOCK is available in my enironment under sway.

sway service
```
[Unit]
Description=Sway compositor session
Documentation=man:sway(5)
BindsTo=graphical-session.target
Wants=graphical-session-pre.target
After=graphical-session-pre.target

[Service]
Type=simple
Environment="XDG_SESSION_ID=1"
#EnvironmentFile="%h/.config/sway/env
ExecStart=/usr/bin/sway
Restart=on-failure
RestartSec=1
TimeoutStopSec=10
```

sway session Target
```
[Unit]
Description=sway compositor session
Documentation=man:systemd.special(7)
BindsTo=graphical-session.target
Wants=graphical-session-pre.target
After=graphical-session-pre.target

[Install]
WantedBy=default.target
```

Waybar  service
```
[Unit]
Description=Highly customizable Wayland bar for Sway and Wlroots based compositors.
Documentation=https://github.com/Alexays/Waybar/wiki/
PartOf=graphical-session.target

[Service]
Type=simple
# This is needed because starting concurently and display not ready yet
ExecStartPre=sleep 1i
## Executing systemctl --user import-environment SWAYSOCK has no effect
ExecStart=/usr/bin/waybar

[Install]
WantedBy=sway-session.target
```
