### ISSUE TITLE
unable to change keyboard layout xkb_layout unknow/invalid command

### ISSUE THREAD

**Issue by stockersky** [swaywm/sway#4399]
**sway version**

sway-0.15.2-3.fc30.x86_64
sway version  (2019-02-07, branch "")

**config file**
Original config file in /etc/sway and just added those in the beginning of the file:
```
input type:keyboard {
    xkb_layout "fr"
    xkb_variant ",azerty"
}
```

returns:
```
'xkb_layout "fr"' : unknown/invalid command
'xkb_variant ",azerty"' : unknown/invalid command
```

I tried different approaches (fr not surrounded by double quote, etc...)

What's wrong with this?

**Comment by emersion** [comment]
Sway 0.15 is outdated, please upgrade to >= 1.0.
