### ISSUE TITLE
[Question] application launcher via terminal

### ISSUE THREAD

**Issue by GitHubRepositoryX** [swaywm/sway#4401]
Hi,

I am completely new to this and can't get the syntax right to accomplish a simple application launcher with alacritty. 

I rad this: https://github.com/swaywm/sway/issues/1367#issuecomment-495306710

`bindsym $mod+d exec alacritty --class 'launcher' --command bash -c 'compgen -c | sort -u | fzf | xargs -r swaymsg -t command exec'
for_window [app_id="^launcher$"] floating enable, border none, resize set width 25 ppt height 100 ppt, move position 0 px 0 px`

I want to modify it to be just alacrity with no sort, fzf or anything else. Just alacritty in a small windows eg: `for_window [app_id="^launcher$"] floating enable, border none, resize set width 25 ppt height 25 ppt, move position 0 px 0 px`

capable running commands like firefox <url> (eg firefox github.com) and after/while execution alacritty should closes automatically without closing firefox or any other app.

`# Your preferred application launcher
# Note: it's recommended that you pass the final command to sway
set $menu dmenu_path | dmenu | xargs swaymsg exec --

I know I need swaymsg in any-form, but I cant do it on my own. I am just learning and I am not very experienced. I tried so many things but haven't any success.

**Comment by emersion** [comment]
(Closing since this isn't a bug report.)

**Comment by GitHubRepositoryX** [comment]
Thanks to @kennylevinsen who help me by posting this in the #sway irc channel:
bindsym $mod+d exec alacritty --class launcher --command bash -c 'echo -n "cmd: "; read cmd; swaymsg -t command exec $cmd'
