### ISSUE TITLE
Environment not included in sway 

### ISSUE THREAD

**Issue by bbaserdem** [swaywm/sway#4403]
* Version: `sway version 1.1-rc1-83-gfc955716 (Jul 31 2019, branch 'master')` though I had this problem with previous releases.
* Configuration File: `exec $XDG_CONFIG_HOME/sway/wallpaper.sh`

Sway does not have any environment variables that I set. My global `$ZHOME` is to `~/.config/zsh/` and `~/.config/zsh/.zshenv` is picked there. My .bash_profile and .Xresources are pointed to sourcing my zshenv. This behaviour is consistent when I run sway from tty (zsh as my login shell, so variables are avaliable there) or from sddm. Everything else works.

There are multiple issues I have due to this. Exec lines don't work when the path includes an environment variable. My status bar (waybar) does not see my custom scripts since their location is not hard coded. I cannot select gtk themes.

**Comment by ddevault** [comment]
I don't know what your issue is but it's not sway's fault. Direct your investigation elsewhere.

**Comment by MichaelRBond** [comment]
I'm seeing the same issue. 

dmenu/rofi all work under X (using i3) but in Wayland the `$PATH` variable is not available. 

my solution for `rofi` was to create a bash script that sources my `.bashrc` file before launching rofi. The downside to this approach is that it takes a couple seconds to launch. 

I've seen several other solutions, mostly pertaining to gnome:
https://superuser.com/questions/992210/how-to-set-environment-variables-for-a-gnome-wayland-session

https://superuser.com/questions/992210/how-to-set-environment-variables-for-a-gnome-wayland-session

**Comment by freed00m** [comment]
@MichaelRBond Look at here, https://github.com/swaywm/sway/issues/4479 If you set PATH with systemd environment.d it fails to do so if you use GDM or SDDM with sway. 
Possibly not sway's responsibility but the login manager's one or perhaps the package manager GDM launch script for sway is missing something.
