### ISSUE TITLE
Can't use discord screenshare

### ISSUE THREAD

**Issue by lefuturiste** [swaywm/sway#4412]
* Sway Version: sway version 4.16.1 (2019-01-27)
* Debug Log: no debug logs
* Configuration File: [Open github gist](https://gist.githubusercontent.com/lefuturiste/1e76b3d96059106ffcbd2d2f0583622f/raw/45c75f93f869a220c919aec727a0adf90db77620/sway_config_last)

Step to reproduce:
- Download Discord desktop client
- Open discord
- Start a call
- Try to share the entire screen
- It will show a black screen with only the cursor moving

**Comment by ddevault** [comment]
They need to use our protocol for screen capture.

**Comment by lefuturiste** [comment]
yep but How I can use discord screen sharing with your software then ?

**Comment by ddevault** [comment]
You don't. Report the bug to them.
