### ISSUE TITLE
Any possiblility to reduce "rendering resolution" without changing output resolution ?

### ISSUE THREAD

**Issue by yw662** [swaywm/sway#4414]
I am using a laptop whose display only support 3840x2160@60, or at least it is what sway reports.
```
$ swaymsg -t get_outputs
Output eDP-1 'Unknown 0x434B 0x00000000' (focused)
  Current mode: 3840x2160 @ 59.997002 Hz
  Position: 0,0
  Scale factor: 1.000000
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 1
  Available modes:
    3840x2160 @ 59.997002 Hz
```

However, it runs on intel HD 620, which does not work well on that output. So, I want to make it faster by reducing actual resolution. I am not able to set output resolution here, but any possibility to set sth like rendering resolution ?

**Comment by RedSoxFan** [comment]
You can scale the output (ex `output eDP-1 scale 2`). See `man 5 sway-output` for more information.

**Comment by emersion** [comment]
Another feature that might help is forcing a user-provided mode on a connector.

**Comment by yw662** [comment]
@RedSoxFan Scale does not reduce redering work load.
@emersion How can I force a mode ?

**Comment by FreeFull** [comment]
The real issue is why sway is only showing a single mode for the screen. I only get a single mode too for my laptop's screen, although with X11 I get many modes. For an external screen, sway does see multiple modes, it's just the internal screen that doesn't get that for some reason.

**Comment by ascent12** [comment]
@FreeFull Laptop screens truly only advertise a single mode. X11 goes and adds all of the standard VESA modes to that list too, which we don't do.
It's not even something I'm actually opposed to doing, but it's something that nobody has bothered to do.
