### ISSUE TITLE
DPMS Off on Focused Output Only

### ISSUE THREAD

**Issue by Elevate08** [swaywm/sway#4419]
* Sway Version:
sway version 1.1-rc1-91-g90d8a4df (Aug  3 2019, branch 'master')
* Debug Log:
https://gist.github.com/Elevate08/ef5f8b6344ccda62c9ef403f252aeb28

* Configuration File:
https://github.com/Elevate08/dots/blob/master/.config/sway/config

Using swayidle to turn the displays off after x time. Only one display is turning off - It appears to be whichever display is the "active" or focused display at the time of running the swaymsg "output * dpms off" command.

What also happens during this time is it appears to remove the output from the configuration as well (workspace moves to one of the active monitors) (See Line 1056, maybe?)

I've installed everything from the AUR repo on a fresh Manjaro install yesterday. Also, for what it's worth i'm running a RX 590 GPU (One DP, 2 HDMI)

**Comment by Elevate08** [comment]
I did some review of the log and wanted to generate a new one where the DPMS off command was sent from within the sway instance that opened when running sway -d 2> ~/sway.log, i'm not sure which log version will be more helpful but both are in the gist posted above.

**Comment by RedSoxFan** [comment]
The logs appear to be from a nested sway session running in another wayland compositor. dpms is not supported on the wayland backend.

If you are using DRM, which it sounds like, please generate the debug log with a sway session running on DRM and not a nested session.

**Comment by Elevate08** [comment]
Updated the gist with a fresh log, DP-1 was the only output that successfully turned off

**Comment by Elevate08** [comment]
Might be tied to this issue swaywm/wlroots#1768 reported 13 days ago by @emersion

**Comment by Emantor** [comment]
Should be fixed by the revert in #4434 and swaywm/wlroots#1781

**Comment by Elevate08** [comment]
Thanks for the fix, tested and working great again.

I'm adding a new log to the gist link in my original post in case there is anything valuable.
