### ISSUE TITLE
Feature request: Don't hide cursor when holding down buttons

### ISSUE THREAD

**Issue by cafehaine** [swaywm/sway#4420]
The current behavior for `hide_cursor` is quite buggy for multiple applications. Some examples:
- Firefox: Hold down left click on a text input with text, wait for the cursor to disapear, release left mouse button, now your cursor moves the selection as if you were still holding the left mouse button.
- Minecraft: break blocks in a line without releasing the left button and without moving the mouse. When the cursor 'disapears', you can no longer move the view and you have to release the left mouse button

Preventing the cursor from hiding when any mouse button is held would prevent those weird behaviors.

My config is available here https://github.com/cafehaine/dotfiles/blob/master/.config/sway/config

**Comment by RedSoxFan** [comment]
Sounds reasonable to me. Submitted as #4424
