### ISSUE TITLE
sway change $XCURSOR_SIZE unexpectly

### ISSUE THREAD

**Issue by yw662** [swaywm/sway#4430]
run sway by
```
if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
XCURSOR_SIZE=60 \
exec sway
fi
```
However, open a terminal and run `echo $XCURSOR_SIZE`:
```
➜  ~ echo $XCURSOR_SIZE 
24
```

Any ideas ?

**Comment by progandy** [comment]
The git version has a ```xcursor_theme``` configuration command and sets the size to 24 if you don't use it to change the theme and size.

https://github.com/swaywm/sway/blob/f59b665792fb664d00c3acd91e30977a05dc09f3/sway/sway-input.5.scd#L222

**Comment by yw662** [comment]
@progandy I am on sway 1.0
```
sway --version
sway version 1.0
```
And `seat seat0 xcursor_theme default 48` makes sway complain for "unknown/invalid command xursor_theme".

**Comment by progandy** [comment]
Sway 1.0 and earlier has this 24px size hardcoded with no configuration option.

**Comment by emersion** [comment]
Indeed. Please uprade.

**Comment by ctype** [comment]
i just want to add here that sway now supports setting the cursor theme and size with the xcursor_theme option in the config and i also had to set it with gsettings for gtk applications like:
```
seat seat0 xcursor_theme ComixCursors-Green 48
exec_always {
gsettings set org.gnome.desktop.interface cursor-theme ComixCursors-Green
gsettings set org.gnome.desktop.interface cursor-size 48
}
```
see: https://github.com/swaywm/sway/blob/f59b665792fb664d00c3acd91e30977a05dc09f3/sway/sway-input.5.scd#L222
