### ISSUE TITLE
Two distinct outputs for 4k MST monitor

### ISSUE THREAD

**Issue by kiryl** [swaywm/sway#4431]
I have 4k MST monitor (Dell UP2414Q). It presents itself as two outputs 1920x2160 each and sway treats them as a separate outputs. I don't see a way to merge them together.

The issue has been handed on Xorg side with introduction of 'monitor' concept in Xrandr 1.5. See https://keithp.com/blogs/MST-monitors/.

Can we get something similar for sway?

* Sway Version:

sway version 1.0
(It's actually sway-1.1.1 from Gentoo)

* Debug Log:

https://gist.github.com/kiryl/56db175226f4277917cdb0ba99417695

**Comment by Emantor** [comment]
swaywm/wlroots#1580

**Comment by emersion** [comment]
Indeed, this is a duplicate.
