### ISSUE TITLE
Workspaces shuffle after idle on multi-output setups

### ISSUE THREAD

**Issue by kennylevinsen** [swaywm/sway#4432]
Workspaces often shuffle when displays wake from idle

# How to reproduce

1. Run a setup with multiple outputs that have swayidle dpms off'ing displays
2. Wait for displays to be disabled, and subsequently hardware suspend
3. Wake the system up
4. Observe workspace locations

# Expected result

Workspaces should be located on the outputs that they were on previously

# Actual result

Workspaces are often shuffled, so that whatever was on output 1 is now on output 2 and vice versa.

While this may seem like a minor issue, it can in fact be extremely frustrating.

**Comment by RedSoxFan** [comment]
I can't replicate, but I do have one theory. Do your output names change after waking up? The output priority code currently uses the output names. I think it might need to be changed to use the output identifiers instead so that it works correctly for DP MST (and maybe others).

**Comment by kennylevinsen** [comment]
Yes, the names swapped in the most recent reproduction, so I suppose that is the case.
