### ISSUE TITLE
Inhibit idle if a window has focus is playing audio/video

### ISSUE THREAD

**Issue by h3fang** [swaywm/sway#4433]
Similar to #2595 #3070, I want to inhibit idle if a window (Chromium, etc.) has focus is playing audio/video (not paused), but not necessarily full screen.

Currently, I am using this approach (https://github.com/swaywm/sway/issues/2595#issuecomment-480673973) by checking whether Chromium is focused and playing in the lock script.

```bash
if [[ $1 != "force" ]]; then
    chromium_focused=$(swaymsg -t get_tree | jq -r '.. | select(.window_properties?.class == "Chromium") | .focused' | grep "true" | wc -l)
    chromium_playing=$(pacmd list-sink-inputs | grep 'application.name = "Chromium"' | wc -l)
    if [[ $chromium_focused -gt 0 && $chromium_playing -gt 0 ]]; then
        echo "Inhibit idle while chromium is focused and playing"
        exit 1
    fi
fi
```

I wander if we can make the inhibit rules more general, and drop this hack.

sway 1.1.1, swayidle 1.5

**Comment by ddevault** [comment]
We have no way of determining if a window is playing audio or video.

**Comment by emersion** [comment]
This should be filled as a feature request for Chromium.

**Comment by h3fang** [comment]
> This should be filled as a feature request for Chromium.

Maybe, when I use i3lock + xss-lock, Chromium do inhibit idle when I am playing video (not full screen).

**Comment by progandy** [comment]
As far as I know chromium is still running with xwayland, so this discussion about mpv should apply here as well:

https://gitlab.freedesktop.org/xorg/xserver/issues/675

**Comment by h3fang** [comment]
Thanks, now I know more about the ping pong game. There seems to be a lot of work to do. I think I will stick to my hack for now.
