### ISSUE TITLE
Option to change the swaybar workspace border thickness

### ISSUE THREAD

**Issue by nostdm** [swaywm/sway#4436]
There are settings that change the border thickness for various elements:

    border pixel n
    default_border pixel n
    default_floating_border pixel n
    titlebar_border_thickness n

But there doesn't seem to be a way to modify the swaybar workspace border. I've set all my borders to 2px but the active workspace border has 1px by default and it looks a bit odd. Ideally there would be a setting like `workspace_border_thickness n` inside the `bar {}` configuration.

Are there any plans to support something like this?

**Comment by emersion** [comment]
Is there a ticket to support this in i3 as well?

**Comment by nostdm** [comment]
Is sway exactly 1:1 with i3 (bug for bug, feature for feature) or is it a superset of i3? 
If the former then feel free to close the issue.

**Comment by emersion** [comment]
We prefer new features to be discussed with i3 first.

**Comment by nostdm** [comment]
Ok, I don't use i3 personally so didn't know if the problem exists in i3 also. For now it doesn't bother me too much so will maybe revisit this once I have some time to spare. Will close the issue for now.

**Comment by Xgames123** [comment]
Will a pull request be accepted for this?
If people want compatibility with i3 they can just not use the option.

**Comment by emersion** [comment]
See https://github.com/swaywm/sway/blob/master/CONTRIBUTING.md#scope-of-future-changes-to-sway
