### ISSUE TITLE
swaylock & libvirt package conflict

### ISSUE THREAD

**Issue by Spectrik** [swaywm/sway#4439]
Hello guys,

this is not a bug, I am asking rather for some recommendation.

I run fedora 30. I installed swaylock from fedora 31 since it is not available for 30. Now, I've tried to install libvirt but there is a conflict:

`
Error:
 Problem: conflicting requests
  - package libvirt-5.1.0-9.fc30.x86_64 requires libvirt-daemon-driver-qemu = 5.1.0-9.fc30, but none of the providers can be installed
  - package libvirt-5.1.0-4.fc30.x86_64 requires libvirt-daemon-driver-qemu = 5.1.0-4.fc30, but none of the providers can be installed
  - package libvirt-daemon-driver-qemu-5.1.0-9.fc30.x86_64 requires systemd-container, but none of the providers can be installed
  - package libvirt-daemon-driver-qemu-5.1.0-4.fc30.x86_64 requires systemd-container, but none of the providers can be installed
  - package systemd-container-241-10.git511646b.fc30.i686 requires systemd(x86-32) = 241-10.git511646b.fc30, but none of the providers can be installed
  - package systemd-container-241-10.git511646b.fc30.x86_64 requires systemd(x86-64) = 241-10.git511646b.fc30, but none of the providers can be installed
  - package systemd-container-241-7.gita2eaa1c.fc30.i686 requires systemd(x86-32) = 241-7.gita2eaa1c.fc30, but none of the providers can be installed
  - package systemd-container-241-7.gita2eaa1c.fc30.x86_64 requires systemd(x86-64) = 241-7.gita2eaa1c.fc30, but none of the providers can be installed
  - package systemd-241-10.git511646b.fc30.i686 requires systemd-libs = 241-10.git511646b.fc30, but none of the providers can be installed
  - package systemd-241-10.git511646b.fc30.x86_64 requires systemd-libs = 241-10.git511646b.fc30, but none of the providers can be installed
  - package systemd-241-7.gita2eaa1c.fc30.i686 requires systemd-libs = 241-7.gita2eaa1c.fc30, but none of the providers can be installed
  - package systemd-241-7.gita2eaa1c.fc30.x86_64 requires systemd-libs = 241-7.gita2eaa1c.fc30, but none of the providers can be installed
  - systemd-libs-241-10.git511646b.fc30.i686 has inferior architecture
  - systemd-libs-241-7.gita2eaa1c.fc30.i686 has inferior architecture
  - cannot install both systemd-libs-241-10.git511646b.fc30.x86_64 and systemd-libs-242-6.git9d34e79.fc31.x86_64
  - cannot install both systemd-libs-241-7.gita2eaa1c.fc30.x86_64 and systemd-libs-242-6.git9d34e79.fc31.x86_64
  - package sway-1.1.1-1.fc31.x86_64 requires libsystemd.so.0(LIBSYSTEMD_243)(64bit), but none of the providers can be installed
  - problem with installed package sway-1.1.1-1.fc31.x86_64
  - package swaylock-1.4-1.fc31.x86_64 conflicts with sway < 1.0 provided by sway-0.15.2-3.fc30.x86_64
  - problem with installed package swaylock-1.4-1.fc31.x86_64
  - package sway-1.1.1-1.module_f30+5053+6884d60c.x86_64 is excluded
  - package swaylock-1.4-1.module_f30+4821+84d606f2.x86_64 is excluded
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages)
`

If I try to add --allowerasing option when installing, we get:

`
Removing dependent packages:
 swaybg                                                             x86_64                         1.0-1.fc31                                          @updates                          64 k
 swaylock                                                           x86_64                         1.4-1.fc31                                          @updates                         119 k
Downgrading:
 iptables                                                           x86_64                         1.8.2-3.fc30                                        updates                          364 k
 iptables-libs                                                      x86_64                         1.8.2-3.fc30                                        updates                           49 k
 systemd                                                            x86_64                         241-10.git511646b.fc30                              updates                          3.6 M
 systemd-libs                                                       x86_64                         241-10.git511646b.fc30                              updates                          473 k
 systemd-pam                                                        x86_64                         241-10.git511646b.fc30                              updates                          150 k
 systemd-rpm-macros                                                 noarch                         241-10.git511646b.fc30                              updates                           21 k
 systemd-udev                                                       x86_64                         241-10.git511646b.fc30                              updates                          1.3 M
 qrencode-libs                                                      x86_64                         3.4.4-8.fc30                                        fedora                            53 k
 sway                                                               x86_64                         0.15.2-3.fc30
`

I **_need_** libvirt but I also need to be able to lock my computer. Is there any way to workaround this except for waiting fedora 31 (who the hell knows when it comes out since Red Hat is now under IBM)

Thanks.

**Comment by Emantor** [comment]
1. This is not a sway issue.
2. Mixing packages from different releases is not supported on any release distribution I know.

You have essentially created a "Franken-Fedora" which has packages from both releases installed. My recommendation is to try to fix this by either removing the Fedora 31 packages, reinstallation and than compiling swaylock from source instead of using the Fedora 31 package or by moving fully to Fedora 31.

**Comment by RedSoxFan** [comment]
Closing since this is not a sway issue. Install from source or use a COPR
