### ISSUE TITLE
sctk CSD disappears during resize

### ISSUE THREAD

**Issue by YaLTeR** [swaywm/sway#4441]
* Sway Version: `1.1-rc1-99-g724926ea (Aug  7 2019, branch 'makepkg')`
* Debug Log: https://gist.github.com/YaLTeR/399b7e98d9f1d78b4a69b2992812adae
* Configuration File: default

`smithay-client-toolkit` CSD briefly disappears in sway during resize. This can be seen on both sctk examples and `winit` windows, such as `alacritty`. Doesn't happen on Weston. [Video.](https://streamable.com/ngorc)

1. Open `alacritty` or a sctk example.
1. Make it floating.
1. `swaymsg border csd`
1. Try resizing by the border or with a shortcut, see CSD disappear.

**Comment by kchibisov** [comment]
Fixed by #5403.
