### ISSUE TITLE
Mouse pointer position in VirtualBox is wrong

### ISSUE THREAD

**Issue by kamulos** [swaywm/sway#4454]
Running Manjaro in Virtualbox:

pacman -Q sway
says: sway 1.1.1-3

swaymsg -t get_version
says: sway version 1.0

The default mouse pointer is correct, the other ones are at the wrong position. If the mouse pointer changes it jumps.

Especially irritating is the text selection pointer. I have to click below and right of the position I actually want to select.

Also not good is the hand pointer which I also have to click right of the desired position.

**Comment by emersion** [comment]
Your bug report is missing debug logs. Please add a link to the full debug log file.

**Comment by kamulos** [comment]
Ah sorry, this is it:
https://gist.github.com/kamulos/bbc1f99afbaa12a6070794075bc5531f

**Comment by freed00m** [comment]
I also observe this behavior if I use multi monitor setup.
On single monitor setup I only observe an offset, like the cursor icon is offseted by circa 15px in both coordinates.

**Comment by kamulos** [comment]
Also this is happens only when mouse pointer integration is used.

This is what I found about it:

> When mouse integration is enabled, this becomes slightly more complicated. VirtualBox emulates a graphics tablet (similar to a touch screen), which can send exact positions instead of just "left", "right", "up", "down". Unfortunately these positions are not in pixels on the screen, but in percentages - e.g. 56 percent along the X axis from the left to the right edge and 73 percent along the Y axis from the top to the bottom edge. For this to work correctly, the guest and the host have to agree about which positions on the tablet correspond to which positions on the guest screens - e.g. virtual screen one might go from 0 to 50 percent along the X axis and from 0 to 100 on the Y axis, while virtual screen two might go from 50 to 100 on X and also from 0 to 100 on Y. This corresponds to screen two laid out to the right of screen one, with the right edge of screen one exactly matching the left edge of screen two. If host and guest agree about this layout then mouse integration can work. Otherwise the position of clicks in the guest will not correctly match the pointer location.

[https://www.virtualbox.org/wiki/MouseInput](https://www.virtualbox.org/wiki/MouseInput)

**Comment by kamulos** [comment]
Now the mouse pointer is gone. But after setting `WLR_NO_HARDWARE_CURSORS=1` it reappears and I can not reproduce this problem. Seems to be solved for me.
