### ISSUE TITLE
Spurious crash on config reload

### ISSUE THREAD

**Issue by YaLTeR** [swaywm/sway#4464]
* Sway Version: `1.2-rc1-15-g84417119 (Aug 16 2019, branch 'makepkg')`
* Stack Trace, if sway crashes: https://gist.github.com/YaLTeR/386767b84b85f8912995f90bf0fc18d8

Enabled the debug log, if this happens again I'll attach it.

**Comment by RedSoxFan** [comment]
Duplicate of #3914
