### ISSUE TITLE
Setting PATH from environment.d

### ISSUE THREAD

**Issue by dinnymate** [swaywm/sway#4479]
My sway config contains the line:
`exec_always "systemctl --user import-environment"`
It works fine for setting most environment variables but it ignores my PATH setting. 
If I change it to PATH1 it works fine.

**Comment by ddevault** [comment]
Whatever this is, it's not our problem.

**Comment by dinnymate** [comment]
Then, at least update the documentation about it, and provide an alternate solution. Thanks

**Comment by emersion** [comment]
We have no docs about this. If you're referring to the wiki, it's user-contributed, we aren't maintaining it.

**Comment by Emantor** [comment]
See #4398, this is more of a systemd issue and you can update the wiki.

**Comment by rumpelsepp** [comment]
https://github.com/systemd/systemd/issues/6414

**Comment by freed00m** [comment]
@dinnymate I was baffled by this also, why in other DE the path can be set from ~/.config/environment.d/ but from sway it was impossible while other variables were loaded. 

For others stumbling uppon this and using pam, you can set path ~/-pam_environment for example like this

```
PATH        DEFAULT=/home/@{PAM_USER}/.local/bin:${PATH}
```

**Comment by EvanCarroll** [comment]
I also came here ready to file this as a bug. It's even clearly supported in `man environment.d`

**Comment by freed00m** [comment]
@EvanCarroll - there is a milion ways how the PATH could've been destroyed in the process.

For example I am currently trying to know why when Sway starts it sets up the SWAYSOCK variable but for some reason is not imported in the systemd --user environment, for some reason you can prevent that somehow.

For example when I use GDM for loggin, I don't have PATH set from systemctl --user import-environment but if I log from agetty and then start sway as service I do have the PATH :O

**Comment by EvanCarroll** [comment]
[Well, this is the reason I found which seems to be it for me,](https://github.com/systemd/systemd/issues/6414#issuecomment-323803511)

> This is what Debian installs in /etc/profile per default. As you can see, this will statically set PATH to a value depending on the effective UID.

Essentially Debian runs `/etc/profile` AFTER `system.d` there by removing `environment.d` setting of the `PATH` variable.

**Comment by freed00m** [comment]
Yep that's propably correct, I suspect there is some garbage in /etc/profile.d/*.sh

as any program can install it and F*ck with your $PATH

```
# Load profiles from /etc/profile.d
if test -d /etc/profile.d/; then
	for profile in /etc/profile.d/*.sh; do
		test -r "$profile" && . "$profile"
	done
	unset profile
fi

```

**Comment by bd-g** [comment]
For anyone using not on Debian and using GDM or KDE Plasma with this issue, see https://wiki.archlinux.org/title/Environment_variables#Per_Wayland_session
