### ISSUE TITLE
Screen tearing with AMD GPU

### ISSUE THREAD

**Issue by lazmol** [swaywm/sway#4480]
I get a lot of screen tearing (see attached images) when I start browsing the internet, especially when watching youtube videos. Moving the mouse or reloading the sway config helps usually but it comes back in a couple of minutes. First I thought it is firefox but then I experienced similar behaviour with qutebrowser as well.

It is on my laptop with amd gpu:
```
Dell Inspiron 13 7375 with GCN5 vega 10 chip, RavenRidge Radeon Vega Series:
$ lspci | grep VGA
10 02:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Raven Ridge [Radeon Vega Series / Radeon Vega Mobile Series] (rev c3)
```

I use arch linux:
```
$ uname -a
Linux 5.2.9-arch1-1-ARCH #1 SMP PREEMPT Fri Aug 16 11:29:43 UTC 2019 x86_64 GNU/Linux
```

with sway version 1.0:
```
$ swaymsg -t get_version
sway version 1.0
```

```
$ sudo pacman -Qs sway
local/sway 1.1.1-3
    Tiling Wayland compositor and replacement for the i3 window manager
local/swaybg 1.0-3
    Wallpaper tool for Wayland compositors
$ sudo pacman -Qs wlroots
local/wlroots 0.6.0-2
    Modular Wayland compositor library
```

I also saw some screen tearing with the default config of sway (though much less). Tried to capture some debug log while it happened with the default config.
Unfortunately I could not reproduce so much screen tearing with the default config of sway. Nevertheless see the debug log here:
https://gist.github.com/lazmol/f78234c85d2323fad19a3a21a81f46f6
I've also uploaded my config just in case to the gist.

One more thing, I am using xonsh as my default shell and I have some env vars set in my .xonshrc file for wayland:
```
$MOZ_ENABLE_WAYLAND = 1
$GDK_BACKEND = 'wayland'
$QT_WAYLAND_FORCE_DPI = 'physical'
$QT_QPA_PLATFORM = 'wayland-egl'
$CLUTTER_BACKEND = 'wayland'
$SDL_VIDEODRIVER = 'wayland'
$BEMENU_BACKEND = 'wayland'
```
Are those ok?

Please tell me on how I can help with resolving this issue! I don't want to go back to KDE, sway is just much better. :)

**Comment by Emantor** [comment]
Probably [this FD bug](https://bugs.freedesktop.org/show_bug.cgi?id=111211). Can you test with a 5.1.x or 5.3-rc kernel?

**Comment by lazmol** [comment]
Thanks @Emantor! It must be it.
Tried 5.3rc5 kernel ->the problem persists. Hope it gets fixed...
Downgraded to 5.1.16 -> I experience no screen tearing so far.
I guess the issue can be closed as it is caused by the kernel.

**Comment by emersion** [comment]
Thanks @Emantor for finding this FDO issue!
