### ISSUE TITLE
KDE-applications misbehave unless launched with dbus-launch

### ISSUE THREAD

**Issue by daanjderuiter** [swaywm/sway#4481]
I am aware that this is something that Sway is not at all responsible for, but it ís the only environment  where I have experienced this issue. I hope some of you nevertheless have some advice how I might solve this issue, thanks for hearing me out.
I have used Plasma for a while before using Sway, and although I switched away from their WM, I did continue to use some of their utilities. Two of these are KDEConnect and Dolphin. The issue under Sway is that they will exhibit the wrong behaviour; KDEConnect just fails outright:
```
$ kdeconnect-cli -l
error activating kdeconnectd: QDBusError("", "")
error: Process org.kde.kdeconnect received signal 6
```
Graphical interfaces to KDEConnect show similar errors. This behaviour is fixed when the application is launched explicitly with `dbus-launch`. Similarly, Dolphin cannot access its wallet for remote share credentials without `dbus-launch` and fails to connect me to shares that I need to access. I don't really feel like creating a huge pile of custom desktop files to cope with this, so I was wondering if there might exist a better workaround for this issue, especially since this is an issue that I didn't experience in other WMs (including i3).
I am running Sway 1.1.1-3, though I have been experiencing this issue for a while now.

**Comment by emersion** [comment]
(Closing since this isn't a sway bug)

**Comment by MayeulC** [comment]
FWIW, I run `export $(dbus-launch)` before `sway` in my sway launch script. I hope that helps you?
