### ISSUE TITLE
exec sudo <command>: not recognized in Sway config file

### ISSUE THREAD

**Issue by Gahia123** [swaywm/sway#4482]
Some aplications need root or _sudo_ permission for being executed, in example I'm developing a machine graphical interface that execute a code to modify GPIO ports and requires to be root or use _sudo_ command for being executed. My Sway config file is the following: 
`exec sudo python program.py` 
The program launch correctly without permissions if I don't use _sudo_, otherwise nothing happen. 
sway version 1.0
[sway.log](https://github.com/swaywm/sway/files/3527475/sway.log)

**Comment by emersion** [comment]
Your bug report is missing debug logs. Please add a link to the full debug log file.

**Comment by Gahia123** [comment]
I've attach that file :)

**Comment by RedSoxFan** [comment]
I'm not sure what you did to get that debug log, but sway is failing well before reading the config in that log.

However, your issue that you need to use `sudo --askpass` with a password helper configured (see `man 8 sudo` for more information on that). sudo won't be able to use standard in to prompt for it.

Closing since this is not a sway issue.

**Comment by Gahia123** [comment]
Sway read the config file, I've configured sudoers file to avoid request the user password, I can open a terminal emulator in Sway and execute the code using _sudo_ without request a password. Nevertheless the command does not execute using the previous _config_ file.
I can do the abovesaid using i3 winows manager and work.

**Comment by RedSoxFan** [comment]
> I've configured sudoers file to avoid request the user password

In that case, can you generate another debug log that actually has sway starting?

**Comment by Gahia123** [comment]
The last log file was wrong, my mistake: executed via ssh. Those're correct:  
config file:
`bindsym Mod4+Return exec urxvt`
`exec sudo python /home/alarm/main.py`
[sway.log](https://github.com/swaywm/sway/files/3527868/sway.log)

**Comment by kennylevinsen** [comment]
sudo doesn't like being run outside an interactive tty. You can see similar issues if you try to run e.g. `ssh <host> sudo blah`.

You can try to ensure that NOPASSWD is set in sudoers, but I wouldn't recommend such a configuration. Closing as it is not an issue with sway.
