### ISSUE TITLE
Web game not working

### ISSUE THREAD

**Issue by lovesegfault** [swaywm/sway#4486]
I have Firefox (Wayland) running on Sway 1.1.1, and I was trying to play https://marsfortherich.com

Whenever I enter the game, if I click, it "captures" the pointer and then it goes insane rotating all over the place. I believe this to be a bug in Sway.

I remember there was some protocol required for this to work, but I couldn't find an open issue on wlroots and decided to open this one to make sure I understood what was happening.

**Comment by emersion** [comment]
Firefox needs to add support for relative-pointer and pointer-constraints.
