### ISSUE TITLE
Every game using SDL-1.2 s failing to run

### ISSUE THREAD

**Issue by eternal-sorrow** [swaywm/sway#4488]
Other Xwayland apps run well. Whenever I try to start an SDL-1.2 game, it gives me error: `No available video device` and fails to start.
* Sway Version: 1.2_rc2

**Comment by SpencerMichaels** [comment]
Is `SDL_VIDEODRIVER=wayland` set in your environment? SDL will try to use X unless you set that flag. See <https://github.com/swaywm/sway/wiki/Running-programs-natively-under-wayland>.

**Comment by eternal-sorrow** [comment]
Oh, you're right.
