### ISSUE TITLE
PyCharm autosuggests will break the application

### ISSUE THREAD

**Issue by JonasKs** [swaywm/sway#4490]
There's already a [Jetbrains issue](https://youtrack.jetbrains.com/issue/IDEA-219063) on this, so feel free to close if you think it's not a Sway problem.

All versions tagged with `2019` of PyCharm breaks in my setup of Sway, while they work in Gnome.  
How to reproduce:  
-  Download newer version of PyCharm
-  Create a Python Project and let it index
-  Type something that PyCharm would give an autocomplete suggestion on, e.g. `print(`. 
-  Try to type something, nothing will happen. Moving the caret still works, deleting text still works.
-  Click somewhere in PyCharm with the mouse and you can type again, until a autocomplete suggestion pops up.

Debug log can be found [here](https://paste.fedoraproject.org/paste/AwY3LM2aQglqnN~mtXzCbA)
```
swaymsg -t get_version  
sway version 1.0
```
Default configuration file.

**Comment by freed00m** [comment]
are you using `_JAVA_AWT_WM_NONREPARENTING=1`

**Comment by JonasKs** [comment]
I’ve tried with both. If I have it off, I had to change the auto load project setting to not do anything, otherwise I was always met with a grey screen.

**Comment by Nikki1993** [comment]
Have you tried using their bintray plugin, to download and install their java8 version of jdk and restart? there seems to be a lot of issues with sway and JetBrains products on their latest jdk (which I believe is 11)

**Comment by JonasKs** [comment]
Can confirm, jdk8 works. Bintray plugin didn't work properly how ever for me, so I downloaded it manually.

Thanks mate!

**Comment by JonasKs** [comment]
JetBrains has acknowledged the bug and say they are working on a fix, see the issue linked to above.
