### ISSUE TITLE
Question: How to launch root applications like gparted

### ISSUE THREAD

**Issue by asbachb** [swaywm/sway#4492]
Hello. I wonder what's the most convenient way of running applications which need root priviliges under sway.

```
sudo gparted
[sudo] password for asbachb: 
No protocol specified
Unable to init server: Could not connect: Connection refused

(gpartedbin:1059): Gtk-WARNING **: 11:35:36.413: cannot open display: :0
```

```
gparted                                                                                                                                                  
localuser:root being added to access control list
Error executing command as another user: No authentication agent found.
localuser:root being removed from access control list
```

**Comment by freed00m** [comment]
You could try gksu. Just an idea.
`gksu <something>` no idea if this tool is still being used.

**Comment by samerickson** [comment]
Are you looking for them to just launch, or are you looking for a password dialog to prompt the opening of gparted?

**Comment by FreeFull** [comment]
The general issue is that programs running as root aren't allowed to show a GUI through Wayland. One workaround would be to run GParted in Xephyr, if it doesn't support PAM authentication.

**Comment by emersion** [comment]
(Closing since this isn't a Sway issue.)

**Comment by X0rg** [comment]
@asbachb: I use GNOME authentication agent to launch root applications.
In my `~/.config/sway/config`:
```
exec --no-startup-id /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
```

**Comment by asbachb** [comment]
> @asbachb: I use GNOME authentication agent to launch root applications.
> In my `~/.config/sway/config`:
> 
> ```
> exec --no-startup-id /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
> ```

Sorry for the late reply. But that was EXACTLY what I was looking for.

**Comment by akvadrako** [comment]
It is possible to run wayland apps as root under sway like so:
```
sudo env XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR \
  WAYLAND_DISPLAY=$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY \
  gedit
```

**Comment by m-khvoinitsky** [comment]
Yet another way, if, for some reason, previous advices doesn't work for you:
```
ssh -X root@localhost
gparted
```
(obviously, it requires configured `sshd` with allowed root login and X forwarding)

**Comment by LamaRaz** [comment]
https://wiki.archlinux.org/index.php/Running_GUI_applications_as_root

xhost si:localuser:root

this works

**Comment by emilheunecke** [comment]
> It is possible to run wayland apps as root under sway like so:
> 
> ```
> sudo env XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR gedit
> ```

This works. 

However, the following quote from [here](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) suggests this is a bad idea:
>$XDG_RUNTIME_DIR defines the base directory relative to which user-specific non-essential runtime files and other file objects (such as sockets, named pipes, ...) should be stored. The directory MUST be owned by the user, and he MUST be the only one having read and write access to it. Its Unix access mode MUST be 0700.

Could somebody explain security considerations of using $XDG_RUNTIME_DIR like this?

**Comment by caplett** [comment]
for me "sudo -E gparted" worked like a charm
