### ISSUE TITLE
Unable to open a terminal using sway config exec/bindsym

### ISSUE THREAD

**Issue by andersfylling** [swaywm/sway#4494]
* Sway Version: sway version 1.2-rc2 (Aug 23 2019, Arch Linux)
* Debug Log (as  requested): https://gist.github.com/andersfylling/905170f833cd8373e1b959b135779f1c
*Debug log (second version): https://gist.github.com/andersfylling/734886306400f004bfafc606775a051a
* Configuration File: https://gist.github.com/andersfylling/83f8124f17121499ce784db0a88cb726 (stops at line 116, notice the contents of line 118)

# Debug log (as requested)
did nothing. Just opened a transparent window (same as the terminal bug) and no info was recorded while that was open.

# Debug log (second version)
I set my .bash_profile to the following:
```
#
# ~/.bash_profile
#

[[ -f ~/.bashrc ]] && . ~/.bashrc
if [[ $(tty) = /dev/tty1 ]]; then
        export RANGER_LOAD_DEFAULT_RC=FALSE
        export SHELL=zsh
        export PATH="$PATH:/home/anders/.cargo/bin"
        export PATH="$PATH:/home/anders/go/bin"

        # wayland rendering
        export QT_WAYLAND_FORCE_DPI=physical
        export GDK_BACKEND=wayland
        export QT_QPA_PLATFORM=wayland-egl
        export CLUTTER_BACKEND=wayland
        export SDL_VIDEODRIVER=wayland
        export BEMENU_BACKEND=wayland
        export MOZ_ENABLE_WAYLAND=1
        export XKB_DEFAULT_LAYOUT=no
        export XDG_CURRENT_DESKTOP=Unity

        # start with logging
        LOG_FILE_PATH="/var/log/sway/$(date +'%Y-%m-%d').log"
        export SWAY_LOG_FILE_PATH=${LOG_FILE_PATH}
        echo "" >> ${LOG_FILE_PATH}
        echo "################################" >> ${LOG_FILE_PATH}
        echo "## Started Sway $(date +'%Y-%m-%d %H:%M')" >> ${LOG_FILE_PATH}
        sway -d 2>&1 >> ${LOG_FILE_PATH}
        LOG_FILE_PATH=""
fi
```

# Steps:
Tried starting a terminal using my windows key and the return key ($mod+Return).

# Result
A new window with a thin border appears. But the content is transparent. When focused on the new window; writing "kitty" and then hitting enter, does not create a new kitty instance.

# Extra
 - All commands which starts with $term yields the same result. 
 - Starting a kitty instance through the bemenu command, in the configuration, starts kitty successfully. Although swaymsg yields an error:
```
[
   {
     "success": false,
     "parse_error": true,
     "error": "Invalid exec command (expected at least 1 argument, got 0)"
   }
 ]
```
 - `swaymsg exec kitty` yields the same result
 - This worked on a fresh install, but I have no clue what changed. 
 - changing $term to alacritty:
 - - does not open a new window, at all
 - - `swaymsg exec alacritty` successfully opens a alacritty instance
 - - no new log output
 - screenshot: https://imgur.com/0qOIERP (left: firefox, middle: sway issue, right: normal terminal instance)
 - logs after enabling WAYLAND_DEBUG: https://gist.github.com/andersfylling/d443b428c8f32f5e5434dbb5779d944e
 - sway -C for the terminal bindsym:
```
2019-08-25 02:18:40 - [sway/commands.c:352] Config command: bindsym $mod+Return exec $term zsh
2019-08-25 02:18:40 - [sway/commands.c:372] After replacement: bindsym Mod4+Return exec kitty zsh
```

**Comment by samerickson** [comment]
Might be related to https://github.com/kovidgoyal/kitty/issues/1525

Also, read this line from the sway wiki: 

> Wayland will be selected by default. Do not set GDK_BACKEND, it will break apps (e.g. Chromium and Electron).

**Comment by andersfylling** [comment]
Hi, thanks for the heads up regarding GDK_BACKEND.

Regarding Kitty, did this not resolve my issue.

**Comment by andersfylling** [comment]
Added wayland debug logs https://gist.github.com/andersfylling/d443b428c8f32f5e5434dbb5779d944e

**Comment by samerickson** [comment]
Yeah it was wishful thinking. It's strange that the border shows up but not the actual terminal. I will spin this up in a virtual machine to do some investigating of my own tomorrow.

**Comment by andersfylling** [comment]
I've been removing quite a lot from the config now. And the title bar is not showing, earlier the border were only 1 pixel so I couldn't read the title bar. It says "wlroots - WL-1". This is not what I would have expected.

**Comment by RedSoxFan** [comment]
Your debug logs don't contain any logging from sway or wlroots. Can you please:
- switch to any tty
- directly run `env WAYLAND_DEBUG=1 sway -d >sway.log 2>&1`
- replicate the issue
- exit sway
- post the complete output of `sway.log`

> changing $term to alacritty:
> - does not open a new window, at all
>
> [...]
>
> sway -C for the terminal bindsym:
> - 2019-08-25 02:18:40 - [sway/commands.c:352] Config command: bindsym $mod+Return exec $term zsh

That's probably because alacritty (like most terminals) uses `<terminal> -e <command>`, not `<terminal> <command>`

**Comment by andersfylling** [comment]
As soon as I go into tty2 and run it, it works fine. So then I took everything inside the if scope, in the bash_profile file and moved it into a wayland-start.sh file.

Running the wayland-start.sh file also successfully starts the terminal. I'm confused now.
Also did you see the debug log I added under "extra"? That holds debug info for when i try to start a terminal in tty1 (where it fails).

**Comment by RedSoxFan** [comment]
> As soon as I go into tty2 and run it, it works fine. So then I took everything inside the if scope, in the bash_profile file and moved it into a wayland-start.sh file.
> Running the wayland-start.sh file also successfully starts the terminal. I'm confused now. It works in tty2 but not tty1..

Maybe comparing the output of `env` will yield something?

> Also did you see the debug log I added under "extra"? That holds debug info for when i try to start a terminal in tty1 (where it fails).

Yes, there is zero sway/wlroots logging there and the wayland debugging appears cut off. The last line is the start of something actually happening

> [1428913,507]  -> wl_compositor@5.create_surface(new id wl_surface@21)

**Comment by andersfylling** [comment]
stored env output to separate files, env1.txt and env2.txt for each tty respectively. Here is the diff:

```
➜ diff env1.txt env2.txt
1c1
< ALACRITTY_LOG=/tmp/Alacritty-2062.log
---
> ALACRITTY_LOG=/tmp/Alacritty-2333.log
7c7,9
< I3SOCK=/run/user/1000/sway-ipc.1000.1256.sock
---
> I3SOCK=/run/user/1000/sway-ipc.1000.2304.sock
> INVOCATION_ID=b47c8641f6704ba3a29f16c3ca6a8808
> JOURNAL_STREAM=9:103326
22c24
< SWAYSOCK=/run/user/1000/sway-ipc.1000.1256.sock
---
> SWAYSOCK=/run/user/1000/sway-ipc.1000.2304.sock
26c28
< WAYLAND_DISPLAY=wayland-0
---
> WAYLAND_DISPLAY=wayland-1
31c33
< XDG_SESSION_ID=1
---
> XDG_SESSION_ID=3
33c35
< XDG_VTNR=1
---
> XDG_VTNR=2
45c47
< GPG_TTY=/dev/pts/0
---
> GPG_TTY=/dev/pts/1
```

**Comment by RedSoxFan** [comment]
The environment looks fine. A debug log when it fails would be really helpful. In your script above, you have the redirections in the wrong order

> sway -d 2>&1 > ${LOG_FILE_PATH}

should be

> sway -d > ${LOG_FILE_PATH} 2>&1

**Comment by andersfylling** [comment]
log file turned out a bit long. I've added it as a zip file.
[log.zip](https://github.com/swaywm/sway/files/3537824/log.zip)

**Comment by andersfylling** [comment]
I cleared the files, hit mod+Return and then zipped it.

**Comment by RedSoxFan** [comment]
It looks like your `.bash_profile` is being sourced when kitty is launched, which is causing sway spawn in a nested session. I'm not sure why it's showing as a blank window though.

Try:
```
#
# ~/.bash_profile
#

[[ -f ~/.bashrc ]] && . ~/.bashrc
if [ -z $WAYLAND_DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
        export RANGER_LOAD_DEFAULT_RC=FALSE
        export SHELL=zsh
        export PATH="$PATH:/home/anders/.cargo/bin"
        export PATH="$PATH:/home/anders/go/bin"

        # wayland rendering
        export QT_WAYLAND_FORCE_DPI=physical
        export GDK_BACKEND=wayland
        export QT_QPA_PLATFORM=wayland-egl
        export CLUTTER_BACKEND=wayland
        export SDL_VIDEODRIVER=wayland
        export BEMENU_BACKEND=wayland
        export MOZ_ENABLE_WAYLAND=1
        export XKB_DEFAULT_LAYOUT=no
        export XDG_CURRENT_DESKTOP=Unity

        # start with logging
        LOG_FILE_PATH="/var/log/sway/$(date +'%Y-%m-%d').log"
        export SWAY_LOG_FILE_PATH=${LOG_FILE_PATH}
        echo "" >> ${LOG_FILE_PATH}
        echo "################################" >> ${LOG_FILE_PATH}
        echo "## Started Sway $(date +'%Y-%m-%d %H:%M')" >> ${LOG_FILE_PATH}
        sway -d >> ${LOG_FILE_PATH} 2>&1
        LOG_FILE_PATH=""
fi
```

**Comment by andersfylling** [comment]
success. That additional condition fixed it. Now I just gotta figure out why my waybar started crashing lol.
