### ISSUE TITLE
redshift temperature after lock 

### ISSUE THREAD

**Issue by kristoferus75** [swaywm/sway#4516]
Hi !

Is use now sway 1.2
and i use redshift in my sway config

exec redshift -m wayland  -O 3000

but if i lock and the next day login the redhsift stop working -> the redhisft temprature is not 3000

regards

kristoferus75

**Comment by emersion** [comment]
Do you suspend? Do you switch TTYs? Logs?

**Comment by kristoferus75** [comment]
Hi !

with lock i meand this :

swaylock -f -e -c 1d2021 --inside-color 000000b3 -s fill -i ~/.cache/lockscreen;;

**Comment by kristoferus75** [comment]
hi !

The problem ist that the program ist startet not once it always wont start  if i make a lock and login !

And after a few redshift process it crashes ...

I need to check if progrmm run  with shell script

regards

**Comment by emersion** [comment]
Please report any crashes to Redshift, including logs and a stack trace.
