### ISSUE TITLE
focus_on_window_activation doesn't work for Wayland applications

### ISSUE THREAD

**Issue by jonleighton** [swaywm/sway#4523]
* Sway Version: 1.2

https://github.com/swaywm/sway/pull/2560 implemented support for the `focus_on_window_activation` configuration option.

Unfortunately, it only seems to work for applications which are running under XWayland.

I ran Firefox via XWayland, and ran `firefox http://github.com` from a terminal, and the Firefox window was focused.

I then ran Firefox via Wayland, and ran `firefox http://github.com`, and the Firefox window was not focused.

**Comment by jonleighton** [comment]
cc @RyanDwyer

**Comment by RyanDwyer** [comment]
As far as I'm aware, Wayland doesn't have any way for clients to request window activation. So this feature is Xwayland only until a Wayland protocol is agreed on.

**Comment by jonleighton** [comment]
Thanks. This kind of thing works under GNOME Shell (i.e. clicking a link in terminal raises the Firefox window) so I wonder how they do it there...

**Comment by elcste** [comment]
Does the [recent xdg-activation-v1 implementation](https://github.com/swaywm/sway/pull/6132) make this possible?

**Comment by emersion** [comment]
To an extent yes. After Sway support is added, Firefox/GTK need to be updated as well.

**Comment by mdouglass** [comment]
I think https://bugzilla.mozilla.org/show_bug.cgi?id=1744002 indicates that support for xdg_activation_v1 was added to Firefox 96, which I am using, but it is still not working.

**Comment by emersion** [comment]
> I think https://bugzilla.mozilla.org/show_bug.cgi?id=1744002 indicates that support for xdg_activation_v1 was added to Firefox 96, which I am using, but it is still not working.

That's not enough, the terminal needs to set the `XDG_ACTIVATION_TOKEN` env variable, and Firefox needs to parse it.

**Comment by emersion** [comment]
Closing since Sway already implements everything needed for this to work.

**Comment by elcste** [comment]
@emersion Should the [man page](https://github.com/swaywm/sway/blob/master/sway/sway.5.scd?plain=1#L623) be changed not to specify xwayland clients for `focus_on_window_activation`?

**Comment by emersion** [comment]
Ah, yes, we should update the man page. Would you be willing to send a patch?

**Comment by AdamantGarth** [comment]
> > I think https://bugzilla.mozilla.org/show_bug.cgi?id=1744002 indicates that support for xdg_activation_v1 was added to Firefox 96, which I am using, but it is still not working.
> 
> That's not enough, the terminal needs to set the `XDG_ACTIVATION_TOKEN` env variable, and Firefox needs to parse it.

Firefox gets the focus when I activate a link from foot in GNOME and KDE, so looks like both the terminal and the browser do what's required. Does sway require something extra? Could you please specify what that is, so that I know what to ask for when I report this to foot/Firefox?
