### ISSUE TITLE
Sway 1.2 Segfault

### ISSUE THREAD

**Issue by lovesegfault** [swaywm/sway#4526]
* How to reproduce:
1. Have Sway 1.2 and Alacritty 0.3.3
2. In an empty workspace, open Alacritty
3. In Alacritty type `nvim .` to open the neovim file manager
4. Focus will go weird and briefly sway with crash
5. After the crash a reboot is needed to start sway again

Note that if you do this on Sway 1.1 the window will go _NUTS_ and flicker all over, but sway won't crash. 

* Sway Version:
sway version 1.2

* Configuration File:
https://github.com/lovesegfault/dotfiles/blob/master/config/sway/config
* Stack Trace, if sway crashes:
(I know this isn't super useful, but I can't rebuild everything with debuginfo right now
```
#0  0x00007f64c0be2f93 in  () at /usr/lib64/libgbm.so.1
#1  0x00007f64bfcdb629 in  () at /usr/lib64/dri/i965_dri.so
#2  0x00007f64bfcdb69c in  () at /usr/lib64/dri/i965_dri.so
#3  0x00007f64c0fb8bce in  () at /usr/lib64/libEGL.so.1
#4  0x00007f64c0fa7ab9 in eglMakeCurrent () at /usr/lib64/libEGL.so.1
#5  0x00007f64c139b2d1 in wlr_egl_make_current () at /usr/lib64/libwlroots.so.3
#6  0x00007f64c139c541 in  () at /usr/lib64/libwlroots.so.3
#7  0x00007f64c138e132 in  () at /usr/lib64/libwlroots.so.3
#8  0x00007f64c138a02b in  () at /usr/lib64/libwlroots.so.3
#9  0x00007f64c13939e0 in  () at /usr/lib64/libwlroots.so.3
#10 0x0000558f39f62610 in  ()
#11 0x0000558f39f57478 in  ()
#12 0x00007f64c112ef1b in __libc_start_main () at /lib64/libc.so.6
#13 0x0000558f39f5764a in  ()
```

**Comment by ddevault** [comment]
Please provide a backtrace with symbols.

**Comment by lovesegfault** [comment]
@ddevault I'll rebuild with debugsymbols now (sway + wlroots) and see if I get a good one

**Comment by lovesegfault** [comment]
@ddevault Here's what I was able to get:

1. Sway debug log on the first run, up to crash: [Gist](https://gist.github.com/lovesegfault/3aa59599cd7ee91f64f8bec7646ad980)
2. Backtrace of crash: [Gist](https://gist.github.com/lovesegfault/5f46c3d8cc2fe32c8463a4231f9f1a2f)
3. Sway debug log on the second run, after the crash, with subsequent crash: [Gist](https://gist.github.com/lovesegfault/471127b5a9d954c8083daf8bcd5643ba)

Hope this helps!

**Comment by emersion** [comment]
Fixed by https://github.com/swaywm/sway/pull/4525
