### ISSUE TITLE
waybar does not start automatically

### ISSUE THREAD

**Issue by HardDie** [swaywm/sway#4535]
Dump:
[dump](https://gist.github.com/HardDie/0d651ffc3373d9e7e215e738f41fbd6a)

Verison:
swaymsg -t get_version
sway version 1.2 (Aug 29 2019, Arch Linux)

Config:
[config](https://github.com/HardDie/My_linux_settings/blob/work_branch/.config/sway/config)

After updating waybar does not start automatically

**Comment by ThreeFx** [comment]
I'm on the same sway version as you and my waybar work without any problems.

Can you execute the waybar command from a terminal? What output do you get?

**Comment by HardDie** [comment]
Then I run it from the console, I see this output

```
waybar -c ~/.config/sway/waybar.conf -s ~/.config/sway/style.css                        
[2019-09-04 14:59:18.627] [info] Resources files: /home/harddie/.config/sway/waybar.conf, /home/harddie/.config/sway/style.css
Unknown option -c
[2019-09-04 14:59:18.696] [info] Bar configured (width: 1920, height: 24) for output: HDMI-A-1
```

But Waybar gets up and running

**Comment by progandy** [comment]
The way the bar command is called has changed (18ce0eec). Now you can only give an executable without any additional arguments. The bar only gets the bar id as a parameter, e.g. 

```
swaybar -b bar-1
waybar -b bar-2
```

If your bar can't do anything with these parameters, then you'll have to use an intermediate script that translates the bar-id to configuration options.

```
#!/bin/sh
[ x"$1" = x"-b" ] || exit 1
exec waybar -c ~/.config/waybar-"$2".conf -s ~/.config/waybar-style.css
```

**Comment by HardDie** [comment]
It's strange decision, but okey, thank you!)

**Comment by progandy** [comment]
waybar already recognizes and ignores the bar id. It should probably use it to try and load a configuration file as well as style file if it isn't explicitly set with a parameter.

**Comment by HardDie** [comment]
I change default location for configuration and style file, I think because of that its failed)
