### ISSUE TITLE
Failed to multiple xkb_options with swaymsg, but works in config file

### ISSUE THREAD

**Issue by neon64** [swaywm/sway#4541]
Setting multiple `xkb_options` inside the sway config file works:

```bash
input "1:1:AT_Translated_Set_2_keyboard" {
    xkb_options caps:super,altwin:ctrl_alt_win
}
```

But using swaymsg returns an error when trying to set more than one option:

> "Error: Unknown/invalid command 'altwin:ctrl_alt_win'"

```bash
swaymsg input "1:1:AT_Translated_Set_2_keyboard" xkb_options "caps:super,altwin:ctrl_alt_win"
```

It looks like the error originates from here, as if sway is interpreting the comma as a delimiter for another command, not as part of the argument to xkb.

https://github.com/swaywm/sway/blob/a074e0f5046244230363c6fa0e5452056bf70038/sway/commands.c#L266

* Sway Version: sway version 1.2 (Aug 29 2019, Arch Linux)

**Comment by RedSoxFan** [comment]
You need to add another layer of quotes since the shell eats a layer. This should work:
```
swaymsg input 1:1:AT_Translated_Set_2_keyboard xkb_options '"caps:super,altwin:ctrl_alt_win"'
```
