### ISSUE TITLE
Sway freezes on disabling output

### ISSUE THREAD

**Issue by okeri** [swaywm/sway#4548]
**GPU**: intel hd graphics 620
**sway version:**
sway version 1.2 (Aug 29 2019, Arch Linux)
[personal config](https://github.com/okeri/cfg/blob/master/.config/sway/config)

I use hotplugging of second monitor from time to time. However enabling of second output works fine, but when i unplug connector of second monitor, sway freezes. I have also mention it freezes not all the time, but when at least one window present of workspace bound to second monitor output. It freezes when i disconnect cable even if i use swaymsg output DP-1 disable.
Here 2 debug logs for comparison:
[debug log 1](https://gist.github.com/okeri/0b9a8794ed09a638f5c0a7735831f666) Freeze (looks like some kind of spin-lock)
[debug log 2](https://gist.github.com/okeri/0b7f11012080a062d809fd2d0d1efe30) ouput disable successfully without any issues.

**Comment by okeri** [comment]
found, there is a typo in my config:
workspace $ws2 output **d**P-1 => workspace $ws2 output **D**P-1
btw its strange, when matching output name/ids some code uses strcmp, while some other - strcasecmp

**Comment by emersion** [comment]
We should only use `strcmp` for comparing output names and identifiers

**Comment by okeri** [comment]
vice versa, i guess strcasecmp is more preferable.
there is strcmp in workspace_output_get_highest_available,
that's why this function could return wrong result in case of wrong CASE of output id in config file.
I'm not sure this is a real issue
