### ISSUE TITLE
Pass hotkey to window

### ISSUE THREAD

**Issue by Vermaak5** [swaywm/sway#4558]
When using a configuration like "bindsym Control+q kill" on an application that also has this hotkey combination, sway will catch this command and the application will never see this.

This is an issue with many applications that won't be shut down properly if sway kills the windows instead of letting the application handle its shutdown.

Is there a way to forward a hotkey combination to the application first before sway executes its hotkey command? 

Alternatively, is there a way to enable/disable certain hotkey combination in the sway config only for specific applications? Like a check if the active window is called XXX and if so do not execute the kill comand.

* Sway Version: sway version 1.2

**Comment by RedSoxFan** [comment]
> This is an issue with many applications that won't be shut down properly if sway kills the windows instead of letting the application handle its shutdown.

This is an application issue. Sway does not actually "kill" the application. There is no difference in Sway's `kill` and pressing the close button in window managers that provide buttons in their decorations. 

> Is there a way to forward a hotkey combination to the application first before sway executes its hotkey command?

No

> Alternatively, is there a way to enable/disable certain hotkey combination in the sway config only for specific applications? Like a check if the active window is called XXX and if so do not execute the kill comand.

You can bind to a script that uses the IPC to retrieve which view is focused and determine what command to execute based on that.

_(Closing because this is not a sway issue)_

**Comment by Vermaak5** [comment]
I created a script for this in case anyone else is having the same issue:

https://gist.githubusercontent.com/Vermaak5/dda22cb1250bb4a08d66ed1910f1ae41/raw/c247389321f8f7459a6d844173a34fe5f36b9e58/gistfile1.txt

This is just an example script to execute a command depending on the value of app_id

**Comment by Vermaak5** [comment]
Here is an alternative/reversed solution that kills the window unless the name matches and in case it does kills the target process instead of only its window
https://gist.githubusercontent.com/Vermaak5/c8b641fdacc910831c77d30cfad71398/raw/7a727aa86fe94e00f6a17bf44bf4e111939449f1/kill
