### ISSUE TITLE
[Feature request] Change swaybar colors during runtime

### ISSUE THREAD

**Issue by schyzophrene-asynchrone** [swaywm/sway#4566]
With sway I can change colors doing something like `swaymsg client.focused <colors>` to change window decoration colors.
I would like to be able to do things like `swaymsg bar <bar-id> colors background <color>` to dynamically change swaybar colors (I use different colors according to the time of day, bright during the day and dark at night).

**Comment by schyzophrene-asynchrone** [comment]
This feature may be implemented by https://github.com/swaywm/sway/pull/4534
Can someone confirm it ?

**Comment by RedSoxFan** [comment]
Yes, this was implemented in #4534.
