### ISSUE TITLE
The wiki and starting sway

### ISSUE THREAD

**Issue by andersfylling** [swaywm/sway#4568]
After the issue: https://github.com/swaywm/sway/issues/4494

should not the current wiki, which reflects:
```sh
# If running from tty1 start sway
if [[ $(tty) = /dev/tty1 ]]; then
	exec sway
fi
```

Be updated to:
```sh
# If running from tty1 start sway
if [[ -z $WAYLAND_DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
	exec sway
fi
```

To avoid this problem? Why is the first one considered correct and the second one not, when the second one fixed an actual issue?

**Comment by emersion** [comment]
This has been reverted because it's not POSIX. Please make sure you use POSIX shell syntax.
