### ISSUE TITLE
[Beyond tiling] [Feature question]: Sway as scrolling WM (fvwmm, paperwm like)

### ISSUE THREAD

**Issue by goodwillcoding** [swaywm/sway#4569]
Hi folks,

Wanted to thank you all for great work first of all. Sway been solid. Wondered if anyone besides me wondered if sway made sense to be extended to be have a scrolling move similar to what FVWM had or what https://github.com/paperwm/paperwm does horizontally right now.

**Comment by emersion** [comment]
Sorry, we're not interested in adding these features to Sway. We prefer to leave this to other compositors.
