### ISSUE TITLE
xf86audiomute just mute can't unmute

### ISSUE THREAD

**Issue by mh4nx7net** [swaywm/sway#4574]
i've been long didn't use sway as my hommie by default  coz i'd use gnome for my extreme rig for a while. but now i am back again, coz i use poor laptop for doing something. but i didn't realize exactly when i can  mute-unmute my speaker with normally. and in the last i got muted speaker then can't unmuted like period ago. 

here i just write a litle script who found same issues like me.
just copie and paste to your config.d 
#>> nano ~/.config/sway/config
bindsym XF86AudioMute           exec sway_ceknyala

put sc on your readable shell env
##>> nano /bin/sway_ceknyala
#!/bin/bash
if [ $(pulsemixer --get-mute) -eq 1 ]; then
echo speaker mati bro
pulsemixer --unmute
echo '==tunggu bentar=='
echo '--> ok nyala'
elif [ $(pulsemixer --get-mute) -eq 0 ]; then
echo speaker nyala bro
pulsemixer --mute
echo '==tunggu bentar=='
echo '--> ok mati'
fi

if you guys have more smart solution please comment bellow thx

**Comment by RedSoxFan** [comment]
This is not a sway issue, but the following is what you are looking for:
```
bindsym XF86AudioMute exec pactl set-sink-mute @DEFUALT_SINK@ toggle
```
