### ISSUE TITLE
segmentation fault (core dumped)  VirtualBox

### ISSUE THREAD

**Issue by mh4nx7net** [swaywm/sway#4575]
litle log what i got 
(base) ➜  ~ VirtualBox
Qt WARNING: Warning: QT_DEVICE_PIXEL_RATIO is deprecated. Instead use:
   QT_AUTO_SCREEN_SCALE_FACTOR to enable platform plugin controlled per-screen factors.
   QT_SCREEN_SCALE_FACTORS to set per-screen factors.
   QT_SCALE_FACTOR to set the application global scale factor.
Qt WARNING: QSocketNotifier: Can only be used with threads started with QThread
[1]    22313 segmentation fault (core dumped)  VirtualBox

i'am just fix these with apt purge qt$(version)*-wayland
==> ubuntu 
$sudo apt purge qtwayland5
==> arch
$sudo pacman -Rns qt5-wayland

are there's have another solve for this issue ? thanks for watch

**Comment by emersion** [comment]
This is a VirtualBox issue. Please report it to VirtualBox.

**Comment by chron-isch** [comment]
Just use xwayland. `QT_QPA_PLATFORM=xcb virtualbox` fixes this.
