### ISSUE TITLE
dpms off: screen doesn't activate on keypress

### ISSUE THREAD

**Issue by tbm** [swaywm/sway#4581]
Under i3, I would something turn off the screen with:

```
xset dpms force off
```

Pressing a key would turn the screen back on.

When I use this on sway:

```
swaymsg "output * dpms off"
```

it turns off the screen but you can't re-activate it by pressing a key.

Is this intentional?  If yes, is there a way to turn it off but have it turned back on when pressing a key?

**Comment by emersion** [comment]
Yes, this is intentional. Use swayidle if you want to disable DPMS on input events.

**Comment by tbm** [comment]
Is there a way to tell swayidle to become active now?

I guess the solution would be to define `lock` and somehow trigger that.  Is that what you meant?

**Comment by tbm** [comment]
For the record, this should trigger lock:

```
loginctl lock-session
```

**Comment by emersion** [comment]
If you're trying to blank the screen on lock, see:
- https://git.sr.ht/~emersion/dotfiles/tree/master/.config/sway/config#L193
- https://git.sr.ht/~emersion/dotfiles/tree/master/.config/sway/config#L129
