### ISSUE TITLE
Line continuation on comments breaks the next line

### ISSUE THREAD

**Issue by somini** [swaywm/sway#4585]
- sway v1.2

If you have `\` as the last character of a commented line, this seems to be joined internally with the next (possible not comented line), 

* Configuration File:

```
# Some commented line \
some command
```

The `some command` will not execute. Not sure this is also a problem on i3, but I can test it.

**Comment by somini** [comment]
Can confirm this does not happen on i3.

**Comment by ddevault** [comment]
I wanted to say "play stupid games, win stupid prizes", but if this isn't reproducable on i3 then I suppose it's worth addressing.

**Comment by somini** [comment]
I accidentally discovered this while debugging the DPMS swayidle configuration:

```
exec swayidle -w \
         timeout 300 'swaylock -f -c 000000' \
#          timeout 600 'swaymsg "output * dpms off"' \
#                resume 'swaymsg "output * dpms on"' \
         before-sleep 'swaylock -f -c 000000'
```

The `before-sleep` line would be ignored.
