### ISSUE TITLE
Criteria [workspace=__focuses__] has unexpected behavior.

### ISSUE THREAD

**Issue by andremarcais** [swaywm/sway#4586]
#### Info
sway version 1.2 (Aug 29 2019, Arch Linux)
[log](https://gist.github.com/andremarcais/32fe005b5ae8f72eefe426f791ba7aca#file-sway-log)
[cfg](https://gist.github.com/andremarcais/32fe005b5ae8f72eefe426f791ba7aca#file-test-conf)

#### Description
First I go to workspace 10 and add some windows. Then I go to workspace 1 and add some windows. If I then execute `[workspace=__focused__] kill` (while on workspace 1), the windows in both workspace 1 and 10 are killed.

**Comment by RPigott** [comment]
I think this can be closed now.
