### ISSUE TITLE
High CPU usage on void linux

### ISSUE THREAD

**Issue by KristupasSavickas** [swaywm/sway#4590]
I'm experiencing extremely high CPU usage and input delay with sway when running on void linux. I've tried both the 1.1 version available in the repos and built my own 1.2 with 0.7 version of wlroots. I also tried musl and glibc versions of void, kernel versions 4.18.17 and 5.2.17, using the i915 and nouveau drivers, nothing helped.

Here's the log of me opening an alacritty window and changing the focus form left to right a few times in a short period of time, during which the CPU usage jumps to 100% on all 4 cores. During idle it uses up around 15% on all cores (it used to be <1% on arch on the same machine).

https://gist.github.com/KristupasSavickas/141da95ba9d78ddb0bdd769e9573f1cb

**Comment by emersion** [comment]
Your bug report is missing your config file. Please add a link to it.

**Comment by KristupasSavickas** [comment]
I'm using the default one

**Comment by emersion** [comment]
You are using software rendering, which explains bad performance. Make sure your Mesa driver is correctly loaded.
