### ISSUE TITLE
PGP signed releases are invalid

### ISSUE THREAD

**Issue by eli-schwartz** [swaywm/sway#4603]
See https://todo.sr.ht/~sircmpwn/git.sr.ht/232 for "why", I assume @ddevault signed these on an alpine system which shares the problem that sourcehut itself had.

I tested the comparison using https://git.sr.ht/~eschwartz/sway/refs since https://git.sr.ht/~sircmpwn/sway/ is no longer mirrored recently.

In order to successfully validate, the signature either needs to be generated using a GNU gzip program or a git master version of busybox... or else the tarball initially used for generating the signature needs to be uploaded as an additional github asset.

EDIT: yes, this means all my effort to debug theoretical future sourcehut signature hosting actually turned out to be immediately useful in practice. :D

**Comment by ddevault** [comment]
I've uploaded a tarball to the Github release alongside its signature, so instead of using the Github-generated tarball please use the auxiliary file.
