### ISSUE TITLE
Error: Unknown/invalid command 'workspace_layout'

### ISSUE THREAD

**Issue by simonwjackson** [swaywm/sway#4607]
```bash
$ swaymsg workspace_layout tabbed
Error: Unknown/invalid command 'workspace_layout'
```

Trying to build a script that will allow me to set layout style for a particular workspace.

```bash
$ sway --version
sway version 1.2 (Aug 29 2019, Arch Linux)
```

**Comment by mynameisflorian** [comment]
Verified in slightly newer version

```
$ sway --version
sway version 1.2 (Sep 26 2019, Arch Linux)
```

Also tried:

```
$ swaymsg -- 'workspace_layout stacking'
Error: Unknown/invalid command 'workspace_layout'
```

The following works:

`swaymsg -- 'workspace test'`

**Comment by mynameisflorian** [comment]
@simonwjackson Also, I'm not sure exactly what you're doing, but the follow may be helpful:

`swaymsg -- '[workspace="WORKSPACE_NAME"] layout stacking'`

However, this:
- only affects existing containers
- will affect all containers on a workspace

Tip: Use the above format for executing sway commands from a shell
- " -- " tells sway that the rest of text is a sway command. This prevents a "--" in your sway command from confusing swaymsg
- Wrap everything after the "--" in single quotes. This should be your actual sway command. Single quotes tell bash to not process anything inside those quotes. Bash does $variables in much the same way sway does...

### My Config (snippet):
Works as expected

```
set $defaultWorkspaceLayout tabbed
# ...[sic]...
workspace_layout $defaultWorkspaceLayout
```
