### ISSUE TITLE
incorrect border statement in man 5 sway

### ISSUE THREAD

**Issue by pbartyik** [swaywm/sway#4608]
* Sway Version: 1.2 (Sep 26 2019, Arch Linux)

`man 5 sway` contains:

> The following commands may only be used in the configuration file.
>
>        border none|normal|csd|pixel [<n>]
>           Set border style for focused window. normal includes a border of thickness n and a title
>           bar. pixel is a border without title bar n pixels thick. Default is normal with border
>           thickness 2. csd is short for client-side-decorations, which allows the client to draw
>           its own decorations.

When applied in config after reload swaynag states:

`Error on line X (~/.config/sway/config) 'border pixel 2': Unknown/invalid command 'border'

MAN page should be updated to use `default_border` instead of `border` in config

**Comment by ddevault** [comment]
Send patch please

**Comment by pbartyik** [comment]
raised in error, the man page is correct.
