### ISSUE TITLE
Is it okay to bind VoidSymbol emitted by Caps Lock with xkb_options caps:none?

### ISSUE THREAD

**Issue by I60R** [swaywm/sway#4612]
I've disabled Caps Lock and instead bound it to switch keyboard layouts:

```
input "1:1:AT_Translated_Set_2_keyboard" {
    xkb_options compose:ralt,caps:none
    xkb_layout us
    xkb_numlock enabled
}

bindsym Ctrl+Shift+VoidSymbol input "1:1:AT_Translated_Set_2_keyboard" xkb_layout ua
bindsym      Shift+VoidSymbol input "1:1:AT_Translated_Set_2_keyboard" xkb_layout ru
bindsym       Ctrl+VoidSymbol input "1:1:AT_Translated_Set_2_keyboard" xkb_layout pl
bindsym            VoidSymbol input "1:1:AT_Translated_Set_2_keyboard" xkb_layout us
```

This config works flawlessly but VoidSymbol part still looks unreliable. As far as I understand, VoidSymbol will be emitted when some pressed key is not associated with keysym, so theoretically binding it may lead to some surprising side effects.

Could sway emit any other keysym here, e.g. `Caps` ?

Or perhaps binding to raw keycodes would be somehow possible, e.g. using `Key(58)` syntax?

**Comment by emersion** [comment]
Try `bindcode`?

**Comment by I60R** [comment]
Yes, exactly what I want. Thank you!
