### ISSUE TITLE
Right-angle transforms cause touchscreen cursor jitter

### ISSUE THREAD

**Issue by ivanbakel** [swaywm/sway#4613]
# Issue info

* Sway Version: `sway version 1.2 (Sep 26 2019, Arch Linux)`
* Debug Log: ~~https://pastebin.com/Kw9Paw8M~~ https://pastebin.com/2p4sXAEN
* Configuration File: Confirmed with default
* Stack Trace, if sway crashes: N/A

# Issue description

When using a right-angled transform (90, 270) on a touchscreen monitor with a pen tool, the pen cursor experiences jitter, and frequently jumps to the edge of the screen.

This issue **has** ben confirmed to occur with
- The default configuration

This issue has been confirmed **not** to occur if
- The transform is 180
- The input is not mapped to the output, even with a right-angled transform. In this case, the reported pen cursor position is transformed from where the pen actually is physically.

## The jitter

What *appears* to happen is that the cursor momentarily jumps to the edge of the screen, particularly if the pen is travelling very close to the horizontal or vertical. In this case, the cursor will jump towards the edge parallel to the direction of travel i.e. a perpendicular jump.

This does not appear to be an input problem. Looking at `libinput debug-events` output, the pen works as normal during these jitter events - specifically, there is *no* jump in pen position in libinput of the kind that appears to happen to the cursor.

## Examples

This is an example of the jitter under a `90` transform, made by moving the calligraphy tool in Inkscape. This tool works because it drags behind the cursor - other drawing tools simply refuse to draw when the cursor jumps.

![example_of_waggle](https://user-images.githubusercontent.com/20319565/66310371-f5d40f80-e903-11e9-8e6e-132f3689fe21.png)

This is the jitter under a `270` transform. Note that the jitter is in the same direction from the perspective of the user - that is, after applying each transform, these images should look pretty much the same.

![example_of_waggle_2](https://user-images.githubusercontent.com/20319565/66310388-fec4e100-e903-11e9-905f-74ce023a5fed.png)

## Debug log

The debug log has me

1. Open the terminal
     1. Use `swaymsg` to transform the output
     1. Use `swaymsg` to map the inputs to the only output, the touchscreen (`LVDS-1`)
2. Open Inkscape
3. Draw an image similar to the above, with the jitter

## Hardware

I'm using a Thinkpad X220T, which is a tablet variant of the X220.

**Comment by ivanbakel** [comment]
Now at https://pastebin.com/2p4sXAEN

**Comment by torwag** [comment]
It might be related to #3781, as I e.g. see also flickering of frames potentially coming from wrong mouse coordinates.
Solving one issue might solve the other as well.

**Comment by Xyene** [comment]
This looks like the same underlying bug as https://github.com/swaywm/sway/issues/4776. `wlr_cursor_absolute_to_layout_coords` is suspect in both cases, and there, too, a 180-degree transform works fine, and a `map_to_output` is necessary for the bug to manifest.

**Comment by emersion** [comment]
Can you try https://github.com/swaywm/wlroots/pull/2137?

**Comment by ivanbakel** [comment]
>Can you try swaywm/wlroots#2137?

Just tried sway from source with the latest master, since that PR was merged. I can confirm that the issue appears to be fixed, and I can't reproduce the jitter behaviour. Thanks!

**Comment by Xyene** [comment]
Happy to hear that!

Out of personal curiosity, if you have the chance, could you `evemu-describe` your touchscreen device, and obtain a short `libinput debug-events` output of touching the screen / moving around (in particular, multitouch)? For that PR to have fixed your issue, I suspect your touchscreen is identified as a tablet device, but then I wonder how multitouch works.

**Comment by ivanbakel** [comment]
Maybe my initial issue was unclear - it would be mostly correct to describe the device as a tablet. The X220T lets you use a pen and touch on the screen. `swaymsg -t get_inputs` lists both a finger input and a tablet tool input (for the pen).

As for how multitouch has worked so far - not well. Using the master version of `sway`, pinch-zooming in a PDF viewer is much smoother.

I'll gather that libinput data later, if it's still relevant to you.

**Comment by Xyene** [comment]
Ah, I understand now, thanks -- that's cool! So then, I assume drawing with touch always worked(?) since it went through the touch device, and tablet didn't since it went through the tablet device that suffered from this issue.
