### ISSUE TITLE
Key release event going missing when starting GTK applications

### ISSUE THREAD

**Issue by matthewhague** [swaywm/sway#4622]
Sway version: sway version 1.2 (Sep 26 2019, Arch Linux)
Debug log: https://pastebin.com/Fzp94JJM
Config file: only the line "bindsym Mod4+Return exec kitty"
Kitty keyboard log showing ENTER repeat: https://pastebin.com/v0kT2deq
Bug report on Kitty: https://github.com/kovidgoyal/kitty/issues/1934

When starting GTK(3?) applications from the Kitty terminal emulator, it often happens that the ENTER key release event is not reported to Kitty. Instead, when the Kitty window is refocused, repeated ENTER key events are sent.

Attached is a Sway log and a Kitty keyboard event log showing:

1) Opening a kitty terminal
2) Opening a second with --debug-keyboard flag (for recording the log)
3) Typing "libreoffice" and pressing ENTER
4) Closing libreoffice with the mouse
5) Repeated ENTER events being sent to Kitty

I reported this bug to Kitty (link above) who pointed to the compositor (which i think i Sway, apologies if wrong).

This bug is largely ignorable, except when opening email attachments in Mutt: i often end up with tens of copies of libreoffice showing the same document!

This may be related to https://github.com/swaywm/sway/pull/4452 as the issue started around the same time.

Many thanks for your hard work.

**Comment by emersion** [comment]
This is a Kitty bug. They don't stop key repeat when they get `wl_keyboard.release`. I think they fixed it, at least in master.

**Comment by matthewhague** [comment]
Thanks. I've been using the git version of Kitty for a week now and the problem appears to be fixed.
