### ISSUE TITLE
Firefox XWayland - doesn't sync to native refresh rate

### ISSUE THREAD

**Issue by aufkrawall** [swaywm/sway#4630]
I checked with sway stable 1.2 from Arch repository and
sway version 1.2-rc1-65-g12505e4c (Oct 12 2019, branch 'master')

* Debug Log:
[sway.log](https://github.com/swaywm/sway/files/3720960/sway.log)

* Configuration File:
[config.txt](https://github.com/swaywm/sway/files/3720961/config.txt)

The problem: I've been told that sway can run applications via xwayland with native refresh rate vsync in windowed mode, unlike other Wayland compositors. And indeed, it works fine e.g. in Chromium, games etc.

But there is one exception: Firefox.
My display's EDID only offers 75Hz, but Firefox renders with fixed 60fps instead, which results in bad stutter.

I assume now that they put their efforts into native Wayland windowing (which I made sure isn't used, as I'm aware that it deliberately renders only with fixed 60fps...), they wouldn't care much about this XWayland issue. And it's probably out of their scope, as on Xorg, Firefox correctly syncs to 75fps @ 75Hz.
Both Firefox stable 69.0.3 from Arch repo and 70 beta 14 from Mozilla show the same behavior. It also applies to both old layered OGL rendering and new OGL WebRender.

My hope would be that it's not expected for single xwayland applications to show different behavior, so that it could be fixed in sway.

**Comment by emersion** [comment]
I think this is either a Firefox bug or an Xwayland bug. We can't do anything about this in Sway.
