### ISSUE TITLE
Version number is unreliable

### ISSUE THREAD

**Issue by emersion** [swaywm/sway#4631]
The version we get from Git is unreliable. At the time of writing it says 1.2-rc1 although the latest release is 1.2. This happens because 1.2 has been tagged on the v1.2 branch, not on master. When building from master the latest tag is 1.2-rc1.

Not sure how to fix this.

**Comment by dnkl** [comment]
Merging the 1.2-branch into master will make the 1.2 tag "visible" in master too.
