### ISSUE TITLE
Issues with 'sway: error while loading shared libraries: libopenh264.so.4: cannot open shared object file: No such file or directory'

### ISSUE THREAD

**Issue by stratosgear** [swaywm/sway#4633]
```
➜ swaymsg -t get_version
sway version 4.17.1 (2019-08-30)
```

Can someone suggest a debug/investigation process for an error of:

```
➜ sway
sway: error while loading shared libraries: libopenh264.so.4: cannot open shared object file: No such file or directory
```

I just rebooted and my sway session failed and it silently restarts the login process.  I can logon with a separate .i3 session, but I really want my sway session back, please.

I'm on X1 carbon thinkpad (3rd gen).

Thanks

**Comment by stratosgear** [comment]
Hmmm that sway version doesn't look right.  That's my i3 version.

`sway -v` also exits with the same error as above.

Trying to remove and reinstall `openh264` results in:

```
➜ yay -R openh264
checking dependencies...
error: failed to prepare transaction (could not satisfy dependencies)
:: freerdp-git: removing openh264 breaks dependency 'openh264'

09:23:18 in ~ 
➜ yay -R freerdp-git 
checking dependencies...
error: failed to prepare transaction (could not satisfy dependencies)
:: wlroots: removing freerdp-git breaks dependency 'freerdp'
```

Is this a wlroots issue then? Should I report there?

I'm on latest arch, btw.

**Comment by stratosgear** [comment]
Fixing it manually with:

```
sudo su
cd /usr/lib
ln -s libopenh264.so.2.0.0 libopenh264.so.4
```

and rebooting. Now it works.

No idea why things like these break sometimes.  I do all my package upgrades through yay!

Leaving this open, in case there is a possible/reasonable explanation.

Feel free to close otherwise!

**Comment by rkanati** [comment]
I'd guess this is an arch packaging issue, but I'm not sure.

**Comment by Xyene** [comment]
Neither sway nor wlroots link openh264; your analysis of it being a packaging issue _somewhere_ is likely true.
