### ISSUE TITLE
Port new i3 focus changes (v4.18?)

### ISSUE THREAD

**Issue by lbonn** [swaywm/sway#4638]
i3 has gained new focus commands here https://github.com/i3/i3/pull/3407.

In the spirit of #2336 and #3082, here is a list of tasks:

- [x] `focus_wrapping workspace`
- [x] `focus next|prev` (check that behavior matches)
- [x] `focus next|prev sibling`

**Comment by loserMcloser** [comment]
Upvote for "focus next|prev" --- I was just coming here to make a feature request for that, and here it was as the most recently opened issue!
