### ISSUE TITLE
swaywm + simplefb?

### ISSUE THREAD

**Issue by protonesso** [swaywm/sway#4639]
Hi, I'm making mini Linux distro for my embedded device (RISC-V CPU). I want to use Wayland and have chosen your Window Manager as main GUI. But unfortunately it says "Initializing DRM backend" and no response. I use simplefb as my GPU. My kernel config:
[config-linux.txt](https://github.com/swaywm/sway/files/3730328/config-linux.txt)

**Comment by emersion** [comment]
If this is about fbdev, I'd prefer not to support it. It's going to be removed eventually from upstream. They have plans to create a KMS shim for fbdev instead. This would allow us to use fbdev drivers through the regular KMS API.

**Comment by protonesso** [comment]
Any older versions do support it?

2019年10月15日(火) 19:13 Simon Ser <notifications@github.com>:

**Comment by emersion** [comment]
No, fbdev was never supported.

**Comment by protonesso** [comment]
In which version fbdev shim will be introduced?

2019年10月15日(火) 19:18 Simon Ser <notifications@github.com>:

**Comment by emersion** [comment]
There's still some discussion going on about this. See for instance this series: https://patchwork.freedesktop.org/series/67980/

**Comment by protonesso** [comment]
Thank you!

2019年10月15日(火) 19:27 Simon Ser <notifications@github.com>:
