### ISSUE TITLE
invalid memory consistency assumptions in {sway_node,sway_view}.destroying

### ISSUE THREAD

**Issue by a-m-joseph** [swaywm/sway#4640]
Hi, sway says that it "is largely documented through comments in the headers. Read 'em.", so I did.

The purpose of the boolean variable "destroying" in sway_view and sway_node is not documented in the headers, so I attempted to infer their purpose.  If I have inferred incorrectly please consider this issue to be a request for an explanatory comment in the headers.

These variables appear to have the following purpose: if one thread is deallocating a sway_node or sway_view, it sets the "destroying" variable to true before taking steps that will cause the other fields of these structs to be invalid/garbage/corrupt/etc.  This is intended to warn other concurrently-executing threads that the fields are not safe to use -- especially calling functions via pointers found in the struct.

If I have understood the purpose of "destroying" correctly, it is bogus for at least two reasons:

1. TOCTOU: the non-destroying thread might check the "destroying" variable, find it to be false, then immediately be descheduled; the destroying thread is then scheduled, sets the flag, corrupts the fields, and is descheduled; finally, the non-destroying thread is descheduled and resumes execution just after the protective if(destroying){..} check.  Mayhem ensues.

2. Unfenced interthread communication through memory.  On most architectures there is no guarantee that the (a) store of "true" to destroying and (b) the store of garbage-data to various other fields will be observed in the same order by the non-destroying thread, unless the programmer explicitly inserts a memory fence.  This might work okay on x86, which requires godawful amounts of complicated circuitry in order to maintain the illusion of serialized RAM (and to maintain the barrier to entry by competing silicon, but that's another story....).  On pretty much anything other than x86 you need to fence.

**Comment by a-m-joseph** [comment]
Alright nevermind, I see that sway is actually single-threaded (in spite of those 19 radeonsi threads and linking against libpthread...).  I guess that is plausible as long as it isn't doing anything computationally intensive or dealing with file descriptors that can't be put into non-blocking mode.  

I stumbled across this while implementing application-sensitive key remapping.

Still unclear on why calling view_get_app_id(view_from_wlr_surface(seat->keyboard_state.focused_surface)) in handle_keyboard_key() causes a SEGV when view_from_wlr_surface(seat->keyboard_state.focused_surface) is true (yes, I am checking for NULLs everywhere).  The validity conditions for some of the fields in sway's datastructures are somewhat elusive.

**Comment by a-m-joseph** [comment]
Turns out the culprit was #4647

**Comment by emersion** [comment]
Thanks for investigating
