### ISSUE TITLE
sway-git-r6074.d19f4f7b crashes (wlroots-git bug?)

### ISSUE THREAD

**Issue by Mel34** [swaywm/sway#4643]
* Sway Version:
 sway-git-r6074.d19f4f7b-1-x86_64.pkg.tar
 wlroots-git-0.8.1.r11.g17242619-1-x86_64.pkg.tar

* Debug Log:
https://pastebin.com/hMB2uj2G

I rebuilt wlroots and sway-git from AUR and resulting binary is producing a flickering on both of my screen which eventually settles into a black screen with cursor I cannot move. Commands defined in config file do not work.
This is triggered with  wlroots-git-0.8.1.r11.g17242619-1-x86_64.pkg.tar
Earlier versions of wlroots-git (such as wlroots-git-0.8.1.r5.g480a31ea-1-x86_64.pkg.tar) work just fine.

* Stack Trace, if sway crashes:

Sway does crash but I've disabled coredumps. It seems pretty obvious something is very wrong with the latest commits to wlroots e.g. https://github.com/swaywm/wlroots/commit/1724261910728bfa63eecb0f1729995c00c7ffe8

**Comment by ddevault** [comment]
Your wlroots is out of date, update it.

**Comment by Mel34** [comment]
I've rebuilt it. Which version number should I get with latest wlroots?

**Comment by Mel34** [comment]
@ddevault I've manually performed the build and installed wlroots from master, same thing happens. I believe you were too quick to close this bug.

**Comment by ddevault** [comment]
It's never sway with these kinds of bugs. It's *always* that your system is broken.

**Comment by Mel34** [comment]
Assuming my wlroots is indeed up to date, what else could be broken on my system?

**Comment by Mel34** [comment]
For posterity: this was caused by swaybg-git not being rebuilt against wlroots-git.
