### ISSUE TITLE
Proposal: Alternate Window wallpaper

### ISSUE THREAD

**Issue by SairesArt** [swaywm/sway#4645]
Would it be possible to set a different wallpaper image for window transparency?

Usage would be a very cheap form of window blur.
Scripts like https://github.com/ganifladi/blurme for i3 replace the wallpaper with a blurred version when a window is opened. Taking this idea further with two wallpapers, one for transparency would make for a very efficient and cheap form of eye candy. No actual blur needs to be implemented, just let the users play with it.

**Comment by ddevault** [comment]
No, not interested in this.

**Comment by SairesArt** [comment]
Holy moly, that was quick. O.O
Too bad :]
Could you give a rough outline of what would have to be changed to make this possible? Just having two wallpapers, where window transparency reads from the second wallpaper.

I would be interested in implementing something like this then. This would open the door for very cheap eyecandy and customization.
