### ISSUE TITLE
GTK3 GdkWindowTypeHint::DIALOG ignored

### ISSUE THREAD

**Issue by loserMcloser** [swaywm/sway#4655]
**Issue**
A Gtk2 window with GdkWindowTypeHint::DIALOG set will open in floating mode, but a Gtk3 window with same hint flag will open in tiled mode.

**Desired behaviour**
Dialog windows should open floating?

**sway version**
1.2 (from Arch Linux repos)

**Config used for debug session**
default as distributed with the Arch Linux sway package, but with two exec lines added at the end to open the following test GTK windows:
[dialog.py2](https://pastebin.com/PUX2eHdZ)
[dialog.py3](https://pastebin.com/k3VpSpeu)

[Debug log](https://pastebin.com/yhbMddWB)

In this debug session I started sway, the exec lines added to the default configuration automatically started dialog.py2 and dialog.py3. To confirm that the dialog.py3 window was opened in tiling mode I switched focus to that window with the "floating toggle" shortcut, then I toggled that window's mode with the "focus mode_toggle" shortcut. Then I exited sway.

**Comment by ddevault** [comment]
You should bring this up with GTK first.

**Comment by progandy** [comment]
As far as I know, wayland doesn't have any way to assign a window type for toplevel windows. You can only create a popup as the child of another window..

**Comment by loserMcloser** [comment]
Thanks for the replies.

gsimplecal uses GTK3 and opens as a toplevel floating window in sway, though I can't figure out in [the source](https://github.com/dmedvinsky/gsimplecal/blob/master/src/MainWindow.cpp) what is making that happen, as it doesn't use the DIALOG type hint....

(Also, while I'm at it, sway seems to ignore gtk_window_set_decorated for gsimplecal and draws a title bar.)

**Comment by progandy** [comment]
Sway floats windows that have a fixed size (minimum size equals maximum size)

https://github.com/swaywm/sway/blob/f984f21b6a71bf8794de61f58b00d99ed3537c50/sway/desktop/xdg_shell.c#L188-L195

**Comment by progandy** [comment]
> Is this really the ideal behavior? Shouldn't it be possible to have a floating window which doesn't have a fixed size or a parent?

That would require a properly thought out and widely supported extension to the xdg-shell protocol. I don't think there would be much interest from gnome, kde, gtk or qt. They are more focused on stacking or fullscreen only layouts.

**Comment by akvadrako** [comment]
So I want to make an app which has a resizable floating window in sway. Would it work if I initially make it fixed size and then make it resizable after a second or so?

**Comment by kennylevinsen** [comment]
Just set a parent of the toplevel, don't abuse min/max size.

**Comment by akvadrako** [comment]
It is a top level window.

**Comment by kennylevinsen** [comment]
> It is a top level window.

Toplevels can have parents: https://gitlab.freedesktop.org/wayland/wayland-protocols/-/blob/master/stable/xdg-shell/xdg-shell.xml#L605

If you mean that you do not have a parent as it is your first or only window, nor is fixed size, then you are a plain window and should not attempt to force floating behavior within xdg-shell.

(If you have a legitimate reason for being able to control presentation, such as being a desktop environment widget like a launcher, notification daemon or bar, then see layer-shell instead of xdg-shell. This protocol is not for normal windows though )

**Comment by akvadrako** [comment]
It's not about forcing anything but providing a hint for sane defaults for things like splash screen or utility windows. The calculator above is a good example; it shouldn't matter if it's resizable. Also things like character pickers. Then I could do something like:

```
for_window [window_type="utility|splash"] floating enable; 
```

**Comment by kennylevinsen** [comment]
xdg_shell has no such functionality. The appropriate forum for xdg_shell suggestions and discussions is the wayland-protocols issue tracker (https://gitlab.freedesktop.org/wayland/wayland-protocols/-/issues).

Personally, I don't think such hints are necessarily a good idea. Auto-float in tiling compositors is to make accessory windows, like file pickers or indicators, work - not to make standalone applications float. I imagine such hints would very quickly devalue to the point of being unusable as random things set the hint, and most compositors would not care by default/at all.

As a semi-related aside: Floating splash screens are terrible and entirely unnecessary. Create the main window immediately, and if content is not ready, put loading placeholders/animations/whatever in there. Flashing additional useless windows, especially modal ones centered on screen, leads to extremely bad UX in a time where computers can be used for more than one thing at a time.

Anyway, please take additional discussions and suggestions about xdg_shell in the appropriate forum.

**Comment by akvadrako** [comment]
Of course. If anyone else is looking for a solution that works now, initially making the window fixed size then making it resizable after it's drawn does work to get a floating resizable window.

**Comment by kennylevinsen** [comment]
> If anyone else is looking for a solution that works now, initially making the window fixed size then making it resizable after it's drawn does work to get a floating resizable window.

Do *not* do this - it is abuse of the xdg-shell protocol and relying on a sway implementation detail.

If your window is not intended to be non-resizable, and does not have a parent, you will not have a floating window by default. The end. If you would like different behavior, do *not* abuse the protocol. Open an issue or merge request on the wayland-protocols repository.
