### ISSUE TITLE
Resize of tiled containters with mouse doesn't work anymore

### ISSUE THREAD

**Issue by kchibisov** [swaywm/sway#4659]
Previously(sway 1.2) I was able to resize tiled windows with mouse when moving mouse to a window border, holding LMB and dragging the border. Window swapping works fine.

sway version 1.2-3ee3a9ef (Oct 18 2019, branch 'master')

If you need more info let me know.

**Comment by kchibisov** [comment]
I've decided to bisect it and this commit broke this 2c1a11016ccb7646a74de51eff003c18e5aa7902.


cc @versusvoid

**Comment by versusvoid** [comment]
Ooupsies :yum: 
I didn't notice that `node_at_coords()` does not find surface if cursor is on border
