### ISSUE TITLE
swaymsg input type:touchpad events toggle doesn't work

### ISSUE THREAD

**Issue by bmartynov** [swaywm/sway#4661]
* Sway Version:
sway version 1.2

* Debug Log:
https://pastebin.com/u1MgQq1v

* Configuration File:
https://pastebin.com/fjBMRX9y

* Stack Trace, if sway crashes:
no stack trace

Hello!
`input type:touchpad events toggle` does not works.

`input type:touchpad events enabled|disabled` - works

**Comment by emersion** [comment]
`input type:touchpad events toggle` can only be used at runtime.

**Comment by bmartynov** [comment]
ok, got it.

swaymsg input type:touchpad events toggle - also doesn't works. it's ok?

**Comment by emersion** [comment]
What's the error message?

**Comment by RedSoxFan** [comment]
`toggle` will cycle through all available states for the device in the order of `enabled`, `disabled_on_external_mouse`, and `disabled`. A touchpad likely supports all three. If you want to omit one of them, list the modes to toggle between after `toggle`

**Comment by bmartynov** [comment]
no error message. exit code - 0.

**Comment by rileyinman** [comment]
Also having this issue - `swaymsg input type:touchpad enabled|disabled` works fine, `swaymsg input type:touchpad toggle` does nothing with no error code and a success exit code.

**Comment by RedSoxFan** [comment]
See #5019

Note that my previous comment still applies:
> `toggle` will cycle through all available states for the device in the order of `enabled`, `disabled_on_external_mouse`, and `disabled`. A touchpad likely supports all three. If you want to omit one of them, list the modes to toggle between after toggle (ex: `input type:touchpad events enabled disabled`)
