### ISSUE TITLE
Desync/freezing with mpv --fullscreen and --video-sync using direct scanout

### ISSUE THREAD

**Issue by LaserEyess** [swaywm/sway#4663]
* Sway Version: `sway version 1.2-fa0abaf7 (Oct 21 2019, branch 'master')`
* debug log: `sway -d -c /etc/sway/config 2>sway.log` https://0x0.st/z3_J.log
* configuration (default): https://0x0.st/z3_y.txt

With the latest mpv, utilizaing the presentation feedback changes for wayland, sway appears to have issues when mpv is started with `--fullscreen` while also using `--video-sync=display-*`. This manifests in vsync jitter being wildly wrong, and frames being mistimed/delayed/dropped. Furthermore, when exiting fullscreen, mpv will freeze and A/V desync will go through the roof. Afterwards, mpv will recover in about a second or two and then there will be *no problems at all*; presentation time and vsync jitter are perfect and no frames drop. Even if you go back and forth between fullscreen it's fine. It only affects the initial fullscreen state and **first** windowed state after exiting fullscreen. Everything else is perfect.

When mpv is not started with `--fullscreen` this behavior does not happen, even when toggling back and forth between fullscreen. Playback is perfect. 

I do not believe this is an mpv bug, although the new wayland presentation time code in mpv could certain be related. Playback in weston is completely normal. I haven't tried any other compositors.

* Minimal command to reproduce:
```mpv --no-config --video-sync=display-resample --fullscreen $video```
* mpv log: https://0x0.st/z3_E.log
* WAYLAND_DEBUG=1 log: https://0x0.st/z32E.log

At the advice of mpv's wayland dev, I reverted https://github.com/swaywm/sway/commit/875edc9c2f497cee2f26042b1cffc8c3495721f8 and https://github.com/swaywm/sway/commit/00c4c7e8cc437c6f905c6fbe94cf8eaf508f8644 and the problem went away. Presentation time works perfectly and there's no more freezing and framedropping even starting mpv with `--fullscreen`.

Here's the exact same logs but with those commits reverted:
* debug log: `sway -d -c /etc/sway/config 2>sway.log` https://0x0.st/z3_G.log
* mpv log: https://0x0.st/z3_D.log
* WAYLAND_DEBUG=1 log: https://0x0.st/z32l.log

Any advice on how to further debug this would be appreciated.

**Comment by Dudemanguy** [comment]
The kicker with this bug is that I cannot reproduce it all anywhere I've tried. I had assumed the scanout commits somehow had something to do with this (i.e. mpv was using direct scanout when it shouldn't) but the debug log says nothing about using direct scanout which is perplexing.

By the way @LaserEyess, could you check to see if the problem still exists if you only revert 00c4c7e but leave 875edc9?

>I do not believe this is an mpv bug, although the new wayland presentation time code in mpv could certain be related.

Oh it is related. What's (probably) happening is that you aren't getting any presentation feedback for a second or two so mpv returns some weird negative values in its renderloop that screws up frame timings.

**Comment by LaserEyess** [comment]
It doesn't seem as severe in terms of dropped frames and amount of time frozen, but reverting https://github.com/swaywm/sway/commit/00c4c7e8cc437c6f905c6fbe94cf8eaf508f8644 only still has this issue.

**Comment by emersion** [comment]
Can you try https://github.com/swaywm/sway/pull/4667?

**Comment by emersion** [comment]
>I cannot reproduce it all anywhere I've tried.

**Comment by LaserEyess** [comment]
@emersion #4667 seems, no more freezing or framedrops. And as far as I can tell, presentation time is working as well as it does in weston.
