### ISSUE TITLE
Sway crash when passing wl_output to get_layer_surface

### ISSUE THREAD

**Issue by joefiorini** [swaywm/sway#4670]
In my code I was calling `zwlr_layer_shell_v1_get_layer_surface` and passing a bound `wl_output` object. It works fine when passing `NULL` for the output param. This caused Sway to segfault. Here is the stack trace:

https://paste.sr.ht/~joef/0d6988bc8ce431154fb00bf3ff31b85e3e67c979

**Comment by emersion** [comment]
This link gives a 404. Can you re-upload the stack trace?

**Comment by joefiorini** [comment]
@emersion Updated the link in the original post.

**Comment by Xyene** [comment]
I believe this was fixed a while ago in https://github.com/swaywm/sway/pull/5071, please reopen if you find this not to be the case.
