### ISSUE TITLE
KeePassXC can't access clipboard after clearing it.

### ISSUE THREAD

**Issue by ZJaume** [swaywm/sway#4678]
When KeePassXC copies a password after the clipboard has been cleared it cannot access to it. The log says: `[xwayland/selection/incoming.c:399] denying write access to clipboard: no xwayland surface focused`. Since the latest version KeePassXC is working as native in Wayland.

Steps to reproduce:

1. Open KeePassXC and copy a password (this password is copied successfully).
2. Wait until clipboard is cleared.
3. Try again copying a password (KeePassXC minimizes normally like it has copied the password to clipboard but it is still empty)

To let KeePassXc use the clipboard again, another thing has to be copied to clipboard and it works again, until the next clipboard clear.

Sway version: 1.2
wl-clipboard version: 2.0.0
wlroots version: 0.8.1-1
KeePassXC version: 2.5.0
OS: Arch Linux

**Comment by ZJaume** [comment]
[Here](https://gist.github.com/ZJaume/ea4886ff21bb03e54c4886a4420dcb01) is the full log.

**Comment by ZJaume** [comment]
Sorry I thought that the problem was due to the new version of KeePassXc but it also happens with the previous version.

**Comment by emersion** [comment]
If KeePassXC isn't the focused surface, it doesn't have access to clipboard.

**Comment by ZJaume** [comment]
But the behaviour is the same at the first copy, copy the password and minimize window, why the second time it does not work?

**Comment by emersion** [comment]
I guess the app copies the password while it still has focus.

**Comment by Xyene** [comment]
> If KeePassXC isn't the focused surface, it doesn't have access to clipboard.

This is indeed the case, even if it breaks some existing X11 applications' assumptions. At any rate, KeePassXC has a native Wayland version now, so I'll go ahead and close this ticket since there's not much we can do, short of granting X11 apps more privileges than regular Wayland apps.
