### ISSUE TITLE
broken scroll_factor behavior in sway and xwayland clients

### ISSUE THREAD

**Issue by RPigott** [swaywm/sway#4679]
* Sway Version: sway version 1.2-1a253ca7 (Oct 28 2019, branch 'master')

So this is an interesting issue with discrete scroll events. Sway introduced a scroll_factor feature with #3018 that allows the user to scale scroll events to control scroll sensitivity for their scrolling devices. 

At the moment, scroll_factor scales the axis value and rounds the axis_discrete * scroll_factor product to the nearest integer. I understand the behavior is application dependent, but in my observation xwayland clients that implement a scroll tab/slot behavior will skip a tab/slot when a scroll_factor > 1.5 causes sway to emit a discrete value greater than 1, and wayland clients tend to work fine.

You can observe in firefox, with the toolkit.tabbox.switchByScrolling pref enabled, the correct behavior on the wayland backend and the skipping behavior on the x11 backend. Swaybar is a wayland client that will not skip, chromium is an xwayland client that will skip.

Sway itself also exhibits the skipping behavior when scrolling to switch windows with scroll_factor in tabbed/stacked layouts. scroll_factor <= 0.5 makes scrolling to switch windows impossible altogether.

I'm not sure how universal the behavior is, so I'd be interested to hear about clients that do not follow the trend.

I don't know why xwayland clients behave this way, but I'm thinking we should just not scale the axis discrete event. It's an easy change, fixes those skipping issues and doesn't appear to have any ill effects on native wayland clients. I've observed in chromium not scaling axis discrete causes scroll_factor to have no effect for my mouse, but of course it still works to scale scroll events from my touchpad, which doesn't emit discrete events.

I understand there is a [new scrolling api in the works](https://gitlab.freedesktop.org/libinput/libinput/merge_requests/139) that should land in libinput soon, and [proposed parallel changes to wl_pointer](https://lists.freedesktop.org/archives/wayland-devel/2019-April/040377.html) which I expect is relevant, but I'm not quite sure how it fits in.

Thoughts on not scaling axis_discrete? Anyone know why only xwayland clients appear to be buggy?

**Comment by sammoth** [comment]
I have scroll_factor set to 2 and sway's own tabs is the only place I can see where this causes any problem. In particular Chromium under Xwayland allows scrolling the tabs and these still scroll correctly (one per mouse wheel click), even though the scrolling of the web view is multiplied. Similarly Dolphin allows scrolling to change tab and this works correctly under Xwayland and Wayland. I'm not sure if something changed since this was opened.

So on my end, the PR is all that is needed to fix this and it works fine (thanks!)

**Comment by RPigott** [comment]
Hmm yeah, I just tested chromium and it doesn't skip anymore.

I guess the PR got a little forgotten, probably because my issue description is pretty ramble-y. Though, if no one has cared in all this time the behavior probably isn't worth changing at this point, other than the small change in that PR. If it gets merged this issue should be closed.

Proper scroll factor support can wait for the v120 api.

**Comment by RPigott** [comment]
Outdated, we now support v120.
