### ISSUE TITLE
Cannot start most of the applications from terminal, cannot run dmenu

### ISSUE THREAD

**Issue by mas15** [swaywm/sway#4685]
Hello everyone. 

- I am using Arch linux and Sway 1.2. I have got integrated Intel GPU. I use zsh as my sh.
- I cannot run most of the applications. I run them from terminal and nothing appears. 
- Only app I can run is Transmission (both in GTK and QT), gitg and Thunar.
- I have got `QT_QPA_PLATFORM=wayland` exported, tried many combination but I doesn't help.
- Same thing happens when I try to run `j4-dmenu-desktop`, I just get `Read 40 .desktop files, found 29 apps.` and no new window appear.
- The worst is when I try to run VLC, I got version printed out but it halts and I cannot kill it with CTRL+C, I have to close the terminal.
- Sway is started from `.zprofile` by `exec sway`
- I tried many apps such as google-chrome, libre-office, vlc
- Cannot run with j4-dmenu because it doesn't work as well
- I have Xwayland installed

I have no clue how to find the issue. Could anyone give a hand, please?

**Comment by RedSoxFan** [comment]
Can you please post a debug log? Start sway as `sway -d >sway.log 2>&1`

**Comment by mas15** [comment]
Also this happens when I try to do WIN+D (run dmenu)

> 2019-10-31 16:41:39 - [sway/commands/bind.c:610] running command for binding: exec j4-dmenu-desktop --
> 2019-10-31 16:41:39 - [sway/commands.c:250] Handling command 'exec j4-dmenu-desktop --'
> 2019-10-31 16:41:39 - [sway/commands/exec_always.c:46] Executing j4-dmenu-desktop --
> 2019-10-31 16:41:39 - [sway/commands/exec_always.c:87] Child process created with pid 8121
> 2019-10-31 16:41:39 - [sway/tree/root.c:275] Recording workspace for process 8121
> Read 41 .desktop files, found 30 apps.

Also nothing appears on the screen

**Comment by Emantor** [comment]
Install `xorg-server-xwayland`.

**Comment by mas15** [comment]
> Install `xorg-server-xwayland`.

This helped! Thanks. How did you sort it out?
And why do I need xorg if I use wayland?

**Comment by Emantor** [comment]
```
2019-10-31 16:23:18 - [xwayland/xwayland.c:110] failed to exec Xwayland: No such file or directory
```
For the why, you'll probably need to talk to framework and application authors.
