### ISSUE TITLE
Display configuration lost on sway reload

### ISSUE THREAD

**Issue by jeffmakes** [swaywm/sway#4687]
sway version 1.2, default configuration (plus a few extra key bindings), Fedora 30 (copr gumieri/sway)

I have a Lenovo X1 laptop with Intel HD Graphics 520. It only has enough bandwidth to drive two DP 4k monitors at 30Hz, plus its internal panel.

It's driving these outputs nicely:
```
Output eDP-1 'Unknown 0x183D 0x00000000'
  Current mode: 1920x1080 @ 60.049000 Hz
Output DP-5 'Samsung Electric Company U28E590 HTPJ203148'
  Current mode: 3840x2160 @ 30.000000 Hz
Output DP-6 'Unknown MAG321CURV DA2A019160072' (focused)
  Current mode: 3840x2160 @ 30.000000 Hz
```
If I reload (mod+Shift+c), sway defaults back to driving the monitors at 60Hz, which doesn't work.
There is no output configuration in my sway config file. That's what I want - I will configure via kanshi because I need hotplugging to work nicely.

Steps to reproduce:
```
$ swaymsg output DP-5 mode 3840x2160@30Hz
$ swaymsg output DP-6 mode 3840x2160@30Hz
```
everything looks good...
```
$ swaymsg reload
```
everything is broken.

In the log file below I start sway, run the two swaymsg output lines above, then reload sway.
`swaymsg -t get_outputs >/tmp/get_outputs.log` [get_outputs.log](https://github.com/swaywm/sway/files/3790835/get_outputs.log)
`sway -d 2> /tmp/sway-monitor-reset.log` [sway-monitor-reset.log](https://github.com/swaywm/sway/files/3790795/sway-monitor-reset.log)
`cat ~/.config/sway/config > config.txt` [config.txt](https://github.com/swaywm/sway/files/3790962/config.txt)

**Comment by emersion** [comment]
This is by design -- reloading removes all configuration applied at runtime (ie. not in the config file).

This is being discussed at https://github.com/emersion/kanshi/issues/43
