### ISSUE TITLE
might houner XDG basedir defaulting

### ISSUE THREAD

**Issue by blaggacao** [swaywm/sway#4692]
```bash
$ sway -v
sway version 1.2
```

sway might honour [XDG basedir spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) defaulting, if $XDG_CONFIG_HOME is not set

Which states, specifcially:
>    A user specific version of the configuration file may be created in $XDG_CONFIG_HOME/subdir/filename, **taking into account the default value for $XDG_CONFIG_HOME if $XDG_CONFIG_HOME is not set.**

According to `man sway`:
```man
 CONFIGURATION
       sway searches for a config file in the following locations, in this
       order:

       1.   ~/.sway/config
       2.   $XDG_CONFIG_HOME/sway/config (suggested location)
       3.   ~/.i3/config
       4.   $XDG_CONFIG_HOME/i3/config
       5.   /etc/sway/config
       6.   /etc/i3/config
```
Moreover, spec states:
> If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used.

**Comment by RedSoxFan** [comment]
Sway already will use `$HOME/.config`, if `$XDG_CONFIG_HOME` is not set or is empty.

https://github.com/swaywm/sway/blob/7efb5d467368ea9168cebc2473bc3c6942e031bb/sway/config.c#L364-L368

If this is not working for you, please attach the output of`env` and a debug log

**Comment by blaggacao** [comment]
Yeah thanks, entirely my fault. (made a mistake when copying the config file...)
Thanks and sorry for the noise.
