### ISSUE TITLE
dmenu loses focus when interrupted by popup

### ISSUE THREAD

**Issue by tbm** [swaywm/sway#4693]
I have:

```
set $menu dmenu_path | dmenu | xargs swaymsg exec
bindsym $mod+d exec $menu
```

I also use `gnome-keyring-daemon` to manage SSH key passwords.

What happens is this:

* I start an SSH connection in one workspace
* I switch to another workspace
* I press mod+d to get dmenu
* I type something but don't complete the task
* In the meantime, the `gnome-keyring-daemon` prompt comes up asking me for the password

At this point, there's no way to get back to the dmenu.  Neither pressing mod+d again or clicking into the bar where I was typing previously helps.  The dmenu stays open (even when switching to other workspaces) but I'm unable to complete the entry.

The easiest way to reproduce might be to launch a `sleep 2; ssh...` in one window, then switch to another workspace, mod+d, enter something (without pressing enter) and just waiting for the password prompt.  Obviously, this only works immediately after starting sway (since gnome-keyring-daemon will only ask for the password once). 

This is with sway 1.2.

**Comment by RPigott** [comment]
To be clear, the real issue is that dmenu cannot regain focus, right? Or have I misunderstood? It makes sense to me that it loses focus I think, but I'm not sure what the i3 behavior is.

**Comment by tbm** [comment]
Yeah, the problem is that - as far as I can tell - there's no way to get back to the dmenu. It's just stuck.

It makes sense for focus to go to the SSH password prompt.  But there should be a way to get back to dmenu afterwards, either by pressing mod+d again or clicking into the dmenu area.
