### ISSUE TITLE
Use gaps as window handles

### ISSUE THREAD

**Issue by gnxlxnxx** [swaywm/sway#4696]
It's sometimes a little fiddly to grab on to the window borders since I've set them to 1px width (everything else seemed to bulky) especially if I try to use a trackpoint(which I prefer over the touchpad) or a touchscreen as input device so I think using the gaps as window handles would be a nice enhancement.

**Comment by RPigott** [comment]
I'm not sure its obvious which window would belong to which gap. If I click the gap between 2 windows, which window am I moving? Even if this was well defined, I don't think there's a high chance of the feature being accepted...

Have you tried using `floating_modifer` to grab windows? Then you can use the entire view.

**Comment by gnxlxnxx** [comment]
Yes I have not meant the floating windows but in "normal" split mode, when there are two windows side by side that instead of grabbing one of the window borders to make one window bigger and the other one smaller, you could also grab the gap in between the two. But I can see what you mean by it being not totally obvious which gap belongs to which two windows and yes I'm aware that this is a feature which is very low on the feature list, just wanted to put that out there.

> Have you tried using floating_modifer to grab windows? Then you can use the entire view.


Yes that is a feature which I regulary use and really enjoy but I meant the resizing of the windows not the dragging around. I'm sorry if that was hard to understand.

**Comment by RPigott** [comment]
With `floating_modifer normal` you can resize tiling windows with right click.

I understand what you mean about the gaps now.

**Comment by gnxlxnxx** [comment]
Oh cool, didn't know about that feature. Thanks a lot.
