### ISSUE TITLE
hide_edge_borders and smart_borders mutually exclusive

### ISSUE THREAD

**Issue by grmat** [swaywm/sway#4698]
# Summary:

`smart_borders` overrides `hide_edge borders`.

I know the sway(5) man page says, `smart_borders on` is identical to `hide_edge_borders smart`, but that's not how it's implemented in i3(-gaps 4.17.1). Hence, I'm not sure if this is considered working as expected, so forgive me my naivety.

* Sway Version: 1.2

* Debug Log: *Don't think this is necessary here, as this seems a design decision. Will file subsequently if you insist.*

# Configuration File:

1. 
       hide_edge_borders vertical
       smart_borders on
       [...]
1. 
       smart_borders on
       hide_edge_borders vertical
       [...]

# Steps to reproduce:
  1. set config as above
  1. on a workspace with no containers, open one window/container
  1. open a second window/container
  1. swap `smart_borders` and `hide_edge_borders` lines as above
  1. reload config and repeat

# Expected result:
  With one container, no border is shown. With >1 containers, only the horizontal borders are shown.

# Actual result:
1. vertical edge borders aren't hidden with >1 container
2. horizontal borders are always shown, also with just one container

  Whatever of the two configs come first is overridden/ignored.

**Comment by RPigott** [comment]
Isn't this what `hide_edge_borders --i3` is for, or am I mistaken?

Also, is your expected result for config 1 or config 2?

Or is it that it only happens when you reload from config 1 to 2? Could you describe just config1->expected->actual and config2->expected->actual if that's the case?

**Comment by grmat** [comment]
`--i3` is documented as option for "tabbed and stacked containers with one child", so it shouldn't apply here (and doesn't, I can confirm).

The expected result is for both configs. Changing the order of the same values in the config file shouldn't affect the result, IMHO.

**Comment by RPigott** [comment]
Okay that clears it up I think. Can you test if that patch has the desired behavior?

**Comment by grmat** [comment]
Yes, it's now equal to i3-gaps. Thanks!
