### ISSUE TITLE
Sway fails to start after the recent "prefer high refresh rate" commit

### ISSUE THREAD

**Issue by colemickens** [swaywm/sway#4705]
```diff
- rev = "3975ca28c2e870eb3f40bbd43a90354743f7ccf1";
-  sha256 = "01lhclh5l6shd0624m5dm3j1irbwwq3ziin5ki5kzzgraqbfqamp";
+  rev = "f33dcd4c604fa24058f6cbaf692831420dc5db67";
+  sha256 = "18xfwpgldn9psf6662anf9zq43b23zxgpb1r2xlp38hzjs3ca1qw";
```

Between there, Sway stopped being able to start with my external monitor attached. I think it's just the most recent commit f33dcd4c604fa24058f6cbaf692831420dc5db67.

[sway.log](https://github.com/swaywm/sway/files/3808884/sway.log)

**Comment by emersion** [comment]
Is this segfaulting? Do you get a coredump?

**Comment by colemickens** [comment]
No, it just fails to start. I normally just get a couple of lines of output, this is stdout and err mixed.

```
2019-11-05 04:11:15 - [backend/drm/atomic.c:57] eDP-1: Atomic commit failed (modeset): Invalid argument
```

eDP-1 is the internal panel, but I'm starting to see quite the pattern. I'm on the very latest kernel, latest DRM, nearly latest mesa. My impressions of Intel graphics support was higher, though maybe it's just Sway bugs, I don't really know much about this area.

Anyway, thanks. Let me know if I should do the usual drm debug dance and post that too.

**Comment by emersion** [comment]
Ah, I missed the atomic commit failures.

Yeah, some DRM logs would be helpful.

**Comment by JonnyMako** [comment]
I get a segfault at startup. Log attached.

[sway.log](https://github.com/swaywm/sway/files/3810022/sway.log)
[gdb.txt](https://github.com/swaywm/sway/files/3810043/gdb.txt)


```
[   74.962174] sway[1002]: segfault at 8 ip 000056060faae0ac sp 00007fffabdf4bc0 error 4 in sway[56060fa80000+5d000]
[   74.962179] Code: f0 8b 40 04 39 45 d0 75 36 48 8b 45 f0 8b 40 08 39 45 ec 75 0a 48 8b 45 f0 48 89 45 f8 eb 47 48 8b 45 f0 8b 50 08 48 8b 45 f8 <8b> 40 08 39 c2 7e 06 48 8b 45 f0 eb 04 48 8b 45 f8 48 89 45 f8 48
[   74.962226] audit: type=1701 audit(1572970639.183:74): auid=1000 uid=1000 gid=1000 ses=1 pid=1002 comm="sway" exe="/usr/local/bin/sway" sig=11 res=1
[   74.969294] audit: type=1130 audit(1572970639.190:75): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@1-1008-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[   75.237541] audit: type=1131 audit(1572970639.456:76): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@1-1008-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[   80.323173] broken atomic modeset userspace detected, disabling atomic
[   83.222722] fuse: init (API version 7.31)
```

**Comment by emersion** [comment]
Can you try https://github.com/swaywm/sway/pull/4706?

**Comment by JonnyMako** [comment]
Works, thanks!
`sway version 1.2-6f5d2efa (Nov  5 2019, branch 'best-mode-segfault')`
