### ISSUE TITLE
cannot move x windows around by mouse anymore (super+click+drag)

### ISSUE THREAD

**Issue by prometheanfire** [swaywm/sway#4707]
* Sway Version: sway version 1.2-f33dcd4c (Nov  5 2019, branch 'HEAD') plus #4704 and #4706

* Debug Log: https://gist.githubusercontent.com/prometheanfire/f950f8f6b1e56f91a68c998f84f9da5d/raw/99490ad16736cbe009101a1dc21a18119f10a800/gistfile1.txt

**Comment by Jamedjo** [comment]
Another consequence of this bug is that clicking an xwayland window doesn't focus it when `focus_follows_mouse` is disabled.

**Comment by synaptiko** [comment]
Resize with mouse also stopped working for xwayland windows (). It works only if it's triggered on the border of the window. On non-xwayland windows (doesn't matter if tiling or floating) you can press modifier and right click anywhere on the window and it starts resizing.
