### ISSUE TITLE
Setting for displaying tiling windows over floating ones

### ISSUE THREAD

**Issue by smolck** [swaywm/sway#4709]
By default, floating windows always show on top of tiling ones, as in i3. However, there are certain cases where this may not be desired, for example in a conky setup with the conky window set to floating. Currently, the conky floating window shows on top of any tiling ones, which means (at least for me) that a proper conky setup displayed on my wallpaper isn’t really possible (at least as far as I know).

Is there a setting for making tiling windows appear over floating ones? If not, could this be added?

Of course, there are some issues that may need to be addressed, like how to deal with floating dialogs. (For that specific case, maybe instead making the focused window appear over all other windows (tiling over floating, floating over tiling) could work?)

**Comment by emersion** [comment]
Conky should probably use the layer-shell protocol.

**Comment by smolck** [comment]
@emersion So should I close this issue then (and maybe open an issue on Conky)?

**Comment by emersion** [comment]
Yeah, please open an issue for Conky, if there's not one already.

**Comment by smolck** [comment]
It appears there's already an issue open for Wayland support on Conky's issue tracker. Here it is if anyone's interested: https://github.com/brndnmtthws/conky/issues/56
