### ISSUE TITLE
Sway configuration reload ignores SwayIdle configuration changes

### ISSUE THREAD

**Issue by a3n** [swaywm/sway#4716]
On the Sway configuration reload, changes related to SwayIdle are not properly taken into account.
It is needed to exit and restart Sway for such changes to be applied.

Killing and starting again the SwayIdle process when the Sway configuration is being reloaded seems to fix the issue.

**Comment by emersion** [comment]
That's by design, because `swayidle` is not part of sway, it's a regular program.
