### ISSUE TITLE
bindsym input with a group of parameters (multiline) — warning: overwriting binding.

### ISSUE THREAD

**Issue by kindaro** [swaywm/sway#4736]
## Motivation.

I am interested in having `us` + `dvorak` on `F1` and `fr` + `dépo` on `F2` — a reasonable setup.

## Description of the problem:

Consider this input configuration:

    input *
    {
        xkb_layout us
        xkb_variant dvorak
    }

It works.

However, this:

    bindsym $mod+F1 input *
    {
        xkb_layout us
        xkb_variant dvorak
    }

— Does not. A warning is issued on startup, and only the last line takes effect. So this _"compound statement"_ would activate `dvorak` variant if the current layout has it, and otherwise have no effect.

Additionally, variations such as:

    bindsym $mod+F1 input * { xkb_layout us; xkb_variant dvorak }

— Or:

    bindsym $mod+F1 input * "{ xkb_layout us; xkb_variant dvorak }"

— Do not seem to have any effect.

## `sway` version.

    % sway --version
    sway version 1.2

**Comment by emersion** [comment]
Look into using a comma to specify multiple layouts/variants and set the key to switch layouts. See `xkeyboard-config(7)`.

**Comment by RedSoxFan** [comment]
This is working as intended.
```
bindsym $mod+F1 input *
{
    xkb_layout us
    xkb_variant dvorak
}
```
gets expanded to
```
bindsym $mod+F1 input * xkb_layout us
bindsym $mod+F1 input * xkb_variant dvorak
```

As emersion mentioned, using the layout switching options from `xkeyboard-config(7)` is the recommended way of switching layouts. If you want to switch to a layout using `$mod+F1` and `$mod+F2`, the following should work:

```
input * {
    xkb_layout us,fr
    xkb_variant dvorak,dépo
}
bindsym $mod+F1 input * xkb_switch_layout 0
bindsym $mod+F2 input * xkb_switch_layout 1
```
