### ISSUE TITLE
qt.qpa.plugin: Could not load the Qt platform plugin "wayland-egl" in "" even though it was found.

### ISSUE THREAD

**Issue by roipoussiere** [swaywm/sway#4741]
I'm not sure if this is an issue with Sway, but I can't manage to execute a specific Qt program under a Wayland session (which is in fact the C++ port of the hello-world described in #4739).

* Sway Version: sway version 1.2
* Debug Log: https://gist.github.com/roipoussiere/f337a7830dd1d071fa3b4884306a9244
* Configuration File: /etc/sway/config
* /etc/environment: 

```
QT_WAYLAND_DISABLE_WINDOWDECORATION=1
QT_QPA_PLATFORM=wayland-egl
```

When executing the program, I get:

```
qt.qpa.plugin: Could not load the Qt platform plugin "wayland-egl" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.
```

Installed packages:

<details>
<summary>yay qt5 | grep Installed</summary>
<pre>
93 community/qt5ct 0.41-1 (201.4 KiB 928.0 KiB) (Installed)
91 community/qt5-styleplugins 5.0.0.20170311-17 (417.2 KiB 1.2 MiB) (Installed: 5.0.0.20170311-16)
79 community/kvantum-qt5 0.12.1-1 (866.2 KiB 6.4 MiB) (Installed)
62 extra/qt5-x11extras 5.13.2-1 (13.1 KiB 38.3 KiB) [qt qt5] (Installed: 5.13.1-1)
59 extra/qt5-webkit 5.212.0alpha3-5 (11.6 MiB 48.9 MiB) (Installed: 5.212.0alpha3-4)
56 extra/qt5-webchannel 5.13.2-1 (61.0 KiB 211.0 KiB) [qt qt5] (Installed: 5.13.1-1)
55 extra/qt5-wayland 5.13.2-1 (923.0 KiB 5.6 MiB) [qt qt5] (Installed)
52 extra/qt5-tools 5.13.2-1 (5.7 MiB 17.9 MiB) [qt qt5] (Installed: 5.13.1-2)
51 extra/qt5-svg 5.13.2-1 (135.2 KiB 494.7 KiB) [qt qt5] (Installed: 5.13.1-1)
47 extra/qt5-sensors 5.13.2-1 (160.1 KiB 928.6 KiB) [qt qt5] (Installed: 5.13.1-1)
43 extra/qt5-quickcontrols2 5.13.2-1 (1.8 MiB 8.4 MiB) [qt qt5] (Installed: 5.13.1-1)
36 extra/qt5-location 5.13.2-1 (2.8 MiB 11.8 MiB) [qt qt5] (Installed: 5.13.1-1)
34 extra/qt5-graphicaleffects 5.13.2-1 (70.4 KiB 551.3 KiB) [qt qt5] (Installed: 5.13.1-1)
30 extra/qt5-declarative 5.13.2-1 (4.0 MiB 20.8 MiB) [qt qt5] (Installed: 5.13.1-1)
26 extra/qt5-base 5.13.2-1 (12.1 MiB 61.2 MiB) [qt qt5] (Installed: 5.13.1-2)
19 extra/python-sip-pyqt5 4.19.19-1 (52.1 KiB 146.0 KiB) (Installed)
17 extra/python-pyqt5 5.13.2-1 (3.3 MiB 23.5 MiB) (Installed: 5.13.1-1)
15 extra/pyqt5-common 5.13.2-1 (508.1 KiB 4.7 MiB) (Installed: 5.13.1-1)
13 extra/polkit-qt5 0.113.0-1 (73.1 KiB 321.0 KiB) (Installed)
</pre>
</details>

<details>
<summary>yay wayland | grep Installed</summary>
<pre>
144 aur/wev-git r3.47d1739-1 (+0 0.00%) (Installed)
78 aur/wob 0.4-1 (+4 1.94%) (Installed: 0.2-1)
34 multilib/lib32-wayland 1.17.0-1 (46.5 KiB 192.0 KiB) (Installed)
32 community/wlroots 0.8.1-1 (248.2 KiB 960.0 KiB) (Installed)
27 community/waybar 0.8.0-4 (248.3 KiB 806.0 KiB) (Installed)
26 community/swaylock 1.4-2 (28.4 KiB 153.0 KiB) (Installed)
25 community/swayidle 1.5-1 (12.3 KiB 95.0 KiB) (Installed)
24 community/swaybg 1.0-3 (14.5 KiB 46.0 KiB) (Installed)
23 community/sway 1:1.2-5 (4.8 MiB 5.5 MiB) (Installed)
22 community/slurp 1.2.0-1 (13.7 KiB 74.0 KiB) (Installed)
21 community/mako 1.4-1 (35.8 KiB 140.0 KiB) (Installed)
16 community/grim 1.2.0-2 (12.2 KiB 33.0 KiB) (Installed)
15 community/glfw-wayland 3.3-2 (92.5 KiB 482.0 KiB) (Installed)
12 community/bemenu 0.1.0-1 (44.9 KiB 215.0 KiB) (Installed)
11 extra/xorg-server-xwayland 1.20.5-4 (775.2 KiB 2.0 MiB) [xorg] (Installed: 1.20.5-2)
10 extra/wayland-protocols 1.18-1 (59.5 KiB 407.0 KiB) (Installed)
8 extra/wayland 1.17.0-1 (117.7 KiB 736.0 KiB) (Installed)
7 extra/sddm 0.18.1-1 (3.4 MiB 4.7 MiB) (Installed)
6 extra/qt5-wayland 5.13.2-1 (923.0 KiB 5.6 MiB) [qt qt5] (Installed)
4 extra/libva 2.5.0-1 (145.1 KiB 715.0 KiB) (Installed)
2 extra/kwayland 5.64.0-1 (2.7 MiB 6.8 MiB) [kf5] (Installed)
1 extra/egl-wayland 1.1.4-1 (21.6 KiB 62.0 KiB) (Installed)
</pre>
</details>

When executing it with `QT_QPA_PLATFORM=xcb`, no problem.

**Comment by emersion** [comment]
This is a Qt issue, not a Sway issue.

**Comment by roipoussiere** [comment]
Ok, thanks. I reported it [here](https://forum.qt.io/topic/109060/qt-qpa-plugin-could-not-load-the-qt-platform-plugin-wayland-egl-in-even-though-it-was-found).
