### ISSUE TITLE
NKRO causes some special keys to not be possible to type

### ISSUE THREAD

**Issue by kittydoor** [swaywm/sway#4748]
* Sway Version: 1.2

* Debug Log: https://gist.github.com/kittydoor/0f0c20272f5961061dfc6f77d4ff0889 sway.log

* Configuration File: Tested with default configuration, and throughout multiple reboots

* Distro: Fedora 31, latest updates as of now
sway:rolling module enabled (issue persists with it disabled and thus an earlier sway version as well)
Sway package: sway-1.2-2.module_f31+6717+05a4cb47.src.rpm
Libinput package: libinput-1.14.3-2.fc31.src.rpm

Certain characters such as colon, pipe, curly brackets, arrow brackets don't work on my desktop on sway with the default configuration.

For reference, some keys that work on both 6KRO and NKRO:
!@#$%^&*()
Some keys that only work on 6KRO:
:{}<>"?

You can find in the gist attached below some libinput debug information:
https://gist.github.com/kittydoor/e9f5a3f8ce547bd13851288a30106f39

My initial observations is that, libinput does detect Shift presses and key presses on both 6KRO and NKRO, but on NKRO it fails to realize that the intent is to combine Shift and [ to create {, etc. And the output is just a '-' rather than any valid character on the nkro.txt which I'm not sure what that means.

This is a sway bug, as it works perfectly on both settings on this keyboard (Coolermaster Quickfire TK) with Gnome-Shell on Wayland

**Comment by RedSoxFan** [comment]
Please try building sway and wlroots from their respective masters. #4373 was merged last week which should handle this situation

**Comment by Vorsplummi** [comment]
I tested sway with a keyboard that can use NKRO over USB and everything worked as expected.
