### ISSUE TITLE
Crash when reloading Sway with multiple seats configured

### ISSUE THREAD

**Issue by paul-ri** [swaywm/sway#4750]
* **Version:** `1.2-1d3cbe9f (Nov 21 2019, branch 'master')`
* **`uname -a:`** `Linux mdu-laptop 5.3.12-arch1-1 #1 SMP PREEMPT Wed, 20 Nov 2019 19:45:16 +0000 x86_64 GNU/Linux`

Sway crashes when reloading it, if some type of seat configuration has been provided.  
e.g. my sway config file has the following line `seat work_laptop_integrated_seat hide_cursor 5000` and sway crashes every time it is being reloaded.

## Reproduction steps
I've narrowed it down to some simple steps
* **config**
  ```
  # sway_config_error.config
  exec xterm
  exec 'sleep 2; swaymsg seat test hide_cursor 5000'
  ```
* **run command**  
  `sway -d -c sway_config_error.config 2> sway.log` -> Crash after 2 seconds
* **output**
  ```
  2019-11-24 18:54:13 - [sway/commands.c:255] Handling command 'seat test hide_cursor 5000'
  2019-11-24 18:54:13 - [sway/commands.c:423] Subcommand: hide_cursor 5000
  2019-11-24 18:54:13 - [sway/config/seat.c:61] Adding non-wildcard seat config
  2019-11-24 18:54:13 - [sway/config/seat.c:78] Config stored for seat test
  2019-11-24 18:54:13 - [sway/input/input-manager.c:398] applying seat config for seat test
  (EE) failed to read Wayland events: Broken pipe
  2019-11-24 18:54:13 - [common/ipc-client.c:88] Unable to receive IPC response
  xterm: fatal IO error 11 (Resource temporarily unavailable) or KillClient on X server ":1"
  fish: Job 2, “/usr/bin/sway $argv” terminated by signal SIGSEGV (Address boundary error)
  ```

## Potential cause
When debugging with Eclipse:
1. I get a crash in [`seat_tablet_pads_notify_enter()`](https://github.com/swaywm/sway/blob/5d882cb5fc2d9d9fd68439021e48a90aa2e50e79/sway/input/seat.c#L137).
   * The function tries to loop the devices of the seat _"test"_ using `wl_list_for_each()`
   * The seat has not been initialised properly at that point: `seat->devices->`'s `prev / next` are `0x0` which causes the segmentation fault
   * The stack:
     ```
     Thread #1 [sway] 209199 [core: 0] (Suspended : Breakpoint)	
     seat_tablet_pads_notify_enter() at seat.c:139 0x555555586d7c	
     seat_send_focus() at seat.c:167 0x555555586e87	
     seat_set_focus() at seat.c:1,057 0x5555555892d9	
     seat_create() at seat.c:514 0x555555587c39	
     input_manager_get_seat() at input-manager.c:44 0x55555557e838	
     input_manager_apply_seat_config() at input-manager.c:412 0x55555557f95e	
     config_handlers() at seat.c:43 0x5555555a1c6d	
     cmd_seat() at seat.c:75 0x5555555a1ded	
     execute_command() at commands.c:286 0x555555564ad4	
     ipc_client_handle_command() at ipc-server.c:634 0x5555555707a7	
     <...more frames...>	
     ```
2. `wl_list_init(&seat->devices);` has not been called on time.
3. It looks like `seat_create()` does not initialise the device list of the new seat properly. This might be due to ab0248a54564b2f644b6fb367f9eb44fe0bf5f3c which calls `seat_set_focus()` before `wl_list_init(&seat->devices);`

**Suggested solution:** put `wl_list_init(&seat->devices);` before what ab0248a54564b2f644b6fb367f9eb44fe0bf5f3c introduced. This fixes the crash. But I have no clue if that's the right thing to do!

I've had other issues with seats for which I might create further issues if this one does not fix it.

And thanks for what you're doing, Sway is amazing!

**Comment by emersion** [comment]
Looks like a good solution to me! Can you send a PR?
