### ISSUE TITLE
XWayland Theme

### ISSUE THREAD

**Issue by joshuachp** [swaywm/sway#4760]
# XWayland Theme

I had a problem with VS-code and Firefox not picking up the GTK theme I've set. Even if I have correctly configured the GTK files and gsetting. Since they run throw XWayland they use xsettings to pick the theme. So I had to start the xsettings demon in the configuration file (I use Gnome):

` exec --no-startup-id /usr/lib/gsd-xsettings`

> An alternative could be [xsettingsd](https://github.com/derat/xsettingsd).

I think it would be useful to add this to the Wiki page [GTK 3 settings on Wayland](https://github.com/swaywm/sway/wiki/GTK-3-settings-on-Wayland).

**Comment by emersion** [comment]
The wiki is world-writable. You're welcome to improve it.
