### ISSUE TITLE
Sway crashes on reloading config with ctrl:swapcaps enabled

### ISSUE THREAD

**Issue by eliedrian** [swaywm/sway#4761]
So sway crashes on my E485 while reloading config with a `ctrl:swapcaps` enabled. Curiously, starting sway the first time does not crash and Caps Lock and Ctrl is indeed swapped. I've narrowed the problem down to my capslock rebinding config; sway only crashed while I had the `input` block.

**Sway version:** sway version 1.2-939c7b2d (Nov 23 2019, branch 'master')

**Debug log:** https://gist.github.com/eliedrian/32bf2876ed751eb15cdc6ceb9e6a1324

**Relevant configuration:**
```
# rebind capslock to ctrl
input 1:1:AT_Translated_Set_2_keyboard {
	xkb_options ctrl:swapcaps
}
```
**Stack trace:** https://gist.github.com/eliedrian/11e54816f308af539a4da559f6c81c27

**Comment by emersion** [comment]
Please try to update to the latest wlroots/sway commit.

**Comment by eliedrian** [comment]
Ah, just updated from git and it works now. Didn't think to update! Thanks.
