### ISSUE TITLE
Can't explicitly start wayland backend

### ISSUE THREAD

**Issue by simonwjackson** [swaywm/sway#4762]
## Goal: Run sway on a laptop and connect my tablet as a second screen via RDP.

Sway Version: 1.2-43bd8dc4 (Oct 24 2019, branch 'master')
Configuration File (stock): https://pastebin.com/0FS4Mrij

### Sway (standalone): Works

log: https://pastebin.com/eUtMY0PH

```bash 
$ sway -Vd -c /etc/sway/config
```

### Sway (RDP backend): Works

log: https://pastebin.com/YvqpiPNJ

```bash
$ WLR_RDP_TLS_CERT_PATH=${HOME}/.keys/tls/tls.crt \
WLR_RDP_TLS_KEY_PATH=${HOME}/.keys/tls/tls.key \
WLR_RDP_ADDRESS=0.0.0.0 \
WLR_BACKENDS=rdp \
sway -Vd -c /etc/sway/config 
```
### Sway (Wayland backend): Fails

log: https://pastebin.com/V8pUQPCg

```bash
$ WLR_BACKENDS=wayland sway -Vd -c /etc/sway/config
```

### Sway (RDP & Wayland backend): Fails

log: https://pastebin.com/FWtGcS5H

```bash
WLR_RDP_TLS_CERT_PATH=${HOME}/.keys/tls/tls.crt \
WLR_RDP_TLS_KEY_PATH=${HOME}/.keys/tls/tls.key \
WLR_RDP_ADDRESS=0.0.0.0 \
WLR_BACKENDS=rdp,wayland \
sway -Vd -c /etc/sway/config 
```

### Log snippet
```
...
[sway/server.c:40] Preparing Wayland server initialization
[backend/wayland/backend.c:234] Creating wayland backend
[backend/wayland/backend.c:250] Could not connect to remote display: No such file or directory
[backend/backend.c:274] failed to start backend 'wayland'
[backend/noop/backend.c:51] Creating noop backend
[sway/server.c:47] Unable to create backend
```

**Comment by emersion** [comment]
The Wayland backend will only work inside another Wayland compositor. What is `WAYLAND_DISPLAY` set to?

Wayland + RDP won't work.

**Comment by simonwjackson** [comment]
```bash
$ echo $WAYLAND_DISPLAY
```
this returns nothing.

Is there a way to start sway for normal use on my laptop and with RDP running in the background?
I'd like to have the RDP client on the same session on connect it would open a new workspace

**Comment by emersion** [comment]
No, this isn't possible. The plan is to support screensharing with clients instead, e.g. https://github.com/atx/wvnc.
