### ISSUE TITLE
Clamshell mode doesn't preserve on reload

### ISSUE THREAD

**Issue by joaomoreno** [swaywm/sway#4765]
Sway version 1.2

Clamshell works great and the laptop display turns on and off as I open and close the laptop lid. But while it is closed, it fails to preserve the off state when `reload` is run.

```
bindswitch lid:on output $laptop disable
bindswitch lid:off output $laptop enable
```

1. Close the laptop lid: laptop display is disabled
2. Reload sway <kbd>$mod+Shift+c</kbd>

Laptop display is suddenly enabled.

**Comment by jasperro** [comment]
See issue #4305 which is fixed by #4312, you need to add `--reload` to your bindswitches, and your display should stay disabled.

**Comment by joaomoreno** [comment]
@jasperro Thanks, I did do some search beforehand but failed to find these.

**Comment by joaomoreno** [comment]
@jasperro I've updated the wiki to include that option: https://github.com/swaywm/sway/wiki#clamshell-mode
