### ISSUE TITLE
dmenu shown on primary screen, not on active workspace

### ISSUE THREAD

**Issue by tbm** [swaywm/sway#4770]
[This is with sway 1.2]

I use a laptop with external monitor. I leave the internal screen enabled (but close the lid) and move the workspaces to the external screen using:

    swaymsg move workspace to right

There was still one workspace on the internal screen (which I obviously didn't see because I closed the lid).

Anyway, when I pressed mod+d to get dmenu it didn't display.  Eventually I figured out that it was always displayed on workspace 5 on the internal screen, even when I was one workspace 1-4 which was displayed on my external monitor.

Shouldn't dmenu always open up in the current active workspace?

My config has:

```
set $menu dmenu_path | dmenu | xargs swaymsg exec
bindsym $mod+d exec $menu
```

**Comment by tbm** [comment]
And of course just after writing this report and trying to add more info (swaymsg -t get_workspaces) I don't see the issue any more.  It was definitely there before though.

**Comment by emersion** [comment]
dmenu is an X11 tool, it won't choose the right workspace unless another X11 window is focused while starting it. I'd suggest using another menu like bemenu.

**Comment by tbm** [comment]
> dmenu is an X11 tool, it won't choose the right workspace unless another X11 window is focused while starting it.

I think that explains why I can't reproduce the issue now (because I started firefox).

**Comment by tbm** [comment]
> dmenu is an X11 tool, it won't choose the right workspace unless another X11 window is focused while starting it.

So, I don't know anything about wayland or sway.  But shouldn't X11 windows open in the currently active workspace regardless?

**Comment by emersion** [comment]
No. X11 windows like dmenu rely on the pointer absolute location to position themselves on the right monitor. Wayland has no such concept.

**Comment by tbm** [comment]
Ok, thanks for taking the time to explain @emersion. I appreciate your time and patience!
