### ISSUE TITLE
Two Alternative Multi-Monitor Setups for Sway

### ISSUE THREAD

**Issue by mrjpaxton** [swaywm/sway#4771]
This is a **suggestion** for two alternate ways of switching between workspaces (virtual desktops) in Sway.

So far, as much as I want to like Sway, I greatly dislike how the workspaces are handled. Right now, they closely follow the implementation of vanilla i3, where workspaces are shared, but separated between monitors (or screens).

For example, I have two monitors, and both workspace 1 and workspace 2 are automatically created on each monitor when I start Sway.

When the user presses Mod+1 it will focus on the workspace on the "first monitor" and if you press Mod+2, it will focus on the "second monitor".

If anything else but Mod+1 and Mod+2 are pressed, a new workspace is created on the currently "focused monitor", and empty workspaces are removed if there are no windows in the workspace, which makes sense.

However, you can imagine how lost someone would be if 4 workspaces were automatically created among 4 monitors, and since there are only 10 digits in most English/cardinal languages, having 10 workspaces only accessible with a minimum of two key-presses can be very limiting, especially when divided among 4 monitors.

Also, new users have to keep remembering which workspaces are created on which screens, which are removed, which exist, and which windows are open in each workspace, on each screen! It's frustrating to say the least!

With all that in mind, here's some alternatives to, in my opinion, this very counter-intuitive, default method.

## Alternative 1 - Grouped workspaces per-monitor

Each monitor can be treated as a separate group. For example, they could be called **Workspace Groups**. Let's say that workspace 1-1 is workspace 1 on the first monitor, and workspace 2-1 is workspace 1 on the second monitor. You can see where this is going....

Applications/Windows can easily be separated between screens, yet still, because you can display whichever workspaces you want for each monitor, it is very flexible for the user to show and hide whichever workspaces you want, and it offers an option for 10 easily accessible workspaces per-monitor (or to be more precise, per-group)!

In order to switch between workspace groups, you could use some unused keybinds, that involve arrow keys or numbering, or perhaps you could just have your mouse cursor on whichever monitor you wanted, in order to specify the group.

Either way, it just makes a lot of sense. Even if it may be difficult to implement.

## Alternative 2 - Workspaces are shared among all screens

Instead of separating workspaces between screens, why not use each workspace for all screens? This is actually somewhat similar to how most DEs and WMs work, such as Openbox and XFCE, and it should be easier to implement!

Like the default implementation, the same amount of keystrokes are required to switch between groups. But you would have a maximum of 10 groups before needing additional keypresses to access more workspaces.

Both the default and this implementation do not scale well the more screens you have, but it should be a lot easier to implement in the meantime.

## Conclusion

I honestly think all 3 methods should be implemented, to give the power-user more options, but the way it works right now is great for veteran i3 users. I am a new user of Sway/i3, so I have a fresh perspective of how these things should work.

I was just really disappointed of how it handles right now. Sure, it's great for single-monitor use, but Sway still extremely fails in terms of dual-monitor, or higher, and I keep going back to other WMs because of it.

I hope the developers consider these options, and I hope non-developers and other uses can support decisions like these, at the very least.

Thank you for reading!

**Comment by RPigott** [comment]
This has a low chance of being implemented in sway without being implemented in i3 first, I think. Maybe you'd like to just change your keybinds?

Have you considered making use of 'workspace next_on_output', 'focus output ___', or 'workspace <name> output' commands? Maybe ask the r/i3wm subreddit if anyone has the same preference as you, and what keybinds they use.

**Comment by synaptiko** [comment]
I had a similar idea recently, I have something non-generic here: https://github.com/synaptiko/.files/blob/master/sway/switch-output.sh

It's adjusted to my setup where I have two monitors, the one on the top, the other on the bottom and I have bindings to switch between them. And because Sway allows to re-bind keys dynamically, you can write a script similar to the above one. It should be possible to automate it with IPC.

**Comment by trains3d** [comment]
> If anything else but Mod+1 and Mod+2 are pressed, a new workspace is created on the currently "focused monitor", and empty workspaces are removed if there are no windows in the workspace, which makes sense.

You can assign workspace to output, then when you press Mod+3 then workspace 3 will be created at proper monitor:

```
# Define outputs
set $output-primary DP-1
set $output-secondary eDP-1

# workspace to displays
workspace 1 output $output-primary
workspace 2 output $output-primary
workspace 3 output $output-primary
workspace 4 output $output-primary
workspace 5 output $output-primary
workspace 6 output $output-primary

workspace 7 output $output-secondary
workspace 8 output $output-secondary
workspace 9 output $output-secondary
workspace 10 output $output-secondary
```

If DP-1 is not connected then workspace will be created at monitor which has focus. When you connect DP1, they will move to proper monitors

I'm using i3, but I guess that in sway it works same way.

**Comment by diraol** [comment]
> I'm using i3, but I guess that in sway it works same way.

Yes it does, and I do use it just like you.

```
# Workspaces:
    # Special workspaces shortcuts
    # Personal firefox
    set $wsp 
    # Music (Deezer)
    set $wsd ♪
    # Messaging (Franz)
    set $wsm 
    # Telegram
    set $wst 

    # Switch to workspace
    bindsym F1 workspace 1
    bindsym F2 workspace 2
    bindsym F3 workspace 3
    bindsym F4 workspace 4
    bindsym F5 workspace 5
    bindsym F6 workspace 6
    bindsym F7 workspace 7
    bindsym F8 workspace 8
    bindsym F9 workspace 9
    bindsym F10 workspace 10
    bindsym F11 workspace $wsm
    bindsym F12 workspace $wst
    bindsym $mod+m workspace $wsd
    bindsym $mod+p workspace $wsp

    # Move focused container to workspace
    bindsym $mods+F1 move container to workspace 1
    bindsym $mods+F2 move container to workspace 2
    bindsym $mods+F3 move container to workspace 3
    bindsym $mods+F4 move container to workspace 4
    bindsym $mods+F5 move container to workspace 5
    bindsym $mods+F6 move container to workspace 6
    bindsym $mods+F7 move container to workspace 7
    bindsym $mods+F8 move container to workspace 8
    bindsym $mods+F9 move container to workspace 9
    bindsym $mods+F10 move container to workspace 10
    bindsym $mods+F11 move container to workspace $wsm
    bindsym $mods+F12 move container to workspace $wst
    bindsym $mods+m move container to workspace $wsd
    bindsym $mods+p move container to workspace $wsp

    # Attaching workspaces to outputs
    workspace 1 output DP-2 DP-1 eDP-1
    workspace 2 output DP-2 DP-1 eDP-1
    workspace 3 output DP-2 DP-1 eDP-1
    workspace 4 output DP-2 DP-1 eDP-1
    workspace $wsp output eDP-1 DP-2 DP-1
    workspace $wsd output eDP-1 DP-2 DP-1
    workspace $wsm output eDP-1 DP-2 DP-1
    workspace $wst output eDP-1 DP-2 DP-1
```

I'd also add that you are not limited to 10 workspaces, as you can see in my config I have some other workspaces using other letters that are more meaningful, and I attach some applications to these workspaces.

**Comment by YaLTeR** [comment]
I also don't particularly like this i3 style of workspace management (coming from the Awesome WM). I have two monitors, so I bound \<something\>+1-9 to workspaces on the first monitor and \<something\>+F1-F9 to workspaces on the second monitor:
```
# Set first monitor workspaces to first monitor
workspace $ws_1 output $first_monitor
workspace $ws_2 output $first_monitor
workspace $ws_3 output $first_monitor
workspace $ws_4 output $first_monitor
workspace $ws_5 output $first_monitor
workspace $ws_6 output $first_monitor
workspace $ws_7 output $first_monitor
workspace $ws_8 output $first_monitor
workspace $ws_9 output $first_monitor
workspace $ws_10 output $first_monitor

# Set second monitor workspaces to second monitor
workspace $ws_11 output $second_monitor
workspace $ws_12 output $second_monitor
workspace $ws_13 output $second_monitor
workspace $ws_14 output $second_monitor
workspace $ws_15 output $second_monitor
workspace $ws_16 output $second_monitor
workspace $ws_17 output $second_monitor
workspace $ws_18 output $second_monitor
workspace $ws_19 output $second_monitor
workspace $ws_20 output $second_monitor

# Switch to workspace
bindsym --to-code $mod+1 workspace $ws_1
bindsym --to-code $mod+2 workspace $ws_2
bindsym --to-code $mod+3 workspace $ws_3
bindsym --to-code $mod+4 workspace $ws_4
bindsym --to-code $mod+5 workspace $ws_5
bindsym --to-code $mod+6 workspace $ws_6
bindsym --to-code $mod+7 workspace $ws_7
bindsym --to-code $mod+8 workspace $ws_8
bindsym --to-code $mod+9 workspace $ws_9
bindsym --to-code $mod+0 workspace $ws_10

# Move focused container to workspace
bindsym --to-code $mod+Shift+1 move container to workspace $ws_1
bindsym --to-code $mod+Shift+2 move container to workspace $ws_2
bindsym --to-code $mod+Shift+3 move container to workspace $ws_3
bindsym --to-code $mod+Shift+4 move container to workspace $ws_4
bindsym --to-code $mod+Shift+5 move container to workspace $ws_5
bindsym --to-code $mod+Shift+6 move container to workspace $ws_6
bindsym --to-code $mod+Shift+7 move container to workspace $ws_7
bindsym --to-code $mod+Shift+8 move container to workspace $ws_8
bindsym --to-code $mod+Shift+9 move container to workspace $ws_9
bindsym --to-code $mod+Shift+0 move container to workspace $ws_10

# Second monitor workspaces with F-keys
bindsym --to-code $mod+F1 workspace $ws_11
bindsym --to-code $mod+F2 workspace $ws_12
bindsym --to-code $mod+F3 workspace $ws_13
bindsym --to-code $mod+F4 workspace $ws_14
bindsym --to-code $mod+F5 workspace $ws_15
bindsym --to-code $mod+F6 workspace $ws_16
bindsym --to-code $mod+F7 workspace $ws_17
bindsym --to-code $mod+F8 workspace $ws_18
bindsym --to-code $mod+F9 workspace $ws_19
bindsym --to-code $mod+F10 workspace $ws_20

bindsym --to-code $mod+Shift+F1 move container to workspace $ws_11
bindsym --to-code $mod+Shift+F2 move container to workspace $ws_12
bindsym --to-code $mod+Shift+F3 move container to workspace $ws_13
bindsym --to-code $mod+Shift+F4 move container to workspace $ws_14
bindsym --to-code $mod+Shift+F5 move container to workspace $ws_15
bindsym --to-code $mod+Shift+F6 move container to workspace $ws_16
bindsym --to-code $mod+Shift+F7 move container to workspace $ws_17
bindsym --to-code $mod+Shift+F8 move container to workspace $ws_18
bindsym --to-code $mod+Shift+F9 move container to workspace $ws_19
bindsym --to-code $mod+Shift+F10 move container to workspace $ws_20
```

**Comment by kennylevinsen** [comment]
I'd like to add that the aforementioned workarounds are workable for fixed dual-screen setups, but does not help in variable-screen setups. Imagine a laptop that is often docked, possibly in multiple places. At any given point, I have anywhere between 1 and 3 screens, and I am sure others' would take it further.

Such a setup pretty much renders i3-style workspaces border-line unusable. Default-positioned workspaces are chaotic: Their initial position is not logical, and empty workspaces spawn on the focused output leaving disorganized workspace->output assignments. On the other hand, trying to fix the issue with a config generalized for N outputs is pretty much impossible.

A per-output workspaces (like is the case for awesomewm's tags) handles this in a general fashion much more elegantly. I think *optional* support for such a mode would be a *very* small feature, and could possibly be implemented without needing i3 support first.

**Comment by mrjpaxton** [comment]
Hey, I am also okay with using multiple workspaces with Alt now.

Here's what I'm using:

```
# Switch to workspace
bindsym --to-code $mod+1 workspace $ws1
bindsym --to-code $mod+2 workspace $ws2
bindsym --to-code $mod+3 workspace $ws3
bindsym --to-code $mod+4 workspace $ws4
bindsym --to-code $mod+5 workspace $ws5
bindsym --to-code $mod+6 workspace $ws6
bindsym --to-code $mod+7 workspace $ws7
bindsym --to-code $mod+8 workspace $ws8
bindsym --to-code $mod+9 workspace $ws9
bindsym --to-code $mod+0 workspace $ws0

bindsym --to-code $mod+Mod1+1 workspace $wsa1
bindsym --to-code $mod+Mod1+2 workspace $wsa2
bindsym --to-code $mod+Mod1+3 workspace $wsa3
bindsym --to-code $mod+Mod1+4 workspace $wsa4
bindsym --to-code $mod+Mod1+5 workspace $wsa5
bindsym --to-code $mod+Mod1+6 workspace $wsa6
bindsym --to-code $mod+Mod1+7 workspace $wsa7
bindsym --to-code $mod+Mod1+8 workspace $wsa8
bindsym --to-code $mod+Mod1+9 workspace $wsa9
bindsym --to-code $mod+Mod1+0 workspace $wsa0

# Move focused container to workspace
bindsym --to-code $mod+Shift+1 move container to $ws1
bindsym --to-code $mod+Shift+2 move container to $ws2
bindsym --to-code $mod+Shift+3 move container to $ws3
bindsym --to-code $mod+Shift+4 move container to $ws4
bindsym --to-code $mod+Shift+5 move container to $ws5
bindsym --to-code $mod+Shift+6 move container to $ws6
bindsym --to-code $mod+Shift+7 move container to $ws7
bindsym --to-code $mod+Shift+8 move container to $ws8
bindsym --to-code $mod+Shift+9 move container to $ws9
bindsym --to-code $mod+Shift+0 move container to $ws0

bindsym --to-code $mod+Mod1+Shift+1 move container to workspace $wsa1
bindsym --to-code $mod+Mod1+Shift+2 move container to workspace $wsa2
bindsym --to-code $mod+Mod1+Shift+3 move container to workspace $wsa3
bindsym --to-code $mod+Mod1+Shift+4 move container to workspace $wsa4
bindsym --to-code $mod+Mod1+Shift+5 move container to workspace $wsa5
bindsym --to-code $mod+Mod1+Shift+6 move container to workspace $wsa6
bindsym --to-code $mod+Mod1+Shift+7 move container to workspace $wsa7
bindsym --to-code $mod+Mod1+Shift+8 move container to workspace $wsa8
bindsym --to-code $mod+Mod1+Shift+9 move container to workspace $wsa9
bindsym --to-code $mod+Mod1+Shift+0 move container to workspace $wsa0

#Workspace output settings

workspace $ws1 output primary
workspace $ws2 output primary
workspace $ws3 output primary
workspace $ws4 output primary
workspace $ws5 output primary
workspace $ws6 output primary
workspace $ws7 output primary
workspace $ws8 output primary
workspace $ws9 output primary
workspace $ws0 output primary

workspace $wsa1 output $secondary
workspace $wsa2 output $secondary
workspace $wsa3 output $secondary
workspace $wsa4 output $secondary
workspace $wsa5 output $secondary
workspace $wsa6 output $secondary
workspace $wsa7 output $secondary
workspace $wsa8 output $secondary
workspace $wsa9 output $secondary
workspace $wsa0 output $secondary
```

While this works okay, my problem is that whichever window is focused, or when the mouse is focused on another output, or something like that, creates the workspace in that output. If that makes sense.

What I want to do is force a newly created workspace to a specific output no matter what, and never create a workspace in a different output that I specify. How do I do that? I couldn't find any kind of setting in the docs so far.

**Comment by diraol** [comment]
> ```
> # Secondary monitor
> 
> set $secondary = DisplayPort-0
> 
> # Workspace output settings
> 
> workspace $ws1 output primary
> ...
> workspace $ws0 output primary
> 
> workspace $wsa1 output $secondary
> ...
> workspace $wsa0 output $secondary
> ```

Three things.
 1. You are not defining the `primary` variable
 2. There is a small mistake in the `secondary` variable (there should be no "equal" there)
 3. After settings the `primary` variable do not forget to use it with `$primary`.

That may help you @mrjpaxton :)

**Comment by zsugabubus** [comment]
> I honestly think all 3 methods should be implemented, to give the power-user more options, but the way it works right now is great for veteran i3 users. I am a new user of Sway/i3, so I have a fresh perspective of how these things should work.

Have you tried scripting? What about these?

```cfg
# Grouped workspaces per-monitor
bindsym $mod+1 exec /path/to/wpo 1
bindsym $mod+2 exec /path/to/wpo 2
...

# Moving between outputs.
bindsym $mod+Left focus output left
...

# Workspaces are shared among all screens
# (Not sure if understood correctly...)
bindsym $mod+1 exec /path/to/biw "1: A"
bindsym $mod+2 exec /path/to/biw "1: B"
...
```

`/path/to/wpo`:
```sh
#!/bin/sh
OUTPUT_INDEX="$(swaymsg -t get_outputs | jq 'map(.focused)|to_entries|.[]|select(.value)|.key+1')"
NUMBER=$1
# Prefix every workspace with output index:
# - If it doesn't exist yet, it will be created on the current, focused output.
# - If it exists it must be on the current output and it will be focused.
swaymsg workspace "$OUTPUT_INDEX-$NUMBER"
```

`/path/to/biw`:
```sh
#!/bin/sh
OUTPUT="$(swaymsg -t get_outputs | jq -r '.[]|select(.focused)|.name')"
WORKSPACE="$1"
# Switch to workspace and simply move it to the focused output.
swaymsg workspace "$WORKSPACE" \; move workspace to output "$OUTPUT"
```

(Untested, but hope it helps something.)

**Comment by kennylevinsen** [comment]
See https://github.com/swaywm/sway/pull/4846 for a draft implementation of output-local workspaces ala how awesomewm behaves.

**Comment by ddevault** [comment]
We're not interested in diverging this far from i3.

**Comment by emersion** [comment]
Sorry, I should have asked this before, but @kennylevinsen can you open a new issue on the i3 bug tracker to see if they would be interested in this feature?

**Comment by NessunoZero** [comment]
Probably is late for this, but I founded this discuss right now, maybe you want take a look to this multi screen possibly config.

[https://github.com/NessunoZero/Sway-multimonitors-config-and-scripts](https://github.com/NessunoZero/Sway-multimonitors-config-and-scripts)

**Comment by einmensch** [comment]
thing is none of this actually works for me. i tryed all sorts of configurations from supposably configuring certain workspaces to show up on certain moninotiors to just trying to move a workspace to a monitor in one command and none of it worked, MAYBE my screen name is wrong but its not only that i cant assign a monitor to my secondary dislay but also that it then does switch to the monitor on my primary display.

**Comment by Hyask** [comment]
I've made an external implementation of "Alternative 1": https://git.hya.sk/skia/swaysome  
It's been working great for the past month, and was fairly easy to develop and setup, so in overall I'm pretty happy with the result.

I already posted this in the [i3 issue](https://github.com/i3/i3/issues/3885#issuecomment-758526106), but I realized this would make more sense to put it here, especially since it doesn't seem to work with i3 as-is (but I don't use i3 and made only a very quick test).

**Comment by nab-os** [comment]
Nice solution @Hyask !
Maybe adding swaysome to the wiki could be interesting.

**Comment by dedsm** [comment]
I too found this issue a bit irritable, and I'm coming from xmonad that implements the "Alternative 2" which to me feels natural, as a bonus, xmonad has this nice default of being able to focus or move windows to specific outputs based on its position, so from left to right.

I've created a python script that will implement both the "focus output on the {left,center,right}", "move container to output on the {left,center,right}" and the transparent sharing of workspaces across outputs the same way xmonad deals with it in all the possible cases:
- both workspaces "belong" to the same output
- both workspaces are visible in different outputs
- the workspace is not visible
- the workspace doesn't exist

The relevant sway config:

```
bindsym Mod4+1 exec i3xmonadhelper workspace 1
bindsym Mod4+2 exec i3xmonadhelper workspace 2
bindsym Mod4+3 exec i3xmonadhelper workspace 3
bindsym Mod4+4 exec i3xmonadhelper workspace 4
bindsym Mod4+5 exec i3xmonadhelper workspace 5
bindsym Mod4+6 exec i3xmonadhelper workspace 6
bindsym Mod4+7 exec i3xmonadhelper workspace 7
bindsym Mod4+8 exec i3xmonadhelper workspace 8
bindsym Mod4+9 exec i3xmonadhelper workspace 9

bindsym Mod4+w exec i3xmonadhelper monitor left
bindsym Mod4+e exec i3xmonadhelper monitor center
bindsym Mod4+r exec i3xmonadhelper monitor right

bindsym Mod4+Shift+w exec i3xmonadhelper send_to_output left
bindsym Mod4+Shift+e exec i3xmonadhelper send_to_output center
bindsym Mod4+Shift+r exec i3xmonadhelper send_to_output right
```

https://gist.github.com/dedsm/610a004d896cac3a93c59558a8326dd9

**Comment by diraol** [comment]
Just to share, I've been using kanshi + sway for my setup and it is working quite well.

This is my kanshi settings:

```
profile dell_xps13 {
    output "Unknown 0x282B" mode 3840x2160 scale 2 position 0,0
}

profile thinkpad_p52s {
    output "Chimei Innolux Corporation 0x15E5" mode 1920x1080 position 0,0
}

profile dell_precision {
    output "Sharp Corporation 0x14D1" mode 1920x1200 position 0,0
}

profile three_mon_dell {
    output "Dell Inc. DELL P2719H" mode 1920x1080 position 0,0
    output "Dell Inc. DELL U2722D" mode 2560x1440 position 1920,0
    output "Sharp Corporation 0x14D1" mode 1920x1200 position 0,0
}

profile three_mon_tp52s {
    output "Dell Inc. DELL P2719H" mode 1920x1080 position 0,0
    output "Dell Inc. DELL U2722D" mode 2560x1440 position 1920,0
    output "Sharp Corporation 0x14D1" mode 1920x1200 position 0,0
}

profile two_external {
    output "Dell Inc. DELL P2719H" mode 1920x1080 position 0,0
    output "Dell Inc. DELL U2722D" mode 2560x1440 position 1920,0
}
```

and this is my sway setting:
```
    # Special workspaces shortcuts
    # Personal firefox
    set $wsp 
    # Music (Deezer)
    set $wsd ♪
    # Messaging (Franz/Ferdi)
    set $wsm 
    # Telegram
    set $wst 

    # Switch to workspace
    bindsym F1 workspace 1
    bindsym F2 workspace 2
    bindsym F3 workspace 3
    bindsym F4 workspace 4
    bindsym F5 workspace 5
    bindsym F6 workspace 6
    bindsym F7 workspace 7
    bindsym F8 workspace 8
    bindsym F9 workspace 9
    bindsym F10 workspace 10
    bindsym F11 workspace $wsm
    bindsym F12 workspace $wst
    bindsym $mod+m workspace $wsd
    bindsym $mod+p workspace $wsp

    # Move focused container to workspace
    bindsym $mods+F1 move container to workspace 1
    bindsym $mods+F2 move container to workspace 2
    bindsym $mods+F3 move container to workspace 3
    bindsym $mods+F4 move container to workspace 4
    bindsym $mods+F5 move container to workspace 5
    bindsym $mods+F6 move container to workspace 6
    bindsym $mods+F7 move container to workspace 7
    bindsym $mods+F8 move container to workspace 8
    bindsym $mods+F9 move container to workspace 9
    bindsym $mods+F10 move container to workspace 10
    bindsym $mods+F11 move container to workspace $wsm
    bindsym $mods+F12 move container to workspace $wst
    bindsym $mods+m move container to workspace $wsd
    bindsym $mods+p move container to workspace $wsp

    # Attaching workspaces to outputs
    workspace 1 output DP-8 DP-7 DP-6 DP-5 DP-4 DP-3 DP-2 DP-1 eDP-1
    workspace 2 output DP-8 DP-7 DP-6 DP-5 DP-4 DP-3 DP-2 DP-1 eDP-1
    workspace 3 output DP-8 DP-7 DP-6 DP-5 DP-4 DP-3 DP-2 DP-1 eDP-1
    workspace 4 output DP-8 DP-7 DP-6 DP-5 DP-4 DP-3 DP-2 DP-1 eDP-1
    workspace 5 output DP-8 DP-7 DP-6 DP-5 DP-4 DP-3 DP-2 DP-1 eDP-1
    workspace 6 output DP-8 DP-7 DP-6 DP-5 DP-4 DP-3 DP-2 DP-1 eDP-1
    workspace 7 output DP-1 DP-2 DP-3 DP-4 DP-5 DP-6 DP-7 DP-8 eDP-1
    workspace 8 output DP-1 DP-2 DP-3 DP-4 DP-5 DP-6 DP-7 DP-8 eDP-1
    workspace 9 output DP-1 DP-2 DP-3 DP-4 DP-5 DP-6 DP-7 DP-8 eDP-1
    workspace 10 output DP-1 DP-2 DP-3 DP-4 DP-5 DP-6 DP-7 DP-8 eDP-1
    workspace 11 output DP-1 DP-2 DP-3 DP-4 DP-5 DP-6 DP-7 DP-8 eDP-1
    workspace 12 output DP-1 DP-2 DP-3 DP-4 DP-5 DP-6 DP-7 DP-8 eDP-1
    workspace $wsp output eDP-1 DP-1 DP-2 DP-3 DP-4 DP-5 DP-6 DP-7 DP-8
    workspace $wsd output eDP-1 DP-1 DP-2 DP-3 DP-4 DP-5 DP-6 DP-7 DP-8
    workspace $wsm output eDP-1 DP-1 DP-2 DP-3 DP-4 DP-5 DP-6 DP-7 DP-8
    workspace $wst output eDP-1 DP-1 DP-2 DP-3 DP-4 DP-5 DP-6 DP-7 DP-8
```

Overall, moving from latptop only to docker + 1 monitor  or docker + 2 monitors is working nicely.

Of course, considering I know the brands/IDs of the monitors I'm used to use and the "order" they are attached to the notebook (which port).

**Comment by bbbart** [comment]
I'd just like to chime in here. I came from `herbstluftwm` and like the way tags are implemented there (similar to how `qtile` does it). To get to something similar, I created a helper script as such:
    
    #!/usr/bin/env sh
    
    # script to mimic herbstluftwm's `swap_monitor_to_get_workspace` feature
    
    PREV_FOCUS_CACHE_FILE="${HOME}/.cache/.prev_focused_workspace"
    
    if [ $# -eq 0 ]; then
        if [ ! -f ${PREV_FOCUS_CACHE_FILE} ]; then
            exit "don't forget to give me a workspace to work with"
        else
            # this is the workspace we want to get onto our focused screen
            WORKSPACE_TO=$(cat ${PREV_FOCUS_CACHE_FILE})
        fi
    else
        # this is the workspace we want to get onto our focused screen
        WORKSPACE_TO=$1
    fi
    
    SWAY_OUTPUTS=$(swaymsg -t get_outputs)
    
    # this is our currently focused screen
    OUTPUT_TO=$(echo ${SWAY_OUTPUTS} |
        jq --raw-output '.[] | select(.focused) | .name')
    
    # this is the screen where our wanted workspace currently is visible (can be empty)
    OUTPUT_FROM=$(
        echo ${SWAY_OUTPUTS} |
            jq --raw-output\
        ".[] | select(.current_workspace==\"${WORKSPACE_TO}\") | .name"
    )
    
    if [ -n ${OUTPUT_FROM} ]; then
        # this is our currently focused workspace
        WORKSPACE_FROM=$(echo ${SWAY_OUTPUTS} |
            jq --raw-output\
            ".[] | select(.name==\"${OUTPUT_TO}\") | .current_workspace")
    
        swayws move "${WORKSPACE_FROM}" "${OUTPUT_FROM}"
    fi
    
    swayws move "${WORKSPACE_TO}" "${OUTPUT_TO}"
    swayws focus "${WORKSPACE_TO}"
    
    echo ${WORKSPACE_FROM} >${PREV_FOCUS_CACHE_FILE}

and then bound this in the sway config:

    bindsym {
        $mod+a exec ~/bin/swap_monitor_to_get_workspace.sh mail
        $mod+s exec ~/bin/swap_monitor_to_get_workspace.sh web
        $mod+d exec ~/bin/swap_monitor_to_get_workspace.sh chat
        $mod+f exec ~/bin/swap_monitor_to_get_workspace.sh adm
        $mod+u exec ~/bin/swap_monitor_to_get_workspace.sh u
        $mod+i exec ~/bin/swap_monitor_to_get_workspace.sh i
        $mod+o exec ~/bin/swap_monitor_to_get_workspace.sh o
        $mod+p exec ~/bin/swap_monitor_to_get_workspace.sh mus
        $mod+Tab exec ~/bin/swap_monitor_to_get_workspace.sh
    }

My only complaint is that it seems to work rather sluggish. :-(

As you can see, I used https://github.com/hw0lff/swayws for this. If anyone knows a way of implementing this avoiding an external tool, I'd be happy to learn.

Just my two cents!

**Comment by jabuxas** [comment]
ty @dedsm for the script. im really in love with xmonad and that just made my transition more possible

**Comment by mildred** [comment]
I'm trying to implement it via an external script but I have some issues with it:

https://gist.github.com/mildred/8c6983295fe5ff8522028e7a2c7c7a0b

**Comment by Hyask** [comment]
You can do this with [`swaysome focus-all-outputs <workspace_number>`](https://gitlab.com/hyask/swaysome#exhaustive-swaysome-commands-list). Hope this helps :-)

**Comment by cRaZy-bisCuiT** [comment]
Is there a way in plain sway to set an variable only if it is not null? E.g. something like:
set $display_left "Dell 1 SomeSerial", "HP 1 SomeSerial"
set $display_right "Dell 2 SomeSerial", "HP 2 SomeSerial"

I did not get his working until now but I'm nore sure if this is supported and if the syntax would work. Because if that would work, you wouldn't even need kanshi for multi monitor setups.
