### ISSUE TITLE
[workspace="__focused__"] evaluates focused workspace as regex

### ISSUE THREAD

**Issue by mynameisflorian** [swaywm/sway#4773]
Summary: `[workspace="__focused__"]` evaluates focused workspace as regex
Sway Version: 1.2

1) Open test app. I'm using gnome-calculator for this.

2) Create workspace:
`swaymsg -- 'workspace ".*"'`

3) On the new workspace, open a new terminal and:
`swaymsg -- '[app_id="gnome-calculator" workspace="__focused__"] focus'`
It shouldn't switch to the other workspace, but does

Renaming the workspace solves the problem:
```
swaymsg -- 'rename workspace to meow'
swaymsg -- '[app_id="gnome-calculator" workspace="__focused__"] focus'
```
With the above commands, launching a calculator in the new workspace focuses it as expected

Same behavior in all 3 cases:
```
swaymsg -- [app_id='gnome-calculator' workspace="__focused__"] focus
swaymsg -- [app_id="gnome-calculator" workspace="__focused__"] focus
swaymsg -- '[app_id="gnome-calculator" workspace="__focused__"] focus'
```

Also ran the following to verify bash wasn't doing anything funky here
`(set +x; swaymsg -- ...)`

One final note:
`workspace="\Q.*\E"`
will focus correctly, but
`workspace="\Q__focused__\E"`
does not match anything.

**Comment by progandy** [comment]
Duplicate  of #4586
Fixed in #4627
