### ISSUE TITLE
Input 'type:' settings not applied on reload

### ISSUE THREAD

**Issue by RPigott** [swaywm/sway#4780]
I have in my config a touchpad config like so:

    input type:touchpad {
        tap enabled
        pointer_accel 0.8
        dwt disabled
    }

When `reload`ing, these settings are reverted to their libinput defaults, and then when executing any `swaymsg input type:touchpad ...` command they are restored as written in the config (with whatever config just applied by swaymsg, of course).

Observed on `sway version 1.2-ad189d27 (Dec  3 2019, branch 'master')`
Appears to be caused by 1a579780. Previous commit does _not_ share the erroneous behavior.

**Comment by RedSoxFan** [comment]
I can replicate, but only with input type configs. Using identifiers and wildcard works fine. I can dig deeper into this tonight (if still open)
