### ISSUE TITLE
swaybar has a large impact on power drain / battery life

### ISSUE THREAD

**Issue by hedgepigdaniel** [swaywm/sway#4784]
- Sway Version: 1.2
- Arch Linux
- kernel 5.4.1
- Dell XPS 15 9560
- No external devices connected, TLP enabled 

My system's power consumption is increased by a large amount (about 7W) when a status command is used for swaybar. This surprises me, since all it is doing is displaying the current time.

### CPU package idle proportion
![image](https://user-images.githubusercontent.com/1217649/70151059-27e4d080-16ff-11ea-8c97-69add87612f9.png)

### Power usage
![image](https://user-images.githubusercontent.com/1217649/70151224-64b0c780-16ff-11ea-8c79-b4e0c0aa4e91.png)

### Configuration
```
bar {
  # Note the absence of `status_command`
}
```

### CPU package idle proportion
![image](https://user-images.githubusercontent.com/1217649/70151098-37fcb000-16ff-11ea-8f22-0b1f2f7938a5.png)

### Power usage
![image](https://user-images.githubusercontent.com/1217649/70151204-582c6f00-16ff-11ea-9a8b-4001c5f74c95.png)

### Configuration
```
bar {
  # Note I took the seconds out to avoid frequent screen updates, and updates only every 10 seconds
  status_command while date +'%Y-%m-%d %l:%M %p'; do sleep 10; done
}
```

**Comment by hedgepigdaniel** [comment]
Just did some more tests, with the refresh interval `sleep <n>` at different values

status_command | Package C8 percentage | Power consumption
--- | --- | ---
not set | 78.4% | 6.10W
`while date +'%Y-%m-%d %l:%M %p'; do sleep 10; done` | 52.3% | 12.0W
`while date +'%Y-%m-%d %l:%M %p'; do sleep 60; done` | 72.8% | 5.92W

So it does seem like the frequency of updates is important - but its still surprising to me that one update every 10 seconds has such a disastrous impact.

**Comment by ddevault** [comment]
Patches welcome for changing the default interval.

**Comment by Vorsplummi** [comment]
I'm using i3status as a status command and I didn't see any meaningful differences between i3status (5s interval), no status command and no bar at all. My testing wasn't really in-depth, I just kept eye on what powertop reported.

**Comment by schauveau** [comment]
The problem may not be related to sway at all. Remember that in shell commands, **date** and **sleep** are external programs so you are actually launching 2 new processes every 10s. From the Linux kernel point of view that could be enough activity to prevent putting the cpus in power saving modes.

**Comment by hedgepigdaniel** [comment]
With Sway 1.4 and an i7-8750H (Instead of an i7-7700HQ), the difference is much smaller.

Closing because its not clear that this is an issue with sway.
