### ISSUE TITLE
sway freezes if dis/connecting HDMI

### ISSUE THREAD

**Issue by shumvgolove** [swaywm/sway#4787]
`Alpine Linux, x86_64` 
`sway version 1.2-939c7b2d (Nov 23 2019, branch 'master')`

Disconnecting and then connecting HDMI freezes sway:

1. `HDMI monitor` starts with black screen and cursor visible, but system unresponsive.
2. After quite some time my `VGA monitor` reloads with default (grey) background (HDMI is still with black screen and cursor) and I can actually execute `alacritty` and exit the `sway` session.
3. Unfortunately, HDMI monitor stays black and isn't showing TTY, so I have to manually restart my system.

Debug log: [sway.log](https://github.com/swaywm/sway/files/3927175/sway.log)

**Comment by emersion** [comment]
Happens with amdgpu as primary GPU (card0) and i915 (card1) as secondary. HMDI wired to card0, VGA wired to card1.

```
2019-12-05 16:51:18 - [backend/drm/atomic.c:56] HDMI-A-1: Atomic commit failed (pageflip): Resource busy
```

**Comment by shumvgolove** [comment]
With new release of Alpine Linux, Linux kernel was updated to `5.4.5` and after dis/connecting HDMI screen returns to normal state (e.g. background, bar, etc.)!

However, HDMI monitor doesn't render my cursor, but VGA does. To overcome this, I spawn `Alacritty` in VGA screen and then HDMI monitor correctly renders my cursor.

Do I need to close this issue and open a new one?

**Comment by emersion** [comment]
Please open a new one
