### ISSUE TITLE
[sway 1.2] crash in wl_list_remove when shutting down with missing xwayland

### ISSUE THREAD

**Issue by yorickvP** [swaywm/sway#4804]
* Sway Version: 1.2

* Steps to reproduce:
1. start sway
2. try to run `vim` in xfce4-terminal (0.8.8)
3. `i3-msg exit`

* Debug Log: https://pub.yori.cc/xwayland_crash.log

You should try to reproduce the issue with the default configuration. If you cannot, please reproduce with a minimal configuration, upload the config to a pastebin service, and link to it below.

* Configuration File: missing

* Stack Trace, if sway crashes:
```
                Stack trace of thread 2771:
                #0  0x00007fa1537fc1d7 wl_list_remove (libwayland-server.so.0 + 0xd1d7)
                #1  0x00007fa1537f7ccd n/a (libwayland-server.so.0 + 0x8ccd)
                #2  0x00007fa1537f7ed1 wl_client_destroy (libwayland-server.so.0 + 0x8ed1)
                #3  0x00007fa15376a464 n/a (libwlroots.so.3 + 0x28464)
                #4  0x00007fa15376b01f wlr_xwayland_destroy (libwlroots.so.3 + 0x2901f)
                #5  0x0000561de469c831 n/a (sway + 0x10831)
                #6  0x0000561de469a406 n/a (sway + 0xe406)
                #7  0x00007fa153dfb153 __libc_start_main (libc.so.6 + 0x27153)
                #8  0x0000561de469a8be n/a (sway + 0xe8be)

                Stack trace of thread 2773:
                #0  0x00007fa1536b4c45 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfc45)
                #1  0x00007fa14cb0460c n/a (i965_dri.so + 0x4e060c)
                #2  0x00007fa14cb04208 n/a (i965_dri.so + 0x4e0208)
                #3  0x00007fa1536ae4cf start_thread (libpthread.so.0 + 0x94cf)
                #4  0x00007fa153ed32d3 __clone (libc.so.6 + 0xff2d3)
```

**Comment by Xyene** [comment]
Hi, is this still reproducible with the latest sway/wlroots master? If so, please obtain a stack trace with debug symbols (you'll need to [compile from source](https://github.com/swaywm/sway/wiki/Development-Setup#compiling-as-a-subproject), then `coredumpctl gdb sway`, `bt full` after the crash).

**Comment by Xyene** [comment]
Going to close this issue due to inactivity; if you find the issue persists on latest sway/wlroots master, please open a new ticket with debug symbols.
