### ISSUE TITLE
localebus support?

### ISSUE THREAD

**Issue by I60R** [swaywm/sway#4810]
I want to to display current keyboard layout on status bar and it's possible by continuously polling `swaymsg -t get_inputs` and doing some text processing.

But [localed](https://www.freedesktop.org/wiki/Software/systemd/localed/) seems to be a much better way to handle that. 

What matters is that it's already supported by [i3-status-rust](https://github.com/greshake/i3status-rust/blob/master/blocks.md#keyboard-layout) (status command which I currently use) so configuration becomes pretty straightforward and users could benefit from that.

**Comment by RPigott** [comment]
Polling is not necessary. You can subscribe to the `input` ipc event which will indicate when xkb_layout has changed. Read about it in `man 7 sway-ipc`. You should be able to use that to display the active layout, e.g. `swaymsg -mt subscribe '["input"]' | jq -r .input.xkb_active_layout_name`.

**Comment by progandy** [comment]
```localed``` is only for the *system default* keymap. That is not the same as the one chosen by sway. You can use a script to initialize sway with the values from localed, though.
