### ISSUE TITLE
Input config merging is broken for repeat_delay

### ISSUE THREAD

**Issue by RPigott** [swaywm/sway#4811]
```
swaymsg -pt get_version
sway version 1.2-f9ce8749 (Dec 13 2019, branch 'master')
```
I have the following keyboard
```
Input device: AT Translated Set 2 keyboard
  Type: Keyboard
  Identifier: 1:1:AT_Translated_Set_2_keyboard
  Product ID: 1
  Vendor ID: 1
  Active Keyboard Layout: English (US)
  Libinput Send Events: enabled
```
and in my config I have the following section:
```
input type:keyboard {
    repeat_rate 25
    repeat_delay 200
}
```
The setting works, but it is fragile. It unexpectedly breaks in the following cases:

1. `swaymsg input 1:1:AT_Translated_Set_2_keyboard xkb_layout us`
  - This command _should_ have no effect, but instead repeat delay is reset to the default 600.
  - The repeat_delay can be corrected by a reload
  - Using `type:keyboard` doesn't reset repeat_delay, and in fact will restore the previously reset repeat_delay to the configured 200 ms.
2. Replace `type:keyboard` with an the identifier in the config, then `swaymsg reload`.
  - This _should_ have no effect, but instead the repeat delay is reset to the default 600. (Very surprising!)
  - Cannot be corrected by a reload.
  - Can be corrected by exiting and restarting sway.

I can't find a concise explanation for both (1) and (2), so I'm not sure how they're related.

**Comment by RedSoxFan** [comment]
1. #4138 should fix that issue
2. This one is an oversight in my keyboard group implementation. I'm working on a fix for it
