### ISSUE TITLE
max_render_time not respected in config file?

### ISSUE THREAD

**Issue by tokyovigilante** [swaywm/sway#4812]
sway version 1.2-82390697 (Dec 14 2019, branch 'master')

Setting `max_render_time` in my sway config results in a swaynag error "Unknown/invalid command 'max_render_time'" despite the fact that `max_render_time` is listed in the documentation as a configuration-file only command. I note that it is included in `commands.c` in the `command_handlers` struct rather than in the `config_handlers` struct.

If it is only meant to be used at runtime for specific apps it would be good to have this clarified.

**Comment by emersion** [comment]
Use `for_window <criteria> max_render_time <time>`. See the comment on top:

>The following commands cannot be used directly in the configuration file.
They are expected to be used with *bindsym* or at runtime through *swaymsg*(1).

**Comment by tokyovigilante** [comment]
Oh right, so it is, glossed right over it. Thanks!
