### ISSUE TITLE
[Feature Request]: Ability to use some other marker than class for workspace assignment

### ISSUE THREAD

**Issue by liljenstolpe** [swaywm/sway#4817]
* Sway Version:

1.2

* Debug Log:

N/A

* Configuration File:

N/A

There are a number of functions that I now access via web access (everything from mail to issue tracking).  I would like to sort those into different workspaces.  I do start them on chrome with separate windows, but there is no way (that I have found) to assign different classes to those windows.  It would be nice if there was a way to start multiple instances of an app (say chrome) and assign something to each one that would allow sway to sort them into separate workspaces.

**Comment by Emantor** [comment]
Apply marks to your chrome windows. Mark the window during startup, afterwards marks can be used as a criteria to move the window to a specific workspace. Or try to match your windows based on the title. See `man 5 sway` for more details. If chrome does not allow setting the `class`, which other marker do you propose to use for this?

**Comment by liljenstolpe** [comment]
I missed the mark command - thank you.
