### ISSUE TITLE
Mod4+Shift+Right not working

### ISSUE THREAD

**Issue by johrpan** [swaywm/sway#4818]
I run Sway 1.2 on Arch Linux. Everything seems to work as expected, except for the specific keybinding `Mod4+Shift+Right`. It's independent of the configuration (I used the default one), the keymap (default and german) and the command that is bound to it.

Debug log: https://gist.github.com/johrpan/b4edfecd2663a64cee1451ce2cbd1c0a

**Comment by RedSoxFan** [comment]
Can you please run `sudo libinput debug-events --show-keycodes`, press `Mod4+Shift+Right`, and post the output?

**Comment by johrpan** [comment]
It looks like it doesn't even appear.

```
-event4   KEYBOARD_KEY      +1.54s      KEY_LEFTMETA (125) pressed
 event4   KEYBOARD_KEY      +1.87s      KEY_LEFTSHIFT (42) pressed
 event4   KEYBOARD_KEY      +2.56s      KEY_LEFT (105) pressed
 event4   KEYBOARD_KEY      +2.61s      KEY_LEFT (105) released
 event4   KEYBOARD_KEY      +3.31s      KEY_LEFTSHIFT (42) released
 event4   KEYBOARD_KEY      +3.32s      KEY_LEFTMETA (125) released
 event4   KEYBOARD_KEY      +4.46s      KEY_LEFTMETA (125) pressed
 event4   KEYBOARD_KEY      +4.89s      KEY_LEFTSHIFT (42) pressed
 event4   KEYBOARD_KEY      +6.11s      KEY_LEFTSHIFT (42) released
 event4   KEYBOARD_KEY      +6.12s      KEY_LEFTMETA (125) released
 event4   KEYBOARD_KEY      +7.43s      KEY_LEFTCTRL (29) pressed
 event4   KEYBOARD_KEY      +7.64s      KEY_C (46) pressed
```

**Comment by johrpan** [comment]
Do you have a hint on how I could find out, what's the problem here?

**Comment by FreeFull** [comment]
My guess is that your keyboard only has 2-key rollover, so some combinations of 3 keys just won't work. You could buy a keyboard with better rollover (either 6 key rollover, or n key rollover).

**Comment by johrpan** [comment]
Thanks, your are right! I was proud of my ThinkPad's keyboard – until now... (It's a L380 Yoga, if somebody is interested)

**Comment by dinama** [comment]
Is there a solution to this problem? It started all of a sudden without any symptoms.
