### ISSUE TITLE
Sway bindswitch configuration issues: --reload not being obeyed

### ISSUE THREAD

**Issue by jwhett** [swaywm/sway#4820]
* Sway Version Info

I've included a bit more information as I think there is an interesting disparity between the version of the RPM and the version that sway is reporting. Maybe this is just a packaging error. I've redacted some of the redundant output.

```
~ $ rpm -qa sway
sway-1.1.1-2.fc31.x86_64
~ $  swaymsg -t get_version
sway version 1.0
~ $ sway -v
sway version 1.0
~ $ rpm -qi (rpm -qa sway)
Name        : sway
Version     : 1.1.1
Release     : 2.fc31
Build Date  : Sat 27 Jul 2019 06:43:54 AM EDT
```

* [Debug logs](https://gist.github.com/jwhett/69ceee8a0aa6179e768a9a34aebaa02c)
  - log 1 is `--reload` in position described in wiki and the [supercollider page](https://github.com/swaywm/sway/blob/ba8586e28269136a8c7278dc10ad6f712c693c2b/sway/sway.5.scd#L415): `bindswitch --reload lid:on output $laptop disable`
  - log 2 is `--reload` in position that seems to load properly, but does not obey the reload behavior: `bindswitch lid:on --reload output $laptop disable`

I'm unable to create a session that can replicate the scenario where loading a config with `--reload` still enables the laptop output. Is there a preferred way to have sway launch in debug upon login? If so, I can replicate this scenario.

* [Config](https://gist.github.com/jwhett/69ceee8a0aa6179e768a9a34aebaa02c) is also in the gist

* Stack trace: n/a

* Potentially related issues I found while investigating:
  - #4765 
  - #4354 
  - #4312 

I've not discovered these particular behaviors in previous issues. I understand that `--reload` is the option that I need in order to keep the laptop output disabled through configuration reloads.

---

**Scenario**: When attempting to implement _clamshell mode_ as described in the wiki, Sway encounters an error loading the config on reload: `'bindswitch --reload lid:on output $laptop disable': invalid bindswitch command (expected binding with the form <switch>:<state>)`. Removing the `--reload` flag or relocating the flag both resolve the first error reported by swaynag. In both cases, the behavior supported by `--reload` doesn't exist; expected only in the case of removing the flag entirely. The debug logs linked above include the error as described, then the successful load of the config with the flag relocated. I would like to provide the best debug for the case when the configuration loads, but is not obeyed, but I'm having trouble creating this scenario. If you have a preferred way to generate debug logs upon login, I can recreate the issue while manipulating the laptop lid. The `bindswitch` behavior otherwise works as expected.

Thank you,
Josh

**Comment by RedSoxFan** [comment]
The reload flag was not added to bindswitch until sway 1.2 (the latest release) so you would need a newer version of sway
