### ISSUE TITLE
Red frowny face for systray icon

### ISSUE THREAD

**Issue by tmccombs** [swaywm/sway#4825]
Otherwise, please include the following four components in your bug report: sway version, debug log, configuration (if applicable), and an explanation of steps taken to reproduce the issue. If sway crashes, also include a stack trace.

* Sway Version: 1.2

Obtain a debug log like so:

    sway -d 2> ~/sway.log

This will record information about sway's activity when it's running. Briefly reproduce your problem and exit sway.  When preparing a debug log, brevity is important - start up sway, do the minimum work necessary to reproduce the error, then close sway.

Upload the debug log to a pastebin service such as [gist.github.com](https://gist.github.com), and link to it below.

* Debug Log:
https://gist.github.com/tmccombs/ee17a563b1459477a39e1911092e6546

I think the most relevant part is this:
```
2019-12-19 01:01:04 - [swaybar/tray/item.c:127] :1.105/org/ayatana/NotificationItem/udiskie IconPixmap: No such property “IconPixmap”
2019-12-19 01:01:04 - [swaybar/tray/item.c:127] :1.105/org/ayatana/NotificationItem/udiskie AttentionIconPixmap: No such property “AttentionIconPixmap”
2019-12-19 01:01:04 - [swaybar/tray/item.c:127] :1.105/org/ayatana/NotificationItem/udiskie ItemIsMenu: No such property “ItemIsMenu”
```

* Configuration File: default

If I run `udiskie --appindicator -t` It starts udiskie and apparantly creates an applet in the tray using SNI. However, the icon is a red frowny face (see screenshot) and clicking on the icon does nothing.

![image](https://user-images.githubusercontent.com/2541726/71155814-ce4ecc80-21fb-11ea-89ce-26ace4eb39e1.png)

**Comment by tmccombs** [comment]
The absense of a context menu is probably because udiskie uses the canonical menu dbus interface (see https://github.com/swaywm/sway/issues/3799). 

It also looks like it is providing an IconName and IconThemePath instead of an IconPixmap.  I found source files in both gnome and kde, which say "names are preferred over pixmaps" (https://github.com/ubuntu/gnome-shell-extension-appindicator/blob/master/interfaces-xml/StatusNotifierItem.xml and https://github.com/ubuntu/gnome-shell-extension-appindicator/blob/master/interfaces-xml/StatusNotifierItem.xml)

**Comment by artizirk** [comment]
Icon not showing up problem could be fixed in sway 1.4

**Comment by ianyfan** [comment]
Is this still an issue?

**Comment by artizirk** [comment]
for me not since 1.4 update

**Comment by ianyfan** [comment]
What is the debug output? i.e. from `swaybar -d`

**Comment by Arnavion** [comment]
```
$ swaybar -b bar-0 -d

...

00:00:00.123 [swaybar/tray/host.c:24] Registering Status Notifier Item 'org.kde.StatusNotifierItem-3242-1/StatusNotifierItem'
00:00:00.126 [swaybar/tray/item.c:152] org.kde.StatusNotifierItem-3242-1/StatusNotifierItem IconThemePath = ''
00:00:00.126 [swaybar/tray/item.c:152] org.kde.StatusNotifierItem-3242-1/StatusNotifierItem Status = 'Active'
00:00:00.126 [swaybar/tray/item.c:152] org.kde.StatusNotifierItem-3242-1/StatusNotifierItem IconName = 'input-keyboard'
00:00:00.126 [swaybar/tray/item.c:121] org.kde.StatusNotifierItem-3242-1/StatusNotifierItem IconPixmap: No such property ('org.kde.StatusNotifierItem.IconPixmap')
00:00:00.126 [swaybar/tray/item.c:152] org.kde.StatusNotifierItem-3242-1/StatusNotifierItem AttentionIconName = ''
00:00:00.126 [swaybar/tray/item.c:121] org.kde.StatusNotifierItem-3242-1/StatusNotifierItem AttentionIconPixmap: No such property ('org.kde.StatusNotifierItem.AttentionIconPixmap')
00:00:00.126 [swaybar/tray/item.c:121] org.kde.StatusNotifierItem-3242-1/StatusNotifierItem ItemIsMenu: No such property ('org.kde.StatusNotifierItem.ItemIsMenu')
00:00:00.126 [swaybar/tray/item.c:152] org.kde.StatusNotifierItem-3242-1/StatusNotifierItem Menu = '/MenuBar'
```

**Comment by Arnavion** [comment]
Opened https://github.com/swaywm/sway/issues/5645 since emersion requested to not reuse this issue.
