### ISSUE TITLE
Display Corruption

### ISSUE THREAD

**Issue by rustysec** [swaywm/sway#4826]
* `sway version 1.2-aa8fe584 (Dec 18 2019, branch 'master')`
* `kernel: 5.4.5-arch1-1`
* `00:02.0 VGA compatible controller: Intel Corporation Iris Plus Graphics G7 (rev 07)`
* [sway debug log](https://gist.github.com/rustysec/f9a0033642d70e15c2b940351e772e98)

I am not quite sure if this is a `wlroots` or `sway` issue.

There are a couple of scenarios in which one or more of my displays experiences major display corruption in which the colors are all wrong and basically becomes unusable. Reloading the sway configuration doesn't fix the issue, I have to log out and back in. Interestingly, if I launch from TTY, logging out and back in doesn't fix the issue, apparently I have to use a display manager (tested with GDM and SDDM, ly does not fix the problem at log in).

Both of these cause the issue:

**Disconnecting Monitor (USB-C)**
- launch sway
- unplug a monitor
- plug it back it
- problem exists

**Switching to TTY**
- launch sway
- switch to TTY
- switch back to sway
- problem exists

UPDATE: also, screenshots taken with `grim` look fine, but the actual image on the monitor is not.

**Comment by rustysec** [comment]
Running the `gamma-control` example from `wlroots` also triggers this issue.

**Comment by emersion** [comment]
Hmm, maybe the default linear gamma LUT we apply in wlroots messes things up?

**Comment by rustysec** [comment]
Interesting, I'll get in and try to adjust it and see what happens.

**Comment by rustysec** [comment]
Well I tried changing "some things" in `wlroots`, but honestly I have zero confidence that I was even turning the right knobs. The fact that `grim` is able to pull a screenshot of the display that looks correct even while `sway` is distorted makes me think this is not a `wlroots` issue.

**Comment by emersion** [comment]
[Here](https://github.com/swaywm/wlroots/blob/fc6c0ca12e941d5d7d567834bff3ab7df9447001/backend/drm/drm.c#L465) we fill the default gamma LUT.

>Atomic commit failed (pageflip): Device or resource busy

Happens when you switch VTs. This is harmless, even if we should fix it so that the logs aren't polluted.

**Comment by cb22** [comment]
@rustysec I believe I've had the exact same thing happen - on what I believe is the same graphics hardware (XPS 7390 2-in-1 / i7 1065G7). 

Interestingly enough, when using redshift (the wlroots patched version), the problem disappears for me completely.

**Comment by rustysec** [comment]
all signs point to gamma being the issue. i actually started looking at this again last night, will post an update later when i have a chance to test my fixes.

**Comment by filips** [comment]
I am experiencing this issue with the same hardware (XPS 7390 2-in-1 / i7 1065G7) on a rather new version of sway (sway version 1.4-55016729 (Mar 14 2020, branch 'master')).

Interestingly, i have noted that the issue also affects TTY colors when having unplugged/replugged monitors in sway. Launching gnome or gdm fixes the issue temporarily for me, whereas a mere restart of sway will not.

**Comment by cjoshmartin** [comment]
I think I am having the same problem with my dell xps and when I change monitors (plug in/out or open/close laptop)

**Comment by kennylevinsen** [comment]
This particular problem is fixed and closed. Please open a new one for any issues you may have on the latest stable (1.6).
