### ISSUE TITLE
Error requires editing new_window pixel '7' to become default_border

### ISSUE THREAD

**Issue by poetician** [swaywm/sway#4827]
Hi,

sway version 4.17.1 (2019-08-30)

The error message at start up is in this section:

##########################################################
##########################################################

# default_border normal | none | pixel
default_border pixel 7
# default_floating_border normal | none| pixel
default_floating_border pixel 7

########### Border control ###########
# hide_edge_borders none|vertical|horizontal|both|smart
hide_edge_borders both
bindsym $mod+shift+b exec --no-startup-id i3-msg border toggle

########### changing border style ###########
bindsym $mod+t border normal
bindsym $mod+y border 1pixel
bindsym $mod+u border none

new_window pixel 7
# new_window normal
# new_window none

new_float pixel 7
# new_float normal
# new_float none

It asks to change new_window pixel 7 to default_border. The manual only goes so far. I'd like to know the consequences before trying that trick. :)

**Comment by RedSoxFan** [comment]
> It asks to change new_window pixel 7 to default_border. The manual only goes so far. I'd like to know the consequences before trying that trick. :)

`new_window` works exactly the same as `default_border`. It just got renamed to make it clearer what it does. This is mirrored from i3.

> `sway version 4.17.1 (2019-08-30)`.

That version matches the latest i3 release and is not a valid Sway version. The latest release of Sway is 1.2

--

Also, please only open issues for bugs or enhancements. Questions should be asked in the IRC channel.
