### ISSUE TITLE
closing nested sway window doesn't exit process

### ISSUE THREAD

**Issue by edrex** [swaywm/sway#4829]
When running a nested sway for testing, closing the window doesn't exit the process (exit does though). Closing window should be caught and trigger an exit I think?

**Comment by Emantor** [comment]
This is by design, since this uses the noop output. AFAIR new outputs can be created using IPC. Instead of closing the window you can exit via IPC with `swaymsg exit`.

**Comment by edrex** [comment]
@Emantor I was wondering if there were some dev reason to want to have the process survive closing the output window. makes sense, thanks for explaining.

**Comment by edrex** [comment]
just for completeness, `swaymsg create_output WL-2` to create additional outputs when using the wayland or x11 backends.
