### ISSUE TITLE
Resuming after suspend results in static on screen and unresponsive inputs

### ISSUE THREAD

**Issue by tmccombs** [swaywm/sway#4837]
After resuming from suspend, both my monitors were covered in static. I've seen similar effects after suspend for areas rendered by the GPU, but they typically recover on the next render. And in this case nothing seemed to happen on attempts to use the keyboard or mouse. Even attempting to switch to a different TTY did nothing. The only way I was able to recover was to reboot. I'm not 100% sure this is because of sway, but I haven't ever seen this happen in i3, and it seems to be related to the GPU, which makes me think sway might be involved somehow.  I am not using swaylock, or doing anything on suspend or resume with swayidle. 

* Sway Version: 1.2

* Debug Log:
I wasn't able to reproduce consistently so I don't have a sway log file however, I do see this in my journald logs:

```
Dec 25 01:47:19 tardis kernel: [drm:amdgpu_job_timedout [amdgpu]] *ERROR* ring sdma1 timeout, signaled seq=1216, emitted seq=1218
Dec 25 01:47:19 tardis kernel: [drm:amdgpu_job_timedout [amdgpu]] *ERROR* ring gfx timeout, signaled seq=201712, emitted seq=201713
Dec 25 01:47:19 tardis kernel: [drm:amdgpu_job_timedout [amdgpu]] *ERROR* Process information: process sway pid 750 thread sway:cs0 pid 764
Dec 25 01:47:19 tardis kernel: [drm:amdgpu_job_timedout [amdgpu]] *ERROR* Process information: process  pid 0 thread  pid 0
Dec 25 01:47:19 tardis kernel: [drm] GPU recovery disabled.
Dec 25 01:47:19 tardis kernel: [drm] GPU recovery disabled.Dec 25 01:47:23 tardis kernel: [drm] schedsdma0 is not ready, skipping
Dec 25 01:47:23 tardis kernel: amdgpu 0000:01:00.0: couldn't schedule ib on ring <sdma0>Dec 25 01:47:23 tardis kernel: [drm:amdgpu_job_run [amdgpu]] *ERROR* Error scheduling IBs (-22)Dec 25 01:47:23 tardis kernel: amdgpu 0000:01:00.0: couldn't schedule ib on ring <sdma0>
Dec 25 01:47:23 tardis kernel: [drm:amdgpu_job_run [amdgpu]] *ERROR* Error scheduling IBs (-22)
Dec 25 01:47:23 tardis kernel: amdgpu 0000:01:00.0: couldn't schedule ib on ring <sdma0>
Dec 25 01:47:23 tardis kernel: [drm:amdgpu_job_run [amdgpu]] *ERROR* Error scheduling IBs (-22)
Dec 25 01:47:23 tardis kernel: amdgpu 0000:01:00.0: couldn't schedule ib on ring <sdma0>
Dec 25 01:47:23 tardis kernel: [drm:amdgpu_job_run [amdgpu]] *ERROR* Error scheduling IBs (-22)
```

**Comment by emersion** [comment]
Sounds like a driver issue.

**Comment by vvrein** [comment]
Do you use early KMS? 
This might happens when pc is hibernated (!), and then waked up, and there is `MODULES=(amdgpu)` in your mkinitcpio.conf.
You mention that pc was suspended, but suspend-then-hibernate feature might be used instead, especially if you use some DE. 

Try to run as root `sleep 2 && systemctl suspend`  and wake up pc several times.

**Comment by tmccombs** [comment]
I do have `MODULES=(amdgpu)` in my mkinitcpio.con config. However, I don't think that I woke from hibernation. I don't have a `resume=...` parameter in my kernel command line, and the power light for my computer was flashing, not off. But I could be wrong.

**Comment by vvrein** [comment]
>I don't have a resume=... parameter in my kernel command line

Got it, you are right, pc was suspended, and if so - most likely this is driver issue
You could try to disable [DPM](https://wiki.archlinux.org/index.php/ATI#Dynamic_power_management) or switch to [linux-next](https://wiki.archlinux.org/index.php/Kernel#kernel.org_kernels)
(I suppose your system is Arch)

**Comment by vvrein** [comment]
@tmccombs do you still have this issue?

**Comment by tmccombs** [comment]
No, I do not.
