### ISSUE TITLE
Proprietary drivers detection is too strict

### ISSUE THREAD

**Issue by gnidorah** [swaywm/sway#4838]
In case of https://wiki.archlinux.org/index.php/PRIME setup on laptop Sway runs on Intel card but since it detects proprietary graphics modules loaded for second card, it refuses to start without special flag.

Is it possible to make detection more correct? I.e. only trigger when Sway runs on device for which proprietary drivers are used.

**Comment by emersion** [comment]
See https://github.com/swaywm/sway/pull/2896
