### ISSUE TITLE
ibus+Mozc setup

### ISSUE THREAD

**Issue by AdrienLemaire** [swaywm/sway#4841]
Related issues: #873, #1225

I tried setting up mozc with ibus, but similarly to this [HN comment](https://news.ycombinator.com/item?id=19360595), once the setup completed (with ibus' property panel always visible and ibus engine reporting mozc-jp), the prediction box doesn't show up and only alphabet letters are being typed.

I would have given up if it wasn't for one of the replies:
>  89nn 9 months ago
> FYI I've been using ibus+anthy on sway for a while now, however recently switched to ibus+mozc because the prediction box in anthy started acting up/disappearing. Mozc seems to be working great so far (and actually what I wanted to use in the first place, but I believe I might have had the same issue you experienced)

This seems to confirm that ibus+mozc on sway is possible.

Anyone can share a working configuration?

```
local/ibus 1.5.21-3
    Next Generation Input Bus for Linux
local/ibus-mozc-ut2 2.23.2815.102.20171008-3 (mozc-im)
    IBus engine module for Mozc
local/libibus 1.5.21-3
    IBus support library
local/mozc-ut2 2.23.2815.102.20171008-3 (mozc-im)
    Mozc the Japanese Input Method with Mozc UT2 Dictionary
```

.local/bin/ibus-toggle
```py
#!/usr/bin/env bash
engine=$(ibus engine)
if [ "${engine}" == "mozc-jp" ] || [ "${engine}" == "xkb:jp::jpn" ]
then
    ibus engine xkb:us::eng
else
    ibus engine mozc-jp
fi
setxkbmap -option caps:escape
```

.config/sway/config
```
# toggle input
bindsym $mod+i exec /home/dori/.local/bin/ibus-toggle

# japanese input
exec ibus-daemon -drx --panel /usr/lib/ibus/ibus-ui-gtk3
```

/usr/share/gdm/env.d/sway.env
```
# For japanese input with ibus & mozc
GTK_IM_MODULE=ibus
XMODIFIERS=@im=ibus
QT_IM_MODULE=ibus
```

commands I've found useful:
* mozc conf: `/usr/lib/mozc/mozc_tool --mod=config_dialog`
* ibus conf: `ibus-setup`
* switch ibus: $mod+i
* check env vars: `env | grep -E 'XMOD|_IM'`
* ibus cli: `ibus --help`
```

**Comment by AdrienLemaire** [comment]
hmmm ... actually, I have the exact same issue with Anthy.

```
$ pacman -S ibus-anthy
$ ibus restart
$ ibus setup  # and add anthy to input method
$ ibus engine anthy
```
The anthy panel shows up, and even if selecting Hiragana mode, only alphabet will be displayed.

Wondering how to debug and fix that issue. It can't be that all the apps I've tried input text into are not supporting ibus without more configuratino (tried chromium-ozone, alacritty, termite), is it?

**Comment by ammgws** [comment]
Using ibus+mozc

kitty: doesn't work, though I have a feeling it did at one stage?
chrome (google): works

**Comment by AdrienLemaire** [comment]
I switched to firefox, but realized (thanks xeyes) that both firefox-developer-edition (expected) and firefox-wayland-hg (unexpected) run under xwayland.
firefox supports mozc input （やった）.

Saying thing because I'm thinking mozc issues are related to wayland apps only, and not xwayland ones.
This can be verified with Anki:

* xwayland : mozc works fine in Anki input fields
* pacman -S qt5-wayland
* restart Anki, it'll auto-run on wayland and mozc doesn't work anymore.

**Comment by AdrienLemaire** [comment]
Confirmed with Alacritty


![image](https://user-images.githubusercontent.com/260983/71966484-08cce780-3245-11ea-9e10-f196d0ab1b02.png)

Apps must run with xwayland for mozc to works properly

**Comment by ammgws** [comment]
I'm running firefox (nightly) natively and 日本語OK

**Comment by AdrienLemaire** [comment]
@ammgws oh... Then I don't know why these problems occur.
Related issue tracked on Alacritty: https://github.com/jwilm/alacritty/issues/2734

Should we re-open this ticket? I'm afraid sway has nothing to do with this issue ^^'

**Comment by ammgws** [comment]
You can try running a different Wayland compositor (non-wlroots based one would be better I guess?) and seeing if it works there to be sure.

**Comment by AdrienLemaire** [comment]
@ammgws I think I figured out the reason (but not the fix yet)

```console
			$ ps auxw|grep ibus
			dori         996  0.1  0.0 308164  5804 ?        Ssl  20:57   0:01 ibus-daemon -drx --panel /usr/lib/ibus/ibus-ui-gtk3
			dori        10```
09  0.0  0.0 233468  5904 ?        Sl   20:57   0:00 /usr/lib/ibus/ibus-dconf
			dori        1014  0.0  0.1 585480 38828 ?        Sl   20:57   0:00 /usr/lib/ibus/ibus-ui-gtk3
			dori        1018  0.0  0.0 338712 24540 ?        Sl   20:57   0:00 /usr/lib/ibus/ibus-extension-gtk3
			dori        1026  0.0  0.0 501888 23824 ?        Sl   20:57   0:00 /usr/lib/ibus/ibus-x11 --kill-daemon    # X11 ??? FIXME
			dori        1034  0.0  0.0 233448  5980 ?        Sl   20:57   0:00 /usr/lib/ibus/ibus-portal
			dori        1230  0.0  0.0 159784  5940 ?        Sl   20:57   0:00 /usr/lib/ibus/ibus-engine-simple
			dori        1966  0.0  0.0 161184  9448 ?        Sl   20:57   0:00 /usr/lib/ibus-mozc/ibus-engine-mozc --ibus
```

My sway config:
```
exec ibus-daemon -drx --panel /usr/lib/ibus/ibus-ui-gtk3
```

Somehow, ibus-daemon gets ibus-x11 to run instead of ibus-wayland.
To run ibus-wayland, I need some input_method 

```
$ /usr/lib/ibus/ibus-wayland
No input_method global
```

From [this comment](https://github.com/ibus/ibus/issues/1633#issuecomment-104877625), with weston we'd do:
```
[input-method]
path= /usr/lib/ibus/ibus-wayland
```

Now this becomes a request for sway to support this feature, which is a duplicate of  #873

**Comment by ammgws** [comment]
Perhaps this? https://github.com/swaywm/sway/issues/3407

**Comment by xdavidwu** [comment]
#4740 is for input-method-unstable-v2, but ibus needs input-method-unstable-v1.
