### ISSUE TITLE
Tap-and-drag is released by other inputs

### ISSUE THREAD

**Issue by Streetwalrus** [swaywm/sway#4842]
* Sway Version: 1.2, both wlroots 0.7.0 and 0.8.1
* Debug Log: https://wank.party/3X3T.log
* Configuration File: default + `input type:touchpad tap enabled`

Repro:
* Start sway
* Open terminal, run wev
* Start dragging with tap to drag, keep your finger on the touchpad
* Press any non-modifier key on the keyboard, or click the physical touchpad button
* Observe that before any other event fires, the left click is released

On X11, I could perform a two finger right click without releasing the drag, or simply continue dragging after physically clicking the touchpad.

Related issue: https://github.com/emersion/slurp/issues/46

**Comment by emersion** [comment]
Do you have DWT (disable while typing) enabled?

**Comment by Streetwalrus** [comment]
I haven't explicitly enabled it, will check.

**Comment by Streetwalrus** [comment]
Yeah turning off DWT fixes it. It looks like sway and xf86-input-libinput both use `libinput_device_config_dwt_get_default_enabled`,  but I've never had this problem on xorg. Weird.
