### ISSUE TITLE
Unintended consequences of nvidia hate

### ISSUE THREAD

**Issue by MadCamel** [swaywm/sway#4850]
I have a laptop with hybrid graphics. My nvidia GPU isn't even capable of being wired to a display. It's not being used for DRI. As far as I'm aware it's not being used for anything at all by sway. Yet I still have to promise not to buy an nvidia GPU in order to use sway.

All I want is the ability to use these nice GPU cores that came with my machine for tensorflow. Your blind hatred of nvidia has made this harder. The second I installed the drivers my window manager simply stopped working. I don't think this is a reasonable approach to take.

Perhaps it should only bail if the nvidia gpu is actually hooked to a display? Would a patch be welcome for this?

**Comment by ddevault** [comment]
Get off of our issue tracker, you know very well that your bug report is not welcome here.
