### ISSUE TITLE
panfrost on Pinebook Pro "Failed to open DRM device / Creating noop backend"

### ISSUE THREAD

**Issue by CameronNemo** [swaywm/sway#4861]
* Sway Version: 1.2
* Debug Log: http://ix.io/269G

Mesa 19.3.1 (with panfrost and kmsro drivers, wayland support), kernel from https://gitlab.manjaro.org/tsys/linux-pinebook-pro (5.4.0 with some patches).

**Comment by Emantor** [comment]
Please attach a debug log and your configuration file.

**Comment by ascent12** [comment]
>does currently not support `DRM_CLIENT_CAP_UNIVERSAL_PLANES`

Yeah, panfrost isn't even a modesetting driver. It's render only.
The "two GPUs" that the log talks about more than likely refers to the separate GPU and separate display controller.

Our code (or most wayland compositors, really) aren't currently geared to handling split render and display controller devices super well, and normally expect it to be abstracted away by the kernel and/or mesa. Improving multi-device stuff is something I've wanted to do for a long time.

**Comment by ddevault** [comment]
I have seen a computer running sway with the panfrost driver before. I think it's possible, but I don't know how.

**Comment by CameronNemo** [comment]
> Wayland is working just fine for me with Sway on Manjaro ARM's latest preview.
>Just spent a couple of hours setting it up, and the experience is very smooth, certainly much better than XFCE+X.org.
>No issues with the cursor or windows. 

https://forum.pine64.org/showthread.php?tid=8248&pid=52935#pid52935

I PM'd them asking for more details.

**Comment by CameronNemo** [comment]
>1969-12-31 16:00:47 - [wayland] unable to open lockfile /run/user/1000/wayland-0.lock check permissions

Is this something I should be concerned about (timestamp notwithstanding)?

**Comment by CameronNemo** [comment]
Looks like that lockfile was my issue. Sway seems to work just fine on the pinebook once I mounted /run correctly.
