### ISSUE TITLE
Sway crashes, possibly to do with marks

### ISSUE THREAD

**Issue by sseneca** [swaywm/sway#4863]
* Sway Version:

sway version 1.2

* Debug Log:

[sway.log](https://gitlab.com/snippets/1926548)

* Configuration File:

[semi-minimal sway conf](https://gitlab.com/snippets/1926552)

Something to do with marks is making sway crash.

I'm moving from i3 to sway. I used to assign a firefox class (set with `firefox --class social` to $ws4 but that no longer works. I'm trying instead then to assign firefox a mark and then have anything with that mark go to $ws4, but even with the firefox line commented out, `assign [con_mark="social"]  $ws4` will crash sway.

Note that [this line](https://gitlab.com/snippets/1926552#L184) can be commented out and it'll still crash.

Sorry if I'm doing something obviously incorrect with marks, I've read & re-read the docs on it and still have next to no idea how they're meant to be used. That being said I've been told by others that the way I'm trying to use them right now is correct.

* Stack Trace, if sway crashes:

[stack trace](https://gitlab.com/snippets/1926549)

**Comment by RedSoxFan** [comment]
Your links are giving me 404 errors. Can you please update them?

**Comment by sseneca** [comment]
Oops, links should be fixed now

**Comment by RedSoxFan** [comment]
The stack trace doesn't contain any debugging symbols. Can you build sway (and wlroots) from source and provide a trace with symbols?

**Comment by sseneca** [comment]
I'm closing this because I don't have time to try it out and it doesn't look like anybody else is having this issue, will re-open if needed
