### ISSUE TITLE
switch border when toggling between tiling and floating

### ISSUE THREAD

**Issue by daenney** [swaywm/sway#4869]
sway version 1.2

I'm trying to express the following for an application:
* When it starts (I default to tiling), `border none`
* When a new floating window gets created, `border normal 2`
* When it switches from tiling floating, `border normal 2`
* When it switches from floating to tiling: `border none`

I can achieve the first 2 with this:

```
for_window [app_id="some_id"] {
  border none
}

for_window [app_id="some_id" floating] {
  border normal 2
}
```

What I can't seem to figure out, is the toggling part. When I toggle this app from tiling to floating, I expected the second rule to apply, and when toggling back the first, since it's no longer floating. This doesn't happen, which gives me the impression this only works for newly created windows?

If the `for_window` only applies to newly created windows, is there a different way to express the desired behaviour in Sway?

**Comment by daenney** [comment]
Taking another pass through the manpage, does indeed state this is for new views

> Criteria may be used with either the for_window or assign commands to specify operations to perform on new views.

**Comment by RedSoxFan** [comment]
For the third and fourth bullets, the following should work
```
bindsym $mod+Shift+space floating toggle; \
    [app_id="some_id" tiling con_id=__focused__] border none; \
    [app_id="some_id" floating con_id=__focused__] border normal 2
```

**Comment by RedSoxFan** [comment]
I'm going to close this since it is a question and not an issue. In the future, please ask questions in the IRC channel.

**Comment by savchenko** [comment]
Trying to accomplish the same and so far with the little success:

Using the following snippet to test:
```bash
bindsym $mod+Ctrl+f floating toggle; \
  [app_id="foot" tiling] client.unfocused #2b2e30 #2b2e30 #888888 #1d1f21 #fb9a00; \
  [app_id="foot" floating] client.unfocused #2b2e30 #2b2e30 #888888 #1d1f21 #2f40cb
```

![image](https://user-images.githubusercontent.com/300146/131252439-cf46ae0b-c5fc-4ed5-b465-c31b329d9250.png)

I am reading it like this:

> If window is toggled between the floating/tiling modes - set borders of the unfocused windows that are (floating|tiling) to the colour (#2f40cb|#fb9a00)

What happens in practise is that command sets `client.unfocused` on _all_ unfocused windows, irrespective of their `app_id` or tiling status.

What am I missing here?
