### ISSUE TITLE
xterm window slowly increases in size after switching to floating mode

### ISSUE THREAD

**Issue by parkerlreed** [swaywm/sway#487]
Arch x86
Asus EeePC 901
GMA 950

http://ix.io/o4V

https://goo.gl/photos/tqqCNpT6atS6s64p7

**Comment by parkerlreed** [comment]
It seems any window I make floating exhibits this behavior.

**Comment by progandy** [comment]
I can confirm that.

**Comment by mikkeloscar** [comment]
This must be a wlc issue as it also happens in the wlc example compositor.

I can also only trigger the issue with xterm.

**Comment by Cloudef** [comment]
Can you move this issue to wlc?

**Comment by parkerlreed** [comment]
I don't have that current setup anymore. @progandy @mikkeloscar Either of you still having the issue? I don't want to submit to the wlc bug tracker without being able to provide extra info.

**Comment by progandy** [comment]
I can still reproduce it with sway, but it has gotten a bit better. A floating xterm is still increasing in size. If I send it to the scratchpad, the size increases after I show it the first time. After I hide and show it again the size is fixed.
Currently I don't have orbment installed, so I cannot test that.

**Comment by Cloudef** [comment]
I can say that xterm works as expected in floating mode inside orbment (and maybe

**Comment by Cloudef** [comment]
(Wlc's example too)

**Comment by mikkeloscar** [comment]
It's related to how we handle geometry requests from wlc.

**Comment by parkerlreed** [comment]
Conformed still happening on latest git for me.

**Comment by SirCmpwn** [comment]
I'm closing issues that are resolved by the yet-unreleased sway 1.0.
