### ISSUE TITLE
Sway assigns sound-only HDMI output display capabilities and workspace

### ISSUE THREAD

**Issue by trobjo** [swaywm/sway#4873]
sway version 1.2-ed022615 (Dec 31 2019, branch 'master')

I have an HDMI cable connecting my computer to an audio system to deliver high quality sound. Sway thinks the connection is a monitor. This is the declared capabilities of the output:

```Output HDMI-A-2 'Unknown M51          0x00000000'
  Current mode: 720x400 @ 87.849998 Hz
  Position: 3840,0
  Scale factor: 1.000000
  Scale filter: nearest
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 4   
  Max render time: off
  Available modes:
    720x400 @ 70.082001 Hz
    720x400 @ 87.849998 Hz
    640x480 @ 59.939999 Hz
    640x480 @ 59.939999 Hz
    640x480 @ 60.000000 Hz
    640x480 @ 66.667000 Hz
    640x480 @ 72.808998 Hz
    640x480 @ 75.000000 Hz
    640x480 @ 85.008003 Hz
    720x480 @ 59.939999 Hz
    720x480 @ 59.939999 Hz
    720x480 @ 60.000000 Hz
    720x480 @ 60.000000 Hz
    720x576 @ 50.000000 Hz
    720x576 @ 50.000000 Hz
    720x576 @ 50.000000 Hz
    800x600 @ 56.250000 Hz
    800x600 @ 60.317001 Hz
    800x600 @ 72.188004 Hz
    800x600 @ 75.000000 Hz
    800x600 @ 85.060997 Hz
    832x624 @ 74.551003 Hz
    1024x768 @ 60.004002 Hz
    1024x768 @ 70.069000 Hz
    1024x768 @ 75.028999 Hz
    1024x768 @ 84.997002 Hz
    1280x720 @ 50.000000 Hz
    1280x720 @ 50.000000 Hz
    1280x720 @ 59.939999 Hz
    1280x720 @ 60.000000 Hz
    1280x720 @ 60.000000 Hz
    1280x720 @ 60.000000 Hz
    1152x864 @ 69.971001 Hz
    1152x864 @ 75.000000 Hz
    1280x800 @ 60.000000 Hz
    1280x960 @ 60.000000 Hz
    1440x900 @ 60.000000 Hz
    1280x1024 @ 75.025002 Hz
    1280x1024 @ 85.024002 Hz
    1680x1050 @ 60.000000 Hz
    1600x1200 @ 60.000000 Hz
    1920x1080 @ 29.969999 Hz
    1920x1080 @ 30.000000 Hz
    1920x1080 @ 59.939999 Hz
    1920x1080 @ 60.000000 Hz
    1920x1080 @ 60.000000 Hz

```

If I disable (or dpms off) the output I am unable to play sound through both PulseAudio and pure ALSA. That is therefore unfortunately not a workaround.

It would be nice if either the capabilities were detected correctly, or an option was added to Sway to only disable the display part of the output, thus retaining audio capabilities.

It is a bug because new surfaces might inadvertently get created there, unbeknownst to me.

**Comment by tobiasjakobi** [comment]
I doubt this is a problem with sway. AFAIK you cannot transfer audio only over a HDMI link, since the audio frames are transported in the video blanking interval. See also chapter 7.3.3 (Video Dependency) in the HDMI specs. If you disable video you also loose the bandwidth for audio.

**Comment by emersion** [comment]
We have no way to detect audio-only devices.

**Comment by trobjo** [comment]
Understandable.

As I am unable to write a pull request that deals with the issue (and would that even interest the Sway developers?) I here provide a workaround that eliminates the problem for me in case anybody in the future stumbles upon the same problem.

My sway config:

```
output DP-1 resolution 3840x2160@60Hz pos 0 0 scale 2
output DP-2 resolution 3840x2160@60Hz pos 1920 0 scale 2
output HDMI-A-2 resolution 640x480@60Hz pos 3840 0 scale 1

workspace 1 output DP-1
workspace 2 output DP-1
workspace 3 output DP-1
workspace 4 output DP-2
workspace 5 output DP-2
workspace 6 output DP-2
workspace "99999" output HDMI-A-2

for_window [workspace="^99999$"] move container to output DP-2; focus output DP-2
```

Now the

**Comment by mist** [comment]
As I stumbled upon the same problem: Thanks for your solution. I change it a bit, so it is more flexible and works better for me:

~~~
set $soundbar 'Samsung Electric Company SAMSUNG 0x00000001'
output $soundbar resolution 640x480@60Hz pos -10000 0
workspace "99999" output $soundbar
for_window [workspace="^99999$"] move container to output $monitor_center; focus output $monitor_center
~~~

The negative position results in the soundbar screen being left to everything else, which leads to dynamic screens to appear right to my other screens instead of to the right of the the soundbar.


Also I think sway could fix this problem by implementing a blank video stream without associating a workspace to the output. Detecting audio-only devices is not what I want, handling is what I need.
