### ISSUE TITLE
Mouse cursor sometimes not visible in fullscreen mpv

### ISSUE THREAD

**Issue by Limero** [swaywm/sway#4890]
Replicate by running: `mpv --fs --config=no --start=10% abc.mp4` on a video file
If mouse cursor is visible when moving it, press `q` and run same command again.

Bug occurs on both sway 1.2 and latest version from master (2020-01-06)
Bug does not occur on Gnome 3.34 on Wayland

mpv 0.31.0 on Arch Linux

**Comment by emersion** [comment]
Please post a `WAYLAND_DEBUG=1` log, alongside with your config file and a debug log.

**Comment by Limero** [comment]
WAYLAND_DEBUG log (open mpv, cursor hidden): https://gist.github.com/Limero/facbe5484f3a7a8f68cc6bfd362f1d4f

sway -d 2 log (open mpv, cursor visible, close, open again and it's hidden): https://gist.github.com/Limero/2bfb218efa9cec7f25d19455d18eae04

Config file is stock but with `exec_always alacritty` in top

**Comment by emersion** [comment]
Looking at the logs, mpv hides the cursors, then shows it and immediately hides it again. This is an mpv bug, please report this upstream.
