### ISSUE TITLE
Feature Request: Tint inactive window

### ISSUE THREAD

**Issue by mox-mox** [swaywm/sway#4891]
I have seen [this code] to make inactive windows transparent and [this proposal] to create user-defined shaders.
This got me thinking: Would it be possible to tint windows?
My use case would be to slightly tint all inactive windows to quickly allow me to see which window is currently focused.
Yes I know the borders can convey the same information, but removing them and just have the windows tinted would make sway even more awsome. 

[this code]:https://github.com/swaywm/sway/blob/master/contrib/inactive-windows-transparency.py
[this proposal]:https://github.com/swaywm/sway/issues/3652

**Comment by emersion** [comment]
You can already change the opacity of windows (see the script in `contrib/`).

Closing this issue since tinting requires user-defined shaders, already tracked in the issue you linked.

**Comment by pm0u** [comment]
Since contrib is now gone from this repo, is there a new recommended way to accomplish this?

**Comment by emersion** [comment]
contrib now lives here: https://github.com/OctopusET/sway-contrib
