### ISSUE TITLE
DRI2: failed to add configs

### ISSUE THREAD

**Issue by Synthetica9** [swaywm/sway#4898]
Sway version:

- master (https://github.com/swaywm/sway/commit/8b251f068f5eda3b933b6014683928aa2f9faeb8)
- 1.3-rc1
- 1.3-rc2

Issue description:

Sway immediately fails with this error message: https://gist.github.com/Synthetica9/91b341c0bdfd64f61a5362bc6555c9d4

Sway works fine on 1.2

Fails to start without any config as well.

cc @emersion

**Comment by Synthetica9** [comment]
(Related: https://github.com/NixOS/nixpkgs/pull/76787)

**Comment by primeos** [comment]
I can now confirm this problem on my old desktop setup (it doesn't affect my main test setup). I initially noticed this problem with cage: https://github.com/Hjdskes/cage/issues/107#issuecomment-573457694 but it affects sway as well. Therefore I assume that this is a wlroots bug (should we move this issue?).

My GPU: Radeon HD 6950 (`radeon` driver)
Error messages from cage: Included in this comment: https://github.com/Hjdskes/cage/issues/107#issuecomment-573457694
Error messages from sway: https://gist.github.com/primeos/2e4f52434fb2d832098dc272f955c60f

**Comment by emersion** [comment]
This looks like a Mesa bug.

**Comment by primeos** [comment]
@emersion, you're right, sorry. I just updated my system (was a bit outdated :o) and Sway 1.3-rc2 is working fine now with Mesa 19.3.1 (before the update Mesa 19.2.7 was installed).

@Synthetica9: Which Mesa version do you use? You can e.g. check with `ls -l /run/opengl-driver/lib/` on NixOS. Maybe a system update fixes your issues as well.

If not, the following might provide valuable debug information ([Source](https://www.mesa3d.org/envvars.html)):
```
export EGL_LOG_LEVEL=debug # IIRC this was most important
export LIBGL_DEBUG=verbose
export MESA_DEBUG=1
```

And in case nothing works it might be worth to try it with `LIBGL_ALWAYS_SOFTWARE=true`.

With the old Mesa version I was getting the following error messages (unfortunately the formatting of the "native format" seems to be broken, from other outputs these bytes should be formatted as hexadecimal numbers):
```
libEGL debug: No DRI config supports native format R8  
libEGL debug: No DRI config supports native format
libEGL debug: No DRI config supports native format ^G^P
libEGL debug: No DRI config supports native format
libEGL debug: No DRI config supports native format 

libEGL debug: No DRI config supports native format ^E
libEGL debug: No DRI config supports native format ^E
libEGL debug: No DRI config supports native format XR24
libEGL debug: No DRI config supports native format XR24
libEGL debug: No DRI config supports native format XR24
libEGL debug: No DRI config supports native format ^X
libEGL debug: No DRI config supports native format XB24
libEGL debug: No DRI config supports native format
libEGL debug: No DRI config supports native format ^D^P
2020-01-14 13:19:25 - [EGL] command: eglInitialize, error: 0x3001, message: "DRI2: failed to add configs"
libEGL debug: EGL user error 0x3001 (EGL_NOT_INITIALIZED) in eglInitialize: DRI2: failed to add configs

2020-01-14 13:19:25 - [EGL] command: eglInitialize, error: 0x3001, message: "eglInitialize"
libEGL debug: EGL user error 0x3001 (EGL_NOT_INITIALIZED) in eglInitialize
```

**Comment by Emantor** [comment]
According to the nixos/nipkg repo nixos is still on 19.2.7.

**Comment by ascent12** [comment]
This is definitely an issue with mesa or how it's configured on your system, or related things like the kernel. Nothing we can/did do affects what is supported here; all we've done is open the GPU and give it to GBM/EGL.

But it sounds like you've fixed it.

**Comment by Synthetica9** [comment]
> @Synthetica9: Which Mesa version do you use? You can e.g. check with ls -l /run/opengl-driver/lib/ on NixOS. Maybe a system update fixes your issues as well.

19.3.1, but still no luck

> And in case nothing works it might be worth to try it with LIBGL_ALWAYS_SOFTWARE=true.

Doesn't work either

**Comment by emersion** [comment]
Please report this to Mesa.
