### ISSUE TITLE
floating toggle on scratchpad descendent toggles scratch root container instead

### ISSUE THREAD

**Issue by edrex** [swaywm/sway#4900]
Something in the last week or so changed the behavior of `floating toggle` on a descendant of a scratchpad container.

- Old behavior: toggles float on the descendant
- New behavior: toggles float on the ancestor/scratch root (not sure what to call that container)

The old behavior seems semantically correct, and I had come to rely on it for moving windows out of scratch.

cc @RedSoxFan

**Comment by RedSoxFan** [comment]
The behavior on master is the same as it is in 1.2 (I haven't checked older releases), which is to toggle floating on the entire floating container

**Comment by edrex** [comment]
huh, you're right (tested 1.2 from dist packages). I swear it used to work differently..
