### ISSUE TITLE
[Feature Request] option to move to mouse without going off screen

### ISSUE THREAD

**Issue by tmccombs** [swaywm/sway#4906]
# Use case

I have some buttons on my status bar (using waybar) which have click handlers that launch applications that have small floating windows. For example, launching gsimplecal when I click on the date/time module. Currently they launch in the middle of the screen. Setting a specific x,y coordinate doesn't work for me, because I have two monitors with different resolutions. and my statusbar is on the bottom. using `for_window [app_id="gsimplecal"] move position mouse` results in the window being partially off-screen. 

# Suggestion

Add an option to the move command like `move --constrain position mouse` which moves the targeted window to the mouse, but if centering would result in the window being partially off screen (including hidden by a layer-shell such as the statusbar) it is adjusted to be fully visible. 

# Alternative

My use case would also be solved by having a way to move to a relative position other than "center". for example `move position bottom right`.

# Workaround

I think I could accomplish this by using `for_window [<match>] exec position-script` where position-script finds the window, computes the proper location and moves it there, but that is substantially more complicated than the above solutions. 

If one of these solutions is acceptable, I'd be happy to take a stab at implementing it.

p.s. is there a difference between cursor, mouse, and pointer in the move command?

**Comment by emersion** [comment]
Please open a feature request on the i3 bug tracker. If it gets accepted there, we'll consider implementing this feature.

**Comment by tmccombs** [comment]
So, I actually just tried `move position mouse` in i3, and it has the behavior described in my first suggestion (that is it takes the edges of the screen into account). So sway actually differs from i3 in it's behavior. Would that make this a bug?
