### ISSUE TITLE
Chrome (Xwayland) flickers when Netflix is open in another window

### ISSUE THREAD

**Issue by colemickens** [swaywm/sway#4907]
So, this is a weird one, and frankly might be hard to demonstrate over video capture, and I don't have a high-enough fidelity camera to try to take a in-person capture. I'm not even sure it's going to come through after YouTube gets done with it.

~~This only happens when the scale factor is integer and~~ It seems like it started around the GL_LINEAR change going in, though it's unrelated (it occurs at non-integer scales).

Note that the flickering:
- seems to only repro with Netflix (haven't had a chance to try other video)
- seems to be worse when there is more to render on the screen (and seems to trigger when I change tabs, or cause a big redraw maybe?)
- generally stops if the tab remains in focus, or I move the mouse around on it a bit, or sometimes even if I just use the keyboard to shift focus away from it

Chrome is my only XWayland client right now, so I don't have data for other XWayland clients. (VSCodium seems to be triggering some edge Intel GPU condition that keeps hanging anything graphical).

So... if you have a 4K monitor, load this video in 4K and go to 1:04-1:10, you should actually be able to see it relatively clearly. The effect is considerably more pronounced in person: https://www.youtube.com/watch?v=zUiAoL8LAt8&feature=youtu.be

**Comment by colemickens** [comment]
I really dropped the ball on editing that after realizing it wasn't related to scale factor. To repeat and be clear, this issue happens when the output scale factor is non-integer as well.

**Comment by colemickens** [comment]
Also, maybe this is just a Chrome issue? Doesn't repro with Hulu. And now that I've tried, I can't repro with Netflix again either (changed window dimensions, etc?).

Of course please close if you don't think its related or don't want to bother since its Xwayland.

**Comment by luispabon** [comment]
It's weird. I certainly don't see that behaviour on Chrome myself with netflix. What sort of flickering is it, is it going blurry / less blurry?

**Comment by phosit** [comment]
Im not sure if it is the same issue. I get "interframe compression artefacts" when i start iceweasel in Xwayland mode on Youtube in fullscren.
Since version 1:1.4-7 (last test 1:1.2-5)
Im using Parabola

**Comment by colemickens** [comment]
I'm pretty sure this was a dupe of #4798 which was fixed by #4903. The description is identical and I haven't noticed this... for about a month (coincidentally right around when I filed this).

**Comment by phosit** [comment]
Should'nt this be fixed in version 1.4.
I have a 1080p monitor.
