### ISSUE TITLE
Binary space partitioning layout?

### ISSUE THREAD

**Issue by harrisonthorne** [swaywm/sway#4909]
On @ddevault 's blog, there's a mention on binary spacing on sway:

> Automatic binary space partitioning layouts ala AwesomeWM

This is a feature I would absolutely love to see with Sway, but I can't find the configuration option anywhere. How does this work? Has it been abandoned? I would love to be able to use Sway with binary spacing.

**Comment by ddevault** [comment]
This was removed.

**Comment by harrisonthorne** [comment]
Bummer. What's the reason? Any chance it will be brought back?

**Comment by ddevault** [comment]
To simplify sway, keep it in line with i3 in spirit, and encourage people to work on alternatives to e.g. bspwm instead.

**Comment by haasn** [comment]
Any chance to get it back? Lack of good BSP layouting on wayland is probably the main reason I'm still using X at this point. (Plus all the other niceties afforded by xmonad)

It's easy to say "work on alternatives!" but perhaps given all the extra work that goes into a wayland compositor relative to an X window manager, I'm not sure we're seeing the progress that we'd need to be seeing, versus a feature that apparently already existed.

**Comment by emersion** [comment]
No, sorry, we won't add this back. Sway has chosen not to add more window management features than i3.

**Comment by johnae** [comment]
Hey @haasn - there are tools that would give you something a bit like what you're after. For example my own tool: https://github.com/johnae/persway

**Comment by jerbaroo** [comment]
> No, sorry, we won't add this back. Sway has chosen not to add more window management features than i3.

So we need to get it into i3 first ;)

**Comment by haasn** [comment]
Very late update, but seeing as this is still the top search result for 'sway binary space partitioning', I want to point out that https://github.com/hyprwm/Hyprland implements this perfectly.

It's not as nice a compositor as sway in other areas (general instability, low code quality, C++, questionable configuration syntax), but given that sway has committed to the gnome philosophy, it's the next best alternative we've got.
