### ISSUE TITLE
[Documentation] FAQ/README.md - can sway be started from oldschool init 3 and "startx", and if so, what would be the proper command to do so?

### ISSUE THREAD

**Issue by rubyFeedback** [swaywm/sway#4912]
Hey folks,

I manage an old slackware system, but I compiled LOTS of things from source. GCC version is 9.2.0 for example, xorg-server 1.20.7 and so forth.

I have had no real exposure to tiling WMs, only a little (tried it once or twice), and I just read about sway on old.reddit.com, from someone who was using it and giving it as example for testing/trying out wayland. So this was my use case.

Right now, though, I am not sure how to use/start it. The main readme says ... start from tty but ... I am not sure I am doing this, or know how to do it. Can I use it via "startx" instead, via a xinitrc file perhaps? I think this would be a useful entry to a FAQ, or to the main README (not sure if you want to have it on the main readme, which is why a FAQ may be more useful). Perhaps I am not the only one either. :)

**Comment by emersion** [comment]
There's a FAQ and a lot of other useful information on the [wiki](https://github.com/swaywm/sway/wiki). Feel free to edit it and improve it, btw. If you have questions, you can join the IRC channel and ask them there.
