### ISSUE TITLE
Input are not correctly forwarded to XWayland windows

### ISSUE THREAD

**Issue by Elyhaka** [swaywm/sway#4926]
Hello,

I'm currently testing the 1.3 version, and I have found a what I think could be a bug : When a popup is spawned by a `XWayland` window and I close it, Sway refocus the window that spawned the popup. Unfortunately, the keyboard is not sending any input to the window even if sway is marking this window as being currently focused.
I can reproduce this issue with several application on current release-candidate like `vscode` for instance.

Let me know if I can provide some details about this issue !

```
> swaymsg -t get_version
sway version 1.3-rc3
```

**Comment by emersion** [comment]
Your bug report is missing debug logs. Please add a link to the full debug log file.
Your bug report is missing your config file. Please add a link to it.

**Comment by emberfade** [comment]
I think I have the same issue.

* Sway Version:

sway version 1.4

# Debug Log:

[sway.log](https://0x0.st/isSK.log)

# Configuration File:

Default

# Reproduction:

What I did in the debug log:

* Open terminal (Super+Enter)
* `$ firefox`
* Open Bookmark Overview (Ctrl+Shift+O)
* Make sure mouse cursor is above the newly spawned window
* Close Bookmark Overview (Ctrl+W).
* No input is possible on Firefox until focus has been switched to another window.

# Additional Information:

This happened with other XWayland windows as well.

It is neccessary to move the mouse onto the new window. Otherwise the main window will take input as usual when the second window is closed.

**Comment by Elyhaka** [comment]
Hello, sorry for the late answer I was a bit short at the moment. I can confirm that what @emberfade is reporting is exactly the behavior I was first reporting.

**Comment by josefbachmann** [comment]
> I think I have the same issue.
> 
>     * Sway Version:
> 
> sway version 1.4

Same sway version, same problem. i can reproduce this as wel and came here for this.

**Comment by emberfade** [comment]
I've tried using git bisect for the first time. So my result may not be accurate.

I believe that the commit introducing the bug is not within sway but wlroots https://github.com/swaywm/wlroots/commit/c067fbc010da0eeb1364a391f13e9609b7fd0477

**Comment by kdryja** [comment]
Same issue here.

# Config and Debug
* [debug.log](https://gist.github.com/kdryja/fedbb797aef48f8fea12af50c1d94e09#file-debug-log)
* Reproducible with default config
# Repro
1. Start Sway
2. Open any XWayland app (tested on Google Chrome `Version 80.0.3987.78 (Official Build) beta (64-bit)` and IntelliJ)
3. (For Google Chrome) Open any contextual window, e.g. Ctrl+O
4. Close the contextual window by hitting ESC
5. Focus on main Chrome window is now lost and can only be reclaimed by switching to different workspace and then back (e.g. if chrome is on workspace 1, I have to run `$mod+2` then `$mod+1` to regain focus)
# Sway Version
`sway version 1.4`
`xorg-server-xwayland 1.20.7`
`wlroots-0.10.0`

**Comment by stlaz** [comment]
Seeing the same problem. I tried to `tail -f` on the debug log, but nothing seems to be logged (although eventually you get 
`2020-02-02 22:02:29 - [sway/input/cursor.c:730] denying request to set cursor from unfocused client`, not sure if it's related to it)

**Comment by Emantor** [comment]
Please test https://github.com/swaywm/wlroots/pull/2017, at least in my testing the chrome issue did not appear. I am currently on a train, so I can't realy test steam and other apps.

**Comment by m0ppers** [comment]
same here. sway 1.2, wlroots 0.8.1 working. sway 1.4/wlroots 0.10 is not. My steps to reproduce:

open hexchat, dismiss the "shall I join a channel" popup after connecting. Input focus goes away and need to switch back and forth between workspaces to make input work again.

The first problem I ever had with sway :D keep up the good work :)

**Comment by jbiel** [comment]
I'm on Arch with wlroots 0.10.0-2 and sway 1.4-7 and this happens to me maybe 1 out of 20 times when opening a new tab in Firefox (using X11Wayland for it because native Wayland support was terrible last time I tried it.) The Firefox window is focused (blue title bar) with the cursor flashing in the address bar, but won't accept input until I focus another window and switch back.

**Comment by jfchevrette** [comment]
Arch with sway 1.4 with wlroots 0.10.0-2, this happens to me a lot when using Visual Studio code as well as Firefox

**Comment by norpol** [comment]
Similar issue with Signal Desktop and attaching files, clicking onto my wallpaper and back into the main window of the application restores keyboard input focus for me.

**Comment by jubalh** [comment]
@norpol ??

**Comment by Ogromny** [comment]
Same issue with JetBrains >=2019.2.X IDE

**Comment by emersion** [comment]
Can you try https://github.com/swaywm/wlroots/pull/2035?

**Comment by p-e-w** [comment]
Is there going to be a patch release with this fix? This is a major regression from Sway 1.2, and makes many applications practically unusable, with no apparent workaround (other than downgrading Sway).

**Comment by emersion** [comment]
I'm thinking about it. We'll discuss with the other core contributors.

**Comment by abmantis** [comment]
Also, considering that wlroots requires Wayland 1.18, it is impossible to easily update on Ubuntu 19.04 (the latest), in order to get this fix.

**Comment by glyh** [comment]
I've encounter this in some DirectX games, is there some workaround or should it just work?

**Comment by ammgws** [comment]
Have you tried running the game via `gamescope`?
