### ISSUE TITLE
make a matrix server

### ISSUE THREAD

**Issue by unmellow** [swaywm/sway#4933]
I'd would love to be able to talk to the devs other sway users about sway and wayland on  [matrix](https://matrix.org/)

**Comment by RedSoxFan** [comment]
There are no plans to create a matrix server. However, we do have the IRC channel #sway on irc.freenode.net, which is accessible from matrix. Just please keep the message lengths short (splitting into multiple messages, if needed) since long messages will come across as links to view the message.

**Comment by unmellow** [comment]
thanks that is good enough for me
