### ISSUE TITLE
[Feature request] swaynag: option to display on top

### ISSUE THREAD

**Issue by PeterNerlich** [swaywm/sway#4939]
I think swaynag could use some argument that makes it display on top, showing regardless whether a window is fullscreen etc. Currently, when I have something fullscreen, I don't notice swaynag appearing.

    $ swaymsg -t get_version
    sway version 1.2

**Comment by distek** [comment]
To add on to this request; This would be a use case:
https://github.com/m00qek/swaynag-battery

**Comment by robsmith11** [comment]
Is there any workaround that can be used now?  I also use swaynag for low battery notifications, but have missed a few when using a fullscreen window, resulting in my laptop shutting off in the middle of my work.

I run this script in the background:
```
#!/bin/bash

while true; do
    sleep 61
    ct=`cat /sys/class/power_supply/BATT/charge_now`
    c0=`cat /sys/class/power_supply/BATT/charge_full`
    (( ct*1000 / c0 < 70 )) && swaynag -m 'low battery'
done
```

**Comment by PeterNerlich** [comment]
I have not found any yet.

**Comment by fluix-dev** [comment]
I believe the following should work, feel free to let me know if it does.

```diff
diff --git a/swaynag/swaynag.c b/swaynag/swaynag.c
index d9bec3687..c8d97fb09 100644
--- a/swaynag/swaynag.c
+++ b/swaynag/swaynag.c
@@ -474,7 +474,7 @@ void swaynag_setup(struct swaynag *swaynag) {
 	swaynag->layer_surface = zwlr_layer_shell_v1_get_layer_surface(
 			swaynag->layer_shell, swaynag->surface,
 			swaynag->output ? swaynag->output->wl_output : NULL,
-			ZWLR_LAYER_SHELL_V1_LAYER_TOP, "swaynag");
+			ZWLR_LAYER_SHELL_V1_LAYER_OVERLAY, "swaynag");
 	assert(swaynag->layer_surface);
 	zwlr_layer_surface_v1_add_listener(swaynag->layer_surface,
 			&layer_surface_listener, swaynag);
```
In the meantime, I'll work on an actual solution of using `--layer background|bottom|top|overlay` to select the layer shell layer.

**Comment by robsmith11** [comment]
> I believe the following should work, feel free to let me know if it does.

Thanks!  I finally got around to patching sway after losing my work one too many times after missing a low battery notification while fullscreen.  It now works perfectly.

**Comment by GrabbenD** [comment]
@Jamedjo Isn't `overlay` type supposed to spawn the bar _above_ existing windows _without_ modifying their size?

E.g. with below config
1. Config with syntax errors successfully spawns `swaynag` (warning) bar at bottom of my screen (as configured).
2. After correcting the syntax and issuing bindsym `reload` command, the bar leaves a big gap below my windows (until all windows are resized by Sway `1.9` on next mouse click event):

```yml
# ~/.config/sway/config

# Error messages
swaynag_command swaynag --type='warning' --layer='overlay' --edge='bottom' --button-dismiss='test'
```

![swaynag-3](https://github.com/swaywm/sway/assets/45666572/1e016dcb-c40a-4815-b5d1-6bb509e065d2)


_(For reference, `swaybar` is able to appear over existing windows without resizing them):_

```yml
bar {
    position top
    height 30
    mode hide
    modifier $mod
}
```
