### ISSUE TITLE
Multi-monitor setup fails for 3 monitors @ 2560x1440

### ISSUE THREAD

**Issue by hkupty** [swaywm/sway#4946]
* sway version: `sway version 1.4-5568f14e (Jan 24 2020, branch 'master')`
    * also happens on sway 1.2
* os: Arch Linux

I have a three-monitor setup at work and all of them allow up to 2560x1440 resolutions (laptop screen + two screens attached through dockstation).

The setup works if I set the external screens to a lower resolution (1920x1080), but if I keep them at maximum resolution, sway behaves weirdly alternating between setting the external screens up and then turning them off until eventually both screens are off and I can't get them to work unless I reboot the computer.

I don't know if relevant or not, but the first screen (at `pos 0 0`) rotated 90 degrees and the subsequent screens' positions mimic roughly their physical positions, so `pos 1080 640` and `pos 1080 1720`.

I suspect the issue with using their full resolution is that the resulting "canvas" is too big, maybe?

I can't reconfigure my setup to generate the logs now, but I'll do so as soon as possible and post the debug logs here.

Thanks in advance and let me know if there's any other relevant information in my setup I can provide.

**Comment by emersion** [comment]
Your bug report is missing debug logs. Please add a link to the full debug log file.

Your bug report is missing your config file. Please add a link to it.

**Comment by hkupty** [comment]
> Your bug report is missing your config file. Please add a link to it.
https://pastebin.com/A2NDGg23

Sorry about that. This is the most updated version of my config, which is pretty standard, that *works*.
If I swap `DP-7` and `DP-3` configs to `2560x1440`, it breaks the way I described above.

**Comment by hkupty** [comment]
Ok, something happened and I can't really understand what.
I was setting up to generate the logs and it no error occurred.
I believe it was troublesome before I got the resolutions and positions working correctly.

I'll close the issue now and if I run into problems again (i.e. on monday, plugging in this setup again), I'll reopen with relevant debug data.

**Comment by emersion** [comment]
Sometimes bad cables can result in black screens. Let us know if you can reproduce again.
