### ISSUE TITLE
Unable to start any application in sway 1.4 on FreeBSD

### ISSUE THREAD

**Issue by shamazmazum** [swaywm/sway#4950]
Hello. I use FreeBSD with sway 1.2 and wlroots 0.8.1 and all works just fine. Now, there are sway 1.4 and wlroots 0.10.0 in the ports collection, but sway 1.4 has the following bug. When I launch sway 1.4, it starts as always, but then I launch a terminal emulator (alacritty), and then another one. The first launches, but neither the second does launch, nor any other application. Sway debug output is as follows:

~~~~
2020-01-25 19:19:21 - [sway/commands/bind.c:610] running command for binding: exec alacritty
2020-01-25 19:19:21 - [sway/commands.c:255] Handling command 'exec alacritty'
2020-01-25 19:19:21 - [sway/commands/exec_always.c:46] Executing alacritty
2020-01-25 19:19:21 - [sway/commands/exec_always.c:87] Child process created with pid 13407
2020-01-25 19:19:21 - [sway/tree/root.c:290] Recording workspace for process 13407
2020-01-25 19:19:21 - [types/wlr_surface.c:607] New wlr_surface 0x80c528600 (res 0x80c292b80)
2020-01-25 19:19:21 - [types/wlr_relative_pointer_v1.c:146] relative_pointer_v1 0x80c32ea00 created for client 0x80cfb9dc0
2020-01-25 19:19:21 - [wayland] error in client communication
wl_display@1: error 2: no memory
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 12, kind: Other, message: "Cannot allocate memory" }', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
~~~~

The full log is [here](https://pastebin.com/MbZzskiu). Also there is another package in the system, called wayland, which provides `libwayland-server.so`, `libwayland-client.so` and other `libwayland-foo.so` libraries. Its version is 1.16.0 I use AMD Radeon RX500 series video card with Linux drivers working atop of Linux API glue (graphics/drm-kmod port).

I understand that there is no much info about this bug and it also can be too FreeBSD-specific, but I've decided to report here first. I also hope that there could be some FreeBSD users here too, who could help me in my situation ;)

**Comment by emersion** [comment]
Can you set `WAYLAND_DEBUG=client` before starting the client, and paste the output here?

**Comment by ammgws** [comment]
Out of interest, when that happens can you even talk to sway at all using swaymsg using the first terminal you opened?

**Comment by shamazmazum** [comment]
@emersion The updated log is [here](https://pastebin.com/MbZzskiu)
@ammgws Yes, I can.

BTW, can the most recent sway work with wlroots 0.8.1 and can the most recent wlroots work with sway 1.2? If yes, I could use `git bisect` command to determine what component and commit introduces the error.

**Comment by shamazmazum** [comment]
I was able to determine what lines of code cause this "no memory" message to be printed. It is in wlroots, in `wlroots/types/xdg_shell/wlr_xdg_shell.c`, function `xdg_shell_bind`:

~~~~
  struct wl_display *display = wl_client_get_display(client->client);
    struct wl_event_loop *loop = wl_display_get_event_loop(display);
    client->ping_timer = wl_event_loop_add_timer(loop,
        xdg_client_ping_timeout, client);
    if (client->ping_timer == NULL) {
        /* HERE "no memory" message is printed */
	wl_client_post_no_memory(client->client);
    }
}
~~~~

I checked with `git blame` and ensured myself, that these lines didn't change between wlroots 0.8.1 (where all is OK) and wlroots 0.9.0 (where sway 1.3-rc1 can open only one terminal emulator).

The only recent change in that file is commit [5cde359](https://github.com/swaywm/wlroots/commit/5cde35923cafe1630dc6b1113c593d2200a1e4b5). Just out of curiosity I compiled wlroots with this commit reverted, but sway only showed a grey screen and was useless, so no luck with this try.

I hope this information can help

**Comment by emersion** [comment]
Can you do this:

```
ls -l /proc/<sway PID>/fd
```

**Comment by shamazmazum** [comment]
Unfortunately, no, sorry :( FreeBSD's procfs doesn't have `/proc/foo/fd` directories, even the one provided by `linprocfs` module.  Instead of this I can provide [this list](https://pastebin.com/QyawZWCh) of open descriptors for sway generated by lsof.

Do you have any particular idea what's happening?

**Comment by shamazmazum** [comment]
Oh, I've got it. The problem is that all this wayland stuff is too linux-dependent, leaving us FreeBSD users a bit aside from the progress ;) And is it really a progress? ;)

I've found, that `wl_event_loop_add_timer()` function calls `timerfd_create()` system call. FreeBSD lacks both this call and `epoll` and has its own notification mechanism called `kqueue`. All `epoll` emulation is done in libraries provided by `devel/libepoll-shim` port. For example, this `timerfd_create()` system call is emulated using FreeBSD's [`timer_create()`](https://www.freebsd.org/cgi/man.cgi?query=timer_create&apropos=0&sektion=0&manpath=FreeBSD+12.1-RELEASE+and+Ports&arch=default&format=html) system call. 

Using dtrace, I found, that `timer_create()` system call fails with the error `EAGAIN`. A quotation from the manual:

~~~~~
[EAGAIN]           The calling process has already created all of the
                        timers it is allowed by this implementation.
~~~~~

So the cure is the following: either reduce the use of timers in sway (why it was OK in sway 1.2 after all?) or boost the limits of FreeBSD somehow.

**Comment by emersion** [comment]
Then I have good news: https://gitlab.freedesktop.org/wayland/wayland/merge_requests/45 should fix your issues. Can you try using libwayland's latest commit?

**Comment by shamazmazum** [comment]
The problem is fixed with the new wayland, but the CPU usage is now too high.

~~~~
 PID USERNAME    THR PRI NICE   SIZE    RES STATE    C   TIME    WCPU COMMAND
36083 vasily       23 103    0   197M   111M CPU5     5  17:56 100.00% sway
36108 vasily       19  20    0   198M    93M kqread  11   0:01   0.35% alacritty
36184 vasily       40  20    0  2609M   306M select   1   0:07   0.07% firefox
36095 vasily        1  20    0    28M    15M select  11   0:01   0.05% swaybar
68505 root          1  20    0    13M  3844K CPU10   10   0:00   0.03% top
36194 vasily       30  20    0    26G   232M select  11   0:03   0.02% firefox
36098 vasily        1  52    0    11M  3204K wait     6   0:00   0.01% sh
~~~~

**Comment by emersion** [comment]
Use something like `perf` to understand what's going on.

**Comment by shamazmazum** [comment]
I wish I could) Early there was nice `pmcstat` program for that. Nice profiler that tracked various CPU performance counters. But now (maybe because I've bought Ryzen or maybe it's a regression) it's useless.

But I have an idea what is happening. Earlier some system calls were blocking, but now they are not.

Look at this enormously high number of calls to `kevent()` (the measurements for about 10 seconds):
~~~~
firefox                                             kevent()                                                        507
  sway                                              kevent()                                                   10377444
~~~~

That's about one million calls per second! I don't know if you are able to help me, this is definitely fault of people who wrote `libepoll-shim` I think.

**Some speculations follow after this line, which can or cannot be true:**
[Vanga](https://en.wikipedia.org/wiki/Baba_Vanga) mode: I think, `kevent()` returns to often because you deleted the following:
~~~~
        struct wl_event_source_timer *timer_source =
		(struct wl_event_source_timer *) source;
	uint64_t expires;
	int len;

	len = read(source->fd, &expires, sizeof expires);
	if (!(len == -1 && errno == EAGAIN) && len != sizeof expires)
		/* Is there anything we can do here?  Will this ever happen? */
		wl_log("timerfd read error: %s\n", strerror(errno));
~~~~

`kevent()` can return to indicate that a timer event is pending and you must `read()` the event to "acknowledge" it in `kqueue` mechanism. Since there is no `read()` anymore, the event can remain "unacknowledged" making `kevent()` return so often.
Does it make sense? I will consult `kqueue` manual and `libepoll-shim` internals to tell you more.

**Comment by shamazmazum** [comment]
I fixed the problem bumping the amount of timers in the kernel and recompiling. Sway now works fine with wayland `1.16.0`. The reason of high CPU consumption in `1.17.91` remains unclear to me, but this is definitely not the problem of sway developers.

I think I'll close the issue and will notify the developer of `libepoll-shim` instead. Thanks for any help

**Comment by emersion** [comment]
I see. Please link the epoll-shim issue when you open it.

Wayland 1.18 will be released soon, so I'd be nice to figure out what's going on and fix the bug.

**Comment by shamazmazum** [comment]
OK. Unfortunately, I don't have much time, but if I find something, I'll let you know.
