### ISSUE TITLE
Unable to drop root

### ISSUE THREAD

**Issue by Hjdskes** [swaywm/sway#4951]
* Sway Version: sway version 1.4-5568f14e (Jan 25 2020, branch 'master')
* Debug Log: https://gist.github.com/Hjdskes/0774511043222e8aacc101020ef7712b
* Configuration File: none, not necessary to show the issue

When launching Sway as root, it is not able to drop permissions:

```
2020-01-25 22:54:24 - [sway/main.c:195] Unable to drop root (we shouldn't be able to restore it after setuid), refusing to start
```

This is on a systemd system. I'm launching Sway as root (not with sudo) from the source directory in which I cloned the repository, i.e. `./build/sway/sway -d`.

[Someone reported this issue for Cage](https://github.com/Hjdskes/cage/issues/112) and since Cage uses the same code as Sway, I reproduced this issue in Sway as well. I have yet to figure out why, but thought I'd let you know in case you find the issue faster than I do :) If I find it, I'll be sure to open a PR for Sway as well!

**Comment by ddevault** [comment]
This isn't a bug - you're not supposed to run sway as root.

**Comment by Hjdskes** [comment]
In that case, perhaps we should rephrase the error message which states "unable to drop root" ([1](https://github.com/swaywm/sway/blob/master/sway/main.c#L190), [2](https://github.com/swaywm/sway/blob/master/sway/main.c#L195)). Currently it is communicating that you can start as root but permissions would be dropped, at least to me.

I can open a simple PR that changes this to "unable to drop permissions" or something like that, what do you think?

**Comment by ddevault** [comment]
No, I think that error message is correct. The purpose of that code is, when the binary is setuid, to set the uid to the euid, effectively "dropping root".
