### ISSUE TITLE
Font size increases after a while

### ISSUE THREAD

**Issue by hjek** [swaywm/sway#4954]
Sorry, this is a terribly vague bug report as I haven't yet been able to figure out what's causing this otherwise persistent issue. :confused:

On a fresh login, after using Sway for some time (typically some hours) the font sizes in certain programs — xterm, Emacs (GTK+ version) and others — will increase to somewhere around 150% and stay at that size.

When the font size increases, I have to go edit the config for all those apps to shrink the font (to fit properly on the screen). :neutral_face: Next time I log in I have to edit the config to increase the font sizes (to make the text readable) until the seemingly random moment when the font size will increase again.

This issue happens only in Sway sessions, not in Gnome sessions.

### System info
```
$ swaymsg -t get_version
sway version 1.0
$ uname -a
Linux fedora 5.4.8-200.fc31.x86_64 #1 SMP Mon Jan 6 16:44:18 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Emantor** [comment]
this is https://github.com/swaywm/wlroots/issues/1119. You want https://github.com/swaywm/sway/issues/3499#issuecomment-456576277.

**Comment by hjek** [comment]
That's probably it. Thanks!
