### ISSUE TITLE
Scale factor defaults to 2.0 upon reload

### ISSUE THREAD

**Issue by kdryja** [swaywm/sway#4960]
Whenever I execute reload directive (e.g. via `$mod+Shift+c` from default config), the scaling of my screen gets bumped to 2.0 (from 1.0), even though nothing sets it explicitly in my config file.

Steps to repro:
1. Launch sway with default config from /etc/sway/config
2. Run the command:
```
$ swaymsg -t get_outputs
> Output eDP-1 'Unknown 0x0000 0x00000000' (focused)
  Current mode: 2560x1440 @ 59.998001 Hz
  Position: 0,0
  Scale factor: 1.000000
  Scale filter: nearest
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 3
  Max render time: off
  Available modes:
    2560x1440 @ 59.998001 Hz
```
3. Reload sway (e.g. using `$mod+Shift+c`)
4. Run the command:
```
$ swaymsg -t get_outputs
> Output eDP-1 'Unknown 0x0000 0x00000000' (focused)
  Current mode: 2560x1440 @ 59.998001 Hz
  Position: 0,0
  Scale factor: 2.000000
  Scale filter: nearest
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 3
  Max render time: off
  Available modes:
    2560x1440 @ 59.998001 Hz
```
5. Scale factor is now doubled

FWIW, I can work around this by putting `output eDP-1 scale 1` in my config file, thus forcing the scale to always be 1, but I'm pretty sure it wasn't necessary before. Is it intended?

* Sway Version:
```
$ swaymsg -t get_version
> sway version 1.4
```
* Debug Log: [sway.log](https://gist.github.com/kdryja/051b4d00a30af3c6bfba99ceaaf9673d#file-sway-log)
* Configuration File: Reproducible with the default config from /etc/sway/config Pasting just in case anyway: [config](https://gist.github.com/kdryja/051b4d00a30af3c6bfba99ceaaf9673d#file-config)

**Comment by emersion** [comment]
This log has been obtained with Sway running nested inside another Wayland compositor. Please provide a debug log with Sway started from a TTY.

**Comment by kdryja** [comment]
Apologies, see here:
[sway.log](https://gist.github.com/kdryja/051b4d00a30af3c6bfba99ceaaf9673d#file-sway-log-tty)

**Comment by emersion** [comment]
Seems like the output scale auto-detection isn't working as expected here.

```
2020-01-28 14:22:16 - [sway/desktop/output.c:871] New output 0x55a525b26b40: eDP-1
2020-01-28 14:22:16 - [sway/config/output.c:337] Turning on output eDP-1
2020-01-28 14:22:16 - [sway/config/output.c:357] Auto-detected output scale: 1.000000
[…]
2020-01-28 14:22:19 - [sway/config/output.c:262] Assigning configured mode to eDP-1
2020-01-28 14:22:19 - [sway/config/output.c:302] Output DPI: 209.754839x215.152941
2020-01-28 14:22:19 - [sway/config/output.c:357] Auto-detected output scale: 2.000000
```

**Comment by Emantor** [comment]
> Seems like the output scale auto-detection isn't working as expected here.
> 
> ```
> 2020-01-28 14:22:16 - [sway/desktop/output.c:871] New output 0x55a525b26b40: eDP-1
> 2020-01-28 14:22:16 - [sway/config/output.c:337] Turning on output eDP-1
> 2020-01-28 14:22:16 - [sway/config/output.c:357] Auto-detected output scale: 1.000000
> […]
> 2020-01-28 14:22:19 - [sway/config/output.c:262] Assigning configured mode to eDP-1
> 2020-01-28 14:22:19 - [sway/config/output.c:302] Output DPI: 209.754839x215.152941
> 2020-01-28 14:22:19 - [sway/config/output.c:357] Auto-detected output scale: 2.000000
> ```

`width` and `heigth` are set after the initial modeset, which means the auto-detection is short circuiting on start and returning the default `1`. On reload a mode is already set and auto-detection correctly calculates the high-dpi case.

**Comment by zikaeroh** [comment]
FWIW, this also seems to affect `dpms on`; I've been having issues with my `swayidle` setup where the scaling was changing on resume. I've found that I can just preemptively set my scale to 1 and future resumes won't have their scaling changed.

**Comment by Yaroslav-95** [comment]
I don't know if this issue I am having is related or not, but for some reason sway doesn't load the scale_filter option I've set in my config upon startup. It only loads it if I manually reload my config file after sway has already launched. 

This only has started happening since version 1.4, which is when I think you actually added the scale_filter option. Before that it already used smart or linear filtering by default, which in my case looks a bit better on non-wayland apps since I am using non-integer scaling due to my display's size and resolution.

**Comment by emersion** [comment]
Can you try this PR? https://github.com/swaywm/sway/pull/4998

**Comment by frzifus** [comment]
I am still running into this using sway `1.7`.
```
output eDP-1 {
   # ...config options...
   mode 1920x1080@60.049Hz
   bg /usr/share/backgrounds/default.png fill
   scale 1
}
```
The background gets applied, the scale not.
```
$ swaymsg -t get_outputs
Output eDP-1 'Unknown 0x403D 0x00000000' (focused)
  Current mode: 1920x1080 @ 60.049 Hz
  Position: 0,0
  Scale factor: 2.000000
  Scale filter: nearest
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 3: Term
  Max render time: off
  Adaptive sync: disabled
  Available modes:
    1920x1080 @ 60.049 Hz
```

**Comment by Emantor** [comment]
Please post a complete debug log and open a new issue.
