### ISSUE TITLE
failed to record screen by ffmpeg through kmsgrab device

### ISSUE THREAD

**Issue by chenjie199234** [swaywm/sway#4961]
![2020-01-30-02:27:00](https://user-images.githubusercontent.com/29348971/73385629-729e5580-4308-11ea-9a40-93787f2651d5.png)

**Comment by jbeich** [comment]
Restart as `env WLR_DRM_NO_MODIFIERS=1 sway`. See swaywm/wlroots@f0594fb73225

**Comment by emersion** [comment]
This is a ffmpeg bug. They should add support for modifiers (via the new `getfb2` ioctl).

**Comment by chenjie199234** [comment]
@jbeich @emersion 
doesn't work
![2020-01-30-16:43:49](https://user-images.githubusercontent.com/29348971/73433320-8507a600-437f-11ea-83ea-9cd3db9c2df2.png)

**Comment by emersion** [comment]
Report this to ffmpeg.

**Comment by chenjie199234** [comment]
@jbeich @emersion i don't known how to report to ffmpeg
ffmpeg's github repository can't report an issue

**Comment by emersion** [comment]
https://ffmpeg.org/bugreports.html

**Comment by chenjie199234** [comment]
@emersion @jbeich still can't work,help~~~
