### ISSUE TITLE
Enhancement: Emit Pointer Enter event when application starts

### ISSUE THREAD

**Issue by nifker** [swaywm/sway#4963]
Sway should emit a pointer enter event when the cursor was already on the surface before the application started, as it currently (sway 1.4-ffbf10d0) doesn't do it. Not sure if a debug log is senseful here.

**Comment by RedSoxFan** [comment]
Sway does appear to be sending a pointer enter event.

Can you post a Wayland debug log for whatever application you are experiencing an issue with? For Wayland applications, you can use `env WAYLAND_DEBUG=1 <application> 2> application.log`. For xwayland applications, you'll have to set `env WAYLAND_DEBUG=client` for Sway itself.

**Comment by nifker** [comment]
Cant reproduce - seemed to be an issue on my side.
