### ISSUE TITLE
Sway crashes on start since update to 1.4 with "Unable to create backend"

### ISSUE THREAD

**Issue by eknoes** [swaywm/sway#4965]
* Sway Version: 1.4
* Debug Log: https://gist.github.com/eknoes/635bf04ad3ef33af7c17c1370e931632
* Configuration File: default configuration

Since upgrading to Sway 1.4 and wlroots 0.10.0 sway crashes on start, I uploaded the Debug Log as gist (see above).

_Edit: Just realized that the coredump I got is from September 2019, so obviously not for this crash, sorry. If it helps I can install the git version and get a stacktrace, if the debug log is not enough._ 

I guess the relevant lines are the following:

```
2020-01-31 18:31:25 - [sway/server.c:40] Preparing Wayland server initialization
2020-01-31 18:31:25 - [backend/x11/backend.c:185] Failed to open X connection
2020-01-31 18:31:25 - [backend/noop/backend.c:51] Creating noop backend
2020-01-31 18:31:25 - [sway/server.c:47] Unable to create backend
```

Before updating everything worked fine, besides the "Failed to open X connection" which also appeared before, but did not raise obvious issues to me. If needed and you can give me little directions I am glad to debug this issue a bit further. Or is this an issue of wlroots, as `	server->backend = wlr_backend_autocreate(server->wl_display, NULL);` in `sway/server.c` does return null?

**Comment by progandy** [comment]
Duplicate of: #4953 
Related: swaywm/wlroots#1930

**Comment by eknoes** [comment]
The solution in the thread is: "This is an issue with your DM. DISPLAY should be unset." as far as I can see. I start sway like that:

```
if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
  exec sway
fi

```

As far as I understand DISPLAY should not be set then, because thats what the if about, or do I misunderstand it?

**Comment by ascent12** [comment]
>if [[ -z $DISPLAY ]]

This is testing if DISPLAY is an empty string, which is not the same thing as being unset.
Just put an explicit `unset DISPLAY` before `exec sway` and see if that works.

**Comment by eknoes** [comment]
Thanks, problem solved. Sorry for the inconvenience!
