### ISSUE TITLE
sway (swaybar?) clones additional i3status on reload

### ISSUE THREAD

**Issue by bhepple** [swaywm/sway#4970]
Using the default configuration in /etc/sway/config except for:

`status_command i3status`

Soon after starting a terminal, I see this:

```
0 14:21 ~/ $ pstree -p|grep i3status
           |-swaybar(3042528)---i3status(3042543)
```

After I perform a 'reload', I see this:

```
0 14:21 ~/ $ pstree -p|grep i3status
           |-i3status(3042746)
           |-swaybar(3042743)---i3status(3042748)
```

In other words, the existing i3status is killed and 2 i3status processes are started up; one has swaybar as a parent, the other is parented by the root process. Both i3status processes try to write to the bar but confusion arises. Killing the i3status parented by root fixes the problem (until the next reload).

**edit**: _Take a close look at the PIDs in my example. The original i3status has a PID of 3042543. After the reload, the 2 i3status's are new with PIDs 3042746 and 3042748. So either the original i3status did a fork/exec (which I doubt) or the new ones are created by swaybar - I don't think it's a case of the old one still running._

This also happens with i3blocks so it would appear to be a problem in swaybar.

* Sway Version: sway version 1.2

I have posted a sway.log at https://pastebin.com/EcmAqUeG

**edit**: _Here's a workaround - use this script instead of reload_
```
#!/usr/bin/env bash

swaymsg reload
sleep 1

# due to a bug (in swaybar?) an extra i3blocks process is started
ps -ef |
grep '\<[i]3blocks\>' |
while read _ pid ppid _; do
    (( ppid == 1 )) && kill $pid
done

```

**Comment by vvrein** [comment]
Update your sway to at least to 1.4 or better - to upstream, and check again. 
I have `sway 1.4` with `i3status 2.13 © 2008 Michael Stapelberg and contributors` without any issues.

**Comment by vvrein** [comment]
I have checked described behavior like this:
- set i3status as status command: `status_command i3status`
- launched sway
- reloaded couple times with Super+Shift+C
- and there was only one i3status in htop

**Comment by panaman67** [comment]
This still happens to me with Swaybg.

**Comment by vvrein** [comment]
@panaman67 What's your sway version?

**Comment by panaman67** [comment]
@vvrein its 1.4.

**Comment by vvrein** [comment]
Still can't reproduce. Can you build latest version from source?

**Comment by panaman67** [comment]
@vvrein Im in class rn, ill see if i can when I get home.

**Comment by vvrein** [comment]
![image](https://user-images.githubusercontent.com/17022100/73685147-49961000-46ce-11ea-99e1-5cc5465aef6c.png)

**Comment by vvrein** [comment]
@panaman67 ok, thanks

**Comment by bhepple** [comment]
@vvrein - thanks for checking this out on 1.4 (my distro, fedora, only has 1.2 and it does not have packages for meson/ninja etc so building 1.4 is quite hard - I wish fedora would improve their support of sway).

Take a close look at the PIDs in my example. The original i3status has a PID of 3042543. After the reload, the 2 i3status's are new with PIDs 3042746 and 3042748. So either the original i3status did a fork/exec (which I doubt) or the new ones are created by swaybar - I don't think it's a case of the old one 'stay running'.

**Comment by panaman67** [comment]
@vvrein I could not get sway to build on OpenSUSE Tumbleweed. Had some troule and sadly homework.. Ill try again tomorrow. 1.3 had this problem with swaybar, swaybg, and swayidle. 1.4 only has this problem with swaybg.

**Comment by vvrein** [comment]
@bhepple Ok, thank you for your reply, i'll check with `pstree -p | grep i3status`.

**Comment by vvrein** [comment]
@bhepple @panaman67 
![image_2020-02-07_13-20-19 (2)](https://user-images.githubusercontent.com/17022100/74026422-dbdc3380-49ae-11ea-9a05-327fb0a2bd70.png)
![image_2020-02-07_13-18-10 (2)](https://user-images.githubusercontent.com/17022100/74026426-dda5f700-49ae-11ea-83f4-56ce89f54a5d.png)
And here is recordings of my actions, it has pretty bad quality, but gives general view.
https://asciinema.org/a/zYkdIDlkM6dUFtiN6RxYEqsV5

**Comment by bhepple** [comment]
@vvrein - Yeah - looks like 1.4 fixes it for you. How about swaybg? I'm gunna try 1.4 if I can get the mhonek/sway copr working.

**Comment by bhepple** [comment]
So I just upgraded to 1.4 (using mhonek/sway fedora COPR) and I can confirm that the problem is now fixed.

**Comment by bhepple** [comment]
So I just upgraded to 1.4 (using mhonek/sway fedora COPR) and I can confirm that the problem is now fixed.
