### ISSUE TITLE
No matching node using swaymsg with criteria con_id

### ISSUE THREAD

**Issue by AdrienLemaire** [swaywm/sway#4972]
Related: #2643 and maybe #4929

sway version 1.4 

how to reproduce:

* `swaymsg -t get_tree`, and find the "pid" value for a container that is not focused, not floating, and has no nodes (it's a leaf).
* send a swaymsg command using that pid as criteria con_id
* It results in `Error: No matching node.`

Example:

```console
$ vimb -p profile1 &  # start a browser
$ pid=$!
$ swaymsg -t get_tree | grep -A1 $pid
                   "pid": 652095,
                   "app_id": "vimb",
$ swaymsg -- \[con_id=$pid\] title_format 'profile1 - %title'
Error: No matching node.
```

Expected result: The titlebar's title of the newly launched browser gets prefixed with 'profile1 -'

**Comment by RedSoxFan** [comment]
There is currently no criteria for pid - see https://github.com/swaywm/sway/pull/4602

`con_id` is the container id, which is the `id` property in the `get_tree` response. This just represents the id of the container in sway's tree structure and has nothing to do with the pid.

What you can do is:
```sh
vimb -p profile1 &
pid=$!
cid=$(swaymsg -t get_tree | jq ".. | objects | select(.pid==$pid) | .id")
swaymsg -- \[con_id=$cid\] title_format 'profile1 - %title'
```

**Comment by AdrienLemaire** [comment]
@RedSoxFan thanks for giving me the jq command I couldn't come up with yesterday :)

I got confused by all the id stuff because man 5 sway explains `con_id` and `id` (x11 window ID), while get_tree lists `id` and `pid`. 

The mapping get_tree -> criteria then goes as follow:

* window -> id
* id -> con_id
* pid -> find related id

If I understand correctly, when running a script from a shell, I'll need to find the parent pid (alacritty) of the parent pid (zsh) of that script's pid, then find the sway container id related to that alacritty pid.

Got my script to work (needed some sleep here and there to wait for containers to be launched), looking good!  Thanks again
