### ISSUE TITLE
Big fonts

### ISSUE THREAD

**Issue by matteocrippa** [swaywm/sway#4978]
I start facing a strange issue, some apps:

- KeepassXC
- GitAhead
- Android Studio
started to have big fonts.

![2020-02-05-164234_shot](https://user-images.githubusercontent.com/475463/73856994-8e3cbb00-4836-11ea-82e3-d13421cf64ac.png)

```bash
❯ swaymsg -t get_outputs  
Output eDP-1 'Unknown 0x0791 0x00000000' (focused)
  Current mode: 1920x1080 @ 60.012001 Hz
  Position: 0,0
  Scale factor: 1.000000
  Scale filter: nearest
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 2
  Max render time: off
  Available modes:
    1920x1080 @ 48.009998 Hz
    1920x1080 @ 60.012001 Hz
```

```bash
❯ sway -v
sway version 1.4-84ea0310 (Feb  4 2020, branch 'master')
```

**Comment by emersion** [comment]
Does this only happen after plugging/unplugging a screen?

**Comment by matteocrippa** [comment]
Nope, atm it happens even on reboot with no external screen attached, just the laptop one

**Comment by mstoeckl** [comment]
I encountered similar behavior after upgrading Qt from 5.14 to 5.14.1; I don't know the exact cause, but setting environment variable `QT_ENABLE_HIGHDPI_SCALING=0` resolved the issue.

**Comment by matteocrippa** [comment]
@mstoeckl thx for hint, that fixes the issue!
