### ISSUE TITLE
Window resize not reporting correctly

### ISSUE THREAD

**Issue by SairesArt** [swaywm/sway#4982]
My GLFW (In Wayland native mode) OpenGL application does not receive proper resize events, e.g. glfwGetWindowSize(); never updates, even though it should. As a result, the glViewport cannot be sized correctly.
Here is the WAYLAND_DEBUG log:
[log2.txt](https://github.com/swaywm/sway/files/4165631/log2.txt)
The application in question simply starts a hello triangle with a 100x100 window. During the log process some resizes of the window were performed (With Metakey+Arrow), then the resize mode was quit with ESC and the program was terminated.

According to analysis of the log by @emersion , this is a sway bug.

**Comment by SairesArt** [comment]
I'm a really dumb chestnut. My Event polling was disabled.
No issue anymore... well there is me :P

**Comment by emersion** [comment]
```
10:53 <linkmauve> emersion, if VladTheImplier ever comes back, tell them to subscribe to the framebuffer size instead of the window size for resizing, the former gives buffer size while the latter gives surface size.
10:53 <emersion> linkmauve: they figured out their bug in the end
10:53 <emersion> forgot to poll or something
10:54 <linkmauve> Yeah, but using the window size is also a bug, especially on HiDPI.
10:54 <linkmauve> They’ll usually render a quarter of window in that case.
10:54 <emersion> hm
```
