### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [swaywm/sway#4983]
I would like to point out that an identifier like “[`_SWAY_IPC_H`](https://github.com/swaywm/sway/blob/6effca7b61e87c7d17885d007d94e556a0137651/include/ipc.h#L1 "Update candidate")” [does not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28IncludeGuard%29 "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by emersion** [comment]
We could do the same as wlroots and strip the leading `_`.

**Comment by emersion** [comment]
Please send a PR.
