### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [swaywm/sway#4984]
Would you like to add more error handling for return values from functions like the following?
- [malloc](https://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [split_args](https://github.com/swaywm/sway/blob/939c7b2d529b8c982672a6e141a8bef2348d358a/common/stringop.c#L92)
- [strdup](https://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html "Duplicate a string.") ⇒ [get_basedirs](https://github.com/swaywm/sway/blob/939c7b2d529b8c982672a6e141a8bef2348d358a/swaybar/tray/icon.c#L22)

**Comment by emersion** [comment]
Sure. Fixing the whole codebase for those will take a while, though.

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?

**Comment by emersion** [comment]
Closing in favor of https://github.com/swaywm/sway/issues/3351

**Comment by elfring** [comment]
I suggest to adjust this software so that it [depends less on undefined behaviour](https://wiki.sei.cmu.edu/confluence/display/c/EXP34-C.+Do+not+dereference+null+pointers "Do not dereference null pointers.").

-----

* Are you interested to apply [aspect-oriented software development](https://aspectc.org/ "Software development with AspectC++?")?
* Would you like to encapsulate error detection and corresponding exception handling as [a reusable aspect](https://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in this software?

**Comment by emersion** [comment]
No. Please stop copy-pasting replies like this across repositories, it's very annoying, especially if you're not actually interested in working on this.
