### ISSUE TITLE
Sway crashes with "dup failed: Too many open files"

### ISSUE THREAD

**Issue by JordanL2** [swaywm/sway#4988]
sway version 1.4

Sway is crashing every couple of days or so, with the error in the logs: ```[wayland] dup failed: Too many open files```

What happens is Firefox will crash, and a script I have running subscribed to workspace events also crashes. I try reloading Sway to restart the script, and Sway crashes.

When Firefox crashes, I see these errors:

```
[wayland] file descriptor expected, object (39), message create_prime_buffer(2nhiiuiiiiii)
[wayland] error in client communication (pid 1222)
(...)
firefox[1222]: Error 22 (Invalid argument) dispatching to Wayland display.
sway[34136]: Exiting due to channel error.
sway[11120]: Exiting due to channel error.
sway[1539]: Exiting due to channel error.
sway[13416]: Exiting due to channel error.
sway[1434]: Exiting due to channel error.
sway[1593]: Exiting due to channel error.
sway[1341]: Exiting due to channel error.
```

The logs from startup and just before the crash (after the "SNIP" - line 1825) is here:
https://github.com/JordanL2/LinuxSetup/blob/master/Sway/sway_crash_2_highlights.txt

My config is here:
https://github.com/JordanL2/LinuxSetup/blob/master/Sway/config/sway/config

One thing that's important to mention is I have a script running that listens for workspace change events over Sway's IPC, and if the workspace is called "Game" it disables output scaling for that output, for all other workspaces it sets the output scale to 2. This is so I can play XWayland games in a workspace without the blurriness. The script is here: https://github.com/JordanL2/LinuxSetup/blob/master/Sway/config/sway/workspace_rules
I mention this because it might be the constant changing of output settings that is causing the issue.

**Comment by progandy** [comment]
I wonder if asyncio closes its sockets properly if you don't call the close method? Maybe sway could impose a limit of allowed simultaneous IPC connections.

**Comment by JordanL2** [comment]
It appears I'm supposed to close the streamwriter connection after writing. I'll try that and see if the issue stops occurring.

**Comment by JordanL2** [comment]
The issue hasn't occurred since, so I think it's fixed.

**Comment by ohk2kt3t4** [comment]
@JordanL2  Did you update your scripts (to close the connection after writing) in order to fix this, or did it go away on its own?

I am investigating a [different issue](https://github.com/altdesktop/i3ipc-python/issues/147) I encountered when using [this autotiling script](https://github.com/nwg-piotr/autotiling). It doesn't crash sway, however it does affect the IPC server itself (can't create new connections) possibly due to too many simultaneous number of IPC connections as mentioned above.

**Comment by JordanL2** [comment]
I updated my scripts.
