### ISSUE TITLE
Fcitx popup on wrong monitor with wayland app

### ISSUE THREAD

**Issue by kuon** [swaywm/sway#4993]
I use fcitx with japanese input.

I have three monitors side by side.

Fcitx works properly for X11 apps, but native wayland app (I tested with firefox and thunderbird, if you have other wayland app which support input method to suggest, I'll be happy to test) will always display the Fcitx popup on my left monitor. It is properly placed on the monitor, but on the wrong one.

If I start firefox or thunderbird with `GDK_BACKEND=x11` I don't have the issue.

I am not sure if this is a sway issue, but as it occurs only in wayland mode, I thought you might know more.

**Comment by RedSoxFan** [comment]
This is a limitation of xwayland. xwayland unmanaged surfaces will open on whatever was the last monitor to receive focus for an xwayland surface. This is why you only see the issue for wayland apps.

As for a Wayland solution, Sway currently does not support the required Wayland protocol extensions. There is an open PR at #4740 to implement them.

**Comment by kuon** [comment]
Aah, this is because fcitx is an Xwayland app. I get it. Thanks for the clarification.
