### ISSUE TITLE
Font blurry on xwayland apps with sway 1.4

### ISSUE THREAD

**Issue by somdoron** [swaywm/sway#4997]
sway version 1.4-f681d529
wlroots 0.10.0

configuration:
```
output "Dell Inc. DELL S2817Q XXXXXXXX" scale 2
```

The display is 4k.

After upgrading from sway 1.2 to 1.4 fonts got really blurry on xwayland apps (much more than usual).

I ran `git bisect` and track it down to the new scale_factor option:
https://github.com/swaywm/sway/commit/6968fb3123e69f563cd01d472967a9e6ddca2ec1

Workaround: setting the scale_filter to linear solves it.

**Comment by emersion** [comment]
Weird, nearest should give better results for integer scaling. Can you provide debug logs?

**Comment by somdoron** [comment]
Both log and configuration:
https://gist.github.com/somdoron/d4acc8ecc27f19ec63facb74df0327e6

**Comment by emersion** [comment]
Well. Nearest is supposed to be better in this case. Can you upload screenshots of nearest vs. linear?

**Comment by somdoron** [comment]
Linear
![linear](https://user-images.githubusercontent.com/2715638/74181288-ac952300-4c49-11ea-9203-56576d9a98fc.png)

Nearest
![nearest](https://user-images.githubusercontent.com/2715638/74181476-0e558d00-4c4a-11ea-8514-4048c4d62b07.png)

**Comment by somdoron** [comment]
It seems that linear give a smoother font but blurrier image and the nearest is pixelated.
The problem is, that on a 28' 4K it is unreadable.

linear:
![linear](https://user-images.githubusercontent.com/2715638/74185461-5d52f080-4c51-11ea-8073-42915b69690b.png)

nearest:
![nearest](https://user-images.githubusercontent.com/2715638/74185475-6643c200-4c51-11ea-9f59-28d9f8032315.png)

**Comment by somdoron** [comment]
@emersion I wonder if is there a way to not scale xwayland or a specific app? or if that can be contributed?

**Comment by emersion** [comment]
https://gitlab.freedesktop.org/xorg/xserver/merge_requests/111

**Comment by somdoron** [comment]
I tried the patch with https://github.com/Dirbaio/wlroots/commit/807064b2c976489ea3341427081c03a02b654222.

The xwayland app only used a quarter of the display. I will try to debug it.
