### ISSUE TITLE
move window to workspace and focus

### ISSUE THREAD

**Issue by breuerfelix** [swaywm/sway#5006]
hello,

I got a config like this:
```
bindsym $mod+control+$left move container to workspace next
bindsym $mod+control+$right move container to workspace prev
```
When I move a window to a different workspace, the focus stays on the current workspace.
Is there an option to move the window to a different workspace AND the focus to this new workspace + window ?

also, is there a wiki where EVERY possible configuration option is mention with a little comment on what it does ? The example config does contain only a subset of all options. i just can't seem to find such a wiki page :S

cheers,

felix

**Comment by Axenntio** [comment]
You can combine commands with a comma separator

```
bindsym $mod+control+$left move container to workspace next, workspace next
bindsym $mod+control+$right move container to workspace prev, workspace next
```

**Comment by breuerfelix** [comment]
thanks alot for your help ! it works like a charm :)

**Comment by edrex** [comment]
Combining the commands has one imperfection: when moving a group container, the selection isn't preserved (the last window in the group is selected after move). Not a huge deal tho.

**Comment by CarsonSlovoka** [comment]
I really like this [answer](https://github.com/swaywm/sway/issues/5006#issuecomment-585169833). Additionally, aside from focusing, sometimes I just want to switch to the previous or next tab, like this:

```
bindsym $mod+Page_Up workspace prev
bindsym $mod+Page_Down workspace next
bindsym $mod+Page_Up+3 exec swaymsg workspace prev | swaymsg workspace prev | swaymsg workspace prev;
bindsym $mod+Page_Down+3 exec swaymsg workspace next | swaymsg workspace next | swaymsg workspace next;

// below same as the @Axenntio said
bindsym $mod+Shift+Page_Up move container to workspace prev, workspace prev
bindsym $mod+Shift+Page_Down move container to workspace next, workspace next
```
