### ISSUE TITLE
Can't start Firefox and VLC: "Caught signal 4 (Illegal instruction). Server aborting"

### ISSUE THREAD

**Issue by mb720** [swaywm/sway#5016]
Hi!

I'm using sway 1.4 on Arch Linux and since the last update with `pacman -Syu`, I can't run Firefox anymore and VLC crashes too.

Running `firefox &` produces this on the command line:

    Unable to init server: Could not connect: Connection refused
    Error: cannot open display: :0

Here's an excerpt from `journalctl` when Firefox was started:

    Feb 15 18:31:58 marathon systemd[1]: Started Process Core Dump (PID 794560/UID 0).
    Feb 15 18:32:00 marathon systemd-coredump[794561]: Process 794549 (Xwayland) of user 1001 dumped core.
                                                      
                                                      Stack trace of thread 794549:
                                                      #0  0x00007fc4a4bd7ce5 raise (libc.so.6 + 0x3bce5)
                                                      #1  0x00007fc4a4bc1857 abort (libc.so.6 + 0x25857)

This is from `sway -d` at the same time:

    2020-02-15 18:31:58 - [xwayland/xwayland.c:89] WAYLAND_SOCKET=22 Xwayland :0 -rootless -terminate -listen 19 -listen 21 -wm 50
    glamor: No eglstream capable devices found
    (EE) 
    (EE) Backtrace:
    (EE) 0: Xwayland (0x55610f405000+0x64a9d) [0x55610f469a9d]
    (EE) 1: Xwayland (0x55610f405000+0x6b990) [0x55610f470990]
    (EE) 2: /usr/lib/libc.so.6 (0x7fc4a4b9c000+0x3bd70) [0x7fc4a4bd7d70]
    (EE) 3: /usr/lib/dri/swrast_dri.so (0x7fc49186d000+0x521044) [0x7fc491d8e044]
    (EE) 4: /usr/lib/dri/swrast_dri.so (0x7fc49186d000+0x533b56) [0x7fc491da0b56]
    (EE) 5: /usr/lib/dri/swrast_dri.so (0x7fc49186d000+0x51ea44) [0x7fc491d8ba44]
    ...
    (EE) Illegal instruction at address 0x7fc491d8e044
    (EE) 
    Fatal server error:
    (EE) Caught signal 4 (Illegal instruction). Server aborting

When starting VLC, this is what shows up in `journalctl`:

    Feb 15 18:58:18 marathon systemd-coredump[849225]: Process 849196 (vlc) of user 1001 dumped core.
                                                      
                                                      Stack trace of thread 849223:
                                                      #0  0x00007fa7d9232d24 __pthread_mutex_lock (libpthread.so.0 + 0xbd24)
                                                      #1  0x00007fa7d51bffe3 wl_proxy_create_wrapper (libwayland-client.so.0 + 0x6fe3)
                                                      #2  0x00007fa7b592d10c n/a (libEGL_mesa.so.0 + 0x2310c)
                                                      #3  0x00007fa7b591590f n/a (libEGL_mesa.so.0 + 0xb90f)
                                                      #4  0x00007fa77e80a622 n/a (libegl_wl_plugin.so + 0x1622)
                                                      #5  0x00007fa7d8f77964 n/a (libvlccore.so.9 + 0x2e964)
                                                      #6  0x00007fa7d8f77f21 vlc_module_load (libvlccore.so.9 + 0x2ef21)
                                                      #7  0x00007fa7d8fd9738 vlc_gl_Create (libvlccore.so.9 + 0x90738)

Here are the log files:

  * [`sway.log`](https://gist.github.com/mb720/c6592e2d7aa81db8d842a2dbbe7528e5)
  * [`firefox_journalctl.log`](https://gist.github.com/mb720/db6530a16c65875f24fd230b40262322)
  * [`vlc_journalctl_with_core_dump.log`](https://gist.github.com/mb720/4d072b3cb69532b24b2e63351d2235ea)
  * [`vlc_journalctl.log`](https://gist.github.com/mb720/97d1dd003782ef04796a5fc642dd921c)

Let me know if you need further information.

Thanks!

**Comment by emersion** [comment]
This is an Xwayland bug. Please report it here: https://gitlab.freedesktop.org/xorg/xserver

**Comment by mb720** [comment]
Turns out this was a [mesa bug](https://gitlab.freedesktop.org/xorg/xserver/issues/985).
