### ISSUE TITLE
Behavioral mismatch with i3: window titles shows in single-element tabbed containers

### ISSUE THREAD

**Issue by jplatte** [swaywm/sway#5027]
Sway Version: 1.4

Hi! I'd like to know whether there is a way of configuring sway to hide the title bar of a singular window inside of a tabbed container. In i3, this is the default behavior if the title bar is hidden with `default_border none|pixel …`.

**Comment by RedSoxFan** [comment]
You can use `hide_edge_borders --i3 none|vertical|horizontal|both|smart|smart_no_gaps`

See the referenced issues/PRs in the description of #3767 for information on why this is behind a flag
