### ISSUE TITLE
Opening the File Chooser Dialog Breaks Keyboard Input for That Program

### ISSUE THREAD

**Issue by ambiso** [swaywm/sway#5030]
* Sway Version: 1.4

* Debug Log:

https://gist.github.com/ambiso/d81dbca2a3abddeacd32ea39665fe458#file-sway_signal-log

https://gist.github.com/ambiso/d81dbca2a3abddeacd32ea39665fe458#file-sway_thunderbird-log

* Configuration File: None provided (therefore default?)

* Steps to Reproduce:

Attached a file in [signal-desktop](https://www.archlinux.org/packages/community/x86_64/signal-desktop/) by clicking the plus sign in a chat. Having selected a file I can't type into the message box anymore - the cursor is showing in the right position but key presses are ignored.

Writing a new E-Mail in [thunderbird](https://www.archlinux.org/packages/extra/x86_64/thunderbird/) I add an attachment and can't continue writing the E-Mail.

I can still use other programs, and after restarting the affected program I can use it normally again (until I again attach a file).

If you need any further information, please tell me.
If this is a bug I should file elsewhere, feel free to simply close/move the issue.

Thanks a lot in advance!
ambiso

**Comment by emersion** [comment]
Fix has been merged in master.
