### ISSUE TITLE
Intellij IDEA popup centered on screen

### ISSUE THREAD

**Issue by Ogromny** [swaywm/sway#5031]
Hi, 
With the last Intellij IDEA (2020.1 EAP) when a popup appear it's centered on screen, and it should be not:
![screenshot](https://i.ibb.co/QFr3qZT/20200221-11h01m01s-grim.png)

> sway version 1.4-f2a60d2d (Feb 20 2020, branch 'HEAD')

**Comment by moberrauch** [comment]
I have similar behaviour in keepassxc for quite some time now: context menus open at the top of the window, all top row menus except "Tools" open upwards and therefore are cut off, etc.
It doesn't really impact my ability to use the program, but can on times be annoying.
The problems go away, when QT is forced use X11 by setting `QT_QPA_PLATFORM=xcb`.
This might also be a fix for @Ogromny , if you don't mind running IntelliJ on X11.

**Comment by juliandemille** [comment]
@moberrauch I tried your suggestion solution to no avail. It seems IntelliJ and derivatives use a Java-based UI framework.

**Comment by lol768** [comment]
I had the same issue with `sway version 1.2` and similar versions of IntelliJ. I had to downgrade all JetBrains products in the meantime.

**Comment by Ogromny** [comment]
See #3007
