### ISSUE TITLE
Two-finger scrolling stops working after suspend

### ISSUE THREAD

**Issue by HardDie** [swaywm/sway#5034]
╰─$ uname -a
Linux DELL 5.5.4-arch1-1 #1 SMP PREEMPT Sat, 15 Feb 2020 00:36:29 +0000 x86_64 GNU/Linux

╰─$ swaymsg -t get_version
sway version 1.4

input 10182:496:DELL096E:00_27C6:01F0_Touchpad {
    tap enabled
    natural_scroll enabled
    dwt enable
    scroll_method two_finger
}

[sway_log.txt](https://github.com/swaywm/sway/files/4237825/sway_log.txt)

After command
`systemctl suspend`
two-finger scrolling does not work until reboot

**Comment by emersion** [comment]
Does `sudo libinput debug-events` print the events after susupend?

In any case, this is likely a libinput or kernel bug.

**Comment by HardDie** [comment]
After suspend libinput show only POINTER_MOTION events
Ok I will create a ticket in the libinput project
Thank you!

**Comment by HardDie** [comment]
https://gitlab.freedesktop.org/libinput/libinput/issues/435
