### ISSUE TITLE
Dragging a floating XWayland window lags and snaps

### ISSUE THREAD

**Issue by emberfade** [swaywm/sway#5035]
### Sway Version:

`sway version 1.4`

### Debug Log:

[sway.log](http://0x0.st/iZY9.log)

### Configuration File:

Default with the following additions:

```
input type:pointer
{
	accel_profile flat
	pointer_accel -0.5
}
```

`accel_profile flat` is optional but it will be easier to see the issue than using `adaptive`.

### Reproduction:

Drag a floating XWayland window. Either through the titlebar or by holding `Super`.

When the cursor moves the window will lag and then snap to the cursor's position. It will keep doing this the whole time.

### Additional information:

I tested this with Weston where this didn't happen.

`.config/weston.ini`
```
[core]
xwayland=true

[libinput]
accel-profile=flat
accel-speed=-0.5
```

I only notice this with _negative_ `pointer_accel` values. It is also far more noticable with a flat profile.

The faster you move the mouse the less it happens. You can see this better with `accel_profile adaptive` where you have to move the mouse really slow to notice this. `swaymsg 'input type:pointer pointer_accel -1'` makes it more obvious.

**Comment by shumvgolove** [comment]
Yeah, this keeps happening for me for quite some time now, but I kept ignoring it.

**Comment by ghost-420** [comment]
This problem is ridiculously severe when actively using the tabbing functionality.

**Comment by Xyene** [comment]
This has been fixed in Sway master; if you are unable / don't want to update, you can also run Sway with `-D noatomic` to prevent this issue from occurring. (Of course, this comes at the cost of nonatomic updates.)

**Comment by emberfade** [comment]
Thank you @Xyene. The issue has been fixed.

**Comment by emberfade** [comment]
@Xyene the behaviour seems to be back for me. Should I open a new issue or can this one be reopened?

**Comment by Xyene** [comment]
Please open a new ticket, with debug logs, and whether `-D noatomic` resolves things. Bonus points if you can build with https://github.com/swaywm/sway/pull/5846 applied (`curl -L https://github.com/swaywm/sway/pull/5846.diff | patch -p1`).
