### ISSUE TITLE
sway reports wrong version number

### ISSUE THREAD

**Issue by bhepple** [swaywm/sway#5036]
I don't have a more up to date version available but:

```
$ sway --version
sway version 1.0
$ rpm -q sway
sway-1.1.1-2.fc31.x86_64
```

**Comment by Emantor** [comment]
Older releases indeed forgot to increase the version number, this is fixed on recent releases. You can confirm this by looking at the `meson.build` file in the 1.1-release and v1.4 branches respectively.
