### ISSUE TITLE
Error: Unknown/invalid command 'caps:escape'

### ISSUE THREAD

**Issue by WhyNotHugo** [swaywm/sway#5039]
I'm trying to set up my keyboard, but I have issues when setting two options at once:

```
➜ swaymsg input 1133:16399:Logitech_K750 xkb_options caps:escape
➜ swaymsg input 1:1:AT_Translated_Set_2_keyboard xkb_options altwin:swap_lalt_lwin,caps:escape

Error: Unknown/invalid command 'caps:escape'
```

The latter options are actually copy-pasted [from the docs](https://github.com/swaywm/sway/wiki#input-configuration), so I've no idea why they don't work.

Setting _only_ caps or _only_ the other option works, but not both.
(Note that I'm not swaping win/alt on my external keyboard since the keys are actually aligned the way I prefer them).

```
➜ swaymsg -v
swaymsg version 1.4
```

**Comment by Emantor** [comment]
At the top of the commands section of the `man5 sway` page:
```
The following commands may only be used in the configuration file.
```

**Comment by WhyNotHugo** [comment]
Nope, doesn't look like an escaping issue (no spacing or special characters here anyway). Adding quotes didn't help here.

**Comment by emberfade** [comment]
`swaymsg 'input 1:1:AT_Translated_Set_2_keyboard xkb_options "altwin:swap_lalt_lwin,caps:escape"'`

I tested this with the comma but different values. It works when using both quotes.

**Comment by emersion** [comment]
For i3 compatibility, an unescaped `,` can be used to execute multiple commands on the same line. Since the shell strips one level of quotes, double-quotes are required.

**Comment by WhyNotHugo** [comment]
And, I would not have figured that out on my own. I appreciate your help!
