### ISSUE TITLE
Can't use "--custom" option to set custom resolution

### ISSUE THREAD

**Issue by TiBeN** [swaywm/sway#5041]
Sway v1.4 installed through pacman in arch linux.

The --custom option is well mentionned in `man 5 sway-output` but i can't make use of this option:

    sway output HDMI-A-1 mode --custom 1680x1050@50

which outputs:

```
sway: unrecognized option '--custom'
Usage: sway [options] [command]

  -h, --help             Show help message and quit.
  -c, --config <config>  Specify a config file.
  -C, --validate         Check the validity of the config file, then exit.
  -d, --debug            Enables full logging, including debug information.
  -v, --version          Show the version number and quit.
  -V, --verbose          Enables more verbose logging.
      --get-socketpath   Gets the IPC socket path and prints it, then exits.
```
It seems the option is not recognized.

**Comment by emersion** [comment]
`--` is needed to disambiguate `swaymsg` options and `output` options:

```
sway -- output HDMI-A-1 mode --custom 1680x1050@50
```

**Comment by TiBeN** [comment]
Thank for your quick answer and apologies, i'm pretty new to Sway and have no experiences in i3.

I tried the following one but without any luck:

```
[ben@ben-fix ~]sway -- output HDMI-A-1 mode --custom 1680x1050@50
2020-02-24 20:48:39 - [sway/main.c:328] Detected both options and positional arguments. If you are trying to use the IPC client, options are not supported. Otherwise, check the provided arguments for issues. See `man 1 sway` or `sway -h` for usage. If you are trying to generate a debug log, use `sway -d 2>sway.log`.
```

**Comment by TiBeN** [comment]
Its works using `swaymsg`:

    swaymsg -- output HDMI-A-1 mode --custom 1680x1050@50

Solved. Thanks.

**Comment by sandov** [comment]
It would be helpful to mention the need for the first '--' in the man page, so that the next person doesn't waste as much time as me wondering why it doesn't work.

**Comment by marcusatiliusregulus** [comment]
had the exact same issues as @TiBeN and his solution (to use swaymsg instead of sway -- output`) works for me too, however i believe this should be mentioned in the docs because otherwise i dont know if i would have figured this out without this issue!!

**Comment by rokobuljan** [comment]
Actually...

- Wrap in quotes
- Don't forget to append `Hz` for the refresh rate

```
swaymsg "output HDMI-A-1 mode --custom 1680x1050@50Hz"
```
