### ISSUE TITLE
Help debugging issue with high number of calls received from sway IPC

### ISSUE THREAD

**Issue by ammgws** [swaywm/sway#5043]
# Question
Do the screenshots below point towards an issue within sway, or is it an issue with how the IPC is being used by third party scripts?

# Background

I have been using this [autotiling](https://github.com/nwg-piotr/autotiling/blob/master/autotiling.py) script which uses the [i3ipc-python](https://github.com/altdesktop/i3ipc-python) library, and on multiple occasions have found the python process pegging my CPU.

After running strace on the process for about 30 seconds I found over 16 million calls from the sway socket:
![image](https://user-images.githubusercontent.com/20397027/74684808-28760900-5210-11ea-8827-58125fe86784.png)

Socket looks to be at least responding to these calls, but with a 0 byte response.
But there are no `write()` calls in between so this seems like sway is just infinitely spamming the client.
![image](https://user-images.githubusercontent.com/20397027/74684999-99b5bc00-5210-11ea-9fe6-f64bcc31a834.png)

# Environment
- sway version 1.4-46561fc9 (Feb  7 2020, branch 'makepkg')
- haven't managed to get a useful debug log yet (Every time I have come across this issue has been after leaving the computer for a few hours and by then the log has gotten out of control)
- haven't tried with default sway config yet (still investigating exactly how to reproduce this issue)

**Comment by emersion** [comment]
Try `strace`'ing Sway and checking whether there are some weird `write` calls?

From just looking at your traces my bet would be that the script is reading a non-blocking FD in a loop.

**Comment by ammgws** [comment]
Yeah I'm going to close this one for now until it happens again and I can determine whether sway was unconditionally sending writes (seems unlikely), or the client was just unconditionally requesting them.
