### ISSUE TITLE
Random freezing

### ISSUE THREAD

**Issue by antonkatz** [swaywm/sway#5045]
I'm running sway 1.4.

Every so often, the screen just freezes. Mouse movement doesn't work. Keyboard doesn't work.
I've looked at `journalctl` logs. Nothing. Went from linux kernel to linux-zen -- seems to have made it worse.

So far, there's no rhyme or pattern that I notice to when the screen freezes. At first I thought it was firefox, but then sway froze without me ever opening firefox. 

One last potentially helpful piece of info: once my screen froze on the login shell. I could still switch to tty2, however.

Latest log obtained with `sway -dV` is here. https://pastebin.com/4iG3fme2

**Comment by antonkatz** [comment]
Tried adding `nouveau.noaccel=1` as a boot option. Made the system unusable as sway completely took over the cpu load. Trying `QT_XCB_FORCE_SOFTWARE_OPENGL=1` now.

**Comment by antonkatz** [comment]
The problem is the `nouveau` driver, unfortunately. I've switched to KDE plasma and experienced the same issue. I installed proprietary `nvidia` drivers and can't use Sway anymore :(

**Comment by mordax777** [comment]
Are you sure it is the `nouveau` driver? I am experiencing similar behavior with Intel.

**Comment by emersion** [comment]
Doesn't seem like this is actionable for Sway. Please report a nouveau bug: https://gitlab.freedesktop.org/drm/nouveau/
