### ISSUE TITLE
Feature request: disable title bars altogether

### ISSUE THREAD

**Issue by Sweenu** [swaywm/sway#5050]
I would love to have the possibility to completely disable title bars, whether in split or tabbed or stacked, whether there's one or several windows.

It seems like this wasn't possible in i3 either so it would be an improvement over it.

If possible, I wish it could be a simple option like `title_bars disabled`. It is simpler and more explicit than having to hack the border size. For someone coming from other WMs like me, it's easier to wrap my head around.

**Comment by vvrein** [comment]
![image](https://user-images.githubusercontent.com/17022100/75588180-c4a9d680-5a80-11ea-9e90-3041ef982c6d.png)  
btw, `default_border none` make what you want, except for tabbed mode, where completely disabled titles are a bit unhandy.

**Comment by Sweenu** [comment]
Well I don't use the tabbed layout, however I use the stacked layout and I do not want to have title bars when in stacked mode. But the `default_border none` trick does not hide title bars in any of those two layouts :/

**Comment by travankor** [comment]
There was a Feature Request for this in i3 and it was explicitly rejected (ie: can not hide tabbed/stacked layout)

**Comment by Sweenu** [comment]
I'm sorry this is apparently a duplicate of https://github.com/swaywm/sway/issues/1286, where they propose the following solution: 
```
font pango:monospace 0
titlebar_border_thickness 0                                                     
titlebar_padding 0
```
This works for me :)

**Comment by beemibrahim** [comment]
What about hiding the title bar only for stacked mode. I see solutions for remove titlebars for all modes what about just stacked mode.
