### ISSUE TITLE
Workspace number should not appear in its name

### ISSUE THREAD

**Issue by Sweenu** [swaywm/sway#5051]
* Sway version 1.4 

I don't know if this is a bug or not but I would expect that using the command
 ```bash
swaymsg workspace 3 d
```
would go to a workspace whose number is 3 and name is "d" but in fact, what happens is that it creates a workspace whose number is 3 but name is "3 d".

This is confusing considering that the man says that the `number` argument is only used for sorting:
```
workspace [--no-auto-back-and-forth] [number] <name>
    Switches to the specified workspace. The string "number" is optional and is used to sort workspaces.
```
And moreover, it forces whichever bar the user is using to implement a way to strip the number from the name. Fortunately for swaybar users, this exists with the option `strip_workspace_numbers` but does not exist in waybar for example. Maybe the solution would be to implement this in waybar but I think it's hacky compare to having the number of a workspace completely separated from its name in sway.

Hope it makes sense!
Thanks for your work on this project. Besides those little things, it's been a really great experience using sway!

**Comment by RedSoxFan** [comment]
The documentation is not correct.I'll submit a PR to fix in it a couple hours.

For the functionality that you want, use `workspace 3:d`.

The `number` string allows you to specify a default name for the workspace, if one for the number does not exist. For example, `workspace number 3:d` would always reference workspace number 3. If there isn't a workspace 3, then a new workspace with the name `3:d` will be created. If a workspace with the number does exist, say `3:c`, then it'll use workspace `3:c` instead.

**Comment by Sweenu** [comment]
Thanks for your answer!

The thing is that I want to create a workspace with the number 3 but the name "d" not "3:d".
If I do `swaymsg workspace 3:d`
and then `swaymsg -rt get_workspaces | jq '.[] | select(.name=="3:d")'`,
it outputs the workspace information, particularly:
```json
{
  "name": "3:d",
  "num": 3
}
```

The reason for my request is that in my bar, I want to see only the name I give to the workspace ("d" here). I want to give a number to that workspace only to tell my bar how it should be sorted.

Maybe my request should go to the Waybar repo instead, let me know :)

**Comment by RedSoxFan** [comment]
If Waybar does not have an option to strip workspace numbers, then that would be a Waybar request as the functionality is supported by swaybar.

Either way, I'll get the man page updated for `workspace [number]`

**Comment by Sweenu** [comment]
Alright I see, thank you for your answers, I let you close this.
