### ISSUE TITLE
Cycle scratchpad without hiding

### ISSUE THREAD

**Issue by hughwilliams94** [swaywm/sway#5052]
* Sway Version: sway version 1.2-ba8586e2

Is there some way to cycle the scratchpad rather than toggling it. (that is, without hiding it between each show command). I have `swaymsg scratchpad show` bound to a libinpput-gesture and currently have to swipe up twice to change between two scratchpad windows.

**Comment by travankor** [comment]
No, I don't think i3 even lets you do this.

**Comment by progandy** [comment]
Can't you just repeat the command?

    swaymsg scratchpad show ';' scratchpad show

**Comment by travankor** [comment]
Actually, you can already achieve this with something like
```
bindsym $key scratchpad show; scratchpad show
```

It's a bit hacky since it doesn't work when there is no scratchpad shown, but I guess you could either use another keybinding or create something more complicated.

**Comment by hughwilliams94** [comment]
Hmm, I'll have a look into it.

**Comment by hughwilliams94** [comment]
This seems to work well enough, thanks very much.
