### ISSUE TITLE
can sway be run as root?

### ISSUE THREAD

**Issue by unmellow** [swaywm/sway#5053]
whenever i try to do it i get
"[sway/main.c:195] Unable to drop root (we shouldn't be able to restore it after setuid), refusing to start"
i assumed you don't allow it but thought i would ask just in case

**Comment by ddevault** [comment]
No.

**Comment by tnagorran** [comment]
@unmellow You can now https://github.com/tnagorran/swayroot :3

**Comment by emersion** [comment]
We don't recommend using binaries from an untrusted third-party, and we don't recommend patching binaries. Instead, patch the source code and build it.
