### ISSUE TITLE
Can't set natural scrolling on my touchpad

### ISSUE THREAD

**Issue by lovesegfault** [swaywm/sway#5054]
If I use [`swaymsg -t get_inputs`](https://gist.github.com/0bf09be55a92e783be37f8d466aa32ec) I see the following as my touchpad:
```
Input device: Synaptics TM3418-002
  Type: Touchpad
  Identifier: 1739:0:Synaptics_TM3418-002
  Product ID: 0
  Vendor ID: 1739
  Libinput Send Events: enabled
```

I then attempt to enable natural scrolling for it by adding this clause to my [configuration](https://gist.github.com/19277a18df5cc4540199ae58a1fe3390):
```
input "1739:0:Synaptics_TM3418-002" {
    accel_profile adaptive
    click_method button_areas
    dwt disabled
    natural_scroll enabled
    scroll_method two_finger
    tap enabled
}
```
I would expect for natural scrolling to be enabled, but that does not happen, as libinput shows:
```
❯ libinput  list-devices | rg TM3418-002 --after-context=17
Device:           Synaptics TM3418-002
Kernel:           /dev/input/event27
Group:            12
Seat:             seat0, default
Size:             97x65mm
Capabilities:     pointer gesture
Tap-to-click:     disabled
Tap-and-drag:     enabled
Tap drag lock:    disabled
Left-handed:      disabled
Nat.scrolling:    disabled
Middle emulation: disabled
Calibration:      n/a
Scroll methods:   *two-finger edge
Click methods:    *button-areas clickfinger
Disable-w-typing: enabled
Accel profiles:   none
Rotation:         n/a
```
Reloading the config, rebooting, and shaking the computer do not seem to help.

* Sway Version:
```
❯ swaymsg -t get_version
sway version 1.4
```

* Debug Log:
```
https://gist.github.com/3c7372ec49dcf8be071a68308987642c
```
* Configuration File:
https://gist.github.com/19277a18df5cc4540199ae58a1fe3390

**Comment by lovesegfault** [comment]
This apparently works now, there is a related issue with libinput reporting things wrong, but it's probably not sway's fault so I am closing this.

**Comment by RedSoxFan** [comment]
For reference, do not use `libinput list-devices` to check the current settings of an input. That lists the default settings for the device.

To view the current settings, use `swaymsg -rt get_inputs` (you'll need the `-r` to see the full json as the information is not currently pretty printed). The settings  will be listed under `libinput` for the appropriate input device. If a setting is not listed, it is not supported for the device.

**Comment by lovesegfault** [comment]
Nice, this shows the correct setting:
```
  {
    "identifier": "1739:0:Synaptics_TM3418-002",
    "name": "Synaptics TM3418-002",
    "vendor": 1739,
    "product": 0,
    "type": "touchpad",
    "libinput": {
      "send_events": "enabled",
      "tap": "enabled",
      "tap_button_map": "lrm",
      "tap_drag": "enabled",
      "tap_drag_lock": "disabled",
      "accel_speed": 0,
      "accel_profile": "none",
      "natural_scroll": "enabled",
      "left_handed": "disabled",
      "click_method": "button_areas",
      "middle_emulation": "disabled",
      "scroll_method": "two_finger",
      "dwt": "disabled"
    }
  },
```
