### ISSUE TITLE
Nested sway crashes randomly

### ISSUE THREAD

**Issue by brandsimon** [swaywm/sway#5055]
I run a nested sway and sometimes it crashes. It happens usually when there is no interaction (I am on another workspace in the host sway).
I use this config:
```
exec xfce4-terminal
```
Here is a debug log:  http://sprunge.us/8mSZHv

My sway version is `sway version 1.4`.

Steps to reproduce:
I basically do nothing.
I start sway with the config and pipe the debug log into a file.
Sometimes I change to the workspace with the nested sway to see if it crashed, then go back to another workspace.
I am using an uptodate Arch Linux with intel graphics card.

The crash is also reproducible when I start firefox, claws-mail or anyithing else in sway.

**Comment by ascent12** [comment]
Please post a backtrace of sway.
```sh
coredumpctl gdb sway
...
(gdb) bt
<copy this bit>
(gdb) q
```

**Comment by brandsimon** [comment]
@ascent12 
There is no backtrace. My last backtrace from sway is over a week ago (the libinput assertion bug).
The exit code from sway is 0.
Here is another log where I didnt even had an `exec something`:
http://sprunge.us/5wVo79

**Comment by RedSoxFan** [comment]
That debug log shows something going horribly wrong.
- 21 keyboards get added in less than a second
- On the 21st, the following in logged. Likely due to running out of memory.
```
file descriptor expected, object (163), message keymap(uhu)
2020-03-02 05:45:36 - [backend/wayland/backend.c:57] Failed to dispatch remote Wayland display
2020-03-02 05:45:36 - [backend/wayland/backend.c:57] Failed to dispatch remote Wayland display
```
- 107 keyboards are removed

**Comment by brandsimon** [comment]
I think this happens when I change tty. (I do this quite often sometimes)

**Comment by brandsimon** [comment]
This is totally related to a tty switch.The crash occurs after 6 switches.
Every time I switch to another tty and back, there are even more keyboards returned with `swaymsg -t get_inputs`.
This can be seen in the log: http://sprunge.us/zg83Tk
Interesting is, that there are no duplicate pointer devices.

I have another problem with firefox (which I did not report because I only encountered it with firefox):
Very rarely one key press seam to get duplicated, I press `a` and there are like 20 `a`s
It would be interesting if this could be fixed with fixing this bug.

**Comment by emersion** [comment]
Can you try this patch? https://github.com/swaywm/wlroots/pull/2048

**Comment by brandsimon** [comment]
@emersion 
Thank you, I tested it today, but it resulted in a coredump after the first tty switch: http://sprunge.us/ezNLTx
Does it help if I compile something with debug symbols?

**Comment by brandsimon** [comment]
Sorry for the little information. The coredump happend in the nested sway.
Here is a coredump http://sprunge.us/ueoMpH with a corresponding debug log http://sprunge.us/DOSGaw

**Comment by emersion** [comment]
Ah, sorry about that. Should be fixed now.

**Comment by brandsimon** [comment]
@emersion 
Great, it seams to work now.
No keyboard / pointer duplication and no crash :)
Thank you very much (to all of you for the great work!)
