### ISSUE TITLE
How does sway do "i3-input" interactively take a command?

### ISSUE THREAD

**Issue by zdmgmail** [swaywm/sway#5057]
I want to rename like this:

bindsym $mod+n exec i3-input -F 'rename workspace to "%s"' -P 'New name for this workspace: '

**Comment by RedSoxFan** [comment]
There is this script here that emulates i3-input: https://github.com/swaywm/sway/issues/2#issuecomment-305380165

You could also just do something similar to the default menu command
https://github.com/swaywm/sway/blob/7fea36750ea23906c41c18a2768acad2f51b2916/config.in#L21

For example:
```
bindsym $mod+n exec echo "" | dmenu -p "New name for this workspace" | xargs -r swaymsg rename workspace to
```

**Comment by zdmgmail** [comment]
Thanks,perfectly solved!

**Comment by hyunlee1o** [comment]
Hey, i was searching for this, thanks for answering. :)
I mostly use letters in workspace names so this helps me.
