### ISSUE TITLE
tmux session_attached with sway

### ISSUE THREAD

**Issue by zdmgmail** [swaywm/sway#5058]
set -g status-left "   Sessions:  #{S:#{?session_attached,*,}#{session_name}  }   
    
When using tmux I use this line configuration to add * know where I am focusing

I want tmux to only add * in the current focus terminal, but in sway, * will be added to the tmux terminal of other workspaces

Is there a way to solve this problem

**Comment by emersion** [comment]
Closing because this isn't a Sway issue. Please ask on IRC.
