### ISSUE TITLE
Question about IPC Response Format 

### ISSUE THREAD

**Issue by mab-on** [swaywm/sway#5060]
Hi, thank you for this awesome software :+1: 

I Have a question: According to the RUN_COMMAND-example in the documentation (https://www.mankier.com/7/sway-ipc#Messages_and_Replies-0._Run_command) there can be more then one object in the payloads (json)list.

When could one RUN_COMMAND-ResponseMessage contain more then one Object in its payload? Because both, RequestMessage and ResponseMessage, contain the corresponding payload-type in the MessageHeader - so i understand it is one Response for each RUN_COMMAND-Request.
What do i miss?

Thank you.

**Comment by RedSoxFan** [comment]
If the payload is a series of commands, the response will be a list of objects with one object per command executed. Syntax errors will terminate execution so there may not be a 1:1 mapping.

For example, if the payload is the following:
```
floating enable, sticky enable
```

Depending on what is focused, you may receive the following response:
```json
[
  {
    "status": "success"
  },
  {
    "status": "success"
  }
]
```

Also, in the future, please ask questions on the IRC channel (#sway on irc.freenode.net)
