### ISSUE TITLE
Simple clients lose their borders when floated

### ISSUE THREAD

**Issue by lephe** [swaywm/sway#5066]
Simple (not to say trivial) Wayland clients seem to lose their border configuration at the moment they go floating. I first noticed this with a hand-written program then with emersion's [`hello_wayland`](https://github.com/emersion/hello-wayland).

Here's an example with the cat. Before floating, the window looks like this (notice the 1 pixel border around the right half of the screen):

![out-1](https://user-images.githubusercontent.com/33732078/75812704-f5468480-5d8e-11ea-8933-6ffa69cbcddd.png)

After floating and tiling back, the border is gone, the `border` attribute is also gone, and the corresponding space has been redistributed to the client:

![out-2](https://user-images.githubusercontent.com/33732078/75812711-f972a200-5d8e-11ea-8fcf-7f056fa9fcbb.png)

The border disappears immediately when floating. I have only observed this problem with such simple programs. Gtk/Qt applications and the like all keep their borders.

Sway version:
```
sway version 1.4-476773dd (Mar  3 2020, branch 'master')
```
Minimal configuration with which I could manipulate my keyboard to reproduce the bug:
```
output * bg #000000 solid_color

bindsym F12 exec alacritty
bindsym Shift+Mod1+C reload
bindsym Mod1+Space floating toggle

bindsym F1 workspace 1
bindsym F2 workspace 2
```
Steps to reproduce:
1. Compile and execute emersion's [`hello_wayland`](https://github.com/emersion/hello-wayland)
2. Make the window float

Also, obligatory big thank you for the project and the work that goes into it. ^^

**Comment by somini** [comment]
Can confirm this happens with alacritty configured for `decorations: none` (to show only sway decorations).

**Comment by patcoll** [comment]
This seems to happen to me using kitty, whether I have `hide_window_decorations` set to either yes or no. Haven't been able to nail down a simple reproducible case for myself yet. Using `sway-launcher-desktop` and looking to have a border on a floating window.

**Comment by dimitris-triantafyllidis** [comment]
I just looked a bit into this and it seems to have something to do with CSD and some logic around view->using_csd. If you print the tree when the window is floating, is the border set to "csd"? I plan to try and fix it one of these days along with a couple of other border related things.

**Comment by lephe** [comment]
> If you print the tree when the window is floating, is the border set to "csd"?

Yes, the border is set to `csd` while the window in my initial example is floating. Well spotted!

**Comment by emersion** [comment]
Simple clients are expected to draw their own borders. Clients that don't want to do it can attempt to pt-out using the xdg-decoration protocol,

**Comment by dimitris-triantafyllidis** [comment]
@emersion But the borders should be restored when going back to tiling, right? The initialization of saved_border is problematic. I had opened a PR for this but it did not work for xwayland clients and it wasn't very clear whether it could cause other issues so I closed it.

**Comment by LastLightSith** [comment]
After making some windows with CSD floating and again tiling, they loose border completely.

![20210818_22h52m04s_grim](https://user-images.githubusercontent.com/29699740/129945889-6b032314-889b-4f40-a55f-d3f0571f982b.png)

Should I create new issue?
