### ISSUE TITLE
Screen sharing through Slack/Teams or similar

### ISSUE THREAD

**Issue by JonasKs** [swaywm/sway#5083]
Has anyone been successful in sharing the screen through `Slack` or `Teams`? 
The official Teams client crashes if I attempt to do so, Slack only show my mouse on a black screen.

I believe `Zoom` worked when I tried a few months back. I’ll confirm next week.

**Comment by JumperPunk** [comment]
How did you get zoom screen sharing to work?

**Comment by cherusk** [comment]
Yes, this is a very generic issue and I wanted to open it myself today. Haven't seen any solution on sway roadmap, would be great to get visibility on whether this can be tackled in one sweep and by when it's planned.

**Comment by cherusk** [comment]
@JonasKs , might turn this into a feature request!

**Comment by JonasKs** [comment]
Honestly i haven’t tried zoom in a few months, so now I’m not sure if my memory is tricking me. Going to edit my comment and try Zoom again this week.

**Comment by cherusk** [comment]
Found quite a decent impromptu workaround which suffices until sway more native screen sharing matures.

1) put all your "communicators", all software that requires screen sharing (slack, google meet) into some seperate, micro run time that is sitting on some X server on your host, I'd suggest https://github.com/mviereck/x11docker as it's super light weight. Also put a remote desktop client software of your choice.
2) Spin up some remote desktop serving agent on your host, my choice was https://github.com/any1/wayvnc (requires sway 1.4 though!)
3) Connect from your runtime via VNC (or whatever protocol of your choice) to your host running sway.
4) Now you can share screen in your micro runtime the screen showing the host VNC session

**Comment by JonasKs** [comment]
That's an interesting approach indeed. I'll check it out!

**Comment by ddevault** [comment]
Closing because this isn't actionable.

**Comment by trougnouf** [comment]
Some applications work with Teams on Chromium when they are both running through xwayland.
