### ISSUE TITLE
sway doesn't send 'wl_keyboard::{enter,leave}' during TTY switch

### ISSUE THREAD

**Issue by kchibisov** [swaywm/sway#5085]
During TTY switch sway removes `pointer` and `keyboard` capability from a `seat`, so clients should release them. This behavior is absolutely correct, however it doesn't send `wl_keyboard::enter/leave` events(same for pointer and touch, I think). While not sending `leave` during going from sway to TTY I could understand, I think that not sending `enter` when returning from TTY to sway seems strange, since client should create a new `wl_keyboard` after `seat` regains `keyboard` capability. So if you start typing after TTY switch, your currently focused client gets key events without `enter` before for its new `wl_keyboard` object. This could break some clients which start accepting input after getting `enter` event.

I feel like clients shouldn't rely on `wl_keyboard::enter` here in this scenario, right?

sway version 1.4-fafc0609

debug log:

[sway_log_enter_leave.log](https://github.com/swaywm/sway/files/4307439/sway_log_enter_leave.log)

**Comment by ianyfan** [comment]
Seems to be the same as https://github.com/swaywm/sway/issues/3244
