### ISSUE TITLE
Eclipse windows flicker

### ISSUE THREAD

**Issue by JonnyMako** [swaywm/sway#5087]
I'm seeing bad window flicker in Eclipse. Started happening in the last couple of days. I see this in the log. This is for the initial splash screen, but the same thing is happening with the regular window/tabs in Eclipse.
```
(Eclipse:3358): Gtk-WARNING **: 11:41:10.120: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)
00:01:52.472 [types/wlr_surface.c:615] New wlr_surface 0x5610fba4da80 (res 0x5610fba316a0)
00:01:52.472 [types/xdg_shell/wlr_xdg_surface.c:458] new xdg_surface 0x5610fba31b50 (res 0x5610fba38fe0)
00:01:52.472 [sway/desktop/xdg_shell.c:493] New xdg_shell popup
```
```
sway version 1.4-fafc0609 (Mar  9 2020, branch 'master')
```
Is this Eclipse or Sway?

**Comment by emersion** [comment]
Can you try xwayland master? xwayland recently had some issues with its buffers.

**Comment by JonnyMako** [comment]
I think Eclipse is running natively in Wayland with GTK3. If I run with `GDK_BACKEND=x11` there is no flicker.

**Comment by JonnyMako** [comment]
Here are the offending commits:
Sway: 9d0aa0cb
Wlroots: https://github.com/swaywm/wlroots/commit/8afc1ed68cfaab0c85dd3252f7680d0a6e9e511e

**Comment by emersion** [comment]
Can you try https://github.com/swaywm/wlroots/pull/2061?

**Comment by JonnyMako** [comment]
Yes, that fixed it. Thanks!
