### ISSUE TITLE
Sway keeps adding the same tablet PAD device multiple times

### ISSUE THREAD

**Issue by ofourdan** [swaywm/sway#5093]
* Sway Version:

sway version 1.4-fafc0609 (Mar 11 2020, branch 'master')

* Debug Log:

[sway.log.gz](https://github.com/swaywm/sway/files/4318863/sway.log.gz)

* Configuration File:

Irrelevant

* Stack Trace, if sway crashes:

[sway-bt.txt.gz](https://github.com/swaywm/sway/files/4318882/sway-bt.txt.gz)

* Steps to reproduce:

https://gitlab.freedesktop.org/xorg/xserver/issues/995#note_433460

* Additional info

This was investigated as a part of an issue reported to Xwayland on instructions from sway developpers.

https://gitlab.freedesktop.org/xorg/xserver/issues/995

As it turns out, I reckon this is a bug with `sway` instead, and that following patch in `sway` fixes it:

[0001-input-Avoid-creating-the-PAD-device-multiple-times.patch.gz](https://github.com/swaywm/sway/files/4318898/0001-input-Avoid-creating-the-PAD-device-multiple-times.patch.gz)

That fixes both the crash in `sway` but also he crash in `Xwayland` and also the same pad devices being added several times on reload.

**Comment by Xyene** [comment]
This seems like it might also be the root cause of https://github.com/swaywm/wlroots/issues/2062, since the reproduction steps are identical (though the backtraces differ).

**Comment by emersion** [comment]
@Xyene Can you try out this patch?

**Comment by Xyene** [comment]
It fixes the issue I filed against `Xwayland` (thanks!) on a real non-emulated device. I didn't have a very reproducible setup for the wlroots bug, but I wasn't able to reproduce it with this patch.

Firefox continues to crash if it has focus while the tablet is disconnected (matches the destroy events, I think), though this doesn't happen in GNOME. This sounds like it might be a related, but separate, issue.
