### ISSUE TITLE
Invisible window cannot update its title

### ISSUE THREAD

**Issue by maximbaz** [swaywm/sway#5104]
We can use terminals as a simple way to predictably change window titles.

With no custom sway config, on an empty workspace open a terminal and run the command below to update its title - this works well.

```
printf "\e]2;%s\a" "one"
```

Now open a second window in a split, run the command below in a terminal and focus on a second window (so that terminal stays unfocused when title will be changed) - this works just as well, title is updated.

```
sleep 5s && printf "\e]2;%s\a" "two"
```

Finally switch layout to the tabbed window, run the command below and focus on another window, so that terminal is not only unfocused, but invisible as the other window is visible - this time, terminal title will **not** get updated until you make the window visible again.

```
sleep 5s && printf "\e]2;%s\a" "three"
```

**Expected:** since I as a user can see the title bar of this invisible window, it should be allowed to update even if the window itself is not visible. My workflow might depend on it, for example I can have a script that updates terminal window title once an execution of a long-running command finishes, and switch to a different tab waiting for the command to complete.

```
sway: 1.4
wlroots: 0.10.1
```

Debug log: https://paste.maximbaz.com/aaea53d3f8d2

**Comment by emersion** [comment]
I think we (incorrectly) wait for a `commit` before updating the window title.

**Comment by kchibisov** [comment]
It seems like a client bug and not like a sway bug, since it's likely due to your terminal blocking, when it's hidden. I can't repro your issue with latest alacritty, which is using frame callbacks, so its event loop is never blocks, however I can repro that when alacritty were using mesa vsync, so it was blocking when it was hidden. So I think it's your terminal bug and not sway.

**Comment by kchibisov** [comment]
Though, `WAYLAND_DEBUG=1 your_terminal 2> out.txt` is likely more useful here, since it could show, whether app requested title change or not. Look for something like 
```
xdg_toplevel@26.set_title
```

**Comment by emersion** [comment]
That makes sense. Can you obtain a debug log, @maximbaz?

**Comment by maximbaz** [comment]
You are right! If I run `sleep 5s && printf "\e]2;%s\a" "two"` and make the window invisible, all that will be printed after 5s interval is `wl_surface@21.frame()` and `wl_surface@21.commit()`, `set_title` will not be printed until I make the window visible again. I'll continue the discussion in the terminal's bug tracker. Thanks!
