### ISSUE TITLE
Segfault on startup

### ISSUE THREAD

**Issue by ammgws** [swaywm/sway#5106]
sway version 1.4-7dd9cd29 (Mar 14 2020, branch 'makepkg')

[sway --config /etc/sway/config --debug 2&> /tmp/swaydebuglog](https://gist.github.com/ammgws/563e779108bb70b9affe48c97b99479f)

[backtrace](https://gist.github.com/d686def74f3219e9fbd117bf10a68b98)

have downgraded to sway 1.4 release for now

**Comment by TheConfuZzledDude** [comment]
I've been getting the same problem. Interestingly, when run from a TTY it doesn't always segfault, it just crashes silently

[sway -c /etc/sway/config -d 2&> sway.log](https://gist.github.com/TheConfuZzledDude/91de2553d8a90f919faaf4860c65d493)

Also, reverting to 1.4 doesn't work for me, it launches, and I can see the cursor, and programs are clearly running (redshift works for example, and focus changes when I open a window in the scratchpad), but both screens are completely grey.
[The same, but on 1.4](https://gist.github.com/TheConfuZzledDude/6fec75925ceb934546a2b5008d0b2eed)

I'm going to assume that it's probably a graphics driver issue?

**Comment by ammgws** [comment]
> I'm going to assume that it's probably a graphics driver issue?

Not sure since my last driver update was around a week before this (opencl-amd), and the ones before that (mesa stuff) were in February. I thought that maybe I could find some recent commits in sway/wlroots that might cause this but haven't seen anything that looks relevant.

**Comment by TheConfuZzledDude** [comment]
Well we both have AMD GPUs, and this only started happening to me after updating Linux to 5.8, so it could be a kernel issue. I'll try downgrading to 5.7 or something and see

**Comment by TheConfuZzledDude** [comment]
Actually, updating to the latest wlroots-git and sway-git seems to have fixed this for me

**Comment by ammgws** [comment]
Yeah it's fixed for me now too.

Things that changed in between:

**sway related**
wlroots-git: `0.10.0.r48.g1282c3b1-1` `to 0.10.0.r49.g5ee52a3a-1`
Just [this](https://github.com/swaywm/wlroots/commit/5ee52a3ab9a12adb157738dc3fba72137c3c6879), but don't think it's relevant

sway-git: `r6258.55016729-1` to `r6261.6498542b-1`
Only new commits are from me and they're irrelevant

swaybg-git, swayidle-git, swaylock-git unchanged

**other**
linux-headers (5.5.8.arch1-1 -> 5.5.9.arch1-2)
linux (5.5.8.arch1-1 -> 5.5.9.arch1-2)

**Comment by emersion** [comment]
Please re-open if you can reproduce again

**Comment by ammgws** [comment]
Out of interest I reverted to the 5.5.8 kernel but it didn't result in a segfault. Oh well. Would have been nice to find out what it was.
