### ISSUE TITLE
Firefox (xwayland) occasionally stops receiving keyboard events

### ISSUE THREAD

**Issue by schauveau** [swaywm/sway#5114]
During the last 2 weeks, I noticed several times that my Firefox window (the X11 version) stops responding to keyboard events. Firefox still responds to the mouse. Fortunately, I can restore the keyboard by switching to another workspace. I am a bit puzzled by that behavior. I could not find a way to reproduce that behavior but I have the feeling that this happens after actions such as exiting fullscreen mode, switching windows, or transforming a tab into a window. That is why I suspect that this is a problem with Sway or with XWayland.  

A few information that may be relevant:

- Sway 1.4 (from Debian Testing). I started noticing the problem soon after starting using the debian package. I was previously using a slightly older git build.  
- Firefox 74 (installed in home dir, not debian package) but I am pretty sure that the problem existed with Firefox 73.
- I have almost no Firefox extensions: Adblock plus and another one to cast URLs to Kodi.
- This is specific to the X11 version so via XWayland. The Wayland version of Firefox (with GDK_BACKEND=wayland) does not seem to be affected. 
- Sway log file in https://gist.github.com/schauveau/fc74374d924a34cf1113cfc1e484e3bf  with the bug occurring near the 17:09:09 mark (the last line). Those xcb errors are quite suspicious but they seem to occur quite often when I close X11 windows so they may not be related to my problem.

**NOTE**: Interestingly, the problem just happened while I was typing this bug report. I opened the "Help/About Firefox" menu to get my Firefox version and, after closing the dialog, the keyboard focus was lost in the main Firefox window. Even better, it seems that this behavior is reproducible. 

I have the following in my sway config to insure that this specific dialog is floating:
 
    for_window [class="Firefox" window_role="About"] floating enabled ; border normal 5

**Comment by emersion** [comment]
Fixed in master.

**Comment by schauveau** [comment]
Thanks. Is there another bug report about that problem?

**Comment by emersion** [comment]
https://github.com/swaywm/sway/issues/4926
