### ISSUE TITLE
Nested sway duplicates keyboard

### ISSUE THREAD

**Issue by brandsimon** [swaywm/sway#5119]
sway version: 1.4
wlroots: 0.10.1-1

I run a nested sway and at some point, when I press one key, the key is pressed several times. Also there are multiple keyboard input devices. I dont know how to reproduce it exactly, it just happens after a very long period of time.
A similar problem was fixed in #5055 (when switching vt).
get_inputs: http://sprunge.us/QZWkM0
debug log: http://sprunge.us/0R90iM

**Comment by emersion** [comment]
The bug has only been fixed in wlroots master.

**Comment by brandsimon** [comment]
@emersion 
Ah, interesting, because this issue happens way less with  wlroots 0.10.1  than  wlroots 0.10.0, so I thought, it was fixed.
