### ISSUE TITLE
sway forgets keyboard layout when wayvnc is started

### ISSUE THREAD

**Issue by d4g** [swaywm/sway#5120]
# Description
I am using a special keyboard configuration in sway. If I start wayvnc, sway "forgets" the keyboard options I have set, until I reload the configuration with ctrl-c.
I also tried to set those settings manually via swaymsg and it did not work. While there was no error message, the settings were note changed

# How to reproduce
- Set custom keyboard layout as noted below
- Start swayvnc from master branch
- Observe change of keyboard layout

# According configuration
sway/config:
```
input type:keyboard { 
  xkb_layout de
  xkb_variant us
  xkb_options lv3:caps_switch
}
```

Trying to set the configuration via swaymsg:
```
swaymsg input type:keyboard xkb_layout de  
swaymsg input type:keyboard xkb_variant us
swaymsg input type:keyboard xkb_options lv3:caps_switch
```

Excerpt of output of swaymsg -t get_inputs in error case
```
Input device: Wooting WootingOne
  Type: Keyboard
  Identifier: 1003:65281:Wooting_WootingOne
  Product ID: 65281
  Vendor ID: 1003
  Active Keyboard Layout: English (US)
  Libinput Send Events: enabled
```

Excerpt of output of swaymsg -t get_inputs after reloading config
```
Input device: Wooting WootingOne
  Type: Keyboard
  Identifier: 1003:65281:Wooting_WootingOne
  Product ID: 65281
  Vendor ID: 1003
  Active Keyboard Layout: German (US, with German letters)
  Libinput Send Events: enabled
```

# Metadata
```
swaymsg -t get_version
sway version 1.4
```

**Comment by emersion** [comment]
Your bug report is missing debug logs. Please add a link to the full debug log file.

**Comment by d4g** [comment]
There is no error log yet. I will try to provide one in the future, e.g. next session.

**Comment by d4g** [comment]
I have pinned down the issue.
This issue occurs as soon as I start wayvnc. After I start wayvnc, capslock immediately is working as capslock again instead of lvl3 switch.

I don't know it this is a wayland, wayvnc or wlroots issue. Does this help?

**Comment by d4g** [comment]
@any1 could you probably have a look?

**Comment by any1** [comment]
I have some more interesting things for work on, but I'll time-box it to an hour and see what I can come up with.

**Comment by d4g** [comment]
I close this issue in favor or https://github.com/any1/wayvnc/issues/26.
