### ISSUE TITLE
Intermittent - outputs go "negative colors" in Wayland/Sway

### ISSUE THREAD

**Issue by ohthehugemanatee** [swaywm/sway#5121]
Regularly (but not predictably) when enabling an output, it seems to get stuck in a sort of "negative" color mode, like the external monitor in this photo:

![photo of the display issue](https://user-images.githubusercontent.com/907257/76946934-1cf82980-6905-11ea-82e4-2c841e1a8312.jpg)

I'm having trouble even determining at what layer of the stack this happens. It's fine in XOrg, this issue only appears in Sway.

Any help is greatly appreciated!

## Symptoms

Once it's started, the output stays like that. I can unplug/replug, switch ports on my computer, change resolution, disable/enable through swaymsg, go through a docking station + DisplayPort, go directly through HDMI, disable/enable... no difference.  

Switching to a display with Xorg running, the colors are fine over there. No problems at all. This only happens in Sway/Wayland.

Oddly, Wayland seems to think it's outputting just fine. Here's a screenshot of the same made with `grim`:

![screenshot with grim](https://user-images.githubusercontent.com/907257/76946864-fdf99780-6904-11ea-820b-877fad0af569.png)

I can go back to normal by exiting Sway to SDDM and logging back in. (Exit/restart sway when running from the console does not fix it).

## Triggers

"When enabling an output" is vague, but it's the only commonality I can think of. I've had it happen:

* Using `swaysm output DP-3 dpms off`/`on`
* Using `swaywm output DP-3 toggle`
* Unplugging and plugging the monitor back in
* Switching to/from Xorg

The last one is most reliable Often when switching back from XOrg it happens to BOTH outputs, external and internal.  

Sway 1.4
I didn't see anything unusual in debug log, so I didn't attach it. Happy to do so if it's helpful.

**Comment by emersion** [comment]
A gamma-related issue has recently been fixed in wlroots.

Can you try again with the latest wlroots and Sway commits? See https://github.com/swaywm/sway/wiki/Development-Setup#compiling-as-a-subproject

**Comment by ohthehugemanatee** [comment]
@emersion that was the fastest response I've ever seen on a github issue. Thank you!

Trying now.

**Comment by ohthehugemanatee** [comment]
Well that's a whole work day gone without seeing the issue! I guess this is exactly the fix. Thank you!
