### ISSUE TITLE
sway debug log leaks personal information

### ISSUE THREAD

**Issue by d4g** [swaywm/sway#5122]
After opening issue #5120 , I wondered if the debug logs contain any critical information. After looking through an attached debug log of another issue, I could see that the debug logs contain:
- Information about the local username
- Information about local paths and configured background images
- All started applications incl. parameters
- Partially logs of applications started by exec
- Comments of the config file (!)
- __Window names, titles and properties including open URLs in Chromium for example__

Especially the window name leaks information about the user, as his __current google searches, open windows__, etc.

I'd suggest to either switch change the debug logs to anonymize, strip or encrypt relevant data and/or to change the process of submitting them via pastebin, as this puts users at risk.

**Comment by ddevault** [comment]
This is by design.

**Comment by d4g** [comment]
You are asking users to leak personal information to pastebin by design?
