### ISSUE TITLE
Opening Wayland-native terminal damages Firefox

### ISSUE THREAD

**Issue by Xyene** [swaywm/sway#5123]
When opening a Wayland-native terminal (reproduced with `kitty` and `alacritty`) beside a Firefox (Developer Edition, 75) window, it looks like the top-left corner of Firefox is damaged.

![image](https://user-images.githubusercontent.com/1403503/76988820-be8a7580-691b-11ea-9120-9191dd897164.png)

I've recorded [a short clip of the behaviour](https://drive.google.com/open?id=1yDcOGKf3bBtR8wobJgAohOUCyBPjXNYe).

Firefox receives no events (as per `WAYLAND_DEBUG=1`) during this time.

I'm currently running sway master, on Debian 10 with an AMD GPU, and would be happy to provide any other details that may be useful.

**Comment by ifreund** [comment]
Are you running firefox with `MOZ_ENABLE_WAYLAND=1`?

**Comment by Xyene** [comment]
Yes, I am. The same doesn't happen with Firefox through Xwayland.

The damaged region *seems* to be the exact size of the initial window created by e.g. `kitty`, prior to receiving the appropriate resize event to fill its tile:

![](https://user-images.githubusercontent.com/1403503/76991267-ab79a480-691f-11ea-8bf5-04726777160e.png)

**Comment by Xyene** [comment]
To add onto this, incidentally the workaround from a bug that I'm also experiencing (from the Mozilla Bugzilla), [[Wayland] Entire window flickers, showing underlying desktop/applications, when resizing window on sway](https://bugzilla.mozilla.org/show_bug.cgi?id=1585314) -- running sway with `-Dnoatomic` -- also seems to work around this issue.

**Comment by ifreund** [comment]
Perhaps firefox is taking too long to redraw and the sway transaction is timing out.  Could you see if running with `-Dtxn-timeout=1000` fixes it? Perhaps the default of 200ms is too low for your setup.

**Comment by Xyene** [comment]
@ifreund thanks for the hint, I tried it but it didn't seem to have any effect. I also tried with `-Dtxn-timeout=10000`, just to be sure. I'm running with an AMD RX 480 GPU and a Ryzen 3900X, so while it's possible, I would hope I'm not under-specced to run Firefox with default settings :)

**Comment by Xyene** [comment]
This looks like it has been fixed through https://github.com/swaywm/sway/pull/5403; I can no longer reproduce this on master, even without `-Dnoatomic`. Thanks @kennylevinsen!
