### ISSUE TITLE
Eclipse (wayland) not respecting scaling

### ISSUE THREAD

**Issue by JonnyMako** [swaywm/sway#5133]
I have the following to scale one of my external monitors. However, when I try to use eclipse (wayland) on that screen, only some of the UI elements are scaled correctly, like menus, dialogues, pop-up windows etc. Everything else that is on screen is scaled to something extremely tiny. Even smaller than 1. I'm guessing something like 0.5. Is this Eclipse or Sway?

`output DP-3 pos 1920 0 res 3840x2160 scale 1.5`

[swayeclps.log](https://github.com/swaywm/sway/files/4371325/swayeclps.log)

**Comment by JonnyMako** [comment]
Looks like this issue?
https://bugs.eclipse.org/bugs/show_bug.cgi?id=541370

**Comment by Xyene** [comment]
Yes, it doesn't look like much can be done on sway's end. I noticed you already bumped up the issue in the Eclipse tracker, so I'm going to close this one here.
