### ISSUE TITLE
virtual-keyboard overrides all keyboard layouts

### ISSUE THREAD

**Issue by any1** [swaywm/sway#5134]
Steps to reproduce:
 * Run sway with a wayland backend: `WLR_BACKENDS=wayland sway`
 * Check keyboard layout in sway session: `swaymsg -t get_inputs`
 * Run wayvnc inside the session or in another shell: `WAYLAND_DISPLAY=wayland-1 wayvnc --keyboard=is`
 * Check the keyboard layout again and note that both "keyboards" now have the Icelandic layout.

This does not happen if smart grouping is turned off.

Looking at the debug log, I can see that the virtual keyboard always matches the group of the incumbent keyboard, which ought not happen with different layouts.

I have a theory that because virtual-keyboard sets the layout after it has created (and thus assigned to a group) the group's keyboard layout changes with the virtual keyboard's layout.

**Comment by emersion** [comment]
The virtual keyboard should definitely not be grouped with something else.

**Comment by any1** [comment]
I've been thinking about how to disable smart grouping specifically for virtual keyboards and there does not seem to be an obvious answer. Matching on "virtual_keyboard" inside sway/input/keyboard.c seems like a rather finicky solution. Perhaps there should be a special "vendor" set for virtual devices, and that can be used for matching?

**Comment by emersion** [comment]
Isn't it easy to detect keyboards created with the virtual-keyboard protocol?

**Comment by any1** [comment]
Never mind, there's a special event for it.
