### ISSUE TITLE
Scale, but don't upscale

### ISSUE THREAD

**Issue by BlackCapCoder** [swaywm/sway#5136]
Scale does two seemingly unrelated things: for every window, if it is HiDPI aware then it gets to render its HiDPI friendly interface at full native resolution- otherwise it forcibly is up-scaled.

I would like to have the first, but not the latter. I absolutely, under no circumstances want any window to be up-scaled, but if it is HiDPI aware then I would like its HiDPI interface.

I propose we add a new `no_upscale` option to `output * scale_filer`, that politely ask every window to render at the given scale, but otherwise does nothing.

**Comment by ddevault** [comment]
This has already been extensively discussed.
