### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by gitmac777** [swaywm/sway#5140]
Sway consumes always 20-100% CPU resources. I use a ROCK64 single-board computer (RK3328 Quad-Core ARM Cortex A53 64-Bit Processor) with Alpine Linux v3.11 (with Mainline Kernel 5.4.15). The problem also exists if i use the Kernel from Armbian.

[Installed APKs.txt](https://github.com/swaywm/sway/files/4383806/Installed.APKs.txt)
[SWAY log.txt](https://github.com/swaywm/sway/files/4383808/SWAY.log.txt)
[Kernel-config-5.4.15.txt](https://github.com/swaywm/sway/files/4383972/Kernel-config-5.4.15.txt)

Thank you in advance for your help
[perf.data.zip](https://github.com/swaywm/sway/files/4397516/perf.data.zip)
[perf report.txt](https://github.com/swaywm/sway/files/4397518/perf.report.txt)
![flamegraph](https://user-images.githubusercontent.com/62674616/77829253-c5ce3200-7118-11ea-9e7e-2c0611ebec44.png)

**Comment by emersion** [comment]
A `perf` record could be helpful to figure out what uses CPU.

**Comment by gitmac777** [comment]
I can't use perf on Alpine Linux (no perf package available), would strace be helpful or maybe a other tool?

**Comment by gitmac777** [comment]
I have uploaded the perf record files (made with Armbian)

**Comment by Emantor** [comment]
Your renderer is `llvmpipe` which is the software rendering by mesa done on the CPU.

**Comment by gitmac777** [comment]
Thanks for the help! I must use rockchip_dri.so
