### ISSUE TITLE
Fractional scaling issues with Xwayland

### ISSUE THREAD

**Issue by mro95** [swaywm/sway#5142]
Sway version 1.4

I have a 27" 4K monitor (1.5x scaling) and I'm using sway for a few days. When I try to open something like Firefox in xwayland. I see weird font artifacts. To prove its not only a Firefox issue i made a screenshot from the settings window in IntelliJ IDEA.

Screenshot 1: Made with maim (xwayland)
https://i.imgur.com/WybCPQy.png

Screenshot 2: Made with grim (native wayland)
https://i.imgur.com/uplD53x.png

As you see the font and icons looks weird in de second screenshot, but not in the first screenshot. This it why I believe it's a sway issue.

_Firefox screenshots_
maim: https://i.imgur.com/shUlzls.png
grim: https://i.imgur.com/TEgPZdV.png

**Comment by emersion** [comment]
This is an xwayland bug, fixed in master. If you can reproduce with xwayland master, let us know.

**Comment by mro95** [comment]
Thanks it's better, but still blurry.
