### ISSUE TITLE
Pointer leave event is triggered when touch down occurs

### ISSUE THREAD

**Issue by gg-rewrite** [swaywm/sway#5145]
Hello.

Pointer leave event is triggered whenever touch down occurs. This is specifically sway's behaviour as it doesn't happen in e.g. wayfire. I'm not sure if this is a bug  or a feature, so I'd like some clarification.

Thanks.

**Comment by emersion** [comment]
Pretty sure this is a bug. Touch and pointer events should be completely separate.

**Comment by gg-rewrite** [comment]
The root cause is cursor_hide function which invariantly calls wlr_seat_pointer_clear_focus. The latter indirectly emits a pointer_leave event.

In comparison, as far as I understand, wayfire has some logic for picking up a suitable surface to transfer focus to and calling wlr_seat_pointer_notify_enter, or wlr_seat_pointer_clear_focus if none is found.

I'm not sure what the correct logic should be for this one. Should it be "find a suitable surface to transfer focus to" or will "don't clear focus if touch event" suffice?

**Comment by emersion** [comment]
Ah, I see why this is an issue. Indeed, hiding the cursor should emit a `wl_pointer.leave` event.

I think everything should be fine if `wl_pointer.leave` happens before any touch event? Is that the case?

**Comment by gg-rewrite** [comment]
```@@ -364,9 +364,9 @@ static void handle_touch_down(struct wl_listener *listener, void *data) {
 
        // TODO: fall back to cursor simulation if client has not bound to touch
        if (seat_is_input_allowed(seat, surface)) {
+         cursor_hide(cursor);
                wlr_seat_touch_notify_down(wlr_seat, surface, event->time_msec,
                                event->touch_id, sx, sy);
-               cursor_hide(cursor);
        }```
 
        seat_set_focus(seat, focused_node);`

Seems like yes, this is the case. Hiding cursor before sending a touch down event instead of after alleviates the initial problem in emersion/slurp#29. Should I send a PR with this fix or is there some other solution?

**Comment by emersion** [comment]
As explained in the slurp PR, clients _should_ be able to cope with a pointer leave event happening after a touch down. However hiding the cursor before triggering the touch events sounds like a more logical thing to do anyway, so I'd accept a PR doing that.

**Comment by gg-rewrite** [comment]
And done #5170.
