### ISSUE TITLE
Question about scrolling

### ISSUE THREAD

**Issue by plattfot** [swaywm/sway#5146]
Hi,

I've been enjoying sway for a while now, been really solid. Thank you for all your hard work creating it!

Now on to my question. I recently bought a [Kyria](https://splitkb.com/) split keyboard. Which I have a rotary encoder as one of the buttons. I have set this to mimic a scroll wheel on a mouse. All works fine and I can scroll using that.

But a slight annoyance is that the scroll follows the mouse pointer. Therefore I have to move the mouse to hover over the window I want to scroll in. Which kind of defeats the purpose of having the scroll on the keyboard.

Is there a way to change that a certain input mouse (Kyria in this case), that the scroll works on the window I have focused and not where the mouse is?  I still want the behavior of scrolling where the pointer is for my real mouse.

I checked the manpages but couldn't find anything.

Thanks

**Comment by emersion** [comment]
I don't think that's possible. Clients expect to know where the mouse is to decide what UI element to scroll (e.g. if there are two scrollbars). The scroll events can only be sent when the pointer has entered a surface.

**Comment by plattfot** [comment]
I was suspecting that be the case. Think I'll switch to send page up/page down instead.
Thanks for the quite response, I'll close this issue.
