### ISSUE TITLE
PDF viewer applications cannot open remote files

### ISSUE THREAD

**Issue by TheChymera** [swaywm/sway#5147]
I did not initially believe this to be a sway issue, but nobody else seems to have any ideas (Gentoo Linux IRC, and [evince issue tracker](https://gitlab.gnome.org/GNOME/evince/-/issues/1358)). The main difference between the system on which I have this issue and all the other systems on which I do not, is that it uses sway/wayland.

Basically, I am trying to open a remote file with evince (though I have also confirmed it with Atril), using `evince https://chymera.eu/articles/ofmhost_drlfom.pdf`. The window opens, but claims it cannot open the temp file. The temp file is indeed being created and has the correct permissions, but size zero. 

The sway log (see below) does contain some info about the attempted download, but I can't figure out whether and what is wrong with it.

* Sway Version:

```
[I] gui-wm/sway
     Available versions:  1.4 **9999*l {X elogind fish-completion +man +swaybar +swaybg +swayidle +swaylock +swaymsg +swaynag systemd tray wallpapers zsh-completion}
     Installed versions:  1.4(10:37:20 AM 02/25/2020)(X elogind man swaybar swaybg swayidle swaylock swaymsg swaynag tray -fish-completion -systemd -wallpapers -zsh-completion)
     Homepage:            https://swaywm.org
     Description:         i3-compatible Wayland window manager
```

* Debug Log:

[sway.log](https://github.com/swaywm/sway/files/4391898/sway.log)

* Configuration File:

[config.txt](https://github.com/swaywm/sway/files/4391902/config.txt)

**Comment by Emantor** [comment]
FWIW, this works fine for me on Arch Linux with latest sway master. IMO should be closed since this is not a sway issue. What does Evince use to download the file? Maybe there is a bug in the download path which results in an empty file.

**Comment by TheChymera** [comment]
@Emantor I'm not sure if that's an external application. Could you maybe list the files which evince installed for you on arch? [This](https://github.com/swaywm/sway/files/4392292/evince_files.txt) is what I have.

**Comment by Emantor** [comment]
[Here](https://github.com/swaywm/sway/files/4392387/evince_arch_files.txt) is a listing from my arch system.

**Comment by prometheanfire** [comment]
It's working here for me on gentoo, current stable sway and wlroots
