### ISSUE TITLE
Sway does not work with mouse

### ISSUE THREAD

**Issue by gitmac777** [swaywm/sway#5154]
If i use "/usr/lib/aarch64-linux-gnu/dri/rockchip_dri.so" with Armbian i can not use a mouse because if a mouse is connected it is not possible to start a program or terminal. Cpu usage are 1-30%. There is the same problem if i use "/usr/lib/xorg/modules/rockchip_dri.so" with Alpine Linux, cpu usage are ok. If i use only kms_swrast_dri.so / swrast_dri.so it works but its too slow...

Always if I disconnect the keyboard or mouse, i can no longer connect it because it is not recognized again, if i close sway usb devices are working correctly. 

I use a ROCK64 single-board computer (RK3328 Quad-Core ARM Cortex A53 64-Bit Processor).

[swaylog 1.txt](https://github.com/swaywm/sway/files/4397996/swaylog.1.txt)
[swaylog 2.txt](https://github.com/swaywm/sway/files/4397997/swaylog.2.txt)
[perfreport 1.txt](https://github.com/swaywm/sway/files/4397999/perfreport.1.txt)
[perfreport 2.txt](https://github.com/swaywm/sway/files/4398000/perfreport.2.txt)

**Comment by travankor** [comment]
use the panfrost driver.

**Comment by emersion** [comment]
If you use proprietary drivers, you're on your own. We can't help you because we can't read the source.

**Comment by gitmac777** [comment]
Thanks for your answers. I found out i can use the mouse with WLR_NO_HARDWARE_CURSORS=1. 
Sway doesn't start without rockchip_dri.so or kms_swrast_dri.so / swrast_dri.so: 
https://github.com/swaywm/sway/issues/5219
