### ISSUE TITLE
Latte dock in Sway

### ISSUE THREAD

**Issue by Avi-D-coder** [swaywm/sway#5165]
latte dock has plasma wayland support, but it won't open in sway.

From @ddevault 's [blog](https://drewdevault.com/2018/04/28/KDE-Sprint-retrospective.html).
> I wrote up a C++ library that extends Qt with layer-shell support called qtlayershell, and extended the popular Latte Dock KDE extension to support it.

The link to https://github.com/ddevault/qtlayershell works, but the link to latte dock does not. Do the modifications to latte still exist. The maintainer of latte never got the the code.

If the code no longer exists is qtlayershell still useful or has to much changed since 2018.

**Comment by emersion** [comment]
Closing because this isn't a Sway issue.

**Comment by emersion** [comment]
Apparently the repo is unlisted: https://git.sr.ht/~sircmpwn/latte-dock

**Comment by Avi-D-coder** [comment]
Thanks

**Comment by WillPower3309** [comment]
The qtlayershell link is also now broken, does it still exist

**Comment by WillPower3309** [comment]
> The qtlayershell link is also now broken, does it still exist?

Realized it's unlisted in the same site mentioned above for anyone else wondering

**Comment by psifidotos** [comment]
I could definitely accept such patches as long as they dont break the main plasma experience. I didnt know there was a branch I could look about the latte changes  to support this.

**Comment by WillPower3309** [comment]
> I could definitely accept such patches as long as they dont break the main plasma experience. I didnt know there was a branch I could look about the latte changes  to support this. 

@ddevault any comments? With the now archived qtlayershell being a dependency of your latte dock fork, what would need to be done to make this happen, and is it feasible within the plasma first constraints?

**Comment by tmpm697** [comment]
any news on this?

**Comment by WillPower3309** [comment]
I recently noticed https://github.com/KDE/layer-shell-qt
I haven't delved deep into how it compares to ddevault's implementation but if it is a functionally modern equivalent, it should be relatively easy to get latte dock working! I'll have a go at it this weekend (post midterm week :p )

**Comment by psifidotos** [comment]
I managed to implement basic support for Layershell for Latte. It works kind of under KWin but the biggest issue are popups and context menus, they appear fullscreen. Nonetheless I will upload a branch in order to track progress. I hope will Plasma eventually support Layershell so Latte will get the relevant fixes on the fly.

**Comment by psifidotos** [comment]
For anyone interested in that.
Branch: https://invent.kde.org/plasma/latte-dock/-/tree/m_layershell
Discussion: https://invent.kde.org/plasma/latte-dock/-/issues/95

**Comment by WillPower3309** [comment]
> I managed to implement basic support for Layershell for Latte. It works kind of under KWin but the biggest issue are popups and context menus, they appear fullscreen. Nonetheless I will upload a branch in order to track progress. I hope will Plasma eventually support Layershell so Latte will get the relevant fixes on the fly.

Wow absolute king! Thank you a ton, I will try to use this on my system and provide whatever feedback I can
