### ISSUE TITLE
Cycle through fullscreen windows

### ISSUE THREAD

**Issue by dschrempf** [swaywm/sway#5171]
Hi!

I am trying to setup a keybinding switching through fullscreen windows on the focused workspace.

I came up with `bindsym $mod+n fullscreen, focus next, fullscreen`, but this binding is really laggy. Is there something more appropriate that can be used?

**Comment by Xyene** [comment]
I think it would be best to ask around in IRC (#sway on Freenode) than on this tracker, since there are other users in there that could share tips and tricks.
