### ISSUE TITLE
Different binding for fullscreen mode

### ISSUE THREAD

**Issue by dschrempf** [swaywm/sway#5172]
Is it possibe to have a different binding for `$mod+j` when in fullscreen mode? I would like to cycle through fullscreen windows, when in fullscren mode, but use the normal `focus down` otherwise.

Thank you!

**Comment by dschrempf** [comment]
I just found that there is the `mode` command. So one could switch to `mode "fullscreen"` when entering fullscreen mode. Is this the correct way to go?

**Comment by Xyene** [comment]
I think it would be best to ask around in IRC (#sway on Freenode), since there are other users in there that could share tips and tricks.
