### ISSUE TITLE
Reset layout

### ISSUE THREAD

**Issue by dschrempf** [swaywm/sway#5173]
Sorry to bother you with mutiple issues, but I am just trying to setup `sway` after having used `xmonad` for a long time.

Is there a way to reset the layout on a workspace to what one would get by just opening different windows. Basically, a command to revert any layout changes, resizes, or container changes?

**Comment by Xyene** [comment]
Same suggestion as in the other tickets, if you still have this issue, I'd recommend popping in on IRC :)

**Comment by dschrempf** [comment]
I just came across this after moving away from Sway and coming back. I don't find any other issues answering this question when searching for "reset layout". Could you please point me to the issues you mention?
