### ISSUE TITLE
Korean layout works as english.

### ISSUE THREAD

**Issue by WhyNotHugo** [swaywm/sway#5183]
```
➜ swaymsg -t get_version
sway version 1.4
➜ sway -v
sway version 1.4
```

I'm trying to configure my keyboard in Korean (I'm trying to learn to type it), but setting the layout to korean doesn't seem to work.

If I run `swaymsg input "*" xkb_layout ru`, and then type on my keyboard, I get russian characters (as expected).

OTOH, if I run `swaymsg input "*" xkb_layout ko`, and then type, it works like a regular english keyboard. Every single letter and symbol matches using `en` perfectly.

**Comment by emersion** [comment]
XKB's Korean layout is just a modified English layout. To write in Hangul, you need an IME since characters need to be combined. See https://github.com/emersion/wlhangul
