### ISSUE TITLE
`swaymsg reload` doesn't effect already opened workspaces

### ISSUE THREAD

**Issue by vired** [swaywm/sway#5184]
Sway Version: sway version 1.4

i have made modification to my config file. when i run `swaymsg reload` the modification doesn't effect already opened workspaces. but it work on newly created workspaces.

**Comment by emersion** [comment]
I think this is by design. Does i3 do it differently?

**Comment by vired** [comment]
@emersion sorry, i haven't used i3

**Comment by jsamr** [comment]
@emersion i3 does behave the same.

**Comment by emersion** [comment]
Thanks for confirming. Let's close this issue then.
