### ISSUE TITLE
On screen keyboard steals focus on touch

### ISSUE THREAD

**Issue by David96** [swaywm/sway#5185]
Hello everyone,

recently there has been a change to transfer focus on touch events, this is all great, but it also applies to onscreen keyboards, which is not so great. It causes the on screen keyboard (squeekboard in my case), which uses the input method protocol to show up whenever a text field is focused, to instantly hide again as soon as it is being touched.

Steps to reproduce:
- install an on screen keyboard like squeekboard
- start it
- focus any text field for it to show up
- try typing using the touchscreen

Result:
- the keyboard instantly hides, since the focus moved away from the textfield

The expected result obviously is, that it should be possible to type using the touch keyboard.

My sway version: Sway version 1.4-3c96a1d3 (Apr  4 2020, branch 'master')

Best regards and thanks in advance :)

**Comment by emersion** [comment]
@dcz-purism @dos1 How do you handle this?

**Comment by dcz-purism** [comment]
Squeekboard does

```
zwlr_layer_surface_v1_set_keyboard_interactivity (priv->layer_surface, false);
```

**Comment by emersion** [comment]
Oh, right, thanks!

**Comment by David96** [comment]
I did some testing and it turns out only reverting https://github.com/swaywm/sway/commit/63e45bf3217a484775f24f14c05d228c79348b7a already fixes the issue, keeping https://github.com/swaywm/sway/commit/798fc240812cc7136a7f2f755e68194884f5dbc4

Apparently cursor_motion does the required checks before setting focus.

**Comment by emersion** [comment]
Can you submit a PR to add the correct checks?

**Comment by David96** [comment]
I can try, not sure I'll succeed though.

**Comment by emersion** [comment]
Feel free to ask for help in #sway-devel on IRC.

**Comment by David96** [comment]
It's already done, was easier than I thought. Thanks anyway :)
