### ISSUE TITLE
[Help] Windows Movements

### ISSUE THREAD

**Issue by ovidius72** [swaywm/sway#5186]
I'm a new sway user switching from i3. I've been using sway for a couple of days and I've noticed this cool feature. I don't even know if that is also available in i3.
I've searched for the documentation about it but I don't know where to start.
It looks like the pre-selection feature in bspwm and I can see it when moving windows with mod+mouse.
Here is a gif about it. 

![ezgif-6-fec960e5b2f6](https://user-images.githubusercontent.com/3592928/78761616-2401dd00-7983-11ea-9b8c-325f8267c737.gif)

Where can i find more information about it ? Ii would be really cool if it was possible to interact with this feature with the keyboard.
Thanks.

**Comment by hughwilliams94** [comment]
Are you referring to moving floating windows? If so, the bindings that begin [here](https://github.com/swaywm/sway/blob/3078f232581d1dcd548810370c193c6d235d2e82/config.in#L101) allow movement of focused floating windows with the keyboard.

**Comment by ovidius72** [comment]
@hughwilliams94 No, I'm not referring to floating windows. For some reason  the gif image was not showing. I've updated the original request with a new gif. It should clarify what I mean.

**Comment by hughwilliams94** [comment]
I had never noticed this before, and my curiosity is thoroughly piqued!

**Comment by ovidius72** [comment]
From the image you can see that one can drag a window into a "sub section"  of another container. As far as I can see this can only be done with the mouse. I was wondering if there is a way to do that with the keyboard, maybe pre-selecting the target node (like bspwm) and then assigning a window to it.

**Comment by David96** [comment]
Not sure. whether this is what you want (I never used bspwm so I don't understand the references) - but I can achieve the behavior of the gif you posted by focusing the parent container of the two terminals (focus parent), doing a split h and then moving the window around by using move left/top/right/bottom.

**Comment by ovidius72** [comment]
@David96 Yes, but are you able to move the window on the left or top of the target ? I think you can only move to the right or at the bottom. The behavior on the gif is different because allows you to move and anchor the window on any direction, even at the top or at the left, or swap the 2 windows.

**Comment by David96** [comment]
How about you just try it? :sweat_smile: As I said, I could achieve exactly the behaviour you showed in your gif. I'm not sure, what you mean by "anchor the window on any direction".

**Comment by ovidius72** [comment]
Sorry, but It doesn't seem to work as I wish. However my request is about this feature that I didn't know was available. It can be really useful, so I think it's good to know how it works. ;-)

**Comment by emersion** [comment]
Closing because this isn't a Sway bug.

**Comment by ovidius72** [comment]
@emersion Sorry but who said that this is a sway bug ? I was intended as a request of help as you can see from the title

**Comment by emersion** [comment]
The issue tracker isn't the place for this.

**Comment by ovidius72** [comment]
ok. So can you please suggest me where can I ask for that ? Thanks

**Comment by Emantor** [comment]
`#sway` on freenode IRC.

**Comment by ovidius72** [comment]
@Emantor Thank you.

**Comment by ammgws** [comment]
@ovidius72 I was surprised to find this feature by accident as well. Regarding i3, it looks like they are still working on implementing this feature: https://github.com/i3/i3/issues/2643
