### ISSUE TITLE
A switch/define to *not* log timestamps?

### ISSUE THREAD

**Issue by michalrus** [swaywm/sway#5187]
Rationale: if someone is using `systemd` for logging, e.g. by starting `sway` like:

```
$ exec dbus-launch --exit-with-session systemd-cat -t sway sway --debug
```

… they get double timestamps: from `journal` and from:

https://github.com/swaywm/sway/blob/3078f232581d1dcd548810370c193c6d235d2e82/common/log.c#L77-L81

Could we have some switch or compile flag to turn those lines off? It looks funny:

![image](https://user-images.githubusercontent.com/4366292/78733748-360d5c80-793e-11ea-87d8-c4247e9bd3b8.png)

**Comment by emersion** [comment]
Sorry, we're not interested in adding a special case for systemd.

**Comment by michalrus** [comment]
Well, it’s not only for `systemd`, it would be similar for `syslog`, or a person might just want to disable timestamps… :cat:
