### ISSUE TITLE
preseted window opacity for a specific program

### ISSUE THREAD

**Issue by vired** [swaywm/sway#5191]
is there is a way that i can use to set opacity to a program, so that it will always run with that window opacity?

i wanted to have opacity on my terminal (gnome-teminal). ( i have seen some people have ) currently i added `swaymsg opacity set 0.95` to my `bashrc`.

by the way **sway is cool**.

**Comment by travankor** [comment]
```
for_window [app_id="gnome-terminal"] opacity minus 5
```
