### ISSUE TITLE
Sanity check regarding proper value for `fullscreen_mode`

### ISSUE THREAD

**Issue by ammgws** [swaywm/sway#5201]
**Steps to reproduce:**
Run sway with the default config, open a terminal and run `swaymsg -t get_tree | jq -r '[null,.]|recurse(.[1] as $parent|try (.[1].nodes[]|[($parent|del(.nodes)),.]) catch empty) | select(.[1].focused)'`.

**Result:**
In sway 1.4: parent has no `fullscreen_mode` entry, child has `fullscreen_mode = 0`
(after creating other containers the parent eventually gets an entry, but its value is 0)

In sway git: parent has `fullscreen_mode = 1`, child has `fullscreen_mode = 0`

Note nothing has been fullscreened at any point.

**Question:**
Is the current behaviour correct?

**Other info:**
- I can't seem to find the commit that changed this behaviour in sway.
- Found this after investigating why an [autotiling script I am using](https://github.com/nwg-piotr/autotiling/issues/7) was not working

**Comment by emersion** [comment]
>Is the current behaviour correct?

It's correct if it's what i3 does.

>I can't seem to find the commit that changed this behaviour in sway.

28e3187df1c85500efa3b3afb9032e8fe21b77d1

**Comment by nwg-piotr** [comment]
Should be no problem: the autotiling script needs to be updated on the next sway release.
