### ISSUE TITLE
Sway's cursor with fractional scale doesn't match other app cursors.

### ISSUE THREAD

**Issue by kchibisov** [swaywm/sway#5202]
Follow up to #4927 .
https://github.com/swaywm/sway/issues/4927#issuecomment-612039996
https://github.com/swaywm/sway/issues/4927#issuecomment-612063267

**Comment by emersion** [comment]
I don't think this is relevant anymore? With fractional-scale clients can now submit a cursor image with the same size as Sway.

**Comment by emersion** [comment]
Except we don't send fractional scale correctly for cursors I suppose?

**Comment by kchibisov** [comment]
@emersion the issue was with sway builtin cursor for decoration elements when using fractional scaling.

**Comment by emersion** [comment]
Right, so none of the above is actually related to this issue.

I believe this has been fixed now, testing with nautilus and comparing sizes with swaybg (default server-side cursor due to empty input region) and foot (cursor-shape).
