### ISSUE TITLE
Sway fails to use any cursor when reenabling output from integer scale factor to fractional

### ISSUE THREAD

**Issue by kchibisov** [swaywm/sway#5203]
When you do `swaymsg output "*" scale 2` and then something like `swaymsg output "*" scale 1.5` you'll notice that cursor over swaybg, borders, etc, is broken and just using latest cursor from the latest app it was on.

Follow up to #4927

**Comment by emersion** [comment]
I believe this has been fixed now, testing with nautilus and comparing sizes with swaybg (default server-side cursor due to empty input region) and foot (cursor-shape).
