### ISSUE TITLE
swaylock: Sway crashes when unplugging keyboard, if any options are used

### ISSUE THREAD

**Issue by aqxa1** [swaywm/sway#5205]
* Problem
If I unplug my keyboard when swaylock is awaiting input, sway crashes and it crashes severely enough that I need to reboot through SSH (or use sysrq). This only occurs if I configure the keyboard with any options like repeat_rate, xkb_options, etc. If I include an empty configuration like this:
```
input "1155:20518:CATEX_TECH._75EC-S" {
}
```

then the crash doesn't occur. It's also okay if I don't specify the input at all. The debug log I've attached includes configurations for multiple detected input devices:  "1155:20518:CATEX_TECH._75EC-S" and  "1155:20518:CATEX_TECH._75EC-S_Keyboard" however specifying just one of these still triggers the bug. I also tested a different keyboard and can trigger the bug with that keyboard as well. In sum to reproduce:

1. Configure keyboard with any options
2. Run swaylock
3. Unplug keyboard

* Sway Version: 
sway version 1.4-4d13cee5 (Apr 11 2020, branch 'HEAD')

* Debug Log: [Debug log Gist](https://gist.github.com/aqxa1/91f395393be75a87c0edcc077f742577)

* Configuration File: [Config gist](https://gist.github.com/aqxa1/6a6fc79fc168b49ea6a3844c02a1a119)

* Stack Trace, if sway crashes:
Attaching to sway and/or swaylock appears to prevent keyboard input completely (or is extremely slow). Will try again later if needed. I don't have coredumpctl as an option since I don't use systemd.

**Comment by r-c-f** [comment]
This is also easily triggered with the virtual keyboard -- something like [this](https://gist.github.com/r-c-f/1db21f3c5a170f0800237ef563e5e85a) works with the wayland backend, avoiding the need to disconnect anything and ruin one's primary session in the process.

**Comment by aqxa1** [comment]
@r-c-f Just tested the wlroots PR and it looks to fix the issue on my end.

**Comment by isafic** [comment]
I am having the same issue in 2024
