### ISSUE TITLE
for_window & assign not obeyed in xwayland classes

### ISSUE THREAD

**Issue by ocehugo** [swaywm/sway#5208]
* Sway Version: 1.4
* Debug log: https://gist.github.com/ocehugo/d3d502c4ce27afdaec597c1d16e5fa0e

* Configuration File:
```
#important bit
for_window [class="[.]*] floating enable
assign [class="[.]*"] workspace 10
```

IMO, this is a bug, since I believe the ```for_window``` & ```asign``` statements to be strict and applied to all cases.

The non-compliance occurs when restoring xwayland windows from ~~waybar~~ swaybar. Software examples include zoom/todoist-linux.

Steps:
1. Open application (application follow the ```for_window```/```assign``` rules correctly). 
2. Close window (app continue on the background/waybar)
3. Re-open window by clicking on ~~waybar~~ swaybar icon. 
4. windows are restored but do not conform to the rules anymore.

As per config, the windows should be assign to workspace 10 and be floating. At Step 4, they are tiled and in the current workspace.

**Comment by atmouse-** [comment]
I am experiencing the similar issue. When configuring youtube video Picture-in-picture mode in chromium. Floating window open as expect first time, after jump next video. the floating window reset into position center again.

reproduce steps
1. config:  
```
for_window [title="^Picture in picture$"] floating enable, move position 1500 785, resize set 367 207 px, sticky enable
assign [title="^Picture in picture$"] 7
```

2. open youtube video in PiP mode
3. click next-video-button in control bar

**Comment by Useless-Pony** [comment]
for_window and assign execute the commands on match and the conditions get checked when property gets changed.

@oranenj Waybar doesn't (and and I think shouldn't) modify the title.
Also just a note, if that's a direct copy from your config file then the first condition isn't quoted properly. You also shouldn't need the brackets. With both of those changes that section would be:
`for_window [class=".*"] floating enable
assign [class=".*"] workspace 10`
though you probably want something more like:
`for_window [shell="^xwayland$" workspace="^10$"] floating enable
assign [shell="^xwayland$" tiling] workspace 10`

@atmouse- Doing what you want seems a lot more complicated.. you might have to write a script to do that...

**Comment by ocehugo** [comment]
>or_window and assign execute the commands on match and the conditions get checked when property gets changed.

If this is true, the check only when modify assumption is clearly broken with the above case. It should be checked at window activation, I assumed.

>@oranenj Waybar doesn't (and and I think shouldn't) modify the title.
Also just a note, if that's a direct copy from your config file then the first condition isn't quoted properly. You also shouldn't need the brackets. With both of those changes that section would be:

I disagree. The regex above is valid and very broad since the class is only for Xwayland according to the sway docs. Also, Using ```shell=``` results in the same 1-4 behaviour.

Finally,  I didn't meant waybar (the alternative bar) but the defacto swaybar in sway - didn't realize that when writing. Either way, it doens't matter since its window behaviour.

**Comment by EvanCarroll** [comment]
assign [class="[.]*"] workspace 10

Is almost certainly not a valid regex. `[.]` in a regex doesn't mean any character, it means a character-class with one character in it, a `.`. So that would match a class of ``, or `.` or `..` or `...` etc.

**Comment by ocehugo** [comment]
> ```
> assign [class="[.]*"] workspace 10
> ```
> 
> Is almost certainly not likely to do what you want. `[.]` in a regex doesn't mean any character, it means a character-class with one character in it, a literal `.`. So that would match a class of ``, or `.` or `..` or `...` etc.

Embarrassing! I was completely blind to the brackets.Closing
