### ISSUE TITLE
Multi Monitor setup - same ID and Serial?

### ISSUE THREAD

**Issue by tobiaspc** [swaywm/sway#5226]
**Logs**
* Arch Linux, 5.6.4-arch1-1
* Sway Version: sway version 1.4
* Debug Log: [sway.log](https://gist.github.com/tobiaspc/fde39976c974a4e9afeeb0ac9149c1d4)
* Configuration File: [config](https://gist.github.com/tobiaspc/cbcca297bec8eb47655d8de32e2215e1)

**Goal**
I want to distinguish my external monitors, either by serial number, or by adapter ID, in order to configure them by script. The serial number seems to be the same for both monitors. The adapter ID keeps changing after undock / dock.

**Hardware**
Lenovo T470p, docked in the ThinkPad Ultra Dock (40A2). 
This dock provides 2xDP, 1x HDMI, 1xDVI and 1x VGA.

- First DP and HDMI share one "lane", e.g. it is only possible to use one of them at the same time.
- Second DP and DVI are also shared.
- VGA is not shared and always working.

I suspect that besides using HDMI and DVI, both ports are handled via DP internally.

The internal NVIDIA GPU is disabled at boot time.

The dock is connected to two identical monitors (Acer S242HL) via the docks HDMI and DVI connectors. The monitors do not support DP, therefore I am forced to use HDMI and DVI.

**Issue**
Sway works with all the monitors, but I am not able to disable / enable specific external monitors, since they somehow share the same serial number / identifier:

`swaymsg -t get_outputs`: [Click](https://gist.github.com/tobiaspc/a9315e06fff45c4ec4ce9c0d3b2a6192)
I redacted the serial of boths monitors: LR90DXXXXXXX

Both monitors can be controlled via their DP identifier, however, those numbers keep changing. After undocking and docking again, they are now they are labeled as DP-6 / DP-7.

There is no way to know which monitor is which one without manually confirming their locations.
On i3/X11, the DP numbers stay the same, since two years of usage.

The sway.log shows the following steps

- Laptop docked, no WM running
- Sway started from commandline
- Confirm monitor IDs via `swaymsg -t get_outputs` (DP-4 / DP-5)
- Laptop undocked
- Confirm only the internal display is detected
- Laptop docked
- Confirm monitor IDs via `swaymsg -t get_outputs` (now DP-6 / DP-7)
- Exit sway
- Laptop docked

See [reddit](https://www.reddit.com/r/swaywm/comments/g19o3b/multi_monitor_setup_same_id_and_serial/) for previous discussion.

**Comment by distek** [comment]
Hey.

I had the same problem.
This might help:
https://gist.github.com/distek/466cb707518228b27719be46dc538f93

I use this for my Thinkpad P50 and it works well enough.

You don't need the wallpaper part if you don't want it, but the general syntax is:
`sway-monitor.sh wallpaper.png`

You're going to need to modify it for your use-case. i.e. these parts:
```
# Change me depending on situation
searchTerm="model" # to serial, for your case
```
and the case statements in
```
function evalScreens() {

    for i in $( eval echo {0..$(( ${#outputNames[@]} - 1))}); do
        case ${outputModels[$i]} in
            #Change us depending on value of $outputModels
            0x143B ) laptopScreen=${outputNames[$i]};;
            22EN43 ) lgScreen=${outputNames[$i]};;
            U27 ) sceptreScreen=${outputNames[$i]};;
            * ) echo -e "Error!\nCheck output of 'swaymsg -t get_outputs. The values in the case statement don't appear to match.\n"
                exit 1;;
        esac
    done

}
```

Hope this helps

**Comment by tobiaspc** [comment]
Hi, thanks for the response.

However I am not able to see how this script could be helpful for my situation.
As far as I can tell, `evalScreens()` is not able to distinguish two monitors with identical model and serial number. 

Did I miss something?

**Comment by emersion** [comment]
X11 does its own numbering. We use the kernel's numbering. To get stable IDs, something like https://lists.freedesktop.org/archives/dri-devel/2019-June/221902.html would be required I think.

**Comment by progandy** [comment]
Does the order of your monitors stay the same, i.e. one monitor always has the smaller number?

If you run [drm_info](https://github.com/ascent12/drm_info), do your connectors have a PATH property that stays the same?

**Comment by distek** [comment]
@tobiaspc I'm assuming that would be useful in your case due to you stating the screens had serial numbers. If these are static (which if they're SN's, I'm assuming they are) you would change the case like this:

```
        case ${outputModels[$i]} in
            #Change us depending on value of $outputModels
            <serial1> ) laptopScreen=${outputNames[$i]};;
            <serial2> ) lgScreen=${outputNames[$i]};;
            * ) echo -e "Error!\nCheck output of 'swaymsg -t get_outputs. The values in the case statement don't appear to match.\n"
                exit 1;;
        esac
```

Replacing the `<serialN>` with whatever your serial numbers are, like I was doing with models.

You can adapt the script more to your use case. For example with `lgScreen`, you can change that, since they're not an LG screen, to whatever to you want.

**Comment by emersion** [comment]
@distek The serial numbers are the same.

**Comment by distek** [comment]
> The serial number seems to be the same for both monitors.

Completely missed that line. Apologies. 

I tried a thing:
I just tested connecting my display to different ports and it always reported the same edid values.

```
[distek] > sha1sum /sys/class/drm/card1-DP-6/edid 
38301a1741b427a97b97624cbfe096eca6852dc8  /sys/class/drm/card1-DP-6/edid
[distek] > sha1sum /sys/class/drm/card1-DP-1/edid 
38301a1741b427a97b97624cbfe096eca6852dc8  /sys/class/drm/card1-DP-1/edid
```
sha1'd for prettier output

Using these info points might be worth a shot. See if they come back differently and use that information to determine which monitor is which.

I unfortunately don't have two identical monitors to test this with.

**Comment by tobiaspc** [comment]
Now we are getting somewhere!

>  I just tested connecting my display to different ports and it always reported the same edid values.

Interestingly, that is not the case for me! The EDID changes if I attach the monitors via DVI.
Using `parse-edid`, I found out that over HDMI, a "Extension block" is encoded in the edid. Over DVI, the edid contains no such data.

I attached the monitors via HDMI to the laptops own HDMI port, here, the edid stays the same.
Somehow, that extension block is not transmitted via DVI. 

Since the port is encoded in the /sys/ path and the sha256 sums stay the same for the same port / monitor combination, I can continue from here, writing a script that matches edid to output.

Thanks a lot for the help!

> Does the order of your monitors stay the same, i.e. one monitor always has the smaller number?

Yes, that seems to be the case, but I would not bet on it.

> If you run drm_info, do your connectors have a PATH property that stays the same?

Yes, that seems to be the case too. The problem here is, that I am not able to map the output from `drm_info` to my connectors. `swaymsg -t get_outputs` shows them as DP-4 / 5 right now, `drm_info` as `Connector 7` and `Connector 8`. Apart from that, no further information is given that would allow me to map which display is which.

**Comment by emersion** [comment]
>I suspect that besides using HDMI and DVI, both ports are handled via DP internally.

Oh, so maybe this would be useful then: https://lists.freedesktop.org/archives/dri-devel/2020-April/261419.html

>swaymsg -t get_outputs shows them as DP-4 / 5 right now, drm_info as Connector 7 and Connector 8

Yeah, connector object IDs are not the same as connector type IDs. drm_info doesn't print `drmModeConnector.connector_type_id`, which we use in wlroots.

**Comment by progandy** [comment]
> Yes, that seems to be the case too. The problem here is, that I am not able to map the output from `drm_info` to my connectors.

So either sway, kanshi or your own tool could implement a match on the connector path to solve your problem.

**Comment by tobiaspc** [comment]
For anyone coming across that issue, this is the script I came up with: [Click](https://gist.github.com/tobiaspc/cbc8eb36430b9a9318c2a1904da45615)
