### ISSUE TITLE
AMDGPU support?

### ISSUE THREAD

**Issue by WhyNotHugo** [swaywm/sway#5234]
Hi. More of a question than an issue, but I do feel that upstream is the right place to ask.

I'm thinking of getting a recent AMD card, and using the in-kernel **AMDGPU** driver.

I know nvidia is definitely not supported, and that Intel is fully supported, but I was wondering on the status of cards, and, particularly, this driver.

Also, assuming you don't mind, I'd like to update the wiki to reflect this, since I don't see this explicitly mentioned anywhere.

Thanks, and thanks a bunch for sway!

**Comment by emersion** [comment]
All upstream kernel drivers are supported.
