### ISSUE TITLE
swaymsg -t get_outputs does not list all available modes

### ISSUE THREAD

**Issue by w3bad** [swaywm/sway#5244]
sway version 1.4

$ swaymsg -t get_outputs
Output DP-1 'Lenovo Group Limited LEN Y27gq-25' (focused)
  Current mode: 2560x1440 @ 119.998001 Hz
  Position: 0,0
  Scale factor: 1.000000
  Scale filter: nearest
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 1
  Max render time: off
  Available modes:
    640x480 @ 59.939999 Hz
    640x480 @ 60.000000 Hz
    800x600 @ 60.317001 Hz
    1024x768 @ 60.004002 Hz
    2560x1440 @ 99.945999 Hz
    2560x1440 @ 119.998001 Hz
    2560x1440 @ 143.973007 Hz
    2560x1440 @ 59.951000 Hz

At the same time:
cat /sys/devices/pci0000\:00/0000\:00\:1c.0/0000\:01\:00.0/drm/card0/card0-DP-1/edid|edid-decode
edid-decode
...
Block 2, DisplayID Extension Block:
  Version: 1.3
  Extension Count: 0
  Display Product Type: Standalone display device
  Display Interface Data Block:
    Interface Type: DisplayPort
    Number of Links: 4
    Interface Standard Version: 1.4
    Supported bpc for RGB encoding: 8, 10, 12
    Supported bpc for YCbCr 4:4:4 encoding: 8, 10, 12
    Supported bpc for YCbCr 4:2:2 encoding: 8, 10, 12
    Supported Content Protection: HDCP 2.0
    Spread Spectrum: Down Spread 0.5%
  Color Characteristics Data Block:
    Uses spatial color
    Uses 1931 CIE (x, y) coordinates
    Primary #0: (0.671143, 0.313965)
    Primary #1: (0.283203, 0.661865)
    Primary #2: (0.147705, 0.051514)
    White point #0: (0.312744, 0.329102)
  Video Timing Modes Type 1 - Detailed Timings Data Block:
    DTD 5:  2560x1440  199.992 Hz  16:9   317.188 kHz 862.750 MHz (aspect 16:9, no 3D stereo)
                 Hfront   48 Hsync  32 Hback  80 Hpol P
                 Vfront    3 Vsync   5 Vback 138 Vpol N
    DTD 6:  2560x1440  239.970 Hz  16:9   388.511 kHz 1056.750 MHz (aspect 16:9, no 3D stereo)
                 Hfront   48 Hsync  32 Hback  80 Hpol P
                 Vfront    3 Vsync   5 Vback 171 Vpol N

DTD 5 and 6 are not offered in swaymsg -t get_outputs.

I tried using 2560x1440  239.970 Hz with custom mode setting but only got to a black screen:
output DP-1 mode --custom 2560x1440@239.970Hz

**Comment by emersion** [comment]
Modes may be filtered out by the kernel. Can you run [drm_info](https://github.com/ascent12/drm_info) and check if the modes are advertised? If not, either this is a kernel bug, either your hardware doesn't support the mode.

**Comment by w3bad** [comment]
Thank you for a quick comment. drm_info does not list the mode either, so it must be getting filtered out for some reason. Hardware shouldn't be an issue as the mode is advertised in windows and in gnome too if nvidia proprietary driver is used (otherwise the mode is not listed). My first suspicion was with nouveau but then after seeing that correct EDID is picked up it made me wonder why such mode is not listed at least. Forcing the EDID on boot shouldn't make a difference right? Output from drm_info for the relevant connector: 
│   ├───Connector 2
│   │   ├───Object ID: 77
│   │   ├───Type: DisplayPort
│   │   ├───Status: connected
│   │   ├───Physical size: 600x340 mm
│   │   ├───Subpixel: unknown
│   │   ├───Encoders: {6, 7}
│   │   ├───Modes
│   │   │   ├───2560x1440@59.95 preferred driver phsync nvsync 
│   │   │   ├───2560x1440@143.97 driver phsync nvsync 
│   │   │   ├───2560x1440@120.00 driver phsync nvsync 
│   │   │   ├───2560x1440@99.95 driver phsync nvsync 
│   │   │   ├───1024x768@60.00 driver nhsync nvsync 
│   │   │   ├───800x600@60.32 driver phsync pvsync 
│   │   │   ├───640x480@60.00 driver nhsync nvsync 4:3 
│   │   │   └───640x480@59.94 driver nhsync nvsync 
│   │   └───Properties
│   │       ├───"EDID" (immutable): blob = 86
│   │       ├───"DPMS": enum {On, Standby, Suspend, Off} = On
│   │       ├───"link-status": enum {Good, Bad} = Good
│   │       ├───"non-desktop" (immutable): range [0, 1] = 0
│   │       ├───"TILE" (immutable): blob = 0
│   │       ├───"underscan": enum {auto, off, on} = off
│   │       ├───"underscan hborder": range [0, 128] = 0
│   │       ├───"underscan vborder": range [0, 128] = 0
│   │       ├───"vibrant hue": range [0, 180] = 90
│   │       ├───"color vibrance": range [0, 200] = 150
│   │       ├───"scaling mode": enum {None, Full, Center, Full aspect} = None
│   │       ├───"dithering mode": enum {auto, off, static 2x2, dynamic 2x2, temporal} = auto
│   │       └───"dithering depth": enum {auto, 6 bpc, 8 bpc} = auto

**Comment by progandy** [comment]
> My first suspicion was with nouveau but then after seeing that correct EDID is picked up it made me wonder why such mode is not listed at least.

nouveau might calculate the link budget (bandwidth available) and determine that the mode requires too much. In that case either nouveau is inefficient or has a bug in that calculation. The proprietary driver does the calculation correctly.

**Comment by emersion** [comment]
Please report this as a nouveau bug.
