### ISSUE TITLE
Can't set background

### ISSUE THREAD

**Issue by partySnacks** [swaywm/sway#5246]
sway version 1.4

log: https://pastebin.com/0U4pFYSV

config: https://pastebin.com/jy7Q4X02

Recently updated sway (only sway) from a old version (from jan 2019) and since then I've been unable to set backgrounds, tried different images and solid colors too. I'm posting it here and not in the swaybg repo since this seems to have been introduced with an update of sway itself.
Steps to reproduce: Try to set a background image

**Comment by emersion** [comment]
Sounds like your `swaybg` is outdated.

**Comment by partySnacks** [comment]
@emersion 
Swaybg is the most recent version in the void linux repos and there's only been one release so far

**Comment by emersion** [comment]
```
2020-04-21 22:50:21 - [swaybg/main.c:264] Do not run this program manually. See `man 5 sway-output` and look for background options.
```

Indicates either Sway or swaybg is out-of-date.
