### ISSUE TITLE
Input method: ibus-mozc on gtk3 application

### ISSUE THREAD

**Issue by junyoshida12021987** [swaywm/sway#5249]
First time post on Github. 
I currently use mozc input method on ibus. 
My /etc/sway/config file is written this way.

```
exec GTK_IM_MODULE_FILE=/usr/lib64/gtk-3.0/3.0.0/immodules.cache
exec GTK_IM_MODULE=ibus
exec QT_IM_MODULE=ibus
exec XMODIFIERS=@im=ibus
exec ibus-daemon -rdx
```

Firefox supports mozc but other gtk3 applications like Libreoffice does not. 
書けない。

**Comment by junyoshida12021987** [comment]
Related issue #4841

**Comment by emersion** [comment]
You can't `exec` to change env variables. Instead you need to set these variables before starting Sway. See https://wiki.archlinux.org/index.php/Environment_variables#Defining_variables
