### ISSUE TITLE
Colour artifacts in fullscreen mode on i915 from linux 5.x.x

### ISSUE THREAD

**Issue by niktob560** [swaywm/sway#5251]
```
ArchLinux
Intel UHD Graphics 620 
sway 1:1.4-8
egl-wayland 1.1.4-2 
glfw-wayland _3.3.2-1_
gtk-layer-shell 0.1.0-2
lib32-libva1 1.8.3-3
lib32-wayland 1.18.0-2
libva 2.7.1-1
libva1 1.8.3-2
qt5-wayland 5.14.2-1
wayland 1.18.0-2
wayland-protocols 1.20-1
wlroots 0.10.1-1
```

Custom compilations and stock kernels tested
Default sway config and no weston config tested

https://youtu.be/1PIhc0x8XRk - artifacts example in VLC 
https://youtu.be/_cRN56ARgZo - artifacts example in feh

artifacts appear in fullscreen mode of many apps
but not always
video in vlc - always
android studio - always
firefox on scrolling - sometimes on scrolling
telegram-desktop - no
feh - always on scrolling
pcbnew - always on scrolling
eschema - always on scrolling
vscode - no
atom - no
dia - always on scrolling
pcmanfm - always on scrolling
dolphin - no
mpv - no
```
mpv 0.32.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
ffmpeg version: n4.2.2
```

This issue appears in ``Weston 8.0.0`` too, but I don't sure where I must send report
No error messages are shown 
Artifacts disappears when ``wf-recorder-git r106.ccbd0c7-1`` is started in background

i915 options in kernel options in entry of systemd-boot
```
i915.modeset=1
i915.enable_rc6=1
i915.enable_fbc=1
i915.enable_guc_loading=1
i915.enable_guc_submission=1
i915.enabe_huc=1
i915.enable_psr=1
i915.disable_power_well=0
i915.semaphores=1
```
removing of them gives no changes
vlc output:
```
VLC media player 3.0.8 Vetinari (revision 3.0.8-0-gf350b6b5a7)
[000055a2ba8095b0] main libvlc: Запуск vlc с интерфейсом по умолчанию. Используйте 'cvlc' для запуска vlc без интерфейса.
qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no
qt5ct: D-Bus system tray: yes
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[00007f8bfc001f50] glconv_vaapi_x11 gl error: vaInitialize: unknown libva error
[00007f8c04efa530] avcodec decoder: Using Intel iHD driver for Intel(R) Gen Graphics - 20.1.1 () for hardware decoding
QObject::~QObject: Timers cannot be stopped from another thread
```
default config log of start of vlc with -d flag and stderr(removed i3 config and current sway config)
[sway.log](https://github.com/swaywm/sway/files/4530630/sway.log)

**Comment by emersion** [comment]
Can you reproduce on Weston?

**Comment by niktob560** [comment]
Yes
Fullscreen mode does not need in weston to see artifacts
[Video](https://youtu.be/hTqBfiAUsto)
``$ weston --debug &>weston.log``
[weston.log](https://github.com/swaywm/sway/files/4531385/weston.log)

**Comment by emersion** [comment]
Okay, then this is probably a driver bug. Can you report it on https://gitlab.freedesktop.org/drm/intel?

**Comment by niktob560** [comment]
Yeah, reported  
But this issue does not appears on Xorg on the same hardware  
Maybe it is a Wayland bug?

**Comment by emersion** [comment]
No, Wayland is just a protocol. X11 doesn't use OpenGL nor KMS, so may be a bug in there.

**Comment by Hermitter** [comment]
Has anyone been able to solve this issue? Fullscreen on GNOME Wayland doesn't have the color artifacts I'm getting with Sway fullscreen.

**Comment by Emantor** [comment]
Older xwayland versions before 1.20.8 have a data race problem where the buffer was send to wayland before the write to it was finished. This didn't show up much in non-fullscreen buffers since by the time sway was done with compositing the non-fullscreen buffers, xwayland had finished the writes on its side. However for fullscreen views Sway skips the compositing and directly displays the buffer making the data race more visible. AFAIK Gnome does not implement direct scan-out, so it might be the Xwayland problem you are seeing.

**Comment by Hermitter** [comment]
Thanks @Emantor! I was able to find a solution from the info you gave.
https://gitlab.freedesktop.org/xorg/xserver/-/issues/966

**Comment by Emantor** [comment]
@niktob560

Reading this again:
```
i915.modeset=1
i915.enable_rc6=1
i915.enable_fbc=1
i915.enable_guc_loading=1
i915.enable_guc_submission=1
i915.enabe_huc=1
i915.enable_psr=1
i915.disable_power_well=0
i915.semaphores=1
```
Remove all of those. You are not gaining anything and instead may experience visual glitches, leave it up to the kernel developers to enable individual module options by default. Especially running an up to date kernel, you will have the best experience not changing any of the module options.
