### ISSUE TITLE
Input devices no longer work after unplug and plug in again

### ISSUE THREAD

**Issue by gitmac777** [swaywm/sway#5252]
Always if I unplug the keyboard or mouse, i can no longer connect it because it is not recognized again. If I unplug in sway for example the mouse and plug it in again it not works, but if i change then from sway to console with alt+F2 and then back to sway the mouse works again (i can see in dmesg that always if i do this, a new device file is created in /sys/devices/platform/ff580000.usb/usb1/1-1/1-1:1.0/). 

I use a ROCK64 single-board computer (RK3328 Quad-Core ARM Cortex A53 64-Bit Processor) with Armbian and Alpine Linux.

I had to create the device file /dev/input/mice with mknod mice c 13 63 because it wasn't there.
[dmesg.txt](https://github.com/swaywm/sway/files/4531535/dmesg.txt)
[stat_sys_devices_platform.txt](https://github.com/swaywm/sway/files/4541016/stat_sys_devices_platform.txt)
[stat_dev_input.txt](https://github.com/swaywm/sway/files/4541018/stat_dev_input.txt)
[ls-alh_dev_input_by_id.txt](https://github.com/swaywm/sway/files/4541025/ls-alh_dev_input_by_id.txt)
[ls-alh_dev_input_by_path.txt](https://github.com/swaywm/sway/files/4541026/ls-alh_dev_input_by_path.txt)
[libinput_list-devices.txt](https://github.com/swaywm/sway/files/4541034/libinput_list-devices.txt)
[stat_sys_bus_pci_drivers.txt](https://github.com/swaywm/sway/files/4541043/stat_sys_bus_pci_drivers.txt)
[swaymsg_-t_get_inputs.txt](https://github.com/swaywm/sway/files/4541045/swaymsg_-t_get_inputs.txt)

**Comment by emersion** [comment]
Can you run `sudo libinput debug-events` in Sway, then unplug and re-plug?

**Comment by gitmac777** [comment]
[libintput-debug-events.txt](https://github.com/swaywm/sway/files/4531597/libintput-debug-events.txt)

**Comment by emersion** [comment]
It doesn't seem like libinput detects that the devices are removed and re-added.

**Comment by gitmac777** [comment]
Maybe missing or wrong libinput device quirks .... i will check that

**Comment by gitmac777** [comment]
I looked at the udev rules and device quirks, it's all standard, I don't think it's because of these files.

**Comment by emersion** [comment]
In any case, if libinput doesn't see it, we can't see it. Please file a libinput issue.
