### ISSUE TITLE
Sway Crash `Unable to create backend`

### ISSUE THREAD

**Issue by JonathanILevi** [swaywm/sway#5267]
Sway is crashing when I try to launch it.

Tested on v1.4 and master, also tested using a blank config file.

I have no problem on v1.2.

Here is the error logs:
https://gist.github.com/JonathanILevi/7a673013f42c31fcb1d07543fa0ccfd5

`coredumpctl gdb sway` gives "No match found."

I am on NixOS, and I run sway directly from a tty.  Sway is crashing before anything happens graphically.

**Comment by Emantor** [comment]
Did you compile locally from the instructions in the wiki? On NixOS you'll have to recompile as soon as you upgrade one of the dependencies, since your libs go out of sync otherwise. Please use the Wayland overlay or create nix pkgs by overwriting the `src` attribute for `sway` and `wlroots`.

**Comment by ascent12** [comment]
>undefined symbol: drmSyncobjTimelineSignal

Your libdrm is too old or otherwise is not set up correctly. This is causing your GPU driver to fail to load.
Perhaps your drivers are not set up correctly in other ways too.

In any case, this is not a sway issue.

**Comment by JonathanILevi** [comment]
It looks like it was an issue with having mismatched OpenGL versions.  I guess OpenGL does not like having multiple versions on a single system.

In NixOS, Sway, typically, needs to be installed from the same channel as the OS.

Thank you for leading me to the answer.
