### ISSUE TITLE
Modifier key not released on focus switch

### ISSUE THREAD

**Issue by Xyene** [swaywm/sway#5269]
My sway modifier key is <kbd>Alt</kbd>, and `focus right` is bound to <kbd>Alt</kbd> + <kbd>→</kbd>. Incidentally, in Firefox, <kbd>Alt</kbd> + scroll moves through the browser history.

It appears that when I execute <kbd>Alt</kbd> + <kbd>→</kbd>, Firefox receives a key down event for <kbd>Alt</kbd>, then sway switches focus to whatever I had on the right of Firefox &mdash; but doesn't notify Firefox of my releasing <kbd>Alt</kbd>. (This all works fine if I hold down <kbd>Alt</kbd> while using my mouse to switch window focus; <kbd>Alt</kbd> is released on the focus switch.)

If my mouse happened to be over Firefox and I attempt to scroll (often this happens because I start scrolling as I move the mouse to the surface that needs scrolling, not necessarily only once I'm already on the surface), Firefox receives those events (fine), and then proceeds to move through dozens of entries of history, since it thinks <kbd>Alt</kbd> is still held (less fine, I've lost work like this before).

It would be nice if sway would notify the application that just lost focus that the modifier key was released. I imagine this doesn't impact _too_ many people since I doubt <kbd>Alt</kbd> is frequently used as a modifier, though.

**Comment by emersion** [comment]
Clients need to lift all keys when they receive `wl_keyboard.leave`.

**Comment by Xyene** [comment]
Aha, thanks for the tip. I figured Firefox being involved was just a coincidence, but I've found the offending code in Firefox.

It attaches two listeners: one comes from GDK, and Firefox computes its modifier state from the keyup/keydown events from this stream. The other is in Firefox itself, and is used to to obtain the keymap. The leave handler [is blank](https://github.com/mozilla/gecko-dev/blob/7e2477521b3622a5a1ee314cf789c57e6e0f957f/widget/gtk/nsGtkKeyUtils.cpp#L716-L718).

I'll see if I can submit a patch for this upstream. At any rate, going to close this since it's not on sway's end &mdash; thanks.

**Comment by Xyene** [comment]
Haha, this was actually patched 26 days ago, in GDK: https://github.com/GNOME/gtk/commit/7444b15d47e40d1c4696bf978319690db0b91c4b

Guess I just have to wait for it to get picked up by Firefox :)

**Comment by Emantor** [comment]
> Guess I just have to wait for it to get picked up by Firefox/etc. :)

This needs to be picked up by the distributions, Firefox AFAIK uses the system libraries.

**Comment by Xyene** [comment]
Yeah, figured that might be the case... `ldd` didn't show it on the Firefox binary, so it was either being dlopened or bundled in some way that I wouldn't be surprised if Firefox did. Thanks for confirming it's the former though, that'll make it easier to get my hands on the fix :+1:
