### ISSUE TITLE
sway crash

### ISSUE THREAD

**Issue by JonnyMako** [swaywm/sway#5272]
With latest sources, sway crashes on startup if no external monitor is connected. If external monitor is present, main monitor remains blank.

    sway version 1.4-f18bcfcd (Apr 28 2020, branch 'master')

[gdblog.txt](https://github.com/swaywm/sway/files/4546708/gdblog.txt)

**Comment by emersion** [comment]
See https://github.com/swaywm/wlroots/pull/2141
