### ISSUE TITLE
Improper behavior of two Sway sessions launched simultaneously

### ISSUE THREAD

**Issue by ikalnytskyi** [swaywm/sway#5274]
First of all, I have little knowledge of Wayland and its ecosystem, so sorry if I'm doing something stupid. My current understanding of Wayland is that there's nothing that prevents running two or more Wayland sessions, each in a separate `tty`, simultaneously. So I decided to give it a try (mostly out of curiosity) with Sway.

I logged in into `tty2` and `tty3`, and started Sway simply by invoking `sway` binary from the shell. Both Sway sessions have been started successfully. Then, I tried to start a terminal in each session and was quite surprised by the result: first Sway session has successfully launched a terminal while the second one has never reacted to my command visibly. It turns out that the command sent to the second session has been launched by the first one.

I also tried `swaymsg --socket` to explicitly control where I want to launch a terminal but the result was still the same. The interesting part here is that it's the proper Sway session that receives and executes the command (I can see it in the logs). However, launched app is always shown and controlled by the first Sway session.

I tried both `1.4` and `master` versions of Sway. The logs from both sessions and both versions can be grabbed from the following gist:

https://gist.github.com/ikalnytskyi/388719e402b53ea516a330175bda96e0

**Comment by emersion** [comment]
What terminal emulator are you using? Some terminal emulators (like gnome-terminal) run a "server process" on first run, then all subsequent runs re-use the same server process, resulting in all windows showing in the same Wayland session.

**Comment by ikalnytskyi** [comment]
That's interesting, I didn't know that. I'm using `tilix`, it's vte-based but it might be the thing. Let me try with something else.

**Comment by ikalnytskyi** [comment]
@emersion You're right! Thank you! `termite`, for instance, works fine and so is `wireshark`. It's so quite unfortunate that I tried only `tilix` and `firefox` and both indeed seem to open new windows in the same session.

Do you know by any chance is there any known workaround how to overcome this limitation? Also, does `mako` (notification daemon) suffers from the same issue?

---

*(I'm closing the issue since apparently it's not the issue of Sway)*

**Comment by emersion** [comment]
>Do you know by any chance is there any known workaround how to overcome this limitation? 

No, but you can ask Tilix devs.

> Also, does mako (notification daemon) suffers from the same issue?

Mako can't be started twice for the same user because of D-Bus architecture limitations. There is one D-Bus session bus per user.
