### ISSUE TITLE
Dragging windows with tablet pen gets stuck in drag mode

### ISSUE THREAD

**Issue by minus7** [swaywm/sway#5280]
When you drag a window by the title bar with a tablet pen, it will only highlight few drop positions and letting go of it won't release the window. Clicking with the mouse will end dragging then.

Sway commit: 99897a6ca058a3cc00c0beea41079d44c0ebdba2

**Comment by Xyene** [comment]
Does https://github.com/swaywm/sway/pull/5259 fix this for you? That fixes a similar issue, with resizing rather than titlebars.

**Comment by minus7** [comment]
Yes, with those two patches applied it works as intended, thanks

**Comment by Xyene** [comment]
Great! They've both been merged now, so I think this can be closed.
