### ISSUE TITLE
Sway not starting after updating json-c from 0.13.1-3 to 0.14-1

### ISSUE THREAD

**Issue by BoostCookie** [swaywm/sway#5283]
My gist can be found here:
[https://gist.github.com/BoostCookie/772ca4951e358b76ac857ae1c3760a5d](https://gist.github.com/BoostCookie/772ca4951e358b76ac857ae1c3760a5d)
Basically Sway doesn't work anymore after updating the package `json-c` from 0.13.1-3 to 0.14-1.
I don't know if the error is on sway's side or on json-c's side.

**Comment by adee** [comment]
Let me guess: Archlinux user?
They rebuilt their sway package, because it depends on json-c. You need to fully update your system. There is no bug in either of these software.
You can close this.

**Comment by BoostCookie** [comment]
Sorry, I'm stupid. I just needed to rebuild sway and wlroots for them to find the new library.
