### ISSUE TITLE
Keys held during suspend get re-triggered on resume

### ISSUE THREAD

**Issue by annacrombie** [swaywm/sway#5284]
* Sway Version:

`1.4-f681d529 (Apr 29 2020, branch 'HEAD')`

* Configuration File:

```
bindsym $mod+f4 exec doas hibernate
```

* `hibernate`

```sh
#!/bin/sh

printf "mem\n" > /sys/power/state
```

When hibernating using this setup, the initial hibernate works fine.  When I wake up the computer though, it wakes up fully then immediately goes back to sleep.  On the second wake, it stays awake.

If I add a `sleep 0.5` right before the setting my power state in the `hibernate` script, it does not hibernate a second time upon waking (unless I keep the keys held down).  This leads me to believe that keys held prior to a sleep in sway get processed a second time on resume.

**Comment by Xyene** [comment]
This sounds like a variation of https://github.com/swaywm/sway/issues/4975. You should be able to achieve what you want by binding the release event, rather than the key down event;

```
bindsym --release $mod+f4 exec doas hibernate
```

**Comment by annacrombie** [comment]
Thats true, I didn't see the --release option for bindsym.  Since that fixes my problem, and there seems to be another issue already tracking this, I'll go ahead and close.
