### ISSUE TITLE
Hidden GTK dropdown with output position parameter

### ISSUE THREAD

**Issue by Eluminae** [swaywm/sway#5285]
Hello there !

I got a problem with one of my laptop on GTK apps. Some dropdown selects are hidden (out of screen?)

I got two screencast of the same app "pavucontrol" with the same informations (same pulse server) in both pcs.

[working pavucontrol](http://dav.misterbanal.net/f8d5a184-56ee-40fd-bedb-ea0d8f1b89ca.flv)
[not working pavucontrol](http://dav.misterbanal.net/defdb9ac-19f4-423b-b753-7ede29980017.flv)

The two env seems really similar. Same dotfiles, same sway version (except the outputs maybe), up to date.

I don't know where to ask for it (gtk3 or other ?) but as it works on some laptops, maybe this is a context issue (sway, wlroots ?)

Another information, I use scaling on both outputs (1.4 and 1.6). Maybe this is relevant

The GTK installed packages seems the same, here the gtk installed packages diff

```
  clutter-gtk                                                               |  clutter-gtk
  colord-gtk                                                                |  ------------------------------------------------------------------------
  gtk+                                                                      |  gtk+
  gtk+3                                                                     |  gtk+3
  gtk+3-devel                                                               |  ------------------------------------------------------------------------
  gtk-layer-shell                                                           |  gtk-layer-shell
  gtk-update-icon-cache                                                     |  gtk-update-icon-cache
  gtkmm                                                                     |  gtkmm
  gtkmm2                                                                    |  ------------------------------------------------------------------------
  gtksourceview                                                             |  gtksourceview
  libcanberra-gtk3                                                          |  libcanberra-gtk3
  libdbusmenu-gtk3                                                          |  libdbusmenu-gtk3
  libgnomecanvasmm                                                          |  pinentry-gtk
  --------------------------------------------------------------------------|  pygtk
  webkit2gtk                                                                |  webkit2gtk
  wxWidgets-common                                                          |  ------------------------------------------------------------------------
  wxWidgets-gtk3                                                            |  ------------------------------------------------------------------------
~                                                                           |~
~                                                                           |~
working-laptop                                                  14,1           All not-working-laptop                                         11,1           All
```

I don't have specific gtk config as you can see:

```
$ tree .config/gtk-*
.config/gtk-2.0
└── gtkfilechooser.ini
.config/gtk-3.0
```
All my dotfiles are available [here](https://hg.sr.ht/~reedwade/dotfiles/browse/.config/sway?rev=default)

$ swaymsg -t get_version
sway version 1.4

I got this issue from a long time now. This is not new that this laptop got issues with gtk drop down. I guess the same issue affect another personal app that use text inputs with auto-complete fields which do not shot themselves.

Thanks a lot for your help.

**Comment by Eluminae** [comment]
Ok I found the config that was causing this issue

```diff
-output eDP-1 scale 1.6 mode 1440x900 position 1372,56
+output eDP-1 scale 1.6 mode 1440x900
```

This position parameter was used with another output to make junction with the other screen consistent with the actual screen positions. 

I think this position parameter should not cause the issue anyway.

**Comment by RedSoxFan** [comment]
This would be #3135. Unfortunately, it is a client issue and is caused by deprecated GTK functions being used. There is nothing we can do about it.
