### ISSUE TITLE
Shortcuts with modifier & multiple keyboards

### ISSUE THREAD

**Issue by melkor217** [swaywm/sway#5288]
Aight, let me describe my case. I have two devices that identify emselves as keyboards.

Shortcuts like `bindsym Mod4+F1 workspace 1` only work for me if both keys come a single device.

If i press Mod4 on my keyboard and then F1 on my mousepad, then shortcut gets ignored by sway.

i3 had no problems with this btw.

My devices:

```
  {
    "identifier": "5426:542:Razer_Razer_Ornata_Chroma",
    "name": "Razer Razer Ornata Chroma",
    "vendor": 5426,
    "product": 542,
    "type": "keyboard",
    "xkb_layout_names": [
      "English (US)",
      "Russian"
    ],
    "xkb_active_layout_index": 0,
    "xkb_active_layout_name": "English (US)",
    "libinput": {
      "send_events": "enabled",
      "natural_scroll": "disabled"
    }
  }
```

Which is regular keyboard and

```
  {
    "identifier": "5426:103:Razer_Razer_Naga_Trinity",
    "name": "Razer Razer Naga Trinity",
    "vendor": 5426,
    "product": 103,
    "type": "keyboard",
    "xkb_layout_names": [
      "English (US)"
    ],
    "xkb_active_layout_index": 0,
    "xkb_active_layout_name": "English (US)",
    "libinput": {
      "send_events": "enabled"
    }
  },
```
Which is a keypad on my mouse.

sway version 1.4

Much thanks!

**Comment by emersion** [comment]
Right now keyboards are grouped by layout, because grouping two keyboards with a different layout can't work. Can you try applying your `xkb_*` options to all keyboards instead of just one? (You can use `input type:keyboard …` for this)

**Comment by melkor217** [comment]
@emersion Thanks you for response!

My previous configuration was:

```
input "5426:542:Razer_Razer_Ornata_Chroma" {
    xkb_layout us,ru
    xkb_options grp:caps_toggle
}
```

Also i had no success no success with:

- `input type:keyboard ...`

- `input * ...`

- No input config at all

Full output of `swaymsg -t get_inputs` with no input config:  https://gist.github.com/melkor217/de0838d468890567ddb778a32c0aae19

```
  {
    "identifier": "5426:542:Razer_Razer_Ornata_Chroma",
    "name": "Razer Razer Ornata Chroma",
    "vendor": 5426,
    "product": 542,
    "type": "keyboard",
    "xkb_layout_names": [
      "English (US)"
    ],
    "xkb_active_layout_index": 0,
    "xkb_active_layout_name": "English (US)",
    "libinput": {
      "send_events": "enabled"
    }
  },
  {
    "identifier": "5426:103:Razer_Razer_Naga_Trinity",
    "name": "Razer Razer Naga Trinity",
    "vendor": 5426,
    "product": 103,
    "type": "keyboard",
    "xkb_layout_names": [
      "English (US)"
    ],
    "xkb_active_layout_index": 0,
    "xkb_active_layout_name": "English (US)",
    "libinput": {
      "send_events": "enabled"
    }
  },
```

**Comment by melkor217** [comment]
upd: Nevermind, it now works somehow with empty input config after restarting sway.
