### ISSUE TITLE
Xwayland window: no pointer interaction if negative output position is used

### ISSUE THREAD

**Issue by Z3NOX** [swaywm/sway#5301]
Sway Version: 1.4
Debug log: [gist.github.com](https://gist.github.com/Z3NOX/97389aa5d30122f5b035893a00b72ce8)

I have a problem using sway with xwayland applications displayed on an external monitor positioned with negative coordinates: The applications cannot be controlled with the mouse. A window on a workspace assigned to the external monitor gets the focus and can be moved correctly with the pointer, though.

```
      ┌-----------------------┐  → resolution: 3840x2160
      |  4K external monior   |    position: -960,-2160
      |                       |
      |                       |
      |                       |
      └-----------------------┘
          ×┌-------------┐   → resolution: 1920x1080
           |  internal   |     position: 0, 0
           |  monitor    |
           |             |
           └-------------┘

× origin of the output position coordinates
```
The external screen is positioned centered above the internal. It seems, that the mouse is virtually stuck on the upper rim of the lower screen, while the pointer is correctly displayed on the upper screen. 

Interactions with native wayland windows seem to be correct though. 

If I adjust my layout not using negative coordinates for the upper screen, I do not observe this issue.

**Comment by Xyene** [comment]
This is an Xwayland issue, [mentioned in the wiki](https://github.com/swaywm/sway/wiki#mouse-events-clicking-scrolling-arent-working-on-some-of-my-workspaces). See also the issue in the [Xwayland tracker](https://gitlab.freedesktop.org/xorg/xserver/issues/899).

**Comment by Z3NOX** [comment]
Oh thank you for the quick response. I was only looking in the man page if the usage of negative coordinates is dissallowed somewhere, which was not the case. Sorry for the noise.
