### ISSUE TITLE
Sway no longer works if Bar is present

### ISSUE THREAD

**Issue by fabean** [swaywm/sway#5304]
Starting today I can no longer use Sway if I have any type of Bar defined. What I'm seeing is a gray screen and a cursor. That cursor will not move and no keyboard shortcuts do anything. Visually it appears the computer has locked up. 

I was using waybar when I first encountered this, then tried swaybar to test. I ultimately changed to the default config and that also didn't work until I turned off the bar. if I comment out the bar everything works just fine. If once Sway is running I try to launch the bar the current things on screen freeze, but audio keeps playing so the entire computer isn't crashing. While audio is playing I was unable to run any commands to close the window or pause the audio.

Also in trying to get my version I realized running `swaymsg -t get_version` also killed sway if I ran that while it was running.

My version is 1.4

I have a log here which is me getting my session to completely freeze on boot using the default config. https://gist.github.com/fabean/333a31e3294d5f87a5bef07eae5e475f

I just tried doing `coredumpctl gdb sway` and the Timestamp of that error is 1 month ago so when it freezes up like I'm experiencing here isn't a full crash and ending up in these logs.

For now I'm using Sway with no Bar, let me know what else I can try to do to figure out this issue and hopefully help with a patch.

**Comment by Xyene** [comment]
From the symptoms described, this sounds a lot like https://github.com/swaywm/sway/issues/5290 &mdash; Arch Linux, probably updated recently, on a processor with broken `RDRAND`.

**Comment by fabean** [comment]
@Xyene That was it, did a bios update and everything is good now. Thank you very much, sorry I missed the duplicate issue.

**Comment by Xyene** [comment]
No problem, happy to help!
