### ISSUE TITLE
Scratchpad window size is different on several outputs

### ISSUE THREAD

**Issue by chep** [swaywm/sway#5308]
When moving a window to scratchpad, it is resized. When it is shown on another output, it is resized again, even if the resolution is the same. 
Then it seems to keep the new size on all monitors.

If you resize it, the size is kept until you display it on another output.

The size seems to be different regarding the application.

sway version: 1.4

Config:
output DVI-I-1 pos 0,0 res 1920x1080
output HDMI-A-1 pos 1920,0 res 1920x1080

**Comment by c-cube** [comment]
I imagine it could be because of [this](https://github.com/swaywm/sway/blob/5501d14a2e7147b533df12b21368639cf01a7c9c/sway/tree/root.c#L150) where it probably resizes too eagerly?

**Comment by chep** [comment]
It does not happen with every windows. For example it happens with kitty but not with terminator.

**Comment by josefbachmann** [comment]
I have the same problem

sway version 1.5.1

### Description:
In my case: [termite](https://github.com/thestinger/termite)
On startup I open a terminal in my scratchpad like:

```
set $term termite
exec $term --name $scratchterm
for_window [app_id="(?i)$scratchterm"] move to scratchpad, resize set 1800 1000 px, opacity set 0.9;
```

I have two monitors:

```
set $display1 DP-1
set $display2 HDMI-A-1
output $display1 pos 0 0 res 2560x1440
output $display2 pos 2560 0 res 1920x1080
output $display1 mode 2560x1440@143.998001Hz
output $display2 mode 1920x1080@60.000000Hz
```

When open scratchpad (`bindsym $mod+Return scratchpad show`) on my main display1 everything is correct set up (size: 1800x1000px). If I close and reopen scratchpad on the second screen the size has completely changed and is much smaller for the scratchpad terminal window. it doesn't matter on which display I create the scratchpad window, when I open it on the other screen the size of the scratchpad changes.

is my config wrong or is this a bug?
thank you.

**Comment by gilbertw1** [comment]
@josefbachmann I've encountered this exact same issue independently (using alacritty), so I don't believe it's an issue with your configuration. It even happens if you use the default keybindings to place a floating terminal in the scratchpad and recall it on a different monitor.

I have the same use case as you for using the scratchpad and had to end up writing a `run-or-raise` style script that manually enforces the dimension anytime the terminal is recalled from the scratchpad.

**Comment by josefbachmann** [comment]
> [...] had to end up writing a `run-or-raise` style script that manually enforces the dimensions anytime the terminal is recalled from the scratchpad.

@gilbertw1 alrighty. Would you mind sharing the script (pastebin?) or some pointers how you did that? thank you very much.

**Comment by gilbertw1** [comment]
@josefbachmann

Hey, I just put the script into a gist here: https://gist.github.com/gilbertw1/96a745cc9cf19c48052140ded4932253

Using the script, this is what I've got in my sway config:
```
    # Terminal Scratch
    for_window [title="scratchterm"] {
        floating enable
        resize set 3000 1800
        move position center
    }
    bindsym f12 exec sway-run-or-raise.sh "alacritty -t=scratchterm -d 0 0 -e ~/bin/tmuxp.sh" scratchterm 3000 1800 "center"
```

The script basically takes a command to run if the program isn't found, then a title used to find and match the program's window, followed by height and width, and then finally a position. I'm currently using center, but you could replace that with something like "100 200" for the x/y offset.

**Comment by chep** [comment]
Thanks @gilbertw1 I adapted my config like this (it's a little more simple and seems to work for now):
```
for_window [title="scratchterm"] {
        move scratchpad
        resize set width 50 ppt height 75 ppt
}

bindsym XF86Favorites scratchpad show
bindsym $mod+Shift+XF86Favorites exec kitty --title scratchterm
```

In my `autostart.sh` I also start `kitty --title scratchterm`

**Comment by ogost** [comment]
I've encountered  the same problem with kitty and some other applications. I don't think this is an expected behavior. Worked around by adding this to the config:
`bindsym --to-code $mod+minus [app_id="..."] scratchpad show, resize set 960 780, move position center`
