### ISSUE TITLE
Sway crash on lid close/open

### ISSUE THREAD

**Issue by JonnyMako** [swaywm/sway#5320]
```
sway version 1.4-7c37e9d0 (May  9 2020, branch 'master')
```
I see this crash on closing and reopening notebook lid with latest sources.
[gdblog.txt](https://github.com/swaywm/sway/files/4604392/gdblog.txt)

**Comment by emersion** [comment]
Duplicate of https://github.com/swaywm/wlroots/issues/2145

**Comment by emersion** [comment]
Eh, actually this is a different issue it seems.

**Comment by JonnyMako** [comment]
Yes, thanks. I was wondering about that since the other fix was merged 8 days ago. :)

**Comment by emersion** [comment]
Can you try https://github.com/swaywm/wlroots/pull/2179?

**Comment by JonnyMako** [comment]
That fixes the crash, but now, on re-hotplugging the monitor does not bring back the screen. It remains blank. Log attached.
[sway.log](https://github.com/swaywm/sway/files/4604466/sway.log)

**Comment by emersion** [comment]
Maybe this one can help? https://github.com/swaywm/wlroots/pull/2167

**Comment by emersion** [comment]
Closing because the crash has been fixed.
