### ISSUE TITLE
External (HiDPI) screen goes black a few seconds at a time

### ISSUE THREAD

**Issue by vandenheuvel** [swaywm/sway#5328]
* **Sway Version**: 1:1.4-9
* **Debug Log**: I don't think this bug leaves any traces in the log (I've watched the log being written and see no output whatsoever when the bug occurs). I can post it if necessary.
* **Configuration File**: default

I am running Arch with all packages up-to-date. External screen 4K is attached via displayport on an XPS 15 9550, intel graphics are being used.

The external screen goes completely black every few minutes, for a second or two. I am not sure if it happens at regular intervals, I don't think so. The laptop screen stays on. All functionality keeps working while the screen is black (video, audio, typing with the keyboard, etc.). I've done a `tail -f` as the log was getting written, and nothing gets written to the log as this happens.

What I've tried:
* Default config file
* Switching back to GNOME, which works perfectly
* Triggering this event by playing video, starting a browser, opening many screens, moving the mouse, etc. to no avail
* Running sway as a daemon instead
* Asking on IRC how I could further debug this problem (no input received)

**Comment by emersion** [comment]
Anything in `dmesg`?

**Comment by vandenheuvel** [comment]
Great suggestion. Sometimes, I find this entry in the `dmesg`:
```
[x.x] [drm:intel_cpu_fifo_underrun_irq_handler [i915]] *ERROR* CPU pipe B FIFO underrun
```
It doesn't consistently appear with when the screen goes black; I've seen it pop up close to the time of the black screen only once. Searching for the error message leads to a kernel bug, see for example [here](https://bbs.archlinux.org/viewtopic.php?id=231972) or [here](https://bugs.freedesktop.org/show_bug.cgi?id=103229). Although the symptoms are not quite the same (I'm seeing the screen temporarily turn off, rather than flicker), they do have some very specific things in common (e.g. only second screen affected, not both).

The [Arch wiki](https://wiki.archlinux.org/index.php/Dell_XPS_15_9550) does mention a kernel parameter for my laptop model that could stop the flickering, but would no longer be needed.

Is this a bug in sway, or a bug in the kernel or intel graphics that gets triggered by sway, but not by GNOME?

**Comment by vandenheuvel** [comment]
[Bug filed for the kernel](https://bugzilla.kernel.org/show_bug.cgi?id=207701).

**Comment by emersion** [comment]
Intel kernel bugs should be reported here: https://gitlab.freedesktop.org/drm/intel

**Comment by emersion** [comment]
Closing because this isn't a Sway bug.
