### ISSUE TITLE
Default config files mention non existent sway-security man pages

### ISSUE THREAD

**Issue by ericonr** [swaywm/sway#5335]
`security.d/00-defaults.in` mentions the `sway-security(7)` man pages, which seem to have been deleted in 2018, if I understood the git log correctly. It probably makes sense to remove that mention, at least for now, as the file is non existent.

**Comment by emersion** [comment]
Indeed, that's an oversight. Would you be willing to send a pull request to fix this?

**Comment by ericonr** [comment]
I would! Is removing the reference all that's needed or should I try to explain something as well? I don't know anything about the current security situation.

**Comment by emersion** [comment]
Yeah, removing the references to security stuff should be enough. The new security infrastructure isn't yet implemented.
