### ISSUE TITLE
Resizing floating window with the mouse jumps

### ISSUE THREAD

**Issue by minus7** [swaywm/sway#5336]
When you grab a floating window at one of the borders for resizing, then move the mouse one pixel, the window will become larger by the size of window borders in each direction. This is especially noticable with thicker borders (`default_border normal 5`) but should also be quite obvious without that.

Sway version: current master: 2262ae60f4c405b881ca342a96f90865adc60ad0

**Comment by emersion** [comment]
Is this fixed by https://github.com/swaywm/sway/pull/5299?

**Comment by minus7** [comment]
Yes, it does. I forgot searching open PRs :/
