### ISSUE TITLE
Can't use upper part of a Xwayland window

### ISSUE THREAD

**Issue by olly1240** [swaywm/sway#5341]
* Sway Version: 

1.4

* Debug Log:    

https://gist.github.com/olly1240/5cdce4f74ac9522b92bf7cd35187b928

* Configuration File:

https://gist.github.com/olly1240/c2d68495691fad0abeedfbe50329c796

### Description:

I have a two monitor setup, one of them (the HDMI-A-2) is set to a higher position to match their real layout (position 1920, -540). Wayland compatible programs does function the right way, but when an Xwayland window is opened on the higher monitor, I can't access the top part of them. The size I can't access from the top of the window is roughly the offset of the screen. X axis works as intended. Y doesn't. The mouse on the Xwayland window seem to stop at a certain height

Here is the difference in xeyes:

Cursor on top of window in the e-DP-1 monitor (pos 0,0)
![e-DP ](https://user-images.githubusercontent.com/46900833/81939982-55f80600-95f7-11ea-80bf-573d071cf2bc.png)

Cursor on top of window (same position) in HDMI-A-2 (pos 1920, -540):
![HDMI-A-2](https://user-images.githubusercontent.com/46900833/81940163-96f01a80-95f7-11ea-9551-d668223c3dc7.png)

**Comment by emersion** [comment]
https://gitlab.freedesktop.org/xorg/xserver/issues/899
