### ISSUE TITLE
Log spammed with "Unable to add DRM framebuffer" when using Vulkan

### ISSUE THREAD

**Issue by escalade** [swaywm/sway#5343]
When using Vulkan, sway.log is filled with these messages:

00:03:43.876 [ERROR] [backend/drm/util.c:210] Unable to add DRM framebuffer: Invalid argument
00:03:43.876 [ERROR] [backend/drm/atomic.c:145] Failed to set plane 31 properties

There's like a dozen of them every second or so. This happens with RetroArch and RPCS3 which is what I have tested, but only in fullscreen.

Sway version: aa48b92
wlroots version: 42e485d
sway.log: http://ix.io/2m0q

**Comment by emersion** [comment]
Duplicate of https://github.com/swaywm/wlroots/issues/2181
