### ISSUE TITLE
Unable to copy to/from clipboard using Vim in terminal

### ISSUE THREAD

**Issue by kevinoid** [swaywm/sway#5352]
* Sway Version: `1.4` (from Debian `sway` package version `1.4-2`)
* Debug Log: https://gist.github.com/kevinoid/cbe093df11408e776e0558b5b7929016
* Configuration File: Default

Steps to reproduce:
1. Start two Wayland-native terminal emulators (`xfce4-terminal` in debug log).
2. Start `vim` in one of them.
3. Copy text from `vim` to clipboard (e.g. using `"+yy` to copy a line).
4. Attempt to paste text into the other terminal (e.g. pressing `Shift+Ctrl+v`).  **Nothing pastes (from Vim to terminal).**
5. Copy text from terminal window into clipboard (e.g. selecting something then pressing `Shift+Ctrl+c`).
6. Attempt to paste text into `vim` (e.g. using `"+p`).  **Original copied text pastes (not text copied from terminal).**

The debug log contains several lines with:

> [`[xwayland/selection/selection.c:117]`](https://github.com/swaywm/wlroots/blob/4cb0697/xwayland/selection/selection.c#L117)`not handling selection events: no seat assigned to xwayland`

Which may help explain the issue.

Thanks,
Kevin

Note: Copying to/from a GVim xwayland window works correctly.

**Comment by progandy** [comment]
That is not a sway bug. vim does not support the wayland clipboard and the xorg clipboard is only accessible if an XWayland window is focused.

neovim should work with wl-clipboard, or you might be able to configure vim to call wl-clipboard [like this](https://old.reddit.com/r/Fedora/comments/ax9p9t/vim_and_system_clipboard_under_wayland/) or modify [vim-fakeclip](https://github.com/kana/vim-fakeclip).

**Comment by kevinoid** [comment]
Thanks @progandy.  I am actually using remappings similar to the ones you linked.  Pasting is adequate, but yanking is far from adequate.

Could you clarify why there is no interest/ability to support clipboard sync without a focused XWayland window?

**Comment by progandy** [comment]
In wayland, the clipboard is only readable by the focused window as a security measure. For compatibility reasons XWayland is a bit more lax and allows any xorg client access while an XWayland window is focused. wl-clipboard can work around this by using the clipboard manager protocol, but the goal is to have that secured with some access control in the future (that seems to be not high on the priority list for now, though)

**Comment by kevinoid** [comment]
Ah, I see.  Thanks for the explanation.  Good to know.

I'll take a closer look at [vim-fakeclip](https://github.com/kana/vim-fakeclip).  Thanks again!

**Comment by kevinoid** [comment]
Thanks again for the [vim-fakeclip](https://github.com/kana/vim-fakeclip) suggestion @progandy!

Just a quick follow-up for anyone in a similar situation: now that kana/vim-fakeclip#32 has been merged, wl-clipboard-x11 is no longer required.  I'm using vim-fakeclip with the following addition to `.vimrc`:

```vim
let g:fakeclip_provide_clipboard_key_mappings = !empty($WAYLAND_DISPLAY)
```
It's not perfect, but much better than the mappings I was using.  Thanks again!

**Comment by toadjaune** [comment]
Just in case someone ever stumbles on this issue in the future, FYI, vim now has a `clipboard_wayland` compile option that works just fine without any workaround plugin. Make sure you have a recent enough vim version, and that it's enabled on your build with `vim --version`, and you should be good to go !

**Comment by kevinoid** [comment]
Thanks @toadjaune!  To close the loop, it looks like this was implemented in https://github.com/vim/vim/pull/17097 appearing in version 9.1.1485 (2025-06-27).
