### ISSUE TITLE
sway crash when docking and disabling laptop screen

### ISSUE THREAD

**Issue by shibumi** [swaywm/sway#5362]
sway version: 1.4
Distribution: Arch Linux

When I dock my X220, one of my screens get activated as expected.
My X220 just supports two outputs, so I normally did the following for activating the second external screen too:

```
swaymsg output LVDS-1 disable
```

After typing this line and pressing enter, the LVDS screen from my laptop gets deactivated and the other external screen gets activated.

Since the last (2)? versions of sway this behavior changed. When I trigger the line above and try to disable my LVDS screen, it gets disabled but I will also lose my sway session and will be greeted by TTY. I expect a crash here. I will try to start sway with debugging information and will attach this to this issue here.

**Comment by emersion** [comment]
Please provide a stack trace. You can do so by compiling from source, reproducing the crash and then running `coredumpctl gdb` and then `bt full`.

Here are some instructions to compile from source: https://github.com/swaywm/sway/wiki/Development-Setup#compiling-as-a-subproject

**Comment by Xyene** [comment]
Closing this ticket due to inactivity; feel free to reopen with logs if you are able to reproduce the crash.
