### ISSUE TITLE
Popups on Sublime Text 4074 not working

### ISSUE THREAD

**Issue by Elinvynia** [swaywm/sway#5364]
* Sway Version: 1.4

* Debug Log: https://pastebin.com/Ly0R0Z52

* Configuration File: https://pastebin.com/wPgF5fHU (not very relevant)

* Stack Trace, if sway crashes: no crash

Hello! This issue could be possibly relevant to: <https://github.com/swaywm/sway/issues/3139>
I believe this is an issue with sway, after talking with the developers of sublime I was told popups work just fine under gnome/wayland.

The following gtk calls are supposedly used for creating the popup:
```
gtk_window_new(GTK_WINDOW_POPUP);
gtk_window_set_type_hint(window, GDK_WINDOW_TYPE_HINT_DIALOG);
gtk_window_move(window, x, y);
gtk_window_set_transient_for(window, parent_window);
gtk_widget_show_all(window);
```

Minimal steps to trigger a popup in Sublime (so you can test it yourself if you want):
Open console with CTRL+\`
`import sublime`
`sublime.active_window().active_view().show_popup('Hello world!')`

Expected behavior: popup appears
Actual behavior: nothing happens

**Comment by trobjo** [comment]
I also run Sublime and Sway. I do not have this issue. Are you using XWayland or only Wayland?

**Comment by Elinvynia** [comment]
This fixed my issue, thanks a lot!
