### ISSUE TITLE
Move windows relative to output

### ISSUE THREAD

**Issue by Samed-Hamma** [swaywm/sway#5376]
### Issue :
Positioning floating windows is not flexible enough.
Example: I am running _krunner_ as a launcher and have two monitors with different resolutions, I can center top position _krunner_ in the first output, but it gets messy when run in the second one.

### Proposal :
Add possibility to move windows relative to the containing output:
1. add **relative** keyword to the move command with (`move up|down|left|right`) + add keywords (`move top|bottom` when used with **relative**)
2. add **%** as a unit to `move position`

P.S. This is my first ever issue post on github, I hope it's clear enough and not breaking any rules.
Thanks for the great WM, I use it as my daily driver, and it helps me get more active and involved in the FOSS community.

**Comment by emersion** [comment]
Thanks for taking the time to write this feature request, However we don't accept new window management features unless i3 implements them.

**Comment by Samed-Hamma** [comment]
Thanks for your fast answer @emersion , looks like I need to make this feature request to the i3 project  in order to get it implemented in sway :p 
I understand this is a policy thing, (which I am curious about).
What if I implement it myself ? Will my merge request get rejected because of this policy ?

**Comment by emersion** [comment]
Yes. You're of course free to keep it in your Sway fork.
