### ISSUE TITLE
Feature request: swaybar: Status blocks on the left side

### ISSUE THREAD

**Issue by mox-mox** [swaywm/sway#5377]
Would it be possible to have swaybar show status blocks on the left or middle part of the bar? I have been thinking about a small addition to the IPC protocol. If a block (or array of blocks) is prefixed with `align_left`, `align_middle` or `align_right`, it gets put to the respective area, if there is no prefix, it is placed according to current standard behaviour, that is in the right.
A piece of sample bar input might then look like the following:

```
{
	"version": 1,
	[
		[
			"align_left":
			[
				{
					"full_text": "E: 10.0.0.1 (1000 Mbit/s)",
					"color": "#00ff00"
				}
			],
			"align_right":
			[
				{
					"full_text": "2012-01-05 20:00:01"
				}
			]
		],
		...
	]
}
```
I also asked the same question for i3bar [here](https://github.com/i3/i3/issues/4101), i3 is not going to support this sadly.

**Comment by emersion** [comment]
Sorry, if i3bar rejected it, we won't be implementing it. It can be implemented in a swaybar fork or in a third-party bar.
