### ISSUE TITLE
sway does not use Intel GPU in dual-GPU (Optimus) configuration

### ISSUE THREAD

**Issue by christianrauch** [swaywm/sway#5392]
Before I get a rant about using Nvidia hardware: This issue is about the Intel/Nvidia GPU selection on Optimus systems and not trying to launch sway with Nvidia drivers.

On an Optimus notebook that runs perfectly with GNOME Shell and Weston on the integrated Intel GPU, sway resist to start and complains about the Nvidia drivers.

Like GNOME and Weston, sway should start on the Intel GPU.

sway version: 1.4
configuration: default (i.e. no user file created)

**Comment by Emantor** [comment]
`sway --my-next-gpu-wont-be-nvidia` as output by the error message should start sway even if you have the proprietary nvidia drivers installed..
Nevertheless the issue template clearly states that bug reports about the nvidia driver are not welcome here.

**Comment by emersion** [comment]
If you have the nvidia driver loaded, there's a chance it'll cause breakage, so we error out. This is by design.

**Comment by emersion** [comment]
Note, we can't just ignore the nvidia GPU, otherwise users complain about external outputs not working.

**Comment by christianrauch** [comment]
I think there is a misunderstanding here: This issue is NOT about starting sway on Nvidia hardware at all.

This issue is about having sway prefer the integrated GPU over the dedicated GPU - independent of whatever hardware and drivers are used for the dedicated GPU. This is not a question about which drivers are installed, but about which GPUs are used.

As far as I know, Weston does not have any Nvidia specific code branches and it is still capable of selecting the integrated GPU. Why shouldn't this be possible with sway? I don't see how the driver for the dedicated GPU can negatively affect sway running on the internal GPU.

**Comment by emersion** [comment]
Sway already selects the iGPU, but supports multi-GPU. So all GPUs are opened on startup.

**Comment by christianrauch** [comment]
> Sway already selects the iGPU, but supports multi-GPU. So all GPUs are opened on startup.

Why is then not just blacklisting all unsupported GPUs and use only the supported GPUs? There could be a simple warning that some GPUs cannot be used. But sway should not suggest installing the nouveau driver when I want to use the integrated Intel GPU.

**Comment by emersion** [comment]
>Note, we can't just ignore the nvidia GPU, otherwise users complain about external outputs not working.

**Comment by christianrauch** [comment]
> > Note, we can't just ignore the nvidia GPU, otherwise users complain about external outputs not working.

Sorry for insisting on this, but this does not make sense. On Optimus hardware, you can use the external monitor output with the integrated GPU. This works perfectly with GNOME Shell and Weston.
If users still want to use the discrete GPU, you can point them to the "sway does not support Nvidia" statement.

And even if - using sway without an external monitor is still better than not using sway at all, right? :-)

**Comment by emersion** [comment]
>Sorry for insisting on this, but this does not make sense. On Optimus hardware, you can use the external monitor output with the integrated GPU. This works perfectly with GNOME Shell and Weston.

Not the case of all hardware.

>If users still want to use the discrete GPU, you can point them to the "sway does not support Nvidia" statement.

We prefer it the other way around: users can't use Sway, and if they understand all the consequences, they can configure Sway to kind-of-work.

>And even if - using sway without an external monitor is still better than not using sway at all, right? :-)

You can use sway -- just add the CLI flag and run with `WLR_DRM_DEVICES=/dev/dri/card0`. Please don't report bugs when running with this flag.

**Comment by trougnouf** [comment]
> You can use sway -- just add the CLI flag and run with `WLR_DRM_DEVICES=/dev/dri/card0`. Please don't report bugs when running with this flag.

I have a dual-GPU setup where I use the AMD GPU specifically for desktop and NVidia for compute. I tried `WLR_DRM_DEVICES=/dev/dri/card0 sway` and `WLR_DRM_DEVICES=/dev/dri/card1 sway` but I still get the same warning. Either sway is ignoring that variable or it should run with no warning.

**Comment by AdsonCicilioti** [comment]
@trougnouf use `--unsupported-gpu` flag.

**Comment by BranchManager** [comment]
> > You can use sway -- just add the CLI flag and run with `WLR_DRM_DEVICES=/dev/dri/card0`. Please don't report bugs when running with this flag.
> 
> 
> 
> I have a dual-GPU setup where I use the AMD GPU specifically for desktop and NVidia for compute. I tried `WLR_DRM_DEVICES=/dev/dri/card0 sway` and `WLR_DRM_DEVICES=/dev/dri/card1 sway` but I still get the NVidia warning. Either sway is ignoring that variable or it should run with no warning.


I have been trying to do this myself. With no luck. Hyprland works on my system at home but even with the --unsupported-gpu flag some terminal emulators won't work.
