### ISSUE TITLE
Sway hangs while complaining about xkbcommon

### ISSUE THREAD

**Issue by nathanblair** [swaywm/sway#5396]
* Sway Version:
(The latest alpine apk sway)
```
sway -v

sway version 1.4
```

* Configuration File:
Reproducible with the default config

On a pretty fresh `alpine` linux install, I installed `sway` through `apk`. `apk` added the `sway` dependencies `wlroots`, `wayland`, and some others I'll have to verify in a moment.

But on launching sway through booting into `alpine` (on bare metal) and entering `sway` into the tty, `sway` is hanging the system without displaying the DE.

I've included the debug log I get while running sway through the tty. It looks like there's something with a missing `xkbcommon` package, but I'm not familiar with `alpine` to know where that package is. Regardless, it seems it should be included with `alpine`'s `apk` runtime-dependencies if its a hard requirement, no?

**Edit**: Checked in the live environment and `libxkbcommon` is installed and is showing as a proper dependency of sway in the `alpine` `apk` package manager. So missing package doesn't appear to be the issue.

[sway.log](https://github.com/swaywm/sway/files/4696024/sway.log)

I'll be populating this issue as I do some more debugging from the actual environment.

**Comment by emersion** [comment]
```
xkbcommon: ERROR: failed to add default include path /usr/share/X11/xkb
```

This is coming from `xkb_context_new` and is probably a bug in xkbcommon's Alpine package. Nothing we can do about it, please report to the Alpine devs.

**Comment by nathanblair** [comment]
In the `alpine` system, I don't have the `/usr/share/X11/xkb` directory, so that's certainly not a good start.

@emersion would you mind if I continued documenting my findings in this issue (without re-opening the issue)? I understand closing it if it isn't strictly a `sway` issue; I just want to make it easier for anyone else to come along and resolve the issue if they have a similar problem. Similar `sway` hanging issues seemed to result from `swaybg` problems; I haven't had a reason to believe this is the case yet though.

**Comment by nathanblair** [comment]
I'll be sure to take a look at how `alpine` might be related to this, for sure. Thanks!

**Comment by nathanblair** [comment]
Okay, so it appears installing `xkeyboard-config` resolves this issue.

For alpine, I just ran `apk add xkeyboard-config`.

Is it perhaps appropriate to add `xkeyboard-config` to the `alpine` dependencies? I think `swaylock` is explicitly what requires `xkeyboard-config`.

From the `alpine` package list (https://pkgs.alpinelinux.org/package/v3.11/main/x86_64/xkeyboard-config), `i3lock` explicitly calls out needing `xkeyboard-config` in addition to `libxkbcommon`. I would think `swaylock` would follow a similar pattern?

**Comment by emersion** [comment]
Yeah, I think that would make sense. But Sway is the package that requires `xkeyboard-config` here (because it doesn't start without it).

**Comment by progandy** [comment]
On arch ```libxkbcommon``` requires ```xkeyboard-config```. Maybe alpine should do that, too.

**Comment by nathanblair** [comment]
> 
> 
> On arch `libxkbcommon` requires `xkeyboard-config`. Maybe alpine should do that, too.

Certainly something I can open up a dialog about on `alpine`. It looks like Drew is the maintainer for the `sway` series of packages on alpine. Would Drew be interested in this discussion?

I could ask whether it makes sense to add `xkeyboard-config` as a dependency for `libxkbcommon` or strictly as a dependency to `sway`.

I would say: I think `sway` fails to start because the default `sway` config calls out to `swaylock`. I haven't tested it but maybe commenting out that `swaylock` line (which I think is actually a callback for `swayidle`) would allow `sway` to launch?

**Comment by nathanblair** [comment]
https://gitlab.alpinelinux.org/alpine/aports/-/issues/11586

I've opened up this against the alpine aports issue tracker.

**Comment by nathanblair** [comment]
> 
> I would say: I think `sway` fails to start because the default `sway` config calls out to `swaylock`. I haven't tested it but maybe commenting out that `swaylock` line (which I think is actually a callback for `swayidle`) would allow `sway` to launch?

Nevermind. This appears to be completely false. The default config did not have the `swayidle`/`swaylock` commands uncommented. It seems `xkeyboard-config` would be a runtime-dependency of `sway` directly (or just `libxkbcommon`).
