### ISSUE TITLE
Feature request: Command to set layer of window

### ISSUE THREAD

**Issue by rhysperry111** [swaywm/sway#5404]
Hi, I am not sure how the layer shell protocol works, so forgive me if this would not be possible.

What I am proposing is a configuration command to change the layer of a window. The reason this would be useful is that you can use XWayland based apps like GLava which are meant to be in the background, but do not have native support for the layer_shell protocol.

An example of a use for this would be:
`for_window [class="GLava"] move to layer background`

**Comment by emersion** [comment]
No, regular apps don't behave like layer-shell surfaces. The solution is to add layer-shell support to these clients so they can behave as expected.

**Comment by rhysperry111** [comment]
Is there any workaround for XWayland apps like GLava?

**Comment by emersion** [comment]
No, these need to be ported to Wayland.

**Comment by progandy** [comment]
If you are interested in creating a glava version for wlroots, then Scoopta has a sample application called [glpaper, GPLv3](https://hg.sr.ht/~scoopta/glpaper), which can probably be  adapted to render the glava shader without great difficulty.

**Comment by rhysperry111** [comment]
@progandy How would I do that (I don't have much experience with programming)? Would I need to modify glava to somehow use glpaper as a renderer?
