### ISSUE TITLE
DPMS

### ISSUE THREAD

**Issue by crondog** [swaywm/sway#541]
Would it be possible for sway to handle turning on and off the monitor? Orbment currently has https://github.com/Cloudef/orbment/blob/master/plugins/core-dpms/core-dpms.c to handle this. 

Could something like this be implemented inside sway with a config option or maybe with swaylock?

**Comment by SirCmpwn** [comment]
I'd like to see a protocol extension written for this, and then a seperate daemon to manage it.

**Comment by crondog** [comment]
Hmm interesting. That sounds like a better idea. I'll need to look into protocol extensions over the weekend and report back

**Comment by SirCmpwn** [comment]
https://github.com/SirCmpwn/sway/tree/master/protocols

They're pretty straightfoward. Write an XML file describing the interface, add it to CMakeLists.txt, and you'll end up with a header to include.

**Comment by SirCmpwn** [comment]
See also https://github.com/SirCmpwn/sway/blob/master/sway/extensions.c

**Comment by crondog** [comment]
Thanks for the tip

**Comment by Fale** [comment]
any news on this?

**Comment by SirCmpwn** [comment]
Nope.

**Comment by Cloudef** [comment]
While orbment's core-dpms implements this using own timer and wlc's set_sleep. I think drm has dpms api too actually.

**Comment by hosaka** [comment]
Looking at DRM docs, there is an api for setting dpms on drm_connector, but no way of getting current state. Would using wlc set_sleep approach be preferable?

**Comment by airstep** [comment]
The question is how to make it possible? 

For now I can advice to switch to tty(n) and it works by default - screen is going off by some time. Why I can't do this in wayland? 

My tty(n) is also in KMS mode (like wayland)... 

So how tty(n) can turn screen off, but wayland can't - if them both in KMS mode? 

What you think?

**Comment by Fale** [comment]
I think the situation around this could/should/will change very soon due to #1076

**Comment by flounders** [comment]
I see on the status issue for for wlroots ([wlroots/#9](https://github.com/swaywm/wlroots/issues/9)) that DPMS is checked off. I also see that DPMS is an unaddressed bounty problem as well. In a general, overview type answer, given the support in wlroots what needs to happen to bring this to Sway? This question is coming from someone not too familiar with the project or Wayland compositors. If it's not too far beyond my skill set, I wouldn't mind working on this as I am able.

**Comment by SirCmpwn** [comment]
It's not currently a priority in the wlroots port. Let's swing back to it later.
