### ISSUE TITLE
Plugging in a secondary monitor at runtime terminates all applications

### ISSUE THREAD

**Issue by main--** [swaywm/sway#5418]
Sway breaks when I plug in / turn on my secondary monitor. The problem appeared after I enabled FreeSync in the monitor's settings (I am not using FreeSync with sway, as I'm on i915). What I see is that after flickering briefly, all displays show a grey background and all applications are gone. All applications are terminated, but sway itself does not crash and I can close it using the hotkey. Everything is fine if I connect the display before launching sway.

Version: sway version 1.4
Debug log: https://gist.github.com/main--/bd5c8c5bf82f8581376babb4756f7445

**Comment by emersion** [comment]
```
2020-06-04 12:54:41 - wl_registry@2: error 0: invalid global wl_output (31)
```

Should be fixed in Sway master.
