### ISSUE TITLE
Graphic tablet lag

### ISSUE THREAD

**Issue by quantmint** [swaywm/sway#5422]
* Sway Version:
1.4
* Debug Log:
https://gist.github.com/quantmint/1f28243be774462cf8ebb7aa884f8c87

I am using a graphic tablet(huion h1161), it works perfectly in Xorg and Gnome on wayland, but when i use it in sway after 5-10 seconds it starts to lag badly, it's seems that refresh rate of the graphic tablet decreases. This issue is completely random and persist most of the time. The graphic tablet is supported through digimend driver.

**Comment by emersion** [comment]
Can you try Sway master?

**Comment by quantmint** [comment]
It's perfect in sway master!!!

**Comment by emersion** [comment]
Glad to hear it, @Xyene has been working hard to fix these tablet issues :)
