### ISSUE TITLE
Sway unresponsive after gpu hang (ecode 9:1:85dffffb)

### ISSUE THREAD

**Issue by mithodin** [swaywm/sway#5424]
I have a rare, but persistent problem on my new notebook with Intel UHD Graphics 620. At a seemingly random moment, the system will freeze from a few seconds, after which I can move the mouse cursor, but not interact with sway or any application (e.g. no switching workspaces by keyboard or mouse, no input into applications, ...).
The problem seems to be a GPU hang. I have reported this at the mesa bug tracker (https://gitlab.freedesktop.org/mesa/mesa/-/issues/2944) but they were not able to reproduce the issue.
I have attached a sway debug log as well as the gpu error log. Maybe someone here can shed light on the problem?

[sway.log](https://github.com/swaywm/sway/files/4736609/sway.log)
[error.log](https://github.com/swaywm/sway/files/4736610/error.log)

**Comment by emersion** [comment]
This is a Mesa bug, we can't do anything about it.

**Comment by mithodin** [comment]
I'm not asking you to fix the gpu hang, I was hoping you might have an idea what triggers the hang in the first place.

**Comment by emersion** [comment]
No idea, sorry
