### ISSUE TITLE
[Feature request] Window swallowing

### ISSUE THREAD

**Issue by avrelaun** [swaywm/sway#5434]
This is a feature from a dwm patch: https://dwm.suckless.org/patches/swallow/

The behaviour is explained in this video: https://www.youtube.com/watch?v=92uo5OBOKfY

Basically, everytime we open a gui app from terminal, the original terminal is hidden until the gui window is closed. Most apps would benefit from launching this way, except some use case which is why a configurable blacklist might be useful.

**Comment by emersion** [comment]
Sorry, we won't add new window management features unless i3 adds them too.

**Comment by markstos** [comment]
@avrelaun You do something similar in Sway using tabs or stacked windows. With your terminal window focused, use the keybindings for `split vertical` followed by `layout tabbed`. Bind the combination to a single key if you'd like. Now launch whatever GUI app you want from the terminal. It will appear in a new tab that covers the terminal. When the GUI app exits, you'll be back at the the terminal. No need to repeat setting up tabbed mode again for that terminal session.

**Comment by BoostCookie** [comment]
> Bind the combination to a single key if you'd like.

I don't think this is possible or even necessary.
`bindsym $mod+n layout toggle tabbed split`
works just fine. Press mod+n before launching your new window and press it again after closing it.

**Comment by markstos** [comment]
`layout toggle tabbed split` converts the parent container to tabs, which might not be what you want.

To make a tabbed container that contains only the current window, it would be:

      `split horizontal; layout tabbed`

The next window you launch will then appear as a new tab above the current window. I use one keybinding for the split and one for the layout switch, but combine them into one step if you like. 

       bindsym $mod+n split horizontal; layout tabbed

**Comment by oruamy** [comment]
> Basically, everytime we open a gui app from terminal, the original terminal is hidden until the gui window is closed.
This app perhaps does what you want:
https://crates.io/crates/swayhide
