### ISSUE TITLE
Issue with mesa 20.1.0 and Xwayland

### ISSUE THREAD

**Issue by nerokeygen** [swaywm/sway#5436]
I just searched for issues for "mesa 20.1' and couldn't find so i will report.
I don't know if this is mesa's issue and im new to github, im bad at English so please forgive me and i'm sorry if I'm wrong something.
this fixed downgrading to mesa 20.0.7
Distro:Gentoo(stable branch) stage 3. it can reproduce on clean installation with only sway and mesa driver etc. -O2 -march=znver1.
GPU:RX 580 ( I have nouveau for GPU that I use only to connect displays. I use old quadro fx 580 for that)
sway version:1.4
wlroots version:0.10.0
(version from packages.gentoo.org. all installed from emerge. just note, it still occurs if I install latest cloning git.)
When I try to launch Xwayland app, just behaves like it successfully launched, but does not appear any window. tested with firefox-bin, xclock, xeyes. normal X wm works without issues in that enviroment. so it's something releated to Xwayland.
When I just launch sway from tty, and try to launch X program, and exit sway,
I can see some logs on console.
one is xkbcomp error, but it tells that it's not fatal to x server.
the other error that I remember that appears is "modifiers specified but dri is too old"
sorry that I'm too lazy to reinstall newer mesa to reproduce this issue, but I just reported this in case it helps. If it's annoying, or bug unreleated to sway, sorry, please ignore.

**Comment by emersion** [comment]
Your bug report is missing debug logs. Please add a link to the full debug log file.

**Comment by nerokeygen** [comment]
Sorry that I'm too lazy to reinstall latest mesa to reproduce because I'm very frustrating that qtwebengine emerge failed >10 times and I have my hands full.
to be honestly, I don't have any issues on 20.0.7 and it is better to use that now. and I don't even know if it's a bug in mesa, so I can't say anything about it. I just reported for in case it helps so if anyone are interested,please send debug log. sorry. I don't have a patience to break my setup again that I finally figured to work after 1 week or something.

**Comment by Quarky9** [comment]
I ran into exactly the same issue as @nerokeygen yesterday & today. 
After all kinds of debugging finally downgraded mesa to 20.0.7 and boom XWayland apps started to appear / work again. This was on Navi10 AMGGPU.

Trying the same next on Intel GPU.

I ran sway with -d -V and saw no explicit errors other than the messages descried in the original post.
Happy to provide logs for sway up to launching e.g xeyes if you guys are still interested.

**Comment by emersion** [comment]
Yes, please provide debug logs.

**Comment by Quarky9** [comment]
I just tried running Sway with Mesa 20.0.8 and 20.1.1 on an Intel i7-6500U integrated graphics. 
Kernel 5.2.14.

XWayland works with both Mesa versions. So the problem seems to be AMDGPU related only.
Testing further later this week ...

**Comment by Quarky9** [comment]
OK tried again now with Kernel 5.7.2 and Mesa 20.1.1 on my AMDGPU setup.
No more issues with XWayland all good. No idea what that has been.
Please close/ignore.
