### ISSUE TITLE
Documenting the "include" config directive

### ISSUE THREAD

**Issue by apiraino** [swaywm/sway#5437]
Hello,

I'd like to use a replacement for i3 `set_from_resource`. As suggested [here](https://github.com/swaywm/sway/issues/2336#issuecomment-469073680) one can workaround importing an external file.

I've read the [man page](https://www.mankier.com/5/sway#include) and tried various combinations but could't figure out how it works, when I reload Sway I always get a config error.

A little help?

Thanks

**Comment by emersion** [comment]
Please ask questions on IRC.
