### ISSUE TITLE
Marks in title bars are not updated when set on current container with children

### ISSUE THREAD

**Issue by lbonn** [swaywm/sway#5460]
sway version 1.4-90d936d4 (Jun 13 2020, branch 'master')

Steps to reproduce:
- create a container with children (e.g: `H[a b]`)
- prepare a command to set a mark `sleep 2; swaymsg 'mark xx'`
- focus on `H[a b]` before sleep finishes

`H[a b]` should then have "[xx]" in its title bar but it does not show until focus is moved to some other container.

An interesting variant (how I found this) is when I use rofi with some script to get a mark name as input and apply it on the currently focused container (`H[a b]`), the mark string appears but blinks at roughly 1Hz.

Maybe a damage tracking issue?

**Comment by lbonn** [comment]
After more tests, it seems that the blinking coincides with my bar (swaybar) refreshing the time and the second bug does not occur when sway is run without a bar (refresh is immediate).

However, the first reproducers still occurs with no bar.

**Comment by emersion** [comment]
Very likely a damage tracking issue indeed.

**Comment by lbonn** [comment]
Another clue: I can only reproduce the blinking using a layer shell menu (bemenu or rofi modified to use layer shell). If I use stock rofi using x11, I get no blink and immediate refresh.

**Comment by vyivel** [comment]
Should be closed by https://github.com/swaywm/sway/pull/6844.

**Comment by lbonn** [comment]
Just confirming that it's not happening anymore (`sway version 1.10-dev-829c75b9 (Feb 27 2024, branch 'master')`)
