### ISSUE TITLE
Sway doesn't send modifiers to all wl_keyboard instances

### ISSUE THREAD

**Issue by wb9688** [swaywm/sway#5462]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1643991. I could reproduces it on the Sway version packaged by Debian Unstable and one built pretty recently from the `master` branch.

@kennylevinsen said on IRC:

>while firefox is not a particularly good citizen (in fact, it is quite an awful one - it wouldn't even have been my first bug in the keyboard handling), it appars that sway is failing to report modifiers on *all* the firefox keyboard instances

>(why yes of course firefox has *multiple* wl_seat and wl_keybaord instances)

>yes, sway (or wlroots) not bringing all the wl_keyboard instances up to speed on currently held modifiers is a bug there.

>oh, just to clarify as I see it could be misinterpreted: I mean that only one wl_keyboard instance seem to receive modifiers, but at least one other wl_keyboard is receiving keypresses without having the modifiers. The latter keyboard is only brought up to speed later when modifiers change again.

**Comment by kchibisov** [comment]
Since the bug report is a bit incomplete, I'll add a `WAYLAND_DEBUG=1 firefox` and a version I can repro the issue on.

sway version 1.4-c22caa54 (Jun 13 2020, branch 'HEAD')

[firefox.log](https://github.com/swaywm/sway/files/4788935/firefox.log)

In a log you can notice

```
[718814.669] wl_keyboard@60.enter(178598, wl_surface@41, array)
[718822.529] wl_display@1.delete_id(51)
```

And not any modifiers after that event `enter` event. However sway **must** send `modifiers` event after `enter`. On the other side for `wl_keyboard@27` in the same log the `modifiers` event is presented right after `enter` as it should.

```
[717857.293] wl_keyboard@27.enter(178591, wl_surface@41, array)
[717857.309] wl_keyboard@27.modifiers(178592, 1, 0, 0, 0)
```

**Comment by Xyene** [comment]
Wild guess: we're not sending the modifiers on keyboard creation, which seems to be what's happening here. Does the below patch fix the issue? (Untested apart from that it compiles.)

```diff
diff --git a/types/seat/wlr_seat_keyboard.c b/types/seat/wlr_seat_keyboard.c
index b366e0af..c084b5b8 100644
--- a/types/seat/wlr_seat_keyboard.c
+++ b/types/seat/wlr_seat_keyboard.c
@@ -469,6 +469,8 @@ void seat_client_create_keyboard(struct wlr_seat_client *seat_client,
                }
 
                wl_array_release(&keys);
+
+               wlr_seat_keyboard_send_modifiers(seat_client->seat, &keyboard->modifiers);
        }
 }
 ```

**Comment by wb9688** [comment]
@Xyene: I could confirm that that patch works (if I manually change the code like that, `git apply` doesn't like it as you posted it here with spaces while there are tabs in the actual file).

**Comment by Xyene** [comment]
Thanks for testing!
