### ISSUE TITLE
mpv does not receive pointer events

### ISSUE THREAD

**Issue by minus7** [swaywm/sway#5464]
When starting mpv in fullscreen, paused and with `--force-window=immediate` (which I assume causes it not to render anything until mouse input or so is received), it will just display a black screen and not receive mouse motion events (observed using `WAYLAND_DEBUG=1`). After moving the mouse cursor to another output and back again it starts receiving motion events but only renders on a portion of the screen corresponding to the size of the image content.
As with #5463, this issue appeared between [45859be](https://github.com/swaywm/sway/commit/45859be03f14fa0506ab8518feaec5ddb157e318) and [e19bd1e](https://github.com/swaywm/sway/commit/e19bd1e47441e6292eb77d7caa8b3211666bef2e).

Edit: Requires `for_window [app_id="mpv"] floating enable` to be configured to trigger

Reproducer: `mpv /usr/local/share/backgrounds/sway/Sway_Wallpaper_Blue_1136x640.png --no-config --fs --force-window=immediate --pause`

**Comment by emersion** [comment]
May be fixed by https://github.com/swaywm/wlroots/pull/2288

**Comment by minus7** [comment]
Yep, it's fixed, thanks
