### ISSUE TITLE
Making the command block implementation generic

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/sway#547]
It would be nice if we tweaked the implementation of command blocks to work for any command. That is, things like this:

```
output HDMI-A-1 {
    pos 1920,0
    res 1920x1080
    bg ~/wallpaper.png
}
```

Would be expanded and run as three seperate commands:

```
output HDMI-A-1 pos 1920,0
output HDMI-A-1 res 1920x1080
output HDMI-A-1 bg ~/wallpaper.png
```

Existing command blocks would change so that this:

```
bar {
    status_command custom_statusbar
    position top
    colors {
        statusline #ffffff
        background #323232
        focused_workspace #32323200 #32323200 #ffffff
        inactive_workspace #00000000 #32323200 #666666
        active_workspace #00000000 #32323200 #666666
    }
}
```

Would be equivalent to this:

```
bar status_command custom_statusbar
bar position top
bar colors statusline #ffffff
bar colors background #323232
bar colors focused_workspace #32323200 #32323200 #ffffff
bar colors inactive_workspace #00000000 #32323200 #666666
bar colors active_workspace #00000000 #32323200 #666666
```

I think this would simplify our implementation of command blocks, simplify the documentation, and allow for more flexibility.

**Comment by SirCmpwn** [comment]
A problem that comes to mind is that bar config blocks can specify the bar ID for multiple bar commands. I think I'm willing to make a breaking change here, considering that most people don't have multiple bar configs, and support something like this:

    bar "bar-0" {
        ...
    }

Instead of the i3-compatible:

    bar {
        id "bar-0"
        ...
    }

Though if anyone can think of a good way to get both working, that'd definitely be better.

**Comment by SethBarberee** [comment]
Any more progress on this? I think this is a great idea for the blocks described above and also to configure others not mentioned.

**Comment by SirCmpwn** [comment]
No one has invested any time in this as far as I know.

**Comment by minus7** [comment]
The suggested flexibility closely resembles what [ferm](http://ferm.foo-projects.org) does for iptables: http://ferm.foo-projects.org/download/examples/dsl_router.ferm
I very much like the idea, although it's kind of sad that i3 doesn't want to go that way.
Special case-ing the bar block shouldn't be a big problem.
