### ISSUE TITLE
Window may not be able to move itself?

### ISSUE THREAD

**Issue by jakbyte** [swaywm/sway#5475]
* Sway Version: 1.4

I was playing [OneShot](https://www.oneshot-game.com/), and in one ending the game window shakes violently, and the game creates a secondary window which has the main character rendered inside and moves every frame as if the character is walking out of the game window. However, the game window only gets recentered and the character window is stuck in the center of the screen as well. I've been told this works in i3. I'm not sure if this is a problem with Sway/Wayland/OneShot/etc., so it'd be helpful if someone could do a bit of testing.

**Comment by rkevin-arch** [comment]
I made a simple script using PyQt to demonstrate the issue:
```python3
#!/usr/bin/python

import sys
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QApplication, QLabel
from qasync import QEventLoop
import asyncio

class MainWindow(QLabel):
    def __init__(self):
        super().__init__()
        self.setWindowFlags(Qt.FramelessWindowHint | Qt.WindowStaysOnTopHint)
        self.setMinimumSize(100, 50)
        self.setMaximumSize(100, 50)
        self.setGeometry(0,0,100,50)
        self.updatelocation(1000,500)

    def updatelocation(self, x, y):
        l = "(%d,%d)"%(x,y)
        print(l)
        self.setText(l)
        self.move(x,y)

async def test(window):
    for y in range(100,1000,50):
        for x in range(100,1900,50):
            window.updatelocation(x,y)
            await asyncio.sleep(0.1)

if __name__ == "__main__":
    app = QApplication(sys.argv)
    loop = QEventLoop(app)
    asyncio.set_event_loop(loop)
    with loop:
        window = MainWindow()
        loop.create_task(test(window))
        window.show()
        loop.run_forever()
```
[Here's](https://youtu.be/u8IXVZoXVn0) a video showing the script running under sway and i3. i3 works properly (window changes locations), while sway does not (window will always be centered).

**Comment by Xyene** [comment]
This is by design on Wayland, you can check out [this](https://gitlab.freedesktop.org/wayland/wayland/-/issues/110) thread for a relevant discussion (and links to more discussions).
