### ISSUE TITLE
How to disable palm rejection?

### ISSUE THREAD

**Issue by Moelf** [swaywm/sway#5476]
Not sure if it's a sway config or libinput?

(The use case is that I need touch pad gaming.)

**Comment by ascent12** [comment]
>sway config or libinput

[libinput doesn't have its own configuration file](https://wayland.freedesktop.org/libinput/doc/latest/configuration.html), and is handled through sway's config instead.

`input <identifier> dwt disabled` sounds like what you're looking for.
