### ISSUE TITLE
Segfault on trigger_pointer_button_binding (v1.5-rc1)

### ISSUE THREAD

**Issue by luispabon** [swaywm/sway#5481]
* Sway Version:
sway version 1.5-rc1-ba0232e (Jun 25 2020, branch 'v1.5')
wlroots a7f48aab69 (Isaac Freund, ed Jun 24 15:19:26, `xdg-decoration: free old configure structs`)
Ubuntu 20.04

* Debug:
sway log: unfortunately I wasn't running in debug mode. Doing now in the hope I can hit the crash again.

* Configuration File:
https://github.com/luispabon/sway-dotfiles/tree/master/configs/sway

* What was I doing
Just doing some stuff in firefox. Crash happened at the exact time I clicked with the mouse in some button.

* Stack Trace, if sway crashes:

coredump https://pastebin.com/m2qa7qf7
bt full https://pastebin.com/1TV4xdhk

**Comment by Xyene** [comment]
Thanks for reporting, this is a regression introduced in https://github.com/swaywm/sway/commit/8fa74add82b4975ea1fb8d1e57308bd591e6d9d0. `device` can be `NULL` [here](https://github.com/swaywm/sway/blob/ba0232e6f056fb7a6832aac21a6bd6230df9ab69/sway/input/seatop_default.c#L282-L286) for [press events sent through `swaymsg`](https://github.com/luispabon/sway-dotfiles/blob/8a119ee092d423ad39a6f3af26bc7d5e47a6998d/scripts/button.sh).

**Comment by luispabon** [comment]
Great work, thank you :ok_hand:
