### ISSUE TITLE
Add an option to move the window to exact position (atleast to the head of the queue) in the scratchpad

### ISSUE THREAD

**Issue by sauraveldho** [swaywm/sway#5496]
I use scratchpad alot... And there'll always be at least 5 windows in my scratchpad, so when I put a new window in it, I have to cycle through atleast 5 of them to get it again.
I'd like to have an option to put it at head of the queue to get it at first.

Alternative option: instead of queue, make scratchpad a stack. FILO(First In Last Out) structure.

**Comment by emersion** [comment]
Sorry, we're not implementing any new window management features unless i3 implements them too. Please consider searching for or opening an i3 feature request.
