### ISSUE TITLE
misleading systemd info regarding swayidle in the wiki

### ISSUE THREAD

**Issue by efouladi** [swaywm/sway#5504]
I opened an issue regarding writing a systemd service for swayidle here: 
https://github.com/swaywm/swayidle/issues/74

But it turns out it's not supported. However in the Wiki there is explicit instruction for writing a systemd service for swayidle:

https://github.com/swaywm/sway/wiki/Systemd-integration#swayidle

**Comment by Xyene** [comment]
The wiki is provided in a best-effort, community-maintained manner. The very first sentence from the link you posted states so:

> **Note:** these instructions are community-maintained and are not supported by sway.

You can find some more context on why this is not officially supported in https://github.com/swaywm/sway/issues/5160.

**Comment by efouladi** [comment]
Thanks a lot for the reply. I see if I can update the wiki page
