### ISSUE TITLE
[Question] one-time run in floating mode

### ISSUE THREAD

**Issue by ngortheone** [swaywm/sway#5508]
Sorry for possibly stupid question:

$mod+enter launches my $terminal app

I want $mod+shift+enter to launch the same terminal app but immediately in floating mode. Is this possible and how do it?

Reason - I often spontaneously need a short-lived terminal window and I don't want it to affect the current layout of the workspace

**Comment by Xyene** [comment]
One way would be to make change your terminal's class. alacritty and kitty both have a `--class` flag for this, so you can bindsym to e.g. `kitty --class=floating-terminal` and have a `for_window [app_id="floating-terminal"] floating enable` rule in your config.

I'm going to close this issue though; you should hop on IRC for these sorts of questions.

**Comment by ngortheone** [comment]
Thanks @Xyene that was exactly what I needed!
