### ISSUE TITLE
Sway crashes xclip operation when xwayland is stopped

### ISSUE THREAD

**Issue by ngortheone** [swaywm/sway#5512]
**Given:**
- Thinkpad T470
- FreeBSD 13 HEAD
- Sway 1.4 (installed from packages)
- Old version of https://www.passwordstore.org/ that does not support wayland yet (also from packages)

**Steps to reproduce:**
- While running sway kill -15 xwayland process
- pass show -c some/password (-c copies password to clipboard using X11 facilities)

**What happens:**
Everything freezes and screen goes black. Keyboard, mouse stops responding. (Impossible to CTL+ALT+Fx to another tty). Power button works, if pressed and held - system shuts down gracefully.

**Expected effect:**
Similar to linux without xwayland - expected error from pass something like "cannot open display" or similar 
non-zero return from xclip attempt, without crashing sway

**P.S:**
I know bug report is not full without logs, I will attach them if developers request them. I didn't attach logs for the following reasons: 
- I am not running latest sway build
- I saw some commits related to xwayland failures https://github.com/swaywm/sway/pull/5507

So it is possible that my report is obsolete.

**Comment by emersion** [comment]
Can you send SIGQUIT to Sway and see where it blocks using `coredumpctl`?

**Comment by ngortheone** [comment]
@emersion  any suggestion how can I send SIGQUIT when all input devices are not responding?

**Comment by RedSoxFan** [comment]
ssh would probably be the easiest way

**Comment by emersion** [comment]
Also please try the latest wlroots & sway commits and provide debug logs. This issue isn't really actionable otherwise.

**Comment by Xyene** [comment]
Clipboard support in wlroots has been reworked, so it's likely this issue has either been fixed, or manifests in a different way by now. Please open a new ticket with fresh logs if you find it still happens on sway/wlroots master.
