### ISSUE TITLE
Clock is slow

### ISSUE THREAD

**Issue by wgmk** [swaywm/sway#5513]
The clock displayed in swaybar by default lags behind other clocks on the system by around a second. This is visible running nested in X11 and comparing to tint2, or when using a clock in another Wayland application such as waybar.

This likely causes extra wakeups and energy usage in addition to the correctness issue.

sway version v1.5-rc2-17ff13fc (Jul  3 2020, branch 'master') on Arch Linux.

**Comment by emersion** [comment]
The default command is a naive `while` loop in sh: https://github.com/swaywm/sway/blob/c3353bb27317d294a91a8accec9a554ea392de04/config.in#L209

I don't think it's worth it to do anything more complicated.
