### ISSUE TITLE
Open multiple windows and swaymsg

### ISSUE THREAD

**Issue by yellowhat** [swaywm/sway#5518]
Hi,
I would like to open multiple windows at the same time in a grid layout.
From my understanding, in order to split a window, I need to wait for the window to be spawned.
So I have written the following script:
```
#!/bin/sh

run() {
    swaymsg "$1"
    out=$(until swaymsg -t subscribe -m "['window']" --raw | grep -m 1 "{"; do : ; done)
    con_id=$( echo $out | sed -E 's/.*"id":"?([^,"]*)"?.*/\1/')
}

run "exec kitty"
con_id1=$con_id

run "exec kitty"
con_id2=$con_id

run "[con_id=$con_id1] focus; splitv; exec kitty"

run "[con_id=$con_id2] focus; splitv; exec kitty"
```
If I run it manually (`~/.local/bin/file_manager`) from a shell it works as expected.
Instead if I bind it to a key (`bindsym $mod+e  exec "~/.local/bin/file_manager"`) only the first window is spawed.
Seems that the scripts ends on the first call to the line:
```
out=$(until swaymsg -t subscribe -m "['window']" --raw | grep -m 1 "{"; do : ; done)
```

Any ideas?

Thanks

**Comment by RedSoxFan** [comment]
Please ask questions on IRC - [#sway on irc.freenode.net](http://webchat.freenode.net/?channels=sway&uio=d4). Questions are not allowed on the issue tracker.
