### ISSUE TITLE
Command "gaps" does not take effect immediately after "swaymsg reload"

### ISSUE THREAD

**Issue by whhone** [swaywm/sway#5519]
**Repro steps**:

1. Add or update the `gaps` command in the config file (for example, adding `gaps inner 20`)
2. Run `swaymsg reload`

**Expected**: The `gaps` command should take effect.

**Actual**: It does not change the existing workspaces. Note that the new `gaps` config work on new workspaces.

**Sway version**: It happens on both `1.4` and `master` (1d149230ea1fbe7bc5ac906e235db3c1fdc63afa)

**Comment by kennylevinsen** [comment]
`gaps inner 20`, the `gaps` command that takes exactly 2 arguments, sets the default gaps for newly created workspaces. To set the *current* workspace, use the command that takes exactly 4 arguments: `gaps inner all set 20`.

Both commands and their behavior is documented in the manual (`man 5 sway`).

**Comment by whhone** [comment]
Problem solved. By design,
- `gaps inner 20` is the command used in config file. It sets the **default** value. It won't change the value of existing workspaces
- `gaps inner all set 20` is the command used with `swaymsg`. It changes the value of existing workspaces but it is **runtime only**.

Hence, to change the gaps value for all existing workspaces. Run `swaymsg gaps inner all set 20`.
