### ISSUE TITLE
Text offset in swaybar caused by CJK

### ISSUE THREAD

**Issue by Hummer12007** [swaywm/sway#552]
When displaying swaybar with some fonts (e.g. the default one, Hack etc.), sway offsets its contents down. Screenshots demonstrating behavior:
![2016-03-29-200652_swaygrab](https://cloud.githubusercontent.com/assets/4984813/14117109/c1151514-f5eb-11e5-84c7-4a239130a9f2.png)
![2016-03-29-200659_swaygrab](https://cloud.githubusercontent.com/assets/4984813/14117110/c11a3e2c-f5eb-11e5-8703-0e3c29b12119.png) 

It does not happen with some other fonts (like Unifont):
![2016-03-29-200626_swaygrab](https://cloud.githubusercontent.com/assets/4984813/14117188/3e43dd22-f5ec-11e5-8e1a-b78b7936038f.png)
![2016-03-29-200635_swaygrab](https://cloud.githubusercontent.com/assets/4984813/14117189/3e49188c-f5ec-11e5-998a-24e901d61791.png)

My config: https://sicp.me/u/m3FPW.txt

For reference, i3bar exhibits the same behavior:
![2016-03-29-191725_2880x1800_scrot](https://cloud.githubusercontent.com/assets/4984813/14117309/caeb2a1e-f5ec-11e5-908a-4eaaa8ef8cb5.png)
![2016-03-29-191732_2880x1800_scrot](https://cloud.githubusercontent.com/assets/4984813/14117310/caec56aa-f5ec-11e5-87c7-3e80330fe2c2.png)

(same i3bar config)

**Comment by mikkeloscar** [comment]
I can't seem to replicate this issue. Tried to use the Hack font you mention.
If you still see this issue, can you post some special characters that cause this issue, cause those I tried do not.
