### ISSUE TITLE
swaymsg input messes with bound keys

### ISSUE THREAD

**Issue by knezi** [swaywm/sway#5523]
When I bind a shortcut to run a shell script that changes the keyboard layout, the script is run multiple times.

(I believe it is a problem with sway, not wlroots, since it uses swaymsg).

* Sway Version: 1.4

* Debug Log: https://paste.sr.ht/~knezi/2eedd66bf6981f6633793a76be38af8b45a8e4bf

I can reproduce this issue with default config, but just to be sure, I included:

```
input * repeat_delay 10000
```

to confirm it's not me pressing it multiple times.

**Steps to reproduce:**

Put this

```
bindsym $mod+x exec /tmp/pokus
```

into config file (in the attached log, the executed script is called `/tmp/pokus`).

`/tmp/pokus` contains:

```
swaymsg input '*' xkb_layout cz
swaymsg input '*' xkb_layout us
echo a >>/tmp/key
```

I included two lines with swaymsg just to make sure the layout is really changed. Otherwise if you have set the **us** layout and include only the first line, it'll work as well. The last line is there just to confirm it is really executed twice.

Now, press `$mod+x` for at least 200ms and the script should be executed at least twice (again, the repeat_delay is set, so it's the problem of sway - I confirmed this with other scripts). The reason for holding it is (I believe) that the keys need to be pressed down after the keyboard layout is changed.

EDIT: BTW when swaymsg is used in the script above, it outputs some blank lines (even with the flag `-q`), but that's probably unrelated.

**Comment by RedSoxFan** [comment]
Fixed by #5393 and swaywm/wlroots#2229
