### ISSUE TITLE
`$mod+Shift+c` inserts `C` into text editor

### ISSUE THREAD

**Issue by tukusejssirs** [swaywm/sway#5526]
- **Sway Version:** 1.4 (stable installed from Fedora 32 `@System` repository; their version: `sway-1.4-6.fc32.src.rpm`)

- **Description:** When I open a text editor (tested on Sublime Merge 3 and Gedit) and press `$mod+Shift+C` set to `reload` the sway config, after the config is reloaded, it inserts `C` character into the currently open editor at the cursor position. No other shortcut/keybinding does that.

**Comment by RedSoxFan** [comment]
Duplicate of #4975
