### ISSUE TITLE
`swaymsg output` doesn't respect quoted display name

### ISSUE THREAD

**Issue by ohthehugemanatee** [swaywm/sway#5531]
after starting sway, the command `swaymsg output "Ancor Communications Inc ASUS VS247 E2LMTF120338" mode 1920x1080 scale 1 position 0,100 enable` returns `Error: Invalid output subcommand: Communications.`.

* Tried with single quotes for the display identifier
* Tried with zsh, bash, and sh shells in case it was a shell expansion thing.

According to the `sway-output` manpage this is the correct way to pass the identifier.

- **Sway Version:** 
  - `sway version 1.4-a8a6ed66 (May 12 2020, branch 'master')`

- **Debug Log:**
probably not that helpful but still: https://gist.github.com/ohthehugemanatee/50c79e5acd22d22fdcf6319cb44199d1
I see lots of spam from Variety wallpaper manager, but nothing related to the issue

**Comment by emersion** [comment]
Yeah that's an annoying thing. I wish we could just use argv, but Sway/i3 performs splitting again when `swaymsg` is called. So you'd need to do this instead:

```
swaymsg 'output "Ancor Communications Inc ASUS VS247 E2LMTF120338" mode 1920x1080 scale 1 position 0,100 enable'
```

**Comment by ohthehugemanatee** [comment]
thanks for the fast response! Unfortunately that still doesn't work:
```
» swaymsg 'output "Ancor Communications Inc ASUS VS247 E2LMTF120338" mode 1920x1080 scale 1 position 0,100 enable'
Error: Missing position argument (y).
```

Happy to submit a docs PR when we sort this out. :)

**Comment by RedSoxFan** [comment]
You'll need to wrap the `0,100` in quotes as well since commas are used as command separators. Replacing that comma with a space is also supported.

**Comment by ohthehugemanatee** [comment]
Thank you for your help! Linked a PR adding a note about this to the swaymsg manpage.

**Comment by emersion** [comment]
Thanks. Closing because this isn't a bug.
