### ISSUE TITLE
Sway leaks file descriptors, probably through XWayland

### ISSUE THREAD

**Issue by gergelypolonkai** [swaywm/sway#5532]
- **Sway Version:** 1.4 (from the Fedora 32 repositories)

- **Debug Log:** https://gist.github.com/gergelypolonkai/e41fe0d5fc665c066633945476931524 (i ran the log through `uniq -c` to condense 405916 lines of output to 149)

- **Configuration File:** My config is [here](https://gitea.polonkai.eu/gergely/dotfiles/raw/branch/main/.config/sway/config), but it happens with the Fedora default config, too.

- **Description:** Just run Sway and use some X11 apps. This happens after 30-120 minutes, depending on how many X apps you run.

May or may not be related to #4286 (i’d vote “related”)

There is also a downstream [Fedora bug](https://bugzilla.redhat.com/show_bug.cgi?id=1854066) for the issue.

**Comment by emersion** [comment]
Can you run `ls -l /proc/(pgrep -x sway)/fd`?

**Comment by gergelypolonkai** [comment]
- [FD list right after startup](https://github.com/swaywm/sway/files/4902528/sway-fds-after-startup.txt) (no X11 apps running, just termite which is Wayland
- [FD list right after starting a bunch of X11 apps](https://github.com/swaywm/sway/files/4902533/sway-fds-after-xapps.txt) (Emacs, XEyes, and two electron apps; firefox is also running at this time, but on Wayland, termite is also still running)
- [FD list after closing all X11 apps](https://github.com/swaywm/sway/files/4902537/sway-fds-after-xapps-closed.txt) (Firefox and termite is still running)

**Comment by gergelypolonkai** [comment]
After cca. 10 minutes of work (only Emacs (X11), Termite, and Firefox being open):

[sway-fds-after-after-some-work.txt](https://github.com/swaywm/sway/files/4902607/sway-fds-after-after-some-work.txt)

**Comment by emersion** [comment]
The first three logs seem normal. The last one contains a lot of pipes, which may indicate stalled clipboard data transfers.

Are you using a clipboard manager? May be related: https://github.com/swaywm/wlroots/issues/2192

**Comment by gergelypolonkai** [comment]
I am using clipman an wl-clipboard. I go and test it without running that.

**Comment by gergelypolonkai** [comment]
Getting rid of wl-paste made me abltoework for an hour, uninterrupted, and without the fd count going up too much. It seems the culprit is indeed wlroots and/or wl-clipboard/clipman.

**Comment by emersion** [comment]
Opened a follow-up issue: https://github.com/swaywm/wlroots/issues/2326
