### ISSUE TITLE
Feature proposition: “smart title bars”

### ISSUE THREAD

**Issue by choreutes** [swaywm/sway#5534]
**Description:**
I propose to introduce an option `smart_title_bars` (or similar). If enabled, a window's title bar would only be rendered if there are no other windows on the currently displayed workspace, analogous to `smart_borders` and `smart_gaps`.

**Usecase:**
I currently use sway together with a waybar in which the window title of the focussed window is displayed. This renders the title bar redundant if there is only one window on the active workspace and some extra screen real estate could be freed by hiding it. For two or more windows, however, I think it might be useful to show the window titles right next to the respective windows.

I found some loosely related issues here (e.g. #1286) but none of them quite fit the functionality I have in mind. So I wanted to put this up here for discussion. Please excuse me if I missed an issue where this was already discussed. I also understand that my usecase might be quite specific but maybe someone else finds it useful as well. If you think that I should propose this to i3 first then I can of course do that, too.

Do you think this would be doable/desirable? Thanks for reading and considering, anyway! Sway is an awesome piece of software and I really enjoy using it!

**Comment by emersion** [comment]
Sorry, we're not implementing any new window management features unless i3 implements them too. Please consider searching for or opening an i3 feature request.
