### ISSUE TITLE
Wallpaper background borked

### ISSUE THREAD

**Issue by shoober420** [swaywm/sway#5538]
- **Sway Version:**
  - sway version v1.5-rc2-5432f00a (Jul 11 2020, branch 'master')

- **Debug Log:**
  - [sway.log](https://github.com/swaywm/sway/files/4907640/sway.log)

- **Configuration File:**
  - https://gist.github.com/shoober420/59a2713bb09487a935a45ef4341a9d46

- **Description:**
  - Recent commits have broke swaybg from loading the wallpaper

**Comment by emersion** [comment]
Your bug report is missing debug logs. Please add a link to the full debug log file.

**Comment by emersion** [comment]
Err, I see it's up now. My bad,

**Comment by emersion** [comment]
Hmm, nothing useful in the debug log it seems. It appears that swaybg is spawned correctly and creates a layer-shell surface.

**Comment by shoober420** [comment]
Well my background is now grey instead of the jpg chosen.

**Comment by RedSoxFan** [comment]
Are you experiencing issues with anything other than swaybg on the output?

Can you please do the following:
1. Comment out the `output * bg ~/Downloads/wallpaper.jpg fill` line in your config
2. Start sway
3. Run the following from a terminal:
```sh
env WAYLAND_DEBUG=1 swaybg -o "*" -i ~/Downloads/wallpaper.jpg -m fill 2> swaybg.log
```
4. After a couple seconds, use Control+C to terminate swaybg.
5. Post the log

**Comment by shoober420** [comment]
I'm going to play around with the "max_render_time" setting and see if it works properly. Here's the log.

[swaybg.log](https://github.com/swaywm/sway/files/4910439/swaybg.log)

**Comment by emersion** [comment]
It seems like Sway never sends a configure event for the layer surface.

**Comment by shoober420** [comment]
@emersion 
Awesome, I’m glad that log caught something.

**Comment by alebastr** [comment]
I've just seen this in my test VM, and I believe I know what's going on.
I have sway 1.5rc2 built against https://github.com/swaywm/wlroots/commit/a54ed8588177a679a131c621c0d300c6a9d910c5, but the installed wlroots package was at https://github.com/swaywm/wlroots/commit/842df2bd6c940c5f4933622987fc9a296f404d67. Rebuilding sway against updated wlroots fixed the issue so I suspect ABI changes in 'layer-shell: remove unused surface list'.

@shoober420 is there any chance that you've updated wlroots without rebuilding sway? Does rebuilding sway fix the issue?

**Comment by shoober420** [comment]
I keep sway, wlroots, and swaybg up to date consistently. I just compiled sway and wlroots right now, and the bug is still present.

**Comment by shoober420** [comment]
Fixed, thank you very much.
