### ISSUE TITLE
obs-studio output laggy if its opened on a different workspace

### ISSUE THREAD

**Issue by phaitonican** [swaywm/sway#5540]
obs-studio output is very laggy if its opened on a different workspace (or in another tab/stack in the same workspace) than the one being recorded. If **its minimized to the tray** or OBS is visible in that workspace everything works fine.

- **Sway Version:**
  - 1.4

- **Debug Log:**
  - OBS not minimized to tray (laggy output):
  - https://pastebin.com/hLCjPHNJ

  - OBS minimized (smooth output):
  - https://pastebin.com/45ns1ft0

- **Configuration File:**
  - https://pastebin.com/WDgHMJuG (Default config beginning from Line 24)

- **Description:**
  - Open OBS and start recording with XComposite/Other (minimize to tray or not)
  - switch workspace to window selected by XComposite and for example type something in that window

**Comment by emersion** [comment]
Your bug report is missing debug logs. Please add a link to the full debug log file.

**Comment by phaitonican** [comment]
Sorry done.

**Comment by phaitonican** [comment]
This seems also to happen with Blender for example, when its opened in another workspace, the other window seems to get very choppy sometimes, so I think maybe this is a xserver issue?
