### ISSUE TITLE
kill doesn't have the semantics of Kill

### ISSUE THREAD

**Issue by appetrosyan** [swaywm/sway#5542]
- **Sway Version:**
  sway version 1.4

- **Configuration File:**
Irrelevant. 

- **Description:**
In sway kill doesn't really kill, but rather closes the application. This is rather confusing, as sway really doesn't have a kill (i.e. `pkill` with `SIGINT` on the owning process of the focused window, but rather politely asks to close it. 

**Steps to reproduce**:
Try to kill a window that hangs. 

**expected behaviour**
the process is killed and the window is closed. 

**actual behaviour**
No-op.

**Comment by emersion** [comment]
This is consistent with i3 behaviour, ie. by design,

By the way, SIGINT also politely asks a process to exit.
