### ISSUE TITLE
Xwayland applications are blurred when scaling is used

### ISSUE THREAD

**Issue by Sirina32** [swaywm/sway#5548]
### Please fill out the following:
- **Sway Version:** 1.4

- **System infos:**

Driver: AMDGPU
Resolution: 3840 × 2160

- **Configuration File:**

Default config with a single change:
output DP-1 scale 2

- **Description:**
When running X11 applications on sway when scaling is used, the image is blurry. This is especially obvious with fonts.
It looks somewhat like it does not use the full resolution (4k in my case) but rather HD resolution
If no scaling is used this does not happen.
If native wayland applications are used this is never an issue.

- **Reproduction:**
  - Running sway with a scaling of 2 (with 4K resolution)
  - starting a X11 application, such as e.g. vscode (or other electron applications)
  - the fonts are blurry/unsharp

**Comment by emersion** [comment]
See https://github.com/swaywm/wlroots/pull/2064

**Comment by someniatko** [comment]
UPD: now it's https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/2064

**Comment by glyh** [comment]
If the MR is not accepted, why should this issue be closed?

**Comment by emersion** [comment]
Because it's not a Sway issue.

**Comment by someniatko** [comment]
@emersion KDE is about to add a workaround for it: https://www.phoronix.com/news/Plasma-5.26-Crisper-XWayland

Could swayvm adopt something like this? It could be an opt-in setting.

**Comment by emersion** [comment]
Nope, the workaround would be too much maintenance cost.
