### ISSUE TITLE
Sway doesn't hide titlebar for single window in tabbed container

### ISSUE THREAD

**Issue by rob-3** [swaywm/sway#5551]
On i3, when using `default_border none` and `workspace_layout tabbed`, a single window does not have a titlebar. When another window is opened (creating a second tab), then both windows get a titlebar. Later, if the number of windows goes back to just 1, the titlebar will disappear again. Sway always displays the titlebar, even if there is only 1 window.

**Comment by Xyene** [comment]
Agreed that this is a place where sway does not (by default) match i3 behavior. Functionality for behaving like i3 was added in https://github.com/swaywm/sway/pull/3767, but it was placed behind a flag (see the discussion in the link), so for getting i3 behavior you'd have to do something like:

```
hide_edge_borders --i3 smart
```

**Comment by rob-3** [comment]
Thanks; this is what I was looking for!

**Comment by CodeJoule** [comment]
Aw, man. Was hoping this would be i3-compatible. I spent an hour trying to figure out why this wasn't working. --i3 is fine though. Is there any reason for this decision?
