### ISSUE TITLE
input-method extension is insecure

### ISSUE THREAD

**Issue by ya-isakov** [swaywm/sway#5555]
Hello! I think that introduce of input-method and/or text-input extensions introduce security breaches in Wayland. From extension description and examples from wlroots, it looks like any app could behave like input method, and get all input from IM-enabled apps. So, please, allow to no enable these extensions, or add a list of applications, which could be safely used as IM methods.

**Comment by emersion** [comment]
Duplicate of https://github.com/swaywm/sway/issues/2333

**Comment by ya-isakov** [comment]
I'm rasing these issues, as there is no progress on #2333. Please, at least allow to not compile these features into Sway.

**Comment by emersion** [comment]
Sorry, this is a project run by volunteers. If you want a change, you can't expect other people to write the patch for you. Thanks.

We accept patches. We've discussed a build option in the past: https://github.com/swaywm/sway/issues/5118#issuecomment-600056715

It would be very nice to have patches to properly fix #2333 as well.
