### ISSUE TITLE
waybar popups are hidden behind other surfaces when using the bottom layer.

### ISSUE THREAD

**Issue by tmccombs** [swaywm/sway#5558]
**Sway Version:** 1.4

**Description:**
  - Run [waybar](https://github.com/Alexays/Waybar) in sway with the "layer" option set to "bottom"
  - Hover over a module with a tooltip when no other applications are open, notice that the tooltip is displayed.
  - Open an application tiled (or floating) so that it would overlap with where the above tooltip would be
  - Hover over the module again, notice that the tooltip is not visible

A similar effect can be seen when opening a menu from the systray.

It looks like this is using xdg-popup to render the tooltip and menu. I suspect what's happening here is since the parent surface is in the "bottom" layer, it's rendering the tooltips and menu at the bottom layer as well, instead of rendering them over other surfaces.

**Comment by progandy** [comment]
Fixed in sway 1.5 with #4781

**Comment by tmccombs** [comment]
Confirmed that this is fixed in 1.5
