### ISSUE TITLE
force_display_urgency_hint is undocumented

### ISSUE THREAD

**Issue by JayceFayne** [swaywm/sway#5573]
The `force_display_urgency_hint` command is not documented in [sway(5)](https://github.com/swaywm/sway/blob/master/sway/sway.5.scd).

**Comment by emersion** [comment]
Some commands are undocumented because they are unstable. Is this implemented and documented in i3?

**Comment by JayceFayne** [comment]
Yes, it is implemented and documented [in i3](https://github.com/i3/i3/commit/28104a480ca9a2ab135488ab98545d67e81a9f9d). I also found [this](https://github.com/swaywm/sway/issues/2336) issue regarding commands that should be implemented in sway.
