### ISSUE TITLE
Sway stops with a segfault

### ISSUE THREAD

**Issue by duck-rh** [swaywm/sway#5577]
### Please fill out the following:
- **Sway Version:** 1.5

This may have happened before but I did not notice. I installed systemd-coredump to debug  #5576 and see if there was a coredump, and then noticed that stopping normally caused one.

- **Debug Log:**
[sway__exit.log](https://github.com/swaywm/sway/files/4977800/sway__exit.log)

- **Configuration File:**

[sway.config.txt](https://github.com/swaywm/sway/files/4977812/sway.config.txt)
[Annael.config.txt](https://github.com/swaywm/sway/files/4977813/Annael.config.txt)

- **Stack Trace:**
[sway__exit__trace.log](https://github.com/swaywm/sway/files/4977803/sway__exit__trace.log)

- **Description:**
I open my session, let all the exec-ed apps start, then use the keyboard shortcut to ask Sway to stop and click to confirm.

**Comment by emersion** [comment]
Can you try re-compiling with the address sanitizer (ASan) and reproducing the crash?

You can compile with ASan by passing `-Db_sanitize=address` to Meson.

**Comment by duck-rh** [comment]
After recompiling with ASan there is no segfault anymore; here is the log:
[sway_asan.log](https://github.com/swaywm/sway/files/4987572/sway_asan.log)

**Comment by duck-rh** [comment]
Since my problem related to #5576 is solved I checked if there was coredumps again and there is none.
