### ISSUE TITLE
Swaybar crashes if only one workspace is open and you scroll on it 4 times

### ISSUE THREAD

**Issue by ianyfan** [swaywm/sway#5580]
Version: latest master

Steps to reproduce:
- have swaybar open with only one workspace open (obviously with workspace buttons enabled)
- scroll on swaybar 4 times in the same direction
- crash with debug line: `[swaybar/input.c:193] workspace_next:axis with null workspace`

The crash occurs because `new` is the same as `active` but the function changes `new->visible` to `true` before changing `active->visible` to `false`, causing it to be confused upon the next call.

Seems like an an easy fix to check that they are not the same, but I'm not sure why the assert fails only on the fourth scroll and not the second. There may be another subtle bug somewhere that causes the assert to not work properly on the second scroll that requires investigation.

**Comment by Geo25rey** [comment]
I can't reproduce the issue. No log messages either.

**Comment by ThreeFx** [comment]
Can reproduce neither on master nor 1.5.
