### ISSUE TITLE
Support for checkpoint/resume (CRIU) of wayland apps?

### ISSUE THREAD

**Issue by jamadazi** [swaywm/sway#5587]
It would be amazing if sway were to consider natively supporting checkpointing and resuming GUI applications.

AFAIK, such functionality was never before supported by any desktop environment, because it is difficult to do under an X server. But now with Wayland, it is no longer necessary to rely on an external component we cannot control (the X server) and the compositor (which is entirely under our control) could implement whatever magic is necessary.

I am not familiar with the technical details of what this would entail (how to handle GPU rendering? the wayland protocols?), but this is why I am creating this issue to start a discussion.

I know that this is uncharted territory, but if other people are interested, this could make sway a truly unique desktop experience.

I read somewhere that there was an attempt to do this in Weston before, but it was never finished.

This would allow for so many interesting use cases, like session management (snapshotting specific running applications and restoring them after a reboot, or just at a later point), or save-states for games. It would effectively obsolete OS-level hibernation for me.

**Comment by Geo25rey** [comment]
This might be something better suited to discuss in wlroots (the library sway is built from). But here's my 2 cents.

You're idea would probably be better as a stand alone compositor since compositors can run within compositors. Also, Sway is a window manager, not a desktop environment. So, that kind of feature wouldn't really correspond to a project like this. I suggest making a fork of cage (a basic window manager built with wlroots) and try to build your feature off of that.

**Comment by jamadazi** [comment]
> This might be something better suited to discuss in wlroots (the library sway is built from).

OK, I agree. This does not seem specific to the i3-like experience that sway implements, but rather the underlying architecture. I will go create an issue at the wlroots repo to continue the discussion.

> Also, Sway is a window manager, not a desktop environment. So, that kind of feature wouldn't really correspond to a project like this.

I disagree that this would be a feature for a "desktop environment"; it feels very much in the scope of the user experience that sway (and similar window managers) aim to provide. It is functionality for managing your open windows/apps, much like launching and closing, or taking screenshots. Sway already provides such things. Even i3 provides session save/restore functionality, and one could view this proposal as being an enhanced version of that experience (which actually preserves the state of applications rather than just reopening them).
