### ISSUE TITLE
Optionally move mouse cursor when creating new terminal/window

### ISSUE THREAD

**Issue by sriedel** [swaywm/sway#5588]
- **Description:**
Enhancement: When creating a new window or terminal, allow the mouse cursor to optionally be automatically placed within the boundaries of the new window.

Motivation: Using the newer behaviour of having a newly created window focused automatically, along with focus-follows-mouse, the mouse cursor can currently remain within the boundaries of the previously focused window. As soon as the mouse cursor is moved, focus switches from the new window back to the old window. On keyboards with a trackpoint as a pointer device this can cause unexpected focus switches while typing, if the user is fat-fingering the trackpoint a bit by mistake or the trackpoint is twitchy or not well calibrated.

I'm frequently having the unexpected focus switch happening, leading to half a shell command being typed into the old window, usually with me noticing too late.

**Comment by emersion** [comment]
The disable-while-typing and focus_follows_mouse settings should already provide you everything you need.

**Comment by progandy** [comment]
There is a global option called

    mouse_warping container
