### ISSUE TITLE
Color #000 crashes sway

### ISSUE THREAD

**Issue by PaperMountainStudio** [swaywm/sway#5590]
- **Sway Version:**
  - `v1.5`

- **Debug Log:**
  - https://gist.github.com/PaperMountainStudio/618b9660d0e5ac2cd189cd9e6f7fb018

- **Configuration File:**
  - https://gist.github.com/PaperMountainStudio/a3877c44440fc8945f8a1783bf56a3a3
  - the only change from the default config is replacing line 212 with `background #000` instead of `background #323232`

- **Description:**
  - Using the default config, only with one change - replacing line 212 with `background #000` instead of `background #323232` crashes sway.
  - replacing any other color with 3 number format crashes sway too

**Comment by emersion** [comment]
Please provide a stack trace. You can do so by compiling from source, reproducing the crash and then running `coredumpctl gdb` and then `bt full`.

Here are some instructions to compile from source: https://github.com/swaywm/sway/wiki/Development-Setup#compiling-as-a-subproject

**Comment by PaperMountainStudio** [comment]
I  compiled it from source and found out it is fixed on master, sorry for wasting your time.
