### ISSUE TITLE
swaybar/swaynag: no subpixel text antialiasing

### ISSUE THREAD

**Issue by Fenveireth** [swaywm/sway#5605]
Using Sway 1.5, on Gentoo and Arch linux

```
output DP-1 {
  subpixel rgb
}
font pango:monospace 10
bar {
  status-command ~/mystatus.sh
}
```

At this point, subpixel blending will be used by sway for window titles/decoration, but not by swaybar to draw text. Swaybar keeps using grayscale AA, even though subpixel seems to be what's wanted by render code in both cases

Testing shows that Cairo will bail out of subpixel AA if the cairo_operator is set to SOURCE. Changing swaybar to use the default OVER "fixes" it, and results in use of subpixel blending for text

Is it Cairo that could be wrong ? Changing to OVER "feels right" because AA will require blending anyway, yet the manual lets one feel that active operator and anti-aliasing modes shouldn't interfere with each other (internal requirements of AA not caller's problem)

**Comment by emersion** [comment]
Can you open an issue on the Cairo bug tracker?

**Comment by Fenveireth** [comment]
I wanted to, but after preparing the repro, and especially after reading the history of this same problem for i3 (https://github.com/i3/i3/pull/3947. I should have started there, duh), I now think what cairo's doing is not unreasonable, and that a corresponding fix would end up not being used :

- the triple-rate blending for 'source' is only skipped for targets that write an alpha channel (need the grayscale glyphs for that)
- the invoked use case for i3's use of 'source' is to draw an opaque bar, then carve the text back through it with a font color alpha=0. In this case (and in fact any other relying on the compositor to materialize the text from the alpha), subpixel antialiasing musn't be used in the first place
- with 'source', it is not possible to draw a completely opaque bar if it contains color emoji

So there wouldn't be a middle ground between disallowing subpixel AA and changing the operator ?

**Comment by emersion** [comment]
Hmm, I don't understand a lot of this. Feel free to open a PR if it fixes a bug, please write an explanation in the commit message :P
