### ISSUE TITLE
Super slow

### ISSUE THREAD

**Issue by Herjanz** [swaywm/sway#5610]
Sway version: 1.4 and 1.5

- **Debug Log:**
https://pastebin.com/KLePQdEP
error at the end:
00:00:00.136 [common/ipc-client.c:88] Unable to receive IPC response

- **Configuration File:**
default

- **Stack Trace:**
It doesn't crash

- **Description:**
Worked with Intel Graphics 530. Issue came after installing a GTX 1650 video card with nouveau drivers.

Sway is super super slow, it takes around 5 seconds to start terminal alacritty (or whatever program)
Typing is no use, after a delay of ~5 seconds characters get typed like this:
llllllllllllllllllls
pkillllllll swayyyyyyyyy
Backspacing/enters do the same, repeating for like 10 times. If I type really fast only the last character is multiplied
Mouse also takes 10 seconds before it starts moving really slow and weird

**Comment by emersion** [comment]
Your bug report is missing debug logs. Please add a link to the full debug log file.

From a tty:

```
sway -d >sway.log 2>&1
```

**Comment by Herjanz** [comment]
@emersion added

**Comment by Emantor** [comment]
```
00:00:00.063 [INFO] [render/gles2/renderer.c:694] GL vendor: VMware, Inc.
00:00:00.063 [INFO] [render/gles2/renderer.c:695] GL renderer: llvmpipe (LLVM 10.0.1, 256 bits)
```
`llvmpipe` means software rendering, which kernel version are you running? Apparently [5.7](https://www.phoronix.com/scan.php?page=news_item&px=Nouveau-GTX-16-Support) is required for 3D acceleration, but I might be wrong in my research.

**Comment by Herjanz** [comment]
Newest 5.7.12, just the normal linux kernel

**Comment by emersion** [comment]
Nouveau doesn't support rendering acceleration for NV160.

**Comment by Herjanz** [comment]
Alright, sorry for wasting your time. Can you guys point me in a direction to fix this?

**Comment by emersion** [comment]
I believe the kernel bits are merged, and this MR adds Mesa support: https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/5377 (merged but not yet released)

You can try out the MR, and report any bugs. You can ask for help in #nouveau on Freenode.

**Comment by Herjanz** [comment]
Thanks @emersion , I have got sway working fine now with the git version of mesa. Only problem is that I have a whole lot of new problems but that has nothing to do with sway. So thanks for the great support!
