### ISSUE TITLE
Upscale game resolution to native desktop resolution

### ISSUE THREAD

**Issue by shoober420** [swaywm/sway#5612]
- **Description:**

When trying to run a game at a lower resolution than desktop native, the game renders at the bottom left or windowed in the middle of the screen. When changing resolutions in Xorg with i3 or any other window manager, the game will upscale the desired game resolution to the native desktop resolution. This is also important for gaming LCDs if you play a game at a resolution that isn’t the native desktop resolution. (CSGO - 1024x768@240Hz) (tyrquake software mode - 640x480@240Hz)

**Comment by emersion** [comment]
Should work with Xwayland master.

**Comment by shoober420** [comment]
I don’t use Xwayland, I intentionally run a pure Wayland system, and don’t want games to run through Xwayland. This is why I suggested that Sway have the ability to upscale resolution. Can it be considered?

**Comment by emersion** [comment]
Ah, but CSGO is X11, not native Wayland.

You can change your resolution in Sway.

Or did you have something like https://gitlab.freedesktop.org/wayland/weston/-/merge_requests/394 in mind? I think there was a wlroots/Sway issue about this, but I can't find it again.

**Comment by shoober420** [comment]
@emersion 

I’m moreso thinking in future terms. Hopefully Valve will port Steam to GTK3/4 for native Wayland support, instead of being stuck on GTK2.

This is for the fact that gaming LCDs seem to only present the 240Hz option at their native resolution.

So for tyrquake in software mode, the particles are huuuge squares because of how they were programmed in assembly. It might be changed if I ask the source port author, but this leads me to scenario two.

My current hardware is pretty poopy (Radeon HD 6310) and struggles at playing even yamagi quake2 at 1920x1080. So playing this game, and a lot of 90s games at lower resolutions would be desirable, even recommended. Tyrquake in software mode was never intended to be played at HD resolutions for example.

Thankfully, source ports like chocolate doom and devilutionx automatically upscale to your desktop resolution for you. But for games that don’t, it would be nice for the fore mentioned reasons above.

The main reason here, being LCDs only support 240Hz at the native resolution, so if a user wanted to play a game at a lower resolution for whatever reason, he would not get the eye candy of 240Hz and be stuck at 60Hz or 75Hz on non-native resolutions.
