### ISSUE TITLE
Reference outputs by device serial

### ISSUE THREAD

**Issue by haraldschioberg** [swaywm/sway#5616]
### Please fill out the following:
- **Description:**
External monitors tend to be inconsistently enumerated. I am using the following script to "sort out" my external screens. It'd be great if sway would allow to specify the device serial directly.

proposed syntax: `output serial=67YGV97DBT3U pos 0 0 res 2560x1440`

My current workaround script: 
```
#!/bin/bash

DP_LEFT="$(swaymsg -t get_outputs --raw | \
  jq -r '.[] | select(.serial == "67YGV97DBT3U") | .name')"
DP_RIGHT="$(swaymsg -t get_outputs --raw | \
  jq -r '.[] | select(.serial == "67YGV97DC4QU") | .name')"

if [ -n "$DP_LEFT" ]; then
  swaymsg "output $DP_LEFT  pos 0 0 res 2560x1440" 
  swaymsg "output $DP_LEFT enable"
fi

if [ -n "$DP_RIGHT" ]; then
  swaymsg "output $DP_RIGHT pos 2560 0 res 2560x1440" 
  swaymsg "output $DP_RIGHT enable"
fi
```

**Comment by Emantor** [comment]
Sway already supports specifying outputs by make model and serial, please look into `man 5 sway-output`.
