### ISSUE TITLE
Layer shell subsurfaces flicker

### ISSUE THREAD

**Issue by wmww** [swaywm/sway#5617]
Subsurfaces on Layer Shell surfaces flicker (tested on master at time of submitting). It appears to be a damage issue, as switching windows underneath the layer shell surface stops the flickering. First spotted on gtk-layer-shell (https://github.com/wmww/gtk-layer-shell/issues/47) and reproduced in a minimal EGL client (https://github.com/wmww/hello-wayland/blob/master/layer-shell-subsurface.c)

EDIT: I'm submitting to wlroots as I suspect that's were the bug is, but I haven't tried testing in anything other than Sway.

**Comment by emersion** [comment]
Created https://github.com/swaywm/sway/issues/5867 for subsurfaces of popups and other subsurfaces.
