### ISSUE TITLE
key bindings with Mod4+Mod1 won't work correctly sometimes

### ISSUE THREAD

**Issue by Eitetsu0** [swaywm/sway#5618]
I have a line in config file like :
`bindsym Mod4+Mod1+Print exec xxx`

But it will only trigger when Mod1(alt) is released before Mod4(Win).

**Comment by Geo25rey** [comment]
Potentially a bug with libinput?

**Comment by Eitetsu0** [comment]
> Potentially a bug with libinput?
Yea , thank  you ,it seems so.

`libinput debug-events --show-keycodes` got below :
    release meta first:
```
 event2   KEYBOARD_KEY     +54.061s	KEY_ENTER (28) released
 event2   KEYBOARD_KEY     +62.909s	KEY_LEFTMETA (125) pressed
 event2   KEYBOARD_KEY     +63.169s	KEY_LEFTALT (56) pressed
////////// PrtSc pressed here 
 event2   KEYBOARD_KEY     +66.548s	KEY_LEFTMETA (125) released
 event2   KEYBOARD_KEY     +66.654s	KEY_LEFTALT (56) released
 event2   KEYBOARD_KEY     +66.654s	KEY_LEFTALT (56) pressed
 event2   KEYBOARD_KEY     +66.654s	KEY_SYSRQ (99) pressed
 event2   KEYBOARD_KEY     +66.654s	KEY_SYSRQ (99) released
 event2   KEYBOARD_KEY     +66.654s	KEY_LEFTALT (56) released
 event2   KEYBOARD_KEY     +72.679s	KEY_ENTER (28) pressed
```
   release alt first:
```
 event2   KEYBOARD_KEY     +72.830s	KEY_ENTER (28) released
 event2   KEYBOARD_KEY     +83.550s	KEY_LEFTMETA (125) pressed
 event2   KEYBOARD_KEY     +83.714s	KEY_LEFTALT (56) pressed
////////// PrtSc pressed here 
 event2   KEYBOARD_KEY     +85.399s	KEY_LEFTALT (56) released
 event2   KEYBOARD_KEY     +85.399s	KEY_LEFTALT (56) pressed
 event2   KEYBOARD_KEY     +85.399s	KEY_SYSRQ (99) pressed
 event2   KEYBOARD_KEY     +85.399s	KEY_SYSRQ (99) released
 event2   KEYBOARD_KEY     +85.399s	KEY_LEFTALT (56) released
 event2   KEYBOARD_KEY     +85.576s	KEY_LEFTMETA (125) released
```

Thats so weird 😂

**Comment by Emantor** [comment]
`Alt`+`PrtSc` is the combination used by the kernel for the [magic  sysrq](https://en.wikipedia.org/wiki/Magic_SysRq_key) sequence, so any combination of `Alt`+`PrtSc` will never reach userspace, since the kernel interprets this as a start of the binding.

**Comment by Eitetsu0** [comment]
I get it. Nothing will be sent to sway until `Alt` is released.
The 2nd way (release alt 1st) works because maybe libinput (or kernel?) automatically regenerate a `Alt`-press-release event since I didn't actually trigger a `alt-sysrq` shortcut.
I guess there is nothing sway can do with this problem.😂
Thank you for your replies !
