### ISSUE TITLE
Surface local touchpoint coordinates 

### ISSUE THREAD

**Issue by NDagestad** [swaywm/sway#5630]
- **Sway Version:**
sway version v1.5

- **Configuration File:**
independant of configuration 

- **Description:**
When sway handle touch.motion events, it sends the surface local coordinate of whatever is under the touchpoint to the programme that started the motion.
This is neither the case in phoc (wlroots based) nor weston. They both send coordinate relative to the surface's origin (making them negative if you are above or to the left of your surface). This behaviour seems more useful than sway's where you get coordinates relative somebody else's surface. 
The wayland protocols call for "surface-local" coordinates and both behaviour would fit that description in my opinion, but in the case of sway's behaviour, this makes it impossible to know if a touchpoint has left your surface or not.

I am no wayland expert though, was this behaviour a deliberate choice ?

**Comment by emersion** [comment]
I don't understand. The expected behaviour is: once the user touches down a surface, touch motion events are sent to this surface. Can you explain in what way Sway's behaviour differs?

**Comment by NDagestad** [comment]
Yes, the problem appears when the motion continues out of the boundaries of the surface.
In sway the coordinates will be local to the new surface under your touchpoint, in weston and phoc the coordinated are still relative to the surface you first touched down on. (being negative if you are to the left or above it and > height or width if you are to the right or under it)

**Comment by emersion** [comment]
Indeed, that's a bug, thanks for explaining.
