### ISSUE TITLE
Sway is not allowing "none" as a modifier for "floating_modifier" 

### ISSUE THREAD

**Issue by vatonbero** [swaywm/sway#5635]
### Please fill out the following:
- **Sway Version:**
  - `sway version 1.4` (regular from Fedora repos, haven't seen this reported in any of the versions)

- **Debug Log:**
  - http://ix.io/2uH5
- **Configuration File:**
  - Done it with default config but i have added `floating_modifier none` at the bottom. Here is the config: http://ix.io/2uH6

- **Description:**
  - Set `floating_modifier none` in config
  - Reload sway. 

Swaynag will show that "none" is not recognized modifier for `floating_modifier`

Again, this version of sway is in the fedora repos so i cannot really comment on the latest one.

**Comment by RPigott** [comment]
This feature was added in #4930 and first released with 1.5.

I'm curious why you thought it would work? Does the shipped sway(5) man-page also document "none" as a valid modifier value?

Either way there's nothing to do here. Update to 1.5 if you want this feature.
