### ISSUE TITLE
Implement foreign toplevel fullscreen output hints

### ISSUE THREAD

**Issue by RPigott** [swaywm/sway#5637]
This was intentionally left out of #5589. Creating this issue so I don't neglect it.

**Comment by fwSmit** [comment]
Is there any reason why it's not implemented yet? Otherwise I would like to (try to) implement it.

**Comment by emersion** [comment]
Feel free to send a PR. Ask questions on the #sway-devel IRC channel if you have any.

**Comment by RPigott** [comment]
No reason. Please do!
