### ISSUE TITLE
Cursor position is wonky with multiple outputs in Wayland backend

### ISSUE THREAD

**Issue by RPigott** [swaywm/sway#5638]
```
$ swaymsg -pt get_version
sway version 1.5-6991ac8c (Aug 18 2020, branch 'master')
$ swaymsg -s $SWAYEMBED -pt get_version
sway version 1.5-6991ac8c (Aug 22 2020, branch 'master')
```

When starting an embedded sway session with `WLR_WL_OUTPUTS=$n` where n > 1, I observe the the cursor position in those outputs doesn't match the drawn cursor. Specifically in an interactive move the y position matches, but the x position is n*x with respect to the offset from 0,0 in the top left.

i.e.
```
$ WLR_WL_OUTPUTS=2 sway
$ swaymsg -s SWAYEMBED exec '$term', floating enable, move abosolute position 0 0
```

Now begin an interactive move using the floating modifier. Observe:

1. moving the cursor to 0,100 moves the client to 0,100
2. moving the cursor to 100,0 moves the client to 200,0.

For clarity, I'm starting sway from a terminal in the parent session that is the only client in a horizontal layout workspace. So I got from H[termite] to H[termite WL-0 WL-1], with each output taking a third of my screen. But even when I move those outputs to their own workspaces the linear offset remains.

Regardless of the geometry of the Wayland output windows in the parent session, using the `swaymsg move` commands moves clients to the intended position. e.g. `swaymsg -s $SWAYEMBED move absolute position 100 0` moves a client to a 100 pixel offset. The position is reported as 100,0 from get_tree and the real distance moved by the client is also 100 pixels, matched by moving the cursor in the parent session 100 pixels over with the ipc.

If I once again place my terminal at 0,0 and invoke slurp with the client geometry from the get_tree response, the client area is highlighted correctly by slurp in the drawn overlay, but only when my cursor is in the left half of the rectangle. I must also click in the left half of the rectangle for slurp to consider the area selected.

**Comment by ony** [comment]
Worth to note that it doesn't manifest for Cage that do extend over all connected outputs.

I think this might be related to how cursor teleports to other output in Sway and how wlroots represent cursor in wayland/x11 back-ends. In particular we have pointer per output. When host pointer leaves one output and [enter another, Wayland back-end switches virtual pointers for it](https://github.com/swaywm/wlroots/blob/master/backend/wayland/seat.c#L53-L54).

I believe, to solve this problem we need to add a hint to compositor either about pointer being locked to specific output (if we want to keep pointer per output), or add hint about pointer getting association with pointer (to have exactly one pointer per host seat). Right now [wlroots associate pointer with output during initialization](https://github.com/swaywm/wlroots/blob/master/backend/wayland/seat.c#L521).

**Comment by RPigott** [comment]
I don't really see how the enter event is related. The offset manifests whether or not the cursor leaves the virtual output.

For example here's a naïve fix:

```diff
diff --git a/backend/wayland/seat.c b/backend/wayland/seat.c
index 71e04de6..d0d73d37 100644
--- a/backend/wayland/seat.c
+++ b/backend/wayland/seat.c
@@ -81,11 +81,13 @@ static void pointer_handle_motion(void *data, struct wl_pointer *wl_pointer,
 		return;
 	}
 
+	int noutputs = wl_list_length(&backend->outputs);
+
 	struct wlr_output *wlr_output = &pointer->output->wlr_output;
 	struct wlr_event_pointer_motion_absolute event = {
 		.device = &pointer->input_device->wlr_input_device,
 		.time_msec = time,
-		.x = wl_fixed_to_double(sx) / wlr_output->width,
+		.x = wl_fixed_to_double(sx) / wlr_output->width / noutputs,
 		.y = wl_fixed_to_double(sy) / wlr_output->height,
 	};
 	wlr_signal_emit_safe(&pointer->wlr_pointer.events.motion_absolute, &event);
```

The above works reasonably for me, which at least demonstrates what's wrong with the current behavior. I don't know why this division would be necessary though, so I'm pretty sure the real error is somewhere else.

**Comment by ony** [comment]
> I don't really see how the enter event is related. The offset manifests whether or not the cursor leaves the virtual output.

@RPigott, sorry. I did not made it clear enough. My main point was that when we have 1 host seat with pointer and request Wayland back-end to create 2 outputs, we actually create 2 pointer devices (by default in same seat) tied to a single host seat pointer, but different outputs.

Problem can be intensified by using config:
```
output WL-1 pos 0 0
output WL-2 pos 3000 0
```
(note that putting one output below another speed-up vertical speed)

This suggests that Sway tries to map coordinates 0.0 .. 1.0 received from back-end to a whole virtual space where outputs are arranged, including that invisible gap between them. And that's causes speed-up. Wayland back-end in wlroots reports absolute coordinates for pointer only within specific output for obvious reason of not knowing how outputs are arranged (see last link).

Useful to have layout:
```
+-------------+
|     wev     |
+------+------+
| WL-1 | WL-2 |
+------+------+
```
After moving cursor to left-most part of `WL-1` (until it stops moving) and then moving there  to right border of `WL-2` gives exactly middle of `wev` window when moving cursor up.

With debug of which pointer serves which movements it becomes more clear that first pass is handled by pointer created for `WL-1` and after that pointer for `WL-2` takes lead.

```diff
--- a/backend/wayland/seat.c
+++ b/backend/wayland/seat.c
@@ -81,6 +81,9 @@ static void pointer_handle_motion(void *data, struct wl_pointer *wl_pointer,
                return;
        }

+       wlr_log(WLR_DEBUG, "pointer %p (%.3f, %.3f)",
+               pointer, wl_fixed_to_double(sx), wl_fixed_to_double(sy));
+
        struct wlr_output *wlr_output = &pointer->output->wlr_output;
        struct wlr_event_pointer_motion_absolute event = {
                .device = &pointer->input_device->wlr_input_device,
@@
```
```
... near the border WL-1/WL-2
00:00:19.758 [backend/wayland/seat.c:85] pointer 0x6120000d0b40 (319.828, 91.086)
00:00:19.759 [sway/desktop/transaction.c:414] Transaction 0x6040001395d0 committing with 4 instructions
00:00:19.759 [sway/desktop/transaction.c:281] Applying transaction 0x6040001395d0
00:00:19.774 [backend/wayland/seat.c:85] pointer 0x6120000d0b40 (320.754, 91.086)
... after crossing WL-1/WL-2 border
00:02:15.214 [backend/wayland/seat.c:85] pointer 0x6120000d0b40 (527.668, 213.535)
... near the right border of WL-2
00:04:05.342 [backend/wayland/seat.c:85] pointer 0x6120000d0b40 (637.750, 212.418)
00:04:07.430 [backend/wayland/seat.c:85] pointer 0x612000129040 (0.617, 212.418)
00:04:07.430 [sway/desktop/transaction.c:414] Transaction 0x6040001f6d50 committing with 4 instructions
00:04:07.430 [sway/desktop/transaction.c:281] Applying transaction 0x6040001f6d50
00:04:07.614 [backend/wayland/seat.c:85] pointer 0x612000129040 (0.969, 212.418)
... teleported and now near the left side of WL-1
```

So.. Having cursor traversing 2 times same outputs while moving from left-most position to right-most - is likely caused by second  pointer being picked up to report mouse entering WL-2. See that  `pointer 0x6120000d0b40` changed to `pointer 0x612000129040`.

Note that right-most position reported by `wev` was 1277. I.e. half of it is 639.

```
[13:      wl_pointer] motion: time: 25193663; x, y: 1276.652344, 132.398438
[13:      wl_pointer] frame
[13:      wl_pointer] leave: surface: 3
```

**Comment by emersion** [comment]
Sway should map each pointer device to its output, via `wlr_input_device.output_name`.
