### ISSUE TITLE
Left-handedness and calibration matrix won't stick to XP Pen tablet

### ISSUE THREAD

**Issue by unresolvedsymbol** [swaywm/sway#5654]
- **Sway Version:**
sway version 1.5-6991ac8c (Aug 22 2020, branch 'master')

- **Debug Log:**
 http://0x0.st/iEd8.txt

- **Configuration File:**
http://0x0.st/iEdN.txt
If needed, full configuration can be found [here](https://github.com/unresolvedsymbol/dotfiles/blob/master/.config/sway/config)

- **Description:**
Setting left handed mode or the calibration matrix on my XP Pen G430S has no effect yet returns success.
https://streamable.com/oy1i9s
Note: The video shows left handedness enabled for the mouse input of the tablet but this has no effect and coordinates are still inverted. Trying to use calibration matrix on either of the two doesn't change it at all, however it can change it on my touchscreen.

**Comment by RedSoxFan** [comment]
Please post the output of `swaymsg -rt get_inputs`.

**Comment by unresolvedsymbol** [comment]
@RedSoxFan Output of that command is shown in the video

**Comment by RedSoxFan** [comment]
Oh oops sorry. It looks like your `tablet_tool` does not support `left_handed` so it will not work.

As for `calibration_matrix`, it looks like Sway currently only supports this for touch devices. I can submit a PR to add support for tablet tools tonight (eastern us).

**Comment by unresolvedsymbol** [comment]
Commit has been working flawlessly, thanks
