### ISSUE TITLE
'DRM universal planes unsupported' ambiguous?

### ISSUE THREAD

**Issue by CaptainBloodz** [swaywm/sway#5657]
- **Sway Version:**
  - `sway -v`
sway version 1.5-2c769232 (Sep  2 2020, branch 'HEAD')
wlroots version to current master.

command line:
exec env XDG_RUNTIME=/home/user/.cache/sway XDG_RUNTIME_DIR=/home/user/.cache/sway sway -dV > ~/.cache/sway/sway.log 2>&1

- **Debug Log:**
[sway.log.zip](https://github.com/swaywm/sway/files/5163675/sway.log.zip)

- **Description:**
log file shows:

00:00:00.392 [INFO] [backend/drm/backend.c:138] Initializing DRM backend for /dev/dri/card1 (vgem)
00:00:00.393 [ERROR] [backend/drm/drm.c:51] DRM universal planes unsupported
00:00:00.393 [ERROR] [backend/backend.c:163] Failed to open DRM device 10
00:00:00.417 [sway/main.c:375] Starting sway version 1.5-2c769232 (Sep  2 2020, branch 'HEAD')
00:00:00.417 [sway/server.c:56] Initializing Wayland server
00:00:00.394 [DEBUG] [types/wlr_idle.c:247] idle manager created
00:00:00.394 [INFO] [backend/noop/backend.c:51] Creating noop backend

Here's:
i965 graphical stack with intel drivers here.

ls /dev/dri/card*
/dev/dri/card0  /dev/dri/card1

Single monitor connected as HDMI-0

There is no log output such as:
Initializing DRM backend for /dev/dri/card0 (vgem)

So it sounds a little ambiguous if following
'DRM universal planes unsupported' refers to:
- /dev/dri/card1 only (likely because there is no monitor connected there, so not graphic stack initiated)
- or to both graphical stacks (which would require investigation as I expect it to be supported on HDMI-0)

Thks 4 ur attention, interest & support.

**Comment by Geo25rey** [comment]
`wlroots` bug not `sway`

**Comment by Geo25rey** [comment]
The error message you are referring to is not ambiguous since the initialization process is synchronous. It loads the first graphics card and checks for it's capabilities. Then, once it is determined whether the graphics card is capable of run with wlroots, the next graphics card is potentially loaded.

**Comment by emersion** [comment]
You need to upgrade your kernel.

**Comment by CaptainBloodz** [comment]
> You need to upgrade your kernel.

Not sure:
uname -r
5.8.5-gentoo

Reconfigure is more likely.
That's what I was more afraid to be raised :(.

Thks 4 ur attention, interest & support.

**Comment by CaptainBloodz** [comment]
> `wlroots` bug not `sway`

I suspected it, but wlroots log lines seems undifferentiated.

Thks 4 ur attention, interest & support.

**Comment by Geo25rey** [comment]
Can we see the output of the following command?
`lsmod | grep vgem`

**Comment by emersion** [comment]
Ah, vgem. You can ignore this error, vgem is a special virtual driver that only supports allocating buffers.

**Comment by Geo25rey** [comment]
@emersion Yes, but if I understand correctly, then it's only really used with X11. I was gonna suggest blacklisting the driver if it's not actually being used, or uninstalling the package that gets it loaded in the first place, but I'm not sure of what package that is.

**Comment by CaptainBloodz** [comment]
> Can we see the output of the following command?
> `lsmod | grep vgem`

Out of scope issue caused older kernel fallback.
amd64 /usr/src/linux-5.4.61-gentoo-rt # lsmod | grep vgem
amd64 /usr/src/linux-5.4.61-gentoo-rt # grep VGEM /usr/src/linux/.config
CONFIG_DRM_VGEM=y
