### ISSUE TITLE
xkb_options only apply if set in a specific order

### ISSUE THREAD

**Issue by ericonr** [swaywm/sway#5661]
### Please fill out the following:
- **Sway Version:**
  - `v1.5`

- **Debug Log:**
  - https://gist.github.com/ericonr/0b1622a07b26ab5ed6ae8561baf51f70

The relevant parts seem to be:

```
00:00:16.024 [sway/commands.c:255] Handling command 'input type:keyboard xkb_options "compose:ralt,ctrl:nocaps"'
00:00:16.024 [sway/commands/input.c:53] entering input block: type:keyboard
00:00:16.024 [sway/config/input.c:15] new_input_config(type:keyboard)
00:00:16.024 [sway/commands.c:423] Subcommand: xkb_options compose:ralt,ctrl:nocaps
00:00:16.024 [sway/commands/input/xkb_options.c:18] set-xkb_options for config: type:keyboard options: compose:ralt,ctrl:nocaps
[...]
00:00:23.687 [sway/commands.c:255] Handling command 'input type:keyboard xkb_options "ctrl:nocaps;compose:ralt"'
00:00:23.687 [sway/commands/input.c:53] entering input block: type:keyboard
00:00:23.687 [sway/config/input.c:15] new_input_config(type:keyboard)
00:00:23.687 [sway/commands.c:423] Subcommand: xkb_options ctrl:nocaps;compose:ralt
00:00:23.687 [sway/commands/input/xkb_options.c:18] set-xkb_options for config: type:keyboard options: ctrl:nocaps;compose:ralt
00:00:23.687 [sway/config/input.c:15] new_input_config(temp)
00:00:23.688 [sway/input/keyboard.c:692] [xkbcommon] Unrecognized RMLVO option "ctrl:nocaps;compose:ralt" was ignored
00:00:23.690 [sway/config/input.c:333] Config stored for input type:keyboard
00:00:23.690 [sway/input/keyboard.c:692] [xkbcommon] Unrecognized RMLVO option "ctrl:nocaps;compose:ralt" was ignored
00:00:23.700 [sway/input/keyboard.c:765] Removing keyboard 0:0:wayland from group 0x7f7d03dce390
```

- **Config**

```
input type:keyboard {
	xkb_layout us,br
	xkb_options ctrl:nocaps
}
```

- **Description:**

I wanted to enable `compose:ralt` and keep `ctrl:nocaps` from my config, so I tried running

```
$ swaymsg 'input type:keyboard xkb_options "ctrl:nocaps;compose:ralt"'
```

which didn't output any error in the terminal, but resulted in neither configuration being applied: the CapsLock key was back to being CapsLock, and Compose wasn't working. On the other hand,

```
$ swaymsg 'input type:keyboard xkb_options "compose:ralt,ctrl:nocaps"'
```

works just fine.

I think there's a chance this might be a `xkb` bug, or sway might be missing some pre-processing it needs to do with `xkb_options`.

Thanks!

**Comment by ericonr** [comment]
> "ctrl:nocaps;compose:ralt"

Stupid typo, `;` isn't supported. Should this be considered a bug still, due to lack of error message?

**Comment by emersion** [comment]
>Should this be considered a bug still, due to lack of error message?

libxkbcommon doesn't return an error, so we can't do much here.

**Comment by Geo25rey** [comment]
> Should this be considered a bug still, due to lack of error message?

No, there is a warning message from xkbcommon:
> 00:00:23.688 [sway/input/keyboard.c:692] [xkbcommon] Unrecognized RMLVO option "ctrl:nocaps;compose:ralt" was ignored

**Comment by ericonr** [comment]
> No, there is a warning message from xkbcommon:

I meant in the output of `swaymsg`. It prints an error for other types of wrong usage.

**Comment by emersion** [comment]
Well, that's complicated, because the command technically succeeded.

**Comment by ericonr** [comment]
> Well, that's complicated, because the command technically succeeded.

I see. So currently the command being executed is propagated, not the result inside sway? And I guess that could be quite complicated to do.

**Comment by Geo25rey** [comment]
@ericonr You can open a bug report with xkbcommon if you want to discuss this further.
