### ISSUE TITLE
hide_cursor stops countdown after left clicking once (but not moving the cursor)

### ISSUE THREAD

**Issue by antisocrates** [swaywm/sway#5679]
- **Sway Version:**
sway version v1.5

- **Debug Log:**
[sway.log](https://gist.github.com/antisocrates/118a0a106e6be87fde9d000541ac144e)

- **Configuration File:**
[config](https://gist.github.com/antisocrates/0595d8908fee19dab3b38d6325497ca7)

- **Description:**
  Using `seat * hide_cursor 3000` in sway config to hide the mouse cursor after 3 seconds of inactivity.
The countdown (towards timeout to hide the cursor) stops after clicking anywhere indefinately (until the cursor moves again)

  _Steps to reproduce:_

 1. Left click anywhere
 2. Dont move the cursor (stay on the same spot you clicked, otherwise countdown resets and hides as normal)

     **Here is a 60second demonstration of the issue i have uploaded:**
     [Video Demonstration](https://streamable.com/03ejjf)

**_Clarification:_**
_Clicking will stop the countdown, showing the cursor, but won't restart it so the cursor will remain visible indefinitely until moved._

**Comment by JustinLovinger** [comment]
Clicking is mouse activity. I would expect the countdown to reset after any mouse activity, not just movement.

**Comment by Emantor** [comment]
Please test #5681.

**Comment by TheAvidDev** [comment]
> Clicking is mouse activity. I would expect the countdown to reset after any mouse activity, not just movement.

To clarify, because I got confused as well, the issue seems to be that clicking will stop the countdown, showing the cursor, but won't restart it so the cursor will remain visible indefinitely until moved.

**Comment by antisocrates** [comment]
> To clarify, because I got confused as well, the issue seems to be that clicking will stop the countdown, showing the cursor, but won't restart it so the cursor will remain visible indefinitely until moved.

Yes thats exactly what happens. I added this clarification to my buy report.

**Comment by antisocrates** [comment]
> Please test #5681.

I am building sway from git master branch with your commit, but the build fails (for unrelated reason as far as i understand)

[ninja](https://gist.github.com/antisocrates/fda2f79d0a231278af19ecdadc9a4821)

[meson](https://gist.github.com/antisocrates/7c4c4363e5c295cdb940638669630957)

**Comment by TheAvidDev** [comment]
@antisocrates update wlroots.

**Comment by Xyene** [comment]
Not quite resolved yet.

**Comment by antisocrates** [comment]
The original issue is fixed.

One minor observation, comparing the hide_cursor behavior, with the behavior of unclutter on i3/xorg:

When you first login on i3/xorg, unclutter starts the countdown immediately and hides the cursor after 3 seconds for example.

In contrast, when you first login on sway, hide_cursor does not start the countdown and the cursor remains visible indefinetely until the first activity. (until you click or move the cursor for the first time)

I am not sure if this is intended behavior or a bug, so i also report this.
