### ISSUE TITLE
hide_cursor timeout doesn't start automatically after login

### ISSUE THREAD

**Issue by antisocrates** [swaywm/sway#5684]
- **Sway Version:**
sway version 1.5-2efecc14 (Sep 15 2020, branch 'master')

- **Debug Log:**
[sway.log](https://gist.github.com/antisocrates/25928b9e16330a651e807948bf9c1f8c)

- **Configuration File:**
[config](https://gist.github.com/antisocrates/5ded2d6d45b5f286b255245b52345a3d)

- **Description:**
  Using `seat * hide_cursor 3000` in sway config to hide the mouse cursor after 3 seconds of inactivity.

  When you first login on i3/xorg, unclutter starts the countdown immediately and hides the cursor after 3 seconds for example.

  In contrast, when you first login on sway, hide_cursor does not start the countdown and the cursor remains visible indefinetely until the first activity. (until you click or move the cursor for the first time)

  _Steps to reproduce:_

  1.  Start sway
  2.  Don't do any mouse activity (moving, scrolling, clicking)
  3.  The cursor remains visible indefenitely, in spite of having a timeout of 3 seconds in sway/config, until the first activity for the session is registered

**Comment by Geo25rey** [comment]
@Emantor @emersion This bug still exist as of sway version 1.5-41999d7c (Sep 16 2020, branch 'master'), at least for secondary seat.

**Comment by antisocrates** [comment]
For seat0 everything works as expected. I dont have seat1 on this system to verify.

**Comment by Geo25rey** [comment]
@antisocrates you can make a new seat by attaching a cursor to a seat other than seat0. The new seat can be named anything not just seat#. See `man 5 sway-input` at the bottom for a better explanation of setup.

**Comment by antisocrates** [comment]
> @antisocrates you can make a new seat by attaching a cursor to a seat other than seat0. The new seat can be named anything not just seat#. See `man 5 sway-input` at the bottom for a better explanation of setup.

I used `seat foo attach *` to attach everything to another seat and later `seat foo attach 0:14373:USB_OPTICAL_MOUSE` to attach just the usb mouse to another seat.
In both cases `seat foo hide_cursor 3000` but also `seat * hide_cursor 3000` worked as expected, hiding the cursor after 3 seconds of inactivity after login (without any prior activity) and also after some initial activity.

I also could hide the cursor of my optical mouse but allow a seperate cursor on another seat to be visible for my touchpad, or hide both in seperate seats as well as in the same seat.

So probably your issue is due to something else.

**Comment by Geo25rey** [comment]
@antisocrates #5685 only armed the hide_cursor timeout for pointers not pens or touch screens. I just sumbitted a pull request (#5695) to fix the issue.

**Comment by newzubakhin** [comment]
@emersion The issue described by @Geo25rey is still persist. hide_cursor timeout doesn't start automatically after login in the case of multiple seats. Here is my config

```
seat seat_tablet {
    attach "1386:891:Wacom_One_by_Wacom_M_Pen"
    fallback false
    hide_cursor 5000
}

seat seat0 {
    fallback true
    hide_cursor 10000
}
```

**Comment by emersion** [comment]
Please open a new issue with debug logs etc
