### ISSUE TITLE
swaywm starts up not applying windows resize

### ISSUE THREAD

**Issue by JAicewizard** [swaywm/sway#5693]
### Please fill out the following:
- **Sway Version:**
sway version v1.5

- **Debug Log:**
https://gist.github.com/JAicewizard/2e3dc2b1c72321f057e985837920910a

- **Configuration File:**
https://gist.github.com/JAicewizard/4e2fd7705e0807d13071114e92ad9ca1

- **Description:**
When sway starts up but the resizing of the scratchpad windows either doesnt happen at all, or only happens for one of the two. It is inconsistent, so it is a bit of a surprise when I start up sway if I can enjoy my terminal. The log is from when the terminal did not resize, the math window I didnt test.

**Comment by Geo25rey** [comment]
@JAicewizard can you fill out the bug report elaborating on your title? Thank you

**Comment by JAicewizard** [comment]
aww sorry I filled out out. I thought github saved it but it didnt. So after I opened my lid it must have removed all that.
I will tag you when I am able to update it, I already have all the logs etc.

**Comment by JAicewizard** [comment]
@Geo25rey again so sorry, I updated the post with the data filled in. The gist upload date is my witness.

**Comment by JAicewizard** [comment]
From testing this a couple times with sway 1.6, this seems to be solved. I will reopen if I see it occurring again
