### ISSUE TITLE
no systemd/elogind system crash at launch

### ISSUE THREAD

**Issue by shoober420** [swaywm/sway#5694]
- **Sway Version:**
  - `sway version 1.5-41999d7c (Sept 16 2020, branch 'master')`

- **Debug Log:**
  - [sway.log](https://github.com/swaywm/sway/files/5235598/sway.log)

- **Configuration File:**
  - https://gist.github.com/shoober420/59a2713bb09487a935a45ef4341a9d46

- **Description:**
  I use Obarun Linux, which uses the s6 init system. I also use the syslinux bootloader. There is no systemd or elogind on my machine. I can't launch sway on Obarun. I followed the instructions on the Gentoo wiki and use this zshenv file (https://gist.github.com/shoober420/35c82715ff4cfc7ba2057e6ea657e40f). Here are the compile options used (https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=wlroots-nosystemd-git).

**Comment by Geo25rey** [comment]
Looks like you haven't provided your user with access to your libinput devices. To enable this, you need to add your user to the "input" group. To achieve this run the following commands.

```
sudo groupadd input # confirm input group exists
sudo usermod -aG input $USER # appends the input group to your user ($USER)
```

**Comment by shoober420** [comment]
The input group does exist on my machine, but even after manually adding myself to the input group, I get the same errors in the logs. I can launch sway when using “WLR_LIBINPUT_NO_DEVICES=1” but I can’t use sway with that of course.

**Comment by shoober420** [comment]
I found it, it’s the “perl” package in the Arch testing repositories. Sorry for the confusion.
