### ISSUE TITLE
Indicators not displayed in splith and splitv layouts

### ISSUE THREAD

**Issue by crocket** [swaywm/sway#5699]
- **Description:**

In i3, indicators are shown on windows in splith and splitv layouts.

In sway, indicators are not shown until I create a split container.

Without indicators, it's difficult to know whether I'm in splith or splitv layout.

**Comment by Xyene** [comment]
Please post your config and reproduction steps, as creating a split highlights the correct edge:

![image](https://user-images.githubusercontent.com/1403503/95027845-b7ce1080-0669-11eb-9a0e-0f7d473a29d6.png)

**Comment by crocket** [comment]
The most minimal config shown below reproduces the issue.

```
set $mod Mod4
set $alt Mod1

workspace_layout default

bindsym $mod+Return exec alacritty
bindsym $mod+d exec my-bemenu-run

bindsym $mod+Shift+s split horizontal
bindsym $mod+$alt+s split vertical
bindsym $mod+Ctrl+s split toggle
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+x layout toggle split

# This is my color theme
include colors
```

You executed either `split horizontal` which creates a nested split container. This is not splith or splitv laytout at the top level.
The default laytout is splith as far as I know.

**Comment by Xyene** [comment]
Thanks for the explanation. Could you give https://github.com/swaywm/sway/pull/5721 a try and see if the behavior matches what you expect?

**Comment by crocket** [comment]
This issue is fixed in the latest commit.
