### ISSUE TITLE
&lt;, &gt;, and other pango escape codes aren't rendered in swaybar.

### ISSUE THREAD

**Issue by crocket** [swaywm/sway#5702]
- **Sway Version:** 1.5
- wlroots version: 0.11.0

- **Debug Log:**

Nothing useful in debug log

- **Description:**

If I try to render `&lt`, `&gt;`, and other pango escape codes on swaybar, they are not shown as `<`, `>`, and so on.
The same issue occurs on i3bar, too.

Only `&amp;` is rendered as `&` on both i3bar and swaybar.

**Comment by RPigott** [comment]
I can't reproduce. I'm guessing it has more to do with your status line program. To interpret pango markup your status program should set the flag for it in the json swaybar-protocol(7).

When I try with plain status lines, <, >, and & all appear normally as expected.
When I use the json protocol and correctly set `"markup":"pango"`, `&lt;`, `&gt;`, and `&amp;` all produce the expected symbols.

**Comment by crocket** [comment]
I currently use i3pystatus.

**Comment by crocket** [comment]
I figured out that it is an i3pystatus issue.
