### ISSUE TITLE
Sway crashes when moving children of container currently in scratchpad

### ISSUE THREAD

**Issue by QuentinI** [swaywm/sway#5707]
###### Setup
- Sway Version: 1.5
- [Debug Log](https://gist.github.com/QuentinI/edfc9e000a3fd344441b62187c549a73)
- [Configuration File](https://gist.github.com/QuentinI/3f4702e63a3b586872063c93fccf3b9c) (only difference from default is removal of default wallpaper)

###### Description
Sway crashes when moving children of a container residing in scratchpad to any workspace. Steps to reproduce with default config (debug log is of me doing this):
- Create a new terminal emulator window (`$mod+Return`)
- Execute `swaymsg 'splith'` in it
- Switch to another workspace (`$mod+2`)
- Create yet another terminal emulator window (`$mod+Return`)
- Run `swaymsg '[con_id=6] move to scratchpad'` in it
- Return to workspace 2 (`$mod+2`)
- Run `swaymsg '[con_id=5] move to workspace 1'`
- Sway crashes

Sway still crashes if there are more children in parent container (i.e. moving one child doesn't leave it empty). Sway doesn't seem to crash if parent container isn't in scratchpad.

**Comment by emersion** [comment]
Please provide a stack trace. You can do so by compiling from source, reproducing the crash and then running `coredumpctl gdb` and then `bt full`.

Here are some instructions to compile from source: https://github.com/swaywm/sway/wiki/Development-Setup#compiling-as-a-subproject

**Comment by QuentinI** [comment]
Sorry, forgot about that.
Stack trace: https://gist.github.com/QuentinI/ff5ba7184a62eadac23cada3e6dce97e
Achieved by running this script: https://gist.github.com/QuentinI/79e8eabf060da679f3c6eac4a9949db3
