### ISSUE TITLE
i3 config is taken until sway config file exists, then i3 config is completely ignored

### ISSUE THREAD

**Issue by BNolet** [swaywm/sway#5708]
- **Sway Version:** 1.4

- **Debug Log:** Not *really* relevant bit here ya go: https://gist.githubusercontent.com/BNolet/0e02edfa39088c1e3852fff6004598f2/raw/ad45e5e69fd8bd017c4db72f913fbb81d363fe1a/sway.log

- **Configuration File:** i3 config: https://gist.github.com/BNolet/83b0615ced4aac0c687e7708562d3f55

sway config: created file and had a single input line to reverse mouse scrolling

- **Description:** When going from i3 to sway, it seems that no default configuration is created, due to sway having found a config file in one of the spots mentioned in `man sway`. But then when you create a sway config in sway config dir, the default assumption would be that this would *add* to the existing configuration, but this does not. You basically end up with an empty screen with no way to exit, save for going into a tty and doing a `killall`

**Comment by Emantor** [comment]
The configuration file search order is documented in `man 1 sway` and sway recommends to install a default configuration to `/etc/sway/config` to prevent startup with an almost empty configuration. The man page does not mention any merging behavior, which AFAIK is also not implemented within i3. Note that  at least sway allows specific `include` commands in the configuration file.

**Comment by BNolet** [comment]
The include command is probably the main reason that I switched over from i3 to sway in the first place. 

I understand that there's no merging mentioned, but I think it would suffice to mention at the very least making sure to create a configuration file with all the regular fixins that i3 includes by default. I don't know if sway includes a first-time setup configurator but if it does, it may want to run when there's a config being taken specifically from a path mentioning i3.

I'm not sure what a more appropriate label for this issue would be, by the way. For something like this, what would you recommend?

**Comment by 0Karakurt0** [comment]
This is intended behaviour and not a bug. No one prohibits you to just copy i3 config into sway's one, and that is exactly what everyone does. Well, almost everyone.
Currently there's no setup wizard, and such a feature will be implemented in one, I guess. If it will be implemented at all
