### ISSUE TITLE
Discrepancy in focusing tabs of split containers by mouse

### ISSUE THREAD

**Issue by Xyene** [swaywm/sway#5710]
Consider the layout `T[app1 H[app2 app3 app4]]`, with `app1` currently having focus. In i3, clicking the `H[app2 app3 app4]` tab gives focus to the `H` _parent container_. In Sway, focus is handed to whatever child last held focus within the `H`. Both i3 and Sway behave the same when switching tabs via keyboard (i.e., focusing last-focused child of `H`).

I think Sway's behavior is more user-friendly here, since it doesn't require a second click to focus the container that was previously focused. Nonetheless, this doesn't match i3's behavior, so I've opened this ticket to at least document the issue. Personally, I'd be in favor of leaving it as-is.

**Comment by RPigott** [comment]
That is pretty weird behavior from i3 imo. Have you considered opening an issue for i3?

**Comment by Xyene** [comment]
I hadn't, but since that seems like a reasonable thing to do, here it is: https://github.com/i3/i3/issues/4225

**Comment by Xyene** [comment]
Closing since https://github.com/i3/i3/pull/4230 implemented this behavior in i3.
