### ISSUE TITLE
Screen mirroring

### ISSUE THREAD

**Issue by mb720** [swaywm/sway#5713]
Hi and thanks for Sway!

Currently, when I attach an external monitor using VGA, Sway creates a new workspace on the external monitor. This is great, but there are times when I want to mirror/duplicate what's going on on the laptop monitor.

From a user perspective, that feature could work similar to [`xrandr`'s `--same-as` option](https://unix.stackexchange.com/questions/371793/how-to-duplicate-desktop-in-linux-with-xrandr).

Thanks!

**Comment by Garzet** [comment]
[#1666](https://github.com/swaywm/sway/issues/1666) includes mirroring and other output layouts. I'm not sure if it is being work on though.

**Comment by emersion** [comment]
Yeah, closing as a dup of #1666

**Comment by Ferdi265** [comment]
#1666 has been split, linking the new issue for output mirroring #8644 for people finding this old issue via web search / google.

**Comment by mb720** [comment]
By the way, for people looking for a solution right now, I've been quite happy with [wl-mirror](https://github.com/Ferdi265/wl-mirror) on Sway.
