### ISSUE TITLE
Blender occasionally renders WM unusable

### ISSUE THREAD

**Issue by clarfonthey** [swaywm/sway#5720]
- Sway Version: 1.5
- Blender Version: 2.90.1
- Graphics: Intel CPU
- Debug Log: https://gist.github.com/clarfonthey/4a47942cd7d6003b1eb9bac90f5e98b1
(included slightly before the crash up until sway exit)
- Reproduced with default config

## Scenario

In the case of the output, on a two-monitor setup, I had Firefox open in one monitor and Blender in the other. Was able to reproduce with only one monitor and without Firefox open. Essentially, just using Blender for a while will eventually crash to the point where no WM hotkeys work, even if you kill Blender. I tried switching TTYs and killing blender to no avail, and in general what happens is you can move the mouse cursor (sometimes it's scaled to be very large) but absolutely nothing on the keyboard will work, although occasionally if Firefox is focused before the crash I can manage to hit spacebar to pause/unpause a video. (Altering the WM state in any way, such as killing blender, will make this no longer possible.)

I should add that I wasn't doing anything specific or complicated in Blender; just messing around, after a while, will cause this to happen. It always causes one of two scenarios to happen -- either the UI appears to be shaking back and forth at a range of around 2px, or the screen just turns black, still showing the cursor like mentioned before.

From the log output, it appears to be an xwayland issue, but I'm honestly not sure and figured I'd start by posting here. I do think it's a bug *somewhere*, but I haven't 100% confirmed whether it's a bug in sway, wlroots, or Xwayland.

Note, sway doesn't ever "crash," it just becomes unusable. Sending SIGTERM to sway causes it to shut down normally.

**Comment by Emantor** [comment]
I can't see which mesa version you are running, but the new `iris` i915 driver default seems to have issues with blender, see https://gitlab.freedesktop.org/drm/intel/-/issues/2380 .
I have previously observed similar GPU hangs on sway even without the usage of blender. Using `MESA_LOADER_DRIVER_OVERRIDE=i965` for my whole sway session fixed this on my laptop.

**Comment by clarfonthey** [comment]
Huh, I didn't know there was a new Intel driver -- I should be running `i915` since I have that autoloaded in my initcpio.

**Comment by Emantor** [comment]
> Huh, I didn't know there was a new Intel driver -- I should be running `i915` since I have that autoloaded in my initcpio.

This refers to the kernel driver, not to the mesa driver which implements i.e. OpenGL ES interface. Note that `i915` refers to the kernel driver and `iris` and `i965` to the mesa 3D graphics implementations.

**Comment by clarfonthey** [comment]
Going to just close this since I haven't been using sway for a while, there have been a lot of changes to wlr, and no one else has commented saying that they also have this issue.

**Comment by itsmeeudrino** [comment]
I was having the same isssue, using `MESA_LOADER_DRIVER_OVERRIDE=i965` fixed it for me!
