### ISSUE TITLE
Laptop + Screen, clamshell mode?

### ISSUE THREAD

**Issue by nschloe** [swaywm/sway#5726]
When attaching my laptop to an external screen, sway will put some desktops on the new screen. The set of desktops has no overlap from one screen to another, so going to "desktop 3", always gets me to one of them. So far, so good.

Now, when I close the laptop lid, I would expect that all desktops move to the active screen. This is not the case. Instead, if desktop 1 was on the laptop screen, it will remain there, even though the lid is closed.

**Comment by emersion** [comment]
Yes, you'll need to use a lid switch binding to toggle the internal screen.

**Comment by nschloe** [comment]
Shouldn't this be the default behavior?

**Comment by nschloe** [comment]
Dup of https://github.com/swaywm/sway/issues/3137 btw.

**Comment by emersion** [comment]
Sway has no way to know what your internal screen is.

**Comment by nschloe** [comment]
Alright, makes sense.

**Comment by rileyrg** [comment]
> Alright, makes sense.

The first one ? swaymsg -t get_tree | jq '.nodes[] | select(.name | test ("^_") | not).name'
