### ISSUE TITLE
Seemingly random crashes involving x11 apps / xwayland

### ISSUE THREAD

**Issue by mirko** [swaywm/sway#5731]
### Please fill out the following:
- **Sway Version:**
sway version 1.5-600cf38c (Oct  4 2020, branch 'HEAD')

- **Stack Trace:**
```
#0  0x000055a2c740b680 in ?? ()
#1  0x00007ff62e947492 in wl_event_loop_dispatch () from /lib/x86_64-linux-gnu/libwayland-server.so.0
#2  0x00007ff62e945105 in wl_display_run () from /lib/x86_64-linux-gnu/libwayland-server.so.0
#3  0x000055a2c6a462e4 in server_run (server=0x55a2c6ab92e0 <server>) at ../sway/server.c:244
#4  0x000055a2c6a45817 in main (argc=1, argv=0x7fff7a2236a8) at ../sway/main.c:412
```

- **Description:**
Occasionally, unfortunately often enough (twice / day in average) for it being really annoying and making me consider switching back to xorg, sway crashes and I end up back in my login manager.
This /seems/ to happen only when xwayland is involved.
Like, when starting a x11 application. I also noticed that when using `xhost` - where it was seemingly running longer than expected and then sway crashed. Other candidates are gimp, pidgin, ..
Happy to help trying to narrow it down. Wasn't able to reproduce unfortunately :/
Another theory is that this only happens when having involved `xhost` before, e.g. `xhost +SI:localuser:other_user`, however since I do this sooner or later after every login as I need other users being able to stat GUI applications, it's only a bare correlation.

**Comment by emersion** [comment]
A full debug log would help.

**Comment by lucastrvsn** [comment]
I'm having this issue as well. Especially when I'm using google-chrome-stable package. I'll try to post some debug of my issue when happen again.

**Comment by Xyene** [comment]
Closing this ticket due to inactivity; feel free to reopen with logs if you are able to reproduce the crash on sway/wlroots master.
