### ISSUE TITLE
swaywm diagonal window resizing broken, poor performance

### ISSUE THREAD

**Issue by Tragyn** [swaywm/sway#5736]
I'm not sure I could describe the issue appropriately so I made a video: https://www.youtube.com/watch?v=jARlwPBSErg&feature=youtu.be

You can see the performance issue when resizing diagonally.  Horizontal/vertical resizing works just fine.

Using latest swaywm-git and wlroots-git

The type of windows I'm resizing doesn't seem to matter, but in this case it's xfce4-terminal and firefox-nightly (xwayland not being used).

**Comment by Xyene** [comment]
Until this is fixed, it can be worked around by starting Sway with `-D noatomic` (at the cost of, well, losing atomic updates).

**Comment by Tragyn** [comment]
> Until this is fixed, it can be worked around by starting Sway with `-D noatomic` (at the cost of, well, losing atomic updates).

Hey, thanks for the tip.  What's Atomic?  I can't find out anything about it.

**Comment by Xyene** [comment]
Atomic layout updates synchronize layout updates with all clients before rendering the next frame, so resizes look less choppy. (Well, normally...)

The issue here turned out to be easier to track down than expected, and I've opened https://github.com/swaywm/sway/pull/5744 to fix it. Could you give it a try?

**Comment by Tragyn** [comment]
> Atomic layout updates synchronize layout updates with all clients before rendering the next frame, so resizes look less choppy. (Well, normally...)
> 
> The issue here turned out to be easier to track down than expected, and I've opened #5744 to fix it. Could you give it a try?

I appreciate you tackling that so very quickly, but unfortunately I'm not knowledgeable enough to test it out.  I cloned the repo and applied the patch but I can't seem to build sway.

> wu% ninja -C build
ninja: Entering directory `build'
[2/4] Compiling C object sway/sway.p/desktop_xwayland.c.o
FAILED: sway/sway.p/desktop_xwayland.c.o 
cc -Isway/sway.p -Isway -I../sway -Iinclude -I../include -Iprotocols -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/json-c -I/usr/include/libevdev-1.0/ -I/usr/include/pango-1.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/libdrm -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -std=c11 -g -DWLR_USE_UNSTABLE -Wno-unused-parameter -Wno-unused-result -Wno-missing-braces -Wundef -Wvla '-DSYSCONFDIR="//usr/local/etc"' '-DSWAY_VERSION="1.5-8355884f (" __DATE__ ", branch '"'"'master'"'"')"' -fmacro-prefix-map=../= -pthread -MD -MQ sway/sway.p/desktop_xwayland.c.o -MF sway/sway.p/desktop_xwayland.c.o.d -o sway/sway.p/desktop_xwayland.c.o -c ../sway/desktop/xwayland.c
../sway/desktop/xwayland.c: In function ‘unmanaged_handle_map’:
../sway/desktop/xwayland.c:77:33: error: ‘struct <anonymous>’ has no member named ‘set_geometry’
   77 |  wl_signal_add(&xsurface->events.set_geometry, &surface->set_geometry);
      |                                 ^
[3/4] Linking target swaybar/swaybar
ninja: build stopped: subcommand failed.

**Comment by Xyene** [comment]
Ah, that happens because your copy of wlroots is too old (when building sway from master, you should also be building wlroots from master). Check out https://github.com/swaywm/sway/wiki/Development-Setup#compiling-as-a-subproject for an example.

**Comment by Tragyn** [comment]
> Ah, that happens because your copy of wlroots is too old (when building sway from master, you should also be building wlroots from master). Check out https://github.com/swaywm/sway/wiki/Development-Setup#compiling-as-a-subproject for an example.

I appreciate the help, but I seem to have broken Sway/wlroots completely. ;)

> wu% cat ~/.profile
export PATH="$HOME/.cargo/bin:$PATH"
export PATH=/usr/local/bin:$PATH
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH
export PKG_CONFIG_PATH=/usr/local/lib64/pkgconfig:$PKG_CONFIG_PATH
export PKG_CONFIG_PATH=/usr/local/share/pkgconfig:$PKG_CONFIG_PATH
**export LD_LIBRARY_PATH=/usr/local/lib/:$LD_LIBRARY_PATH**
export LD_LIBRARY_PATH=/usr/local/lib64/:$LD_LIBRARY_PATH
wu [cat ~/.profile] ~/git/wlroots                                                                                                                             20-10-18  4:35PM
wu% ls /usr/local/lib|grep wlroots
libwlroots.so
libwlroots.so.6
wu [ls /usr/local/lib|grep wlroots] ~/git/wlroots                                                                                                             20-10-18  4:35PM
wu% source ~/.profile
wu [source ~/.profile] ~/git/wlroots                                                                                                                          20-10-18  4:35PM
wu% sway
sway: error while loading shared libraries: libwlroots.so.6: cannot open shared object file: No such file or directory

**Comment by Xyene** [comment]
Try running `sudo ldconfig`.

**Comment by Tragyn** [comment]
> Try running `sudo ldconfig`.

Yep gave that a shot and still in the same boat.  Seems pretty weird.

**Comment by Tragyn** [comment]
Seems to work now.  I rebuilt both sway and wlroots, found that /usr/local/lib wasn't in my LD_PATH_LIBRARY (despite being in ~/.profile, and sourced, multiple times).  

The fix seems to work great.

Thanks so much for the help!

**Comment by Xyene** [comment]
Great, thanks for testing!
