### ISSUE TITLE
Extra split when escaping container

### ISSUE THREAD

**Issue by RPigott** [swaywm/sway#5754]
```
$ swaymsg -pt get_version
sway version 1.5-cc8d318a (Oct 20 2020, branch 'master')
$ i3-msg -t get_version
4.18.2 (2020-07-26)
```

Begin with layout:

`H[H[app1 app2]]`

Steps to reproduce:

1. `swaymsg '[con_mark=app1]' move left`

i3's result:

`H[app1 H[app2]]`

sway's result:

`H[H[app1] H[app2]]`

**Comment by RPigott** [comment]
Regressed by #5500. ping @Xyene.

**Comment by Xyene** [comment]
I guess my analysis in https://github.com/swaywm/sway/pull/5500/files#diff-fcf5a35c88e94d24870f5242b57cc1120fd954e9849ed7dce9e05efed9be4748L279 was not entirely correct; I suspect that's what's breaking things here.

**Comment by Xyene** [comment]
I think this was fixed in https://github.com/swaywm/sway/pull/5756, please re-open if I'm wrong.
