### ISSUE TITLE
no support for named based output mapping

### ISSUE THREAD

**Issue by alexcote1** [swaywm/sway#5763]
currently the sway output directive looks like this
`output  DP-5 pos 2560 0 scale 2.0`
and this works great on some machine as the mapping of DP-5 is set to a port. However on mobile workloads thunderbolt docks are used, these do not keep the same mapping necessarily, depending on when its plugged in. 
My proposal is to use the display name as an option to have a more stable mapping.
`Output DP-5 **'Goldstar Company Ltd LG HDR 4K 0x00005C5C'** (focused)
  Current mode: 3840x2160 @ 59.997002 Hz
  Position: 2560,0
  Scale factor: 2.000000`

i expect it to look something like this and display based mappings override port based mappings
`output  'Goldstar Company Ltd LG HDR 4K 0x00005C5C' pos 2560 0 scale 2.0`

I would be willing to put in the time to implement this, it is my first time working with this project and before i make a pr i would like to submit this as a type of rfc of sorts.

**Comment by emersion** [comment]
Already implemented. For more complex setups use kanshi.
