### ISSUE TITLE
Arrow keys do not work with Mod4

### ISSUE THREAD

**Issue by Bering** [swaywm/sway#5769]
### Please fill out the following:
- **Sway Version:**
  - v1.5

- **Debug Log:**
  - This is probably overkill but I'm on a Pinebook Pro so this might be the first log on that computer... https://pastebin.com/USz2876s

- **Configuration File:**
  - https://pastebin.com/1kHALaK8

- **Description:**
  - When using the default Mod1 for $mod, I can use $mod+Left and $mod+Right to change focus. But when I do "set $mod Mod4" it doesn't work. Every other key binding seems to work well with Mod4.

- **NOTE:**
  - I'm on a Pinebook Pro, with Manjaro Sway 20.10 installed

**Comment by Xyene** [comment]
Depending on your keyboard/settings, it's very likely that <kbd>Mod4</kbd>+<kbd>&rarr;</kbd> etc. are being converted to other keycodes. You'll have to use those keycodes in your Sway config. You should be able to figure out their names from `sudo libinput debug-events`.

**Comment by Bering** [comment]
Interesting. No event is generated when I press the arrow key while having Mod4 pressed! I guess the problem is with the keyboard itself. I'll see what I can find on the Pinebook Pro forums.

Looks like this has nothing to do with Sway, I'm closing the issue.

Thanks for your help!

**Comment by Bering** [comment]
In case others are having the same problem: It is indeed a known issue with the keyboard's firmware. Fortunately you can flash a fixed firmware. Follow instructions there: (note that I had to shutdown after step 1, as step 2 was not working after rebooting)

https://github.com/jackhumbert/pinebook-pro-keyboard-updater#revised-firmware
