### ISSUE TITLE
mouse_warping container does't take effect when toggling focus between floating and tiled layers

### ISSUE THREAD

**Issue by b0o** [swaywm/sway#5772]
### Please fill out the following:
- **Sway Version:**
  - `sway version v1.5`

- **Description:**

Based on the descriptions of the `mouse_warping` and `focus mode_toggle` commands, it would seem to reason that changing container focus via `focus mode_toggle` should trigger a mouse warp when `mouse_warping container` is set. Currently, the mouse cursor remains stationary.

```
mouse_warping output|container|none
  If output is specified, the mouse will be moved to new outputs as you move focus between them. If con‐
  tainer is specified, the mouse will be moved to the middle of the container on switch. Default is out‐
  put.

focus mode_toggle
  Moves focus between the floating and tiled layers.
```

**Comment by Xyene** [comment]
Indeed, your understanding is correct. I just tested this, and it seems the conditions necessary to reproduce this issue are that the area of the floating container must overlap with the location on the tiling layer that will be warped to. In that case, the warp will not happen; otherwise, the warp succeeds.

Does this match what you are experiencing?

**Comment by b0o** [comment]
> I just tested this, and it seems the conditions necessary to reproduce this issue are that the area of the floating container must overlap with the location on the tiling layer that will be warped to

Yes. To be more specific, it seems if the center of the floating window overlaps the container to be focused on the tiling layer, the warp does not happen.

**Comment by Xyene** [comment]
I've submitted https://github.com/swaywm/sway/pull/5780 to address this, if you'd like to give it a try.

**Comment by b0o** [comment]
@Xyene Thank you! I haven't had a chance to test it personally yet, will do so soon. Glad to see it's merged.
