### ISSUE TITLE
Sound over hdmi require startx in another tty to work

### ISSUE THREAD

**Issue by Eluminae** [swaywm/sway#5775]
Hello there, 

everything is on the title.

Does anyone got an idea ? What information should I provide to you ?

```
$ neofetch
                __.;=====;.__                   reed@terminator
            _.=+==++=++=+=+===;.                ---------------
             -=+++=+===+=+=+++++=_              OS: Void Linux x86_64
        .     -=:``     `--==+=++==.            Host: MS-7850 1.0
       _vi,    `            --+=++++:           Kernel: 5.8.16_1
      .uvnvi.       _._       -==+==+.          Uptime: 13 mins
     .vvnvnI`    .;==|==;.     :|=||=|.         Packages: 1503 (xbps-query)
+QmQQmpvvnv; _yYsyQQWUUQQQm #QmQ#:QQQWUV$QQm.   Shell: bash 5.0.18
 -QQWQWpvvowZ?.wQQQE==<QWWQ/QWQW.QQWW(: jQWQE   Resolution: 1920x1080
  -$QQQQmmU'  jQQQ@+=<QWQQ)mQQQ.mQQQC+;jWQQ@'   WM: sway
   -$WQ8YnI:   QWQQwgQQWV`mWQQ.jQWQQgyyWW@!     CPU: Intel i5-4690K (4) @ 3.900GHz
     -1vvnvv.     `~+++`        ++|+++          GPU: AMD ATI Radeon HD 7970/8970 / R9 280X
      +vnvnnv,                 `-|===           Memory: 1266MiB / 15940MiB
       +vnvnvns.           .      :=-
        -Invnvvnsi..___..=sv=.     `
          +Invnvnvnnnnnnnnvvnn;.
            ~|Invnvnvvnvvvnnv}+`
               -~|{*l}*|~
```

ps: After startx, I can close the i3 session and logout from tty. Sound work now forever on sway.
ps2: I got an .asoundrc configured to default output to the right hdmi alsa subdevice.

**Comment by Xyene** [comment]
Sounds like your pulseaudio server isn't starting up. This is independent of Sway: you can have it start up through an init system like systemd, or add something like `exec start-pulseaudio-x11` or similar to the end of your Sway config. #sway on IRC would likely be able to assist you further if you still have issues -- this tracker is meant for things like bug reports/requests rather than questions.

**Comment by Eluminae** [comment]
I don't use pulseaudio.

The exact same config run through startx. Maybe this is unrelated to sway or wlroots but I think maybe we could do the same thing as in startx.
