### ISSUE TITLE
xdg-open from Flatpak on Sway fails

### ISSUE THREAD

**Issue by rrichardson** [swaywm/sway#5777]
### Please fill out the following:
- **Sway Version:**
  - 1.4

OS is Silverblue 32

- **Configuration File:**

Default, but with this addition to try to make xdg-open open Firefox from within a Flatpak: 

```
exec "dbus-update-activation-environment --systemd DISPLAY MOZ_DBUS_REMOTE"

```
I also have MOZ_DBUS_REMOTE=1 set in my environment. 

- **Description:**
Originally, when clicking on URLs in apps running in `flatpak` I'd get these errors: 
```
Oct 29 12:04:48 localhost.localdomain xdg-desktop-portal[4551]: Error: no DISPLAY environment variable specified
Oct 29 12:05:18 localhost.localdomain xdg-desktop-por[4515]: Failed to get application states: GDBus.Error:org.freedesktop.portal.Error.Failed: Could not get window list
Oct 29 12:09:03 localhost.localdomain xdg-desktop-portal[5368]: Error: no DISPLAY environment variable specified
Oct 29 12:09:06 localhost.localdomain xdg-desktop-portal[5390]: Error: no DISPLAY environment variable specified
``` 

It would print a new `no DISPLAY...` error every time I clicked a URL. 

I followed these directions from a related issue in `xdg-desktop-portal` https://github.com/flatpak/xdg-desktop-portal/issues/285#issuecomment-665109459  which recommended the above `dbus-update-activation-environment` line. 

After that,  I no longer got the `no DISPLAY environment ... ` log errors in xdg-desktop-portal.  
However, Firefox would still give the dreaded "Firefox not responding ... no profile .. " dialog box. 

As was explained by @hadess in https://github.com/flatpak/xdg-desktop-portal/issues/285#issuecomment-719076010 this is because the DISPLAY variable isn't registered by sway at startup, so there is no way to pipe the display through to the flatpak execution context.  

Is there another recommended approach to teach my flatpak apps how to launch URLs?

**Comment by emersion** [comment]
This isn't a Sway bug, Sway has nothing to do with systemd.

**Comment by rrichardson** [comment]
@emersion - Thanks for the update.  

So what would be the route by which flatpak apps under sway could interact with other components in the system? 

Opening URLs from within Flatpak apps works by default in mutter/Gnome, but not in sway.   Apparently mutter relies on systemd in order to get the appropriate information into dbus.   

How would this be done under sway?

**Comment by emersion** [comment]
Workaround you found can be used for third-party software that (ab)uses systemd like this.

**Comment by hadess** [comment]
> This isn't a Sway bug, Sway has nothing to do with systemd.

The problem doesn't have anything to do with systemd either. You need a way to pass the DISPLAY variable from sway (which starts XWayland) to the sibling process that starts xdg-desktop-portal (whether it's systemd, or dbus-daemon, or some session helper, it doesn't matter). You don't seem to have that mechanism.

**Comment by emersion** [comment]
This is an xdg-desktop-portal bug. It relies on being started via systemd or D-Bus activation.

**Comment by hadess** [comment]
> This is an xdg-desktop-portal bug. It relies on being started via systemd or D-Bus activation.

"D-Bus service relies on being started like a D-Bus service" shocker.

Suit yourself.

**Comment by emersion** [comment]
It's more of a "graphical app works like a D-Bus daemon" shoker.

**Comment by markstos** [comment]
> Is there another recommended approach to teach my flatpak apps how to launch URLs?

To address this, the Arch Linux package for Sway installs the following into `/etc/sway/config.d/50-systemd-user.conf`:

```
 sway does not set DISPLAY/WAYLAND_DISPLAY in the systemd user environment
# See FS#63021
# Adapted from xorg's 50-systemd-user.sh, which achieves a similar goal.

exec systemctl --user import-environment DISPLAY WAYLAND_DISPLAY SWAYSOCK
exec hash dbus-update-activation-environment 2>/dev/null && \
     dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY SWAYSOCK
```
