### ISSUE TITLE
dmenu losing focus requires clicking

### ISSUE THREAD

**Issue by kitkittia** [swaywm/sway#5789]
#### Version:
`sway version v1.5`

#### Description:
In default config `$mod+d` spawns `dmenu`. Then I can write a command, but if I lose focus mid-command I then need to click the `dmenu` bar to continue the command.

#### Improvement:
Pressing `$mod+d` again, when `dmenu` is out of focus should refocus the `dmenu` prompt or restart it. I shouldn't have to use the mouse.

**Comment by emersion** [comment]
No, we can't do that as a compsoitor. dmenu would need to figure out that an existing dmenu is in use.

**Comment by kitkittia** [comment]
Okay. Thanks for a speedy reply.
