### ISSUE TITLE
virt-manager not working

### ISSUE THREAD

**Issue by kitkittia** [swaywm/sway#5790]
- **Sway Version:**
  - `sway version v1.5`

- **Debug Log:**
  - [Here](https://gist.github.com/kitkittia/c907528b3aa69f5ce5a3a157d906884c)

- **Configuration File:**
  - Default

- **Description:**
  - Running `virt-manager` in a shell prompts for a password in Gnome, but not in Sway. Result is empty VM list.
  - Running `sudo virt-manager` gives the following error:
    ```
	Unable to init server: Could not connect: Connection refused
	No protocol specified
	Unable to init server: Could not connect: Connection refused
	No protocol specified
	Unable to init server: Could not connect: Connection refused

	(virt-manager:229663): Gtk-WARNING **: 16:15:33.985: cannot open display: :0
    ```

**Comment by emersion** [comment]
You're probably missing polkit. Add this to your config file:

```
exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
```

**Comment by wmww** [comment]
For future reference, `sudo --preserve-env=XDG_RUNTIME_DIR,WAYLAND_DISPLAY <app>` or simply `sudo -E <app>` carries through the environment variables Wayland apps need to run and allows running them as root.
