### ISSUE TITLE
Gamma isn't applied when an output is DPMS off

### ISSUE THREAD

**Issue by emersion** [swaywm/sway#5791]
1. Run a wlr-gamma-control client, like redshift
2. Turn an output off
3. The client sets a gamma
4. wlroots sets the new gamma, but Sway rollbacks that change for some reason

**Comment by Vorsplummi** [comment]
Seems to work fine after few DPMS on/off-cycles.

**Comment by crocket** [comment]
This issue has been fixed on my machine.

sway-1.5.1
wlroots-0.12.0

**Comment by emersion** [comment]
I believed https://github.com/swaywm/wlroots/pull/2630 should fix this.

**Comment by Vorsplummi** [comment]
Redshift works as it should now, thanks.
