### ISSUE TITLE
Colors from .Xdefaults

### ISSUE THREAD

**Issue by pblgomez** [swaywm/sway#5796]
In i3wm you can read the color values from .Xresources like this:
set_from_resource $bg i3wm.color0
and then read it like $bg

It doesn't seem to work in sway

**Comment by emersion** [comment]
`.Xresources` is purely an X11 thing, Sway won't support it.

**Comment by andi242** [comment]
@pblgomez if you wanted .Xresources colors you could just execute something like this:
`xrdb -query  | grep color | sed 's/*/set $/g' | sed 's/://g' > <path/to/file>/colors.conf`
this basically translates .Xresources syntax to sway syntax, given the standard *color syntax is in place or you replace the seds with a pattern that fits your needs.

add this to your sway config file:
`include <path/to/file>/colors.conf`

you may want to wrap this into a startup script to regenerate colors when sway ist started.

**Comment by pblgomez** [comment]
I have scripts to change colors for multiple apps, but in X I used to read them all from one central place like Xresources.
Now I have to use sed for every app.
In the Arch wiki I read something about wayland using Xdefaults but maybe is not.
