### ISSUE TITLE
Some applications hang during startup

### ISSUE THREAD

**Issue by luispabon** [swaywm/sway#5799]
### Please fill out the following:
- **Sway Version:**
sway version 1.5-5ae4f650 (Nov 10 2020, branch 'master')
wlroots 238d1c07 master (0.12)
Ubuntu 20.04
GDM 3.36.3

- **Debug Log:**
https://pastebin.ubuntu.com/p/GMvJsm5PNn/

This log comprises starting sway in debug mode, and wait for however long it takes Waybar to finally appear (see bug description below for the relevance of it). Then I switch to a tty and kill the sway process.

- **Configuration File:**
https://github.com/luispabon/sway-dotfiles/tree/master/configs/sway

- **Stack Trace:**
n/a

- **Description:**
Some applications freeze around 30 seconds during startup. I have the suspicion these are applications that are enumerating sound inputs and outputs, specifically Waybar, gnome-control-center and pavucontrol. I'm not sure at all how to get debug information for this.

If I logout and log back in, the problem continues. If I log out and log into gnome, the problem does not happen there, and after logging out and back into sway the problem remains.

If I downgrade sway and wlroots to 1.5 and 0.11 respectively, the problem does not occur. What's more, if I switch back to sway/wlroots master again during the same boot, the problem does not re-occur. It will start happening again only after a reboot.

I know there's not a lot of info here for anyone to sink their teeth, but I would appreciate some pointers that would help me perhaps bisect to a specific commit in sway or wlroots or maybe where to look for logs or what have you.

**Comment by luispabon** [comment]
The hang also occurs with Evolution. Perhaps it's not audio but something else like dbus?

**Comment by emersion** [comment]
Known issue: https://github.com/swaywm/sway/wiki#gtk-applications-take-20-seconds-to-start

**Comment by luispabon** [comment]
Thank you @emersion :+1:
