### ISSUE TITLE
Only Group1, not Group2 bindings are active when using more than one keyboard layout

### ISSUE THREAD

**Issue by dddlr** [swaywm/sway#5800]
### **Sway Version:**
``sway version 1.5-0df5753a (Nov  7 2020, branch 'master')``

### **Debug Log:**
https://gist.github.com/dddlr/6ecbc566d1ec6a0ea74d4f756457738b

### **Configuration File:**
https://gist.github.com/dddlr/ca76e94599d6acee9f52fd8abf18a584

### **Description:**

When using two keyboard layouts defined via ``xkb_layout``, bindings prefixed with ``Group1+`` appear to be active regardless of the current layout. On the other hand, bindings prefixed with ``Group2+`` are never active.

To reproduce the debug log:

1. Type the equivalent of Super+D in Programmer Dvorak (i.e. Super + the physical H key) to run ``i3-dmenu-desktop``. Note that Programmer Dvorak is the default keyboard layout.
2. Open termite
3. Switch keyboard layout to QWERTY using Alt+Space (which is configured in ``xkb_options``)
4. Type Super+D in QWERTY
5. ``i3-dmenu-desktop`` still runs despite the binding only being defined for Group1.

In addition:

- Super+Shift+r (defined as ``Group1+$mod+Shift+r``) works for both Programmer Dvorak and QWERTY even though it is a Group1 binding.
- Super+Shift+b (defined as ``Group2+$mod+Shift+b``) doesn't do anything regardless of whether Programmer Dvorak or QWERTY is used.

I should mention that this bug shouldn't exist due to #3662 and #4351, so I'm wondering if I'm doing something wrong here?

Thanks!

**Comment by RedSoxFan** [comment]
@dddlr Can you please try #5800?

**Comment by dddlr** [comment]
Thanks for the fix! I can confirm #5807 fixes the problem.
