### ISSUE TITLE
Wofi is not launching with newest sway

### ISSUE THREAD

**Issue by mmojzis** [swaywm/sway#5803]
# Please fill out the following:
- **Sway Version:** sway version 1.5-b42ed320 (Nov  5 2020, branch 'master')

- **Description:**
  - I updated sway and wlroots last week on ArchLinux
 - After update wofi stopped working:
 - wofi
Gdk-Message: 14:03:31.888: Error 71 (Protocol Error) dispatching to Wayland display.

When I try to run GIMP it's launched properly.

**Comment by emersion** [comment]
See https://github.com/swaywm/sway/wiki#gtk-applications-take-20-seconds-to-start

**Comment by mmojzis** [comment]
@emersion Already tried that. Other GTK applications are working for me and also wofi crashes immediately - not after 15-20 seconds.

**Comment by Geo25rey** [comment]
Try using the master brach of wofi. I think the fix was added recently.

**Comment by emersion** [comment]
If wofi crashes, it's a wofi bug.

**Comment by mmojzis** [comment]
I thought that issue comes from sway because it was working before update, but newest wofi fixed this issue. So thanks for help and sorry for spamming here.
