### ISSUE TITLE
Cursors over Xwayland windows display extra line when scaled

### ISSUE THREAD

**Issue by quantum5** [swaywm/sway#5809]
- **Sway Version:**
  - `sway version 1.5-5ae4f650 (Nov  9 2020, branch 'master')`

- **Configuration File:**
  ```
  output DP-1 pos 0 0 res 2560x1440
  output DP-2 pos 2560 0 res 3840x2160 scale 1.5
  ```
- **Description:**
  - Launch `xeyes` on `DP-2`, move the mouse over `xeyes`. On the white portion, you can see a vertical line next to the cursor:
    ![](https://user-images.githubusercontent.com/461885/99007086-7d318080-2511-11eb-83c3-faf6cae06418.png)
    This line moves with the cursor. I believe this only happens with cursor that have non-transparent pixels in the first column.

**Comment by Xyene** [comment]
Fixed in https://github.com/swaywm/wlroots/pull/2476.
