### ISSUE TITLE
grimshot filenames

### ISSUE THREAD

**Issue by eoli3n** [swaywm/sway#5817]
### Please fill out the following:
- **Sway Version:**
sway version 1.5.1

Is there a way to be able to change default screenshots filename with grimshot ?
Because i use curl to upload screenshots and default grimshot filename contains ``,`` which is problematic.
```
$ curl -F "file=@2020-11-15T16:41:25,109868379+01:00.png" 'https://x0.at/'
curl: (26) Failed to open/read local data from file/application

$ mv 2020-11-15T16:41:25,109868379+01:00.png test.png

$ curl -F "file=@test.png" 'https://x0.at/'
https://x0.at/lSy.png
```

**Comment by emersion** [comment]
We don't track issues for `contrib/` material.

**Comment by 0atman** [comment]
Where do issues go for contrib material?
