### ISSUE TITLE
Fullscreen display problem with Hybrid Graphics (intel+amd)

### ISSUE THREAD

**Issue by ytalha** [swaywm/sway#5819]
- **Sway Version:**
  - sway version 1.5.1

- **Debug Log:**
https://dpaste.com/3THNN6HW2

- **Description:**
  - Hello. I started using Sway in Artix Linux. I read the wiki and it says that if I have multi-gpu, i can start sway with "WLR_DRM_DEVICES=/dev/drm/card0:/dev/drm/card1 sway". I did that and everything was fine, until i made alacritty fullscreen with $mod+f. The screenshot doesn't show the problem so i captured my monitor with my phone. That's how full screen alacritty looks: http://0x0.st/i5mg.jpg
Also full screen imv (image viewer) looks like that too. But other applications like Firefox and Nautilus works just fine with fullscreen.
There are not any fullscreen problems if I start sway without WLR_DRM_DEVICES variable. But i want to use my computer's hardware as efficient as can it be.
I'd be very grateful if you guys help me about this problem. Thank you.

**Comment by emersion** [comment]
Which is the output you're putting a fullscreen window on? To which GPU is it wired up?

**Comment by ytalha** [comment]
> Which is the output you're putting a fullscreen window on? To which GPU is it wired up?

This problem occurs in both of my monitors. It also occurs with or without secondary monitor either.

It uses radeon gpu as its OpenGL renderer. (according to glxinfo)

 /dev/dri/card0 is radeon, /dev/dri/card1 is intel driver.

**Comment by shumvgolove** [comment]
I think this is duplicate of https://github.com/swaywm/wlroots/issues/2451 :thinking:

**Comment by ytalha** [comment]
I kinda solved this problem for myself. I added "radeon.si_support=0 radeon.cik_support=0 amdgpu.si_support=1 amdgpu.cik_support=1" commands to my GRUB_CMDLINE_LINUX variable in /etc/default/grub file. After grub update, my two graphics cards are being used without any extra configuration. And fullscreen applications are just fine.
