### ISSUE TITLE
Validating the configuration file requires XDG_RUNTIME_DIR, a valid logind session, and more

### ISSUE THREAD

**Issue by berbiche** [swaywm/sway#5823]
### Please fill out the following:
- **Sway Version:**
  - `Sway version 1.5-96578aa9 (branch 'master')`

- **Debug Log:**
  ``` console
  $ sway --config ${configFile} --validate --debug
  00:00:00.002 [backend/wayland/backend.c:269] Could not connect to remote display: No such file or directory
  00:00:00.002 [sway/server.c:50] Unable to create backend
  ```

  On newer revisions:
  ``` console
  $ sway --config ${configFile} --validate --debug
  XDG_RUNTIME_DIR is not set in the environment. Aborting.
  ```

- **Description:**
  As part of the [home-manager](https://github.com/nix-community/home-manager) project, I have integrated the feature to verify the user's Sway configuration is absent of errors when building the resulting configuration.
  The validation is run within a sandbox environment (as is the case for everything that is built with Nix, unless opting out) and lacks environment variables like `$XDG_RUNTIME_DIR`.
  This variable can be added in the builder script with no problem, I just thought it was weird to have such a dependency on `$XDG_RUNTIME_DIR` when only validating a file.

  Looking at the logs further, and I may be over my head about this, I cannot reason about the usefulness of initializing the wayland backend and the sway socket to verify the configuration file.
  I don't think the variable `$XDG_RUNTIME_DIR` should be required to validate the configuration file.

**Comment by berbiche** [comment]
It also requires a valid logind session to validate the configuration.

Once the `XDG_RUNTIME_DIR` variable is set to `$PWD` within the builder,
> ```
> builder for '/nix/store/yqrrqnc8m3f6q8cr5gbzxbikm4a2ym19-sway-config.drv' failed with exit code 1; last 10 log lines:
>   00:00:00.019 [sway/main.c:141] SWAYSOCK=(null)
>   00:00:00.019 [sway/server.c:43] Preparing Wayland server initialization
>   00:00:00.026 [backend/session/logind.c:665] User has no sessions
>   00:00:00.027 [backend/session/logind.c:724] Couldn't find an active session or a greeter session
>   00:00:00.027 [backend/session/direct.c:171] Cannot open /dev/tty: No such device or address
>   00:00:00.046 [backend/session/session.c:113] Failed to load session backend
>   00:00:00.046 [backend/backend.c:285] Failed to start a DRM session
>   00:00:00.046 [sway/server.c:49] Unable to create backend
> ```

@charvp what version of Sway was being used in the builder?

**Comment by charvp** [comment]
I was using the latest nixos-unstable-small, so 1.5.1.

**Comment by RPigott** [comment]
Related #4691

**Comment by berbiche** [comment]
I will close this issue in favor of #4691.
