### ISSUE TITLE
input identifier not valid

### ISSUE THREAD

**Issue by DiegoGuidaF** [swaywm/sway#5827]
### Please fill out the following:
- **Sway Version:**
  - 1.5-a56098a2, branch master

- **Debug Log:**
```
$ swaymsg seat seat1 attach 1241:854:DuckyChannel_International_Co.,_Ltd._Ducky_Keyboard
Error: Unknown/invalid command '_Ltd._Ducky_Keyboard'
```
Debug log prints:
https://gist.github.com/DiegoGuidaF/df23a7de538a223758be545fd06a2dca

- **Configuration File:**
Reproducible with default config file

- **Description:**
I cant configure my keyboard since the Id has a comma (,) on it.
```
$ sway -t get_inputs
Input device: DuckyChannel International Co., Ltd. Ducky Keyboard
  Type: Keyboard
  Identifier: 1241:854:DuckyChannel_International_Co.,_Ltd._Ducky_Keyboard
  Product ID: 854
  Vendor ID: 1241
  Active Keyboard Layout: Spanish
  Libinput Send Events: enabled

Input device: DuckyChannel International Co., Ltd. Ducky Keyboard Mouse
  Type: Mouse
  Identifier: 1241:854:DuckyChannel_International_Co.,_Ltd._Ducky_Keyboard_Mouse
  Product ID: 854
  Vendor ID: 1241
  Libinput Send Events: enabled

Input device: DuckyChannel International Co., Ltd. Ducky Keyboard Consumer Control
  Type: Keyboard
  Identifier: 1241:854:DuckyChannel_International_Co.,_Ltd._Ducky_Keyboard_Consumer_Control
  Product ID: 854
  Vendor ID: 1241
  Active Keyboard Layout: Spanish
  Libinput Send Events: enabled

Input device: DuckyChannel International Co., Ltd. Ducky Keyboard System Control
  Type: Keyboard
  Identifier: 1241:854:DuckyChannel_International_Co.,_Ltd._Ducky_Keyboard_System_Control
  Product ID: 854
  Vendor ID: 1241
  Active Keyboard Layout: Spanish
  Libinput Send Events: enabled

Input device: DuckyChannel International Co., Ltd. Ducky Keyboard
  Type: Keyboard
  Identifier: 1241:854:DuckyChannel_International_Co.,_Ltd._Ducky_Keyboard
  Product ID: 854
  Vendor ID: 1241
  Active Keyboard Layout: Spanish
  Libinput Send Events: enabled

```

I have tried quoting the input id with "" or '' and the issue persists. I also tried cutting the Id up to the first comma and still doesn't work.
Same issue if I try to edit input settings, ie:
`swaymsg input 1241:854:DuckyChannel_International_Co.,_Ltd._Ducky_Keyboard repeat_delay 1`

**Comment by TheAvidDev** [comment]
Have you tried escaping the comma with `\,`?

**Comment by emersion** [comment]
Please try

```
swaymsg "input '1241:854:DuckyChannel_International_Co.,_Ltd._Ducky_Keyboard' repeat_delay 1"
```

**Comment by DiegoGuidaF** [comment]
> Have you tried escaping the comma with `\,`? (possibly alongside quoting)

Couldn't get this to work, neither:
´swaymsg input "1241:854:DuckyChannel_International_Co.\,_Ltd._Ducky_Keyboard" repeat_delay 800´
nor
´swaymsg input 1241:854:DuckyChannel_International_Co.\,_Ltd._Ducky_Keyboard repeat_delay 800´

> Please try
> 
> ```
> swaymsg "input '1241:854:DuckyChannel_International_Co.,_Ltd._Ducky_Keyboard' repeat_delay 1"
> ```
This does indeed work! Got to say it is weird that I need the double quotation.

Thank you!

**Comment by kpe** [comment]
I've just noticed that the identifier returned by 
```bash
$ swaymsg -t get_inputs

[
...
{
    "identifier": "2:14:ETPS\/2_Elantech_TrackPoint",
     ...
},
...
]
```
is escaping `/` with an `\` which needs to be omitted in the `~/.config/sway/config` in order has an effect, i.e. it has to be written like this in the `config`:
```
input "2:14:ETPS/2_Elantech_TrackPoint" {
...
}
```

Its probably not intended having different identifiers, but just the result of `swaymsg -t get_inputs` return escaped json strings, while the `config` file expecting "normal"/non-escaped strings.
