### ISSUE TITLE
Lately, hot-plugging monitors rarely works

### ISSUE THREAD

**Issue by nmschulte** [swaywm/sway#5828]
Using swaywm/sway@f5ca4c26acdd65aa6e7f2c2eb83f54e13323c403 with swaywm/wlroots@526ae5944c5cc97e02f0282c57ce7320ceb2daa5, monitors connected after starting sway rarely work, though `drm_info` seems to indicate a change.  I have tried other versions as well, though less recently and with less thorough testing, including v1.5/0.11.0 as packaged in Debian Sid, v1.5.1/0.12.0 built from source, and various other combinations of the two projects.

The machine I'm testing on is a laptop, a Dell Precision Workstation 7510 running Debian Sid.  It has a hybrid graphics setup with Intel Iris Pro Graphics P580 and AMD FirePro W5170M, using `i915` and `radeon` open source drivers.  The machine has a 4K embedded DisplayPort screen, a Thunderbolt 3 port, a mini DisplayPort (DP++), and an HDMI port (which appears to also be a DP++ port), and a docking port on the underside.  Additionally, the machine seems to support a fully switchable graphics matrix, though I'm uncertain how it is configured (_and am grateful for any support in better understanding how to best configure the hybrid nature of this machine; I have been using it naively for quite some time with i3/X11 and manually setting `DRI_PRIME` and `xrandr --setprovideroffloadsync`, recently switching to sway/Wayland_).

Attached are two sets of diagnostic, one where the monitor works ("good") and another where it does not ("bad"), both following this procedure:
1. Cold boot the machine with no attached peripherals other than the power adapter.
2. Start `sway` from tty1 via `sway -d 2> sway.log`.
3. Start `urxvt` via keybinding (`exec urxvt`).
4. Capture `drm_info` output from sway session via `drm_info > drm_info.before`.
5. Connect monitor to HDMI port (HDMI -> DVI cable); wait some time.
6. Capture `drm_info` output from sway session via `drm_info > drm_info.after`.
7. Shutdown the machine via keybinding (`exec "systemctl poweroff -i"`).

My tests were not performed with the default configuration, though this can be performed.  I can also share my configuration, though it needs sanitization.

The "good" log includes this message not present in the "bad" log: `udev event for card1 (change)`
When viewing the logs, grep for `running command for binding: exec urxvt`, both around the 6.44s timestamp.

[good.sway.log](https://github.com/swaywm/sway/files/5564049/good.sway.log)
[good.drm_info.before.log](https://github.com/swaywm/sway/files/5564052/good.drm_info.before.log)
[good.drm_info.after.log](https://github.com/swaywm/sway/files/5564053/good.drm_info.after.log)

[bad.sway.log](https://github.com/swaywm/sway/files/5564054/bad.sway.log)
[bad.drm_info.before.log](https://github.com/swaywm/sway/files/5564055/bad.drm_info.before.log)
[bad.drm_info.after.log](https://github.com/swaywm/sway/files/5564056/bad.drm_info.after.log)

Possibly this problem is not sway's fault, as I have other issues with this machine lately (the embedded display used to have many more modes than the only the 4K resolution), but this is all I have to start with.  Any help and guidance is very much appreciated.

**Comment by emersion** [comment]
>The "good" log includes this message not present in the "bad" log: udev event for card1 (change)

If the kernel doesn't send us a udev hotplug event, we can't detect the connector changes. This sounds like an issue lower down the stack.

**Comment by nmschulte** [comment]
> This sounds like an issue lower down the stack.

I agree, but I don't know where else to begin.

I've done some more investigation looking at `journalctl -fx` output and `udevadm monitor` output.  I found that when udev change events are not issued, I can switch to tty2 and after a short period the attached display changes from black to show a corrupted image (see attached), at which point it seems the udev change events are triggered.  Switching back to tty1 (sway session), the connected monitor is recognized and can be enabled.

Running `drm_info` has no effect in that it does not cause the udev events to trigger, though it does show the changed connector information.

As well, I receive messages like these in the `journalctl` log (from switching ttys), which I'm guessing indicates an (power management?) issue with the `radeon` driver:
```Nov 19 10:59:39 desmas-l kernel: [drm] PCIE gen 3 link speeds already enabled
Nov 19 10:59:39 desmas-l kernel: [drm] PCIE GART of 2048M enabled (table at 0x00000000001D6000).
Nov 19 10:59:39 desmas-l kernel: radeon 0000:01:00.0: WB enabled
Nov 19 10:59:39 desmas-l kernel: radeon 0000:01:00.0: fence driver on ring 0 use gpu addr 0x0000000080000c00
Nov 19 10:59:39 desmas-l kernel: radeon 0000:01:00.0: fence driver on ring 1 use gpu addr 0x0000000080000c04
Nov 19 10:59:39 desmas-l kernel: radeon 0000:01:00.0: fence driver on ring 2 use gpu addr 0x0000000080000c08
Nov 19 10:59:39 desmas-l kernel: radeon 0000:01:00.0: fence driver on ring 3 use gpu addr 0x0000000080000c0c
Nov 19 10:59:39 desmas-l kernel: radeon 0000:01:00.0: fence driver on ring 4 use gpu addr 0x0000000080000c10
Nov 19 10:59:39 desmas-l kernel: radeon 0000:01:00.0: fence driver on ring 5 use gpu addr 0x0000000000075a18
Nov 19 10:59:39 desmas-l kernel: radeon 0000:01:00.0: fence driver on ring 6 use gpu addr 0x0000000080000c18
Nov 19 10:59:39 desmas-l kernel: radeon 0000:01:00.0: fence driver on ring 7 use gpu addr 0x0000000080000c1c
Nov 19 10:59:40 desmas-l kernel: [drm] ring test on 0 succeeded in 1 usecs
Nov 19 10:59:40 desmas-l kernel: [drm] ring test on 1 succeeded in 1 usecs
Nov 19 10:59:40 desmas-l kernel: [drm] ring test on 2 succeeded in 1 usecs
Nov 19 10:59:40 desmas-l kernel: [drm] ring test on 3 succeeded in 9 usecs
Nov 19 10:59:40 desmas-l kernel: [drm] ring test on 4 succeeded in 3 usecs
Nov 19 10:59:40 desmas-l kernel: [drm] ring test on 5 succeeded in 2 usecs
Nov 19 10:59:40 desmas-l kernel: [drm] UVD initialized successfully.
Nov 19 10:59:40 desmas-l kernel: [drm] ring test on 6 succeeded in 13 usecs
Nov 19 10:59:40 desmas-l kernel: [drm] ring test on 7 succeeded in 4 usecs
Nov 19 10:59:40 desmas-l kernel: [drm] VCE initialized successfully.
Nov 19 10:59:40 desmas-l kernel: [drm] ib test on ring 0 succeeded in 0 usecs
Nov 19 10:59:40 desmas-l kernel: [drm] ib test on ring 1 succeeded in 0 usecs
Nov 19 10:59:40 desmas-l kernel: [drm] ib test on ring 2 succeeded in 0 usecs
Nov 19 10:59:40 desmas-l kernel: [drm] ib test on ring 3 succeeded in 0 usecs
Nov 19 10:59:40 desmas-l kernel: [drm] ib test on ring 4 succeeded in 0 usecs
Nov 19 10:59:41 desmas-l kernel: [drm] ib test on ring 5 succeeded
Nov 19 10:59:41 desmas-l kernel: [drm] ib test on ring 6 succeeded
Nov 19 10:59:42 desmas-l kernel: [drm] ib test on ring 7 succeeded
Nov 19 10:59:42 desmas-l kernel: radeon_dp_aux_transfer_native: 200 callbacks suppressed
```
```
Nov 19 10:59:51 desmas-l kernel: radeon_dp_aux_transfer_native: 116 callbacks suppressed
Nov 19 10:59:51 desmas-l kernel: [drm:si_dpm_set_power_state [radeon]] *ERROR* si_restrict_performance_levels_before_switch failed
```
```
Nov 19 11:00:35 desmas-l kernel: radeon_dp_aux_transfer_native: 242 callbacks suppressed
```

I execute `swayidle` via sway config like so (note I have stopped using `dpms` with `swayidle` a while back, as apparently it was causing issues...):
```
exec swayidle -w \
    timeout 900 $lockCommand \
    before-sleep $lockCommand
#exec swayidle -w \
#    timeout 900 $lockCommand \
#    timeout 930 'swaymsg "output * dpms off"' \
#        resume 'swaymsg "output * dpms on"' \
#    before-sleep $lockCommand
```
I will test the effects of starting sway with only the i915 card enabled, and vice-versa, and also the effects of the BIOS configurations regarding the hybrid/switchable graphics.

![0](https://user-images.githubusercontent.com/8540239/99701851-a0e94f00-2a5a-11eb-8438-95b13f948035.jpg)

**Comment by nmschulte** [comment]
> I will test the effects of starting sway with only the i915 card enabled, and vice-versa, and also the effects of the BIOS configurations regarding the hybrid/switchable graphics.

Of course `WLR_DRM_DEVICES=/dev/dri/card0 sway` (i915, integrated) and `WLR_DRM_DEVICES=/dev/dri/card1 sway` (radeon, discrete) have the intended and expected effect: sway launches on the laptop screen (card0), or the connected monitor (card1).

Changing the switchable graphics configuration so the connectors are directed to the i915/integrated card mitigates the issue I'm describing, and the connected monitor is seemingly always recognized (udev events always issued).  That is, disabling the "Discrete Graphics Controller Direct Output Mode" in the BIOS.

![0](https://user-images.githubusercontent.com/8540239/99703894-47365400-2a5d-11eb-9042-fbbf6f0b35ab.jpg)

Where should I report this behavior if sway is not the correct place or source of the problem?

**Comment by emersion** [comment]
https://gitlab.freedesktop.org/drm/amd/-/issues
