### ISSUE TITLE
Add ppt unit to move position command

### ISSUE THREAD

**Issue by MetaDark** [swaywm/sway#5837]
### Please fill out the following:
- **i3 PR:** https://github.com/swaywm/sway/pull/5546

- **Description:**
i3 has recently added support for the ppt unit on the move position command. I would use this feature specifically to position a Firefox Picture-in-Picture window to the bottom right of my screen:

```i3
for_window [title="Picture-in-Picture"] floating enable, sticky enable, border pixel 0, move position <x> ppt <y> ppt
```

**Comment by Xyene** [comment]
I'm not sure I understand this ticket...

Your link is to a Sway PR, not an i3 one. I assume you meant https://github.com/i3/i3/pull/4189. The PR you linked implements this behavior in Sway, and was merged back in July (ahead of the i3 PR) &mdash; `swaymsg move position <x> ppt <y>ppt` works as advertised for me.

**Comment by MetaDark** [comment]
Oh wow sorry, I was being dumb. I thought I was looking into the i3 repo when I found the PR :sweat_smile:. I'm using sway 1.5.1, and wasn't available, but master has it.
