### ISSUE TITLE
Feature request: A way to execute a command before other `exec` commands run

### ISSUE THREAD

**Issue by mortie** [swaywm/sway#5841]
There are situations where you want some commands to run when sway launches (launcher, swayidle, applets, ...), but where some setup needs to be done before such commands can execute. One example is systemd user environment variables which must be set before certain applications launch. Consider the following example:

1. I want some GNOME application (such as the Nextcloud sync client, which uses the GNOME keyring) to run when Sway starts. I add `exec nextcloud` to my Sway config.
2. The application tries to access the xdg-desktop-portal d-bus server (`org.freedesktop.portal.Desktop`).
3. `xdg-desktop-portal-gtk` launches as a d-bus activated service.
4. Because systemd doesn't have a way to know what Sway set the `WAYLAND_DISLAY` environment variable to be, `xdg-desktop-portal-gtk` is unable to connect to Sway and everything breaks.

The solution is to run `systemctl --user import-environment WAYLAND_DISPLAY` in a context where the WAYLAND_DISPLAY env var is set by Sway. However, currently, people will just add `exec systemctl --user import-environment WAYLAND_DISPLAY` to their Sway config files, and either rely on systemctl winning the race, or explicitly do `exec sleep 2 && whatever` for every application which relies on the previous `systemctl` command. Neither solution is great, both solutions are open for race condition issues (though the second solution less so).

I have used the systemd environment as an example here, but it's by no means the only case where this is a problem. I think you would have the same kind of race condition with gsettings commands; I have `exec gsettings set org.gnome.desktop.interface gtk-theme 'Yaru'` in my config file too, and this would also race against any GTK applications executed by the `exec` command.

---

I hope I've made a clear case for the need to have some concept of a setup command, executed by Sway with environment variables set by Sway, which blocks execution of other programs until the setup command is complete. I have some ideas on how to solve this, but I'm not sure which is better. The solutions I can think of are:

1. Add an `exec_setup` command, with the idea that every process spawned by `exec_setup` has exited before any `exec` or `exec_always` commands execute.
2. Write an external tool (swaywait?) which ensures ordering. I'm imagining a config file which has one line, `exec swaywait --block systemctl --user import-environment WAYLAND_DISPLAY`, and another line, `exec swaywait nextcloud`. I'm not 100% sure how one would implement such a program, but I'm sure it's possible.
3. Build in a whole dependency graph system, where commands can depend on each other arbitrarily. I don't see this option as very realistic.
4. Acknowledge that this issue exists, but don't solve it. GTK applications will probably be so slow to launch anyways that any systemctl and gsettings commands have long completed by the time GTK gets ready, and if not, you can always add a sleep. I don't like this solution very much, but it has, arguably, worked thus far.

I have to admit, I kind of like solution 2. I get that Sway isn't a process manager; it forks, execs, and forgets about it. Technically, it wouldn't even need to be an official Sway program, though I think it would be best if Sway provided an official solution to the problem (like it does with swaybg, which also doesn't technically need to be a Sway program).

---

It's worth noting that this has recently become a bigger problem. Sway recently changed the default WAYLAND_DISPLAY value from wayland-0 to wayland-1. This means that a lot of previously broken-yet-functional setups will now no longer work at all (or, as was the case with me, every GTK application will take 30 seconds to start waiting for the d-bus timeout). I like that previously subtly broken setups are now obviously broken, and agree with the change, but it means that more people will soon start looking for ways to fix this issue.

**Comment by RPigott** [comment]
This doesn't seem to me like the kind of thing that should be handled in sway. If you want your commands to be executed one after another, the 5th, and best, solution is to put them in a script that will do just that and exec the script instead. If you need the power of a shell, use one.

Ideally your daemons would be resilient to being exec'd in the wrong order in the first place, but either way I don't think any changes are needed in sway.

**Comment by emersion** [comment]
If you need to execute commands in a pre-defined order, use a script.

**Comment by mortie** [comment]
I have to point out that Sway's own FAQ recommends putting `exec systemctl --user import-environment DISPLAY WAYLAND_DISPLAY SWAYSOCK` in the config: https://github.com/swaywm/sway/wiki#gtk-applications-take-20-seconds-to-start. This FAQ entry should probably at least point out that if you start _any other GTK or GNOME-related programs at startup_, you should do that via a script which ensures that the systemctl command exits before the other processes launch.

I just did a test, and it doesn't seem like at least Ubuntu's set-up handles things being exec'd in the wrong order. If I launch, for example, nautilus, while the environment variables are incorrect, then run the systemctl command to import env vars, the systemctl command has no effect and the nautilus launch remains slow.

**Comment by Geo25rey** [comment]
I could see a --wait-until-exit flag for the exec command and it wouldn't be too hard to implement

**Comment by georglauterbach** [comment]
@mortie did you find a nice solution to the problem? I am dealing with this myself now..
