### ISSUE TITLE
Claws-Mail (gtk3) fails to start

### ISSUE THREAD

**Issue by andyrtr** [swaywm/sway#5842]
Claws-Mail (gtk3 - 3.99.0 beta release) refuses to start under sway here.

Sway Version is 1.5.1 using Arch Linux.
Debug Log: [sway.log](https://github.com/swaywm/sway/files/5604995/sway.log)

It happens with my local dualhead dektop system(radeon card) as well as on my notebook (integrated intel gpu). It happens with my custom and with default config.

I cannot manage to run claws-mail gtk3 version while the gtk2 release runs well under sway. The gtk3 version works well under i3wm but always crashes in swaywm.

Log when starting Claws-Mail from terminal: [claws.log](https://github.com/swaywm/sway/files/5605016/claws.log)

Claws developers can't confirm this because none of them runs a wayland desktop and no swaywm.

Is there anything else I can offer how to find out why it's crashing?

**Comment by emersion** [comment]
If a client crashes, it's a client bug.
