### ISSUE TITLE
Proposal: windows with opacity can get alpha blended with custom image

### ISSUE THREAD

**Issue by iwikal** [swaywm/sway#5845]
**Description:**
I would like an option that makes windows with opacity get alpha blended over a custom image texture, instead of whatever is actually behind them at that time.

**Use case**
Since swaywm is (has?) a tiling window manager, I very rarely have windows on top of others. With this feature, I could fake a gaussian blur effect by pre-rendering a blurred version of my wallpaper, and have that be shown through the transparent windows instead of the background. This idea was inspired by remembering that the Aero theme first seen in Windows Vista had a lite-mode that would show some glassy, blurry image through transparent parts of the window decorations, instead of running a blurring algorithm in real time, for people who didn't have the performance to spare.

**Comment by emersion** [comment]
Sorry, we're not interested in eye-candy features like this. If we ever get support for this, will probably be via https://github.com/swaywm/sway/issues/3652.
