### ISSUE TITLE
Sway isn't working with nouveau (laptop)

### ISSUE THREAD

**Issue by Diegovsky** [swaywm/sway#5849]
- **Sway Version:**
  - sway version 1.5-32b93ef6

- **Debug Log:**
  - Nouveau: https://gist.github.com/Diegovsky/ccf17408d8f3fe6d5680d8fdf9ec9077
  - Nvidia blob: https://gist.github.com/Diegovsky/fea9fdd74ab9ef78721353ef9318ce90

- **Description:**
  Firstly, I started using sway with the proprietary drivers because I thought Nouveau didn't work with laptops. When I first ran sway, I noticed it wasn't detecting my external monitor, which X does, but still has some problems. I then started to write an issue, when I had the idea to install the nouveau driver as nvidia's doesn't play nicely with Linux and it isn't supported here. Unexpectedly, sway stopped working.

**Comment by RPigott** [comment]
Looks like swaywm/wlroots#2480. It should work if you completely uninstall the nvidia driver.

Otherwise you need [this libglvnd patch](https://gitlab.freedesktop.org/glvnd/libglvnd/-/merge_requests/235) to start sway with the nvidia driver installed.

**Comment by Diegovsky** [comment]
It was exactly as you said. Upon installing libglvnd from git, sway ran flawlessly, but after a minute or so a there was a segfault. Should I open a new issue or reopen this one?
