### ISSUE TITLE
Infinite transaction loop

### ISSUE THREAD

**Issue by RPigott** [swaywm/sway#5857]
In quick resize operations, some clients can get stuck in an infinite transaction loop where sway will send constant configure events. This bug was also introduced by #5812. Programming is hard.

Steps to reproduce:

1. Float a slow-reacting client, e.g. slow-ack
2. `swaymsg '[con_mark=slow]' resize shrink width 40px && swaymsg '[con_mark=slow]' resize grow width 20px`
3. Observe it transform back-and-forth between sizes.

Note the use of && instead of comma separator in swaymsg. Alternatively, it's pretty easy to accidentally trigger with an interactive resize. I can't reproduce this with termite, but I can with the imv image viewer.

I noticed that when the client is in this loop, it somehow always has the wrong configure serial (an old one) to offer transaction_notify_view_ready_by_serial, so that function never does anything.

**Comment by kennylevinsen** [comment]
I suppose one could make an argument for never, or only once, sending a configure with size to floating windows. Just draw what size they give us and call it a day.

**Comment by emersion** [comment]
Yeah, that sounds reasonable. Unless the user resizes the window, in case we really need to send a configure.

Figuring out which case it is (extraneous configure, or manual configure) may be an issue.

**Comment by tadeokondrak** [comment]
Not sure if this is the same issue or not, but #5812 causes weston-terminal floating windows to forever grow in height on their own for me.

**Comment by kennylevinsen** [comment]
> Yeah, that sounds reasonable. Unless the user resizes the window, in case we really need to send a configure.

Only if it's a server-side resize, right?

> Figuring out which case it is (extraneous configure, or manual configure) may be an issue.

I was thinking of setting a sticky bit on the container state when we are doing server-initiated resizing, which would cause the transaction logic to send a configure. The bit would be cleared in the pending state when setting up the transaction.

There's only two locations that would be exempt from setting this bit (xwayland and xdg_shell commit), and only for floating windows.
