### ISSUE TITLE
Sway & XWayland end up in endless loop consuming 100% CPU each

### ISSUE THREAD

**Issue by sochotnicky** [swaywm/sway#5859]
### Please fill out the following:
- **Sway Version:**
1.5.1

- **Debug Log:**

I uploaded last minutes before I killed sway. It's not a complete log - I filtered out IPC replies to keep it sane and somewhat more private. 

What is also missing is the fact that towards the end there were millions of following lines:
`_XSERVTransSocketUNIXAccept: accept() failed`

I had to strip them - the log would be several GB big otherwise. 

[.sway.stderr.log.filtered.log](https://github.com/swaywm/sway/files/5643790/default.sway.stderr.log.filtered.log)

- **Configuration File:**
- TODO - not sure it's important here

- **Description:**

There are a few similar issues in github but nothing exactly like this so I figured I'd file a separate one. 

I have swayidle setup to lock screen & later dpms. On wakeup the screen comes on but sway accepts no input. 

I sshed into the machine using another computer and saw that both sway & XWayland were consuming 100% CPU. If I killed XWayland it would be re-spawned and continue consuming 100% CPU.

Sway does not actually crash - it stops processing input or anything however and swaylock can't be unlocked. Killing swaylock from another tty gets a semi-working sway where "old" windows do not accept input (but if I spawn a new terminal it works fine).

The debug log contains several smoking guns. For example there's:
`
5:53:17.468 [INFO] [wayland] error marshalling arguments for keymap: dup failed: Too many open files
`
Or
`
45:53:17.836 [sway/desktop/transaction.c:379] Transaction 0x5646dd3c0460 timed out (2 waiting)
45:53:17.836 [sway/desktop/transaction.c:281] Applying transaction 0x5646dd3c0460
45:53:17.849 [sway/desktop/transaction.c:414] Transaction 0x5646dda71cd0 committing with 7 instructions
`
But it's not quite clear where to look/debug this further.

**Comment by sochotnicky** [comment]
I updated to Xorg 1.20.10 - there's few fixes that might be related perhaps... We'll see in a few days

**Comment by d4g** [comment]
Could be related to #5592 ?
I just can confirm the message flood of
```
grep '_XSERVTransSocketUNIXAccept: accept() failed' sway_segaufault_debug.log_1607091437 | wc -l
3676618
```

**Comment by sochotnicky** [comment]
Yeah, maybe it makes sense to close this as duplicate though in my case - this really has nothing to do with reloads etc (as mentioned in some comments in the other issue - it could just be a trigger).

In my case - it didn't seem like sway would crash until it would fill the drive :-)
```
$ grep '_XSERVTransSocketUNIXAccept: accept() failed'  .sway.stderr.log | wc -l 
105246785
```

For me updating to XOrg 1.20.10 did not help - it just happened again though there was a crash. I have 2 XWayland apps generally running:
 * Spotify
 * Synology Drive 

For now I'll not use them and see if it helps with crashes...

**Comment by sochotnicky** [comment]
FWIW, I can no longer reproduce this even with XWayland running anymore on recent wlroots & sway so closing the issue. Will comment in the other one for people to re-check as well.
