### ISSUE TITLE
Sway uses software renderer rather than Nouveau & NVIDIA 980Ti

### ISSUE THREAD

**Issue by sseneca** [swaywm/sway#5864]
- **Sway Version:**
  - sway version 1.5.1

- **Debug Log:**
  - https://gist.github.com/sseneca/dc0299c814ff5529ca13b2573df8f1bd

- **Configuration File:**
  - https://gist.github.com/sseneca/566c4ab72384d72dba29a1faca4df1a6

- **Description:**

I have an NVIDIA 980Ti, which I figured I'd try with Sway & Nouveau. However, things are laggy, and looking at the logs (in the above gist):

```
00:00:00.040 [INFO] [render/gles2/renderer.c:674] Using OpenGL ES 3.2 Mesa 20.2.3
00:00:00.040 [INFO] [render/gles2/renderer.c:675] GL vendor: Mesa/X.org
00:00:00.040 [INFO] [render/gles2/renderer.c:676] GL renderer: llvmpipe (LLVM 11.0.0, 256 bits)
```

Sway uses a software renderer. This was surprising to me since the 980Ti is such an old card, and I thought the older cards were generally better supported. According to [here](https://nouveau.freedesktop.org/CodeNames.html#NV110), the card is in the NV110 family (Maxwell), and according to the Nouveau [feature matrix](https://nouveau.freedesktop.org/FeatureMatrix.html), `video decoding accel` is not supported but the rest is. Not sure if this means it should work or not. The module is loaded, afaict.

I also noticed this, just above that snippet:

```
00:00:00.007 [INFO] [backend/drm/backend.c:138] Initializing DRM backend for /dev/dri/card0 (nouveau)
00:00:00.007 [DEBUG] [backend/drm/drm.c:66] Atomic modesetting unsupported, using legacy DRM interface
00:00:00.007 [INFO] [backend/drm/drm.c:255] Found 4 DRM CRTCs
00:00:00.007 [INFO] [backend/drm/drm.c:176] Found 12 DRM planes
nvc0_screen_create:1046 - Base screen init failed: -19
```

**Comment by progandy** [comment]
The log mentions Parabola, so you probably do not have linux-firmware installed. The nvidia cards require firmware blobs to unlock all functions, even with the nouveau driver.

**Comment by sseneca** [comment]
Ah, yeah I don't have `linux-firmware`. So there's no way to use the card with Sway on Parabola (i.e., with only free software)? If not, then I guess only the very old cards work with 100% free software, since the 980Ti itself is also quite old at this point.

**Comment by emersion** [comment]
Closing because all of the driver selection logic is in Mesa. Report a Mesa bug if the right driver isn't selected.

**Comment by progandy** [comment]
Look in your distro support forum if you use 100% libre (or those of other libre distros). They should know more about what works that way. For example: https://trisquel.info/en/forum/newest-desktop-gpu-works-trisquel

**Comment by sseneca** [comment]
@emersion Could be mistaken but I'm pretty sure it's selecting the correct driver first, and only switching to software rendering when it gets the aforementioned `nvc0_screen_create:1046 - Base screen init failed: -19` error.

**Comment by sseneca** [comment]
@progandy Thank you. According to [this thread](https://lists.parabola.nu/pipermail/assist/2020-September/001561.html), the 750 Ti is the newest card that doesn't require the binary blob. I'll switch back to using my CPU's iGPU.
