### ISSUE TITLE
focus_wrapping workspaces will wrap focus

### ISSUE THREAD

**Issue by ahmadie** [swaywm/sway#5866]
focus_wrapping no: will stop focus wrapping
focus_wrapping workspace: can only focus inside a workspace but focus will wrap

Can we have a new option where the focus is only restricted by the current workspace and without wrapping? eg. I would like to restrict focus to the current workspace, but also does not wrap.

**Comment by emersion** [comment]
Sorry, we're not implementing any new window management features unless i3 implements them too. Please consider searching for or opening an i3 feature request.
