### ISSUE TITLE
Enable Discussions to provide some recipes for Sway integrations with DM's and Swaylock/idle

### ISSUE THREAD

**Issue by dzintars** [swaywm/sway#5869]
Hi all.
First of all, GitHub introduced a new feature "Discussions" [docs.github.com](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/about-team-discussions) which could be helpful to provide some "How-to's" and other unrelated to the actual issues discussions. It would be nice to enable it there.

Second:
As Sway homepage states, it's a "drop-in" replacement for the i3. In the i3 as for a simple user i had no issues to use i3lock, with some fancy blur effects and what not. As user i was expecting that i can get same "drop-in" features in the Sway as well. But, turns out it's not the "simple user" case as there are some Wayland security restrictions, some opinionated Sway features and so on.

It would be great if someone could provide a simple and idiomatic recipe to enable:

1) Lock the screens after period of inactivity (swaylock/swaylock-effects) (+ proper display orientation handling).
2) Turn off the all displays after some period of time + mby put the pc in the sleep mode.
3) Wake up all the screens after some/any key press, mouse move or other triggers (AMD).
4) Show the GDM. Because for a simple user it's a nice to have human friendly login screen. It could be other Wayland DM as well.

There are other welcome recipes as well. Like:

1) Printscreen handling in simple human friendly way (besides slurp and grim)
2) Screen sharing in simple human friendly way with OBS and other software.

This is why GH Discussions would be helpful there to build such knowledge base/'go-to' reference without cluttering the Issues.

**Comment by emersion** [comment]
>First of all, GitHub introduced a new feature "Discussions" docs.github.com which could be helpful to provide some "How-to's" and other unrelated to the actual issues discussions. It would be nice to enable it there.

We already have IRC and the wiki ofr this kind of things. I'm not sure adding another "official" medium is a good idea.

>As Sway homepage states, it's a "drop-in" replacement for the i3.

It's a drop-in replacement for i3, not for i3lock and whatever other X11-specific tools you were using before.

**Comment by dzintars** [comment]
For sure i have no single rights to argue there, but IMO chat is really bad knowledge base medium and is one more tool (read block) which "simple users" should learn to use. Chat messages come and go. Not searchable. Constant repeating of the same questions. And so on.
Wiki is maintained and moderated by the repo owners, so simple users (in a simple way) basically can't make any influence/improvements just because have no rights or does not match the opinions of the repo owners.
StackOverflow is one more unrelated medium without Sway specific community.
GH Issues is not tailored for these king of things.

I was talking more from the end-user perspective where the general context is Sway.
From this perspective, as soon as you swap the i3 for the Sway, you immediately hit the entirely new world. Not because of solely Sway, more like because of Wayland. But Wayland is too low level for the casual users. So Sway could serve as the host to find different recipes to do the things which was done in X11 i3.

I am totally not complaining there at all. And i am able to Google the things i want to do.
My intention/idea was to make Sway more user accessible. Ability to go to the repo and find all the answers there and you don't need to waste hours or days googling gazillion of medium posts (btw - not so many there), browsing other GH repos and what not.
Discussions would allow for the users to build the knowledge base incrementally without pinging the maintainers. Link to the commits, issues. Would give some feedback for the maintainers about the popular questions, etc. Like in SO, but in the same single location.

**Comment by emersion** [comment]
>Chat messages come and go. Not searchable. Constant repeating of the same questions.

Yes, chat is ephemeral by design.

>Wiki is maintained and moderated by the repo owners, so simple users (in a simple way) basically can't make any influence/improvements just because have no rights or does not match the opinions of the repo owners.

No, the wiki is community-maintainer.

>GH Issues

GitHub issues are only for bug reports and feature requests indeed.
