### ISSUE TITLE
sway crash when trying to start intellij

### ISSUE THREAD

**Issue by hypergig** [swaywm/sway#5888]
### sway
sway version 1.4

### ubuntu
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

### intellij
intellij-idea-ultimate
2020.3  263

## Description
First Intellij closes with the warning of `WARN - com.intellij.ide.IdeEventQueue - Too many mouse clicks (28)!!!`, then upon reopening it sway hard crashed. No repro steps as it happens uninstigated. 

## Configuration
_Very minimal as I am in the middle of transitioning_
https://github.com/hypergig/workstation/pull/4/files?file-filters%5B%5D=.config

### Relevant Snippet
```
(EE) failed to write to XWayland fd: Broken pipe

(wofi:194502): Gtk-WARNING **: 17:37:25.883: Theme file for DMZ-Black has no directories
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
2020-12-15 17:37:29,509 [    476]   WARN - llij.ide.plugins.PluginManager - Resource bundle redefinition for plugin 'com.microsoft.tooling.msservices.intellij.azure'. Old value: com.microsoft.intellij.ui.messages.messages, new value: com.microsoft.intellij.hdinsight.messages.messages
thread 'thread 'thread 'thread 'mainmainmainmain[2020-12-15 17:37:29.547] [error] Window: Unable to receive IPC header
' panicked at '' panicked at '' panicked at '' panicked at 'failed to read wayland events: Broken pipe (os error 32)failed to read wayland events: Broken pipe (os error 32)failed to read wayland events: Broken pipe (os error 32)[2020-12-15 17:37:29.547] [error] Window: Unable to receive IPC header
failed to read wayland events: Broken pipe (os error 32)', ', ', ', <::std::macros::panic macros>[2020-12-15 17:37:29.547] [error] Window: Unable to receive IPC header
<::std::macros::panic macros><::std::macros::panic macros><::std::macros::panic macros>::[2020-12-15 17:37:29.547] [error] Window: Unable to receive IPC header
::[2020-12-15 17:37:29.547] [error] Window: Unable to receive IPC header
5555::[2020-12-15 17:37:29.547] [error] Window: Unable to receive IPC header
::6666[2020-12-15 17:37:29.547] [error] Window: Unable to receive IPC header
```
### More context
[sway.log](https://github.com/swaywm/sway/files/5699149/sway.log)

**Comment by emersion** [comment]
Please provide a stack trace. You can do so by compiling from source, reproducing the crash and then running `coredumpctl gdb` and then `bt full`.

Here are some instructions to compile from source: https://github.com/swaywm/sway/wiki/Development-Setup#compiling-as-a-subproject

**Comment by hypergig** [comment]
Sounds good. I will take a look this weekend.

**Comment by Xyene** [comment]
Closing this ticket due to inactivity; feel free to reopen with logs if you are able to reproduce the crash on sway/wlroots master.
