### ISSUE TITLE
workspace {prev,next}_on_output --create is undocumented

### ISSUE THREAD

**Issue by RPigott** [swaywm/sway#5913]
`workspace prev_on_output --create` and `workspace next_on_output --create` are implemented in sway and not i3. The `--create` flag is not mentioned in the sway(5) man page.

Also, with numbered workspaces 1, 2, and 4 open, executing a `workspace next_on_output --create` with workspace 4 focused creates an empty workspace 3 (I expected 5), and does not focus it (almost certainly a bug). So that case may need some clarification.

Added in #3697.  @ddevault can you clarify?

**Comment by emersion** [comment]
Since this is undocumented, I'd be okay with dropping it, FWIW.

**Comment by dongdigua** [comment]
I think this feature is GREAT, will you bring it back?

**Comment by y0nei** [comment]
Bumping again since some time passed, could we get this feature back? Its very useful

**Comment by emersion** [comment]
It should be possible to implement this functionality in a script instead of in Sway.

**Comment by dongdigua** [comment]
like this: [workspace.sh](https://github.com/dongdigua/configs/blob/main/sway/scripts/workspace.sh)

**Comment by proehlen** [comment]
I'm using rust crate [sway-new-workspace](https://github.com/nzig/sway-new-workspace) and it works great but now it requires that every machine I port my setup to also has it installed. Maybe I'm missing something but it seems like a really fundamental action that should be possible via Sway natively.
