### ISSUE TITLE
Setting sway environment with gdm in fedora

### ISSUE THREAD

**Issue by hboetes** [swaywm/sway#5916]
Since there is no decent way in fedora to get an environment file for sway and fedora I hacked up the following start script:
```
% cat /usr/local/bin/startsway
#!/bin/sh
source ~/.config/sway/env
sway
```
And edited the sway.desktop file which gdm reads.
```
% cat /usr/share/wayland-sessions/sway.desktop
[Desktop Entry]
Name=Sway
Comment=An i3-compatible Wayland compositor
Exec=/usr/local/bin/startsway
Type=Application
```

So now I can finally set all the environment settings that need to be set in the sway environment.
```
export XDG_RUNTIME_DIR=/run/user/$(id -u)
export XDG_CURRENT_DESKTOP=sway
export SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/ssh-agent.socket
export TZ='Europe/Vienna'
export MOZ_ENABLE_WAYLAND=1
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
```

For some mysterious reason `~/.pam_environment` is not used, not even after disabling selinux and you don't want to need to that anyway. Nor after adding `user_readenv=1` to `auth       required    pam_env.so` in the pam config.

**Comment by emersion** [comment]
I don't see any actionable item here, closing.

**Comment by hboetes** [comment]
That's great that you care about use cases outside of your own, well at least now it can be found.

**Comment by Artturin** [comment]
@hboetes it is not a case of "not caring about other use cases" but you not suggesting any enchancements
