### ISSUE TITLE
Closing CSGO Freezes Machine

### ISSUE THREAD

**Issue by shoober420** [swaywm/sway#5924]
### Please fill out the following:
- **Sway Version:**
  - sway version 1.5-53f5197c

- **Debug Log:**
  - I unfortunately can’t produce this consistently, it occurs randomly.

- **Configuration File:**
 https://gist.github.com/shoober420/59a2713bb09487a935a45ef4341a9d46

- **Description:**
  - Exiting CSGO using ‘quit’ in the console will close out of sway, and return back to the tty in a completely locked up state, so I have to hard shut down.

**Comment by Emantor** [comment]
might be related to #5884.

**Comment by shoober420** [comment]
Interesting, he’s experiencing a similar error using latest stable. Although when he quits CSGO, he doesn’t mention it completely locks up his system at the TTY. This might be a further regression due to me using git master.

Last night I tried to get a log of the crash happening. I must have closed out of CSGO 10 times. I’ll try and reproduce this today for a log.

**Comment by shoober420** [comment]
Managed to get a log. I hope this helps.

[swayhalt.log](https://github.com/swaywm/sway/files/5759831/swayhalt.log)

**Comment by shoober420** [comment]
Here is a fixed reupload of the log.

[swayhalt2.log](https://github.com/swaywm/sway/files/5759904/swayhalt2.log)

**Comment by emersion** [comment]
There isn't anything explaining the bug in the logs.

**Comment by shoober420** [comment]
Sway must crash before the debug can spit out the event. My machine crashes back to the TTY and is completely frozen, so I’m sorry I can’t provide a better log.

**Comment by emersion** [comment]
If your machine goes back to the TTY, then Sway is probably crashing.

Please provide a stack trace. You can do so by compiling from source, reproducing the crash and then running `coredumpctl gdb` and then `bt full`.

Here are some instructions to compile from source: https://github.com/swaywm/sway/wiki/Development-Setup#compiling-as-a-subproject

**Comment by LastLightSith** [comment]
> he doesn’t mention it completely locks up his system at the TTY

sway crashes. I can restart it from tty

**Comment by zeroeightysix** [comment]
> Please provide a stack trace. You can do so by compiling from source, reproducing the crash and then running `coredumpctl gdb` and then `bt full`.

I'm getting the same crash (I think).
Here's the [backtrace](https://gist.github.com/zeroeightysix/e8f47cf21e71013f9c9e62927f18922e)

This is on arch linux. Any more info you need?

**Comment by zeroeightysix** [comment]
> Can you reproduce with latest commit from master?

I have not been able to reproduce it the past few days.

**Comment by shoober420** [comment]
I haven't seen this happen for about a week now either, but it does happen randomly. I'll keep you guys posted too.

**Comment by RPigott** [comment]
If anyone feels like trying to reproduce this on master, asan might help, like the report in #5884.

I looked into this briefly a few days ago but didn't see the issue. I think it's clear from the other report that the surface->parent is UAF, so surface->parent->parent is the segfault. AFAICT the parent link is handled safely in xwm.c:xwayalnd_surface_destroy when a surface is destroyed so my best guess is that an already destroyed surface is being added as a parent somehow. It's my understanding xwayland would refuse such a request with BadWindow or something though, so I dunno.

**Comment by shoober420** [comment]
I must mention that I havent experienced this behavior for quite some time, many months. Honestly, Im going to close for now and reopen if it ever occurs again.
