### ISSUE TITLE
master: fails to display when launched from xorg terminal

### ISSUE THREAD

**Issue by CaptainBloodz** [swaywm/sway#5928]
sway version 1.5-d1bf3b8a (Jan  4 2021, branch 'HEAD')

- **Debug Log:**
  - Run `sway -dV 2> ~/sway.log`:
[sway-terminal-dbg-verbose.out.zip](https://github.com/swaywm/sway/files/5764290/sway-terminal-dbg-verbose.out.zip)

- **Configuration File:**
  - Please try to produce with the default configuration.
Default configuration file used.

- **Description:**
  - Launching sway from xorg terminal displays a window frame titled wlroots-X11-1 that forever remains grey.
  - Launching wayfire from xorg terminal works fine.

**Comment by emersion** [comment]
Nothing interesting in the logs, except maybe

```
00:00:00.132 [DEBUG] [wlr] [backend/x11/backend.c:656] Unhandled X11 event: 21
00:00:00.133 [DEBUG] [wlr] [backend/x11/backend.c:656] Unhandled X11 event: 19
```

**Comment by CaptainBloodz** [comment]
Likely originated in recent changes, as config has been working fine until then:
'output HDMI-A-{1,2}...' in config seems to have caused the issue:
Adding 'output X11-1...' in config has fixed the issue.
