### ISSUE TITLE
DPMS toggle

### ISSUE THREAD

**Issue by PopeRigby** [swaywm/sway#5929]
Outputs can be toggled without DPMS, but only `on` and `off` are provided for DPMS. Strangely, Sway does respond to `output dpms toggle` but it seems to just do the same thing as `output dpms off`.

**Comment by emersion** [comment]
We need to provide the current state instead of `true` here:

https://github.com/swaywm/sway/blob/40bdd0eecfc19a52a2f1e96d319c54fdea0a6cde/sway/commands/output/dpms.c#L13

**Comment by ebrensi** [comment]
I might try to tackle this, but I'm a web developer and I don't know C.   I can `dpms {id} off` a monitor but I cannot turn it back on with `dpms {id} on`.

**Comment by emersion** [comment]
No problem. If you want, you can join #sway-devel on Freenode and we can help you to write the patch!

**Comment by emersion** [comment]
>  I can dpms {id} off a monitor but I cannot turn it back on with dpms {id} on.

Ah, that's weird. You may want to open a new bug report for this.

**Comment by ebrensi** [comment]
> Ah, that's weird. You may want to open a new bug report for this.

I thought that is what @PopeRigby  was referring to when he said

> Strangely, Sway does respond to `output dpms toggle` but it seems to just do the same thing as `output dpms off`.

That's why I came here actually.  I can blank the screen with `swaylock` just fine but if I want to have the screens go to standby without the lock, I can't use `dpms on/off` because I won't be able to turn them back on.  This is a problem with the two laptops I have tried, with the same dual external monitor setup.  I cannot turn back on either one.

**Comment by emersion** [comment]
Ah, no. The issue is that currently `toggle` is interpreted as `off` by Sway. If `on` doesn't work, that's an unrelated bug that deserves its own issue.

**Comment by fluix-dev** [comment]
@ebrensi if you're still interested in tackling this (I'm happy to take this on otherwise), here's just something to note:
```
17:41 <emersion> the output commands operate on a brand new output config iirc
17:41 <emersion> and then it's merged afterwards
17:43 <emersion> yeah we'd need to get the current config
17:44 <emersion> ah, we have sway_output->enabled
17:45 <emersion> so we could have something like
17:46 <emersion> current_dpms = (!wlr_output->enabled && sway_output->enabled) ? DPMS_OFF : DPMS_ON
17:47 <emersion> or maybe just stash the dpms state into the sway_output
17:47 <emersion> latter would probably be cleaner
17:48 <fluix> also the parse_boolean takes in a bool, so you would use == DPMS_ON instead of the ternary operator
17:48 <emersion> yup!
```

**Comment by ebrensi** [comment]
@fluix-dev go ahead!  I have my hands full anyway. Thanks to everyone working on Sway.  It's my daily driver on a laptop and a "desktop" laptop.

**Comment by PopeRigby** [comment]
> That's why I came here actually. I can blank the screen with `swaylock` just fine but if I want to have the screens go to standby without the lock, I can't use `dpms on/off` because I won't be able to turn them back on. This is a problem with the two laptops I have tried, with the same dual external monitor setup. I cannot turn back on either monitor.

I'm also having a similar problem unrelated to this one. Let me know if you open an issue so I can chime in.
