### ISSUE TITLE
All xwayland apps are simultaneously closed

### ISSUE THREAD

**Issue by Omrigan** [swaywm/sway#5946]
- **Sway Version:** sway version 1.5-9ef5cc03 (Jan  2 2021, branch 'master')
- **Debug Log:** https://gist.github.com/Omrigan/b85075e77ed79dcede2557f6869f84a2
- **Configuration File:** https://gist.github.com/Omrigan/a185f2f06f2fb853c2bea3d640753a98
- **Stack Trace:** no crash
- **Environment:** https://gist.github.com/Omrigan/d84c52a5edc05f53b086931222bb3830

## Description
 - All xwayland clients exit at the same time. Non-X11 applications keep running.
 - One example what happens to the X11 client is java goland, which produces a crash report: https://gist.github.com/Omrigan/fc7ee9a76ae42d07e3d3a7518751d451
 - It is a bit tough to reproduce the issue since it happens spontaneously and while the active work is performed, such as switching windows, using clipboard, etc. 
 - My guess is the issue somehow related to bad GTK apps behaviour. I had similar issues with [emacs-pgtk](https://github.com/emacs-mirror/emacs/tree/feature/pgtk), even though it is supposed to be wayland native if properly built.

**Comment by emersion** [comment]
These are repeated many times:

```
00:24:59.709 [ERROR] [wlr] [xwayland/selection/incoming.c:395] convert selection failed
```

Eventually we run out of FDs:

```
00:24:59.815 [ERROR] [wlr] [xwayland/selection/outgoing.c:306] pipe() failed: Too many open files
00:25:03.312 [INFO] [wlr] [wayland] file descriptor expected, object (65), message add(huuuuu)
00:25:03.312 [INFO] [wlr] [wayland] error in client communication (pid 47027)
00:25:03.312 [INFO] [wlr] [xwayland/server.c:202] Restarting Xwayland (lazy)
```

This makes Xwayland exit.

**Comment by emersion** [comment]
It seems like the log doesn't contain debug info. Can you start Sway with `-d`, reproduce the issue again and re-upload another log?

**Comment by Omrigan** [comment]
Thank you, Simon, with your help I was able to figure out the problem is related to X11<-> wl  clipboard interaction. 
I've temporarily disabled my `wl-paste -t text --watch clipman store --max-items=100` and was able to mitigate the problem.

I'll be back in a couple of days with more debug information and a cleaner reproduction.

**Comment by Omrigan** [comment]
Here is the log with debug enabled: https://gist.github.com/Omrigan/f8a6ce3019ed739f8272728c8686e90f

I've also figured out the issue happens only when clipman is running, wl-paste --watch with dummy command doesn't trigger the issue.

It is still unclear to me who eats up all fds, but perhaps java IDE continuously triggers copy event in a short period of time (maybe it is a positive feedback loop), so that a huge number of clipman instances are spawned, and pipes which transmits the selection content to clipman are drain fds.

**Comment by emersion** [comment]
Ah, thanks for collecting a log.

@Xyene has been working on improving our X11 clipboard logic (e.g. https://github.com/swaywm/wlroots/pull/2687). I think we still have issues around handling multiple X11 clipboard selections at a time, but @Xyene has a plan to fix these.

> I've also figured out the issue happens only when clipman is running, wl-paste --watch with dummy command doesn't trigger the issue.

Hmm. I wonder if clipman could avoid overwriting the selection on copy, and instead do it when the selection is cleared (which happens when the source is killed). This is what e.g. KDE does (https://github.com/swaywm/wlr-protocols/pull/94).

**Comment by Xyene** [comment]
I believe I've addressed the fd leak in https://github.com/swaywm/wlroots/pull/2699, but I suspect the loop still happens (unless https://github.com/swaywm/wlroots/pull/2687 happened to fix it by accident).

**Comment by emersion** [comment]
Maybe https://github.com/swaywm/wlroots/pull/2739 helps?

**Comment by Xyene** [comment]
> Maybe swaywm/wlroots#2739 helps?

If I were a betting man, looking at the logs with a fresh eye...

> 30:31:22.140 [DEBUG] [wlr] [xwayland/selection/outgoing.c:403] XCB_SELECTION_REQUEST (time=0 owner=**2097153**, requestor=**2097153** selection=275, target=254, property=276)

This request will now be rejected outright by wlroots if it manages to happen (we won't enter a feedback loop leaking pipes &mdash; so Xwayland apps won't die), and the request itself should no longer be triggered in the first place.

Given clipman was the trigger here as well, this is fundamentally the same issue as https://github.com/swaywm/wlroots/pull/2739, and should be fixed now. Feel free to reopen if you find this is not in fact the case on sway/wlroots master.
