### ISSUE TITLE
vulkan isn't working

### ISSUE THREAD

**Issue by GreyXor** [swaywm/sway#5961]
I try to run vulkaninfo or vkcube but I can't get vulkan to work. This is my error :

`ERROR at /build/vulkan-tools/src/Vulkan-Tools-1.2.162/vulkaninfo/vulkaninfo.h:248:vkGetPhysicalDeviceSurfaceFormats2KHR failed with ERROR_SURFACE_LOST_KHR`

xwayland is working and activated and **vulkan works under weston**
AMD Renoir 4750U vega and free mesa driver

I have installed all the drivers for AMD mesa, amd vulkan, I'm on arch linux and my packages are up to date.

`sway version 1.5-62ec528c (Jan 20 2021, branch 'master')`

https://drmdb.emersion.fr/snapshots/4aa1956a81a6

[env.txt](https://github.com/swaywm/sway/files/5845714/env.txt)
[strace_vkcube.txt](https://github.com/swaywm/sway/files/5845715/strace_vkcube.txt)
[strace_vulkaninfo.txt](https://github.com/swaywm/sway/files/5845717/strace_vulkaninfo.txt)

**Comment by emersion** [comment]
Can you make sure you have this wlroots commit: https://github.com/swaywm/wlroots/commit/7c995b78b2f74a0a2e4c96c6be1736702d3733c7

**Comment by GreyXor** [comment]
I still have the last wlroots but here I was 3 hours late apparently. **thank you vulkan works again now.**
As I can reproduce the bug, don't hesitate if you need test or specific feedback.

**Comment by emersion** [comment]
OK, thanks for confirming.
