### ISSUE TITLE
System freezes on Gentoo

### ISSUE THREAD

**Issue by YorozuyaDev** [swaywm/sway#5964]
### Please fill out the following:
- **Sway Version:** 1.5.1
- **Gentoo with SystemD**
- **Debug Log:**
  00:00:00.000 [sway/main.c:326] Sway version 1.5.1
00:00:00.029 [sway/main.c:153] Linux localhost 5.4.80-gentoo-r1-x86_64 #1 SMP Wed Jan 20 17:51:05 CET 2021 x86_64 Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz GenuineIntel GNU/Linux
00:00:00.029 [sway/main.c:169] Contents of /etc/os-release:
00:00:00.029 [sway/main.c:153] NAME=Gentoo
00:00:00.029 [sway/main.c:153] ID=gentoo
00:00:00.030 [sway/main.c:153] PRETTY_NAME="Gentoo/Linux"
00:00:00.030 [sway/main.c:153] ANSI_COLOR="1;32"
00:00:00.030 [sway/main.c:153] HOME_URL="https://www.gentoo.org/"
00:00:00.030 [sway/main.c:153] SUPPORT_URL="https://www.gentoo.org/support/"
00:00:00.030 [sway/main.c:153] BUG_REPORT_URL="https://bugs.gentoo.org/"
00:00:00.030 [sway/main.c:169] Contents of /etc/gentoo-release:
00:00:00.030 [sway/main.c:153] Gentoo Base System release 2.7
00:00:00.030 [sway/main.c:141] LD_LIBRARY_PATH=(null)
00:00:00.030 [sway/main.c:141] LD_PRELOAD=(null)
00:00:00.030 [sway/main.c:141] PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/usr/lib/llvm/11/bin
00:00:00.030 [sway/main.c:141] SWAYSOCK=(null)
00:00:00.030 [sway/server.c:43] Preparing Wayland server initialization
00:00:00.168 [INFO] [backend/session/logind.c:839] Waiting for 'CanGraphical' on seat seat0

- **Description:** I installed sway with following portage flags:  swaybg swayidle X policykit flags. The first time I launched it, it gaves me two error: no permission and backend DRM. I tried with sudo and it returned XDG_RUNTIME_ERROR. Now if I launch it with `$ sway`, it freezes the system. I tried with sudo but it returns XDG_RUNTIME_ERROR again.

**Comment by emersion** [comment]
Don't try to run Sway as root.

Is there anything in `/dev/dri`? If not, you're missing kernel drivers.

**Comment by YorozuyaDev** [comment]
Nope, no /dev/dri file

**Comment by emersion** [comment]
Consult your distribution docs to use kernel display drivers.
