### ISSUE TITLE
sway crashes when connecting a display with a displaylink docking station

### ISSUE THREAD

**Issue by gPirkes** [swaywm/sway#5968]
- **Sway version:** `sway version 1.4`

- **Debug Log:** (`sway --debug --verbose`)

sway starts and works as intended. plugging in the monitor now:
```
[2021-01-24 20:44:51.266] [error] Window: Unable to receive IPC header
[2021-01-24 20:44:51.266] [error] Window: Unable to receive IPC header
[2021-01-24 20:44:51.266] [error] Window: Unable to receive IPC header
[2021-01-24 20:44:51.266] [error] Window: Unable to receive IPC header
```
or (if i leave out the screen resolution definitions, lines 37 through 39 in my config):
```
[2021-01-24 21:15:29.024] [error] Window: Unable to receive IPC header
[2021-01-24 21:15:29.024] [error] Workspaces: Unable to receive IPC header
```
and i get thrown back to the tty. If i leave the monitor plugged in and try to start sway through gdm, i can enter my password and get thrown back to the gdm login screen immediately.

- **Configuration File:**
[my config](https://gist.github.com/gPirkes/77408e8e816eddc2a3b4ed942498d51b). I tried this with and without the `output` lines enabled.

- **Stack Trace:**
I am currently trying to get coredumpctl running on my PC but there is a problem with the installation. i will try to get a debug output once i've reached the bottom of that rabbit hole :upside_down_face:

- **Description:**
As soon as i attempt to attach a display to [my displaylink docking station](https://www.amazon.com/Plugable-Universal-Docking-Station-Ethernet/dp/B00ECDM78E/ref=sr_1_6?dchild=1&keywords=Plugable+USB+Laptop+Docking+Station%2C+USB+3.0+Universal&qid=1611522419&sr=8-6), sway crashes. I have the [displaylink drivers for ubuntu](https://www.displaylink.com/downloads/ubuntu) installed as they are needed for ethernet and sound. If i attach the screen, then try to start sway, it crashes. I have a laptop, and it has an HDMI port on which a second monitor is plugged in (its 4k and the docking station is rather old, so it cant run 4k via the USB cable without lagging). I don't think this is the problem, since it crashes regardless of whether the other monitor is plugged in or not.
Any ideas why this happens, or where i could start looking? I quickly grep'd through the wlroots and sway code but did not find the code where this error message comes from.

**Comment by emersion** [comment]
This doesn't seem like a Sway log. This seems like a waybar log.

Please post the full Sway debug log.

**Comment by gPirkes** [comment]
sorry, im an iditot. i didnt realize that sway logs to standard error not standard out. [Here is the full sway log (from stderr)](https://gist.github.com/gPirkes/9b16cc737e9e95f436ad77f1dbd27dfc)
Thanks!

**Comment by gPirkes** [comment]
> iditot 

Turns out, i cant even spell :roll_eyes: 
Just as a side note: this log was created by plugging in the monitor and starting sway with the monitor attached (in which case it immediately crashes back to the tty). Also, i disabled waybar and used the default swaybar but the behavior is the same with and without waybar.

**Comment by emersion** [comment]
Hm, it does look like a crash. Please provide a stack trace. You can do so by compiling from source, reproducing the crash and then running `coredumpctl gdb` and then `bt full`.

Here are some instructions to compile from source: https://github.com/swaywm/sway/wiki/Development-Setup#compiling-as-a-subproject

**Comment by gPirkes** [comment]
hm, I've hit another snag. i built sway with wlroots as a subproject as suggested. when running it from a running graphical dm like ubuntu on wayland or sway itself (the one without debug symbols), sway starts in a separate window in that display manager. If i try to run it from a tty i get [this debug log](https://gist.github.com/gPirkes/cc53f2eefd2f5ac634d3967f3e4102b4).

It seems like libinput does not recognize the peripherals. If i run `export WLR_LIBINPUT_NO_DEVICES=1` and then try to start sway, it starts, but neither the attached keyboard or mouse nor the builtin keyboard and touchpad are responding, so i cannot exit sway. it also doesn't crash when i attach the other monitor to the docking station, but simply does nothing and i cannot interact with it. the same happens if i attach the screen first and then try to start from tty (with the WLR_LIBINPUT_NO_DEVICES flag). [Here](https://gist.github.com/gPirkes/76b3a6c75069f98f032b9dbc8e867821) is the debug log for when i start sway without peripherals and then force restart my PC because i cant get out of the dm any more.

i also got no coredumps, since sway doesn't exactly *crash* but simply does not identify inputs (coredumpctl list shows the old coredumps, without debug symbols).

**Comment by emersion** [comment]
```
00:00:00.003 [INFO] [wlr] [backend/session/direct.c:274] Successfully loaded direct session
```

It's trying to use the direct session. You want the logind session on Ubuntu. Can you install the missing dependency, probably libsystem-dev? Then `meson setup build/ --wipe` and rebuild.

**Comment by gPirkes** [comment]
okay, i think i managed to get the dump: 
```
[Current thread is 1 (Thread 0x7fcb7e7fc700 (LWP 15017))]
(gdb) bt full
#0  0x00007fcbc6bfb342 in  () at /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#1  0x00007fcbc6bfb65c in  () at /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#2  0x00007fcbc6c8f41f in  () at /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#3  0x00007fcbc6c8eebb in  () at /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#4  0x00007fcbc6c8f64a in  () at /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#5  0x00007fcbc6c8f46b in  () at /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#6  0x00007fcbc8756609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = 
              {cancel_jmp_buf = {{jmp_buf = {140511977391872, -4974041431880608434, 140730638402894, 140730638402895, 140730638402896, 140511977389440, 5003036655128302926, 5003278463642916174}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#7  0x00007fcbc8892293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
[Here](https://gist.github.com/gPirkes/560187238aadcadaf498f8b10d99f272) is the sway log from that core dump as well.

**Comment by emersion** [comment]
This sounds like a crash in radeonsi, not sure we can do anything about it.

**Comment by gPirkes** [comment]
all right - thanks for looking into it. if i manage to get it working somehow ill let you know!
