### ISSUE TITLE
Showing activated window from scratchpad crashes Sway

### ISSUE THREAD

**Issue by qoheniac** [swaywm/sway#5977]
I'm not completely sure if this is the right place for this issue. To reproduce the crash I do the following:

1. move window to scratchpad
2. request window activation
3. show window from scratchpad

Here some details on what I did exactly:

1. Start some program (e. g. Firefox) and send it to the scratchpad by pressing `[super]+[shift]+[minus]` (`swaymsg 'bindsym Mod4+Shift+minus move scratchpad'`)
2. Click on the program's icon in [Waybar's taskbar module](https://github.com/Alexays/Waybar/wiki/Module:-Taskbar) to request activation (`"wlr/taskbar": {"on-click": "activate"}` which uses the activate request from the `wlr-foreign-toplevel-management-unstable-v1` protocol)
3. Try to show the window by pressing `[super]+[minus]` (`swaymsg 'bindsym Mod4+minus scratchpad show'`)

The window does not show up, but instead Sway crashes immediately.

**Comment by emersion** [comment]
Please provide a stack trace. You can do so by compiling from source, reproducing the crash and then running `coredumpctl gdb` and then `bt full`.

Here are some instructions to compile from source: https://github.com/swaywm/sway/wiki/Development-Setup#compiling-as-a-subproject

**Comment by qoheniac** [comment]
I will try to that. One thing I forgot to mention is that Sway prints out `[error] Workspaces: Unable to receive IPC header`.

**Comment by qoheniac** [comment]
I compiled from source and with that it worked without problems. While in version 1.5 which I installed from the Fedora 33 repo requesting activation seemed to do nothing (which is why I tried to get the window back from scratchpad using swaymsg) in the compiled version the activation request on its own already brings the window back from scratchpad to floating focus.

**Comment by qoheniac** [comment]
Not sure what ftm is, but mayby this commit fixed it?
https://github.com/swaywm/sway/commit/3520fd2c192f087dc6f3525b0d7d15c2790103b8

**Comment by qoheniac** [comment]
I will close this as I guess, that this issue will disappear for me when Fedora goes from Sway version 1.5 to 1.5.1. If that doesn't prove to be true I'll reopen.

**Comment by qoheniac** [comment]
Then maybe when Fedora goes from wlroots version 0.11.0 to 0.12.0.

**Comment by WillPower3309** [comment]
@emersion can confirm this issue still exists with sway version 1.5.1. Encountered it myself by trying to activate a a window in the scratchpad via the wlr/taskbar module in waybar.
