### ISSUE TITLE
Cave Story+ Crashes XWayland+Sway

### ISSUE THREAD

**Issue by shoober420** [swaywm/sway#5978]
- **Sway Version:**
  - sway version 1.5-4d43f1dd (Jan 27 2021, branch 'master')

- **Debug Log:**
  - [swaycavestory.txt](https://github.com/swaywm/sway/files/5886048/swaycavestory.txt)

- **Configuration File:**
  - https://gist.github.com/shoober420/59a2713bb09487a935a45ef4341a9d46

- **Description:**
  - Launch Cave Story+
  - Quit Game
  - Reopen Steam, XWayland will crash, or close sway and it will crash just like https://github.com/swaywm/sway/issues/5924

**Comment by emersion** [comment]
Please provide a stack trace. You can do so by compiling from source, reproducing the crash and then running `coredumpctl gdb` and then `bt full`.

Here are some instructions to compile from source: https://github.com/swaywm/sway/wiki/Development-Setup#compiling-as-a-subproject

**Comment by shoober420** [comment]
There is another bug in this, it crashes XWayland first. After trying to relaunch Steam, then the https://github.com/swaywm/sway/issues/5924 bug occurs.

**Comment by shoober420** [comment]
I compiled wlroots and sway with the “-Db_sanitize=address,undefined“ flag, but coredumpctl and bt are not installed on my system. After launching sway with “ ASAN_OPTIONS=abort_on_error=1:disable_coredump=0:unmap_shadow_on_exit=1 sway”, how do I get the log for you?

BTW, I don’t use systemd, this is a s6 init system.

**Comment by shoober420** [comment]
Ok, I got some core. files from the newly compiled sway strace. Do I skip coredumpctl and just run gdb and “bt full” on those?

**Comment by shoober420** [comment]
I havent had this behavior for quite some time. Im going to close this unless this specific behavior occurs again.
