### ISSUE TITLE
sway master doesn't launch, unsupported egl platform

### ISSUE THREAD

**Issue by nullobsi** [swaywm/sway#5984]
- **Sway Version:**
  - master as of this writing. `sway version 1.5-8b7008a2 (Jan 30 2021, branch 'master')`

- **Debug Log:**
  - running from a TTY: https://gist.github.com/nullobsi/365485e6f4fc7f827a51f78a1271add5
- **Configuration File:**
  - I used both my config and the default config with the same issue. Though I don't believe the config has much to do with this.

- **Stack Trace:**
  - Nothing shows under coredumpctl.

- **Description:**
  - Building straight from master and running leads to this error. I've also tried the packages from the AUR `sway-git` with similar results. wlroots has also been built from master.
  - Using intel graphics, the latest stable works fine

**Comment by emersion** [comment]
You're probably hitting https://gitlab.freedesktop.org/glvnd/libglvnd/-/merge_requests/235 because you have the proprietary NVIDIA drivers installed.

**Comment by nullobsi** [comment]
i think that's it; i have nvidia disabled when I don't need it, but it's strange that it just having it installed would be an issue

thank you!

**Comment by emersion** [comment]
Yeah, it's a bug in libglvnd, you'll get the fix once a new version is released.
