### ISSUE TITLE
inhibit_idle config option returns an error

### ISSUE THREAD

**Issue by snakedye** [swaywm/sway#5986]
### Please fill out the following:
 sway version 1.5.1

- **Debug Log:**
https://srv-store1.gofile.io/download/KfEeY9/sway.log

- **Configuration File:**
https://gitlab.com/snakedye/wlr_config/-/raw/master/sway/config

- **Description:**
![image](https://user-images.githubusercontent.com/49378990/106387229-cb368180-63a6-11eb-890b-1cafe0bdf19c.png)

**Comment by emersion** [comment]
You need to specify criteria.

See e.g. https://github.com/swaywm/sway/pull/3962#issuecomment-478131471
