### ISSUE TITLE
Occasional full desktop freeze/crash

### ISSUE THREAD

**Issue by ChrisLane** [swaywm/sway#5988]
- **Sway Version:** sway version 1.5-8b7008a2 (Jan 31 2021, branch 'master')
- **Debug Log:** https://gist.github.com/ChrisLane/12857833023233d6799df9886922b67c
- **Configuration File:** https://gist.github.com/ChrisLane/f473cad0c3950dfa152501a0447fbc61
- **Stack Trace:** https://gist.github.com/ChrisLane/d10d64344c6384fe25e88962e4af3fa9
- **Journalctl from crash period:** https://gist.github.com/ChrisLane/cfb488324c8493ff777d6eabb2b2bd9b

**Description:**
During normal usage running firefox, telegram desktop, alacritty, IntelliJ Idea and Datagrip, sway will become unresponsive.
The screen stays the same despite attempting to switch workspace etc. The mouse pointer updates based on what should be on the screen (e.g. switch to different workspace, hover over button for pointer cursor icon).

- The time until a freeze doesn't seem be consistent or coincide with any open processes to my knowledge.
- This particular freeze happened after around 6 hours.
- I've also been having occasional issues where parts of windows or the screen flash grey when the screen updates.
- When I switch to a different TTY and then switch back, the screen is black but the mouse pointer still updates. I pkill sway from the different TTY to get back to a desktop.
- I have two monitors, a laptop screen on the left that's 3200x1800 and an external monitor on the right that's 1920x1080
- Intel integrated graphics + an Nvidia 860M on nouveau

**Comment by staalmannen** [comment]
I have also had occasional complete freezes when running Teams meetings in Sway. I can still hear people talking etc, just completely unresponsive graphics.

**Comment by Emantor** [comment]
```
Feb 01 15:39:00 chrispc kernel: i915 0000:00:02.0: [drm] GPU HANG: ecode 7:1:dc7bafff, in Renderer [1323]
Feb 01 15:39:00 chrispc kernel: GPU hangs can indicate a bug anywhere in the entire gfx stack, including userspace.
Feb 01 15:39:00 chrispc kernel: Please file a _new_ bug report at https://gitlab.freedesktop.org/drm/intel/issues/new.
Feb 01 15:39:00 chrispc kernel: Please see https://gitlab.freedesktop.org/drm/intel/-/wikis/How-to-file-i915-bugs for details.
Feb 01 15:39:00 chrispc kernel: drm/i915 developers can then reassign to the right component if it's not a kernel issue.
Feb 01 15:39:00 chrispc kernel: The GPU crash dump is required to analyze GPU hangs, so please always attach it.
Feb 01 15:39:00 chrispc kernel: GPU crash dump saved to /sys/class/drm/card0/error
Feb 01 15:39:00 chrispc kernel: i915 0000:00:02.0: [drm] Resetting chip for stopped heartbeat on rcs0
Feb 01 15:39:00 chrispc kernel: i915 0000:00:02.0: [drm] Renderer[1323] context reset due to GPU hang
```
The i915 driver hangs, nothing much we can do on the sway side about this.

**Comment by ChrisLane** [comment]
@Emantor That's not something that the DE could recover from or wait for?

**Comment by Emantor** [comment]
> @Emantor That's not something that the DE could recover from or wait for?

AFAIK we don't get any information about a GPU crash delivered to userspace using the DRM FD, all we could do in this case is shutdown the compositor anyway.

**Comment by emersion** [comment]
Hm, I thought we already had an issue about it. We don't, so I created one:

https://github.com/swaywm/wlroots/issues/2705

Mind, this is non-trivial to implement.

**Comment by ChrisLane** [comment]
Okay, thanks for the consideration.
I'll close this issue and report my GPU hang at https://gitlab.freedesktop.org/drm/intel if there isn't an issue there already. Will add a link here for anyone else who comes across this.

**Comment by koxu1996** [comment]
My two cents about i915. Over the last 10 years I experienced so many issues - hangs, freezes - and it was always casued by this iGPU. Around 2019 I spent few days to dump kernel logs precisely before CPU freeze - fortunately it helped Intel team to quickly fix the bug that was affecting people **for years** (some chicken bit was missing in the driver).

For the last 2 years I have been using Sway and experiencing exactly what @ChrisLane described, but I always thought it's bad SATA cable, I/O error, some process utilizing too much CPU - nope, it was the damn i915...

Just blacklist i915 and you will be good 🚀.

**Comment by Emantor** [comment]
> Just **blacklist i915** and you will be good 🚀.

AFAICS this means that sway will fallback to CPU rendering.

my 2c: I had occasional crashes on my old 6th gen skylake laptop as well, which I can no longer observe with the 12th gen intel hardware I use now.
