### ISSUE TITLE
[Qt] Can't run game in Duckstation

### ISSUE THREAD

**Issue by GreyXor** [swaywm/sway#5989]
Hello,
when i try to run a PS1 game in [Duckstation](https://github.com/stenzek/duckstation). i get this message

`Failed to get window info from widget`
`Failed to acquire host display`
`Unknown PNI platform  "wayland-egl"`

Duckstation is correctly compiled with Wayland support

**It's working on weston**

`sway version 1.5-8b7008a2 (Jan 30 2021, branch 'master')`

duckstation version : 
![image](https://user-images.githubusercontent.com/24626758/106502486-b6501000-64c4-11eb-89dd-bf2de6eda2b0.png)

Update: Fixed, Close me, i've setted a wrong QT_QPA_PLATFORM

**Comment by fluix-dev** [comment]
> Close me

You should be able to close the issue yourself.
