### ISSUE TITLE
uxterm is out of focus when opening it with SUPER + ENTER

### ISSUE THREAD

**Issue by Lepidos** [swaywm/sway#5996]
Cannot write to uxterm right after, pressing SUPER + ENTER.
I need to do a mouse click on it or loop between workspaces.

sway version 1.5-169b90f9 (Feb  5 2021, branch 'master')

**Comment by emersion** [comment]
Please provide debug logs.

**Comment by Lepidos** [comment]
How?

**Comment by emersion** [comment]
See https://github.com/swaywm/sway/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by Lepidos** [comment]
I cannot reproduce the issue anymore.
Sorry for inconvenience.
