### ISSUE TITLE
Opening a window which takes times does not gives feedback (like loading icon on mouse)

### ISSUE THREAD

**Issue by etienne02** [swaywm/sway#5997]
When i try to open a program (like Firefox), the window does not appear immediately, it takes some time.
In i3, I have a feedback on my mouse saying that program is loading and will open soon.
In sway, I don't have any feedback sometimes don't know if my program will open or not.

**Comment by emersion** [comment]
The Wayland protocol is missing the necessary bits for this. Follow https://gitlab.freedesktop.org/wayland/wayland-protocols/-/issues/31#startup-notifications if you're interested.
