### ISSUE TITLE
Compositor effects, blurr, fade, shadows?

### ISSUE THREAD

**Issue by KoalaV2** [swaywm/sway#5998]
Hey, apologies if this has been requested / answered well before but are there any plans to add picom effects such as blurr and shadows to windows in sway? I found this issue https://github.com/swaywm/sway/issues/453 which had rather of a interesting response but considering it was 5 years ago maybe it has changed?

**Comment by emersion** [comment]
Sorry, we still have no plans to implement this.

**Comment by KoalaV2** [comment]
How so?

**Comment by emersion** [comment]
I don't want to maintain such code.

Feel free to implement the feature in a fork, ofc.

**Comment by fluix-dev** [comment]
> blurr and shadows

At least for the latter, [my fork](https://github.com/fluix-dev/sway-borders) has it. I plan on adding blur _at some point_.

**Comment by WillPower3309** [comment]
[swayfx](https://www.github.com/willpower3309/swayfx) currently has all of these effects. Although, blur is currently in a draft PR, so it will be merged soon
