### ISSUE TITLE
[FR] give .config file compositor options (in the traditional sense)

### ISSUE THREAD

**Issue by user18130814200115-2** [swaywm/sway#6010]
I used to run i3 without a compositor (picom etc). SO no transparency, drop shadows transitions etc.
Sway integrates traditional compositor things such as transparency in the window manager itself.
I think it is important for the user to be able to control these options in the config file and turn them off.

**Comment by kennylevinsen** [comment]
Sway is not an effects compositor. It does not draw drop shadows, animate transitions, etc.

If you see drop shadows, it's client-side decorations. See `man 5 sway`, look for border.

**Comment by emersion** [comment]
Yeah, this behavior is not configurable. The front-buffer rendering X11 typically uses won't be implemented in Sway.

**Comment by user18130814200115-2** [comment]
I gave drop shadows and transitions as example of what I meant with the term "classical compositor" since sway is a "wayland compositor".
I specifically meant configuring and disabling transparency.

**Comment by kennylevinsen** [comment]
Forced transparency is set by the `opacity` command.

It is not possible to disable client transparency. It is required for things to work, and trying to interfere with it to limit it is more work (requires drawing black with 0xFF alpha under the window before copying it in), not less. This is what we do in fullscreen, as this is a requirement.

If you don't want an application to have transparency, fix the application.
