### ISSUE TITLE
Cycling through layouts doesn't work

### ISSUE THREAD

**Issue by Slickytail** [swaywm/sway#6011]
**Sway Version:** 1.5.1

**Debug Log:**
https://pbox.ca/4064245

**Relevant config:** 
```
input type:keyboard {
     xkb_layout us,us(intl)
}
```

**Steps to reproduce:**
Set two keyboard layouts under xkb_layout. Either with a bindsym or through swaymsg, run `input type:keyboard xkb_switch_layout next`. Specifying an index (ie, 0 or 1) rather than `next` or `prev` is able to switch the layout just fine, but the keyboard layout does not change if `next` or `prev` is used.

**Comment by faern** [comment]
I can reproduce on sway 1.5

**Comment by mikeroll** [comment]
Same problem here. An ugly hack I came up with to toggle between two layouts:
```bash
swaymsg -t get_inputs -r \
  | jq '[.[] | select(.type == "keyboard") | .xkb_active_layout_index][0] - 1 | fabs' \
  | xargs swaymsg 'input type:keyboard xkb_switch_layout'
```

**Comment by inwwin** [comment]
Somehow, for me, this bug can be reproduced very reliably using two of my rubber dome keyboards. But it affects my cherry mx keyboard only some of the times.
Also, after the command `input type:keyboard xkb_switch_layout next` is `bindsym` to a key combination, that key combination will produce something weird in `wev`.

**Comment by fbernier** [comment]
For me, it cycles properly with two layouts, but as soon as I add a third it stops at the last one.

**Comment by lrazovic** [comment]
Same problem with sway 1.6.1 and wlroots 0.14.1. Relevant `config` part:
```
input type:keyboard {
    xkb_layout "us,it"
    xkb_numlock enabled 
}

bindsym $mod+Escape exec swaymsg input type:keyboard xkb_switch_layout next 
```

Nothing changes even with `swaymsg input type:keyboard xkb_switch_layout next` from the terminal. Is there anything I can do to help with debugging?

**Comment by inwwin** [comment]
I've found that the problem for me occurs because I have a yubikey plugged in which is recognised as a keyboard and does not accept any layout other than 'us'. The issue is gone once I remove the yubikey. It can also be worked around by using `input <identifier> xkb_switch_layout next` (with a specific identifier for your keyboard) instead of `input type:keyboard xkb_switch_layout next`

**Comment by paolomainardi** [comment]
I am having the same trouble here:

```
input type:keyboard {
    xkb_layout "us(altgr-intl),it"
}

While `swaymsg input type:keyboard xkb_switch_layout 0|1` is working fine, `swaymsg input type:keyboard xkb_switch_layout next|prev` does not have any effect, i have also tried what @inwwin proposed, but it doesn't work too.

**Comment by inwwin** [comment]
> **EDIT:** Using the right identifier it works, but is something quite strange to understand how it works, should the `input:keyboard` next/prev behave like using the index ?

In my case, it doesn't work because I have two keyboards in my system, and configured two layouts. When I execute 'next', sway go the 'next' layout twice (equal to the number of keyboards), and hence it returns to the original layout.

**Comment by emersion** [comment]
Sounds like this is the same as https://github.com/swaywm/sway/pull/6740

**Comment by vitek** [comment]
Recently experienced the issue and found that it's related to dependent keyboard devices. When I switch layout on device A it also changes layout on device B and vice versa.  So when I change it on B it changes it back for A.

Here is fix for sway 1.7 https://github.com/swaywm/sway/pull/6940

**Comment by vitek** [comment]
And here is fix against master https://github.com/swaywm/sway/pull/6966

**Comment by kurotych** [comment]
> Recently experienced the issue and found that it's related to dependent keyboard devices. When I switch layout on device A it also changes layout on device B and vice versa.

Ohhh it was not a bug but a feature for me :(
