### ISSUE TITLE
Trackpad is occasionally completely unresponsive on reboot

### ISSUE THREAD

**Issue by j-james** [swaywm/sway#6015]
- **Sway Version:**
  - 1.5.1

- **Debug Log:**
  - This is not reproducible when launching from a TTY. I'm not sure of the best way to get a debug log - putting something like `sway -d 2> ~/sway.log` in `wayland-sessions/sway.desktop` doesn't let me log in.

- **Configuration File:**
  - This occurs with or without the default configuration.

- **Description:**
  - This issue occurs semi-randomly when logging in from a display manager (LightDM) after a reboot.
  - While the mouse is usable in the display manager, upon login it snaps to near the upper left corner of the screen, and doesn't move and doesn't recognize clicks.
  - It occurs frequently enough (probably 3/5 times, the remaining 2/5 times there are no issues whatsoever) that I could provide a debug log, if there's a way to get one when launching from a display manager.
  - This doesn't happen with external mice. Plugging in one lets you move the mouse around normally, but the trackpad remains unresponsive.

Please let me know how I can provide any better information.

**Comment by emersion** [comment]
Sorry, login managers are unsupported, exactly because they cause these kind of issues.

**Comment by j-james** [comment]
Interesting. LightDM's been causing me some other issues for a while too.

Out of curiosity, how do you use and start Sway without a login manager? It can't be through the TTY each time, no?

**Comment by emersion** [comment]
Through the TTY each time. I have FDE and TTY auto-login.
