### ISSUE TITLE
Strange position of newly spawned floating windows.

### ISSUE THREAD

**Issue by vvrein** [swaywm/sway#6024]
Strange new behavior as of commit 90fa6953ea84477c09cb57fd60ded2bb0e33414d

- **Description:**
  - run sway
  - press $mod+d (start alacritty as app launcher)
  - watch as alacritty spawns in top left corner and takes near ~30ppt instead to take 100ppt of height
  - same thing for telegram image viewer windows

- **Videos:**
  - sway ok version 50205ade, how it supposed to be  [LINK](https://user-images.githubusercontent.com/17022100/107873555-17f87d00-6ebc-11eb-9c82-3c75f6601738.mp4)
  - sway not ok version 90fa6953, how it works [LINK](https://user-images.githubusercontent.com/17022100/107873608-69a10780-6ebc-11eb-9e2e-af076e84a596.mp4)
  - sway not ok version 90fa6953, with minimal config [LINK](https://user-images.githubusercontent.com/17022100/107873626-8b01f380-6ebc-11eb-8ae6-079ce1f1644c.mp4)
  - sway not ok version 90fa6953, telegram example [LINK](https://user-images.githubusercontent.com/17022100/107873665-b389ed80-6ebc-11eb-891d-12c041bc3801.mp4)

- **Sway Version:**
  - ok: `sway version 1.5-50205ade (Feb 14 2021, branch 'master')`
  - not ok: `sway version 1.5-90fa6953 (Feb 14 2021, branch 'master')`

- **Debug Log:**
  - log for version 90fa6953ea84477c09cb57fd60ded2bb0e33414d and default config https://gist.github.com/vvrein/415e30307c322645478045288b767a95
  - steps I did with debug log enabled:
    - `sway -d 2> sway.log`
    - pressed `$mod+d`
    - pressed `esc`
    - pressed `$mod+shift+e`
    - pressed `yes`

- **Configuration File:**
  - minimal config which reproduces behavior https://gist.github.com/vvrein/2f7da85776d2889ca492118f06e3110d
  - default config which reproduces behavior https://gist.github.com/vvrein/1f7b6c962e95c7b4278379487abf879c

- **Some details**
  - To find out precise commit I reseted to when there was no issue, and then stepped forward by 1 commit till issue appears
 And this one the first when issue appears `git reset 90fa6953ea84477c09cb57fd60ded2bb0e33414d --hard`
  - Rebuild was done each time with `meson setup --wipe ./build && ninja -C build`
  - subprojects/wlroots in both cases (90fa6953 & 50205ade) was at https://github.com/swaywm/wlroots/commit/5e19e0053a5800252a27ce127fd015d641ee2e9e

**Comment by kennylevinsen** [comment]
I cannot seem to reproduce locally, with alacritty consistently showing up on the requested position. Note that I changed the minimal configuration file to not include any command to alacritty. Maybe it's a race in the affected applications?

@vvrein Can you please share the output from running the alacritty example with `WAYLAND_DEBUG=1` set in good/bad cases? Please limit interaction with the window, and just close it after observing the geometry. Only set the var for alacritty, not for sway itself.

**Comment by vvrein** [comment]
**Bad case**
```
| sway --version
sway version 1.5-b7d43c88 (Feb 14 2021, branch 'master')
```

Alacritty exited after `sleep 1`:
LOG: [WAYLAND_DEBUG=1 alacritty --class 'launcher'  --command '/usr/bin/sleep' 1](https://gist.github.com/vvrein/a358ec852cce1934a0e9e6e3ec90064a) VIDEO: [mp4](https://user-images.githubusercontent.com/17022100/107888229-959ba780-6f13-11eb-8499-79207956bf2e.mp4)

Alacritty exited with ^d:
LOG: [WAYLAND_DEBUG=1 alacritty --class 'launcher'](https://gist.github.com/vvrein/8d7d6a4bf837e0882bb504efe415e49b) VIDEO: [mp4](https://user-images.githubusercontent.com/17022100/107888353-60dc2000-6f14-11eb-83ec-23efd92bcf69.mp4)
 
---

**Good case**
```
| sway --version
sway version 1.5-50205ade (Feb 14 2021, branch 'master')
```

Alacritty exited after `sleep 1`:
LOG: [WAYLAND_DEBUG=1 alacritty --class 'launcher'  --command '/usr/bin/sleep' 1](https://gist.github.com/vvrein/17a32f04d073d406f3f536009d285da7) VIDEO: [mp4](https://user-images.githubusercontent.com/17022100/107888584-f4fab700-6f15-11eb-9fbd-a79129569fed.mp4)

Alacritty exited with ^d:
LOG: [WAYLAND_DEBUG=1 alacritty --class 'launcher'](https://gist.github.com/vvrein/7a89915d6766f8f11e7ad307e16627a2) VIDEO: [mp4](https://user-images.githubusercontent.com/17022100/107888636-4e62e600-6f16-11eb-9bd9-62d09d5f1c99.mp4)


---

```
alacritty --version
alacritty 0.7.1 (a852eb85)
```

**Comment by vvrein** [comment]
Additional info:
```
for_window [app_id="^xfce4-terminal$"] floating enable, resize set width 40 ppt height 100 ppt, move position 0 px 0 px
for_window [app_id="^org.gnome.meld$"] floating enable, resize set width 40 ppt height 100 ppt, move position 0 px 0 px
for_window [app_id="^firefox$"] floating enable, resize set width 40 ppt height 100 ppt, move position 0 px 0 px
```
I also did some tests with `for_window` option on 50205ade and 90fa695 exactly:
warn! external links!
ok 50205ade: [mp4](https://tort.icu/bin/raw/window-resizing.mp4)
not ok 90fa695: [mp4](https://tort.icu/bin/raw/window-resizing-1.mp4)

It feels like after 90fa695 sway forgets to resize window, and only place it in top left corner.
Firefox: was newer resized, constant behavior, ok
xfce4-terminal: resized on 50205ade but not on 90fa695
meld: same as xfce4-terminal

**Comment by vvrein** [comment]
1.1 vs 2.1 differences begin at 210th line

**Comment by kennylevinsen** [comment]
@vvrein Could you try https://github.com/swaywm/sway/pull/6009? It's just been rebased onto master.

I have managed to reproduce locally. The issue seems to be as follows:
1. We see the new app id, and run the resize command
2. We run a transaction and *schedule* a configure for this size
3. We then proceed to process the rest of the incoming messages, which include a buffer commit of a different size
4. We run a resize to the new requested size, scheduling yet another configure
5. As the first configure had not yet been sent, the second one just overwrites it

This kind of setup is one of the general annoyances of trying to treat client buffer sizes as equal to user resize requests.

The referenced PR makes it so that we only send configures for *our* resize requests, and for floating windows just draw what we get. Seems to do the trick locally for me.

**Comment by vvrein** [comment]
Thanks! Gonna chek after 7pm GMT, maybe sooner, if I can.

**Comment by vvrein** [comment]
@kennylevinsen 
So I tested master branch rebased onto [reduce_configure](https://github.com/kennylevinsen/sway/tree/reduce_configure)
It fixes for me everything I mention about, and slightly more: even firefox window began to conform resizing rules :)

**Comment by Xyene** [comment]
https://github.com/swaywm/sway/pull/6009 has been merged, so I think we can close this. Feel free to re-open if this is not the case.

**Comment by vvrein** [comment]
Thanks! 
Just rebuilded from master - works fine :+1:
