### ISSUE TITLE
Proper Fullscreen Functionality

### ISSUE THREAD

**Issue by kushraj** [swaywm/sway#6025]
- **Sway Version:**
  latest-git version

Everytime sway fulscreen is triggered manually, compositor detects it and removes the vertical_offset which is normally used by the status bar ( swaybar in my case) and all the windows in that workspace are shifted up by that offset.

But if you use fullscreen functionality via app itself , like pressing F or F11 key in media players/browser, compositor detects it but does nothing for other windows as opposed to wm fullscreen toggle, 

- **Description:**
toggle sway fullscreen ( mod+f ) vs toggle app fulscreen ( F or F11)

**Comment by Xyene** [comment]
Your bug report is missing debug logs. Please add a link to the full debug log file.

Fullscreen from F11 on Wayland Firefox and F in mpv works, so I imagine this is an application issue.

**Comment by kushraj** [comment]
nvm, stupid mistake on my side :P
