### ISSUE TITLE
Applications (Libreoffice Impress, Firefox) crash when working with large images

### ISSUE THREAD

**Issue by cshapeshifter** [swaywm/sway#6042]
Libreoffice Impress crashes randomly but consistently when working on a slide show with large images embedded. It crashes quickly and with just this message on the command line:
```Gdk-Message: 15:19:54.909: Lost connection to Wayland compositor.```
I can't upload a sample slide show because of GitHub size limitations, but I can easily reproduce the crash via the following steps:

1. Create a new empty Impress slide show.
2. Open the following large image in Firefox: [https://upload.wikimedia.org/wikipedia/commons/4/41/Space_Shuttle_Columbia_launching.jpg](https://upload.wikimedia.org/wikipedia/commons/4/41/Space_Shuttle_Columbia_launching.jpg)
3. Right-click and "Copy Image", switch to Impress and Ctrl-V to insert the picture.
4. Try editing the slide (move the picture, duplicate the slide...)
5. Try saving the slide deck.

It might work fine for a while and not crash immediately. The crash is random, but it happens on average every second time I try to save the document and within less than a minute of trying to edit the slides.

I also had Firefox crash, for example when showing the linked picture in a tab and then opening another split window next to Firefox (so it had to resize). But Firefox crashes less frequently and less consistently. It's usually stable.

Package information:
```
libreoffice-fresh 7.1.0-1
linux 5.10.16.arch1-1
sway 1:1.5.1-1
swayidle 1.6-1
swaylock 1.5-1
wayland 1.19.0-1
wayland-protocols 1.20-1
xorg-xwayland 1.20.0.r844.g1e72c3ce8-1
```
This is a Dell XPS 2-in-1 7390 running Archlinux. I use sway with 'scale 3' on the display output.

**Comment by Xyene** [comment]
I was able to reproduce this crash on Sway master, but also on GNOME (mutter 3.38.3). This sounds like a LibreOffice bug, and should be reported to the LibreOffice developers.
