### ISSUE TITLE
seat <name> hide_cursor when-typing enable does not work

### ISSUE THREAD

**Issue by user18130814200115-2** [swaywm/sway#6047]
IOn the wiki, an alternative to xbanish is given in the command `seat <name> hide_cursor when-typing enable`. Using this setting however gives the error `Error: Invalid hide_cursor command (expected 1 argument, got 2)`

**Comment by emersion** [comment]
I think this feature hasn't been released yet.

**Comment by ymatsiuk** [comment]
Noticed the same. It's not present in man though, but mentioned in wiki section related to migration from i3
