### ISSUE TITLE
Sway Unresponsive

### ISSUE THREAD

**Issue by NickSica** [swaywm/sway#6066]
### Please read the following before submitting:
- Please do NOT submit bug reports for questions. Ask questions on IRC at #sway on irc.freenode.net.
- Proprietary graphics drivers, including nvidia, are not supported. Please use the open source equivalents, such as nouveau, if you would like to use Sway.
- Problems with the Wayland version of Firefox are likely to be Firefox bugs. Start by submitting your issue to the Firefox Bugzilla and come back here only after they confirm otherwise.
- Please do NOT submit issues for information from the github wiki. The github wiki is community maintained and therefore may contain outdated information, scripts that don't work or obsolete workarounds.
  If you fix a script or find outdated information, don't hesitate to adjust the wiki page.

### Please fill out the following:
- **Sway Version:**
  sway version 1.5-bb41b7b8 (Feb 24 2021, branch 'master')

- **Debug Log:**
  https://gist.github.com/NickSica/3bab5f25ca1f16006eb465083193aeeb

- **Configuration File:**
  https://gist.github.com/NickSica/d1132274896355dc37e66998b8b8d1f5

- **Stack Trace:**
  I'm not 100% sure if sway crashes or what the issue is here

- **Description:**
  I run a headless server and use it to program remotely among other things. To get the GUI and VNC server up and running I ssh into the system, open tmux and run sway which then in turn runs vnc. I disconnect and VNC in which works relatively well. It used to get in an unrecoverable state every once in awhile but happens a bit more often now. When I connect, I lose all connection to it. It's still connected to my router(according to my router), but I can't ssh in and I can't access sway or wayvnc. I have to go and manually reboot it in order to use it again. I'm not sure if it's a sway issue or something else, but it only happens when running sway so I thought I'd try my luck here.

**Comment by emersion** [comment]
If you can't SSH in, probably a driver bug. Maybe grab dmesg from last boot and see if there are kernel errors in there?

**Comment by NickSica** [comment]
UFW floods my dmesg logs, is there a way to grab just kernel errors?

**Comment by emersion** [comment]
`grep -v` maybe?

**Comment by NickSica** [comment]
Yeah very little is being printed out because of UFW. Let me turn off UFW logging and reproduce.

**Comment by emersion** [comment]
Note, it's important to get dmesg logs after the hang, otherwise you won't see the potential reason for the hang in the kernel logs.

**Comment by NickSica** [comment]
Does dmesg get wiped on reboot?
<script src="https://gist.github.com/NickSica/2920e25d1e5fc06ea81ebb93de273517.js"></script>

**Comment by emersion** [comment]
Assuming systemd: https://wiki.archlinux.org/index.php/Systemd/Journal#Filtering_output

**Comment by NickSica** [comment]
I'm not 100% sure what I'm looking for but nothing seems to be causing a panic.
https://gist.github.com/NickSica/d3b491757c31b13163dcd5d25e27c8eb

**Comment by NickSica** [comment]
Going from sway-git to sway(and wlroots-git to wlroots) seems to get it to crash less consistently. Before it would hang the system most of the time on startup. Now I have yet to have a hang although I know it does occasionally.

**Comment by NickSica** [comment]
This has gotten significantly worse since the latest updates to master. Nothing of note shows up in the logs.

**Comment by NickSica** [comment]
This seems to be an issue with wlroots so I am closing this.
