### ISSUE TITLE
sway-sensible-terminal

### ISSUE THREAD

**Issue by ollieparanoid** [swaywm/sway#6067]
- **i3 patch:** https://github.com/i3/i3/commit/6420b2b102bab214ad0bf1fa0f5e190f02984e82

- **Description:**
Sway uses alacritty in its default config, without trying to look for other terminals as fallback. Distros may decide to ship another terminal with sway ([postmarketOS discussion](https://gitlab.com/postmarketOS/pmaports/-/issues/984)), it would be nice if we wouldn't need to touch the default config for that.

Would a PR get accepted, which adds a sway-sensible-terminal script?

**Comment by rumpelsepp** [comment]
Personally, I never saw why this script is needed in i3. Basically it always spawns the wrong terminal… The only benefit is that on a new installation at least some terminal for comleting the setup could be spawned with the default shortcut.

**Comment by emersion** [comment]
I don't really like these i3-sensible-* scripts hardcoding a bunch of tool names. I think it's reasonable for downstream to patch the default config.

I'd be open to a build option to set the default terminal emulator.

**Comment by ollieparanoid** [comment]
Okay then, thanks for considering.
