### ISSUE TITLE
GTK2/3 cursor theme not loading

### ISSUE THREAD

**Issue by shoober420** [swaywm/sway#6071]
- **Sway Version:**
  - `sway version 1.5-1afedcb9 (Feb 27 2021, branch master)`

- **Debug Log:**
  - See next comment below

- **Configuration File:**
  - https://gist.github.com/shoober420/59a2713bb09487a935a45ef4341a9d46

- **Description:**
I've been trying to get the Chicago95 cursor theme to work with sway. I have it working great with my pure x11 machine. I've tried numberous things before posting this of course and I will outline them now.

I configured and installed all the gtk2/3 files outlined in the Arch wiki.
https://wiki.archlinux.org/index.php/GTK#Configuration

This is adequate for setting up gtk themes on x11. But even when using lxappearance-gtk2 with sway and setting it up that way, the mouse cursor will not stay to the xcursor theme I selected, Chicago95_Cursor_White. Here are my gtk2/3 configuration files.
https://gist.github.com/shoober420/74dbd782eeae9616d381dc5874ebb162
https://gist.github.com/shoober420/8f931b710e0e48bb661a9bbf34cd4659 (I do properly name this settings.ini when installing.)

I'm going to further explain how the configuration files and lxappearance effect sway in detail. I'm going to use pcmanfm and steam as examples.

On a fresh launch of sway, and starting pcmanfm, the gui-theme, icon-theme, and font-theme will load. What is missing is the cursor-theme. The cursor will remain the default gtk2 raleigh theme. When starting steam, the mouse cursor will remain in the gtk2 raleigh theme.

Launching lxappearance to force the Chicago95_Cursor_White theme will change it when launched, and keep the mouse cursor at the desired theme until closed with pcmanfm. Steam still will switch to the raleigh gtk2 theme even with lxappearance open.

When closing lxappearance, the mouse cursor will return to the black gtk2 raleigh cursor theme. When reopening pcmanfm, the mouse cursor will revert back to the desired Chicago95_Cursor_White theme, and vice versa to the black gtk2 raleigh theme when mousing off the program or switching to another desktop.

I also must mention I also tried editing my sway config and adding in these commands from the GTK3 settings on Wayland. This didnt work either.
https://github.com/swaywm/sway/wiki/GTK-3-settings-on-Wayland

**Comment by shoober420** [comment]
Here is the log.
[swaygtk.txt](https://github.com/swaywm/sway/files/6058407/swaygtk.txt)

I also should mention that on x11, I use xsetroot to further force the Chicago95_Cursor_White theme. Here is my xinitrc file.
https://gist.github.com/shoober420/97bfda60fc39bee9c7021ebc559fccc5

**Comment by shoober420** [comment]
Thanks to fluix on irc with the solution. It makes complete sense now. Steam being the program most effected, is a xwayland application, and this setting specifically mentions Xcursor themes. 

seat seat0 xcursor_theme Chicago95_Cursor_White 0

Now when launching sway, my cursor is always the correct gtk cursor theme, just like when using x11. Im for certain that all the config files mention prior are needed for settings up the gui-theme, icon-theme, and font-theme, so they are still needed.

**Comment by scott092707** [comment]
What does setting the cursor size to "0" do?
IS there only one size of your cursor, so if "0" means "any", 
it would work even if you changed the size of your cursor?

**Comment by shoober420** [comment]
I’m not entirely sure, I’ve seen size 0 for X11 settings as well. I’ve been very busy with some other projects, but i’ll try messing with it some other time.
