### ISSUE TITLE
lid:on event is not triggered when lid is closed

### ISSUE THREAD

**Issue by VRichardJP** [swaywm/sway#6072]
- sway version 1.5.1
- sway debug log: https://gist.github.com/VRichardJP/bec8e6f6a16f794a23301a7def02a834

Hi,

I am trying to setup clamshell mode on my laptop following the wiki instruction (https://github.com/swaywm/sway/wiki#clamshell-mode). However, when I close the laptop lid the laptop won't suspend appropriately:
- when the lid is closed, the computer is still playing music/video
- when I open the lid again swaylock is running as expected 

I have added debug messages to my sway config (see below) to see what happens when I close/open the lid. I observe that the lid:on event is never triggered:

```
$ tail -f /tmp/lid
lid:toggle    <- I closed the lid
lid:off
lid:toggle    <- I open/close the lid again 
lid:off
lid:toggle    <- etc
lid:off
...
```

With my configuration, I would expect to see something like:
```
lid:toggle
lid:on
lid:toggle
lid:off
```

In the meantime the lid state seems to be correctly reported:

```
$ while true; do cat /proc/acpi/button/lid/LID/state && sleep 1; done
state:      open
state:      open
state:      open
state:      open
state:      closed    <- I closed the lid
state:      closed
state:      closed
state:      open
state:      open
state:      open
state:      open
state:      open
state:      open
...
```

The relevant section of my sway config:

- ~/.config/sway/config
```
[...]
exec swayidle -w \
    timeout 300 'swaylock -f' \
    timeout 600 'swaymsg "output * dpms off"' \
         resume 'swaymsg "output * dpms on"' \
    before-sleep 'swaylock -f -c 000000'

set $laptop eDP-1
bindswitch --reload --locked lid:on output $laptop disable
bindswitch --reload --locked lid:off output $laptop enable
bindswitch --reload --locked --no-warn lid:on exec echo "lid:on" >> /tmp/lid
bindswitch --reload --locked --no-warn lid:off exec echo "lid:off" >> /tmp/lid
bindswitch --reload --locked --no-warn lid:toggle exec echo "lid:toggle" >> /tmp/lid
exec_always clamshell_enable $laptop
[...]
```

with the following script clamshell_enable:

- ~/bin/clamshell_enable
```
#!/bin/sh
if [[ $# -eq 0 ]]; then
  echo "missing display identifier"
  exit 1
fi

LAPTOP=$1
if grep -q open /proc/acpi/button/lid/LID/state; then
  swaymsg output $LAPTOP enable
else
  swaymsg output $LAPTOP disable
fi
```

systemd is configured to suspend then hibernate on lid close:

- /etc/systemd/logind.conf (default values):
```
[...]
#HandleLidSwitch=suspend
#HandleLidSwitchExternalPower=suspend
#HandleLidSwitchDocked=ignore
[...]
```

- /etc/systemd/sleep.conf
```
[Sleep]
suspend=suspend-then-hibernate
HibernateDelaySec=10min
[...]
```

Thanks in advance

**Comment by VRichardJP** [comment]
Looking at the code, I have realized that lid:on/off and lid:toggle are actually in conflict and the bindswitch won't work properly if both are used. When I only have:
```
bindswitch --reload --locked lid:on exec echo "lid:on" >> /tmp/lid
bindswitch --reload --locked lid:off exec echo "lid:off" >> /tmp/lid
```
I correctly get:
```
tail -f /tmp/lid
lid:on
lid:off
```

However, my issue is still present when I only have the following:
```
set $laptop eDP-1
bindswitch --reload --locked lid:on output $laptop disable
bindswitch --reload --locked lid:off output $laptop enable
exec_always clamshell_enable $laptop
```

The laptop still fails to suspend on lid close

**Comment by kennylevinsen** [comment]
> The laptop still fails to suspend on lid close

The commands provided will not suspend the laptop, they just disable/enable the output. Does the output not disable/enable as it should?

If you want the machine to suspend, you'll have to run a command that will do that.

**Comment by VRichardJP** [comment]
After spending some more time on debugging this I finally made it work. I am not sure exactly why, but I have a few clues:
- I think the laptop was actually suspending on lid close (by systemd), then was instantly woken up by _something_
- this _something_ may be this 'trick' I copied/pasted from somewhere to deal with sway locking the screen while some application was running fullscreen:
```
for_window [class="^.*"] inhibit_idle fullscreen
for_window [app_id="^.*"] inhibit_idle fullscreen
```
I have removed these two lines and I have not had any suspend issue since then. 
May it be this totally breaks swaylock?

I also experienced a couple sway segfaults with these 2 lines when I was trying to suspend the laptop

**Comment by kennylevinsen** [comment]
> I also experienced a couple sway segfaults with these 2 lines when I was trying to suspend the laptop

Please file bugs for crashes separately.

> I have removed these two lines and I have not had any suspend issue since then.

Those lines will stop e.g. swayidle from considering the session idle when anything is fullscreen, and thus won't run any actions nor inform logind that the system is idle.

That might affect action execution, but logind actions are quirky and uses weird/broken heuristics. Use at own risk.
