### ISSUE TITLE
Changing tab with mouse click is not working anymore

### ISSUE THREAD

**Issue by Moonlight-Angel** [swaywm/sway#6074]
- **sway version:** 1.5-d358aab8 (Mar  2 2021, branch 'master')

- **Description:**
After upgrading to the latest commit on `master`, it looks like I'm not able to change tabs with mouse click anymore.
I'm not able to find a commit that would indicate a change of behavior, so I'm not sure if it's intended behavior.

- **Quick steps to reproduce**
  - Switch to tab or stacked layout
  - Open 2 or more windows
  - Try changing tab focus with mouse clicks

**Comment by tsdh** [comment]
I can confirm that.  It also affects the stacked layout.

**Comment by kennylevinsen** [comment]
Observations from quick local test:

1. It works for floating containers.
2. It works for *unfocused* tiling containers - sneaking the cursor in from the top without touching the surface content to click a titlebar works.
3. It does not work for *focused* tiling containers.

Sounds like an edge-case in focus handling or the default seat ops.

**Comment by kuon** [comment]
Also, if grabbing/drag the tab that is not focused and moving it, it actually moves the focused tab.

**Comment by Xyene** [comment]
I'm on 1afedcb94c0517b5434e2220e63b997cf01427bd and things work. So, maybe a6544f5a64e5d0899555795915d9a05f7bb09f9c or d358aab8d9dd6121533326423759394ca804a05a?

**Comment by kennylevinsen** [comment]
> I'm on [1afedcb](https://github.com/swaywm/sway/commit/1afedcb94c0517b5434e2220e63b997cf01427bd) and things work. So, maybe [a6544f5](https://github.com/swaywm/sway/commit/a6544f5a64e5d0899555795915d9a05f7bb09f9c) or [d358aab](https://github.com/swaywm/sway/commit/d358aab8d9dd6121533326423759394ca804a05a)?

Indeed, the latter met a quirk in view_container_at.

https://github.com/swaywm/sway/pull/6077 should fix it.

**Comment by tsdh** [comment]
I can confirm it is fixed now.
