### ISSUE TITLE
Incorrect monitor geometry/refresh rates sent to floating mpv windows in multi-monitor configurations.

### ISSUE THREAD

**Issue by Dudemanguy** [swaywm/sway#6080]
It seems like floating windows in sway can receive incorrect monitor information. It should happen to any wayland client, but mpv is a pretty easy way to see it go wrong.

- **Sway Version:** 1.5-d358aab8 (git master)
- **Debug Log:** https://0x0.st/-Pup.log
- **Configuration File:** Everything default, you just need `for_window [app_id="mpv"] floating enable` in there.
- **Description:**
  - Have a multi-monitor setup; preferably with different resolutions and refresh rates.
  - Launch an mpv window (it should be floating as per above config).
  - Set to fullscreen (press 'f').
  - Press "i" to look at the stats menu and observe badly rendered text (this is because mpv is told the resolution/dpi of the other monitor).
  - Observe that the reported display fps is incorrect (if you have two monitors, it will report the fps of the other one; no clue what happens if you have more).

I bisected this and it actually started with #5812 (ironic because that actually fixed another bug easily seen with mpv). It looks like the xdg_shell logic has changed since then but the issue still occurs. I'm not aware of the details but something `view_update_size` does in `handle_commit`[¹](https://github.com/swaywm/sway/blob/master/sway/desktop/xdg_shell.c#L302) seems to cause this. This only happens with floating windows. Nothing else is affected.

**Comment by kennylevinsen** [comment]
Observations:

- [wlhax](https://git.sr.ht/~kennylevinsen/wlhax) reveals that the mpv surface enters two outputs when full-screened from floating. Although perfectly valid (a window can overlap multiple screens), this definitely wasn't the intention from our end.
- The fullscreen surface can be moved (???) using floating modifiers. Not sure what that's about. It snaps to another output when it's more than 50% moved.

However, if mpv doesn't know what *resolution* to render to in this state, I would say that's an mpv bug revealed by the above.

The output resolution should not be used for anything. The only relevant numbers to a fullscreen surface is the size sent in the configure event, and the output *scale*. If there is overlap with outputs of multiple scales, it should just render at the highest scale.

**Comment by Dudemanguy** [comment]
>The fullscreen surface can be moved (???) using floating modifiers. Not sure what that's about. It snaps to another output when it's more than 50% moved.

Yeah that was our bug. We were sending move request when we shouldn't be. It was fixed recently.

>The output resolution should not be used for anything. The only relevant numbers to a fullscreen surface is the size sent in the configure event, and the output scale. If there is overlap with outputs of multiple scales, it should just render at the highest scale.

Right, the actual video resolution is whatever it receives in the configure event. However, the lua stuff uses internal mpv properties obtained from various windowing backends. So in this case its calculated using wrong geometry which is why it looks bad/blurry.

**Comment by kennylevinsen** [comment]
> Yeah that was our bug. We were sending move requests when we shouldn't be. It was fixed recently.

It's also our job to ignore them, so we can split the blame. :)

If it's moved using surface attach point, then maybe the cause is that a non-zero attach delta is offsetting the surface away from the output? We're known to handle these incorrectly.

My other bet would a geometry issue such as border overflowing to the neighboring outputs (doesn't have to be rendered, could just be messed up math).

**Comment by Dudemanguy** [comment]
So I looked this again and nailed down the culprit here. Well not the gory details, but the overview of what's happening. When a floating window in sway gets fullscreened, sway thinks it enters the output of other monitor and sends an event ([log](https://0x0.st/-mnZ.log)).

>00:00:20.844 [DEBUG] [sway/tree/container.c:1258] Container 0x556e567e07a0 entered output 0x556e5617c330

So that means at this [conditional](https://github.com/swaywm/sway/blob/master/sway/tree/container.c#L1256), no index from `list_find` is returned and `intersects` is true. So probably at least one of those things shouldn't happen (or maybe even both; not sure).

**Comment by kennylevinsen** [comment]
> So that means at this [conditional](https://github.com/swaywm/sway/blob/master/sway/tree/container.c#L1256), no index from `list_find` is returned and `intersects` is true. So probably at least one of those things shouldn't happen (or maybe even both; not sure).

This logic is fine. The intersect indicates that the container overlaps with the output and so needs to be present on it. The missing index indicates that the container has not yet entered the output and so it needs to send and enter event.

The problem is that the container geometry is overlapping with the extra output, leading to the intersect being true.
