### ISSUE TITLE
Build fail on master

### ISSUE THREAD

**Issue by LeForjeron** [swaywm/sway#6086]
Using sway master and wlroots 0.12.0, building on kiss-linux using musl :

`sway/input/text_input.c: in function relay_send_im_state :
error : WLR_TEXT_INPUT_V3_FEATURES_CONTENT_TYPE undeclared`

It looks like there is a typo in the definition which is named WLR_TEXT_INPUT_v3_FEATURES_CONTENT_TYPE. (Notice the lowercase v)

**Comment by emersion** [comment]
Master sway requires master wlroots.
