### ISSUE TITLE
Setuid Issues

### ISSUE THREAD

**Issue by LeForjeron** [swaywm/sway#6090]
Using sway master, wlroots master, kiss linux with musl.
I compiled sway without logind or elogind support. I ran `chmod a+s /usr/local/bin/sway` after the installation.
When I start sway as root I get the `Unable to drop root (we shouldn't be able to restore it after setuid), refusing to start` error.
When I start sway as a regular user (in the input and video group), the screen freeze (but I can still ssh into the computer).
When I check the log, I got these errors :
`00:00:00.089 [INFO] [wlr] [wayland] unable to open lockfile /run/user/1000/wayland-1.lock check permissions
00:00:00.089 [INFO] [wlr] [wayland] unable to open lockfile /run/user/1000/wayland-2.lock check permissions
00:00:00.089 [INFO] [wlr] [wayland] unable to open lockfile /run/user/1000/wayland-3.lock check permissions
00:00:00.089 [INFO] [wlr] [wayland] unable to open lockfile /run/user/1000/wayland-4.lock check permissions
00:00:00.089 [INFO] [wlr] [wayland] unable to open lockfile /run/user/1000/wayland-5.lock check permissions
00:00:00.089 [INFO] [wlr] [wayland] unable to open lockfile /run/user/1000/wayland-6.lock check permissions
00:00:00.089 [INFO] [wlr] [wayland] unable to open lockfile /run/user/1000/wayland-7.lock check permissions
00:00:00.089 [INFO] [wlr] [wayland] unable to open lockfile /run/user/1000/wayland-8.lock check permissions
00:00:00.089 [INFO] [wlr] [wayland] unable to open lockfile /run/user/1000/wayland-9.lock check permissions
00:00:00.089 [INFO] [wlr] [wayland] unable to open lockfile /run/user/1000/wayland-10.lock check permissions
00:00:00.089 [INFO] [wlr] [wayland] unable to open lockfile /run/user/1000/wayland-11.lock check permissions
00:00:00.089 [INFO] [wlr] [wayland] unable to open lockfile /run/user/1000/wayland-12.lock check permissions
00:00:00.089 [INFO] [wlr] [wayland] unable to open lockfile /run/user/1000/wayland-13.lock check permissions
00:00:00.089 [INFO] [wlr] [wayland] unable to open lockfile /run/user/1000/wayland-14.lock check permissions
00:00:00.089 [INFO] [wlr] [wayland] unable to open lockfile /run/user/1000/wayland-15.lock check permissions
00:00:00.089 [INFO] [wlr] [wayland] unable to open lockfile /run/user/1000/wayland-16.lock check permissions
00:00:00.089 [INFO] [wlr] [wayland] unable to open lockfile /run/user/1000/wayland-17.lock check permissions
00:00:00.089 [INFO] [wlr] [wayland] unable to open lockfile /run/user/1000/wayland-18.lock check permissions
00:00:00.089 [INFO] [wlr] [wayland] unable to open lockfile /run/user/1000/wayland-19.lock check permissions
00:00:00.089 [INFO] [wlr] [wayland] unable to open lockfile /run/user/1000/wayland-20.lock check permissions
00:00:00.089 [INFO] [wlr] [wayland] unable to open lockfile /run/user/1000/wayland-21.lock check permissions
00:00:00.089 [INFO] [wlr] [wayland] unable to open lockfile /run/user/1000/wayland-22.lock check permissions
00:00:00.089 [INFO] [wlr] [wayland] unable to open lockfile /run/user/1000/wayland-23.lock check permissions
00:00:00.089 [INFO] [wlr] [wayland] unable to open lockfile /run/user/1000/wayland-24.lock check permissions
00:00:00.089 [INFO] [wlr] [wayland] unable to open lockfile /run/user/1000/wayland-25.lock check permissions
00:00:00.089 [INFO] [wlr] [wayland] unable to open lockfile /run/user/1000/wayland-26.lock check permissions
00:00:00.089 [INFO] [wlr] [wayland] unable to open lockfile /run/user/1000/wayland-27.lock check permissions
00:00:00.089 [INFO] [wlr] [wayland] unable to open lockfile /run/user/1000/wayland-28.lock check permissions
00:00:00.089 [INFO] [wlr] [wayland] unable to open lockfile /run/user/1000/wayland-29.lock check permissions
00:00:00.090 [INFO] [wlr] [wayland] unable to open lockfile /run/user/1000/wayland-30.lock check permissions
00:00:00.090 [INFO] [wlr] [wayland] unable to open lockfile /run/user/1000/wayland-31.lock check permissions
00:00:00.090 [INFO] [wlr] [wayland] unable to open lockfile /run/user/1000/wayland-32.lock check permissions
00:00:00.090 [ERROR] [sway/server.c:177] Unable to open wayland socket`

Should I install sudo and run `sudo sway` as a regular user ?

**Comment by LeForjeron** [comment]
Test with sudo, and as I expected I also got the `Unable to drop root (we shouldn't be able to restore it after setuid), refusing to start` error

**Comment by emersion** [comment]
Sway should be run from a regular user.

Can you check if your user can write to `/run/user/1000/`?

**Comment by LeForjeron** [comment]
That was it ! Actually my XDG_RUNTIME_DIR was set to `/run/user/1000` but the permissions were not set properly.
Thank you !
