### ISSUE TITLE
Silence error message regarding IconThemePath property?

### ISSUE THREAD

**Issue by piyueh** [swaywm/sway#6092]
### Please read the following before submitting:
- We are not accepting any new window management features unless they get implemented by i3.

### Please fill out the following:
- **Description:**
  #3249 uses `IconThemePath` property from a `StatusNotifierItem` object. And as that PR denotes, `IconThemePath` is not in [XDG's specification](https://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/StatusNotifierItem/#org.freedesktop.statusnotifieritem.tooltip). It's from [KDE](https://github.com/KDE/kde-workspace/commit/a54f9ec9dbbe7001f5a38c15c7c7371ab0932b1b). That is to say, many applications that only follow XDG's specification do not have `IconThemePath`. For example, I think those using qt5 do not have `IconThemePath` (though those using qt4 and sni-qt do).

  When Sway encounters applications that do not implement `IconThemePath`, it dumps a lot of error messages in syslog (through function `sni_get_property_async`, ~[line 182](https://github.com/swaywm/sway/blob/bc239b2f6b0cf9d29adb8df7e464e7d104cad4bb/swaybar/tray/item.c#L182)~ [line 121](https://github.com/swaywm/sway/blob/bc239b2f6b0cf9d29adb8df7e464e7d104cad4bb/swaybar/tray/item.c#L121-L123)). These messages are somehow annoying. Is it possible to silence messages regarding `IconThemePath`? Or at least lowering down the importance of the messages so that the messages are only printed when we use `--debug` flag?

Thanks!

**Comment by emersion** [comment]
Sounds reasonable to me. Would you be willing to send a PR?

**Comment by piyueh** [comment]
Yes, I can do that.

**Comment by nmschulte** [comment]
I've been wondering about this message/property myself; thank you for detailing @piyueh.
