### ISSUE TITLE
Sway blocks during startup / fails to take /dev/dri/card0

### ISSUE THREAD

**Issue by lovesegfault** [swaywm/sway#6096]
### Please fill out the following:
- **Sway Version:**
  - `sway version 1.5.1`
  - `e5913f81064d4c5b89cdab0cd75d2b5ff5a47c48` with wlroots `44fa2c4b49ced30a69e86a2ed78dd9bf62e0fbb3`

- **Debug Log:**
Stable run ([full logs](https://gist.github.com/bda488c264ba0a6c7419a2c54982bfb7)):
```
00:00:00.000 [sway/main.c:326] Sway version 1.5.1
00:00:00.002 [sway/main.c:153] Linux hegel 5.11.5 #1-NixOS SMP Tue Mar 9 10:21:23 UTC 2021 x86_64 GNU/Linux
00:00:00.002 [sway/main.c:169] Contents of /etc/os-release:
00:00:00.002 [sway/main.c:153] NAME=NixOS
00:00:00.002 [sway/main.c:153] ID=nixos
00:00:00.002 [sway/main.c:153] VERSION="21.05.20210312.d7bae4c (Okapi)"
00:00:00.002 [sway/main.c:153] VERSION_CODENAME=okapi
00:00:00.002 [sway/main.c:153] VERSION_ID="21.05.20210312.d7bae4c"
00:00:00.002 [sway/main.c:153] PRETTY_NAME="NixOS 21.05 (Okapi)"
00:00:00.002 [sway/main.c:153] LOGO="nix-snowflake"
00:00:00.002 [sway/main.c:153] HOME_URL="https://nixos.org/"
00:00:00.002 [sway/main.c:153] DOCUMENTATION_URL="https://nixos.org/learn.html"
00:00:00.002 [sway/main.c:153] SUPPORT_URL="https://nixos.org/community.html"
00:00:00.002 [sway/main.c:153] BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
00:00:00.002 [sway/main.c:141] LD_LIBRARY_PATH=(null)
00:00:00.002 [sway/main.c:141] LD_PRELOAD=(null)
00:00:00.002 [sway/main.c:141] PATH=/run/wrappers/bin:/home/bemeurer/.nix-profile/bin:/etc/profiles/per-user/bemeurer/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin
00:00:00.002 [sway/main.c:141] SWAYSOCK=(null)
00:00:00.002 [sway/server.c:43] Preparing Wayland server initialization
00:00:00.071 [INFO] [backend/session/logind.c:839] Waiting for 'CanGraphical' on seat seat0
00:02:50.460 [INFO] [backend/session/logind.c:853] Successfully loaded logind session
00:02:50.462 [INFO] [backend/backend.c:157] Found 1 GPUs
00:02:50.462 [INFO] [backend/drm/backend.c:138] Initializing DRM backend for /dev/dri/card0 (amdgpu)
00:02:50.462 [DEBUG] [backend/drm/drm.c:70] Using atomic DRM interface
00:02:50.462 [INFO] [backend/drm/drm.c:255] Found 6 DRM CRTCs
00:02:50.462 [INFO] [backend/drm/drm.c:176] Found 13 DRM planes
00:02:50.595 [INFO] [render/egl.c:297] Using EGL 1.5
...
```

Master Run:
```
00:00:00.000 [INFO] [sway/main.c:346] Sway version 1.5
00:00:00.002 [INFO] [sway/main.c:154] Linux hegel 5.11.5 #1-NixOS SMP Tue Mar 9 10:21:23 UTC 2021 x86_64 GNU/Linux
00:00:00.002 [INFO] [sway/main.c:170] Contents of /etc/os-release:
00:00:00.002 [INFO] [sway/main.c:154] NAME=NixOS
00:00:00.002 [INFO] [sway/main.c:154] ID=nixos
00:00:00.002 [INFO] [sway/main.c:154] VERSION="21.05.20210312.d7bae4c (Okapi)"
00:00:00.002 [INFO] [sway/main.c:154] VERSION_CODENAME=okapi
00:00:00.002 [INFO] [sway/main.c:154] VERSION_ID="21.05.20210312.d7bae4c"
00:00:00.002 [INFO] [sway/main.c:154] PRETTY_NAME="NixOS 21.05 (Okapi)"
00:00:00.002 [INFO] [sway/main.c:154] LOGO="nix-snowflake"
00:00:00.002 [INFO] [sway/main.c:154] HOME_URL="https://nixos.org/"
00:00:00.002 [INFO] [sway/main.c:154] DOCUMENTATION_URL="https://nixos.org/learn.html"
00:00:00.002 [INFO] [sway/main.c:154] SUPPORT_URL="https://nixos.org/community.html"
00:00:00.002 [INFO] [sway/main.c:154] BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
00:00:00.002 [INFO] [sway/main.c:142] LD_LIBRARY_PATH=
00:00:00.002 [INFO] [sway/main.c:142] LD_PRELOAD=
00:00:00.002 [INFO] [sway/main.c:142] PATH=/run/wrappers/bin:/home/bemeurer/.nix-profile/bin:/etc/profiles/per-user/bemeurer/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin
00:00:00.002 [INFO] [sway/main.c:142] SWAYSOCK=
00:00:00.002 [DEBUG] [sway/server.c:49] Preparing Wayland server initialization
00:00:00.002 [INFO] [wlr] [backend/session/logind.c:572] Selecting session from XDG_SESSION_ID: 6
00:00:00.005 [INFO] [wlr] [backend/session/logind.c:706] Successfully loaded logind session
00:00:00.005 [ERROR] [wlr] [backend/session/logind.c:74] Failed to take device '/dev/dri/card0': No such device
00:00:00.005 [ERROR] [wlr] [backend/session/session.c:307] Unable to open /dev/dri/card0 as DRM device
00:00:00.005 [INFO] [wlr] [backend/backend.c:167] Found 0 GPUs
00:00:00.005 [ERROR] [wlr] [backend/backend.c:312] Failed to open any DRM device
00:00:00.057 [ERROR] [sway/server.c:55] Unable to create backend
```

- **Configuration File:**
https://gist.github.com/56fc7b7e5c4a7c46d1e3f30a9cddc479

- **Description:**
I just built a new system with an AMD RX 6800 XT GPU. Before this I ran Sway on a laptop with an AMD RX 6700 attached via TB3 and the same configuration.

With stable sway (1.5.1) starting up takes a long time, as sway seems to get blocked on `00:00:00.072 [INFO] [backend/session/logind.c:839] Waiting for 'CanGraphical' on seat seat0`. It eventually unblocks (takes ~3 minutes) and after that sway works flawlessly. I mentioned this in #5824 and was asked to try master sway/wlroots.

With the latest commit of sway, it instead fails to start altogether with, as the logs above mention, failing to take `/dev/dri/card0`. Nothing else changed between the runs of sway stable and latest, and I verified that that the card indeed was present there.

Unclear to me whether the long delay in starting stable sway and the failure to start the latest commit are related. I'm happy to do any further testing that may be necessary.

**Comment by emersion** [comment]
Can you upload a `dmesg` log too?

**Comment by lovesegfault** [comment]
> Can you upload a `dmesg` log too?

Here you go: https://gist.github.com/943e98136b78502d150935404af5cc9b

It includes a few hours of it running since I booted it yesterday. Let me know if you'd like `dmesg` from a fresh boot with either stable or latest sway.

**Comment by lovesegfault** [comment]
Turns out I had forgotten to enable OpenGL on my system, once I did that, sway starts right away. Testing master now.

**Comment by lovesegfault** [comment]
I can confirm that with OpenGL properly setup `sway master` starts and works fine.

Leaving whether or not to keep this bug open up to you, @emersion, since I think there are two open questions:

1. Is the long delay when OpenGL isn't setup expected/okay?
2. Is the failure in master expected/okay?

**Comment by 0x450x6c** [comment]
Faced the same issue on a test nixos VM (qemu).

Setting `virtualisation.kvmgt.vgpus = true` helped.

**Comment by emersion** [comment]
How do you "enable OpenGL" on your system?

**Comment by johnae** [comment]
On NixOS you "enable OpenGL" through the NixOS declarative configuration system like this:

https://search.nixos.org/options?channel=20.09&show=hardware.opengl.enable&from=0&size=50&sort=relevance&query=opengl

When `enable = true` it will symlink the shared libraries to `/run/opengl-driver/lib` and add that path to the `LD_LIBRARY_PATH` session variable. It all happens here: 

https://github.com/NixOS/nixpkgs/blob/60b18a066e8ce5dd21ebff5324345d3586a67ad9/nixos/modules/hardware/opengl.nix#L127

**Comment by emersion** [comment]
Hm. Not sure if we can do anything better to make it clearer what's happening. I don't know where that ENODEV is coming from.
