### ISSUE TITLE
Wrong touchscreen position causes wierd cursor / finger placement.

### ISSUE THREAD

**Issue by KoalaV2** [swaywm/sway#6106]
Unsure if this is a issue with just Wayland or sway but every time i use a touchscreen with another monitor connected it's in a odd placement, for example if i thought the top ish eft of my screen it goes into the second monitor even though it should still be on the first one, video included: https://imgur.com/a/pJeP37H

Now on xorg the fix for this issue is: https://wiki.archlinux.org/index.php/Touchscreen#Using_a_touchscreen_in_a_multi-head_setup But I haven't found anything similar for Wayland / sway.

**Comment by emersion** [comment]
Similarly to Xorg, you need to add `input XXX map_to_output YYY` to your config.

Note, Sway master should be able to automatically do that for you if you have a built-in touchscreen.

**Comment by KoalaV2** [comment]
Oh alright, so it should be auto doing that? Cause if so it's no on my T480s with a integrated touchscreen

**Comment by KoalaV2** [comment]
But hey, the map_to_output thing works, thank!

**Comment by emersion** [comment]
First, are you running Sway master?

Then, can you run these commands:

```
swaymsg -t get_outputs
udevadm info /sys/class/input/event*/
```

**Comment by KoalaV2** [comment]
Yeah I am, and sure 
```Output eDP-1 'Unknown 0x103D 0x00000000' (focused)
  Current mode: 1920x1080 @ 60.006001 Hz
  Position: 0,0
  Scale factor: 1.000000
  Scale filter: nearest
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 1
  Max render time: off
  Adaptive sync: disabled
  Available modes:
    1920x1080 @ 60.006001 Hz```
    udevadm: https://termbin.com/ckq6

**Comment by emersion** [comment]
Ah, the touchscreen is wired up via USB, so we can't auto-detect that it's internal:

```
P: /devices/pci0000:00/0000:00:14.0/usb1/1-10/1-10:1.0/0003:2386:432E.0002/input/input9/event5
N: input/event5
L: 0
S: input/by-id/usb-Raydium_Corporation_Raydium_Touch_System-event-if00
S: input/by-path/pci-0000:00:14.0-usb-0:10:1.0-event
E: DEVPATH=/devices/pci0000:00/0000:00:14.0/usb1/1-10/1-10:1.0/0003:2386:432E.0002/input/input9/event5
E: DEVNAME=/dev/input/event5
E: MAJOR=13
E: MINOR=69
E: SUBSYSTEM=input
E: USEC_INITIALIZED=22975539
E: ID_INPUT=1
E: ID_INPUT_TOUCHSCREEN=1
E: ID_INPUT_WIDTH_MM=320
E: ID_INPUT_HEIGHT_MM=180
E: ID_VENDOR=Raydium_Corporation
E: ID_VENDOR_ENC=Raydium\x20Corporation
E: ID_VENDOR_ID=2386
E: ID_MODEL=Raydium_Touch_System
E: ID_MODEL_ENC=Raydium\x20Touch\x20System
E: ID_MODEL_ID=432e
E: ID_REVISION=0108
E: ID_SERIAL=Raydium_Corporation_Raydium_Touch_System
E: ID_TYPE=hid
E: ID_BUS=usb
E: ID_USB_INTERFACES=:030000:
E: ID_USB_INTERFACE_NUM=00
E: ID_USB_DRIVER=usbhid
E: ID_PATH=pci-0000:00:14.0-usb-0:10:1.0
E: ID_PATH_TAG=pci-0000_00_14_0-usb-0_10_1_0
E: LIBINPUT_DEVICE_GROUP=3/2386/432e:usb-0000:00:14.0-10
E: DEVLINKS=/dev/input/by-id/usb-Raydium_Corporation_Raydium_Touch_System-event-if00 /dev/input/by-path/pci-0000:00:14.0-usb-0:10:1.0-event
```

**Comment by KoalaV2** [comment]
Ahhh alright, yeah the "fix" you sent earlier worked well enough though, so that's good enough for me.
