### ISSUE TITLE
Chromium/Electron apps don't receive focus under xwayland

### ISSUE THREAD

**Issue by Synthetica9** [swaywm/sway#6107]
### Please fill out the following:
- **Sway Version:**
  - `sway version 1.6-rc1`
  - On NixOS, using https://github.com/NixOS/nixpkgs/pull/116544

- **Debug Log:**
  - ~~(I got the following: ```00:00:00.004 [sway/main.c:355] Detected both options and positional arguments. If you are trying to use the IPC client, options are not supported. Otherwise, check the provided arguments for issues. See `man 1 sway` or `sway -h` for usage. If you are trying to generate a debug log, use `sway -d 2>sway.log`.``` I don't know if that's also a bug or something in NixOS. In any case, @emersion was able to reproduce on IRC.)~~ I'm an idiot, shell redirection works differently under `fish` so it parsed the 2 as an argument to `sway` instead of `2>` as "redirect stderr" 

- **Configuration File:**
  - Reproducible with default config

- **Description:**
  - Open any window (ex. alacritty)
  - Open a chromium/vscodium/... window _without_ ozone-platform wayland
  - Expected: the chromium window has focus. Reality: the alacritty window still has focus. This is a regression from 1.5.

cc @emersion @kennylevinsen

**Comment by Ghosthree3** [comment]
I'm not sure if it's the same bug but I can cause the exact same behavior opening an image with `imv-x11` and `sxiv`.
`imv-wayland` works as expected, xwayland problem in general?

**Comment by Synthetica9** [comment]
> xwayland problem in general?

It's definitely not _all_ xwayland apps either; opening xterm for example doesn't trigger this behavior. I can also reproduce with `sxiv` though, good find!

**Comment by emersion** [comment]
Should be fixed by https://github.com/swaywm/wlroots/pull/2813.
