### ISSUE TITLE
Executing some apps leads to wayland crash

### ISSUE THREAD

**Issue by kinshakov** [swaywm/sway#6108]
### Please fill out the following:
Arch Linux.
sway version 1.5.1

- **Debug Log:**
```
00:00:03.577 [INFO] [xwayland/server.c:92] WAYLAND_SOCKET=25 Xwayland :0 -rootless -terminate -listen 22 -listen 24 -wm 58
(WW) Option "-listen" for file descriptors is deprecated
Please use "-listenfd" instead.
(WW) Option "-listen" for file descriptors is deprecated
Please use "-listenfd" instead.
glamor: No eglstream capable devices found
00:00:03.645 [DEBUG] [types/wlr_surface.c:666] New wlr_surface 0x55c8a6d02950 (res 0x55c8a6d02d00)
00:00:03.645 00:00:03.645 [DEBUG] [xwayland/server.c:343] sent SIGUSR1 to process 6000
(EE) failed to read Wayland events: Broken pipe
Gdk-Message: 13:50:08.615: Error reading events from display: Broken pipe
[2021-03-18 13:50:08.615] [error] Workspaces: Unable to receive IPC header
Gdk-Message: 13:50:08.615: Error reading events from display: Broken pipe
```

- **Description:**
This happens if I start some apps right after sway is started. But if I wait some time (approx 30 seconds or more) the apps start normally. For example, midnight commander from termite. Or telegram-desktop.
 And if I add in sway config "xwayland disable" every app starts without falling back to tty.
 With this issue there is impossible to start sway with "exec telegram-desktop" string in its config, until uncomment "xwayland disable". Or need to wait 30 sec after sway strarts and execute the telegram or mc manually.

**Comment by emersion** [comment]
Please try sway master.

See https://github.com/swaywm/sway/wiki/Development-Setup#compiling-as-a-subproject

**Comment by kinshakov** [comment]
> Please try sway master.
> 
> See https://github.com/swaywm/sway/wiki/Development-Setup#compiling-as-a-subproject

Removed native packages (sway, swaybg and wlroots).

Installed from aur:
swaybg-git
wlroots-git
sway-git.

```
swaymsg -t get_version
sway version 1.6-rc1-6059c744 (Mar 18 2021, branch 'master')
```
The apps are starting ok now. Should I wait for native packages will be fixed? Or this issue will be permanent?

**Comment by emersion** [comment]
A new Sway version will be released in the coming weeks. Should fix it.

**Comment by jokeyrhyme** [comment]
For me, the crashes seem to happen if I launch apps in quick succession

- Firefox, wait 2 seconds, Discord, crash
- Firefox, wait 15 seconds, Discord, fine

**Comment by xTpx** [comment]
Firefox For me this is totally random, sometimes it's saving a file, or playing video, or dragging a picture. Every day it quit due to crash. 
`````
(firefox:30763): Gdk-CRITICAL **: 16:08:59.091: gdk_wayland_window_remove_frame_callback_surface: assertion 'surface != NULL' failed
Gdk-Message: 16:18:09.906: Error reading events from display: 断开的管道
Exiting due to channel error.

`````

**Comment by emersion** [comment]
This is a Firefox crash. Please report it to the Firefox bug tracker.
