### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by kamushadenes** [swaywm/sway#6112]
I just wanted to say thank you.

Having used i3 for several years and getting addicted to tilling WMs, I always felt it a little bit clunky, but never could tell why. It's an excellent piece of software.

Discovering Wayland, I finally figured out the problem was Xorg. Wayland in general just feel a lot smoother, and now my daily driver is a NixOS with Sway and Waybar, and honestly, after so much time in Linux (over 10 years), I have never been happier.

I have everything (snippets, notes, tasks, applications) just a few keystrokes away, with a lot of information present all the time through Waybar and a bunch of custom modules.

So thank you, a thousand times. You greatly improved my life quality, helped me in organizing all aspects of it, and overall made me a much happier security specialist.

<3 

EDIT: clearly not a bug, but I can't edit the label

**Comment by keis** [comment]
sway is doing the "impossible" by setting a separate keyboard layout for my 2fa key. Thank you :)

**Comment by emersion** [comment]
Glad you like it! :heart:
