### ISSUE TITLE
Completely turn off output if `output * dpms off` is toggled

### ISSUE THREAD

**Issue by KoalaV2** [swaywm/sway#6117]
Currently if I put my laptop lid down or run `swaymsg "output eDP-1 dpms on" ` the laptop screen turns off / black but the workspaces are still active and i can still move my mouse cursor over to said screen, which is not that great for "clamshell" mode when the laptop lid is closed down but the system is still powered on, is this is a bug or is there any "fix" for this?

**Comment by emersion** [comment]
Use `output XXX disable`

**Comment by emersion** [comment]
Please ask questions like this on IRC.

**Comment by KoalaV2** [comment]
Sorry! And thank you, will keep it in irc from now on
