### ISSUE TITLE
Subsurfaces with odd width or height are not displayed with scale factor > 1

### ISSUE THREAD

**Issue by zsolt-donca** [swaywm/sway#6136]
**Description:**

On recent Sway+wlroots, sub-surfaces with either an odd width, or and odd height isn't displayed by Sway, when the scale factor is > 1. Originates from https://codeberg.org/dnkl/foot/issues/409 , see in particular comment https://codeberg.org/dnkl/foot/issues/409#issuecomment-184702.

Affects only recent `master` builds of `sway` and `wlroots`, seems to work well with the latest `sway` and `wlroots` releases.

Steps to reproduce:

0. Have a scaled output (e.g. factor of 2)
1. Open `foot`
2. Echo some URLs as described in https://codeberg.org/dnkl/foot/issues/409
3. Press CTRL+SHIFT+u to enter the URL highlight mode; press `t` also for additional labels. See https://codeberg.org/dnkl/foot/issues/409#issuecomment-184436 for exactly what is the desired behavior.

**Sway Version:**
I am on Arch Linux and using the [sway-git](https://aur.archlinux.org/packages/sway-git/) and [wlroots-git](https://aur.archlinux.org/packages/wlroots-git/) packages. As of writing this, I am on https://github.com/swaywm/sway/commit/d79ea9a0db11abbdad1e751326a06d6d48332f07 and https://github.com/swaywm/wlroots/commit/d9cae04ffc3140408f2604eeff7d4776fe8d9548.

```
❯ swaymsg -t get_version
sway version 1.6-rc1-d79ea9a0 (Mar 24 2021, branch 'master')
```

**Configuration File:**

It is reproducible with the default sway configuration, it just requires using a scaling factor greater than 1. I am normally using 1.5 and 2.

**Comment by kennylevinsen** [comment]
Please share debug output (`sway -2 2>sway.log`).

It should be noted that buffer sizes must be divisible with their buffer scale. We currently omit sending a protocol error in this case due to a libwayland bug (https://gitlab.freedesktop.org/wayland/wayland/-/issues/194).

**Comment by zsolt-donca** [comment]
I obtained the below logs as just instructed, though using `sway -d` instead of `sway -2`, and using no sway config at all, and just setting a scale factor of 2 for my external monitor (which would be otherwise scaled to `1`):

[sway-debug-2021-03-24T15:38:03-check.log](https://github.com/swaywm/sway/files/6197658/sway-debug-2021-03-24T15.38.03-check.log)

[foot_log.txt](https://github.com/swaywm/sway/files/6197654/foot_log.txt)

I hope it helps debug this.

**Comment by kennylevinsen** [comment]
The debug log indeed states that buffer sizes are being posted that are not divisible by their own scale, so it's an error on foots' behalf.

**Comment by zsolt-donca** [comment]
Thank you @kennylevinsen !
