### ISSUE TITLE
Sway 1.6-rc1 and 1.6-rc2 not running - EGL _BAD_PARAMETER

### ISSUE THREAD

**Issue by fwSmit** [swaywm/sway#6140]
I compiled the rc1 and rc2 with the recommended commits from wlroots. Both wouldn't run, reporting the same error, while Sway 1.5.1 runs fine. It has most likely something to do with nouveau, since there are nouveau stack traces in the dmesg output. Unfortunatly the dmesg log was rotated, so if you need more dmesg output, please tell me and I'll try it again.

### Debug logs
- [Gist](https://gist.github.com/fwSmit/20f7146ac326bc7225be724b62fbde82)

**Comment by emersion** [comment]
This is a libglvnd bug. Either uninstall proprietary nvidia drivers, either upgrade libglvnd to the latest commit.

**Comment by fwSmit** [comment]
Thank, I knew I'd seen this before. I just couldn't find it
