### ISSUE TITLE
Nouveau stack traces in sway 1.6.1-rc2

### ISSUE THREAD

**Issue by fwSmit** [swaywm/sway#6141]
Every time a frame is drawn a stack trace appears in the dmesg log. The only interfering package I have might be nivida-utils, so if it's useful I can try replacing it (with what?). This time I did install libglvnd-git ;).
I'm using `WLR_DRM_NO_MODIFIERS=1 ./build/sway/sway` to launch sway, since without the environment variable I get a black screen (there is already an issue about that).
Sway mostly works fine, even with the stack traces. I only noticed that firefox freezed while watching a video, but still no sway crash :)

### Logs
- [Gist](https://gist.github.com/fwSmit/ea7f8ccf862c6d1c73f5b54a6401e084)

### Versions
- Linux 5.11.9-arch1-1
- Sway 1.6.1-rc2

**Comment by emersion** [comment]
Please report a Nouveau bug. Whatever user-space is doing, the driver shouldn't trigger WARN_ONs.
