### ISSUE TITLE
(EE) failed to read Wayland events: Connection reset by peer

### ISSUE THREAD

**Issue by MuhammedTaha02** [swaywm/sway#6143]
### Please fill out the following:
- **Sway Version:**
sway version 1.5.1

- **Debug Log:**
http://ix.io/2Uib

- **Configuration File:**
https://github.com/MuhammedTaha02/swaydots/tree/main/.config/sway

- **Description:**
Hello. I'm using swaywm on archlinux. But when i typing "inxi -G" or opening "Chrome etc.", sway crashes and drops to the login screen. I ran the dbus-run-session -- sway command and got a this log. How can I solve this problem? Thanks.

**Comment by emersion** [comment]
Fixed in Sway master.
