### ISSUE TITLE
[WIP] multimedia playback not working

### ISSUE THREAD

**Issue by andersfylling** [swaywm/sway#6144]
> My browsers keep crashing fairly often since a week ago. Will add more details later, don't want to lose my issue progress.

### Please fill out the following:
- **Sway Version:** 1.5.1
- **arch linux:** 5.11.10-arch1-1

- **Debug Log:**
  - Firefox debug log: https://pastebin.com/KLGS6z1W
  - sway debug log https://pastebin.com/KtQSzNtU *note that sway crashes when i try to start up firefox now for some reason... **sway -d -c .config/sway/config_default 2> ~/sway_test.log***
  Also for some reason, I'm unable to paste everything into pastebin.. Last few lines should have been
```
(WW) Option "-listen" for file descriptors is deprecated
Please use "-listenfd" instead.
(WW) Option "-listen" for file descriptors is deprecated
Please use "-listenfd" instead.
glamor: No eglstream capable devices found
00:00:02.690 [DEBUG] [types/wlr_surface.c:666] New wlr_surface 0x55c5bda97c40 (res 0x55c5bda97ff0)
00:00:02.690 [DEBUG] [xwayland/server.c:343] sent SIGUSR1 to process 17736
(EE) failed to read Wayland events: Connection reset by peer
00:00:02.361 [common/ipc-client.c:88] Unable to receive IPC response
date: write error: Broken pipe
```

- **Configuration File:**
  Used the default configuration file found in this repository https://pastebin.com/qKjQHYFG

- **Description:**
Unable to play media, be it youtube or vlc, video is stuck at and no frames are rendered. Youtube buffering and preview is working, according to their UI design. This has been an issue for the last few weeks. 
  1. start any application with multimedia playback support (firefox, chromium, vlc)
  2. try to play a video

**Comment by emersion** [comment]
Fixed in wlroots master.
