### ISSUE TITLE
Second monitor isn´t being listed 

### ISSUE THREAD

**Issue by thiagomtt** [swaywm/sway#6150]
- **Sway Version:**
  - Sway version 1.5.1

- **Debug Log:**
  - sway -d 2> ~/sway.log- https://pastebin.com/xq641hfU
  - swaymsg -t get_outputs - https://pastebin.com/uzmMQrz7
  - drm_info - https://ghostbin.co/paste/h6ttv

- **Description:**
  - I have installed, in order to use CUDA nvcc,  lib32-nvidia-utils 460.67-1 and nvidia-settings 460.67-1 but after that my second monitor stoped working and isn´t being listed on swaymsg -t getoutputs too.

**Comment by emersion** [comment]
From the issue template:

> Proprietary graphics drivers, including nvidia, are not supported
