### ISSUE TITLE
Sway does not open after pci remove.

### ISSUE THREAD

**Issue by MuhammedTaha02** [swaywm/sway#6154]
- **Sway Version**
sway version 1.6-rc2-62fbf33c (Apr  3 2021, branch 'master')

- **Debug Log:**
http://ix.io/2UTl

~ $ ls /dev/dri/ 
card0  renderD128

- **Configuration File:**
https://github.com/MuhammedTaha02/swaydots

- **Description:**
Hello. I am using swaywm on archlinux. But there was a problem like this. There was a crash in older versions of Sway. And I recompiled wlroots and swaywm from source code. Crash problem has been fixed. This time there was a problem with nvidia. I don't play games because I'm busy. And I pci remove my nvidia graphics card and remove it from the system. And I'm just using my intel card. I was able to open swaywm with --my-next-gpu-wont-be-nvidia parameter without any problem by removing pci in older versions. But in the new swaywm version the underlying error comes up. If I do not pci remove my nvidia card, sway opens without any problem. How can i fix this problem? Thanks.

00:00:00.011 [sway/main.c:96] !!! Proprietary Nvidia drivers are in use !!!
00:00:00.061 [wlr] [EGL] command: eglGetPlatformDisplay, error: EGL_BAD_PARAMETER (0x300c), message: "EGL_BAD_PARAMETER error: In internal function: Additional INFO may be available
"
00:00:00.063 [wlr] [EGL] command: eglQueryDevicesEXT, error: EGL_BAD_ALLOC (0x3003), message: "EGL_BAD_ALLOC error: In eglQueryDevicesEXT: Failed to allocate device list.
"
00:00:00.063 [wlr] [EGL] command: eglQueryDeviceStringEXT, error: EGL_BAD_DISPLAY (0x3008), message: "(null)"
00:00:00.063 [wlr] [render/egl.c:273] eglQueryDeviceStringEXT(EGL_EXTENSIONS) failed
00:00:00.063 [wlr] [EGL] command: eglMakeCurrent, error: EGL_BAD_DISPLAY (0x3008), message: "Invalid display (nil)"
00:00:00.063 [wlr] [render/wlr_renderer.c:263] Could not initialize EGL
00:00:00.064 [wlr] [backend/wayland/backend.c:448] Failed to create renderer
00:00:00.064 [sway/server.c:55] Unable to create backend

**Comment by emersion** [comment]
Update glvnd to latest commit or uninstall nvidia.

**Comment by MuhammedTaha02** [comment]
> Update glvnd to latest commit or uninstall nvidia.

![image](https://user-images.githubusercontent.com/62564400/113477537-19d9c800-948b-11eb-8f72-ab203e99b8a7.png)

Already updated

**Comment by emersion** [comment]
Latest commit is newer than latest version.

**Comment by MuhammedTaha02** [comment]
> Latest commit is newer than latest version.

https://github.com/freedesktop/glvnd > Latest release in 2016
https://github.com/NVIDIA/libglvnd > Latest release in 2019 and This package is the most important package of the system and all dependencies depend on it.

**Comment by progandy** [comment]
> https://github.com/NVIDIA/libglvnd > Latest release in 2019 and This package is the most important package of the system and all dependencies depend on it.

The release is old. There are newer changes to the code (~= commits), that haven't been packaged in a release. On arch you can use libglvnd-git from the AUR.

**Comment by MuhammedTaha02** [comment]
> > https://github.com/NVIDIA/libglvnd > Latest release in 2019 and This package is the most important package of the system and all dependencies depend on it.
> 
> The latest release is from June 2020. The tag was created without a description, so github does not show it as a release.
> Still, there are some newer commits, that haven't been packaged in a release. On arch you can use libglvnd-git from the AUR.
> 
> By the way, official upstream is https://gitlab.freedesktop.org/glvnd/libglvnd/-/releases

Hmm, this worked. Thanks for helping :)

![image](https://user-images.githubusercontent.com/62564400/113505385-30455980-9547-11eb-8b52-bb75e05c7d63.png)
