### ISSUE TITLE
Sway crashes if I start a program too early after starting it

### ISSUE THREAD

**Issue by Doctor5555** [swaywm/sway#6158]
- **Sway Version:**
  - sway version 1.5.1

- **Environment:**
  - New Arch Linux installation
  - Sway and xwayland installed using pacman

- **Debug Log:**
  - https://gist.github.com/Doctor5555/d7b6ea0b3b3082c8d8b0eeb05635897a

- **Configuration File:**
  - Happens with default

- **Stack Trace:**
  - Also in gist above

- **Description:**
  - If I try and launch an application through the command line too soon after starting sway, then sway crashes. If I wait a few seconds, then sway will work and I have not encountered any crash at a later point.
  - Reproduction steps:
    1. Log in
    2. Type `sway` and press enter
    3. Open command prompt with mod+enter
    4. Type `firefox` and press enter
    5. Sway crashes

**Comment by emersion** [comment]
Fixed in master.
