### ISSUE TITLE
Sway: anchors on opposing sides do not center the layer-shell

### ISSUE THREAD

**Issue by fwSmit** [swaywm/sway#6160]
The documentation of the layer-shell protocol states:

```xml
<request name="set_anchor">
  <description summary="configures the anchor point of the surface">
    Requests that the compositor anchor the surface to the specified edges
    and corners. If two orthogonal edges are specified (e.g. 'top' and
    'left'), then the anchor point will be the intersection of the edges
    (e.g. the top left corner of the output); otherwise the anchor point
    will be centered on that edge, or in the center if none is specified.

    Anchor is double-buffered, see wl_surface.commit.
  </description>
  <arg name="anchor" type="uint" enum="anchor"/>
</request>
```

It isn't mentioned that two opposing anchors are not allowed, but when trying
that the window doesn't get accepted. So maybe mention something about that in
the documentation? I would suggest adding something like this:

>     If two opposing edges are specified it will result in undefined
>     behaviour.

**Comment by fwSmit** [comment]
I'm working on a patch

**Comment by BLumia** [comment]
> Two opposite edges center the surface on that axis.

@emersion Hi, where does this quote come from? I didn't find anything related to this in the documentation. Should other composers/wayland libraries also follow such conclusion?
