### ISSUE TITLE
Swaybar:New mode where the bar is rendered behind windows

### ISSUE THREAD

**Issue by Valleriite** [swaywm/sway#6162]
- **Description:**
A new mode for the bar which is similar to overlay except the bar is rendered on top of the desktop but not on top of windows.
I have tried other modes but none seemed to do the job,
there is probably a way to do this functionality using an external program but I'll appreciate it being added as a native feature.

I do understand that currently you are not accepting new window management features unless they are implemented by i3,this is here in case you change your mind.

Thank you,
Have a nice day

**Comment by emersion** [comment]
The bar should already be displayed behind windows.

**Comment by Valleriite** [comment]
> The bar should already be displayed behind windows.
thanks for the reply but, in which mode?

**Comment by Valleriite** [comment]
To clarify what I mean is:
when I am on an empty workspace the bar should be shown
when I am on a workspaces with other windows the bar shouldn't be shown or shown but windows cover it.

**Comment by kennylevinsen** [comment]
The "hide" mode is there if you don't always want to see the bar. You can also use IPC to monitor workspace changes and change bar mode between hidden and normal, or have a custom bar that does whatever you want.
