### ISSUE TITLE
sway refuses to launch when both amdgpu and nvidia linux modules are loaded

### ISSUE THREAD

**Issue by danielbarter** [swaywm/sway#6163]
My development machine uses an integrated AMD GPU to drive a monitor and an NVIDIA GPU purely for GPU computing. Usually, I start sway and then load the `nvidia` kernel module and everything works fine. 

I noticed that if you try and start sway with both `amdpgu` and `nvidia` kernel modules already loaded, you get the "NVIDIA sucks" message: 

```
Apr 06 21:46:30 rupert dbus-run-session[12339]: 00:00:00.004 [sway/main.c:99] Proprietary Nvidia drivers are NOT supported. Use Nouveau. To launch sway anyway, launch with --my-next-gpu-wont-be-nvidia and DO NOT report issues.
```

Here are the relevant kernel modules on my machine:
```
Module                  Size  Used by
nvidia              34041856  0
amdgpu               4907008  15
amd_iommu_v2           20480  1 amdgpu
gpu_sched              32768  1 amdgpu
ttm                   110592  1 amdgpu
drm_kms_helper        180224  1 amdgpu
drm                   487424  17 gpu_sched,drm_kms_helper,amdgpu,ttm
agpgart                40960  2 ttm,drm
fb_sys_fops            16384  1 drm_kms_helper
syscopyarea            16384  1 drm_kms_helper
sysfillrect            16384  1 drm_kms_helper
sysimgblt              16384  1 drm_kms_helper
i2c_algo_bit           16384  2 igb,amdgpu
i2c_core               77824  8 videodev,drm_kms_helper,i2c_algo_bit,igb,nvidia,amdgpu,i2c_piix4,drm
backlight              20480  2 video,amdgpu
```

I don't think it would even be possible for the nvidia GPU to be used for compositor rendering since it is isolated from the drm module 

I am not particularly happy that NVIDIA drivers are closed source and I much prefer using linux with integrated graphics, but for scientific computing, CUDA is becoming more and more important.

This feels like it would be easy to fix since running sway then loading the nvidia modules works totally fine, so presumably it will be a matter of just looking for the relevant shared libraries rather than just giving up if `nvidia` is present. I would be more than happy to write a PR if it would be accepted. I know that `nvidia` is a touchy subject :sweat_smile: 

Regardless, I really love sway and will keep on using it either way. Would just be nice if i didn't need to unload `nvidia` in the unlikely event of sway crashing only to reload it once sway is running again.

**Comment by danielbarter** [comment]
ah, my bad. The `--my-next-gpu-wont-be-nvidia` flag works perfectly.

**Comment by pshirshov** [comment]
Actually it doesn't work when Prime is enabled.
