### ISSUE TITLE
Entire screen flashing while using a specific background and opacity for a specific region of the screen

### ISSUE THREAD

**Issue by etu** [swaywm/sway#6165]
### Please fill out the following:
- **Sway Version:**
  - `swaymsg -t get_version` or `sway -v`: 1.5.1

- **Debug Log:**
I've tried to keep it short, but it took me a bit to pin it down: https://gist.github.com/etu/e0c2e7315ff5cb0494062cac0ddda487

- **Configuration File:**
I started sway with the default configuration.

Then I ran the following commands to inject some extra configs:
```
# Set resolution
wlr-randr --output eDP-1 --off
wlr-randr --output DP-1 --mode 5120x1440
```

```
# Set keymap
swaymsg 'input "type:keyboard" xkb_file /nix/store/kv0zk5ylix5sjdikl98dn5y10wwdy5h3-us-dvorak-compose'
```
Text file containing this: https://github.com/etu/nixconfig/blob/2a13235e9558fadedd996ea4cac688c6e2ba497c/modules/my-sway.nix#L49-L66

```
# Set opacity
swaymsg 'for_window [app_id="Alacritty"] opacity set 0.9'

# Set background
swaymsg 'output * bg /nix/store/yfaa3axc8k1bh9gzx76nijxvm05raj1x-sunpaper-2021-03-19/share/sunpaper-backgrounds/5.jpg fill'
```

- **Description:**
A couple of weeks ago I started using https://github.com/hexive/sunpaper with their provided background images which are nice and change during the day. But after some time (at the right time of the day) I've noticed the flashing.

So I've looked into the issue more deeply, it depends on *which* image from the theme I've selected from sunpaper to use, it's only image 5.jpg that cause flashing, the others doesn't. I've tried to use setwallpaper from wallutils directly to set the image and it still flashes so I resorted to setting the image directly with sway to get the same result.

The image I have issues with is https://github.com/hexive/sunpaper/blob/main/images/Lakeside/5.jpg, I do pre-process it in my installation process by running all images of that theme through graphicsmagick to resize it to the screen resolution of my screen, this way I can crop out the part I want as well, this is the bit where I do the cropping and resizing: https://github.com/etu/nixconfig/blob/2a13235e9558fadedd996ea4cac688c6e2ba497c/modules/my-sway.nix#L35-L38

If you want the resulting image in my case, I can provide it as well.

If I take any other image from that directory and crop them just the same, it doesn't flash.

I've recorded a video of me triggering this by resizing panes (or windows that are tiled) to reproduce it: https://imgur.com/a/a2lfWrN

It may require one gtk program running, at first ot mostly happened with firefox (running native in wayland) but it worked to reproduce with emacs from the pgtk branch as well.

**Comment by berbiche** [comment]
Hi,

Judging by the video and the resolution you shard, you seem to use an Odyssey G9.

The flickering is a known issue with the panel in these monitors.

Some links from Reddit:
- https://www.reddit.com/r/ultrawidemasterrace/comments/jej7qq/samsung_odyssey_g9_dimming_and_flickering_when/
- https://www.reddit.com/r/ultrawidemasterrace/comments/l3nxux/fix_for_the_flickering_dimmed_interlacing_on/

**Comment by etu** [comment]
I can confirm the hardware used while closing the issue. It seems like I had to dig deeper...
