### ISSUE TITLE
Invisible mouse cursor in some apps under certain output scales since sway 1.6

### ISSUE THREAD

**Issue by maximbaz** [swaywm/sway#6166]
- **Sway Version:** 1.6

- **Debug Log:** [link](https://paste.maximbaz.com/?5690060774846c74#jG7ZsWgMzHW4PuGa2fWvqL3tk1gM2aaTzw6cHgJzRa6)

- **Configuration File:** default

- **Stack Trace:** n/a

- **Description:**

Hello, I'm testing new release of sway & wlroots and I noticed a weird new bug: in some apps (kitty, mpv) mouse cursor is invisible, that is when I hover my cursor over this app, cursor disappears.

![record_1617907022](https://user-images.githubusercontent.com/1177900/114079303-51d97480-98aa-11eb-9d36-9b03dd780de3.gif)

Interestingly this only happens to the "default" cursor, i.e. I can see a resize or move cursor:

![record_1617907444](https://user-images.githubusercontent.com/1177900/114080104-4470ba00-98ab-11eb-8ae0-ecf70f1524d2.gif)

Both kitty (on the right) and browser (on the left) are running in wayland mode, not in Xwayland.

With the default configuration it is not reproducible, until I change output scale.

Normally I use scale `2.5`, so in the debug log attached above I performed the following action:

1. Start `sway`, with default config, it seems to have detected scale `2` - open new kitty, cursor is visible on it.
1. Set scale to `2.5` - open new kitty, cursor **is not** visible on it
1. Set scale to `2` - open new kitty, cursor **is** visible on it
1. Set scale to `3` - open new kitty, cursor **is not** visible on it
1. Set scale to `4` - open new kitty, cursor **is** visible on it

Do you have any ideas what might be going on? Why cursor is visible on scales 2 and 4, but not anymore on 2.5 or 3?

**Comment by kennylevinsen** [comment]
```
00:00:34.502 [DEBUG] [wlr] [types/wlr_surface.c:189] Client bug: submitted a buffer whose size (64x64) is not divisible by scale (3)
00:00:34.502 [DEBUG] [wlr] [types/wlr_surface.c:189] Client bug: submitted a buffer whose size (64x64) is not divisible by scale (3)
00:00:34.502 [DEBUG] [wlr] [types/wlr_surface.c:189] Client bug: submitted a buffer whose size (64x64) is not divisible by scale (3)
00:00:34.502 [DEBUG] [wlr] [types/wlr_surface.c:189] Client bug: submitted a buffer whose size (64x64) is not divisible by scale (3)
00:00:34.502 [DEBUG] [wlr] [types/wlr_surface.c:189] Client bug: submitted a buffer whose size (64x64) is not divisible by scale (3)
00:00:34.502 [DEBUG] [wlr] [types/wlr_surface.c:189] Client bug: submitted a buffer whose size (64x64) is not divisible by scale (3)
00:00:34.502 [DEBUG] [wlr] [types/wlr_surface.c:189] Client bug: submitted a buffer whose size (64x64) is not divisible by scale (3)
00:00:34.502 [DEBUG] [wlr] [types/wlr_surface.c:189] Client bug: submitted a buffer whose size (64x64) is not divisible by scale (3)
00:00:34.502 [DEBUG] [wlr] [types/wlr_surface.c:189] Client bug: submitted a buffer whose size (3828x2322) is not divisible by scale (4)
```

**Comment by maximbaz** [comment]
Ah nice catch, I missed this! Was I right to report this to sway, or whose bug is this exactly? 🙂

**Comment by Dudemanguy** [comment]
It's a client bug, so it's not sway's fault. https://github.com/mpv-player/mpv/pull/8729 should fix it for mpv.

**Comment by maximbaz** [comment]
To give an update, we [looked into this on kitty's side](https://github.com/kovidgoyal/kitty/issues/3483), and found that it's a bug in `wl_cursor_theme_load()` that it returns cursor not of the requested size, but seemingly of a closest available size in the theme. There is no API to scale the cursor afterwards, and in general it feels wrong that wayland returns a cursor that sway will not accept afterwards.

**Comment by emersion** [comment]
@maximbaz: This is tracked here: https://gitlab.freedesktop.org/wayland/wayland/-/issues/194

**Comment by 0x777** [comment]
One workaround is to use a cursor theme which supports `72x72` size or set the cursor size to `16` as most themes will have support for `48x48` cursor size.

**Comment by emersion** [comment]
Worked around in https://github.com/swaywm/wlroots/pull/2998
