### ISSUE TITLE
External display doesn't turn on in certain cases

### ISSUE THREAD

**Issue by zsolt-donca** [swaywm/sway#6167]
**Sway Version:**
  - [sway-git on AUR](https://aur.archlinux.org/packages/sway-git/), building https://github.com/swaywm/sway/commit/7a68a28475bfefd65d618b053b566e0877abcc75
  - [wlroots-git on AUR](https://aur.archlinux.org/packages/wlroots-git/), building https://github.com/swaywm/wlroots/commit/78befa59f96bb0a13e9ffeb4df1272738c6b5012

**Debug Log:**

https://gist.github.com/zsolt-donca/d64d6a397230f9ab61b5433d57e52f21

**Configuration File:**

Reproducible without a configuration file, and did not use one while obtaining the above configuration file

**Description:**

Under certain circumstances, my external monitor won't turn on when plugging it in (when plugging in the docking station with the monitor connected, see below), even though sway detects the screen. Using commands such as `swaymsg "output DP-6 scale 2"` don't have any effect. Trying to turn it on with [wdisplays](https://github.com/artizirk/wdisplays) also won't work, the tool gives me a generic error message. Using `kanshi` also doesn't work, its logs the message `failed to apply configuration for profile 'docked_7'`. 

I found a **workaround**: turning off my the laptop's screen and simultaneously turning on the external screen using wdisplays works (fortunately it allows me to make multiple changes with a single hit of the "Apply" button). This turns on the external screen. Afterwards, I can turn on the laptop's own screen as well. Alternatively, if I have kanshi running, it automatically turns on the laptop's screen for me after I apply the workaround in wdisplays.

This issue has a randomness factor in it. It does not always reproduce the same way. Mostly it reproduces for me when resuming my laptop from sleep without the docking being connected to it, and then connecting the docking. It also sometimes reproduces the first time I plug the docking in after startup (this is what I reproduced to obtain the logs).

The issue never reproduces if I have the docking connected when sway starts; that way, the external screen always gets turned on. If I keep the docking connected, sleep the laptop, and resume it while the docking is still connected, it also always works.

**Hardware configuration:**

I have a Dell Precision 5540 laptop. This has a intel + nvidia prime configuration (I am using the nouveau drivers). The laptop has a thunderbolt adapter, and I am using it with a USB-C docking station (Dell K20A). I have a single monitor connected to the docking station through displayport. 

**Steps to reproduce:**

I did the following steps to obtain the above logs:
- Started up sway without configuration, without my docking station being connected
- I connected the docking station through the thunderbolt adaptor, and noticed that the external screen did not turn on automatically
- checked `swaymsg -t get_outputs` and noticed that it saw the external screen (`DP-6`), marked as inactive; the laptop's own screen was `eDP-1`;
- I tried turning on the external screen with `swaymsg "output DP-6 scale 2"`; this had no effect, but the command itself did not fail either;
- I tried turning on the external scren with wdisplays, it failed with a generic error message
- I applied the above-mentioned workaround: in wdisplays, I deactivated the laptop's own screen, activated the external screen, hit apply, and this worked as intended;
- I turned on the laptop's own screen as well in wdisplays; this also worked, finally getting both screens on at the same time.

**Comment by zsolt-donca** [comment]
I suspect that this issue might be related to or is a duplicate of https://github.com/swaywm/wlroots/issues/1877 

Going through that ticket, I've found many similarities, and going through the logs there are also many similarities, in particular the ERROR logs in this section:

```
00:00:11.882 [INFO] [wlr] [backend/drm/drm.c:1432] connector DP-6: Requesting modeset
00:00:11.882 [DEBUG] [sway/desktop/output.c:880] New output 0x561d61155c10: DP-6
00:00:11.882 [DEBUG] [sway/config/output.c:351] Turning on output DP-6
00:00:11.882 [DEBUG] [sway/config/output.c:329] Output DPI: 157.316129x161.364706
00:00:11.882 [DEBUG] [sway/config/output.c:382] Auto-detected output scale: 1.000000
00:00:11.882 [DEBUG] [sway/config/output.c:412] Committing output DP-6
00:00:11.882 [INFO] [wlr] [backend/drm/drm.c:779] connector DP-6: Modesetting with '3840x2160@59996mHz'
00:00:11.882 [DEBUG] [wlr] [backend/drm/drm.c:672] connector DP-6: Initializing renderer
00:00:11.882 [DEBUG] [wlr] [render/swapchain.c:105] Allocating new swapchain buffer
00:00:11.889 [DEBUG] [wlr] [render/gbm_allocator.c:123] Allocated 3840x2160 GBM buffer (format 0x34325241, modifier 0x100000000000002)
00:00:11.889 [DEBUG] [wlr] [render/gles2/renderer.c:131] Created GL FBO for buffer 3840x2160
00:00:11.890 [ERROR] [wlr] [backend/drm/atomic.c:35] connector DP-6: Atomic commit failed (modeset): Invalid argument
00:00:11.890 [INFO] [wlr] [backend/drm/drm.c:701] connector DP-6: Page-flip failed with primary FB modifiers enabled, retrying without modifiers
00:00:11.890 [DEBUG] [wlr] [render/swapchain.c:105] Allocating new swapchain buffer
00:00:11.897 [DEBUG] [wlr] [render/gbm_allocator.c:123] Allocated 3840x2160 GBM buffer (format 0x34325241, modifier 0xFFFFFFFFFFFFFF)
00:00:11.897 [DEBUG] [wlr] [render/gles2/renderer.c:131] Created GL FBO for buffer 3840x2160
00:00:11.897 [ERROR] [wlr] [backend/drm/atomic.c:35] connector DP-6: Atomic commit failed (modeset): Invalid argument
00:00:11.897 [ERROR] [wlr] [backend/drm/drm.c:715] connector DP-6: Failed to initialize renderer:initial page-flip failed
00:00:11.897 [ERROR] [wlr] [backend/drm/drm.c:785] connector DP-6: Failed to initialize renderer for plane
00:00:11.897 [ERROR] [sway/config/output.c:417] Failed to commit output DP-6
00:00:11.897 [DEBUG] [wlr] [backend/drm/drm.c:734] connector DP-6: Output has a desired mode and a CRTC, attempting a modeset
00:00:11.897 [INFO] [wlr] [backend/drm/drm.c:779] connector DP-6: Modesetting with '3840x2160@59996mHz'
00:00:11.897 [DEBUG] [wlr] [backend/drm/drm.c:672] connector DP-6: Initializing renderer
00:00:11.898 [DEBUG] [wlr] [render/swapchain.c:105] Allocating new swapchain buffer
00:00:11.905 [DEBUG] [wlr] [render/gbm_allocator.c:123] Allocated 3840x2160 GBM buffer (format 0x34325241, modifier 0x100000000000002)
00:00:11.905 [DEBUG] [wlr] [render/gles2/renderer.c:131] Created GL FBO for buffer 3840x2160
00:00:11.905 [ERROR] [wlr] [backend/drm/atomic.c:35] connector DP-6: Atomic commit failed (modeset): Invalid argument
00:00:11.905 [INFO] [wlr] [backend/drm/drm.c:701] connector DP-6: Page-flip failed with primary FB modifiers enabled, retrying without modifiers
00:00:11.905 [DEBUG] [wlr] [render/swapchain.c:105] Allocating new swapchain buffer
00:00:11.913 [DEBUG] [wlr] [render/gbm_allocator.c:123] Allocated 3840x2160 GBM buffer (format 0x34325241, modifier 0xFFFFFFFFFFFFFF)
00:00:11.913 [DEBUG] [wlr] [render/gles2/renderer.c:131] Created GL FBO for buffer 3840x2160
00:00:11.913 [ERROR] [wlr] [backend/drm/atomic.c:35] connector DP-6: Atomic commit failed (modeset): Invalid argument
00:00:11.913 [ERROR] [wlr] [backend/drm/drm.c:715] connector DP-6: Failed to initialize renderer:initial page-flip failed
00:00:11.913 [ERROR] [wlr] [backend/drm/drm.c:785] connector DP-6: Failed to initialize renderer for plane
00:00:11.913 [DEBUG] [wlr] [backend/session/session.c:63] udev event for card0-DP-6 (add)
00:00:11.913 [DEBUG] [wlr] [backend/session/session.c:63] udev event for card0 (change)
00:00:11.913 [DEBUG] [wlr] [backend/session/session.c:88] DRM device card0 changed
00:00:11.913 [DEBUG] [wlr] [backend/drm/backend.c:131] /dev/dri/card0 invalidated
```

**Comment by kennylevinsen** [comment]
Try `WLR_DRM_NO_MODIFIERS=1`

**Comment by Svanto24** [comment]
I seem to be having a similar issue since the 1.6 release, my external monitor would either just show a black screen but with a cursor on it (when I had it render on my intel iGPU by default), or strange graphical artifacts on a frozen screen (when I used WLR_DRM_DEVICES to render sway via my nouveau eGPU).

> Try `WLR_DRM_NO_MODIFIERS=1`
This completely fixed the issue, thanks!

**Comment by edkv** [comment]
Same issue here after upgrade to sway 1.6 and wlroots 0.13 on Void linux. My external screen is always black, only the cursor is visible. The screen is connected through HDMI and I'm using my Intel GPU (UHD Graphics 630). `WLR_DRM_NO_MODIFIERS=1` helps, but then I get white flashes through half of the screen on every mouse move / image change. I'm going to stay on the older versions for now.

**Comment by zsolt-donca** [comment]
@kennylevinsen I can confirm that setting `WLR_DRM_NO_MODIFIERS=1` does indeed solve the issue for me.

What are the downsides of setting this variable?

**Comment by zsolt-donca** [comment]
> my external monitor would either just show a black screen but with a cursor on it (when I had it render on my intel iGPU by default), or strange graphical artifacts on a frozen screen (when I used WLR_DRM_DEVICES to render sway via my nouveau eGPU).

This might not be the same issue as for me, as I don't have any activity on my external screen. I think it would be best if you opened a new bug for it, with your sway debug log files, sway version and other details. It could help investigating it - I don't think that it's technically possible to investigate such issues without access to log files and further details.

**Comment by zsolt-donca** [comment]
@edkv 
> Same issue here after upgrade to sway 1.6 and wlroots 0.13 on Void linux. My external screen is always black, only the cursor is visible. The screen is connected through HDMI and I'm using my Intel GPU (UHD Graphics 630). `WLR_DRM_NO_MODIFIERS=1` helps, but then I get white flashes through half of the screen on every mouse move / image change. I'm going to stay on the older versions for now.

I think that's a different issue than what I reported here. I have been having this issue for a while (since around December 2020), and so it's definitely not a regression of sway version 1.6 that was released just 16 days ago. Also, I suspect that mine is a duplicate of https://github.com/swaywm/wlroots/issues/1877, which is an issue from 2019.

I'd advise opening a new bug report for this issue as well - I don't think that issues such as yours can be investigated only based on a description, and without the debug log files, detailed version information and so on.

**Comment by edkv** [comment]
@zsolt-donca you're right, I opened a new issue
