### ISSUE TITLE
Middle mouse clipboard not shared between windows

### ISSUE THREAD

**Issue by Xartos** [swaywm/sway#6169]
## Version
**Sway Version:** 1.6-be4b92c6 (Apr  8 2021, branch 'HEAD')
**wlroots Version:** 0.13.0

## Description

When selecting some text in one window and middle mouse clicking in the same window the text is pasted as expected.
If I try to the same thing but pasting in another window, some other text might show instead (the text last selected in that other window)
However the "regular", Ctrl+C/Ctlr+V, clipboard works as expected

So from what I can gather it seems like the middle mouse clipboard isn't shared between windows while the "regular" clipboard is.

This issue is resolved if I install `sway v1.5.1/wlroots 0.12.0` so it seems like a 1.6 bug

**Comment by Xyene** [comment]
Your bug report is missing debug logs. Please add a link to the full debug log file.

Also useful would be running a problematic app with `WAYLAND_DEBUG=1`. My gut feeling is the app (or toolkit) is relying on the deprecated `gtk-primary-selection` protocol, which was removed in Sway 1.6: https://github.com/swaywm/sway/pull/5788.

**Comment by Xartos** [comment]
> Your bug report is missing debug logs. Please add a link to the full debug log file.
> 
> Also useful would be running a problematic app with `WAYLAND_DEBUG=1`. My gut feeling is the app (or toolkit) is relying on the deprecated `gtk-primary-selection` protocol, which was removed in Sway 1.6: #5788.

Aah, sorry about that. I didn't see any logs that were generated when I copy/pasted stuff, but I didn't realize that I could've used debug logs for the applications. 

But anyway, your gut feeling seems to be very much spot on. I have just about too old GTK version (3.24.23) and that seems to be why it's not working. But, as the PR mentions, I tried to re-add the lines that were removed and now it works as expected. Thanks!
