### ISSUE TITLE
Sway crash

### ISSUE THREAD

**Issue by hanckmann** [swaywm/sway#6170]
I have a nasty bug which is hard to reproduce, but bites me quite regularly.

It usually right after a fresh start (system boot). I usually start opening these applications:
- firefox
- thunderbird
- sublime text 3
and sometimes:
- skype
- teams

I think it is related to thunderbird, but I am not sure.

After the applications are loading sway crashes and drops me into my shell. This is what is on my screen:

![screenshot](https://user-images.githubusercontent.com/925657/114142523-571ed980-9913-11eb-889f-d4aa79a7e5d4.jpeg)

I have no clue how to get that info in a textual format. Therefore this picture.

I hope it helps.
I have now cloned and (debug-)build sway from git and will start sway with debug symbols the next few days to see if I can get a debug dump. Until then, maybe the picture does provide some useful information.

--
Working on a Lenovo T14s laptop with a fully updated Arch Linux.

_λ ~/ sway --version_
sway version 1.5.1
_λ ~/ uname -a_
Linux plato 5.11.12-zen1-1-zen #1 ZEN SMP PREEMPT Wed, 07 Apr 2021 21:48:33 +0000 x86_64 GNU/Linux

**Comment by emersion** [comment]
Try redirecting the Sway output to a file.

```
sway -d >sway.log 2>&1
```

**Comment by hanckmann** [comment]
Why did I not think of that...
I did now put that in my default startup script. Thanks for this hint.

**Comment by MuhammedTaha02** [comment]
If you install the latest versions of libglvnd sway and wlroots from source code, the sway will be fixed #6154

**Comment by emersion** [comment]
This issue doesn't seem to be the same as #6154, since it happens on 1.5.1. My guess would be that it's the Xwayland SIGUSR1 issue, fixed by 1.6.

**Comment by hanckmann** [comment]
I do not have nvidea hardware... so I guess it should not be related to libglvnd.

**Comment by hanckmann** [comment]
sway 1.6 is in archlinux staging... so if it is the SIGUSR1 related issue, then I will check if it (still) happens in sway 1.6.

I propose to close this report.
If it happens again after updating to 1.6 (from the arch repositories), I will file a new bug-report with a log file as described in the first comment.

**Comment by MuhammedTaha02** [comment]
> This issue doesn't seem to be the same as #6154, since it happens on 1.5.1. My guess would be that it's the Xwayland SIGUSR1 issue, fixed by 1.6.

This same problem happened with me. Typing inxi -G or running xwayland calling applications such as google-chrome, sway crashed. The problems are alike. #6143
