### ISSUE TITLE
Segfault on launch

### ISSUE THREAD

**Issue by fluix-dev** [swaywm/sway#6174]
Not sure of a more creative title: sway (master) with wlroots (master) crashes on startup with the default config. 

Coredump: https://paste.sr.ht/blob/8f19a44f1a5f4466f61c19b16771c4c1283302f3
Log with ASan: https://paste.sr.ht/blob/4408c0e85cc6222c7adc4e6c3ac9161c7c098a8b

**Comment by fluix-dev** [comment]
Doing some more debugging, it seems that starting a GUI app is what causes a segfault, whether that's swaybg, swaybar, or alacritty.

**Comment by emersion** [comment]
Are you sure wlroots is up-to-date, and not an old checkout?

**Comment by fluix-dev** [comment]
Apologies for the wasted time, compiling with wlroots as a subproject works... time to figure out why installing through the AUR doesn't.
