### ISSUE TITLE
Macro and virtual keyboards

### ISSUE THREAD

**Issue by sujay1844** [swaywm/sway#6184]
I'd love to see some macro functionality in Sway. I want to use touchpad gestures like 3 finger swipe for workspace switching and pinching for zoom in/out. We have `libinput-gestures` for that but in Xorg I used `xdotool` for such things. An on-screen keyboard would be useful. I believe Wayland doesn't have an equivalent due to security reasons. In that case, could you implement a feature wherein there is a program that can be executed to switch workspaces and so on.

**Comment by emersion** [comment]
Sway has a virtual-keyboard and a virtual-pointer protocol, which allow this kind of things.

**Comment by progandy** [comment]
Sway commands like switching workspaces can be run with ```swaymsg``` as well.

**Comment by sujay1844** [comment]
where is the documentation for it?? @progandy

**Comment by rumpelsepp** [comment]
Did you try `man 5 sway`?

**Comment by sujay1844** [comment]
yep got it thnx
