### ISSUE TITLE
Some programs open too late

### ISSUE THREAD

**Issue by MuhammedTaha02** [swaywm/sway#6186]
- **Sway Version:**
sway version 1.6-4e77bc29 (Apr 15 2021, branch 'master')

- **Debug Log:**
http://ix.io/2W9g

- **Configuration File:**
https://github.com/MuhammedTaha02/swaydots

- **Description:**
Hello, I compiled sway from the source code due to a bug I experienced in older versions of sway. The problem I was experiencing has disappeared. But this time, some programs open too late. For example waybar. Sway opens 30 seconds after opening. Or google-chrome. It opens 30 seconds after I open it.

**Comment by emersion** [comment]
See https://github.com/swaywm/sway/wiki#gtk-applications-take-20-seconds-to-start
