### ISSUE TITLE
Keyboard config block stops keyboard grouping from working

### ISSUE THREAD

**Issue by itaton** [swaywm/sway#6187]
- **Sway Version:**
1.5.1

- **Debug Log:**
https://gist.github.com/itaton/3f2d9645ae9253ad9cc0fbce7dd57c45
(The gist contains the config file and the two debug logs (for explanation see Description)

- **Configuration File:**
https://gist.github.com/itaton/3f2d9645ae9253ad9cc0fbce7dd57c45
Differs from default on lines 50-60 (keyboard config) and 227-230 (bindsyms)

- **Description:**
This is a follow-up on #3540. I had a workaround for a while and came back to this today.
With my current config the bindsym shift+XF86BrightnessUp/Down still does not work. 
Reading up on the original issue and the linked issues, I understand that XF86BrightnessUp/Down is probably on a different virtual keyboard. Looking though `libinput list-devices`:
```
Device:           AT Translated Set 2 keyboard
Kernel:           /dev/input/event3
Group:            7
Seat:             seat0, default
Capabilities:     keyboard 
[...]

Device:           ThinkPad Extra Buttons
Kernel:           /dev/input/event5
Group:            8
Seat:             seat0, default
Capabilities:     keyboard 
[...]
```
I guess XF86BrightnessUp would be on `ThinkPad Extra Buttons`

After some experimentation I found shift+XF86BrightnessUp/Down to be working with the default sway config, but as soon as I include the config block for the 'normal' keyboard the keybinds stops working. The config block looks like this:
```
    input "1:1:AT_Translated_Set_2_keyboard" {
            repeat_rate 45
            repeat_delay 500
            xkb_options compose:ralt
    }
```
In the gist, I included 2 debug logs: The one called 'logWithKeyboardConfig' is with a config that contains that block (the keybind does not work there). The other one called 'logWithoutKeyboardConfig' is without that config block (the keybind works here).

I would not expect changing the key-repeat rate/delay and compose key to mess with that keybinding.
I also tried setting the same options for the other virtual keyboard (see commented-out block lines 56-60), but to no avail.

**Comment by RedSoxFan** [comment]
This is working as intended. In order to group keyboards together they must have the same `xkb_keymap` (which `xkb_options` is a part of), We also require the `repeat_rate` and `repeat_delay` to match because the group is exposed as a keyboard and changing the `repeat_rate`/`repeat_delay` depending on the source would require changing the group's keyboard's repeat info and interfere with any other keys that are currently held down. #4811 is an example of one of the issues when allowing keyboards with different repeat info in the same group.

The following should work for you:
```
input type:keyboard {
    repeat_rate 45
    repeat_delay 500
    xkb_options compose:ralt
}
```

**Comment by itaton** [comment]
Ah, sorry for missing that. Thank you for the quick help. That does indeed work like a charm.
Maybe this could be mentioned in the default config (as an example) or in the man page? (Maybe I was just too blind to find it?)
