### ISSUE TITLE
Keyboard key repeat issue

### ISSUE THREAD

**Issue by user18130814200115-2** [swaywm/sway#6188]
Sway 1.6 on manjaro-arm on pinebook pro
default config
If key repeat is active (meaning a key is pressed for long enough to pass the delay and start repeating), and the window in which this key was pressed loses focus, they key will keep repeating until it is pressed again.

The easiest way i found to reproduce this issue is by using the nnn file manager.
In nnn i select an image and hold the right arrow key, the program opens after a second or so, now the right arrow key is permanently pressed down and upon returning to nnn, the file will be opened again and again.

The bug  is not limited to nnn though, it occurs whenever the key delay is passed and the window loses focus.
This become especially annoying on a low powered system where the key repeat delay sometimes triggers falsely due to a lag spike.

EDIT: example video for clarity: https://twester.tk/recording.mp4

**Comment by kennylevinsen** [comment]
Key repeat is handled by the client, not the compositor. We just send up/down events, and tell it what the key repeat setting is. When a window loses focus, it must cancel all held keys.

If the window doesn't lose focus when it should, or has focus but doesn't receive a key up even when it should, then it would be a sway bug. Otherwise it's a client bug. You can try to see what is going on with `WAYLAND_DEBUG=1 nnn 2>debug.log`, and then minimally reproduce the issue.

**Comment by user18130814200115-2** [comment]
Thank you for the clear explanation, I will investigate the clients on which this issue occurs. Closing for now as it does not seem to be a sway issue.

**Comment by user18130814200115-2** [comment]
I did some more investigation and am therefore reopening this issue.
I found a strange but extremely easy way to trigger this bug.
Opening nvim and pressing `:` will open the vim prompt, then the `;` key will remain pressed. 

The reason I am reopening this issue is because it was fixed after downgrading from sway 1.6 to 1.5.1

**Comment by user18130814200115-2** [comment]
Sorry for the many changes in opening and closing this issue. It seems to me that this issue lies with the combination of sway 1.6, my terminal emulator (foot) and fcitx.
Since sway 1.6, foot can use the fcitx input method framework. If I `killall fcitx5`, the key repeat issue no longer occurs. I will report this issue to the developer of foot instead.
