### ISSUE TITLE
Sway crashes to DM when opening terminal before Firefox

### ISSUE THREAD

**Issue by deadly-platypus** [swaywm/sway#6189]
- **Sway Version:**
  - sway version 1.5.1

- **Debug Log:**
 https://gist.github.com/deadly-platypus/e1a76cf014f95a65ddd12d42cd538ef9

- **Configuration File:**
This happens with the default configuration

- **Stack Trace:**
No match found when I try to find a stack trace

- **Description:**
OS: Manjaro
Kernel: 5.9.16-1-MANJARO

When logging in, if the first thing I do is start a terminal (I've tried alacritty, kitty, and tilix), sway crashes back to GDM.  However, if I start Firefox, and then a terminal, sway does not crash.

**Comment by emersion** [comment]
This is the SIGUSR1 Xwayland bug, fixed in master.
