### ISSUE TITLE
Sway doesn't start after upgrade to 1.6 due to EGL_BAD_PARAMETER

### ISSUE THREAD

**Issue by gohm44** [swaywm/sway#6192]
- **Description:**
After the upgrade of sway from version 1.5 to 1.6 does not start anymore. At first, I had seatd issue but found a solution. Now there a few error messages as shown in sway.log file.

- `sway version 1.6`
- [sway.log](https://gist.github.com/gohm44/83de4f65bc2cd8f0b41297ffe6a0fd19)
- [config](https://gist.github.com/gohm44/75f71251e6d80879a42f9cc7d88d1f64)
- GPU: AMD Firepro w5100

**Comment by emersion** [comment]
This is a libglvnd bug. Uninstall nvidia drivers or upgrade libglvnd to latest commit (fix not released yet).

**Comment by gohm44** [comment]
I thought I did this but left some garbage. After that works. Thanks a lot for the quick response.
