### ISSUE TITLE
mpv titlebar/border becomes smaller than the actual video window after fullscreen/float mode

### ISSUE THREAD

**Issue by diegoviola** [swaywm/sway#6201]
### Please fill out the following:
- **Sway Version:**
  - sway version 1.6

- **Debug Log:**
  - http://0x0.st/H94T.txt

- **Configuration File:**
  - http://0x0.st/H94A.txt

- **Description:**
  - Play a high res video with mpv (higher than your screen resolution); for example, if your resolution is 1366x768, play a 1080p video.
  - Press F to go into fullscreen.
  - While the video is in fullscreen, hit $mod+Shift+Space.
  - Press F to exit fullscreen.
  - Press $mod+Shift+Space twice.
  - Move the window around and look at the window borders, etc. You should see something like the screenshot below.

- **Screenshot:**

![screenshot](https://i.imgur.com/eLVM827.png)

**Comment by RPigott** [comment]
What's ctrl+alt+space supposed to do? It's not bound in the sway config and it's not a default binding for mpv I don't think.

**Comment by diegoviola** [comment]
> What's ctrl+alt+space supposed to do? It's not bound in the sway config and it's not a default binding for mpv I don't think. I tried to reproduce but I think I'm confused about this step.

Sorry, I meant $mod+Shift+Space, not ctrl+alt+space.

**Comment by diegoviola** [comment]
It happens with other windows as well, not just mpv.

**Comment by diegoviola** [comment]
I can't reproduce this anymore (sway 1:1.10-1, wlroots 0.18.1-1).

Closing.
