### ISSUE TITLE
screen is distorted after startup

### ISSUE THREAD

**Issue by Hardy7cc** [swaywm/sway#6203]
I upgraded sway to version 1.6 and got into startup issues (see Description).

- **Version:**
  - sway version 1.6
  - Arch Linux
  - Linux 5.11.15-arch1-2 #1 SMP PREEMPT Sat, 17 Apr 2021 00:22:30 +0000 x86_64 GNU/Linux
  - xf86-video-nouveau   Version: 0.17-1

- **Debug Log:**
  - https://gist.github.com/Hardy7cc/e91709f4ada0cb23860796545897fad2

- **Configuration File:**
  - default configuration

- **Description:**
  - When I startup sway it only display some kind of distorted screen.
  - After about 10 seconds I changed to tty2 with ctrl-alt-f2
  - Another 10 seconds later I change back to tty1 (my sway session) and it all works fine.

I hope the description is good enough. If there are question tell me.
And by the way I really like sway and I really appreciate your work.

**Comment by emersion** [comment]
Try setting `WLR_DRM_NO_MODIFIERS=1`

**Comment by Hardy7cc** [comment]
Okay that works. Thanks.
Is this a solution which should work forever?
I am interested is there an easy way to explain what is going on here or maybe somewhere I can read about it.

**Comment by emersion** [comment]
No, the Nouveau bug should be fixed in latest commit of Mesa and kernel. Should be fixed by https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/8500 and https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/3724.
