### ISSUE TITLE
sway hangs under QEMU/KVM (virtio gpu driver)

### ISSUE THREAD

**Issue by diegoviola** [swaywm/sway#6210]
### Please fill out the following:
- **Sway Version:**
  - sway version 1.6

- **Debug Log:**
  - https://gist.github.com/diegoviola/2f1230bfe1a50ce6e862c70a25630378

- **Configuration File:**
  - https://gist.github.com/diegoviola/4b6d9af338f9d8903b5ac0fa80ea0c19

- **Description:**

Basically, sway hangs when running it under QEMU/KVM (virtio gpu driver), the hang occurs when running certain Xwayland apps (I experienced a hang when running Calibre for example).

This does not happen when I use i3-wm or weston.

I am running the VM with this command:

    qemu-system-x86_64 -enable-kvm -hda arch.qcow2 -m 4G -vga virtio

I use Arch Linux both as the guest and host OS.

**Comment by emersion** [comment]
```
00:00:00.334 [INFO] [wlr] [render/gles2/renderer.c:872] GL renderer: llvmpipe (LLVM 11.1.0, 128 bits)
```

You're using llvmpipe software rendering, things are expected to be slow.

**Comment by emersion** [comment]
Turns out the VM just hangs completely, it's not just slow. Caused by a virtio bug: https://gist.github.com/diegoviola/cc941c6468e631331a5d788e390dbc3e

**Comment by minijackson** [comment]
Hello! Are we sure this is a virtio bug? I'm having a quite similar issue with sway 1.6 where starting sway freezes the screen, but the VM was not frozen: killing sway by other means gives back control, and I'm not seeings Oops in the kernel logs.

Sway could run fine under qemu with version 1.5.1

Here are the sway logs: https://gist.github.com/minijackson/67e21539a1d1f295e1fae9d2514c129a
And the output of dmesg: https://gist.github.com/minijackson/cc67a1607c2caef08f7936bd85ecb53b

Should I open another issue?

**Comment by emersion** [comment]
Please open a separate bug report.

**Comment by kennylevinsen** [comment]
(And note that you're not using virtio-gpu at all, but bosch-drm)
