### ISSUE TITLE
Graphical artifacts on AMD

### ISSUE THREAD

**Issue by filtsin** [swaywm/sway#6212]
- **Sway Version:**
  - `sway version 1.6`

- **Debug Log:**
  - https://gist.github.com/filtsin/c091f64be236804d21ebb12984c7d579

- **Configuration File:**
  -  default

- **Description:**
  - Graphic artifacts appear when launching the application. I'm not sure but this happens with alacritty only. When I click on terminal graphical artifacts are disappearing. Radeon rx 5700xt, 2 monitors
![222](https://user-images.githubusercontent.com/25691786/115462926-e68d8c00-a233-11eb-8d79-d8dd4146084d.png)

**Comment by asahaf** [comment]
I've GPU similar to yours, Radeon RX 5500XT. Actually I've noticed this graphical artifacts since I've updated `mesa` to version `21.x.x`. This was also happens with `Sway v1.5`

**Comment by ohhskar** [comment]
This is also happening on my system running `mesa 21.0.3-1` with an RX 5600XT. However, this only happens on some application: kitty, discord, and pinentry-tty on mine. All other applications that I use does not have this issue.

**Comment by asahaf** [comment]
This issue happens with any GPU accelerated application. It happens with `Alacritty` on my machine.

**Comment by oscarpax** [comment]
This is an issue with `mesa 21.0.3-1` update, downgrade to `mesa 21.0.2-1` fixes it for now.

https://gitlab.freedesktop.org/mesa/mesa/-/issues/4691

**Comment by grafov** [comment]
Just add a bit of info. I have sway 1.6 too and Radeon RX-5600XT. A couple of days ago I got similar graphics bugs in `alacritty` but after several updates in Void Linux (sadly I not checked them carefully) the same bugs appeared in all applications that use OpenGL. The applications that use Vulkan still run without the problems (for example I switched Chromium to Vulkan rendering with `enable-vulkan=true` and `ignore-gpu-blocklist=true` settings and the bugs disappeared). Only apps that use OpenGL was affected.

The advice above to downgrade `mesa` and its dependencies to `21.0.2_1` helped me. I've not found any info about these bugs in my distro news only this thread clear the picture! Thank a lot guys! :handshake:

**Comment by Chlorophytus** [comment]
Replicated the bug by launching `alacritty` with a RX 6900XT. It is still happening on an updated `mesa` but I might do the suggested downgrade procedure to `21.0.2_1` to see if that fixes the graphical issue. I'm not on my computer with the 6900XT but I'll edit it promptly when I switch.

**Comment by asahaf** [comment]
Issue is fixed for me with mesa 21.1.0

**Comment by emersion** [comment]
Closing as an upstream bug.
