### ISSUE TITLE
swaywm segfault when full-screening vnc clients on a headless output.

### ISSUE THREAD

**Issue by dnfm** [swaywm/sway#6213]
- **Sway Version:**
Latest HEAD from git.

- **Debug Log:**
https://pastebin.com/eSe67KUX

- **Configuration File:**
https://pastebin.com/2vq6GhHw

- **Stack Trace:**

```
(gdb) bt
#0  0x0000000000000000 in  ()
#1  0x00007f1223ce8b79 in wlr_output_test (output=0x55a705b31140) at ../wlroots-9999/types/wlr_output.c:583
#2  0x000055a702adb30b in scan_out_fullscreen_view (output=0x55a705afc150, view=0x55a705bc62e0) at ../sway-9999/sway/desktop/output.c:515
#3  0x000055a702adb419 in output_repaint_timer_handler (data=0x55a705afc150) at ../sway-9999/sway/desktop/output.c:547
#4  0x000055a702adb707 in damage_handle_frame (listener=0x55a705afc2d0, user_data=0x55a705b286e0) at ../sway-9999/sway/desktop/output.c:639
#5  0x00007f1223cfda9b in wlr_signal_emit_safe (signal=0x55a705b28748, data=0x55a705b286e0) at ../wlroots-9999/util/signal.c:29
#6  0x00007f1223ce2862 in output_handle_frame (listener=0x55a705b287c8, data=0x55a705b31140) at ../wlroots-9999/types/wlr_output_damage.c:44
#7  0x00007f1223cfda9b in wlr_signal_emit_safe (signal=0x55a705b312c8, data=0x55a705b31140) at ../wlroots-9999/util/signal.c:29
#8  0x00007f1223ce8fd7 in wlr_output_send_frame (output=0x55a705b31140) at ../wlroots-9999/types/wlr_output.c:687
#9  0x00007f1223cab942 in signal_frame (data=0x55a705b31140) at ../wlroots-9999/backend/headless/output.c:172
#10 0x00007f1223d5535d in wl_event_loop_dispatch () at /usr/lib64/libwayland-server.so.0
#11 0x00007f1223d53845 in wl_display_run () at /usr/lib64/libwayland-server.so.0
#12 0x000055a702ad6a93 in server_run (server=0x55a702b4e540 <server>) at ../sway-9999/sway/server.c:254
#13 0x000055a702ad5f56 in main (argc=4, argv=0x7ffd8a5aeb08) at ../sway-9999/sway/main.c:433
```

- **Description:**
My setup is a bit weird, but I've whittled it down a bit to try to make reproducing this as simple as reasonably possible.

For this test, I am using 4x1080p displays on a system running sway.
I normally have another system to the right of that running sway/wlroots/wayvnc that I connect to from the first system using 2 headless outputs.
And then to the right of those, I have a laptop running Windows that I also use a headless output to connect to with a vnc client.

I've been able to reproduce this issue with both vinagre as well as remmina.  This particular test was with remmina as it's easier to use and test with.

So I start sway with the above config, and then I run remmina like this:

remmina --name=vncwindows --class=vncwindows vnc://windows

Because of my for_window listed above, remmina starts in the headless output, connects, and works as expected, but it's not in 'full screen' as it has a toolbar on the left side of the window.

When I hit CTRL_R+F to full screen and remove the titlebar in remmina, it works, and I can use the window.  HOWEVER, as soon as I move the mouse out of that headless display, sway segfaults with the above bt.

**Comment by emersion** [comment]
Can you try https://github.com/swaywm/wlroots/pull/2882?

**Comment by dnfm** [comment]
That fixed it.  Thanks!
