### ISSUE TITLE
Brave closing on workplace switch.

### ISSUE THREAD

**Issue by debendraoli** [swaywm/sway#6214]
### Please fill out the following:
- **Sway Version:**
  - 1.6

- **Debug Log:**
  - https://gist.github.com/debendraoli/3e270882b3b4cd30b5e1f8f10f834a50

- **Configuration File:**
  - Please try to produce with the default configuration.
  - If you cannot reproduce with the default configuration, please try to find the minimal configuration to reproduce.
  - Upload the config to a pastebin such as gist.github.com.

- **Description:**
  -  All other programs seems okay and I have problem with brave browser which is running on wayland.
  -  The issue occurs when switching to workspace where the brave is assigned.
  -  I got issue after sway upgrade to 1.6.

**Comment by emersion** [comment]
This is a client bug. Please open a bug report with them, with a `WAYLAND_DEBUG=1` log file of the client.

```
[178289:178289:0420/191438.010969:ERROR:wayland_event_watcher.cc(138)] Fatal Wayland protocol error 4 on interface xdg_wm_base (object 12). Shutting down..
```

**Comment by danielmorlock** [comment]
Same problem here but with sway 1.5, running Chromium based Brave Browser (1.25.40) with `WAYLAND_DEBUG=1` leads to the following obvious error:
```
[2517482.142] wl_display@1.delete_id(218)
[2517482.147] wl_display@1.error(xdg_wm_base@13, 4, "wrong configure serial: 352092")
[631659:631659:0425/145831.931189:ERROR:wayland_event_watcher.cc(138)] Fatal Wayland protocol error 4 on interface xdg_wm_base (object 13). Shutting down..
```

**Comment by debendraoli** [comment]
I downgraded to brave 1.22 (chromium 89) from 1.23 (chromium 90).

So far so good, not updating once fixed.

@daniellockyer that chromium bug tracker you mentioned may not addresses this particular issue, because chromium 90 was recently released and that issue was fixed 24 days ago.

**Comment by danielmorlock** [comment]
You sure the fix already hit the code based used by brave?

**Comment by debendraoli** [comment]
yeah, see here https://www.chromestatus.com/features/schedule, the chromium stable was released  13 days ago and the issue you mentioned was closed 24 days, which makes sense that the issue was not addressed rather it is new one.
