### ISSUE TITLE
Unusable second screen on nouveau multi-GPU setup

### ISSUE THREAD

**Issue by LucaFulchir** [swaywm/sway#6215]
After the upgrade from sway 1.5 to 1.6, my second screen is completely unusable.
Looks corrupted, just a couple of bands of random pixels and nothing else.

All the keybinding related to working on the second screen still work, I can launch applications there and they run (checked via `ps`), the virtual desktops are correctly allocated to that screen, it's just I can see anything

The only sway conf I have on the output is:
```
output LVDS-1 pos 0 1390 res 1920x1080
output HDMI-A-1 pos 1920 0 res 3840x2160 transform 270
```
and that worked with 1.5. I tried changing resolution, removing the rotation and a few other things, but nothing changed.

Using:
* arch linux, kernel `5.11.15`
* (old) laptop with intel i7-3630 + nvidia GT 650M
* the nvidia card uses the nouveau drivers, glxinfo:
```
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: nouveau (0x10de)
    Device: NVE7 (0xfd1)
    Version: 21.0.2
```
* wayland/sway uses the nouveau card as primarily, I set `WLR_DRM_DEVICES=/dev/dri/card1:/dev/dri/card0` in my `~/.profile`
* not an hardware/driver problem, the second screen works fine with xfce
I do have a lot of `nouveau 0000:01:00.0: DRM: bo 0000000060cc6e82 pinned elsewhere` messages in the journald logs which are new, but I am unable to figure out why, and again, the main screen works and the external monitor works with xfce
* tried removing the `WLR_DRM_DEVICES` and let wayland/sway use my intel (verified with `glxinfo`), second monitor still not usable, although it was all black instead of showing a couple of corrupted bands

I don't know how to debug this further, or where to dig, any suggestions?

**Comment by emersion** [comment]
> (old) laptop with intel i7-3630 + nvidia GT 650M

You may want to try `WLR_DRM_NO_MODIFIERS=1`, as per https://github.com/swaywm/sway/wiki#sway-16-shows-garbage-on-nouveau

There is also this issue for multi-GPU setups: https://github.com/swaywm/wlroots/issues/2636

**Comment by LucaFulchir** [comment]
> > (old) laptop with intel i7-3630 + nvidia GT 650M
> 
> You may want to try `WLR_DRM_NO_MODIFIERS=1`, as per https://github.com/swaywm/sway/wiki#sway-16-shows-garbage-on-nouveau
> 
> There is also this issue for multi-GPU setups: [swaywm/wlroots#2636](https://github.com/swaywm/wlroots/issues/2636)

Thank you, the `WLR_DRM_NO_MODIFIERS` fixed it, I missed that on the wiki.  
Don't know why I did not need it before, but good enough for me, tnx.  
I'll try checking on wlroots next time, too
