### ISSUE TITLE
man page: link to pango font description no longer work 

### ISSUE THREAD

**Issue by inwwin** [swaywm/sway#6217]
The link to pango font description provided in the man page no longer work. ([see this commit](https://github.com/swaywm/sway/commit/6061d083ca746de525c39f061510f058840198f5))
The link in question is https://developer.gnome.org/pango/stable/pango-Fonts.html#pango-font-description-from-string which, last time I check, gives me 403 Forbidden.

**Comment by fluix-dev** [comment]
Seems you have to pin a specific version like [`1.46`](https://developer.gnome.org/pango/1.46/pango-Fonts.html#pango-font-description-from-string) instead of `stable`.
