### ISSUE TITLE
Monitor not found when using usb-c based dockingstation

### ISSUE THREAD

**Issue by hanckmann** [swaywm/sway#6221]
### Please fill out the following:
- **Sway Version:** sway version 1.6
- **Debug Log:** There is nothing to show

**Description:**

My laptop is a Lenovo T14s (amd based; 06:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Renoir (rev d1)).
I use a docking station: https://www.lenovo.com/us/en/accessories-and-monitors/docking/universal-cable-docks-usb/TP-Hybrid-USB-C-Dock-US/p/40AF0135US

My monitor is connected to the docking station HDMI connector.
Under Windows 10, the monitor is detected and I can use both the  LCD and the external (HDMI) monitor.
Under Sway (wlroots 0.13.0) the external monitor is not found (and thus cannot be used).

Other parts of the docking station do work (network and USB, I have not yet tested audio).

I do not know if this bugreport belongs here, or elsewhere.
I do not know how to help debugging this. What more info do you need?

**Comment by hanckmann** [comment]
Note, that when I attach the monitor directly to the laptops HDMI port, the monitor is detected and can be used.

**Comment by emersion** [comment]
>  Debug Log: There is nothing to show

There _is_ something to show. Please attach a debug log.

**Comment by hanckmann** [comment]
[sway.log](https://github.com/swaywm/sway/files/6365386/sway.log)

O, of course you are right... and it was an interesting read (that config file).
So, apparently the HDMI (HDMI-A-1) was detected.
So I added it to the config.
But it is not being used.

So  now I do not know if my config is wrong, or if this really is a bug.

My config has this part in it:
```
    output eDP-1 pos 0 0
    output DP-1 pos 1920 0
    output HDMI-A-1 pos 1920 0
```
where DP-1 is the HDMI output on my laptop, and HDMI-A-1 is (apparently) the HDMI output on the docking station.

**Comment by emersion** [comment]
It seems like only eDP-1 is detected as connected.

Can you try running [drm_info](https://github.com/ascent12/drm_info) and attach the output here? If the kernel doesn't tell us that the connector is connected, not much we can do.

**Comment by hanckmann** [comment]
This is the output of drm_info.
For me this is a bit cryptic, so I am not sure if/how to give you pointers.
I generated the file from sway, directly after a reboot. Befoire the reboot I attached the HDMI monitor to the docking station.

[drm_info.log](https://github.com/swaywm/sway/files/6371844/drm_info.log)

**Comment by emersion** [comment]
`drm_info` says all connectors except eDP-1 are disconnected. This is a kernel bug, we can't do anything about it.

Please report a bug here: https://gitlab.freedesktop.org/drm/amd/-/issues

**Comment by ekini** [comment]
You need to install https://www.synaptics.com/products/displaylink-graphics/downloads/ubuntu driver

**Comment by emersion** [comment]
I don't see "DisplayLink" mentioned in the dock specs.

**Comment by hanckmann** [comment]
Yes, well...  It was not in the specs I checked either,  but (I only now noticed) it is printed at the bottom of the docking station.

Would never have bought it if i knew... and the DisplayLink driver is not working properly (maybe because of amd... dunno).

Anyway, you can close this issue as it is not sway related.
Thanks for you great work on sway (and related software). It is very much appreciated!
