### ISSUE TITLE
crash after closing laptop lid, removing hdmi monitor, and opening laptop lid

### ISSUE THREAD

**Issue by hanckmann** [swaywm/sway#6222]
### Please fill out the following:
- **Sway Version:** sway version 1.6

- **Debug Log:** see attachment.

- **Stack Trace:**
I don't think I have a detailed stack trace

**Description:**
Sway crashed.

I did the following:
1. close the laptop lid
2. removed all attached devices (external monitor, external mouse, power supply, etc.)
3. opened the laptop lid

[crash.sway.log](https://github.com/swaywm/sway/files/6365573/crash.sway.log)

(I removed the first part of the log file because of its size, but I still have the whole file if required -- but it is larger than 6 MB)

**Comment by emersion** [comment]
Please provide a stack trace. You can do so by compiling from source, reproducing the crash and then running `coredumpctl gdb` and then `bt full`.

Here are some instructions to compile from source: https://github.com/swaywm/sway/wiki/Development-Setup#compiling-as-a-subproject

**Comment by hanckmann** [comment]
I am currently unable to reproduce. I will reopen this issue when it occurs again.
Sorry :-1:
