### ISSUE TITLE
slurp：slurp will be repeatedly exec in waybar until click waybar 

### ISSUE THREAD

**Issue by wuliaotc** [swaywm/sway#6231]
- **Sway Version:**sway version 1.6-80128d23 (Apr 25 2021, branch 'master')

- **Waybar Version:**Waybar v0.9.7-9-g66d8035 (branch 'master')

- **Configuration File:** waybar config

    ``` conf
    {
    |   "layer": "top",.
    |   "position": "top",
    |   "modules-right": ["custom/colorchooser"],
    |   "custom/colorchooser":{
    |   |   "format":"",
    |   |   "on-click": "slurp -p",
    |   },
    }
    ```

- **Description:**
    - Write the above settings to the file `$CONFIG_PATH/config`
    - run sway
    - run `waybar -c $CONFIG_PATH/config -s /dev/null` 
    - **1st:** click the  icon`` to triger `slurp -p`.
    - **2nd:**click **anywhere but waybar**,and slurp excute success and get true output.
    - **3rd(this action will be repeated until do as `4th`):**Click **anywhere on waybar** ,`slurp -p` will be triger  again,then do as **2nd** to repeat or do as `4th` to stop.
    - **4th**:click **anywhere on waybar**,then `slurp -p` excute success and get true output.

**Comment by emersion** [comment]
Sounds like a waybar bug to me. Please report it to them.
