### ISSUE TITLE
1.6 rendering issues

### ISSUE THREAD

**Issue by ixru** [swaywm/sway#6233]
- **Sway Version:**
1.6-fd36289f (Apr 26 2021, branch 'master')

- **Debug Log:**
https://gist.github.com/ixru/ee113f3e4ef0b1233ab05a7d08e7329f

- **Configuration File:**
default

- **Description:**
Launching sway presents a black screen. Sometimes the backrgound is rendered, but not corrrectly. Nothing else will show.
Worked well with 1.5. Hardware is an i7-4790k with a 1080ti.

**Comment by ixru** [comment]
Fixed with `WLR_DRM_NO_MODIFIERS=1`

**Comment by rkanati** [comment]
This should probably be left open, if `WLR_DRM_NO_MODIFIERS=1` is just a work-around.

**Comment by ixru** [comment]
You can find why here https://github.com/swaywm/sway/wiki#sway-16-shows-garbage-on-nouveau

**Comment by emersion** [comment]
> This should probably be left open, if WLR_DRM_NO_MODIFIERS=1 is just a work-around.

These are upstream bugs fixed in Mesa master, so we're closing the downstream Swya issues.
