### ISSUE TITLE
Kinetic scrolling cannot be disabled in Chromium/Firefox

### ISSUE THREAD

**Issue by gbaranski** [swaywm/sway#6237]
### Please fill out the following:
- **Sway Version:** 1.6.

- **Configuration File:** default

- **Description:**
Kinetic scrolling is enabled by default and cannot be disabled(at least i couldn't find that option), to reproduce:
  - Run sway
  - Open chromium/Firefox
  - Scroll with touchpad

https://user-images.githubusercontent.com/34353640/116209656-6ccd3500-a742-11eb-99a2-7883b79a4451.mp4

**Comment by emersion** [comment]
This is not something Sway has control on. This is something clients (Chromium) do on their own.

**Comment by gbaranski** [comment]
> This is not something Sway has control on. This is something clients (Chromium) do on their own.

Okay, sorry for disturbing. 

If anyone is also having the same issue, just install Firefox, open `about:config` and set `apz.gtk.kinetic_scroll.enabled` to false. Then open preferences and scroll to the bottom and uncheck "Use smooth scrolling". I could not find any solution for Chromium.
