### ISSUE TITLE
Sway does not start normally after upgrade to v. 1.6

### ISSUE THREAD

**Issue by Galicarnax** [swaywm/sway#6238]
First - thanks for this nice window manager, using it for more than a year already.

- **Sway Version:**
`sway version 1.6`

- **Debug Log:**
https://gist.github.com/Galicarnax/7c32579ae944ffaaa2cad3b68c3abfb2
(this is the log of the `sway` launched with default config)

- **Configuration File:**
The issue is reproduced with default config copied from `/etc/sway/config`

- **Description:**
After updating sway to version 1.6, it won't start normally. The issue is reproduced with the default config. Sway starts, but its default background image is destorted like this:
![image](https://user-images.githubusercontent.com/44889241/116250264-631dee80-a78f-11eb-95af-020e8d10af8f.png)
and nothing happens if I invoke key bindings or move the mouse. The only thing I can do is to switch to virtual console, kill sway, and downgrade it to previous version (1.5.1), together with wlroots. Downgraded version works fine. The linked debug log reveals one `[ERROR]` (`Failed to set DPMS property: Permission denied`), from which, however, it's not clear for me what to do next (or even if it's relevant to the issue).

  - __Hardware__: Lenovo Legion 5 laptop, AMD Ryzen 5 CPU, GeForce GTX 1650 Ti GPU
  - __OS__: Arch Linux
  - __GPU driver__: nouveau

**Comment by emersion** [comment]
See https://github.com/swaywm/sway/wiki#sway-16-shows-garbage-on-nouveau

**Comment by Galicarnax** [comment]
Solved, thanks.
