### ISSUE TITLE
Raspberry Pi VC4 detection code

### ISSUE THREAD

**Issue by dev-0x7C6** [swaywm/sway#6241]
Hi,

Is this a valid detection for vc4 support? I'm currently running raspberry pi with build-in vc4 module.

https://github.com/swaywm/sway/blob/30e400c0a3d5d11ba15dc4ab6cdcfe2e71cfce01/sway/main.c#L70-L74

**Comment by emersion** [comment]
Since vc4 is now in mainline, we can probably remove this whole function altogether.

**Comment by dev-0x7C6** [comment]
#6242

**Comment by MarkusVolk** [comment]
Branch v1.6 still contains this function. 
I'm getting an error message if vc4 wasn't built as a module
