### ISSUE TITLE
sway hangs under QEMU/KVM (bochs-drm driver)

### ISSUE THREAD

**Issue by minijackson** [swaywm/sway#6244]
- **Sway Version:**

`sway version 1.6`

- **Debug Log:**

sway debug log: https://gist.github.com/minijackson/67e21539a1d1f295e1fae9d2514c129a
dmesg: https://gist.github.com/minijackson/cc67a1607c2caef08f7936bd85ecb53b

- **Configuration File:**

The provided default configuration file

- **Stack Trace:**

No crash

- **Description:**

Trying to execute sway under QEMU with the bochs-drm driver hangs the screen, but does not hang the VM, as said in https://github.com/swaywm/sway/issues/6210#issuecomment-829479837.

I'm using NixOS on master with just sway and its default configuration file. The same configuration with sway 1.5.1 does not hangs the screen, and I can use sway without issues.

<details>
<summary>Here is the full qemu command-line (sorry for the NixOS-specific stuff)</summary>

```bash
/nix/store/b99cqrag2qiz5qc9z1py0dswl24pb47y-qemu-5.2.0/bin/qemu-system-x86_64 \
  -enable-kvm \
  -cpu max \
  -name nixos \
  -m 1024 \
  -smp 1 \
  -device virtio-rng-pci \
  -net nic,netdev=user.0,model=virtio \
  -netdev user,id=user.0 \
  -virtfs local,path=/nix/store,security_model=none,mount_tag=store \
  -virtfs local,path=/tmp/nix-vm.J19LPTb5OX/xchg,security_model=none,mount_tag=xchg \
  -virtfs local,path=/tmp/nix-vm.J19LPTb5OX/xchg,security_model=none,mount_tag=shared \
  -drive cache=writeback,file=/tmp/nixpkgs/nixos.qcow2,id=drive1,if=none,index=1,werror=report \
  -device virtio-blk-pci,drive=drive1 \
  -usb \
  -device usb-tablet,bus=usb-bus.0 \
  -kernel /nix/store/s4r1b8ci3d5jhr77sgg0f43w70paw1c4-nixos-system-nixos-21.05pre-git/kernel \
  -initrd /nix/store/s4r1b8ci3d5jhr77sgg0f43w70paw1c4-nixos-system-nixos-21.05pre-git/initrd \
  -append "loglevel=4 net.ifnames=0 init=/nix/store/s4r1b8ci3d5jhr77sgg0f43w70paw1c4-nixos-system-nixos-21.05pre-git/init regInfo=/nix/store/6d6vr25qxn7cmydq0jnvw35l485sc8jp-closure-info/registration console=ttyS0,115200n8 console=tty0"
```

</details>

<details>
<summary>To reproduce with Nix</summary>

- [Install Nix](https://nixos.org/download.html#nix-quick-install)
- Clone https://github.com/NixOS/nixpkgs/ on the master branch and cd into it
- Create a file named `sway-config.nix`

<details>
<summary>Content of sway-config.nix</summary>

```nix
{ modulesPath, ... }:

{
  imports = [
    (modulesPath + "/virtualisation/qemu-vm.nix")
  ];

  programs.sway.enable = true;

  users.users.bob = {
    isNormalUser = true;
    password = "foobar";
    extraGroups = [ "video" ];
  };

  virtualisation.memorySize = 1024;

  documentation.enable = false;
}
```

</details>

- Execute `NIXOS_CONFIG=$PWD/sway-config.nix nixos-rebuild --fast build-vm -I nixpkgs=.`
- Launch the VM with `./result/bin/run-nixos-vm`
- Login with `bob:foobar`
- execute sway
- You can take back control of the VM by switching to the serial tab from the "View" menu

</details>

Thanks for the great work!

**Comment by emersion** [comment]
This is required to make Sway work:

```
00:00:00.730 [DEBUG] [wlr] [render/egl.c:599] DMA-BUF import extension not present
```

This means 3D accel is unavailable:

```
00:00:00.758 [INFO] [wlr] [render/gles2/renderer.c:872] GL renderer: llvmpipe (LLVM 11.1.0, 256 bits)
```

This is weird:

```
00:00:01.015 [ERROR] [wlr] [backend/drm/renderer.c:236] Renderer doesn't support format 0x34325258
```
