### ISSUE TITLE
Rendering issues after switching tty with nouveau

### ISSUE THREAD

**Issue by ArenM** [swaywm/sway#6248]
Sway Version: `1.6-7c74f01f (Apr 30 2021, branch 'master')` built from the `sway-git` aur package
Debug Log (and screenshots): https://gist.github.com/ArenM/98fcb8d76799f8361fa5d36088827db8
Configuration File: default

To reproduce this I've been starting sway from a tty, switching to a different tty and back (because of a separate bug that seems to be in wlroots) to get sway to render nicely, then after switching ttys and back again sway doesn't render correctly. I have included pictures (artifacts don't appear in screenshots using grimshot) of this in the gist along with the debug logs.

I also tested with wayfire, and weston and could not reproduce this bug.

**Comment by emersion** [comment]
See https://github.com/swaywm/sway/wiki#sway-16-shows-garbage-on-nouveau
