### ISSUE TITLE
Gnome apps fail to connect to DBUS

### ISSUE THREAD

**Issue by lucabaldesi** [swaywm/sway#6250]
Hi,
I am running sway 1.6 on arch linux and last week, after a system update, my GNOME apps (evolution, nextcloud and gnome-terminal) could not start anymore.

The error is very cryptic:
```
Error calling StartServiceByName for org.gnome.Terminal: Timeout was reached
```

However, after some googling and trial and error I found out it is DBUS related. DBUS to me looks designed to be the more opaque to users and developers as possible, but I solved the issue by adding in my sway configuration file the following line:
```
exec --no-startup-id dbus-update-activation-environment --all
```
This command loads environmental variables into dbus. Note that if I run dbus-update-activation-environment before sway, it does not take effect. Hence, I think sway is initializing some extra variables and then it fails to share them with the bus daemon.

Best,
Luca

P.s., thanks to all the community, sway is awesome!

**Comment by emersion** [comment]
Yes, this is documented on the wiki: https://github.com/swaywm/sway/wiki#gtk-applications-take-20-seconds-to-start

Not much we can do about it.
