### ISSUE TITLE
QT applications are partly transparent when using scale factor

### ISSUE THREAD

**Issue by pkupper** [swaywm/sway#6252]
### Please fill out the following:
- **Sway Version:**
sway version 1.6

- **Debug Log:**
https://gist.github.com/pkupper/370543e8e7aa1ba250f71650eca0a737

- **Configuration File:**
Default config with modified output configuration:
https://gist.github.com/pkupper/6d9fffc8654a2d239688bd6808a68d9a

- **Description:**
#### Steps to reproduce
1. Configure at least one output to have a scale factor != 1.
2. Open a floating window in any QT applications on any output (e.g. QT "Standard Dialogs" Example, OBS, QSynth, FreeCAD, Qjackctl).

#### Result
- Most of the time the window's background and some widgets are fully transparent (see screenshots).
- Widgets with hover effects appear when hovering over them.
- Everything appears when resizing the window or moving it to another output.

#### Additional observations
- For some applications the issue only occurs on the unscaled output (when the second output has a scale factor != 1).
- This issue has some similarities to #6147, which I am also affected by.

#### Screenshots
![color_dialog](https://user-images.githubusercontent.com/11900073/117068708-ef01be80-ad2b-11eb-8408-7f77b187ca96.png)
![font_dialog](https://user-images.githubusercontent.com/11900073/117068710-ef9a5500-ad2b-11eb-866b-26bf701b5645.png)
More screenshots can be found in the QT bug report (see below).

As it is unclear whether this is a sway or a QT bug (only occurs with both), I have also reported this issue to QT: https://bugreports.qt.io/browse/QTBUG-93380

**Comment by kennylevinsen** [comment]
> 00:00:07.783 [DEBUG] [wlr] [types/wlr_surface.c:189] Client bug: submitted a buffer whose size (1079x499) is not divisible by scale (2)

Client bug

**Comment by pkupper** [comment]
Thanks, that makes perfect sense. I'll take this over to the QT report then and close this for now.

**Comment by faern** [comment]
@pkupper Do you have a link to your corresponding QT issue? I have the same problem and would like to keep track of the issue.

**Comment by pkupper** [comment]
@faern The QT issue is already linked at the end of my original bug report. But here it is again: https://bugreports.qt.io/browse/QTBUG-93380
It's reassuring to hear that I'm not the only one with this issue. It does seem very setup specific. If you have made any additional observations be sure to share them in the QT issue. Your sway output config could also be useful.

**Comment by faern** [comment]
Ah. I did not read carefully enough. Thanks. I wrote about some of my findings in that thread
