### ISSUE TITLE
Ability for windows sizes to exceed monitor size?

### ISSUE THREAD

**Issue by kamiyaa** [swaywm/sway#6257]
I'm not sure if this is a "feature" of i3, but right now sway prevents windows from exceeding the size size for no reason?

Steps to reproduce:
1. make a floating window
2. try to increase its size as much as possible
3. window size gets limited to the screen size (ie. 1920x1080)

Would appreciate it if this restriction gets removed because certain programs expect their windows to be able to increase in size indefinitely.
One example would be [swappy](https://github.com/jtheoof/swappy).
If I were to take a screenshot of the whole screen and open up the edit tools, the window gets cut off because  
`width_of_screen + width_of_edit_tools >= width_of_screen`

**Comment by emersion** [comment]
I'm able to resize windows past the screen size. Maybe swappy is setting a max size?

**Comment by kamiyaa** [comment]
That's odd, I've tried this with other applications (firefox, alacritty, nautilus, etc) and they all seem to be not working. Could it be a sway config that does this?

**Comment by kamiyaa** [comment]
Never mind, I realized there is an option called `floating_maximum_size`
```
       floating_maximum_size <width> x <height>
           Specifies the maximum size of floating windows. -1 x -1 removes the upper limit. The default is 0 x 0,
           which will use the width and height of the entire output layout as the max
```
Its fixed with `floating_maximum_size -1 x -1`
