### ISSUE TITLE
Keybord repeat-rate acceleration

### ISSUE THREAD

**Issue by bagnaram** [swaywm/sway#6258]
It would be nice to support a  key-hold acceleration rate rather than a constant repeat rate. This was common in some IBM compatibles like the Zenith eaZy PC. The logic to handle the acceleration would need to be included here:
https://github.com/swaywm/sway/blob/4e77bc293515ea2f00ebbc4395cb0eb4446d0195/sway/input/keyboard.c#L627

Propose adding an additional repeat acceleration field to wlroots:
https://github.com/swaywm/wlroots/blob/84dea55b20b60c229a5e31ccd37b58c96cba611a/include/wlr/types/wlr_keyboard.h#L65

**Comment by emersion** [comment]
The Wayland protocol doesn't support this. If you want this feature, please open a new issue in the Wayland issue tracker.
