### ISSUE TITLE
Native linux webex client crashes during authentication and unable to join meetings

### ISSUE THREAD

**Issue by jeLee6gi** [swaywm/sway#6271]
### Please fill out the following:
- **Sway Version:**
  - sway version 1.6-31b4b96e (May 13 2021, branch 'master')

- **Debug Log:**
  - Recorded while trying to authenticate with SSO https://pastebin.com/kZSU0mDW

- **Configuration File:**
  - I was able to reproduce the error with the default configuration file

- **Description:**
  - I am trying to run the native linux webex client, which was released only a few days ago (https://www.webex.com/downloads.html)
  - It starts up and I can enter my email address in the first step of the authentication flow
  - In the second step you are supposed to get redirected to your SSO provider but at this point `CiscoCollabHost` dumps core (https://pastebin.com/bipwvPEv)
  - I switched over to gnome and completed the authentication there to test if it's fine beyond that point
  - Back in sway, the main UI of webex works fine and I can use the messaging feature of but I am unable to join any meetings (works in gnome too)

**Comment by emersion** [comment]
These are likely client bugs, and we can't do anything about them because it's closed-source.

**Comment by jeLee6gi** [comment]
There is a workaround in the comments in the AUR that works for me too. Forcing webex to run under xwayland by unsetting `WAYLAND_DISPLAY` prevents the crashes and allows me to join meetings.

https://aur.archlinux.org/packages/webex-bin/#comment-808695
