### ISSUE TITLE
Ghidra main window blank with display rotation

### ISSUE THREAD

**Issue by icecream95** [swaywm/sway#6272]
### Please fill out the following:
- **Sway Version:**
  - sway version 1.6

- **Debug Log:**

https://gist.github.com/icecream95/ac887ea52ee4adb614dcfb1501666d59

- **Configuration File:**

Only change from default for the issue to reproduce:

```
output * {
 transform 270
}
```

- **Description:**

Run [Ghidra](https://ghidra-sre.org/) (I used 9.2, with OpenJDK 11.0.5), using the `ghidraRun` script.

The main window will be a solid grey colour, though there are a couple of popup windows which render fine.

**Comment by distek** [comment]
Have you tried launching it like so:
```
_JAVA_AWT_WM_NONREPARENTING=1 ghidraRun
```
Source: https://github.com/swaywm/sway/wiki/Running-programs-natively-under-wayland#java-under-xwayland

This works with OWASP's Zap

**Comment by icecream95** [comment]
Thanks, that fixes it.
