### ISSUE TITLE
Command to dim windows

### ISSUE THREAD

**Issue by 9ary** [swaywm/sway#6274]
There is already a command to set the opacity of windows, and a contrib script to fade out inactive windows. I find that translucency tends to be distracting and impacts legibility (especially without a blurring filter, which sway does not have).
I'd like to be able to dim windows instead (ie multiply pixels by an arbitrary coefficient, without blending with the background).

**Comment by 9ary** [comment]
After digging into this a little bit I've found that this would be fairly complex to implement, and experimentation with a hacky implementation tells me I don't actually want this anyway. It's far more usable than translucency, but it's still distracting and really unnecessary.

**Comment by juchiast** [comment]
Can we reopen this? I miss picom's inactive dim option when switching to sway
