### ISSUE TITLE
Flickering on some sites

### ISSUE THREAD

**Issue by igorlfs** [swaywm/sway#6291]
- **Sway Version:**
  - `sway version 1.6`

- **Debug Log:**
  - https://gist.github.com/igorlfs/515f45334e4df65e5b8c19d5ec0dbed1 (default config) 

- **Configuration File:**
  - I believe it's unnecesary, as it can be reproduced with the default config.
  
- **Description:**
  - Open Firefox (wayland). 
  - Visit https://play.cprewritten.net/
  - The game (as opposed to the whole window) will flicker constantly.
  
This may seem silly (ie, club penguin), but it does happen on other websites, it's just not as reproducible.
I also recorded it happening (though is not high quality), if it may help explaining:

https://user-images.githubusercontent.com/84649544/119245780-26f16a00-bb52-11eb-82a2-30a051749b34.mp4

**Comment by wmww** [comment]
I can repro, and it doesn't happen under WebRender. Might be related to https://bugzilla.mozilla.org/show_bug.cgi?id=1637397/https://bugzilla.mozilla.org/show_bug.cgi?id=1685263.

**Comment by igorlfs** [comment]
I'm no longer able to reproduce this so I'm closing
