### ISSUE TITLE
Unexpected `next_on_output` behavior with `workspace_auto_back_and_forth`

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [swaywm/sway#6299]
- **Sway Version:** 1.6

- **Debug Log:** [here](https://gist.github.com/RagnarGrootKoerkamp/4b7b56a9c1737a4c2230d092b09cd641)

- **Configuration File:**
```
set $mod Mod4
workspace_auto_back_and_forth yes
bindsym $mod+Tab workspace next_on_output

bindsym $mod+Return exec foot
bindsym $mod+1 workspace number 1
bindsym $mod+2 workspace number 2
bindsym $mod+3 workspace number 3
bindsym $mod+4 workspace number 4
bindsym $mod+5 workspace number 5
```

- **Description:**
- Set `workspace_auto_back_and_forth` to `yes`
- Execute `swaymsg 'workspace next_on_output'` on an output with only a single workspace. Instead of doing nothing, this will focus the last active workspace, which may have been on a different output (or could be a now empty workspace on the same workspace). Note that the last active workspace is completely ignored when there is more than one active workspace on the current output.

Expected behavior: `next_on_output` does nothing when a workspace is the only active workspace on its output, regardless of the `workspace_auto_back_and_forth` setting.

Actual behavior: `next_on_output` switches to the last active workspace, which can be on a different output or an empty workspace.

**Comment by RagnarGrootKoerkamp** [comment]
This behavior comes from here: https://github.com/swaywm/sway/blob/master/sway/commands/workspace.c#L212-L238

When handling the `workspace [--no-auto-back-and-forth] <workspace identifier>` command, the identifier is first resolved, and the `auto-back-and-forth` is only applied at the end.

I find that this makes for quite confusing behavior, so I'd argue that `--no-auto-back-and-forth` should be implied for all the 'relative' movements `next`, `prev`, `next_on_output`, `prev_on_output`.

`--no-auto-back-and-forth` is also ignored for the `workspace back_and_forth` command.

Anyway, this is all quite subjective and I've found my workaround, so feel free to close.

**Comment by Xyene** [comment]
What does i3 do in this case? If i3 differs we'd want to mark this as i3-compat and address it, otherwise we want to retain i3 behavior.

**Comment by RagnarGrootKoerkamp** [comment]
Just tested: i3 never switches output when doing `workspace next_on_output`, so when there is only a single workspace on an output, it just keeps that workspace focused when doing `workspace next_on_output` from there.

Not sure whether `next` and `prev` also differ. I never use those so don't really know whats expected anyway.
