### ISSUE TITLE
Ubuntu 20.04 intalled with apt gets error [swaymsg/main.c:412] Unable to retrieve socket path

### ISSUE THREAD

**Issue by Silve2611** [swaywm/sway#6300]
### Please fill out the following:
- **Sway Version:**
user@B9440UA:~/termite-install$ swaymsg -t get_version
2021-05-31 16:31:19 - [swaymsg/main.c:412] Unable to retrieve socket path
sway version 1.4

- **Debug Log:**
https://pastebin.com/ukXf2DCr

- **Configuration File:**
on made install with **sudo apt install sway**

- **Description:**
swaymsg is returning the error **[swaymsg/main.c:412] Unable to retrieve socket path** no matter what command is used

**Comment by emersion** [comment]
swaymsg needs to be run from inside Sway.
