### ISSUE TITLE
Xwayland apps are blurry on High DPI / HiDPI screen

### ISSUE THREAD

**Issue by tuschla** [swaywm/sway#6311]
- **Sway Version:sway version 1.6**

- **Configuration File: Default configuration file**

- **Description:**
Xwayland Apps like vscode, signal-desktop etc. appear blurry on the 14' 4K screen of my notebook while the problem is non-existant on Gnome 40 on Wayland.

**Comment by emersion** [comment]
This is an Xwayland bug: https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/432

GNOME uses a hack to address this.
