### ISSUE TITLE
Hot plugging a new monitor doesn't become active

### ISSUE THREAD

**Issue by atl-mk** [swaywm/sway#6312]
- **Sway Version:** sway version 1.6 (but I've experienced this issue for about a year)

- **Debug Log:** [Debug log gist](https://gist.github.com/atl-mk/b6c5088dd26a546872886060587e88b6)

- **Configuration File:** Default + 
`output eDP-1 scale 1.5`
`output eDP-1 res 3840x2160`
`output DP-1  res 3840x2160`
`output DP-2  res 3840x2160`
`set $laptop eDP-1`
`bindswitch --reload --locked lid:on output $laptop disable`
`bindswitch --reload --locked lid:off output $laptop enable`

I did try moving the config file to a separate location so it wouldn't be picked up and this did not fix the issue

- **Stack Trace:** N/A sway does not crash

- **Description:**
  - Start sway on laptop
  - Plug in monitor that wasn't plugged in when sway started
  - Sway fails to enable the the 'new' monitor

- **Additional Info:**
  - This only happens if
    - sway was not started with the monitor OR
    - sway was started with the monitor, then the monitor was unplugged, then the computer sleeps via closing the lid, then the computer wakes, the n the monitor is plugged back in
  - As probably guessed by the logs `swaymsg --pretty -t get_outputs` will show that the monitor is plugged in, it's just that it's inactive and I can't manually set it active with `swaymsg output DP-2 enable`
  - I can close the lid of the laptop without sleeping the device and continue to use the secondary monitor if it was already active
  - I can suspend the laptop with the monitor being active and it will resume and make the monitor active again
  - I can unplug the monitor, suspend the laptop without closing the lid, resume, plug the monitor back in and it will work (become active)
  - Removing the bindswitch commands doesn't resolve the issue
  - Device: `Dell precision 7550` using the Intel GPU
  - Primary GPU: `Intel CometLake-H GT2 [UHD Graphics]`
  - Secondary disabled GPU: `NVIDIA Quadro T2000 Mobile / Max-Q`
  - Previous device (same issue): `Dell precision 5530` using the Intel GPU. This used the same OS installation, and I migrated
  - Monitor: `Dell U2718Q`
  - Connection: `USB-C (laptop) -> DP (monitor)` cable which connects to the Intel GPU

**Comment by emersion** [comment]
The debug log isn't complete. Please provide a full debug log.

Can you try this? https://github.com/swaywm/sway/wiki#sway-16-shows-garbage-on-nouveau

```
00:00:34.296 [ERROR] [wlr] [backend/drm/atomic.c:35] connector DP-2: Atomic commit failed (modeset): Invalid argument
```

Can you provide DRM debug logs as well? https://github.com/swaywm/wlroots/wiki/DRM-Debugging

**Comment by atl-mk** [comment]
> Can you try this? https://github.com/swaywm/sway/wiki#sway-16-shows-garbage-on-nouveau

That fixed it! Thank you! Sorry I didn't think it would be the same issue. I enjoy using sway, thanks for maintaining it.

I've added to the wiki that my symptom was an entirely inactive screen (the monitor reported no input at all).

> The debug log isn't complete. Please provide a full debug log.

Sorry, I cut it to the point where the monitor was plugged in.

> Can you provide DRM debug logs as well? https://github.com/swaywm/wlroots/wiki/DRM-Debugging

I will edit this comment with the debug log

For others following along, it seems like the issue was reported here: https://github.com/swaywm/sway/issues/6167

IDK why I feel like I've had this issue for longer, probably bad memory conflating a separate unrelated issue I used to have with a TB3 dock.

**Comment by emersion** [comment]
Ah, if that fixed it, no need for additional info :)

**Comment by jeanlucthumm** [comment]
This link is dead:

https://github.com/swaywm/sway/wiki#sway-16-shows-garbage-on-nouveau

What was the fix (having same issue)?

**Comment by atl-mk** [comment]
Sorry, I updated the title, but you can see from the anchor in the link what section was being pointed to.

https://github.com/swaywm/sway/wiki#sway-16-shows-garbage-or-a-blank-screen-on-nouveau
