### ISSUE TITLE
Secondary screen only shows pointer

### ISSUE THREAD

**Issue by carlpett** [swaywm/sway#6314]
### Please fill out the following:
- **Sway Version:**
  - 1.6 (From Fedora package sway-1.6-1.fc34.src.rpm)

- **Debug Log:**
  - https://gist.github.com/carlpett/6610e6d4185f6ab8fd71f269492808c6

- **Configuration File:**
  - Reproduces with default config

- **Stack Trace:**
  - N/A

- **Description:**
When plugging in an external display, it seems to be correctly detected and turns on, but the only thing shown is the mouse pointer. `swaymsg -t get_outputs` shows the output, and claims a workspace is active on it. However if I move containers there, or start applications, they do not render anything. Just the pointer (which renders movement etc correctly).

System is Fedora 34 running on a Thinkpad X1 Extreme gen3. Built-in screen uses Intel graphics, but there is a Nvidia card as well (noveau is installed, not the proprietary driver). I've tried the ways of connecting the external screen available, direct HDMI and HDMI -> USB-C, with same results.

**Comment by emersion** [comment]
Can you try this? https://github.com/swaywm/sway/wiki#sway-16-shows-garbage-on-nouveau

**Comment by carlpett** [comment]
Yeah, that fixed it, thanks! Would it be okay if I update that entry to mention that "garbage" might be a blank screen? I interpreted as being some garbled mess of flickering colors or something like that, not a functional pointer and a blank screen :)

**Comment by emersion** [comment]
Sure, go ahead
