### ISSUE TITLE
`for_window [app_id=".*"] floating enable` doesn't work for all windows

### ISSUE THREAD

**Issue by Kreyren** [swaywm/sway#6315]
I am trying to configure floating by default while having tiling on demand on my sway, but the configuration is seemingly not identifying the `app_id` correctly.

### Steps to reproduce
0. Get `sway` and run it
1. Set `for_window [app_id=".*"] floating enable` and reload config
2. Notice that some windows are floating by default and others such as `firefox` are not

### System info
- **Sway Version:** 1.6
- **Configuration File:** http://ix.io/3pcp
- **OS:** NixOS 21.05 (Okapi) x86_64
- **Host:** 20089 Lenovo G770
- **Kernel:** 5.10.40

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
I'd try matching for any `class`, `instance` and the `title`, too.

**Comment by Kreyren** [comment]
Title works! thanks

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
> Title works! thanks

good.
as the [Archwiki post on swaywm, section Floating windows](https://wiki.archlinux.org/title/Sway#Floating_windows) notes:
> If the app_id happens to be null for some windows, you might have to use the class and/or the instance attributes to enable floating mode/window assignments. You can search the output and create fine grained rules for your windows.
