### ISSUE TITLE
Sway crashes upon opening any program

### ISSUE THREAD

**Issue by rbutoi** [swaywm/sway#6320]
https://x0.at/P0py.txt shows the runtime log of it crashing. Upon opening a new konsole, or any other terminal or Firefox, sway crashes.

The backtrace is https://x0.at/VIip.txt

**Comment by rbutoi** [comment]
Latest version seems to work fine, not sure what happened there.

**Comment by Sukhman723** [comment]
it is also happening with me but in my case it is Makehuman when sway crashes
