### ISSUE TITLE
Output Identifiers not Unique

### ISSUE THREAD

**Issue by evlli** [swaywm/sway#6321]
I have two outputs attached to my laptop that have the same identity.
They show up as `Output DP-3 'Goldstar Company Ltd 24MB56 '` and `Output DP-5 'Goldstar Company Ltd 24MB56 '` respectively.
I think? there should be an address trailing the model name like it does for `eDP-1` but it seems to be missing.
A feasible workaround might be to allow matching for both Port and Display at the same time.

If I'm missing something please let me know.

**Comment by emersion** [comment]
We can't really do anything about it, the screen don't tell us their serial number, so we can't tell them apart. Use the connector names (`DP-3` and `DP-5`) instead.
