### ISSUE TITLE
Scratchpad: send/receive in tabbed mode?

### ISSUE THREAD

**Issue by tmpm697** [swaywm/sway#6328]
Info:
```
sway ver: 1.6
os: archlinux up-to-date
```
Issue: when I use tabbed layout and send a window to scratchpad. When I bring it back, it will come in floating window mode -- not tabbed into other windows.

So I want somehow it attach to other windows in tabbed mode and next to current active window (so I can cycle back to active it)

**Comment by emersion** [comment]
What is the i3 behavior here?

**Comment by tmpm697** [comment]
Idk, I don't use i3 before asking this question.

**Comment by emersion** [comment]
If i3 does it like Sway, we'll want to retain our current behavior.

**Comment by qqwa** [comment]
I don't really understand what he tries to do. But scratchpad works as expected.

https://i3wm.org/docs/userguide.html#_scratchpad
> [..] `move scratchpad` will move a window to the scratchpad workspace [..] when using `scratchpad show`, the window will be shown again, as a **floating window**, centered on your current workspace

**Comment by fluix-dev** [comment]
For the desired functionality, you could set up a bind for `scratchpad show` immediately followed by `floating disable`.

**Comment by tmpm697** [comment]
I think the use case can be useful but add up some costs.

Anyway it's name "floating" so it should floating. 

Problem is sending an tabbed window to scratchpad but receive back a floating. 

I gave up in this and use tabbed and workspace to achieve my purpose. Closed.

**Comment by shakakibara12** [comment]
> I think the use case can be useful but add up some costs.
> 
> Anyway manpage mentions "floating" so it should be floating.
> 
> Problem is sending an tabbed window to scratchpad but receive back a floating one.
> 
> I gave up on this and use tabbed and workspace to achieve my purpose. Closed.

sorry for reviving closed discussion.
This is what you need to do:

**`bindsym $mod+minus scratchpad show, floating toggle`**
