### ISSUE TITLE
Allow to cycle through windows despite in fullscreen mode?

### ISSUE THREAD

**Issue by tmpm697** [swaywm/sway#6329]
Info:
```
sway ver: 1.6
os: archlinux up-to-date
```
Issue: When I've been playing youtube video and press f11 to watch it in fullscreen mode, I can not cycle to next/prev windows (focus right/left).

I expect somehow I still be able to cycle other windows and f11 in firefox will just have video rendered pixels on all screen space but not prevent cycle to other windows.

**Comment by emersion** [comment]
Sorry, but this doesn't make sense to me.

**Comment by tmpm697** [comment]
Sorry but how to set back firefox window to normal mode (not fullscreen mode) before `focus left/right`. Is there a sway command to do that before `focus left/right`?
