### ISSUE TITLE
Document and/or fix `workspace next_on_output --create` flag

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [swaywm/sway#6333]
The `--create` flag to `workspace next_on_output` was added in https://github.com/swaywm/sway/pull/3697, but is undocumented in `man 5 sway`, and appears to have some bugs:

I'm using this configuration:
```
    workspace  1 output $monitor
    workspace  2 output $monitor
    workspace  3 output $monitor
    workspace  4 output $monitor
    workspace  5 output $monitor
    workspace  6 output $laptop
    workspace  7 output $laptop
    workspace  8 output $laptop
    workspace  9 output $laptop
    workspace 10 output $laptop
```
Without my monitor plugged in (so laptop only), I do the following:
- open a terminal on workspace 10, and make sure that's the only workspace.
- Run `swaymsg 'workspace --no-auto-back-and-forth next_on_output --create'`
- This creates workspace 6 (because that would be the next on on this monitor), but *does not focus it*.
- Running the same command again then creates workspace 7, but again does not focus it.
- Repeating creates workspaces 8 and 9 as well.
- Doing it one more time creates **and switches to** workspace `--no-auto-back-and-forth next_on_output`. The name is probably a leftover from an earlier accidental switch to a named workspace, but it's very surprising that now the switching does work.

Should this `--create` flag be fixed&documented, or just be removed alltogether? I also don't really understand why this flag would work for `prev_on_output` and `next_on_output`, but not for `prev` and `next`.

`prev_on_output --create` has similar, although slightly different issues.

**Comment by emersion** [comment]
Is this a duplicate of https://github.com/swaywm/sway/issues/5913?

**Comment by RagnarGrootKoerkamp** [comment]
Ah yes, that seems to be the same; should have searched first.
