### ISSUE TITLE
Sway does not let other clients receive pointer events if client restricts its input region.

### ISSUE THREAD

**Issue by Dudemanguy** [swaywm/sway#6341]
- **Sway Version:**
sway version 1.6-c53ef023 (Jun 23 2021, branch 'master') or just 1.6

- **Debug Log:**
[Sway Debug](https://0x0.st/-95l.log)
[Wayland Debug](https://0x0.st/-950.log)

- **Configuration File:**
It happens with the default config.

- **Description:**
I discovered this while trying to implement cursor passthrough in mpv here: https://github.com/mpv-player/mpv/pull/8949. When setting the region to 0 (`wl_region_add(region, 0, 0, 0, 0);`) to ignore the entire surface, what happens in sway is that the mouse events/buttons are correctly ignored. However, any windows/surfaces below the mpv window do not appear to receive any mouse events as one would expect. In weston, this works as one would expect (the window below receives clicks and so on).

**Comment by emersion** [comment]
Should be fixed by scene-graph, please re-open if you can reproduce with Sway master.
