### ISSUE TITLE
Vulkan games black screen

### ISSUE THREAD

**Issue by shoober420** [swaywm/sway#6343]
- **Sway Version:**
  - `sway version 1.6-5cdce42d`

- **Debug Log:**
  - [swayvulkan.log](https://github.com/swaywm/sway/files/6711603/swayvulkan.log)

- **Configuration File:**
  - https://github.com/shoober420/rootscripts/blob/main/home/shoober420/.config/sway/config

- **Description:**
  - To test out Vulkan, I used Left 4 Dead 2 with the "-vulkan" launch parameter. I keep black screening and/or have very odd graphical corruption when trying to launch vulkan games. This included Proton with DXVK. All OpenGL games run fine on my system.
 
![9D385E30-27C6-41C9-97F3-A30C3CBC0E9F](https://user-images.githubusercontent.com/5150898/123319796-e729f380-d4fe-11eb-856a-f607a326a6db.jpeg)

**Comment by emersion** [comment]
Sounds like a driver issue. Can you reproduce with another Wayland compositor like Weston?

**Comment by shoober420** [comment]
You’re right, it was mesa being compiled with the “-flto=auto” flag, which was black screening and/or doing that thing. I made a issue on the mesa gitlab about it.

https://gitlab.freedesktop.org/mesa/mesa/-/issues/5017
