### ISSUE TITLE
Doesn't appear on GDM3

### ISSUE THREAD

**Issue by Blackrucat** [swaywm/sway#6344]
- **Sway Version:**
  - `1.5`

- **Description:**
  - STEP 1: Install Sway througt apt on Pop!_OS!, 
  - STEP 2: At GDM3 perceive that SWAY don't appear at the WM selector menu,
  - STEP 3: Cry, because I really wanted to use it.

**Comment by emersion** [comment]
Sorry, display managers like GDM aren't officially supported, because they are pretty flaky in general.

Maybe try running `sway` directly from a TTY?

**Comment by Blackrucat** [comment]
For some reason it appeared, but has an error that I can't click in anything, I will check it later and give more details to you.
