### ISSUE TITLE
Glitches on start

### ISSUE THREAD

**Issue by rustzz** [swaywm/sway#6346]
- **Sway Version: 1.6**

- **Debug Log:**
  - https://pastebin.com/mKCMuUFX

- **Configuration File:**
  - https://pastebin.com/FSSgWtbx

- **Description:**
  - Launching Sway
  - I see glitches
  - Switch to another TTY and back
  - If you repeat step 3, then again there will be glitches and they can be eliminated only by restarting Sway

![image](https://user-images.githubusercontent.com/74064444/123443840-b2499980-d5ef-11eb-8b64-07506e89a47e.png)

**Comment by RPigott** [comment]
Have you tried with WLR_DRM_NO_MODIFIERS=1? https://github.com/swaywm/sway/wiki#sway-16-shows-garbage-or-a-blank-screen-on-nouveau

**Comment by rustzz** [comment]
Works! Thx
