### ISSUE TITLE
Sway crashes 

### ISSUE THREAD

**Issue by sukhmancs** [swaywm/sway#6347]
### Sway info: 
- **Sway Version:**
   - sway version = 1.6
- **Config file**
  - http://ix.io/3r7R or public GitHub gist: https://gist.github.com/Sukhman723/0d7f8f4850c73e8c582335e236d096ad
- **Debug Logs**
  - https://gist.github.com/Sukhman723/b674c98dfe1933f857c8ebf4f6fe9487
- **Stack Trace**    
  - https://gist.github.com/Sukhman723/9c372cf7fc855653159ecff9ee612d0c

 **Description:**
  - I was running MakeHuman (modeling software) when this crash happened. 
 
 **Solutions _(I tried)_**
  - I already tried compiling it through Archlinux AUR repository. (Do I need to compile it directly)
  - I can run MakeHuman (modeling software) if I switch from Wayland to x server. It means MakeHuman works with no any error in i3.

**Comment by Xyene** [comment]
Your stack trace is missing debug symbols. You can get symbols by compiling from source, reproducing the crash and then running `coredumpctl gdb` and then `bt full`.

Here are some instructions to compile from source: https://github.com/swaywm/sway/wiki/Development-Setup#compiling-as-a-subproject

**Comment by Sukhman723** [comment]
> Your stack trace is missing debug symbols. You can get symbols by compiling from source, reproducing the crash and then running `coredumpctl gdb` and then `bt full`.
> 
> Here are some instructions to compile from source: https://github.com/swaywm/sway/wiki/Development-Setup#compiling-as-a-subproject

I already complied it through the source. I'm using Archlinux so it is damn easy to compile it through their AUR repository.

**Comment by emersion** [comment]
That stack trace doesn't come from a Sway binary compiled from source.

**Comment by fluix-dev** [comment]
The stack trace may be from source, it just still has it's debug symbols stripped. Either patch the PKGBUILD appropriately (I think you add `!strip` in `options`) or just clone the git repo and build it yourself.

**Comment by FreeFull** [comment]
The PKGBUILD already has `options=(debug)`, so it should be making a sway-git-debug package alongside sway-git. The -debug package contains the symbols. (Make sure to install the one for wlroots too).

**Comment by Sukhman723** [comment]
I even tried adding !strip in 'options' but still it crashes. 
Error: Unable to receive IPC header

**Comment by fluix-dev** [comment]
That isn't meant to stop crashing, it's just meant to have debug symbols in your coredump. Right now, your dump has `n/a` for the sway addresses which we don't want. Please compile sway + wlroots from source.
