### ISSUE TITLE
for_window doesn't parse pipes

### ISSUE THREAD

**Issue by sjug** [swaywm/sway#635]
When I pipe together several class names or window roles in the for_window config, like this:
`for_window [class="mpv|Galculator|Gimp|Gajim|Pidgin"] floating enable`

It doesn't work as expected, doesn't match all the class names.
If we just have one per line then it works as expected, but that's not really viable.

**Comment by SirCmpwn** [comment]
I'm closing issues that are resolved by the yet-unreleased sway 1.0.
