### ISSUE TITLE
Pasting misbehave and drag&drop fail in Firefox in multiseat mode

### ISSUE THREAD

**Issue by inwwin** [swaywm/sway#6356]
### Steps to reproduce
1. Plug in two sets of keyboard and mouse
2. Attach the second set of keyboard and mouse to a new seat (e.g. `seat1`) in the configuration file
3. Restart sway
4. Start Firefox
5. Using `seat0`, try dragging and dropping e.g. try rearranging the tabs
6. Using `seat0`, try pasting something with Ctrl-V, middle-click or right-click and select Paste
### Observed behaviours
- In `seat0`, drag and drop does not work or it sometimes crash firefox.
- In `seat1`, drag and drop works normally.
- In `seat0`, when pasting, the clipboard from `seat1` is pasted instead
- In `seat1`, when pasting, the clipboard from `seat1` is pasted correctly
- However, these still work correctly in other applications, e.g., gedit and alacritty
### Affected versions
Firefox 89.0.2
Sway 1.6

**Comment by fluix-dev** [comment]
> However, these still work in other applications, e.g., gedit and alacritty

This sounds like a Firefox bug, but in the case it's not, please provide Sway logs (`sway -d`) and likely client logs (`WAYLAND_DEBUG=1 firefox`).

**Comment by inwwin** [comment]
### Logs for the clipboard bug
I use the default config file with the following added
```
seat seat1 attach 9390:6163:RAPOO_Rapoo_2.4G_Wireless_Device
seat seat1 attach 9390:6163:RAPOO_Rapoo_2.4G_Wireless_Device_Consumer_Control
seat seat1 attach 9390:6163:RAPOO_Rapoo_2.4G_Wireless_Device_Mouse
```
From the tty I launched sway,
Then I launched alacritty, and execute the following:
```
wl-copy -s seat0 's0m';
wl-copy -s seat1 's1m';
wl-copy -p -s seat0 's0p';
wl-copy -p -s seat1 's1p';
WAYLAND_DEBUG=1 firefox https://gist.github.com/ &> ~/firefox_wayland.log;
```
Then I tried pasting a couple times using either keyboards and either mice, both with the main and the primary clipboard. Only either 's1m' or 's1p' appear.
The log of firefox and sway can be found here: https://gist.github.com/inwwin/26e628b1f7f8da93c2de44f8e9028d9c

**Comment by inwwin** [comment]
After I've been using Firefox in multiseat mode for a while, I've discovered myriad of weird behaviours, and so, I think the problem here is that the input model of Firefox always assume single seat mode, and never make any accomodation for multiseat users. Hence, I am closing down this issue.
