### ISSUE TITLE
No display on Sway after switching TTY

### ISSUE THREAD

**Issue by Roboron3042** [swaywm/sway#6364]
### Please fill out the following:
- **Sway Version:** 1.6.1
- **Debug Log:** https://gist.github.com/Roboron3042/1afe423335e4b7dd5c5a17476e3934c9
- Using default config file
- **Description:**
  - After a recent update, Sway doesn't send any display signal if I switch TTY's. To reproduce:
  1. My system starts SDDM at TTY1.
  2. I switch to TTY2 and open sway (everything works).
  3. I switch back to TTY1 (SDDM).
  4. I switch again to TTY2. This time Sway doesn't show, instead my monitor says "no signal".

Sway doesn't crash though. I have to manually kill it (I did this on the attached log).
System: Arch Linux / AMD 5500 XT graphics

**Comment by emersion** [comment]
```
00:00:06.574 [DEBUG] [wlr] [render/gbm_allocator.c:128] Allocated 1920x1080 GBM buffer (format 0x34325241, modifier 0xFFFFFFFFFFFFFF)
00:00:06.574 [DEBUG] [wlr] [render/gles2/renderer.c:137] Created GL FBO for buffer 1920x1080
00:00:06.574 [ERROR] [wlr] [backend/drm/atomic.c:143] Failed to acquire FB
00:00:06.574 [ERROR] [wlr] [backend/drm/atomic.c:165] Failed to set plane 82 properties
00:00:06.574 [ERROR] [wlr] [backend/drm/drm.c:723] connector HDMI-A-1: Failed to initialize renderer: initial page-flip failed
```

**Comment by Roboron3042** [comment]
A recent MESA update fixed this, so it was not a sway issue. Sorry for taking your time. Closing.

**Comment by emersion** [comment]
Thanks for the update.
