### ISSUE TITLE
AMD GPU: corrupted image while using wayland + vulkan applications

### ISSUE THREAD

**Issue by alandiwix** [swaywm/sway#6366]
- **Sway Version:**
1.6.1-7571507451 (Jun 26 2021, branch 'master')

- **Debug Log:**
will be here shortly

- **Configuration File:**
reproducable on default

- **Description:**
That's a really longstanding bug, previously XWayland was also affected, but in this case it resolved some time ago.
Here is what I'm getting with:
- window above - every X11 app or wayland with opengl
- window below - every wayland app using vulkan

https://ibb.co/JR9TsSV

I've tried the same with KDE wayland session - it works nicely, so that's probably not upstream mesa bug.

**Comment by emersion** [comment]
Sounds like a driver bug. Bad buffer tiling.

**Comment by emersion** [comment]
Can you try with Weston?

**Comment by alandiwix** [comment]
@emersion would you kindly provide hint or instructions how to reproduce this on wayland correctly?

**Comment by emersion** [comment]
1. Run `weston`, either in a TTY or in an already-running Wayland or X11 session
2. Start a terminal inside Weston
3. Run Vulkan app

**Comment by alandiwix** [comment]
@emersion 
Thanks. I was able to reproduce this on weston with wayland backend, started in sway session. Not sure what does rendering in this case, isn't it still sway/wlroots?
As for "bare TTY": weston doesn't start from TTY for some reason. No error produced and I can switch TTYs, but the TTY where weston runs just hangs, weston shell doesn't appear.

**Comment by emersion** [comment]
OK. Then this really sounds like a driver bug. Please search/open a new issue on their bug tracker: https://gitlab.freedesktop.org/drm/amd/-/issues
