### ISSUE TITLE
System Freezes - Sway 1.6.1 - wlroots 0.14.0

### ISSUE THREAD

**Issue by mcarni** [swaywm/sway#6371]
after the recent upgrades, system keeps freezing and becomes unresponsive

as per title:
Sway 1.6.1 - wlroots 0.14.0 - mesa 21.1.3-1
nouveau - NVIDIA g98 (GeForce 8400)

(https://pastebin.com/buyGGpc8)

(https://pastebin.com/pfmCUHXN)

**Comment by emersion** [comment]
Fixed in wlroots master.
