### ISSUE TITLE
i3ipc Floating Properties not Present

### ISSUE THREAD

**Issue by calebstewart** [swaywm/sway#6390]
# Description
I'm attempting to make some modifications to the builtin `inactive-windows-transparency.py` script in order to ignore floating windows (I only use them for dialogs, and they generally have different/separate transparency settings). The `i3ipc` Python module documentation states that there is a `floating` property and a `is_floating()` method for returned window objects, but they aren't present when I run a Python script within Sway. Relevant docs are [here](https://i3ipc-python.readthedocs.io/en/latest/con.html#i3ipc.Con.is_floating).

## Sway Version
```
$ sway --version
sway version 1.6
```
## i3ipc version
```
$ pip freeze | grep "i3ipc"
i3ipc==2.2.1
```
## Reproduction Script 
The following script shows that no returned windows have a `is_floating()` method. A similar test can be done with the `floating` property with similar results.

```py
#!/usr/bin/env python3
import i3ipc

ipc = i3ipc.Connection()

for window in ipc.get_tree():
    try:
        print(f"window {window.id} {'is' if window.is_floating() else 'is not'} floating")
    except AttributeError as exc:
        print(f"window {window.id} has no is_floating method")
```
# Caveat
If this isn't an issue with Sway, I'm happy to open an issue with `i3ipc` directly, but I don't have an `i3` installation to test with, so thought I'd ask here to see if someone more familiar with the compatibility layer can point out the problem or verify that it's **not** a problem with the i3-sway compatibility. Thanks!

**Comment by fluix-dev** [comment]
I don't think this is a Sway bug. The commit (https://github.com/altdesktop/i3ipc-python/commit/abd242b7f2eba7323fa4345ff9a3b9e0bd426b3d) which adds `is_floating` was made in October of 2020 while the [latest release](https://github.com/altdesktop/i3ipc-python/releases) was in April of 2020. It's been over a year so perhaps ask for a new release or use `floating` directly (not really sure how).

**Comment by calebstewart** [comment]
Thanks for the response! I'll look into that. I missed the release timeframe, and trusted the documentation (silly me :wink:). Interestingly, I'm seeing `None` for the `floating` property and `False` for `is_floating()` for all Windows regardless, while the `type` property is `floating_con` for floating windows and `con` for regular windows.

This is likely a problem in `i3ipc` as you said, though, since I'm on an unreleased version, so I'll direct my questions there. Again, thanks for getting back to me! :+1:
