### ISSUE TITLE
Sway complains about not being able to connect to /run/seatd.sock because the file doesn't exist

### ISSUE THREAD

**Issue by PopeRigby** [swaywm/sway#6393]
### Please fill out the following:
- **Sway Version:** 1.6.1

- **Debug Log:**
https://gist.github.com/PopeRigby/aaa7de4ba3f4691e01de82b044651b0b

- **Configuration File:**
Default configuration

- **Description:**
When launching Sway from tty1, I noticed that it displays this error message before it boots:
```
[ERROR] [wlr] [libseat] [libseat/backend/seatd.c:78] Could not connect to socket /run/seatd.sock: No such file or directory
```
Nothing seems to be broken, but there are a few other possibly unrelated errors in the log file.

**Comment by fluix-dev** [comment]
On its own, this is merely an optional feature that doesn't get enabled. See [here](https://github.com/swaywm/sway/issues/6179#issuecomment-819526095) onwards and the line in your debug log just after the error:

> 00:00:00.002 [INFO] [wlr] [libseat] [libseat/libseat.c:70] Backend 'seatd' failed to open seat, skipping

**Comment by emersion** [comment]
Indeed, not a bug.

**Comment by PopeRigby** [comment]
Got it. If I understand correctly, that message is being downgraded to warning/info? If so, that's a good idea.

**Comment by emersion** [comment]
Yeah, next version of libseat should have the downgraded log message.
