### ISSUE TITLE
With a multiple monitor setup touch screen and stylus input seems to be controlling the wrong screen

### ISSUE THREAD

**Issue by henrytseng** [swaywm/sway#6397]
### Please read the following before submitting:
It appears that with multiple monitors (HIDPI) and touch screen, or stylus, input seems to be controlling the wrong screen.  

Setup exists on a laptop with a HIDPI screen scaled 2x and is offset to a position below the external monitor.  

### Please fill out the following:
- **Sway Version:**
`sway version 1.6.1`

- **Debug Log:**
  - Run `sway -d 2> ~/sway.log` from a TTY and upload it to a pastebin, such as gist.github.com.
  - This will record information about sway's activity. Please try to keep the reproduction as brief as possible and exit sway.

- **Configuration File:**

Sway config:
```
output eDP-1 resolution 3840x2400 position 640,1440
output DP-3 resolution 2560x1440 position 0,0

input "1739:52602:DLL08B0:01_06CB:CD7A_Touchpad" {
        pointer_accel .3
        dwt enabled
        tap disabled
        natural_scroll enabled
        middle_emulation enabled
    }
```

Setup `swaymsg -t get_outputs`:
```
Output eDP-1 'Sharp Corporation 0x14A8 0x00000000'
  Current mode: 3840x2400 @ 59.994 Hz
  Position: 640,1440
  Scale factor: 2.000000
  Scale filter: nearest
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 3
  Max render time: off
  Adaptive sync: disabled
  Available modes:
    3840x2400 @ 47.995 Hz
    3840x2400 @ 59.994 Hz

Output DP-3 'Dell Inc. DELL U2715H H7YCC75L09WS' (focused)
  Current mode: 2560x1440 @ 59.951 Hz
  Position: 0,0
  Scale factor: 1.000000
  Scale filter: nearest
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 2
  Max render time: off
  Adaptive sync: disabled
  Available modes:
    ...
    2560x1440 @ 59.951 Hz
```

- **Stack Trace:**
Does not crash

- **Description:**
While unplugged input correctly corresponds with correct output display, but when plugged in display outputs do not seem to be respecting scaling and positional offsets.  

Let me know if there's anything else I can provide.

**Comment by henrytseng** [comment]
My mistake didn't see the `map_to_output` config.  Closing

**Comment by emersion** [comment]
You'll need to map the input device to the output device. See `map_to_output`.

We do it automatically in some cases, but you forgot to attach a debug log, so can't say if we can improve our logic.
