### ISSUE TITLE
Sway identifies devices as a keyboard

### ISSUE THREAD

**Issue by flopun** [swaywm/sway#6400]
When I run <swaymsg -t get_inputs> sway identifies multiple devices such as camera, power button and video bus as a keyboard. For example:
Input device: Power Button
  Type: Keyboard
  Identifier: 0:1:Power_Button
  Product ID: 1
  Vendor ID: 0
  Active Keyboard Layout: English (US)
  Libinput Send Events: enabled

Input device: Video Bus
  Type: Keyboard
  Identifier: 0:6:Video_Bus
  Product ID: 6
  Vendor ID: 0
  Active Keyboard Layout: English (US)
  Libinput Send Events: enabled

I run sway 1.6.1.
Debug log: https://gist.github.com/flopun/6211b8060ec0e4e165cbf5ab24d26e99

**Comment by fluix-dev** [comment]
Not sure about the others, but I think the power button being detected as a "Keyboard" type is correct. It's a button after all.

**Comment by emersion** [comment]
Yeah, libinput does that, thèse devices have buttons.
