### ISSUE TITLE
Sway crashes on start with nouveau

### ISSUE THREAD

**Issue by atl-mk** [swaywm/sway#6401]
- **Sway Version:**
  - sway version 1.6.1

- **Debug Log:**
  - [https://gist.github.com/atl-mk/16ebdc8dcc53231d3e176a5bf07c7700#file-sway-log](https://gist.github.com/atl-mk/16ebdc8dcc53231d3e176a5bf07c7700#file-sway-log)

- **Configuration File:**
  - used default config

- **Stack Trace:**
  - [https://gist.github.com/atl-mk/16ebdc8dcc53231d3e176a5bf07c7700#file-stacktrace](https://gist.github.com/atl-mk/16ebdc8dcc53231d3e176a5bf07c7700#file-stacktrace)

- **Description:**
  - Sway will start momentarily, the grey background and cursor is visible, and then crashes (also exits) almost immediately
  - Using nouveau (checked with lspci) with a geforce 30XX series as the only GPU and kernel version 5.13.4
  - Tried (with no success)
    - WLR_DRM_NO_MODIFIERS
    - WLR_DRM_DEVICES

**Comment by emersion** [comment]
Fixed in master. Note, nouveau doesn't support OpenGL on your card.

**Comment by atl-mk** [comment]
Thanks! Can confirm it works if built from commit e7f4e50d
