### ISSUE TITLE
can't run sway after upgrade to 1.6.1

### ISSUE THREAD

**Issue by fedya** [swaywm/sway#6402]
### Please fill out the following:
- sway-1.6.1-1.x86_64

- **Debug Log:**
```
00:00:00.001 [ERROR] [wlr] [libseat] [libseat/backend/seatd.c:78] Could not connect to socket /run/seatd.sock: No such file or directory
00:00:00.001 [ERROR] [wlr] [libseat] [libseat/libseat.c:73] No backend was able to open a seat
00:00:00.001 [ERROR] [wlr] [backend/session/session.c:84] Unable to create seat: Function not implemented
00:00:00.001 [ERROR] [wlr] [backend/session/session.c:218] Failed to load session backend
00:00:00.001 [ERROR] [wlr] [backend/backend.c:353] Failed to start a DRM session
00:00:00.001 [ERROR] [sway/server.c:53] Unable to create backend
```

```
00:00:00.000 [INFO] [sway/main.c:347] Sway version 1.6.1
00:00:00.000 [INFO] [sway/main.c:348] wlroots version 0.14.0
00:00:00.001 [INFO] [sway/main.c:155] Linux bongie 5.13.4-desktop-clang-1omv4050 #1 SMP PREEMPT Thu Jul 22 13:41:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
00:00:00.001 [INFO] [sway/main.c:171] Contents of /etc/lsb-release:
00:00:00.001 [INFO] [sway/main.c:155] LSB_VERSION=
00:00:00.001 [INFO] [sway/main.c:155] DISTRIB_ID=OpenMandrivaLinux
00:00:00.001 [INFO] [sway/main.c:155] DISTRIB_RELEASE=4.50
00:00:00.001 [INFO] [sway/main.c:155] DISTRIB_CODENAME=Nickel
00:00:00.001 [INFO] [sway/main.c:155] DISTRIB_DESCRIPTION="OpenMandriva Lx 4.50"
00:00:00.001 [INFO] [sway/main.c:171] Contents of /etc/os-release:
00:00:00.001 [INFO] [sway/main.c:155] NAME="OpenMandriva Lx"
00:00:00.001 [INFO] [sway/main.c:155] VERSION="4.50 (Nickel) Cooker"
00:00:00.001 [INFO] [sway/main.c:155] ID="openmandriva"
00:00:00.001 [INFO] [sway/main.c:155] VERSION_ID="4.50"
00:00:00.001 [INFO] [sway/main.c:155] PRETTY_NAME="OpenMandriva Lx 4.50 (Nickel) Cooker"
00:00:00.001 [INFO] [sway/main.c:155] BUILD_ID="20210506.16"
00:00:00.001 [INFO] [sway/main.c:155] VERSION_CODENAME="nickel"
00:00:00.001 [INFO] [sway/main.c:155] ANSI_COLOR="1;43"
00:00:00.001 [INFO] [sway/main.c:155] LOGO="openmandriva"
00:00:00.001 [INFO] [sway/main.c:155] CPE_NAME="cpe:/o:openmandriva:openmandriva_lx:4.50"
00:00:00.001 [INFO] [sway/main.c:155] HOME_URL="http://openmandriva.org/"
00:00:00.001 [INFO] [sway/main.c:155] BUG_REPORT_URL="http://issues.openmandriva.org/"
00:00:00.001 [INFO] [sway/main.c:155] SUPPORT_URL="https://forum.openmandriva.org"
00:00:00.001 [INFO] [sway/main.c:155] PRIVACY_POLICY_URL="https://www.openmandriva.org/tos"
00:00:00.001 [INFO] [sway/main.c:171] Contents of /etc/redhat-release:
00:00:00.001 [INFO] [sway/main.c:155] OpenMandriva Lx release 4.50 (Nickel) Cooker for x86_64
00:00:00.001 [INFO] [sway/main.c:143] LD_LIBRARY_PATH=
00:00:00.001 [INFO] [sway/main.c:143] LD_PRELOAD=
00:00:00.001 [INFO] [sway/main.c:143] PATH=/bin:/usr/local/bin:/usr/bin:/usr/local/games:/usr/games:/usr/lib/jvm/java-15-openjdk/bin:/home/fdrt/.local/bin:/home/fdrt/bin
00:00:00.001 [INFO] [sway/main.c:143] SWAYSOCK=
00:00:00.001 [DEBUG] [sway/server.c:47] Preparing Wayland server initialization
00:00:00.001 [ERROR] [wlr] [libseat] [libseat/backend/seatd.c:78] Could not connect to socket /run/seatd.sock: No such file or directory
00:00:00.001 [INFO] [wlr] [libseat] [libseat/libseat.c:70] Backend 'seatd' failed to open seat, skipping
00:00:00.001 [ERROR] [wlr] [libseat] [libseat/libseat.c:73] No backend was able to open a seat
00:00:00.001 [ERROR] [wlr] [backend/session/session.c:84] Unable to create seat: Function not implemented
00:00:00.001 [ERROR] [wlr] [backend/session/session.c:218] Failed to load session backend
00:00:00.001 [ERROR] [wlr] [backend/backend.c:353] Failed to start a DRM session
00:00:00.001 [ERROR] [sway/server.c:53] Unable to create backend
```

- **Description:**
  - i'm not changing my sway config for years and have no clue what's wrong now

**Comment by emersion** [comment]
Your bug report is missing debug logs. Please add a link to the full debug log file.

**Comment by fedya** [comment]
> Your bug report is missing debug logs. Please add a link to the full debug log file.

i updated my report

**Comment by emersion** [comment]
Are you using systemd? libseat doesn't seem like it's been built with logind support.

**Comment by fedya** [comment]
@emersion yes i'm systemd user

meson build log for seatd

```
un-time dependency libelogind found: NO (tried pkgconfig and cmake)
Run-time dependency libsystemd found: YES 249
Found pkg-config: /usr/bin/pkg-config (1.7.4)
Build-time dependency scdoc found: YES 1.11.1
Program sh found: YES (/bin/sh)
Program /usr/bin/scdoc found: YES (/usr/bin/scdoc)
Build targets in project: 8

seatd 0.5.0

    seatd  : YES
    builtin: NO
    systemd: YES
    elogind: NO
```

**Comment by emersion** [comment]
Are you sure Sway is using this particular seatd build?

**Comment by fedya** [comment]
yes, i'm sure
```
seatd-0.5.0-1.x86_64
lib64seat1-0.5.0-1.x86_64
```

**Comment by emersion** [comment]
Well, for some reason libseat doesn't try logind.

**Comment by kennylevinsen** [comment]
There are 3 scenarios where libseat will not try logind:
1. seatd succeeds, so it never tries any other backends.
2. another backend is forced with `LIBSEAT_BACKEND` . This will either print "No backend matched name ..." or "Backend ... failed to open seat" if it fails. Note: It does not print "Skipping", or "No backend was able to open a seat", as only a single backend is tried in this mode.
3. libseat is not compiled with logind support. This will print "Backend ... failed to open seat, skipping" for every other backend, and never mention logind, followed by "No backend able to open a seat".

Your log clearly doesn't match 1 or 2, and matches 3 perfectly. I'd double-check that `ldd` reports a path to the libseat you build and installed.

For a standalone test, you can build libseat with examples enabled (`-Dexamples=enabled`), and then run `./build/simpletest /dev/dri/card0`. If that fails without printing logind, then logind is not compiled in. If that succeeds, then logind is compiled into this libseat.so, but your sway instance is likely using a different libseat.so, possibly an old install.

**Comment by fedya** [comment]
I found what's wrong, seatd wasn't built with pkgconfig(libsystemd)

**Comment by archieve-cn** [comment]
> 

I find the same issue. the libseat_backend has skipping due of  backend seatd failed to open seat permission denied.
And it's happen when I open the Hyprland.
As I learnd, the libseat has not a logind. If I missing some steps for config seat?
I try add the user to seat group, but I can't find the seat when use `groups`.

**Comment by kennylevinsen** [comment]
> And it's happen when I open the Hyprland.

This is the sway issue tracker, not libseat or Hyprland.

> I find the same issue. the libseat_backend has skipping due of backend seatd failed to open seat permission denied.

libseat tries its backends in order, and will pick the first one that succeeds (printing each attempt). If you want to use logind, but libseat states "No backend was able to open a seat" without ever trying logind, then you need to ensure that your libseat was built with logind support. Official distro packages for systemd-based distributions will usually be built correctly.

If you instead want to use seatd, ensure that it was started by your service manager as root and that your user is in the appropriate group before you start sway.
