### ISSUE TITLE
Sway 1.6.1 screws up compositing & using the default config just freezes sway entirely

### ISSUE THREAD

**Issue by 0ae** [swaywm/sway#6404]
- **Sway Version:**
  - `1.6.1`

- **Debug Log:**
Full debug log (my config) : https://gist.github.com/0ae/c63089ef3bcd48047f0bb9062dddc703
Full debug log with the default config: https://gist.github.com/0ae/16fac3360c74adfa3c9ddb9b35e6c023

- **Configuration File:**
https://gist.github.com/0ae/f40f102c616155ec653ca2702146c8ab

- **Description:**

I'm using nouveau.

Whenever I start up sway 1.6.1 with my config, it works fine at first but after around 30~ seconds  the compositing screws around i.e. my cursor entirely disappears from my 2nd monitor, a big (~40% size of my monitor) pops up, disappears and pops up again on my monitor (in a loop unless I end the sway session via another tty).

With the default config, I simply just open up sway , move my mouse around a bit and then it just freezes.

**Comment by emersion** [comment]
You're using wlroots version 0.14.0. Please upgrade to 0.14.1.
