### ISSUE TITLE
SDL_WINDOW_BORDERLESS doesn't work on wayland sway, but works on xwayland sway

### ISSUE THREAD

**Issue by 1ace** [swaywm/sway#6414]
**Sway Version:** 1.6.1
**Debug Log:** https://gist.github.com/1ace/59d502f9c82ba2f2123f34752a04c48e#file-sway-log
**Configuration File:** https://gist.github.com/1ace/59d502f9c82ba2f2123f34752a04c48e#file-sway-config
**Description:**

As the title says, SDL's `SDL_WINDOW_BORDERLESS` only works when talking to sway through xwayland, but not when talking directly wayland to sway.

Expected behaviour: the window decorations are not shown
Actual behaviour on wayland sway: the window decorations are shown regardless of the flag (incorrect)
Actual behaviour on xwayland sway: the window decorations are not shown (correct)

Everything needed to reproduce the issue is in this gist: https://gist.github.com/1ace/59d502f9c82ba2f2123f34752a04c48e
In `run.sh`, replace `SDL_VIDEODRIVER=wayland` with `SDL_VIDEODRIVER=x11` to reproduce the xwayland behaviour.

**Comment by emersion** [comment]
Do you have a `WAYLAND_DEBUG=1` log?

Might be xdg-decoration related.

**Comment by 1ace** [comment]
same log with `WAYLAND_DEBUG=1`: https://gist.github.com/1ace/cbe3b6db6d9aa5155fddcc3e0013cc8d

**Comment by emersion** [comment]
Ah, sorry, I forgot to mention: can you collect a `WAYLAND_DEBUG=1` log of the client? That is, set it then run the client, redirecting its output to a file?

**Comment by 1ace** [comment]
sorry, I should've known that :sweat_smile:
app's wayland log: https://gist.github.com/1ace/870f5a58f39687654c62479802295d30

**Comment by FreeFull** [comment]
Looking at SDL's source, it seems like that if SDL_WINDOW_BORDERLESS is specified, it tells the compositor to use server-side decorations, and otherwise to use client-side decorations? I don't see any code that would actually result in there not being any borders at all.

**Comment by 1ace** [comment]
It's the other way around: with `BORDERLESS` it requests CSD, otherwise SSD ([`src/video/wayland/SDL_waylandwindow.c:991`](https://github.com/libsdl-org/SDL/blob/d4e1b4974ac8711cc89bd187c9f412f84771372b/src/video/wayland/SDL_waylandwindow.c#L991)) and I haven't looked at that code but presumably the CSD is "nothing" which why it ends up borderless.

And yeah, [`libdecor`](https://gitlab.gnome.org/jadahl/libdecor) is not very popular yet, but hopefully it will catch on :)
I know that at least electron is going to be relying on it in the next release to work around Gnome's refusal to support SSD.

In any case, I'm not using the `libdecor` code path, so you can ignore that for this issue :slightly_smiling_face:

**Comment by FreeFull** [comment]
Ah, study, I had a brainfart and didn't realize `bordered = !borderless`
