### ISSUE TITLE
Allow following GTK theme colors

### ISSUE THREAD

**Issue by flipflop133** [swaywm/sway#6417]
The possibility to follow the current GTK theme seems currently missing and would be a proper way of theming sway. Furthermore, it would allow easy light mode/dark mode switching.
For example, colors definition would look like this:
`set $black @theme_fg_color`
Another way would be to directly allow using GTK tags like so:
```
# class                border          backgr.         text            indicator       child_border
client.focused         @theme_fg_color @theme_fg_color @theme_fg_color @theme_fg_color @theme_fg_color

```
For example, Waybar implemented [this](https://github.com/Alexays/Waybar/wiki/Styling#making-waybar-follow-the-gtk-theme) properly.

**Comment by emersion** [comment]
Nack, we won't be using GTK for theming. You can instead write a script that parses the GTK theme and applies it via the Swau IPC.

**Comment by flipflop133** [comment]
Thanks for the explanations!

**Comment by flipflop133** [comment]
I looked for a way to parse the GTK theme colors but without success, you seem to have a better understanding of this, would you mind provide some links for reference?
