### ISSUE TITLE
Headless + software rendering: Assertion `wlr_texture_is_gles2(wlr_texture)' failed

### ISSUE THREAD

**Issue by ownaginatious** [swaywm/sway#6419]
- **Sway Version:** 1.6.1
- **Debug Log:** https://gist.github.com/ownaginatious/78cb6e38c13ce6b0d0d26db9e456d1e4
- **Configuration File:** Used the default.
- **Stack Trace:**
   Sorry for the screenshot; I'm doing this all through VNC and can't easily copy-paste.

   <img width="558" alt="image" src="https://user-images.githubusercontent.com/1163192/127962826-6e9589e5-9839-4bd8-b7c9-45208ccccee4.png">

- **Description:** So I'm currently trying to run `sway` headless completely within a FreeBSD bhyve VM running Arch Linux. This VM has absolutely no GPU support, so I'm trying to run this entirely in software with the following:

```bash
WLR_BACKENDS=headless \
WLR_RENDERER=pixman \
WLR_LIBINPUT_NO_DEVICES=1 \
WAYLAND_DISPLAY=wayland-1 \
XDG_RUNTIME_DIR=/tmp \
XDG_SESSION_TYPE=wayland \
WLR_RENDERER_ALLOW_SOFTWARE=1 \
    sway -d -V
```

I cobbled those environment variables together through various threads on the internet, so not entirely sure it's all necessary or makes sense.

Any help is greatly appreciated!

**Comment by emersion** [comment]
This has been fixed in master, but hasn't been released yet.

**Comment by jbeich** [comment]
Also [fixed](https://github.com/swaywm/sway/commit/6cad038eea48) in `v1.6` branch or [future 1.6.2](https://github.com/swaywm/sway/milestone/9).
