### ISSUE TITLE
Sway freezes on background change

### ISSUE THREAD

**Issue by ghost** [swaywm/sway#642]
On changing a background via `swaymsg output <OUTPUT> bg <FILE> <MODE>`, sway hangs while it loads the image from disk.

While this is low priority, it would be nice to have it load in a separate thread, or using non-blocking IO, as to allow uninterrupted use of background rotators.

Note that I think this might only happen when a bar {} is used.

**Comment by SirCmpwn** [comment]
I'm closing issues that are resolved by the yet-unreleased sway 1.0.
