### ISSUE TITLE
config: Segmentation fault from use of undefined variable

### ISSUE THREAD

**Issue by frogtile** [swaywm/sway#6424]
- **Sway Version:**
1.5.1

- **Debug Log:**
https://termbin.com/oe1o

- **Configuration File:**
https://termbin.com/qt1u

- **Stack Trace:**
running `coredumpctl gdb sway` gives 
<details>
<summary>coredumpctl gdb sway</summary>
<pre>
           PID: 19320 (sway)
           UID: 1000 (tile)
           GID: 1000 (tile)
        Signal: 11 (SEGV)
     Timestamp: Sat 2021-08-07 09:15:06 +06 (16min ago)
  Command Line: sway -d
    Executable: /usr/bin/sway
 Control Group: /user.slice/user-1000.slice/session-8.scope
          Unit: session-8.scope
         Slice: user-1000.slice
       Session: 8
     Owner UID: 1000 (tile)
       Boot ID: 3b7b1afb384749cd983a5012222df993
    Machine ID: 0a56b79174f747d5a4072d0d914e27c3
      Hostname: fedora
       Storage: none
       Message: Process 19320 (sway) of user 1000 dumped core.

Coredump entry has no core attached (neither internally in the journal nor externally on disk).
</pre>
</details>

- **Description:**
- use an undefined variable in the `colors` subsection of `bar` section of sway's config file
```
bar {
	status_command statuscmd
	position top

	colors {
		background $bar_background
        }
}
```
here `$bar_background` is not defined.
- run `sway`

**Comment by frogtile** [comment]
Another event:

sway's default config file has
```
bindsym $mod+d exec $menu
```
if i change it to
```
bindsym $mod+d exec $menud
```
pressing `Mod+d` runs `$menu` (dmenu), but the program i select doesn't start. after quitting sway i saw an error message on console with
```
swaymsg: unrecognized option '--d'
```

**Comment by frogtile** [comment]
I am closing since it hasn't been looked at. I guess I will just not use undeclared variables.

(also not just copy others config into mine)

**Comment by ammgws** [comment]
It's a bit premature to close it. If you have the ability then take the time to submit a bugfix PR,  since the segfault is something that should eventually be addressed.
