### ISSUE TITLE
"Ultimaker Cura" menubar bugs out and scrolls left.

### ISSUE THREAD

**Issue by KoalaV2** [swaywm/sway#6434]
When trying to use the 3D printing software called "Cura" and trying to make a selection in the menubar above it just scrolls the selection far left making it impossible to make a selection. https://imgur.com/XdvesfC 

This happens on the latest master branch but also on the latest stable release on arch linux.

If any more details need to be provided I'm more then happy to include them.

**Comment by RPigott** [comment]
This looks to me like a client bug. A WAYLAND_DEBUG log would probably be the most useful in debugging this on the client end.

**Comment by KoalaV2** [comment]
> This looks to me like a client bug. A WAYLAND_DEBUG log would probably be the most useful in debugging this on the client end.

I wasn't able to get the whole log file since redirecting sdtout to a file didn't work properly but around the end of this paste should include the essential logs where i click on the menubar buttons. https://pastebin.com/8ns2yg4N

**Comment by RPigott** [comment]
> redirecting sdtout to a file didn't work properly

libwayland writes debug messages to stderr.

Anyway I recommend you report this to Cura, I don't think there is a sway bug here. We can reopen this if we find something that indicates otherwise.

**Comment by KoalaV2** [comment]
Does appear to be a wayland issue considering running `QT_QPA_PLATFORM=xcb cura` to force it to use xwayland works fine and everything works well in that case.

**Comment by torwag** [comment]
I can confirm that `QT_QPA_PLATFORM=xcb cura` "solves" the problem. Furthermore, for me it is not the very left, but centering. This differs among which monitor I use in my multi monitor setup. Seems monitors on the left side (pos 0,X) are unaffected, but anything with an X offset seems to have trouble.
