### ISSUE TITLE
Add Autoclose Xwayland Feature

### ISSUE THREAD

**Issue by JuanCldCmt** [swaywm/sway#6437]
- **Description:** Gnome 40 has a new experimental feature named autoclose-Xwayland, which automatically closes Xwayland when no X program is running, here's the [link](https://www.phoronix.com/scan.php?page=news_item&px=GNOME-40-XWayland-On-Demand). And I think it will be a great addition to sway.
- **Current status of Xwayland:** Currently, when you set xwayland=enable, sway will automatically load Xwayland when you open up an application requiring X, but if you close the X application, the Xwayland process hangs on even no software requiring X is running, which adds up memory usage and is completely useless.
- **The Enhancement:** when you set xwayland=enable, sway should lazily load Xwayland and close Xwayland if the last software requiring X has closed.

**Comment by Xyene** [comment]
Closing as a duplicate of https://github.com/swaywm/wlroots/issues/2356, which has a draft implementation in https://github.com/swaywm/wlroots/pull/2988.
