### ISSUE TITLE
Sway crashes on startup

### ISSUE THREAD

**Issue by pomonella01** [swaywm/sway#6441]
- **Sway Version:**
  1.6.1

- **Debug Log:**
 https://pastebin.com/p70vDh2b

- **Configuration File:**
Default configuration
- **Stack Trace:**
Couldn't obtain
- **Description:**
  Run sway.
  If ran through a dm, screen will be black for a minute and dm will relaunch.

**Comment by emersion** [comment]
```
00:00:00.002 [INFO] [wlr] [backend/x11/backend.c:396] Creating X11 backend
00:00:00.002 [INFO] [wlr] [backend/x11/backend.c:463] X11 does not support DRI3 extension
```

Seems like you're trying to start Sway like a X11 window manager. This won't work.

The crash is fixed in Sway master.
