### ISSUE TITLE
force option for sway output

### ISSUE THREAD

**Issue by unmellow** [swaywm/sway#6443]
- **Description:**
the ability to force the use of a resolution not officially supported by your monitor 

(on Xorg and Windows, I know my monitor supports  1080p at 75Hrz, but I can't set my screen to it under Wayland)

(so i can use wlr-randr for this)

**Comment by unmellow** [comment]
Closed this earlier when I realized I wasn't typing in the command correctly

reopening now that I realize I still can't set my display to unlisted resolutions

**Comment by emersion** [comment]
Use `--custom`.

**Comment by unmellow** [comment]
E.G.
Entering

Swaymag output HDMI-A-1 MODE --custom 1920x1080@75hz results in that resolution at 60hz

**Comment by unmellow** [comment]
so turns out what i encountered was a wdisplays bug it does not show you your actual refresh rate
