### ISSUE TITLE
Cannot switch to a workspace named with a japanese character

### ISSUE THREAD

**Issue by magnus-ISU** [swaywm/sway#6447]
- **Sway Version:**
sway version 1.6.1

  - Run `sway -d 2> ~/sway.log` from a TTY and upload it to a pastebin, such as gist.github.com.
This uses a different configuration file from the minimal one I paste below, but the problem is the same on both.
You want to search for the text `workspace number` or maybe just jump to line 990, see lines 320, 731, and 800 also. That seems to be the relevant sections.
https://gist.github.com/magnus-ISU/2f64adcd221c75f9a1ce986a48638e2f

- **Configuration File:**
https://gist.github.com/magnus-ISU/7aa0a18d3e45bb002b9ae34b9cb52363

- **Description:**
I intend to use japanese characters for my workspaces, as I like the mnemonic for putting the workspace keys onto alphabetic characters. I changed the config file to use them as workspace numbers, and now am unable to switch workspaces (except with the mouse, if I go to a workspace with an ascii number, while leaving behind a window on the japanese workspace). In addition (this happened with the minimal config too, and I never noticed it before trying this so I'm 99% sure it is related: the mod+Shift+e shortcut for `swaynag` would not do anything when I clicked `Yes, exit sway` with this configuration either.

The expected behaviour is that it shouldn't matter whether my workspace is called 1 or 一, as the documentation says

        # Note: workspaces can have any name you want, not just numbers.

The debug information indicates that the error is in `sway/commands.c: 257` or `sway/commands/bind.c: 617`, but I am not familiar enough with the sway codebase to understand exactly what is going wrong.

**Comment by magnus-ISU** [comment]
Humourously, while trying to comment out this issue, I didn't realize that `#` is still interpreted when assigning a workspace name.

The following line in the config file:

        bindsym $mod+i workspace number 1 # 一

works perfectly as expected. So whatever the issue is, it doesn't apply when there is a unicode in the name in general, only maybe when it starts the string or when there are no other characters in the workspace name or something.

**Comment by Xyene** [comment]
"number" in `workspace number`, refers to ASCII number (0-9, as per C's `isdigit`), not locale-specific number. It is a bug that `workspace number 一` doesn't raise an error at all during parsing (it does, in i3), not that it doesn't work.

If you wish to give your workspaces names, just drop the `number` from the command. These work fine:

```
bindsym $mod+i workspace 一
bindsym $mod+Shift+1 move container to workspace 一
```

etc.

**Comment by magnus-ISU** [comment]
Is there a reason to ever use `workspace number 1` over just `workspace 1`? That makes sense I guess, though it seems like a distinction that shouldn't need to exist.

**Comment by Xyene** [comment]
Workspaces can have both numbers and names associated with them. Check out the i3 docs for details: https://i3wm.org/docs/userguide.html
