### ISSUE TITLE
Unable to connect to Sway socket from Emacs terminal

### ISSUE THREAD

**Issue by fosskers** [swaywm/sway#6451]
I am unable to run `swaymsg` commands from within terminals inside GTK Emacs (`vterm` specifically). If I run such commands in a regular terminal (`alacritty`) or terminal Emacs, they run fine. The error I see is:

```
00:00:00.000 [common/ipc-client.c:67] Unable to connect to /run/user/1000/sway-ipc.1000.1275.sock
```

Which was previously reported in #1190 . 

- **Sway Version:**
```
❯ swaymsg -t get_version
sway version 1.6.1
```

- **Debug Log:**
  - https://gist.github.com/fosskers/4d556be9392298a9129fddccae373c4a

- **Configuration File:**
  - Basically the default: https://gist.github.com/fosskers/ddd177c390b9ad45df4e437086d96684

- **Description:**
  - Start `sway`.
  - Open a terminal.
  - Run `swaymsg -t get_version` and see it succeed.
  - Open a terminal version of Emacs (`emacs -nw`).
  - Open a `vterm` and repeat the `swaymsg` command. **See it succeed.**
  - Open a GTK version of Emacs.
  - Open a `vterm` and repeat the `swaymsg` command. **See it fail.**

Thank you!

**Comment by Xyene** [comment]
This is not a Sway bug. Very likely the environment block is not the same, or the GTK version is otherwise sandboxed. You could probably check by running `env` in both terminal and GTK Emacs `vterm` and comparing.

**Comment by fosskers** [comment]
Indeed the two insta

**Comment by Xyene** [comment]
Wild guess: if emacs daemonizes off one Sway instance, it'll pick up one value of `SWAYSOCK`. If then you restart that Sway instance, the `SWAYSOCK` will change, but the daemon will continue running, and any `emacsclient`s connecting to it will inherit the old `SWAYSOCK` for their `vterm`s. If the GTK Emacs is connecting to (and starting) the daemon that'd be one explanation, since `emacs -nw` won't.

**Comment by fosskers** [comment]
I don't use a daemonized Emacs so I don't think that could be the issue :thinking:

**Comment by Antiarchitect** [comment]
Any solution to this? Having the same $SWAYSOCK value mismatch in user session and from within Emacs somehow.
