### ISSUE TITLE
wl_touch and wl_pointer positions

### ISSUE THREAD

**Issue by stacyharper** [swaywm/sway#6454]
### Please fill out the following:

- sway version 1.6.1-50f979363e (Jun 26 2021, branch 'master')

My context: I'm implementing pointer and touch event on bemenu (https://github.com/Cloudef/bemenu/pull/200)

I come here after asking in #sway cause it initially could be a question. I now think there is an issue in the behavior of wl_touch motions. And someone in irc asked me to open an issue for futher discussion.

Lets say I got this window composition : 

 ![](http://dav.misterbanal.net/fb6b2521-8bf0-44c6-8f7c-7a6e8ab5da43.png)

Here, Clicking (and holding) on the Wev surface. I then move to other windows without releasing. I continue to receive motion events with the position relative to the initial surface position. Other windows dont grab focus and the initial surface got everything needed to understand and behave correctly.

Not take the exact same composition and touch the screen with you finger. Then you move your finger outside of wev. You will continue to receive motion event but here, the position will be relative to the new surface. The initial surface then think you entered again to this surface and cant behave accordingly to your real finger position.

I also suffer more issue with this bemenu works. I dont receive those pointer motion event when holding click when I leave the surface.

Is it a bug ? Is there something bemenu must to do to receive those event correctly ?

Thanks a lot

**Comment by emersion** [comment]
>  I dont receive those pointer motion event when holding click when I leave the surface.

Ref https://github.com/swaywm/sway/pull/6418

> You will continue to receive motion event but here, the position will be relative to the new surface.

Sounds like a bug.

**Comment by Eluminae** [comment]
I just edited a part :  

I also suffer more issue with this bemenu works. I dont receive those pointer motion event when holding click when I leave the surface IF THERE IS NO OTHER SURFACE BELLOW. I still dont know why. I received them exactly as Wev receive them.

**Comment by Xyene** [comment]
> > You will continue to receive motion event but here, the position will be relative to the new surface.

> Sounds like a bug.

Ref https://github.com/swaywm/sway/issues/5630

I think this is just due to Sway not having a seatop_down implementation for touch input. If you (or someone else) wanted to take a stab at it, it shouldn't be too hard to get working. https://github.com/swaywm/sway/commit/5d13f647f9384e59012c0f829651911564bb5365 implemented this for tablet input, and I suspect a touch implementation would be very similar.

**Comment by Eluminae** [comment]
Yeah but we receive event if there is another window under the touch. I feel there is just a bug on an output determination at one point.

**Comment by Eluminae** [comment]
This method is in cause : https://github.com/swaywm/sway/blob/master/sway/input/cursor.c#L519

We grab the surface under the position of the touch and we compute local coordinate. We notify the motion at the end using those new coordinate. This behavior look coded this way. If it is unexpected, then we must just rewrite this completly right ? I may dig into it but I want to be sure firtly
