### ISSUE TITLE
XWayland: windows don't redraw content until resized/moved 

### ISSUE THREAD

**Issue by michelesr** [swaywm/sway#6459]
This can be reproduced in different apps using GTK2, such as GIMP or Ardour. In Ardour reproducing is easier, so I'll use it in the steps below. This doesn't appear to be an XWayland issue as I can't reproduce under `weston --xwayland`.

- **Sway Version:**
  - sway version 1.6-bb3fd0ab (Aug 24 2021, branch 'master')

- **Debug Log:**
  - http://sprunge.us/NKGZad

- **Configuration File:**
  - A single `bindsym` line to allow spawning a terminal window to run programs

- **Stack Trace:**
  - N/A

- **Steps to reproduce**
  - start sway
  - spawn a terminal using an hotkey from your miminal config
  - run `ardour6` from the terminal (keep the terminal window open)
  - load a session or create a new one from an empty template
  - look at the window that hasn't refreshed properly (see screenshots)
  - resize the window, or toggle fullscreen on/off, or move the window, or change the border type
  - look at the window that is now refreshed properly
  
- **Additional info**

This xcb error and similar ones are printed approximately near the time Ardour is loading the session:

```
00:00:07.305 [ERROR] [wlr] [xwayland/xwm.c:1477] xcb error: op ChangeProperty (no minor), code Window (no extension), sequence 404, value 4195298
``` 

Also the issue can't be reproduced if the XWayland window is the only window in the active workspace, or in stacked/tabbed layout. Basically, this happens when there's another window actively occupying a part of the output.

 **Screenshots**

Ardour after loading the session:
![screenshot-2021-08-24-22:59:18](https://user-images.githubusercontent.com/2516077/130695809-39490b99-5268-4ade-a672-fe2c881e0653.png)

Ardour after resizing/moving the window
![screenshot-2021-08-24-22:59:29](https://user-images.githubusercontent.com/2516077/130695813-d4ab0113-a76c-4244-b603-25d4d14c7add.png)

**Comment by michelesr** [comment]
The steps to reproduce in GIMP are similar:

- spawn a terminal while in split mode
- run `gimp` while keeping the terminal open
- start a new project (`CTRL+N` and `Enter`)

The project can be saved to reproduce quicker by simply running `gimp Untitled.xcf`

Screenshots (before and after resizing gimp window):

![screenshot-2021-08-30-13:12:23](https://user-images.githubusercontent.com/2516077/131337302-7c77de0a-11ba-4e93-850e-792183e264d3.png)
![screenshot-2021-08-30-13:13:55](https://user-images.githubusercontent.com/2516077/131337305-14b14a47-5124-42a4-a2ea-0655a9b9bebb.png)

When running with gdb and breaking at [surface_create](https://github.com/swaywm/wlroots/blob/72a156b18aea4da5a87823da8a10ace389f9325e/types/wlr_surface.c#L742), if continuing manually, the window is rendered properly, which probably means the window is rendered somehow too quickly?

**Comment by emersion** [comment]
Can you reproduce with `-Ddamage=rerender`?

**Comment by michelesr** [comment]
> Can you reproduce with `-Ddamage=rerender`?

Yes

**Comment by Jordanyay** [comment]
I have recently encountered a similar, if not identical bug when trying to launch GIMP from Alacritty in a "splith" layout workspace.

I first noticed this bug when trying to open an image in GIMP from the nnn terminal file manager, from there I tested different methods to try and eliminate the problem, some successful methods include:

- Running `gimp` directly from the terminal, navigating to GIMPs menubar and clicking "File>Open Recent>[image]", from there you have a couple of options of which you can use to "unfreeze" GIMP:
  - Holding the default Sway mod key (Mod4) and right-click dragging to resize the GIMP window.
  - Moving the cursor focus to the parent terminal.
  - Switching to a different workspace, then switching back to the workspace GIMP is already open in.
  - Toggling GIMP into fullscreen with Sways default `$mod+f` keybinding.
  - Opening a floating GIMP window through the menubar, e.g. "Edit>Preferences".

- Running `gimp & exit` directly from the terminal, causing `gimp` to be run in the background while also exiting the terminal. Next, navigating to GIMPs menubar and clicking "File>Open Recent>[image]", from there the image would open normally without any other additional input required.

It looks to be that GIMP works as you would expect when it's the only window in the workspace or when the window focus is moved to a different window after GIMP "freezes".

I hope this helps.

**Comment by Jordanyay** [comment]
Update:

When testing it out just a moment ago, I have found that "File>Open Recent>[image]" isn't having any problems opening an image with the pixel dimentions of 256x256 (Minecraft: Java logo), but freezes with large images, e.g. a 1080p screenshot.

I haven't tested anything else beyond that.

**Comment by chiraag-nataraj** [comment]
I am also running into a variation of this issue. The difference is that even when Ardour is the only window in the workspace, I _still_ run into this issue.

**Comment by michelesr** [comment]
With the new version of Sway (1.10) I cannot reproduce the issue anymore.
