### ISSUE TITLE
Tooltips in xwayland in firefox make it impossible to change display

### ISSUE THREAD

**Issue by cafehaine** [swaywm/sway#646]
When hovering a tab in firefox (I'm using developer, maybe it's the problem) a tooltip is displayed, but if you move your mouse to another display before this tooltip pops up, it will stay in this new display, and you won't be able to change display unless you hover this tooltip on the second display.

How to reproduce:
-firefox-developer running in sway (xwayland)
-2 displays arranged vertically (firefox on the bottom one)
-hover a tab
-mouve your mouse to the other display right before the tooltip pops up
-the tooltip will display on this new display, and you will have to hover it to select another display

EDIT:
might be a duplicate of #626

**Comment by SirCmpwn** [comment]
This has been fixed on the wlroots branch. :tada:
