### ISSUE TITLE
Drag and dropping files into sandboxed applications

### ISSUE THREAD

**Issue by WhyNotHugo** [swaywm/sway#6460]
When an application is sandboxed (e.g.: Flatpak), dragging files into it doesn't work out-of-the-box.

This is because the receiving application does not have access to the dropped file.

For this to work, the compositor needs dedicated support. That is, the compositor needs to export the file to the receiving application, and replace the data in the drop event with the exported path.

There's more background on this https://github.com/flatpak/xdg-desktop-portal/issues/99 and https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/418.

I don't think sway itself should implement this mechanism entirely; I think a [somewhat privileged] helper would make sense. However, sway still needs to expose a mechanism for this helper to work.

Off the top of my head, I think of a helper that gets details of all inter-process drag-and-drop events, and returns an [optionally] modified copy of the event for the receiving application. Doing any flatpak-specific magic is up to this helper.

**Comment by WhyNotHugo** [comment]
[just realised I drafted this comment and never saved it!]

I've been thinking about this further. We probably need a new protocol for a special client to handle this. I'll call it the "drag manager" from now on:

- the drag manager register with the compositor using a privileged interface
- when a drag event happens across clients, the drag manager receives this event which includes a reference to the original `wlr_data_control_offer`, and the pid of both clients.
- the regular event **is not** send immediately to the receiving client.
- the drag manager must do one of the following:
  - send a request indicating that the `wlr_data_control_offer` should be forwarded as-is.
  - send a request with a new `wlr_data_control_offer`. This can, for example, alter file-paths to paths that are accessible for sandboxed applications.
  - send a request indicating that the operation must be cancelled.

I can try and draft a protocol with these ideas a bit more clearly. I wouldn't be surprised if I'm missing some obvious fault here.

**Comment by WhyNotHugo** [comment]
I also now realise that the same protocol can also handle pastes (e.g.: when pasting files into a sandboxed client).

**Comment by emersion** [comment]
It seems like clients need to use https://github.com/flatpak/xdg-desktop-portal/pull/222, but then I'm unsure the compositor actually needs to do anything in particular?

I'm not a huge fan of the DnD interception protocol.

**Comment by WhyNotHugo** [comment]
> It seems like clients need to use flatpak/xdg-desktop-portal#222 [...]

This would need to be implemented by both the sending and the receiving client. It seems to be rather tricky to get every single client that supports drag and drop to implement a new protocol.

That aside, the `xdg-desktop-portal` is tightly coupled into a few Flatpak internals, and some interfaces won't work with other sandboxing mechanism (for example, firejail, manual usages of bubblewrap, etc). Trying to use FileChooser+Document portal with any non-Flatpak sandboxes won't work (https://github.com/netblue30/firejail/issues/4716), since the portal reads a lot of Flatpak metadata, and will treat the application as non-sandboxed if it's not a Flatpak. I suspect this is likely the case for the scenario at hand too.

> I'm not a huge fan of the DnD interception protocol.

To be honest, me neither, but I can't think of another approach. If client support for the protocol you linked were ubiquitous, then writing a sandbox-agnostic portal _might_ be possible. However, the xdg-desktop-portal is implemented as a monolith, and I'm not sure that overriding _just_ the `org.freedesktop.portal.FileTransfer` interface alone is possible.

This interception protocol would also allow writing a privileged client that shows some indicator whenever an application pastes (e.g.: to catch misbehaving applications). I tried implementing this with `wlr-data-control-unstable`, but it seems to not be possible to implement reliably due to a couple of issues with race conditions. Might make sense to at least report that separately though.
