### ISSUE TITLE
Damage artifacts with fractional scaling

### ISSUE THREAD

**Issue by dnkl** [swaywm/sway#6469]
Multiple users have reported what appears to be damage tracking related artifacts, in foot, when using fractional scaling. 

Downstream issue: https://codeberg.org/dnkl/foot/issues/350.

There's a screenshot in the first post. The artifact appears to be one row of pixels from the cursor, from the previous frame. I'm betting the cursor is the only glyph leaving artifacts because it is the only glyph that spans the entire row (and foot's damage reporting to Wayland is row based).

Quoting https://codeberg.org/dnkl/foot/issues/350#issuecomment-245782:

> I had a session where I tried to reproduce on Sway. With fractional scaling == 1.25, I was finally able to.
> 
> I'm still not sure exactly which parameters matter: window size, cell size, other?
> 
> The interesting thing is this: the issue only happened on a specific row in the terminal. This suggests the offset (within the surface) of the damage region matters. Fairly sure the size of it also matters.
> 
> But what's more interesting is the issue disappeared when I moved the entire window (window was floating at all times).
> 
> ... And came back when I moved the window back to the original location.
> 
> Note that this came down to individual pixels: trigger the issue, move window one pixel up and it went away. Move it back down one pixel, and it reappears.
> 
> To me, this screams of a rounding issue in the compositor.

I don't think debug logs will add anything useful, but can do another session where I reproduce the issue while debug logging. If you think that would be useful.

Unsure _exactly_ which Sway version I used when reproducing. 1.6 something, but was likely a git snapshot. Fairly sure others have seen it in plain 1.6 though.

FWIW, I did look through Sway's damage tracking code, and couldn't see anything obviously wrong, related to fractional scalilng. `ceil()`'s and `floor()`'s appears to be used correctly.

I also haven't seen this in any other application (though, I don't use normally fractional scaling). Not sure if this is related to foot being SHM based, or other applications reporting damage differently.

**Comment by emersion** [comment]
Hm. I kind of wish we had `-Wconversion` turned on because of all of these issues.

Yes, it's very likely that we are implicitly converting a float to an int somewhere. Probably with the container coordinates.
