### ISSUE TITLE
Keyboard and mouse not working after unplugging/replugging dock station

### ISSUE THREAD

**Issue by lucabaldesi** [swaywm/sway#6471]
Hi,
I have a Dell Precision 5550 and sway works flawlessly on it. I also have a Dell wd19tb docking station with connections to a display port monitor, mouse and keyboard.

If I boot the laptop after I have plugged in the docking station everything works as I expect. If I unplug the docking station and plug it back, the monitor keeps working while the mouse and keyboard do not.
Mouse and keyboard do not even appear in the output of "swaymsg -t get_inputs".

Is there a way to force sway to rescan for inputs?
sway version 1.6.1

Thanks,
Luca

**Comment by emersion** [comment]
Does it show up in `sudo libinput list-devices`?

If not, might be a kernel bug.

**Comment by lucabaldesi** [comment]
No, they do not appear in the output of list-devices.
In fact, they are not detected at all if I turn on the laptop, and then plug-in the docking station, without starting sway.
So it cannot be a bug of sway.

kernel 5.13.12 with arch linux

**Comment by lucabaldesi** [comment]
No, they do not appear in the output of list-devices.
In fact, they are not detected at all if I turn on the laptop, and then plug-in the docking station, without starting sway.
So it cannot be a bug of sway.

kernel 5.13.12 with arch linux
