### ISSUE TITLE
Random crashes/freezes

### ISSUE THREAD

**Issue by nod0ubt** [swaywm/sway#6474]
Hey, I've been using sway since last week and I really like it, but I've been experiencing random X crashes ever since I installed it. It's Endeavour OS workstation with two different monitors (4k + 2k) which is why I've gone for wayland DE, so I can utilize screen scaling.

Anyway, my issue is that at any point my graphics can crash and that's really uncomfortable when working. Usually happens when I'm browsing with Chromium - sway just crashes and reloads, sending me back to login screen and closing everything. Sometimes it will freeze the whole PC and a hard reset will be required.

It is (to me) very random and I cannot find a way to force it. Yesterday was fine almost the whole day and this morning it happened right after I opened new tab to browse into gmail. 
It's been happening when browsing, listening to music, switching between workspaces and whatnot. I'm using NVIDIA gpu with the (obviously) nouveau driver.

**sway version 1.6.1**

Thats my custom config

```
# Initial Setup 
exec ~/set_once.sh

# Config for sway
#
# Read `man 5 sway` for a complete reference.

# user config directory
include $HOME/.config/sway/config.d/*

# only enable this if every app you use is compatible with wayland
# xwayland disable

focus output HDMI-A-1

output HDMI-A-1 scale 2

output HDMI-A-1 pos 0 0 res 3840x2160
output DP-1 pos 1920 0 res 2560x1440
```

And my debug log:

[sway.log](https://github.com/swaywm/sway/files/7096666/sway.log)

Let me know if anything else is needed.
Thanks

**Comment by RPigott** [comment]
> nouveau: kernel rejected pushbuf: No such device
> nouveau: ch6: krec 0 pushes 1 bufs 12 relocs 0


Looks like a dup of #5883
