### ISSUE TITLE
journal spam filled with 'Could not resolve keysym XF86...'

### ISSUE THREAD

**Issue by ayushnix** [swaywm/sway#6476]
I noticed that sway is generating a lot of journal spam by printing messages like

```
> Warning:          Could not resolve keysym XF86Macro1
> Warning:          Could not resolve keysym XF86Macro2
> Warning:          Could not resolve keysym XF86Macro3
...
```

[Here's](https://paste.ack.tf/69ee88) the debug logs. If it helps, I'm using an external USB keyboard attached to my laptop. 

The only thing I have in my sway config related to xkb is `xkb_layout us`. Is this journal spam intended? How can I fix this?

I'm also getting libinput messages like

```
SONiX USB DEVICE: client bug: event processing lagging behind by 30ms, your system is too slow
```

**Comment by emersion** [comment]
These come from Xwayland.

**Comment by ayushnix** [comment]
Is there no way to remove them from the logs besides doing something like piping sway output to `grep -v` or disabling Xwayland (can't do the latter just yet)?

**Comment by kennylevinsen** [comment]
sway can't do anything about output from an entirely different application.

Options involve patching Xwayland (well, probably xkbcomp) to not output these messages, or to disable Xwayland.

**Comment by AzP** [comment]
Just for the historic scrolls: 
Related upstream bug with merged MR: https://gitlab.freedesktop.org/xorg/lib/libx11/-/issues/137

**Comment by akhiljalagam** [comment]
I am still viewing logs in libX11-1.8.7 as well.

**Comment by AzP** [comment]
> I am still viewing logs in libX11-1.8.7 as well.

Are you seeing it if you're running Gnome (or other DE) as well? Perhaps it is better to note that on the issue I linked above, as it seems sway is not responsible for XWayland/xlib, etc.
