### ISSUE TITLE
Sway crashes when waybar starts

### ISSUE THREAD

**Issue by alejor** [swaywm/sway#6492]
- **Sway Version:**
  - `swaymsg -t get_version` or `sway -v` 
  - sway version 1.6-ae80bded (Sep  6 2021, branch 'master')
     wlroots-git  : 0.14.0.r209.gba0525c5-1
     waybar-git : r1590.4e256cf-1

- **Debug Log:**
  - Run `sway -d 2> ~/sway.log` from a TTY and upload it to a pastebin, such as gist.github.com.
  - This will record information about sway's activity. Please try to keep the reproduction as brief as possible and exit sway.
  - https://pastebin.com/3KMbbmQs

- **Configuration File:**
  - Please try to produce with the default configuration.
  - If you cannot reproduce with the default configuration, please try to find the minimal configuration to reproduce.
  - Upload the config to a pastebin such as gist.github.com.
  

- **Stack Trace:**
  - This is only needed if sway crashes.
  - If you use systemd, you should be able to open the coredump of the most recent crash with gdb with
    `coredumpctl gdb sway` and then `bt full` to obtain the stack trace.
  - If the lines mentioning sway or wlroots have `??` for the location, your binaries were built without debug symbols. Please compile both sway and wlroots from source and try to reproduce.
https://pastebin.com/WKvDdABk

- **Description:**
After latest update, I rebooted and sway crashed seconds after start, I tried to debug and disable alexays's waybar, then it started without crash. When I tried to start waybar, sway crashes with SIGABRT. My setup was working without problems until today when I update wlroots, sway and waybar stack. I tried to recompile cleaning up with 
yay -S gtk-layer-shell-git seatd-git wlroots-git sway-git wl-clipboard-git waybar-git but issue persists.
Latest update prior today was at aug 31
[2021-09-06T14:37:59-0500] [ALPM] upgraded sway-git (r6751.57d6f6f1-1 -> r6758.ae80bded-1)

Looking at wlroots commits, I think this commit has smt to do with this issue
https://github.com/swaywm/wlroots/commit/ba0525c5c08b31ade48368df4d2fd1bbefd1304a

Any info I'm glad to provide. Thank you

**Comment by alejor** [comment]
In effect, compiling wlroots with a commit before swaywm/wlroots@ba0525c and recompiling dependencies again (sway, waybar, etc,) causes sway stop to crashing when waybar starts.

**Comment by jbeich** [comment]
> https://pastebin.com/3KMbbmQs
[...]
> sway: types/wlr_buffer.c:198: wlr_buffer_from_resource: Assertion `resource && wlr_resource_is_buffer(resource)' failed.

Duplicate of https://github.com/swaywm/wlroots/issues/3173. Update wlroots as it's already fixed.

**Comment by alejor** [comment]
Closing as already fixed in wlroots.
