### ISSUE TITLE
`swaymsg output` not parsing files with parentheses properly

### ISSUE THREAD

**Issue by rieje** [swaywm/sway#6499]
Filename: `/home/rieje/pictures/wallpapers/The Red Tower (La Tour Rouge) - Giorgio de Chirico.jpg`

Command: `swaymsg output "*" bg "/home/rieje/pictures/wallpapers/The Red Tower (La Tour Rouge) - Giorgio de Chirico.jpg" fill`

Output:` Error: Invalid syntax (/home/rieje/pictures/wallpapers/The Red Tower (La Tour Rouge) - Giorgio de Chirico.jpg)`

- **Sway Version:** 1.61

**Comment by progandy** [comment]
The command given to swaymsg  is most likely parsed twice, once by the shell and once by sway. You need to nest quotes to pass the path through, e.g.

    swaymsg 'output "*" bg "/home/gcheng/pictures/wallpapers/The Red Tower (La Tour Rouge) - Giorgio de Chirico.jpg" fill'

**Comment by rieje** [comment]
That did not work but escaping the parentheses did, whether or not I quote the swaymsg command as in your example (on both bash/zsh--I'm too familiar with the shell to know the exact culprit). I get no issues from the command `swaymsg output "*" bg "~/pictures/wallpapers/The Doctor.jpg" fill` (without quotes). It runs once and exits 0. 

I'm pretty sure I have experienced the issue the manpage and you've described where swaymsg and the shell attempts to run the command twice, but I am not able to reproduce this right now.

I will follow your advice and will look into my simple [wallpaper script](https://pastebin.com/v1Xy10UP) on how to parse the argument `"/home/rieje/pictures/wallpapers/The Red Tower (La Tour Rouge) - Giorgio de Chirico.jpg"`  and convert it to one for swaymsg.

**Comment by progandy** [comment]
I found the reason. I forgot sway calls ```wordexp``` to expand the path (with some workarounds for spaces). I think that is missing from the documentation.

I'm not sure if that behaviour should be changed or only documented.

**Comment by rieje** [comment]
I see.

I am able to reproduce the the behavior where swaymsg runs many times(?). On [the terminal and bash](https://pastebin.com/UZ947UD7) with the command quoted in single quotes. Maybe the single quotes around the variable name unquote the single quotes around the swaymsg command or something, but I'm not able to get the command to work otherwise (tried escaping inner quotes and/or $).

**Comment by progandy** [comment]
> I'm pretty sure I have experienced the issue the manpage and you've described where swaymsg and the shell attempts to run the command twice, but I am not able to reproduce this right now.

The command is not run twice, but each step parses the text and consumes some quotes or escape sequences. Here is the full codepath with a working filename. 

```$ swaymsg 'output "*" bg "/tmp/foo \(bar\).jpg" fill'```

bash consumes single quotes, swaymsg receives  one parameter with the complete string,
backslash escapes are not consumed since they are inside single quotes.

```output "*" bg "/tmp/foo \(bar\).jpg" fill```

that is sent to sway as a single string. sway parses it to:

```
output
*
bg
/tmp/foo \(bar\).jpg
fill
```

wordexp is run on the path with some stuff to fix whitespace. It consumes the backslash escapes:
It would fail if there were brackets without backslash escape. This is your original problem.

```/tmp/foo (bar).jpg```

swaybg is started with that path.

**Comment by rieje** [comment]
I used `sed` to add backslashes before parentheses for swaymsg so the wallpaper script can take a file path "normally" as if passed from the terminal with shell completion or from the output of `find`. Seems fine. I forgot to post the [pastebin](https://pastebin.com/ZVf7z3ur) where after every time swaymsg executes, it's as if I'm pressing "Enter" on the terminal multiple times without entering any commands. I guess that's the result of

> each step parses the text and consumes some quotes or escape sequences

and probably not avoidable? Looks a little janky getting that every time setting the wallpaper via script.
