### ISSUE TITLE
`Unable to drop root` while launched as regular user

### ISSUE THREAD

**Issue by yonatan8070** [swaywm/sway#6506]
### Please fill out the following:
- **Sway Version:**
  - 1.6.1 (From official Arch repos)

- **Debug Log:**
  - Sway log: https://gist.github.com/yonatan8070/d984f1753f1403040d171ec5e5c48182

- **Configuration File:**
  - Given the nature of this issue, I do not think the configuration matters here, all of my config files can be viewed here: https://github.com/yonatan8070/dotfiles

- **Description:**
  - Install Sway from the official Arch repos on a brand new Arch installation. My user can use sudo, but does not have root privilages (I can't change any files in / without sudo)

- **Hardware**
  - I'm using a Lenovo IdeaPad 530S with this configuration:
    - Intel Core i7-8550U CPU
    - Intel UHD 620 + NVIDIA GeForce MX150 (I did not install *any* drivers for the NVIDIA card)
    - 8GB RAM

**Comment by kennylevinsen** [comment]
How do you start sway?

**Comment by yonatan8070** [comment]
I just run `sway` in a tty, after logging in using my username and password

**Comment by kennylevinsen** [comment]
The error means that sway could freely become UID 0 (root). This suggest something funky is up - either some caps were set on  the sway process/executable or something like pam_cap is giving your session CAP_SYS_ADMIN, which is bad.

**Comment by yonatan8070** [comment]
Sorry it took me a while to reply, I had some IRL stuff going on

Could you explain what you mean by that comment? I'm not sure what caps are, or what pam_cap/CAP_SYS_ADMIN are.

And how would I go about checking for their status?

**Comment by yonatan8070** [comment]
After a bit more Googling and banging my head against a wall, I figured out that my user's default group was `root` instead of `yonatan`, changing it to `yonatan` allows sway to start properly
