### ISSUE TITLE
Crash with Sway and Wlroots master

### ISSUE THREAD

**Issue by stacyharper** [swaywm/sway#6508]
### Please fill out the following:
- **Sway Version:**
  - `sway version 1.6-57ae7516 (Sep 12 2021, branch 'master')`

- **Wlroots Version:**
  - `52da68b5`

- **Debug Log:**
  - https://dav.missbanal.net/5d8b00d9-55f3-43b6-9c53-cdf5b33a91c8

- **Configuration File:**
  - The default one `-c /usr/local/etc/sway/config` https://dav.missbanal.net/c0b57142-3a18-4899-91c7-f9cb037ff9f9

- **Stack Trace:**
  - I'm not on systemd, I'm trying to enable core files to have the stacktrace

- **Description:**
  - I just pulled and I now have a crash on start. I talked a little bit on irc with emersion and kennylevinsen and as it looks like a bug, I open this.

**Comment by emersion** [comment]
```
00:00:00.020 [ERROR] [wlr] [EGL] command: eglQueryDeviceStringEXT, error: EGL_BAD_PARAMETER (0x300c), message: "eglQueryDeviceStringEXT"
00:00:00.020 [ERROR] [wlr] [EGL] command: eglQueryDeviceStringEXT, error: EGL_BAD_PARAMETER (0x300c), message: "eglQueryDeviceStringEXT"
```

Means you have NVIDIA proprietary drivers installed, which trigger a libglvnd bug. Either upgrade libglvnd to the latest git commit, or remove the proprietary drivers.

**Comment by stacyharper** [comment]
Okay but I dont have libglvnd. So I probably got a substitute with the same issue ? And I still cant findout which package brings me nvidia proprietary drivers. Maybe something integrated with my kernel? I'm on pmOs, an Alpine based os.

**Comment by RPigott** [comment]
> Means you have NVIDIA proprietary drivers installed [...]

I don't think so, the nvidia egl vendor library has weirdly verbose/formatted error messages but this is just "eglQueryDeviceStringEXT". I think it's emitted here: https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/egl/main/egldevice.c#L273.

**Comment by stacyharper** [comment]
I just rebuilded Sway with an up to date system and master branches. The issue seems gone. 

I am no sure about the reason but I still close this.
