### ISSUE TITLE
bindsym keybinding that only activates when no modifier is used 

### ISSUE THREAD

**Issue by PremiumUsername** [swaywm/sway#6522]
### Please fill out the following:
- **Sway Version:**
sway version 1.6.1

I was trying to create a keybinding that would work only when you press the key without using a modifier, so I could use that modifier for other programs: I tried:

`bindsym F5 layout toggle split tabbed`

This would activate even for ctrl+f5

...but using the bindcode equivalent:

`bindcode 71 layout toggle split tabbed` 

...works just fine. It does not activate on ctrl+f5 

This is not a difference I've manged to see in the man pages? Is this supposed to be a difference? Shouldn't it be possible to use bindsym for this as well. 

I also tried using:

`bindsym ctrl+F5 nop` but it made little difference. It would no longer activate for ctrl+f5, but the the program I tried to use the ctrl+f5 shortcut with (visual code running in wayland) could not see the key presses anyway.

**Comment by RPigott** [comment]
Sway always consumes bindings. So if you bind F5 apps won't see it when you press it, same for Ctrl+F5.

Your issue is that F5 is emitted by both "F5" and the key combo "Ctrl+F5". This is a quirk of your keymap. The Control modifier is consumed for the function keys specifically, since they are of Ctrl+Alt type. The end result is that a lone F5 binding triggers on F5 and Ctrl+F5, while a Ctrl+F5 triggers on Ctrl+F5 only.

`bindcode` seems like a fine workaround if you don't want to change the keymap. It works because sway calculates code bindings without the modifiers consumed. Though, `bindsym --to-code F5` should also work and is a little cleaner.

**Comment by PremiumUsername** [comment]
> It works because sway calculates code bindings without the modifiers consumed. Though, `bindsym --to-code F5` should also work and is a little cleaner.

Trying `bindsym --to-code F5` was the first thing I did after discovering that `bindcode` worked, but it didn't work I'm afraid.

I'm still not quite sure why some keys work in one way and other doesn't. I certainly wasn't aware that there was a Ctrl+Alt type that would be handled differently, that explains a lot. Are these details written down somewhere. I've noticed that if I do a custom map for a key with `XF86AudioLowerVolume`, sway seems to swallow all varieties, but `XF86Back` will let things through.  It's all a bit confusing.

**Comment by RPigott** [comment]
I'm pretty sure you're mistaken about --to-code. I tried it just now with a standard us keymap and it works fine.

Like I said, it's a quirk of your keymap that some work differently. You need to find some xkb docs and examine your keymap. archwiki is alright here [1], but doesn't seem to cover this. Last resort is [2], chapter 7 has the details.

[1] https://wiki.archlinux.org/title/X_keyboard_extension#Modifiers_and_types
[2] https://www.x.org/releases/current/doc/kbproto/xkbproto.pdf

**Comment by PremiumUsername** [comment]
> I'm pretty sure you're mistaken about --to-code. I tried it just now with a standard us keymap and it works fine.

Maybe it's just a problem with Visual Studio Code then, but with `--to-code` I'm can't create a ctrl+F5 binding in VSC, but using bindcode I can, Maybe you're saying, that with  `--to-code` Sway doesn't activate the keybinding for ctrl+F5 if the keybinding is just for F5, in which case I agree completely. However, the problem I'm having is not that, but that it does not let the (for sway) unused keybinding through so that it can be used for other programs.

In any case, thanks for your time and patience for what, I realise, is a rather small and esoteric problem.
