### ISSUE TITLE
Can't set native resolution on hotplugged external output

### ISSUE THREAD

**Issue by diggit** [swaywm/sway#6538]
### Please fill out the following:
- **Sway Version:**
  - `sway version 1.6.1`

- **Debug Log:**
[sway.log](https://gist.github.com/diggit/8d9683e21021931c26fd5645d4e2c25e)

- **Configuration File:**
output related section below
```
output * bg ~/Images/wallpaper-3840x2160_black.png fill
#
# Example configuration:
#
output LVDS-1 {
        enable
}
```

- **Description:**
Setting maximum (native) resolution on newly connected output is not possible.
- **Steps (recorded in log)**
  - start with attached only internal `LVDS-1` (1600x900)
  - attach external output `DP-3` (resolution info below)(laptop inserted into docking station)
  - try to enable `DP-3` by `swaymsg output DP-3 mode 2560x1440` -> fail (log line ~1560)
  - try to enable `DP-3` by `swaymsg output DP-3 mode 1920x1080` -> success (log line ~2690)

Starting sway with already connected output `DP-3` works fine and sway starts on `LVDS-1` and `DP-3` in native (maximum) resolutions. It's possible to break `DP-3` output by enabling and disabling outputs in some order and settings, butI was not able to find reproducible pattern.

- **Outputs**
```
Output DP-3 'BenQ Corporation BenQ LCD G7G04942019' (focused)
  Current mode: 2560x1440 @ 59.951 Hz
  Position: 0,0
  Scale factor: 1.000000
  Scale filter: nearest
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 2
  Max render time: off
  Adaptive sync: disabled
  Available modes:
    720x400 @ 70.082 Hz
    640x480 @ 59.940 Hz
    640x480 @ 59.940 Hz
    640x480 @ 60.000 Hz
    640x480 @ 75.000 Hz
    720x480 @ 59.940 Hz
    720x480 @ 59.940 Hz
    720x480 @ 59.940 Hz
    720x480 @ 60.000 Hz
    720x480 @ 60.000 Hz
    720x576 @ 50.000 Hz
    720x576 @ 50.000 Hz
    720x576 @ 50.000 Hz
    800x600 @ 60.317 Hz
    800x600 @ 75.000 Hz
    832x624 @ 74.551 Hz
    1024x768 @ 60.004 Hz
    1024x768 @ 75.029 Hz
    1280x720 @ 50.000 Hz
    1280x720 @ 50.000 Hz
    1280x720 @ 59.940 Hz
    1280x720 @ 60.000 Hz
    1280x720 @ 60.000 Hz
    1152x864 @ 75.000 Hz
    1280x800 @ 59.910 Hz
    1280x1024 @ 60.020 Hz
    1280x1024 @ 75.025 Hz
    1600x900 @ 60.000 Hz
    1680x1050 @ 59.883 Hz
    1920x1080 @ 50.000 Hz
    1920x1080 @ 59.940 Hz
    1920x1080 @ 60.000 Hz
    1920x1080 @ 60.000 Hz
    2560x1440 @ 59.951 Hz

Output LVDS-1 'Unknown 0x0362 0x00000000' (inactive)
  Available modes:
    1600x900 @ 59.985 Hz
```

**Comment by emersion** [comment]
Can you still reproduce with `WLR_DRM_NO_MODIFIERS=1`?

**Comment by diggit** [comment]
Stopped sway, set environment variable, verified it's value, started sway again, but behavior is still the same. So, no effect.

**Comment by diggit** [comment]
I noticed, that if I connect HDMI output to TV (1920x1080 @ 60Hz), there is no such issue and output can be configured to native resolution.

**Comment by emersion** [comment]
Maybe try https://github.com/swaywm/wlroots/wiki/DRM-Debugging

**Comment by diggit** [comment]
probably same issue as in #3511 and swaywm/wlroots/issues/2124
common factor is same CPU/GPU generation, my device is Thinkpad T430
It could be bug in i915, but why it was not happening under X11?

**Comment by diggit** [comment]
I am closing this issue, as it's not present anymore. Unfortunately, I am not sure what resolved it.
