### ISSUE TITLE
segfault when starting Spotify 

### ISSUE THREAD

**Issue by TobTobXX** [swaywm/sway#6539]
### Please fill out the following:
- **Sway Version:**
  - `sway -v`
  - `sway version 1.6.1`

- **Debug Log:**
  - N/A (not reproducable; sorry)

- **Configuration File:**
  - https://paste.sr.ht/~tobtobxx/1be073d58489533a03dbfd6deb6b3331d5b23a99

- **Stack Trace:**
```
#0  0x00007f51ebdf4330 in  () at /usr/lib/libwayland-server.so.0
#1  0x00007f51ebde907a in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#2  0x00007f51ebde6be7 in wl_display_run () at /usr/lib/libwayland-server.so.0
#3  0x000055f0461c697b in  ()
#4  0x00007f51ebafcb25 in __libc_start_main () at /usr/lib/libc.so.6
#5  0x000055f0461c6cee in  ()
```

- **Description:**
  - I started Spotify (an electron app)
  - sway crashed (segfault)

Sorry, I don't know if this has already been reported, but I just wanted to throw it up here, as I don't have a lot of time for investigating right now. You guys can close it if duplicate and/or ask for more infos. I saved the coredump.

... and if you don't feel like fixing, just close it. It's a one-off as far as I can tell.

You rock :+1:

**Comment by Zeioth** [comment]
I'm not sure this is an sway issue. I can run spotify just fine. Did you manage to solve it?

**Comment by TobTobXX** [comment]
It didn't happan again. So I guess no?
