### ISSUE TITLE
Sway sometimes crashes after resuming from sleep

### ISSUE THREAD

**Issue by zsolt-donca** [swaywm/sway#6542]
### Please fill out the following:
- **Sway Version:**
  - `sway version 1.6.1-3b1effdf (Sep 15 2021, branch 'makepkg')`, built with the hidpi patch set against the 1.6.1 tag using https://aur.archlinux.org/packages/sway-hidpi-git/
  - `wlroots` is version `0.14.1.r0.g49a57442-1`, built with the corresponding hidpi patch set against the 0.14.1 tag using https://aur.archlinux.org/packages/wlroots-hidpi-git/
  - `xorg-xwayland-hidpi-git` version 21.1.2.r251.g735dbde48-1, built with the corresponding hidpi patch set, latest build using https://aur.archlinux.org/packages/xorg-xwayland-hidpi-git/

- **Debug Log:**
  - The logs produced by Sway right after resuming from sleep, ending in the crash: https://gist.github.com/zsolt-donca/f8860e2b7f210a922daf0e2e1186d600
  - If it's relevant, I can upload the logs of the entire sway run, but it includes a whole day of working and thus it's quite large (~75 MB)
  - note that the logs are decorated by journalctl, as I'm running sway as a systemd user service
  
- **Configuration File:**
  - My actual sway config: https://gist.github.com/zsolt-donca/dfd1f9b8f411b99e411b72187c9c2d46
  - This is my actual configuration; I'm sorry that it's not minimal, but I could never not manage to consistently reproduce this issue and thus experiment with different configurations

- **Stack Trace:**
```
(gdb) bt full
#0  0x00007fbdb1780078 in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#1  0x00007fbdb177dbe7 in wl_display_run () at /usr/lib/libwayland-server.so.0
#2  0x00005643fe9e3979 in server_run (server=0x5643fea5a100 <server>) at ../sway/sway/server.c:254
        config_path = 0x0
        usage = 0x5643fea3c250 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
        c = <optimized out>
        long_options = 
            {{name = 0x5643fea3b33c "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x5643fea3fc18 "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x5643fea3b341 "validate", has_arg = 0, flag = 0x0, val = 67}, {name = 0x5643fea3b34a "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x5643fea3af00 "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x5643fea3a90f "verbose", has_arg = 0, flag = 0x0, val = 86}, {name = 0x5643fea3b350 "get-socketpath", has_arg = 0, flag = 0x0, val = 112}, {name = 0x5643fea3b35f "unsupported-gpu", has_arg = 0, flag = 0x0, val = 117}, {name = 0x5643fea3b36f "my-next-gpu-wont-be-nvidia", has_arg = 0, flag = 0x0, val = 117}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        validate = 0
        debug = 1
        allow_unsupported_gpu = 0
        verbose = 0
#3  main (argc=<optimized out>, argv=0x7ffe10bfd3b8) at ../sway/sway/main.c:433
        config_path = 0x0
        usage = 0x5643fea3c250 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
        c = <optimized out>
        long_options = 
            {{name = 0x5643fea3b33c "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x5643fea3fc18 "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x5643fea3b341 "validate", has_arg = 0, flag = 0x0, val = 67}, {name = 0x5643fea3b34a "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x5643fea3af00 "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x5643fea3a90f "verbose", has_arg = 0, flag = 0x0, val = 86}, {name = 0x5643fea3b350 "get-socketpath", has_arg = 0, flag = 0x0, val = 112}, {name = 0x5643fea3b35f "unsupported-gpu", has_arg = 0, flag = 0x0, val = 117}, {name = 0x5643fea3b36f "my-next-gpu-wont-be-nvidia", has_arg = 0, flag = 0x0, val = 117}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        validate = 0
        debug = 1
        allow_unsupported_gpu = 0
        verbose = 0
```

- **Description:**
Sway sometimes crashes after resuming from sleep. It is very rare, but happens every week or so. I never managed to reproduce this issue on will.
My setup is a laptop connected to a thunderbolt docking station with some USB devices attached including a keyboard, an external monitor (connected to the docking through DisplayPort), and the laptop's own screen. I'm not sure if relevant, but I often turn off the external monitor after putting the laptop to sleep, as my docking has a weird but that makes the screen wake up every 5-10 minutes for a brief "no signal" message on the screen; so it's possible for my external screen to be there before sleep but missing after, or me just turning it on right after resume from sleep.
I am using an Intel GPU; even though my laptop is an nvidia optimus model, I'm not using nvidia at all, and don't have the proprietary drivers installed.
I am running sway with the env variable `WLR_DRM_NO_MODIFIERS=1` because otherwise in some cases my external monitor won't turn on.

**Comment by KoalaV2** [comment]
Related to #6395 , I had the same issue removing the "clamshell" mode for now fixes it. Aka removing these two lines 
```
bindswitch --locked lid:on output $laptop disable
bindswitch --locked lid:off output $laptop enable
```

**Comment by zsolt-donca** [comment]
I haven't had this issue for months now, using the latest development builds. Closing as this issue is probably fixed already.
