### ISSUE TITLE
Sway crashes when opening certain webpages in Chromium

### ISSUE THREAD

**Issue by h3x4d3c1m4l** [swaywm/sway#6543]
- **Sway Version:**
  - `1.6.1`

- **Debug Log:**
  - https://pastebin.com/pA8SiNDN
    - I removed the parts that showed window titles and config lines for privacy reasons

- **Configuration File:**
  - It is not reproducable with the default config, I'm still in progress of finding the line of config that screws it up...

- **Stack Trace:**
  - https://pastebin.com/xFP0a0pt

- **Description:**
  - Started Chromium 94.0.4606.54 with flags `--enable-features=UseOzonePlatform,WebRTCPipeWireCapturer --ozone-platform=wayland` to ensure it will natively run under Wayland
  - Opened this page: https://flutterbeads.com/state-management-in-flutter-using-the-bloc-design-pattern/
  - Then clicked on one of the ads on the right side (even though the page showed me different ads, Sway crashed for all (two) of the different ads I tested it with)
  - As I have uBlock installed, it starts loading a page that asks me whether I would like to make an exception for opening the ad URL (you see it loading for very short while)
  - Before it finished loading this special page, it crashes and the system goes back to either `gdm` or the TTY I started Sway from

- **Platform description:**
  - Dell XPS15 9500 with Intel 10th gen UHD Graphics
    - It also has a NVIDIA GPU but I blacklisted the driver and confirmed it is not loaded (nor is nouveau loaded)
  - Arch Linux with latest packages installed

**Comment by mindrunner** [comment]
I do have a similar issue. Seems not necessary relate to opening websites, but general interaction with chrome. Sometimes switching between two different chrome clients make sway crash. Sometimes interacting with web3 wallets make sway crash. Sometimes does not happen for days, sometimes happens every minute.

**Comment by emersion** [comment]
Fixed in https://github.com/swaywm/sway/pull/6726

**Comment by mindrunner** [comment]
I think my issue is more related to https://github.com/swaywm/sway/issues/5128#issuecomment-1029308494
