### ISSUE TITLE
Swaybg spinning up CPU

### ISSUE THREAD

**Issue by J0nnyMak0** [swaywm/sway#6546]
With [this](https://github.com/swaywm/wlroots/commit/59fa3637c348270cd1adb239296be1219538394b) commit, swaybg is loading CPU at 100%

**Comment by stacyharper** [comment]
I think we suffer the same issue when using wayout (https://git.sr.ht/~proycon/wayout) (https://pkgs.alpinelinux.org/packages?name=wayout&branch=edge)

When wayout is running, swaybg burn 100% cpu, swaybar 20%. Virtual keyboard instantly crash.

~proycon recently reimplemented the drawing code to try to mitigate the issue.
