### ISSUE TITLE
Sioyek has transparent foreground text

### ISSUE THREAD

**Issue by Epse** [swaywm/sway#6549]
[Sioyek](https://github.com/ahrm/sioyek), a PDF document viewer has an issue where the text (and anything non-background really) is transparent and thus unreadable.

In the attached screenshot, you can tell the text is blue, which is the dominant colour in my wallpaper. Some patches of text are also white where there are clouds in my wallpaper. Swapping the background and foreground colours using sioyek makes this even more apparent.

I have no transparency configured in my sway config, for testing I explicitly set the opacity of sioyek's `app_id` to `1.0`, without a difference. When grepping for sioyek in `swaymsg -t get_tree`, I did see a reference to kitty, my terminal emulator. Just to be sure I disabled transparency in its config, once again without changes.

```json
              "representation": "H[sioyek kitty]",
               "app_id": "sioyek",
```

This does not happen under GNOME running either Wayland or X.

Background is set in the sway config using the snippet below, nothing fancy is going on in my config otherwise, it is essentially default with some keybindings changed.
```
output * bg $HOME/wallpaper.png fill
```

If I can give you any extra info to help debug this or if you think I should file an issue with sioyek, please let me know. I did not attach a log or stack trace as sway is not actually crashing, just doing something weird with transparency.

**Sway Version:**
```
❯ swaymsg -t get_version
sway version 1.4
```

**Comment by Epse** [comment]
**Screenshots**
<details>
<summary>screenshots</summary>

![Screenshot_2021-09-24-113416](https://user-images.githubusercontent.com/10013355/134654908-989f2e65-3b09-447b-b838-828a47c16940.png)
![Screenshot_2021-09-24-113619](https://user-images.githubusercontent.com/10013355/134654917-2782015e-66dc-49ff-a374-25ddd8fe4096.png)

</details>

**Comment by neonsea** [comment]
I can reproduce this, but I'd like to point out that this is probably a [wlroots](https://github.com/swaywm/wlroots) issue as the renderer uses GL fragment shaders (see `/usr/share/sioyek/shaders/simple.fragment` for PDF renderer).

**Comment by emersion** [comment]
Can you collect a `WAYLAND_DEBUG=1` log of the client?

**Comment by Epse** [comment]
[sioyek_debug.log](https://github.com/swaywm/sway/files/7225860/sioyek_debug.log)

**Comment by RPigott** [comment]
Relevant bit from the log:
```
[2268275,938] wl_registry@17.global(2, "zwp_linux_dmabuf_v1", 3)
[2268275,968]  -> wl_registry@17.bind(2, "zwp_linux_dmabuf_v1", 3, new id [unknown]@19)
[...]
[2268277,092] zwp_linux_dmabuf_v1@19.modifier(875713089, 0, 0) # fourcc_code('A', 'R', '2', '4')
[2268277,107] zwp_linux_dmabuf_v1@19.modifier(875713089, 16777216, 1)
[2268277,122] zwp_linux_dmabuf_v1@19.modifier(875713089, 16777216, 2)
[2268277,136] zwp_linux_dmabuf_v1@19.modifier(875713089, 16777216, 6)
[2268277,151] zwp_linux_dmabuf_v1@19.modifier(875713089, 16777216, 7)
[...]
[2268382,196]  -> zwp_linux_dmabuf_v1@19.create_params(new id zwp_linux_buffer_params_v1@33)
[2268382,214]  -> zwp_linux_buffer_params_v1@33.add(fd 20, 0, 0, 8192, 16777216, 6)
[2268382,245]  -> zwp_linux_buffer_params_v1@33.add(fd 21, 1, 9175040, 1024, 16777216, 6)
[2268382,271]  -> zwp_linux_buffer_params_v1@33.create_immed(new id wl_buffer@34, 1926, 1113, 875713089, 0)
[2268382,298]  -> zwp_linux_buffer_params_v1@33.destroy()
[2268382,306]  -> wl_surface@21.attach(wl_buffer@34, 0, 0)
[2268382,322]  -> wl_surface@21.damage(0, 0, 2147483647, 2147483647)
[2268382,344]  -> wl_surface@21.commit()
```
Looks like the client requests a context with alpha but doesn't actually support it, then draws the whole buffer with alpha = 0. Without pre-multiplied alpha the bright regions still appear opaque in sway, but the dark foreground text is transparent.

I don't know any Qt, but I searched the docs and the client author probably needs this https://doc.qt.io/qt-5/qsurfaceformat.html#setAlphaBufferSize to disable transparency in the client if it doesn't support it.

No idea why this wouldn't affect GNOME.

**Comment by Epse** [comment]
The author of sioyek as written some new shaders for me to test in the issue I opened there, I will report back with any changes and tell him your information if the issue persists. Thank you all for the investigation anyway

**Comment by RPigott** [comment]
If the client doesn't support alpha, it would be better to disable the alpha channel so the compositor can optimize this case. If your shaders draw an opaque window but you don't report an opaque region the compositor can't skip drawing the stuff behind it.

**Comment by emersion** [comment]
Yeah, pick an `EGLConfig` with `EGL_ALPHA_SIZE = 0` for instance.

**Comment by RPigott** [comment]
Right. I'm assuming Qt already does this on X but defaults to requesting a config with alpha on Wayland.

**Comment by Epse** [comment]
Just to keep people updated here, the new shader pack provided by the sioyek author resolves the issue, I assume by properly setting alpha to 1 everywhere

**Comment by Epse** [comment]
I'll close this issue as it is not really a sway issue (anymore), the help in debugging here has been very greatly appreciated
