### ISSUE TITLE
Resizing window without change top and left window's side.

### ISSUE THREAD

**Issue by ahmadraniri1994** [swaywm/sway#6554]
When I enter resize mode and press arrow keys, window is resized (usually for both left and right or top and bottom). I want to achieve when I resize a window via resize mode (use arrow keys), the left and top side stay on it's position or not changed (like hikari wm does). Any clue to achieve that? Thanks.

**Comment by emersion** [comment]
`resize grow bottom 10 px` should do it. Next time, please don't open a bug report, ask on IRC.

**Comment by ahmadraniri1994** [comment]
not work... no respond when I applied it.
