### ISSUE TITLE
swaywm.org down?

### ISSUE THREAD

**Issue by Parn23** [swaywm/sway#6557]
When I go to https://swaywm.org, it gives me the default GitHub Pages 404 page. Is this only on my side or is it global?

**Comment by emersion** [comment]
It's now hosted on SourceHut Pages. It loads fine for me, maybe just need to wait for DNS changes to propagate?

**Comment by emersion** [comment]
Please open an issue in https://github.com/swaywm/swaywm.org if you still have issues reaching the website.
