### ISSUE TITLE
Opening emacs while in fullscreen crashes the amdgpu driver

### ISSUE THREAD

**Issue by multun** [swaywm/sway#6558]
### Please fill out the following:
- **Versions:**
  - `Sway 1.6.1`
  - `NixOS 21.05`
  - `Linux 5.10.62`

- **Debug Log:**
  - sway: https://gist.github.com/multun/279bc169cc3ae1fc6c4754f762985751
  - kernel stack trace: https://gist.github.com/multun/7fb51343e1b33661ddbdbdb8b3be0804

- **Configuration File:**
  - **This crash does not happen with the default configuration file !!**
    I reduced my configuration until this single line was enough to reproduce this issue:
    `for_window [class=".*"] border pixel 2`

- **Description:**

With my sway configuration, if I open emacs using a keyboard shortcut while in fullscreen mode, one my my CPU threads hangs in the kernel, sway hangs, and my machine becomes pretty much unusable.

I believe sway does something weird, which makes the amdgpu driver crash.

```
echo 'for_window [class=".*"] border pixel 2' > config
echo 'exec xterm'
sway -c config

# in the terminal that just opened inside sway
swaymsg fullscreen
swaymsg exec emacs
```

**Comment by emersion** [comment]
Please report this to amdgpu: https://gitlab.freedesktop.org/drm/amd/
