### ISSUE TITLE
Use wlroots' scene-graph API

### ISSUE THREAD

**Issue by emersion** [swaywm/sway#6562]
I think the wlroots' scene-graph API is now powerful enough for Sway to use.

Here's how I think we can organize the scene-graph nodes for Sway. The main hurdle is painting the fullscreen views and popups in the correct order.

- Root
  - Output 1 (used to offset output coords)
    - Background and bottom layers
    - Workspace 1 (enabled because focused)
      - View container (used to offset container coords)
        - Borders (rects)
        - View 1
          - Main surface + subsurfaces
          - Saved buffers, if any
          - Decorations (border rects + titlebar buffer)
        - View 2
          - …
      - Popups container (used to offset container coords)
        - Popups for view 1
        - Popups for view 2
    - Workspace 2 (disabled because unfocused)
      - View
        - …
    - Top and overlay layers
  - Output 2
    - Background and bottom layers (disabled because there's a fullscreen view)
    - Workspace 3 (disabled because there's a fullscreen view)
    - Top layer (disabled because there's a fullscreen view)
    - Fullscreen view
      - …
    - Fullscreen popups
    - Overlay layer
  - Floating
    - View
      - …

**Comment by Xyene** [comment]
>   - Floating
    - View
      - …

Note that this isn't what i3 does. i3 has a stack of floating views _per output_, and when a view spans across another output, it'll either appear under all views of that output or over (depending on output order), but never in-between.

I'm personally in favor of not replicating this quirk when we move to the scene-graph API. It's a little janky and leads to bugs like https://github.com/swaywm/sway/issues/6073 (and likely others we haven't run into yet).
