### ISSUE TITLE
Move temporarily floated container back to original tiled position

### ISSUE THREAD

**Issue by siikamiika** [swaywm/sway#6573]
How to reproduce
1. Create a layout such as `H[1 2 3 V[4 5]]` or `T[1 2 3 4 5]`
1. `floating toggle` two times while focusing container `5`

Expected results (i3 behavior):
The layout stays the same

Actual results (in sway):
The layout becomes `V[H[1 2 3 V[4]] 5]` or `H[T[1 2 3 4] 5]`

This can also be reproduced by creating a new container belonging to the tiled layout when the floating container is focused.

----

Related issue: `focus mode_toggle` when focusing a floated container selects the entire tiled tree in sway instead of the container hinted by `client.focused_inactive` colors. If there are multiple such `focused_inactive` containers visible, i3 also focuses the previously active one and not the parent of everything like sway.

**Comment by RPigott** [comment]
Wasn't this resolved in #6175? You should really report your sway version in issues.

**Comment by siikamiika** [comment]
Sorry, I couldn't find anything related from issues when searching so I assumed this wasn't reported or noticed before. I'm running Arch build of sway 1.6.1 which seems to have been released after #6175 was merged, so I'm not sure if there was a regression or if that fix wasn't included in the release.

**Comment by siikamiika** [comment]
https://github.com/swaywm/sway/commit/a558866f42de74f7dc0500c3fe29bb506cf03cf6 seems to be only on master, so I'll test on it and close this issue. If there are any remaining issues, they're probably nothing similar to the original report.

**Comment by siikamiika** [comment]
Finally tested this and it seems to work great on master. Thanks for your work @RPigott

**Comment by siikamiika** [comment]
Reopening to track a few small fixes

**Comment by siikamiika** [comment]
Is there anything required from me to help with the review of the patches? So far I haven't noticed any issues using them.
