### ISSUE TITLE
[Feature request] Toggleable transparency for group of windows

### ISSUE THREAD

**Issue by rieje** [swaywm/sway#6574]
Currently, there doesn't seem to be any way to allow toggling transparency on/off for windows. You can set the value of a window's transparency, but there's not a way toggle them for a group of windows. It might be possible to script this if there's a way to get the transparency level of a window.

An example of toggling transparency of a focused window on/off:

    set $trans 0.8
    set $alphamark "α"
    for_window [con_mark=$alphamark] opacity set $trans
    bindsym $mod+Control+a mark --toggle "$alphamark" ; [con_id=__focused__] opacity set 1 ; [con_mark=$alphamark con_id=__focused__] opacity set $trans

But it is not possible to apply that to a group of windows. It is useful for example to bind to a single keybinding to toggle the transparency of all terminal windows, for instance (for improved readability when background color of terminal window might not pair well with the window or wallpaper behind it).

**Comment by emersion** [comment]
This can be done in a long-running script which remembers the last values it's set.

**Comment by rieje** [comment]
True, I use the following:

    opacity="0.8"
    file="/tmp/.sway-transparency-marker"

    if [ -f "$file" ]; then
      rm "$file" &&
      swaymsg '[title="^Alacritty$"]' opacity set 1
    else
      touch "$file" &&
      swaymsg '[title="^Alacritty$"]' opacity set "$opacity"
    fi

**Comment by RPigott** [comment]
> It is useful for example to bind to a single keybinding to toggle the transparency of all terminal windows

You can do this in sway with bindsym, since sway supports rebinding at runtime. A binding that toggle transparency on all terminal windows would be:

```
set $key $mod+x
set $alpha 0.9
set $alpha-on [app_id=$term] opacity $alpha; bindsym $key $$alpha-off
set $alpha-off [app_id=$term] opacity 1; bindsym $key $$alpha-on
bindsym $key $alpha-on
```

**Comment by rieje** [comment]
@RPigott This seems to work, but it affects existing windows only. This is expected and unavoided? E.g. on I open windows and they are opaque. The keybind then makes these windows transparent, but a new window that is opened is opaque until I toggle the keybind off and on again to apply to all existing windows.

**Comment by RPigott** [comment]
If you want to affect new windows, you need a for_window rule:

```
set $key $mod+x
set $alpha 1.0
set $alpha-on  [app_id=$term] opacity 0.9; bindsym $key $$alpha-off; set $$alpha 0.9
set $alpha-off [app_id=$term] opacity 1.0; bindsym $key $$alpha-on ; set $$alpha 1.0
bindsym $key $alpha-on
for_window [app_id=$term] opacity $$alpha
```
