### ISSUE TITLE
Add way to do keychords

### ISSUE THREAD

**Issue by rambip** [swaywm/sway#6576]
Hi come from Xmonad, and one thing I was able to do and almost worked was key combinations:
If I pressed windows+special key and then `fx`, that started firefox. Is there a way to do the same thing with sway ?
The expected behaviour would be to keep listening to incoming keys that match the keychord, until you open something or you stop listening yo the keys.

And if it is not possible, what wayland tool could I use to create arbitrary keymaps, that integrate well with sway ?

**Comment by emersion** [comment]
1. We aren't adding any more features like this one, we've decided to stick with i3.
2. Maybe a mode would be enough for you? See man page.
3. You can set any custom xkeyboard keymap. See the libxkbcommon docs.

**Comment by senkowo** [comment]
I implemented keychord-like functionality in Sway using something like this:
```conf
# Keymaps

set $main_map Launch: [c]application-map, [e]emacs
set $application_map Launch: [f]firefox, [p]keepassxc, [d]vencord, [s]spotify, [c]steam, [e]emacs, [r]renoise

bindsym $mod+c mode "$main_map"
	
mode "$main_map" {
    # note: don't change mode back to "default" after opening another mode/keymap
    bindsym c mode "$application_map"
    bindsym e exec emacsclient -a '' -c ; mode "default"
    
    bindsym Escape mode "default"
    bindsym Return mode "default"
    bindsym $ctrl+g mode "default"
}
     
mode "$application_map" {
    bindsym f exec firefox                         ; mode "default"
    bindsym p exec firejail keepassxc              ; mode "default"
    bindsym d exec flatpak run dev.vencord.Vesktop ; mode "default"
    bindsym s exec flatpak run com.spotify.Client  ; mode "default"
    bindsym c exec steam                           ; mode "default"
    bindsym e exec emacsclient -a '' -c            ; mode "default"
    bindsym r exec firejail renoise                ; mode "default"
    
    bindsym Escape mode "default"
    bindsym Return mode "default"
    bindsym $ctrl+g mode "default"
}
```
I'm sure there's a much better way of doing this but this works for me.

**Comment by anasouardini** [comment]
If you're lucky enough to get `Kanata` working.... you won't need keychords, layers, mods, etc in your WM.
It didn't work for me, in fact it made my `Sxhkd` not work anymore :laughing:, but, hey, you're using Wayland not X11

**Comment by LUKE-GG33** [comment]
> I implemented keychord-like functionality in Sway using something like this:
> 
> ```
> # Keymaps
> 
> set $main_map Launch: [c]application-map, [e]emacs
> set $application_map Launch: [f]firefox, [p]keepassxc, [d]vencord, [s]spotify, [c]steam, [e]emacs, [r]renoise
> 
> bindsym $mod+c mode "$main_map"
> 	
> mode "$main_map" {
>     # note: don't change mode back to "default" after opening another mode/keymap
>     bindsym c mode "$application_map"
>     bindsym e exec emacsclient -a '' -c ; mode "default"
>     
>     bindsym Escape mode "default"
>     bindsym Return mode "default"
>     bindsym $ctrl+g mode "default"
> }
>      
> mode "$application_map" {
>     bindsym f exec firefox                         ; mode "default"
>     bindsym p exec firejail keepassxc              ; mode "default"
>     bindsym d exec flatpak run dev.vencord.Vesktop ; mode "default"
>     bindsym s exec flatpak run com.spotify.Client  ; mode "default"
>     bindsym c exec steam                           ; mode "default"
>     bindsym e exec emacsclient -a '' -c            ; mode "default"
>     bindsym r exec firejail renoise                ; mode "default"
>     
>     bindsym Escape mode "default"
>     bindsym Return mode "default"
>     bindsym $ctrl+g mode "default"
> }
> ```
> 
> I'm sure there's a much better way of doing this but this works for me.

Thanks！
