### ISSUE TITLE
Mouse movement choppy when playing very demanding game like Cyberpunk2077 or Crysis Remastered

### ISSUE THREAD

**Issue by ErikReider** [swaywm/sway#6593]
### Please fill out the following:
- **Sway Version:**
  - `sway version 1.6-8aae6a8e (Oct  3 2021, branch 'master')`

- **Debug Log:**
  - https://gist.github.com/ErikReider/74625924b7bc805d082da4c589848ce1

- **Configuration File:**
  - Default config

- **Description:**
  - Launch Sway and Steam
  - Run Cyberpunk 2077
  - Set resolution to 2560x1440 borderless or fullscreen
  - Set graphics preset to High and texture quality to High
  - Load a save and start walking around while moving your mouse
  - Then run `sway exit` to return to tty

- **Hardware:**
```
System:    Host: Erik-Arch-Desktop Kernel: 5.14.9-zen2-1-zen x86_64 bits: 64 compiler: gcc v: 11.1.0
           Desktop: sway 1.6-8aae6a8e dm: GDM Distro: Arch Linux
CPU:       Info: 8-Core model: AMD Ryzen 7 5800X bits: 64 type: MT MCP arch: Zen 3 rev: 0 cache: L2: 4 MiB
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm bogomips: 121605
           Speed: 2234 MHz min/max: 2200/3800 MHz boost: enabled Core speeds (MHz): 1: 2234 2: 2231 3: 2223 4: 2224 5: 2234
           6: 2228 7: 2236 8: 2777 9: 2216 10: 2234 11: 2241 12: 2235 13: 2219 14: 2800 15: 2228 16: 2226
Graphics:  Device-1: Advanced Micro Devices [AMD/ATI] Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT] vendor: XFX Pine
           driver: amdgpu v: kernel bus-ID: 13:00.0 chip-ID: 1002:731f
           Device-2: Logitech HD Pro Webcam C920 type: USB driver: snd-usb-audio,uvcvideo bus-ID: 5-1:2 chip-ID: 046d:082d
           Display: wayland server: X.org 1.20.13 compositor: sway driver: loaded: modesetting alternate: ati,fbdev,vesa
           resolution: <missing: xdpyinfo>
           OpenGL: renderer: AMD Radeon RX 5700 XT (NAVI10 DRM 3.42.0 5.14.9-zen2-1-zen LLVM 12.0.1)
           v: 4.6 Mesa 21.3.0-devel (git-3e36a20a34) direct render: Yes
```

**Comment by ErikReider** [comment]
I'm also experiencing this issue with Gamescope which is also built upon wlroots? This should be a wlroots issue then right?

No issues playing on Gnome Wayland and x.Org but running the aforementioned games within Gamescope on Gnome also causes this issue

**Comment by WillPower3309** [comment]
Hey Erik! Does your panel have adaptive sync on? Possible duplicate of https://github.com/swaywm/sway/issues/6832

**Comment by ErikReider** [comment]
> Hey Erik! Does your panel have adaptive sync on? I suspect it's related to https://github.com/swaywm/sway/issues/6832

Hey Will! Haven't tried playing those games in a while but I'll check.

From what I can remember, the choppiness was horrible! As if someone was constantly disconnecting and reconnecting my mouse every 100ms

**Comment by ErikReider** [comment]
I've replaced my 5700XT with a newer GPU so can't test it on that GPU any more. Not experiencing any stutter on my 6800XT so I'll close this
