### ISSUE TITLE
Prevent cycling during focus up|down|left|right

### ISSUE THREAD

**Issue by I60R** [swaywm/sway#6596]
I rarely have more than two windows in workspace and it seems to be quite efficient to just press $mod+h or $mod+l in order to focus on what I want. But the current behavior also requires me to know what window is currently focused, since movements are only relative. In addition, sometimes I cannot notice that the window which I want is already focused and then I try to focus on it with aforementioned shortcut but the opposite happens — quite annoying.

Would you like to consider adding --nocycle option to `focus`? Should I also propagate this issue to i3 bug tracker?

**Comment by emersion** [comment]
Maybe `focus_wrapping` can help here?

**Comment by I60R** [comment]
Yes, exactly what I've needed, thank you!
