### ISSUE TITLE
Can't use max_render_time or adaptive_sync

### ISSUE THREAD

**Issue by Lahvuun** [swaywm/sway#6604]
**Sway Version:**
`sway version 1.6.1`

**Debug Log:**
https://gist.github.com/Lahvuun/8bf8668d2eabb7ee04771ff37e84ba65

**Configuration File:**
```
set $mod Mod4
set $term alacritty -e tmux attach
bindsym $mod+Shift+Return exec $term
```
**Description:**
Setting `max_render_time` or `adaptive_sync` with a command like `swaymsg output DP-3 max_render_time 10` often fails with the following errors in the log:
```
00:08:49.180 [ERROR] [wlr] [backend/drm/atomic.c:35] connector DP-3: Atomic commit failed (pageflip): Device or resource busy
00:08:49.180 [ERROR] [sway/config/output.c:417] Failed to commit output DP-3
```
This is not 100% consistent, every now and then the command will succeed.

A workaround I found is turning the display off and on with something like `swaymsg output DP-3 disable; sleep 1s; swaymsg output DP-3 enable`. Doing this temporarily fixes the issue, but after some time (around a few minutes?) trying to change `max_render_time` or `adaptive_sync` begins to fail again.

**Comment by Lahvuun** [comment]
I looked into this a bit more.

There is a similar issue on chromium's tracker: https://chromium-review.googlesource.com/c/chromium/src/+/2707457/

Of particular interest is the following message by Sean Paul:
> The kernel reserves the right to reject commits for any arbitrary reason, so in that sense it's not a kernel bug.
>
> EBUSY means the kernel flip queue (size=1) is full, so there's nowhere to store the commit. Userspace can either drop the frame or retry.

Now, from what I understand both `max_render_time` and `adaptive_sync` immediately try to do an atomic commit, and often times there already is one enqueued (is it the pageflips done by sway at 60fps?), so the commit fails with EBUSY.

I also found a couple similar issues on the wlroots tracker: https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/2239 and https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/2492#note_1140895

---

@emersion sorry for the ping but I'd like to know if this is sway incorrectly using wlroots, or an issue with wlroots itself. If it is the latter, should I close this issue and open a new one on the wlroots tracker? Or maybe there already is an open issue?

Also, inspired by the chromium patch I came up with the following patch for wlroots to retry with a blocking commit:
```diff
diff --git a/backend/drm/atomic.c b/backend/drm/atomic.c
index 70f55aff..872f047f 100644
--- a/backend/drm/atomic.c
+++ b/backend/drm/atomic.c
@@ -36,7 +36,17 @@ static bool atomic_commit(struct atomic *atom,
                        "Atomic %s failed (%s)",
                        (flags & DRM_MODE_ATOMIC_TEST_ONLY) ? "test" : "commit",
                        (flags & DRM_MODE_ATOMIC_ALLOW_MODESET) ? "modeset" : "pageflip");
-               return false;
+
+               flags &= ~DRM_MODE_ATOMIC_NONBLOCK;
+               ret = drmModeAtomicCommit(drm->fd, atom->req, flags, drm);
+               if (ret != 0) {
+                       wlr_drm_conn_log_errno(conn,
+                               (flags & DRM_MODE_ATOMIC_TEST_ONLY) ? WLR_DEBUG : WLR_ERROR,
+                               "Atomic %s failed (%s)",
+                               (flags & DRM_MODE_ATOMIC_TEST_ONLY) ? "test" : "commit",
+                               (flags & DRM_MODE_ATOMIC_ALLOW_MODESET) ? "modeset" : "pageflip");
+                       return false;
+               }
        }

        return true;
```
It solves the problem, but as I understand you have a good reason to make the commit non-blocking.

If you have better things to do than fixing this, I can try to make a patch if you outline how you want it done. For example, instead of immediately doing a commit, `adaptive_sync` could set a flag that would then be used to set `crtc->props.vrr_enabled` when doing the next commit.

**Comment by emersion** [comment]
I think this is a wlroots bug. It shouldn't use `DRM_MODE_ATOMIC_NONBLOCK` when switching `vrr_enabled`.

**Comment by Lahvuun** [comment]
OK. Do you want me to open a new issue at https://gitlab.freedesktop.org/wlroots/wlroots/-/issues? This isn't a bug in sway, but you didn't close this issue, so I'm not sure what to do.
