### ISSUE TITLE
Support Wayland backend with software rendering

### ISSUE THREAD

**Issue by DemiMarie** [swaywm/sway#6613]
The Wayland backend doesn’t support software rendering.  This makes testing in virtualized environments with no GPU unnecessarily difficult.

**Comment by bl4ckb0ne** [comment]
It does, use `WLR_RENDERER=pixman` when launching sway.

https://github.com/swaywm/wlroots/blob/master/docs/env_vars.md#wlroots-specific

**Comment by DemiMarie** [comment]
That must have been a newer addition, since the Sway from Fedora 34’s repository doesn’t have it.
