### ISSUE TITLE
There is no way to let Sway start if nvidia proprietary module is loaded, even if it's used just for compute

### ISSUE THREAD

**Issue by pshirshov** [swaywm/sway#6624]
Currently Sway rejects to start in case it detects nvidia proprietary driver loaded, even if the only loaded module is `nvidia` and Nvidia GPU is used only for compute purposes while KMS uses simultaneously loaded amdgpu. This happens even in case a headless Nvidia GPU (e.g. A10/A100) is present in the system.

Also it doesn't help if I specify the GPU I want to use with `WL_DRM_DEVICES`.

All other compositors happily start in such configuration and use just amdgpu, but for some reason Sway doesn't.

See also: https://github.com/swaywm/sway/issues/6623 - I've tried to use PRIME (amdgpu+nvidia proprietary drivers) to workaround this problem, but that attempt failed too.

Maybe it's a good idea to let user specify which GPUs should be ignored?

**Comment by pshirshov** [comment]
The answer is kinda non sequitur. I'm not saying anything about proprietary driver support, I'm saying that Sway rejects to work when proprietary driver is present in the system even in the situations when the environment is specifically configured to avoid any use of the proprietary driver by graphical apps `--unsupported-gpu` flag doesn't help, Sway just ignores it.

**Comment by bl4ckb0ne** [comment]
Could you provide the full debug logs please? And which sway/wlroots version are you using?

`--unsupported-gpu` was introduced in https://github.com/swaywm/sway/commit/b48cb6b0ec1320ad25fd2c0a1b5118dbe2536060, before that the flag was named `--my-next-gpu-wont-be-nvidia`

Proprietary driver detection always runs, and will fail even if the module is loaded and not in use.
https://github.com/swaywm/sway/blob/master/sway/main.c#L50

**Comment by lilydjwg** [comment]
Got bitten by this today. It surprises me that nvidia can harm users by simply being present...

**Comment by emersion** [comment]
https://github.com/swaywm/sway/pull/7861 should help.

**Comment by bl4ckb0ne** [comment]
@lilydjwg it doesnt harm users, its mostly about not being able to debug issues when it fails. With the open source driver we can just go look at the code and identify if it's a driver issue or a wlroots issue. With prioprietary drivers we can do jack.

So we chose this option to tell the user that we can't and won't provide support.
