### ISSUE TITLE
Configure event with wrong size is sent after a floating window resizes itself

### ISSUE THREAD

**Issue by giucam** [swaywm/sway#6625]
After a client resizes a floating window, by just submitting a new frame, without the user resizing the window, when exiting/entering the window with the mouse a configure event is sent with the old size.
What happens is that after the new buffer is committed there is no wlr_xdg_toplevel_set_size() called with the new size, so when some state on the window changes, like activation state, a configure event is sent with the old size.

On https://gist.github.com/giucam/dd938c4bb4c6f6008b48275b2f2a21cf there is a Qt test client that shows the issue. Compile it with `g++ test.cpp -I /usr/include/qt/QtGui/ -I /usr/include/qt/QtCore/ -I /usr/include/qt -I /usr/include/qt/QtWidgets/ -fPIC -lQt5Gui -lQt5Core -lQt5Widgets`

**Comment by emersion** [comment]
I believe this is fixed now.
