### ISSUE TITLE
`grayscale` in addition to `opacity`

### ISSUE THREAD

**Issue by I60R** [swaywm/sway#6632]
I have a border-less setup that relies on `inactive-windows-transparency.py` in order to distinguish the focused window. It kind of works but occasionally something still attracts my attention to the unfocused window.

And now I figured out what: it's the bright and shiny neon wallpaper which appears at the top plane and makes the transparent area more bright thus the focused window grim and uninteresting. Moreover, sometimes unfocused window may contain colorful items while focused remain empty, and it worsens when focused window also has some transparency (e.g. terminal emulator). 

So, the first thought was that blur effect could be applied in order to make unfocused windows more obscure but after some lurking over Github issues it became clear that blur wouldn't be available, at least in the near future.

Making unfocused windows less transparent isn't an option, since already the contrast between focused and unfocused windows is too low (0.77 opacity) and swapping the wallpaper isn't possible either because I like it!

Thus `opacity` alone isn't enough, so I propose to add `grayscale` to complement it. Something like that doesn't seem to be a big maintenance burden and there could be other applications e.g. to implement a "night mode" or just dim the browser with timeout in order to prevent using it for too long. Although, I'm not sure whether it would be enough or next enhancements in form of `brightness` and `contrast` would be required in order to achieve the perfect result.

**Comment by rbozan** [comment]
I'd love to have a grayscale option. I am currently just using i3 just for that reason alone, that I can always change the display to grayscale with ease.

**Comment by I60R** [comment]
An interesting thought come into my mind: in tiling WM applying blur, grayscale etc. effects to window background isn't really necessary, at least in my use case it's completely useless. Instead it would be just enough to apply them to wallpaper when workspace contains more than one window, and the rest could be achieved with setting opacity.

Effects could be applied to the whole wallpaper or there could be some daemon that listens to workspace updates and depending on geometry of windows applies them to only specific regions. The single drawback of this approach is that effects other than opacity wouldn't be applied on floating windows when they're positioned on top of other windows...

But anyway it's a tiling WM and using floating windows especially with opacity is very uncommon (I have that applied for Picture-in-Picture windows, through, it doesn't seem to be critical to have effects behind them). Maybe even not applying effects here might become a quite interesting behavior on its own.

This should be better performance-wise, configuration-wise and as far as I understand it shouldn't require any shader changes in renderer. Also, because `opacity` alone doesn't work well with some wallpapers I don't think that this feature request is about eye-candiness at all but rather about feature-completeness of Sway and comfort of using it

**Comment by WillPower3309** [comment]
> An interesting thought come into my mind: in tiling WM applying blur, grayscale etc. effects to window background isn't really necessary, at least in my use case it's completely useless. Instead it would be just enough to apply them to wallpaper when workspace contains more than one window, and the rest could be achieved with setting opacity.
> 
> Effects could be applied to the whole wallpaper or there could be some daemon that listens to workspace updates and depending on geometry of windows applies them to only specific regions. The single drawback of this approach is that effects other than opacity wouldn't be applied on floating windows when they're positioned on top of other windows...
> 
> But anyway it's a tiling WM and using floating windows especially with opacity is very uncommon (I have that applied for Picture-in-Picture windows, through, it doesn't seem to be critical to have effects behind them). Maybe even not applying effects here might become a quite interesting behavior on its own.
> 
> This should be better performance-wise, configuration-wise and as far as I understand it shouldn't require any shader changes in renderer. Also, because `opacity` alone doesn't work well with some wallpapers I don't think that this feature request is about eye-candiness at all but rather about feature-completeness of Sway and comfort of using it

psst, shameless self plug to my "just needs to be packaged" (swayblur)[https://github.com/WillPower3309/swayblur] :)

**Comment by I60R** [comment]
@WillPower3309 thank you, the concept works even better than I expected and I really like the animations!

And from commits it looks like you've implemented it just a day earlier before I've posted my previous comment, what a coincidence!

**Comment by WillPower3309** [comment]
> @WillPower3309 thank you, the concept works even better than I expected and I really like the animations!
> 
> And from commits it looks like you've implemented it just a day earlier before I've posted my previous comment, what a coincidence!

No problem, I was thinking the same thing! I'm going to fix this as soon as I can but one caveat right now is that if you change your wallpaper and want to generate new blurred versions of it you'll need to remove `~/.cache/swayblur`

**Comment by I60R** [comment]
Yes, I've figured it out and just filled some issues in your repo. Maybe I will help to fix that, however, due to my lack of experience with Python don't promise anything
