### ISSUE TITLE
Sway kills all workspaces when outputs are reconnected / reconfigured

### ISSUE THREAD

**Issue by luispabon** [swaywm/sway#6640]
### Please fill out the following:
- **Sway Version:** e76e13ef and aaf68cf4 (latest master).
```
~ sway --version
sway version 1.6-aaf68cf4 (Oct 27 2021, branch 'master')
```

- **Debug Log:**
https://gist.github.com/luispabon/041ea2fe2ddeec7e9e9013c98949d085

Session: start sway, do some stuff, go idle, swayidle kicks in and starts swaylock, then it eventually turns off the displays. Weirdness happens upon re-activating those displays. Swaylock is killed as well so I go straight into sway bypassing it.

- **Configuration File:**
https://github.com/luispabon/sway-dotfiles/tree/master/configs/sway

I'll try to reproduce with the default config

- **Stack Trace:**
Sway does not crash to greeter or tty

- **Description:**
My setup is a laptop with a 4k display, scale 2, and 2 further displays (scale 1 each) via a thunderbolt dock.

Since I upgraded to Ubuntu 21.10, sway keeps seemingly killing all workspaces and the apps inside, including Waybar, on situations where displays were re-connected. For instance, after resuming from sleep, I'll be greeted by sway with all apps killed (eg I can only see the background image, all apps I had open aren't running. I can start new apps from sway though). Even swaylock dies, leaving the laptop unlocked.

Sometimes this also happens when displays are eventually turned off via swayidle due to inactivity.

Sometimes this happens when re-configuring my outputs. For instance, after resuming from sleep [kanshi will die every now and then](https://github.com/emersion/kanshi/issues/99) leaving my displays on but with the wrong layout, and when I restart kanshi manually, the issue will present itself as well.

I have reverted back to the version of sway and wlroots I had prior to upgrading to Ubuntu 21.10 and the issue seemingly still happens. The debug log above is from that session.

**Comment by luispabon** [comment]
I haven't been able to reproduce this error since I built sway and wlroots with ASAN for a different issue. I won't pretend I know what that is.

**Comment by WhyNotHugo** [comment]
Possibly #6629? I had this issue a few times and that PR fixed it for me.

Can you try reproducing with and without it?

**Comment by luispabon** [comment]
Thank you @WhyNotHugo

The version I'm at indeed has 38020d157d (I'm on fc25e494).

I'll revert back to the commit just before and see if the issue comes back.

**Comment by luispabon** [comment]
Well, I haven't been able to reproduce the issue anymore, before or after 38020d1.

I'm inclined to think the issue was elsewhere in the system and some update got rid of it.

Closing this. Thank you all.
