### ISSUE TITLE
Vulkan renderer causes sway to become unable to take screenshots

### ISSUE THREAD

**Issue by Kommynct** [swaywm/sway#6646]
I don't know what to include but when I try to use grim -g "$(slurp -b 00000000 -s cc000090 -w 0)" for example on the latest master on arch with AMDGPU with WLR_RENDERER=vulkan

the only output I get is:

failed to copy output DP-1

I also have swaylock effects setup with the screenshot option, it also doesn't work.

**Comment by bl4ckb0ne** [comment]
Duplicate of https://github.com/swaywm/wlroots/issues/3290

**Comment by Kommynct** [comment]
My bad searched wrong thanks!
