### ISSUE TITLE
Google Chrome looks strange

### ISSUE THREAD

**Issue by 532910** [swaywm/sway#6647]
sway 1.6 from debian experimental

With an empty config:
```
% cat .config/sway/config
xwayland disable
bindsym --to-code Mod1+F2 exec wofi --show=drun --allow-images --columns=4 --width=70% --height=70%
```

![20211030_19h36m54s_grim](https://user-images.githubusercontent.com/14617699/139541765-1c8f7274-fe89-4f69-b91c-14b46273cf1a.png)

With my config:
![image](https://user-images.githubusercontent.com/14617699/139541308-928c5ec5-f567-4f6e-b7ad-5b189654004f.png)

```
(19:49:52)[sergio@disaster:~]% apt policy google-chrome-stable 
google-chrome-stable:
  Installed: 95.0.4638.69-1
  Candidate: 95.0.4638.69-1
  Version table:
 *** 95.0.4638.69-1 500
        500 https://dl.google.com/linux/chrome/deb stable/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by markstos** [comment]
Could you update the title to be more specific? By "strange" are you referring to some pixels on the right and bottom sides apparently being cut off?

**Comment by 532910** [comment]
Could you suggest something more specific?

**Comment by junglerobba** [comment]
If it's about the window being cut off, that appears to be a chrome bug, happens the same on gnome.

**Comment by bl4ckb0ne** [comment]
Closing since it's a chrome bug. Feel free to reopen if you can provide a debug log indicating this is a sway issue.

**Comment by 532910** [comment]
> happens the same on gnome

@junglerobba, could you provide a link.


> Closing since it's a chrome bug

@bl4ckb0ne, could you provide a proof.


Google Chrome looks fine under weston, please reopen.

**Comment by junglerobba** [comment]
Here's a screenshot of how it looks on gnome, with the chrome window maximized. Though in this case it simply shows the cut off part on my second monitor, but it looks like the same issue to me. 

![image](https://user-images.githubusercontent.com/18437660/140664587-00c9f3ef-5484-4a80-882b-cacc47e81c43.png)

**Comment by 532910** [comment]
It looks fine in weston and plasma using the ozone wayland platform, please reopen.
