### ISSUE TITLE
Start to support nvidia proprietary driver please

### ISSUE THREAD

**Issue by safocl** [swaywm/sway#6650]
i have gtx 1650 and 495 proprietary driver that support for GBM now, but SWAY don't start.

please turn off this the bad code sample on https://github.com/swaywm/sway/blob/38020d157ddb58e756c654e9a2ff203c1562b25b/sway/main.c#L52

**Comment by RPigott** [comment]
You can use `--unsupported-gpu` to ignore the check.

**Comment by safocl** [comment]
> You can use `--unsupported-gpu` to ignore the check.

i start under xorg server
```
--> sway --unsupported-gpu
00:00:00.003 [sway/main.c:97] !!! Proprietary Nvidia drivers are in use !!!
00:00:00.004 [wlr] [backend/x11/backend.c:608] Failed to query DRI3 DRM FD
00:00:00.004 [sway/server.c:53] Unable to create backend
```

**Comment by emersion** [comment]
Proprietary drivers are unsupported. Don't open issues if you're using them.

**Comment by safocl** [comment]
> Proprietary drivers are unsupported. Don't open issues if you're using them.

this feature was before the nvidia driver supported GBM

**Comment by safocl** [comment]
i started sway with nvidia proprietary driver from sddm for "sway --unsupported-gpu" command line changed in sway.desktop file.
ok...
