### ISSUE TITLE
Blank screen when started from lightdm with libseat 0.6.3

### ISSUE THREAD

**Issue by wouterh** [swaywm/sway#6655]
- **Sway Version:** 1.6.1
- **Debug Log:** See https://gist.github.com/wouterh/88306fffe6090d0ea7cf2ed2d1e83ddb
- **Configuration File:** reproducible with default configuration in arch linux (see the gist above)
- **Description:**
  - Start sway from lightdm 1.30.0 with libseat 0.6.3 installed (see `sway.desktop` in the gist above)
  - sway starts but the screen is blank
- **Additional info:**
  - Starting sway from a TTY with libseat 0.6.3 installed works
  - Starting sway from lightdm with libseat 0.6.2 installed works
  - Might be a libseat bug instead?
  - Found somebody else with the same problem: https://github.com/void-linux/void-packages/issues/33758

**Comment by pjanx** [comment]
I confirm that downgrading libseat improves the situation, although Sway only started on the second try, on the first one I got:
```
00:00:00.305 [ERROR] [wlr] [backend/libinput/backend.c:116] libinput initialization failed, no input devices
00:00:00.305 [ERROR] [wlr] [backend/libinput/backend.c:117] Set WLR_LIBINPUT_NO_DEVICES=1 to suppress this check
00:00:00.306 [ERROR] [wlr] [backend/multi/backend.c:32] Failed to initialize backend.
00:00:00.306 [ERROR] [sway/server.c:244] Failed to start backend                 
```

**Comment by emersion** [comment]
The OP's issue is:

```
00:00:07.746 [ERROR] [wlr] [backend/drm/atomic.c:35] connector eDP-1: Atomic commit failed (modeset): Permission denied
00:00:07.746 [INFO] [wlr] [libseat] [libseat/backend/logind.c:375] Disabling seat
00:00:07.746 [INFO] [wlr] [backend/drm/backend.c:134] DRM fd paused
```

@pjanx, your issue seems different.

> Start sway from lightdm

Sorry, but DM are not supported, exactly because they cause these kind of issues. Closing.

**Comment by pjanx** [comment]
I can have two issues.
