### ISSUE TITLE
Crash in Arch Linux with noveau when dragging windows around

### ISSUE THREAD

**Issue by greenlucid** [swaywm/sway#6669]
- **Sway Version:**
1.6.1

- **Debug Log:**
 https://gist.github.com/greenlucid/49709a2ba6ac106a1393f425307f73e7

- **Configuration File:**
  - https://gist.github.com/greenlucid/be2fdf65d03a149a10d7135dd5adc894
  - Only differences are Spanish keyboard and a mod command on Super + Q. Crashes never happened when running the command.

- **Stack Trace:**
  - Somehow, it didn't register as a crash on `coredumpctl`

- **Description:**
  - Made in roughly 30s. Happened when dragging a window around with Super + Maintained mouse click, moved it pretty fast and it crashed. I've had 3 crashes before today, my system may be unstable. But they've  always happened when interacting with Sway in a meaningful way

**Comment by emersion** [comment]
This is a nouveau bug, please report it to Mesa.
