### ISSUE TITLE
Sway SEGFAULT on VT switch

### ISSUE THREAD

**Issue by andraxin** [swaywm/sway#6684]
### Please fill out the following:
- **Sway Version:**
  - `sway version 1.6.1` running on Gentoo (OpenRC; i.e. **not** `systemd`) using `seatd`

- **Debug Log:**
  - Attached as [sway.log](https://github.com/swaywm/sway/files/7591273/sway.log)

- **Configuration File:**
  - default configuration (essentially) <details><summary>diff</summary>
      ```diff
      --- sway-1.6.1/config.in        2021-06-24 18:26:29.000000000 +0200
      +++ /etc/sway/config    2021-11-23 22:46:46.327985727 +0100
      @@ -22,8 +22,8 @@
       
       ### Output configuration
       #
      -# Default wallpaper (more resolutions are available in @datadir@/backgrounds/sway/)
      -output * bg @datadir@/backgrounds/sway/Sway_Wallpaper_Blue_1920x1080.png fill
      +# Default wallpaper (more resolutions are available in /usr/share/backgrounds/sway/)
      +#output * bg /usr/share/backgrounds/sway/Sway_Wallpaper_Blue_1920x1080.png fill
       #
       # Example configuration:
       #
      @@ -214,4 +214,4 @@
           }
       }
       
      -include @sysconfdir@/sway/config.d/*
      +include /etc/sway/config.d/*
      ```
      </details>

- **Stack Trace:**
  - If this is needed, I'll recompile and produce a trace.
  - My current guess based on the logs is that issue _may_ be simple enough not to require a trace.

- **Description:**
  - Started Sway on VT#2 and eventually switched to VT#1 with `Ctrl+Alt+F1`.
    - For the minimal reproduction, I switched as soon as Sway has loaded
  - Upon switching back to VT#2 with `Ctrl+Alt+F2`, found a SEGFAULT; no Sway... 
    ```console
    user@host ~ $ WLR_DRM_DEVICES=/dev/dri/card1 sway -d 2> sway.log
    Segmentation fault
    user@host ~ $
    ```

**Comment by emersion** [comment]
> My current guess based on the logs is that issue may be simple enough not to require a trace.

Nope, needs a trace.

**Comment by andraxin** [comment]
> > My current guess based on the logs is that issue may be simple enough not to require a trace.
> 
> Nope, needs a trace.

Actually, it doesn't.  As I suspected, this turned out to be more of a `seatd` bug.
This issue disappears when using ` seatd`'s "live ebuild" (built from current main branch).
