### ISSUE TITLE
Focusing (wayland) signal-desktop after some time crashes Sway

### ISSUE THREAD

**Issue by pescepalla** [swaywm/sway#6685]
### Please fill out the following:
- **Sway Version:** 1.6.1

- **Debug Log:**
This bug happens after hours of activity but it is fairly consistent.

- **Configuration File:**
default

- **Stack Trace:**
`coredumpctl gdb sway` results in "No match found" but Sway does crash (or at least log out unexpectedly).

- **Description:**
 Run `signal-desktop --enable-features=UseOzonePlatform --ozone-platform=wayland` for some time (it could be minutes or hours). Switching to it may lead to Sway exiting unexpectedly. This doesn't happen if it is run in Xwayland mode.

**Comment by bl4ckb0ne** [comment]
We're going to need more data to identify the bug. Please provide a full debug log and a stacktrace if possible. 

See [1] to configure `coredumpctl`.

[1]: https://wiki.archlinux.org/title/Core_dump

**Comment by pescepalla** [comment]
Here's the log from `sway -d 2> sway-log.txt`
[sway-log.txt](https://github.com/swaywm/sway/files/7602555/sway-log.txt)

It's long as the crash happened approx. after 2 hours' activity.

I still cannot produce a coredump.

**Comment by bl4ckb0ne** [comment]
> i965: Failed to submit batchbuffer: Bad address

Might be a mesa issue, very hard to tell without stacktrace.

**Comment by emersion** [comment]
Ah, yes, "Failed to submit batchbuffer" errors are Mesa bugs. Please open a Mesa bug report.

**Comment by pescepalla** [comment]
For reference: https://gitlab.freedesktop.org/mesa/mesa/-/issues/5683
