### ISSUE TITLE
Close edges of monitors for cursor

### ISSUE THREAD

**Issue by rustzz** [swaywm/sway#6691]
I want the mouse not to pop out to another monitor when it reaches the edge of the first monitor. How to set it up?

**Comment by fluix-dev** [comment]
IIRC, you can try positioning the outputs with a 1px gap between them (ie. if you have one monitor at `0, 0` and another at `1920, 0`, place the second one at `1921, 0`).

**Comment by rustzz** [comment]
after changing the position of the screen, the mouse moving away from the other side

**Comment by fluix-dev** [comment]
> the mouse moving away from the other side

I don't understand. What do you mean?

**Comment by rustzz** [comment]
ok, i'm closes issue
