### ISSUE TITLE
$mod+s types "s" first, then runs binded command

### ISSUE THREAD

**Issue by PowerMan2206** [swaywm/sway#6699]
sway version: 1.6.1
wlroots version: 0.14.1

configuration file: https://raw.githubusercontent.com/PowerMan2206/dots/master/.config/sway/config
also binds: https://raw.githubusercontent.com/PowerMan2206/dots/master/.config/sway/binds
also script: https://raw.githubusercontent.com/PowerMan2206/dots/master/.local/bin/screenshot

Basically I set $mod+s to run a screenshot script I made. The thing is that before taking a screenshot, it sends out an `s`, like this:
![2021-12-04_21:09:33](https://user-images.githubusercontent.com/61635519/144723228-368f1938-5825-46e9-aa46-6c9d3df220ae.png)

It doesn't happen when opening stuff like qutebrowser/Thunar/bemenu/etc. Is this an issue in Sway or my script? 'Cause I admit, it's kinda funky...

**Comment by RPigott** [comment]
You have it bound to the release:

```
# screenshot stuff
bindsym --release $mod+s exec screenshot area #select area
bindsym --release $mod+Shift+s exec screenshot window #focused window
```

You need to bind the keypress if you want it masked from applications.

**Comment by PowerMan2206** [comment]
Hm, then I can accidentally spam it by holding it down... I guess I can add a lockfile. Thanks

**Comment by RPigott** [comment]
Use the --no-repeat flag.
