### ISSUE TITLE
Black screen when trying to set a custom resolution

### ISSUE THREAD

**Issue by nonij59242** [swaywm/sway#6711]
- **Sway Version:**
  1.6.1

- **Debug Log:**
  https://pastebin.com/SL0mvfH4

- **Configuration File:**
 ```
set $mod Mod1
set $term kitty
bindsym $mod+Return exec $term
```

- **Description:**

My laptop only lists the following available modes:
```Output eDP-1 'Unknown 0x408D 0x00000000' (focused)
  Current mode: 1920x1080 @ 60.049 Hz
  Position: 200,1080
  Scale factor: 1.250000
  Scale filter: linear
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 1
  Max render time: off
  Adaptive sync: disabled
  Available modes:
    640x480 @ 60.049 Hz
    800x600 @ 60.049 Hz
    1024x768 @ 60.049 Hz
    1280x720 @ 60.049 Hz
    1280x800 @ 60.049 Hz
    1440x900 @ 60.049 Hz
    1280x1024 @ 60.049 Hz
    1680x1050 @ 60.049 Hz
    1920x1080 @ 60.049 Hz
```
    
It is a small 13-inch screen. Therefore, I would like to use a lower resolution so that everything is readable and I do not have to use fractional scaling.

Since none of the available modes (aside from 1280x720 which is a bit too low) are 16x9, I tried to set a custom resolution:
`swaymsg -- output eDP-1 mode --custom 1366x768`
or
`swaymsg -- output eDP-1 mode --custom 1600x900`

Unfortunately, this leads to a black screen. Trying to add corresponding refresh rates (e.g. `@60Hz`) does not seem to work either. I would like to use a custom resolution that is not listed above. I have tried searching for related issues and came across  #5619, but unfortunately, I think this issue here is slightly different as the custom mode I want to set is not listed in the available modes (hence `--custom`).
I have used a very basic config in order to reproduce this without a complex config.

Please let me know if there is any additionaly information that I could or should provide (I have uploaded the `sway.log` to pastebin as seen above) in order to get to the bottom of this.

**Comment by Emantor** [comment]
While we allow setting custom modes, there is no guarantee that the display will actually support the most. This could very well be a limitation of your panel not supporting your desired resolution. Does this work with Xorg/Weston?

**Comment by nonij59242** [comment]
You are right, it does not work under Xorg either (tried using XFCE).

I tried something else though aswell. I tried setting the desired resolution in Windows, and there it works, so somehow the display is not outright incabable of handling this resolution (as would be the suggestion by the black screen in both sway and XFCE)?

**Comment by Emantor** [comment]
Interesting. Windows could very well be rendering to a 1366x768 framebuffer that is scaled to the native resolution of 1920x1080. Anyhow, this is all just speculation since we can't look at the code.

**Comment by nonij59242** [comment]
Fair enough. I guess 1920x1080 and a 1.25 (or similiar) fractional scaling is the only solution for my use case for now.
Thank you for your answers! I think this can be closed then.
