### ISSUE TITLE
imv segfaults because wl_output is NULL

### ISSUE THREAD

**Issue by primalmotion** [swaywm/sway#6713]
- Sway Version: master 

I have opened an issue against imv (https://todo.sr.ht/~exec64/imv/1), but now I believe this is a breaking change from sway that may not be intentional.

With latest wlroots (1c3e0816) and latest sway (57a7b39), imv segfaults:

```
listener function for opcode 4 of wl_output is NULL
[1]    347009 abort (core dumped)  imv Downloads/screenshot-2021-12-13-19:58:23.png
```

I have reverted to wlroots (1fbd13ec) and sway (1eaa61f5) and then imv works perfectly fine. 

I noticed a change just after these commits related to output names, and this error seems awfully close to the subject of this change.

I would be glad to provide additional information if you need to.

**Comment by emersion** [comment]
Nope, that's a client bug. imv shouldn't be binding to the latest version supported by the compositor, it should be binding to the latest version it supports itself.

**Comment by primalmotion** [comment]
imv is fixed. Thanks!
