### ISSUE TITLE
Firefox not starting with wayland on Fedora 35

### ISSUE THREAD

**Issue by flipflop133** [swaywm/sway#6714]
- **Sway Version:**
1.6.1

- **Description:**
  - Firefox launch with wayland when using gnome but when I switch to sway, it won't launch under wayland, it falls back to xwayland.
  - I tried running it with `MOZ_ENABLE_WAYLAND=1 firefox` but it doesn't work either.

- **Sway config file:**
https://github.com/flipflop133/dotfiles/blob/main/sway/.config/sway/config
- **Dotfiles:**
https://github.com/flipflop133/dotfiles

**Comment by emersion** [comment]
Missing debug log

**Comment by flipflop133** [comment]
{
  "application": {
    "name": "Firefox",
    "osVersion": "Linux 5.15.6-200.fc35.x86_64 #1 SMP Wed Dec 1 13:41:10 UTC 2021",
    "version": "95.0",
    "buildID": "20211206150432",
    "distributionID": "fedora",
    "userAgent": "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0",
    "safeMode": true,
    "supportURL": "https://support.mozilla.org/1/firefox/95.0/Linux/en-US/",
    "osTheme": "Adwaita / Adwaita",
    "numTotalWindows": 1,
    "numFissionWindows": 0,
    "numRemoteWindows": 1,
    "fissionAutoStart": false,
    "fissionDecisionStatus": "disabledBySafeMode",
    "remoteAutoStart": true,
    "policiesStatus": 0,
    "keyLocationServiceGoogleFound": true,
    "keySafebrowsingGoogleFound": true,
    "keyMozillaFound": true
  },
  "securitySoftware": {
    "registeredAntiVirus": "",
    "registeredAntiSpyware": "",
    "registeredFirewall": ""
  },
  "processes": {
    "remoteTypes": {
      "privilegedabout": 1,
      "extension": 1,
      "prealloc": 1
    },
    "maxWebContentProcesses": 8
  },
  "environmentVariables": {
    "MOZ_GRE_CONF": "/etc/gre.d/gre64.conf",
    "MOZ_DBUS_REMOTE": "1",
    "MOZ_ALLOW_DOWNGRADE": "1",
    "MOZ_GMP_PATH": "/usr/lib64/mozilla/plugins/gmp-gmpopenh264/system-installed",
    "MOZ_APP_LAUNCHER": "/usr/bin/firefox",
    "DISPLAY": ":0",
    "MOZ_USE_XINPUT2": "1",
    "MOZ_PLUGIN_PATH": "/usr/lib64/mozilla/plugins:/usr/lib64/firefox/plugins",
    "MOZ_ASSUME_USER_NS": "1",
    "MOZ_CRASHREPORTER_EVENTS_DIRECTORY": "/home/francoisbechet/.mozilla/firefox/fcd06wen.default-release/crashes/events",
    "MOZ_CRASHREPORTER_RESTART_ARG_0": "/usr/bin/firefox",
    "MOZ_CRASHREPORTER_RESTART_ARG_1": "",
    "MOZ_CRASHREPORTER_DATA_DIRECTORY": "/home/francoisbechet/.mozilla/firefox/Crash Reports",
    "MOZ_CRASHREPORTER_PING_DIRECTORY": "/home/francoisbechet/.mozilla/firefox/Pending Pings",
    "MOZ_CRASHREPORTER_STRINGS_OVERRIDE": "/usr/lib64/firefox/browser/crashreporter-override.ini",
    "MOZ_LAUNCHED_CHILD": "",
    "MOZ_APP_SILENT_START": "",
    "XRE_PROFILE_PATH": "",
    "XRE_PROFILE_LOCAL_PATH": "",
    "XRE_START_OFFLINE": "",
    "XRE_BINARY_PATH": "",
    "XRE_RESTARTED_BY_PROFILE_MANAGER": "",
    "MOZ_SAFE_MODE_RESTART": "",
    "MOZ_APP_RESTART": "1"
  },
  "modifiedPreferences": {
    "accessibility.typeaheadfind.flashBar": 0,
    "browser.contentblocking.category": "standard",
    "browser.search.region": "BE",
    "browser.sessionstore.upgradeBackup.latestBuildID": "20211206150432",
    "browser.startup.homepage_override.buildID": "20211206150432",
    "browser.startup.homepage_override.mstone": "95.0",
    "browser.urlbar.placeholderName": "Google",
    "browser.urlbar.quicksuggest.migrationVersion": 1,
    "browser.urlbar.quicksuggest.scenario": "history",
    "doh-rollout.balrog-migration-done": true,
    "doh-rollout.doneFirstRun": true,
    "doh-rollout.home-region": "BE",
    "dom.push.userAgentID": "8d9842bfcc064e00bf276e128945e543",
    "dom.security.https_only_mode": true,
    "dom.security.https_only_mode_ever_enabled": true,
    "extensions.lastAppVersion": "95.0",
    "idle.lastDailyNotification": 1639480859,
    "media.gmp-manager.buildID": "20211206150432",
    "media.gmp-manager.lastCheck": 1639480055,
    "media.gmp.storage.version.observed": 1,
    "network.dns.disablePrefetch": true,
    "network.http.speculative-parallel-limit": 0,
    "network.predictor.enabled": false,
    "network.prefetch-next": false,
    "network.trr.blocklist_cleanup_done": true,
    "places.database.lastMaintenance": 1639480859,
    "privacy.sanitize.pending": "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]",
    "privacy.donottrackheader.enabled": true,
    "privacy.purge_trackers.date_in_cookie_database": "0",
    "privacy.purge_trackers.last_purge": "1639480859057",
    "privacy.userContext.enabled": true,
    "security.remote_settings.crlite_filters.checked": 1639479421,
    "security.remote_settings.intermediates.checked": 1639479421,
    "security.sandbox.content.tempDirSuffix": "9656c64d-3f30-41b4-8ff6-4c24e0c190dc",
    "services.sync.declinedEngines": "",
    "services.sync.lastPing": 1639481828,
    "services.sync.lastSync": "Tue Dec 14 2021 18:24:02 GMT+0100 (Central European Standard Time)",
    "services.sync.engine.creditcards": true,
    "services.sync.engine.prefs.modified": false,
    "storage.vacuum.last.index": 0,
    "storage.vacuum.last.places.sqlite": 1639480859
  },
  "lockedPreferences": {
    "fission.autostart.session": false
  },
  "printingPreferences": {},
  "media": {
    "currentAudioBackend": "pulse-rust",
    "currentMaxAudioChannels": 2,
    "currentPreferredSampleRate": 48000,
    "audioOutputDevices": [
      {
        "name": "Tiger Lake-LP Smart Sound Technology Audio Controller HDMI / DisplayPort 3 Output",
        "groupId": "",
        "vendor": "",
        "type": 2,
        "state": 1,
        "preferred": 0,
        "supportedFormat": 12336,
        "defaultFormat": 4096,
        "maxChannels": 2,
        "defaultRate": 48000,
        "maxRate": 384000,
        "minRate": 1,
        "maxLatency": 0,
        "minLatency": 0
      },
      {
        "name": "Tiger Lake-LP Smart Sound Technology Audio Controller HDMI / DisplayPort 2 Output",
        "groupId": "",
        "vendor": "",
        "type": 2,
        "state": 1,
        "preferred": 0,
        "supportedFormat": 12336,
        "defaultFormat": 4096,
        "maxChannels": 2,
        "defaultRate": 48000,
        "maxRate": 384000,
        "minRate": 1,
        "maxLatency": 0,
        "minLatency": 0
      },
      {
        "name": "Tiger Lake-LP Smart Sound Technology Audio Controller HDMI / DisplayPort 1 Output",
        "groupId": "",
        "vendor": "",
        "type": 2,
        "state": 1,
        "preferred": 0,
        "supportedFormat": 12336,
        "defaultFormat": 4096,
        "maxChannels": 2,
        "defaultRate": 48000,
        "maxRate": 384000,
        "minRate": 1,
        "maxLatency": 0,
        "minLatency": 0
      },
      {
        "name": "Tiger Lake-LP Smart Sound Technology Audio Controller Speaker + Headphones",
        "groupId": "",
        "vendor": "",
        "type": 2,
        "state": 2,
        "preferred": 15,
        "supportedFormat": 12336,
        "defaultFormat": 4096,
        "maxChannels": 2,
        "defaultRate": 48000,
        "maxRate": 384000,
        "minRate": 1,
        "maxLatency": 0,
        "minLatency": 0
      }
    ],
    "audioInputDevices": [
      {
        "name": "Monitor of Tiger Lake-LP Smart Sound Technology Audio Controller HDMI / DisplayPort 3 Output",
        "groupId": "",
        "vendor": "",
        "type": 1,
        "state": 2,
        "preferred": 0,
        "supportedFormat": 12336,
        "defaultFormat": 4096,
        "maxChannels": 2,
        "defaultRate": 48000,
        "maxRate": 384000,
        "minRate": 1,
        "maxLatency": 0,
        "minLatency": 0
      },
      {
        "name": "Monitor of Tiger Lake-LP Smart Sound Technology Audio Controller HDMI / DisplayPort 2 Output",
        "groupId": "",
        "vendor": "",
        "type": 1,
        "state": 2,
        "preferred": 0,
        "supportedFormat": 12336,
        "defaultFormat": 4096,
        "maxChannels": 2,
        "defaultRate": 48000,
        "maxRate": 384000,
        "minRate": 1,
        "maxLatency": 0,
        "minLatency": 0
      },
      {
        "name": "Monitor of Tiger Lake-LP Smart Sound Technology Audio Controller HDMI / DisplayPort 1 Output",
        "groupId": "",
        "vendor": "",
        "type": 1,
        "state": 2,
        "preferred": 0,
        "supportedFormat": 12336,
        "defaultFormat": 4096,
        "maxChannels": 2,
        "defaultRate": 48000,
        "maxRate": 384000,
        "minRate": 1,
        "maxLatency": 0,
        "minLatency": 0
      },
      {
        "name": "Monitor of Tiger Lake-LP Smart Sound Technology Audio Controller Speaker + Headphones",
        "groupId": "",
        "vendor": "",
        "type": 1,
        "state": 2,
        "preferred": 0,
        "supportedFormat": 12336,
        "defaultFormat": 4096,
        "maxChannels": 2,
        "defaultRate": 48000,
        "maxRate": 384000,
        "minRate": 1,
        "maxLatency": 0,
        "minLatency": 0
      },
      {
        "name": "Tiger Lake-LP Smart Sound Technology Audio Controller Headphones Stereo Microphone",
        "groupId": "",
        "vendor": "",
        "type": 1,
        "state": 1,
        "preferred": 15,
        "supportedFormat": 12336,
        "defaultFormat": 4096,
        "maxChannels": 2,
        "defaultRate": 48000,
        "maxRate": 384000,
        "minRate": 1,
        "maxLatency": 0,
        "minLatency": 0
      },
      {
        "name": "Tiger Lake-LP Smart Sound Technology Audio Controller Digital Microphone",
        "groupId": "",
        "vendor": "",
        "type": 1,
        "state": 2,
        "preferred": 0,
        "supportedFormat": 12336,
        "defaultFormat": 4096,
        "maxChannels": 2,
        "defaultRate": 48000,
        "maxRate": 384000,
        "minRate": 1,
        "maxLatency": 0,
        "minLatency": 0
      }
    ]
  },
  "accessibility": {
    "isActive": false,
    "forceDisabled": 0,
    "handlerUsed": false,
    "instantiator": ""
  },
  "startupCache": {
    "DiskCachePath": "/home/francoisbechet/.cache/mozilla/firefox/fcd06wen.default-release/startupCache/startupCache.8.little",
    "IgnoreDiskCache": false,
    "FoundDiskCacheOnInit": false,
    "WroteToDiskCache": false
  },
  "libraryVersions": {
    "NSPR": {
      "minVersion": "4.32",
      "version": "4.32"
    },
    "NSS": {
      "minVersion": "3.73",
      "version": "3.73"
    },
    "NSSUTIL": {
      "minVersion": "3.73",
      "version": "3.73"
    },
    "NSSSSL": {
      "minVersion": "3.73",
      "version": "3.73"
    },
    "NSSSMIME": {
      "minVersion": "3.73",
      "version": "3.73"
    }
  },
  "userJS": {
    "exists": false
  },
  "intl": {
    "localeService": {
      "requested": [
        "en-US"
      ],
      "available": [
        "en-US"
      ],
      "supported": [
        "en-US"
      ],
      "regionalPrefs": [
        "en-US"
      ],
      "defaultLocale": "en-US"
    },
    "osPrefs": {
      "systemLocales": [
        "en-US"
      ],
      "regionalPrefsLocales": [
        "en-US"
      ]
    }
  },
  "crashes": {
    "submitted": [],
    "pending": 0
  },
  "sandbox": {
    "hasSeccompBPF": true,
    "hasSeccompTSync": true,
    "hasPrivilegedUserNamespaces": true,
    "hasUserNamespaces": true,
    "canSandboxContent": true,
    "canSandboxMedia": true,
    "syscallLog": [],
    "contentSandboxLevel": 4,
    "effectiveContentSandboxLevel": 4,
    "contentWin32kLockdownState": "Win32k Lockdown disabled -- Operating system not supported"
  },
  "remoteAgent": {
    "listening": false,
    "url": ""
  },
  "graphics": {
    "numTotalWindows": 1,
    "numAcceleratedWindows": 1,
    "windowLayerManagerType": "WebRender (Software)",
    "windowLayerManagerRemote": true,
    "windowUsingAdvancedLayers": false,
    "adapterDescription": "Mesa Intel(R) Xe Graphics (TGL GT2)",
    "adapterVendorID": "0x8086",
    "adapterDeviceID": "0x9a49",
    "adapterRAM": 0,
    "adapterDrivers": "",
    "driverVendor": "mesa/iris",
    "driverVersion": "21.3.1.0",
    "driverDate": "",
    "adapterVendorID2": "",
    "adapterDeviceID2": "",
    "isGPU2Active": false,
    "targetFrameRate": 60,
    "windowProtocol": "xwayland",
    "desktopEnvironment": "unknown",
    "webgl1Renderer": "WebGL is currently disabled.",
    "webgl1Version": "-",
    "webgl1DriverExtensions": "-",
    "webgl1Extensions": "-",
    "webgl1WSIInfo": "-",
    "webgl2Renderer": "WebGL is currently disabled.",
    "webgl2Version": "-",
    "webgl2DriverExtensions": "-",
    "webgl2Extensions": "-",
    "webgl2WSIInfo": "-",
    "info": {
      "AzureFallbackCanvasBackend": "skia",
      "AzureCanvasBackend": "skia",
      "AzureContentBackend": "skia",
      "ApzWheelInput": 1,
      "ApzDragInput": 1,
      "ApzKeyboardInput": 1,
      "ApzAutoscrollInput": 1,
      "ApzZoomingInput": 1,
      "CMSOutputProfile": "Empty profile data",
      "DisplayCount": 1,
      "Display0": "1920x1080 "
    },
    "featureLog": {
      "features": [
        {
          "name": "HW_COMPOSITING",
          "description": "Compositing",
          "status": "blocked",
          "log": [
            {
              "type": "default",
              "status": "available"
            },
            {
              "type": "runtime",
              "status": "blocked",
              "message": "Acceleration blocked by safe-mode"
            }
          ]
        },
        {
          "name": "OPENGL_COMPOSITING",
          "description": "OpenGL Compositing",
          "status": "unavailable",
          "log": [
            {
              "type": "default",
              "status": "unavailable",
              "message": "Hardware compositing is disabled"
            }
          ]
        },
        {
          "name": "WEBRENDER",
          "description": "WebRender",
          "status": "unavailable-in-safe-mode",
          "log": [
            {
              "type": "default",
              "status": "available"
            },
            {
              "type": "runtime",
              "status": "unavailable-in-safe-mode",
              "message": "Safe-mode is enabled"
            }
          ]
        },
        {
          "name": "WEBRENDER_QUALIFIED",
          "description": "WebRender qualified",
          "status": "available",
          "log": [
            {
              "type": "default",
              "status": "available"
            }
          ]
        },
        {
          "name": "WEBRENDER_COMPOSITOR",
          "description": "WebRender native compositor",
          "status": "blocklisted",
          "log": [
            {
              "type": "default",
              "status": "disabled",
              "message": "Disabled by default"
            },
            {
              "type": "env",
              "status": "blocklisted",
              "message": "Blocklisted by gfxInfo"
            }
          ]
        },
        {
          "name": "WEBRENDER_PARTIAL",
          "description": "WebRender partial present",
          "status": "available",
          "log": [
            {
              "type": "default",
              "status": "available"
            }
          ]
        },
        {
          "name": "WEBRENDER_SHADER_CACHE",
          "description": "WebRender shader disk cache",
          "status": "unavailable",
          "log": [
            {
              "type": "default",
              "status": "disabled",
              "message": "Disabled by default"
            },
            {
              "type": "runtime",
              "status": "unavailable",
              "message": "WebRender disabled"
            }
          ]
        },
        {
          "name": "WEBRENDER_OPTIMIZED_SHADERS",
          "description": "WebRender optimized shaders",
          "status": "unavailable",
          "log": [
            {
              "type": "default",
              "status": "available"
            },
            {
              "type": "runtime",
              "status": "unavailable",
              "message": "WebRender disabled"
            }
          ]
        },
        {
          "name": "WEBRENDER_ANGLE",
          "description": "WebRender ANGLE",
          "status": "unavailable",
          "log": [
            {
              "type": "default",
              "status": "available"
            },
            {
              "type": "env",
              "status": "unavailable",
              "message": "OS not supported"
            }
          ]
        },
        {
          "name": "WEBRENDER_DCOMP_PRESENT",
          "description": "WebRender DirectComposition",
          "status": "unavailable",
          "log": [
            {
              "type": "default",
              "status": "available"
            },
            {
              "type": "user",
              "status": "disabled",
              "message": "User disabled via pref"
            },
            {
              "type": "env",
              "status": "unavailable",
              "message": "Requires Windows 10 or later"
            },
            {
              "type": "runtime",
              "status": "unavailable",
              "message": "Requires ANGLE"
            }
          ]
        },
        {
          "name": "WEBRENDER_SOFTWARE",
          "description": "WebRender software fallback",
          "status": "available",
          "log": [
            {
              "type": "default",
              "status": "available"
            }
          ]
        },
        {
          "name": "WEBGPU",
          "description": "WebGPU",
          "status": "blocked",
          "log": [
            {
              "type": "default",
              "status": "disabled",
              "message": "Disabled by default"
            },
            {
              "type": "runtime",
              "status": "blocked",
              "message": "WebGPU can only be enabled in nightly"
            }
          ]
        },
        {
          "name": "X11_EGL",
          "description": "X11 EGL",
          "status": "available",
          "log": [
            {
              "type": "default",
              "status": "available"
            }
          ]
        },
        {
          "name": "DMABUF",
          "description": "DMABUF",
          "status": "available",
          "log": [
            {
              "type": "default",
              "status": "available"
            }
          ]
        }
      ],
      "fallbacks": []
    },
    "crashGuards": []
  },
  "experimentalFeatures": [
    [
      "experimental-features-abouthome-startup-cache",
      "browser.startup.homepage.abouthome_cache.enabled",
      false
    ],
    [
      "experimental-features-cookie-samesite-lax-by-default2",
      "network.cookie.sameSite.laxByDefault",
      false
    ],
    [
      "experimental-features-cookie-samesite-none-requires-secure2",
      "network.cookie.sameSite.noneRequiresSecure",
      false
    ],
    [
      "experimental-features-cookie-samesite-schemeful",
      "network.cookie.sameSite.schemeful",
      false
    ],
    [
      "experimental-features-css-cascade-layers",
      "layout.css.cascade-layers.enabled",
      false
    ],
    [
      "experimental-features-css-constructable-stylesheets",
      "layout.css.constructable-stylesheets.enabled",
      false
    ],
    [
      "experimental-features-css-masonry2",
      "layout.css.grid-template-masonry-value.enabled",
      false
    ],
    [
      "experimental-features-devtools-compatibility-panel",
      "devtools.inspector.compatibility.enabled",
      false
    ],
    [
      "experimental-features-devtools-execution-context-selector",
      "devtools.webconsole.input.context",
      false
    ],
    [
      "experimental-features-devtools-serviceworker-debugger-support",
      "devtools.debugger.features.windowless-service-workers",
      false
    ],
    [
      "experimental-features-fission",
      "fission.autostart",
      true
    ],
    [
      "experimental-features-media-jxl",
      "image.jxl.enabled",
      false
    ],
    [
      "experimental-features-multi-pip",
      "media.videocontrols.picture-in-picture.allow-multiple",
      true
    ],
    [
      "experimental-features-ime-search",
      "browser.urlbar.keepPanelOpenDuringImeComposition",
      false
    ],
    [
      "experimental-features-web-gpu2",
      "dom.webgpu.enabled",
      false
    ],
    [
      "experimental-features-webrtc-global-mute-toggles",
      "privacy.webrtc.globalMuteToggles",
      false
    ],
    [
      "experimental-features-win32k-lockdown",
      "security.sandbox.content.win32k-disable",
      false
    ]
  ],
  "addons": [
    {
      "name": "Add-ons Search Detection",
      "type": "extension",
      "version": "2.0.0",
      "isActive": true,
      "id": "addons-search-detection@mozilla.com"
    },
    {
      "name": "Amazon.co.uk",
      "type": "extension",
      "version": "1.9",
      "isActive": true,
      "id": "amazon@search.mozilla.org"
    },
    {
      "name": "Bing",
      "type": "extension",
      "version": "1.3",
      "isActive": true,
      "id": "bing@search.mozilla.org"
    },
    {
      "name": "DuckDuckGo",
      "type": "extension",
      "version": "1.1",
      "isActive": true,
      "id": "ddg@search.mozilla.org"
    },
    {
      "name": "eBay",
      "type": "extension",
      "version": "1.3",
      "isActive": true,
      "id": "ebay@search.mozilla.org"
    },
    {
      "name": "Google",
      "type": "extension",
      "version": "1.1",
      "isActive": true,
      "id": "google@search.mozilla.org"
    },
    {
      "name": "Wikipedia (en)",
      "type": "extension",
      "version": "1.1",
      "isActive": true,
      "id": "wikipedia@search.mozilla.org"
    },
    {
      "name": "ClearURLs",
      "type": "extension",
      "version": "1.21.0",
      "isActive": false,
      "id": "{74145f27-f039-47ce-a470-a662b129930a}"
    },
    {
      "name": "Dark Reader",
      "type": "extension",
      "version": "4.9.43",
      "isActive": false,
      "id": "addon@darkreader.org"
    },
    {
      "name": "Enhancer for YouTube™",
      "type": "extension",
      "version": "2.0.109",
      "isActive": false,
      "id": "enhancerforyoutube@maximerf.addons.mozilla.org"
    },
    {
      "name": "Grammar & Spell Checker — LanguageTool",
      "type": "extension",
      "version": "4.4.1",
      "isActive": false,
      "id": "languagetool-webextension@languagetool.org"
    },
    {
      "name": "Grammarly for Firefox",
      "type": "extension",
      "version": "8.892.0",
      "isActive": false,
      "id": "87677a2c52b84ad3a151a4a72f5bd3c4@jetpack"
    },
    {
      "name": "Refined GitHub",
      "type": "extension",
      "version": "21.12.12",
      "isActive": false,
      "id": "{a4c4eda4-fb84-4a84-b4a1-f7c1cbf2a1ad}"
    },
    {
      "name": "To Google Translate",
      "type": "extension",
      "version": "4.2.0",
      "isActive": false,
      "id": "jid1-93WyvpgvxzGATw@jetpack"
    },
    {
      "name": "uBlock Origin",
      "type": "extension",
      "version": "1.39.2",
      "isActive": false,
      "id": "uBlock0@raymondhill.net"
    },
    {
      "name": "Wikiwand: Wikipedia Modernized",
      "type": "extension",
      "version": "5.1.3",
      "isActive": false,
      "id": "jid1-D7momAzRw417Ag@jetpack"
    },
    {
      "name": "Youtube Audio",
      "type": "extension",
      "version": "0.0.2.5",
      "isActive": false,
      "id": "{580efa7d-66f9-474d-857a-8e2afc6b1181}"
    }
  ],
  "features": [
    {
      "name": "DoH Roll-Out",
      "version": "2.0.0",
      "id": "doh-rollout@mozilla.org"
    },
    {
      "name": "Firefox Screenshots",
      "version": "39.0.1",
      "id": "screenshots@mozilla.org"
    },
    {
      "name": "Form Autofill",
      "version": "1.0.1",
      "id": "formautofill@mozilla.org"
    },
    {
      "name": "Picture-In-Picture",
      "version": "1.0.0",
      "id": "pictureinpicture@mozilla.org"
    },
    {
      "name": "Proxy Failover",
      "version": "1.0.2",
      "id": "proxy-failover@mozilla.com"
    },
    {
      "name": "Web Compatibility Interventions",
      "version": "28.0.0",
      "id": "webcompat@mozilla.org"
    },
    {
      "name": "WebCompat Reporter",
      "version": "1.4.2",
      "id": "webcompat-reporter@mozilla.org"
    }
  ],
  "normandy": {
    "addonStudies": [],
    "prefRollouts": [
      {
        "slug": "bug-1690367-rollout-moving-webrtc-networking-functionality-into-i-release-87-100",
        "state": "active",
        "preferences": [
          {
            "preferenceName": "media.peerconnection.mtransport_process",
            "value": true,
            "previousValue": false
          },
          {
            "preferenceName": "network.process.enabled",
            "value": true,
            "previousValue": false
          }
        ],
        "enrollmentId": "47ef909c-351f-4714-8f88-bfed911f0f34"
      },
      {
        "slug": "bug-1732206-rollout-fission-release-rollout-release-94-95",
        "state": "active",
        "preferences": [
          {
            "preferenceName": "fission.experiment.enrollmentStatus",
            "value": 4,
            "previousValue": 0
          }
        ],
        "enrollmentId": "39fb488d-a7a4-437d-b6d5-6d91e6538cb6"
      }
    ],
    "prefStudies": [],
    "nimbusExperiments": [],
    "remoteConfigs": []
  }
}

**Comment by bl4ckb0ne** [comment]
That's not a proper debug log. We need either logs from sway, logs from firefox, a trace from running firefox with `WAYLAND_DEBUG=1`, or all of those if possible.

**Comment by flipflop133** [comment]
### Trace of `WAYLAND_DEBUG=1 firefox`
[3161288.719]  -> wl_display@1.get_registry(new id wl_registry@2)
[3161288.735]  -> wl_display@1.sync(new id wl_callback@3)
[3161288.846] wl_display@1.delete_id(3)
[3161288.865] wl_registry@2.global(1, "wl_shm", 1)
[3161288.878]  -> wl_registry@2.bind(1, "wl_shm", 1, new id [unknown]@4)
[3161288.903] wl_registry@2.global(2, "wl_drm", 2)
[3161288.918] wl_registry@2.global(3, "zwp_linux_dmabuf_v1", 3)
[3161288.931] wl_registry@2.global(4, "wl_compositor", 4)
[3161288.945]  -> wl_registry@2.bind(4, "wl_compositor", 3, new id [unknown]@5)
[3161288.959] wl_registry@2.global(5, "wl_subcompositor", 1)
[3161288.969]  -> wl_registry@2.bind(5, "wl_subcompositor", 1, new id [unknown]@6)
[3161288.983] wl_registry@2.global(6, "wl_data_device_manager", 3)
[3161288.992]  -> wl_registry@2.bind(6, "wl_data_device_manager", 3, new id [unknown]@7)
[3161289.001] wl_registry@2.global(7, "zwlr_gamma_control_manager_v1", 1)
[3161289.010] wl_registry@2.global(8, "zxdg_output_manager_v1", 3)
[3161289.037]  -> wl_registry@2.bind(8, "zxdg_output_manager_v1", 3, new id [unknown]@8)
[3161289.056]  -> wl_display@1.sync(new id wl_callback@9)
[3161289.069] wl_registry@2.global(9, "org_kde_kwin_idle", 1)
[3161289.082] wl_registry@2.global(10, "zwp_idle_inhibit_manager_v1", 1)
[3161289.095] wl_registry@2.global(11, "zwlr_layer_shell_v1", 4)
[3161289.108] wl_registry@2.global(12, "xdg_wm_base", 2)
[3161289.121] wl_registry@2.global(13, "zwp_tablet_manager_v2", 1)
[3161289.134]  -> wl_registry@2.bind(13, "zwp_tablet_manager_v2", 1, new id [unknown]@10)
[3161289.154] wl_registry@2.global(14, "org_kde_kwin_server_decoration_manager", 1)
[3161289.169]  -> wl_registry@2.bind(14, "org_kde_kwin_server_decoration_manager", 1, new id [unknown]@11)
[3161289.193] wl_registry@2.global(15, "zxdg_decoration_manager_v1", 1)
[3161289.207] wl_registry@2.global(16, "zwp_relative_pointer_manager_v1", 1)
[3161289.223] wl_registry@2.global(17, "zwp_pointer_constraints_v1", 1)
[3161289.235] wl_registry@2.global(18, "wp_presentation", 1)
[3161289.248] wl_registry@2.global(19, "zwlr_output_manager_v1", 2)
[3161289.256] wl_registry@2.global(20, "zwlr_output_power_manager_v1", 1)
[3161289.266] wl_registry@2.global(21, "zwp_input_method_manager_v2", 1)
[3161289.276] wl_registry@2.global(22, "zwp_text_input_manager_v3", 1)
[3161289.289] wl_registry@2.global(23, "zwlr_foreign_toplevel_manager_v1", 3)
[3161289.299] wl_registry@2.global(24, "zwlr_export_dmabuf_manager_v1", 1)
[3161289.307] wl_registry@2.global(25, "zwlr_screencopy_manager_v1", 3)
[3161289.316] wl_registry@2.global(26, "zwlr_data_control_manager_v1", 2)
[3161289.325] wl_registry@2.global(27, "zwp_primary_selection_device_manager_v1", 1)
[3161289.335]  -> wl_registry@2.bind(27, "zwp_primary_selection_device_manager_v1", 1, new id [unknown]@12)
[3161289.357] wl_registry@2.global(28, "wp_viewporter", 1)
[3161289.380] wl_registry@2.global(29, "zxdg_exporter_v1", 1)
[3161289.391]  -> wl_registry@2.bind(29, "zxdg_exporter_v1", 1, new id [unknown]@13)
[3161289.405] wl_registry@2.global(30, "zxdg_importer_v1", 1)
[3161289.416]  -> wl_registry@2.bind(30, "zxdg_importer_v1", 1, new id [unknown]@14)
[3161289.431] wl_registry@2.global(31, "zxdg_exporter_v2", 1)
[3161289.444] wl_registry@2.global(32, "zxdg_importer_v2", 1)
[3161289.455] wl_registry@2.global(33, "zwp_virtual_keyboard_manager_v1", 1)
[3161289.467] wl_registry@2.global(34, "zwlr_virtual_pointer_manager_v1", 2)
[3161289.477] wl_registry@2.global(35, "zwlr_input_inhibit_manager_v1", 1)
[3161289.488] wl_registry@2.global(36, "zwp_keyboard_shortcuts_inhibit_manager_v1", 1)
[3161289.500]  -> wl_registry@2.bind(36, "zwp_keyboard_shortcuts_inhibit_manager_v1", 1, new id [unknown]@15)
[3161289.516] wl_registry@2.global(37, "wl_seat", 7)
[3161289.526] wl_registry@2.global(38, "zwp_pointer_gestures_v1", 1)
[3161289.538]  -> wl_registry@2.bind(38, "zwp_pointer_gestures_v1", 1, new id [unknown]@16)
[3161289.551] wl_registry@2.global(39, "wl_output", 3)
[3161289.559]  -> wl_registry@2.bind(39, "wl_output", 2, new id [unknown]@17)
[3161289.608]  -> zxdg_output_manager_v1@8.get_xdg_output(new id zxdg_output_v1@18, wl_output@17)
[3161289.618]  -> wl_display@1.sync(new id wl_callback@19)
[3161289.625] wl_callback@3.done(2471)
[3161289.654]  -> wl_shm@4.create_pool(new id wl_shm_pool@3, fd 11, 2304)
[3161289.746]  -> wl_shm_pool@3.resize(8704)
[3161289.857]  -> wl_shm_pool@3.resize(21504)
[3161289.998]  -> wl_shm_pool@3.resize(47104)
[3161290.577]  -> wl_shm_pool@3.resize(98304)
[3161290.858]  -> wl_shm_pool@3.resize(200704)
[3161291.821]  -> wl_shm_pool@3.resize(405504)
[3161293.587]  -> wl_shm_pool@3.resize(815104)
[3161296.102]  -> wl_shm_pool@3.resize(1634304)
[3161301.818]  -> wl_registry@2.bind(37, "wl_seat", 5, new id [unknown]@20)
[3161304.307]  -> wl_compositor@5.create_surface(new id wl_surface@21)
[3161304.322]  -> zwp_primary_selection_device_manager_v1@12.get_device(new id zwp_primary_selection_device_v1@22, wl_seat@20)
[3161304.329]  -> wl_data_device_manager@7.get_data_device(new id wl_data_device@23, wl_seat@20)
[3161304.409]  -> wl_compositor@5.create_surface(new id wl_surface@24)
[3161304.415]  -> zwp_tablet_manager_v2@10.get_tablet_seat(new id zwp_tablet_seat_v2@25, wl_seat@20)
[3161304.421]  -> wl_display@1.sync(new id wl_callback@26)
[3161304.527] wl_display@1.delete_id(9)
[3161304.532] wl_display@1.delete_id(19)
[3161304.535] wl_display@1.delete_id(26)
[3161304.537] wl_shm@4.format(0)
[3161304.540] wl_shm@4.format(1)
[3161304.542] wl_shm@4.format(875709016)
[3161304.545] wl_shm@4.format(875708993)
[3161304.548] wl_callback@9.done(2471)
[3161304.552] org_kde_kwin_server_decoration_manager@11.default_mode(2)
[3161304.557] wl_output@17.geometry(0, 0, 520, 290, 2, "Samsung Electric Company", "S24F350", 0)
[3161304.576] wl_output@17.mode(1, 1920, 1080, 60000)
[3161304.583] wl_output@17.scale(1)
[3161304.586] wl_output@17.done()
[3161304.597] zxdg_output_v1@18.name("VGA-1")
[3161304.601] zxdg_output_v1@18.description("Samsung Electric Company S24F350 H4ZH504584 (VGA-1)")
[3161304.603] zxdg_output_v1@18.logical_position(0, 0)
[3161304.607] zxdg_output_v1@18.logical_size(1920, 1080)
[3161304.611] wl_output@17.done()
[3161304.614] wl_callback@19.done(2471)
[3161304.617] wl_seat@20.name("seat0")
[3161304.621] wl_seat@20.capabilities(3)
[3161304.625]  -> wl_seat@20.get_pointer(new id wl_pointer@19)
[3161304.637]  -> zwp_pointer_gestures_v1@16.get_swipe_gesture(new id zwp_pointer_gesture_swipe_v1@9, wl_pointer@19)
[3161304.643]  -> zwp_pointer_gestures_v1@16.get_pinch_gesture(new id zwp_pointer_gesture_pinch_v1@27, wl_pointer@19)
[3161304.647]  -> wl_seat@20.get_keyboard(new id wl_keyboard@28)
[3161304.656] wl_callback@26.done(2471)
[3161304.660]  -> wl_registry@2.bind(12, "xdg_wm_base", 1, new id [unknown]@26)

**Comment by flipflop133** [comment]
It seems it was related to my nvidia graphic card missing some drivers but I switched to my intel integrated graphics and now it's fine.
