### ISSUE TITLE
Config files are not composed together, leading to gray screen and unresponsive input with simple user-level config

### ISSUE THREAD

**Issue by huguesb** [swaywm/sway#6715]
- **Sway Version:**
  1.6.1 from official arch linux package

- **Debug Log:**
  - without config file: https://gist.github.com/huguesb/9a412938906a2789f6dffffead15e3fa
  - with config https://gist.github.com/huguesb/d779e6a1416e75d6278c27ec87c0de25

- **Configuration File:**
```

input type:touchpad {
  dwt enabled
  natural_scroll disabled
  tap enabled
  tap_button_map lrm
}


```

- **Description:**
  - start sway
  - excited to customize behavior
  - create above config file to get desired behavior from laptop touchpad, install a few addons
  - restart sway
  - screen is gray instead of default background, no status bar is visible, mouse pointer is visible, keyboard seems unresponsive (although vt switching still works)
  - freak out and try uninstalling addons, and reverting to wayland 1.19 since behavior change after upgrade to 1.20 seems suspicious, hunt for similar issues on tracker, get into a rabbit hole of checking intel mesa driver, come here to file a bug report, notice the recommendation to reproduce with default config
  - remove config file
  - restart sway
  - things works again
  - put config back in
  - things break again, ok this is solidly reproducible, and the drm errors are plausibly red herrings

**Comment by huguesb** [comment]
Update: it seems like the contents of the config file are irrelevant. Even an empty or fully commented-out file reproduces the issue

**Comment by emersion** [comment]
Hm interesting…

```
00:00:59.406 [ERROR] [wlr] [backend/drm/atomic.c:35] connector eDP-1: Atomic commit failed (pageflip): Permission denied
00:01:00.412 [ERROR] [wlr] [backend/drm/atomic.c:35] connector eDP-1: Atomic commit failed (pageflip): Permission denied
00:01:01.419 [ERROR] [wlr] [backend/drm/atomic.c:35] connector eDP-1: Atomic commit failed (pageflip): Permission denied
00:01:02.426 [ERROR] [wlr] [backend/drm/atomic.c:35] connector eDP-1: Atomic commit failed (pageflip): Permission denied
00:01:03.432 [ERROR] [wlr] [backend/drm/atomic.c:35] connector eDP-1: Atomic commit failed (pageflip): Permission denied
00:01:04.439 [ERROR] [wlr] [backend/drm/atomic.c:35] connector eDP-1: Atomic commit failed (pageflip): Permission denied
00:01:05.445 [ERROR] [wlr] [backend/drm/atomic.c:35] connector eDP-1: Atomic commit failed (pageflip): Permission denied
00:01:05.819 [ERROR] [wlr] [libseat] [libseat/backend/logind.c:76] Ping failed: org.freedesktop.DBus.Error.NoReply: Method call timed out
```

It seems like maybe we're trying to pageflip an output while our seat isn't enabled or something?

cc @kennylevinsen

**Comment by huguesb** [comment]
Update: looks like a config in $HOME completely overrides the entirety of the default config in /etc (and any default config in the binary itself) instead of the various config files being composed together.

If I copy /etc/sway/config into ~/.config/sway/config and add my `input {}` section there things work again. The error lines about pageflip still show up in  the logs but don't seem to affect visibly functionality.

Updating issue title accordingly

**Comment by Emantor** [comment]
This is not unexpected behavior, this is intended. The defaults in /etc/sway/config are meant as a distribution provided starting point, if you want to compose you'll need to include files explicitly.

**Comment by huguesb** [comment]
> This is not unexpected behavior, this is intended. The defaults in /etc/sway/config are meant as a distribution provided starting point, if you want to compose you'll need to include files explicitly.

As implemented right now it feels pretty user-hostile. Config file composing is a pretty standard behavior so any deviation from that standard ought to be very clearly documented. The fact that as an advanced user following the docs to do a very simple tweak I basically completely broke this is a clear sign that something needs to change. Whether that's merely documentation, sane defaults with empty/minimal config file, or full composition of config files, or a combination thereof.

@emersion I did have to vt-switch to collect the logs because the empty config meant I couldn't even exit out of sway...

I would be happy to run more troubleshooting/diagnostics to zero-in on the permission issue.

**Comment by emersion** [comment]
Oh, then these ENOPERM errors are expected. Not sure there's anything else to do here.

> As implemented right now it feels pretty user-hostile. Config file composing is a pretty standard behavior so any deviation from that standard ought to be very clearly documented. The fact that as an advanced user following the docs to do a very simple tweak I basically completely broke this is a clear sign that something needs to change. Whether that's merely documentation, sane defaults with empty/minimal config file, or full composition of config files, or a combination thereof.

You're the first confused user I've heard of. I think Sway's behaviour is pretty standard, on the contrary.

**Comment by huguesb** [comment]
> Oh, then these ENOPERM errors are expected. Not sure there's anything else to do here.
> 
Great, happy to ignore them.


> > As implemented right now it feels pretty user-hostile. Config file composing is a pretty standard behavior so any deviation from that standard ought to be very clearly documented. The fact that as an advanced user following the docs to do a very simple tweak I basically completely broke this is a clear sign that something needs to change. Whether that's merely documentation, sane defaults with empty/minimal config file, or full composition of config files, or a combination thereof.
> 
> You're the first confused user I've heard of. I think Sway's behaviour is pretty standard, on the contrary.
Probably because anyone who encountered this behavior didn't bother reporting the issue and decided to use some other window manager... I can live with poorly designed software. To a large extent, most software has glaring defects so it's really  about tradeoffs. I sure as hell wouldn't want to put my name on a piece of software that *defaults* to a broken state however. It's okay if yall have different standards, just maybe consider documenting them...

**Comment by tiosgz** [comment]
Fwiw, i also consider the no-defaults behaviour pretty standard, and it’s way way nicer if you want to differ from the fallback a lot. Imagine having to reset every single default just because the example config gets merged in.

The manpage (`man 5 sway`) also suggests that only one config is used

> An example config is likely present in `/etc/sway/config` for you to check out.

but i think a patch to make it clearer will be welcome.
