### ISSUE TITLE
wayst terminal: listener function for opcode 4 of wl_output is NULL

### ISSUE THREAD

**Issue by shoober420** [swaywm/sway#6717]
- **Sway Version:**
  - sway version 1.6-f2b6d1ec (Dec 14 2021, branch 'HEAD')

- **Debug Log:**
  - [GDCHPTFLU.txt](https://github.com/swaywm/sway/files/7716583/GDCHPTFLU.txt)

- **Configuration File:**
  - https://github.com/shoober420/rootscripts/blob/main/home/shoober420/.config/sway/config

- **Description:**
  - When launching the wayst terminal, I get the following error.

```
@gentoo:~$ wayst
[warning] Error in config on line 20: invalid option 'h-bg-color'. 'wayst -h' to list options
[warning] Error in config on line 21: invalid option 'h-fg-color'. 'wayst -h' to list options
[warning] Could not find font 'MxPlus IBM VGA 8x16'
[warning] Could not find font 'MxPlus IBM VGA 8x16'
listener function for opcode 4 of wl_output is NULL
The process was killed by SIGABRT: Aborted
@gentoo:~$
```

**Comment by Emantor** [comment]
This is the same as #6713, wayst shouldn't bind to the latest protocol version, it should bind to the one it supports.

**Comment by Emantor** [comment]
As a reference, this is the commit that fixed imv: https://git.sr.ht/~exec64/imv/commit/c7306a6325df0282c16d60b7201b6bd963f76756

**Comment by shoober420** [comment]
Thank you for the information.

**Comment by zezba9000** [comment]
How did you fix this? I tried version 1-3 and its just the same error
```
listener function for opcode 0 of wl_output is NULL
```
