### ISSUE TITLE
Sway aborts during startup under qemu virtio alpine

### ISSUE THREAD

**Issue by timmydo** [swaywm/sway#6718]
- **Sway Version:**
  - sway version 1.6.1-6ef8a4d4d7 (Oct 17 2021, branch 'master')
  - from alpine

- **Debug Log:**
  - (https://gist.github.com/timmydo/7dbe33545fa35cce71c0c32a23a4aa80)

- **Configuration File:**
  - I didn't create one, just took the distro's https://gist.github.com/timmydo/28d3484033cf67b6c1e2d8ed055fee5f

- **Description:**
  - `qemu-system-x86_64 -m 8G -hdd ~/qemu/alpine/disk1 -enable-kvm -vga virtio -net user,hostfwd=tcp::10022-:22 -net nic`

Was just trying out latest alpine on qemu today, but wasn't able to get sway working. Seems to crash immediately although I see the screen flash gray before being dropped to getty. Tried following https://wiki.alpinelinux.org/wiki/Sway

```
00:00:00.190 [DEBUG] [sway/desktop/layer_shell.c:197] Usable area changed, rearranging output
00:00:00.190 [DEBUG] [sway/tree/arrange.c:263] Usable area for ws: 1716x1343@0,22
00:00:00.190 [DEBUG] [sway/tree/arrange.c:293] Arranging workspace '1' at 0.000000, 22.000000
00:00:00.190 [DEBUG] [sway/desktop/transaction.c:398] Transaction 0x7fc028004cf0 committing with 1 instructions
00:00:00.190 [DEBUG] [sway/desktop/transaction.c:294] Applying transaction 0x7fc028004cf0
00:00:00.190 [DEBUG] [wlr] [types/wlr_surface.c:743] New wlr_surface 0x7fc026d74490 (res 0x7fc027fc1520)
Assertion failed: wlr_texture_is_gles2(wlr_texture) (render/gles2/texture.c: gles2_get_texture: 27)
00:00:00.029 [ERROR] [common/ipc-client.c:87] Unable to receive IPC response
Aborted
```

**Comment by emersion** [comment]
This has been fixed in master.

Note, you're running without hardware acceleration, ie. with software rendering.

**Comment by yavko** [comment]
This still happens for me
