### ISSUE TITLE
Sway crashes when attempting to swap focused fullscreen container with itself

### ISSUE THREAD

**Issue by NumenHackerCracker** [swaywm/sway#6724]
### Steps To Reproduce
1. Open a terminal, then full-screen it
2. Run `sway mark "x"` then `sway swap container with mark "x"`

### Expected behavior
Sway crashes. I am running sway version 1.6.1 on void linux with musl libc and runit init. It also might be worth mentioning that I am not using elogind, and instead using seatd and setting the `XDG_RUNTIME_DIR` in my .profile.

[Debug log](https://gist.github.com/NumenHackerCracker/4d2ee6e75e618c56df4c0e6361cbb499)

**Comment by emersion** [comment]
Please provide a stack trace. You can do so by compiling from source, reproducing the crash and then running `coredumpctl gdb` and then `bt full`.

Here are some instructions to compile from source: https://github.com/swaywm/sway/wiki/Development-Setup#compiling-as-a-subproject

**Comment by RPigott** [comment]
swap_container should probably always be a noop when swapping a con with itself.
