### ISSUE TITLE
Sway crashes if started through lightdm

### ISSUE THREAD

**Issue by carlpett** [swaywm/sway#6736]
### Please fill out the following:
- **Sway Version:**
```
sway version 1.6.1
```

- **Debug Log:**
Need help to produce

- **Configuration File:**
Reproduces with default config.

- **Stack Trace:**
```
#0  0x00007feb7a8ff84c __pthread_kill_implementation (libc.so.6 + 0x8f84c)
#1  0x00007feb7a8b26a6 raise (libc.so.6 + 0x426a6)
#2  0x00005567ca82d825 _sway_assert (sway + 0x64825)
#3  0x00005567ca82bd07 view_map.part.0 (sway + 0x62d07)
#4  0x00005567ca7f752a handle_map.lto_priv.1 (sway + 0x2e52a)
#5  0x00007feb7ab7a01c wlr_signal_emit_safe (libwlroots.so.9 + 0x7a01c)
#6  0x00007feb7ab5bc1d handle_xdg_surface_commit (libwlroots.so.9 + 0x5bc1d)
#7  0x00007feb7ab71db9 surface_commit_state (libwlroots.so.9 + 0x71db9)
#8  0x00007feb7ab729bb surface_commit.lto_priv.0 (libwlroots.so.9 + 0x729bb)
#9  0x00007feb7a270c04 ffi_call_unix64 (libffi.so.6 + 0x6c04)
#10 0x00007feb7a270108 ffi_call (libffi.so.6 + 0x6108)
#11 0x00007feb7abc9670 wl_closure_invoke.constprop.0 (libwayland-server.so.0 + 0x9670)
#12 0x00007feb7abcd6e4 wl_client_connection_data (libwayland-server.so.0 + 0xd6e4)
#13 0x00007feb7abcc21a wl_event_loop_dispatch (libwayland-server.so.0 + 0xc21a)
#14 0x00007feb7abcc985 wl_display_run (libwayland-server.so.0 + 0xc985)
#15 0x00005567ca7de1ec main (sway + 0x151ec)
#16 0x00007feb7a89d560 __libc_start_call_main (libc.so.6 + 0x2d560)
#17 0x00007feb7a89d60c __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x2d60c)
#18 0x00005567ca7de595 _start (sway + 0x15595)
```

- **Description:**
After updating to Fedora 35, Sway crashes when logging in from the default lightdm greeter. Interestingly, if I start directly from the console (ctrl+alt+f2, login, `sway`), it works. So there's something different which I cannot determine between how they are launched.

I also failed to get lightdm to produce a sway debug log, and need to ask for help to do so. I've edited `/usr/share/wayland-sessions/sway.desktop` so it should call `Exec=sway -d`. However, I still do not get a debug log. What am I missing here?

I do have core dumps, let me know if having them would help out with anything else than the trace.

**Comment by bl4ckb0ne** [comment]
Use `sway -Vd` to get the full debug log.

**Comment by carlpett** [comment]
Thanks, I'll try that. I've previously gotten _some_ log at least with `-d`, in this case I don't get one at all.
But I'll try `-Vd` and report back!

**Comment by carlpett** [comment]
Ah, seems lightdm outputs to `.xsession-errors`, which confused me. [Here's the log](https://gist.github.com/carlpett/ff7c36890928d2cd0c386d648089edde).
The 45s delay is me looking at a blank screen until I press $mod+enter, upon which it crashes.

One thing I notice is that Fedora apparently bundles `sway-systemd` in F35, including the cgroup assigning thing, which is new... Not sure if this is relevant, but highlighting it at least.

I'll check if it makes a difference to remove it tomorrow, but I need to turn in for the night now.

**Comment by johnae** [comment]
I know this may not be particularly helpful but using display managers has historically been discouraged and unsupported. See https://github.com/swaywm/sway/wiki for more and a link to a list of compatible ones (lightdm doesn't seem to be among those).

A recent possibly relevant (but closed) issue: https://github.com/swaywm/sway/issues/6655

**Comment by bl4ckb0ne** [comment]
You can try [greetd][1] and [gtkgreet][2] if you want to have a graphic login manager. But as mentionned in #6655, display managers arent doing too good with wayland.

Im closing the issue, it has nothing to do with sway/wlroots.

[1]: https://sr.ht/~kennylevinsen/greetd/
[2]: https://git.sr.ht/~kennylevinsen/gtkgreet

**Comment by carlpett** [comment]
While I agree that this is probably caused by something silly being done by the caller, and something which should be solved by whatever downstream created the packaging problem, is there really a situation where Sway **should** core dump?

**Comment by bl4ckb0ne** [comment]
It core dumps on a defensive assert [here](https://github.com/swaywm/sway/blob/eaeb173a4b9b22d8ba1b35d3d863f0dcb8595341/sway/tree/view.c#L712)
