### ISSUE TITLE
can't bindsym XF86PowerOff to execute a software

### ISSUE THREAD

**Issue by Relected** [swaywm/sway#6738]
hi, I use void linux with sway 1.6.1 with elogind

I wanted to make the power button excte a software instead of shutting down the system immedietly

I tried adding `bindsym XF86PowerOff exec wlogout` to my config file, but the software appears for a moment and then it shuts down immedietly

I also tried changing `/etc/elogind/logind.conf` and changed the power button to run wlogout instead of shutting down but it didn't work to

I tried adding this to my confid file instead `bindsym XF86PowerOff exec elogind-inhibit --what=handle-power-key wlogout` but the pc shuts down again immedietly right after when wlogout appears for a moment

is there a way to prevent the system from shutting down immedietly and instead executes a software?

EDIT: i realized that all lines on logind.conf are all commented out, which means that somehow desktop environments like xfce, KDE and gnome are the one controlling what happens when the power button is pressed and the system doesn't shut down automatically because of that

and neither sway or wlogout don't do that but do I make that happen?

**Comment by progandy** [comment]
You need to either disable the default action in ```logind.conf``` (```HandlePowerKey=ignore```) or you need to permanently run a daemon that inhibits it. (e.g. ```elogind-inhibit --what=handle-power-key sh``` or write something that inhibits reacts to the dbus key event sent by elogind as well)

**Comment by tobiasjakobi** [comment]
> EDIT: i realized that all lines on logind.conf are all commented out, which means that somehow desktop environments like xfce, KDE and gnome are the one controlling what happens when the power button is pressed and the system doesn't shut down automatically because of that

That's not how it works. If all lines are commented out, then the defaults apply. And the default for HandlePowerKey is poweroff.

**Comment by Relected** [comment]
@progandy ty
