### ISSUE TITLE
workspace_layout tabbed crash 

### ISSUE THREAD

**Issue by thuck** [swaywm/sway#674]
1) Configure sway to use "workspace_layout tabbed"
2) Open firefox on one workspace
3) Open konsole on another workspace
4) Press Mod4+w (bindsym $mod+w layout tabbed)
5) In the same workspace open konsole again
6) Sway crashes

[Crash Log - WLC_DEBUG=xwm sway -d &> /tmp/sway.log](https://gist.githubusercontent.com/thuck/da0499c42bf5230f3054608d694fa8d7/raw/d97ed02a8921dc13e5b314cfb45327117ccb976f/sway_workspace_layout_crash)

**Comment by VoidNoire** [comment]
I get something similar occurring when I set workspace_layout tabbed into my ~/.config/sway/config file: https://bbs.archlinux.org/viewtopic.php?id=215904

**Comment by okeri** [comment]
i  faced up to the same issue

**Comment by SirCmpwn** [comment]
I'm closing issues that are resolved by the yet-unreleased sway 1.0.
