### ISSUE TITLE
Mirror each display output to its respective xwayland display as a screenshare workaround

### ISSUE THREAD

**Issue by ErikReider** [swaywm/sway#6759]
- **Description:**
Most applications that support screen sharing like Discord and MS Teams don't support the Wayland way of sharing your screen. These applications can only see the XWayland displays. So my proposal is to add a config option to mirror each display to its respective XWayland display for an easier screen sharing experience.

**Comment by emersion** [comment]
Sorry, we won't support this.

**Comment by ErikReider** [comment]
Is there a specific reason why?

**Comment by emersion** [comment]
It's not possible, and even if it was, we don't do workarounds, we prefer proper solutions.

**Comment by ErikReider** [comment]
Ok, thanks for your time! :)

**Comment by progandy** [comment]
See this list for options: https://gist.github.com/progandy/bff675311aa2c3b777a37abe81aa4b4d
and maybe some things here: https://github.com/swaywm/sway/wiki/Useful-add-ons-for-sway#remoterecording
