### ISSUE TITLE
Make it easier to add the --unsupported-gpu flag

### ISSUE THREAD

**Issue by xsrvmy** [swaywm/sway#6760]
Currently the only place to add the --unsupported-gpu flag involves editing the file inside `/usr/share/wayland-sessions` (or whatever the path is). Consequently, if the package manager updates sway and overwrites the edited file, the session would fail to start. It would be much more user-friendly if one of the following is done:
- Allow specifying the flag in the sway config file
- Ask on first launch (similar to the i3 prompt for mod1 vs mod4 on first launch)

BTW the unsupported-gpu flag should probably be unsupported-gpu-driver, because nouveau is supported right?

**Comment by xsrvmy** [comment]
BTW I think some sort of GUI response needs to be added to when sway is started without --unsupported-gpu flag regardless, because the console message is obviously not going to appear on screen if you use a login manager.

**Comment by emersion** [comment]
Sorry, I'm not really interested in making it easier to run Sway on unsupported GPUs.

**Comment by xsrvmy** [comment]
At least the flag should be mentioned in the readme or in the wiki section on GPU's. The current way of printing to stderr is not sufficient, because most people trying sway for the first time would be trying it from a login manager.

**Comment by tukusejssirs** [comment]
> The current way of printing to stderr is not sufficient, because most people trying sway for the first time would be trying it from a login manager.

Well, I’d suggest the opposite: to remove the `stderr` warning about the proprietary GPU (reasoning: I use `ly` desktop/login manager and it always prints that error on the screen after login in), however, I know that the Sway devs won’t change it unless they change their attitude towards proprietary GPUs (don’t need to support it, but don’t act like there is no one using it).

On the other hand, if you want to make it even more visible in the GUI, I am okay with that if I can turn it off.

---

Sorry for being a bit off topic, but is there any Sway fork for nVidia/proprietary GPUs? It could be just a script to modify some portions of Sway after cloning it and before building it. I wish it would be in the AUR.

**Comment by xsrvmy** [comment]
To silence warning, can't you redirect stderr to a file?

BTW I am on an optimus laptop, and the issue I had with nvidia driver was actually to do with wayland crash on resume from suspend (also affects KDE but not GNOME). Ended up fixing it by installing driver without opengl files and disabling the card to the WLR_DRM_DEVICES variable. I have no idea if sway works with nvidia as the rendering device though because my DP port uses intel.
