### ISSUE TITLE
Pinch gesture does not prevent hide_cursor

### ISSUE THREAD

**Issue by iyzana** [swaywm/sway#6765]
- **Sway Version:** 1.6.1

- **Debug Log:** https://trash.randomerror.de/x8szq/sway.log

- **Configuration File:**
  - Default configuration plus `seat * hide_cursor 2000` (and [this distro patch](https://raw.githubusercontent.com/archlinux/svntogit-community/master/sway/trunk/50-systemd-user.conf))

- **Description:**
  - The cursor hides even when a GESTURE_PINCH is active
  - The cursor does not reappear when starting a GESTURE_PINCH
  
When performing a pinch gesture on a touchpad (e.g. for zooming in the currently active window, which is supported by firefox) the cursor still hides after the configured delay.
When the cursor hides the application also stops responding to the pinch events until I move the cursor again to unhide it.
For the scrolling gesture this works correctly.

My guess, based on the following two log lines, is that sway does not know the pinch gesture and then ignores the events and stops passing them to the active application as soon as the cursor is hidden.
```
00:00:01.708 [DEBUG] [wlr] [backend/libinput/events.c:309] Unknown libinput event 806
00:00:01.711 [DEBUG] [wlr] [backend/libinput/events.c:309] Unknown libinput event 807
```

**Comment by Xyene** [comment]
Should be addressed in https://github.com/swaywm/sway/pull/4952.

**Comment by Xyene** [comment]
Actually, maybe not, could you try this patch?

```diff
diff --git a/sway/input/cursor.c b/sway/input/cursor.c
index d8b1abeb..e715f627 100644
--- a/sway/input/cursor.c
+++ b/sway/input/cursor.c
@@ -927,6 +927,7 @@ static void handle_pointer_pinch_begin(struct wl_listener *listener, void *data)
        struct sway_cursor *cursor = wl_container_of(
                        listener, cursor, pinch_begin);
        struct wlr_event_pointer_pinch_begin *event = data;
+       cursor_handle_activity_from_device(cursor, event->device);
        wlr_pointer_gestures_v1_send_pinch_begin(
                        cursor->pointer_gestures, cursor->seat->wlr_seat,
                        event->time_msec, event->fingers);
@@ -936,6 +937,7 @@ static void handle_pointer_pinch_update(struct wl_listener *listener, void *data
        struct sway_cursor *cursor = wl_container_of(
                        listener, cursor, pinch_update);
        struct wlr_event_pointer_pinch_update *event = data;
+       cursor_handle_activity_from_device(cursor, event->device);
        wlr_pointer_gestures_v1_send_pinch_update(
                        cursor->pointer_gestures, cursor->seat->wlr_seat,
                        event->time_msec, event->dx, event->dy,
@@ -946,6 +948,7 @@ static void handle_pointer_pinch_end(struct wl_listener *listener, void *data) {
        struct sway_cursor *cursor = wl_container_of(
                        listener, cursor, pinch_end);
        struct wlr_event_pointer_pinch_end *event = data;
+       cursor_handle_activity_from_device(cursor, event->device);
        wlr_pointer_gestures_v1_send_pinch_end(
                        cursor->pointer_gestures, cursor->seat->wlr_seat,
                        event->time_msec, event->cancelled);
```

**Comment by Xyene** [comment]
```
00:00:01.708 [DEBUG] [wlr] [backend/libinput/events.c:309] Unknown libinput event 806
00:00:01.711 [DEBUG] [wlr] [backend/libinput/events.c:309] Unknown libinput event 807
```

These should be `LIBINPUT_EVENT_GESTURE_HOLD_BEGIN` and `LIBINPUT_EVENT_GESTURE_HOLD_END` (https://gitlab.freedesktop.org/libinput/libinput/-/blob/main/src/libinput.h#L980), which wlroots handles as of https://github.com/swaywm/wlroots/pull/3047, but Sway does not yet.

**Comment by Xyene** [comment]
Thanks for confirming!

**Comment by iyzana** [comment]
Thanks!
