### ISSUE TITLE
need wlroots 0.16 which is not available

### ISSUE THREAD

**Issue by christianrauch** [swaywm/sway#6773]
- **Sway Version:** master

- **Description:**

I am trying to build sway from master. It fails with:
```
Dependency wlroots found: NO found 0.15.0 but need: '>=0.16.0' ; matched: '<0.17.0'
[...]
../src/meson.build:54:0: ERROR: Invalid version of dependency, need 'wlroots' ['>=0.16.0'] found '0.15.0'.
```

Currently, the repo at https://github.com/swaywm/wlroots only has version [0.14.1](https://github.com/swaywm/wlroots/releases/) and the repo at https://gitlab.freedesktop.org/wlroots/wlroots only has version [0.15.0](https://gitlab.freedesktop.org/wlroots/wlroots/-/tags). Is there another repo that has version 0.16.0? If so, that should be stated clearly in the build instructions.

**Comment by emersion** [comment]
wlroots 0.16 is unpublished. Sway master always requires wlroots master.
