### ISSUE TITLE
Unset xkb_variant

### ISSUE THREAD

**Issue by lilithium-hydride** [swaywm/sway#6777]
Let's say that you wish to toggle between `xkb_variant colemak_dh` and the default keymap provided by `xkb_layout us`. Currently, there does not appear to be any way to do this without restarting Sway, as the default variant doesn't have any identifying string to pass to `xkb_variant` (as per `man xkeyboard-config`).

As for how it could be implemented, just passing the layout string to `xkb_variant`  could set it to whatever keymap is provided by default on that layout (ex: `xkb_variant us`).

**Comment by RPigott** [comment]
Can't you just set multiple layouts and swap through them like normal? You can leave a field blank to not set it, i.e. `xkb_variant ,colemak_dh`.

Also, you can redefine your keymap to use the default variant by passing an empty string. From the command line you have to double quote an empty string b/c it will get lost on first parse otherwise, e.g.:

`swaymsg input type:keyboard xkb_variant '""'`

**Comment by lilithium-hydride** [comment]
I was having trouble getting the first suggestion to work, but the provided command works! I was indeed missing the extra layer of quotes in the command, much appreciated.

**Comment by RPigott** [comment]
> I was having trouble getting the first suggestion to work

You need to have the same number of configured layouts. E.g.

```
xkb_layout us,us
xkb_variant ,colemak_dh
```

for two us layouts with different variants. Make sure a grp key is set or just use the ipc to switch (by index, since apparently by relative index is broken atm #6011)

**Comment by lilithium-hydride** [comment]
> You need to have the same number of configured layouts. E.g.
> 
> ```
> xkb_layout us,us
> xkb_variant ,colemak_dh
> ```

This clears some of it up for me, but I unfortunately use this across multiple devices and it looks like I'll have to wait on #6740 in order to use `xkb_switch_layout next` with, for example, `type:keyboard`. I suppose I could write a small script to grab every device ID and pass them in with `swaymsg`, but the one extra keybind doesn't irk me enough to warrant bothering with it right now. For the time being, doing 
```
bindsym $mod+Control+Alt+1 input type:keyboard xkb_variant ""
bindsym $mod+Control+Alt+2 input type:keyboard xkb_variant colemak_dh
```
is fine for my usage.
