### ISSUE TITLE
[Sway 1.7 Release] Missing the height of tab title.

### ISSUE THREAD

**Issue by axionl** [swaywm/sway#6782]
- **Sway Version:**
  - sway version 1.7
  - wlroots version 0.15.0

- **Debug Log:**
  - [sway debug](https://gist.githubusercontent.com/axionl/2f0554069ef4999aeaf852a981915cf7/raw/e078120b33211bf36f251f621c8aeb2feb3a4be3/sway_debug.log)

- **Configuration File:**
  - [sway config](https://gist.githubusercontent.com/axionl/2f0554069ef4999aeaf852a981915cf7/raw/e078120b33211bf36f251f621c8aeb2feb3a4be3/sway%2520config)

- **Description:**
  - Build and update to the latest version (1.7)
  - Switch the  layout to `stacking` or `tabbed` mode.
  - There are three tab titles but stick together: ![image](https://user-images.githubusercontent.com/8396456/150671517-7578841b-c55d-4107-a99a-36d6cb42dafb.png)
  - Downgrade to the older version `(1.6.1)` without this problem.

**Comment by axionl** [comment]
I have solved this problem after I set the font size not to 0.

**Comment by rif** [comment]
How did you set the font size?

**Comment by Apppppppple** [comment]
For me `font "DejaVu Sans Mono" 14px` worked. The issue i had was that I had a comment at the end of the line, which didn't cause issues in 1.6 but does now apparently.

**Comment by ObiWahn** [comment]
Where did you set the font size?
