### ISSUE TITLE
Fullscreen: apps are not initally displayed / rendered correctly.

### ISSUE THREAD

**Issue by RicArch97** [swaywm/sway#6785]
- **Sway Version:**
  - Sway 1.7

- **Debug Log:**
  - [here](https://gist.github.com/RicArch97/4165751fc22bcbd09f41b529a37ae2ec)

- **Configuration File:**
  - [here](https://github.com/RicArch97/sway-dotfiles/tree/master/.config/sway)

- **Description:**
  - Start a game on Steam. In my case, it was Horizon Zero Dawn. In the game's settings, window mode was set to **fullscreen**. When the game starts, the frames do not seem to be fully rendered. ![2022-01-25T05:37:49,729536897+01:00](https://user-images.githubusercontent.com/61013287/151081310-200e81d2-0519-4f0e-963c-67847edb0a20.png) Game only goes to normal state when toggling fullscreen with `super + f`. So first toggle to tilting, and then back to fullsceen makes it behave like normal. I've seen similar behaviour with OBS studio (not in the logs) where i also had to toggle fullscreen first to make the app render correctly.

**Comment by rjd22** [comment]
It seems this happens because the screen is opened next to the steam screen not yet in Fullscreen mode.

It might be that opening the window floating would solve the issue. When I have some time I will test this.
