### ISSUE TITLE
Firefox does not show oversized menus

### ISSUE THREAD

**Issue by TAforever** [swaywm/sway#6786]
A week ago I wrote a reddit post about this issue (https://www.reddit.com/r/swaywm/comments/s73v2o/sway_performance_issues_in_firefox/) and today I updated to sway 1.7-1 and wlroots 0.15.0- 4 and the problem is still reproduced: a folder with a large number of bookmarks does not open, and a window with a choice of language does not open. It was not possible to post the log on Pastebin because it is too large, and there is only 512 kilobytes maximum. So I am attaching the log file.
[sway.log](https://github.com/swaywm/sway/files/7939633/sway.log)

**Comment by Emantor** [comment]
For reproduction: The toolbar menu is not displayed by default, it needs to be added by customizing the toolbar and adding the icon. I can reproduce on master.

**Comment by TAforever** [comment]
I do not quite understand you, English is not my native language, I communicate with the help of an interpreter. I haven't changed any settings, I have GNOME and Sway installed. Everything is displayed correctly in GNOME, but not on Sway. Follow the link to my post on Reddit, I recorded a video there so that you can understand what the problem is.

**Comment by Titaniumtown** [comment]
I cannot reproduce this issue and I don't know how this would be related to sway...

**Comment by kennylevinsen** [comment]
Sounds like https://bugzilla.mozilla.org/show_bug.cgi?id=1746812. This bug describes a scenario where large menus will not show, and in some cases cause the browser to crash.

**Comment by xzsk2** [comment]
can confirm here, sway 1.7-2 and wlroots 0.15.1-2
Looks like if the bookmarks are more than the screen can display, it will not show. on my screen can't display more than 26 bookmarks in one folder, depends on dpi i think

**Comment by TAforever** [comment]
> For reproduction: The bookmark button is not displayed by default, it needs to be added by customizing the toolbar and adding the icon. I can reproduce on master.
> 
> Edit: fix the sentence.



For reproduction: The bookmark button is not displayed by default, it needs to be added by customizing the toolbar and adding the icon. I can reproduce on master.

Edit: fix the sentence.

**Comment by TAforever** [comment]
> For reproduction: The bookmark button is not displayed by default, it needs to be added by customizing the toolbar and adding the icon. I can reproduce on master.
> 
> Edit: fix the sentence.

The problem is solved in the git version, I close this issue.

**Comment by pm4rcin** [comment]
@TAforever could you tell which commit has fixed the issue? Because the same problem exists in [dwl](https://github.com/djpohly/dwl).
