### ISSUE TITLE
Display corruption on nouveau

### ISSUE THREAD

**Issue by mightyiam** [swaywm/sway#6789]
![IMG_20220127_130446](https://user-images.githubusercontent.com/635591/151303327-1e6c75ea-d142-40f6-a959-e37c4f5f8930.jpg)
![IMG_20220127_130458](https://user-images.githubusercontent.com/635591/151303340-12e6981b-e8d1-4bf1-879f-2ff382a625ce.jpg)
Video: https://photos.app.goo.gl/Hg9v6z8fzrRKzL5bA

Version information seems to be included in the log:
[sway.log](https://github.com/swaywm/sway/files/7948071/sway.log)

**Comment by mightyiam** [comment]
This is using the default config file.

Do these provide a hint it the cause of the issue? A permissions problem?

```
00:02:59.564 [DEBUG] [wlr] [backend/drm/legacy.c:171] connector DP-2: drmModeSetCursor failed: Permission denied
00:02:59.564 [DEBUG] [wlr] [backend/drm/legacy.c:171] connector DP-1: drmModeSetCursor failed: Permission denied
```

**Comment by adamjbc** [comment]
I have the same problem.  Seems to works when I switch to the CPU's (Intel 8700k) onboard graphics, but not working using graphics card (1050Ti, nouveau drivers).

**Comment by emersion** [comment]
Can you try unsetting `WLR_DRM_NO_MODIFIERS`?

**Comment by adamjbc** [comment]
That fixed it, thanks!

**Comment by mightyiam** [comment]
@emersion unsetting `WLR_DRM_NO_MODIFIERS` did the trick. Happy :tada:

**Comment by lebe-dev** [comment]
Hi. I have the same issue with nouveau driver after arch system update.

My CPU is 12700K (Alder Lake), Intel driver will be shipped with kernel 5.18 so i have to use nouveau with GTX 1080.

Variable `WLR_DRM_NO_MODIFIERS` is set to 1. Also i did bash-script wrapper with export `WLR_DRM_NO_MODIFIERS`, it didn't help :(

Any suggestions?

**Comment by mightyiam** [comment]
@lebe-dev unset that variable.

**Comment by lebe-dev** [comment]
> @lebe-dev unset that variable.

i've tried this approach yesterday and it didn't work.
After your advice i've checked again all places: `/usr/share/wayland-sessions/sway.desktop`, `~/.bashrc` and `/etc/profile`, add `unset` for that variable.

Now It works. Thanks!

p.s.: Topic is too complex to me, i feel like a monkey :/

**Comment by mightyiam** [comment]
@lebe-dev no need to `unset` if it is never set. There are no monkeys here.

**Comment by lebe-dev** [comment]
> @lebe-dev no need to `unset` if it is never set. There are no monkeys here.

I did that as quick fix and will remove it today of course.

I feel like a monkey because I don't understand what `WLR_DRM_NO_MODIFIERS` does and related stuff. Topic is too  complex for me. I love Sway but digging inside guts of nouveau (bugs), desktop environment is too much :)

Thanks again.
