### ISSUE TITLE
DEADZONE for XWayland apps if output starts at negative position

### ISSUE THREAD

**Issue by Microwave-WYB** [swaywm/sway#6790]
### Please fill out the following:
- **Sway Version:** 1.6.1

- **Description:**
  - In my output config, I configured 3 displays with the following values:
    ```
    output eDP-1 pos 0     0   res 2256x1504 scale 1.5
    output DP-4  pos 1504 -300 res 1920x1080 transform 270
    output DP-3  pos 2584 -300 res 3840x2160 scale 1.5
    ```
    I set the `y` values to `-300` because those two screens appear to be higher than the first screen, which `-300` make them perfectly match my setup. 

    This is no problem at all for native Wayland apps, but I found these settings will make XWayland apps unable to click within that `-300` region, thus leads to a "deadzone". Xwayland seems to recognize all click events in the negative region as a click on `0`. For example, clicking at `100, -100` will result in a click at `100, 0`.

- **Fix suggestions**: either output a warning or error when applying these negative values, or fix XWayland to recognize click events at negative positions.

**Comment by Emantor** [comment]
This is an Xwayland bug, see https://gitlab.freedesktop.org/xorg/xserver/-/issues/899

**Comment by emersion** [comment]
Closing because this isn't a Sway bug.
