### ISSUE TITLE
interface 'wl_output' has no event 4

### ISSUE THREAD

**Issue by erfanmola** [swaywm/sway#6794]
Hi, any electron based app or chromium app I try to open on sway, crashes :
```
interface 'wl_output' has no event 4
/usr/bin/google-chrome: line 2:  2980 Trace/breakpoint trap   (core dumped) google-chrome-stable --enable-features=UseOzonePlatform --ozone-platform=wayland
```

**Comment by emersion** [comment]
This is a Chromium bug, fixed in their latest snapshot, not sure the fix is released yet.

**Comment by OctopusET** [comment]
Fix is merged to chromium version 98. It will be released on Feb, 1
