### ISSUE TITLE
add a a way to set properties for windows

### ISSUE THREAD

**Issue by alexmo1997** [swaywm/sway#6795]
# description
I think there should be a way to set properties like the app_id when you start a program.

# use case
I have two monitors, each with a workspaces I usually use for firefox and thus I would want to be able to autostart firefox with two windows where one of them gets moved to one workspace and the other to the second one.
Firefox is sadly not able to do this (except if I used two separate firefox profiles, which I don't want to do) and thus the only possible way (please correct me if I'm wrong but I haven't found another way) would be this feature. 

I know that you are not implementing functionality that is not present in i3, but this is possible in i3 using some Xorg tools like xdotool or xprop, so I suppose this classifies as something you might implement?

And yes, another way would be to fix this upstream in firefox, but as said, this is something you can do in i3 and I don't really have much hope for them to implement this kind of feature (at least in the near future).

**Comment by Emantor** [comment]
Sway supports marks, you may be able to start the firefox window, attach a mark to its window and have sway act on the mark.

**Comment by emersion** [comment]
Sorry, we aren't interested in implementing this.
