### ISSUE TITLE
wf-recorder on wlr_renderer vulkan

### ISSUE THREAD

**Issue by fuzunspm** [swaywm/sway#6796]
### Please fill out the following:
- **Sway Version:**
  - sway version 1.7

- **Description:**
  - Setting WLR_RENDERER to vulkan breaks wf-recorder with the issue below
  [https://github.com/ammen99/wf-recorder/issues/163#issuecomment-1024590781](#163)

**Comment by bl4ckb0ne** [comment]
The wlroots vulkan renderer doesn't support screencopy [yet](https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3290)

**Comment by xiliuya** [comment]
I wrote a screenshot tool that can screenshot in Vulkan Sway.
[https://aur.archlinux.org/packages/swayvkshot](swayvkshot)
