### ISSUE TITLE
Add alias for --unsupported-gpu

### ISSUE THREAD

**Issue by morr0ne** [swaywm/sway#6797]
Sway 1.7 replaced the flag --my-next-gpu-wont-be-nvidia with --unsupported-gpu. This change makes total sense but unfortunately it has also broken tons of machines and vms where my login file included "exec sway --my-next-gpu-wont-be-nvidia". It would be nice if sway could still recognize the option, maybe in a deprecated form, so that user such as me have some breathing room to update their config files.

**Comment by fluix-dev** [comment]
If we're following semver, this should indeed only be part of 2.0, right?

**Comment by emersion** [comment]
This flag is undocumented, ie. it can change anytime and isn't part of any stability guarantee.

**Comment by morr0ne** [comment]
As @emersion said, the flag isn't documented at all so it shouldn't really matter for semver compatibility. A patch update like 1.7.1 should be enough.

**Comment by fluix-dev** [comment]
Ah fair enough. Didn't realize it was undocumented.

**Comment by morr0ne** [comment]
@fluix-dev this is what the output of the help command is:
```zsh
~ sway --help
Usage: sway [options] [command]

  -h, --help             Show help message and quit.
  -c, --config <config>  Specify a config file.
  -C, --validate         Check the validity of the config file, then exit.
  -d, --debug            Enables full logging, including debug information.
  -v, --version          Show the version number and quit.
  -V, --verbose          Enables more verbose logging.
      --get-socketpath   Gets the IPC socket path and prints it, then exits.
```
The only way to know about --unsupported-gpu/--my-next-gpu-wont-be-nvidia is either by reading the wiki or by running sway and getting this output:
```zsh
~ sway
00:00:00.002 [sway/main.c:65] Proprietary Nvidia drivers are NOT supported. Use Nouveau. To launch sway anyway, launch with --unsupported-gpu and DO NOT report issues.
```
Unfortunately I don't have much experience with C to make a PR but it should be simple enough to implement

**Comment by chen244** [comment]
Maybe some config file under /etc to open unsupport gpu. Otherwise, When sway is upgrade , I should edit the sway.desktop again..

**Comment by bl4ckb0ne** [comment]
The flag is not likely to change in future releases. I'm not too fond of giving more time and effort to unsupported GPUs.
