### ISSUE TITLE
security: rofi stays visible on top of screen locker

### ISSUE THREAD

**Issue by primalmotion** [swaywm/sway#6800]
### Please fill out the following:
- **Sway Version:** sway version 1.8-dev-cd1ee0e1 (Jan 29 2022, branch 'master'

- **Description:**
If you leave rofi window open, then let swayidle lock the screen (I'm using swaylock), the rofi window stays visible and usable, over the lockscreen. This can be potentially be very dangerous, as raw commands from rofi are executed without any issue.

**Comment by emersion** [comment]
This shouldn't be the case anymore with the session-lock protocol.
