### ISSUE TITLE
Kernel panic when running 'systemctl reboot' from an sway keybinding

### ISSUE THREAD

**Issue by Zeioth** [swaywm/sway#6834]
If I run this command, the logout goes gracefuly

    systemctl reboot

But if I run the same command through an sway keybinding, it produces a kernel panic that freezes the computer.

**Version**: wlroots-git/sway-git.

[Coredump](https://pastebin.com/XWQkzYRd)  (coredumpctl gdb swaybg)
Kernels tested: Arch kernel, Zen kernel.

![20220215_023456.jpg](https://user-images.githubusercontent.com/3357792/153990468-5c4fcb62-9943-45e7-8580-355d0f40eefc.jpg)

**Comment by emersion** [comment]
If it's a kernel panic, it's a kernel bug. Please report it upstream.
