### ISSUE TITLE
Switching keyboard layouts via swaymsg stops working after a while

### ISSUE THREAD

**Issue by luispabon** [swaywm/sway#6837]
### Please fill out the following:
- **Sway Version:**
```
Sway 1.7-5543acff
wlroots 4377b552
```
These versions are as close as I can get to master on Ubuntu 21.10 given the versions of wayland-server and protocols that are available.

- **Debug Log:**
[Log when layout switching does not work](https://github.com/swaywm/sway/files/8099500/sway-lang-switch.log)
[Log when layout switching works](https://github.com/swaywm/sway/files/8099501/sway-lang-switch-good.log)

- **Configuration File:**
https://github.com/luispabon/sway-dotfiles/blob/master/configs/sway/conf.d/inputs

- **Stack Trace:**
n/a

- **Description:**
I have 2 keyboard layouts configured on my setup, GB's English and Spain's Spanish. 

```
input type:keyboard {
    xkb_layout gb,es
}
```

I toggle one or the other with:

```
~ swaymsg input 'type:keyboard' xkb_switch_layout next
```

This works fine on a pristine session, but as the hours pass it eventually ceases to function - I get stuck on one of the two layouts, and running the command above has no effect.

I've attached logs for when it works, and when it does not.

**Comment by mhdzli** [comment]
You can use  `swaymsg input "<YOUR KEYBOARD IDENTIFIER>" xkb_switch_
layout next`

**Comment by kerneis-anssi** [comment]
I think it's a duplicate of #6011

**Comment by luispabon** [comment]
Yes it is, gonna close this in favour of that. Thanks for the heads up 👍🏽
