### ISSUE TITLE
one command not execute from sway but execute from terminator

### ISSUE THREAD

**Issue by superiums** [swaywm/sway#6840]
It's very strage that one script could work in terminator but not in sway.
i'm tring to switch windows in sway. i followed the man page of wofi, and found this script will work.

- **Sway Version:*1.7*
- Arch os.

- **Configuration File:**
- sway config:
```
set $switcher 'sway-switch'
bindsym --to-code {
    Alt+Tab exec --no-startup-id $switcher
    $mod+z exec --no-startup-id $switcher
}
```

- the script in sway-switch.sh:
```shell
#!/usr/bin/sh

 swaymsg -t get_tree |
    jq -r '.nodes[].nodes[] | if .nodes then [recurse(.nodes[])] else [] end  +  .floating_nodes  |  .[]  |  select(.nodes==[]) | ((.id | tostring) + " " + .name)' |
    wofi --show dmenu -W 600 -w 1 -p "" -Gi --term alarcritty | 
    {    read -r id name
        swaymsg "[con_id=$id]" focus
    } 
```

- **Description:**
  - The scritp works if start from terminator.
  - The script not work through the keybinding of sway.
  
(i've tried to write the script in sway config too, but always some format err occurs, so i put the script in a single file.)

**Comment by superiums** [comment]
I'm tring to find some err logs and strated from tty, And found this issue only occurs if i login with sddm, and not occurs if i start sway from tty.
but after login through sddm, every other keybindings works well except this one. maybe the Alt+Tab used by sddm, but $mod+z is not. this is very strange.

**Comment by bl4ckb0ne** [comment]
Display managers are not officially supported because they can lead to that kind of issue.

There's some doc about using sddm in the [wiki](https://github.com/swaywm/sway/wiki/Setting-Environmental-Variables) but we wont provide any support.
