### ISSUE TITLE
would it be possible to add -Dsd_bus=none?

### ISSUE THREAD

**Issue by a-m-joseph** [swaywm/sway#6843]
Hello, as part of the packaging of sway in nixpkgs, when the build is configured to omit systemd, we use `-Dsd_bus=basu`.

This appears to work, but is a bit confusing for people reading the packaging file.

I was asked [here](https://github.com/NixOS/nixpkgs/pull/160972#discussion_r811411976) to inquire if upstream would be willing to add a `none` option for `sd_bus` to make this more obvious.  If you would like me to write the PR let me know.

**Comment by emersion** [comment]
Set `-Dtray=disabled`, then sd-bus won't be looked up.

**Comment by a-m-joseph** [comment]
Thanks.  For the record, `meson` still requires that `sd-bus-provider` is one of the four supported options, even when `-Dtray=disabled`:

```
meson flags: ...        -Dauto_features=enabled   ... -Dsd-bus-provider=none -Dtray=disabled
meson.build:1:0: ERROR: Value "none" (of type "string") for combo option "Provider of the sd-bus library" is not one of the choices. Possible choices are (as string): "auto", "libsystemd", "libelogind", "basu".
```

I guess you are saying that the `sd-bus-provider` value is ignored in this case.  It would have been nice to have a `none` value to use, so that we would notice if sway ever changed this policy.  But instead we can use `basu`, since it is not packaged for nix so we can be sure that any attempt to depend on it would fail.
