### ISSUE TITLE
SIGSEGV when pulling out USB devices

### ISSUE THREAD

**Issue by nazarewk** [swaywm/sway#6856]
- **Sway Version:**
  - Sway at https://github.com/swaywm/sway/tree/0ee54a524329ab8d3db7dbe8286dc97b0bf57bed
  - installed through https://github.com/nix-community/nixpkgs-wayland/blob/f97d635541fb778d46b1bc5767c796c2d0005de7/pkgs/sway-unwrapped/metadata.nix

- **Debug Log:**
  	looks like this is the relevant part https://gist.github.com/nazarewk/28d531e41377125107a36c0eaefdf3e5#file-logs

- **Configuration File:**
	 mostly this https://github.com/nazarewk-iac/nix-configs/blob/d22b60c685b47870339223fb4bcf29131f3af6bc/users/nazarewk/sway/config

- **Stack Trace:**
   	https://gist.github.com/nazarewk/28d531e41377125107a36c0eaefdf3e5#file-coredump

- **Description:**
  	~~No idea what are steps to reproduce, it happened in seconds after i have closed a Firefox window after exiting Google Meet call.~~
  	I am getting reproducible crashes every time i plug out my YubiKey or turn off bluetooth headset (with some buttons included).

**Comment by nazarewk** [comment]
I'm running it with [`--verbose --debug`](https://github.com/nazarewk-iac/nix-configs/commit/12db0474), but I can't really spend more time on it unless it keeps crashing (so far just 1 occurence)

**Comment by nazarewk** [comment]
@bl4ckb0ne I've second crash with `--verbose --debug`: https://gist.githubusercontent.com/nazarewk/4818a797fecfe6f491b30374e6f54b06/raw/587ec229c46f5ff10ac502851a4bc9a4205c3f3e/sway%2520log%2520before%2520crash

**Comment by nazarewk** [comment]
Also happened today

**Comment by nazarewk** [comment]
I can confirm it is not confirmed to exiting Google Meets/Firefox, but to losing connection to or adding USB devices:
- i know one of my USB hubs is flaky (reconnects randomly)
- just got a crash on pulling out Yubikey

switched all devices to the stable HUB to see if it helps

**Comment by bl4ckb0ne** [comment]
```
Feb 28 10:57:46 nazarewk-krul /nix/store/98sf58748yqq51197whkqc4ik0sr2mmh-gdm-41.3/libexec/gdm-wayland-session[4258]: 02:34:47.371 [DEBUG] [wlr] [backend/libinput/events.c:226] Removing Earmuffs (AVRCP) [158:16420]
Feb 28 10:57:46 nazarewk-krul /nix/store/98sf58748yqq51197whkqc4ik0sr2mmh-gdm-41.3/libexec/gdm-wayland-session[4258]: 02:34:47.371 [DEBUG] [sway/input/input-manager.c:202] removing device: '158:16420:Earmuffs_(AVRCP)'
Feb 28 10:57:46 nazarewk-krul /nix/store/98sf58748yqq51197whkqc4ik0sr2mmh-gdm-41.3/libexec/gdm-wayland-session[4258]: 02:34:47.371 [DEBUG] [sway/input/seat.c:959] removing device 158:16420:Earmuffs_(AVRCP) from seat seat0
```

It works when plugged in and crashes when plugged out, is that right? Could you give me the output of `swaymsg -t get_inputs` when plugged please.

**Comment by nazarewk** [comment]
I guess this is what you're interested in:
```
nazarewk@nazarewk-krul ~ % swaymsg -t get_inputs
Input device: Earmuffs (AVRCP)
  Type: Keyboard
  Identifier: 158:16420:Earmuffs_(AVRCP)
  Product ID: 16420
  Vendor ID: 158
  Active Keyboard Layout: Polish
  Libinput Send Events: enabled
```

**Comment by bl4ckb0ne** [comment]
Could you try https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3469? Bear in mind that it's very much a wip.

**Comment by nazarewk** [comment]
FYI: I'm getting reproducible crashes every time I turn off the headset or plug out any of my YubiKeys from 2 different machines (got intel-based dell laptop & amd-based desktop)

**Comment by nazarewk** [comment]
@bl4ckb0ne using `wlroots` from your last commit didn't change anything for me
see https://github.com/nazarewk-iac/nix-configs/commit/7fa4bc54a78af1a5969ea4156342f6d58ef70a87

**Comment by bl4ckb0ne** [comment]
Is the nix config pointing to the right repo? The branch/commit is on my personal repo, not the wlroots one.

The regression was accidentally introduced in https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3434, anything prior to this should not have it. wlroots 0.15.1 is also good.

**Comment by nazarewk** [comment]
> The regression was accidentally introduced in [gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3434](https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3434), anything prior to this should not have it. wlroots 0.15.1 is also good.

Thanks for info, I will be r[olling back to the `nixpkgs-unstable`](https://github.com/nazarewk-iac/nix-configs/commit/92d96dca4221be74d10413295c4a40133a003faa#diff-5df5e5c7fee281fd834534d02a697fcd4e5e36342670cd231e8bebee65cac434R17) (which holds Sway 1.7 with wlroots 0.15.1) as doesn't look like i need `nixpkgs-wayland` (bleeding edge commits) anymore with 1.7 released.

Let me know if you have changes that need testing I should be able to more or less quickly switch back.

**Comment by bl4ckb0ne** [comment]
I'll continue and get the patches merged, I'll update the issue when it's merged so you can test and close it. Thanks for your feedback.

**Comment by bl4ckb0ne** [comment]
2 patches recently got merged, could you try sway/wlroots master please.

**Comment by Artturin** [comment]
works 
```
(self: super: {
  wlroots = super.wlroots.overrideAttrs (oldAttrs: {
    src = super.fetchFromGitLab {
      domain = "gitlab.freedesktop.org";
      owner = "wlroots";
      repo = "wlroots";
      rev = "cfed039c9a353cff5d8c3c678d7eb272c887de77";
      sha256 = "sha256-NleC+PoYM5qKTU2Ji4GUIx5hT4GOdHt6g/j9rHENyhM=";
    };
  });
})
```

**Comment by bl4ckb0ne** [comment]
Glad to see it works. I'll close the issue, reopen if it occcurs again.
