### ISSUE TITLE
Full screen corruption for some applications

### ISSUE THREAD

**Issue by zdykstra** [swaywm/sway#6859]
### Please fill out the following:
- **Sway Version:** 1.7

- **Debug Log:**
[sway.log](https://github.com/swaywm/sway/files/8165581/sway.log)

- **Configuration File:**
[config.minimal.txt](https://github.com/swaywm/sway/files/8165587/config.minimal.txt)

- **Description:**
Setting some windows (mpv, kitty, alacritty) as full screen on un-rotated displays results in heavy pixelation / corruption. Moving the window to a rotated output (270 degrees or 180 degrees) and then full screening it works as expected.

![0301221825_HDR](https://user-images.githubusercontent.com/13874853/156271468-4702feeb-9939-46d4-ba2b-0284d04a638f.jpg)

I'm happy to provide any additional details, test cases, etc.

**Comment by emersion** [comment]
Can you obtain a `drm_info` log when running with fullscreen corruption?

This looks like a buffer tiling mismatch. This is an a card without modifiers support.

**Comment by emersion** [comment]
This is likely fixed by https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=2f350ddadca3b96c72ed1481875f0b8fc1a01612 released in kernel 5.16.

**Comment by zdykstra** [comment]
> This is likely fixed by https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=2f350ddadca3b96c72ed1481875f0b8fc1a01612 released in kernel 5.16.

I can confirm that this appears to be working in kernel 5.16. I'm able to full screen `kitty` with out issues.  Where can I find `drm_info` ? I'm happy to upload a log from that.
