### ISSUE TITLE
Crash during suspend

### ISSUE THREAD

**Issue by luispabon** [swaywm/sway#6860]
### Please fill out the following:
- **Sway Version:**
sway version 1.8-dev-061ffc30 (Mar  1 2022, branch 'master')
wlroots c84744321edf3e5f083feb01addd82eae0969e31 (latest master as of today)
Ubuntu 22.04

- **Debug Log:**
https://pastebin.ubuntu.com/p/rDpBPJHHxF/  

The debug log starts with me activating the wofi menu I use to power-cycle the laptop. In this case I chose suspend.

- **Configuration File:**
Inputs only: https://github.com/luispabon/sway-dotfiles/blob/master/configs/sway/conf.d/inputs
All conf: https://github.com/luispabon/sway-dotfiles/blob/master/configs/sway

- **Stack Trace:**
https://pastebin.ubuntu.com/p/tgr6m6GgBm/

- **Description:**
Crash happened apparently during suspend. The lock screen (swaylock) activated correctly. 

This crash is new, previously I was running sway and wlroots pre-1.7 from december or so, last version I could rightly compile in Ubuntu 21.10.

**Comment by bl4ckb0ne** [comment]
Could you try https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3460, and if it still fails, https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3469 please. Bear in mind that the latest is a WIP and may crash elsewhere.

**Comment by luispabon** [comment]
Thank you @bl4ckb0ne , I checked out your branch and rebuilt everything. I'll report back.

**Comment by luispabon** [comment]
@bl4ckb0ne so far so good, I've had no crashes since.

**Comment by bl4ckb0ne** [comment]
Glad to hear that. I'll close the issue, reopen it if the crash reoccurs.
