### ISSUE TITLE
Unable to select some archive types in nautilus

### ISSUE THREAD

**Issue by TAforever** [swaywm/sway#6864]
STEPS TO REPRODUCE:
1) open nautilus
2) select any file or folder
3) open context menu
4) compress
5) open the archive type selection window
6) the third and fourth type of archive is not captured by focus from the mouse cursor

Sway 1.7

**Comment by bl4ckb0ne** [comment]
Can you try with sway/wlroots master?

**Comment by TAforever** [comment]
> Can you try with sway/wlroots master?

Yes, the issue is reproducible on sway-git version r6884.061ffc30-1 and wlroots-git version 0.16.0.r5402.39b68ea4-1

**Comment by TAforever** [comment]
> > Can you try with sway/wlroots master?
> 
> Yes, the issue is reproducible on sway-git version r6884.061ffc30-1 and wlroots-git version 0.16.0.r5402.39b68ea4-1

Also, I found a deterioration in the git version: if you hover over the clock-module, the pop-up window with the calendar is halfway out of the screen. I understand that the git version is not a stable release, but I think that this information will be useful for you.

**Comment by bl4ckb0ne** [comment]
@vyivel could it be a regression from the xdg-popup refactor?

@TAforever can you provide a full debug log please.

**Comment by TAforever** [comment]
> @vyivel could it be a regression from the xdg-popup refactor?
> 
> @TAforever can you provide a full debug log please.

Here is the log https://pastebin.com/fSRQbKMS , I also want to add that the clock module means waybar.

**Comment by vyivel** [comment]
> could it be a regression from the xdg-popup refactor?

Not the original issue, I can reproduce this on Sway 1.6 / wlroots 0.13.0.
This has something to with the way Sway determines the container at the specified position, and the fact that Nautilus archive type menu is not an `xdg_popup`, but a `wl_subsurface`.

> Also, I found a deterioration in the git version: if you hover over the clock-module, the pop-up window with the calendar is halfway out of the screen. I understand that the git version is not a stable release, but I think that this information will be useful for you.

```
shimarin $ ~ WAYLAND_DEBUG=1 waybar 2>&1 | grep xdg_positioner
[4094418.599]  -> xdg_wm_base@36.create_positioner(new id xdg_positioner@42)
[4094418.609]  -> xdg_positioner@42.set_size(176, 169)
[4094418.615]  -> xdg_positioner@42.set_anchor_rect(1832, -4, 92, 38)
[4094418.625]  -> xdg_positioner@42.set_offset(0, 0)
[4094418.634]  -> xdg_positioner@42.set_anchor(2)
[4094418.640]  -> xdg_positioner@42.set_gravity(2)               # bottom
[4094418.648]  -> xdg_positioner@42.set_constraint_adjustment(9) # slide_x | flip_y
```

As per `xdg-shell.xml` (emphasis mine):

>Slide the surface along the x axis until it is no longer constrained.
>
>First try to slide **towards the direction of the gravity on the x axis**
>until either the edge in the opposite direction of the gravity 
>unconstrained or the edge in the direction of the gravity is
>constrained.
>
>Then try to slide **towards the opposite direction of the gravity on the
>x axis** until either the edge in the direction of the gravity is
>unconstrained or the edge in the opposite direction of the gravity is
>constrained.

The way I understand this, `slide_x` is a no-op if the gravity isn't present on the X axis.
https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/types/xdg_shell/wlr_xdg_positioner.c#L346

As such, either the protocol is misleading, I can't read, or Waybar (GTK?) is buggy.

Note, KWin ignores any mention of gravity when sliding: https://invent.kde.org/plasma/kwin/-/blob/master/src/xdgshellclient.cpp#L1887

**Comment by TAforever** [comment]
Due to the update of Nautilus, the problem is no longer relevant
