### ISSUE TITLE
Random crashes involving the functions  xkb_keymap_layout_get_name and xkb_state_layout_index_is_active

### ISSUE THREAD

**Issue by zsolt-donca** [swaywm/sway#6865]
### Please fill out the following:
**Sway Version:**
I am using the hidpi patch set ([sway-hidpi-git](https://aur.archlinux.org/packages/sway-hidpi-git), [wlroots-hidpi-git](https://aur.archlinux.org/packages/wlroots-hidpi-git)). 

On 2022-02-23 and 24, i was using b38b845c for sway and [e279266f](https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/e279266f714c7122e9ad97d56d047313f78cfdbe) for wlroots. 
On 2022-03-01 and 02, I built and used the more recent commits 061ffc30 / [c8474432](https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/c84744321edf3e5f083feb01addd82eae0969e31) as well, and had the same issue.

The latest commits that I know of that don't have the issue are f707f583 / [252b2348](https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/252b2348bd62170d97c4e81fb2050f757b56d67e) (I've been using these since).

**Debug Log:**

I am running sway as a systemd user service with the `-d` flag. I have the logs from two boots containing seven crashes in total:
- boot from 2022-02-23 to 24, containing three crashes: https://ufile.io/uopnhbvp (compressed because the uncompressed logs were ~300 MB)
- from 2022-03-01 to 02, containing four crashes: https://gist.github.com/zsolt-donca/c5475d31e2a01c3b7c675d3bf00223fc

**Configuration File:**
Since the crashes are random, I don't have a reliable way to reproduce them; I've experienced them while normally using my computer, with my normal config file: https://gist.github.com/zsolt-donca/54ce1bd581514e887825795ef9a396e8

I can try reproducing with reduced config files if needed.

**Stack Trace:**
Crash 1 on 2022-02-23: https://gist.github.com/zsolt-donca/feb6a71c799bcdb80af4a3ee7f0aad1b
Crash 2 on 2022-02-23: https://gist.github.com/zsolt-donca/706cc3168f3b07ba9c043190ae207459
Crash 3 on 2022-02-24 : https://gist.github.com/zsolt-donca/9c7672b30f49ced6beeaffe45fda7a2c

Crash 4 on 2022-03-01: https://gist.github.com/zsolt-donca/fa0245ccf237b18156be0cb7b9aa56a6
Crash 5 on 2022-03-01: https://gist.github.com/zsolt-donca/693e29f0580ecb1bbed26cf558361e1b
Crash 6 on 2022-03-01: https://gist.github.com/zsolt-donca/f64feccf58bc59220db1e947bb61708b
Crash 7 on 2022-03-02: https://gist.github.com/zsolt-donca/c4b97f55a9d9f50b7de3467c7f29b163

**Description:**
Sway randomly crashes for me, not long after startup. I didn't observe any apparent pattern in what action causes it to crash. The stack traces contain references to the functions xkb_keymap_layout_get_name and xkb_state_layout_index_is_active.

I am on Arch Linux with latest packages (at the moment of the crashes). In case it's relevant, I am using an external USB keyboard and my laptop's built-in keyboard as well with three layouts, and a script that automatically switches layouts based on the application window in focus.

**Comment by bl4ckb0ne** [comment]
Can you try https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3469 please

**Comment by zsolt-donca** [comment]
@bl4ckb0ne Have been using a wlroots built based on the branch of that merge request (plus the hidpi patches), and the latest sway since this morning. So far so good, haven't had any crashes or other issues. Will get back here in case I discover something, or after a couple of days in case there are no crashes.

**Comment by bl4ckb0ne** [comment]
I'll close the issue, reopen it if the crash happens again.
