### ISSUE TITLE
Keybindings can't call up any applications

### ISSUE THREAD

**Issue by glyh** [swaywm/sway#6885]
### Please fill out the following:
- **Sway Version:** sway version 1.7

- **Debug Log:**
   https://gist.github.com/glyh/043528accc199dcba5b1d9954df02cb5

- **Configuration File:**
   /etc/sway/config

- **Description:**
  After a recent update of my system, my sway config dead. I try to reproduce with vanilla sway, it's also not working. Specifically, in the default config, I can't fire up foot with Super+Enter, I can't exit with Super+Shift+E.

- **Additional information**
The title bar says `error reading from status command`.

**Comment by emersion** [comment]
This debug log is incomplete.

**Comment by glyh** [comment]
@emersion fixed.

**Comment by emersion** [comment]
Everything looks like foot is started up normally from the Sway side.

```
00:00:09.443 [DEBUG] [sway/commands/bind.c:617] running command for binding: exec foot
00:00:09.443 [INFO] [sway/commands.c:258] Handling command 'exec foot'
00:00:09.443 [DEBUG] [sway/commands/exec_always.c:46] Executing foot
00:00:09.452 [DEBUG] [sway/commands/exec_always.c:92] Child process created with pid 7563
```

**Comment by emersion** [comment]
Note, you are running with the X11 backend (ie you're starting Sway from within an Xorg server instance). Is that intentional?

**Comment by glyh** [comment]
Not intentional, but guess I have to because I can't exit this with any keybindings. If I just run this in display manger, I would be dropped in an environment I can't exit, having to shutdown manually. ttys does not work anymore but I don't know why.(Is it alt+f1~f8?)

**Comment by glyh** [comment]
OK, I figured out that it's because my system is broken and `sh` is linked to some other files. Fixed after fixing sh.
