### ISSUE TITLE
Mouse clicks not registered when output position coordinate negative

### ISSUE THREAD

**Issue by CrfzdPQM6** [swaywm/sway#6894]
- **Sway Version: 1.7**
When I position an external monitor to the left of my primary monitor, I can no longer click on VisualStudio Code when it's running on that monitor. If I send VScode to a monitor positioned to the right of my primary monitor, or if I reposition the other external monitor to be also on the right, everything is fine. It is as if the clicks are registered at a different coordinate to the location of the pointer on screen.

Does Sway fall over with negative position coordinates?

Does not work:
output "Lenovo Group Limited LEN P27h-10 0x00000101" {
  resolution 2560x1440
  position -2560,0
}

Works fine:
output "Lenovo Group Limited LEN P27h-10 0x00000101" {
  resolution 2560x1440
  position 1920,0
}

**Comment by Estebiu** [comment]
It's a well known problem. Just try to avoid negative positions.

**Comment by emersion** [comment]
That's an Xwayland bug, not a Sway bug.

**Comment by CrfzdPQM6** [comment]
> It's a well known problem. Just try to avoid negative positions.

Thank you, that's helpful. Is there any way we can insert a warning to avoid that others are caught out by this?

**Comment by ckhordiasma** [comment]
In case anyone else has this issue: was able to resolve by adding a  `~/.config/codium-flags.conf` file with:

```
--enable-features=WaylandWindowDecorations
--ozone-platform-hint=auto
```

also possible using environment variables 

```
export ELECTRON_OZONE_PLATFORM_HINT=wayland
export ELECTRON_ENABLE_FEATURES=WaylandWindowDecorations
```
