### ISSUE TITLE
Adaptive sync for headless outputs

### ISSUE THREAD

**Issue by lukaslihotzki** [swaywm/sway#6902]
After `swaymsg output HEADLESS-1 adaptive_sync on`, `swaymsg -t get_outputs` still shows `Adaptive sync: disabled`. No log messages are generated. Adaptive sync should be possible for headless outputs.

This feature would help developers without adaptive sync-capable hardware. They could test or understand the behavior of applications, application frameworks, and the compositor under VRR.

zwlr_export_dmabuf_frame_v1 can be used to capture the output. The ready event contains the output frame timestamps.

**Comment by emersion** [comment]
There is no need to explicitly enable this in the headless, Wayland and X11 backends. With Wayland and X11 backends the compositor can already submit a late frame. The headless backend has a fixed timer but should be easy to turn into a non-fixed one. In any case this isn't a Sway issue.

**Comment by emersion** [comment]
Looking at it again, headless already allows submitting late frames. The fixed timer is removed in https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3493.
