### ISSUE TITLE
DnD between firefox and mpv does not work if using focus_follows_mouse

### ISSUE THREAD

**Issue by LaserEyess** [swaywm/sway#6906]
### Please read the following before submitting:
- Please do NOT submit bug reports for questions. Ask questions on IRC at #sway on Libera Chat.
- Proprietary graphics drivers, including nvidia, are not supported. Please use the open source equivalents, such as nouveau, if you would like to use Sway.
- Please do NOT submit issues for information from the github wiki. The github wiki is community maintained and therefore may contain outdated information, scripts that don't work or obsolete workarounds.
  If you fix a script or find outdated information, don't hesitate to adjust the wiki page.

### Please fill out the following:
- **Sway Version:**
  - `sway version 1.7`

- **Debug Log:**
  - generated with `MOZ_ENABLE_WAYLAND=1 sway -c test.conf -d 2>log`
  - `focus_follows_mouse yes` in `test.conf`: https://0x0.st/oN_I.log (DnD does *not* work)
  - `focus_follows_mouse no` in `test.conf`: https://0x0.st/oN_l.log (DnD does work)
     - Despite the file name this is actually a different file, `l` vs `I`

- **Configuration File:**
  - https://0x0.st/oN_U.conf
  - NOTE: between configurations, `focus_follows_mouse` will be toggled between `yes` and `no`

- **Stack Trace:**
   - N/A

- **Description:**
   - When `focus_follows_mouse yes` is set, drag and drop does not work between firefox (wayland native) and mpv (wayland native)
   - Steps to reproduce:
      1. Start sway with the `test.conf` above, with `focus_follows_mouse yes` set
      2. Start mpv with `mpv --no-config --force-window --idle`
      3. Drag a youtube video from firefox to mpv
      4. Nothing happens
   - Changing `focus_follows_mouse` to `no` makes step 3 work

#### Additional Information
mpv/wayland client logs of DnD **working** from `WAYLAND_DEBUG=1 mpv --no-config --gpu-context=wayland --force-window --idle`:
 - mpv: https://0x0.st/oN_D.log
 - wayland: https://0x0.st/oN_k.log

mpv/wayland client logs of DnD **not working** from `WAYLAND_DEBUG=1 mpv --no-config --gpu-context=wayland --force-window --idle`:
 - mpv: https://0x0.st/oN_R.log
 - wayland: https://0x0.st/oN_5.log

Some previous discussions from mpv's side: https://github.com/mpv-player/mpv/pull/9821 https://github.com/mpv-player/mpv/issues/9789

**Comment by aacebedo** [comment]
Also having this issue on 1.8.
Note that it is working when the mpv window is not in a container with other windows (tabs, etc...)

**Comment by kzdixon** [comment]
I'm on 1.8.1 and unable to drag urls from firefox (wayland enabled) to mpv as well. DnD options did not seem to matter for my testing.

**Comment by alterNERDtive** [comment]
I just made the i3 → sway switch, and I’m running into this as well; just that it _also_ affects Thunar, which makes it … extra bad :)

`swaymsg focus_follows_mouse no` immediately fixes this issue, but obviously leads to a bigger one (`focus_follows_mouse` being off).

**Comment by alterNERDtive** [comment]
Oh, almost forgot: the extra fun thing is that it works _if I drag the file(s) over a different, non-Thunar window first_. Like, wat.

**Comment by alterNERDtive** [comment]
Any update on this (he asked after forgetting that this issue was a thing, and pestering the mpv devs about it 😬)?

**Comment by emersion** [comment]
Patches welcome.

**Comment by LaserEyess** [comment]
GTK3 bug, apparently. https://github.com/mpv-player/mpv/issues/9789#issuecomment-1961721292
