### ISSUE TITLE
mako notifications stay "burnt in" until screen/region updates otherwise

### ISSUE THREAD

**Issue by HarHarLinks** [swaywm/sway#6914]
### Please fill out the following:
- **Sway Version:**
  - 1.7

- **Debug Log:**
  - [sway_burnin.log](https://github.com/swaywm/sway/files/8334130/sway_burnin.log)

- **Configuration File:**
```
 input type:keyboard {
    xkb_layout "de"
    xkb_model "pc105"
    xkb_capslock disabled
    xkb_numlock enabled
    xkb_options numpad:microsoft
}
input type:pointer {
    accel_profile flat
    dwt disabled
    left_handed disabled
    natural_scroll disabled
    pointer_accel -0.4
    scroll_button BTN_MIDDLE
    scroll_method on_button_down
}
output DP-1 {
    res 2560x1440
    pos 1920 0
    adaptive_sync on
}
output DP-2 {
    res 1080x1920@60Hz
    pos 4480 0
    transform 270
}
output HDMI-A-1 {
    res 1920x1080@60Hz
    pos 0 360
}
output HDMI-A-2 {
    res 1920x1080@60Hz
    pos 5530 0
}
focus output DP-1
set $mod Mod4
bindsym $mod+Return exec urxvtc -ls
bindsym $mod+Shift+q kill
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right
bindsym $mod+Control+j move workspace to output left
bindsym $mod+Control+k move workspace to output down
bindsym $mod+Control+i move workspace to output up
bindsym $mod+Control+l move workspace to output right
bindsym $mod+Control+Left move workspace to output left
bindsym $mod+Control+Right move workspace to output right
bindsym $mod+less split h
bindsym $mod+minus split v
bindsym $mod+Shift+c reload
bindsym $mod+Shift+r restart
bindsym $mod+Shift+e exec "swaynag -t warning -m 'You pressed the exit shortcut. Do you really want to exi ? This will end your session.' -b 'Yes, exit' 'swaymsg exit'"
 ```
  - mako is launched via `systemctl --user start mako.service` (usually autostarts because enabled, but not in this minimal config)

- **Description:**
Originally opened at https://github.com/emersion/mako/issues/418

Here is a video of the test case `for x in 1 2 3 4 5; do notify-send "test" "message $x"; done`:

https://user-images.githubusercontent.com/2803622/158804837-4b88b127-bdda-489a-9543-da793e0e292e.mp4

As you can see, clicking to dismiss a notification makes the others move down, yet they also stay burnt in at their old position. It looks particularly weird if notifications have different heights.

Any update to the screen area will "flush" the lingering notification, that includes switching to (from?) the window behind it. Thus the issue mainly appears when there is no window open on the monitor, e.g. on boot or with a multi monitor setup. The interaction with the mouse cursor wiping the notifications away, while illustrating my point about updating the screen area, actually appears only during recording with `wf-recorder` - I can normally only get windows to clear them.

Per the original issue, emersion said to try `sway -Ddamage=rerender` which did help work around the issue.

My platform is arch's core/linux kernel (currently 5.16.16), mako 1.6-3, sway 1.7-2, wlroots 0.15.1-3, gdm 41.3-2.

**Comment by Nefsen402** [comment]
Does #6844 help?

**Comment by HarHarLinks** [comment]
what would testing it entail? clone master, merge PR, build manually? do I need a git version of wlroots?

**Comment by Nefsen402** [comment]
Yeah, you need wlroots from git. You can also just pull in the source branch of the PR directly for now, I rebased recently so there shouldn't be conflicts with git wlroots. To test, just run mako and see if the "burn in" remains.

**Comment by Moonlight-Angel** [comment]
I just came across this issue and I'm experiencing something similar, although not exactly the same behavior.
On my side, when I receive multiple notifications at once, some notifications start to flicker until I move my cursor back into the screen (when the notifications appear while my cursor is on the screen, I need to move it out of the screen and back in).
I've had this issue for a very long time (maybe more than a year), I just didn't take the time to report it :see_no_evil: 
#6844 seems to fix the issue, I'm gonna run this fork for now :shrug: 

Don't know if it's related, if it's not, I'll create a new issue :+1: 

https://user-images.githubusercontent.com/2933420/170819652-c4b09b1a-8017-418d-bf27-e2c6ad1f6bc5.mp4

**Comment by HarHarLinks** [comment]
> Don't know if it's related, if it's not, I'll create a new issue

Yes, it looks like in your video for me too sometimes. I think using a screen recorder as I did changes the effect slightly, you seem to have used an external camera.

**Comment by vyivel** [comment]
Closed by https://github.com/swaywm/sway/pull/6844.
