### ISSUE TITLE
Implement Maximize as an alternative to Fullscreen

### ISSUE THREAD

**Issue by Programatic** [swaywm/sway#6925]
### Please fill out the following:
- **Description:**
While Sway has the existing fullscreen functionality, there should also be the equivalent for maximize. While I never thought there was really a difference, for some projects, such as Chromium under ozone, they read the fullscreen state from wayland and alter their behavior. For instance, in Chromium, when you use fullscreen it activates as though it was pressed by F11, thus removing elements from the UI, which is not really desirable. However, when running a version where I replaced xdg_wlr_toplevel_set_fullscreen to set_maximized, then it works properly. Thus, I think maximize would be much more intuitive as I just want the container to be fullscreen, not the actual program.

**Comment by emersion** [comment]
Sorry, we're not accepting any new window management features anymore. See https://github.com/swaywm/sway/blob/master/CONTRIBUTING.md#scope-of-future-changes-to-sway

**Comment by emersion** [comment]
I don't understand what you mean by "i3 doesn't have this issue". chromium also hides some UI elements under i3 when fullscreen. Same as Sway.

We don't take decisions based on whether or not we'd gain more users. This isn't a popularity contest.
