### ISSUE TITLE
cron is not working with swaymsg and swaybg

### ISSUE THREAD

**Issue by HqNw** [swaywm/sway#6933]
i have SWAYSOCK set and cron still drops 

`CMDOUT (00:00:00.021 [ERROR] [swaymsg/main.c:419] Unable to retrieve socket path)`

**Comment by emersion** [comment]
You need WAYLAND_DISPLAY.

**Comment by HqNw** [comment]
> WAYLAND_DISPLAY

`[$] echo $WAYLAND_DISPLAY  `                                                                                                                                                                                                        
`wayland-1 `
