### ISSUE TITLE
Clicks on areas in floating windows that aren't part of an input region don't get passed down; are treated as drags instead

### ISSUE THREAD

**Issue by expenses** [swaywm/sway#6935]
https://wayland-book.com/surfaces-in-depth/surface-regions.html says that:
>The input region indicates which parts of your surface accept pointer and touch input events. You might, for example, draw a drop-shadow underneath your surface, but input events which happen in this region should be passed to the client beneath you. Or, if your window is an unusual shape, you could create an input region in that shape. For most surface types by default, your entire surface accepts input.

However when I've tried setting an empty input region on floating windows, clicks are treated as drag-moving the window. This seems like the incorrect behaviour to me. However, if there is a justification for this then feel free to inform me and close the issue.

Setting an empty input region does work as expected on layer shell surfaces, however.

- **Sway Version:** sway version 1.7
  - `swaymsg -t get_version` or `sway -v`

**Comment by emersion** [comment]
Should be fixed by scene-graph, please re-open if you can reproduce with Sway master.
