### ISSUE TITLE
Floating windows can't set their own position

### ISSUE THREAD

**Issue by OJFord** [swaywm/sway#6937]
- **Description:**

Alacritty for example can be launched with options (or a config file) that (are supposed to) define the position of the window:

```shell
$ alacritty -o window.class.instance=something-that-floats -o window.position.x=0
```

In i3, as long as `[class="something-that-floats"] floating enable`, this works, and the window appears pinned to the left of the display.

In Sway, with `[app_id="something-that-floats"] floating enable`, this doesn't work, the window always appears centrally (unless otherwise defined in sway config).

**Comment by emersion** [comment]
This is by design. Wayland clients can't dictate their absolute position.
