### ISSUE TITLE
Extend floating_modifier function like bindsym?

### ISSUE THREAD

**Issue by tmpm697** [swaywm/sway#6938]
[Here](https://www.reddit.com/r/swaywm/comments/etchzk/dragging_windows_around_without_floating_modifier/) is one of the use-case. 

Default `floating_modifier $mod normal` would allow dragging window around screen but it's fixed and there's no way user can add more useful stuff while doing the `dragging` motion.

I want to define hold `$mod` key and left mouse to drag window and also doing some background stuffs, so if we can define `floating_modifier` like with `bindsym` would solve the issue as I can extend `bindsym` to `exec` a script that extend to my use-case, like:
```
modifiersym exec script.sh
```
scipt.sh contains something like:
```
floating_modifier $mod normal
echo "my extension goes here"
```

**Comment by emersion** [comment]
Sorry, we're not accepting any new window management features anymore. See https://github.com/swaywm/sway/blob/master/CONTRIBUTING.md#scope-of-future-changes-to-sway
