### ISSUE TITLE
How can I remove the tittle bar?

### ISSUE THREAD

**Issue by skhrr** [swaywm/sway#6946]
**Description:**
  -I have tried all the ways to remove the tittle bar but nothing seems to be working.. 

**Tried this but didn't word**
```bash
font pango:monospace 0
titlebar_border_thickness 0                                                     
titlebar_padding 0
```

**Comment by Lythenas** [comment]
You have to change the "border" of a window (which includes the title bar). "normal" means with title bar. From the man page (man 5 sway):

```
       border none|normal|csd|pixel [<n>]
           Set border style for focused window. normal includes a border of thickness n and a title bar. pixel is
           a border without title bar n pixels thick. Default is normal with border thickness 2. csd is short for
           client-side-decorations, which allows the client to draw its own decorations.

       default_border normal|none|pixel [<n>]
           Set default border style for new tiled windows.

       default_floating_border normal|none|pixel [<n>]
           Set default border style for new floating windows. This only applies to windows that are spawned in
           floating mode, not windows that become floating afterwards.
```

**Comment by emersion** [comment]
Please ask questions on IRC.

**Comment by vanarok** [comment]
default_border none
default_floating_border none
font pango:monospace 0
titlebar_padding 1
titlebar_border_thickness 0

**Comment by epragalakis** [comment]
`font pango:monospace 0` no longer works in the newer versions.
any other workarounds?

**Comment by yuki0iq** [comment]
You can use `font pango:Any_font_name 0.001` instead of `font pango:Any_font_name 0`

**Comment by Cole-Hartman** [comment]
I got it working with the following settings but I'm pretty sure the line that actually hides the tab bar is default_border pixel 3.

smart_borders on
gaps inner 5
gaps outer 3
default_border pixel 3
corner_radius 10
shadows enable
shadows_on_csd enable
shadow_blur_radius 20
blur enable
blur passes 2
blur_radius 3

**Comment by nghiatr84** [comment]
`
# Leave 1 pixel for window border
for_window [class=".*] border pixel 1
`
