### ISSUE TITLE
`focus` commands do nothing when run from `for_window`

### ISSUE THREAD

**Issue by oati** [swaywm/sway#6955]
- **Sway Version:**
  - sway version 1.7

- **Reproduction Steps:**
  - `for_window [app_id="some_app"] focus prev sibling`
  - `exec some_app`
  - Expected behavior: focus the window before `some_app`.
  - Actual behavior: focus `some_app`
  - This also happens with `[criteria] focus` bound to `for_window`

**Comment by emersion** [comment]
This is expected, `exec` is asynchronous and new windows take focus by default.
