### ISSUE TITLE
chromium opens a new transmission window instead of using the one that exists

### ISSUE THREAD

**Issue by DNDEBUG** [swaywm/sway#6957]
when i try to open a magnet link or a torrent file instead of using xdg-open to open the link or file with the already existing instance of transmission it opens a new one
i don't know if this is a chromium thing, xdg-open thing or a transmission thing
but it only happens on sway

**Comment by emersion** [comment]
Sway doesn't have a say in this.

**Comment by DNDEBUG** [comment]
@emersion then why does it only happens on sway if sway hyas nothing to do with this?
