### ISSUE TITLE
Segfault with autotiling

### ISSUE THREAD

**Issue by ErikReider** [swaywm/sway#6968]
### Please fill out the following:
- **Sway Version:**
  - sway version 1.8-dev-519038a7 (Apr 29 2022, branch 'master')

- **Debug Log:**
  - [Gist](https://gist.github.com/ErikReider/6a34e1497bd7aad8549137d029ce2e07)

- **Configuration File:**
  - Default config file with `exec autotiling`

- **Stack Trace:**
  - [Stacktrace](https://gist.github.com/ErikReider/258548e5852baaa3c1fb87d3e3cc55a6)

- **Description:**
  - Open two windows (in my case two kitty terminals but works for applications like Firefox)
  - Focus one of the windows
  - Move the window to another workspace through your keybinding (`bindsym $mod+Shift+2 move container to workspace number $ws2
`)

Only seems to be affected by [519038a](https://github.com/swaywm/sway/commit/519038a7e903caae731007b276f5666a341498e9)

**Comment by emersion** [comment]
cc @danieldg

**Comment by danieldg** [comment]
This actually requires a nested layout such as "H[V[win]]" and using a move to empty that inner container, which is why I didn't notice it in testing after introducing it in the last revision of that patch.

**Comment by J0nnyMak0** [comment]
I'm ran into this as well. Attaching log just in case  it is a different variation.
[gdb.log](https://github.com/swaywm/sway/files/8595111/gdb.log)
