### ISSUE TITLE
Input broken for xwayland applications (only) when switching external monitor position

### ISSUE THREAD

**Issue by Blind55** [swaywm/sway#6975]
### Please fill out the following:
- **Sway Version:**
$ swaymsg -t get_version
sway version 1.7

- **Configuration File:**
Default, except the following addition that will help reproduce the bug (I am using someone's idea to position the external monitor found in the Archlinux forums):
`set $scr_main eDP-1`
`set $scr_aux HDMI-A-1`
`set $native_width 1920`
`set $mode_display AUX SCREEN: (l) LEFT (r) RIGHT (o) OFF (m) MIRROR`
`mode "$mode_display" {`
`    bindsym l output $scr_aux enable, output $scr_main pos 0 0, output $scr_aux pos -$native_width 0, mode "default"`
`    bindsym r output $scr_aux enable, output $scr_main pos 0 0, output $scr_aux pos $native_width 0, mode "default"`
`    bindsym m output $scr_aux enable, output $scr_main pos 0 0, output $scr_aux pos 0 0, mode "default"`
`    bindsym o output $scr_aux disable, mode "default"`
`    bindsym Return mode "default"`
`    bindsym Escape mode "default"`
`}`
`bindsym $mod+x mode "$mode_display"`

- **Description:**
  - When switching the external monitor from the right of the main monitor to its left using the above configuration snippet, any application running under xwayland loses its input, in particular no mouse clicks are registered correctly. Native wayland applications run fine and receive mouse events/clicks properly.
  - I believe this bug is related to [#6907](https://github.com/swaywm/sway/issues/6907), but I wanted to provide another test case as this one seems more general. I tried with slack and xfreerdp, both of which show the same problem (running under xwayland).

**Comment by emersion** [comment]
See https://github.com/swaywm/sway/wiki#mouse-events-clicking-scrolling-arent-working-on-some-of-my-workspaces
