### ISSUE TITLE
Ability to show previous scratchpad window (show in reverse order)

### ISSUE THREAD

**Issue by PAI5REECHO** [swaywm/sway#6977]
If you have a dozen windows in the scratchpad it can be easy to accidentally pass the window you intended to view. It would be nice if you could cycle showing windows in the opposite direction to go back 1 window sometimes.

**Comment by Dhamma-valence** [comment]
I've been wanting this too, and you could map next to Ctrl+Tab and previous to Ctrl+Shift+Tab to emulate a task switcher.

**Comment by emersion** [comment]
Sorry, we're not accepting any new window management features anymore. See https://github.com/swaywm/sway/blob/master/CONTRIBUTING.md#scope-of-future-changes-to-sway
