### ISSUE TITLE
Wayland Session Recovery

### ISSUE THREAD

**Issue by Hummer12007** [swaywm/sway#698]
Enlightenment has relatively recently introduced a protocol for session recovery after crashes (the relevant blog post is https://blogs.s-osg.org/recovery-journey-discovery/ ), apparently this let's the client assign a UUID to each of it's windows (as per https://git.enlightenment.org/core/enlightenment.git/tree/src/protocol/session-recovery.xml protocol). Though apparently it requires client-side support, it's still interesting.
The enlightenment implementation: https://git.enlightenment.org/core/enlightenment.git/commit/?id=df041fe77b5ee660b430ee63b3941911636fd196 & https://git.enlightenment.org/core/enlightenment.git/commit/?id=ef1772b8cb992b115411f01e1915fca015eea158
CC @Cloudef

**Comment by emersion** [comment]
This needs a standard Wayland protocol to move forward. We can re-open this once there's a MR against the wayland-protocols repo.

**Comment by clawoflight** [comment]
Let me know if you would rather have a new issue - the freedesktop standardization MR was *merged* recently:

https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/18
