### ISSUE TITLE
set env var while running

### ISSUE THREAD

**Issue by alexmo1997** [swaywm/sway#6982]
I'd be great if you could set/unset env vars of sway while sway is running.
Use case:
launcher runs from sway keybind, so even if I change a env var in my shell config, I always need to restart sway in order for the started applications to get the new env vars.

**Comment by Xyene** [comment]
You should already be able to accomplish this by making your launcher bindsym look something like `bash -c 'the-launcher-command'`.

**Comment by emersion** [comment]
This has been discussed at length in the past. Sorry, this won't get added.
