### ISSUE TITLE
Implement libinput's Scroll Button Lock

### ISSUE THREAD

**Issue by JJGadgets** [swaywm/sway#6987]
### **Description:**

When I use Xorg, I can have a file `/etc/X11/xorg.conf.d/99-libinput.conf` defining libinput options, and I can use the option `Option "ScrollButtonLock" "1"` to enable locking of the scroll button of a pointer device. This effectively changes the scroll button's behavior of switching between cursor and scroll, from holding the button to clicking once to toggle.

For example, I use a ThinkPad which has a TrackPoint and a middle click. Current default behavior is for holding the middle click to convert the TrackPoint from moving the cursor to scrolling. In Xorg, I can use ScrollButtonLock to have the button toggle between cursor and scrolling.

It seems to be a **supported** official libinput option in the spec, from my understanding of [the libinput spec docs referencing scrolling](https://wayland.freedesktop.org/libinput/doc/latest/scrolling.html?highlight=scroll#on-button-scrolling). Could this option be implemented in sway-input?

**Comment by JJGadgets** [comment]
> Patches welcome

Sorry, I don't have any experience with C, or any time to implement this right now, else I would've just sent in a PR to begin with.

Should I have requested a feature another way?

**Comment by JJGadgets** [comment]
Actually, if the [libinput.c](https://github.com/swaywm/sway/blob/master/sway/input/libinput.c) file is all I have to change, since it seems to just be implementing libinput methods and nothing much more, I might try it out just to get my hands dirty. No guarantees, but no harm for me to try.

**Comment by JJGadgets** [comment]
Update: I have it working in https://github.com/JJGadgets/sway/tree/sway-scroll-lock and I only need to test that the command/input/scroll_button_lock.c works. Will open a PR soon.

**Comment by DeltaWhy** [comment]
@JJGadgets I'm also interested in this feature, do you still intend to open that PR?

**Comment by JJGadgets** [comment]
> @JJGadgets I'm also interested in this feature, do you still intend to open that PR?

I'll try to get to it this weekend, I haven't gotten it configurable via swaymsg yet, but enabling it through config works.

**Comment by DeltaWhy** [comment]
I had to make a small change to your branch to get it to build against the latest sway:
```
diff --git a/sway/commands/input.c b/sway/commands/input.c
index 77acb671..28d4384f 100644
--- a/sway/commands/input.c
+++ b/sway/commands/input.c
@@ -27,6 +27,7 @@ static const struct cmd_handler input_handlers[] = {
 	{ "scroll_button", input_cmd_scroll_button },
+	{ "scroll_button_lock", input_cmd_scroll_button_lock },
 	{ "scroll_factor", input_cmd_scroll_factor },
 	{ "scroll_method", input_cmd_scroll_method },
```
There's a comment above this array which says it needs to be sorted - in your branch they are out of order. After fixing this I was able to apply the patch against master and it's working!
I also saw the file `sway/ipc-json.c` has something about `scroll_button` and this may need to be updated as well.
