### ISSUE TITLE
Add a note about firefox in FAQ

### ISSUE THREAD

**Issue by xsrvmy** [swaywm/sway#6991]
There has been a bug for a while with Firefox where dragging a tab would sometimes freeze the browser. While this is definitely a bug, there is a fix for this which is to disable the tab image preview when moving the tab. The setting for this is nglayout.enable_drag_images which needs to be set to false in about:config.

It would be nice to put this in the sway FAQ if this is a sway/wlroots only issue (ie. not with mutter or kwin) and it still exists.

**Comment by emersion** [comment]
The wiki is user-editable.
