### ISSUE TITLE
Mouse cannot control firefox window in second monitor

### ISSUE THREAD

**Issue by Dhamma-valence** [swaywm/sway#7002]
- **Sway Version:**
  - sway version 1.7 (from debian unstable repo)

- **Debug Log:**
[debug.log](https://gist.github.com/Dhamma-valence/c4964328f61903f744daa9c7d681ee4b)

- **Configuration File:**
[config](https://gist.github.com/Dhamma-valence/33232d81d49b1a5992ef9c73efe900b4)

- **Description:**
Mouse control of firefox on the second screen (HDMI-A-3) doesn't work at all, no clicking or scrolling. Keyboard still works fine though.  This is in all tiling modes, floating too.

Both alacritty and lutris work fine, however.

At first I thought it was because of my second display's offset
```
    output DVI-D-1  resolution 1920x1080 position 0,0
    output HDMI-A-3 resolution 1920x1080 position 400,-1080
```
but even after changing it to `0,-1080` and rebooting, the issue persists.

This looks similar to #6651. I've only just started using sway today so my config is pretty darn close to default except for a few rebinds and the inclusion of waybar/swayr.

**Comment by Lythenas** [comment]
Negative offsets don't work for X windows. Lutris and alacritty both run directly in wayland. Firefox runs in xwayland. (at least on my machine)

See https://github.com/swaywm/sway/wiki#mouse-events-clicking-scrolling-arent-working-on-some-of-my-workspaces

Something like this might work for you:
```
    output DVI-D-1  resolution 1920x1080 position 0,1800
    output HDMI-A-3 resolution 1920x1080 position 400,0
```

**Comment by Dhamma-valence** [comment]
Hey, that worked!  Brilliant, thank you so much!
