### ISSUE TITLE
Nested wayland with HiDPI is blurry

### ISSUE THREAD

**Issue by sorpaas** [swaywm/sway#7005]
- **Sway Version:** sway version 1.7
- **Configuration File:** reproducible with default config

Running nested sway with parent wayland having an output scale results in blurry display. Reproducing steps:
* Start `sway`.
* `swaymsg output DP-1 scale 2`
* Start a terminal and run sway again, nesting it.
* The child sway (and any wayland programs running it) looks blurry.

**Comment by emersion** [comment]
Duplicate of https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/854

**Comment by zarkone** [comment]
just in case, I've made a patch to wlroots which fixes the problem, -- at least with river wm which I'm running. 

https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/5186
