### ISSUE TITLE
Window title in swaybar?

### ISSUE THREAD

**Issue by UtkarshVerma** [swaywm/sway#7014]
Could we please have option to show focused window title (with icon) in swaybar next to workspaces? On a small screen such as my laptop's, I had to disable the window title bar to save space. Having this would be really helpful.

**Comment by UtkarshVerma** [comment]
This is a feature request, accidentally labelled as bug

**Comment by Emantor** [comment]
This is already achievable by using a different status bar command, i.e. i3-status-rust implements a window title which can be shown within swaybar. AFAIR waybar also supports showing the window title.

**Comment by UtkarshVerma** [comment]
Waybar and i3status-rust do have it, but i3status-rust doesn't have the title left-aligned. In case of waybar, I am facing other issues. All in all, I don't feel shifting to another status bar just because of the window title because I appreciate the simplicity of swaybar.

**Comment by emersion** [comment]
Sorry, we're not accepting any new window management features anymore. See https://github.com/swaywm/sway/blob/master/CONTRIBUTING.md#scope-of-future-changes-to-sway

**Comment by noelcurray** [comment]
I've been looking for a way to have a window title bar on swaybar and I land here. I also like the simplicity of swaybar. It's sad that window title bar won't happen.
