### ISSUE TITLE
New option for not setting DISPLAY variable when using xwayland

### ISSUE THREAD

**Issue by whenov** [swaywm/sway#7016]
### Please read the following before submitting:
- We are not accepting any new window management features unless they get implemented by i3.

### Please fill out the following:
- **Description:**
I am switching to wayland from X11, but there is still one application which does not support wayland. If I install xwayland, all applications which support both wayland and X11 but prioritize X11 would use X11, which is not what I want. (Some apps allow users to specify the backend but it's cumbersome to configure all of them)
Therefore, I hope there is a new option which allows users to control whether the DISPLAY variable is set. If DISPLAY is not set, sway can save its value to another environment variable, e.g. XWAYLAND_DISPLAY. Then the users can launch their X11-only apps with `DISPLAY=$XWAYLAND_DISPLAY app_cmd` while all other apps can only see wayland.

**Comment by emersion** [comment]
Nah, sorry. You can achieve the same thing by wrapping your launcher with a script which fiddles with the env variables as you'd like.
