### ISSUE TITLE
accel_profile "flat" too slow

### ISSUE THREAD

**Issue by ignamartinoli** [swaywm/sway#7018]
### Please fill out the following:
- **Sway Version:** 1.7

- **Debug Log:**
https://pastebin.com/xjR3WQdn

- **Configuration File:**
https://pastebin.com/Dv7PNgjV

- **Description:**
When I set the `accel_profile` option to `"flat"` the cursor moves extremely slow even when `pointer_accel` is set to `1`, while if I use the `"adaptive"` profile to cursor is working fine again

**Comment by Emantor** [comment]
Isn't that whats expected? According to the [flat pointer acceleration profile](https://wayland.freedesktop.org/libinput/doc/latest/pointer-acceleration.html#the-flat-pointer-acceleration-profile) this corresponds to a 1:1 movement between pointer and the cursor so you would need to increase the `pointer_accel` variable to higher than 1 for bigger screens and low resolution trackpads/pointers. We also just feed the acceleration profile into libinput: https://github.com/swaywm/sway/blob/624ffa45162d7df1ae0796b283bef2f4a0d6a0d7/sway/input/libinput.c#L89
So if this is an issue, its probably something for libinput and not for sway.

**Comment by ignamartinoli** [comment]
Thanks. I opened a bug there
