### ISSUE TITLE
Black screen when running sway on new laptop with Intel graphics

### ISSUE THREAD

**Issue by zsolt-donca** [swaywm/sway#7022]
**Sway Version:**
```
❯ sway -v
sway version 1.7
```  

**Debug Log:**
- sway debug logs and system journal: https://gist.github.com/zsolt-donca/dec3d6989c41a06bf1db9e9ac501e0a9

**Configuration File:**
Default configuration.

**Description:**
I just installed Arch Linux and Sway on a brand new Dell XPS 15 9520 laptop. When starting sway from the TTY, I just get a black screen with the mouse cursor on it (which moves), but nothing else. It doesn't appear to respond to anything I do. The system journal is full of errors such as:

> May 23 13:54:10 ROC01-02336 kernel: DMAR: DRHD: handling fault status reg 3
> May 23 13:54:10 ROC01-02336 kernel: DMAR: [DMA Read NO_PASID] Request device [00:02.0] fault addr 0x1007206d61000 [fault reason 0x04] Access beyond MGAW
> May 23 13:54:10 ROC01-02336 kernel: i915 0000:00:02.0: [drm] *ERROR* Fault errors on pipe A: 0x00000080

I tried some kernel Intel-related options to no avail, the only one that actually did something was `intel_iommu=off`, the effect being that some weird graphic artifacts appearing in the top of the screen which changed as I moved the mouse cursor. I tried `-git` builds of sway and wlroots as well, and got the same behavior.

**Comment by Emantor** [comment]
This is probably an ACPI bug, probably some kind of misconfiguration for the memory region used by the internal GPU. It doesn't work with the IOMMU since the out of bounds access is restricted (mentioned in the logs) and without the IOMMU something else also writes in the FB region of the GPU. Either way there is nothing we can do in sway about it, but you'll want to report to the intel GPU people [here](https://gitlab.freedesktop.org/drm/intel/-/issues).

**Comment by zsolt-donca** [comment]
You are right, @Emantor . Before logging a bug, I've tried to reproduce the issue with the latest development branch of the intel drm driver (and the AUR build [linux-drm-tip-git](https://aur.archlinux.org/packages/linux-drm-tip-git) was very handy), and sway miraculously worked.

Btw, whatever the bug is, it doesn't seem to affect all compositors, as GNOME with Wayland seems to work even without this fixed kernel driver.

**Comment by jerry-h-chen** [comment]
hi! I am currently experiencing this exact same issue :sweat_smile: (Dell Latitude instead of XPS). However, I'm currently running Fedora instead of Arch...

unfortunately still pretty new to Fedora+Linux, so I was wondering if you may know how I could solve this on this Fedora? I looked around but was unable to find how I could update my intel drm driver. Is this because Fedora bundles these drivers together and you can't pick and choose when to update?

**Comment by jerry-h-chen** [comment]
Actually, might be a different issue... I'm able to start sway by just running `sway` after booting into Gnome (Wayland), but the display doesn't fill the screen:

```
00:00:00.026 [ERROR] [wlr] [types/wlr_drm_lease_v1.c:705] No DRM backend supplied, failed to create wlr_drm_lease_v1_manager
2022-05-25 22:57:04 - [main.c:340] Found config * for output WL-1 ((null))
Another session found; refusing to overwrite the variables
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Could not resolve keysym XF86EmojiPicker
Errors from xkbcomp are not fatal to the X server
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 708, clipping.
>                   X11 cannot support keycodes above 255.
Errors from xkbcomp are not fatal to the X server
INFO:assign-cgroups:X-Resource version 1.2
INFO:assign-cgroups:compositor:6498 /user.slice/user-1000.slice/user@1000.service/app.slice/app-org.gnome.Terminal.slice/vte-spawn-17d39662-36b1-4ba3-a5ca-7e1006631290.scope
```

![Screenshot from 2022-05-25 23-04-52](https://user-images.githubusercontent.com/13864027/170427381-86c1a3f9-cb54-4cdc-afcd-0dba12afa008.png)

However, if I create execute sway from TTY, or via GDM, I get either a black screen, as described above, or sometimes broken display (that I am unable to interact with), with a different set of logs:
```
2022-05-25 22:58:36 - [main.c:340] Found config * for output eDP-1 (Unknown 0x0940 0x00000000)
Environment variable $DESKTOP_SESSION not set, ignoring.
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Could not resolve keysym XF86EmojiPicker
Errors from xkbcomp are not fatal to the X server
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 708, clipping.
>                   X11 cannot support keycodes above 255.
Errors from xkbcomp are not fatal to the X server
INFO:assign-cgroups:X-Resource version 1.2
INFO:assign-cgroups:compositor:7402 /user.slice/user-1000.slice/session-5.scope
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 708, clipping.
>                   X11 cannot support keycodes above 255.
Errors from xkbcomp are not fatal to the X server
```
![sway_broken](https://user-images.githubusercontent.com/13864027/170428178-8702caef-32e4-42be-b515-326dbfbc7c57.jpg)

Do you suspect this is a unrelated error? If so, should I open a separate issue on this?

**Comment by apognu** [comment]
I have the exact same issue, which is fixed when I run `sway` with `MESA_LOADER_DRIVER_OVERRIDE=i915` (but obviously running on the old driver). I can try and provide more information if necessary.

**Comment by zsolt-donca** [comment]
Hi, @jerry-h-chen !

>  I looked around but was unable to find how I could update my intel drm driver. Is this because Fedora bundles these drivers together and you can't pick and choose when to update?

The Linux kernel itself is bundled together with most device drivers, the so-called "in-tree" drivers. Drivers that are not bundled can use the [DKMS](https://wiki.archlinux.org/title/Dynamic_Kernel_Module_Support) to be loaded separately (e.g. the nvidia proprietary driver). 

Since the Intel driver is "in-tree", you'll need to recompile the Linux kernel with the updated drivers. That's what the [Intel Graphics For Linux build guide](https://01.org/linuxgraphics/documentation/build-guide-0) explains. I don't have much experience with Fedora either, but this official documentation on [Building a Custom Kernel](https://docs.fedoraproject.org/en-US/quick-docs/kernel/build-custom-kernel/) looks relevant to me. Note that compiling a Linux kernel can take a couple of hours - a possible speedup is to configure parallel compilation (which is not default, at least not on Arch).

Note that the Linux kernel 5.18 just recently landed into the official Arch repos, and that completely fixes my issues. According to [this page](https://packages.fedoraproject.org/pkgs/kernel/kernel/), Fedora Rawhide should have a kernel version even newer than that. You could look into it, maybe only for testing and for confirmation that the bug you're experiencing is indeed an Intel driver bug.

> However, if I create execute sway from TTY, or via GDM, I get either a black screen, as described above, or sometimes broken display (that I am unable to interact with), with a different set of logs:

That screenshot of a broken display is very similar to what I also got when launching Sway through GDM. To me, our issues seem very similar, but I'm not really in a position to tell exactly. If trying out a new kernel doesn't help, consider opening a separate bug report (and include a full debug log of your sway session).
