### ISSUE TITLE
SwayWM - bindsym for special windows

### ISSUE THREAD

**Issue by kereell** [swaywm/sway#7026]
How can I bind key Escape to kill only some apps \ windows in SwayWM config? I mean when the app is focused.

The problem is
`bindsym Escape [title="some_app"] kill`
conflicts with
`bindsym Escape [title="other_app"] kill.`

Is it possible to do something like
`for_window [title="some_app"] on_escape_key_press kill`

**Comment by emersion** [comment]
Please ask questions on IRC.
