### ISSUE TITLE
Sway crashes with headless displays on latest sway HEAD

### ISSUE THREAD

**Issue by dnfm** [swaywm/sway#7030]
### Please fill out the following:
- **Sway Version:**
sway version 1.0-dev-42b61ab2 (May 26 2022, branch 'HEAD')

- **Debug Log:**
https://pastebin.com/xpNQVRqR

- **Configuration File:**
I kept the config nice and short:

```
set $mod Mod1

bindsym $mod+Return exec /home/jwheeler/bin/term
bindsym $mod+Shift+e exit
```

- **Stack Trace:**
I recompiled sway, wayland, and wlroots with debug symbols and without stripping, but the entire backtrace is full of ?? anyway.. my dmesg says the seg fault is in libc.so.6.

- **Description:**
- Open a terminal
- Execute `swaymsg create_output`
- Execute `swaymsg -t get_outputs`

Kablooie

**Comment by emersion** [comment]
https://github.com/swaywm/sway/pull/7031

**Comment by dnfm** [comment]
Fastest turnaround ever.  That fixed it.
