### ISSUE TITLE
red screen of death after unlocking

### ISSUE THREAD

**Issue by primalmotion** [swaywm/sway#7046]
### Please fill out the following:
- **Sway Version:** 
sway version 1.8-dev-251a648e (Jun  1 2022, branch 'master')

- **Debug Log:**
https://gist.github.com/primalmotion/c4d39ea0879cb7559dafc12fa0f58718

- **Description:**
Randomly (but pretty often) when I wake the machine up, I can enter my password from swaylock to unlock the screen, then all monitors are red (literaly completely red) and sway, while still running, does not respond to anything. I must switch to another tty, login, kill sway and restart it. This started to happen a few weeks ago

**Comment by emersion** [comment]
This happens when swaylock crashes.

That log is incomplete and only contains ERROR messages.

**Comment by primalmotion** [comment]
yeah it's my classic log.. I've enabled debug and will run in that mode for a while until it happens again

**Comment by primalmotion** [comment]
that did not take long

https://gist.github.com/primalmotion/94cd2492896568363ea7358c5bac6643/

**Comment by emersion** [comment]
Can you try to update sway+wlroots to latest commit?

The end of the log says the unlock is successful, but is followed by a EBUSY:

```
00:02:20.348 [ERROR] [wlr] [backend/drm/atomic.c:71] connector DP-2: Atomic commit failed: Device or resource busy
00:02:20.348 [DEBUG] [wlr] [backend/drm/atomic.c:75] (Atomic commit flags: PAGE_FLIP_EVENT | ATOMIC_NONBLOCK)
00:02:20.827 [DEBUG] [sway/lock.c:88] session unlocked
```

**Comment by primalmotion** [comment]
Sure let me upgrade. I'll report if it happens again

**Comment by primalmotion** [comment]
ok after multiple fight with other issue, I was able to test latest master. The issue still happens

**Comment by ldelossa** [comment]
experiencing this as well.

**Comment by primalmotion** [comment]
Yeah I noticed this way to reproduce too. I found out because swaylock was not responding. switch to another tty, and killed it. red screen. From what I understand, the red screen is basically here to prevent unlocking the laptop even if the swaylock process dies. So it seems the actual problem is not the red screen, but the fact that swaylock crashes one way or another without "releasing" the session lock

**Comment by primalmotion** [comment]
I haven't seen this issue in a while now (seems it's been 2 weeks)

**Comment by primalmotion** [comment]
obviously I had to write a comment just before it actually happened again.

**Comment by emersion** [comment]
Please obtain a stack trace for swaylock.

**Comment by alxchk** [comment]
I have this screen of death when system is under high load, one display is off and one display is on. However I'm not able to reproduce it withing some reasonable period of time. Running weeks with debug looks seems not to be good idea..

**Comment by ljupchokotev** [comment]
I can reproduce this each time my laptop comes out of sleep and I have my external monitors connected. Both of the monitors will just have a red screen and I have to switch to a tty and do a `systemctl suspend` a few times to get rid of it.

Today I also got it on my laptop without any external monitors. Swayidle triggered swaylock, I saw the lockscreen for a second and then it turned to the red screen on my laptop screen. But this doesn't seem to be reproducible easily.

Here is a stack trace https://gist.github.com/ljupchokotev/22cf9ef0163d7d865aa1f7c1c734cb5f.

**Comment by bigfreak85** [comment]
same problem here. I have a yubikey and do some udev rules to automaticly lock the screen https://kliu.io/post/yubico-magic-unlock/ 
if i use kill anytime the red-screen appears. I have downgraded to 1.5 fixed it for me... seems to be a Security improvment but how can i do my usecase with swaylock 1.6?

**Comment by scippio** [comment]
After yesterday updates of my Archlinux my swaylock go to red screens too...

**Comment by asas1asas200** [comment]
Same issue

**Comment by kenshaw** [comment]
Same issue as @scippio -- just reporting here. Downgrading `sway` and `wlroots` has fixed the issue temporarily. Had the same version changes as `scippio` did.

**Comment by bigfreak85** [comment]
with the latest Version you can send a USR1 Signal to the process to stop it. So yubikey unlock works now with some modifications (pkill -USR1 swayidle)

**Comment by WholesomeDoktor** [comment]
> **warning !EDIT: "official" package from Archlinux community (swaylock version 1.7) works fine! warning**
> 
> After yesterday updates of my Archlinux my swaylock go to red screens too...
> 
> ```
> [2023-01-04T12:38:48+0100] [ALPM] upgraded wlroots (0.15.1-6 -> 0.16.1-2)
> [2023-01-04T12:38:48+0100] [ALPM] upgraded sway (1:1.7-10 -> 1:1.8-3)
> ```
> 
> I'm using this command: `swaylock -F -c 000000 -k` `sway version 1.8` `swaylock version v1.6.10-4-ga1cf657 (Jan 5 2023, branch 'master')`
> 
> btw I'm using this version: https://github.com/jirutka/swaylock-effects

Agree with OP. Same error on my side, even firefox crashes on external monitor with scaling different than 1.0.

**Comment by hungshihhan** [comment]
I ran into the same issue after a system upgrade on gentoo. Rolling `swaylock-effects` back to `1.6.3` (but keeping other packages updated) the problem disappears.

**Comment by ferdinandschober** [comment]
The problem seems to be with swaylock-effects and swaylock-fancy only. 
The default swaylock works flawlessly

**Comment by prometheanfire** [comment]
I've had this issue with swaylock only (I don't have any effects or fancy module installed).

**Comment by kj** [comment]
> Updating to swaylock 1.7.2 fixed the issue.

Are you sure about that? I had a red screen yesterday and according to my package manager I installed 1.7.2 on 29 January.

**Comment by blastrock** [comment]
I still have the issue here with sway 1.8 and swaylock 1.6.11 when I wake my laptop from hibernation.

I have no idea about the cause, but I have found a workaround to recover the session. Open another TTY and run

```
WAYLAND_SESSION=wayland-1 swaylock
```

Now go back to the red screen sway which is now locked. Unlock it with your password, and your session is recovered!

**Comment by blastrock** [comment]
I didn't notice I didn't have the latest version! I forgot that I switched to swaylock-effects and it looks like that one is abandoned.

Anyway, I've been using the latest version of swaylock for the past week or so and I didn't have this bug anymore. A bit sad to lose the nice features of swaylock-effects, but at least my issue is fixed, thanks!

**Comment by thyeun** [comment]
@blastrock i'm not sure which version of `swaylock-effects` that use by you, but there was an upgrade from arch linux that upgrade the version from `swaylock-effects-git r402.xxxxxxx-1` to `swaylock-effects-git r416.xxxxxx-1` when you reinstall `swaylock-effects` again

And i'm not sure either it will solved the red screen of death or not but is solve one of the issue i facing `ext_session_lock_surface_v1@21: error 0: session lock surface has never been configured`. (i also facing red screen of death too)

**Comment by blastrock** [comment]
I don't use archlinux but I can't find any r416 version on AUR. The [swaylock-effects-git package](https://aur.archlinux.org/packages/swaylock-effects-git) (r402) just seems to be based of https://github.com/jirutka/swaylock-effects whose latest version is 1.6.11, and I had the red screen with that version. I can't find that r416.

**Comment by thyeun** [comment]
@blastrock as you can see from the pic below, the aur at arch linux is r402, but once you re-install it, you will get r416

![Screenshot_2023-04-23-01-17-26_8001](https://user-images.githubusercontent.com/1939446/233797997-78ea0bf3-9b0e-4faf-b1c6-cf196bfd7030.png)

**Comment by thyeun** [comment]
And i can start swaylock without getting RSOD any more

**Comment by blastrock** [comment]
The commit hash seems to be same as the one I was using: https://github.com/jirutka/swaylock-effects/commit/a7691b86dabe5241c7292c7b8d0551d579ba1848, and I had RSODs with that :(

**Comment by blastrock** [comment]
Hi there, in case there are other people like me using swaylock-effects, I have made my own fork. The only thing I did on it is merge the upstream swaylock: https://github.com/blastrock/swaylock-effects-second . I didn't get the red screen of death in the last week so it might be fixed.

In any case, it looks like this bug is unrelated to sway, so this issue can be closed I guess...?

**Comment by shaohme** [comment]
Using Debian trixie/testing, this happens on my setup when killing swaylock, start a wayvnc session, and trying to connect to it with a vnc client over a ssh session. 

swayidle = 1.8.0-1
swaylock = 1.7.2-1
sway = 1.8.1-2

**Comment by command-z-z** [comment]
I can find r420 version on AUR. The [swaylock-effects-git package](https://aur.archlinux.org/packages/swaylock-effects-git) (r420) works for me and I don't have the red screen with this version any more.

**Comment by Sewer56** [comment]
> I still have the issue here with sway 1.8 and swaylock 1.6.11 when I wake my laptop from hibernation.
> 
> I have no idea about the cause, but I have found a workaround to recover the session. Open another TTY and run
> 
> ```
> WAYLAND_SESSION=wayland-1 swaylock
> ```
> 
> Now go back to the red screen sway which is now locked. Unlock it with your password, and your session is recovered!

This didn't quite seem to work for me, however, I might aswell share what I ran across.

In my case, I was running under Hyprland and the environment variable appears to be called `WAYLAND_DISPLAY`. 

I found this out by finding a process that started under the compositor. And reading it's environment variables under `/proc/$pid/environ`.

That seemed to work towards running the application, but the application would just error out, saying the screen was already locked `failed to lock session -- is another lockscreen running`.

In my case, `swaylock` was not responding to my keyboard after waking up from suspend. To lock, I originally ran `systemctl suspend & swaylock`.

**Comment by prometheanfire** [comment]
for me, this issue happens if oomkiller kills things, swaylock in particular

**Comment by thyeun** [comment]
After i commented till today, i will never getting RSOD any more no matter manually trigger by keyboard or let the timer set accordingly or even ```oomkiller```, my laptop is intel gen-2 from 2008 till now. 

Try follow my comment and do exactly, see will it happen again. Hope you all no more RSOD on year 2024.

**Comment by blastrock** [comment]
Not sure everybody noticed but there has been a couple releases of swaylock-effects since last time: https://github.com/jirutka/swaylock-effects/tags . I upgraded a couple weeks ago and didn't get a RSOD yet, might be fixed.

**Comment by KiaraGrouwstra** [comment]
@blastrock 1.7.0.0 of swaylock-effects seems still affected.
thread over there: https://github.com/jirutka/swaylock-effects/issues/57

**Comment by hughobrien** [comment]
Saw this for the first time today, was using wayvnc for the first time and left the session unattended. Might be reproducible that way.

**Comment by kaiserbh** [comment]
Yea, I am having this issue as well for the first time ever (well 2nd time now), I left it locked, and then when I am back, it just red screen of death! 


![20241121_175441.jpg](https://github.com/user-attachments/assets/ed726bcf-d265-4679-b5a7-4cad63bb654b)


Everything is updated.


I can probably reproduce it again, I had my work stuff, nvim, and a few electron apps running.

**Comment by thyeun** [comment]
commented out swayidle and make sure there was a swap with enough memory, if you have turn on hibernate.

Than seat and see will you getting RSOD or not.

**Comment by thyeun** [comment]
@veganomy ok, than it should not in this post, this post mainly related with swaylock/hibernate/swayidle. luckily i change to Hyprland with no more wlroots. :P

**Comment by hughobrien** [comment]
This seems reproducible to me, leave `wayvnc` running, and leave a client connected. Let the screen lock and wait a little while. It will go red.

In my case entering the password at the physical terminal and disconnecting the client seemed enough to recover it, no need to re-execute `swaylock` as mentioned above (though that did work for me before)

**Comment by Trust2k** [comment]
Initial configuration: The laptop is connected to an external monitor.

To reproduce the appearance of the red screen, just follow these steps::

1. Transfer the PC to suspend.
2. Turn off the external monitor by pressing the button.
3. Make sure that the laptop is working.
4. Turn on the external monitor by pressing the button.
5. We get a red screen.

It plays stably.

**Comment by GameKing505** [comment]
> This seems reproducible to me, leave `wayvnc` running, and leave a client connected. Let the screen lock and wait a little while. It will go red.
> 
> In my case entering the password at the physical terminal and disconnecting the client seemed enough to recover it, no need to re-execute `swaylock` as mentioned above (though that did work for me before)

I can verify the same occurs for me. If I leave a wayvnc client connected - I'll get a RSOD.

**Comment by hyperfocusedblur** [comment]
why is this issue closed? the bug is still reproducable in sway 1.11 and swaylock-effects 1.7.0

**Comment by FraCata00** [comment]
> why is this issue closed? the bug is still reproducable in sway 1.11 and swaylock-effects 1.7.0

Ye, i have the same so annoying

**Comment by jheidbrink** [comment]
I also observe this, with sway 1.12-dev, swaylock 1.8.4, swayidle 1.9.0. I'm using way-displays to configure my screen layout. The last time this happened, I fixed it by removing the external screen, closing the laptop lid which triggers suspend-to-ram and opening the lid again -> swaylock was back, I could enter the password was back at my sway session

**Comment by arunprasaddoss** [comment]
I am also having this issue. It happens when my laptop is disconnected from dock while in suspend. 

This doesn't occur when I start it without disconnecting the dock.

**Comment by SourceOfHTML** [comment]
It still happens on sway 1.12, swaylock 1.8.5, 1.9.0, on a mostly default Archlinux install (default as in I have not touched systemd's ACPI-related features)

I don't have exact details on what causes my RSOD (testing it manually seems too difficult to me), but whenever I let my laptop idle, and swayidle starts swaylock, I have to be gone for a really long time (or, maybe, close the laptop lid?) for me to experience the RSOD.

Here is the relevant section of my `.config/sway/config`:

```
exec swayidle -w \
         timeout 420 'swaylock -f -i $lock_screen' \
         timeout 900 'swaymsg "output * power off"' resume 'swaymsg "output * power on"' \
         before-sleep 'swaylock -i $lock_screen -f'
```

This could be a misconfiguration on my end, as I basically copy-pasted this snippet from somewhere I do not recall.

P.S.: I (as a simple user of swaylock) don't see why this issue can't be re-opened. Is this a bug in systemd or the device's configuration rather than a swaylock bug?

**Comment by smlx** [comment]
I have tried to reproduce this with various combinations of external monitors / suspend / plug / unplug and not been able to. I wonder if it is hardware-specific?

If you see this bug, could you try running swaylock with `WAYLAND_DEBUG=1` and capturing the output?

First find out the value of `WAYLAND_DISPLAY`:

```bash
echo $WAYLAND_DISPLAY
```

Then run swaylock. For example:

```bash
WAYLAND_DEBUG=1 swaylock 2>&1 | tee /tmp/swaylock.debug.log & sleep 1 && systemctl suspend
# turn off monitor and resume, or whatever triggers the bug
```

Once swaylock has exited and you see the red screen you can unlock by switching to a virtual console (Ctrl+Alt+F1) and running swaylock with the WAYLAND_DISPLAY variable set to the value from earlier. e.g.

```bash
WAYLAND_DISPLAY=wayland-1 swaylock
```

Then switch back to your sway console and unlock the screen normally.

And finally, post the debug log.
