### ISSUE TITLE
Implement dbus interface

### ISSUE THREAD

**Issue by Zocker1999NET** [swaywm/sway#7048]
## Feature

Please implement (or let someone implement) a D-Bus interface reflecting the current features which are already exposed using the UNIX socket. This interface should use verbose names for methods and signals (events) so developers can use them right away without reading & understanding too much documentation. This might be implemented as an optional feature, where if no D-Bus service is running, sway would still run.

## Reasoning

D-Bus interfaces are, if done correctly, usable to many 3rd party applications with using just a single library for D-Bus support without either requiring or rewriting another library especially for sway. Also the more verbose nature of D-Bus interfaces allow easier usage, debugging and retrospection with other tools already built for D-Bus like D-Feet.

**Comment by emersion** [comment]
NACK. We already have an API, no need to add and maintain another one, and especially not D-Bus.

**Comment by Zocker1999NET** [comment]
I accept this. I get that maintaining multiple APIs is not always acceptable. But, if I am allowed to ask, why not especially D-Bus?

Also, I close this issue as *not planned* (seems to be a new feature here) so that the issue is in the "correct state" IMO.
