### ISSUE TITLE
imv and mpv broke with latest sway

### ISSUE THREAD

**Issue by primalmotion** [swaywm/sway#7050]
- **Sway Version:**
sway version 1.8-dev-e5728052 (Jun  4 2022, branch 'master')

- **Debug Log:**
https://gist.github.com/primalmotion/54dba19523531a9968bd01698331da87

With latest wlroots/sway, imv or mpv cannot launch:

mpv:
```
 mpv Downloads/recording-2022-06-04_10:06:19.mp4 
 (+) Video --vid=1 (*) (h264 1258x920 57.407fps)
 (+) Audio --aid=1 (*) (aac 2ch 44100Hz)
[ffmpeg] AVHWDeviceContext: Failed to query surface attributes: 20 (the requested function is not implemented).
[vo/gpu/vaapi-egl] failed to retrieve libavutil frame constraints
Cannot load libcuda.so.1
AO: [pulse] 44100Hz stereo 2ch float
Using hardware decoding (vaapi).
VO: [gpu] 1258x920 vaapi[nv12]
wl_surface@6: error 2: Buffer size (629x460) is not divisible by scale (2)
[vo/gpu/wayland] Error occurred on the display fd, closing

Exiting... (Quit)
```

imv:
```
imv Downloads/screenshot-2022-06-01-14:47:56.png
wl_surface@10: error 2: Buffer size (717x795) is not divisible by scale (2)
```

**Comment by emersion** [comment]
This is an mpv bug, please report it to them.

**Comment by primalmotion** [comment]
both mpv and imv that broke at the same time? I reverted wlroots and sway and they both works again

**Comment by tiosgz** [comment]
They were broken long before, but only recently wlroots started refusing that kind of behaviour. If i’m not mistaken, the relevant commit is [18595000f](https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/18595000f3a21502fd60bf213122859cc348f9af).
