### ISSUE TITLE
ID addressing issue

### ISSUE THREAD

**Issue by 0Karakurt0** [swaywm/sway#7065]
**Issue**
swaymsg can not address a window by it's ID
**Description**
I was porting a script of mine, where I rely on being able to address specific window, no matter where it is.
At first it looked promising, sway does have window ID's in window tree, but no matter how I tried I always get an error.
```
~ swaymsg [ id=10 ] focus
Error: No matching node.
```
**i3 behavior**
i3-msg can address a window by it's ID

**Comment by emersion** [comment]
`id` is for the X11 window ID. Use `con_id` for Sway's ID.

**Comment by 0Karakurt0** [comment]
> con_id

Okay, great, but then why don't I see it in window tree?
