### ISSUE TITLE
Failed assertion in wlroots render.c

### ISSUE THREAD

**Issue by benjamb** [swaywm/sway#7070]
### Please fill out the following:
- **Sway Version:**
  - 1.7

- **Configuration File:**
  - I have a few deviations from the default configs, though I can't imagine what would be relevant here. Can provide them if required.
  - Potentially relevant:
    ```
    exec swayidle -w \
        timeout 180 'swaymsg "output * dpms off"' \
            resume 'swaymsg "output * dpms on"' \
        before-sleep 'swaylock -f -i $wallpaper'
    ```

- **Stack Trace:**
  - https://gist.github.com/benjamb/ae5ca22201f7d2a6573dccd2cc2e2e7f

- **Description:**
  - I wasn't actively doing anything at the time, so really wouldn't have any idea how to reproduce this, though I will run with `-d` until I see this again. I was in a meeting when all of a sudden my sway session closed and I was dropped out to a login screen.
    I get the feeling my screen was perhaps about to reach the swayidle timeout, though this may not be at all relevant.

**Comment by benjamb** [comment]
Apologies there's no real context to work with here, but figured I should at the very least report the backtrace.

**Comment by Nefsen402** [comment]
Fixed by https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3601

**Comment by benjamb** [comment]
@Nefsen402 Great, thanks!
