### ISSUE TITLE
Could not use two external UHD monitors with a Thunderbolt 3 dock

### ISSUE THREAD

**Issue by teiesti** [swaywm/sway#7072]
I have trouble connection two external UHD monitors to my notebook via a Thunderbolt 3 dock. When trying to use full resolution (3840x2160@30Hz), both external monitors stay black.

My hardware includes

- a Lenovo Thinkpad Carbon X1 (Gen. 8),
- a Lenovo Thinkpad Thunderbolt 3 Dock (Gen. 2), and
- two Samsung UHD S27A800NMU monitors, both connected via HDMI to the dock.

The issue may be reproduced with sway 1.7 under Arch Linux using the following minimal configuration:
```
output "Samsung Electric Company LS27A80 HNMR400034" pos 0 0 res 3840x2160@30Hz
output "Samsung Electric Company LS27A80 HNMR400028" pos 3840 0 res 3840x2160@30Hz
output "Unknown 0x0608 0x00000000" pos 7680 0 res 1920x1080
```

I have tried to debug the DRM subsystem myself [as explained here](https://github.com/swaywm/wlroots/wiki/DRM-Debugging), but I do not understand what the problem is. These are the log files:
- [sway.log](https://github.com/swaywm/sway/files/8931767/sway.log)
- [dmesg.log](https://github.com/swaywm/sway/files/8931766/dmesg.log)

Here is some additional information I find worth mentioning:

1. I have tried different Sway configurations. Disabling one monitor (e.g., with `output "Samsung Electric Company LS27A80 HNMR400034" disable`) allows me to use the other monitor at 30 Hz or 60 Hz. Anyhow, the 60 Hz mode is not very stable (any ~10 seconds the monitor goes black for ~1 second).
2. I have tried my hardware with Ubuntu 20.04 running GNOME and Windows 11. In either case I can use both monitors at 30 Hz.
3. Due to the limited bandwidth of Thunderbolt 3, it should not be possible to run both monitors at 3840x2160@60Hz. Nevertheless, it should be possible to run a single monitor at 60 Hz or two monitors at 30 Hz.

**Comment by emersion** [comment]
Sounds like it's the classic

```
[   34.480549] i915 0000:00:02.0: [drm:skl_compute_wm [i915]] Requested display configuration exceeds system DDB limitations
[   34.480594] i915 0000:00:02.0: [drm:skl_compute_wm [i915]] minimum required 242/199
```

Does `WLR_DRM_NO_MODIFIERS=1` help?

**Comment by teiesti** [comment]
This does indeed solve the problem! Thank You very much!

Can you explain in simple terms what `WLR_DRM_NO_MODIFIERS=1` does? I have only found [this documentation](https://github.com/swaywm/wlroots/blob/master/docs/env_vars.md) which doesn't really explain what the drawbacks are. If this is a classic problem and there are no drawbacks, one could simply make this setting the default.

Beside that, I would suggest to give this setting a more prominent place in the [troubleshooting section](https://github.com/swaywm/sway/wiki#troubleshooting). After you suggested this, I've seen the setting explained for Nouveau but since I am not using Nouveau here, I wouldn't have thought of it myself.

**Comment by emersion** [comment]
It has drawbacks: worse performance. We have a plan to fix this, but it's complicated to implement.
