### ISSUE TITLE
Sway should (attempt to) close IPC socket on `ipc_recv_response` failure

### ISSUE THREAD

**Issue by wolterhv** [swaywm/sway#7073]
- **Sway Version:** sway version 1.7
- **Debug Log:** NA
- **Configuration File:** NA
- **Stack Trace:** NA
- **Description:**
  - As part of an unrelated crash, where Sway prints a message saying "Unable to receive IPC response" and exits, I've noticed that the IPC socket file (`/run/user/$UID/sway-ipc.$UID.$SWAY_PID.sock`) remains in place. The socket file should not remain after the death of the Sway process, therefore Sway should attempt to close the socket before exiting.

**Comment by emersion** [comment]
Sway already removes the socket on exit. On crash, Sway doesn't get the chance to do that.

**Comment by wolterhv** [comment]
Well, perhaps crash was the wrong word choice. The error is reported from [line 87 in common/ipc-client.c](https://github.com/swaywm/sway/blob/master/common/ipc-client.c#L87) by the `sway_abort` function. If `close(socketfd)` were called before `sway_abort`, an attempt to close the socket would surely be made in time before Sway's exit. Do you think this would be a bad idea?

**Comment by emersion** [comment]
ipc-client.c isn't used by Sway. It's used by swaybar/swaymsg.

**Comment by wolterhv** [comment]
Ah, that makes a lot of sense. I guess I'll have to debug the crash then. Thanks for your quick resolution.
