### ISSUE TITLE
Weird complaints about built-in commands

### ISSUE THREAD

**Issue by 04ELY** [swaywm/sway#7080]
### Please fill out the following:
- **Sway Version:**
  - sway version 1.7

- **Debug Log:**
[sway.log](https://gist.github.com/04ELY/b7824f8a012d944d85b082a4bf21da36)

- **Description:**
  - Sway complaints about built-in commands like "exec" or "include", "Unknown/invalid command"

**Comment by RPigott** [comment]
Don't share a picture of your config. Share the full text of your actual config.

Anyway your config is malformed – make sure you exit all blocks before adding more commands below.
