### ISSUE TITLE
External Monitor Instability at Higher Resolution

### ISSUE THREAD

**Issue by hughesjs** [swaywm/sway#7089]
### Please fill out the following:
- **Sway Version:**
  `v1.7`

- **Debug Log:**
[sway.log](https://github.com/swaywm/sway/files/8987627/sway.log)

- **Configuration File:**
[sway config](https://gist.github.com/hughesjs/7973b576eca5f04a93aef9378d90e3c8)

- **Stack Trace:**
n/a

- **Description:**
  - Connect external monitor via USB-C/DP
  - Set resolution to `3840x2160@60Hz`
  - Observe how the screen gets corrupted and flickers black whenever anything on-screen changes

- **Extra Notes:**
  - I can run the display fine at `3840x2160@144Hz` in Windows using the same cable and port.
  - I can run the display fine at `2560x1440@144Hz` in sway just fine which works out at more pixels/s that `3840x2160@60Hz` so that should rule-out bandwidth issues.

- **Sys Info:**
![image](https://user-images.githubusercontent.com/4203766/175836178-f2e88dc3-a3b9-49d1-a1eb-0eda243414bc.png)

**Comment by emersion** [comment]
Anything in `dmesg` by any chance?
