### ISSUE TITLE
Missing keyword in default config file

### ISSUE THREAD

**Issue by ThomFlor** [swaywm/sway#7096]
- **Sway Version:**
  sway version 1.7

- **Debug Log:**
  no need.

- **Configuration File:**
 present with default configuration.

- **Stack Trace:**
no crash

- **Description:**
  The splith and splithv keybinding don't work out-of-the-box. They lack the "layout" keyword.
Changing:
      bindsym $mod+b splith
      bindsym $mod+v splitv
To:
      bindsym $mod+b layout splith
      bindsym $mod+v layout splitv
Solves the problem.
 I believe it would be best if changed upstream.

**Comment by emersion** [comment]
`splith` is a command as well. It's the same as `split horizontal`. See the man page.
