### ISSUE TITLE
Chromium/Chrome 103+ prevents sway keybinds from activating when launched with --app and Ozone

### ISSUE THREAD

**Issue by nermolov** [swaywm/sway#7106]
- **Sway Version:** 1.7
- **Debug Log:** https://gist.github.com/nermolov/27af733d353db0f3daf72a686e0e23da
- **Configuration File:** Default
- **Description:**
  - Launch Chrome/Chromium version 103 or newer with `google-chrome --enable-features=UseOzonePlatform --ozone-platform=wayland --app="https://google.com/"` and attempt to use any sway keybindings.

Since Chrome/Chromium version 103 (problem does not occur with versions 102 and older), chrome (ozone) windows launched with the `--app` flag somehow capture all sway keybinds when they are focused. This issue does not happen with normal, non-app windows, nor does it happen when chrome is launched with xwayland.

This issue does not happen under Gnome (Gnome's keybinds work as expected).

**Comment by PremiumUsername** [comment]
I can confirm this bug. For me:
`google-chrome-stable  --profile-directory=Default --app-id=ddifbjdgicpgdgphcocemmlofhjcpnph` 
...will result in the web app consuming all key presses.  All web apps I use are affected by this bug (home-assistant, jellyfin etc.). Just as nermolov said, a regular chrome instance works like normal.

**Comment by cshei** [comment]
Seems like it also happens on KDE and is likely a Chrome regression: https://bugs.chromium.org/p/chromium/issues/detail?id=1338554

**Comment by AdamantGarth** [comment]
Workaround:
```ini
for_window [app_id="^chrome-.*"] shortcuts_inhibitor disable
```

**Comment by nermolov** [comment]
Thanks for the workaround! Works here. Seems to be intended behavior on Sway's side and it being a regression on the chrome side.
