### ISSUE TITLE
Fade in and fade out effect

### ISSUE THREAD

**Issue by nullbyto** [swaywm/sway#7107]
Hello,
I know effects are not really a focus here. As I read for the `blur` effect, which is really unfortunate. It's not easy to implement, I get it.

That's why I'm asking if it's possible to add a `fading` effect when opening/closing windows + switching workspaces.
As far as I'm concerned it is not hard to implement unlike the `blur` effect. It is just increasing/decreasing `opacity` before/after closing/opening in a way or another. 

And there are scripts that implements it, that works only for opening/closing windows:
- https://github.com/user18130814200115-2/swayscrips/tree/main/fade

I'd like to know the feedback for that.

I appreciate your great work 👍.

**Comment by emersion** [comment]
Sorry, but this is not something I'd like to add. As you mentioned, effects are out of scope, and opacity is nontrivial when an app uses multiple surfaces (e.g. sub-surfaces and popups).

**Comment by 9ktz** [comment]
Been enjoyable for me at least, thanks @nullbyto

**Comment by WillPower3309** [comment]
Shameless plus but I'll be adding this to [swayfx](https://github.com/WillPower3309/swayfx) as part of a milestone soon. So far I've replaced the renderer and updated the shaders to allow for rounded corners ([which will be merged within the next day or so](https://github.com/WillPower3309/swayfx/pull/9)), with blur being worked on next. After those two features are merged it will get an initial release upon which time work will start of animations. If this is something you want I'd suggest keeping an eye on the repo

**Comment by MubinMuhammad** [comment]
I hate the fact that you all does not support blur, fading, shadow etc. You guys have to change yourselves.

**Comment by MubinMuhammad** [comment]
I am sincerely sorry about what I said. This is my first time messaging in Github.
