### ISSUE TITLE
Virtualbox gui opens a black window without content

### ISSUE THREAD

**Issue by theailer** [swaywm/sway#711]
When opening Virtualbox GUI there is an additional black window opening. The same for each virtual machine as well.
Im not so savvy with debugging but here's atleast the xprop

```
_NET_SUPPORTING_WM_CHECK(WINDOW): window id # 0x200005
_NET_SUPPORTED(ATOM) = _NET_WM_CM_S0, _NET_WM_PID, _NET_WM_NAME, _NET_WM_STATE, _NET_WM_STATE_FULLSCREEN, _NET_SUPPORTING_WM_CHECK, _NET_WM_WINDOW_TYPE, _NET_WM_WINDOW_TYPE_DESKTOP, _NET_WM_WINDOW_TYPE_DOCK, _NET_WM_WINDOW_TYPE_TOOLBAR, _NET_WM_WINDOW_TYPE_MENU, _NET_WM_WINDOW_TYPE_UTILITY, _NET_WM_WINDOW_TYPE_SPLASH, _NET_WM_WINDOW_TYPE_DIALOG, _NET_WM_WINDOW_TYPE_DROPDOWN_MENU, _NET_WM_WINDOW_TYPE_POPUP_MENU, _NET_WM_WINDOW_TYPE_TOOLTIP, _NET_WM_WINDOW_TYPE_NOTIFICATION, _NET_WM_WINDOW_TYPE_COMBO, _NET_WM_WINDOW_TYPE_DND, _NET_WM_WINDOW_TYPE_NORMAL
_XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us", "", ""
```

**Comment by t0b1nux** [comment]
I can confirm this still behave as you described in the latest wlc+sway (github's ones).

**Comment by apreiml** [comment]
It works fine for me on the current master branch (arch with qt 5.11.1 and virtualbox 5.2.12)

**Comment by SirCmpwn** [comment]
Sweet.

**Comment by includereserved** [comment]
@apreiml In virutalbox, dialog boxes don't like to respond. Do they work for you? For example open a machines settings, go to storage and add a virtual hard disk controller, the dialog box disappears until you move your mouse on it and it the buttons on it don't work. I just installed i3 and tested it in another tty and it works fine. Kind of hard to get a video.

**Comment by apreiml** [comment]
@includereserved I've tried it on the current sway and wlroots master branch and it works fine for me. (Virtualbox 5.2.16). There was done a lot of work on floating windows in the last weeks though.
