### ISSUE TITLE
Add inverse of $mod+a (focus parent)

### ISSUE THREAD

**Issue by PAI5REECHO** [swaywm/sway#7111]
I'm unable to unfocus if I have the top most parent focused, I have to click my mouse once. There should be a keybind for this.

**Comment by PAI5REECHO** [comment]
Nevermind, time to use a different window manager (https://github.com/swaywm/sway/issues/6977#issuecomment-1134227758)

**Comment by Emantor** [comment]
FWIW, `man 5 sway` says that there also is a `focus child`.
