### ISSUE TITLE
Grimshot: copy and save

### ISSUE THREAD

**Issue by Nielius** [swaywm/sway#7116]
Grimshot allows you to copy to clipboard, or save to a file. It would be nice of there was also a copy-and-save option. (That is especially useful for a keyboard shortcut, in my opinion.)

Would you be open to a PR where I add `copysave` as an additional action?

**Comment by dasehak** [comment]
@adastx, you can use wl-copy for copying:
`wl-copy < $(grimshot save area 123.png)`

**Comment by emersion** [comment]
`contrib/` has been moved to another repo, see https://github.com/swaywm/sway/pull/7541
