### ISSUE TITLE
gray background

### ISSUE THREAD

**Issue by blackscreenissue** [swaywm/sway#7117]
### Please fill out the following:
- **Sway Version:**
  - swaymsg version 1.7

- **Debug Log:**
- https://pastebin.com/jG9XdRs8 

- **Configuration File:**
- Default

- **Stack Trace:**
- N

- **Description:**
Installed sway, gray background. 
attempted to change background from default, still gray background.
I have no idea what is wrong, there no errors nothing
I am using Nvidia open source driver if it matters

**Comment by emersion** [comment]
It seems like `swaybg` is not in your `$PATH`. It's a runtime dependency of Sway.

**Comment by blackscreenissue** [comment]
> 

Thanks installing it fixed it.
shouldn't swaybg be a required dependency?
