### ISSUE TITLE
Sway is super slow

### ISSUE THREAD

**Issue by blackscreenissue** [swaywm/sway#7118]
### Please fill out the following:
- **Sway Version:**
  - sway version 1.7

- **Debug Log:**
  - https://pastebin.com/jG9XdRs8

- **Configuration File:**
- default
https://pastebin.com/jG9XdRs8

- **Description:**
  - from moment I installed sway it is just chubby but slowness get much worse when i open an application like terminal that has been configured to have background opacity, it makes sway so slow it can't be used
  - keep in mind slowness happen only when i hover my house on other windows other than opacity one,one error i noticed from running "foot" inside foot to see logs is this error: "warn: render.c:2503: compositor is not releasing buffers immediately; expect lower rendering performance"
  - slowness from opacity is not just foot's problem but it also happen with any application that supports background opacity

**Comment by emersion** [comment]
```
00:00:00.004 [DEBUG] [wlr] [render/wlr_renderer.c:305] Skipping GLES2 renderer: no DRM FD available
```

Sounds like Sway doesn't detect any GPU on your system.

**Comment by blackscreenissue** [comment]
> ```
> 00:00:00.004 [DEBUG] [wlr] [render/wlr_renderer.c:305] Skipping GLES2 renderer: no DRM FD available
> ```
> 
> Sounds like Sway doesn't detect any GPU on your system.

How?? Sway is working fine except for the slowness so clearly it detects my gpu? I think this is a bug

**Comment by emersion** [comment]
You are running Sway nested inside another Wayland compositor, and that compositor doesn't advertise any GPU.

**Comment by blackscreenissue** [comment]
don't close this, that is not the case as i run sway directly from tty

**Comment by bl4ckb0ne** [comment]
> 00:00:00.004 [INFO] [wlr] [wayland] unable to lock lockfile /run/user/1000/wayland-1.lock, maybe another compositor is running

Are you trying to run sway twice on the same computer?

**Comment by blackscreenissue** [comment]
no i just log in tty and type 'sway' and sway starts

**Comment by emersion** [comment]
The debug log comes from a nested Sway.

**Comment by blackscreenissue** [comment]
> The debug log comes from a nested Sway.

ohhh correct the log does come from nested sway , how do i get debug log without nesting sway?

**Comment by blackscreenissue** [comment]
nvm I figured it out, here's non-nested log
https://pastebin.com/Cj1f0gW8

**Comment by bl4ckb0ne** [comment]
> nvc0_screen_create:1085 - Base screen init failed: -19

looks like a driver issue

**Comment by blackscreenissue** [comment]
> > nvc0_screen_create:1085 - Base screen init failed: -19
> 
> looks like a driver issue

what can i do about it? i have nvidia so my options are limited

**Comment by emersion** [comment]
Check if you card is supported by Nouveau. If so, open a Mesa bug report. If not, you're out of luck.

**Comment by bl4ckb0ne** [comment]
Report it to [mesa](https://gitlab.freedesktop.org/mesa/mesa/-/issues), try to [dig in the code](https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/gallium/drivers/nouveau/nouveau_screen.c#L191)

**Comment by blackscreenissue** [comment]
> Check if you card is supported by Nouveau. If so, open a Mesa bug report. If not, you're out of luck.

it is supported, sway was working flawless couple months ago but now its not for some reason

**Comment by emersion** [comment]
I see. Then I'd suggest asking folks in #nouveau on Libera Chat and reporting a Mesa bug.

**Comment by blackscreenissue** [comment]
> I see. Then I'd suggest asking folks in #nouveau on OFTC and reporting a Mesa bug.

got it, but in mean time do u suggest i downgrade mesa and nouveau? will that have any security complications
