### ISSUE TITLE
I want commands executed during sway exit.

### ISSUE THREAD

**Issue by amano-kenji** [swaywm/sway#7128]
I want to start a user process supervisor when sway starts up and kill it when sway exits.

Executing commands when sway starts up is easy.

But, I can't execute commands in sway configuration when sway exits.

I want something like

```
exec --on-exit cmd ...
```

or

```
exec-on-exit cmd ...
```

**Comment by emersion** [comment]
You can achieve something like this by waiting for `WAYLAND_SOCKET` or `SWAYSOCK` to be closed. For instance, `swaymsg -m -t SUBSCRIBE '[]'` should exit when Sway does.

**Comment by amano-kenji** [comment]
What about

```
exec --die-on-exit cmd ..
```

This starts a command when sway starts and kills it when sway exits.

**Comment by amano-kenji** [comment]
I think you will have to write a script that communicates with sway over an IPC channel.

**Comment by tmccombs** [comment]
Using IPC, as I understand at least, the command is run _after_ sway stops, or at best concurrently with sway shutting down. There isn't a way to run a command _before_ the actual shutdown happens.
