### ISSUE TITLE
Ability to define sway session services easily.

### ISSUE THREAD

**Issue by amano-kenji** [swaywm/sway#7129]
In theory, I can execute a sway session service with this.

die-with-sway

```
#!/bin/sh

sh -c "$@" &
pid=$!

swaymsg -m -t subscribe '[]'

kill $pid
```

~/.config/sway/config

```
...

exec die-with-sway cmd arg1 arg2 ...

...
```

But, this is a one-off hack that will not be used by other people. I want this capability to be readily available to every sway user. Most sway users don't know about subscribe hack.

I propose a new sway command like `exec-die-on-exit`. It would be written as

```
exec-die-on-exit cmd arg1 arg2 ...
```
in sway config. Any command executed by `exec-die-on-exit` dies when sway exits.

In theory, I can create a custom login session that executes programs before executing sway and kills the program after sway exits, but the programs executed before sway don't have access to graphical environment.

If process supervision is wanted, I can do something like

```
exec-die-on-exit dinit
```

dinit can be a user process supervisor.

**Comment by amano-kenji** [comment]
It turns out that anything that requires graphical environment would die with sway anyway.

**Comment by mhmdanas** [comment]
For anybody looking to use the `die-with-sway` script as given in the issue, keep in mind that `"$@"` should be replaced with `"$*`", like so:

```sh
#!/bin/sh

sh -c "$*" &
pid=$!

swaymsg -m -t subscribe '[]'

kill "$pid"
```

This is because `sh -c` expects the whole command to be passed as one argument, but `"$@"` expands to the arguments exactly as passed to `die-with-sway`. `"$*"` meanwhile expands into the arguments as one string, which is what we need here.

**Comment by amano-kenji** [comment]
Or, you can just call

```
"$@" &
```

**Comment by mhmdanas** [comment]
That also works, but keep in mind that it may not work as expected if you pass any piped commands.
