### ISSUE TITLE
RFE: port to pcre2

### ISSUE THREAD

**Issue by kloczek** [swaywm/sway#7131]
From: https://www.pcre.org/
"There are two major versions of the PCRE library. The current version, PCRE2, [released in 2015,](https://lists.exim.org/lurker/message/20150105.162835.0666407a.en.html) is now at version 10.39.

The older, but still widely deployed PCRE library, originally released in 1997, is at version 8.45. This version of PCRE is now at end of life, and is no longer being actively maintained. Version 8.45 is expected to be the final release of the older PCRE library, and new projects should use PCRE2 instead."

**Comment by emersion** [comment]
We are already using PCRE2.

**Comment by kloczek** [comment]
In last release I still see
https://github.com/swaywm/sway/blob/5543acff06981639086bc9a0fc9b608796a23e84/meson.build#L39

**Comment by kloczek** [comment]
https://github.com/swaywm/sway/blob/89d73beedbad2d484adc85fe114680e85d391958/meson.build#L48
Do you have any plans to make the new release soon? 🤔

**Comment by kloczek** [comment]
Any update? 🤔 
it would be good to have new release not only pcre2 but wlroots updates.
