### ISSUE TITLE
Cannot launch Sway without --unsupported-gpu even with intel card selected (intel+nvidia hybrid graphics)

### ISSUE THREAD

**Issue by Thymelizabeth** [swaywm/sway#7133]
- **Sway Version:**
  - sway version 1.7

- **Debug Log:**
  - https://gist.github.com/Thymelizabeth/c5075e88d50c1d67928254f5af8734b4

- **Configuration File:**
  The error occurs with the default configuration.

- **Description:**
  - Running Sway on Gentoo with Openrc, Intel+Nvidia hybrid graphics. Nvidia proprietary driver installed.
  - Only 2 cards in /dev/dri.
  - Run `sway` with WLR_DRM_DEVICES set to either of the 2 cards, and it will try to run with the proprietary Nvidia driver. 

- **Expectation:**
  - That Sway will not try to start using the proprietary Nvidia driver.

**Comment by emersion** [comment]
This is intended. Sway will bail out if the proprietary kernel module is loaded.
