### ISSUE TITLE
Sway crash on switching workspaces after closing swaylock

### ISSUE THREAD

**Issue by ChemicalXandco** [swaywm/sway#7140]
### Please fill out the following:
- **Sway Version:** 1.7 (arch linux)

- **Debug Log:**
https://gist.github.com/ChemicalXandco/aca2f22d1923427318eaf80d9647aca3

- **Configuration File:**
mostly default other than uncommenting:
```
exec swayidle -w \
         timeout 300 'swaylock -f -c 000000' \
         timeout 600 'swaymsg "output * dpms off"' resume 'swaymsg "output * dpms on"' \
         before-sleep 'swaylock -f -c 000000'
```

- **Stack Trace:**
https://gist.github.com/ChemicalXandco/9c10f85d7f655a17d85efd9014c52c23

- **Description:**
It occurs when switching workspaces immediately after the screen has been unlocked. Specifically this occurred when switching to a workspace with fullscreen Minecraft running under Xwayland but I have also had this problem with other applications running on Xwayland (not fullscreen).

**Comment by mbessler** [comment]
I'm experiencing the same issue on sway 1.7 on Ubuntu 22.04.

**Comment by ChemicalXandco** [comment]
Unable to produce with sway version `1.8.1`.
