### ISSUE TITLE
Two external monitors: Can't reenable monitor

### ISSUE THREAD

**Issue by mb720** [swaywm/sway#7142]
- **Sway Version:**
  1.7

- **Debug Log:**
  I ran Sway with `sway --config /etc/sway/config --debug --verbose &> ~/sway_debug.log`. [Here](https://gist.github.com/mb720/76e3eb2c1b3bd2f7b0b4454924b14201) are the contents of `sway_debug.log`.

- **Configuration File:**
Config file used was the unaltered `/etc/sway/config`.

- **Description:**
  - I have two external monitors attached to a Lenovo X220. One monitor is connected via VGA (output VGA-1), the other is connected via DisplayPort (DP-2).
  - Starting Sway, both external monitors work splendidly (they get the video signal). The laptop's screen (LVDS-1) is off, as expected since the X220 has [a limitation](https://forums.lenovo.com/t5/X-Series-ThinkPad-Laptops/Dual-screens-on-x220-amp-Ubuntu-12-04/td-p/769331) of outputting at maximum to two monitors simultaneously. `swaymsg -t get_outputs` shows LVDS-1 as inactive, both VGA-1 and DP-2 are active. Everything's fine.
  - I turn off the DP-2 monitor.
  - I turn the monitor back on. The monitor stays black, it has no signal. `swaymsg -t get_outputs` lists DP-2 and says it's inactive.
  - Trying to activate the monitor with `swaymsg output DP-2 enable` doesn't do anything.
  - I restart Sway and both monitors work fine again.
  - What sticks out are these errors from the log, repeated until I exit Sway:

        [ERROR] [wlr] [types/output/output.c:894] Failed to get primary display formats
        [DEBUG] [wlr] [types/output/render.c:267] Output doesn't support format 0x34325258
        [ERROR] [wlr] [types/output/render.c:59] Failed to pick primary buffer format for output 'LVDS-1'

  - The same errors occur when I unplug the VGA monitor and plug it back in.
  - If I start Sway with DP-2 as the only attached external monitor, I can turn it off and on again without issues.

**Comment by Emantor** [comment]
Please post the full debug log file.

**Comment by mb720** [comment]
> The log file indicates that LVDS-1 still has the `desired_enabled` flag set. Did you explicitly disable LVDS-1?

Yes, but before that Sway session whose debug log I've linked. I issued `swaymsg output LVDS-1 disable` in a previous session.

Thanks for looking into this.

**Comment by ohthehugemanatee** [comment]
probably related to #7003  and #6962 . 

OP, can you try running a build of wlroots since that patch?

**Comment by mb720** [comment]
@ohthehugemanatee: Thanks for the pointer. I built the latest version of Sway and wlroots using `sudo aura -A --force sway-git wlroots-git`. I used `--force` to avoid this issue:

>ERROR: A package has already been built. (use -f to overwrite)

Without restarting Sway, I ran `sway --version` which showed:

>sway version 1.8-dev-07bfeb2a (Sep  8 2022, branch 'master')

I ran `swaymsg output LVDS-1 disable;swaymsg output DP-2 enable` to get the desired setup with the two monitors connected via VGA and DisplayPort active and the laptop's monitor (LVDS) disabled.

To my surprise turning the monitor connected with DisplayPort off and on worked now: It got the signal and was usable after turning it back on. Also unplugging and plugging the VGA monitor back in worked. The symptoms of the issue were gone.

I was a bit suspicious that things were fixed after not having restarted Sway since I assumed it was still the old process running.

After rebooting (in passing I upgraded the kernel to 5.19.7) and starting Sway, it seems that the issue is back again: The DisplayPort monitor doesn't get a signal after turning it off and back on. Both LVDS (laptop monitor) and the DisplayPort monitor stayed black/inactive. Running `swaymsg output DP-2 enable` did not do anything visible.

Experimenting, I ran `swaymsg output LVDS-1 disable;swaymsg output DP-2 enable` again and the DisplayPort monitor indeed turned on (LVDS stayed inactive, as expected).

I assume it's as @Emantor hinted at: Explicitly disabling LVDS fixes it (although it was already off at that time).

Thanks everybody for your help! 👍

I'll keep testing this setup with two external monitors and report back if I run into problems as well as their fixes, if I have any.
