### ISSUE TITLE
Bluetooth audio doesn't work without dbus

### ISSUE THREAD

**Issue by hboetes** [swaywm/sway#7148]
This is a request for enhancing the documentation/FAQ with the following lessons learned.

The long story: https://bugzilla.redhat.com/show_bug.cgi?id=2019631

TLDR; if you start sway without using a display manager like gdm, you'll have to invoke it with dbus, or else Bluetooth audio won't work, i.e.

  `dbus-run-session sway`

For example my start script for sway looks like this:

```
#!/bin/zsh
export PATH="//usr/local/sbin:/usr/local/bin:/sbin:/usr/sbin:/bin:/usr/bin:/usr/games:/music/bin"
export TMP="$HOME/.local/tmp"
export TMPDIR="$TMP"
export XDG_RUNTIME_DIR=/run/user/$(id -u)
export XDG_CURRENT_DESKTOP=sway
export XDG_SESSION_TYPE=wayland
gnome-keyring-daemon --start --components=pkcs11,secrets -d
exec dbus-run-session sway
```

TAG: br-connection-profile-unavailable a2dp-sink profile connect failed

**Comment by emersion** [comment]
Sway has nothing to do with audio.
