### ISSUE TITLE
Firefox menus disappear as soon as tooltips pop up

### ISSUE THREAD

**Issue by mightyiam** [swaywm/sway#7149]
### Please fill out the following:
- **Sway Version:** 1.7

- **Debug Log:** https://gist.github.com/mightyiam/c150c27cfc9c0bc5b9ce0e43f0ea2508

- **Configuration File:** I did manage to reproduce with pretty much the default config, but for reasons I did not investigate the firefox took a very long time to appear from the moment I launched it.

- **Stack Trace:**
No crash

- **Description:**

In Firefox, the opening of a tooltip (by hovering over some UI elements with the mouse pointer) causes UI windows, such as extension windows and Firefox's own menu to disappear.

For example, I click the burger menu button in the toolbar, causing the menu to open. I then take the mouse pointer off of that button and return it back to that button. Soon, a tooltip "Close application menu" appears and the menu that was open and visible disappears.

The tooltip text seems to suggest that the menu is still open. So I guess that it remains open and what occurs when the tooltip opens is that the primary Firefox window gets above the menu window in the z dimension.

**Comment by git-bruh** [comment]
fixed in sway-git. Just encountered this and thought it might be an nvidia thing as always but I stumbled upon some similar issues like #7011 which suggested to use sway-git

**Comment by mightyiam** [comment]
I'm sorry, @git-bruh . What is sway-git, please?

**Comment by git-bruh** [comment]
It means that it's fixed in a commit on the sway repo but it's not been included in a release yet

**Comment by emersion** [comment]
Please re-open if you can reproduce with the latest commit.

**Comment by mightyiam** [comment]
I'm happy to hear it's fixed in development. I'll look forward to the release and update of the nix package.
