### ISSUE TITLE
Flicker with called Sway Menus from Wofi / Swayr

### ISSUE THREAD

**Issue by zDEFz** [swaywm/sway#7153]
### Please read the following before submitting:

https://user-images.githubusercontent.com/24463722/187961933-280de52f-0a7d-494b-82a5-d97947e7e41d.mp4

### Please fill out the following:
- **Sway Version:1.7**

- **Debug Log:**
  - https://termbin.com/q833

- **Configuration File:**
- https://termbin.com/qxvm

- **Stack Trace:**
- not applicable

- **Description:**
  - Sway flickers on one of my monitor when swayrd calling its native menu/s. 
  
  Video:

**Comment by Zeioth** [comment]
No idea what could be the cause, but it doesn't happen on my end with sway 1.7 and wofi. Did you try with a different wofi config file?

**Comment by zDEFz** [comment]
I found the solution and the issue. Wofi is incapable of setting height and width with two monitors that are 1920x1080, but one is in portrait mode. The solution? Supply height and width extra. Like 

Control+e exec wofi -H 800 -W 800 -s /home/def/.config/wofi/style.css --show drun

That aint a wofi problem, but probably the issue is that appropriate dimensions are not given by default.

**Comment by zDEFz** [comment]
I added a issue on swayr, perhaps they can issue a bugfix for something that isnt even their fault. https://todo.sr.ht/~tsdh/swayr/28

**Comment by zDEFz** [comment]
Turns out we have to configure to have fixed width and height. But why does it flicker in the first place. no clue!

**Comment by languitar** [comment]
Here is the related wofi bug: https://todo.sr.ht/~scoopta/wofi/183. Shouldn't this issue here be re-opened? At least the wofi developer thinks this might be a sway bug.

**Comment by zDEFz** [comment]
> Here is the related wofi bug: https://todo.sr.ht/~scoopta/wofi/183. Shouldn't this issue here be re-opened? At least the wofi developer thinks this might be a sway bug.

Alright. I re-opened the issue.

**Comment by francocalvo** [comment]
I have the same problem! The current workaround is setting a fixed height/width when calling wofi then?

**Comment by zDEFz** [comment]
> I have the same problem! The current workaround is setting a fixed height/width when calling wofi then?

precisely. Think it was -H 800 -W 800 or so in my config for 1920x1080

**Comment by alxndr13** [comment]
This issue can be closed, or? this is not a sway bug then.
