### ISSUE TITLE
Removing python-xlib dependency from inactive-windows-transparency contrib script

### ISSUE THREAD

**Issue by gibbz00** [swaywm/sway#7166]
Hi!

Found a guy on reddit, @difrex, that implemented the Sway IPC bindings in Go and used them to create his own inactive-windows-transparency script. 

* Reddit post:
https://www.reddit.com/r/swaywm/comments/fip3oh/comment/fkjka27/?utm_source=share&utm_medium=web2x&context=3
* Script:
https://github.com/Difrex/sway/blob/master/scripts/transparent_inctive.go 
* Sway IPC bindings in Go;
https://github.com/Difrex/gosway

I'm quite picky with my system packages and noticed that the currently included contrib script requires the python-i3ipc package, which in turn has the python-xlib dependency. 

* Current contrib script:
https://github.com/swaywm/sway/blob/master/contrib/inactive-windows-transparency.py
* python-i3ipc dependencies:
https://github.com/altdesktop/i3ipc-python/blob/master/requirements.txt 

Am I wrong to assume that python-xlib is irrelevant for our purposes? Would it be an enhancement to replace the current script with Difrex's go version? Not in terms of performance gains but, but maybe more in terms of not having ~30K lines of unused code as a dependency for a rather simple feature. 

Any comments stating your stance towards this potential effort would be greatly appreciated :)

**Comment by emersion** [comment]
Opened https://github.com/altdesktop/i3ipc-python/issues/198

**Comment by emersion** [comment]
Upstream no longer depends on python-xlib.
