### ISSUE TITLE
Invisible mouse cursor on void install 

### ISSUE THREAD

**Issue by riotearring** [swaywm/sway#7169]
### Please fill out the following:
- Sway Version 1.7
 `

- **Debug Log:**
https://gist.github.com/riotearring/871dd616887344f2af220c155472234c

 **Configuration File:**
 reproduced using default config file

- **Stack Trace:**
Sway does not crash 

- **Description:**
Install Sway on void linux, using elogind following arch-wiki, void official docs, and sway wiki. I cannot remember the exact changes I made such as changing a few environment variables. 
Install computer is Asus X301A using Intel i3-2328M CPU and Intel 2nd Generation Core Pro GPU

Notice that  everything works as intended (keyboard, second monitor..) but that even though mouse is detected and works (I can click on objects and if I hover over icons they may change) mouse cursor is invisible, no matter what app is used. 
Try changing icon theme through swayconfig and seat0, and try setting WLR_NO_HARDWARE_CURSORS=1 as descrbed in sway wiki and notice that nothing changes. 

Thanks in advance for any help, it is getting tricky to use my laptop, even though sway is great for using with no mouse.

**Comment by emersion** [comment]
These logs are using a nested Wayland backend. Please post logs of Sway running directly from a TTY.

**Comment by riotearring** [comment]
I just tried with both default and personal config in TTY2 from and had no issue, could see my mouse cursor. Thanks a lot, it must be because of the way I'm launching sway. Thanks a lot for helping me diagnose this.
I'm launching sway from TTY1 using Fish, as described in the wiki, any idea this happens ?  
Otherwise I guess this issue can be closed, thanks again.

**Comment by ldelossa** [comment]
This seems to be an issue on Fedora when I upgraded to kernel 5.19.13. Downgrading back to 5.19.11 fixed my issue. 
Need to do some work, but will hopefully will have time to get some logs on the broken kernel in a bit.
