### ISSUE TITLE
Can't click anything in specific apps, on specific displays in a multi monitor config

### ISSUE THREAD

**Issue by GeorgeBroughton** [swaywm/sway#7171]
So, here's the situation.

I installed Sway on my 5 monitor setup. Here's my config:
```
# 4K
output HDMI-A-1 pos 0           0
# 1080p
output DP-5     pos 3840        0
# 1080p
output DP-6     pos -1920       0
# 1080p
output DP-8     pos 3840        1080
# 1080p
output DP-9     pos -1920       1080
```
Any monitor a negative number is used on, i cannot click any menu items in applications like `Discord`, `gimp`, `firefox`, `vscode`

In the end, it was an easy fix:
```
# 4K
output HDMI-A-1 pos 1920 0
# 1080p
output DP-5     pos 5760 0
# 1080p
output DP-6     pos 0    0
# 1080p
output DP-8     pos 5760 1080
# 1080p
output DP-9     pos 0    1080
```
I would at least like some kind of error for this though if it isn't supported.

**Comment by emersion** [comment]
It's supported by Sway/Wayland, but not by X11.

**Comment by GeorgeBroughton** [comment]
Interesting, because I'm running it on Wayland

**Comment by ragusa87** [comment]
I often have issue with XWayland application (can't click, menu don't open) when using a screen that has a position different from (0,0). My workaround is to move the screen on position 0,0 and use the X11 Application in it.

**Comment by smlx** [comment]
This third-party bug is [documented in the FAQ](https://github.com/swaywm/sway/wiki#mouse-events-clicking-scrolling-arent-working-on-some-of-my-workspaces). It is [unlikely to be fixed](https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/395#note_555613).
