### ISSUE TITLE
Get list of key bindings via swaymsg

### ISSUE THREAD

**Issue by deifactor** [swaywm/sway#7179]
I'd like to be able to invoke `swaymsg <something>` to get the list of current bindings formatted via JSON along the lnes of

```json
[
  {
    "key": "Mod1+shift+a",
    "ccommand": "layout none",
    "locked": false
  }
]
```

I don't particularly care about the format or what the exact swaymsg incantation has to be, just that it has the same information that you'd get by reading the original bindsym commands.

The use case for this is that I'm trying to build something that emulates a feature in awesomewm that shows a list of your keybinds, and in order to do that I need to know what the keybinds actually are. I can parse the output of `swaymsg -t get_config`, but it'd be cleaner if it was already presented in JSON format for me, and that also doesn't appear to include any 'manual' invocations of `swaymsg bindsym`.

**Comment by deifactor** [comment]
Aaaand double-checking I immediately see this is a dupe of #5561.

**Comment by RPigott** [comment]
> Aaaand double-checking I immediately see this is a dupe of #5561.

I have been running that patch since I posted it, so it's been maintained. If you want to use it and have any issues feel free to report them to me.

**Comment by deifactor** [comment]
> > Aaaand double-checking I immediately see this is a dupe of #5561.
> 
> I have been running that patch since I posted it, so it's been maintained. If you want to use it and have any issues feel free to report them to me.

Yeah, I'll let you know if I run into anything. I might try parsing it out of the config just for fun and as a coding exercise, or just using [remontoire](https://github.com/regolith-linux/remontoire) since no approach that doesn't involve magic comments will give me nice names.
