### ISSUE TITLE
Segfault with gucharmap

### ISSUE THREAD

**Issue by FreeFull** [swaywm/sway#718]
Reproduction steps:
- Start gucharmap with the GDK_BACKEND environment variable set to wayland
- Float the gucharmap window
- Press Ctrl+f to open the find dialogue
- Move mouse to switch focus back to the main gucharmap window
- Close gucharmap

Swaylog:
https://gist.github.com/FreeFull/73bc768183f7fea34074caeb26faaa71

**Comment by SirCmpwn** [comment]
I'm closing issues that are resolved by the yet-unreleased sway 1.0.
