### ISSUE TITLE
Systemd-managed start + XDG autostart, yet another take

### ISSUE THREAD

**Issue by Vladimir-csp** [swaywm/sway#7181]
- **Description:**
Hi!
I've created an integrated and plugin-extendable script for managing sessions for sway (and other wayland WM's). It supports environment management, XDG autostart, including best effort clean stop. I hope it might be of interest.
https://github.com/Vladimir-csp/uwsm/

**Comment by bl4ckb0ne** [comment]
You can add you project to the wiki, it's open for public edit. Issues are not made for sharing projects.
