### ISSUE TITLE
Touchscreen support

### ISSUE THREAD

**Issue by tinchou** [swaywm/sway#721]
Hi,

I've been using sway for a couple of weeks. Great work :).

I have a Lenovo Yoga 3 14'', which has a touchscreen. It seems to be supported with different X desktops like LXDE, Unity, i3, but not on sway. It can scroll and sometimes pinch and zoom, but the focused element is usually wrong. I can't tap on any button because of this focus issue.

I just installed Weston, and it seems like touch works pretty well on weston-terminal, but I opened pcmanfm and I couldn't even hit the close button (pretty much what happens on sway). However, a weston-terminal window in sway doesn't work well. 

Anyway, I'm not sure who has to work on touch support (Wayland? WLC? Sway?), so I'm posting this here as a starting point.

Thanks,
Martín.

**Comment by SirCmpwn** [comment]
Probably best for this to go into wlc. It provides us some touch stuff but it doesn't work well.

**Comment by GrayHatter** [comment]
@tinchou I'm going to take a look at this, could you explain in very descriptive detail what's going wrong, why you think it's happening, and what you expect to be happening?

**Comment by tinchou** [comment]
I'm having trouble with my Arch installation at the moment. Will let you
know when I can test this!

**Comment by tinchou** [comment]
Hi, I'm back :).

Let's start with a very simple feature: I want to be able to touch buttons!

My primary use case is Google Chrome, but even with a native app like `pcmanfm` I can't touch them.

But that is very weird because scrolling and zooming *kind of* works. With Chrome, I am able to scroll the page, but the behavior is very weird:

1. Touch and drag the page. It scrolls.
1. Do (1) again. The page scrolls back to the original position, so you'll never be able to go down more than one page.
1. It doesn't keep scrolling after you lift your finger (I think it's called momentum scrolling)

**Comment by SirCmpwn** [comment]
So work on it?

**Comment by tinchou** [comment]
That's a great idea, but I haven't found the time yet. @GrayHatter seems to be interested in working on this, so I'm trying to help in some way.

**Comment by GrayHatter** [comment]
Yeah, I'm planning to put a little work in to touchscreen on sway when I get a few other projects cleaned up.

**Comment by ranmacar** [comment]
Hi!

Any progress on this? I just started with sway, as it seemed to be the only option for my yoga notebook with a second screen (not hidpi). Is there some way I could help?

Thanks

**Comment by JaneSmith** [comment]
I'd love to see a tiling window manager with solid touchscreen support. Maybe I'm wrong, but from my experience tiling window managers always seem to lack touch support entirely, and even have poor mouse support. While being keyboard-friendly is an advantage of TWMs, that doesn't mean mouse or touch support should be abandoned. A good use case for this in my opinion would be hybrid tablets/laptops. People often recommend TWMs on laptops to make use of the limited screen space and be more effective with a keyboard, but as soon as you switch it to tablet mode you need to rely on touch input only.

**Comment by matiasbattocchia** [comment]
I managed to calibrate my touchscreen accuracy following this [article](https://wiki.archlinux.org/index.php/Calibrating_Touchscreen). It seems that both the status bar (i3status) and the window title bar introduce an offset of 40 px in my setup. Now it works rather well with certain programs. It is not the case of Firefox/Chrome; I think it also depends on the software support for touch interaction.

Window focus and screen splitting are still problematic. 

Example configuration for the aforementioned guide.

```
total_width  = 1366
total_height =  768

touch_area_x_offset =   0
touch_area_y_offset = -40

touch_area_width  = total_width  
touch_area_height = total_height
```

**Comment by ellbur** [comment]
For anyone finding this page while searching touchscreen issues, I'll just note that my touchscreen on my Dell Latitude E7250 works great after I configured it with:

    input 1003:35459:Atmel map_to_output eDP-1 

See `man 5 sway-input` for the setting.

**Comment by voronind-com** [comment]
Sorry for necroing, but I have an issue with some of the taps not working as clicks. I need to tap like 20 times for it to register as a click. I tried setting `tap` but no luck. Any known ways to make taps behave like on a touchpad?
