### ISSUE TITLE
[grimshot] add an option to delay taking a screenshot

### ISSUE THREAD

**Issue by Pebor** [swaywm/sway#7215]
- **Description:**
Adding an option to first select a target, wait [amount] of time and only then take the screenshot in that area/target would be helpful for, my use case, screenshoting right click or pick list menus, or overall, things like dmenu which take all input away (or get closed when input is registered, etc...).

**Comment by vyivel** [comment]
Wrong repo?
https://github.com/hyprwm/contrib

**Comment by Pebor** [comment]
Sorry, my bad, ofc grimshot

**Comment by ebbit1q** [comment]
with merging https://github.com/swaywm/sway/pull/7541 this can now be closed as completed
