### ISSUE TITLE
'bindsym --release' emmits Escape + the binded key

### ISSUE THREAD

**Issue by JosefLitos** [swaywm/sway#7217]
### **Description:**
example config:
`bindsym --release Mod4+Mod1+q exec sleep 1 && echo random command`
When run in a shell, or vim for a better example, the Escape and q keys seem to get pressed.
i3 forwards no keyboard output when using any keybindings

**Comment by thesword53** [comment]
I have the same issue after updating XWayland to `22.1.4`. `22.1.3` works fine.

**Comment by JosefLitos** [comment]
I am not using xwayland

**Comment by JosefLitos** [comment]
This shouldn't be that hard to fix, the key combo shouldn't be passed through when pressed just as a normal combo.

**Comment by junaruga** [comment]
I wanted to use the Space key as a left mouse key enabling the drap & drop by the sway config with [ydotool](https://github.com/ReimuNotMoe/ydotool). However, it seems that the `bindsym --release` doesn't sometimes react.

```
mode "media" {
    # Left down (drag and drop start)
    bindsym Space exec "sudo ydotool click 0x40"
    # Left up (drag and drop end)
    bindsym --release Space exec "sudo ydotool click 0x80"
    ...
}
```
