### ISSUE TITLE
Option to not destroy empty workspaces

### ISSUE THREAD

**Issue by luke876** [swaywm/sway#7220]
I like to assign specific workspace numbers to each of my monitors.
It's pretty simple to hardcode these into the config file with a static monitor layout, but on a laptop with dynamic outputs this becomes a nightmare. Using kanshi I can move specific workspaces onto specific monitors depending on the monitor layout, but new workspaces are always created on the focused monitor.

An option to keep empty workspaces would solve this issue.

**Comment by emersion** [comment]
Sorry, we're not accepting any new window management features anymore. See https://github.com/swaywm/sway/blob/master/CONTRIBUTING.md#scope-of-future-changes-to-sway
