### ISSUE TITLE
Wayland session file is missing optimal config option for use with GDM

### ISSUE THREAD

**Issue by brianredbeard** [swaywm/sway#7222]
- **Description:**
A few years ago a new mechanism was introduced to GDM allowing for better session handling, especially in cases of X11 fallback:

> Recording when sessions start, for Wayland → Xorg fallback or
transitioning to the user session, is currently done with timeouts.
>
> This isn't ideal, because on some very slow machines the timeout can be
hit before the session has had a chance to fail: if gnome-session takes
more than 3 seconds to fail then the session will be considered to have
exited rather than failed, and so we don't do Xorg fallback.
>
> We can do this more reliably if we allow sessions to optionally register
themselves with GDM. Then we will know when they've started, so can shut
down the greeter or fall back to Xorg as appropriate. The mechanism is
that they specify X-GDM-SessionRegisters=true in their file, and then
call RegsterSession on the DisplayManager interface on the bus to say
that they've started up. If X-GDM-SessionRegisters is missing or false,
GDM will call the same method for them after 10 seconds.

https://gitlab.gnome.org/GNOME/gdm/-/merge_requests/67

This issue is resolved by #7221

**Comment by bl4ckb0ne** [comment]
As pointed in #7221, this is GDM specific.

**Comment by RPigott** [comment]
As also pointed out in #7221, it doesn't actually solve your issue because it relies on sway to register its session over dbus, which it won't do.
