### ISSUE TITLE
I can't launch sway on alpine docker image. It gives drmGetDevices2 failed and No DRM backend supplied erros.

### ISSUE THREAD

**Issue by RajaMuneerBaigal** [swaywm/sway#7224]
Hi, I am trying to install swaywm on the alpine image in docker. I follow all the steps in the given link [ swayonalpinelinux](https://wiki.alpinelinux.org/wiki/Sway.)
I built the image and then try to run it using these commands.
`docker run -it -e XDG_RUNTIME_DIR=/home/Baigal \
           -e WAYLAND_DISPLAY=wayland-0 \
           -v $XDG_RUNTIME_DIR/$WAYLAND_DISPLAY:/tmp/wayland-0  \
           --user=Baigal \
           -e WLR_BACKENDS=headless \
           -e WLR_LIBINPUT_NO_DEVICES=1 \
           -e WLR_DRM_NO_MODIFIERS=1 \
            test dbus-run-session -- sway `

I get following errors. I don't know if I am missing anything or is it even possible to run swaywm on a docker alpine image. Please assist me as I have been trying to remove these errors for days but no result.

00:00:00.018 [wlr] [render/wlr_renderer.c:322] drmGetDevices2 failed: No such file or directory
00:00:00.019 [wlr] [types/wlr_drm_lease_v1.c:705] No DRM backend supplied, failed to create wlr_drm_lease_v1_manager
2022-10-15 19:38:33 - [main.c:340]

**Comment by emersion** [comment]
Sorry, Docker is not supported.

**Comment by RajaMuneerBaigal** [comment]
I can run it though

**Comment by RajaMuneerBaigal** [comment]
I can see the sway screen but I get these above two errors. I don't know what I am missing
