### ISSUE TITLE
Allow specifying xkb include path

### ISSUE THREAD

**Issue by CyberShadow** [swaywm/sway#7229]
Heya,

I have some custom keyboard layouts which I'd like to use with sway. I have these described in `.xkb` files. On Xorg, I compile these to `.xkm` and then load them with `xkbcomp`.

To use custom symbol definitions (without modifying system directories), I run `xkbcomp` with `-I.`. But, I don't see an equivalent option to specify the xkb include path with sway, so sway fails to load the keymap:

```console
$ swaymsg 'input type:keyboard xkb_file "~/work/DvorakLayouts/layouts/xkb/layout-3.xkb"'
Error: Failed to compile keymap: Couldn't find file "symbols/my_ru" in include paths
```

An option equivalent to `xkbcomp`'s `-I` would allow this to work. Alternatively, a hack would be to implicitly add to the include search path the directory which contains the `.xkb` file.

Thanks!

**Comment by markstos** [comment]
According to [this page](https://unix.stackexchange.com/a/698044), you can add your  `symbols/my_ru` file to `$XDG_CONFIG_HOME/xkb/symbols`. If that works, consider submitting a patch to the `sway-input` docs to mention the tip there.

**Comment by RPigott** [comment]
Yeah that method should work. Peter Hutterer wrote a bit about custom xkb layouts on his blog, probably the best available source still.

Part [1](https://who-t.blogspot.com/2020/02/user-specific-xkb-configuration-part-1.html), [2](https://who-t.blogspot.com/2020/07/user-specific-xkb-configuration-part-2.html), [3](https://who-t.blogspot.com/2020/08/user-specific-xkb-configuration-part-3.html), [4](https://who-t.blogspot.com/2020/09/user-specific-xkb-configuration-putting.html)

**Comment by RPigott** [comment]
Correction, it requires a small change to work. Let's just support the default config paths here, rather than a new option.

**Comment by Ypnose** [comment]
Yes, when the binary has `cap_sys_nice`, I cannot use my custom keymap anymore (in `$XDG_CONFIG_HOME/xkb/symbols`). It was fine with `1.7` with this [configuration](https://github.com/Ypnose/dotfiles/blob/master/gui/swayconfig#L238). Now, I need to wait for new `libxkbcommon` release if I do not want to rollback ?
