### ISSUE TITLE
Reverse PRIME: render on Intel, send to Nvidia

### ISSUE THREAD

**Issue by yellowhat** [swaywm/sway#7241]
### Please fill out the following:
- **Sway Version:**
  - `sway version 1.7`

- **Description:**

Hi,
I have just got a Lenovo X1 Extreme Gen 4 laptop, it has an Intel iGPU and a dedicated Nvidia 3050Ti. I have installed Fedora 36.

Unfortunately seems that the external display outputs are directly connected to the Nvidia GPU, therefore if I disable the Nvidia GPU I can only use the laptop display, no external/attached one, with the Intel GPU.

The Intel GPU is fast enough for my usecase, therefore I would like to render on the iGPU and use the external GPU for external displays.

If I use the following:

```bash
if [ ! -z "$(udevadm info -a -n /dev/dri/card0 | grep i915)" ]; then
    intel="/dev/dri/card0"
    nvidia="/dev/dri/card1"
else
    intel="/dev/dri/card1"
    nvidia="/dev/dri/card0"
fi
export WLR_NO_HARDWARE_CURSORS=1
export WLR_DRM_DEVICES="${intel}:${nvidia}"
sway -d &>~/.cache/sway.log
```

Only the laptop screen work, no external output.

Am I missing something?

Thanks

- **Debug Log:**
[sway.log](https://github.com/swaywm/sway/files/9952181/sway.log)

**Comment by emersion** [comment]
```
00:00:00.026 [ERROR] [wlr] [EGL] command: eglInitialize, error: EGL_NOT_INITIALIZED (0x3001), message: "DRI2: failed to create screen"
libEGL warning: egl: failed to create dri2 screen
00:00:00.029 [ERROR] [wlr] [EGL] command: eglInitialize, error: EGL_NOT_INITIALIZED (0x3001), message: "DRI2: failed to create screen"
00:00:00.029 [ERROR] [wlr] [EGL] command: eglInitialize, error: EGL_NOT_INITIALIZED (0x3001), message: "eglInitialize"
```

Seems like we fail to create the GLES2 renderer for some reason…

**Comment by emersion** [comment]
> The Intel GPU is fast enough for my usecase, therefore I would like to render on the iGPU and use the external GPU for external displays.

FWIW this should be what wlroots does by default when `WLR_DRM_DEVICES` is unset.

**Comment by yellowhat** [comment]
Thanks for your reply.
If I just run `sway` (no `WLR_DRM_DEVICES`) only the laptop display works, external ones do not.

**Comment by emersion** [comment]
Can you try the latest commits of Sway and wlroots?

This sounds similar to https://github.com/swaywm/sway/issues/7203#issuecomment-1268290572.

**Comment by yellowhat** [comment]
I am having some difficulty in compiling the latest versions.
I have tried with this https://download.copr.fedorainfracloud.org/results/alebastr/sway-extras/fedora-36-x86_64/04995635-sway-git/, and got the same behavior.

**Comment by yellowhat** [comment]
I have just installed arch linux and `sway-git` (`sway version 1.8-dev-3e19836f (Nov 7 2022, branch 'master'`):
* `sway`: runs on the Intel gpu but no external monitors
* `WLR_DRM_DEVICES=/dev/dri/card1 sway`: runs on the Intel gpu but no external monitors
* `WLR_DRM_DEVICES=/dev/dri/card0 sway`: it errors immediately

```console
libEGL warning: egl: failed to create dri2 screen
00:00:00.018 [wlr] [EGL] command: eglInitialize, error: EGL_NOT_INITIALIZED (0x3001), message: "DRI2: failed to create screen"
libEGL warning: egl: failed to create dri2 screen
00:00:00.021 [wlr] [EGL] command: eglInitialize, error: EGL_NOT_INITIALIZED (0x3001), message: "DRI2: failed to create screen"
00:00:00.021 [wlr] [EGL] command: eglInitialize, error: EGL_NOT_INITIALIZED (0x3001), message: "eglInitialize"
00:00:00.021 [wlr] [render/egl.c:264] Failed to initialize EGL
00:00:00.021 [wlr] [render/egl.c:554] Failed to initialize EGL context
00:00:00.021 [wlr] [render/gles2/renderer.c:679] Could not initialize EGL
00:00:00.021 [wlr] [render/wlr_renderer.c:333] Could not initialize renderer
00:00:00.021 [sway/server.c:79] Failed to create renderer
```

**Comment by yellowhat** [comment]
Sure
[sway.log](https://github.com/swaywm/sway/files/9953408/sway.log)

**Comment by emersion** [comment]
Right, this is Ampere thus not supported by Mesa yet: https://nouveau.freedesktop.org/FeatureMatrix.html

> When I force to use the nvidia gpu, with WLR_DRM_DEVICES, it displays output only on external screens, it is pretty slow but it shows.

Probably via the Pixman renderer. There's no way to combine GLES2 for iGPU and Pixman for eGPU right now.

**Comment by yellowhat** [comment]
Hi,
Out of desperation I have installed Fedora 37-beta KDE.
Strangely out-of-the-box laptop + external monitors are working as expected and GPU accelerated.
Seems that it is using the Intel GPU to render (from `sudo intel_gpu_top`).

Could you reopen the issue?

Thanks

**Comment by yellowhat** [comment]
I have tried to install `sway` on the same system, played with `WLR_DRM_DEVICES`, but it still displays output only on external screens, it is pretty slow but it shows.
Therefore it is not something "magical" installed by the spin.

**Comment by bl4ckb0ne** [comment]
A more recent Fedora will not add nouveau support for Ampere out of thin air.

**Comment by yellowhat** [comment]
I know, my assumption is that KDE is using a specific configuration to achieve the render on Intel and display through nvidia.
Infact `sway` on Fedora 37 give me the same behaviour as the open post

**Comment by yellowhat** [comment]
I understand that. My question is: why KDE is able to render using nouveau? (I have no nvidia proprietary driver installed)

**Comment by emersion** [comment]
llvmpipe means it's using software rendering.

wlroots doesn't support llvmpipe at the moment, but the Pixman renderer should be better performance-wise. As noted above, Pixman can't be used for secondary GPUs yet.

**Comment by yellowhat** [comment]
Thanks for the explanation. Got too much excited by KDE 😢

**Comment by bl4ckb0ne** [comment]
Support for Ampere has begun not too long ago [1], you just have to be patient.

[1]: https://www.phoronix.com/news/Mesa-RTX-30-Ampere-OpenGL
