### ISSUE TITLE
focus floating window keeping it behind others

### ISSUE THREAD

**Issue by bugsbugsbux** [swaywm/sway#7243]
Please add a command to focus a floating window without bringing it to the foreground.

This is not a "real" feature request, as this functionality already exists, but does not have a command: when you have several floating windows and `focus_follow_mouse yes` in your config, you can move your mouse over the window (partly) behind the other and it gets focus while staying in the background.

This is useful as sometimes I want to arrange my windows in a certain overlapping way, but the only way to keep them this way, when changing focus, is to use the mouse...

**Comment by emersion** [comment]
Sorry, we're not accepting any new window management features anymore. See https://github.com/swaywm/sway/blob/master/CONTRIBUTING.md#scope-of-future-changes-to-sway
