### ISSUE TITLE
Java cannot put floating windows on non-focused monitors

### ISSUE THREAD

**Issue by matejdro** [swaywm/sway#7255]
Steps to reproduce:

1. Add `for_window [title="Floating Java Window"] floating enable` to your i3/sway config
2. Save this to `Main.java`:

```
import javax.swing.*;
import java.awt.*;

public class Main {
    public static void main(String[] args) {
        GraphicsDevice[] screens = GraphicsEnvironment.getLocalGraphicsEnvironment().getScreenDevices();
        for (GraphicsDevice screenDevice : screens) {
            GraphicsConfiguration configuration = screenDevice.getDefaultConfiguration();
            Rectangle bounds = configuration.getBounds();

            System.out.println("Monitor " + screenDevice.getIDstring() + ": " + bounds);

            JFrame frame = new JFrame();
            frame.setTitle("Floating Java Window");

            frame.setSize(200, 200);

            frame.setLocation(
                    (int) (bounds.x + (bounds.getWidth() - frame.getWidth()) / 2),
                    (int) (bounds.y + (bounds.getHeight() - frame.getHeight()) / 2)
            );
            System.out.println("Frame location: " + frame.getLocation());
            frame.setVisible(true);
        }
    }
}
```

3. Compile the program with `javac Main.java`
4. Run the program with `java Main`

Above program will create a window for every monitor and call `setLocation` function to set absolute position of every window to the center of each monitor. On i3, this works fine. However, on Sway, it seems window manager ignores absolute position given by the program and just puts all windows in the center of the currently focused monitor.

I know Java does not support Wayland natively, but supposedly this should work through XWayland?

Reproducible with the:

```
openjdk version "19.0.1" 2022-10-18
OpenJDK Runtime Environment (build 19.0.1+10)
OpenJDK 64-Bit Server VM (build 19.0.1+10, mixed mode)

sway version 1.7

i3 version 4.21.1 (2022-10-24) © 2009 Michael Stapelberg and contributors
```

**Comment by Xyene** [comment]
XWayland applications cannot position themselves arbitrarily. XWayland itself is a Wayland client, so has the regular Wayland client constraint of not being allowed to set top-level window positions.

That means `setLocation` is a no-op Wayland, and will remain a no-op even after Java gets proper Wayland support.

**Comment by matejdro** [comment]
Huh that's a bummer. Is there any plan to change this (maybe some way for user to give app explicit permission to do this, so there is no security issue)?

**Comment by Xyene** [comment]
Not that I'm aware of. If such a protocol were to exist in the future, it's possible wlroots would pick it up and Sway would gain support through it.

For Sway specifically as a one-off, you could hack something together through the Sway IPC to position the windows however you want, but that won't be portable to other compositors.

**Comment by matejdro** [comment]
Thanks for your explanation.
