### ISSUE TITLE
Popup Window styling differs from i3

### ISSUE THREAD

**Issue by bd-g** [swaywm/sway#7259]
## Expected (i3) Behavior

Popup windows by definition are not "first class" windows. i3 treats them properly by placing them in a non-instrusive, floating style instead of a full window. 

In the below picture, the microphone usage popup window is displayed in the top middle of the display. There is not a title bar.

![image](https://user-images.githubusercontent.com/49082060/201486201-8d4bde71-d56c-4fb2-8b2a-30d09c191da2.png)

## Actual (swaywm) Behavior

Popup windows are blown up as a full window and are intrusive.

![image](https://user-images.githubusercontent.com/49082060/201486247-0609c360-d517-484d-9f77-b0bb803d26c2.png)

 I can manually switch it to a floating window, but then there is still a title bar on the window.

![image](https://user-images.githubusercontent.com/49082060/201486514-955fb282-8ccb-4b6b-9ad5-f842a02a4f72.png)

## Other Examples

Popups for Zoom application - audio settings, chat boxes, and others should appear as popups floating over the main zoom screen, but instead are blown up as individual windows.

**Comment by emersion** [comment]
Wayland has no concept of standalone popup window.

**Comment by bd-g** [comment]
> Wayland has no concept of standalone popup window.

[This link](https://wayland-book.com/xdg-shell-in-depth/popups.html) says otherwise. Am I misunderstanding?

**Comment by emersion** [comment]
xdg-popups are unrelated, and used for e.g. right-click menus.

**Comment by bd-g** [comment]
Thanks for explaining that to me.

**Comment by xplshn** [comment]
So. What's the situation now? No progress in 2 years? Why is this marked as closed if the issue hasn't been resolved?
