### ISSUE TITLE
Sway & 'libwlroots.so.12' path issues

### ISSUE THREAD

**Issue by frkli1965** [swaywm/sway#7261]
Hi,

Within the last couple of days, 'Sway' (Ubuntu 22.04.1 kernel v6.1rc4) now searches '/usr/lib/x86_64-linux-gnu' for 'libwlroots.so.12' when logging into 'Sway' rather than '/usr/local/lib/x86_64-linux-gnu' where it has always looked previously.

If 'libwlroots.so.12' does not happen to reside in '/usr/lib/x86_64-linux-gnu' then 'Sway' steadfastly refuses to load, which as I've stated above, has never been a show-stopper up until now.

To rectify the situation I experimented with two approaches on separate PCs:-

1) Configure the build with 'meson setup build --prefix=/usr' in place of 'meson setup build
   --prefix=/usr/local' having completely uninstalled' Sway', 'wlroots' and 'seatd' first.
       
2) Stick with 'meson setup build --prefix=/usr/local' and then merely move over 'libwlroots.so*' to
    '/usr/lib/x86_64-linux-gnu' as follows within my build script once the compilation has completed successfully:-
       
    'sudo mv /usr/local/lib/x86_64-linux-gnu/libwlroots.so* /usr/lib/x86_64-linux-gnu'
       
Both approaches appear to work fine however the first method results in 'swaybg' having to be re-installed i.e. 'sudo apt --reinstall install swaybg' otherwise the background (wallpaper) will not load on start up.

Apologies if these issues are more to do with 'wlroots' rather than 'Sway' in advance...

Kind regards,

**Comment by bl4ckb0ne** [comment]
This is an issue with your distro/packaging, we can't do much about how your software is installed.

**Comment by frkli1965** [comment]
OK, no worries, as I said there are simple workarounds.

Just seemed weird that for months on end there were no issues, not even the day before, then all of a sudden Sway decides to look in a totally different place just for one lib.

Anyway, thought I'd mention it just to make sure that it wasn't a widespread problem. Interesting thing is, it's now happened to me on three different PCs that have all been running the very latest Sway builds with no issues whatsoever for months on end.

All the best,
