### ISSUE TITLE
`.bash_logout` does not execute after sway exit

### ISSUE THREAD

**Issue by asklow** [swaywm/sway#7267]
### Description
As for i3/x11, I always do `startx && exit` in my `.bash_profile` so that `.bash_logout` is executed too.
On sway, I couldn't find a way to achieve it. I've tried `exec sway && exit`, but `.bash_logout` doesn't execute.
Exiting the session is the command on both, `i3-msg exit` and `swaymsg exit`
- **Sway Version:** `4.21.1 (2022-10-28)`

**Comment by emersion** [comment]
This is not a Sway bug. This is a question about your system's configuration. Sorry, we don't take these in the issue tracker.
