### ISSUE TITLE
cannot copy and paste between two programs

### ISSUE THREAD

**Issue by notwidow** [swaywm/sway#7274]
# ISSUE
Hi, I cannot copy and paste between firefox and alacritty. When i copy text from firefox then i can only paste it in firefox and not outside of firefox.
# INFO
> OS: Arch Linux
Terminal: Alacritty v 0.11.0 (8dbaa0bb)
WM: Sway v 1.7
wl-clipboard is installed

**Comment by emersion** [comment]
Your bug report is missing debug logs. Please add a link to the full debug log file.

    sway -d >sway.log 2>&1

**Comment by notwidow** [comment]
Since i cannot copy and paste so uploaded the log file.

[sway.log](https://github.com/swaywm/sway/files/10055504/sway.log)

**Comment by notwidow** [comment]
> Your bug report is missing debug logs. Please add a link to the full debug log file.
> 
> ```
> sway -d >sway.log 2>&1
> ```

also:
when i start sway in tty by sway command then upon exiting sway . I cannot write any command in tty i have to press enter a few times and then can write it in tty. Please have a look at it.
> shell is zsh 5.9

**Comment by notwidow** [comment]
# Update
 I forgot i have enabled xwayland layer. upon disabling xwayland the clipboard now works well.

**Comment by bl4ckb0ne** [comment]
> [ERROR] [wlr] [xwayland/server.c:443] Cannot find Xwayland binary "/usr/bin/Xwayland"

Could it be that you have no xwayland and firefox isnt started with the wayland backend explicitly, and somehow auto-detection messes up the copy paste.

**Comment by emersion** [comment]
If Xwayland cannot be found, we don't set `DISPLAY`, so X11 applications should fail to start. It should have the same effect as disabling Xwayland in the config.
