### ISSUE TITLE
Mouse disappears when launching Firefox in Wayland mode

### ISSUE THREAD

**Issue by HenrikDK2** [swaywm/sway#7276]
- **Sway Version:** 1.7-10
- **Libinput Version:** 1.22.0-1
- **Wlroots Version:** 0.15.1-6
-  **Distro:** Arch Linux

- **Debug Log:** https://pastebin.com/1UZxHrEk
- **Debug log with default configuration:** https://pastebin.com/uVYQYH82

- **Description:**
  - Launch Firefox in Wayland mode (It doesn't occur on XWayland)
  - Go to YouTube, and play any video
  - Once the mouse hides itself, it won't reappear in the Firefox window.
  
  The issue occurs on both Firefox Developer Edition (108.0b5-1) and Firefox (107.0-1)
  I have a video showcasing the issue (https://www.youtube.com/watch?v=toeJhCGAAtc)

**Comment by evgfilim1** [comment]
Hi. I'm having the same issue. The mouse cursor stays as it was in the previous window and doesn't change when hovering over text fields and links. Other apps work fine.
Have you tried downgrading Firefox and/or Sway to check which versions are affected?

**Comment by anriha** [comment]
Hi, I was having the same issue after booting up into Sway (I normally use DWL) and it persisted even after switching back. To me it seems that Sway does something with cursor settings. It was fixed for me after I set my cursor-theme again with
`gsettings set org.gnome.desktop.interface cursor-theme Adwaita`

**Comment by evgfilim1** [comment]
After some "investigation" it seems like it's a bug in gtk as the bug is present in any gtk app (Firefox is one of them)

**Comment by HenrikDK2** [comment]
> After some investigation it seems like it's a bug in GTK as the bug is present in any GTK app (Firefox is one of them). ~I'll look further and update the comment.~
> 
> UPD. Yes, I was right.
> 
>     * https://gitlab.gnome.org/GNOME/gtk/-/issues/5365
> 
>     * https://bugs.archlinux.org/task/76651

The issue seems to be with GTK, and the latest version solved the issue on my end.

I will close this issue.

**Comment by Akimitsu333** [comment]
I was having the same issue in Wayland without Xwayland.I solved it by installing `xdg-desktop-portal-gtk` and then setting `gsettings set org.gnome.desktop.interface cursor-theme Adwaita`.
