### ISSUE TITLE
1.8-rc1 doesn't use monitors attached to a 2º GPU when WLR_RENDERER=vulkan

### ISSUE THREAD

**Issue by Zeioth** [swaywm/sway#7282]
This is probably not a bug, but work in progress, but I write it here just in case. It's the only thing preventing me to enable the flag permanently.

Please confirm me if you need the logs to debug this one and I will attach them.

**UPDATE:**

### Please fill out the following:

- **Packages:** wlroots-git+sway-git from AUR
- **Sway Version:** way version 1.9-dev-81518e29 (Nov 27 2022, branch 'master')

- **Debug Log:**
  - Command runned in TTY: `sway -d 2> ~/sway.log`
  - [Link to the log on pastebin](https://pastebin.com/raw/jQbhW9Vr)

- **Configuration File (I'm attaching /env/environment just in case, but should be anything relevant here, or in my sway's config):**

```
# Use AMD6700XT as the main GPU
WLR_DRM_DEVICES=/dev/dri/card1:/dev/dri/card0

# Run sway using the normal mesa RADV drivers.
AMD_VULKAN_ICD=RADV

# Enable the vulkan renderer
WLR_RENDERER=vulkan
```

- **Stack Trace:**
  - There is no crash, so, so stack trace needed.

- **Description:**
  - Have an sway config that works correctly, with at least 1 monitor attached to each GPU. 
  - Set WLR_RENDERER=vulkan in /etc/environment
  - The monitors attached to the 2º GPU won't work when using the vulkan renderer.

## How it looks

![20221127_094545.jpg](https://user-images.githubusercontent.com/3357792/204127200-4ba24180-3bdb-4740-8c0a-8689f4cdab20.jpg)

**Comment by emersion** [comment]
> you need the logs

Yes

**Comment by Zeioth** [comment]
All info uploaded. As usual please let me know if there's anything else you need 😊

**Comment by emersion** [comment]
```
00:00:00.117 [ERROR] [wlr] [render/vulkan/vulkan.c:429] vulkan: required device extension VK_EXT_image_drm_format_modifier not found
```

Your second GPU doesn't support an ext required by the wlroots Vulkan renderer.

**Comment by Zeioth** [comment]
Damn things move fast. 2º GPU is a RX 580. I will try again in the future with a newer GPU thanks.

**Comment by emersion** [comment]
Right, RX 580 is GFX8. The Vulkan renderer requires DRM format modifier support, which amdgpu only has on GFX9+.

**Comment by Zeioth** [comment]
I don't know if it would be technically possible, but maybe it would be a good idea to fallback to opengl rendering if vulkan rendering fail. If you are thinking in defaulting vulkan rendering in the future.

**Comment by emersion** [comment]
Yes, that's the plan.
