### ISSUE TITLE
9f4229827f43cc26cf699a92e847834fed61e950 in 1.8 causes a failure to build in Debian Stable

### ISSUE THREAD

**Issue by n3rdopolis** [swaywm/sway#7284]
Not sure if it's a problem with the linker in Debian... I compile a number of things under /opt, but librt.so is NOT one of them

I am building it with `meson --buildtype=plain --prefix=/opt --libdir=/opt/lib/$(dpkg-architecture -qDEB_HOST_MULTIARCH) build`

I don't have any `LD_FLAGS` and from my research `LD_LIBRARY_PATH` and `ld.conf` does NOT impact the search order of the linker...

I get this
```
/usr/bin/ld: swaybg.p/pool-buffer.c.o: in function `create_buffer':
pool-buffer.c:(.text+0x88): undefined reference to `shm_open'
/usr/bin/ld: pool-buffer.c:(.text+0x96): undefined reference to `shm_unlink'
collect2: error: ld returned 1 exit status
```

from this command
```
cc  -o swaybg swaybg.p/background-image.c.o swaybg.p/cairo.c.o swaybg.p/log.c.o swaybg.p/main.c.o swaybg.p/pool-buffer.c.o -Wl,--as-needed -Wl,--no-undefined -Os -Wno-error -Wl,--start-group libclient_protos.a /opt/lib/x86_64-linux-gnu/libcairo.so /opt/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so /opt/lib/x86_64-linux-gnu/libgobject-2.0.so /opt/lib/x86_64-linux-gnu/libglib-2.0.so /opt/lib/x86_64-linux-gnu/libwayland-client.so -Wl,--end-group
```

adding `-lrt` at the end seems to get it too not fail

**Comment by emersion** [comment]
Yeah we need to add `rt` to the list of deps.

**Comment by n3rdopolis** [comment]
OK, I think I get similar issues with swaybg and swaylock. I was worried that it was something with my scripts or my Debian chroot
