### ISSUE TITLE
layer-shell: Infinite of `configure` events when setting surface size

### ISSUE THREAD

**Issue by WhyNotHugo** [swaywm/sway#7302]
### Please fill out the following:
**Sway Version:**

`sway version 1.8-dev-85005b52 (Nov 13 2022, branch 'master')`

 **Configuration File:**

Configuration has no impact on this.

 **Description:**

When a client is relying on the compositor to set the surface size, it'll await a [`zwlr_layer_surface_v1::configure`](https://wayland.app/protocols/wlr-layer-shell-unstable-v1#zwlr_layer_surface_v1:event:configure) event, and then call [`zwlr_layer_surface_v1::set_size`](https://wayland.app/protocols/wlr-layer-shell-unstable-v1#zwlr_layer_surface_v1:request:set_size) with the correct size. sway will then send _another_ `configure` event with the same `width` and `height`.

This results in clients very easily ending up in an infinite loop setting their size to the same value over and over. A simple check to compare the `configure` event with the previous one can work around this, but it doesn't seem correct that the compositor would continuously send `configure` events with no changes.

If `set_size` is called with values equal to those provided by `configure`, the compositor should not send another meaningless `configure` event.

**Comment by bl4ckb0ne** [comment]
Cant the client check that the size is equal to the one it sets and no-op the configure?

**Comment by WhyNotHugo** [comment]
Yes, keeping the details of the previous `configure` event and comparing them is the workaround I'm using now.

**Comment by bl4ckb0ne** [comment]
Alright then, I'm closing the issue.

**Comment by WhyNotHugo** [comment]
>        The client is free to dismiss all but the last configure event it
>        received.

In this case, my client is ignoring the last, which is contrary to what the spec says. If I do not ignore the last, then I end up in an infinite loop with the compositor.

While the workaround is trivial, it would be ideal if every single client using this protocol there didn't need to implement it -- developers may well be ignorant of this quirk.

I mentioned this on IRC a few weeks ago and it was suggested that this should be addressed on the compositor side, hence the issue here.

**Comment by bl4ckb0ne** [comment]
That would require modifying the layer shell spec. If the client sets a size, the compositor sends a configure event 
to answer the size change on its side and that the client can change its size. I get that it's silly, but thats what the protocol dictates.
