### ISSUE TITLE
Disabling sound bar results in no audio

### ISSUE THREAD

**Issue by gytis-ivaskevicius** [swaywm/sway#7306]
- **Description:**
I disabled the soundbar which is connected via HDMI and it resulted in no audio
If I keep it enabled - I got an invisible monitor which is annoying

- **Scenario:**
**Given:**
Sway version 1.7
Config defines `output HDMI-A-1 disable`
**When:** 
Playing audio
**Then:** 
The audio does not work

**Comment by emersion** [comment]
Sway can't do anything about this, sorry.

**Comment by chrissygem42** [comment]
> Sway can't do anything about this, sorry.

[perhaps try reset re use and recycle the memory stack and change ur signal and reset your privacy setting to 0 maybe ?https://youtu.be/ktm2xg4KOPk)
