### ISSUE TITLE
Segfault when connecting the same docking station for a second time

### ISSUE THREAD

**Issue by nkoester** [swaywm/sway#7307]
### Please fill out the following:
**Sway Version:**
`sway version 1.7`

**Debug Log:**
[log](https://gist.github.com/nkoester/f6cd219d135dec441599fded14219da4)

**Configuration File:**
default config used.

**Stack Trace:**
[bt full](https://gist.github.com/nkoester/172c1d144e4af2ef087d83b1197f4525)

**Description:**

Either step 1a. and 1b. lead to the same result. The docking station (thunderbolt 3) has 3 additional displays connected: two via HDMI, one via DP.

1a. start sway with no docking station connected & connect docking station
1b. (alternative) start sway already connected to docking station
2. disconnect docking station
3.  (optional) wait any time
4. re-connect same docking station 
   (screen goes to black twice when extending the display)
5. segfault

Some other observations:
- I also tried the same without the DP screen connected, similar results: sway crashes.
- Segfault does not happen when I disconnect all HDMI screens (so with only the DP screen connected to the docking station). Re-adding them one by one does not crash sway. But disconnecting and reconnecting the docking station with all screes connected will crash sway afterwards.
- Segfault does not happen when I have no screens connected to the docking station. I can re-plug as often as I want without issues in this configuration.

**Comment by nkoester** [comment]
I re-ran tests with

```
$ sway --version
sway version 1.9-dev-6b3245ac (Dec  3 2022, branch 'master'
```

Indeed sway does not crash. But my screens also do not turn back on after unplug, wait, and replug.

**Comment by emersion** [comment]
Can you try with the latest Sway and wlroots commits?
