### ISSUE TITLE
Crash when selecting text from chrome

### ISSUE THREAD

**Issue by MoetaYuko** [swaywm/sway#7308]
- **Sway Version:**
  - sway version 1.9-dev-6b3245ac (Dec  2 2022, branch 'master')
  - wlroot HEAD commit: https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/79aea5883454e4ef92df428a8874ca1e02392719

- **Debug Log:**
https://fars.ee/_f4n

- **Stack Trace:**
https://fars.ee/4J_F

- **Core dump:**
https://fars.ee/md8q.zst

- **Description:**
Sway accidentally crashed when I was selecting some texts from chrome, which ran with the native Wayland backend. However, the issue seldom occurs so I can't find a reliable way to reproduce it.

**Comment by yofsh** [comment]
Faced the same issue for all chromium based browsers

Steps to reproduce:
1. Set sway scale to any other then 1 e.g. `output $laptop scale 1.3`
2. Run chromium  based browser with `google-chrome-stable --enable-logging --v=1 --ozone-platform-hint=auto`
3. Load any page, e.g. https://google.com.
4. Select any text and try to drag.
5. Browser crashes and following message can be found in the log: `[113131:113131:0128/141825.249679:ERROR:wayland_event_watcher.cc(38)] libwayland: wl_surface@33: error 2: Buffer size (83x54) is not divisible by scale (2)`

Google Chrome: `Version 109.0.5414.119 (Official Build) (64-bit)`
Sway: `sway version 1.8`

As a temporary workaround is to disable drag and drop for all websites with Tampermonkey extension, keep in mind that could break dnd for some JS apps, though all working fine for me so far:
```
// ==UserScript==
// @name         Disable drag and drop on all websites
// @version      0.1
// @match        *://*/*
// @grant        none
// ==/UserScript==

document.addEventListener("dragstart", e => e.preventDefault());
```

**Comment by emersion** [comment]
This is a Chrome bug. Someone already opened a bug report iirc.
