### ISSUE TITLE
XWayland popups are poorly sized

### ISSUE THREAD

**Issue by tasn** [swaywm/sway#731]
Hey,

XWayland popups are poorly sized, I tested on firefox. For example, try going to the following url to trigger http auth: http://www.httpwatch.com/httpgallery/authentication/authenticatedimage/default.aspx?0.7424363763312372
The popup window for the password is very poorly sized (and I also can't resize it from the keybindings, but I guess that's a different matter).
![bla](https://cloud.githubusercontent.com/assets/108670/16517450/5fd29ad2-3f75-11e6-9c8c-d7b3dc3a0e23.png)

Thanks.

**Comment by tasn** [comment]
Or the uMatrix (firefox extension) window that is poorly sized, accepts input in areas in doesn't render to and etc...

**Comment by onny** [comment]
This bug is still present in:

- wlc-git (from today)
- sway-git (from today)
- wayland 1.12.0
- wayland-protocols 1.7

**Comment by asymmetric** [comment]
Still an issue on sway 0.15.0, especially with Firefox's uMatrix, pop-up where click aren't detected properly.

**Comment by asymmetric** [comment]
Has this been fixed as part of the hackathon? :)

**Comment by SirCmpwn** [comment]
Yep.

**Comment by emersion** [comment]
Can reproduce again in 1.0.

**Comment by sqrtroot** [comment]
Any status update?

**Comment by emersion** [comment]
Status update: please send patches to fix this.

**Comment by sqrtroot** [comment]
Any insight as to where this problem stems from, a place to start making a patch to fix this?

**Comment by RyanDwyer** [comment]
I poked around in `xwayland.c`'s `handle_map`. In my case the size that it's committing with is 299x186, which is too small. It seems to be a problem with Firefox or xwayland.

**Comment by emersion** [comment]
GNOME doesn't have this issue so its unlikely. There's a preferred size alongside the min and max size for xwayland views, maybe there's something to do about it.

**Comment by SirCmpwn** [comment]
I don't think this is us

**Comment by emersion** [comment]
Well, I do think this is us.

**Comment by SirCmpwn** [comment]
oh.

**Comment by ixru** [comment]
Firefox submits two configure requests for any surface it intends to have mapped I think.
The first one requests the correct geometry, but the second passes 1x1 causing it to shrink.
https://github.com/swaywm/wlroots/blob/master/xwayland/xwm.c#L804
This handles the event, but always handles it as an attempt to set the geometry even though that might not be the case. 
https://tronche.com/gui/x/xlib/events/structure-control/configure.html
I think these are the other actions it can make. 
https://tronche.com/gui/x/xlib/window/configure.html#XWindowChanges
If I print value_mask for each event I get 12(width and height) for the first one and 64(StackMode) for the second. Perhaps it is trying to raise the window.
