### ISSUE TITLE
Sway crashing after swaylock exits

### ISSUE THREAD

**Issue by pmengelbert** [swaywm/sway#7310]
### Please fill out the following:
- **Sway Version:**
```
$ swaymsg -t get_version
sway version 1.7
```

- **Debug Log:**
  - Run `sway -d 2> ~/sway.log` from a TTY and upload it to a pastebin, such as gist.github.com.
    - [gist here](https://gist.github.com/pmengelbert/7d628b94bab89bb812ae55abc10a6cc0)

- **Configuration File:**
  - This tends to happen when sway is running for several days. I don't want to run on a minimal configuration for that long
  - Here is my config: [gist](https://gist.github.com/pmengelbert/5631ea70eebd92045162f871fa658694)

- **Stack Trace:**
  - [coredump backtrace gist](https://gist.github.com/pmengelbert/00eb99b49ff1f00ba59e1769e964cf87)

- **Description:**
  - Use sway as usual, leaving it running for several days
  - wait for swaylock to come on via swayidle
  - unlock the computer
  - Eventually, sway will crash

**Comment by bl4ckb0ne** [comment]
Can you reproduce with the 1.8 rc?

**Comment by pmengelbert** [comment]
I'll try it with the 1.8 rc later this week

**Comment by emersion** [comment]
Please re-open if you can repro with Sway's latest commit.

**Comment by pmengelbert** [comment]
Been running 1.8 and haven't had a problem since. Working great!
