### ISSUE TITLE
"output right" doesn't follow i3's behaviour

### ISSUE THREAD

**Issue by regnat** [swaywm/sway#733]
On i3, using "focus output right" while on the outer right monitor focuses the outer left monitor (and the same for "output {left,above,below}" of course).
On sway it does nothing, and the ipc returns (when trying `swaymsg focus right` on the cli) :

``` json
{ "success": false, "input": "focus output", "error": "Can't find output with name\/at direction 'right' @ (2240,885)" }
```

EDIT: It may be not clear on the message, but of course, this isn't specific to the "focus" command : others commands like "move container to" or "move workspace to" follow the same behaviour.

**Comment by acrisci** [comment]
I can confirm this.
