### ISSUE TITLE
EGL_BAD_ALLOC: Failed to allocate device list.

### ISSUE THREAD

**Issue by KaiserBh** [swaywm/sway#7335]
- **Sway Version**
   - 1.9-dev-1ade0ce7

- **Debug Log:**
  - http://sprunge.us/rNuTJj

- **Configuration File:**
  - http://sprunge.us/OQtqZn

- **Stack Trace:**
  - This is only needed if sway crashes.
  - If you use systemd, you should be able to open the coredump of the most recent crash with gdb with
    `coredumpctl gdb sway` and then `bt full` to obtain the stack trace.
  - If the lines mentioning sway or wlroots have `??` for the location, your binaries were built without debug symbols. Please compile both sway and wlroots from source and try to reproduce.

- **Description:**
  - So I didn't know sway didn't support nvidia proprietary drivers and installed it, alas there was a lot of issues with it and I wanted to go back to Nouveau so I proceed to uninstall nvidia Proprietary drivers and made sure to follow what arch wiki said by making sure there wasn't any blacklist for nouveau and removed nomodset from kernel parameters and now nouveau is loaded back but I am getting "EGL_Bad_ALLOC error: failed to allocate device list." All I want is just go back to open source drivers and get it back up and working.

**Comment by bl4ckb0ne** [comment]
> 00:00:00.004 [INFO] [wlr] [backend/drm/backend.c:186] Initializing DRM backend for /dev/dri/card0 (nouveau)

You're using Nouveau

> nvc0_screen_create:1093 - Base screen init failed: -19

That's a driver issue, your card is not supported (Ampere or higher)
