### ISSUE TITLE
Mouse cursor too larger when scaling enabled

### ISSUE THREAD

**Issue by omgold** [swaywm/sway#7344]
### Please fill out the following:
- **Sway Version:**
1.7

- **Configuration File:**
Default but with scale changed to 3

`output * scale 3`

- **Description:**

With scale set like this, some applications show a huge mouse cursor (waybar, firefox, emacs-pgtk...).

Emacs provides a message on the console about what is going on. Apparently it is related to gdk:

`(emacs:1033266): Gdk-WARNING **: 08:52:09.642: ../gtk/gdk/wayland/gdkcursor-wayland.c:242 cursor image size (64x64) not an integermultiple of scale (3)`

Version of gtk3 is 3.24.36. It seems something has changed there recently. It works correctly with version 3.24.35.

**Comment by maxnoe** [comment]
Also in 1.8

**Comment by omgold** [comment]
`ìmv` (the image viewer) doesn't start up at all, now, only producing this message:

`wl_surface@10: error 2: Buffer size (1280x720) is not divisible by scale (3)`

It doesn't seem to use gdk, though, just pango/cairo.

**Comment by emersion** [comment]
@omgold, please report this as a bug to imv.

**Comment by omgold** [comment]
Seem that already happened:

https://todo.sr.ht/~exec64/imv/20

**Comment by maxnoe** [comment]
Connected? https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/4762

**Comment by emersion** [comment]
This is a GTK bug AFAIK.

**Comment by hacker1024** [comment]
> This is a GTK bug AFAIK.

This issue also occurs on KDE with 2.5x scaling, so it's very likely not a Sway or wlroots issue at least.
