### ISSUE TITLE
Reproducible sway freeze when merging tabs from different windows in firefox/xwayland

### ISSUE THREAD

**Issue by rsidd120** [swaywm/sway#7345]
- **Sway Version:**
sway version 1.8-dev-5c239eaa (Dec 31 2022, branch 'HEAD')

- **Debug Log:**  
https://gist.github.com/rsidd120/ddf368c37a54c57b97f8c1d982fc161f

- **Configuration File:**
It is reproducible with default config, but here is my config. 
https://gist.github.com/rsidd120/71dea70ab0039c174710db54659734fd

- **Stack Trace:**
Not applicable

- **Description:**
Open firefox in xwayland mode. Create two windows on the same workspace. Try to merge them by dragging one tab onto the other window (drag until a blue line appears on the tab bar, then release the mouse button).  Sway instantly freezes the system and a hard reboot is the only solution. This doesn't happen with sway/firefox/wayland.  But is 100% reproducible with sway/firefox/xwayland [edit: clarified last two sentences].

**Comment by bl4ckb0ne** [comment]
> 00:03:01.705 [ERROR] [wlr] [xwayland/xwm.c:1526] xcb error: op 2:0, code 3, sequence 1135, value 106

 I don't know if it's a wlroots or a firefox issue tbh.

**Comment by rsidd120** [comment]
> > 00:03:01.705 [ERROR] [wlr] [xwayland/xwm.c:1526] xcb error: op 2:0, code 3, sequence 1135, value 106
> 
> I don't know if it's a wlroots or a firefox issue tbh.

I checked that it doesn't happen with firefox/xwayland under gnome/wayland (same laptop).  But it continues to happen on sway after a firefox update (to 108.0.2). 

Also, a firefox issue could crash firefox but I don't think it should freeze the computer. 

Let me know if I can give further information, or should I file the bug in wlroots.

**Comment by bl4ckb0ne** [comment]
Should be fixed in sway/wlroots master, could you try to reproduce it please.

**Comment by rsidd120** [comment]
It is fixed, thank you. 

I faced another issue, a sway crash while doing frequent copy-paste in gimp (xwayland, again). It is hopefully fixed by the same commit so am not reporting it yet.
