### ISSUE TITLE
upgrading sway on arch linux today broke everything

### ISSUE THREAD

**Issue by r3k2** [swaywm/sway#7353]
Writing this from my phone, my PC and Laptop are borked both running sway/wlroots for years, doing upgrades with no fuzz, until today, seems today release broke my both systems for what I can read now on screen:
Failed to create //.cache shader cache Permission Denied -- Disabling  (not sure if this is related)
then a bit after:
[wayland-client error] Attented to dispatch unknown opcode 0 for wl_shm, aborting
[common/ipc-client.c:87] Unable to recieve IPC response

laptop is Intel/lenovo
PC is AMD/Radeon

**Comment by emersion** [comment]
This is not helpful. Read the issue template and provide the requested information.

**Comment by r3k2** [comment]
I wish I could and I will be happy as soon I can get into any of my PC's im on my phone :(

**Comment by sweenu** [comment]
Go to another tty then downgrade sway (https://wiki.archlinux.org/title/downgrading_packages). Then you should probably build sway 1.8 and run it manually from sway 1.7 to make your tests before upgrading it again.

**Comment by r3k2** [comment]
update: in the case of my laptop it was wlgreet, booting from a external usb with arch and removing wlgreet and leeting the default greetd allowed me to enter the system finally, on my PC so far looks like a different issue but will double check as soon I finish with my laptop since I need it for work

**Comment by r3k2** [comment]
> Go to another tty then downgrade sway (https://wiki.archlinux.org/title/downgrading_packages). Then you should probably build sway 1.8 and run it manually from sway 1.7 to make your tests before upgrading it again.

dont you think I already try to change console before even the pain to login into github etc from my phone? :) ;) I ended up having to usb boot and mount my luks partitions to troubleshoot

**Comment by r3k2** [comment]
ok I can confirm now it was wlgreet on both, is fixed now I moved it temp to tuigreet
I am finally in my keyboards :)
