### ISSUE TITLE
Support keyboard layout udev rules

### ISSUE THREAD

**Issue by JohnGebbie** [swaywm/sway#7354]
Hello, I maintain [dotool](https://sr.ht/~geb/dotool) which is a tool for simulating keyboard/mouse using uinput. The virtual keyboard needs to have a US layout but, unlike X, sway doesn't seem to support keyboard layout udev rules like this:

    ACTION=="add", ATTRS{name}=="dotool keyboard", ENV{XKBLAYOUT}="us"

so sway users with a non-us keyboard layout have to set the virtual keyboard's layout in their user configs.

I think it would be good to support these udev rules but I'd be interested in any other solutions.

**Comment by JohnGebbie** [comment]
Actually, it doesn't need to be udev rules, just a system wide way to set the keyboard layout. X has the `/usr/share/X11/xorg.conf.d` directory.

**Comment by emersion** [comment]
Sway has `@sysconfdir@/sway/config.d/*`.

**Comment by JohnGebbie** [comment]
Ah thank you! I see `/etc/sway/config` has `include /etc/sway/config.d/*` at the bottom.

Installing this to `/etc/sway/config.d/dotool` works:

    input "18193:2069:dotool_keyboard" xkb_layout "us"

but I'm unsure how consistent the identifier will be? and I couldn't work out how to use the input's name instead. All instances seem to have the same identifier on both my machines, which is promising.
