### ISSUE TITLE
Output gets stuck after changing TTY

### ISSUE THREAD

**Issue by haselwarter** [swaywm/sway#7356]
I'm using sway version 1.9-dev-88c17ece3 (Jan  4 2023, branch 'master') and wlroots-git 0.17.0.r6057.e0b2bf2a-1 on Arch, kernel 6.1.2-arch1-1. Hardware is a Thinkpad x1 yoga gen 6 laptop.

- log in on tty1 with user1, start sway
- log in on tty2 with user2, start sway
- switching between tty1 and tty2 now works as expected
- log out and back in on tty2, starting sway again
- fiddle around (unfortunately this seems necessary to reproduce the bug. idk if it's about timing or something else)
- switching back to tty1 now results in either the external monitor, or more rarely the internal monitor, getting stuck displaying the contents from tty2.
- un- and re-plugging the monitor causes it to be usable on tty1 again, but switching to tty2 and back after replugging will recreate the issue.

I'm attaching two logs of the issue. The first one is from a patched version of sway (very minor 4 line patch changing fullscreen behaviour, should be completely orthogonal), the second is from sway master.
[dmesg.log.gz](https://github.com/swaywm/sway/files/10353814/dmesg.log.gz)
[sway-debug.log.gz](https://github.com/swaywm/sway/files/10353815/sway-debug.log.gz)
[dmesg-patched.log.gz](https://github.com/swaywm/sway/files/10353816/dmesg-patched.log.gz)
[sway-patched-debug.log.gz](https://github.com/swaywm/sway/files/10353817/sway-patched-debug.log.gz)

**Comment by unusualpepe** [comment]
I have the same issue on sway 1.8 running on Arch.

No need to open sway twice on different TTYs. Just switching to tty2 (with or without having logged in) and going back to the sway tty makes the external monitor be stuck on tty2.

**Comment by tezoi** [comment]
i have the same on sway 1.8 on Gentoo
It used to happen on both screen, and i was able to recover with `swaymsg output DP-1 disable;swaymsg output DP-1 enable` but now it's only on the external screen and i can't recover from it
The external screen is stuck with a static "screenshot" of the tty at the time of the switch to sway

**Comment by haselwarter** [comment]
@unusualpepe @tezoi It might help getting the bug fixed if you could upload a debug log following the instructions at https://gitlab.freedesktop.org/wlroots/wlroots/-/wikis/DRM-Debugging

**Comment by tezoi** [comment]
I finally catched the bug, it's kind of random but eventually happens.. I trimed the kernel log but can provide earlier data if necessary
The bug happened around 19:07, after unlocking the computer from physlock. some i915 related failure is visible in the log

Now the external screen will mirror whatever happens in any TTY at the moment i switch back to Sway

Unfortunately sway didn't provide debug info, but i may install from git if it can help

[sway.log.gz](https://github.com/swaywm/sway/files/10405479/sway.log.gz)
[hostdata.txt.gz](https://github.com/swaywm/sway/files/10405480/hostdata.txt.gz)
[kernel_drmdebug.txt.gz](https://github.com/swaywm/sway/files/10405481/kernel_drmdebug.txt.gz)

**Comment by emersion** [comment]
Sounds like it's caused by:

```
[  453.325970] i915 0000:00:02.0: [drm:drm_atomic_helper_check_modeset] [CRTC:167:pipe B] enabled/connectors mismatch
[  453.325980] i915 0000:00:02.0: [drm:intel_crtc_state_dump [i915]] [CRTC:167:pipe B] enable: yes [failed]
```

Also reported by https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3342

**Comment by unusualpepe** [comment]
Here are my log files. After enabling the log, I switched to sway, plugged my monitor (sway appeared just fine on both), went back to a tty, and back to sway (the monitor image got stuck). Then back to a tty to stop the logging.

[dmesg.log.tar.gz](https://github.com/swaywm/sway/files/10418187/dmesg.log.tar.gz)
[sway.log.tar.gz](https://github.com/swaywm/sway/files/10418188/sway.log.tar.gz)

**Comment by emersion** [comment]
Can you try this patch?

https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3967

**Comment by oddfellow** [comment]
Maybe related: #7006
