### ISSUE TITLE
Dropping a file on Firefox crashes FF

### ISSUE THREAD

**Issue by the8472** [swaywm/sway#7357]
**Sway Version:**
sway version 1.8 (arch package version 1:1.8-3)

**Debug Log:**
https://gist.github.com/44c3b6cd894b807d0d84d1b6a9143f20

**Configuration File:**
I have used the default configuration file from the arch package

**Description:**
Dragging&Dropping an image file from the nemo file manager to firefox nightly (currently on build 20230105213109) crashes firefox. Both processes use wayland, not xwayland. [Screencapture of the procedure](https://user-images.githubusercontent.com/1065730/210929270-1ca5a521-bc33-4d36-8692-281a69054438.mp4)
It crashes hard enough that the crash reporter doesn't trigger.

The same procedure works fine on i3.

I already [filed a bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1792754) on the mozilla issue tracker but was directed here since they couldn't reproduce it on mutter and judged it a sway-specific issue.

**Comment by emersion** [comment]
Can you post a `WAYLAND_DEBUG=1` log of Firefox while reproducing the crash?

**Comment by the8472** [comment]
https://gist.github.com/7719c4139fa4b57de12f01fce94e90fc

**Comment by kriansa** [comment]
I can reproduce it, as it also happens with Firefox stable (108 as of writing this)

**Comment by the8472** [comment]
Closing since firefox implemented the wayland proxy workaround that I proposed it has not been crashing anymore for me.
