### ISSUE TITLE
High idle amd gpu memory clock

### ISSUE THREAD

**Issue by Raucev** [swaywm/sway#7361]
### Please fill out the following:
- **Sway Version:**
  sway version 1.8(1:1.8-3)

- **Debug Log:**
 https://gist.github.com/Raucev/3db7685e2f624322d045eebfcfc595e4

- **Configuration File:**
  Can reproduce with a default configuration file.  https://github.com/swaywm/sway/blob/master/config.in

- **Description:**
  I have 1 VGA monitor(1080@60) connected with HDMI adapter to a gpu and 1 DVI monitor(1080@60) connected to a gpu. After updating sway from 1.7 to 1.8 my gpu is constantly at 100% mem clock and have ~30w idle draw(instead of 10w) Downgrading sway back to 1.7-10 resolves the problem.

**Comment by ErikReider** [comment]
I'm experiencing the same issue but only when my DP monitors refresh rate is above 59.96hz. Setting it to 60.01hz and above maxes the memory clock speed. Also reproducible on Gnome Wayland

**Comment by Raucev** [comment]
Problem seems to be fixed for me in 1.8.1

>       Apply new adaptive sync value from wlr-output-management
