### ISSUE TITLE
Segfaults when merging Firefox windows

### ISSUE THREAD

**Issue by ErikReider** [swaywm/sway#7368]
### Please fill out the following:
- **Sway Version:**
  - 1.8

- **Debug Log:**

  - [Log](https://gist.github.com/ErikReider/1b142dad29a8d05f2d65d61b71d1af38)

- **Configuration File:**
  - Default

- **Stack Trace:**
  - [Backtrace](https://gist.github.com/ErikReider/e09741ba26835982262ad42bedc14554)

- **Description:**
  - Open two Firefox windows with one tab each
  - Drag one of the tabs into the other window (merging the windows only leaving one window)
  - Move the mouse a little bit
  - **Segfault**

**Comment by vyivel** [comment]
https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3963 seems to fix this.

**Comment by ErikReider** [comment]
dup of #7345
