### ISSUE TITLE
SIGSEGV in input/tablet.c sway_tablet_pad_notify_enter

### ISSUE THREAD

**Issue by ToxicMushroom** [swaywm/sway#7369]
- **Sway Version:**
  - 1.8

- **Debug Log:**
  - https://paste.sr.ht/~pixelhamster/bd2369292c3ecc93c7309306b2af57510ff26c3f

- **Configuration File:**
  - I don't have tablet configuration, so I assume this is irrelevant

- **Stack Trace:**
  - https://paste.sr.ht/blob/f378b7a494e21e02b7d2821bc50193b79ed23401

- **Description:**
  - Using sway with a tablet, I only got this crash once during months of tablet usage.
  - Maybe this is some race condition ?

**Comment by ToxicMushroom** [comment]
I am now able to reproduce by launching sway (tablet plugged in) and hitting mod + l after sway started
`bindsym $mod+l exec --no-startup-id swaylock`
I'll provide more info and debug logs later today

**Comment by ToxicMushroom** [comment]
sway log: 
https://paste.sr.ht/~pixelhamster/bd2369292c3ecc93c7309306b2af57510ff26c3f

**Comment by bl4ckb0ne** [comment]
Could you try sway master to validate the fix in #7371?

**Comment by ToxicMushroom** [comment]
I ran sway-git at 53c9a4a6438824abfb3d539bf55aec92074977e0 and was no longer able to reproduce the issue moments after being able to reproduce it on the community sway pkg.
Thanks a lot for the quick fix :D

**Comment by bl4ckb0ne** [comment]
Great, thanks @vyivel for the fix
