### ISSUE TITLE
cannot recreate 'HEADLESS-1' output after destroying with unplug command

### ISSUE THREAD

**Issue by mdhen** [swaywm/sway#7374]
Sway version 1.8

after using unplug on a previously created HEADLESS-1 output, any attempt to recreate that output instead creates an output named HEADLESS-2, then headless-3, headless-4, etc. going up sequentially. These new outputs do not follow the location, size and Hz properties that are defined in sway config for headless-1. So it's a bit of a problem.

**Comment by mdhen** [comment]
can we get an option not to do that? it decreases functionality quite a bit.

**Comment by emersion** [comment]
Nope.

**Comment by mdhen** [comment]
any potential work arounds? use case is creating a virtual display for sunshine, and not having it up all the time for that use case.

**Comment by lulu-berlin** [comment]
@mdhen, I hit the same issue. The best workaround I could find is to disable the output instead of unplugging it:

```sh
swaymsg create_output
swaymsg output HEADLESS-1 disable
# and then:
swaymsg output HEADLESS-1 enable
```

You can enable and disable as many times as you want and you get the same result as you would with `unplug`.
