### ISSUE TITLE
sway randomly crashes

### ISSUE THREAD

**Issue by AggamR** [swaywm/sway#7377]
### Please fill out the following:
- **Sway Version:**
  1.8

- **Debug Log:**
  - Run `sway -d 2> ~/sway.log` from a TTY and upload it to a pastebin, such as gist.github.com.
[log file](https://pastebin.com/fuYxwbHh)

I got a dmesg error as well: 
`[150049.469221] sway[10696]: segfault at 8 ip 00007f5a11b50eaf sp 00007ffe6457cb68 error 6 in libwayland-server.so.0.21.0[7f5a11b4e000+8000] likely on CPU 0 (core 0, socket 0)`

- **Configuration File:**
[config](https://github.com/AggamR/dotfiles/tree/main/.config/sway)

- **Stack Trace:**
[stack trace](https://pastebin.com/XUxfdnrP)

- **Description:**
Sway just crashed and I hot thrown back to the login manager.

**Comment by emersion** [comment]
Does this patch help? (scheduled for wlroots 0.16.2 but not yet released)

https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3963

**Comment by AggamR** [comment]
> Does this patch help? (scheduled for wlroots 0.16.2 but not yet released)
> 
> https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3963

I'm sorry, I don't know how to install that...

**Comment by jasondaigo** [comment]
actually its for me also crashing for the first time in 2 years. just session exit and back to login. and i have to login again. might test that wlroots thingy now. indeed very random though.

**Comment by eternal-sorrow** [comment]
For me sway sometimes crashes when I close VSCode window (native wayland).

**Comment by bl4ckb0ne** [comment]
Fixed in wlroots master (see #7345)
