### ISSUE TITLE
pkill -RTMIN+5 waybar  kills bar with status_command

### ISSUE THREAD

**Issue by valdur55** [swaywm/sway#7393]
- **Sway Version:**
sway version 1.7

- **Debug Log:**
https://gist.github.com/valdur55/2c44ad4ffaed5457a0fcef9919feeb36#file-sway-log

- **Configuration File:**
https://gist.github.com/valdur55/2c44ad4ffaed5457a0fcef9919feeb36#file-sway-config

- **Description:**
I am using statusbar which uses status_command.
When I call **pkill -RTMIN+5 waybar** on terminal bar will dissapear.

**Comment by kennylevinsen** [comment]
Your config does not use waybar, and swaybar does not handle RTMIN+5.
