### ISSUE TITLE
[Bug confirmed] Input freezes on games with certain key combinations (when "hide_cursor when-typing enable" is present)

### ISSUE THREAD

**Issue by Zeioth** [swaywm/sway#7399]
### Please fill out the following:
- **Sway Version:** Tested from 1.7.6 to 1.8.3

-  **Debug Log:**
[LOG.](https://pastebin.com/raw/yxRWuw8Y)

- **Configuration File:**

```
seat * hide_cursor 899000
seat * hide_cursor when-typing enable
bindsym --to-code Mod4+d exec wofi -p run
xwayland enable
```

- **Description:**
  - When certain inputs are introduced, mouse freezes (only in games, not on desktop).
  - Started like a month ago.
  - The bug doesn't appear in Hyprland or any other DE, only sway.

- **How to reproduce**
  - Open Apex/Quake, or any other FPS game.
  - While you move from left to right, click your mouse and drag.
  - The camera will freeze until click is released.

Apologies for being too vague, but this is such an obscure bug that I'm not sure how to start debugging it. Only thing I'm sure is it's only present on sway. [I recorded a video commenting the issue](https://www.youtube.com/watch?v=7W8581YQqqs).

**Comment by Zeioth** [comment]
log added. Possible xwayland issue

    [xwayland/xwm.c:837] unhandled X11 property 404 (_NET_WM_BYPASS_COMPOSITOR) for window 37748737

Reverting xwayland version and testing.

**Comment by Zeioth** [comment]
Reverted xwayland version and restarted sway. Bug still present.

**Comment by Zeioth** [comment]
Running sway with this config solves the issue.

    bindsym --to-code Mod4+d exec wofi -p run
    xwayland enable

Looling for the line causing the issue on my original config.

**Comment by Zeioth** [comment]
Got it. I'm able to reproduce 100% of the time. This line is the culprit:

    seat * hide_cursor 899000
    seat * hide_cursor when-typing enable

Specifically, the second line.

Very likely there is something [in this commit](https://github.com/swaywm/sway/commit/96578aa91e9856bfb3e2d26fb7a625ff7c9b79e3) that is doing things that it should not.

**Comment by bl4ckb0ne** [comment]
It doesnt really feel like a bug, more like "by design". What maybe sway could not hide the cursor when a specific application is focused? Otherwise you should just disable this during your gaming sessions.

**Comment by Zeioth** [comment]
Its not actually hiding the mouse when the issue triggers (that would require 899000, aka 15 minutes of inactivity). It seems to be related with how that option checks if the user is typing? or inactive? I mean, using only 

    seat * hide_cursor 899000

Doesn't cause the issue.

**Comment by Zeioth** [comment]
Thiis bug is a duplicated of #7383. Closing.
