### ISSUE TITLE
Sway mistakenly assumes nvidia proprietary driver is in use

### ISSUE THREAD

**Issue by FilippoBonazziSUSE** [swaywm/sway#7402]
I am running sway on openSUSE Tumbleweed **with the Nouveau driver** installed, and **no** nvidia proprietary drivers.

A recent openSUSE Tumbleweed update installed the **open-source** nvidia driver [nvidia-open-driver-G06-signed-kmp-default](https://build.opensuse.org/package/show/openSUSE:Factory/nvidia-open-driver-G06-signed).

Now my sway session complains that I'm using the proprietary nvidia drivers, and will not start unless I declare that I'm running the proprietary nvidia driver (which I'm not):
```
Proprietary Nvidia drivers are NOT supported.  Use Nouveau. To launch sway anyway, launch with --unsupported-gpu and DO NOT report issues.
```

Of course there is a nvidia module in `/proc/modules`:
```
$ cat /proc/modules | grep nvidia
nvidia_drm 73728 0 - Live 0x0000000000000000 (O)
nvidia_modeset 1359872 1 nvidia_drm, Live 0x0000000000000000 (O)
nvidia_uvm 2969600 0 - Live 0x0000000000000000 (O)
nvidia 6025216 2 nvidia_modeset,nvidia_uvm, Live 0x0000000000000000 (O)
video 69632 4 dell_laptop,nvidia_modeset,dell_wmi,i915, Live 0x0000000000000000
```
... but it's an open source one.

How can the check in `sway/main.c:52` be improved to account for this situation?

---
System information:

```
$ uname -a
Linux tumbleweed 6.1.8-1-default #1 SMP PREEMPT_DYNAMIC Tue Jan 24 06:29:25 UTC 2023 (baebfe0) x86_64 x86_64 x86_64 GNU/Linux

$ sway --version
sway version 1.8

$ zypper search -i nvidia
Loading repository data...
Reading installed packages...

S | Name                                      | Summary                                                                | Type
--+-------------------------------------------+------------------------------------------------------------------------+--------
i | kernel-firmware-nvidia                    | Kernel firmware files for Nvidia Tegra and graphics drivers            | package
i | kernel-firmware-nvidia-gsp-G06            | Kernel firmware file for open NVIDIA kernel module driver G06          | package
i | nvidia-open-driver-G06-signed-kmp-default | NVIDIA open kernel module driver for GeForce RTX 2000 series and newer | package
```

**Comment by emersion** [comment]
Nouveau and the open-source NVIDIA kernel drivers are mutually exclusive. Are you sure you're running Nouveau?

The open-source NVIDIA kernel drivers are unsupported, because they require the proprietary NVIDIA GL stack in user-space.

**Comment by FilippoBonazziSUSE** [comment]
Well now that you say that, I can't find `nouveau` in `/proc/modules` anymore.

However I didn't install any proprietary NVIDIA GL stack in my userspace, that's for sure

**Comment by Arnavion** [comment]
>Well now that you say that, I can't find `nouveau` in `/proc/modules` anymore.

The `nvidia-open-driver-G06-signed-kmp-default` package installs `/usr/lib/modprobe.d/50-nvidia-default.conf` which contains `blacklist nouveau`, so if that package is installed nouveau will not get auto-loaded. You'll have to uninstall the package to be able to load nouveau again.

(Tumbleweed is a bit overzealous in installing this package - it installed it on my old Thinkpad even though its GPU is a decade older than what the open source driver supports. I had to uninstall it to get the GPU working again through nouveau.)
