### ISSUE TITLE
Clamshell mode not working

### ISSUE THREAD

**Issue by 8FordPrefect8** [swaywm/sway#7403]
I recently wanted to configure clamshell mode. After som unseccsessfull tries I read here that it's buggy now and the following oneliner would work.

```
exec_always 'if grep -q open /proc/acpi/button/lid/LID/state; then swaymsg output eDP-1 enable; else swaymsg output eDP-1 disable; fi'
 ```
Sadly, for me it doesn't work. If I run this command in terminal, when lid is open or closed, it does what one would expect. However, if I have this as exec_always in sway config it doesn't do anything.

_Originally posted by @8FordPrefect8 in https://github.com/swaywm/sway/issues/3137#issuecomment-1402557157_

**Comment by emersion** [comment]
`exec_always` is run once at startup, and when reloading the config file.

**Comment by 8FordPrefect8** [comment]
Ah, that explains why it can't work. Don't unterstand why it was frased as workaround.   

The commands from the community wiki don't work for me. I don't know if it's a general problem or a setup problem wigh my laptop.

**Comment by 8FordPrefect8** [comment]
Hmm okay, guess I have to search by myself then.
