### ISSUE TITLE
Steam is not showing on screen when using vulkan renderer

### ISSUE THREAD

**Issue by ardadem** [swaywm/sway#7404]
### Please fill out the following:
- **Sway Version:**
  - `sway version 1.8`

- **Debug Log:**
  - [logs](https://gist.github.com/ardadem/003243556b3293ecac4cbcc9023b7471)

- **Configuration File:**
  - [config](https://gist.github.com/ardadem/49cb03b82e7d4d223eab192964b0e048)

- **Description:**
  - To reproduce set `WLR_RENDERER=vulkan` then launch sway. Open steam and only tray icon shows up.
  - To fix unset `WLR_RENDERER` and launch sway. Open steam and everything works fine.

**Comment by emersion** [comment]
Nothing we can do about it. The Wayland client uses implicit format modifiers, which Vulkan doesn't support.

```
00:00:41.232 [DEBUG] [wlr] [render/vulkan/texture.c:424] vulkan_import_dmabuf: XR24 (mod ffffffffffffff), 384x142, 1 planes
00:00:41.232 [ERROR] [wlr] [render/vulkan/texture.c:441] Format 34325258 (XR24) can't be used with modifier ffffffffffffff
00:00:41.232 [ERROR] [wlr] [types/buffer/client.c:60] Failed to create texture
00:00:41.232 [ERROR] [wlr] [types/wlr_compositor.c:372] Failed to upload buffer
```

**Comment by jayofdoom** [comment]
Going to note for anyone seeing this in more recent times: This is tested working on my WLR_RENDERER=vulkan sway machine w/latest steam.
