### ISSUE TITLE
sway-1.8: swaylock mouse can handle windows behind lock

### ISSUE THREAD

**Issue by arbitrary-dev** [swaywm/sway#7407]
After update to Sway v1.8, I can now not only observe mouse cursor in `swaylock`, but can even move/resize underlying windows behind the lock screen.

- **Sway Version:** 1.8

- **Configuration File:**
```
$ cat .config/sway/config
...
bindsym $mod+Ctrl+l exec swaylock
...

$ cat ~/.config/swaylock/config
daemonize
hide-keyboard-layout
color=000000
```

- **Description:**
  - lock the screen with `swaylock`
  - you can still see the mouse cursor (was not the case in 1.7)
  - moving the mouse around you can locate underlying windows and even resize them behind the screen lock

- **Proposal**
  - remove mouse cursor from `swaylock`

**Comment by emersion** [comment]
This is fixed in master.
