### ISSUE TITLE
Sway crashes when shutting down Chromium (with Devtools panel open)

### ISSUE THREAD

**Issue by nickdiego** [swaywm/sway#7416]
- **Sway Version:** 
  - sway version 1.7

- **Debug Log:**
  - https://0x0.st/oFn9.log

- **Configuration File:**
  - repro with default config file.

- **Stack Trace:**
  - https://0x0.st/oFnp.txt

- **Description:**
  - Launch Chromium with the command below
  - Interrupt it with `Ctrl+C` in the launching prompt. 
  - Sway crashes at this point.
  - _(Reproduced` only with latest devel release 111.0.5562.0-1 - `google-chrome-dev` AUR in Arch Linux)_

```shell=bash
google-chrome-unstable --enable-logging=stderr \
  --user-data-dir=/tmp/chr-dev \
  --ozone-platform=wayland \
  --auto-open-devtools-for-tabs
```
I'll file a chromium bug and link it here, though I assume Sway shouldn't crash anyway.

**Comment by emersion** [comment]
The backtrace you provided doesn't contain debug symbols. This most likely happens because the Sway binary you're using doesn't have debug information bundled.

Can you try again with a manually compiled Sway binary? See https://github.com/swaywm/sway/wiki/Development-Setup#compiling-as-a-subproject

**Comment by nickdiego** [comment]
Will do that and share the output here. thanks

**Comment by nickdiego** [comment]
Here we go: https://0x0.st/oCo1.log

IIUC, it's a null deref, which seems to have been recently [fixed](https://github.com/swaywm/sway/pull/7168/files), so 1.8 would no longer crash (couldn't upgrade to it yet).

Assuming that surface pointer holds the [requestor surface](https://wayland.app/protocols/xdg-activation-v1#xdg_activation_token_v1:request:set_surface), this is probably related to this [recent change]() in chromium. For which we've filed this [upstream bug](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/issues/129), asking for clarification about that argument.

If that's correct, I guess this can be marked as fixed. thanks

**Comment by emersion** [comment]
Alright, let's cl;ose this for now. Please re-open if you can still reproduce on Sway master.
