### ISSUE TITLE
Shift key symbols not accessible for keybindings + keyboard layout discrepancy

### ISSUE THREAD

**Issue by SoumyaRanjanPatnaik** [swaywm/sway#7434]
Hello.
I have observed that sway doesn't detect certain keybindings that have the `Shift` modifier. Let us take a US keyboard layout for example.  The question mark key ('?') is detected within the keybindings when the following is placed in the sway config:
```
bindsym $mod+Shift+slash
``` 

This works because `Shift+slash` is essentially same as `?`. But using the following in the configuration leads to the keybinding to be not detected.
```
bindsym $mod+Shift+question
```
This is in contrast to the behavior presented by i3. This becomes a concern when you want to be able the same keybinding for different keyboard layouts. For example, `Shift+slash` on US layout gives `question` as expected, but the same on the Spanish (es) layout doesn't make sense as `/` itself requires `Shift` to access (refer to image below).
![ES layout keyboard](https://user-images.githubusercontent.com/75623505/216988634-e9424803-2660-465f-a331-273aa379a9db.png)

I tried searching for related issues, and was quite surprised to see no one has noticed this issue yet. 

**NOTE**: The same issue also happens with the `plus` (`+`) key, or any other symbols that are accessed using shift.

**Comment by kgilmer** [comment]
Related: https://github.com/swaywm/sway/issues/5409
