### ISSUE TITLE
Crashes with certain applications using Xwayland

### ISSUE THREAD

**Issue by ethanalker** [swaywm/sway#7439]
- **Sway Version:**
`sway version 1.8`

- **Debug Log:** 
[Sway debug log](https://github.com/swaywm/sway/files/10672017/2023-02-07-00-39-sway-gschem.log)

- **Configuration File:**
Can be reproduced with minimal config

- **Stack Trace:**
[gdb coredump log](https://github.com/swaywm/sway/files/10672026/2023-02-07-00-39-coredump-gschem.log)

- **Description:**
I have had sway crash a few times, always with Xwayland applications. I managed to consistently reproduce it with gEDA gschem, a schematic capture program. Sway will consistently crash when bringing up a certain text box and typing quickly. The sway log and crash report I included are with my normal config but I tested it and can reproduce it with minimal config. I have a few logs saved from various tests. Other programs it has crashed while running include intel Quartus Prime and a steam game. The steam game started from a desktop file, and there was a wired controller in the picture (when starting it from steam directly I haven't had it crash, but I didn't test it). For Quartus I don't remember much about what I was doing, I tried to reproduce it but could not. 

I have sway logging on now, so if it crashes using a different application I'll post that log and stack trace as well.
 
**Steps to Reproduce**
1. Start sway
2. Open gschem
3. Focus on the right panel
4. Begin typing. A text box should appear above.
5. Type quickly (keyboard smash). Sway should crash.

**Comment by bl4ckb0ne** [comment]
Dup of https://github.com/swaywm/sway/issues/7389

Issue has been fixed in wlroots master
