### ISSUE TITLE
Border/titlebar issues on layout switch with pixel 1

### ISSUE THREAD

**Issue by thejan2009** [swaywm/sway#745]
Titlebars and borders of tabbed container persist after switching to vertical/horizontal split.

How to reproduce:
swaymsg new_window pixel 1
Spawn a few windows in tabbed layout, split v, spawn a few windows, layout tabbed, layout splitv.

When views in the vertically split layout are focused, titlebars from previous tabbed layout appear.
![2016-07-10-195240_swaygrab](https://cloud.githubusercontent.com/assets/1621134/16715244/8f20024a-46da-11e6-8321-78ad61b479c2.png)

**Comment by SirCmpwn** [comment]
I'm closing issues that are resolved by the yet-unreleased sway 1.0.
