### ISSUE TITLE
contrib/inactive-windows-transparency.py doesn't apply opacity rule properly on multiple displays

### ISSUE THREAD

**Issue by GoodGuyPat** [swaywm/sway#7452]
### Please fill out the following:
- **Sway Version:** 1.8.1

- **Configuration File:**
Default config with `exec /usr/share/sway/scripts/inactive-windows-transparency.py --opacity 0.85` appended

- **Description:**
In a system with multiple (5 in this case) displays, inactive-windows-transparency.py works as expected when first run. The expected behavior is that windows will present 100% opacity whenever in focus, and whichever percentage specified in the `--opacity` argument when not in focus. This is true, except in cases where a window is the only one in a given workspace, where it will present the unfocused opacity value when inactive-windows-transparency.py is first ran, but once it gains focus once, the opacity will remain at 100% as if the window had focus, even if focus is lost.

**Comment by emersion** [comment]
`contrib/` has been moved to another repo, see https://github.com/swaywm/sway/pull/7541
