### ISSUE TITLE
External monitor not working under opengl

### ISSUE THREAD

**Issue by lpaulino07** [swaywm/sway#7455]
- **Sway Version:**
  - sway version 1.8.1

- **Debug Log:**
  - https://gist.github.com/lpaulino07/c6db83edcb1882fc8368de24acd150e2
 
- **Description:**
  - External monitor connected to laptop through mini-DP doesn't display anything unless I start sway with WLR_RENDERER=vulkan. Tried with default config file and still didn't work. I don't mind using the vulkan backend, but I assumed this is not expected behavior so decided to submit it. I guess it is worth noting that the external monitor works fine under gnome, kde and windows 11.

**Comment by emersion** [comment]
IIRC @bl4ckb0ne hit this as well:

```
00:00:00.656 [ERROR] [wlr] [EGL] command: eglCreateImageKHR, error: EGL_BAD_ALLOC (0x3003), message: "createImageFromDmaBufs failed"
00:00:00.656 [ERROR] [wlr] [render/egl.c:767] eglCreateImageKHR failed
00:00:00.656 [ERROR] [wlr] [render/gles2/texture.c:291] Failed to create EGL image from DMA-BUF
00:00:00.656 [ERROR] [wlr] [backend/drm/renderer.c:95] Failed to import source buffer into multi-GPU renderer
00:00:00.656 [ERROR] [sway/config/output.c:511] Failed to commit output DP-1
```

**Comment by bl4ckb0ne** [comment]
Related to https://github.com/swaywm/sway/issues/7352

I had this issue once then it went away after a reboot. I have 3 GPU (Cezanne, Navi24 and Navi22) with both screens in the Navi22 GPU. The issue appeared on kernel 6.1.11 and went away with 6.1.12.

**Comment by lpaulino07** [comment]
I see. #7352 suggests that this is a mesa issue. Should I close this issue then?

**Comment by bl4ckb0ne** [comment]
Its unclear to me weather its a mesa issue or a kernel issue, but it doesnt seems related to sway or wlroots to me.

I'll close the issue, reopen or add more comment if you can provide logs that points to a sway issue.
