### ISSUE TITLE
Weird screen updates (?) issues with some recent apps

### ISSUE THREAD

**Issue by alxchk** [swaywm/sway#7458]
There is strange behavior, which I observe now with two apps -- Signal Desktop (using wayland as native backend) and latest Telegram Desktop (4.6.2, 4.5.3 works fine, both are Qt6.4.2). While this was just with Signal Desktop, I thought that's just application problem, now I'm not so sure..

The problem can best be described next way (for both apps).
There is IM window with chat. And sometimes (?) but quite often new messages are not drawn to the screen. If I resize a window (for example to fullscreen then back) it's updated, and there is a new text in it. This may happen when I switch to another screen, this may happen while the IM window is open. 

 > swaymsg -t get_version
sway version 1.9-dev-9162b536 (Feb 17 2023, branch 'HEAD')

wlroots: 58067a20844d23527c29b4382a2b182c6590317e
linux: 6.1.7
Intel UHD Graphics 620

**Comment by alxchk** [comment]
Is there any way how to diagnose this properly? I'm not sure it's about focus. As this may happen when app is opened (i.e. not clear how it may lose the focus). Also signal-desktop is electron (not QT). And same version of Qt works fine with different versions of the app..

**Comment by llyyr** [comment]
Can reproduce this with any electron app and I'm quite sure it was a recent wlroots comments I'll try to bisect it later

Easy way to reproduce it is to open an Electron app and send it to scratchpad, then bring it back out of the scratchpad

**Comment by llyyr** [comment]
I was able to narrow it down to to the linux-dmabuf-v1 changes earlier this month. Specifically, these commits

https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3933/commits
https://github.com/swaywm/sway/commit/b4ce0a30c1d8d7f2af82f4da5858c1379f8399a1

cc @emersion

**Comment by rpigott** [comment]
In that case a WAYLAND_DEBUG log of the client during the event might be helpful.

**Comment by llyyr** [comment]
this is me pressing mod+c to `scratchpad show` the window until it fails to render an update

for some reason there's a primary selection offer which is uhhh ????

[log.log](https://github.com/swaywm/sway/files/10847101/log.log)

**Comment by msmol** [comment]
Can confirm seeing same issue
```
$ swaymsg -t get_version
sway version 1.8.1
```

**Comment by vyivel** [comment]
Should be closed by https://github.com/swaywm/sway/pull/6844.
