### ISSUE TITLE
Key bindings do not work in Cyrillic layout

### ISSUE THREAD

**Issue by glow12121** [swaywm/sway#7486]
I use two layouts, US English and Russian ones. The default key bindings are set for the Latin alphabet only.

Is it possible to get keybindings mirrored for non-Latin layouts, so that keyboard keys, not alphabet letters be what matters?

**Comment by SergeyKasmy** [comment]
Here's a snippet from `man sway`

>bindsym [--whole-window] [--border] [--exclude-titlebar] [--release] [--locked] [--to-code] [--input-device=<device>] [--no-warn] [--no-repeat] [Group<1-4>+]<key combo> <command>
>
>...
>
>Bindings to keysyms are layout-dependent. This can be changed with the --to-code flag. In this case, the keysyms will be translated into the corresponding keycodes in the first configured layout.

I'm using `en_US` and `ru_RU` layouts as well and can confirm `bindsym --to-code` works

**Comment by glow12121** [comment]
@SergeyKasmy many thanks, it works for me too.
