### ISSUE TITLE
No pixel hunting to resize windows with mouse

### ISSUE THREAD

**Issue by glow12121** [swaywm/sway#7488]
I was wondering if it is possible to make the area at the edges of floating windows, the one where you can drag and resize windows with the mouse, a little bigger? Right now, really, pixel hunting is required to find this tiny spot where you can click and start resizing.

**Comment by Xyene** [comment]
You can hold <kbd>Mod</kbd> and right click to enter an interactive resizing mode from any point on the window under your cursor, without hunting for the border.

**Comment by glow12121** [comment]
That's a workaround, a different method to resize. Plus, it doesn't work with my touchpad.

**Comment by glow12121** [comment]
@mstoeckl with this setting, regular floating windows look like this, and again pixel hunting is needed to resize:

![2023-03-08T06:13:17,247772860+03:00](https://user-images.githubusercontent.com/29035180/223610968-78b0b2b3-50a0-4f12-933b-cba79e83aeee.png)

While dialogue windows look like this:

![2023-03-08T06:11:13,144977349+03:00](https://user-images.githubusercontent.com/29035180/223611050-eb464c42-c91a-42e0-b700-949f2d184a40.png)

I want to completely get rid of borders but still be able to resize floating and dialogue (these are different classes, right?) conveniently. It seems that it would be better to separate borders and areas for resizing.

**Comment by emersion** [comment]
Sorry, we're not accepting any new window management features anymore. See https://github.com/swaywm/sway/blob/master/CONTRIBUTING.md#scope-of-future-changes-to-sway
