### ISSUE TITLE
Make several scroll methods possible

### ISSUE THREAD

**Issue by glow12121** [swaywm/sway#7491]
I want to scroll by using 1) the edge of the touchpad and 2) two fingers.

But right now only one method is possible: `input <identifier> scroll_method none|two_finger|edge|on_button_down`.

**Comment by rpigott** [comment]
You'd have to request this feature from libinput first, it currently is not supported.

**Comment by glow12121** [comment]
Thanks for pointing this out.

I've registered on [theit Git](https://gitlab.freedesktop.org/libinput/libinput) but cannot do anything because I am a new user. I've read the wiki page they advised but can't figure out how to get even minimal access.

> Due to an influx of spam, we have had to impose restrictions on new accounts. Please see [this wiki page](https://gitlab.freedesktop.org/freedesktop/freedesktop/-/wikis/home) for instructions on how to get full permissions. Sorry for the inconvenience.

**Comment by rpigott** [comment]
Yeah, hopefully that is temporary. Anyway https://gitlab.freedesktop.org/libinput/libinput/-/issues/590 seems related maybe watch that one.

**Comment by glow12121** [comment]
@rpigott thanks!

**Comment by bentiss** [comment]
@glow12121: when you register on gitlab.fd.o you can file issues without asking for permissions. When you want to fork an existing project or create one from scratch you have to ask for permission. So in your case you should be able to just file your RFE on libinput without trouble.

**Comment by glow12121** [comment]
@bentiss it's true. But yesterday, after I registered, I couldn't even see the issues. Everything, somehow, was blocked.

**Comment by bentiss** [comment]
@glow12121 that is weird. It is as if you were blocked by gitlab, which should only happen if you posted spam and be reported as such. I also do not see any trace of this username in the logs. Do you mind retrying?

(and sorry for hijacking this thread)

**Comment by glow12121** [comment]
I do have a Gitlab account but I thought a new one was needed for the FDO board.
