### ISSUE TITLE
Vim/Neovim with GPU acceleration freezes on main monitor only with sway

### ISSUE THREAD

**Issue by Samuelfaure** [swaywm/sway#7492]
OS: Arch linux
Sway version: 1.8.1 

GL_VENDOR: AMD
GL_RENDERER: AMD Radeon Graphics (rembrandt, LLVM 15.0.7, DRM 3.49, 6.2.1-arch1-1)
GL_VERSION: OpenGL ES 3.2 Mesa 22.3.6

Very weird issue: Vim/Neovim through Alacritty or Foot terminal gets regular freezes/huge lags when launched on my main screen (laptop screen). It works great on the HDMI screen.

Problem doesn't happen when:

- The sway window is fullscreen 
- The sway window is on external HDMI monitor
- GPU acceleration is disabled with LIBGL_ALWAYS_SOFTWARE=1
- Using Weston instead of Sway
- Launching with WAYLAND_DISPLAY= (launching on XWayland)
- running alacritty with --print-events or -vvv also fixes the lag/freeze, but not with -vv (?????)
- Another GPU-rendered terminal (Kitty) do not reproduces the issue, Alacritty and Foot however do

Switching from ZSH to Bash do not fix the issue

Note, I also been having some full freezes on main monitor when using Tor browser, not sure if related.

**Comment by lolzballs** [comment]
Pretty sure this is an issue with PSR on AMD. Disabling PSR by adding `amdgpu.dcdebugmask=0x10` to my kernel cmdline resolves the issue.

**Comment by Samuelfaure** [comment]
@lolzballs You saved me! Thank you so much :)
