### ISSUE TITLE
Add fork/backgrounding option to swaynag, analogous to swaylock

### ISSUE THREAD

**Issue by OJFord** [swaywm/sway#7503]
I'm having some trouble integrating swaynag via a script for waybar, since I need it to appear but continue with the script and exit successfully. It seems waybar doesn't consider the script completed until any child (even disowned) processes also exit - the output doesn't appear until I dismiss the nag bar.

A more convenient solution anyway would be if I could `swaynag -f` or even `swaymsg nag [... options to swaynag]`.

**Comment by emersion** [comment]
This doesn't make sense to me, sorry.
