### ISSUE TITLE
Focus follows mouse breaks when a combo menu is open.

### ISSUE THREAD

**Issue by WhyNotHugo** [swaywm/sway#7511]
### Sway version

  - `sway version 1.8.1`

### Configuration File

  - Nothing special; `focus_follows_mouse` is on by default.

### Stack trace

  - n/a

### Description

Focus follows mouse does not work when a combo menu is open in the window that the mouse is leaving.

### Reproduction steps

- Open a client that can render a combo menu. let's use `pavucontrol` for example (switch to the Configuration tab).
- Make the workspace a horizontal split, and open any other client on the right. For example, a terminal.
- On the first client, click to open the combo menu.
- Move the mouse to the right client.

The combo menu will close on the left client, but the right one does not gain focus. If you press <kbd>Space</kbd>, you'll notice that the left client still has focus (since <kbd>Space</kbd> interacts with its focused control).

**Comment by smlx** [comment]
I can also reproduce in 1.7.

**Comment by lanodan** [comment]
Might be a slightly different bug but I also have it on my desktop here with multiple displays (and so across workspaces).

**Comment by WhyNotHugo** [comment]
This seems to be fixed in master. I tried reproducing the issue with pavucontrol and firefox. When the mouse hovers another window, that other window grabs focus and the original combo is closed.

I'll go ahead and close this. If you can reproduce with some other client, please report which one and I'll reopen.
