### ISSUE TITLE
Thinkpad P16 (nouveau + i915): no external screen recognized

### ISSUE THREAD

**Issue by pevik** [swaywm/sway#7513]
Thinkpad P16 has these GPU:
00:02.0 VGA compatible controller: Intel Corporation Alder Lake-HX GT1 [UHD Graphics 770] (rev 0c)
01:00.0 VGA compatible controller: NVIDIA Corporation GA107GLM [RTX A1000 Laptop GPU] (rev a1)

I'm not able to use external screen on sway, only laptop screen (i915) is working. I see dmesg before booting into sway on both screens (it's working on console level). I tested it on both openSUSE Tumbleweed (latest stable kernel) and recently downloaded manjaro Live CD (of course not using nvidia propritetary driver).

NOTE: external screen works on GNOME 43 on Fedora 37 live also reported to be working on GNOME 3 (both with nouveau + i915).

**sway stdout and stderr log** 
* sway run **with `-d`** (openSUSE Tumbleweed): **https://gist.github.com/pevik/0efbf1952e0a3874b31d558dc8d385a2**
* *without* `-d`(Manjaro installer and Live CD): https://gist.github.com/pevik/1831951748c202a9f47c3c3954c683f4

Logs get on sway on Manjaro:
```
$ lspci -nnk |grep -A3 VGA
00:02.0 VGA compatible controller [0300]: Intel Corporation Alder Lake-HX GT1 [UHD Graphics 770] [8086:4688] (rev 0c)
	Subsystem: Lenovo Device [17aa:22fb]
	Kernel driver in use: i915
	Kernel modules: i915

01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA107GLM [RTX A1000 Laptop GPU] [10de:25b9] (rev a1)
	Subsystem: Lenovo Device [17aa:22db]
	Kernel driver in use: nouveau
	Kernel modules: nouveau

$ lsmod |grep -e ^nouveau -e ^nvidia -e ^i915
i915                 3784704  9
$ sway -v
sway version 1.8.1

$ uname -r
6.2.5-1-MANJARO # but tested with the same result also on 6.1.x on openSUSE

$ cat /proc/cmdline
... quiet systemd.show_status=1 driver=free nouveau.modeset=1 i915.modeset=1 radeon.modeset=1

# note, I also tested it also on 

$ swaymsg -t get_outputs
Output eDP-2 'AU Optronics 0xB69D Unknown' (focused)
  Current mode: 1920x1200 @ 60.096 Hz
  Position: 0,0
  Scale factor: 1.000000
  Scale filter: nearest
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 1:  
  Max render time: off
  Adaptive sync: disabled
  Available modes:
    1920x1200 @ 60.096 Hz
    1920x1200 @ 48.015 Hz
```

[`drm_info`](https://github.com/ascent12/drm_info) shows unsupported for Nvidia with nouveau driver:
```
Node: /dev/dri/card1
├───Driver: i915 (Intel Graphics) version 1.6.0 (20201103)
│   ├───DRM_CLIENT_CAP_STEREO_3D supported
│   ├───DRM_CLIENT_CAP_UNIVERSAL_PLANES supported
│   ├───DRM_CLIENT_CAP_ATOMIC supported
│   ├───DRM_CLIENT_CAP_ASPECT_RATIO supported
│   ├───DRM_CLIENT_CAP_WRITEBACK_CONNECTORS supported
...
Node: /dev/dri/card0
├───Driver: nouveau (nVidia Riva/TNT/GeForce/Quadro/Tesla/Tegra K1+) version 1.3.1 (20120801)
│   ├───DRM_CLIENT_CAP_STEREO_3D supported
│   ├───DRM_CLIENT_CAP_UNIVERSAL_PLANES supported
│   ├───DRM_CLIENT_CAP_ATOMIC not supported
│   ├───DRM_CLIENT_CAP_ASPECT_RATIO supported
│   ├───DRM_CLIENT_CAP_WRITEBACK_CONNECTORS not supported
```
Full [`drm_info`](https://github.com/ascent12/drm_info) output is in https://gist.github.com/pevik/db59c60be7f154a73897a2d344adb894.

I just wonder if there is something missing in the support, but there is basic GA107 RTX A1000 support in kernel 
(besides that is obviously working on GNOME), see [`drivers/gpu/drm/nouveau/nvkm/engine/device/base.c`](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/gpu/drm/nouveau/nvkm/engine/device/base.c?h=v6.2#n2717).

There are more commits which support Ampere acceleration support, but not GA107 (https://kernelnewbies.org/Linux_6.2#Graphics):
* [4b569ded09fd ("drm/nouveau/acr/ga102: initial support")](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=4b569ded09fdadb0c14f797c8dae4e8bc4bbad9f)
* [21e938d0017d ("drm/nouveau/ltc/ga102: initial support")](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=21e938d0017d3523ef5114a8feebc32e95007983)
* [c4bdac754ca0 ("drm/nouveau/gr/ga102: initial support")](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=c4bdac754ca0bb21bad598b47dd8c2c86eee1cc1)

**Comment by emersion** [comment]
Your bug report is missing debug logs. Please add a link to the full debug log file.

    sway -d >sway.log 2>&1

**Comment by pevik** [comment]
@emersion I'm sorry, it's here https://gist.github.com/pevik/1831951748c202a9f47c3c3954c683f4

**Comment by pevik** [comment]
@emersion sway run with `-d` (in openSUSE Tumbleweed): https://gist.github.com/pevik/0efbf1952e0a3874b31d558dc8d385a2

**Comment by kennylevinsen** [comment]
The log you posted only successfully bring up the Intel GPU due to the nouveau_dri error, and therefore only sees what is connected there, so post the full load with everything loading correctly.

You can also post the output of `drm_info`.

**Comment by pevik** [comment]
Actually, after installing `Mesa-dri-nouveau` (really the only packaging change on the system) and rebooting on openSUSE Tumbleweed, sway refused to run:
```
00:00:00.000 [INFO] [sway/main.c:338] Sway version 1.8.1
00:00:00.000 [INFO] [sway/main.c:339] wlroots version 0.16.2
00:00:00.001 [INFO] [sway/main.c:120] Linux p16 6.1.10-1-default #1 SMP PREEMPT_DYNAMIC Mon Feb  6 07:27:26 UTC 2023 (2a0570b) x86_64 x86_64 x86_64 GNU/Linux
00:00:00.001 [INFO] [sway/main.c:136] Contents of /etc/os-release:
00:00:00.001 [INFO] [sway/main.c:120] NAME="openSUSE Tumbleweed"
00:00:00.001 [INFO] [sway/main.c:120] # VERSION="20230213"
00:00:00.001 [INFO] [sway/main.c:120] ID="opensuse-tumbleweed"
00:00:00.001 [INFO] [sway/main.c:120] ID_LIKE="opensuse suse"
00:00:00.001 [INFO] [sway/main.c:120] VERSION_ID="20230213"
00:00:00.001 [INFO] [sway/main.c:120] PRETTY_NAME="openSUSE Tumbleweed"
00:00:00.001 [INFO] [sway/main.c:120] ANSI_COLOR="0;32"
00:00:00.001 [INFO] [sway/main.c:120] CPE_NAME="cpe:/o:opensuse:tumbleweed:20230213"
00:00:00.001 [INFO] [sway/main.c:120] BUG_REPORT_URL="https://bugs.opensuse.org"
00:00:00.001 [INFO] [sway/main.c:120] HOME_URL="https://www.opensuse.org/"
00:00:00.001 [INFO] [sway/main.c:120] DOCUMENTATION_URL="https://en.opensuse.org/Portal:Tumbleweed"
00:00:00.001 [INFO] [sway/main.c:120] LOGO="distributor-logo-Tumbleweed"
00:00:00.001 [INFO] [sway/main.c:108] LD_LIBRARY_PATH=
00:00:00.001 [INFO] [sway/main.c:108] LD_PRELOAD=
00:00:00.001 [INFO] [sway/main.c:108] PATH=/usr/local/bin:/usr/bin:/bin
00:00:00.001 [INFO] [sway/main.c:108] SWAYSOCK=
00:00:00.001 [INFO] [sway/main.c:376] Starting sway version 1.8.1
00:00:00.001 [DEBUG] [sway/server.c:67] Initializing Wayland server
00:00:00.001 [INFO] [wlr] [libseat] [libseat/backend/seatd.c:80] Could not connect to socket /run/seatd.sock: No such file or directory
00:00:00.001 [INFO] [wlr] [libseat] [libseat/libseat.c:76] Backend 'seatd' failed to open seat, skipping
00:00:00.004 [INFO] [wlr] [libseat] [libseat/libseat.c:73] Seat opened with backend 'logind'
00:00:00.004 [INFO] [wlr] [backend/session/session.c:109] Successfully loaded libseat session
00:00:00.007 [INFO] [wlr] [backend/backend.c:220] Found 2 GPUs
00:00:00.007 [INFO] [wlr] [backend/drm/backend.c:200] Initializing DRM backend for /dev/dri/card1 (i915)
00:00:00.007 [DEBUG] [wlr] [backend/drm/drm.c:88] Using atomic DRM interface
00:00:00.007 [DEBUG] [wlr] [backend/drm/drm.c:100] ADDFB2 modifiers supported
00:00:00.007 [INFO] [wlr] [backend/drm/drm.c:253] Found 4 DRM CRTCs
00:00:00.007 [INFO] [wlr] [backend/drm/drm.c:180] Found 24 DRM planes
00:00:00.007 [INFO] [wlr] [backend/drm/backend.c:200] Initializing DRM backend for /dev/dri/card0 (nouveau)
00:00:00.007 [DEBUG] [wlr] [backend/drm/drm.c:84] Atomic modesetting unsupported, using legacy DRM interface
00:00:00.007 [DEBUG] [wlr] [backend/drm/drm.c:100] ADDFB2 modifiers supported
00:00:00.007 [INFO] [wlr] [backend/drm/drm.c:253] Found 4 DRM CRTCs
00:00:00.007 [INFO] [wlr] [backend/drm/drm.c:180] Found 12 DRM planes
00:00:00.008 [INFO] [wlr] [render/egl.c:201] Supported EGL client extensions: EGL_EXT_device_base EGL_EXT_device_enumeration EGL_EXT_device_query EGL_EXT_platform_base EGL_KHR_client_get_all_proc_addresses EGL_EXT_client_extensions EGL_KHR_debug EGL_EXT_platform_device EGL_EXT_platform_wayland EGL_KHR_platform_wayland EGL_EXT_platform_x11 EGL_KHR_platform_x11 EGL_EXT_platform_xcb EGL_MESA_platform_gbm EGL_KHR_platform_gbm EGL_MESA_platform_surfaceless
00:00:00.009 [DEBUG] [wlr] [render/egl.c:469] Using EGL device /dev/dri/card0
nvc0_screen_create:1093 - Base screen init failed: -19
```

openSUSE uses greetd for starting, but exactly the same output happens when I log into tty console and run `sway -d >sway.log 2>&1` as logged user (without greetd`).
BTW If I'm not mistaken, there is no GA107 (`0x177`) support in https://gitlab.freedesktop.org/nouveau/mesa (https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/nouveau/codegen/nv50_ir_driver.h#L73-79), file is the same in the mesa fork (https://gitlab.freedesktop.org/nouveau/mesa).
Maybe it's a problem of my config, but I suspect some driver is not ready yet.

**Comment by XGX1** [comment]
https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3541
Maybe you can take a look at this, similar to your situation, I also encountered this problem, fk n

**Comment by pevik** [comment]
@XGX1 Thanks, I'll have look into. BTW in my case X11 is not working (at least not fluxbox), that was one of the reasons for me trying to switch to wayland based VM.

**Comment by pevik** [comment]
@emersion @kennylevinsen do you still expect anything from me? I uploaded logs, which show that with `Mesa-dri-nouveau` package sway even does not start. This can be bug in [openSUSEway](https://build.opensuse.org/package/show/X11:Wayland/openSUSEway) (sway + additional configs, using greetd for login) or even sway bug.

**Comment by emersion** [comment]
The error is coming from Mesa, not Sway. Either your GPU isn't supported by nouveau's user-space driver, either this is a Mesa bug.

**Comment by pevik** [comment]
FYI in the end I gave up and migrate to Nvidia proprietary GPU driver (see https://sndirsch.github.io/nvidia/2022/06/07/nvidia-opengpu.html), which works well with Sway (including external screens). It requires to set `options nvidia NVreg_OpenRmEnableUnsupportedGpus=1` in `/usr/lib/modprobe.d/50-nvidia-default.conf`).

**Comment by ethnh** [comment]
> FYI in the end I gave up and migrate to Nvidia proprietary GPU driver (see https://sndirsch.github.io/nvidia/2022/06/07/nvidia-opengpu.html), which works well with Sway (including external screens). It requires to set `options nvidia NVreg_OpenRmEnableUnsupportedGpus=1` in `/usr/lib/modprobe.d/50-nvidia-default.conf`).

Awesome, thx for sharing. Fixed my problem too :D
