### ISSUE TITLE
TMPDIR is not available

### ISSUE THREAD

**Issue by jmcantrell** [swaywm/sway#7555]
### Please fill out the following:
- **Sway Version:**
  - sway version 1.8.1

- **Debug Log:**
  - https://gist.github.com/jmcantrell/a45c5c71ba6b6bb523ca227e8b071715

- **Configuration File:**
  - default config file for arch

- **Description:**
  - from console: `export TMPDIR=/path/to/tmp`
  - run sway
  - from foot or alacritty: `typeset -p TMPDIR`
  - see output: `typeset: no such variable: TMPDIR`
  - from a terminal: `sudo strings /proc/$(pidof sway)/environ | grep TMPDIR`
  - see the exported variable

Any other environment variable exported from the console will be available.

**Comment by emersion** [comment]
As explained on IRC, this is the doing of ld.so when the Sway executable has `CAP_SYS_NICE`. Nothing Sway can do about it.

**Comment by jmcantrell** [comment]
Thanks for your help understanding this.

**Comment by Jorenar** [comment]
> As explained on IRC, this is the doing of ld.so when the Sway executable has `CAP_SYS_NICE`. Nothing Sway can do about it.

Hmm, is there perhaps any workaround?
