### ISSUE TITLE
Kicad very sluggish when some of its windows are hidden

### ISSUE THREAD

**Issue by kuon** [swaywm/sway#7557]
I run wayland, with sway 1.8.1, and I use kicad under xwayland.

The issue is quite simple to explain and reproduce, if any of kicad window is not directly visible, the whole application becomes very sluggish, with mini freezes all over the place.

I would really like to help pinpoint and fix this issue as it is the only major issue making kicad hard to use on wayland (xwayland).

I am still trying to figure out where this issue should be addressed, and then I will provide debug logs or any other requested data.

Reference:

https://gitlab.freedesktop.org/wayland/weston/-/issues/749

**Comment by emersion** [comment]
Mesa will block in `eglSwapBuffers` when a window is hidden. This is not Sway-specific, will happen under any Wayland compositor. Xwayland has a 1Hz fallback timer when a window is hidden.

**Comment by kuon** [comment]
Ok, so in this case, it is an issue of wxWidgets?
