### ISSUE TITLE
With latest sources Sway crashes with hardware cursors

### ISSUE THREAD

**Issue by J0nnyMak0** [swaywm/sway#7560]
Works fine with WLR_NO_HARDWARE_CURSORS=1

Trace and log attached.

[gdb.txt](https://github.com/swaywm/sway/files/11376923/gdb.txt)
[sway.log](https://github.com/swaywm/sway/files/11376924/sway.log)

**Comment by rpigott** [comment]
Did you mean after 33cfdbe88614?
