### ISSUE TITLE
Memory leak on output mode change

### ISSUE THREAD

**Issue by jpalus** [swaywm/sway#7582]
First off I want to be completely clear I don't know where the issue is but had to start somewhere and I believe expertise of `sway` maintainers will help direct this report in proper direction. This might as well be `wlroots`, `Mesa`, `kernel` or me if I did something really stupid.

- **Sway Version:**
  - 1.8.1

- **Debug Log:**
  - https://gist.github.com/jpalus/3d7deb98a6cca2ba178ad62a8125815b

- **Configuration File:**
  - not relevant I believe, log is with config having just two bindings -- for spawning terminal and quitting

- **Description:**
  On my Pinebook Pro (`panfrost` Mesa driver) cycling from output mode on external display `2560x1440` -> `1920x1080` -> `2560x1440` reduces "available memory" (as reported by `free`) by 40-50MB. Doing this in a loop eventually exhaust whole memory and freezes machine. Quitting sway at any point reclaims whole memory. No process grows in regards to memory usage so it looks like it's a kernel level memory buffer that gets allocated each time but never gets freed. Here's a `strace` log from one of such mode change cycles: https://gist.github.com/jpalus/04e09194a856438343d7703b59ba5aed

**Comment by emersion** [comment]
Would probably help understand the root cause to run under ASan and exit after a few mode switches.

**Comment by jpalus** [comment]
Turned out to be `Mesa` driver issue fixed by https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/23746
