### ISSUE TITLE
Some apps takes too long to start

### ISSUE THREAD

**Issue by sukhmancs** [swaywm/sway#7600]
- **Sway Version:**
  - `sway version 1.8.1`

- **Debug Log:**
  - https://gist.github.com/sukhmancs/2b185ad84544e17fe987f94109915c8a

- **Configuration File:**
  - Full configuration file: https://gist.github.com/sukhmancs/9fbc68a80847b1c2c980760d3eafa730

- **Description:**
  - **System:**
       - 6.1.29-1-lts (Arch Linux) 
  - The solution provided in #5732 did not work for me.
  - Alacritty and other applications like Firefox and Gnome files take a long time to start, around 20-30 seconds.
  - Adding `exec dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY SWAYSOCK` to the config file did not solve the problem.
  - Setting the environment variable wayland-0 to wayland-1 did not work either.
  - I tried using the latest Linux kernel, but the problem persists.

**Comment by taha-ghadirian** [comment]
Same as my issue #7594 

This problem happened after updating to Linux kernel `6.3.2-arch1-1`. 
Can you please give say what distro you are using?

**Comment by taha-ghadirian** [comment]
Arch Linux has just completed it's migration from SVN to Git, 
Here is the news page in official Arch Linux website: https://archlinux.org/news/git-migration-completed/

Please update your pacman and pacman configuration file, then update whole system. 
It can fix problem.

**Comment by sukhmancs** [comment]
`pkgctl repo clone linux` gives me this error:
```
Cloning into 'linux'...
git@gitlab.archlinux.org: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
==> ERROR: failed to clone linux
```

**Comment by sukhmancs** [comment]
> Same as my issue #7594
> 
> This problem happened after updating to Linux kernel `6.3.2-arch1-1`. Can you please say which distro, kernel, and Desktop Manager you are using?
> 
> I think there is a conflict between kernel modules and sway.

I do not think so because I am using linux-lts kernal.

**Comment by christian-heusel** [comment]
Do you have `xdg-desktop-portal-gnome` installed by chance? There is a known bug for this:
https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/issues/74 

I solved the slow startup by uninstalling the program, but that may not be the ideal solution ^^

Also regarding your comment https://github.com/swaywm/sway/issues/7600#issuecomment-1556261938:
Updating is still done via `pacman -Syu`, no need to use `pkgctl` here

**Comment by sukhmancs** [comment]
> Do you have `xdg-desktop-portal-gnome` installed by chance? There is a known bug for this: https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/issues/74
> 
> I solved the slow startup by uninstalling the program, but that may not be the ideal solution

Hey, thanks for your help! After upgrading, I had some trouble with my system, but I fixed it by uninstalling `xdg-desktop-portal-gnome`. I'm unsure what caused the issue, but I'm glad it's resolved now. Thanks again for your assistance!

**Comment by sukhmancs** [comment]
I'm facing the same problem again, but this time I'm using sway on NixOS (version 23.05.2573.61676e4dcfee (Stoat)). I've verified that xdg-desktop-portal-gnome is not installed. Here are the commands I used to search for that package: nix-env -q xdg-desktop-portal-gnome and nix-env -q --profile /nix/var/nix/profiles/system --drv-path /run/current-system/sw/bin/gnome-session.

**NixOS: 23.05.2573.61676e4dcfee (Stoat)**
**Linux Kernal: 6.1.43**

**Comment by emersion** [comment]
This is not a Sway bug. This is an issue with the applications.

**Comment by sukhmancs** [comment]
But i did not find that application installed anywhere else. I even tried using plasma after deleting whole gnome desktop environment but the problem persists.

**Comment by expenses** [comment]
I'm also having this issue, especially (only?) with GPU-based terminals such as kitty, alacritty and rio. I've attached a strace of what alacritty was doing in the several seconds between starting and actually rendering anything (which is when it only emits `clock_nanosleep`s).

[alacritty_strace.zip](https://github.com/swaywm/sway/files/12567224/alacritty_strace.zip)

**Comment by expenses** [comment]
> I'm also having this issue, especially (only?) with GPU-based terminals such as kitty, alacritty and rio. I've attached a strace of what alacritty was doing in the several seconds between starting and actually rendering anything (which is when it only emits `clock_nanosleep`s).
> 
> [alacritty_strace.zip](https://github.com/swaywm/sway/files/12567224/alacritty_strace.zip)

I looked through the strace more and I saw that it was trying to access a bunch of nvidia files/drivers that I had installed while on a laptop with an intel GPU (I use an external GPU occasionally). I removed the `nvidia-utils`, `egl-wayland` and `eglexternalplatform` arch linux packages and that solved the slowness for me.

**Comment by burein-ita** [comment]
> I removed the `nvidia-utils`, `egl-wayland` and `eglexternalplatform` arch linux packages and that solved the slowness for me.

Another option is setting the following environment variable BEFORE launching sway:

`__EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/50_mesa.json`

Source: [Archwiki](https://wiki.archlinux.org/title/Wayland#Avoid_loading_NVIDIA_modules)
