### ISSUE TITLE
Part of XWayland window is unclickable with mixed resolution multimonitor setup.

### ISSUE THREAD

**Issue by geekylthyosaur** [swaywm/sway#7604]
- **Sway Version:** `sway version 1.8.1`

- **Debug Log:** [pastebin.com](https://pastebin.com/MG5KdH0j)

- **Configuration File:** [pastebin.com](https://pastebin.com/UJDhrtJm) 
the part that matters:
```
output eDP-1 {
    resolution 1366x768 
    position 0,0
}
output HDMI-A-1 {
    resolution 1920x1080 position 1366,-312
}
```

- **Description:**

As you can see from part of my config file, I have a laptop with a built-in 1366x768 display and an external 1920x1080 display. On XWayland windows on the external display (tested with XTerm and VSCode), clicks on the app window located in the top 312 pixels of the display correspond to clicks that are 312 pixels from the top of the display, and clicks in other part work as expected.

All Wayland native windows (including VSCode (`--ozone-platform=wayland`)) work as expected.

The issue is not present when replacing the `resolution 1920x1080 position 1366,-312` with the `resolution 1920x1080 position 1366,0`.

**Comment by smlx** [comment]
https://github.com/swaywm/sway/wiki#mouse-events-clicking-scrolling-arent-working-on-some-of-my-workspaces

**Comment by geekylthyosaur** [comment]
Actually it can be fixed with math.

Change
```
output eDP-1 {
    resolution 1366x768 position 0,0
}
output HDMI-A-1 {
    resolution 1920x1080 position 1366,-312
}
```
to
```
output eDP-1 {
    resolution 1366x768 position 0,312
}
output HDMI-A-1 {
    resolution 1920x1080 position 1366,0
}
```
