### ISSUE TITLE
segmentation fault on launch, using vulkan renderer

### ISSUE THREAD

**Issue by haxibami** [swaywm/sway#7611]
### Please fill out the following:
- **Sway Version:**
  - `sway version 1.8.1`

- **Debug Log:**
  - `WLR_RENDERER=vulkan /usr/bin/sway -d -V -c /etc/sway/config 2> sway.log`
  - [gist](https://gist.github.com/haxibami/03fb90cb51041ce740b578f12d93a017)

- **Configuration File:**
  - default config file (`/etc/sway/config` on Arch Linux)

- **Stack Trace:**
  - [gist](https://gist.github.com/haxibami/48dce0dd5c7ef7127d614dd2102002f0)

- **Description:**
  - When I try to launch sway using vulkan renderer, it crashes with `segmantation fault` error.
  - This is probably a `vulkan-validation-layers` related bug.
  - There is [a similar issue](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5649) (already resolved, waiting for next release) on `KhronosGroup/Vulkan-ValidationLayers`.

**Comment by emersion** [comment]
Sounds like a radv bug.

**Comment by emersion** [comment]
My bad, this is exactly the Vulkan-ValidationLayer bug linked above. Closing.
