### ISSUE TITLE
Remapping right control key and context menu key

### ISSUE THREAD

**Issue by developer1105** [swaywm/sway#7617]
I would like to remap:

Right control => / (slash)
Shift + Right control => ? (question mark)
Context menu => Ctrl + W

The context menu key lies between AltGr and Right control, and is never used. Just in case I need to use it, I can use the Shift+F10 shortcut instead.

From what I have researched, it has to do with editing a file in /usr/share/X11/xkb/symbols and using wev, but I don't know how to go ahead from there.

**Comment by emersion** [comment]
Please see this wiki entry: https://github.com/swaywm/sway/wiki#load-a-modified-custom-xkb-keymap-xmodmap-equivalent
