### ISSUE TITLE
Sway does not send updated wlr_output_head information when enabling an output via IPC 

### ISSUE THREAD

**Issue by hw0lff** [swaywm/sway#7627]
- **Sway Version:** 1.8.1
- **Sway Debug Log:** [sway.log](https://gist.github.com/hw0lff/66e7b354030d94ee697c37c88e44c6c4)
- **Kanshi Version:** 1.3.1
- **Kanshi Debug Log:** [kanshi.log](https://gist.github.com/hw0lff/0972b03f5b28f268da4017341c4765ca)
- **Configuration File:** default configuration file

#### Monitoring the events:
0. `WAYLAND_DEBUG=1 kanshi -c /dev/null`

#### In a separate terminal:
0. `swaymsg output eDP-1 enable` (to have it at the end of my shell history)
1. `swaymsg output eDP-1 disable`
2. `swaymsg output eDP-1 enable`
3. `swaymsg output eDP-1 enable`

I waited several seconds between steps `[1;3]` to see the results of each step with a different timestamp.

### What happens
After step 1 at `[3197137.*]`: `kanshi` receives a `wl_registry.global_remove` and gets notified about the _disabled_ `wlr_output_head`.
After step 2 at `[3209312.*]`: `kanshi` receives only a `wlr_output_manager.done` and a `wl_registry.global` event.
After step 3 at `[3221293.*]`: `kanshi` gets notified about the _enabled_ `wlr_output_head`; followed by more `wlr_output_head` events.

### What I expect to happen
When enabling an output via `swaymsg output eDP-1 enable`, `kanshi` should receive the `wl_registry` event together with all the `wlr_output_head` events.
Enabling an output should exhibit inverse behavior to disabling an output (order of events does not matter).
Running `wlr-randr --output eDP-1 --on` exhibits the desired behavior.
Using `swaymsg` should not be different from the `wlr-randr` command.

**Comment by Raenthnx** [comment]
Similar issue here on a laptop.
Updated sway from 1.8.0 to 1.8.1
Since then, sway does not update output when unplugging hdmi.

**What is expect:**
When I unplug hdmi, i expect to go back to one screen on my workstation, and `swaymsg -t get_outputs` shows one output.

**What happens:**
i have a "phantom" output (I can move mouse, windows, workspaces to it) and `swaymsg -t get_outputs` still shows the output I unplugged hdmi cable from.

Will try to downgrade sway.

**Comment by Nefsen402** [comment]
I am unable to reproduce the issue on master. Kanshi using WAYLAND_DEBUG=1 is properly receiving the events through zwlr_output_head_v1

**Comment by SteavenGamerYT** [comment]
can this be moved to 1.11 and sway 1.10 get released? i need explicit sync

**Comment by emersion** [comment]
Please re-open if you can still reproduce on master.
