### ISSUE TITLE
Slow startup on GTK apps

### ISSUE THREAD

**Issue by SafinWasi** [swaywm/sway#7630]
- **Sway Version:**
`sway version 1.8.1`

- **Debug Log:**
https://pastebin.com/ZYQKzZ8D

- **Configuration File:**
https://gist.github.com/SafinWasi/3a1c73b7a061f23e7834319efa90d434

- **Stack Trace:**
N/A

- **Description:**
  - Host is Arch Linux x64 `6.3.6-arch1-1` running AMD 6600XT
  - Apps are suffering from a slow startup despite not having `xdg-desktop-portal-gtk` or `-gnome` installed.
  - The first start takes about 15 seconds for even wofi and waybar. Other apps include firefox and chromium. After starting once apps start instantaneously
  - I have KDE Plasma installed alongside Sway, along with`xdg-desktop-portal`, `xdg-desktop-portal-kde` and `xdg-desktop-portal-wlr`
  - I have SDDM installed; however, this issue persists even when starting sway from TTY
  - The issue persists only on boot. Exiting sway and logging back in does not cause the issue.
  - I have tried removing all portals, and all systemd import commands mentioned in the wiki and closed issues.

**Comment by colorsakura** [comment]
maybe you shoud try this: https://github.com/swaywm/sway/wiki#gtk-applications-take-20-seconds-to-start
