### ISSUE TITLE
Laptop screen remains black post commit 65b1a6964c81efd84832c80ec9fc0273c8975225

### ISSUE THREAD

**Issue by RobertMueller2** [swaywm/sway#7632]
- **Sway Version:** sway version 1.9-dev-65b1a696 (Jun 10 2023, branch 'HEAD')
- **Debug Log:**
[Debug log with issue](https://gist.github.com/RobertMueller2/b66cd0be35a6df35e1ebd138babd85f7#file-sway-debug-ko-65b1a696-log)  
[Debug log without issue](https://gist.github.com/RobertMueller2/b66cd0be35a6df35e1ebd138babd85f7#file-sway-debug-ok-f3b8c9fe-log)

- **Configuration File:**
[config file - Debian default config](https://gist.github.com/RobertMueller2/b66cd0be35a6df35e1ebd138babd85f7#file-config)

- **Description:**
  - wlroots has commit 36376e2ddf0d16baae37e6b733f0baf53f82ebb7
  - Start sway with commit 65b1a6964c81efd84832c80ec9fc0273c8975225
  - Internal laptop screen remains black
  - Using commit f3b8c9feeed9f79fc8f06e7f1dcfaadde522ce90, the issue does not occur

- Additional remarks:
  - after the issue repro, I had to issue SIGTERM because I can't see if I'm clicking anything ;)
  - This part is not present with the "working" commit:

```
00:00:00.450 [DEBUG] [wlr] [backend/drm/atomic.c:72] connector eDP-1: Atomic commit failed: Invalid argument
00:00:00.450 [DEBUG] [wlr] [backend/drm/atomic.c:76] (Atomic commit flags: ATOMIC_TEST_ONLY)
```

**Comment by RobertMueller2** [comment]
Sorry, Copy+Paste mistake in the title. ;)

**Comment by GreyXor** [comment]
I have the same issue

**Comment by emersion** [comment]
Can you try this?

https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4189

**Comment by GreyXor** [comment]
> Can you try this?
> 
> https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4189

Fixed the issue for me, thanks

**Comment by RobertMueller2** [comment]
> Can you try this?
> 
> https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4189

That works, thanks. I guess this issue can stay open until the PR is merged?

**Comment by BBaoVanC** [comment]
Will this land in a release soon? I had to switch both wlroots and sway to the git versions to fix this issue

**Comment by emersion** [comment]
@BBaoVanC The bug this issue is about has not been included in a release (see the referenced commit).

Closing because the wlroots fix had been merged.
