### ISSUE TITLE
Black screen wait and then exit

### ISSUE THREAD

**Issue by berkaysaahn** [swaywm/sway#7635]
sway version 4.22 (2023-01-02)

[sway.log](https://github.com/swaywm/sway/files/11725417/sway.log)

when you start sway from terminal

"00:00:00.048 [wlr] [types/wlr_drm_lease_v1.c:715] No DRM backend supplied, failed to create wlr_drm_lease_v1_manager
00:00:00.052 [sway/config/output.c:817] execvp failed: No such file or directory"

it gives these errors but it opens. When I try to log in from the login screen, after waiting for a while on a black screen, it sends me back to the login page. Please help.

**Comment by emersion** [comment]
Duplicate of https://github.com/swaywm/sway/issues/7632

**Comment by emersion** [comment]
Bleh, is not.

There is no Sway version 4.22.

**Comment by berkaysaahn** [comment]
I downloaded it using pacman and when I run swaymsg -t get_version it gives this
