### ISSUE TITLE
quarterly releases

### ISSUE THREAD

**Issue by normalisnormal** [swaywm/sway#7658]
- Description:

Distros update their package repos following version changes. It'd be great if Sway can get at least quarterly releases since it's been in fairly intense development. Same goes with wlroots too. Even Mesa had a major release meanwhile. Please honor us the binary plebs with the gift of up-to-date software

**Comment by bl4ckb0ne** [comment]
Keep in mind that sway is community managed and we're maintaining it on our free time. We don't stick to a release calendar, we just release things when we feel we're ready.
