### ISSUE TITLE
xkb_layout and xkb_switch_layout not working

### ISSUE THREAD

**Issue by Luab** [swaywm/sway#7660]
### Please fill out the following:
- **Sway Version:**
  - sway version 1.8.1

- **Debug Log:**
  [debug log](https://gist.github.com/Luab/6dd1f03551ccb99d59d15d14acbb065f)

- **Configuration File:**
  Relevant config section: 
  ```
   input "type:keyboard" { 
    xkb_layout "us,de" 
    xkb_options grp:win_space_toggle 
   } 

- **Description:**
 Layout switching stopped working after update. 
 Running `swaymsg input 'type:keyboard' xkb_switch_layout next` does not switch the layout. 
 Setting it manually with `swaymsg input 'type:keyboard' xkb_layout de` works. 
 Running `swaymsg input 'type:keyboard' xkb_layout us,de` or `swaymsg input 'type:keyboard' xkb_layout "us,de"` fails with `Error: Unknown/invalid command 'de'`

**Comment by emersion** [comment]
Can you reproduce with master?

**Comment by Luab** [comment]
@emersion yep, same. [Here is debug log](https://gist.github.com/Luab/2c6b666417813542803941a874dc8efb). 
`swaymsg input 'type:keyboard' xkb_layout de` works, `swaymsg input type:keyboard xkb_switch_layout next` does not.

**Comment by Luab** [comment]
Somehow fixed itself without me doing anything.
