### ISSUE TITLE
Unlock programmatically

### ISSUE THREAD

**Issue by veyxov** [swaywm/sway#7665]
# Problem
How to unlock swaylock using shell commands?

# What I tried
`killall swaylock` and `sudo killall swaylock` doesn't work.

# Use case
Remotely unlock, for example from phone using kde-connect

Thanks.

**Comment by emersion** [comment]
Moving to Sway, because an IPC command can be added for this.

**Comment by emersion** [comment]
BTW, this exists: https://git.sr.ht/~emersion/sesame

**Comment by mhmdanas** [comment]
From `man swaylock`:
```
SIGNALS
       SIGUSR1
           Unlock the screen and exit.
```

Isn't that just what you want?

**Comment by veyxov** [comment]
Yes, thank you.

For some reason it disconnects the monitor, resulting a black screen.
It's something about my configuration, I think.
I'm using sway, kanshi, swaylock-effects

**Comment by mhmdanas** [comment]
How are you sending the signal to the swaylock process?

**Comment by emersion** [comment]
Shorter: `pkill -USR1 swaylock`
