### ISSUE TITLE
Firefox and other applications do not register clicks or scrolling when positioned with a negative number.

### ISSUE THREAD

**Issue by cicilapetitesorciere** [swaywm/sway#7667]
sway version 1.8.1

I have a three-monitor setup, and since I installed sway several weeks ago, several applications on my leftmost monitor including Firefox weren't registering clicks or scrolls from the mouse. The mouse showed up fine, and I was able to use it to change workspaces and interact with Sway itself, but the applications themselves did not seem to be aware of its existence. It was only just now that it dawned on me where the issue originated. I had my monitors configured as following:

```
output HDMI-A-1 pos -360 350
output HDMI-A-2 pos 0 0
output DP-3 pos 1920 100
```
When I set this, Sway accepted it and everything seemed to work fine, so I left it and didn't think much about it,not noticing that my use of negative numbers would cause problems. Changing it to 

```
output HDMI-A-1 pos 0 350
output HDMI-A-2 pos 1360 0
output DP-3 pos 3280 100
```

fixed the issue for me, however I think it is important to prevent other users from accidentally stumbling onto the same issue, because as much as the source of the issue seems obvious now, the connection was not obvious in practice. 

I think the simplest fix would be to just disallow negative numbers in output positioning.

**Comment by emersion** [comment]
This is a known Xwayland bug. See https://github.com/swaywm/sway/issues/3060 and many others.
