### ISSUE TITLE
for_window [title="..."] selection does not work

### ISSUE THREAD

**Issue by yagarea** [swaywm/sway#7673]
**Sway Version:** sway version 1.8.1  
**Configuration:**
```
for_window [title="KeePassXC - Browser Access Request"] floating enable border normal, move position center, focus
```

**Description:**  
This does not make keepassxc dialog float even if it should. Sway displays it like regular window spread over all screen.

```
...
    #8: workspace "1"
      #28: con "(null)"
        #29: con "KeePassXC - Browser Access Request" (xdg_shell, pid: 1376, app_id: "org.keepassxc.KeePassXC")
...
```

**Comment by iguanajuice** [comment]
I think u forgot a comma/semicolon lol

`for_window [title="KeePassXC - Browser Access Request"] floating enable, border normal, move position center, focus`
