### ISSUE TITLE
seat_idle_notify_activity uses a wrong input source mask

### ISSUE THREAD

**Issue by kupospelov** [swaywm/sway#7674]
**Sway Version:**
sway version 1.9-dev-6c234d01 (Jul 14 2023, branch 'master')

**Configuration File:**
```
seat * {
	idle_wake keyboard
}
```
**Description:**
As per the documentation:
- `idle_wake` sets the set of input event sources which can wake the seat from its idle state.
- `idle_inhibit` sets the set of input event sources which can prevent the seat from becoming idle.

The configuration above should only affect which input devices can *wake* the seat. The code below though does not seem to work with the new `ext-idle-notify-v1` protocol and uses the same mask regardless of whether the seat is idle.

```c
uint32_t mask = seat->idle_inhibit_sources;
struct wlr_idle_timeout *timeout;
int ntimers = 0, nidle = 0;
wl_list_for_each(timeout, &server.idle->idle_timers, link) {
	++ntimers;
	if (timeout->idle_state) {
		++nidle;
	}
}
if (nidle == ntimers) {
	mask = seat->idle_wake_sources;
}
if ((source & mask) > 0) {
	wlr_idle_notify_activity(server.idle, seat->wlr_seat);
	wlr_idle_notifier_v1_notify_activity(server.idle_notifier_v1, seat->wlr_seat);
}
```

Note that both `nidle` and `ntimers` are set to 0 when using `ext-idle-notify-v1`. This always sets the mask to `idle_wake_sources`.

**Comment by emersion** [comment]
Related: https://github.com/swaywm/sway/pull/7669

**Comment by kupospelov** [comment]
> It never worked properly with the new idle-notify-v1 protocol and no-one noticed.

Well, that is no longer true :smile: 

 #7669 makes sense though. I only used `idle_wake` to disable mouse when the system is idle, but I can do the same using `swaymsg`.
