### ISSUE TITLE
QuteBrowser like "clicking" on opened apps only with keyboard

### ISSUE THREAD

**Issue by holotrack** [swaywm/sway#7685]
### Please read the following before submitting:
- We are not accepting any new window management features unless they get implemented by i3.

Didn't hear i3 have it but still I think it can be interesting option if possible at all

### Please fill out the following:
Is it possible to implement such shortcuts for clicking like it is eg in qutebrowser? So instead of mouse you can just use some shortcut and then additional shortcuts are appearing all over workspace apps and you can chose from keyboard what you want to click. Screenshot to show what im talking about:

![image](https://github.com/swaywm/sway/assets/100580892/096b4c29-f9c7-4ae6-88ab-f2a72571b914)

So same thing like on image above but for workspace and any app started on that workspace.

**Comment by emersion** [comment]
Wayland only deals with pixel buffers. There is no information about where the links may appear. In other words, this isn't a feature Sway could implement, applications need to provide it.
