### ISSUE TITLE
no drm backend supplied

### ISSUE THREAD

**Issue by evanescente-ondine** [swaywm/sway#7688]
I boot from tty, and every time I boot I get this message:
```
drm@drm-4236wv5 ~ [1]> sway -C
00:00:00.057 [wlr] [types/wlr_drm_lease_v1.c:715] No DRM backend supplied, failed to create wlr_drm_lease_v1_manager
drm@drm-4236wv5 ~> sway -v
sway version 1.8.1
```

machine: `Linux drm-4236wv5 6.4.5-arch1-1 #1 SMP PREEMPT_DYNAMIC Sun, 23 Jul 2023 14:33:22 +0000 x86_64 GNU/Linux`

**Comment by emersion** [comment]
This is harmless, the error message should probably get degraded to DEBUG or something.

**Comment by evanescente-ondine** [comment]
Yeah I read it's harmless. but still causing that red bar each time.
annoying
I'll just ignore it, ok.

Le mer. 26 juil. 2023 à 09:57, Simon Ser ***@***.***> a
écrit :

**Comment by bl4ckb0ne** [comment]
Closed in https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4302
