### ISSUE TITLE
Transform:90=Transform:270 , Transform:270=Transform:90?

### ISSUE THREAD

**Issue by exkc** [swaywm/sway#7701]
This a very odd way bug . I seted DP-2's Transform to 90 n dvi-i-1's Transform to 270 vis some third party tools like wdisplay , wlays , wlr-randrs.Then i run `swaymsg -t get_outputs` and it said DP-2 's Transform is 270 n dvi-i-1's Transform is 90.

Sway version : 1.8.1
GPU:muit-gpu(1xnouveau,1xamdgpu,1xradeon)

dvi-i-1 n DP-2 r from my nouveau

**Comment by emersion** [comment]
Yes, this is expected. In a previous version we mixed up these two, and we fixed our mistake without breaking the configuration file.
