### ISSUE TITLE
Why sway still does not support dynamic tiling.

### ISSUE THREAD

**Issue by MubinMuhammad** [swaywm/sway#7705]
It is a long time, and sway still does not support dynamic tiling. It's annoying to work with manual tiling and I don't think it's hard to implement. You just have to check `if (window_count % 2 == 0)` or not. If it is zero that means window count is even and we need to put the next window to the bottom of the current one. And if it is not equal to 0 that means the window count is odd and we have to create the window horizontally.

I don't think a manual tiling is needed today.
I hope that the sway team would be kind enough to implement it.

Thanks.

**Comment by emersion** [comment]
Sorry, we're not accepting any new window management features anymore. See https://github.com/swaywm/sway/blob/master/CONTRIBUTING.md#scope-of-future-changes-to-sway

What you describe should be achievable with a script.
