### ISSUE TITLE
The border is missing around unfocused floating windows

### ISSUE THREAD

**Issue by Helenah2020** [swaywm/sway#7706]
- **Description:**
  - Configuration from i3 was copied over and the `client.<class>` lines were not changed. The border around unfocused floating windows that I configured i3 to have seems to be missing in Sway. I have read documentation about Sway's `client.<class>` lines and it seems to be the same as that of i3.
- **Configuration:**
```
client.focused          #d79921 #d79921 #1d2021 #b16286 #d79921
client.focused_inactive #d79921 #1d2021 #d79921 #b16286 #d79921
client.unfocused        #1d2021 #282828 #d79921 #b16286 #282828
client.urgent           #cc241d #cc241d #ffffff #cc241d #cc241d
```
- **Expected behaviour:**
![18QG3iA](https://github.com/swaywm/sway/assets/60333516/fab54156-b6ac-4685-abca-331651a36905)
- **Actual behaviour:**
![2023-08-13-1830](https://github.com/swaywm/sway/assets/60333516/da4f9b25-2a0a-43a7-8942-f0f7154f163f)

**Comment by fluix-dev** [comment]
Can you provide your (or even better, a minimal) configuration file?

**Comment by Helenah2020** [comment]
> Can you provide your (or even better, a minimal) configuration file?

Yes, sorry about that, I have included it into the issue.

**Comment by fluix-dev** [comment]
Your config has:
```
client.unfocused        #1d2021 #282828 #d79921 #b16286 #282828
```

which means the border around the titlebars is `#1d2021` and around the view itself is `#282828`  which are both gray, not the yellow/orange `#d79921` you want? Shouldn't it be:

```
client.unfocused        #d79921 #282828 #d79921 #b16286 #d79921
```

**Comment by Helenah2020** [comment]
> Your config has:
> 
> ```
> client.unfocused        #1d2021 #282828 #d79921 #b16286 #282828
> ```
> 
> which means the border around the titlebars is `#1d2021` and around the view itself is `#282828` which are both gray, not the yellow/orange `#d79921` you want? Shouldn't it be:
> 
> ```
> client.unfocused        #d79921 #282828 #d79921 #b16286 #d79921
> ```
> 
> **Edit**: I'm not sure what i3 is doing; maybe it doesn't think they're unfocused or something, but whatever it is seems odd.

The ordering of the hex codes is one thing I checked and I did not scan read either, I did a proper comparison, however what you suggested seems to work, I'm not sure whether to close this issue or not yet. I didn't however check the i3 and Sway source code, maybe you did.

**Comment by fluix-dev** [comment]
> The ordering of the hex codes is one thing I checked and I did not scan read either, I did a proper comparison, however what you suggested seems to work, I'm not sure whether to close this issue or not yet. I didn't however check the i3 and Sway source code, maybe you did.

I didn't check anything either, I'm just referencing the manpage, sway(5).

**Comment by fluix-dev** [comment]
> I'm not sure whether to close this issue or not yet

Based on your config, our behavior seems correct. If you can figure out what i3 is doing differently that certainly wouldn't hurt.

**Comment by Helenah2020** [comment]
Upon further analysis, it seems I missed out the fact that this is probably an i3 bug, I do apologise for opening an issue. I will let the i3 folks know.
