### ISSUE TITLE
Space between swaybar and windows

### ISSUE THREAD

**Issue by jkobezda** [swaywm/sway#771]
See screenshot: http://imgur.com/a/IVhAD

Bisected to here:

```
d3752b41405b5572d0ba488aaf969f308e06968a is the first bad commit
commit d3752b41405b5572d0ba488aaf969f308e06968a
Author: David Eklov <david.eklov@gmail.com>
Date:   Mon Jul 4 17:03:55 2016 -0500

    swaybar: Make swaybar a shell surface

:040000 040000 916d52a5a6a03a2a6e99a6c4f3723c92d7c865ec ec0f1d90d309d526316e4ea71c49b24b74ca3ac1 M  swaybar
```

**Comment by jkobezda** [comment]
Config file: http://ix.io/15sN

**Comment by jkobezda** [comment]
Config file: http://ix.io/15sN

**Comment by thejan2009** [comment]
Those are actually 2 swaybars, because you have 2 bar{} sections in your config. If you merge them, your issue will disappear.

There is another bug actually: the button for workspace 3: Term is smaller than the others.
