### ISSUE TITLE
support fractional scaling by default?

### ISSUE THREAD

**Issue by KairuiLiu** [swaywm/sway#7710]
### Please fill out the following:
- **Sway Version:**
  - sway version 1.8.1-075fceb (Aug  9 2023, branch 'master')

- **Description:**

I want to confirm that sway currently supports fractional scaling by default? sway sets my screen to 200% by default, I pass

output eDP-1 resolution 2880x1800 position 0 0 scale 1.75

Set the screen to 175%, but I don’t know if it’s my hallucination or what, I feel that the text is a little blurry under 175% zoom, is it because I set it wrong?

**Comment by emersion** [comment]
Sorry, this issue tracker is not for questions. Use IRC instead.
