### ISSUE TITLE
XWayland apps and games blurry

### ISSUE THREAD

**Issue by h0tc0d3** [swaywm/sway#7715]
Since all past hidpi bugs have been closed, a new request has been opened.

**Sway Version:** 1.9-dev-bb91b7f5fa7f (Aug 16 2023, branch 'master')
Apps and games are blurry with fractional scale. 
gamescope solves the problem in full screen games.
```
gamescope -f -W ${screen_width} -H ${screen_height} -r ${screen_refresh_rate} ${game_path}
```

Related issues: 
 - https://github.com/swaywm/sway/issues/7709
 - https://intellij-support.jetbrains.com/hc/en-us/articles/4403794663570-Blurry-text-when-using-Sway-or-fractional-scaling-on-Wayland
 - https://youtrack.jetbrains.com/issue/IDEA-218458/Blurry-fonts-on-Wayland-fractional-scaling

**Comment by emersion** [comment]
X11 apps will get blurry, yes. This is expected.

**Comment by h0tc0d3** [comment]
@emersion so you don't care about the problem that you're closing it? It is not normal! 
KDE Plasma doesn't have this problem. I wanted to switch to sway for many years, but this problem persists on any monitors. Most screens now have a resolution other than 1080p, and text and programs look too small. wayland garbage can still not be completed to normal use.
It is not clear why fractional scaling was adopted if it does not work.
