### ISSUE TITLE
`meson build/` step fails on Debian in master branch, while v1.8 compiles fine

### ISSUE THREAD

**Issue by denppa** [swaywm/sway#7719]
# System
Debian Bookworm

# Description
All the dependencies necessary for v1.8 to compile has been installed, and v1.8 compiled successfully. While trying to compile the current HEAD (commit `bf44690ee`) during the `meson build/` phase, this error message pops up:
```
protocols/meson.build:4:0: ERROR: Could not get an internal variable and no default provided for <InternalDependency null: True>
```

Not sure what this means, but it doesn't sound like a dependency problem. Perhaps something is wrong with the `meson.build` file?

**Comment by bl4ckb0ne** [comment]
Sounds like `wayland-protocols` was not found. Do you have the right version?

**Comment by emersion** [comment]
Are you running with a Wayland subproject?

Can you try updating this line with `get_variable('wayland_scanner')`?

https://github.com/swaywm/sway/blob/bf44690ee8ce8438ffb1a84fbe6e8dbb6a851c04/protocols/meson.build#L5

**Comment by denppa** [comment]
@bl4ckb0ne  and @emersion I suspect that `wayland-protocols` is not found because it did not compile correctly due to a missing dependency called `libdisplay-info`.

So I cloned the project into the `subprojects` folder, re-ran `meson build/`, and was greeted with this message:
```bash
wlroots| Dependency wayland-protocols found: YES 1.32 (overridden)
wlroots| Dependency wayland-scanner found: YES 1.22.90 (overridden)
wlroots| Program wayland-scanner found: YES (overridden)
wlroots| Has header "linux/dma-buf.h" : YES
wlroots| Run-time dependency egl found: YES 1.5
wlroots| Run-time dependency gbm found: YES 22.3.6
wlroots| Run-time dependency glesv2 found: YES 3.2
wlroots| Program ./embed.sh found: YES (/home/pilot/rsync/git/sway/subprojects/wlroots/render/gles2/shaders/./embed.sh)
wlroots| Run-time dependency vulkan found: YES 1.3.239
wlroots| Check usable header "vulkan/vulkan.h" with dependency vulkan: YES
wlroots| Program glslang glslangValidator found: NO
wlroots| Dependency pixman-1 found: YES 0.42.2 (cached)
wlroots| Dependency gbm found: YES 22.3.6 (cached)
wlroots| Checking for function "gbm_bo_get_fd_for_plane" with dependency gbm: YES
wlroots| Run-time dependency libudev found: YES 252
wlroots| Run-time dependency libseat found: YES 0.7.0
wlroots| Found pkg-config: /usr/bin/pkg-config (1.8.1)
wlroots| Build-time dependency hwdata found: YES 0.368
wlroots| Run-time dependency libdisplay-info found: NO (tried pkgconfig and cmake)
wlroots| Looking for a fallback subproject for the dependency libdisplay-info

Executing subproject wlroots:libdisplay-info

libdisplay-info| Project name: libdisplay-info
libdisplay-info| Project version: 0.0.0
libdisplay-info| C compiler for the host machine: cc (gcc 12.2.0 "cc (Debian 12.2.0-14) 12.2.0")
libdisplay-info| C linker for the host machine: cc ld.bfd 2.40
libdisplay-info| Program tool/gen-search-table.py found: YES (/home/pilot/rsync/git/sway/subprojects/libdisplay-info/tool/gen-search-table.py)
libdisplay-info| Library m found: YES
libdisplay-info| Compiler for C supports arguments -Wundef: YES (cached)
libdisplay-info| Compiler for C supports arguments -Wmissing-prototypes: YES (cached)
libdisplay-info| Compiler for C supports arguments -Walloca: YES (cached)
libdisplay-info| Compiler for C supports arguments -Wdeclaration-after-statement: YES
libdisplay-info| Compiler for C supports arguments -Wconversion: YES
libdisplay-info| Compiler for C supports arguments -Wno-unused-parameter: YES (cached)
libdisplay-info| Compiler for C supports arguments -Wno-missing-field-initializers: YES (cached)
libdisplay-info| Compiler for C supports arguments -Werror=implicit: YES
libdisplay-info| Build targets in project: 144
libdisplay-info| Subproject libdisplay-info finished.

wlroots| WARNING: Subproject 'libdisplay-info' did not override 'libdisplay-info' dependency and no variable name specified
```

Which file should I edit to allow `libdisplay-info` to be overriden and used as a dependency by `wayland-protocols`?

Thank you for the response.

**Comment by denppa** [comment]
@bl4ckb0ne Thank you so much for linking to the proper repo, now the `libdisplay-info` dependency is found and included. Though the configuration still failed, so I edited the `protocol`'s `build.meson` as emersion mentioned above.

> Are you running with a Wayland subproject?
> 
> Can you try updating this line with `get_variable('wayland_scanner')`?
> 
> https://github.com/swaywm/sway/blob/bf44690ee8ce8438ffb1a84fbe6e8dbb6a851c04/protocols/meson.build#L5

Thank you so much @emersion , this is the change I need to properly configure `meson`. Maybe this should be a PR?

**Comment by emersion** [comment]
Feel free to open a PR.
