### ISSUE TITLE
Resolution for UltraHD monitor fails

### ISSUE THREAD

**Issue by KlapenHz** [swaywm/sway#7721]
Hi, I have problem with display screen on ultrawide monitor 5120x1440. Monitor is turning off.Lower resolutions work well. 

- **Sway Version:**
```swaymsg -t get_version
sway version 1.8.1```
```
```
uname -r
6.4.12-arch1-1
```
```
cat /proc/cpuinfo | grep model\ name | head -n1
model name	: Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
```
```
swaymsg -t get_outputs
Output eDP-1 'BOE 0x097D Unknown' (focused)
  Current mode: 1920x1080 @ 60.004 Hz
  Position: 0,0
  Scale factor: 1.000000
  Scale filter: nearest
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 1
  Max render time: off
  Adaptive sync: disabled
  Available modes:
    1920x1080 @ 60.004 Hz
    1920x1080 @ 48.004 Hz

Output DP-1 'Dell Inc. Dell U4919DW H1WNXH3'
  Current mode: 3840x1080 @ 59.968 Hz
  Position: 1920,0
  Scale factor: 1.000000
  Scale filter: nearest
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 2
  Max render time: off
  Adaptive sync: disabled
  Available modes:
    5120x1440 @ 59.977 Hz
    3840x1080 @ 59.968 Hz
    5120x1440 @ 29.978 Hz
    2560x1080 @ 60.000 Hz (64:27)
    2560x1080 @ 59.940 Hz (64:27)
    2560x1080 @ 59.978 Hz
    1920x1080 @ 60.000 Hz
    1920x1080 @ 60.000 Hz (16:9)
    1920x1080 @ 59.940 Hz (16:9)
    1920x1080 @ 50.000 Hz (16:9)
    1600x1200 @ 60.000 Hz
    1280x1024 @ 75.025 Hz
    1280x1024 @ 60.020 Hz
    1280x800 @ 59.810 Hz
    1152x864 @ 75.000 Hz
    1280x720 @ 60.000 Hz (16:9)
    1280x720 @ 59.940 Hz (16:9)
    1280x720 @ 50.000 Hz (16:9)
    1024x768 @ 75.029 Hz
    1024x768 @ 60.004 Hz
    800x600 @ 75.000 Hz
    800x600 @ 60.317 Hz
    720x576 @ 50.000 Hz (16:9)
    720x480 @ 60.000 Hz (16:9)
    720x480 @ 60.000 Hz (4:3)
    720x480 @ 59.940 Hz (16:9)
    720x480 @ 59.940 Hz (4:3)
    640x480 @ 75.000 Hz
    640x480 @ 60.000 Hz (4:3)
    640x480 @ 59.940 Hz
    640x480 @ 59.940 Hz (4:3)
    720x400 @ 70.082 Hz
```

- **Debug Log:**
  - Run `sway -d 2> ~/sway.log` from a TTY and upload it to a pastebin, such as gist.github.com.
[sway.log](https://github.com/swaywm/sway/files/12452248/sway.log)
[dmesg.log](https://github.com/swaywm/sway/files/12452250/dmesg.log)

I have default configuration, clear installation on Arch. 
I only added output section:
```
output eDP-1 pos 0 0 res 1920x1080
output DP-1 {
    #mode 5120x1440
    mode 3840x1080
    pos 1920 0
}
```

**Comment by kennylevinsen** [comment]
> [75274.304903] i915 0000:00:02.0: [drm:skl_plane_check [i915]] requested Y/RGB source size 5120x1440 outside limits (min: 1x1 max: 4096x4096)

[Data from ARK for your CPU](https://ark.intel.com/content/www/us/en/ark/products/195436/intel-core-i5-10210u-processor-6m-cache-up-to-4-10-ghz.html):
>  Max Resolution (HDMI)‡ 4096 x 2304@24Hz
> Max Resolution (DP)‡ 4096 x 2304@60Hz
> Max Resolution (eDP - Integrated Flat Panel)‡ 4096 x 2304@60Hz

Just seems like you're asking for more than your GPU supports.

You also have:

> [75274.318096] i915 0000:00:02.0: [drm:skl_compute_wm [i915]] Requested display configuration exceeds system DDB limitations
> [75274.318194] i915 0000:00:02.0: [drm:skl_compute_wm [i915]] minimum required 242/216

Which you might be able to work around by running sway with `WLR_DRM_NO_MODIFIERS=1` set, or by disabling the built-in panel. That won't circumvent maximum resolution issues though.

**Comment by kennylevinsen** [comment]
```c
static int skl_plane_max_width(const struct drm_framebuffer *fb,
			       int color_plane,
			       unsigned int rotation)
{
	int cpp = fb->format->cpp[color_plane];

	switch (fb->modifier) {
	case DRM_FORMAT_MOD_LINEAR:
	case I915_FORMAT_MOD_X_TILED:
		/*
		 * Validated limit is 4k, but has 5k should
		 * work apart from the following features:
		 * - Ytile (already limited to 4k)
		 * - FP16 (already limited to 4k)
		 * - render compression (already limited to 4k)
		 * - KVMR sprite and cursor (don't care)
		 * - horizontal panning (TODO verify this)
		 * - pipe and plane scaling (TODO verify this)
		 */
		if (cpp == 8)
			return 4096;
		else
			return 5120;
	case I915_FORMAT_MOD_Y_TILED_CCS:
	case I915_FORMAT_MOD_Yf_TILED_CCS:
	case I915_FORMAT_MOD_Y_TILED_GEN12_MC_CCS:
		/* FIXME AUX plane? */
	case I915_FORMAT_MOD_Y_TILED:
	case I915_FORMAT_MOD_Yf_TILED:
		if (cpp == 8)
			return 2048;
		else
			return 4096;
	default:
		MISSING_CASE(fb->modifier);
		return 2048;
	}
}
```

Hmm, so you should be able to get 5120 through for LINEAR and X_TILED. Try with the NO_MODIFIERS thing.

**Comment by KlapenHz** [comment]
Hi, thank's for answer. This is very strange and suprising for me because I have on my laptop also Ubuntu (KDE), PopOs and NixOs (with Gnome) and all they support 5120x1440 and I don't have any problems with this resolution. 
Ok, could you tell me where I should put this (WLR_DRM_NO_MODIFIERS=1) paramather?

**Comment by kennylevinsen** [comment]
It is an environment variable that must be set before starting your compositor.

**Comment by KlapenHz** [comment]
Ok, thanks :)

**Comment by KlapenHz** [comment]
Currently I don't have sway installed, but I checked it on hyperland and it works. I will check it also on sway in the evening. But it also should work. Thanks a lot :)
