### ISSUE TITLE
Crash when launching some X11 apps in Xwayland

### ISSUE THREAD

**Issue by rhoot** [swaywm/sway#7722]
- **Sway Version:**
  - sway version 1.9-dev-bf44690e (Aug 28 2023, branch 'master')
  - wlroots 717ded9b (latest 'master' as of writing)

- **Debug Log:**
  - https://gist.github.com/rhoot/34d89f85ad8bc0502eb0bbf5d8601641

- **Configuration File:**
  - Using the default config

- **Stack Trace:**
  - https://gist.github.com/rhoot/60ae2033e6fc12040035a99794ed267e
  - This was with wlroots linked statically, which I only tried after linking it normally (using the `sway-git` and `wlroots-git` AUR packages) had crashed with the same call stack.

- **Description:**
  - Repro:
    1. Launch sway
    2. Launch an X11 app
    3. Sway crashes
  - It doesn't seem to happen with every X11 app. Discord and Steam both cause sway to crash, xev, xeyes, vkcube do not

**Comment by ppascher** [comment]
Hitting (probably) the same issue. I noticed when starting a headless sway session connectiong with vnc and starting steam.
bt full: http://0x0.st/H9DD.log
this is on current git of sway, wlroots, mesa and llvm. Tried with both xorg-xwayland 23.1.2 and 23.2.0

**Comment by Scrumplex** [comment]
Experiencing the same thing here.

This did not happen with Sway bf44690ee8ce8438ffb1a84fbe6e8dbb6a851c04 and wlroots `717ded9bb0191ea31bf4368be32e7a15fe1b8294`

But it does happen with Sway 4a2210577c7c4f84a99ca03386b8910d2f419ab6 and wlroots `7bf6c1fc6c824bb2e031d464000ae41c86c459e5`

As FDO GitLab is currently not available, it is hard to check if wlroots is the culprit here. I will try reverting the Sway commit to see if that fixes it

**Comment by Scrumplex** [comment]
Yep. It looks like bf44690ee8ce8438ffb1a84fbe6e8dbb6a851c04 is at fault here.

Related #7676

CC @Dudemanguy @rpigott

**Comment by ppascher** [comment]
Good find, thank you. Reverting sway to 4a2210577c7c4f84a99ca03386b8910d2f419ab6 fixes the issue.

**Comment by Dudemanguy** [comment]
Oh so the xwayland code also uses `view_update_size`. I can change that commit to only apply to xdg_shell.

**Comment by 20kdc** [comment]
Either this bug or something like it seems to be back, at least on Ubuntu 24.04?

Trace, version details: https://gist.github.com/20kdc/03c88c834933080306d6bc22a2add000
Please tell me if there's something I'm missing (i.e. if this was filed separately and then fixed again in a later version, and thus the bug report should be forwarded to Ubuntu)

**Comment by matteoldani** [comment]
+1 I think I hit the same issue on Ubuntu 24.04
