### ISSUE TITLE
Setting outputs power to on causes visual corruption and stuttering

### ISSUE THREAD

**Issue by lbatalha** [swaywm/sway#7726]
- **Sway Version:** 1.9-dev-bf44690e
- **Debug Log:** https://gist.github.com/lbatalha/b1d9de146912f12ac3f02442671d076f
- **Configuration File:** https://gist.github.com/lbatalha/62447bfca5d5d26b5b86a70696d447fc
- **Description:**

Intel A750, Mesa 1:23.1.6-1, Linux 6.4.12 (Arch)

Running `swaymsg "output * power on"` (or an output by name individually) causes mild to severe horizontal-ish jagged/corrupted looking black tears momentarily as well as stutters (0-1s). I detected this via `swayidle` when the `resume` block runs. The severity of the tears varies seemingly at random. Happens with both egl2 and vulkan backends.

Line 2563 of the log file is when I trigger the issue.

Reverting to sway commit `bb91b7f5` (wlroots `c74f89d4`) from earlier this month eliminates the issue.
My suspicion is that #7695 causes this, since sway stopped checking for the previous output state (If I understand the changes correctly).

As a slight confounding event, I had a full system freeze when resuming outputs that were powered off, while a VM with GPU passthrough was running (different GPU), though I had not debugged the tearing/suttering at the time and did not grab a core dump unfortunately.

**Comment by emersion** [comment]
Can you still reproduce? Might've been caused by https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4338

**Comment by lbatalha** [comment]
Using wlroots-git d817ebb8, sway-git 8a8fb76e, mesa 23.2.1, linux 6.5.5, it still appears to have the issue.

I realize I should have attached a video before (just repeating the command every 0.1 seconds for demo purposes):
https://github.com/swaywm/sway/assets/5883822/522c2f8d-7969-44e2-87de-143e98d8f748

Since my original post I have bypassed the issue by implementing a bash script to deal with all `power` on/off events, which first checks the state of the display and only executes the `power` command if it isn't already in the requested state.
```bash
declare -A outputs="($(swaymsg -rt get_outputs | jq -r '.|map("[\"\(.make) \(.model) \(.serial)\"]=\"\(.power)\"")|join(" ")'))"
case "$1" in                                                                                                                                                                                                                                                    
        off)
                echo "off"
                for key in "${!outputs[@]}"; do
                        if [ "${outputs[$key]}" = "true" ]; then
                                echo "$key power off"
                                swaymsg "output '$key' power off"
                        fi
                done
                ;;
        on)
                echo "on"
                for key in "${!outputs[@]}"; do
                        if [ "${outputs[$key]}" = "false" ]; then
                                echo "$key power on"
                                swaymsg "output '$key' power on"
                        fi
                done
                ;;
        *)
                echo "Provide parameter: 'on', 'off'"
esac
```

I don't really like all this janky bash syntax but also didn't want to invoke python or something at this level of complexity.
Regardless, using this in my `swayidle` config makes everything perfectly smooth at every `swayidle` trigger.

Would adding such a check in the code be a good idea?

**Comment by emersion** [comment]
Can you try again? Might've been fixed by https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3753

**Comment by lbatalha** [comment]
The issue appears to be fixed :+1: 

Tested the same way, repeat `power on` one or all displays every 100ms, no noticeable impact on wm usage.

(for future reference, running `linux` `6.6.3`, `mesa` `23.2.1`, `wlroots` commit `91182266`, `sway` commit `2cd73a33`)
