### ISSUE TITLE
Sway crashes when xwayland is disabled

### ISSUE THREAD

**Issue by genevieve-me** [swaywm/sway#7727]
### Please fill out the following:
- **Sway Version:**
  - `sway version 1.9-dev` (bf44690)

- **Debug Log:**
  - https://gist.github.com/genevieve-me/31a5496c824e5fa6bdfc3a2f2c0fcab5
  - 
- **Configuration File:**

```
xwayland disable
```

- **Stack Trace:**

[swaycoredump.txt](https://github.com/swaywm/sway/files/12458033/swaycoredump.txt)

```
#0  0x000000000041da93 in filter_global ()
#1  0x00007f38dddd6cfc in display_get_registry ()
   from /nix/store/5krz3xqcjgxgr7x8pd1z5xms9dkc0wjh-wayland-1.22.0/lib/libwayland-server.so.0
#2  0x00007f38dd33da3a in ffi_call_unix64 ()
   from /nix/store/86wfcbx4zg1dmgrfs2d54flvsdadgb0p-libffi-3.4.4/lib/libffi.so.8
#3  0x00007f38dd33c935 in ffi_call_int ()
   from /nix/store/86wfcbx4zg1dmgrfs2d54flvsdadgb0p-libffi-3.4.4/lib/libffi.so.8
#4  0x00007f38dd33d518 in ffi_call () from /nix/store/86wfcbx4zg1dmgrfs2d54flvsdadgb0p-libffi-3.4.4/lib/libffi.so.8
#5  0x00007f38dddda886 in wl_closure_invoke ()
   from /nix/store/5krz3xqcjgxgr7x8pd1z5xms9dkc0wjh-wayland-1.22.0/lib/libwayland-server.so.0
#6  0x00007f38dddd5c4b in wl_client_connection_data ()
   from /nix/store/5krz3xqcjgxgr7x8pd1z5xms9dkc0wjh-wayland-1.22.0/lib/libwayland-server.so.0
#7  0x00007f38dddd88f2 in wl_event_loop_dispatch ()
   from /nix/store/5krz3xqcjgxgr7x8pd1z5xms9dkc0wjh-wayland-1.22.0/lib/libwayland-server.so.0
#8  0x00007f38dddd6455 in wl_display_run ()
   from /nix/store/5krz3xqcjgxgr7x8pd1z5xms9dkc0wjh-wayland-1.22.0/lib/libwayland-server.so.0
#9  0x0000000000412034 in main ()
```

- **Description:**

Launch sway with `xwayland disable` and get an immediate crash. This occurs with wlroots revision `717ded9b`, wayland 1.22, wayland-protocols revision `e1d61ce9402ebd996d758c43f167e6280c1a3568`. I tested and checked this also occurred on the second-to-last sway revision 4a22105, but couldn't bisect further. As you can see from the trace, this is on an AMD APU with the mesa driver.

`uname -a : 
Linux 6.4.12 #1-NixOS SMP PREEMPT_DYNAMIC Wed Aug 23 15:32:56 UTC 2023 x86_64 GNU/Linux`

*Edited to fix formatting issue*.

**Comment by emersion** [comment]
We probably want to add an extra NULL check in there. Are you willing to submit a patch?

**Comment by genevieve-me** [comment]
> Are you willing to submit a patch?

I can take a look and submit one when I have time!
