### ISSUE TITLE
vulkan renderer transparency nonlinear

### ISSUE THREAD

**Issue by JosefLitos** [swaywm/sway#7731]
### Please fill out the following:
- **Sway Version:** 1.8.1

- **Debug Log:** [sway.log](https://github.com/swaywm/sway/files/12487205/sway.log)
- **Configuration File:** default
- **Description:**
  - transparency isn't linear but rather parabola
  - vulkan at 0.5:
![vulkan](https://github.com/swaywm/sway/assets/54900518/d972d6bd-b281-489b-9155-44df952e1c96)
  - default at 0.5:
![default](https://github.com/swaywm/sway/assets/54900518/36b6a3d9-b469-4e89-b473-36f8205c3ca9)

**Comment by emersion** [comment]
Probably a bug in the sRGB conversion logic. Can you report this as a wlroots issue?

**Comment by JosefLitos** [comment]
Will do, btw, I just noticed with `vulkan` backend I also get these messages once every while when using `foot`:
`wayland.c:1507: no server-side cursors available, falling back to client side`

**Comment by emersion** [comment]
Sounds unrelated to Vulkan and this issue... Are you sure you don't get these with GL?

Closing in favor of the wlroots issue.

**Comment by JosefLitos** [comment]
Yes - I get it almost immediately when playing with multiple windows. I was testing the lag difference (I didn't use the vulkan renderer before, because it was very laggy with transparent windows) and the same script used (just creates 1000 terminals) always evoked the message, whereas with gles2 backend no message appeared.

**Comment by JosefLitos** [comment]
Also, the issue I had the first time I tried vulkan out is still present anyway - the cursor stutters, quite noticeable at lower motion speed.

Is there a way to find out the current fps of the desktop? I have a normal 60fps display, but I feel like with vulkan it doesn't quite reach that fps.
