### ISSUE TITLE
alttab

### ISSUE THREAD

**Issue by aloispichler** [swaywm/sway#7734]
Is there a (useful and beautiful) alttab switcher on Sway?
Something similar to ‘Ctrl+Tab‘ on firefox or https://github.com/sagb/alttab (which, unfortunately, only works on X11)?

**Comment by emersion** [comment]
Sway does not support this. External programs might.

**Comment by aloispichler** [comment]
It would be friendly and helpful to answer the question instead of killing it.

**Comment by emersion** [comment]
This issue tracker is not for questions. Moreover, I've answered your question.

**Comment by aloispichler** [comment]
Yes, you did. I have expected a constructive answer, though.
