### ISSUE TITLE
Desktop wallpaper rendered through transparet objects in various applications

### ISSUE THREAD

**Issue by zoopp** [swaywm/sway#7739]
- **Sway Version:** 
	- sway version 1.8.1
- **Debug Log:** 
	- [sway.log](https://github.com/swaywm/sway/files/12552732/sway.log)
- **Configuration File:** 
	- default
- **Description:**

Some applications that have transparent objects in them will render part of the desktop wallpaper where these objects show up UNLESS the application is in full screen. Here is an example of what I'm talking about (showing FreeCAD and Ultimaker Cura):

https://github.com/swaywm/sway/assets/1645023/6d542408-812c-4d99-b8fd-b3132f436405

It's happening regardless if I use the integrated Intel GPU or my AMD eGPU. This has been happening since over a year ago after I switched to SwayWM and Wayland and while it doesn't really bother me, I'd be glad for this effect to be gone.

I've tested the same scenario under weston and it seems to behave fine:

https://github.com/swaywm/sway/assets/1645023/eee68ded-6222-42d6-8ce7-717952521eaf

**Comment by emersion** [comment]
This is likely an app bug. They shouldn't use an alpha format when they don't intend to use the alpha channel.

The fact that it works under Weston is likely "by chance", due to a culling optimization.

**Comment by zoopp** [comment]
Alright, I understand. Would it be fair to say that the issue should be closed as is since it does not look like a problem with SwayWM?

**Comment by rpigott** [comment]
Yes, you can always re-open it if there is something to be done in sway. You should report this to the application developer though. If it helps you, #6549 is the last time this was reported.
