### ISSUE TITLE
regression: white flash when sway starts

### ISSUE THREAD

**Issue by WhyNotHugo** [swaywm/sway#7754]
### Please fill out the following:
- **Sway Version:**
  - `sway version 1.9-dev-bb91b7f5 (Aug  4 2023, branch 'master')`
  - This problem **is not** reproducible with `sway version 1.8.1`

- **Debug Log:**
  - sway.err: https://paste.sr.ht/~whynothugo/64ba3ec1f70da394e98a74da37f21cc536ed91b5

- **Configuration File:**

```
exec foot
output WL-1 scale 2
```

- **Stack Trace:**

n/a

- **Description:**

- On a tty, run `sway`.

This is on AMD hardware. Alpine Linux Edge. I built sway from `master` and installed it with meson. Exactly as detailed at https://whynothugo.nl/journal/2023/08/04/building-and-running-sway-master/

**Comment by WhyNotHugo** [comment]
Oh, the white flash is just one frame, but blinding when starting sway in a dark environment.

**Comment by emersion** [comment]
Can you still reproduce? Might've been caused by https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4338

**Comment by WhyNotHugo** [comment]
I can no longer reproduce on latest master. Thanks.
