### ISSUE TITLE
Sway GTK apps dont launch from wofi

### ISSUE THREAD

**Issue by InvisibleRasta** [swaywm/sway#7760]
swaymsg version 1.8.1

Debug Log:
https://bpa.st/U7SQ

.config/sway/config 
https://bpa.st/URMQ

Description:
I am trying to launch gtk applications that require root permissions. In the terminal when i run just "gparted" i get a popup dialog to enter the password, once entered it crashes with the following error:

`(gpartedbin:48026): Gtk-WARNING **: 21:14:53.999: cannot open display:`

Launching gparted from wofi will also prompt me for a password and it will just crash.

The only way I was able to launch gparted is with `sudo -E gparted`

swaymsg -t get_outputs                                                                                       
```
Output Unknown-1 'Unknown Unknown Unknown' (focused)
  Current mode: 2560x1440 @ 60.000 Hz
  Position: 0,0
  Scale factor: 1.000000
  Scale filter: nearest
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 1
  Max render time: off
  Adaptive sync: disabled
  Available modes:
    2560x1440 @ 60.000 Hz
```

**Comment by emersion** [comment]
This is not a Sway bug. Most likely a gparted bug.

**Comment by InvisibleRasta** [comment]
i tought i had maybe some lines missconfigured in my config file. 

exec dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY SWAYSOCK
exec systemctl --user import-environment
exec --no-startup-id /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
