### ISSUE TITLE
Mesa attempts to load wrong driver on startup which might be causing issues with other applications.

### ISSUE THREAD

**Issue by telephrag** [swaywm/sway#7767]
### Please fill out the following:
- **Sway Version:**
  - sway version 1.8.1

- **Debug Log:**
  - https://gist.github.com/telephrag/002abc23aca06d3aeb0e3e3135a10f4b
  - Most likely you'll be interested only in the first lines few dozen lines. since, bug occurs at startup.
  - Collected with `dbus-run-session -- sway -d 2> sway.log`

- **Configuration File:**
  - https://gist.github.com/telephrag/002abc23aca06d3aeb0e3e3135a10f4b#file-config
  - Mostly default config. XDG_RUNTIME_DIR is set properly.

- **Description:**
  - OS: Alpine Linux 3.18.4
  - Laptop: HP db0006ur w/ Ryzen 2500U (APU that also hauses Vega 8 GPU)
  - GPU driver: `linux-firmware-radeon-20230515-r6`
  - DRI lib is installed: `mesa-dri-gallium-23.0.4-r0`
  - Sway is launched via `dbus-run-session -- sway`. 
  - On startup Mesa attempts to load non-existent driver related to xorg: `MESA-LOADER: failed to open simpledrm: Error loading shared library /usr/lib/xorg/modules/dri/simpledrm_dri.so: No such file or directory (search paths /usr/lib/xorg/modules/dri, suffix _dri)`
  - With `MESA_LOADER_DRIVER_OVERRIDE=radeonsi` set or not, the issue persists. This variable is supposed to override which driver mesa loads but, it appears to have no effect.

- **Other possibly related things:**
  - `mpv` has to be launched with `--vo=gpu --gpu-context=wayland` to play videos. Otherwise SEGFAULTs.
  - `lshw -c video` states that display is unclaimed: 
    ```
    *-display UNCLAIMED       
       description: VGA compatible controller
       product: Raven Ridge [Radeon Vega Series / Radeon Vega Mobile Series]
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 0
       bus info: pci@0000:04:00.0
       version: c4
       width: 64 bits
       clock: 33MHz
       capabilities: vga_controller cap_list
       configuration: latency=0
       resources: memory:d0000000-dfffffff memory:e0000000-e01fffff ioport:1000(size=256) memory:e0600000-e067ffff memory:c0000-dffff
    ```
  - `swaymsg -t get_outputs` sees display as Unknown:
    ```
    Output Unknown-1 'Unknown Unknown Unknown' (focused)
     Current mode: 1366x768 @ 60.000 Hz
     Position: 0,0
     Scale factor: 1.000000
     Scale filter: nearest
     Subpixel hinting: unknown
     Transform: normal
     Workspace: 3
     Max render time: off
     Adaptive sync: disabled
     Available modes:
       1366x768 @ 60.000 Hz
    ```
  - Steam ran as a flatpak refuses to fully render UI. The whole screen is grey while drop down menus (Store, Library etc.) pop up if you hover over them.
  - `/sys/class/backlight` is empty so, controlling screen brightness is impossible.

Edit0: Some additions to system configuration's description.
Edit1: Added information about `MESA_LOADER_DRIVER_OVERRIDE`. See **Description**.

**Comment by bl4ckb0ne** [comment]
You need `mesa-dri-gallium` to have radeonsi or radv, the firmware is not the userland driver.

**Comment by emersion** [comment]
Yeah, you're missing some kernel drivers here. Maybe dmesg has more clues.

**Comment by telephrag** [comment]
> You need to install `mesa-dri-gallium` to have radeonsi or radv, the firmware is not the userland driver.
> 
> > 00:00:00.003 [INFO] [wlr] [backend/drm/backend.c:200] Initializing DRM backend for /dev/dri/card0 (simpledrm)
> 
> simpledrm is the kernel default framebuffer driver when no gpu is available.

Nah, it's already installed. 
```
doas apk list | grep mesa-dri
mesa-dri-gallium-23.0.4-r0 x86_64 {mesa} (MIT AND SGI-B-2.0 AND BSL-1.0) [installed]
```

**Comment by telephrag** [comment]
> Yeah, you're missing some kernel drivers here. Maybe dmesg has more clues.

Weird, it tries to do something with `amdgpu`. `linux-firmware-amdgpu` isn't even installed because my GPU uses `linux-firmware-radeon`.
```
doas dmesg | grep gpu
[    3.108337] [drm] amdgpu kernel modesetting enabled.
[    3.108904] amdgpu: Topology: Add APU node [0x0:0x0]
[    3.109422] amdgpu 0000:04:00.0: Direct firmware load for amdgpu/raven_gpu_info.bin failed with error -2
[    3.109426] amdgpu 0000:04:00.0: amdgpu: Failed to load gpu_info firmware "amdgpu/raven_gpu_info.bin"
[    3.109427] amdgpu 0000:04:00.0: amdgpu: Fatal error during GPU init
[    3.109429] amdgpu 0000:04:00.0: amdgpu: amdgpu: finishing device.
[    3.109465] amdgpu: probe of 0000:04:00.0 failed with error -2
```

**Comment by bl4ckb0ne** [comment]
Weird, I recall there was some issues with the firmware not too long ago. Have you tried edge? You packages are not up to date (`linux-firmware-radeon-20230919-r1` and `mesa-dri-gallium-23.1.8-r1` on my system)

**Comment by telephrag** [comment]
> Weird, I recall there was some issues with the firmware not too long ago. Have you tried edge? You packages are not up to date (`linux-firmware-radeon-20230919-r1` and `mesa-dri-gallium-23.1.8-r1` on my system)

No I didn't. Can it be that you're referring to this: https://gitlab.freedesktop.org/mesa/mesa/-/issues/5042 ?

**Comment by bl4ckb0ne** [comment]
This https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/52340 but now that I looked it seems unrelated.

**Comment by telephrag** [comment]
> Weird, I recall there was some issues with the firmware not too long ago. Have you tried edge? You packages are not up to date (`linux-firmware-radeon-20230919-r1` and `mesa-dri-gallium-23.1.8-r1` on my system)

Upgraded to the edge. The issue remains.

**Comment by bl4ckb0ne** [comment]
Very strange. Nevertheless I don't think this is a sway bug, I invite you to report it to alpinelinux, there's #alpinelinux on OFTC for that kind support.

**Comment by telephrag** [comment]
> Very strange. Nevertheless I don't think this is a sway bug, I invite you to report it to alpinelinux, there's #alpinelinux on OFTC for that kind support.

Will do but, it seems pretty quite in that chat.

**Comment by bl4ckb0ne** [comment]
Ask your question, but you have to stick around. It might be not answered immediately.

**Comment by telephrag** [comment]
> Very strange. Nevertheless I don't think this is a sway bug, I invite you to report it to alpinelinux, there's #alpinelinux on OFTC for that kind support.

Turns out that Alpine Wiki provides false information. Vega GPUs need `amdgpu` instead of `radeon`. Everything seem to be working perfectly now and my eyes physically hurting from screen brightness even.
