### ISSUE TITLE
Feature request: sway-portals.conf for xdg-desktop-portals

### ISSUE THREAD

**Issue by yourealwaysbe** [swaywm/sway#7773]
Since version 1.17, xdg-desktop-portals requires desktops [to declare which portals should be used](https://github.com/flatpak/xdg-desktop-portal/blob/main/doc/portals-conf.rst). This is via a file, e.g. `/usr/share/xdg-desktop-portal/sway-portals.conf `:

    [preferred]
    default=wlr;gtk

Or [this more precise one used by Fedora](https://src.fedoraproject.org/rpms/sway/blob/rawhide/f/sway-portals.conf). Or "default=*" to just use whatever is available.

It's not clear to me whether Sway should provide a default, individual distributions should provide their own, or end users should take care of it with a local config. The Arch Linux packagers [prefer an upstream file](https://bugs.archlinux.org/task/79883#comment222699).

**Comment by emersion** [comment]
Sway does not officially support xdg-desktop-portal. xdpw is a third-party project. I don't think it's Sway's responsibility to ship any kind of portal-related file.

**Comment by yourealwaysbe** [comment]
Ok -- i'll got for a note in the Arch Wiki.
