### ISSUE TITLE
WAYLAND_DISPLAY always set to wayland-1

### ISSUE THREAD

**Issue by taminob** [swaywm/sway#7782]
- **Sway Version:**
  `1.8.1` / `master`

- **Debug Log:**
https://pastebin.com/CVBsCw4P
```
...
00:00:00.110 [INFO] [wlr] [wayland] unable to lock lockfile /run/user/1000/wayland-1.lock, maybe another compositor is running
00:00:00.110 [INFO] [wlr] [backend/headless/backend.c:67] Creating headless backend
00:00:00.111 [ERROR] [sway/main.c:393] server.socket: 'wayland-2' (added by me directly after setenv call)
...
00:00:00.143 [INFO] [sway/server.c:343] Starting backend on wayland display 'wayland-2'
00:00:00.583 [INFO] [sway/server.c:355] Running compositor on wayland display 'wayland-2'
...
```

- **Configuration File:**
I was able to reproduce this issue with the default configuration

- **Description:**

While looking at issue #7556, I noticed that for me, `WAYLAND_DISPLAY` has always the same value (`wayland-1`) if I start multiple instances of sway.
Weirdly, for each instance, a socket is created with the correct name (`wayland-2`, ´wayland-3`, ...) and they work as expected.
Only the environment variable has always the value `wayland-1`.

Additionally, I had a look at the value of `server.socket` in `sway/main.c` where `setenv` is called: the value is also the correct one (e.g. `wayland-2`).
I cannot find any other place except `sway/main.c:392` where the environment variable is modified, so it could very well be some other process on my system that sets it. Does anyone else experience this issue?

Since I'm running arch linux which includes [this file](https://gitlab.archlinux.org/archlinux/packaging/packages/sway/-/blob/main/50-systemd-user.conf], I thought at first that this was the issue, but excluding it from the configuration and rebooting didn't change anything and `systemctl show-environment --user` also doesn't list `WAYLAND_DISPLAY` anymore.

**Comment by emersion** [comment]
`WAYLAND_DISPLAY` is set inside the nested instances of Sway, not outside.

**Comment by taminob** [comment]
Sorry in case I haven't been clear - the value inside the nested instance (and also inside sway if started on a separate tty) is always `wayland-1`.

Is this normal behavior?

**Comment by taminob** [comment]
In case someone else struggles with this issue in the future - for me the problem was that I checked the variables inside `tmux` session which contained the environment variables of the first time I started it across different `sway` instances.

Everything works as it should outside of `tmux`.
