### ISSUE TITLE
Add testing infrastructure to project

### ISSUE THREAD

**Issue by taminob** [swaywm/sway#7788]
While working on the code, I was a little bit surprised to find that the project has no testing setup.

I'd propose to setup a testing infrastructure (choose a testing framework, integrate it in build system and have a CI for running them) for at least a few basic unit and regression tests.
Once the structure is in-place, it will get easier to gradually improve the test suite's size and coverage.
In the long term, a good test suite can help to improve stability and simultaneously reduce the risk of regressions.

In case you want this, I'd be willing to help implement it although I'd be glad to get some opinions on C testing frameworks since I come from C++, I mainly know the testing frameworks there first-hand.
It would also be possible to use them to test the C code if there is no suitable C-only library, but this would add the requirement of a C++ compiler.

**Comment by emersion** [comment]
Sorry, I'm not interested in maintaining a testing suite for Sway. The overhead is just too high, and I don't think it'd be that useful at identifying regressions: most of the changes nowadays affect the wlroots-related parts of the code, not the WM features.

BTW, i3 already has a test suite, so if someone is interested in having third-party tests, maybe that would be a start.

**Comment by taminob** [comment]
I understand, it definitely would add additional maintenance effort.

I'll have a look at the i3 tests, but will close this issue for now since it won't be relevant for this repository.
