### ISSUE TITLE
Sway should use xdg_shell's configure_bounds to limit tile size

### ISSUE THREAD

**Issue by colinmarc** [swaywm/sway#7794]
This is something between a bug and enhancement, I wasn't sure which template to use. I'm using sway 1.8.1.

Per the wayland protocol, a client wishing to change the shell geometry may issue a [`set_window_geometry`](https://wayland.app/protocols/xdg-shell#xdg_surface:request:set_window_geometry) request to update the shell's "visible bounds from the user's perspective". On sway, which doesn't allow resizing tiles this way, the request is ignored, and since there's no indication to the client that it shouldn't present buffers at the new size, this results in clipped content. On other compositors, as far as I can tell, this usually results in the shell resizing, as if a user had dragged it bigger.

Sway's choice not to allow tiles to be resized by client code seems reasonable to me, but as a client author, I have no way of differentiating "my content is going to be clipped and broken" from "the window will resize and will look good". I can use heuristics such as whether the toplevel is explicitly tiled, but other tiling compositors could presumably allow tiles to be resized this way, so that would be imperfect.

It would help if sway would send the [`xdg_toplevel::configure_bounds`](https://wayland.app/protocols/xdg-shell#xdg_toplevel:event:configure_bounds) event, from version 4 of `xdg_shell`, to indicate that shell resizes greater than that will be ignored. Then clients could clamp their `set_window_geometry` requests to that size.

**Comment by colinmarc** [comment]
Hi, thanks for the quick response!

The protocol you linked specifically mentions the maximized case, but not the tiled one, as a protocol error:

```
The surface is maximized. The window geometry specified in the configure
event must be obeyed by the client, or the xdg_wm_base.invalid_surface_state
error is raised.
```

Nor does sway raise the `xdg_wm_base.invalid_surface_state` error in the tiled case.

Aside from those issues, that seems like a good way to resolve the ambiguity I'm encountering. I can try to raise it as an issue with the framework ([winit](https://github.com/rust-windowing/winit)) I'm using; should I also open an issue on the wayland-protocols repository to adjust the documentation there?

**Comment by emersion** [comment]
Yeah, it's correct that the wording is missing for the tiled states, we've discussed about this on IRC and came up with this patch: https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/258

Sway does not raise `xdg_wm_base.invalid_surface_state` because too many clients are misbehaving.

**Comment by colinmarc** [comment]
A fix for this on the winit side was included this changeset: https://github.com/rust-windowing/winit/pull/3189
