### ISSUE TITLE
Sway creates a window for exit message; i3 uses a pop-up

### ISSUE THREAD

**Issue by WinFan3672** [swaywm/sway#7798]
By default, under i3, hitting $mod+Shift+e creates a pop-up above the current window content, as seen here: https://imgur.com/a/MXodROY

However, under Sway, a window is created, which looks like this: https://imgur.com/a/VSZeWyh

This already looks out of place when nothing is open, but having multiple open windows causes even more issues: https://imgur.com/a/DTR0E7o

This is clearly an issue, and has understandably flown under the radar for quite some time. As someone who exits using this shortcut, I cannot tolerate this and it's literally the only thing stopping me from making the switch to Sway.

**Comment by bitraid** [comment]
What you're seeing is not normal. Have you tried with default configuration?

**Comment by WinFan3672** [comment]
> What you're seeing is not normal. Have you tried with default configuration?

I am using a default i3 config with a few things modified, so I can't see any reason why it wouldn't work. I haven't touched the parts that modify the exit window. For reference, my dotfiles can be found [here](https://codeberg.org/WinFan3672/dotfiles/src/branch/main/i3/config).

**Comment by bitraid** [comment]
You are executing i3-nagbar/i3-msg:
```
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -B 'Yes, exit i3' 'i3-msg exit'"
```
You should change it to swaynag/swaymsg:
```
bindsym $mod+Shift+e exec "swaynag -t warning -m 'You pressed the exit shortcut. Do you really want to exit sway? This will end your Wayland session.' -B 'Yes, exit sway' 'swaymsg exit'"
```

**Comment by WinFan3672** [comment]
> You are executing i3-nagbar/i3-msg:
> 
> ```
> bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -B 'Yes, exit i3' 'i3-msg exit'"
> ```
> 
> You should change it to swaynag/swaymsg:
> 
> ```
> bindsym $mod+Shift+e exec "swaynag -t warning -m 'You pressed the exit shortcut. Do you really want to exit sway? This will end your Wayland session.' -B 'Yes, exit sway' 'swaymsg exit'"
> ```

Thanks, this worked!
