### ISSUE TITLE
bindsym - Easier Configuration

### ISSUE THREAD

**Issue by Doomer-Cat** [swaywm/sway#7807]
```
bindsym $mod1+(Shift)+i firefox 
```

Press mod+i = opens firefox
Press mod+shift+i = opens firefox

Essentially a way for easier configuration with just a single line

Another idea i had was to add arguments or other stuff when (key) is pressed kinda like this:
```
bindsym $mod1+(Shift)+s steam (-bigpicture)
```
Press mod+s = opens steam
Press mod+shift+s = opens steam in big picture

not sure if it works like this but you get the idea

Edit: i used to have a lot of diffrent bindsym lines in i3 because of this

**Comment by emersion** [comment]
Sorry, we're not accepting any new window management features anymore. See https://github.com/swaywm/sway/blob/master/CONTRIBUTING.md#scope-of-future-changes-to-sway
