### ISSUE TITLE
Support for Wayland Tearing Protocol?

### ISSUE THREAD

**Issue by sad-goldfish** [swaywm/sway#7811]
Can Sway support the (somewhat) recently merged [tearing  updates protocol](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/65)? This will minimize latency when software anti-tear methods are not needed (e.g. VRR, GSync enabled).

I realise that #4715 exists but it was closed before the above protocol was merged. I think it is worth reconsidering now that WLRoots has this functionality.

**Comment by emersion** [comment]
There is https://github.com/swaywm/sway/pull/7598 for this already.

**Comment by sad-goldfish** [comment]
Apologies, it didn't come up [when I searched for tearing](https://github.com/swaywm/sway/issues?q=is%3Aissue+tearing).
