### ISSUE TITLE
Refuse to use max resolution connecting monitor while Sway is running but working when monitor is connected prior from tty

### ISSUE THREAD

**Issue by 2Belette** [swaywm/sway#7813]
- **Sway Version:**
 sway version 1.8.1, OS : Alpine Linux

- **Debug Log:** (screen connected before launching sway, everything is working fine)
https://gist.github.com/2Belette/cf834acae082a40636828988af5deb67

- **Debug Log:** (screen connected while Sway is running, black screen)
https://gist.github.com/2Belette/9829d7ce89bd0825ffa38e072c2088ef

- **Extract of DRM Log:**
https://gist.github.com/2Belette/ab1be176047be9889866e2a4f863900c

Easy to spot the `connector DP-1: Atomic commit failed: Invalid argument`issue but trying with `WLR_DRM_NO_MODIFIERS=1` is gving me the same result.

- **Configuration File:**
```
exec --no-startup-id kanshi
output 'Dell Inc. DELL U3224KBA F8Q77P3' mode 6144x3456@60.001Hz position 0,0 scale 1.2
output "*" background /home/blt/pictures/back.jpg fill
```
Same issue with or without kanshi, same issue doing it manually as well with swaymsg (`swaymsg "output 'Dell Inc. DELL U3224KBA F8Q77P3' mode 6144x3456@60.001Hz scale 1.2"`)

- **Description:**
If I connect my monitor when I am still on tty and start Sway, my monitor is going on and is correctly using the max res/refresh rate:
```
swaymsg -t get_outputs
Output DP-1 'Dell Inc. DELL U3224KBA F8Q77P3' (focused)
  Current mode: 6144x3456 @ 60.001 Hz
  Position: 0,0
  Scale factor: 1.199219
  Scale filter: linear
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 4
  Max render time: off
  Adaptive sync: disabled
  Available modes:
    6144x3456 @ 60.001 Hz
    3840x2160 @ 59.997 Hz
    6144x3456 @ 29.995 Hz
    6016x3384 @ 59.998 Hz
    5120x2880 @ 59.995 Hz
```

If I starts Sway and connect my monitor afterwards, I got a black screen with an (inactive) state. I am able to make it work if I use another resolution (5120x2880 @ 59.995 Hz) but as my configuration file and kanshi are trying to use the max res I have a black screen,
Same issue if I turn my monitor off -> on.

If you have any suggestion or idea :) Many thanks

**Comment by emersion** [comment]
Hm, weird. Relevant part of the log:

```
[47056.764373] i915 0000:00:02.0: [drm:intel_dp_compute_link_config [i915]] DP link computation with max lane count 4 max rate 810000 max bpp 24 pixel clock 1378800KHz
[47056.764414] i915 0000:00:02.0: [drm:intel_dp_compute_link_config [i915]] DP lane count 4 clock 810000 bpp 18
[47056.764451] i915 0000:00:02.0: [drm:intel_dp_compute_link_config [i915]] DP link rate required 3102300 available 3240000
[47056.764489] i915 0000:00:02.0: [drm:intel_atomic_check [i915]] [CRTC:233:pipe D] hw max bpp: 24, pipe bpp: 18, dithering: 1
[47056.764531] i915 0000:00:02.0: [drm:intel_atomic_check [i915]] [CRTC:233:pipe D] Cannot act as big joiner master (need 0x18 as pipes, only 0xf possible)
```

**Comment by 2Belette** [comment]
Thanks @emersion , would you suggest me any test/logs to understand the reason?

**Comment by 2Belette** [comment]
@emersion on interesting thing, I had to boot on an Ubuntu Live to update one firmware on the same laptop and so I had an opportunity to test the exact same setup (laptop, cable, monitor) on Ubuntu and when I connected the cable the screen turned on with the max resolution, same thing when I disconnected & connected..

The only thing I noticed, is the short pop-up on my screen was indeed showing 18bit and not 24bit so it seems aligned with the revelant part of the log you noticed ! Is there a way to force to use 18bit instead of from swaymsg/kanshi or sway configuration so I can confirm ?

Screenshot from Ubuntu for info 
![2023 11 10 15 28 21](https://github.com/swaywm/sway/assets/2325706/b2f8635b-784d-4d45-8d09-2ab2f45ef93d)

**Comment by emersion** [comment]
Does it help to make this function return 6? https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/backend/drm/atomic.c?ref_type=heads#L169

**Comment by 2Belette** [comment]
So if I got it right returning 6 will impact the test from line 193 to 198 ? But I still don't get why thupis would allow/fallback to 18 bit

**Comment by emersion** [comment]
Will set the "max bpc" KMS property to 6. 6 bpc = 18 bpp.

**Comment by 2Belette** [comment]
Ha ! OK I got it now !
Yes I think it should solve it

**Comment by 2Belette** [comment]
@emersion you think this change would be able to be in a patch version or next release ? many thanks

**Comment by emersion** [comment]
Have you tested it?

No, this change is just a quick hack to check what the issue is. The max bpc is just a maximum and the kernel is supposed to automatically pick a lower value if it can't use the max. So I suspect this bug to be a driver bug.

**Comment by 2Belette** [comment]
I haven't as I am not 100% sure how to do :
Should I have to make a custom .tar.gz with your suggested tweak on the atomic.c file and refer to this new / local .tar.gz to a newly APKBUILD base on the [original](https://git.alpinelinux.org/aports/tree/community/sway/APKBUILD) ? 
That's my idea but not sure if this is the right way to do. Thanks for your advice

**Comment by emersion** [comment]
You don't need to install a patched Sway, you can just build it and run it directly. See https://github.com/swaywm/sway/wiki/Development-Setup#compiling-as-a-subproject

**Comment by 2Belette** [comment]
I must doing something stupid...
I followed your link and `meson build/` is giving me this error : 

```
wlroots| Project name: wlroots
wlroots| Project version: 0.18.0-dev
wlroots| C compiler for the host machine: cc (gcc 12.2.1 "cc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924")
wlroots| C linker for the host machine: cc ld.bfd 2.40
wlroots| Compiler for C supports arguments -Wundef: YES
wlroots| Compiler for C supports arguments -Wlogical-op: YES
wlroots| Compiler for C supports arguments -Wmissing-include-dirs: YES
wlroots| Compiler for C supports arguments -Wold-style-definition: YES
wlroots| Compiler for C supports arguments -Wpointer-arith: YES
wlroots| Compiler for C supports arguments -Winit-self: YES
wlroots| Compiler for C supports arguments -Wstrict-prototypes: YES
wlroots| Compiler for C supports arguments -Wimplicit-fallthrough=2: YES
wlroots| Compiler for C supports arguments -Wendif-labels: YES
wlroots| Compiler for C supports arguments -Wstrict-aliasing=2: YES
wlroots| Compiler for C supports arguments -Woverflow: YES
wlroots| Compiler for C supports arguments -Wmissing-prototypes: YES
wlroots| Compiler for C supports arguments -Walloca: YES
wlroots| Compiler for C supports arguments -Wno-missing-braces: YES
wlroots| Compiler for C supports arguments -Wno-missing-field-initializers: YES
wlroots| Compiler for C supports arguments -Wno-unused-parameter: YES
wlroots| Compiler for C supports arguments -fmacro-prefix-map=/prefix/to/hide=: YES
wlroots| Found pkg-config: /usr/bin/pkg-config (1.9.5)
wlroots| Found CMake: /usr/bin/cmake (3.26.5)
wlroots| Run-time dependency wayland-server found: NO (tried pkgconfig and cmake)
wlroots| Looking for a fallback subproject for the dependency wayland-server

wlroots| subprojects/wlroots/meson.build:105:17: Exception: Neither a subproject directory nor a wayland.wrap file was found.

Subproject subprojects/wlroots is buildable: NO (disabling)
Run-time dependency wlroots found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency wlroots

meson.build:47:10: ERROR: Subproject "subprojects/wlroots" required but not found.
```
subprojects/wlroots is present as I did the git clone from the previous command.

**Comment by 2Belette** [comment]
Reply to myself : I was missing some dev package on my system, I am able to compile everything now.

@emersion : your suggestion doesn't seem to work, got the same issue with sway version 1.9-dev-0aceff74 (Jan 12 2024, branch 'master') and modifying the return function to 6 as you suggested.. Would you suggest me to put some logs here to be sure that I did everything correctly or if you have another idea to test ?

I also tried with this version I compiled and with the modified function to connect my monitor prior to launch Sway and like the stock version, my monitor goes to full resolution, the issue is still the same (connecting my monitor while Sway is running)

Thanks
