### ISSUE TITLE
Waybar crashing while using Sway?

### ISSUE THREAD

**Issue by CDTay** [swaywm/sway#7816]
sway version 0.3.2-19414f6 (Nov 12 2023, branch 'master')

When booting Waybar with the terminal, and using the wlr/taskbar module, it will often crash upon clicking one of the open window icons. It works for a while, but after a random amount of time (usually less than a minute) the next click on a taskbar icon will crash waybar. I moved to Sway from Hyprland, and didn't have the same issue with Hyprland, so I'm not quite sure what difference has caused this to start happening.

Below is the output waybar gives on the console when it crashes:

````
(waybar:9909): Gdk-CRITICAL **: 14:35:15.897: gdk_wayland_window_get_wl_surface: assertion 'GDK_IS_WAYLAND_WINDOW (window)' failed

Gdk-Message: 14:35:15.897: Error 22 (Invalid argument) dispatching to Wayland display.
````

**Comment by emersion** [comment]
Sounds like a waybar bug. Please report it to them.
