### ISSUE TITLE
Support key pressing for `seat`, like in `seat - cursor press` for mouse

### ISSUE THREAD

**Issue by madmanxxx** [swaywm/sway#7825]
I have a mouse, which has two buttons integrated into wheel (left, right). `wev` reports them as "horizontal wheel", but I use them as BACK / FORWARD. To accomplish this, my _sway_ configuration contains the following:
```
bindsym --whole-window button6 exec wtype -P XF86Back
bindsym --whole-window button7 exec wtype -P XF86Forward
```
This generally works, but `exec`ing an external binary every time a button is pressed seems a bit too much. `man 5 sway-input` describes a few `seat` options for mouse, but lacks an equivalent for keyboard...

PS: Maybe this kind of mapping can be done on some other level than _sway_. I am open for any solution that avoids executing a binary on every keypress.

**Comment by emersion** [comment]
BTW, `cursor press` is already marked as deprecated.

**Comment by danieldg** [comment]
Would the best solution here be:

- Adding a wayland protocol to allow `bindsym`-like event delivery to non-focused clients, which could then grab the event and send the translated keyboard event with the existing virtual-keyboard protocol (or -mouse, in the case of binds currently mapped to `cursor press`)
- Encouraging the use of `swaymsg -m -t subscribe '["binding"]'` and a `nop` binding as an event-delivery mechanism, which can then do the same keyboard/mouse delivery
- Some other way to remap input events - can libinput udev rules do this in a sufficiently flexible way?

The second seems like something you can do today.

**Comment by emersion** [comment]
Oh I completely forgot that we have binding events! Yeah, that sounds like something which can work today.

For a cross-compositor solution, there will be https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/216. However, it's mainly for keyboard events. Maybe it can work for other kinds of events as well, but would require configuration in the compositor.

**Comment by tmccombs** [comment]
> BTW, cursor press is already marked as deprecated.

the man page says to "use virtual-pointer wayland protocol instead". But how would you use that in a simple shell script, or a keybinding?

**Comment by danieldg** [comment]
Unfortunately, if sway isn't willing to expose a command for it, this will require a helper process (`exec` for each press) or a daemon.

**Comment by tmccombs** [comment]
First of all, are there existing programs that could be used to move and press mouse buttons, and scroll, that are included in common distributions that support sway?

Secondly, requiring spawning  a separate process may add unacceptable latency if the goal is to map one button press to another, which would increase the importance of https://github.com/swaywm/sway/issues/3960.

**Comment by emersion** [comment]
Ref https://github.com/swaywm/sway/issues/7825 for pointer event support in wtype.

If spawning a process on each key event is unacceptable, one can use a daemon listening on Sway's IPC instead as @danieldg explained.

Closing because we don't plan to add support for key event emulation via Sway commands.

**Comment by tmccombs** [comment]
Did you mean to link to something else? That link is just to this issue.

**Comment by emersion** [comment]
Oops, fixed.
