### ISSUE TITLE
Unable to add more than 4 keyboard layouts

### ISSUE THREAD

**Issue by DanisDGK** [swaywm/sway#7829]
### Please fill out the following:
- **Sway Version:**
  - 1.8.1

- **Debug Log:** (the difference between the two is the layout positions swapped between 4th and 5th in the list)
https://gist.github.com/DanisDGK/3fe5d95d16b053a9f767297349b14789

- **Configuration File:**
```
input type:keyboard {
    xkb_layout "us,lv,canary,semimak,graphite"
    xkb_options "grp:shifts_toggle" # Technically not required to reproduce, but is necessary to actually notice, obviously
}
```

- **Description:**
Adding any more than 4 xkb layouts causes any further ones to be ignored. The "layout" can even contain bogus content, and it won't cause an error, simply skipping it.

**Comment by kennylevinsen** [comment]
This is a libxkbcommon limitation. See https://github.com/xkbcommon/libxkbcommon/issues/311
