### ISSUE TITLE
Sway does not start with a Vulkan renderer on RADV

### ISSUE THREAD

**Issue by TakinaLisa** [swaywm/sway#7835]
- **Sway Version: 1.8.1**

- **Debug Log: https://pastebin.com/yiwqY6Rp**

- **Description:**
Sway doesn't want to turn on when WLR_RENDERER environment variable is set to "vulkan".

**Comment by emersion** [comment]
amdgpu doesn't support format modifiers on this hw.

**Comment by bl4ckb0ne** [comment]
See https://gitlab.freedesktop.org/mesa/mesa/-/issues/5882

`POLARIS10` is GFX8 [1]

[1]: https://www.x.org/wiki/RadeonFeature/#radeongraphicscomputehardware
