### ISSUE TITLE
Differentiate between app_ids that start the same

### ISSUE THREAD

**Issue by josecastillolema** [swaywm/sway#7838]
### Please fill out the following:
- **Sway Version:**
  - 1.8.1

- **Description:**
  I have two applications that start the same:
   - `org.gnome.Nautilus`
   - `org.gnome.NautilusPreviewer`

  I have `org.gnome.Nautilus` assigned to workspace 0 and I **do not have** any assignments for `org.gnome.NautilusPreviewer`:
  ```
  assign [app_id="org.gnome.Nautilus"]     → workspace 0
  ```

  However, when I start `org.gnome.NautilusPreviewer` it gets assigned to workspace 0, which I did not ask for:
  ```
  flatpak run org.gnome.NautilusPreviewer teste    # gets assigned to workspace 0, even with no corresponding assignment
  ```

My guess is that Sway is only taking into consideration the start of the _app_id_ and not the full _app_id_.

**Comment by emersion** [comment]
The string is a regex IIRC. Maybe try `^org\.gnome\.Nautilus$`?

**Comment by josecastillolema** [comment]
Thanks @emersion !
That did the trick.
