### ISSUE TITLE
Failure to set up reverse PRIME for the connectors wired to the dGPU

### ISSUE THREAD

**Issue by Omrigan** [swaywm/sway#7846]
Hi,

I am an owner of the laptop with an unpleasant GPU configuration. The laptop is ThinkPad X1 Extreme Gen 5, it has Alder Lake and RTX 3070 (Ampere), and external connectors are wired to the dGPU.

Findings on the internet suggested I need to have the following set of environment variables to make it work.
```
export XWAYLAND_NO_GLAMOR=1
export WLR_NO_HARDWARE_CURSORS=1
export WLR_DRM_DEVICES=/dev/dri/card1:/dev/dri/card0
export DRI_PRIME=1
```
However, the two kinds of tearing appears:
1. Ever present black squares
2. Only on opened windows, black and grey-ish squares 

I've found two kinds of workaround:
1. Apply the patch (was recently removed from Hyprland) [1]
2. `export WLR_RENDERER=vulkan`

However, both of that fail:
1. The patch fixes the first kind of tearing, but the second one is still there
2. Setting the vulkan renderer fails to modeset the external displays at all.

What can I do to make external displays usable? AFAIK, nouveau for Ampere is not very usable at this moment.

[1]: https://github.com/hyprwm/Hyprland/pull/3957/commits/5e3f20908a56e9ca2dd76f6dac8474024b1cfd72#diff-15eea4d627f9ea586d14f5356c523040de2fd0012b87909db9b2080aaee5e3e5

### Please fill out the following:
 - **Sway Version:** 1.9-dev-bc7d15d6 - latest main at the time of writing
 - Also, tried with sway=1.8.1 and wlroots=0.17 (with patch applied), same thing

- **Debug Log:** Both logs are at https://gist.github.com/Omrigan/684d81412e07bf935c32586f723fd5d5

- **Config:** default

**Comment by Omrigan** [comment]
> Proprietary NVIDIA drivers are not officially supported.

Yeah, I know that. I'd be happy not to use it, but the hardware configuration makes me.

Anyway, if there are any ideas what else I could try, I'd appreciate it.

**Comment by bl4ckb0ne** [comment]
Report the issue to nvidia, pray for improvements in Optimus.
