### ISSUE TITLE
assign/for_window does not expand variables

### ISSUE THREAD

**Issue by zDEFz** [swaywm/sway#7850]
### Please fill out the following:
- **Sway Version:** sway version 1.8.1
  - `swaymsg -t get_version` or `sway -v`

- **Debug Log:**
**on demand**

- **Configuration File:**
Refer to https://github.com/i3/i3/discussions/4660#discussioncomment-1613552
Sway is not compatible to use that syntax and will just fail to expand the variables

- **Description:**

As in what I actually use in i3:

```
set $as assign
set $fw for_window
set $c class
set $R DP-1
set $ws01-R "2"
workspace $ws01-R output $R
$as [$c="^firefox(-nightly)?$"] $ws01-R # take either firefox or firefox nightly
```

Sway fails to expand the variables.
Could be anything.

Another sample

```
$fw [$c="^.*steam_app_[0-9]+$"] $mtw $ws04-R
```

related: #7718

**Comment by zDEFz** [comment]
Hey, is there any update regarding this issue?

**Comment by carlfarrington** [comment]
damn. this has just burned me too :-(
```
for_window [app_id="chrome.*"] move up, resize set height ${CHROMIUM_HEIGHT} px
for_window [app_id="wlfreerdp"] move down, resize set height ${RDP_HEIGHT} px
```

Doesn't work. These are in an EnvironmentFile of the systemd unit. Any ideas for workarounds?

**Comment by kennylevinsen** [comment]
OP is talking about sway variables, not environment variables.

As a workaround you could shell out to swaymsg, in which case the shell will expand environment variables: `exec swaymsg for_window ... ${RDP_HEIGHT} px`.

**Comment by carlfarrington** [comment]
> OP is talking about sway variables, not environment variables.
> 
> As a workaround you could shell out to swaymsg, in which case the shell will expand environment variables: `exec swaymsg for_window ... ${RDP_HEIGHT} px`.

Environment variables are fine. It's variable expansion of any sort in for_window.
For example, I started with:
```
set $rdp_height ${RDP_HEIGHT}
for_window  ... $rdp_height
```
but of course it was no good.

What I have ended up doing is putting a pre-launch script in my systemd unit which replaces placeholders in a template config.

**Comment by zDEFz** [comment]
> > OP is talking about sway variables, not environment variables.
> > As a workaround you could shell out to swaymsg, in which case the shell will expand environment variables: `exec swaymsg for_window ... ${RDP_HEIGHT} px`.
> 
> Environment variables are fine. It's variable expansion of any sort in for_window. For example, I started with:
> 
> ```
> set $rdp_height ${RDP_HEIGHT}
> for_window  ... $rdp_height
> ```
> 
> but of course it was no good.
> 
> What I have ended up doing is putting a pre-launch script in my systemd unit which replaces placeholders in a template config.

I tested sway variables:

```bash
$fw [$a="org.pulseaudio.pavucontrol"] $fe, $rs $foo bar
whereas fe is floating enable, rs is resize set and $foo $bar is 1280 px 1024 px set in config

config:

set $foo 1280 px
set $bar 1024 px
```

**Comment by carlfarrington** [comment]
> > > OP is talking about sway variables, not environment variables.
> > > As a workaround you could shell out to swaymsg, in which case the shell will expand environment variables: `exec swaymsg for_window ... ${RDP_HEIGHT} px`.
> > 
> > 
> > Environment variables are fine. It's variable expansion of any sort in for_window. For example, I started with:
> > ```
> > set $rdp_height ${RDP_HEIGHT}
> > for_window  ... $rdp_height
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but of course it was no good.
> > What I have ended up doing is putting a pre-launch script in my systemd unit which replaces placeholders in a template config.
> 
> I tested sway variables WORKING:
> 
> ```shell
> ####
> set $fw for_window
> set $a app_id
> set $rs resize set
> set $foo 1280 px
> set $bar 1024 px
> 
> $fw [$a="org.pulseaudio.pavucontrol"] floating enable, $rs $foo bar
> ```
> 
> Therefore, my issue was fixed over time. ...
> 
> @carlfarrington do you want me to close this issue, so you can open your own, as it appears my issue with sway variables had been resolved.

hmm, maybe it's just a problem in the version of sway I have on Raspberry Pi OS. It's sway 1.7. I tested that the env variable makes it into the config, but the size didn't work.

**Comment by zDEFz** [comment]
> > > > OP is talking about sway variables, not environment variables.
> > > > As a workaround you could shell out to swaymsg, in which case the shell will expand environment variables: `exec swaymsg for_window ... ${RDP_HEIGHT} px`.
> > > 
> > > 
> > > Environment variables are fine. It's variable expansion of any sort in for_window. For example, I started with:
> > > ```
> > > set $rdp_height ${RDP_HEIGHT}
> > > for_window  ... $rdp_height
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > but of course it was no good.
> > > What I have ended up doing is putting a pre-launch script in my systemd unit which replaces placeholders in a template config.
> > 
> > 
> > I tested sway variables WORKING:
> > ```shell
> > ####
> > set $fw for_window
> > set $a app_id
> > set $rs resize set
> > set $foo 1280 px
> > set $bar 1024 px
> > 
> > $fw [$a="org.pulseaudio.pavucontrol"] floating enable, $rs $foo bar
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Therefore, my issue was fixed over time. ...
> > @carlfarrington do you want me to close this issue, so you can open your own, as it appears my issue with sway variables had been resolved.
> 
> hmm, maybe it's just a problem in the version of sway I have on Raspberry Pi OS. It's sway 1.7. I tested that the env variable makes it into the config, but the size didn't work.

You are correct. the size didn't work! 
What does however work is

`$fw [$a="org.pulseaudio.pavucontrol"] floating enable, resize set 800px 600px`
This is so strange.

**Comment by carlfarrington** [comment]
I don't quite understand. You are saying the variables only work for sizes if you first start with fixed constants, start sway, and then change them into variables and reload the config? I don't really understand. It sounds like it's broken and you've found an obscure way in which the variables can be realised, but that most of the time they don't work.

Anyway I have my workaround - as I said, I have a script which takes a template config and uses sed to replace placeholders on unit startup.

**Comment by zDEFz** [comment]
> I don't quite understand. You are saying the variables only work for sizes if you first start with fixed constants, start sway, and then change them into variables and reload the config? I don't really understand. It sounds like it's broken and you've found an obscure way in which the variables can be realised, but that most of the time they don't work.
> 
> Anyway I have my workaround - as I said, I have a script which takes a template config and uses sed to replace placeholders on unit startup.

I guess, then I could close this issue.
