### ISSUE TITLE
Regression: zwlr_layer_surface_v1.configure event before surface is committed

### ISSUE THREAD

**Issue by WhyNotHugo** [swaywm/sway#7855]
### Please fill out the following:
- **Sway Version:**
  - current master, bf2b79b2845a070d84aafaf95e6cfcf9af7eeb9b

- **Debug Log:**
  - https://paste.sr.ht/~whynothugo/239130eff889f2cf99552c695969f989193af76d

- **Configuration File:**
  - `exec shotman --capture output`

Note: I used the following config when generating the log:

```
exec sh -c "shotman --capture window; swaymsg exit"
```

- **Stack Trace:**

No crash

- **Description:**

Sway is now sending a `configure` event to a surface before it has been committed.
This makes [shotman](https://shotman.whynothugo.nl/) crash because it never occurred to me to handle this, but this makes for a good reproduction example.

It looks like `wlroots` prints an error warning about this:

```
00:00:00.085 [wlr] [types/wlr_layer_shell_v1.c:295] A configure is sent to an uninitialized wlr_layer_surface_v1 0x7f332fac0390
00:00:00.085 [wlr] [types/wlr_layer_shell_v1.c:295] A configure is sent to an uninitialized wlr_layer_surface_v1 0x7f332169d6f0
00:00:00.085 [wlr] [types/wlr_layer_shell_v1.c:295] A configure is sent to an uninitialized wlr_layer_surface_v1 0x7f332fac0390
00:00:00.085 [wlr] [types/wlr_layer_shell_v1.c:295] A configure is sent to an uninitialized wlr_layer_surface_v1 0x7f332169d6f0
00:00:00.089 [wlr] [types/wlr_layer_shell_v1.c:295] A configure is sent to an uninitialized wlr_layer_surface_v1 0x7f332169d6f0
```

**Comment by WhyNotHugo** [comment]
I haven't been able to bisect this properly yet. I started and realized halfway that I'd screwed up the associated wlroots version at some point, so have to start over.

**Comment by rpigott** [comment]
I use a series of tags to bisect sway, by tagging sway commits with the wlroots commits they follow then using an alias to find a working wlroots commit for whatever sway commit I land on.

```
$ git config alias.wlrfind
describe --tags --abbrev=0 --match=wlroots/*
$ git wlrfind HEAD                                                                                                                                                                                                                
wlroots/c85838892d56
$ git wlrfind HEAD~20                                                                                                                                                                                                    
wlroots/1c24b1182ba3
```
If you think it would help you, you can fetch the tags I use:

```
$ git fetch https://github.com/rpigott/sway 'refs/tags/wlroots/*:refs/tags/wlroots/*'
```

Anyway this is probably the result of [1], we'll need to update `handle_layer_shell_surface` appropriately.

[1] https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4265/diffs?commit_id=e8413660686bf94322799470ef5b109ea4580cc9

**Comment by WhyNotHugo** [comment]
I had a peek at this, but I think it's a bit beyond my current understanding of wlroots/sway.

The `new_surface` event was previously raised at an earlier time? Or is the event entirely new?

**Comment by vyivel** [comment]
Closed by https://github.com/swaywm/sway/pull/7909.
