### ISSUE TITLE
Focus follows mouse over outputs with `focus_follows_mouse no`

### ISSUE THREAD

**Issue by acrisci** [swaywm/sway#786]
Focus should not follow mouse over outputs with `focus_follows_mouse no` to be compatible with the i3 behavior of this config directive.

**Comment by SirCmpwn** [comment]
This is a limitation with wlc. Ping @Cloudef.

**Comment by acrisci** [comment]
Some issues with this are discussed here: [wlc#32](https://github.com/Cloudef/wlc/issues/32)
