### ISSUE TITLE
Sway shutdown handler

### ISSUE THREAD

**Issue by tbaumann** [swaywm/sway#7869]
**Description:**

It would be nice to have `exec` commands in the config file that are executed upon shutdown of sway.

Specifically I like to improve the systemd integration like it is proposed in https://github.com/swaywm/sway/wiki/Systemd-integration.
The issue there is that the session target is only started and never stopped.

I added a workaround to stop the `sway-session.target` on shutdown.
```bash
exec swaymsg -t subscribe '["shutdown"]' && systemctl --user stop sway-session.target
```
But that is honestly super kludgy.
A bit more sane and reliable would be to have
```bash
exec_on_shutdown systemctl --user stop sway-session.target
```
Or `exec_exit` because the term shutdown could be a bit misleading.

**Comment by emersion** [comment]
Duplicate of https://github.com/swaywm/sway/issues/7128
