### ISSUE TITLE
eDP-1 black screen with linux-6.6.7

### ISSUE THREAD

**Issue by fabro122** [swaywm/sway#7875]
sway version 1.8.1 on Archlinux
Debug Log: https://drive.proton.me/urls/BEW6NPBAH0#02Slrwxq4R8E
Configuration File: https://drive.proton.me/urls/9TA9WKGYGM#0HVMsb0iL3jA
swaymsg -t get_outputs: https://drive.proton.me/urls/Q4R0RYJ4FR#IOKejgreoWLb
Laptop: Yoga 7 gen 7 14"

**The Problem:**
After upgrading to linux-6.6.7 eDP-1 (the Laptop screen) turns black immediately after starting sway (other screens over HDMI for example still work). Except for showing nothing (as I said black screen) everything seems to work as expected. wdisplays shows everything fine (on the other screen) and you can focus the workspace on eDP-1, open a terminal and poweroff the laptop for example.
This happens no matter if another screen is initially connected via HDMI or not.
Even after exiting sway, eDP-1 stays off.

**To reproduce:**
1. Install linux 6.6.7
2. Boot up (screen is still working)
3. exec sway (eDP-1 turns black)

**Workaround:**
Downgrade Linux to previous version, in my case to linux-6.6.1

**Comment by kennylevinsen** [comment]
From our perspective the modeset succeeded and the output is active. Considering that it happened after a kernel upgrade, it sounds like a driver bug.

You might find more if you enable and collect drm debug output from your kernel, but I doubt there's anything we can do. Closing for now.
