### ISSUE TITLE
Sway Crash latest arch version

### ISSUE THREAD

**Issue by Riptils** [swaywm/sway#7885]
### Please fill out the following:
- **Sway Version:**
  - `1.9-dev-bbabb9aa (Dec 23 2023, branch 'master')`

- **Debug Log:**
  - [logs](https://gist.github.com/Riptils/8e4289b240ddfdf59b481e0830700185)

- **Configuration File:**
  - [dotfiles(sway config and others)](https://gitlab.com/Riptils/dotfiles/-/tree/main)

- **Description:**
  - I updated on archlinux by running the `paru -Syu` command, rebooted, noticed a crash on TTY1, ran the debug on TTY2. Then I downgraded wlroots and sway, which worked again, so I reported the problem.

**Comment by GreyXor** [comment]
Should now be fixed since #7884's merged. Recompile everything with `paru -Sd wlroots-git sway-git` and try again.

**Comment by GreyXor** [comment]
The recent breaking changes in wlroots have been addressed and resolved with the #7884 PR. To incorporate the fixes, please recompile using the command paru -S --rebuild wlroots-git sway-git and proceed with your testing again.

**Comment by Riptils** [comment]
Thanks, that solved my problem!
