### ISSUE TITLE
Implement --unsupported-gpu using environment variables

### ISSUE THREAD

**Issue by jefer94** [swaywm/sway#7887]
https://github.com/swaywm/sway/issues/6760

**Comment by andraxin** [comment]
Given the general attitude around here, this is not going to happen,
unless you submit a patch **and** manage to convince reviewers
to actually approve and merge.

I'd suggest a simple wrapper instead, which one could create with
the following commands (adjust the `SWAY_*` variables as needed):
```sh
SWAY_ORIG=${SWAY_ORIG:-$(which sway)}
SWAY_WRAP=${SWAY_WRAP:-/usr/local/bin/sway}
echo exec $SWAY_ORIG --unsupported-gpu \"\$@\" \> \$HOME/.sway/log 2\>\&1 | sudo tee $SWAY_WRAP
sudo chmod +x $SWAY_WRAP
hash -r  # alternatively, `rehash` or simiilar, depending on your shell...
```
The redirection is not necessary, I just like have it that way.

Of course, `PATH` must include `$(dirname $SWAY_WRAP)`  **before**
`$(dirname $SWAY_ORIG)` for this to work...

**Comment by jefer94** [comment]
I don't understand the reasons, actually all developer works with environment variables all days, it's normal, and the the implementation is easy to be done, but I won't write anything until a maintainer tell me what is the decision that he will take, I would rather that this fix will not be added before I waste my time. I don't understand why the unix ecosystem insist in their products be hostile towards the users, exists a thing called user experience

**Comment by jefer94** [comment]
Actually, the solution of read a environment variable is also a trash but it will solve this issues for the power users

**Comment by emersion** [comment]
This has been rejected before, and I see no reason to change our decision here.

**Comment by jefer94** [comment]
Great, you chose ignore the half of users, that is literally have "no reason" to do it, whatever, whoever be affected should be better that switch to [Hyprland](https://hyprland.org/), I'm guessing that should be mentally exhausting get an environment variable and add a conditional
