### ISSUE TITLE
`map_to_output` results in input devices being always disabled

### ISSUE THREAD

**Issue by alebastr** [swaywm/sway#7890]
- **Sway Version:**
  - `sway version 1.9-dev-0aceff74 (Dec 29 2023, branch 'master')`

- **Configuration File:**
```
input "1386:21110:Wacom_HID_5276_Finger" {
    events enabled
    map_to_output eDP-1
}
```

- **Description:**
 
After https://github.com/swaywm/sway/commit/7036769bea886ab1f9d627785f14cea9e25b16f7 any input device with `map_to_output` configured will be disabled on start and needs to be enabled manually later.

The logic before the change resulted in calling `sway_input_configure_libinput_device`, which checked if the new mapping configuration is valid and set the device state with `set_send_events` accordingly.

The new logic skips full reconfiguration and does only `seat_apply_input_mapping`. Notably, it does not include enabling/disabling the device if necessary and sending an IPC event.

- **Workaround:**

`exec swaymsg input <identifier> events enabled` in the config

**Comment by emersion** [comment]
Does this help? https://github.com/swaywm/sway/pull/7891
