### ISSUE TITLE
Swaymsg: add a way to get the current location of the config file

### ISSUE THREAD

**Issue by godalming123** [swaywm/sway#7894]
A command in swaymsg that returns an absolute path to the current config eg:

`swaymsg get_config_location` - /home/example/.config/sway/config

This functionality would be useful because it allows for sway configs to update themselves even if sway is launched with a config in a different location. For example someone who has different keyboard layouts can easily use a keybinding which activates a sed command to change their keyboard layout.

**Comment by emersion** [comment]
Updating the config file is not the intended way to change settings at runtime (such as the keyboard layout). Instead, you can use `swaymsg`.
