### ISSUE TITLE
Crash in handle_dissociate() during output enable, XWayland, git:22d0dd8b

### ISSUE THREAD

**Issue by alxchk** [swaywm/sway#7895]
### Please fill out the following:
- **Sway Version:**
  - `sway version 1.9-dev-22d0dd8b (Dec 26 2023, branch 'HEAD')`

- **Debug Log:**
   Can't reproduce with debug log enabled

- **Stack Trace:**
[crash-gdb-bt.txt](https://github.com/swaywm/sway/files/13827700/crash-gdb-bt.txt)

- **Description:**
 Crash happens with some probability with next chain:
 1. Workspace: docked laptop + display. lid closed:
      Output DP-6 (focused), Position: 0,0
      Output eDP-1 (disabled)
 2. VirtualBox started (only app which uses XWayland)
 3. VM started
 4. At same time lid opened, eDP-1 enabled with command `swaymsg output eDP-1 enable`
 5. Crash happend

**Comment by vyivel** [comment]
Should be fixed in wlroots now. Please reopen if the crashes persist.

**Comment by kennylevinsen** [comment]
User report of this happening on 1.9 with this SDL2 client: https://paste.linux.chat/?696d0fec20644a98#2MvsE3JXB6iW7RfYfxySbnWKXqr5fmvZ75bh6ApyxCYp

Reproduces locally, doesn't reproduce on master. Not sure what the fix was, but it might need a backport.

**Comment by kennylevinsen** [comment]
I'm told https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4524 is the fix, which should be included in wlroots 0.17.2

**Comment by KenMacD** [comment]
As a confirmation, updating to wlroots `63e2f2e28fc1f037a0117bb85d37f84397345c71` (latest 0.17 commit as of writing) fixed these crashes for me. Before it would crash every time I started `sdl-freerdp`.

**Comment by emersion** [comment]
wlroots 0.17.2 fixes this crash.
