### ISSUE TITLE
Not possible to screenshare with render_bit_depth 10 set

### ISSUE THREAD

**Issue by richardtatum** [swaywm/sway#7898]
### Please fill out the following:
- **Sway Version:**
  - `sway version 1.8.1`

- **Debug Log:**
  - [sway.log](https://github.com/swaywm/sway/files/13833478/sway.log)

- **Description:**
  - Attempting to screen share (in either Firefox or Chrome with `--enable-usermedia-screen-capturing`) when `render_bit_depth 10` is set in `~/.config/sway/config.d/output` fails.
  - Removing this line allows screensharing to work as expected.

- **Notes:**
  - Using the following relevant software versions:
    - `xdg-desktop-portal 1.18.2-1`
    - `xdg-desktop-portal-gtk 1.15.1-1`
    - `xdg-desktop-portal-wlr 0.7.0-2`
    - `pipewire 1:1.0.0-2`
  - `WAYLAND_DISPLAY` and `XDG_CURRENT_DESKTOP=sway` return correctly when running `systemctl --user show-environment`

 Let me know if there is anything else I can provide.

**Comment by emersion** [comment]
This happens because Firefox/Chrome expect 8 bpc. Firefox/Chrome need to add support for more formats, or a Pipewire element needs to be placed in-between xdpw and Firefox/Chrome to convert. In any case, not a Sway bug.

**Comment by richardtatum** [comment]
Thanks for the response @emersion.

I was reading an issue from the `xdg-desktop-portal-wlr` repo where someone had mentioned having screen sharing working with 10 bpc using another DE/WM (and where I originally stumbled across the fix for Sway) so I thought it would be worth raising. 

If that is not the case, I’ll drop a note in that issue thread too.

**Comment by emersion** [comment]
The specific compositor shouldn't matter here, all of the code responsible for screen sharing is shared by all compositors in wlroots.
