### ISSUE TITLE
Sway can be reliably crashed by wofi with negative height

### ISSUE THREAD

**Issue by savchenko** [swaywm/sway#7915]
- **Sway Version:**

v1.5

- **Debug Log:**

https://gist.github.com/savchenko/ae12ca7dba1cf1eff510ca6ac941f1b4

- **Configuration File:**

In its entirety:
```sh
set $term "foot"
set $mod Mod4
bindsym $mod+Return exec $term
```

- **Stack Trace:**

N/A, (probably) most relevant snippet from the log file:
```
sway: sway/input/seat.c:1245: seat_set_focus_layer: Assertion `layer->mapped' failed.
 err: wayland.c:1116: failed to read events from the Wayland socket: Broken pipe
 err: wayland.c:1602: failed to roundtrip Wayland display: Broken pipe
 err: wayland.c:1602: failed to roundtrip Wayland display: Broken pipe
 err: wayland.c:1602: failed to roundtrip Wayland display: Broken pipe
warn: terminal.c:1568: slave exited with signal 1 (Hangup)
 err: wayland.c:1567: failed to flush wayland socket: Broken pipe
info: main.c:579: goodbye
```

- **Description:**

1. Run the following: `wofi --fork --dmenu --width 1 --height -1`
1. Click on the `wofi` window.
1. Sway crashes.

**Comment by vyivel** [comment]
This is also a Wofi bug; it shouldn't try to create a surface with negative height (which in this case overflows to UINT32_MAX).

**Comment by vyivel** [comment]
Fixed in https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4519.
