### ISSUE TITLE
Linux Kernel 6.7 & Nouveau & Sway GSP Error: mmu fault queued

### ISSUE THREAD

**Issue by cartok** [swaywm/sway#7921]
I actually don't know if it's an issue for **nouveau** or for **sway**.
Link to other (duplicated) issue: https://gitlab.freedesktop.org/mesa/mesa/-/issues/10475

### System information
> inxi -GSC -xx
```
System:
  Host: local Kernel: 6.7.0-zen3-1-zen arch: x86_64 bits: 64 compiler: gcc
    v: 13.2.1 Desktop: sway v: 1.8.1 dm: N/A Distro: Arch Linux
CPU:
  Info: 8-core model: Intel Core i9-9900K bits: 64 type: MT MCP
    arch: Coffee Lake rev: D cache: L1: 512 KiB L2: 2 MiB L3: 16 MiB
  Speed (MHz): avg: 5000 high: 5013 min/max: 800/5000 cores: 1: 5000 2: 5005
    3: 5013 4: 5000 5: 5001 6: 5000 7: 5000 8: 4996 9: 5000 10: 4999 11: 5000
    12: 5001 13: 5000 14: 5000 15: 5000 16: 4999 bogomips: 115200
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: NVIDIA AD104 [GeForce RTX 4070] vendor: Gigabyte driver: nouveau
    v: kernel arch: Lovelace pcie: speed: 8 GT/s lanes: 16 ports:
    active: DP-1,DP-2 empty: DP-3,HDMI-A-1 bus-ID: 01:00.0 chip-ID: 10de:2786
  Device-2: Sunplus Innovation Sandberg USB Webcam Pro
    driver: snd-usb-audio,uvcvideo type: USB rev: 2.0 speed: 480 Mb/s lanes: 1
    bus-ID: 1-5.1:5 chip-ID: 1bcf:2650
  Display: wayland server: Xwayland v: 23.2.4 compositor: sway v: 1.8.1
    driver: gpu: nouveau d-rect: 5360x1440 display-ID: 1
  Monitor-1: DP-1 pos: right model: Gigabyte M34WQ res: 3440x1440 dpi: 109
    diag: 867mm (34.1")
  Monitor-2: DP-2 pos: primary,left model: Dell AW2521HFL res: 1920x1080
    dpi: 90 diag: 623mm (24.5")
  API: EGL v: 1.5 platforms: device: 0 drv: nouveau device: 1 drv: swrast
    gbm: drv: nouveau surfaceless: drv: nouveau wayland: drv: nouveau x11:
    drv: nouveau
  API: OpenGL v: 4.5 compat-v: 4.3 vendor: mesa v: 23.3.3-arch1.1 glx-v: 1.4
    direct-render: yes renderer: NV194 device-ID: 10de:2786
  API: Vulkan Message: No Vulkan data available.
```

- OS: Arch Linux
- GPU: 01:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD104 [GeForce RTX 4070] [10de:2786] (rev a1)
- Kernel version: Linux local 6.7.0-zen3-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Sat, 13 Jan 2024 14:36:54 +0000 x86_64 GNU/Linux
- Mesa version: OpenGL version string: 4.3 (Compatibility Profile) Mesa 23.3.3-arch1.1
- Desktop manager and compositor: sway version 1.8.1

### Problem Description

I've tried to switch from using my APU to my RTX 4070 using **nouveau**, now that the **GSP** firmware is live, but it's unstable on my system. From time to time sway exists, the program does not finish, I don't get the debug output from sway when I run it with `sway -d > foo.log`, but I get some other info:
```
Jan 21 14:23:37 local kernel: nouveau 0000:01:00.0: gsp: mmu fault queued
Jan 21 14:23:37 local kernel: nouveau 0000:01:00.0: gsp: rc engn:00000001 chid:16 type:31 scope:1 part:233
Jan 21 14:23:37 local kernel: nouveau 0000:01:00.0: fifo:c00000:0002:0010:[sway[915]] errored - disabling channel
Jan 21 14:23:37 local kernel: nouveau 0000:01:00.0: sway[915]: channel 16 killed!
Jan 21 14:23:37 local systemd[1]: Created slice Slice /system/systemd-coredump.
```

Not easily reproducible, happens after around an hour or so.

### Further System Information
I install nouveau like this:
```sh
# Vulkan is not yet working with nouveau, still installing `vulkan-mesa-layers`.
# See: https://wiki.archlinux.org/title/nouveau
pacman -S --needed --noconfirm \
  mesa \
  libva-mesa-driver \
  mesa-vdpau \
  vulkan-mesa-layers

# Add early loading
declare REQUIRED_MODULES="nouveau"
declare MODULES=$(rg $REQUIRED_MODULES $(readlink /etc/mkinitcpio.conf))

if ! [[ $MODULES =~ $REQUIRED_MODULES ]]; then
  sd "(^MODULES=\()" "\$1 $REQUIRED_MODULES" $(readlink /etc/mkinitcpio.conf)
fi

mkinitcpio -P linux-zen
```

The early loading works. I disabled the APU (i915) in the BIOS. No other drivers are loaded, not **i915** nor **nvidia** and so far everything seems to run fine (chrome, glxgears, eglgears).

### Possible Trace
Sway does is not detecting that the 34" Gigabyte Screen actually has 144 Hz, it only detects 100 Hz for the default resolution:
> swaymsg -t get_outputs
```
Output DP-1 'GIGA-BYTE TECHNOLOGY CO., LTD. M34WQ 0x000002FF' (focused)
  Current mode: 3440x1440 @ 59.973 Hz
  Position: 1920,0
  Scale factor: 1.000000
  Scale filter: nearest
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 1 - linux
  Max render time: off
  Adaptive sync: disabled
  Available modes:
    3440x1440 @ 59.973 Hz
    3440x1440 @ 99.982 Hz
    2560x1440 @ 119.998 Hz
    2560x1440 @ 59.951 Hz
    2560x1080 @ 143.945 Hz
```

The sway output configuration looks like this:
```
output "GIGA-BYTE TECHNOLOGY CO., LTD. M34WQ 0x000002FF" {
  scale 1
  pos 1920 0
}

output "Dell Inc. AW2521HFL DDR4M23" {
  mode 1920x1080@143.981Hz
  pos 0 0
  scale 1
}
```

**Comment by bl4ckb0ne** [comment]
I don't think Lovelace is supported by nouveau but I might be wrong. Last time I checked they were barely supporting Ampere (the previous gen).

**Comment by cartok** [comment]
Oh boy, I should've checked that before. Sorry for the fuzz. Thanks for the reply.  
Here are the references for anyone else frustrated:
- https://nouveau.freedesktop.org/FeatureMatrix.html
- https://nouveau.freedesktop.org/FeatureMatrix.html

**Comment by ItsMeDek** [comment]
> Oh boy, I should've checked that before. Sorry for the fuzz. Thanks for the reply. Here are the references for anyone else frustrated:
> 
>     * https://nouveau.freedesktop.org/FeatureMatrix.html
> 
>     * https://nouveau.freedesktop.org/FeatureMatrix.html

The references you've provided state that Ada Lovelace IS supported by nouveau, so I'm not sure what you mean by that?

**Comment by cartok** [comment]
Thanks. Yes but not the 2D acceleration, thought it might cause the issue, for example in chrome rendering. But I actually have no idea if those unsupported topics matter or not to have it fully functioning.

If not, then I wonder if this is a common issue or not.

**Comment by ItsMeDek** [comment]
AFAIK if you're getting an MMU fault, then 2D acceleration shouldn't matter, I'd reopen it.

**Comment by Zambieslar** [comment]
Do  you guys know if there is a workaround? I'm running Hyprland and experiencing the same issues using NVK drivers.

**Comment by jpxaraujo** [comment]
> Do you guys know if there is a workaround? I'm running Hyprland and experiencing the same issues using NVK drivers.

Today I tested Fedora 40 beta sway spin, and it has the same problem.

**Comment by whitespace-v** [comment]
same with Arch + Hyprland running on:
System:
  Host: ArchLinux Kernel: 6.9.3-arch1-1 arch: x86_64 bits: 64 compiler: gcc
    v: 14.1.1
  Desktop: Hyprland v: 0.40.0 dm: N/A Distro: Arch Linux
CPU:
  Info: 12-core (8-mt/4-st) model: 12th Gen Intel Core i7-12700K bits: 64
    type: MST AMCP arch: Alder Lake rev: 2 cache: L1: 1024 KiB L2: 12 MiB
    L3: 25 MiB
  Speed (MHz): avg: 3872 high: 4700 min/max: 800/4900:5000:3800 cores:
    1: 4700 2: 4700 3: 4567 4: 4700 5: 4700 6: 800 7: 4626 8: 800 9: 4588
    10: 800 11: 4700 12: 4610 13: 4684 14: 4699 15: 4689 16: 4688 17: 3601
    18: 3601 19: 3599 20: 3600 bogomips: 144440
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: Intel AlderLake-S GT1 vendor: Gigabyte driver: i915 v: kernel
    ports: active: none empty: DP-1,HDMI-A-1,HDMI-A-2 bus-ID: 00:02.0
    chip-ID: 8086:4680
  Device-2: NVIDIA GA104 [GeForce RTX 3060 Ti Lite Hash Rate]
    driver: nouveau v: kernel arch: Ampere pcie: speed: 16 GT/s lanes: 16 ports:
    active: DP-2,DP-3,HDMI-A-3 empty: DP-4 bus-ID: 01:00.0 chip-ID: 10de:2489
  Display: wayland server: Xwayland v: 24.1.0 compositor: Hyprland v: 0.40.0
    driver: gpu: nouveau display-ID: 1
  Monitor-1: DP-2 model: AF24H1 res: 1920x1080 dpi: 92 diag: 609mm (24")
  Monitor-2: DP-3 model: AF24H1 res: 1920x1080 dpi: 92 diag: 609mm (24")
  Monitor-3: HDMI-A-3 model: MSI MP243X res: 1920x1080 dpi: 92
    diag: 604mm (23.8")
  API: EGL Message: EGL data requires eglinfo. Check --recommends.

**Comment by bl4ckb0ne** [comment]
There's a patch here [1], i encourage you to try it

[1]: https://gitlab.freedesktop.org/drm/nouveau/-/issues/346#note_2413805

**Comment by cartok** [comment]
> There's a patch here [1], i encourage you to try it
> 
> [1]: https://gitlab.freedesktop.org/drm/nouveau/-/issues/346#note_2413805

Unfortunately I already changed to AMD and can't test it 🙏

**Comment by bl4ckb0ne** [comment]
Alright then, I'll close the issue since its not sway.

**Comment by spectrum70** [comment]
I still have this same issue.

**Comment by emersion** [comment]
Please open a new issue if you are hitting a bug.
