### ISSUE TITLE
Sway crashes when fractionally scaled client submits out of bounds viewport src box 

### ISSUE THREAD

**Issue by Ferdi265** [swaywm/sway#7930]
### Please fill out the following:
- **Sway Version:** 1.9.r7273.a4e8533-1 (commit a4e8533)
- **Wlroots Version:** 0.18.0.r6839.98c708618-1 (commit 98c708618)

- **Debug Log:**
  - sway and client debug log: [log.txt](https://github.com/swaywm/sway/files/14030665/log.txt)

- **Configuration File:**
  - sway config: [config.txt](https://github.com/swaywm/sway/files/14028458/config.txt)
  - test client: [client.c.txt](https://github.com/swaywm/sway/files/14028466/client.c.txt)
  - full testcase files: [sway-viewport-crash.tar.gz](https://github.com/swaywm/sway/files/14030662/sway-viewport-crash.tar.gz)

- **Stack Trace:**
  - `bt full` stacktrace: [bt-full.txt](https://github.com/swaywm/sway/files/14030663/bt-full.txt)
  - coredump in testcase files linked above

- **Description:**
  - tested on a screen with 2256x1504 resolution (Framework Laptop 13) and 1.175 scale
  - run the attached test wayland client in sway with another window already open
  - sway will crash after the test client submits an invalid viewport src box
  - (this crash was originally discovered with the fractional scaling branch of `Xwayland` rootful mode, you can also replace the test client with `Xwayland -hidpi :1`)
 
- **Crash Details:**
  - `sway: render/pass.c:23: wlr_render_pass_add_texture: Assertion 'box->x >= 0 && box->y >= 0 && box->x + box->width <= options->texture->width && box->y + box->height <= options->texture->height' failed.`
  - Sway crashes in some cases when a fractionally scaled client submits an out of bounds viewport src box (not exactly sure when)
  - The handler for `wp_viewport_set_source()` in sway actually rejects the invalid viewport, but the bad viewport is still used in the next render for some reason
  - Sway then crashes when the viewport is rejected when rendering the scene
  - This only happens on some scales and on some output sizes, but in situations where it happens it happens reliably. I haven't found the exact circumstances yet

**Comment by Ferdi265** [comment]
I seem to have attached the wrong log file; let me fix that

**Comment by Ferdi265** [comment]
The crash is in wlroots code, so I'm not sure whether sway or wlroots is at fault here.

**Comment by vyivel** [comment]
Closing this is as a wlroots issue: https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3790
