### ISSUE TITLE
Scrolling is buggy (mouse scrolling not touchpad)

### ISSUE THREAD

**Issue by MubinMuhammad** [swaywm/sway#7931]
I have recently updated my Archlinux. Starting from that update till now the scrolling is glitchy.

The best way to describe it, is, when I scroll down on a page let's say, randomly the page goes up for less than a second and starts to work like normal again. This happens pretty often. And it's just frustrating.

It also happens when I'm working in gimp for example. When zooming in on an image, for a split second it zooms out. And then zooms in again.

My software versions:
**Libinput** `1.25.0`.
**Sway** `sway version 0.3.2-26cdeeb (Dec 6 2023, branch 'master') (It's swayfx, by the way)`.
**Kernel** `6.6.12-1-lts`.

**Comment by vyivel** [comment]
Can you reproduce this with _Sway_ and not SwayFX?

**Comment by MubinMuhammad** [comment]
It happens in sway too. Here is the bug in a video. In it I'm scrolling down the whole time but the page stops for a second or goes up by some unit. Here's the video:

https://github.com/swaywm/sway/assets/101094719/1ef96fca-a2dd-4b82-baff-4d0dfbbe79fa

**Comment by Billli11** [comment]
Do you have another mouse to test if it is a hardware problem?

I also have this problem from time to time but only on mouses that used a long while.

And my current mouse have this problem but only with scroll wheel and not the macro button with repeat scrolling mapped.

**Comment by MubinMuhammad** [comment]
let me check.

**Comment by MubinMuhammad** [comment]
It somehow doesn't happend for me anymore! thanks.
