### ISSUE TITLE
Strange artefacts with current latest git versions

### ISSUE THREAD

**Issue by alxchk** [swaywm/sway#7935]
After last updates (somewhere after commits where wl_drm has been deprecated) I observe screen artifacts in specific conditions. I have no logs, and will try describe as precise as I can. Currently i'm at the latest git of sway and wlroots  - f202bc84 and wlroots d1b39b58432c471c16e09103fd2c7850e3c41950.
Kernel 6.7.1, video - WhiskeyLake-U GT2 [UHD Graphics 620]

The artifact looks like flickering between old image and new one. For example, if there was a 22:10 at the waybar clock, it begin to show 22:09 then 22:10 then 22:09 then 22:10 and so on. This is most obvious case to describe how this looks like.

Interesting here, that it reproduced more or less frequently only with `foot` terminal emulator. Symptoms are same -- picture (parts of the view) changed from the old to the new and back, many times. Picture changes forward and backward on some event, like keypress. Workaround is to change workspace to some other and then go back. It may fix situation for some time.
Initially I thought it's an issue just with `foot`, however in very very very rare cases this also happen with bars (waybar or sway tabs). This reproduced after some time, and looks like system load may increase probability of the bug.

I don't have much idea how to collect the logs, because it may be a very long time once this begin to happen.

**Comment by alxchk** [comment]
Will try for a day

**Comment by alxchk** [comment]
Day has passed and so far there are no artifacts. So, likely, patch works

**Comment by vyivel** [comment]
The patch linked above has been merged.
