### ISSUE TITLE
Layer Shell regression: Layershell never releasing mouse again, once it is set to exclusive

### ISSUE THREAD

**Issue by feschber** [swaywm/sway#7936]
Setting the layershell keyboard interactivity to `exclusive` and then `none` makes it impossible to focus windows.
This must be a recent regression possibly related to the `scene_graph` api.

Might be  related: #7918

- **Sway Version:**
  - `swaymsg -t get_version` or `sway -v`
  
I tried to bisect but could not get an exact commit
it must be one of the following
```
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
188811f80861caacd016b857b0d07f6d2d62d15a
5b8b505af5d5925ae9e617ee8f3c7a0f9c43409d
6d7b1321db54155cf78305dbafdcfc7de9b78415
946fc8094559801bc4be629368ac31025d28165a
08c484f46f130aa7e590ef4bcb39d2ceed7160f6
869baff25221e1a1881e9559453faa43f90da33e
b38ed8b4792928dca3e1580e8160792ea41e25c4
bac3ab552683516ee5a09632468cd8de529d311f
6e5fc4c2aafd211323c6037aa868c075852bfe15
9a579666068d62b9354a39941e1ac8c1f4a58093
0639bde9fb5637fbe63c65bfe85660745f159b96
ed2724bd6c83ad3fdc2010b3a1e2f5967f0e8b38
06ad734e70227ad0527fe11b88ad37e93005ce0c
c640c3015f3a7ea2987bd7854d13ff282f90804f
1e018e72b4d57c8f354b9be9686a7a75797cdcab
9c17cba0b29979ae23c4521b884f7419fd558770
0e1a02bf0aad3d743985602b55043c5de019d1f0
5f0801b6f245cc789ea93b9449dd0c573ef36e66
2e53de80bb0f4c93e74ae050fa07e78f18e909d9
We cannot bisect more!
```

- **Description:**
  - Run [Lan Mouse](https://github.com/feschber/lan-mouse) and configure an arbitrary client. Then move the mouse in one of the layershell surfaces on the configured screen edge.
  - There is now no way of focusing any other window.
  
  The relevant code can be found here: https://github.com/feschber/lan-mouse/blob/5cc8cda19d2bef25cff0d767361d0622a8fbf3e8/src/backend/producer/wayland.rs#L407-L487

**Comment by feschber** [comment]
So I did some more testing, and my suspicion seems to be confirmed by https://github.com/wmww/gtk-layer-shell

To reproduce the issue:
```sh
git clone https://github.com/wmww/gtk-layer-shell
cd gtk-layer-shell
meson setup -Dexamples=true build
ninja -C build
build/examples/gtk-layer-demo
```

Now setting keyboard from none to exclusive and back to none makes it impossible to focus any other window until either gtk-layer-demo or sway is killed.

**Comment by ackstorm23** [comment]
@feschber can you test this on Sway 1.9? the lan-mouse software KVM project cited this bug as a blocker for using their app, but the developer has tested with Sway 1.9 and not encountered the bug.

**Comment by feschber** [comment]
> but the developer has tested with Sway 1.9 and not encountered the bug.

That's me, I'm the developer ;)

@Nefsen402 has there been a change since release 1.9? I don't encounter this bug with sway 1.9 from the Arch repos.
I assumed it is still broken because this issue was not updated but from my testing the issue is not present in the release version.

**Comment by Nefsen402** [comment]
> has there been a change since release 1.9?

Yes, a large PR that rewrites and reworks all of sway's rendering code has landed in the current development version. This bug is a result of a regression the PR introduced.

**Comment by ackstorm23** [comment]
> > has there been a change since release 1.9?
> 
> Yes, a large PR that rewrites and reworks all of sway's rendering code has landed in the current development version. This bug is a result of a regression the PR introduced.

Did this bug not make it into 1.9, even though it appeared in git a week or more prior to 1.9's release?

**Comment by emersion** [comment]
The branch point for 1.9 has been created long before 1.9's first RC.

**Comment by WhyNotHugo** [comment]
This is fixed by https://github.com/swaywm/sway/pull/8261
