### ISSUE TITLE
wl_display_roundtrip failed

### ISSUE THREAD

**Issue by sss20081** [swaywm/sway#7939]
Just now, a new software update was pushed to Aur. After the update, sway could not be opened, prompting wl_display_roundtrip failed. Then I downgraded the update package that I suspected was related to the problem, and then sway could be started. sway was the latest version on aur.

`sway --version
sway version 1.8.1`

This is the log [sway.log](https://github.com/swaywm/sway/files/14071538/sway.log)

In addition, several software packages I downgraded are:
![图片](https://github.com/swaywm/sway/assets/62577592/f5d1c885-698f-4885-a227-fc8219182c97)

**Comment by vyivel** [comment]
```
2024-01-27 14:54:06 - [swaybg-git/main.c:571] wl_display_roundtrip failed
```

This error comes from swaybg.

What do you mean by "sway could not be opened"? Does it crash or print any other error?

**Comment by sss20081** [comment]
I didn't use a display manager, I used the login script in archwiki
`if [ -z $DISPLAY ] && [ "$(tty)" = "/dev/tty1" ]; then exec sway fi`
When I log in on tty1, it automatically starts sway, but this time it does not start as usual, and an error is reported.

**Comment by sss20081** [comment]
At first I thought it was a problem with the swaybg package, but the problem still existed after I reinstalled swaybg. So I tried to uninstall swaybg to see if it could solve the problem. This is the error log of sway after I uninstalled swaybg.
[sway_noSwaybg.log](https://github.com/swaywm/sway/files/14071778/sway_noSwaybg.log)

**Comment by sss20081** [comment]
After observing the two log files, I found a keyword "vulkan" that concerned me. I thought that I had just upgraded the software package, so I downgraded the corresponding software package and sway started normally.

**Comment by vyivel** [comment]
Can you try running Sway with `WLR_RENDERER=gles2`?

**Comment by sss20081** [comment]
> Can you try running Sway with `WLR_RENDERER=gles2`?

After setting this environment variable, sway can be started normally.
Can you tell me why setting this environment variable works fine? Also why is this not mentioned in archwiki?

**Comment by emersion** [comment]
GLES2 is the default renderer. Do you have another `WLR_RENDERER` env var with a different renderer set?

**Comment by vyivel** [comment]
```
00:00:00.012 [INFO] [wlr] [util/env.c:25] Loading WLR_RENDERER option: vulkan
```

**Comment by sss20081** [comment]
> GLES2 is the default renderer. Do you have another `WLR_RENDERER` env var with a different renderer set?

In my system there is another WLR_RENDERER
`echo $WLR_RENDERER`
`vulkan`

**Comment by sss20081** [comment]
According to what you said, there is a problem with the vulkan soft翻译类型
文本翻译
原文
在我的系统中，存在另一个WLR_RENDERER
Zài wǒ de xìtǒng zhōng, cúnzài lìng yīgè WLR_RENDERER
​
24 / 5,000
翻译结果
翻译结果
In my system there is another WLR_RENDERER
​
发送反馈
侧边栏
x1.00
ware package. Should I go to their source to submit feedback?
