### ISSUE TITLE
Screen is black for 1s when switching to sway from another tty

### ISSUE THREAD

**Issue by WhyNotHugo** [swaywm/sway#7956]
### Please fill out the following:
- **Sway Version:**
  - sway master (d2f3ef40). This version if like a week old, but I've seen this issue for at least 18 months.

- **Debug Log:**
  - https://paste.sr.ht/~whynothugo/f329c972e3bb2530b769884aad0c14eb6520d8e7
  
- **Configuration File:**
  - `exec foot` (just used to run `swaymsg exit`).
 
- **Stack Trace:**

n/a

- **Description:**
  - Switch to another tty via ctrl+alt+f3
  - Switch back to sway via ctrl+alt+f1

When switching from sway to a non-sway tty, the switch is instantaneous.
When witching from any tty to a sway tty, the screen goes black for a second before rendering.

I might have mixed up the terms `tty` and `vt`. Please let me know if I mixed up, but I trust that the issue is clear anyway.

I don't think that hardware information is relevant here. I can reproduce this on ARM, Intel (on at least two devices) and AMDGPU.

**Comment by WhyNotHugo** [comment]
I tried using:

- `sway` on `tty1`
- `getty` on `tty2`
- `kmscon` on `tty3`
- `sway` on `tty4`

Results:

- Switching from sway to getty or kmscon else is instantaneous.
- Switching from anything to sway has this 1s delay. This includes switching from tty1 to tty4 or viceversa.
- Switching between getty and kmscon back and forth is instantaneous.

So basically the issue is only when sway is the target.

**Comment by WhyNotHugo** [comment]
I tried including `river` into the mix, and it has the same behaviour as sway. Maybe this is a wlroots issue?

**Comment by nekopsykose** [comment]
this vaguely sounds like https://old.reddit.com/r/swaywm/comments/13sp692/switching_to_virtual_console_tofrom_sway_takes_a/ (see emersions comment) but in my case that kinda thing affects switching *from* sway too, not only to it. and yeah, if it's the same thing it's technically a wlroots limitation

**Comment by emersion** [comment]
Yeah… See https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/cb815e88476cac1fb5ce2e369672e4beb4f5d469/backend/drm/backend.c#L107

**Comment by WhyNotHugo** [comment]
Would using the atomic API remove the flickering here? Eg: would the transaction be a no-op if KMS is already in the desired state?

**Comment by emersion** [comment]
Yeah, it should.

**Comment by emersion** [comment]
[wlroots!4552](https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4552) should help. There is also related work in [wlroots!4551](https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4551) and [wlroots!4548](https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4548).

**Comment by WhyNotHugo** [comment]
Thanks for the fix!
