### ISSUE TITLE
Vulkan renderer only renders still images in some games (AMD)

### ISSUE THREAD

**Issue by max-moser** [swaywm/sway#7957]
# Sway Version
`sway version 1.10-dev-c8676fad (Feb  5 2024, branch 'master')`

# Debug Log
`~/git/sway/build/sway/sway -c /etc/sway/config -D legacy-wl-drm -d 2> sway.log`
[sway.log](https://github.com/swaywm/sway/files/14172002/sway.log)

# Configuration File
Default configuration that comes with the [sway 1.8.1-5 package](https://software.manjaro.org/package/sway) (`/etc/sway/config`)

# Description

* Start `sway` with the Vulkan renderer (`WLR_RENDERER=vulkan`, `AMD_VULKAN_ICD=RADV`)
* Launch Elden Ring through `steam-native`
* The game will start and sound will play, but the screen is filled with only a static image (usually white or black right after starting the game)
* Manually toggling fullscreen causes the "current" frame to be displayed

When I use the default renderer, everything runs as expected however.

**Comment by emersion** [comment]
Seems like the Wayland client (Xwayland?) is trying to pass through DMA-BUFs with implicit modifiers, however these are not supported by Vulkan.

```
00:01:21.222 [ERROR] [wlr] [render/vulkan/texture.c:542] Format XR24 (0x34325258) can't be used with modifier INVALID (
0x00FFFFFFFFFFFFFF)
00:01:21.222 [ERROR] [wlr] [types/buffer/client.c:61] Failed to create texture
00:01:21.222 [ERROR] [wlr] [types/wlr_compositor.c:437] Failed to upload buffer
```

**Comment by max-moser** [comment]
Thanks for your [response](https://i.kym-cdn.com/photos/images/original/001/909/636/a8c.png)!

The client should indeed be XWayland, as it's a Windows game running through GE-Proton (8.32, I think).
Should I report this issue on another project like XWayland?

**Comment by max-moser** [comment]
Update: In the meanwhile, I've switched back to Arch where some games wouldn't launch and I encountered issues like [this one for gamescope](https://github.com/ValveSoftware/gamescope/issues/991).
Uninstalling `{,lib32-}amdvlk` seems to have done the trick, now everything runs as expected.

**Comment by bl4ckb0ne** [comment]
Could this be an amdvlk issue?

**Comment by max-moser** [comment]
Definitely looks like it!
I booted into my old system, upgraded all packages and ran into the same issues as originally reported.
After uninstalling `{,lib32-}amdvlk` and rebooting, the game runs fine.
Just like in the gamescope issue, simply setting `AMD_VULKAN_ICD=RADV` alone didn't do the trick.

Closing this issue, and continuing on with only RADV.
