### ISSUE TITLE
Display configuration not respected

### ISSUE THREAD

**Issue by enrico223** [swaywm/sway#7960]
- **Sway Version:** 1.8.1

- **Debug Log:**
https://gist.github.com/enrico223/7e393fc31c49796326ed6f8b0d5b7b00

- **Configuration File:**
 https://gist.github.com/enrico223/7cf6a6e439ab65d9e74daa486783f48f

- **Description:**
Just changed my laptop and transferred the SSD.
1. adjust the config to the new display
2. reload config // log out - log in // reboot
3. new display configuration not working, should be 2560x1600 but it is instead the old 1920x1080

- **Additional information**
On GNOME I have no issue.

**Comment by emersion** [comment]
Sway first applies the 2560x1600 mode, but later on kanshi applies 1920x1080. You likely still have 1920x1080 in your kanshi config.

**Comment by enrico223** [comment]
Silly me, you are right! Changing kanshi config did the trick
