### ISSUE TITLE
Sway seg-faults when run with WLR_RENDERER=vulkan (1.8.1)

### ISSUE THREAD

**Issue by Morris-pi** [swaywm/sway#7966]
This issue has been happening constantly since I last updated sway (2024/01/31) and is particularly frustrating because gles2 is unstable for me

https://gist.github.com/Morris-pi/2949269c258b8a1b346cf3bb75d98594

**Comment by bl4ckb0ne** [comment]
Are you running with the vulkan validation layer?

```
 #0  0x000078e7aa91bd18 n/a (libvulkan_radeon.so + 0x11bd18)
                #1  0x000078e7aa91c0c9 n/a (libvulkan_radeon.so + 0x11c0c9)
                #2  0x000078e79e8e2136 _ZNK10CoreChecks30HasExternalMemoryImportSupportERKN3vvl5ImageE34VkExternalMemoryHandleTypeFlagBits (libVkLayer_khronos_validation.so + 0x14e2136)
                #3  0x000078e79e8f231d _ZNK10CoreChecks23ValidateBindImageMemoryEjPK21VkBindImageMemoryInfoRK11ErrorObject (libVkLayer_khronos_validation.so + 0x14f231d)
                #4  0x000078e79ead1c34 _ZN20vulkan_layer_chassis16BindImageMemory2EP10VkDevice_TjPK21VkBindImageMemoryInfo (libVkLayer_khronos_validation.so + 0x16d1c34)
                #5  0x000078e7ac2a6c5e n/a (libwlroots.so.11 + 0x3ac5e)
                #6  0x000078e7ac2a946c n/a (libwlroots.so.11 + 0x3d46c)
                #7  0x000078e7ac2ce2e2 n/a (libwlroots.so.11 + 0x622e2)
                #8  0x000078e7ac2ce3c2 n/a (libwlroots.so.11 + 0x623c2)
                #9  0x000078e7ac30903e n/a (libwlroots.so.11 + 0x9d03e)
                #10 0x000078e7ac2cda47 wlr_output_commit_state (libwlroots.so.11 + 0x61a47)
```

Are you able to get debug symbols? We can't do much without them.

**Comment by Morris-pi** [comment]
I don't know how to check and I don't know how to get debug symbols

**Comment by Morris-pi** [comment]
I am running with the vulkan validation layer, i do not know what a debug symbol is.

**Comment by emersion** [comment]
Can you reproduce with latest Sway and wlroots commits?

**Comment by zimward** [comment]
i had the same bug on 1.8.1 but can't reproduce it on master. so it seems to be fixed.

**Comment by bl4ckb0ne** [comment]
@Morris-pi are you able to run master to confirm the bug is fixed?

**Comment by Morris-pi** [comment]
I was talking with a vlkan dev and they said that it was to do with this bug on vulkan validation layers: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7318.
It was fixed jan 22nd but not in release yet. Will close when I can confirm that this fixes the issue.

**Comment by bblacher** [comment]
Just want to add that with sway 1.9 on Arch everything works as expected with the vulkan renderer, I don't even need vulkan-validation-layers.

**Comment by bl4ckb0ne** [comment]
@Morris-pi you are you able to run it without the validation layer?

**Comment by bl4ckb0ne** [comment]
> 00:00:00.016 [wlr] [render/vulkan/vulkan.c:185] Could not create instance: ERROR_LAYER_NOT_PRESENT (-6)

You're still trying to use the layer

**Comment by emersion** [comment]
Yeah, Sway 1.9 no longer force-enables the validation layer.
