### ISSUE TITLE
Resizing windows results in poor performance.

### ISSUE THREAD

**Issue by DarkDefender** [swaywm/sway#798]
When resizing windows in sway, I get quite poor performance and the window content is quite ugly during the resize.

Let's say I create two terminals with the default tiling layout (one vertical split) and I want to resize the split so i get a 70/30 split instead of a 50/50. When I hold the modifier key and use my mouse to resize the split, sway slows down to a crawl when I try to drag the split for more than about 10 pixels. So it's quite annoning to have to drag the split, wait for sway to catch up, drag a bit more and repeat till I have the size I feel looks good.

It's not that bad when resizing floating windows but the window content still jumps around and grey bars gets added around the original window content.

This does not happen in weston when resizing windows. So I'm guessing this is a sway/wlc problem.

It seems to me that perhaps sway tries to refresh the window content too much. Perhaps it would be better only to refresh the content with the new size after the resize operation is done?

**Comment by zandrmartin** [comment]
Out of curiosity when was the last time you updated Sway? I know there was a short period where this happened for me too after all of the desktop shell stuff was implemented, but that bug was fixed about a week ago (I believe by #777).

**Comment by DarkDefender** [comment]
I built and tested with todays git version. I have had this issue for as long as I tried sway (About 3 months)

**Comment by Cloudef** [comment]
Weston throttles input, wlc doesn't. This is most likely the problem. (Also the fact that content is indeed updates as soon as possible).

**Comment by DarkDefender** [comment]
@Cloudef Ah, I guess that maybe the problem is more obvious for me then because I have a 1000hz mouse.

**Comment by leorosa** [comment]
An option to mimic the i3 behavior (move only a wireframe, and _then_ resize the windows) could be useful.

**Comment by SirCmpwn** [comment]
I'm closing issues that are resolved by the yet-unreleased sway 1.0.
