### ISSUE TITLE
Invisible toggle buttons

### ISSUE THREAD

**Issue by mjollnir14** [swaywm/sway#7983]
- sway version 1.8.1 

- **Debug Log:**
 https://gist.github.com/mjollnir14/cca69216ae07040aaa2de1b8c4495407

- **Configuration File:**
  - Fresh install
  - Same bug on my laptop (Manjaro Sway installed 2 months ago)

Steps to reproduce:
- Launch pamac-manager
- Click "..." / "Advanced" or "Third Party"
- There is no toggle button next to each label as you can see here:
- See attached screenshot

Expected:
- https://forum.endeavouros.com/uploads/default/original/3X/5/a/5ab9b4f449d8562f961e0dd70592ff03f1f5510a.png

![swappy-20240216_150211](https://github.com/swaywm/sway/assets/33414448/95bac169-474e-4e7f-bedd-ae59482fa2f1)

Not sure if this is sway or pamac-manager relaated tho.

**Comment by emersion** [comment]
Very likely a pamac-manager bug. Please report this bug to them. Sway doesn't draw buttons.
