### ISSUE TITLE
1.9 update changes PrintScreen key

### ISSUE THREAD

**Issue by yagarea** [swaywm/sway#8004]
### Please fill out the following:
- **Sway Version:** sway version 1.9
- **Sys info**: Arch linux + 6.7.6-arch1-1 kernel
- **Hardware**: Lenovo x390 yoga
- **Configuration File:**
  ```
  # printscreen
  bindsym --release Print exec $sway_scripts/grimshot --notify copy area
  bindsym --release Shift+Print exec $sway_scripts/grimshot --notify save window ~/Pictures/screenshots/$(date +%Y-%m-%d-%H-%M-%S).png
  bindsym --release $mod+Print exec $sway_scripts/grimshot --notify copy window
  bindsym --release $mod+Shift+Print exec sway_scripts/grimshot --notify save window ~/Pictures/screenshots/$(date +%Y-%m-%d-%H-%M-%S).png
  ```

### Description
After an update to 1.9 when I press PrintScreen key it does not send `Print` event. In alacritty pressing printscreen key writes `[57361u` code. When I press printscreen + `fn` key it does not do anything.

The `sudo libinput debug-events` prints this for printscreen key:
```
-event3   KEYBOARD_KEY            +0.000s	KEY_SYSRQ (99) pressed
 event3   KEYBOARD_KEY            +0.063s	KEY_SYSRQ (99) released
```

and this for `fn` + printscreen key:
```
-event18  KEYBOARD_KEY            +5.478s	KEY_PROG2 (149) pressed
 event18  KEYBOARD_KEY            +5.478s	KEY_PROG2 (149) released
```

**Comment by bradrn** [comment]
Looks like this is because 1.9 has split out the scripts folder into a separate repo: https://github.com/swaywm/sway/pull/7541

**Comment by alexiscampusano** [comment]
Scripts in /usr/share/sway dissappear

**Comment by emersion** [comment]
Right, this is expected:

1. As linked above, the scripts are no longer in Sway.
2. The scripts were never officially supported, they were contrib/ material before 1.9.

**Comment by Lege19** [comment]
Has anyone found a workaround for binding to print screen? It's quite inconvenient not being able to, as without that it's basically a wasted key.

**Comment by smlx** [comment]
This snippet works for me in sway 1.10.1.

```
bindsym print exec ~/.config/sway/screenshot
```

Have you tried debugging the keypress event with `wev`?

**Comment by yagarea** [comment]
I confirm it works on 1.10.1.

**Comment by Lege19** [comment]
I'm on 1.9.0 and can't easily update, wev shows nothing. It's possible that key is broken, but that seems unlikely because I've been using it for screenshot with plasma until recently. But it's hard test because plenty of programs wouldn't recognize weird keys like that one anyway.

**Comment by Lege19** [comment]
I just figured it out, I had bindsym print = ...
removing the = fixed it. Although there should probably be an error for that
