### ISSUE TITLE
Wayland-session.log growing too fast

### ISSUE THREAD

**Issue by voiceroy** [swaywm/sway#8006]
- **Sway Version:** sway version 1.9

- **Debug Log:** https://pastebin.com/GWi5YqbU

- **Configuration File:** https://pastebin.com/1mdLaEcw

- **Description:**
  - Login using sddm
  - Launch firefox
  - Watch the log file grow fast
  - I use archlinux

**Comment by emersion** [comment]
Closing because these messages are not coming from Sway, they are coming from another Wayland client.

**Comment by voiceroy** [comment]
I've currently made the log file `~/.local/share/sddm/wayland-session.log` immutable since it was consuming disk space too much

**Comment by bl4ckb0ne** [comment]
> /usr/bin/bash -c '/usr/lib/firefox/firefox '

It's coming from firefox

**Comment by voiceroy** [comment]
Any way to solve this?

**Comment by Xartos** [comment]
@voiceroy 
The only workaround I've found [*(this thread)*](https://bbs.archlinux.org/viewtopic.php?pid=2153594) is to start firefox without wayland (i.e. `MOZ_ENABLE_WAYLAND=0 firefox`)

There seems to be a bug upstream you can follow https://bugzilla.mozilla.org/show_bug.cgi?id=1882449 for the proper fix

**Comment by voiceroy** [comment]
Will try, thank you.
