### ISSUE TITLE
keyboard interactivity broken in lxqt-panel menus

### ISSUE THREAD

**Issue by stefonarch** [swaywm/sway#8030]
Searched the open issues, didn't find something related.

- **Sway Version:**
sway version 1.9

- **Description:**
 After the release of `layer-shell-qt 6.0` basics are implemented in lxqt-panel, positioning, exclusive zone etc.. What does not work is keyboard focus in panel menus, including search. Same issue can be seen in [labwc](https://github.com/labwc/labwc/issues/1572) and [wayfire](https://github.com/WayfireWM/wayfire/issues/1779#issuecomment-1973801630), not in Hyprland and kwin_wayland. Where the cursor is not moving I tried keyboard:

https://github.com/swaywm/sway/assets/10681413/bfa3aacc-09c4-4bdd-b97a-14b2343cf168

EDIT: it says on top "labwc 7...." but that's my script which tells me what I'm using, it's a nested sway window.

**Comment by stefonarch** [comment]
Issue on our side,`KeyboardInteractivityNone` was set instead of `KeyboardInteractivityOnDemand`.

**Comment by emersion** [comment]
Ah, thanks for the update! If you have time, maybe consider reporting bugs to Hyprland and KWin if they give keyboard interactivity to layer surfaces that set keyboard interactivity to none?

**Comment by stefonarch** [comment]
Done at Hyprland's side, not going down kde bugtracker.
