### ISSUE TITLE
Mouse and keyboard input out of sync after popup window

### ISSUE THREAD

**Issue by kamiyaa** [swaywm/sway#8036]
### Please fill out the following:
- **Sway Version:**
sway version 1.10-dev-5e18ed3c (Mar  4 2024, branch 'master')

- **Debug Log:**
In comment

- **Description:**

This is a regression because this didn't occur before.

Steps to reproduce
  - Open up vscode
  - Open a popup
  - Mouse input now is nowhere to be found
    - Need to go through each individual window to find where the mouse input is to restore mouse input
  - Keyboard input continues to work correctly dispite mouse input not sending events to correct window

Video: 
https://github.com/swaywm/sway/assets/8345320/50356754-1136-469b-8d2d-d758140318e4

**Comment by kamiyaa** [comment]
Debug log:

[sway.log](https://github.com/swaywm/sway/files/14487179/sway.log)

**Comment by Nefsen402** [comment]
Seems like a duplicate of https://github.com/swaywm/sway/issues/7974. Is this software running under xwayland?

**Comment by kamiyaa** [comment]
Yes, running on xwayland

**Comment by Nefsen402** [comment]
There are some recent fixes on master that I think will fix or at least help this issue. Can you try the latest version?

**Comment by Nefsen402** [comment]
This sounds like it would have been an issue with xwayland stacking. A similar issue has been closed and the xwayland stacking has been rewritten since on master. Closing as assumed fixed.
