### ISSUE TITLE
Flameshot screenshots are sometimes cut in half depending on the application where they are pasted and the Sway version being used

### ISSUE THREAD

**Issue by AkechiShiro** [swaywm/sway#8051]
- **Sway Version:**
  - `swaymsg -t get_version` or `sway -v` 
  - sway version 1.8.1

-**Flameshot Version:**
  - Flameshot v12.1.0 (-)
  - Compiled with Qt 5.15.10

- **Debug Log:**
  - Run `sway -d 2> ~/sway.log` from a TTY and upload it to a pastebin, such as gist.github.com.
  - This will record information about sway's activity. Please try to keep the reproduction as brief as possible and exit sway.
  - Attach the **full** file, do not truncate it.

- **Configuration File:**
- I will setup a clean virtual machine to reproduce this issue with the most minimal Sway configuration.

- **Description:**
  - Setup xdg-portal usage under Sway, first of all flameshot does not work out of the box for Sway, I've went through the troubleshooting page :  https://github.com/emersion/xdg-desktop-portal-wlr/wiki/%22It-doesn't-work%22-Troubleshooting-Checklist
  - Once I applied most of the troubleshooting steps, Flameshot started working but there were still issues.

-**Additional Context**
Please read this issue reported downstream : https://github.com/flameshot-org/flameshot/issues/2063

I will provide further debug logs later by editing or commenting on this issue.

**Comment by emersion** [comment]
If wl-copy works as a workaround, then this is unlikely to be a Sway issue. Probably a bug in the client clipboard handling.

**Comment by AkechiShiro** [comment]
There are also other issues, however I would like feedback if they should be handled in Flameshot or if there is way we can fix them in some other way (in Sway), I lack foresight where exactly those issue should be fixed : 
- https://github.com/flameshot-org/flameshot/issues/2941
- https://github.com/flameshot-org/flameshot/issues/3012

**Comment by AkechiShiro** [comment]
Thanks @emersion, I will close this issue then, and will investigate downstream in the code.

**Comment by AkechiShiro** [comment]
@emersion would you have any idea what this means ?? 

https://github.com/flameshot-org/flameshot/issues/2063#issuecomment-1355552735

Could the bug be related to Electron apps ? Or specific libraries ?
