### ISSUE TITLE
When statically linking wlroots, do not install it

### ISSUE THREAD

**Issue by WhyNotHugo** [swaywm/sway#8053]
## Sway Version

    sway version 1.10-dev-2e951163c (Mar  9 2024, branch 'master')

## Reproduction Steps

When statically linking wlroots:

```
meson -DDwlroots:default_library=static build
meson compile -C build
doas meson install -C build
```

## Actual behaviour

Installing sway still installs wlroots' shared object file:

    Installing subprojects/wlroots/libwlroots.so.13 to /usr/local/lib

## Expected behaviour

Installing `sway` shouldn't install `wlroots`'s shared object if it has been linked statically.

**Comment by emersion** [comment]
This is a Meson bug. Nothing we can do about it.

**Comment by emersion** [comment]
(See https://github.com/mesonbuild/meson/issues/2550)

**Comment by WhyNotHugo** [comment]
Workaround is to use `--skip-subprojects wlroots`. E.g.:

```sh
meson -DDwlroots:default_library=static build
meson compile -C build
doas meson install -C build --skip-subprojects wlroots
```
