### ISSUE TITLE
XWayland applications unable to query XResourceManagerString

### ISSUE THREAD

**Issue by tim-rex** [swaywm/sway#8055]
### Please fill out the following:
- **Sway Version:**
1.9

- **Description:**
It seems that `XResourceManagerString()` returns null when running under Sway

I've fixed my own dodgy code to not blow up on that scenario, but figure this might be something to be handled/supported by Sway

The calling code is simply
```
char *resourceString = XResourceManagerString(xlib_dpy);
```

The behaviour is consistent for both an xlib_dpy and an xcb_dpy

**Comment by emersion** [comment]
An X11 WM is not responsible for `RESOURCE_MANAGER`. Users would typically use something like xrdb if they want/need one.

**Comment by tim-rex** [comment]
Thanks for the pointer, was unaware of this. xrdb does the trick, I guess desktop environments handle that functionality behind the scenes (be it xrdb or their own resource manager implementation). Cheers!
