### ISSUE TITLE
Display scale not matching specified value

### ISSUE THREAD

**Issue by thekakkun** [swaywm/sway#8057]
**Sway Version:**
  1.9 

**Configuration File:**
- https://raw.githubusercontent.com/thekakkun/dotfiles/main/.config/sway/config
- https://raw.githubusercontent.com/thekakkun/dotfiles/main/.config/kanshi/config

**Description:**

When a second monitor is connected, I set the display scale to 1.6711111

```
swaymsg output eDP-1 scale 1.6711111
```
However, checking the output settings gives me:
```
swaymsg -t get_outputs
Output eDP-1 'BOE 0x0BCA Unknown'
  Current mode: 2256x1504 @ 59.999 Hz
  Power: on
  Position: 0,0
  Scale factor: 1.675000
  Scale filter: linear
  Subpixel hinting: unknown
  ...
```
Which means, while I expect my screen to be 1350x900, it ends up being 1346.8x897.9.
My monitor (positioned at 1350,0) isn't actually there, and the slight mismatch causes an issue where my mouse cursor gets 'stuck' between the two displays.

**Comment by emersion** [comment]
This is by design. Sway rounds to the nearest scale representable by the fractional-scale protocol.

**Comment by thekakkun** [comment]
Thanks, just read up on it. So if I understand correctly, it seems like the denominator needs to be 120.
