### ISSUE TITLE
Support for global shortcuts

### ISSUE THREAD

**Issue by jchv** [swaywm/sway#8062]
I propose implementing hyprland_global_shortcuts_v1 in SwayWM.

This should enable:
- Applications using this protocol to register global shortcuts
- An implementation of the xdg-desktop-portal GlobalShortcuts API

Doesn't seem like there's much point in making another non-standard protocol if the Hyprland one is exactly what is needed.

Versus applications implementing IPC, this would enable a more uniform way of implementing and binding global shortcuts, and open the door for runtime enumeration of global shortcuts. Applications such as OBS have signaled intent to implement xdg-desktop-portals-based global shortcuts so this approach seems positioned to be strong into the future.

Not proposing anyone work on this, just wanted to see what the temperature reading is. I'd love to work towards a solution that would help push the Wayland ecosystem forward, even if I am not really a huge fan of the reliance on dbus protocols for a lot of things.

**Comment by emersion** [comment]
There is a standard protocol for this in development: https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/216

I'd rather not foster the proliferation of non-standard protocols if we can avoid it.
