### ISSUE TITLE
Screen starts flickering after taking a screenshot with grim

### ISSUE THREAD

**Issue by svix-jplatte** [swaywm/sway#8066]
After taking a screenshot with `grim`, any redraw of that screen has a 50/50 chance of transitioning the screen from the regular image to all-white, or the other way around, going forward. When not much is happening on that screen, it doesn't flicker but as soon as something changes on that output, it often does a transition (when it's just a small change) or flickers like crazy (if it needs to redraw a lot, e.g. because the cursor is moving, a video is playing, whatever). The only fix was to restart sway (reload was not enough).

_Extracted from comment in another issue: https://github.com/swaywm/sway/issues/8040#issuecomment-1997768669_

**Comment by svix-jplatte** [comment]
I tried with `WLR_SCENE_DEBUG_DAMAGE=rerender` and `WLR_SCENE_DISABLE_VISIBILITY=1` as suggested in https://github.com/swaywm/sway/issues/8040#issuecomment-1997793215 and the problem goes away entirely. This is on wlroots 0.17.1, sway 1.9, both with and without the one-line wlroots patch from https://github.com/swaywm/sway/issues/8040#issuecomment-1988476085.

**Comment by emersion** [comment]
Interesting, can you try to find which one of these is making the issue go away?

**Comment by svix-jplatte** [comment]
Can do on Monday.

**Comment by svix-jplatte** [comment]
Huh, maybe it wasn't the flags afterall. I'm no longer able to reproduce this even without them.

Recent upgrades include linux (6.7.8.arch1-1 -> 6.7.9.arch1-1), linux-firmware (20240220.97b693d2-1 -> 20240312.3b128b60-1), mesa (1:24.0.2-2 -> 1:24.0.3-1). Maybe one of those fixed the issue :shrug:
