### ISSUE TITLE
$WL_DRM_DEVICES is ignored

### ISSUE THREAD

**Issue by dvoytik** [swaywm/sway#8074]
With `$WL_DRM_DEVICES` set only for the internal Intel GPU, sway still uses both GPUs.
The problem is reproducible with the default config.
I also tried to use `/dev/dri/card1` 

```
↪ echo $WL_DRM_DEVICES
/dev/dri/by-path/pci-0000:00:02.0-card

↪ ls /dev/dri/by-path/pci-0000:00:02.0-card -l
lrwxrwxrwx 1 root root 8 Mar 18 20:24 /dev/dri/by-path/pci-0000:00:02.0-card -> ../card1

↪ cat /etc/environment | grep WL_DRM_DEVICES
WL_DRM_DEVICES="/dev/dri/by-path/pci-0000:00:02.0-card"

↪ lspci -k | grep -e VGA -A5 | grep -e 'Kernel driver' -e VGA
00:02.0 VGA compatible controller: Intel Corporation Raptor Lake-S GT1 [UHD Graphics 770] (rev 04)
        Kernel driver in use: i915
01:00.0 VGA compatible controller: NVIDIA Corporation AD104 [GeForce RTX 4070] (rev a1)
        Kernel driver in use: nouveau

↪ lsmod | grep -m 1 nouveau
nouveau              3670016  10

↪ ls -l ~/.config/sway
ls: cannot access '/home/voyt/.config/sway': No such file or directory

↪ sway -d 2> ~/sway.log

↪ swaymsg -t get_version
sway version 1.9

```

Full log:
https://gist.github.com/dvoytik/54cd40b0ed892b898a937d03d3adc2aa

**Comment by emersion** [comment]
The env var is called `WLR_DRM_DEVICES` (notice the "R", "wlr" stands for "wlroots").

**Comment by dvoytik** [comment]
Oh, I see... I was confused by this answer: https://www.reddit.com/r/swaywm/comments/10lwums/is_there_a_way_of_only_using_the_integrated_gpu/
I was dumb enough to not check the source code...
Thank you!

**Comment by emersion** [comment]
No problem. FWIW, no need to check the source, the variables are documented here: https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/docs/env_vars.md?ref_type=heads
