### ISSUE TITLE
crash when trying to run any qt app with no space on monitor to display it

### ISSUE THREAD

**Issue by pd2s** [swaywm/sway#8083]
- **Sway Version:**
sway version 1.10-dev-5a7477cb (Mar 18 2024, branch 'master')
wlroots built from 538a7a190dacd4068908e44bbd0a8a5143aaba69 commit

- **Debug Log:**
https://gist.github.com/pd2s/76eb9272ef8a9bdcafde5f4fc5d4b7dc

- **Configuration File:**
default

- **Stack Trace:**
sway: types/xdg_shell/wlr_xdg_toplevel.c:549: wlr_xdg_toplevel_set_size: Assertion `width >= 0 && height >= 0' failed.
if needed i can recompile sway & wlroots with debug symbols and send stack trace

- **Description:**
- **steps to reproduce :**
1. create layer surface (e.g swaybar with height setting) with height > monitor height
2. execute any QT app
3. crash

**Comment by emersion** [comment]
Duplicate of https://github.com/swaywm/sway/issues/7946
