### ISSUE TITLE
can't make a new line in terminal using shift+return or Shift+enter

### ISSUE THREAD

**Issue by sachinchaudhary1808** [swaywm/sway#8088]
so i'm using sway on nixos-unstable and when i press shift + return or enter in terminal it does not create a new line

so in foot terminal it just shows like this 

![image](https://github.com/swaywm/sway/assets/138745629/d1f94b44-f069-44b0-a0ea-4bd63ee403a3)

and in other terminal's it just execute's the command

**Comment by emersion** [comment]
Sway has no control over this. The shell is the program that needs to handle this.
