### ISSUE TITLE
GTK3's client-side decorations have no shadow or border.

### ISSUE THREAD

**Issue by pablo-888** [swaywm/sway#8090]
sway version 1.10-dev-5a7477cb (Mar 27 2024, branch 'master')
archlinux GTK3 version 3.24.41

here's what they look on the 1.9 stable release:
![1711559704](https://github.com/swaywm/sway/assets/104789095/2dd8302b-af50-4379-8c56-3314e41b6265)

and here's what they look like right now:
![1711559669](https://github.com/swaywm/sway/assets/104789095/6c4c621c-3ec3-4222-8bc5-20dc40fde191)

**Comment by thal** [comment]
This should be fixed in #8033
