### ISSUE TITLE
Handling multiple displays with different format/modifier combinations after a4ef377

### ISSUE THREAD

**Issue by matt1606** [swaywm/sway#8105]
Comparing two versions here:
- **Sway Version:** not affected: 1.10-dev up to commit 125c74338ac8bf8c15323a49730352b82d6d51bd
- **Sway Version:** affected: 1.10-dev up to commit a4ef37752fd6ae9e84d60cbe4eaead07f71f9435
  - with #8095 on top, but just to test if it could bring some improvement
- both built against wlroots 0.18.0-dev commit 3fc66d4525916b9301236a000a6ed03311ed25a7 + [wlroots_patches ](https://gist.github.com/matt1606/2e8e6c91c17e547f12ed934149f68dce)
  - some extra debug logs for the swapchain part
  - patch from [wlroots/issues/1823#note_2146862](https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/1823#note_2146862) - I know, not supported DisplayLink evdi driver in use, yet I think this issue is more generic than DisplayLink specific, see in description section.

- **Debug Log:**
  - not affected: [sway-debug.125c743.log](https://gist.github.com/matt1606/3498b68288ce95390c7726fee6bb560a), [swaymsg-get_outputs.125c743.json](https://gist.github.com/matt1606/2430a71519c67e760f093e3ace924361), [drm_info.125c743.txt](https://gist.github.com/matt1606/dda441e92f7452db3a9ef0bd9178dd14)
  - affected: [sway-debug.a4ef377.log](https://gist.github.com/matt1606/7775c315bfb3771167463243b2302896), [swaymsg-get_outputs.a4ef377.json](https://gist.github.com/matt1606/9afada7416e85c9ac3d777115b72e9fc), [drm_info.a4ef377.txt](https://gist.github.com/matt1606/88522f3e04d06e983a31f8cd83a0e39d)

- **Configuration File:**
  - [config](https://gist.github.com/matt1606/209e0aa4981ad72a61186486941112ed)

- **Stack Trace:**
  - no crash observed

- **Description:**
  - since the series of commits between 125c74338ac8bf8c15323a49730352b82d6d51bd and a4ef37752fd6ae9e84d60cbe4eaead07f71f9435 one of the displays, the one connected via the DisplayLink (`DVI-I-1`), remains disabled (power: off).
  - the DisplayLink connected display uses a different combination of pixel format and the modifier (format AR24 (0x34325241), modifier LINEAR (0x0000000000000000)) than the other two connected displays (format XR24 (0x34325258), modifier Y_TILED_GEN12_RC_CCS_CC (0x0100000000000008)), that scenario was properly handled up to 125c74338ac8bf8c15323a49730352b82d6d51bd
  - for a4ef37752fd6ae9e84d60cbe4eaead07f71f9435 the logs show the following error message:
`[ERROR] [wlr] [backend/drm/atomic.c:335] Failed to acquire FB for plane 31`
the test setup with all 3 displays fails and DVI-I-1 display remains in disabled state.
  - so far by static code analysis I was able to find the faulty path:
`manager_output_prepare` returns true after which
`manager_test` continues with calling
`wlr_backend_test`
`backend->impl->test` which for DRM calls
`drm_connector_test`
`drm_connector_commit_state`
`drm_commit`
`drm->iface->commit`
`atomic_device_commit`
`atomic_connector_add`
`set_plane_props` -> Failed to acquire FB for plane 31
  - by drm_info analysis it looks like some planes switched places, including the one holding the FB for DVI-I-1 with format AR24 (0x34325241), modifier LINEAR (0x0000000000000000), i.e. plane 31 in 125c74338ac8bf8c15323a49730352b82d6d51bd <-> plane 15 in a4ef37752fd6ae9e84d60cbe4eaead07f71f9435
  - what can be done to get the display working again?

Regards<br/>Mateusz

**Comment by kennylevinsen** [comment]
> not affected: [sway-debug.125c743.log](https://gist.github.com/matt1606/3498b68288ce95390c7726fee6bb560a),

This log does not light up DVI-I-1. Only eDP-1 and HDMI-A-1 gets lit up.

> so far by static code analysis I was able to find the faulty path:

This does not look right - drm_connector_test and drm_connector_comit_state is the old path, not the new one.

However, I do suspect we might have a multi-gpu issue with the new backend-wide commits. Specifically, in the per-connector code-path, we skip blit and test of secondary GPUs.

With the new backend-wide wlroots logic, we commit all connectors, but we're still skipping the blit in `drm_connector_prepare` leading to no primary fb being present when we test all connectors, which fails.

---

As a terrible hack, this seems to work:

```diff
diff --git a/backend/drm/atomic.c b/backend/drm/atomic.c
index 9defa7c6..f42ccee6 100644
--- a/backend/drm/atomic.c
+++ b/backend/drm/atomic.c
@@ -333,7 +333,7 @@ static void set_plane_props(struct atomic *atom, struct wlr_drm_backend *drm,
 
        if (fb == NULL) {
                wlr_log(WLR_ERROR, "Failed to acquire FB for plane %"PRIu32, plane->id);
-               atom->failed = true;
+               // atom->failed = true;
                return;
        }
```

**Comment by kennylevinsen** [comment]
Try with this branch: https://gitlab.freedesktop.org/kennylevinsen/wlroots/-/tree/displaylink-hack?ref_type=heads

This combines https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4639 with a better hack for DisplayLink. The old one was broken, leading to additional copies.

**Comment by Dev-Aligator** [comment]
The Displaylink-hack doesn't seem to work with:
- Hyprland v0.41.2
- libliftoff 0.5.0-1

What can be done to get the display working again?

**Comment by kennylevinsen** [comment]
> The Displaylink-hack doesn't seem to work with:
> 
>     * Hyprland v0.41.2
>     * libliftoff 0.5.0-1

This is the sway issue tracker. Hyprland discussions belong on the Hyprland issue tracker.

**Comment by kennylevinsen** [comment]
DisplayLink show now work with wlroots master as of today
