### ISSUE TITLE
sway won't start since config/output: Refactor handling of tiered configs 

### ISSUE THREAD

**Issue by GreyXor** [swaywm/sway#8113]
### Please fill out the following:
- **Sway Version:**
  - https://github.com/swaywm/sway/commit/1267e47de913d2cda2644ad89bba4e9c55842cd3

- **Debug Log:**
https://gist.github.com/GreyXor/824a4b228b6dbe00f2a22ed86566d025

- **Configuration File:**
https://gitlab.com/greyxor/dotfiles/-/tree/main/.config/sway?ref_type=heads

- **Description:**
Hello, I just start sway, and it directly.

if the issue is not straightforward, I can reduce my config to being more specific for the context, let me know

**Comment by emersion** [comment]
Likely fixed by https://github.com/swaywm/sway/pull/8111

**Comment by GreyXor** [comment]
Yes, fixed by https://github.com/swaywm/sway/pull/8111
