### ISSUE TITLE
[master] A configure is scheduled for an uninitialized xdg_surface 0x7fd951c70620 

### ISSUE THREAD

**Issue by WhyNotHugo** [swaywm/sway#8115]
- **Sway Version:**

- sway version 1.10-dev-dcb142bf (Mar 31 2024, branch 'master')

- **Debug Log:**

https://paste.sr.ht/~whynothugo/dafdf6ca7bacfc184b1a337f739283c04ae18c22

- **Configuration File:**

    exec foot

- **Stack Trace:**

n/a

- **Description:**

sway itself logs `[Apr 15 11:52:30] user hugo/sway: 15:23:49.181 [ERROR] [wlr] [types/xdg_shell/wlr_xdg_surface.c:169] A configure is scheduled for an uninitialized xdg_surface 0x7fd94efccc50` when a new window opens.

sway only logs an error (thousands of times per day), but I see no other symptoms.

I can reproduce this with `foot`, `firefox`, `audacious` and `nemo`. I suspect that it happens with any regular client.

Clients which render layer-shell don't seem to have this problem.

**Comment by WhyNotHugo** [comment]
I bisected with `python checkout-wlroots.py && rm -rf build && meson build && meson compile -C build && ./build/sway/sway -c test.conf`.

[`checkout-wlroots.py` checks out the latest wlroots commit for a given sway commit](https://paste.sr.ht/blob/42051469c1cb97576a24f7e5860c29751adf2b01)


```
3ef5abd405a6fd32aeeffb2f48a6cadd9fc14574 is the first bad commit
commit 3ef5abd405a6fd32aeeffb2f48a6cadd9fc14574
Author: Simon Ser <contact@emersion.fr>
Date:   Tue Feb 27 15:10:09 2024 +0100

    xdg-shell: send WM capabilities

 sway/desktop/xdg_shell.c | 4 ++++
 sway/server.c            | 2 +-
 2 files changed, 5 insertions(+), 1 deletion(-)
```

The first bad commit uses wlroots 94dbb3cfb5293e58580083cd26f059669030956d.

The last good commit uses wlroots 94dbb3cfb5293e58580083cd26f059669030956d

**Comment by WhyNotHugo** [comment]
Ah, calling `wlr_xdg_toplevel_set_wm_capabilities` implicitly schedules a `configure` event, but it is too early in this case.

**Comment by emersion** [comment]
Fixed in https://github.com/swaywm/sway/pull/8232
