### ISSUE TITLE
`xdg-desktop-portal-gtk` only uses GTK3 file chooser while sway is installed

### ISSUE THREAD

**Issue by phisch** [swaywm/sway#8121]
- **Sway Version:** 1.9
- **Configuration File:** happens with the default

I have `xdg-desktop-portal`, `xdg-desktop-portal-wlr` and `xdg-desktop-portal-gtk` installed, and the gtk one provides a file chooser. But I noticed that my applications use the legacy GTK3 chooser. 

On a machine running GNOME, it shows the GTK4 chooser. But installing sway, which adds these 4 packages: `seatd-0.8.0-1  wlroots-0.17.2-1  xcb-util-errors-1.0.1-1 sway-1:1.9-3`, makes even GNOME use the GTK3 file chooser.

This does not seem to be a user configuration error, though I can't quite figure out what exactly causes this.

**Comment by emersion** [comment]
Sorry, but the Sway project itself doesn't have anything related to xdg-desktop-portal. Probably the best place to ask this kind of question would be an xdg-desktop-portal support channel, or xdg-desktop-portal-wlr?
