### ISSUE TITLE
One of two DisplayPort MST displays stays black; reloading fixes the issue

### ISSUE THREAD

**Issue by B4ckslash** [swaywm/sway#8144]
### Please fill out the following:
- **System Info:**
  - `sway version 1.9`
  - GPU driver `i915`
  - Displays
    - Two identical Dell 2560x1440 27" screens
    - Configuration: Daisychain (Displayport MST) `PC -> DP-4 -> DP-6`

- **Debug Log:**
 [Log](https://gist.github.com/B4ckslash/cbcad90ff248cbfa86223c9894969986)
I think the most pertinent are the lines like these (occur for both DP-4 and DP-6, depending on which stays black):
```
00:00:01.953 [ERROR] [wlr] [types/output/swapchain.c:109] Swapchain for output 'DP-6' failed test
00:00:01.953 [ERROR] [sway/config/output.c:525] Failed to commit output DP-6
```

- **Configuration File:**
Custom config adapted from i3, but reproducible with the example config adapted to my output configuration, with the same error mentioned above

- **Description:**
Whenever sway has to initialize the displays (either after logging in or after the display turning off with swayidle+DPMS), one of my displays stays blank. Usually after logging in, DP-6 stays black, but after idling it's normally DP-4. 
Reloading the config manually using `swaymsg reload` fixes the issue. Interestingly, that command seems to emit many `<CR>` inputs, as there are many lines in my terminal that look as though there was an empty CLI command being issued after executing `swaymsg` (this did not happen with separate DP connections whenever I had to reload the config).
I also tried setting `WLR_DRM_NO_MODIFIERS=1` as suggested in #4980, but this did not fix the issue.

**Comment by emersion** [comment]
Can you try again with the latest Sway commit? See https://github.com/swaywm/sway/wiki/Development-Setup#compiling-as-a-subproject

**Comment by B4ckslash** [comment]
Alright latest Sway seems to work. In particular according to the logs, test commits of the swapchains seem to succeed eventually.

[Here](https://gist.github.com/B4ckslash/378f0fa86a9f3ef0c763cc00dbb96de9) is the new log.

Tell me if you need anything else, otherwise feel free to close the issue, as this will seemingly be fixed with the next release.

**Comment by emersion** [comment]
Good to hear!
