### ISSUE TITLE
gpu hotplug doesn't work

### ISSUE THREAD

**Issue by athul-krishna-kr** [swaywm/sway#8149]
### Device and Software Info:
- **Sway Version:** `sway version 1.9`
- **Device:** Asus Zephyrus G14 GA402RJ
- **BIOS:** 319
- **OS:** Arch Linux
- **Kernel:** 6.8.9-arch1-1
- **DGPU:** AMD Radeon RX 6700S(amdgpu)

### dgpu_add:
- `echo 1 | sudo tee /sys/bus/pci/rescan`

### dgpu_remove:
- `echo "0000:03:00.0" | sudo tee /sys/bus/pci/devices/0000:03:00.0/driver/unbind &&
   echo 1 | sudo tee /sys/bus/pci/devices/0000:03:00.0/remove`

### udev_trigger:
- `sudo udevadm trigger --verbose --type=devices --action=remove --subsystem-match=drm --property-match="MINOR=0"`

### Bug report:
`lsof_before` shows output of `sudo lsof /dev/dri/card* ` before udev_trigger. After udev_trigger there seems to be one thread(?) using file `/dev/dri/card0`(see `lsof_after`).

After dgpu_remove and dgpu_add, dgpu comes backup with different card number(card1) tries to initialize drm backend and fails to initialize egl context. Again removing and adding dgpu, it comes back with different card number(card3) and again fails to initialize egl context with error;
- `[ERROR] [wlr] [EGL] command: eglQueryDeviceStringEXT, error: EGL_BAD_PARAMETER (0x300c), message: "eglQueryDeviceStringEXT"`
- `[ERROR] [wlr] [EGL] command: eglQueryDeviceStringEXT, error: EGL_BAD_PARAMETER (0x300c), message: "eglQueryDeviceStringEXT"`
- `amdgpu_device_initialize: amdgpu_get_auth (2) failed (-1)`
- `amdgpu: amdgpu_device_initialize failed.`

both times.

Closing sway session and removing and adding dgpu from tty does reset the dgpu card number to 0 or1.
Starting a new sway session with dgpu removed, and then adding dgpu does work. It does show up in `sudo lsof /dev/dri/card*`.

### Log files:
- lsof_before
- lsof_after
- sway_log
- Link: https://gist.github.com/athul-krishna-kr/a6da70cc3a3b1196a3f6e0370387f737

**Comment by bl4ckb0ne** [comment]
That's probably a wlroots bug.

It's weird that `eglQueryDeviceStringEXT` fails with `EGL_BAD_PARAMETER`, from the spec [1]

    On failure, NULL is returned.  An EGL_BAD_DEVICE_EXT error is
    generated if <device> is not a valid EGLDeviceEXT.  An
    EGL_BAD_PARAMETER error is generated if <name> is not one of the
    values described above.
 
Would you be able to get a stacktrace? 
    
[1]: https://registry.khronos.org/EGL/extensions/EXT/EGL_EXT_device_query.txt

**Comment by athul-krishna-kr** [comment]
How should I get stacktrace? stacktrace kf what?

**Comment by bl4ckb0ne** [comment]
of the value being given to `eglQueryDeviceStringEXT`

**Comment by athul-krishna-kr** [comment]
Please give me instructions to get stack trace.

**Comment by bl4ckb0ne** [comment]
See the build instruction in the repo to build in debug, then start sway in a gdb session from another computer in ssh.

**Comment by athul-krishna-kr** [comment]
I should add debug flags to only wlroots?
