### ISSUE TITLE
Processes are spawned with `sh -c`

### ISSUE THREAD

**Issue by camj2** [swaywm/sway#8159]
All processes spawned by Sway are spawned using `sh -c`. This is fine, however the `sh` process is never dropped.

Take the following for example:

```
bindsym $mod+t exec alacritty
```

Using said keybinding results in the following output from `pstree -a`:

```
runit
--- snip ---
  |-sh -c alacritty
  |   `-alacritty
  |       |-zsh
  |       `-16*[{alacritty}]
--- snip ---
```

`alacritty` is spawned by `sh` but remains a subprocess.

You can workaround this by using `exec` twice:

```
bindsym $mod+t exec exec alacritty
```

This results in the following process tree:

```
runit
--- snip ---
  |-alacritty
  |   |-zsh
  |   `-16*[{alacritty}]
--- snip ---
```

While this isn't a massive issue, it would be nice if programs launched by Sway didn't remain a subprocess of `sh`.

**Comment by emersion** [comment]
That's not technically possible to implement. Even if we wanted to parse the shell syntax to figure out whether sh can be skipped it would be pretty fragile.

**Comment by camj2** [comment]
Current behavior:

```
sh -c "command"
```

Couldn't we just add `exec` to the `sh -c` command?:

```
sh -c "exec command"
```

From my understanding this is what happens anyway when using `exec` twice:

```
bindsym $mod+t exec exec command
```

**Comment by emersion** [comment]
No, would break things like `bindsym $mod+t exec foo && bar` (and many more).

**Comment by camj2** [comment]
Ah, sounds like this is the intended behavior then.
