### ISSUE TITLE
Display remains off after lock

### ISSUE THREAD

**Issue by ajvn** [swaywm/sway#8176]
**Sway Version:**
1.9

**Description:**
Since upgrading to Fedora 40, and Sway 1.9 (previous version was 1.8.1), there's an issue with display remaining off while attempting to unlock it.

Hardware is Dell XPS 13 9370 with Intel UHD 620.

Tested kernels:
```bash
* 6.8.9-300
* 6.8.10-300
```

Potentially relevant packages:
```bash
* mesa-*              24.0.7-3
* intel-gpu-firmware  20240513
* wlroots.x86_64      0.17.3
* wlroots0.16.x86_64  0.16.2-2
```

I've managed to track it down to setting custom resolution, which works in all cases beside `swayidle resume`.

Relevant part of config:
```bash
output eDP-1 mode --custom 1920x1080@60Hz \
    subpixel rgb
```

When that part is removed, there are no issues with unlocking and powering display back on.

Locking script:
```bash
#!/usr/bin/env bash

swayidle -w \
    timeout 5 'swaymsg "output * dpms off"' \
    resume 'swaymsg "output * dpms on"' &
swaylock --image someimage.jpg
kill %%
```

Relevant log:
```bash
May 23 17:58:38 /usr/libexec/gdm-wayland-session[6360]: 00:02:55.909 [ERROR] [sway/config/output.c:525] Failed to commit output eDP-1
May 23 17:58:38 /usr/libexec/gdm-wayland-session[7438]: [
May 23 17:58:38 /usr/libexec/gdm-wayland-session[7438]:   {
May 23 17:58:38 /usr/libexec/gdm-wayland-session[7438]:     "success": true
May 23 17:58:38 /usr/libexec/gdm-wayland-session[7438]:   }
May 23 17:58:38 /usr/libexec/gdm-wayland-session[7438]: ]
```
**Workaround**
When setting supported resolution before locking, and then restoring custom one after unlocking, issue is circumvented.

Locking script:
```bash
#!/usr/bin/env bash
swaymsg output "eDP-1 mode 3840x2160"

swayidle -w \
    timeout 5 'swaymsg "output * dpms off"' \
    resume "<path-to>/swayresume.sh" &
swaylock --image someimage.jpg
kill %%
```

Unlocking/resume script (`swayresume.sh`):
```bash
#!/usr/bin/env bash
swaymsg output "* dpms on"
sleep 5
swaymsg output "eDP-1 mode --custom 1920x1080@60Hz \
    subpixel rgb"
```

Let me know if anything else is needed, `dmesg` output doesn't contain anything Sway related, only relevant piece of log I managed to find is already linked.

I could potentially do git-bisect between 1.8.1 release and now, build and test each of those, but I don't know how long it would take for me to provide feedback as life is a bit busy at the moment.

Thank you.

**Comment by emersion** [comment]
Can you try again with the latest Sway commit? See https://github.com/swaywm/sway/wiki/Development-Setup#compiling-as-a-subproject

**Comment by ajvn** [comment]
I've built it from `master`, and using original config with which I had issues after upgrading to sway 1.9.

I'm starting it from existing Sway session.

Config part that I'm using to test locking behavior:
```
exec_always swayidle -w \
    timeout 15 'swaylock -f -i $lock_image' \
    timeout 20 'swaymsg "output * dpms off"' \
        resume 'swaymsg "output * dpms on"' \
    before-sleep 'swaylock -f -i $lock_image'
```

This is version I've compiled and am testing:
```bash
> ./sway -v
sway version 1.10-dev-a168b202 (May 24 2024, branch 'master')
```
This is how I'm executing compiled binary and output I'm getting:
```bash
> ./sway -c config
2024-05-24 17:31:06 - [main.c:278] Could not find config for output WL-1 ((null))
Another session found; refusing to overwrite the variables
i3status: trying to auto-detect output_format setting
i3status: auto-detected "i3bar"
Xlib.xauth: warning, no xauthority details available
INFO:assign-cgroups:X-Resource version 1.2
INFO:assign-cgroups:compositor:63329 /user.slice/user-1000.slice/user@1000.service/app.slice/app-Alacritty.slice/tmux-spawn-c2dac755-0c6c-43f7-aa0e-4aa7e670ea13.scope
00:00:36.644 [wlr] [types/xdg_shell/wlr_xdg_surface.c:169] A configure is scheduled for an uninitialized xdg_surface 0x1829460
```
Display does lock, but when it executes `swaymsg "output * dpms`, wlroots window is gone and then I have to send SIGTERM to the terminal window I'm executing command from.

I'm probably doing something wrong, could you please point out what?

**Comment by emersion** [comment]
"Turning off" an output from a nested Sway session makes the nested window disappear. That's by design.

**Comment by ajvn** [comment]
Tried again with current `master`:
```
sway version 1.10-dev-6e4ccb99 (Aug  3 2024, branch 'master')
```
However now I'm getting:
```
00:00:00.040 [wlr] [types/wlr_shm.c:536] wl_global_create failed
...
2024-08-03 22:01:14 - [main.c:576] Missing a required Wayland interface
```
along some configuration problems, but those are not critical.

I'd like to try with system-wide installation, but `wayland-server>=1.23` is only available in Fedora Rawhide (41), which is in testing and not released.
Current build was compiled in a container with required dependencies versions.

If you have any guidelines, please do share.

**Comment by ajvn** [comment]
I've just upgraded to Fedora 41, reported Sway version is 1.10 and this issue doesn't occur anymore.
Whoever fixed it, thank you.

Closing the issue.
