### ISSUE TITLE
Rerender swaybar when font configuration changes

### ISSUE THREAD

**Issue by mmlb** [swaywm/sway#818]
`sway.5.txt` should mention `font` support. It is (currently?) only handled in the configuration file, which needs to be specified in the man page. Should `swaymsg` return an error instead of success?

affects #2

**Comment by SirCmpwn** [comment]
swaymsg is doing the right thing, and the command is doing the right thing, but it should restart or at least signal a reload of swaybar and should redraw window borders. You'll probably notice that if you use the font command and then resize a window or something it'll be rerendered with the correct font.

**Comment by mmlb** [comment]
ahh yes that would explain why I did not see an update after the command returned succes, I did not force a render. So this is in fact just missing documentation. Possibly with a note that it does not take effect until something forces a render?

**Comment by SirCmpwn** [comment]
Nah the right call for this is to defender everything.

**Comment by SirCmpwn** [comment]
Rerender* on mobile

**Comment by mmlb** [comment]
Sure, but I'd think a PR for doc update _now_ is better than undocumented `font` until rerender is done. Unless rerender is super quick, though I wouldn't be able to take care of the rerender case.

**Comment by SirCmpwn** [comment]
Let's do it right the first time instead of putting in a temp solution.

**Comment by Hi-Angel** [comment]
Minimal steps to reproduce would help. I've no idea how font could be changed with `swaymsg` or `i3-msg`, and google only gives font-configuration through files, which is how I did it with i3 either. My best guess a `i3-msg "font pango:Hack, FontAwesome 9"` didn't work.

**Comment by SirCmpwn** [comment]
Edit your config and reload sway (`$mod+shift+c` by default). Right now we restart the swaybar process whenever we reload the config, which to be honest I'm entirely okay with. This ticket would propose instead sending the reload signal over IPC and having swaybar pull down the new config.

**Comment by Hi-Angel** [comment]
> Right now we restart the swaybar process whenever we reload the config, which to be honest I'm entirely okay with.

So, if I understand correctly, the original problem of font not being changed is have been solved, by making Sway to restart swaybars upon config reload, right? I.e. the issue can be closed.

> This ticket would propose instead sending the reload signal over IPC and having swaybar pull down the new config.

I looked at the code, and it seems currently the communication channel between Sway and its bars is closed at `invoke_swaybar()`. Making bars to get reloaded instead of being restarted requires to store the pipe descriptors somewhere in Sway. I'm not seeing much point in doing this, given reload of configs happens rarely enough to consider restart of bars a no-op.

**Comment by SirCmpwn** [comment]
>I.e. the issue can be closed.

yeah

>I looked at the code, and it seems currently the communication channel between Sway and its bars is closed at invoke_swaybar(). Making bars to get reloaded instead of being restarted requires to store the pipe descriptors somewhere in Sway

No, swaybar then reaches out to sway as an IPC client.

https://i3wm.org/docs/ipc.html#_barconfig_update_event
