### ISSUE TITLE
Need support for Nvidia driver

### ISSUE THREAD

**Issue by blakemcbride** [swaywm/sway#8184]
I love sway.  It is my window manager of choice.

I use LLM software and video editing software.  For efficient and practical use of these, I need the Nvidia drivers.  Sway does not work with the Nvidia drivers.  For this reason, I am forced to go back to X11 and i3.

Please make Sway work with the Nvidia driver!

Thank you!

**Comment by emersion** [comment]
We do not provide support for proprietary drivers. Please do not open issues if you're using such driver.

**Comment by blakemcbride** [comment]
I presume you realize that sway cannot be used with LLM or video recording or editing software.

**Comment by bl4ckb0ne** [comment]
We are well aware of that, unfortunately the proprietary driver doesn't always play nice and it's impossible for us to troubleshoot. We prefer to be upright about it.

You can still use the `unsupported-gpu` option, but don't expect anything from us if something goes wrong.

**Comment by samvv** [comment]
Just adding that at least as of June, part of the drivers of NVIDIA will be open-sourced for Turing, Ampere and Ada Lovelace architectures. 

Does this change anything to your current stance @bl4ckb0ne or @emersion?

Asking because I was stupid enough to buy a laptop with an NVIDIA GPU.

**Comment by emersion** [comment]
Unfortunately only the kernel driver is open-source. The GL and Vulkan implementations remain closed-source.

**Comment by samvv** [comment]
Oh right I didn't know that, sorry for the noise!

**Comment by bl4ckb0ne** [comment]
NVK looks promising but it's not yet available in mainstream distros, you can give it a try if you want but it could still be unstable.
