### ISSUE TITLE
build error after wlroots!4614 "Version pkgconfig, headers, and library for parallel installation"

### ISSUE THREAD

**Issue by Billli11** [swaywm/sway#8188]
- **Sway Version:**
N/A

- **Debug Log:**
N/A

- **Configuration File:**
N/A

- **Stack Trace:**
N/A

- **Description:**

After[ wlroots!4614 "Version pkgconfig, headers, and library for parallel installation"](https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4614/diffs?commit_id=4b4f76cc13574544216b59b3a9902b468b82108b)  
The pkg-config name have been changed to include versioning, cause meson fail to find wlroots.  
Update dependency name from `wlroots` to `wlroots-0.18` seem to fix it.  

```
diff --git a/meson.build b/meson.build
index 3c444e077..02866bc58 100644
--- a/meson.build
+++ b/meson.build
@@ -45,7 +45,7 @@ subproject(
        required: false,
        version: wlroots_version,
 )
-wlroots = dependency('wlroots', version: wlroots_version)
+wlroots = dependency('wlroots-0.18', version: wlroots_version)
 wlroots_features = {
        'xwayland': false,
        'libinput_backend': false,
```

**Comment by emersion** [comment]
Ref https://github.com/swaywm/sway/pull/8070 and https://github.com/swaywm/sway/pull/8187
