### ISSUE TITLE
XDG_CACHE_HOME gets ignored when launching sway.

### ISSUE THREAD

**Issue by Samueru-sama** [swaywm/sway#8191]
### Please fill out the following:
  - `sway version 1.9`

- **Debug Log:**
  - Run `sway -d 2> ~/sway.log` from a TTY and upload it to a pastebin, such as gist.github.com.
  https://pastebin.com/4uYrVHNC
  I ended up killing sway from another tty, as part of my troubleshooting was launching it with its default configuration, and I couldn't figure out how to exit lol.

- **Configuration File:**
  - default configuration was used. 

- **Description:**
  - Define `$XDG_CACHE_HOME` to any other location other than the default one.
  - Launch sway
  - A `~/.cache/mesa_shader_cache` dir gets created
  
Yes I made sure to `echo $XDG_CACHE_HOME` to make sure that it was defined, it still creates the ~/.cache directory.

This issue doesn't happen with other window managers like i3 or Hyprland.

**Comment by emersion** [comment]
Unlikely to be due to Sway: it doesn't do anything special with env vars.

**Comment by Samueru-sama** [comment]
> Unlikely to be due to Sway: it doesn't do anything special with env vars.

Is there a way to check what's creating the directory? Once again this was tested with the default configuration and doesn't hapoen with other window managers.

Also I dont think the issue is the how env var gets treated, but that there is some hardcoded path to `~/.cache`.

**Comment by emersion** [comment]
It could be that Mesa uses `secure_getenv()` which refuses to read the env because Sway has `CAP_SYS_NICE`, maybe?

**Comment by kennylevinsen** [comment]
To clarify, sway has no involvement in this and cannot fix it, hence closing.

mesa uses `secure_getenv` to get `XDG_CACHE_HOME` (a bit silly perhaps, and done in two locations), which means that if you set `CAP_SYS_NICE` on sway, mesa will not see the variable. The only option is to not set `CAP_SYS_NICE`, or to change mesa.

**Comment by Samueru-sama** [comment]
> To clarify, sway has no involvement in this and cannot fix it, hence closing.
> 
> mesa uses `secure_getenv` to get `XDG_CACHE_HOME` (a bit silly perhaps, and done in two locations), which means that if you set `CAP_SYS_NICE` on sway, mesa will not see the variable. The only option is to not set `CAP_SYS_NICE`, or to change mesa.

Hi, one thing I don't understand is that I set `XDG_CACHE_HOME` on my zsh config before I even start sway, why does it still fail to get the right dir?

I use a few appimages that internally use bubblewrap with `CAP_SYS_NICE` and I don't have this issue with the mesa dir showing up.

**Comment by kennylevinsen** [comment]
`secure_getenv` will refuse to read environment variables if the calling process executing it has any capabilities like `CAP_SYS_NICE` set. See `man 3 getenv`.
