### ISSUE TITLE
Alacritty is having problems opening in Sway

### ISSUE THREAD

**Issue by PrathmeshVishwakarma** [swaywm/sway#8195]
### Version
- **Sway Version: 1.9**

- **Debug Log:**
- https://paste.ofcode.org/RDCVty87U5gbUj7Eg3B9Rw
- https://paste.ofcode.org/em3BWMWHtNdjDw3uxFcV8L

- **Configuration File:**
- No configuration as such, rather than adding gaps to tabs

- **Description:**
- I asked the same bug in Alacritty issues, they forwarded me to Sway repo. 
- I googled, it says people with nvidia graphics drivers are having an issue, but I have an amd graphics
- I am running VMware 17, if that matters (which changes my Graphics to `VMware SVGA II Adapter`)
Thanks.

**Comment by llyyr** [comment]
> I have an amd graphics

You have virtual VMware SVGA graphics, not amd graphics. This is probably the problem, figure out GPU passthrough or use a terminal that's not gpu accelerated.

**Comment by PrathmeshVishwakarma** [comment]
Yeah, I mentioned that below. I see the issue here. Thanks
