### ISSUE TITLE
MPV with dmabuf-wayland No Output

### ISSUE THREAD

**Issue by sakarie9** [swaywm/sway#8198]
- **Sway Version:**
  - sway version 1.10-dev-2e9139df (Jun  4 2024, branch 'makepkg')

- **Debug Log:**
  - https://pastebin.com/4P1B60Rz

- **Configuration File:**
  - Default config

- **Description:**
  - MPV with `--vo=dmabuf-wayland` on the latest -git sway is not showing any window, although it works well on release 1.9
  - Other VOs like `--vo=gpu-next` works
  - Reproduce: playing any video using `mpv --no-config --vo=dmabuf-wayland /path/to/video.mp4`, no window is displayed, and mpv prints errors as below
  ```
   (+) Video --vid=1 (*) (h264 1080x1920 24.000fps)
   (+) Audio --aid=1 (*) (aac 2ch 48000Hz)
  [hwupload] no support for this hw format
  [hwupload] hardware format not supported
  [autoconvert] HW-uploading to drm_prime
  [hwupload] upload yuv420p -> drm_prime[yuv420p]
  [hwupload] failed to upload frame
  Cannot convert decoder/filter output to any format supported by the output.
  Could not initialize video chain.
  Video: no video
  ```

**Comment by cal-andrew** [comment]
Could be related to intel/intel-vaapi-driver#566 not being merged yet (if you have an Intel GPU), in which case #7916 might help.

**Comment by sakarie9** [comment]
> Could be related to [intel/intel-vaapi-driver#566](https://github.com/intel/intel-vaapi-driver/pull/566) not being merged yet (if you have an Intel GPU), in which case #7916 might help.

I'm using an AMD iGPU as wlroots render device, so this may not be related?

**Comment by bl4ckb0ne** [comment]
> 00:00:01.459 [ERROR] [wlr] [types/xdg_shell/wlr_xdg_surface.c:169] A configure is scheduled for an uninitialized xdg_surface 0x5a10bbe04b60

Might be unrelated but that's a bit weird.

**Comment by llyyr** [comment]
> I'm using an AMD iGPU as wlroots render device, so this may not be related?

vaapi is used on amd as well, although dmabuf-wayland should work for yuv420p even in the absence of vaapi but you should try running sway with `sway -Dlegacy-wl-drm`.

Also mpv logs would be more useful here, `mpv --no-config --vo=dmabuf-wayland --log-file=mpvsucks.log [video]`

**Comment by sakarie9** [comment]
> > I'm using an AMD iGPU as wlroots render device, so this may not be related?
> 
> vaapi is used on amd as well, although dmabuf-wayland should work for yuv420p even in the absence of vaapi but you should try running sway with `sway -Dlegacy-wl-drm`.
> 
> Also mpv logs would be more useful here, `mpv --no-config --vo=dmabuf-wayland --log-file=mpvsucks.log [video]`

`sway -Dlegacy-wl-drm` indeed solved my problem, dmabuf-wayland works as expected now

And the mpv log of my issue here: https://pastebin.com/bE776G7b
