### ISSUE TITLE
Sway doesn't update window visibility when a container changes

### ISSUE THREAD

**Issue by WhyNotHugo** [swaywm/sway#8205]
### Sway Version

sway version 1.10-dev-40ca4150b (Jun 10 2024, branch 'master')

I've seen this bug for several weeks now, I think it was introduced with the scene graph changes.

### Debug Log

https://paste.sr.ht/~whynothugo/a7173261a6e1d238ddb739a040b70080921fe84b

### Configuration File

    exec foot
    exec foot
    # You'll need these mapping to easily reproduce the issue.
    bindsym Mod4+a focus parent
    bindsym Mod4+shift+s move container to scratchpad

### Stack Trace

No crash

### Description

- Start on an empty workspace
- Open a terminal
- Open another terminal
- `focus parent`
- `move container to scratchpad`
- **BUG: Both windows are still there**
- Switch to another workspace and back
- Windows are gone (they're now in the scratchpad).

Note that you can still interact with the windows in shrödinger's scratchpad until you switch to another workspace (when they disappear).

**Comment by WhyNotHugo** [comment]
There is another sequence of step with similar results, and I suspect they are the same issue:

- Open FOUR terminals.
- Switch to a tabbed layout.
- Focus the second terminal
- Split vertically
- Focus the fourth terminal
- `move left` twice
- The tab-bar shows the second tab as active, but the third tab is visible (although we never unfocused the terminal that is not part of the split inside the second tab).
- `move left` again (nothing happens on screen, although the window moves to the left inside the split)
- `move left` again. The focused terminal (originally on the far right) has now escaped the split without it ever having been rendered inside the split.

**Comment by WhyNotHugo** [comment]
I bisected the issue, but had to skip a lot of commits that either don't build, or render a black screen.

The first bad commit could be any of:

188811f80861caacd016b857b0d07f6d2d62d15a
5b8b505af5d5925ae9e617ee8f3c7a0f9c43409d
6d7b1321db54155cf78305dbafdcfc7de9b78415
946fc8094559801bc4be629368ac31025d28165a
08c484f46f130aa7e590ef4bcb39d2ceed7160f6
869baff25221e1a1881e9559453faa43f90da33e
b38ed8b4792928dca3e1580e8160792ea41e25c4
bac3ab552683516ee5a09632468cd8de529d311f
6e5fc4c2aafd211323c6037aa868c075852bfe15
9a579666068d62b9354a39941e1ac8c1f4a58093
0639bde9fb5637fbe63c65bfe85660745f159b96
ed2724bd6c83ad3fdc2010b3a1e2f5967f0e8b38
06ad734e70227ad0527fe11b88ad37e93005ce0c
c640c3015f3a7ea2987bd7854d13ff282f90804f
1e018e72b4d57c8f354b9be9686a7a75797cdcab
9c17cba0b29979ae23c4521b884f7419fd558770
0e1a02bf0aad3d743985602b55043c5de019d1f0
5f0801b6f245cc789ea93b9449dd0c573ef36e66
2e53de80bb0f4c93e74ae050fa07e78f18e909d9

I seems that the bug was introduced with the scene graph changes. I'm not sure that this information is of any use.

**Comment by Nefsen402** [comment]
I didn't know this issue existed. I'll look at it now.

**Comment by Nefsen402** [comment]
> There is another sequence of step with similar results, and I suspect they are the same issue:

I cannot reproduce this issue. Mind sending a recording of the steps being reproduced?

**Comment by WhyNotHugo** [comment]
Sorry, I couldn't make a clear video showing the issue (you can't really understand what's going on in a video). I've made a reproduction script which should help you visualise the issue: https://github.com/swaywm/sway/issues/8292
