### ISSUE TITLE
Fullscreen applications not rendered on external monitor on a 2x AMD system with Vulkan renderer

### ISSUE THREAD

**Issue by lpaulino07** [swaywm/sway#8206]
- **Sway Version:**
  - sway version 1.10-dev-cc342107

- **Debug Log:**
  - https://gist.github.com/lpaulino07/1ac0a761094114964c3baee6c34a19b4
  - Relevant portion?

 ```
00:00:10.152 [DEBUG] [sway/commands/bind.c:618] running command for binding: fullscreen
00:00:10.153 [INFO] [sway/commands.c:260] Handling command 'fullscreen'
00:00:10.153 [DEBUG] [sway/tree/arrange.c:262] Usable area for ws: 1920x1059@0,21
00:00:10.153 [DEBUG] [sway/tree/arrange.c:296] Arranging workspace '1' at 0.000000, 21.000000
00:00:10.153 [DEBUG] [sway/tree/arrange.c:262] Usable area for ws: 1920x1059@0,21
00:00:10.153 [DEBUG] [sway/tree/arrange.c:296] Arranging workspace '2' at 1920.000000, 21.000000
00:00:10.153 [DEBUG] [sway/desktop/transaction.c:787] Transaction 0x5fb91a9eee40 committing with 3 instructions
00:00:10.170 [DEBUG] [sway/desktop/transaction.c:873] Transaction 0x5fb91a9eee40 is ready
00:00:10.170 [DEBUG] [sway/desktop/transaction.c:683] Applying transaction 0x5fb91a9eee40
00:00:10.171 [DEBUG] [wlr] [types/scene/wlr_scene.c:1843] Direct scan-out enabled
00:00:10.171 [ERROR] [wlr] [backend/drm/renderer.c:88] Failed to import source buffer into multi-GPU renderer
00:00:10.172 [ERROR] [wlr] [backend/drm/renderer.c:88] Failed to import source buffer into multi-GPU renderer
00:00:14.364 [ERROR] [wlr] [backend/drm/renderer.c:88] Failed to import source buffer into multi-GPU renderer
00:00:14.454 [ERROR] [wlr] [backend/drm/renderer.c:88] Failed to import source buffer into multi-GPU renderer
```

- **Configuration File:**
  - Default configuration file.

- **Description:**
  - Making a window fullscreen (Super + F) will stop the screen from rendering anything on that workspace until fullscreen is removed (Super + F again). The window itself still works (I can still type into a "frozen" terminal, and I can hear audio on a fullscreen video player), but the visual updates won't show until fullscreen is removed. This issue is not present on sway 1.9. Also, I think it's worth noting that it never actually goes into fullscreen (I can still see waybar sections on the screen).

**Comment by lpaulino07** [comment]
Turns out that this is only happening on external monitor (this is a laptop, and monitor is connected through a mini-DP to DP cable). Changed title of this issue.

**Comment by emersion** [comment]
Does it work with the GLES2 renderer?

**Comment by lpaulino07** [comment]
Just tried with `WLR_RENDERER=gles2`  and it still happens, but I get this instead:

```
00:00:35.397 [INFO] [sway/commands.c:260] Handling command 'fullscreen'
00:00:35.397 [DEBUG] [sway/ipc-server.c:326] Sending window::fullscreen_mode event
00:00:35.397 [DEBUG] [sway/tree/arrange.c:262] Usable area for ws: 1920x1020@0,30
00:00:35.397 [DEBUG] [sway/tree/arrange.c:296] Arranging workspace '2' at 1920.000000, 30.000000
00:00:35.397 [DEBUG] [sway/desktop/transaction.c:787] Transaction 0x5ca46e6410f0 committing with 2 instructions
00:00:35.402 [DEBUG] [wlr] [render/gles2/renderer.c:158] Created GL FBO for buffer 1920x1080
00:00:35.403 [DEBUG] [sway/desktop/transaction.c:873] Transaction 0x5ca46e6410f0 is ready
00:00:35.403 [DEBUG] [sway/desktop/transaction.c:683] Applying transaction 0x5ca46e6410f0
00:00:35.405 [DEBUG] [wlr] [types/scene/wlr_scene.c:1843] Direct scan-out enabled
00:00:35.405 [ERROR] [wlr] [EGL] command: eglCreateImageKHR, error: EGL_BAD_MATCH (0x3009), message: "createImageFromDmaBufs failed"
00:00:35.405 [ERROR] [wlr] [render/egl.c:778] eglCreateImageKHR failed
00:00:35.405 [ERROR] [wlr] [backend/drm/renderer.c:88] Failed to import source buffer into multi-GPU renderer
00:00:35.408 [DEBUG] [wlr] [render/gles2/renderer.c:158] Created GL FBO for buffer 1920x1080
00:00:35.408 [ERROR] [wlr] [EGL] command: eglCreateImageKHR, error: EGL_BAD_MATCH (0x3009), message: "createImageFromDmaBufs failed"
00:00:35.408 [ERROR] [wlr] [render/egl.c:778] eglCreateImageKHR failed
00:00:35.408 [ERROR] [wlr] [backend/drm/renderer.c:88] Failed to import source buffer into multi-GPU renderer
```
I also just realized that it seems to be app dependent (with both vulkan and GLES2), since I tried using Firefox and noticed that I was able to make it go fullscreen. I tested with some of the apps that I have installed in case that helps.

- Some apps that work: Firefox, Chromium (with --ozone-platform-hint=auto), Thunderbird, lapce, OBS Studio.
- Some apps that don't work: VLC media player, FileZilla, GIMP Nightly, qBitorrent, Nyxt browser, LibreOffice Suite, FreeCAD, Alacritty.

Something really strange that I noticed while testing these apps is that if I have OBS Studio open and capturing the display, all of the apps will magically start working in fullscreen. Not sure what's the relation but it seems like I can straight up work around the issue by just having OBS Studio open, and the errors don't show up in the logs anymore. Instead, I get these 4 lines being spammed in the log while OBS is capturing the display:

```
00:19:03.386 [DEBUG] [wlr] [types/output/render.c:146] Enabling direct scan-out on output 'DP-1' (locks: 0)
00:19:03.386 [DEBUG] [wlr] [types/output/cursor.c:54] Enabling hardware cursors on output 'DP-1' (locks: 0)
00:19:03.387 [DEBUG] [wlr] [types/output/render.c:146] Disabling direct scan-out on output 'DP-1' (locks: 1)
00:19:03.388 [DEBUG] [wlr] [types/output/cursor.c:54] Disabling hardware cursors on output 'DP-1' (locks: 1)
```

**Comment by lpaulino07** [comment]
Issue is present in sway 1.10rc1. It behaves pretty much the same way: some apps are able to go full screen while others are not, and letting OBS capture the screen fixes the issue for all apps.

Anyways, the error is slightly different now, in case it helps:

```00:00:18.526 [DEBUG] [sway/desktop/transaction.c:798] Transaction 0x5e6d8d715630 committing with 4 instructions
00:00:18.526 [ERROR] [wlr] [render/vulkan/texture.c:527] Format AR24 (0x34325241) can't be used with modifier GFX9,GFX9_64K_D_X,DCC,DCC_PIPE_ALIGN,DCC_INDEPENDENT_64B,DCC_MAX_COMPRESSED_BLOCK=64B,DCC_CONSTANT_ENCODE,PIPE_XOR_BITS=2,BANK_XOR_BITS=0,RB=1,PIPE_2 (0x020000044051BA01)
00:00:18.526 [ERROR] [wlr] [backend/drm/renderer.c:88] Failed to import source buffer into multi-GPU renderer
00:00:18.526 [ERROR] [sway/desktop/output.c:307] Page-flip failed on output DP-1
00:00:18.530 [DEBUG] [sway/desktop/transaction.c:884] Transaction 0x5e6d8d715630 is ready
00:00:18.530 [DEBUG] [sway/desktop/transaction.c:694] Applying transaction 0x5e6d8d715630
00:00:18.531 [DEBUG] [wlr] [types/scene/wlr_scene.c:1858] Direct scan-out disabled```

**Comment by Nefsen402** [comment]
Looks like a multi-gpu fault.

**Comment by emersion** [comment]
Does `WLR_SCENE_DISABLE_DIRECT_SCANOUT=1` help? If so, sounds like we're sending a bad modifier list when a surface is fullscreen on multi-GPU setups.

**Comment by lpaulino07** [comment]
Yeah, `WLR_SCENE_DISABLE_DIRECT_SCANOUT=1` fixes it.

**Comment by lpaulino07** [comment]
Fixed by https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4932.
