### ISSUE TITLE
Terminal doesn't reach the bottom of the screen

### ISSUE THREAD

**Issue by juru1234** [swaywm/sway#8220]
- **Sway Version: 1.9**

- **Debug Log: https://gist.github.com/juru1234/ad5cfb89634ffadc61776a36aa723cb7**

- **Configuration File: default**

- **Description:**
  - Sometimes there is some padding at the bottom when using the terminal. Then the terminal doesn't reach the bottom of the screen as seen in the picture.
![image](https://github.com/swaywm/sway/assets/6987211/4f9d7c2e-e0cf-4c9e-b139-27924330359a)
This only happens with foot/alacritty windows. Not e.g. with Firefox.  Firefox always goes completely to the bottom. 
It also seems that this bug depends on the resolution. When using exclusively my external screen (2560 x 1440) the terminal goes completely to the bottom. But not when using my 1920x1080px laptop screen exclusively.

**Comment by juru1234** [comment]
Surprisingly it works well with kitty. But not with alacritty and foot.

**Comment by mwiens91** [comment]
@juru1234 Did you ever manage to fix this issue in alacritty or foot?

**Comment by smlx** [comment]
Have you tried this option in foot?

https://codeberg.org/dnkl/foot/src/commit/6183d1b767480b0a96db967e0e1e268317966ce6/doc/foot.ini.5.scd#L357-L370

**Comment by mwiens91** [comment]
> Have you tried this option in foot?
> 
> https://codeberg.org/dnkl/foot/src/commit/6183d1b767480b0a96db967e0e1e268317966ce6/doc/foot.ini.5.scd#L357-L370

Yes, I did. Unfortunately it seems to have no impact on this issue for me.

My current band-aid solution is to set some vertical padding with

`pad=0x9`

Interestingly this reduces the total amount of apparent bottom padding, but whether there is a reduction or not is very sensitive to the exact pixel value in the above setting. 9 pixels was the sweet spot for me.

**Comment by juru1234** [comment]
> [@juru1234](https://github.com/juru1234) Did you ever manage to fix this issue in alacritty or foot?

I'm using alacritty with `dynamic_padding = true`
