### ISSUE TITLE
Support digits of Arabic numbers in the config file.

### ISSUE THREAD

**Issue by Doods0** [swaywm/sway#8254]
- **Sway Version:**
sway version 1.7

[**Debug Log**](https://gist.github.com/Doods0/f9e5aa4165ffb08c715836dd13e0a1a5)

- **Configuration File:**
Any config containing this should work:
```
    # Switch to workspace (Arabic)
    bindsym $mod+١ workspace number 1
```

- **Description:**

I wanted to add `ara(digits)` to the list of layouts I am using. In contrast to normal `ara`, which uses numbers from 0-9, `ara(digits)` uses the digits ٩-٠.

The problem arised when I tried to switch layouts using `$mod+١`, which - obviously - did not work, so I tried to manually bind it (and the 19 other keybinds), then I reloaded the config, only to meet this error: `'bindsym $mod+١ workspace number 1': Unknown key or button '١'`.

This isn't a big deal since you made such a beautiful program, but I would be thankful if you could resolve this issue.

**Comment by emersion** [comment]
The name of the key symbol is probably something else than "١". You can find out with e.g. `wev`.

**Comment by Doods0** [comment]
Many thanks emersion, the keys were indeed named Arabic_1-Arabic_9.

This issue was hard to write as I have been learning *Colmak-DH*.
