### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by the8472** [swaywm/sway#8278]
- **Sway Version:** 1.9 (arch package 1:1.9-5)

- **Debug Log:** No logs available, I have already closed the virtual terminal where it happened

- **Configuration File:** I was using the default sway configuration that comes with the arch package

- **Stack Trace:** [sway-stack.txt](https://github.com/user-attachments/files/16514723/sway-stack.txt)

- **Description:** Sway crashed while testing drag&drop between firefox and nemo. I was not able to reproduce it.

If the stacktrace is not informative feel free to close this since I don't know how to reproduce it.

**Comment by emersion** [comment]
Not debuggable, sorry. We'd need a reproducer on latest commit and a better stack trace.
