### ISSUE TITLE
Slight refactor of focus.c

### ISSUE THREAD

**Issue by acrisci** [swaywm/sway#828]
I've taken a look at focus.c and I want to do some refactoring, specifically in `set_focused_container()` and some places that call it. My goals are:
- Make logic clear to prevent rending of the same container twice
- Merge paths of rendering for stack/tab and normal containers as much as possible
- Make sure ipc events are emitted properly and in the right order
- Make sure an output is never focused

**Comment by SirCmpwn** [comment]
That sounds like a pretty solid set of goals. :+1:
