### ISSUE TITLE
Run "wmenu-run" instead of "wmenu" in default config

### ISSUE THREAD

**Issue by o-alquimista** [swaywm/sway#8286]
**Sway Version:**
1.9

**Description:**
By default, Sway calls `wmenu`, which doesn't have suggestions enabled (see issue for context): https://codeberg.org/adnano/wmenu/issues/12

https://github.com/swaywm/sway/blob/951a22c2445f5c32b831bac0db86869627940402/config.in#L21

The documentation of wmenu tells us to run `wmenu-run`. From the [README](https://codeberg.org/adnano/wmenu/src/commit/12b8f83be447379eded03c6109fe944945cd48aa#usage):
> To use wmenu with Sway, you can add the following to your configuration file:
>
> `set $menu wmenu-run`

And suggestions will work.

Draft PR #8151 appears to be related.

**Comment by emersion** [comment]
`dmenu_path` generates the suggestions.

**Comment by o-alquimista** [comment]
> `dmenu_path` generates the suggestions.

Sorry, I don't get it. What is `dmenu_path`?

**Comment by apprehensions** [comment]
`dmenu_path` is a script that utilizes a in-house file status utility program called `stest` to list all programs in `$PATH` with caching capabilities

**Comment by o-alquimista** [comment]
> `dmenu_path` is a script that utilizes a in-house file status utility program called `stest` to list all programs in `$PATH` with caching capabilities

Well, it's not working for me.

@emersion Should I create a new issue for this?

**Comment by apprehensions** [comment]
This is out of scope for Sway.

**Comment by emersion** [comment]
Most likely you don't have it installed.

**Comment by o-alquimista** [comment]
> Most likely you don't have it installed.

It's not obvious to me which package provides that, but this showed up on my search results: https://gitlab.archlinux.org/archlinux/packaging/packages/sway/-/issues/3

I'll try to install `dmenu` later. Will close this issue if that fixes it.

**Comment by o-alquimista** [comment]
That's it. Not a bug. Thanks for the help.

I'll propose adding _dmenu_ as an optional dependency to the Sway package on Void Linux.

**Comment by o-alquimista** [comment]
I've added a Troubleshooting item in the wiki to document this. Void Linux won't add the dependency.

https://github.com/swaywm/sway/wiki#wmenu-doesnt-show-command-suggestions-as-you-type

**Comment by emersion** [comment]
The real fix is still to switch to wmenu-run: https://github.com/swaywm/sway/pull/8289
