### ISSUE TITLE
xwayland windows are ran with llvmpipe on master

### ISSUE THREAD

**Issue by Stoppedpuma** [swaywm/sway#8288]
- **Sway Version:**
1.10-dev-951a22c2 (Aug  8 2024, branch 'master')

- **Debug Log:**
https://puma.s-ul.eu/pxMO3pxO

- **Description:**
Windows running under xwayland will use software rendering instead of hardware. This issue doesn't happen under native Wayland windows. Running programs such as vkcube will spit out the follow error: `vulkan: No DRI3 support detected - required for presentation`.

**Comment by emersion** [comment]
Does `-Dlegacy-wl-drm` help?

**Comment by Stoppedpuma** [comment]
That would be the reason! I forgot I was using a custom branch of xwayland.
