### ISSUE TITLE
Unreal engine's popup windows and context menus don't work on sway.

### ISSUE THREAD

**Issue by sarahkittyy** [swaywm/sway#8304]
- **Sway Version:**
  - 1.9

- **Description:**

Unreal engine works horribly under sway. The right click context menus appear and then disappear after a frame. The drop-downs like File, Edit, etc require LMB to be held to use them. None of the pop-up dialogs are interactable. I switched to i3 and also tried cinnamon and it works perfectly under both. One of my coworkers also had to switch. I believe this is a sway issue and not a wayland issue.

**Comment by sahinf** [comment]
https://github.com/swaywm/sway/wiki#how-do-i-report-issues

I just googled "unreal engine for wayland" and this [post](https://forums.unrealengine.com/t/theres-a-way-to-run-or-build-ue-5-with-wayland-support/1744085/5) on their forums suggests it currently doesn't work under Wayland. i3 is xorg. 

In fact people from other Wayland compositors are [reporting](https://forums.unrealengine.com/t/ue-5-4-3-crash-on-linux-wayland-with-nvidia-555-58-02/1949325/7) issues as late as 4 days ago. 

I wouldn't be so quick to blame Sway without a modicum of evidence.

**Comment by sarahkittyy** [comment]
On X11/cinnamon unreal works fine. I then tried switching to i3/X11 and started getting the exact same issues again. So it's not specific to wayland. believe it's a sway/i3 related issue, maybe related to how unreal handles popup windows or window focus or something.
