### ISSUE TITLE
wlr-randr failed to set output scale

### ISSUE THREAD

**Issue by lbwtw** [swaywm/sway#8309]
- **Sway Version:**
  - sway origin/v1.10 branch

- **Debug Log:**
  - Refer to the attached sway.log
[sway.log](https://github.com/user-attachments/files/16703107/sway.log)

- **Description:**
  - Use WAYLAND_DISPLAY=wayland-1 wlr-randr --output DP-1 --scale 2 to set the scale, wlr-randr reports an error "failed to apply configuration"

**Comment by lbwtw** [comment]
i discussed this issue in the IRC channel yesterday. I changed the computer and the problem still exists.

**Comment by lychee-yycy** [comment]
I started sway on one tty and then went to another tty to run wlr-randr which caused this problem
