### ISSUE TITLE
sway 1.10-rc normal layershell will be under the layershell with exclusive_zone

### ISSUE THREAD

**Issue by Decodetalkers** [swaywm/sway#8368]
### related code
https://github.com/waycrate/lala-bar/blob/master/lala_bar/src/main.rs#L982-L994
This the our code. we create a hidden panel, which has exclusive_zone, on the right of the screen. and the notify widget is just normal layershell on the right top corener. but now when a new hidden panel is created, the layershell will be under the widget which has excludezone

### Please fill out the following:
- **Sway Version:**
 `sway version 1.10-rc1`

- **Description:**

I think there maybe some bugs with the layershell..

https://github.com/user-attachments/assets/496ec039-7c19-4ace-8939-8edfe2ce68c9

**Comment by Nefsen402** [comment]
Maybe the two layer shells are on different layers?

**Comment by Nefsen402** [comment]
Does https://github.com/swaywm/sway/pull/8385 help?

**Comment by Decodetalkers** [comment]
Yes, then are on the same layer, LayerTop. and , yes, that pr solved! Thanks!

**Comment by Nefsen402** [comment]
Liked PR was merged
