### ISSUE TITLE
Layershell, cannot switch position from LEFT | RIGHT | BOTTOM to TOP | LEFT | BOTTOM

### ISSUE THREAD

**Issue by Decodetalkers** [swaywm/sway#8369]
### related code

https://github.com/waycrate/exwlshelleventloop/blob/master/iced_examples/counter/src/main.rs#L95-L99

### Please fill out the following:
- **Sway Version:**
  - `sway version 1.10-rc1`

- **Debug Log:**
https://gist.github.com/Decodetalkers/e95277d09554e19dc84c9e91dfb82408

[log.txt](https://github.com/user-attachments/files/17211121/log.txt)

- **Description:**
 - the program above just switch layershell from LEFT|RIGHT|BOTTOM to TOP|LEFT|BOTTOM, and from the log, it is be set to 7, because `1 | 2 | 4 = 7`

**Comment by vyivel** [comment]
The log is either truncated or invalid; there's no `zwlr_layer_surface_v1#16` creation sequence, for example.

This, however, seems like a bug in the client, given that it doesn't match the code:

```
[3882072.719]  -> zwlr_layer_surface_v1#16.set_anchor(7)
[3882072.754]  -> wl_surface#14.commit()
```

**Comment by Decodetalkers** [comment]
> The log is either truncated or invalid; there's no `zwlr_layer_surface_v1#16` creation sequence, for example.
> 
> This, however, seems like a bug in the client, given that it doesn't match the code:
> 
> ```
> [3882072.719]  -> zwlr_layer_surface_v1#16.set_anchor(7)
> [3882072.754]  -> wl_surface#14.commit()
> ```

Ok , I upload the full log, it is little huge.. 

Emm, what do you mean it doesn't match the code? I think the anchor is 7, because it is set to TOP | LEFT | BOTTOM

**Comment by Decodetalkers** [comment]
I see, is  it because that I set the anchor , but now the width is still set as 0? maybe I can give it a (1, 400) first then set to (400, 0)

**Comment by vyivel** [comment]
Within a single commit (atomic surface state update), only the anchor is updated, and the desired size (0x400) remains. The resulting state violates the protocol.

The sequence should be something like

```
zwlr_layer_surface_v1#16.set_anchor(7)
zwlr_layer_surface_v1#16.set_size(400, 0)
wl_surface#14.commit()
```

Closing this as a client bug.

**Comment by Decodetalkers** [comment]
> Within a single commit (atomic surface state update), only the anchor is updated, and the desired size (0x400) remains. The resulting state violates the protocol.
> 
> The sequence should be something like
> 
> ```
> zwlr_layer_surface_v1#16.set_anchor(7)
> zwlr_layer_surface_v1#16.set_size(400, 0)
> wl_surface#14.commit()
> ```
> 
> Closing this as a client bug.

Thank you very much
