### ISSUE TITLE
Sway randomly crashes when a monitor is connected to a laptop

### ISSUE THREAD

**Issue by PowerMan2206** [swaywm/sway#8373]
- **Sway Version:** 1.9

- **Debug Log:** https://gist.github.com/PowerMan2206/6c4ce786afc61673412ac8f4d2c3fcee
  
- **Configuration File:** default config (just `mv sway swaymoved` in .config so that it uses default)

- **Stack Trace:** crash happens with already installed binaries (built without debug symbols), cannot reproduce within a reasonable timeframe when compiled from source

- **Description:** I got a Lenovo Legion 5 laptop (with apparently very good Linux support) with both Nvidia 30 series and AMD integrated graphics. I'm *pretty* sure I'm using the integrated AMD ones when in Sway, but I don't know how to check for sure. Even if it does use the Nvidia one, though, that shouldn't be an issue because I don't have any proprietary drivers installed, so it would use nouveau.

  (EDIT: upon viewing the debug log, I can see on like 38 that it's apparently using the Nvidia card)

  Sway works fine when running by itself just on the laptop screen, but when I connect any kind of monitor to the HDMI output, it crashes after a random amount of time. I think it's important to emphasize that, from what I've seen, it only happens when I do something, not when it's just sitting and doing nothing. I.e. when moving the mouse.

**Comment by sahinf** [comment]
https://github.com/swaywm/sway/issues/8279 related? Can you test moving your mouse to crash it?

**Comment by PowerMan2206** [comment]
I did mention that it happens only when doing somthing, like moving the mouse.

**Comment by PowerMan2206** [comment]
Looks like using [this conifg](https://github.com/swaywm/sway/wiki#i-have-a-multi-gpu-setup-like-intelnvidia-or-intelamd-and-sway-does-not-start--some-video-cards-cannot-display--full-screen-images-etc-will-be-corrupted) from the wiki seemed to fix it. Although it's the reverse of what it says? I put the integrated AMD graphics as the 2nd one (what the wiki says will be copied) and the Nvidia ones as the 1st one (what it says will be used for rendering), but the debug log says it's using AMD, so it's probably just an error on the wiki.

New problem, mouse doesn't work on Xwayland programs on the connected monitor. *But* that's an issue for another day. We ballin now.
