### ISSUE TITLE
1.10-rc3 pop ups protruding outside the window are cut off

### ISSUE THREAD

**Issue by ToxicMushroom** [swaywm/sway#8397]
### Please fill out the following:
- **Sway Version:**
sway version 1.10-rc3-dc8f5338 (Oct 19 2024, branch 'v1.10')

- **Debug Log:**
[sway.log](https://github.com/user-attachments/files/17448321/sway.log)

- **Configuration File:**
default one

- **Description:**
Opening a large gtk popup like below that goes out of bounds is cut off.
This was not the case in 1.9 on my laptop, not the case in hypeland.
![image](https://github.com/user-attachments/assets/2abe8887-d840-409f-bf64-7e08242762da)

**Comment by ToxicMushroom** [comment]
fwiw also happens when tiled

**Comment by Nefsen402** [comment]
I cannot reproduce this even with other GTK apps. Perhaps this has to do specifically with the popup that gnome happens to use for the QR code? Gnome might be using a subsurface in which case this behavior is intentional and this is an app bug. What application was being used here?

**Comment by ToxicMushroom** [comment]
That's gajim, I dont use gnome so I wouldn't know

**Comment by Nefsen402** [comment]
I don't think I can get to that popup window without setting up an account on the application.
Does applying this patch workaround the issue?
```diff
diff --git a/sway/tree/view.c b/sway/tree/view.c
index 492095b9..6fcbb283 100644
--- a/sway/tree/view.c
+++ b/sway/tree/view.c
@@ -959,7 +959,7 @@ void view_center_and_clip_surface(struct sway_view *view) {
                                .height = con->current.content_height,
                        };
                }
-               wlr_scene_subsurface_tree_set_clip(&con->view->content_tree->node, &clip);
+               //wlr_scene_subsurface_tree_set_clip(&con->view->content_tree->node, &clip);
        }
 }
```

**Comment by ToxicMushroom** [comment]
that doesnt build

**Comment by Nefsen402** [comment]
I updated the patch so that it will build. It didn't build before because of an unused variable.

Better yet, apply this patch:  https://github.com/Nefsen402/sway/commit/cdee33e2f55e67aa88f1e7b6b82348fe248d1d55

Running `swaymsg -t get_scene_tree` will confirm if the fault is with the application using a subsurface or it will give some clues about what might be the problem with the popup.

**Comment by ToxicMushroom** [comment]
here is the swaymsg -t get_scene_tree output with the cut off pop up opened
[scene-tree.txt](https://github.com/user-attachments/files/17452162/scene-tree.txt)

**Comment by Nefsen402** [comment]
Thanks for the fast reply. It looks like this is an application bug unfortunately. The important part of the log is here:

```json
{
  "x": 0,
  "y": 0,
  "enabled": true,
  "tree": [
    {
      "x": 0,
      "y": 0,
      "enabled": true,
      "has_buffer": true,
      "is_surface": true,
      "type": "WLR_SCENE_NODE_BUFFER",
      "descriptors": []
    },
    {
      "x": 447,
      "y": -277,
      "enabled": true,
      "tree": [
        {
          "x": 0,
          "y": 277,
          "enabled": true,
          "has_buffer": true,
          "is_surface": true,
          "type": "WLR_SCENE_NODE_BUFFER",
          "descriptors": []
        }
      ],
      "type": "WLR_SCENE_NODE_TREE",
      "descriptors": []
    }
  ],
  "type": "WLR_SCENE_NODE_TREE",
  "descriptors": []
}
```

It looks like the application is using a subsurface to render the popup. Noting the two `WLR_SCENE_NODE_BUFFER` nodes. One buffer is for the application proper, the second with an offset of x: 447, y: -277 is the one for the QR code.

I posted an issue with the gajim project here: https://dev.gajim.org/gajim/gajim/-/issues/12129

Thanks for your patience.

**Comment by ToxicMushroom** [comment]
Thank you for creating the gajim issue for me and for your outstanding help :D !
