### ISSUE TITLE
copy paste dosen't work somtimes 

### ISSUE THREAD

**Issue by sachinchaudhary1808** [swaywm/sway#8409]
- **Sway Version:**
  - 1.9

- **Debug Log:**
  - Run `sway -d 2> ~/sway.log` from a TTY and upload it to a pastebin, such as gist.github.com.
  https://gist.github.com/sachinchaudhary1808/6383e8858e814a13c23beec79773e902
  

- **Description:**
  - so when i tried copying something from like foot terminal and then try to paste that text in my browser or neovim or anywhere there is nothing get pasted sometimes

**Comment by sachinchaudhary1808** [comment]
https://github.com/sachinchaudhary1808/nixos-dotfiles/blob/main/modules/config/sway/config
my config

**Comment by sachinchaudhary1808** [comment]
when i close the copy something from foot terminal and then close it i can't really paste anything

**Comment by sachinchaudhary1808** [comment]
> This is probably an issue with wl-paste in your config file, when you encounter the problem can you check if wl-paste is running without errors?

it does i think the main issue is when i close foot terminal or any terminal i can't paste anything i can only if having the terminal opened

**Comment by markstos** [comment]
This not clearly a Sway bug. I have had problems pasting into WezTerm sometimes, but not into Foot.

**Comment by sachinchaudhary1808** [comment]
okay i don't see the issue now it's just when i close the terminal and try to paste it which is some wayland thing idk
