### ISSUE TITLE
Hot-plugging a disabled head sends an additional "phantom" mode through the zwlr_output_head_v1 protocol

### ISSUE THREAD

**Issue by andriyDev** [swaywm/sway#8420]
### Please fill out the following:
- **Sway Version:**
  - sway 1.10

- **Debug Log:**
  - https://gist.github.com/andriyDev/70cd4e4f2593e2ac3ac8b5234899c291

- **Configuration File:**
  - Used the default config (except switched to term=alacritty, menu=wofi)

- **Description:**
  - Connect to sway with any app that supports the zwlr_output_management_v1 protocol and just listen to the events (Here's my [tiny Rust example](https://gist.github.com/andriyDev/c03fba9065ecca64a687c0ae82816fd8), you need the `wayland-client` and `wayland-protocols-wlr` dependencies).
  - Connect an external monitor (I am using a monitor connected through HDMI)
  - Disable the monitor (I did this using wdisplays which itself uses the output management protocol).
  - Disconnect the monitor
  - Reconnect the monitor
  - See that the new head sends a `mode` event, but this mode is never populated (its size and refresh rate are never sent).
  - **Bonus**: Adjust any monitor (e.g., change the position of another monitor, re-enable the disabled monitor), and a `finished` event will be sent for the "phantom" mode.

- **Other details:**
  - I tried this on `river` and `dwl` which both use wlroots 0.18. They do not seem to report this phantom mode, but they also have different behavior: Sway will keep the monitor disabled after hotplugging. `river` and `dwl` on the other hand will re-enable the monitor on hotplug (I suspect they are just treating the monitor as a brand new monitor). This is also why I've filed this issue against Sway and not `wlroots`.

**Comment by andriyDev** [comment]
Ok perhaps I'm misinterpreting the relationship with `river` and `dwl`. Something I didn't notice before (running two desktops at once and sharing a monitor): the "bonus" part seems to always re-enable the disabled monitor. That is, if you have two monitors eDP-1 and HDMI-A-1, apply the above steps to the HDMI-A-1 monitor, and then move eDP-1 (e.g., through wl-displays), HDMI-A-1 enables itself. So maybe `river` and `dwl` are doing something correctly that Sway isn't, resulting in this weird buggy behavior.

I assumed Sway was trying to be "smart" and keeping the monitor disabled since it was previously disabled, but maybe instead its a race condition of some kind. That could explain why after changing any other head, the "phantom" mode gets a finished event: the mode gets created accidentally which is sent before this phantom gets cleared server-side. Only later when another "done" batch is sent does the mode realize it doesn't exist and it "finishes" itself.

**Comment by emersion** [comment]
Do you have a `WAYLAND_DEBUG=1` log of your client?

**Comment by andriyDev** [comment]
Here you go! https://gist.github.com/andriyDev/dfc662d8ea79df1f61b1efdfc6fa2bad

**Comment by andriyDev** [comment]
Sorry, I just realized I misread your ask! Here's a `WAYLAND_DEBUG=1` from **my client** rather than Sway. https://gist.github.com/andriyDev/4af66bdb0795e74b180d8cccd805e8e3

Just like before, mode ~107 gets created but then never filled out!

**Comment by emersion** [comment]
Thanks for the logs! Does this help?

https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4899
