### ISSUE TITLE
Can't rename parent containers

### ISSUE THREAD

**Issue by ArijanJ** [swaywm/sway#8441]
## Description:
in i3, if I have two windows in a .... let me show you an image, since I doubt I can explain this properly:

![H\[foot foot\] which contains two successfully renamed foot terminal windows](https://github.com/user-attachments/assets/cfab21b7-dbe7-4738-b045-cb169659bcc0)

i3 lets me select the parent of one of the two terminals with mod+a (`focus parent`) and then call this bind:
```
bindsym $mod+F2 exec i3-input -F 'title_format "%s"' -P 'Rename container: '
```

This also works in Sway for a single window, but renaming a parent such as the screenshot doesn't seem to do anything. I usually use this when I have multiple terminals in a project and I call the container "terminals" or something similar. Please let me know if I'm missing something obvious :pray:

**Comment by emersion** [comment]
Sounds like a bug. Patches welcome!

**Comment by ArijanJ** [comment]
Sorry for the noise, it works properly on the latest git version, I just had an outdated package on the Fedora VM that I tested it on
![image](https://github.com/user-attachments/assets/1d8f87a2-be1b-48ec-8558-bcebe2d3fe21)

**Comment by ArijanJ** [comment]
@jamborm it's the same as i3, `select parent` and then `bindsym $mod+F2 exec i3-input -F 'title_format "%s"' -P 'Rename container: '` for the actual rename dialog  (using i3-input here as that's what I'm familiar with and seems to do the trick)

**Comment by ArijanJ** [comment]
Hey @emersion, I actually reinstalled Linux and I'm not sure whether sway has an alternative for the `i3-input` binary. Do you know how we could rename a container without having `i3-input` present?Sorry if I missed something obvious.

Edit: can just do `swaymsg 'title_format "new-title"'` with any tool like rofi or dmenu: https://github.com/swaywm/sway/issues/2#issuecomment-305380165
