### ISSUE TITLE
Sway 1.10 fails with "EGL_EXT_platform_base not supported" despite 1.7 claiming it to be supported

### ISSUE THREAD

**Issue by Nikratio** [swaywm/sway#8453]
With Sway 1.10, I get (full output at https://pastebin.com/1TqVFvbQ):

```
# sway --debug
[...]
00:00:00.009 [INFO] [wlr] [backend/drm/drm.c:268] Found 9 DRM planes
00:00:00.009 [INFO] [wlr] [render/egl.c:205] Supported EGL client extensions: 
00:00:00.009 [ERROR] [wlr] [render/egl.c:208] EGL_EXT_platform_base not supported
00:00:00.009 [ERROR] [wlr] [render/egl.c:523] Failed to create EGL context
00:00:00.009 [ERROR] [wlr] [render/gles2/renderer.c:499] Could not initialize EGL
00:00:00.009 [DEBUG] [wlr] [render/wlr_renderer.c:192] Failed to create a GLES2 renderer. Skipping!
00:00:00.009 [ERROR] [wlr] [render/wlr_renderer.c:272] Could not initialize renderer
00:00:00.009 [ERROR] [sway/server.c:236] Failed to create renderer
```

At first I thought this is obviously a GPU driver issue since my GPU doesn't support "EGL_EXT_platform_base". But then I noticed that Sway 1.7 claims that this is supported:

```
# grep "EXT_platform" sway_old.txt
00:00:00.010 [INFO] [wlr] [render/egl.c:180] Supported EGL client extensions: EGL_EXT_device_base EGL_EXT_device_enumeration EGL_EXT_device_query EGL_EXT_platform_base EGL_KHR_client_get_all_proc_addresses EGL_EXT_client_extensions EGL_KHR_debug EGL_EXT_platform_device EGL_EXT_platform_wayland EGL_KHR_platform_wayland EGL_EXT_platform_x11 EGL_KHR_platform_x11 EGL_EXT_platform_xcb EGL_MESA_platform_gbm EGL_KHR_platform_gbm EGL_MESA_platform_surfaceless
```

(full output at https://pastebin.com/bJFbMv8S)

Am I doing something wrong, or is this a bug in Sway?

(I'm using the Sway 1.7 Debian package and the Sway 1.10 Nix package).

**Comment by emersion** [comment]
Perhaps the GL driver for your hardware is not available from inside Nix? It indicates zero available extensions.

**Comment by Nikratio** [comment]
Hmm... I'm not sure if there is such a thing as "inside Nix" in this case. I'm not using a new namespace or anything like that, I'm just calling the binary from its install path in `/nix/store`.

Do you know how these extensions are discovered? Do they exist in form of files somewhere in the filesystem? Or does this go through some ioctl, Unix socket, syscall, ..?

**Comment by emersion** [comment]
Binaries inside Nix don't load libraries outside of Nix.

**Comment by Nikratio** [comment]
> Binaries inside Nix don't load libraries outside of Nix.

Yeah, but Nix dependencies should ensure that they don't need to, either, as far as I know.

Looking at `ldd sway`, it seems to find everything it needs (https://pastebin.com/byidCmsH).

Do you know which library is needed to provide GL drivers?

**Comment by emersion** [comment]
GL drivers are dynamically loaded with `dlopen()` depending on hardware so they don't show up in `ldd`.

**Comment by Nikratio** [comment]
It looks like it's finding everything it's looking for, in particular libEGL.so:

```
> WAYLAND_DISPLAY= strace -o sway.log -f -e %file /nix/store/vv0fbywzi417g8nfq3fdaygfn4hnkw72-sway/bin/sway 
00:00:00.004 [wlr] [backend/wayland/backend.c:601] Could not connect to remote display: Connection refused
00:00:00.005 [sway/server.c:228] Unable to create backend
> grep -i egl sway.log 
627960 openat(AT_FDCWD, "/nix/store/hinb0m8if8ic0dgm4h6dr2x3yk1f0qcr-libglvnd-1.7.0/lib/glibc-hwcaps/x86-64-v3/libEGL.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
627960 openat(AT_FDCWD, "/nix/store/hinb0m8if8ic0dgm4h6dr2x3yk1f0qcr-libglvnd-1.7.0/lib/glibc-hwcaps/x86-64-v2/libEGL.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
627960 openat(AT_FDCWD, "/nix/store/hinb0m8if8ic0dgm4h6dr2x3yk1f0qcr-libglvnd-1.7.0/lib/libEGL.so.1", O_RDONLY|O_CLOEXEC) = 3

```

(full output at https://pastebin.com/TBAjv9JN)

Do you happen to know what library specifically it should be looking for?

Also, thanks for all the suggestions so far!

**Comment by emersion** [comment]
This libEGL comes from glvnd. glvnd is a GL driver loader, it doesn't contain any real driver.

I'd suggest asking in a Nix forum how to install graphics drivers.

I'm closing this since it's unrelated to Sway.
