### ISSUE TITLE
`preferred_scale` notified before new `wl_output` global

### ISSUE THREAD

**Issue by OkamiW** [swaywm/sway#8463]
Since https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/0f255b46fcebceafb3e426c67777afe11a82fe1f
outputs are destroyed on tty switch.

When you switch back to compositor, `preferred_scale` is fired before new `wl_output` get created.

This breaks foot's assertion in `get_font_dpi`: `xassert(tll_length(term->wl->monitors) > 0)`, causing it to crash.

```
dbg: wayland.c:278: seat0: keyboard=yes, pointer=no, touch=no
dbg: wayland.c:1412: global removed: 0x0000003f
info: wayland.c:1423: monitor unplugged or disabled: HDMI-A-1
dbg: wayland.c:710: unmapped from HDMI-A-1
dbg: wayland.c:1412: global removed: 0x0000003e
info: wayland.c:1423: monitor unplugged or disabled: eDP-1
dbg: wayland.c:1761: fractional scale: 2.00 -> 1.00
dbg: wayland.c:729: wl_surface preferred scale: 2 -> 1
dbg: wayland.c:1761: fractional scale: 1.00 -> 2.00
dbg: wayland.c:729: wl_surface preferred scale: 1 -> 2
dbg: wayland.c:1092: global: 0x00000040, interface=wl_output, version=4
dbg: wayland.c:1092: global: 0x00000041, interface=wl_output, version=4
```

**Comment by OkamiW** [comment]
cc @kennylevinsen

**Comment by emersion** [comment]
Sounds like a foot bug.

**Comment by OkamiW** [comment]
> Sounds like a foot bug.

From the logic perspective, shouldn't `preferred_scale` event be fired after `new_output`? Since when there's no output, `preferred_scale` would be pointless.

**Comment by emersion** [comment]
There is no guarantee that there will be a `wl_output` global, and even less of a guarantee that `preferred_scale` events are tied to a particular `wl_output`. Example: a compositor with all outputs disconnected and with screen capture active.

**Comment by OkamiW** [comment]
By "screen capture", do you mean something like VNC? Last time I checked, with headless sway and wayvnc, there would still be a virtual output(not physical), right?

**Comment by emersion** [comment]
If Sway is started with `WLR_BACKENDS=headless`, there would be a headless output. If Sway is started normally with the DRM backend, there would be no output.

**Comment by OkamiW** [comment]
Reported to the foot issue tracker: https://codeberg.org/dnkl/foot/issues/1874
