### ISSUE TITLE
Frequent crash

### ISSUE THREAD

**Issue by J0nnyMak0** [swaywm/sway#8473]
Encountered crash after opening a new Sway session. Was not doing anything remarkable when the crash happened. No programs running. No external monitors connected.

[gdb.txt](https://github.com/user-attachments/files/17878156/gdb.txt)

Also consistently reproducible by just opening a terminal window and trying to exit out of it.

**Comment by vyivel** [comment]
Fixed by https://github.com/swaywm/sway/pull/8472.
