### ISSUE TITLE
Dual monitor configuration problem

### ISSUE THREAD

**Issue by akrram09** [swaywm/sway#8479]
### Please fill out the following:
- **Sway Version:**
1.10

- **Configuration File:**
`exec blueman-applet
exec_always "/home/akram/.config/sway/laptop.sh"
exec mako 
exec "/usr/libexec/polkit-gnome-authentication-agent-1"
smart_gaps on

# Logo key. Use Mod1 for Alt.
set $mod Mod4
# Home row direction keys, like vim
set $left h
set $down j
set $up k
set $right l
# Your preferred terminal emulator
set $term kitty 
set $files nautilus 
set $menu fuzzel 
### Output configuration
#
output eDP-1 {
    resolution 1920x1080
    scale 1.64
    transform normal
    pos 0 0 
}

output HDMI-A-2 {
    resolution 1366x768
    scale 1
    transform normal
    pos 1920 0
}
`

- **Description:**

i followed the wiki for configuring dual monitors but im facing a problem i have my laptop eDP-1 on the left and my monitor HDMI-A-2 on the right when i try to move to the next monitor using the mouse its not same direction like i need to move my mouse to the right to go to the left monitor i tried to switch pos between the 2 but still same the second problem is even tho i set the focus to be eDP-1 its not main monitor like when i connect HDMI-A-2 its HDMI-A-2 main monitor and take the first workspace

**Comment by parnavh** [comment]
I also was facing the same issue, something seems to have changed in 1.10
Earlier (using 1.9) my config was:
```
output eDP-1 scale 1.25
output HDMI-A-3 resolution 1920x1080@165Hz
```
and it worked fine, but in 1.10 it sets my external monitor as primary and at pos 0,0 so explicitly set eDP-1 to pos 0,0 and it behaves the same, but i do have to reload the config once after starting sway as for some reason both my monitors have the output of eDP-1 till I do

**Comment by Set2Minecraft** [comment]
try position 1920,0
sway may be erroring out and not showing an error so it defaults

Also is the scale with position off? in my experience sway calculates screen size by dividing not multiplying. so 1920/1.64= 1170.737.... so try position 1170.737,0 and check if its better by how your mouse moves between the screens ( it should be no distance, mouse should move to next screen the instant you move on the edge of screen )

**Comment by akrram09** [comment]
> try position 1920,0 sway may be erroring out and not showing an error so it defaults
> 
> Also is the scale with position off? in my experience sway calculates screen size by dividing not multiplying. so 1920/1.64= 1170.737.... so try position 1170.737,0 and check if its better by how your mouse moves between the screens ( it should be no distance, mouse should move to next screen the instant you move on the edge of screen )

i set it to 1170 and now it working thanks!!
