### ISSUE TITLE
Not all monitors are working

### ISSUE THREAD

**Issue by manio** [swaywm/sway#8481]
- **Sway Version:**

Latest git version

- **wlroots version:**

applied https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4923

- **Debug Log:**

https://skyboo.net/temp/sway/sway-not-starting3.log

- **Description**
It is starting, but only one graphic card is available from two (2 monitors working, 4 are black)

for the reference:
this bug started with my report in #8465, then it has moved to #8442 and after @emersion request I am creating this one

**Comment by manio** [comment]
@emersion 
If you like I can try to bisect this. This is related to sway only, not a wlroots. As when I downgrade only sway then it is working fine. New version is not working - only with your #4923 it is starting but not all monitors.

**Comment by emersion** [comment]
This is a copy-paste of #8465, which is not helpful. When I asked to re-open an issue, I was asking about the stuff in https://github.com/swaywm/sway/issues/8442#issuecomment-2495545574 instead.

**Comment by manio** [comment]
@emersion I've updated the issue body. Is it ok now?

**Comment by ethanalker** [comment]
I'm experiencing a similar (but possibly different) issue on sway 1.10. Making an app fullscreen on a second monitor doesn't work (screen freezes), and it also crashed a few times when playing around. It was fixed by downgrading. I'll give more detail and include logs when I get the chance (which might not be soon).

**Comment by manio** [comment]
@emersion 
As this is a regression (working with arch package 1:1.9-5, but not working with 1:1.10-1) so I was trying to bisect this to help you track the problem down.

Unfortunately I've encounter multiple problems:
I thought that I will just mark good/bad commit based on tags to begin the bisect process but I have to admit that I am a little lost in the development workflow:
I can see all tags and version branches but when I do a git log on specific tag, e.g. `1.10` then looking down there is a huge gap between tagged `1.10-rc1` and `1.6-rc2`. Where is the `1.7`, `1.8`, `1.9`?

I suspect that each release have own branch - so I need to compare branch-to-branch to make the bisect between those two versions? Is this possible?

Another problem is that each version needs specific `wlroots` which complicates the problem. Even when I am trying hard to match the version, then it seems I am doing something wrong, e.g.:
I am at sway tag `v1.9` and it is telling me:
`Dependency wlroots found: NO found 0.18.0-dev but need: '>=0.17.0', '<0.18.0' (overridden)`
It is telling me needs version >=0.17 and < 0.18. When I checkout wlroots 0.17 it can't compile:
https://pastebin.com/D3HXrT13
but when I choose 0.18 then it is also complaining (because it is too high). I tested something in the middle and also can't compile :(

**Comment by emersion** [comment]
Does this help? https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4930

Relevant part of the log:

```
00:00:00.593 [DEBUG] [wlr] [types/wlr_output_swapchain_manager.c:160] Preparing test commit for 6 outputs with explicit modifiers
00:00:00.593 [DEBUG] [wlr] [types/output/render.c:194] Failed to pick output format
```

> I suspect that each release have own branch

Yes

> so I need to compare branch-to-branch to make the bisect between those two versions? Is this possible?

You can probably compare with the base commit each branch is based on.

> Another problem is that each version needs specific wlroots which complicates the problem

Yes, this makes it pretty tricky to bisect. Sway master branch tracks wlroots master, which means each time a breaking wlroots change is made, a matching Sway change is made. This PR contains a script to checkout the right wlroots commit: https://github.com/swaywm/sway/pull/8347

**Comment by manio** [comment]
@emersion 
This was it! All monitors are working now :)
Thank you! Closing.
