### ISSUE TITLE
Frozen screen on secondary Intel GPU after upgrading to 1.10

### ISSUE THREAD

**Issue by Blaxar** [swaywm/sway#8483]
- **Sway Version:**
  - `1.10`

- **Debug Log:**
  - Content of `sway -d 2> ~/sway.log`: [Here](https://gist.github.com/Blaxar/22cf741b65679b15bd53def18c7c4bfa)

- **Configuration File:**
  - [There](https://gist.github.com/Blaxar/f0146c9bdc4d376db0ddf797268e0b6a)

- **Description:**
  - Upgrade from sway version `1.9` to `1.10`.
  - Stop and restart sway, either via the display manager or manually (tried both: result is the same).
  - Screen hooked to the secondary GPU (the integrated one) doesn't refresh at all, unless I specifically open `wdisplays` somehow, but it goes right into being frozen as soon as I close it.
  - Downgrading from `1.10` to `1.9` makes the issue disappear, no need to downgrade anything else.
  
- **System:**
  - Distro: ArchLinux
  - Linux: `6.12.1-arch1-1`
  - CPU: `13th Gen Intel Core i9-13900K`
  - GPUs:
    - Discrete: `Intel Arc A770` (Primary)
    - Integrated: `UHD Graphics 770` (Secondary, for which the faulty behavior happens)
  - Mesa: `24.2.7-arch1.1`

**Comment by emersion** [comment]
Can you try again with the latest Sway commit? See https://github.com/swaywm/sway/wiki/Development-Setup#compiling-as-a-subproject

**Comment by Blaxar** [comment]
@emersion Current `master` is working, thanks!

Then I guess it's just a matter of time before this hits the official repositories here and there, in the meantime I can stick to `1.9`.

**Comment by Blaxar** [comment]
For reference, this was the commit I tested: https://github.com/swaywm/sway/commit/1d783794b508e529bdc665296d690057c93997df
