### ISSUE TITLE
Workspace number background transparency not working.

### ISSUE THREAD

**Issue by drewbussi** [swaywm/sway#8490]
### Please fill out the following:
- **Sway Version:1.10**

- **Debug Log:**
  [sway.log](https://github.com/user-attachments/files/18052668/sway.log)

- **Configuration File:**
  default from /etc/sway/config

- **Stack Trace:**
 - sway doesn't crash.

- **Description:**
  - The little squares which shows the inactive workspace numbers used to have transparency in sway versions 1.9 and prior. After updating to 1.10 they are now black. I also noted a lot of "page-flip failed" warnings from sway, see attached "sway-warngings.png". 
  - Attached image sway-1.9*.png shows how it used to and/or should look.
  - Attached image sway-1.10*.png shows how it looks now.
  - Attached image sway-warnings.png shows some of the page-flip warnings.
![sway-1 9-transparent-bar-20241208_12h04m05s_grim](https://github.com/user-attachments/assets/4a2e47fd-ac9b-471d-9506-f9921afcbab2)
![sway-1 10-black-bar-20241208_10h52m10s_grim](https://github.com/user-attachments/assets/71e5f45a-69fa-4aa5-842e-dcfe9cc5874f)
![sway-warnings](https://github.com/user-attachments/assets/c540be93-4d33-4aad-86dc-7c11087350bc)

**Comment by Nefsen402** [comment]
This can probably be worked around with the environment variable `WLR_SCENE_DISABLE_VISIBILITY=1`. Is this the default swaybar?

**Comment by drewbussi** [comment]
Hey, that worked wonderfully, thanks!
