### ISSUE TITLE
Chromium notifications aren't displayed correctly

### ISSUE THREAD

**Issue by cactorium** [swaywm/sway#863]
Good afternoon! The notifications in Chromium appear to be offset too far to the right to be readable. Is there anything I can do to help fix this, and is there any way I can tell if this is at fault instead of XWayland? Thank you for your awesome compositor and your time

**Comment by FreeFull** [comment]
I've ran into this bug too, but I'm not sure if it's sway's fault, wlc's fault, or XWayland's fault either. It'd be a good idea to test it with Weston and also orbment if possible.

**Comment by PaulDebus** [comment]
I have this exact problem too. You know any more about this?

**Comment by cactorium** [comment]
Same problem in Weston at least. I guess I'll go poke around in Chromium's notification code to see if I can force some debugging output

**Comment by PaulDebus** [comment]
@cactorium have you found out something? I just realized it is still not working correctly...

**Comment by SirCmpwn** [comment]
I'm closing issues that are resolved by the yet-unreleased sway 1.0.
