### ISSUE TITLE
Support setting (dynamic) title bar location

### ISSUE THREAD

**Issue by johnp** [swaywm/sway#883]
"Use case": 16:10 screens are unreasonably high price and nearly impossible to get in a laptop.
(Also, Firefox tabs-in-titlebar doesn't work in sway/i3, which means you can't just flick the mouse pointer to the screen edge to switch tabs)

It would therefore be nice to have a `title_bar` command in the sway config with the basic options:
- top/bottom/left/right/none

Advanced options (not sure if these are worth it, but would make some nice /r/unixporn posts):
- outer_edge_horizontal/outer_edge_vertical

Advanced options need to have a fallback, specifying which option to choose, should no outer edge or two exist in that plane.

Examples:

`title_bar outer_edge_vertical bottom`

E.g. first doing horizontal splits always places the title bar at the bottom, but upon doing a vertical split, the title bar of the upper window will be placed at the top (outer vertical edge).

`title_bar outer_edge_vertical outer_edge_horizontal bottom`

Same as above, but if a window doesn't have vertical outer edges (or two of them) it tries to find a horizontal outer edge first, before falling back to bottom.  
E.g. one horizontal split and then split the right container three times vertically. The top right will have it's title bar on the top, the bottom right on the bottom and the window in between those two will have it's title bar at the right edge (outer horizontal).

**Comment by SirCmpwn** [comment]
I don't understand what you're asking for.

**Comment by johnp** [comment]
Currently, setting `border pixel <n>` disables the title bar, `border normal` has it's title bar at the top.
`title_bar bottom` would now instead place the title bar at the bottom. That's pretty much the main thing I'd be asking for.

**Comment by SirCmpwn** [comment]
Interesting thought. May be worth looking into. Have you pitched this feature request to i3 as well?

**Comment by johnp** [comment]
No, I've just done a quick search and could only find this: https://www.reddit.com/r/i3wm/comments/463mtj/window_titlebars_on_bottom/
Should I place a feature request there too?

**Comment by SirCmpwn** [comment]
Wouldn't be a bad idea.

**Comment by johnp** [comment]
Opened i3/i3/issues/2441. The explanation of the dynamic placement option may be a bit better there.

**Comment by alkino** [comment]
This feature has been refused in i3.

**Comment by SirCmpwn** [comment]
Link to i3 discussion?

**Comment by bearcatsandor** [comment]
I'd like to add, that a 'floating only' option would be ideal too. There are some ideas related to this with add-on C programs, in this reddit discussion: https://www.reddit.com/r/i3wm/comments/4a8bj5/titlebars_only_on_floating_windows/

**Comment by jplatte** [comment]
It's two comments above yours.

**Comment by izhakjakov** [comment]
+1

**Comment by emersion** [comment]
Closing as per i3 decision.

**Comment by izhakjakov** [comment]
:disappointed:

**Comment by herkhinah** [comment]
I still love the idea, even though it's reject by i3. In my setup (my focus is more on the top of the display because that way I can sit more ergonomically) I want the most important information at the top of my screen and the noise like system bar and window titles at the bottom.

**Comment by KrulYuno** [comment]
So, is there no way to set the titlebar sideways? Just like what i3 devs did, they ignored the request. Did sway make the same decision?

**Comment by waflessnet** [comment]
👀 we need this function
