### ISSUE TITLE
handling views depending on their type.

### ISSUE THREAD

**Issue by taiyu-len** [swaywm/sway#91]
right now we are using this https://github.com/SirCmpwn/sway/blob/master/sway/handlers.c#L192
poorly done method to handle it.

there is some effort to mimic certain programs behaviors.
mostly `dmenu` and `firefox` popup windows.

however the information about the views that can be gained from wlc, is not enough to properly figure out how to handle views.

for dmenu here is all the information we can get
`handle:3 type:1 state:0 parent:0 mask:1 (x:0 y:0 w:2704 h:15) title:(null) class:(null) appid:(null)`
and for a program opened with wine.
`handle:3 type:1 state:0 parent:0 mask:1 (x:30 y:8 w:540 h:538) title:(BElJ}:0<nEA!!4D6-%+%9%?%`%W%m%0%i%` class:custom.exe appid:(null)`

they look the same (other then the title and class), but behave completely differently.

here is dmenu shown with `xwininfo -all` http://ix.io/klF
here is the program opened with wine http://ix.io/klG

so the issue is.
get more info about views, and have better handling depending on said info.

**Comment by SirCmpwn** [comment]
Sounds a lot like a wlc thing. Paging @Cloudef, and you should probably report upstream.

**Comment by Cloudef** [comment]
The xwininfo outputs don't really have much useful information for wlc. I invite you to https://github.com/Cloudef/wlc/blob/master/src/xwayland/xwm.c#L470-L485 check out the xwm.c and decide what information you need for X11 windows.

**Comment by robotanarchy** [comment]
Just an update on this issue: for me, it makes Firefox barely usable, because most of the time tooltips behave like regular windows - see the attached screenshot. (this happens, when hovering the 'x' on a tab - but not all the time).
![2015-12-25-004110_swaygrab](https://cloud.githubusercontent.com/assets/7833187/12013024/25ab00ec-ad0d-11e5-9525-c895dec18965.png)
