### ISSUE TITLE
Sway lags 

### ISSUE THREAD

**Issue by speculees** [swaywm/sway#916]
Hello,
been using i3 for a while, so I thought I give sway a try. however Its so laggy it is unusable. for example all 4 cores work at 80% when i watch youtube on chromium.  CPU% process is 154%  /usr/lib/chromium/chromium --type=renderer --primordial-pipe token=190*******4 --lang=en-US...
lspci | grep ATI gives:
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Cypress LE [Radeon HD 5830] MESA
and CPU is intel quad q6600
 lshw -c video is:
*-display  
       description: VGA compatible controller
       product: Cypress LE [Radeon HD 5830]
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 0
       bus info: pci@0000:01:00.0
       version: 00
       width: 64 bits
       clock: 33MHz
       capabilities: pm pciexpress msi vga_controller bus_master cap_list rom
       configuration: driver=radeon latency=0
       resources: irq:26 memory:d0000000-dfffffff memory:efcc0000-efcdffff ioport:dc00(size=256) memory:c0000-dffff
Any ideas why?

**Comment by SirCmpwn** [comment]
I'm closing issues that are resolved by the yet-unreleased sway 1.0.
