### ISSUE TITLE
Title_bar should be part of container

### ISSUE THREAD

**Issue by alkino** [swaywm/sway#944]
Hi o/

Today if you click on the title_bar of a floating windows it clicks on container behind it. It will be better if it click on it.

Regards

**Comment by alkino** [comment]
Partially fixed by #948 
If the mouse goes on the title bar the window lost focus.

**Comment by alkino** [comment]
Reopen it please.

**Comment by SirCmpwn** [comment]
Sup?

**Comment by SirCmpwn** [comment]
I'm closing issues that are resolved by the yet-unreleased sway 1.0.
