### ISSUE TITLE
Can't handle criteria string: Refusing to execute command

### ISSUE THREAD

**Issue by PaulDebus** [swaywm/sway#962]
I trigger the following command with a `bindsym` and get the result in the log:

```
Command '[title="Franz"] floating enable, resize set 1600 1200, move container to workspace current, move absolute position center' failed: Can't handle criteria string: Refusing to execute command
```

I use the same criteria in an `assign` statement and it works. Also `swaymsg -t get_tree` shows, that the window has the right title. 

Thank you for your time, i am not sure if I am maybe doing something wrong. In i3 it worked

**Comment by thejan2009** [comment]
This functionality is yet to be implemented.
