### ISSUE TITLE
No "real" transparency when stacking/tabbing transparent windows

### ISSUE THREAD

**Issue by camoz** [swaywm/sway#973]
When having two (or more) transparent windows in stacked or tabbed mode (in my test case sakura and termite), no matter which window you currently select, you always sie the background shining through the selected window.

I tested this with and without Xwayland, and both times used the default sway configuration.

This was different in i3 -- there one would see the last selected window (possibly on another workspace, if your last action was switching workspaces). Here is a screenshot of the i3 behaviour:
https://lut.im/2Tiumkpol3/od0qu5ulmVNLT3aY.png

I found the i3 behaviour very useful for single monitor setups, especially on laptops, where your screen size is often limited. For example, you could code in a transparent vim, and on the 'background' / behind the window you could see datasheets/code examples/videos/whatever you like.

Not sure if it's an issue or rather a feature request, but since sway imitates i3 in many ways (and for me it really limits me in productivity, as I mostly work on my 14" laptop), I decided to make it an issue :)

**Comment by chuckhacker** [comment]
This. I am using a 12.5" laptop so this is also really important to me, thanks.

**Comment by SirCmpwn** [comment]
I'm closing issues that are resolved by the yet-unreleased sway 1.0.

**Comment by JonnyMako** [comment]
Is this in beta 1?

**Comment by emersion** [comment]
I don't think so.

I'm not a fan of this. It would mean wasting resources in case windows are opaque. It would make the rendering code more complicated, it's already pretty complicated.

**Comment by JonnyMako** [comment]
> I don't think so.
> 
> I'm not a fan of this. It would mean wasting resources in case windows are opaque. It would make the rendering code more complicated, it's already pretty complicated.

ok, thanks. I've always weighed the pros and cons of "real" transparency

pros:
1. seems more intuitive (definitely so for floating windows and this already works)
2. can see the window behind the terminal without having to switch to it.

cons:
1. resource hog
2. less privacy (can't hide windows behind terminals)
3. can't enjoy the wallpaper as much :smile: 

I think I'm coming around to the side of not minding having real transparency.

**Comment by progandy** [comment]
> I found the i3 behaviour very useful for single monitor setups, especially on laptops, where your screen size is often limited. For example, you could code in a transparent vim, and on the 'background' / behind the window you could see datasheets/code examples/videos/whatever you like.

Create a script that makes a screenshot and sets it as your background, then bind it to a shortcut.

**Comment by camoz** [comment]
@RyanDwyer: Thank you very much for your detailed explanation!

With that background now it seems reasonable not to implement it in fullscreen mode (since it's a protocol violation) or general "real transparency" like in i3 with a compositor like compton (due to the massive overhead).

Out of curiousity: That would mean that sway is a lot more power/ressource efficient than traditional X11 WMs like i3 or openbox with "real transparency", right?

> > What about a compromise: When a window gets fullscreened, it has "real transparency" meaning one can see the windows behind it? This would maybe limit the performance penality and also the complexity of the rendering code?
> 
> Even if we found a resolution to the above, this would still be a protocol violation.

Another idea I could think of is designing/adding a "second, transparent fullscreen mode", without the solid, black background. But it sounds like that would also require changes to the protocol specifications, which is of course a big thing and not done unless it's clear that the developers want it or unless there's a strong demand from the community. (I'm assuming that it's not an issue of the wayland-protocol, but of the wlr-protocols.) 

Sorry, I may be technically incorrect here and there and things may sound a bit stupid, I'm unfortunately still very unfamiliar with sway and all that graphics stuff is kind of a miracle to me.

The reason I'm still discussing this is that a) I've become very used to that feature and don't wanna miss it :D; but also b) that I think it's a useful feature in general, and that other people would want that. But that's maybe only in my head.

I generally like to think about how one can optimize workflows, especially while working with computers. Although I don't like many "desktop graphics effects" (there's all kinds of unecessary shit out there), I e.g. think that having a "sliding" effect when switching workspaces would increase productivity for quite some people (including me). Similar to smooth scrolling it helps the mind focusing the new workspace during a switch (since humans have been practicing that for thousands of years), and it would probably help the mind keeping track of the order/locations of the workspaces and therefore improve orientation between the workspace (I have a single monitor setup with usually 6-8 workspaces).

**Comment by camoz** [comment]
FWIW I'm now happy with a border-less floating window for such situaltions (where I want to see something behind the terminal).

In case anyone's interested, I added this to my config:
`bindsym $mod+backslash exec termite --name="scratchterm"`
`for_window [app_id="scratchterm"] floating enable; border none; resize set 100 ppt 50 ppt; move absolute 1280 23; move scratchpad; scratchpad show`
As I'm not using the scratchpad for other things, this works great.

I actuallay also have a "fullscreen" one bound to $mod+Shift+backslash, but that's currently buggy, see  https://github.com/swaywm/sway/issues/3236

Thanks everyone for the comments and insights.

**Comment by alexherbo2** [comment]
It does not work for me, using Sway version 1.4.

I observe the same behavior than the issue: false transparency and totally opaque in fullscreen.

**Comment by al-caveman** [comment]
@ddevault closed this because it was supposedly fixed in beta in 2018.  But it's 2021 and seems not fixed in version 1.6.1.

What's the status on this bug?

**Comment by emersion** [comment]
The [comment above](https://github.com/swaywm/sway/issues/973#issuecomment-438163389) explains why this isn't a desirable feature.
