### ISSUE TITLE
sway crush when xorg is not there

### ISSUE THREAD

**Issue by Fale** [swaywm/sway#975]
I have XWayland installed and often (sadly) I use Xorg native app. Sometimes, closing one of those app (I've noticed it with mpv, firefox, and chromium), the whole sway get restarted. This is what it saved on the log (sorry, the -d option was missing, but since it does not happens all the times, is hard to create that kind of output, but I'll try).

http://paste.fedoraproject.org/490547/80247687/

**Comment by Fale** [comment]
I've been able to reproduce this in a consitant way in the following way:

- Start mpv
- Go in full screen (f)
- Close mpv (Windows + Shift + Q)
- sway crushes

**Comment by Fale** [comment]
Having found the sequence to reproduce the bug, I have been able to get a better log: http://paste.fedoraproject.org/499040/80891120/

**Comment by Fale** [comment]
I tried having the following  `~/.config/mpv/config`:

```
vo=opengl
```

But I obtained the same result (https://paste.fedoraproject.org/513291/77859714)

**Comment by RichardVoid** [comment]
Have same issue. But it crash only, when i close mpv second time with `$mod + Shift + Q`. Close mpv with its own hotkeys `q` and `Q `works fine. Seems like this issue related to `kill`.

**Comment by SirCmpwn** [comment]
I'm closing issues that are resolved by the yet-unreleased sway 1.0.
