### ISSUE TITLE
Security feature status

### ISSUE THREAD

**Issue by ddevault** [swaywm/sway#984]
* [x] Default security config for /etc/sway/config.d/
* [x] Run config files through sed to replace PREFIX and SYSCONFDIR
* [x] Config structure changes & support code
* [x] Implement the permit and reject commands
* [x] Feature policies
  * [x] background
  * [x] panel
  * [x] lock
  * [x] lock
  * [x] fullscreen
  * [x] keyboard
  * [x] mouse
  * [x] ipc
  * [ ] screenshot
* [x] Command policies
* [x] IPC security
  * [x] Enable/disable features
  * [x] Enable/disable events
* [x] Startup sanity check
  * [x] Check permissions on /etc/sway
  * [x] Check procfs is available
  * [x] Check for CAP_SYS_PTRACE
  * [x] Check for security sensitive command policies
  * [ ] Inform user visually of sanity check failures
* [x] Write sway-security(7)
* [x] Drop -Denable-binding-event from cmake
* [ ] Optimize permission checks
* [ ] New Wayland protocol extensions
  * [ ] Screenshot
* [ ] Handle permission errors in swaybar, swaygrab, swaymsg, etc more gracefully
* [ ] Paranoid mode for swaygrab
* [ ] Standard mechanisms for sandboxing (collab with wayland-devel)
* [x] Configure IPC features per-executable
* [ ] `exec --policy=... [...]`

**Comment by emersion** [comment]
This issue was about Sway 0.15. Closing in favor of https://github.com/swaywm/sway/issues/2333.
