### ISSUE TITLE
criteria.c needs to be refactored wrt error handling

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/sway#994]
```c
// Returns error string on failure or NULL otherwise.
```

This sort of thing doesn't work, because the error strings are allocated and if the allocation fails we have no way of indicating an error occured.

**Comment by Kinokoio** [comment]
It is possible to create a new function which encapsulates the universal code used to generate the error messages. Insde the function we can also check if strings were allocated and try to send a different kind of error message if allocation failed.

**Comment by SirCmpwn** [comment]
Sounds overengineered.

**Comment by Kinokoio** [comment]
Well, not encapsulate but create a function for it. There are 5 different implementations of the code.

**Comment by automat0n** [comment]
Seems a good idea.

**Comment by automat0n** [comment]
@Kinokoio your idea may be a bit too complex. After tackling it a bit I created this function which can help creating the error messages just as other types of messages:

`int allocprint(char **message, int lenght, int argc, char *fmt, ...)  {
    va_list ap;
    char *error;
    int i, len;

    va_start(ap, fmt);
    error = malloc(lenght);
    // Terminate process if allocation fails
    if( error == NULL)
        raise(SIGKILL);
    // Create error string
    vsprintf(error, fmt, ap);
    *message = error;
    va_end(ap);
    return 0;
}`

It can be done in fewer lines of code if we use vasprintf(). And, I still need a bit of help with the way we indicate an error occured during memory allocation.

**Comment by SirCmpwn** [comment]
I don't want to wrap malloc/realloc/calloc. It's better for the code doing the allocations to handle failure intelligently. I *certainly* don't want to terminate if allocation fails.

All we have to do is redesign criteria.c a bit. criteria.c is a poorly designed regardless and I should have picked up on that during the initial review.

**Comment by SirCmpwn** [comment]
As a rule of thumb sway should never terminate in response to an error if it can avoid it. Terminating sway means all subprocesses are terminated and the user loses their work.

**Comment by SirCmpwn** [comment]
I'm closing issues that are resolved by the yet-unreleased sway 1.0.
